### PR TITLE
Replace apache http remnant / Beolingus parse fix

### LINKED ISSUE #5376: Pronunciation sometimes shows "The word was not found"
###### Reproduction Steps

1. add a new note -> the Add note screen displayed
2. selected type: Basic, Deck: any, Front: type in "text", click the Clip sign on the right -> Advanced editor
3. click on PRONUNCIATION button, selected language: English, click on Load button
Wait dialog is shown with "Searching the word" on it

###### Expected Result
Editing field screen is shown with Play, Stop, and Rec buttons.
Play plays the downloaded pronunciation file

###### Actual Result
"The word was not found" toast is displayed at the bottom

### PR DESCRIPTION
**Pull request by mikehardy**
## Purpose / Description

I noticed a crash in 2.9 related to Apache HTTP client and it led me to discover there was one more Apache HTTP remnant in the HttpFetcher used to download pronunciation and translations.

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/33a4184e-c3d7-4b60-af73-ca68b02fdfbb

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:354)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IncompatibleClassChangeError: Class 'org.apache.http.conn.ssl.SSLSocketFactory' does not implement interface 'org.apache.http.conn.scheme.SchemeSocketFactory' in call to 'java.net.Socket org.apache.http.conn.scheme.SchemeSocketFactory.createSocket(org.apache.http.params.HttpParams)' (declaration of 'org.apache.http.impl.conn.DefaultClientConnectionOperator' appears in base.apk)
at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:13)
at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:11)
at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:5)
at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:31)
at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:29)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:7)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:4)
at com.ichi2.anki.web.HttpFetcher.fetchThroughHttp(HttpFetcher.java:8)
at com.ichi2.anki.multimediacard.activity.LoadPronounciationActivity$BackgroundPost.doInBackground(LoadPronounciationActivity.java:2)
at com.ichi2.anki.multimediacard.activity.LoadPronounciationActivity$BackgroundPost.doInBackground(LoadPronounciationActivity.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
```

I additionally discovered, while testing, that Beolingus had changed their response text to include extra information after the word, so our pronunciation downloader was no longer matching it correctly, so no pronunciations were ever found for words that definitely had matches

## Fixes
Fixes #5376 by altering beolingus match to "contains" vs "equals"

## Approach
Converts HttpFetcher to OkHTTP
Converts online requests to HTTPS
Fixes the matcher so beolingus works

## How Has This Been Tested?
API28 emulator, it easily reproduced all the problems, and worked after making these changes

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/web/HttpFetcher.java [hunk 1]
```diff
@@ -125,28 +110,51 @@ public static String downloadFileToSdCard(String UrlToFile, Context context, Str
...
-            urlConnection.setRequestMethod(method);
-            urlConnection.setRequestProperty("Referer", "com.ichi2.anki");
-            urlConnection.setRequestProperty("User-Agent", "Mozilla/5.0 ( compatible ) ");
-            urlConnection.setRequestProperty("Accept", "*/*");
-			urlConnection.setConnectTimeout(10000);
-			urlConnection.setReadTimeout(60000);
-            urlConnection.connect();
+            Request.Builder requestBuilder = new Request.Builder();
+            requestBuilder.url(url);
+            if (method.equals("GET")) {
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/web/HttpFetcher.java]: Codacy Issue found: [Position literals first in String comparisons](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5010008)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- AnkiDroid/src/main/java/com/ichi2/anki/web/HttpFetcher.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5010008&bid=16525335)

**Comment by mikehardy** [comment]
The lesson learned here is be oh-so-careful with silencing deprecation, I had left a comment that this was being tracked as part of http deprecation in github but github didn't have a list of the files or anything, so it was missed.

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/main/java/com/ichi2/anki/web/HttpFetcher.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5010008&bid=16525335)
