### PR TITLE
Fix LaTeX rendering+Notetype changing

### LINKED ISSUE #12379: [Bug] Change a card type leads to an error
###### Reproduction Steps
1. Add a basic and reversed note
2. Go to Card Browser, Edit the note, change Card Type to Basic
3. Save
4. OK

###### Expected Result
Card type is changed.

###### Actual Result
Card type is changed but an error appears. The error appears everytime I try to open Card Browser. Card Browser seems empty. Check database resolves the issue but there is no advice to run Check database.  

###### Possible solution
1. Check database could be run automatically after a note type is changed.
2. There could be an advice to run Check database in the error message.

###### Debug info
AnkiDroid Version = 2.16alpha83

Android Version = 12

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-A225F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/104.0.5112.97 Mobile Safari/537.36

ACRA UUID = d4a82cc8-397d-4a8f-81c8-87106ce0ba00

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by dae**
`+` Other small fixes

Closes https://github.com/ankidroid/Anki-Android/issues/12249
Closes #12379

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt [hunk 1]
```diff
@@ -1152,7 +1152,8 @@ open class Collection(
             html = ChessFilter.fenToChessboard(html, context)
             if (!browser) {
                 // browser don't show image. So compiling LaTeX actually remove information.
-                html = LaTeX.mungeQA(html, this, model)
+                val svg = this.col.get_config("latexsvg", false) ?: false
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt:1155]: If I understand correctly what is going on, someone who had `svg` in some model and uses LaTeX will get warning that the `png` file can't be found. This seems to be especially dangerous if a shared deck comes with some svg, because, not only the user would need to go on computer to recompile everything, but maybe they don't even have LaTeX nor know how to install it.

This is even worse because there is no way currently to edit this parameter from AnkiDroid. (But anyway, even if they edited it, the same problem would exists for note type with png)

So it seems to me that this change would be acceptable only if you check that the collection has a version of the schema in which the update was done already on computer, and where, I assume, Anki ensured that the user is warned that some images may be missing and must be recomputed.


An alternative solution, which would have make sense years ago actually, would be to consider svg/png as a preference to check first. That is, if the preference is svg, but the svg is missing, then search for png, and only if png is also missing, write the latex in the card question/answer.
I assume that for most cards, a second check for file would not be that bad. And if a user gets their card actually slowed down because of doubling the number of checks, there is probably bigger issuer with their cards in the first place

**Review by Arthur-Milchior — COMMENTED** [review]
Fine with commits 1 and 3.

File: AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt (hunk 1 above)
Comment (dae) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt]: Good catch, this was a silly mistake on my part - I'd originally intended to reference the notetype setting, but got distracted. Should be fixed now.

**Review by mikehardy — APPROVED** [review]
These look good - thanks @dae - I re-pinged @Arthur-Milchior for review since it appears you addressed their concerns, and hopefully we can get this in and do a new release to close out these issues + keep moving forward

**Review by david-allison — APPROVED** [review]
Optional follow-ups, non-blocking. 

* I don't think we're documenting that "not svg" means PNG
* I'd like to see either using a named argument for `svg` on the callers in tests

I won't merge this as it's waiting for @Arthur-Milchior , but I'd be happy to

**Comment by mikehardy** [comment]
Going to merge so we can keep backend progress

**Comment by lervag** [comment]
Thanks guys, you rock!
