### PR TITLE
Fix UI being in bad state when storage migration fails

### LINKED ISSUE #13668: UI is left in inconsistent state when storage migration fails
When migration fails, we are stuck in a kind of a limbo: the migration is considered done (failed, but done) by the service, but `userMigrationIsInProgress` is still going to return true, so the UI is not updated to reflect the state of the migration. And, in fact, what exactly should the UI say? We can't keep showing the “ongoing-migration button” since no migration is ongoing, but then showing “start migration” button and going through all the dialogs offering to sync & to backup & to migrate also doesn't make sense, as we can't really do all that when the collection might be split in two.

I suppose we want to have a state “migration paused due to a failure”, have the UI reflect it, and to allow user to resume migration.

### PR DESCRIPTION
**Pull request by oakkitten**
## Fixes
Fixes #13668

## Approach
This introduces the state of “migration is paused due to an error”, which is saved in shared preferences. In this state, the toolbar shows the same start-migration-button that now offers to resume migration, and the sync icon is hidden. It might be more proper to create a new button for resuming migration, possibly reusing the ongoing-migration-button. Or possibly even some sort of a sticky banner that informs the user that migration is paused. Or possibly even lock up the UI completely. (I opted to not go for this last option particularly because we don't know what problems we are going to encounter, and giving the user some freedom may allow us, with their help, to diagnose the issue.)

Ideally needs further and more extensive refactoring, but it just takes so much time.

## How Has This Been Tested?
Tested on my device.

## Checklist
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by BrayanDSO** [comment]
I'll wait until this is undrafted and split into more commits before reviewing.

**Comment by oakkitten** [comment]
Updated with very minor changes; edited the first comment with a little more details.

**Review by david-allison — CHANGES_REQUESTED** [review]
Partial review. On me to continue.

This very likely need to be split out into separate commits. There's a lot going on here.

File: AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt [hunk 1]
```diff
@@ -129,12 +134,14 @@ class MigrationService : ServiceWithALifecycleScope(), ServiceWithASimpleBinder<
...
+                migrateUserDataTask = MigrateUserData.createInstance(preferences)
 
-                val remainingTransferSize = getRemainingTransferSize(migrateUserDataTask)
-                val totalBytesToTransfer = getOrSetTotalTransferSize(valueToPersistIfNotCalculated = remainingTransferSize)
-                var transferredBytes = max(totalBytesToTransfer - remainingTransferSize, 0)
+                val remainingBytesToTransfer = getRemainingBytesToTransfer(migrateUserDataTask)
+                val totalBytesToTransfer = preferences.getOrSetLong(
+                    key = PREF_TOTAL_BYTES_TO_TRANSFER,
+                    defaultValue = remainingBytesToTransfer
+                )
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt:143]: nit: this feels more complex

File: AnkiDroid/src/main/java/com/ichi2/preferences/PreferenceExtensions.kt [hunk 2]
```diff
@@ -39,12 +39,12 @@ fun SharedPreferences.getOrSetString(key: String, supplier: Supplier<String>): S
 }
 
 @CheckResult // A "set" API should be used if the result is not required.
-fun SharedPreferences.getOrSetLong(key: String, supplier: Supplier<Long>): Long {
-    if (contains(key)) {
+fun SharedPreferences.getOrSetLong(key: String, defaultValue: Long): Long {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/preferences/PreferenceExtensions.kt:42]: This makes the signature inconsistent with the above

**Review by david-allison — CHANGES_REQUESTED** [review]

**Comment by mikehardy** [comment]
Marking as needs review as comments indicate review is ongoing, but also marking as needs author reply because some things are already actionable

**Comment by oakkitten** [comment]
To address the last review I'll just remove (hopefully tomorrow) the code related to refactoring `MigrationService`, that was a result of a mess in my git and I was too lazy to get rid of it (sorry). (But why shouldn't we be using spaces in preference keys?)

**Comment by oakkitten** [comment]
Updated to remove changes unrelated to the PR. And to remove spaces in preference keys, although I still don't know what's the problem with that.

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 3]
```diff
@@ -2600,6 +2610,32 @@ open class DeckPicker :
...
+            setTitle(R.string.scoped_storage_title)
+            setMessage(getString(R.string.storage_migration_is_paused_after_failing_with_the_error_x_try_again, errorText))
+            setNegativeButton(R.string.dialog_cancel) { _, _ -> }
+            setPositiveButton(R.string.resume_migration) { _, _ ->
+                getSharedPrefs(this@DeckPicker).edit { remove(PREF_MIGRATION_ERROR_TEXT) }
+                startMigrateUserDataService()
+                invalidateOptionsMenu()
+            }
+        }
+    }
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:2624]: This functionality significantly differs from: https://github.com/ankidroid/Anki-Android/blob/d1f8672e2f43b38ac6dac8618378efa83fea0815/AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt#L265-L277

Especially as it does not provide the user an avenue to get help

**Review by david-allison — CHANGES_REQUESTED** [review]
This view of the error significantly differs from the notification. We should provide users help here, in case "try again" fails.

**Review by BrayanDSO — COMMENTED** [review]
Overall looks good, but I ressonate with David about the help option

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt (hunk 3 above)
Comment (oakkitten) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:2624]: I didn't include that functionality here as it's included in the Migration failed dialog, which is shown along with the notification

https://github.com/ankidroid/Anki-Android/blob/4120c6aa46720a6096bab8234c986b048391fec6/AnkiDroid/src/main/java/com/ichi2/anki/ui/dialogs/ActivityAgnosticDialogs.kt#L70-L85

You think we need help here as well? And the traceback?

Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:2624]: At least a Help button yeah, so they can know what to do with the shown error in case it persists and/or they dismissed the failed dialog/notification

File: AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt [hunk 4]
```diff
@@ -310,11 +323,57 @@ fun <O> O.migrationServiceWhileStartedOrNull(): ReadOnlyProperty<Any?, Migration
...
- * See also the logic in [com.ichi2.anki.DeckPicker.shouldOfferToUpgrade]
+ * This is not determined by permissions or static variables.
  */
-private val Context.userMigrationHasSucceeded get() =
-    !userMigrationIsInProgress(this) && !isLegacyStorage(this)
+sealed interface MediaMigrationState {
+    sealed interface NotOngoing : MediaMigrationState {
+        sealed interface NotNeeded : NotOngoing {
+            object CollectionIsInAppPrivateFolder : NotNeeded
+            object CollectionIsInPublicFolderButWillRemainAccessible : NotNeeded
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt:340]: I believe this one would benefit from a comment.
I assume "remain accessible" means that we are not using play store, so it remains accessible even after uninstall/reinstall (assuming the same flavor).
Because as long as you just update, it should always remain accessible.

File: AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt [hunk 5]
```diff
@@ -310,11 +323,57 @@ fun <O> O.migrationServiceWhileStartedOrNull(): ReadOnlyProperty<Any?, Migration
...
+        class PausedDueToError(val errorText: String) : Ongoing
+    }
+}
+
+// TODO Consider refactoring ScopedStorageService to remove its methods used here,
+//   inlining them, and use this method throughout the app for media migration state.
+fun Context.getMediaMigrationState(): MediaMigrationState {
+    val preferences = AnkiDroidApp.getSharedPrefs(this)
+
+    fun migrationIsOngoing() = ScopedStorageService.userMigrationIsInProgress(preferences)
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt:356]: I'm sorry, but I'm confused. What's the point of redefining those functions.
I could understand `val migrationIsOngoing = ScopedStorageService.userMigrationIsInProgress(preferences)`, to make the `if` more readable. But I admit I don't get the point of creating a new function with a single usage.

I may understand that you want to remove all use of `userMigrationIsInProgress` and only use `getMediaMigrationState`. But, for example, `isLegacyStorage` seems natural to use, and I don't see a point of removing it. You may want to care about this even outside of migration strictly speaking

**Review by Arthur-Milchior — COMMENTED** [review]
thanks a lot for this change. Looks good to me. Main request is really: if you were able to record the usage of this new version, new dialog, that would help a lot understand in which context it occurs.

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 6]
```diff
@@ -443,29 +444,36 @@ open class DeckPicker :
...
-                //     invalidateOptionsMenu()
-                //     handleStartup(skipStorageMigration = true)
-                // })
-                return false // TODO: Allow startup normally
-            }
-            ScopedStorageService.Status.IN_PROGRESS -> {
+        val mediaMigrationState = getMediaMigrationState()
+        Timber.i("migration status: %s", mediaMigrationState)
+        when (mediaMigrationState) {
+            is MediaMigrationState.NotOngoing.Needed -> {
```
[the remark this answers is not in the document]
Comment (oakkitten) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:455]: You do need `is` for classes, but you are right that it can be ditched as `Needed` is also an object. However I prefer using `is` instead of `==` with sealed classes/interfaces at all times—for consistency, and for a little easier refactoring, e.g. if you were to change `MediaMigrationState.NotOngoing.Needed` to `MediaMigrationState.NotOngoing` you'd need to add back the `is` if you weren't using it in the first place.

File: AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt [hunk 7]
```diff
@@ -217,6 +219,10 @@ object ScopedStorageService {
     /**
      * Checks if current directory being used by AnkiDroid to store user data is a Legacy Storage Directory.
      * This directory is stored under [CollectionHelper.PREF_COLLECTION_PATH] in SharedPreferences
+     *
+     * DEPRECATED. Use either [com.ichi2.anki.services.getMediaMigrationState], or
```
[the remark this answers is not in the document]
Comment (oakkitten) [reply AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt:223]: It is okay to continue using deprecated things.

I think it's too late for a full refactor, but in case someone makes a smaller refactor they can take hints from this deprecation.

File: AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt (hunk 4 above)
Comment (oakkitten) [reply AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt:340]: Not sure if this needs a comment. This is a rather high-level enum and the consumer of it should not care for what reasons the collection is going to remain accessible. This should read “Migration is not needed, as the collection will remain accessible even though it is in a public folder.” I didn't suffix this with `AfterReinstall` because

* the name is too long already
* the detail about updating without reinstalling retaining access is too low level for this enum
* there are perhaps ways of losing access such as user upgrading their OS so you just can't have a perfectly precise name

If the reader is interested in the implementation detail, the implementation does have a comment

File: AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt (hunk 5 above)
Comment (oakkitten) [reply AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt:356]: * To make the `if` more readable. Using `val` would compute everything even though it might be not needed, `val get()` is illegal in local functions, so `fun`
* `isLegacyStorage` is a bad name (we decided to use the terms “app-private folder“ & “public folder”) and should probably be replaced with `isInsideDirectoriesRemovedWithTheApp` (or the latter should be renamed into `isInsideAppPrivateFolders`).
* `collectionWillBeMadeInaccessibleAfterUninstall` is only used once here and can be inlined. Didn't do it right away as I wanted a smaller diff

**Review by BrayanDSO — APPROVED** [review]

**Comment by BrayanDSO** [comment]
I'm interpreting David's comment as an approval. Didn't see nothing breaking or major on Arthur's comments. Pending merge

**Review by david-allison — APPROVED** [review]
Review was dismissed: my comment was handled, but I wasn't at a computer to re-review.

I've now had time to look through. Looks good to me. Needs a follow up to move the TODOs to the board.

**Comment by mikehardy** [comment]
This was a one-commit change, and had a conflict - in those cases for speed, doing the github web UI "resolve conflicts" (which adds a merge commit to the branch) is functionally equivalent in my opinion to pulling branch / rebase-with-interactive-de-conflict / re-push, because a squash merge after the merge commit is still just one commit

So I just did the resolve conflicts / merge commit thing here and if CI goes green I will merge this once string sync is done (string sync in process....)

**Comment by mikehardy** [comment]
Took another conflict when #13762 went in, apparently user friendly error text util moved in that PR and this PR used it.
Did another de-conflict merge commit, these are trivial fixups, if CI goes green it's good
