### PR TITLE
Fix cloze number when existing clozes are present

### LINKED ISSUE #20350: Adding additional clozes doesn't work properly for Instant Cards in AnkiDroid
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

On Android, share some text with AnkiDroid selecting the option "Instant Card". A small panels appear when one can select which words should be in a cloze. Selecting a word should create an additional cloze, but instead create a cloze with the same number. For example, if you share (e.g. with copy text -> open clipboard -> share to AnkiDroid selecting "Instant Card") the following text
```txt
This is the {{c1::first cloze}}. This should be the second cloze.
```
you get this  window

Image

Notice that on the top right of the window, there is the `[...]+` symbol (second from right) which should mean that by tapping on a word, you can add a **second cloze**. Instead, if you select another word, you still get a first cloze (which should be the behavior of the `[...]` mode, not the `[...]+` mode):

Image

### Expected behaviour

In the above example, if when the Instant Card window open you tap on the `[...]+` two times (which switches to `[...]` and then back to `[...]+`), then it correctly allows you to add further clozes: 

Image

This should be the correct behavior, without the need to tap on `[...]+` two times. 

### Debug info

```text
AnkiDroid Version = 2.23.3 (9001068fd4819c6fb66cb8239e7166868ab47859)  
Backend Version = 0.1.62-anki25.09.2 (25.09.2 3890e12c9e48c028c3f12aa58cb64bd9f8895e30)  
Android Version = 13 (SDK 33)  
ProductFlavor = play  
Device Info = samsung | samsung | gts7xl | gts7xlxeea | SM-T976B | qcom  
Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-T976B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/144.0.7559.59 Safari/537.36  
ACRA UUID = f27fbdd7-0677-4de1-aae5-34cfe93d5620  
FSRS = 5.1.0 (Enabled: true)  
Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by Alok-Silswal**
## Purpose / Description
_Instant Note was not displaying cloze number properly with cloze text._

## Fixes
* Fixes #20350 

## Approach

- Cloze counter and `intClozeList` is derived from actual text.

## How Has This Been Tested?
- Verified that existing unit tests pass (`InstantEditorViewModelTest.kt`).

- Added 3 unit test cases based on observations as mentioned in https://github.com/ankidroid/Anki-Android/issues/20350#issuecomment-3941428645

- Tested on my phone (Android 14, Xiaomi / HyperOS) using a debug build.

Used the following two texts for testing:

```
This is the {{c1::first cloze}}. This should be the second cloze.
```
```
This is the {{c1::first cloze}}. This should be the {{c2::second cloze}}. Similarly, this one as {{c3::third cloze}}.
```

Two screen recording attached as evidence.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

https://github.com/user-attachments/assets/3355ef98-565e-4a0a-8001-38089b000ab6

https://github.com/user-attachments/assets/7cee9321-8b5c-42e5-bd35-952cb9da1502

### CODE REVIEW

**Review by david-allison — COMMENTED** [review]
Could you add a unit test?

**Comment by Alok-Silswal** [comment]
> Could you add a unit test?

In `InstantEditorViewModelTest.kt`?

**Comment by david-allison** [comment]
Yep

**Comment by Alok-Silswal** [comment]
Done! 
@david-allison Does it suffice?

File: AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt [hunk 1]
```diff
@@ -180,6 +180,28 @@ class InstantEditorViewModel :
...
+        clozePattern.findAll(text).forEach {
+            val value = it.groups[2]?.value?.toIntOrNull()
+            if (value != null) {
+                intClozeList.add(value)
+                if (value > max) max = value
+            }
+        }
+
+        _currentClozeNumber.value = max + 1
+    }
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt]: How about: 

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt b/AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt	(revision d7931f4029d1ccb158ca2f31043b006b0cb53b78)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt	(date 1772761343666)
@@ -17,6 +17,7 @@
 
 package com.ichi2.anki.instantnoteeditor
 
+import androidx.annotation.CheckResult
 import androidx.annotation.VisibleForTesting
 import androidx.lifecycle.LiveData
 import androidx.lifecycle.MutableLiveData
@@ -26,6 +27,7 @@
 import com.ichi2.anki.NoteFieldsCheckResult
 import com.ichi2.anki.OnErrorListener
 import com.ichi2.anki.checkNoteFieldsResponse
+import com.ichi2.anki.common.utils.ext.replaceWith
 import com.ichi2.anki.instantnoteeditor.InstantNoteEditorActivity.DialogType
 import com.ichi2.anki.libanki.DeckId
 import com.ichi2.anki.libanki.Note
@@ -180,27 +182,17 @@
             }
     }
 
-    /** Make cloze counter and intClozeList consistent with actual text.  */
-    private fun syncClozeState(text: String?) {
-        if (text.isNullOrEmpty()) {
-            intClozeList.clear()
-            _currentClozeNumber.value = 1
-            return
-        }
-
-        intClozeList.clear()
+    /**
+     * Extracts the cloze ordinals from text (if any).
+     *
+     * `"{{c2::text}} {{c1::more}}"` => `[2, 1]`
+     */
+    @CheckResult
+    private fun getClozeOrdinals(text: String): List<Int> =
+        clozePattern.findAll(text)
+            .mapNotNull { it.groups[2]?.value?.toIntOrNull() }
+            .toList()
 
-        var max = 0
-        clozePattern.findAll(text).forEach {
-            val value = it.groups[2]?.value?.toIntOrNull()
-            if (value != null) {
-                intClozeList.add(value)
-                if (value > max) max = value
-            }
-        }
-
-        _currentClozeNumber.value = max + 1
-    }
 
     /**
      * Retrieves all cloze text fields from the current editor note's note type.
@@ -228,7 +220,8 @@
 
     fun setClozeFieldText(text: String?) {
         _actualClozeFieldText.value = text
-        syncClozeState(text) // Keep internal list of cloze indices(intClozeList) aligned with actual clozes in text
+        intClozeList.replaceWith(getClozeOrdinals(text ?: ""))
+        _currentClozeNumber.value = (intClozeList.maxOrNull() ?: 0) + 1
     }
 
     /**
```

File: AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt [hunk 2]
```diff
@@ -233,10 +256,15 @@ class InstantEditorViewModel :
 
         val clozeText: String?
 
-        val clozeNumber = currentClozeNumber
-        if (currentClozeMode.value == InstantNoteEditorActivity.ClozeMode.INCREMENT) {
-            incrementClozeNumber()
-        }
+        val clozeNumber =
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt]: Is this still necessary? Tests pass without it

File: AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt [hunk 3]
```diff
@@ -379,18 +407,13 @@ class InstantEditorViewModel :
     }
 
     fun toggleClozeMode() {
-        val newMode =
+        _currentClozeMode.value =
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt]: Is this still necessary? Tests pass without it

**Comment by david-allison** [comment]
minor guidance: Could you spend a little more time on the self-review phase of submissions, it looks like a lot of code was changed unnecessarily

If I'm wrong, could you add tests to showcase the bugs you're fixing

The test you added was great! Failed on `main`, passes on your branch

File: AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt (hunk 2 above)
Comment (Alok-Silswal) [reply AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt]: No, it isn't. Earlier, when I tested, issues were coming while toggling, so I modified it, thinking that both modes were not handled here properly. 

But functionally, both are the same. So this change isn't vital.

File: AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt (hunk 3 above)
Comment (Alok-Silswal) [reply AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt]: Again! No, it isn't. I tried to simplify it while checking for toggling issue.

Also, `val newNode` as a separate variable seemed redundant to me as at the end of the funtion its value is getting assigned to `_currentClozeMode.value`. That's why I modified. 

But I will revert this change.

**Comment by Alok-Silswal** [comment]
> Could you add a unit test?

Actually, this needs 3 different unit test cases (one already committed) as mentioned by me in https://github.com/ankidroid/Anki-Android/issues/20350#issuecomment-3941337649 i.e.

> On first load, the existing `c1` is not detected, so the cloze counter starts from 1 again, and the next insertion reuses `c1`.
> 
> After toggling `[...] +`, the state refresh causes the existing cloze to be detected correctly, and further insertions increment as expected.

---

> I tested this further with text that already has multiple clozes (c1, c2, c3).
> 
> **Observations:**
> 
> * On first load, when I select a new word in `[...] +` mode, it does not continue from `c4`. It starts again from `c1`.
> * The next selections then go `c2`, `c3`, but this numbering is clearly independent of the existing clozes in the text.
> * After toggling `[...] +`, selecting another word still does not continue from the highest existing index. Instead, it starts from `c2`.
> 
> So the counter does not seem to be derived from the current clozes present in the text. It looks like it’s using some local counter that gets reset or out of sync.

---

**Comment by Alok-Silswal** [comment]
@david-allison On deeper inspection, I found that there is no unit case to verify the cloze counter adjustment when switching from `INCREMENT` to `NO_INCREMENT` mode and vice-versa for cloze text. 

Shall I add that unit test case in this PR only, or open a separate Issue for that? I have the function ready for that.

File: AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt (hunk 1 above)
Comment (Alok-Silswal) [reply AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt]: Yes! This is working. I verified this with additional unit test cases also. This approach is better.

The thing is I was not aware of

`import androidx.annotation.CheckResult`, and
`import com.ichi2.anki.common.utils.ext.replaceWith`

as they in other files.

Thanks for pointing it out. I will modify the code accordingly.

**Comment by david-allison** [comment]
When you're bugfixing, keep the commit as lean as possible:

* fix
* test

If you notice more tests could be added, feel free to either add them as a new commit, or raise a separate PR. No issue necessary

**Review by david-allison — APPROVED** [review]
Cheers

**Comment by david-allison** [comment]
Could do with a squash and a commit message change. We're able to do this as it's a first merged PR:

The current commit message doesn't reference the screen

`fix(instant-card): set cloze number when existing clozes are present`

**Review by criticalAY — APPROVED** [review]
Looks good but the commit message needs to be cleaned

**Review by david-allison — APPROVED** [review]
