### PR TITLE
Handle 3-letter language roots correctly

### LINKED ISSUE #6254: Missing Language Name for "yu"
###### Reproduction Steps

1. Open Anki at provided commit
2. Scroll Down in the Language Picker

###### Expected Result

3. `yu` is displayed at the bottom

###### Actual Result

3. A name is given to the language.

Note: We might also need to ensure that each of the languages is picking up the correct value if there's a mismatch

###### Debug info
Run from commit 6d7e2deac75ecc5548bfb919b2cf752c498506a7

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### LINKED ISSUE #6256: Crowdin -> AnkiDroid import process misses / misattributes languages
###### Reproduction Steps

1. Run our crowdin script that updates app strings: ./tools/update_localizations.py

###### Expected Result

All the languages we support are visible and translated in the app preference for language selection

###### Actual Result

#6254 - missing language name for language 'yu'
#6255 - English is maybe not there (it is our base language)

3-letter language codes may not be working correctly either - we may need to handle this separately unless the fix for 'yu' is to switch to 'yue':

https://github.com/ankidroid/Anki-Android/blob/51bc1f601199f0f5748eb5f059b2217b526817e9/AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.java#L84

###### Thoughts

I would like the script to automatically generate the array for LanguageUtil so that the app is automatically up to date, but:

1. it needs to work around the fact the crowdin zip won't contain the base language (a la #6255)
1. it may or may not need to transpose hyphen to underscores between language families and variants (i.e. it is 'pt-BR' on crowdin, it was 'pt_BR' in Android, but is now 'pt-BR' in Android too, which should it be?)
1. it may need to handle differences between crowdin language codes and other ones (a la #6254)

### PR DESCRIPTION
**Pull request by mikehardy**
## Purpose / Description

Previously there was an expectation in the importer script that all
language codes had a 2-letter root, but many valid codes that Android
accepts have 3-letter codes *and* collide with the 2-letter codes (fi vs fil)

Additionally, the 'yu' (Cantonese) custom code needed to map to 'yue' for Android to recognize it

## Fixes

Fixes #6254
Fixes #6256

## Approach

- Instead of a 2-character hard split, I split on the hyphen while importing languages
- I was unable to map the custom language code 'yu' created by earlier AnkiDroid maintainers in Crowdin, so on import we special case that one and move it to 'yue' to match it's IATA tag

LanguageUtil also needed quite a bit of work for the same reason, splitting now on hyphen and underscore (because Android uses both at different times - hyphen for display in our language picker, underscore during system resource fetch) where it used to split hard on character index 2

This also cleans up the import done earlier while adding Sorani that produced
truncated (3-letter to 2-letter) languages (ckb->ck, got->go) while also adding all updated translations from a crowdin export

The only interesting changes are to tools/update-localizations.py and LanguageUtil.java - the rest is localization change

## How Has This Been Tested?

Thanks to the rejuvenated ability to test languages easily and see them in their own locale codes this was easily verified by visual inspection on an API16 and API28 emulator

I was able to see 'yu', then see the working (Cantonese) code when it was moved to 'yue', and I saw 'fi' but no Filiipino, with 'fi' messed up, then after moving 'fil' to it's own directory 'fi' was Finnish and Filipino was Filipino.

I also added unit tests that covered every case that was wrong and discovered during the manual inspection

## Learning (optional, can help others)
Android consumes IANA tags (thanks for the tip @david-allison-1) just fine, we just need to put our language files in the right spot

https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry

Our language display list expects regional variants to be like 'pt-BR', while the resource fetch code expects 'pt-br'

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by mikehardy** [comment]
Okay - will split yes, good catch on LanguageUtil, didn't realize it had the 2-char assumption as well.

**Comment by mikehardy** [comment]
Well that was a fun journey. At the last minute I thought "yeah, I'll unit test that" then i saw it was close but still all wrong and now I think it is all right.

Does everything as expected in API29 and API16 emulator plus in the test, after verifying that the res/values-* files are the result of a fresh import from crowdin

Our language infrastructure may still have bugs - I don't think so but it might - but I can assert that it has never been this great with the combo of language breadth and language selection features.

**Comment by david-allison-1** [comment]
> Does everything as expected in API29 and API16 emulator plus in the test, after verifying that the res/values-* files are the result of a fresh import from crowdin

Do you want this in quickly, or would you be happy if I manually tested this with a deadline of ~3 days or so?

It feels slightly embarrassing that we might be mistranslating Filipino to Finnish, it's a personal aim for this, and I wouldn't expect to block the review over it.

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 1]
```diff
@@ -398,6 +398,7 @@ public static Context updateContextWithLanguage(@NonNull Context remoteContext)
     private static Configuration getLanguageConfig(@NonNull Configuration remoteConfig, @NonNull SharedPreferences prefs) {
         Configuration newConfig = new Configuration(remoteConfig);
         Locale newLocale = LanguageUtil.getLocale(prefs.getString(Preferences.LANGUAGE, ""), prefs);
+        Timber.d("AnkiDroidApp::getLanguageConfig - setting locale to %s", newLocale.toString());
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:401]: Nit: No need to call `.toString()`, let the logging framework do it for efficiency.

File: AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.java [hunk 2]
```diff
@@ -81,10 +83,13 @@ public static Locale getLocale(@Nullable String localeCode, @NonNull SharedPrefe
...
-        if (localeCode.length() > 2) {
+        // Language separators are '_' or '-' at different times in display/resource fetch
+        if (localeCode != null && (localeCode.contains("_") || localeCode.contains("-"))) {
             try {
-                locale = new Locale(localeCode.substring(0, 2), localeCode.substring(3, 5));
-            } catch (StringIndexOutOfBoundsException e) {
+                String[] localeParts = localeCode.split("[_-]", 2);
+                locale = new Locale(localeParts[0], localeParts[1]);
+            } catch (ArrayIndexOutOfBoundsException e) {
+                Timber.w(e, "LanguageUtil::getLocale regional variant split failed. Using code raw.");
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.java:92]: Best to log the input

File: AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.java [hunk 3]
```diff
@@ -71,4 +76,32 @@ public void testCurrentLanguagesHaveNotChanged() {
...
+                LanguageUtil.getLocale("pt_BR").getDisplayName().equals("Portuguese (Brazil)"));
+    }
+
+    @Test
+    public void localeThreeLetterRegionalVariantResolves() {
+        assertThat("A locale with a 3-letter coe and regional variant resolves correctly",
+                LanguageUtil.getLocale("yue_TW").getDisplayName().equals("yue (Taiwan)"));
+        assertThat("A locale with a 3-letter coe and regional variant resolves correctly",
+                LanguageUtil.getLocale("yue-TW").getDisplayName().equals("yue (Taiwan)"));
+    }
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.java:106]: Do we need/intend to handle ISO 639 here? `zh-Hant-TW` for example?

https://android.googlesource.com/platform/external/icu4c.git/+/master/data/locales/ - not sure if this is relevant

File: AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.java [hunk 4]
```diff
@@ -71,4 +76,32 @@ public void testCurrentLanguagesHaveNotChanged() {
...
+                LanguageUtil.getLocale("pt-BR").getDisplayName().equals("Portuguese (Brazil)"));
+        assertThat("A locale with a 2-letter code and regional variant resolves correctly",
+                LanguageUtil.getLocale("pt_BR").getDisplayName().equals("Portuguese (Brazil)"));
+    }
+
+    @Test
+    public void localeThreeLetterRegionalVariantResolves() {
+        assertThat("A locale with a 3-letter coe and regional variant resolves correctly",
+                LanguageUtil.getLocale("yue_TW").getDisplayName().equals("yue (Taiwan)"));
+        assertThat("A locale with a 3-letter coe and regional variant resolves correctly",
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.java:104]:
```suggestion
        assertThat("A locale with a 3-letter code and regional variant resolves correctly",
```

File: AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.java [hunk 5]
```diff
@@ -71,4 +76,32 @@ public void testCurrentLanguagesHaveNotChanged() {
...
+    public void localeTwoLetterRegionalVariantResolves() {
+        assertThat("A locale with a 2-letter code and regional variant resolves correctly",
+                LanguageUtil.getLocale("pt-BR").getDisplayName().equals("Portuguese (Brazil)"));
+        assertThat("A locale with a 2-letter code and regional variant resolves correctly",
+                LanguageUtil.getLocale("pt_BR").getDisplayName().equals("Portuguese (Brazil)"));
+    }
+
+    @Test
+    public void localeThreeLetterRegionalVariantResolves() {
+        assertThat("A locale with a 3-letter coe and regional variant resolves correctly",
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.java:102]:
```suggestion
        assertThat("A locale with a 3-letter code and regional variant resolves correctly",
```

File: AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.java [hunk 6]
```diff
@@ -71,4 +76,32 @@ public void testCurrentLanguagesHaveNotChanged() {
         assertThat("Languages have been updated, please modify test variables: " +
                 "PREVIOUS_LANGUAGES and CURRENT_LANGUAGES", actual, contains(CURRENT_LANGUAGES));
     }
+
+    @Test
+    public void localeTwoLetterCodeResolves() {
+        assertThat("A locale with a 2-letter code resolves correctly",
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.java:82]: Will these tests pass if the users locale is non-English? I think all of our non-instrumented test runs are still in English.

File: tools/update-localizations.py [hunk 7]
```diff
@@ -178,12 +178,16 @@ def build():
 t.close()
 
 for language in languages:
-    if language[:2] in localizedRegions:
-        androidLanguage = string.replace(language, '-', '-r')
+    # Regional files need a marker in Android
+    if language.split('-', 1)[0] in localizedRegions:
```
Comment (david-allison-1) [inline tools/update-localizations.py:182]: Could you link some docs here. I assume this is correct, but I really can't know.

File: tools/update-localizations.py [hunk 8]
```diff
@@ -178,12 +178,16 @@ def build():
...
+        androidLanguage = string.replace(language, '-', '-r') # zh-CW becomes zh-rCW
     else:
-        androidLanguage = language[:2] # Example: es-ES becomes es
+        androidLanguage = language.split('-', 1)[0] # Example: es-ES becomes es
 
-    print "\nCopying language files for: " + androidLanguage
+    if language == 'yu':
+        androidLanguage = 'yue'
+
+    print "\nCopying language files from " + language + " to " + androidLanguage
```
Comment (david-allison-1) [inline tools/update-localizations.py:190]: This is python2?

File: tools/update-localizations.py (hunk 7 above)
Comment (david-allison-1) [inline tools/update-localizations.py:182]: This feels subject to change. Would it be possible to make a HashSet of the prefixes and see if there are collisions.

Something like `af_NA` and `af_ZA` Afrikaans (South Africa/Namibia) probably wouldn't be caught here, and it'd be useful to flag this new conflict to a maintainer.

File: AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.java (hunk 6 above)
Comment (mikehardy) [reply AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.java:82]: Robolectric has locale-changing power but I've not used it, an extension to the tests to do so could be a separate PR if you want to investigate. I have used Robolectric API switching so I know it's effective, it's just an annotation IIRC

File: AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.java (hunk 3 above)
Comment (mikehardy) [reply AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.java:106]: I have no intention of going farther than supported functionality at this point which is two part codes only

File: tools/update-localizations.py (hunk 7 above)
Comment (mikehardy) [reply tools/update-localizations.py:182]: I have no docs, just direct experience while testing, sorry. Definitely needs to split on underscore or the language switch isn't recognized for 2-part codes, definitely needs to split on the hyphen or the language list doesn't work for 2-part codes

File: tools/update-localizations.py (hunk 8 above)
Comment (mikehardy) [reply tools/update-localizations.py:190]: It's all just python to me ;-)

File: tools/update-localizations.py (hunk 7 above)
Comment (mikehardy) [reply tools/update-localizations.py:182]: good point on that one - the more guard rails we can put in there the better, but I'm out of time for polishing on the release and publish and locale scripts. There are problems still in there but in the last release cycle I already fixed about 10 and de-linted and they'll have to wait their turn again. I can leave a note though

File: AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.java (hunk 6 above)
Comment (david-allison-1) [reply AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.java:82]: My concern is ensuring that new contributors coming into the project won't have broken tests. In a normal circumstance, this should change, but we should ensure this doesn't happen for foreign developers.

<details><summary>getDisplayLanguage Comments</summary>

```java
/**
     * Returns a name for the locale's language that is appropriate for display to the
     * user.
     * If possible, the name returned will be localized for the default
     * {@link Locale.Category#DISPLAY DISPLAY} locale.
     * For example, if the locale is fr_FR and the default
     * {@link Locale.Category#DISPLAY DISPLAY} locale
     * is en_US, getDisplayLanguage() will return "French"; if the locale is en_US and
     * the default {@link Locale.Category#DISPLAY DISPLAY} locale is fr_FR,
     * getDisplayLanguage() will return "anglais".
     * If the name returned cannot be localized for the default
     * {@link Locale.Category#DISPLAY DISPLAY} locale,
     * (say, we don't have a Japanese name for Croatian),
     * this function falls back on the English name, and uses the ISO code as a last-resort
     * value.  If the locale doesn't specify a language, this function returns the empty string.
     *
     * @return The name of the display language.
     */
```
</details>

File: tools/update-localizations.py (hunk 7 above)
Comment (david-allison-1) [reply tools/update-localizations.py:182]: Happy with a TODO

Comment (david-allison-1) [reply tools/update-localizations.py:182]: OK, could we mark with a TODO to get this a little better documented.

File: AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.java (hunk 6 above)
Comment (mikehardy) [reply AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.java:82]: I now have a strong dislike for the Hamcrest matchers. On failure between expected/actual they don't spit out the actual or expected so you can't visually inspect immediately. You have to instrument, waste of time. Switching to junit Assert. I'm adding resource loading configs on robolectric and SDK skew though, as this would have tripped new developers with non-'en' system langauge

File: tools/update-localizations.py (hunk 7 above)
Comment (mikehardy) [reply tools/update-localizations.py:192]: I expanded the docs for variant addition a great deal, very prescriptive for maintainers now in the "add new regional variant" case

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.java  2
- AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.java  2
         

Clones added
============
- AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5612957&bid=18387374)

File: tools/update-localizations.py (hunk 7 above)
Comment (mikehardy) [reply tools/update-localizations.py:196]: Added https://developer.android.com/guide/topics/resources/providing-resources#AlternativeResources

**Comment by mikehardy** [comment]
Pushed an NF commit resolving all items

File: AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.java (hunk 6 above)
Comment (david-allison-1) [reply AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.java]: Hamcrest definitely outputs the failures, that's the point of a fluent library. 

You shouldn't be using `assertThat(bool)`

You should use `assertThat("string", is("string"))``

image

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.java  2
- AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.java  2
         

Clones added
============
- AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5612957&bid=18387374)

File: tools/update-localizations.py (hunk 7 above)
Comment (david-allison-1) [reply tools/update-localizations.py:196]: Just a TODO in the code will do

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.java  2
- AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.java  2
         

Clones added
============
- AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5612957&bid=18387374)
