### PR TITLE
fix(reminders): catch BadParcelableException in NotificationService

### LINKED ISSUE #20782: NotificationService: Crash when reading the bytes of an old alarm after a schema change
https://ankidroid.org/acra/app/1/bug/396907/report/ca2337af-89c5-4595-beb0-dc57e02a62a5

2.24.0alpha14

`SDK_INT: 33`; Xiaomi Poco F5 Pro

```
java.lang.RuntimeException: Unable to start receiver com.ichi2.anki.services.NotificationService: android.os.BadParcelableException: Parcelable protocol requires subclassing from Parcelable on class za.a0
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4501)
	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2227)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8247)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: android.os.BadParcelableException: Parcelable protocol requires subclassing from Parcelable on class za.a0
	at android.os.Parcel.readParcelableCreatorInternal(Parcel.java:4872)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4766)
	at android.os.Parcel.readParcelable(Parcel.java:4743)
	at com.ichi2.anki.reviewreminders.ReviewReminder$Creator.createFromParcel(ReviewReminder.java)
	at com.ichi2.anki.reviewreminders.ReviewReminder$Creator.createFromParcel(ReviewReminder.java)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4775)
	at android.os.Parcel.readValue(Parcel.java:4532)
	at android.os.Parcel.readValue(Parcel.java:4312)
	at android.os.Parcel.-$$Nest$mreadValue(Unknown Source)
	at android.os.Parcel$LazyValue.apply(Parcel.java:4410)
	at android.os.Parcel$LazyValue.apply(Parcel.java:4369)
	at android.os.BaseBundle.getValueAt(BaseBundle.java:394)
	at android.os.BaseBundle.getValue(BaseBundle.java:374)
	at android.os.BaseBundle.getValue(BaseBundle.java:357)
	at android.os.BaseBundle.getValue(BaseBundle.java:350)
	at android.os.Bundle.getParcelable(Bundle.java:913)
	at androidx.core.os.BundleCompat.getParcelable(BundleCompat.java:73)
	at com.ichi2.anki.services.NotificationService.onReceive(NotificationService.kt:459)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4488)
	... 9 more

```

@ericli3690 - could be a weird device; could you take a quick look for anything obvious?

### PR DESCRIPTION
**Pull request by ericli3690**
## Purpose / Description
If an old intent for a review reminder notification somehow sticks around after a schema migration update, the ReviewReminder stored in the intent will become out of date and cause a BadParcelableException.

## Fixes
* Fixes #20782

## Approach
While we could implement custom logic to migrate that reminder, that would duplicate the logic for schema migrations currently present in ReviewRemindersDatabase. It's simpler to just fallback on that already-existing logic by triggering a total review reminder schedule and returning early. Hence, this code change.

## How Has This Been Tested?
I cannot reproduce this bug personally, as whenever I trigger an update to the schema, the entire app uninstalls and re-installs, which throws out the old intents. I assume the original cause of the bug was some transient error. Nonetheless, this defensive try-catch should be a good addition to the codebase here.

## Learning (optional, can help others)
[Pertinent code in the AOSP](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/apex/jobscheduler/service/java/com/android/server/alarm/AlarmManagerService.java;l=4994)

Quoting from my initial response to this issue:
> I can think of two ways to solve this, both of which should work:

> 1. Try-catch, and when a BadParcelableException is thrown, simply trigger a AlarmManagerService.scheduleAllNotifications and return. Once https://github.com/ankidroid/Anki-Android/pull/20755 is merged, what scheduleAllNotifications does is fire any notifications that should have recently been fired and then schedule any future ones that need to happen. This is the simple solution.
> 2. Create a proper getParcelableReminder helper that successively attempts to de-parcelize using every schema from newest to oldest, and which only throws if all old schemas fail. Once a schema successfully parses the reminder, use .migrate() to bring it up to date. This is the most correct solution.

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.kt [hunk 1]
```diff
@@ -458,11 +459,21 @@ class NotificationService : AnkiBroadcastReceiver() {
...
+                        EXTRA_REVIEW_REMINDER,
+                        ReviewReminder::class.java,
+                    ) ?: return
+                } catch (e: BadParcelableException) {
+                    // #20782: If the extra's review reminder has an invalid schema, attempt a full re-schedule of all
+                    // review reminder notifications, as that will retrieve reminders from Shared Preferences
+                    // and handle any necessary schema updates. It will also trigger immediate notifications
+                    // (and thus this onReceiveBroadcast again for an uncorrupted version of this corrupted review reminder) as necessary.
+                    Timber.w(e, "Failed to get review reminder from intent extras, triggering full re-schedule")
+                    AlarmManagerService.scheduleAllEnabledReviewReminderNotifications(context)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.kt:474]: (sorry, I'm on my phone) 

Just to confirm: can this throw?

Comment (ericli3690) [reply AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.kt:474]: Reviewing code on a phone is crazy dedication haha

To answer your question: I would be surprised if it did, and would consider it a bug.

Deserialization etc. of the stored reminders in SharedPrefs is handled by `decodeJson`, which is built to not throw and to instead serialize and store errors for later viewing, preventing broken review reminders from blocking the app.

So the rest of the logic is just scheduling the alarms, which shouldn't throw.

**Review by david-allison — APPROVED** [review]
LGTM, cheers!

**Review by lukstbit — APPROVED** [review]

**Review by mikehardy — COMMENTED** [review]
I have been through all of these things with Notifee (react-native notification library) before - it's like seeing old friends 😆
