### PR TITLE
Dealing with ":::" in deck name

### LINKED ISSUE #5603: Can't open database with many decks after update
###### Reproduction Steps

1. Open AnkiDroid
2. Error message appears (see screenshot in Italian, giving only two options: "close" and "options")
3. Even after trying to check the database (the most reasonable option), I can't open my collection. But the same collection works fine with Anki desktop and previous AnkiDroid versions

Screenshot_2019-11-04-04-04-25

###### Expected Result

Open decks and use normally.

###### Actual Result

Can't open collection, need to close.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

I cannot copy the debug info, because the app doesn't allow to do anything. However, I know from google play it in version 2.9.2beta4

###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
## Purpose / Description
The method `parent` as I implemented it, does not deal with names
having ":::" in them. "::::" is impossible, but ":::" is totally
okay. So now it deals with it.

Anki believe that in this case, the first two colons are the
separators, the last one is part of the deck name.

## Fixes
#5603

## How Has This Been Tested?

Trying to reproduce the above-mentionned bug, and failing the reproduction.

## Learning (optional, can help others)
_Describe the research stage_
I did read the three commits during which the problems did appear, and which were listed by timrae

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java [hunk 1]
```diff
@@ -1137,6 +1137,11 @@ public static String parent(String deckName) {
 		if (index == -1) {
 			return null;
 		}
+        if (deckName.charAt(index-1) == ':') {
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java]: Out of curiosity, why not use the upstream libanki 'split' style to match it's code? I think String.split is fit for purpose by taking a String (vs a single character) https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#split(java.lang.String)

```python

        def parent(name):
            parts = name.split("::")
            if len(parts) < 2:
                return None
            parts = parts[:-1]
            return "::".join(parts)
```

Seems like it would handle things well, and you can chop the last element of an array in java without too much trauma I think https://stackoverflow.com/a/26357886/9910298

Comment (Arthur-Milchior) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java]: Only because it's more efficient to cut once and never to join than to cut everywhere to split back almost everything.
I can port this code if that's requested. But honestly, the academician I am would feel dirty doing it; even if in real life, this would not by really costly as far as time is concerned.

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java]: I'm sorry to request something that doesn't feel great but I think it would be better for it to be just like anki - this bug wouldn't have happened e.g. if it was a straight port

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java]: to be clear - a valid reason to depart from libanki behavior would be known performance pathology, or API simply not available etc, or some language-difference between Python and Java, but here the analogs are all available I think, and if it works in Python it should work on Java performance wise

Comment (Arthur-Milchior) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java]: Ok. Corrected. I now stick to anki code. I can't deny that not sticking to it was the cause of the problem in the first place

File: AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java [hunk 2]
```diff
@@ -1131,17 +1131,18 @@ public boolean isDyn(long did) {
     * ***********************************************************
     */
 
-	public static String parent(String deckName) {
-		// method parent, from sched's method deckDueList in python
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java]: This comment was actually a vital clue for me to find the upstream code when I was comparing it to double-check correctness, could you leave it in?

Comment (Arthur-Milchior) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java]: done

**Comment by timrae** [comment]
Thanks Arthur for the quick fix and Mike for the nice review!

**Comment by mikehardy** [comment]
Indeed - I was being pesky there on the review :-) but @Arthur-Milchior big thanks for all the libanki ports in general, and the quick fix here.
