### PR TITLE
fix: MigrationService: Progress is incorrect after service restart

### LINKED ISSUE #13634: MigrationService: Progress is incorrect after service restart
Migration progress is calculated on service start. Therefore on a service restart, the `total` is incorrect

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
After restarting the phone, Storage Migration Progress should be preserved

## Fixes
Fixes #13634

## Approach
* Save a variable to Shared Preferences
* Restore & use it while converting

## How Has This Been Tested?
* API 30 emulator, with commit rebased on https://github.com/ankidroid/Anki-Android/pull/13657
  * Loaded AnKing. Started a migration. Turned off the emulated phone. Progress (total + files copied) were restored when emulated phone was turned on

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt [hunk 1]
```diff
@@ -168,6 +171,19 @@ class MigrationService : ServiceWithALifecycleScope(), ServiceWithASimpleBinder<
...
+     * Returns the total number of bytes which the MigrationService expects to transfer
+     */
+    private fun getTotalTransferSize(task: MigrateUserData): Long {
+        // The first time that this is accessed will be on the first run of the service, so calculate the remaining transfer size.
+        // On subsequent runs, return the value we stored in Shared Preferences
+        return AnkiDroidApp.getSharedPrefs(this.baseContext).getOrSetLong(
+            PREF_MIGRATION_TOTAL_TO_TRANSFER
+        ) {
+            getRemainingTransferSize(task)
+        }
```
Comment (oakkitten) [inline AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt:184]: Why `baseContext`?

Nit: I prefer writing it like this:

```kt
        return AnkiDroidApp.getSharedPrefs(this.baseContext)
            .getOrSetLong(PREF_MIGRATION_TOTAL_TO_TRANSFER) { getRemainingTransferSize(task) }
```

It places one call on one line, and seeing how the trailing lambda is not an unconditionally run block of arbitrary length but a supplier of a default value, it is about just as “important” as the key argument. In fact, if `get or set` wasn't a common idiom I would even prefer not using trailing lambdas, as in: `getOrSet(key, default = { ... })`

**Review by oakkitten — COMMENTED** [review]
I was initially thinking of calculating the size of the target directory and using it for `transferredBytes`, and a sum of that and `getRemainingTransferSize` for the total. But this is probably better, as we don't deal with changes in the size of the target directory, and partially copied files do not become a problem. 👍

As this resolves [one TODO](https://github.com/ankidroid/Anki-Android/blob/a24217b1f8df059d12dfd73fa0804e74a3dce6c3/AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt#L155-L158) it should probably be removed as well.

**Review by mikehardy — APPROVED** [review]
LGTM. I'm not that interested in the nit proposals but the one regarding perf seems interesting
You marked "needs author reply" which implies intent to address nits, will merge after what I guess will be a re-push

**Comment by mikehardy** [comment]
David is aware, I suppose fixup is a follow-on to address the nits. Mea maxima culpa - I'm intending to push hard on progress in these PRs but this was an error on my part.
