### PR TITLE
fix(manage-space): crash if `getPackageSizeInfo` fails

### LINKED ISSUE #17387: ManageSpaceActivity: NoSuchMethodException: getPackageSizeInfo
https://ankidroid.org/acra/app/1/bug/253484/report/1766425b-f629-44a7-83cd-c9928a3add89

```
java.lang.NoSuchMethodException: getPackageSizeInfo [class java.lang.String, interface b.a]
	at java.lang.Class.getMethod(Class.java:1981)
	at java.lang.Class.getMethod(Class.java:1637)
	at com.ichi2.anki.ui.windows.managespace.FileUtilsKt.getUserDataAndCacheSizeUsingGetPackageSizeInfo(FileUtils.kt:115)
	at com.ichi2.anki.ui.windows.managespace.FileUtilsKt.getUserDataAndCacheSize(FileUtils.kt:46)
	at com.ichi2.anki.ui.windows.managespace.ManageSpaceViewModel$launchCalculationOfSizeOfEverything$1$1.invokeSuspend(ManageSpaceFragment.kt:155)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.java:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [p0{Cancelling}@219e5c1, Dispatchers.Main.immediate]
```

### PR DESCRIPTION
**Pull request by david-allison**
On a (knockoff?) API 25 phone, `getPackageSizeInfo` failed with

```
java.lang.NoSuchMethodException: getPackageSizeInfo [class java.lang.String, interface b.a]
	at java.lang.Class.getMethod(Class.java:1981)
	at java.lang.Class.getMethod(Class.java:1637)
	at com.ichi2.anki.ui.windows.managespace.FileUtilsKt.getUserDataAndCacheSizeUsingGetPackageSizeInfo(FileUtils.kt:115)
```

## Fixes
* Fixes #17387

## Approach

* handling the exception
* documenting the exception

## How Has This Been Tested?

I modified the code to throw an exception

Screenshot 2024-11-10 at 17 14 48

* button still worked

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/FileUtils.kt [hunk 1]
```diff
@@ -38,6 +38,7 @@ import kotlin.coroutines.resume
 /**
  * Get the size of user data and cache for the current package, in bytes.
  * This should amount to the sum of User data and Cache in App info -> Storage and cache.
+ * @throws NoSuchMethodException occasionally on some phones < [Build.VERSION_CODES.O] (#17387)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/FileUtils.kt:41]: I link the version code so it'll be caught when we upgrade

**Review by mikehardy — APPROVED** [review]
works for me

**Review by lukstbit — APPROVED** [review]
LGTM
