### PR TITLE
Don't crash Check Database when Database is locked

### LINKED ISSUE #6067: [ACRA 2.10alpha71] - A locked database crashes "Check Database"
We need a design for what to do if the database is locked. Presumably cancel the check.

But the UI shouldn't be working when the database is locked.

Nothing in logcat for the device aside from the stack trace.

----

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/reports-browser/user/fd9d9e7c-9e17-4df3-810e-43af4dc764e2

Sync:
```
android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)
at io.requery.android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
at io.requery.android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:7)
at io.requery.android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:6)
at io.requery.android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:2)
at io.requery.android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:5)
at io.requery.android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:1)
at com.ichi2.libanki.sync.Syncer.sync(Syncer.java:6)
at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:16)
at com.ichi2.async.Connection.doOneInBackground(Connection.java:2)
at com.ichi2.async.Connection.doInBackground(Connection.java:4)
at com.ichi2.async.Connection.doInBackground(Connection.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:304)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)
```

Check Database:
```
android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)
at io.requery.android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
at io.requery.android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:7)
at io.requery.android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:6)
at io.requery.android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:2)
at io.requery.android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:5)
at io.requery.android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:1)
at com.ichi2.libanki.Collection.fixIntegrity(Collection.java:7)
at com.ichi2.async.CollectionTask.doInBackgroundCheckDatabase(CollectionTask.java:5)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:45)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:304)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)
```

Crash:
```
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:318)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.IllegalStateException: Cannot perform this operation because there is no current transaction.
at io.requery.android.database.sqlite.SQLiteSession.throwIfNoTransaction(SQLiteSession.java:2)
at io.requery.android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:1)
at io.requery.android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:2)
at com.ichi2.libanki.Collection.fixIntegrity(Collection.java:11)
at com.ichi2.async.CollectionTask.doInBackgroundCheckDatabase(CollectionTask.java:5)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:45)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:304)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 4 more
```

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description
`beginTransaction` was throwing `SQLiteDatabaseLockedException`

This meant that `endTransaction` threw in Check Integrity.

## Fixes
Fixes #6067 

## Approach
We handle this case in Check Database, and add in a new "Database Error" screen to handle "Database Locked".

## How Has This Been Tested?

Tested on my phone, and unit tests. No longer crashes.

image

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/testutils/CollectionUtils.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerCheckDatabaseListenerTest.java  1
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java  1
- AnkiDroid/src/test/java/com/ichi2/async/AbstractCollectionTaskTest.java  3
- AnkiDroid/src/main/java/com/ichi2/anki/debug/DatabaseLock.java  1
- AnkiDroid/src/test/java/com/ichi2/async/CollectionTaskCheckDatabaseTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5461550&bid=17899202)

File: AnkiDroid/src/main/java/com/ichi2/anki/debug/DatabaseLock.java [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+
+import android.content.Context;
+
+import com.ichi2.anki.CollectionHelper;
+import com.ichi2.libanki.Collection;
+
+import timber.log.Timber;
+
+/** Debug only class which will lock the database */
+public class DatabaseLock {
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/debug/DatabaseLock.java:27]: Codacy Issue found: [The utility class name 'DatabaseLock' doesn't match '[A-Z][a-zA-Z0-9]+(Utils?|Helper|Constants)'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5461550)

File: AnkiDroid/src/test/java/com/ichi2/async/AbstractCollectionTaskTest.java [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+
+@RunWith(AndroidJUnit4.class)
+public class AbstractCollectionTaskTest extends RobolectricTest {
+
+    protected CollectionTask.TaskData execute(int taskType) {
+        CollectionTask task = CollectionTask.launchCollectionTask(taskType);
+        try {
+            return task.execute().get();
+        } catch (Exception e) {
+            throw new RuntimeException(e);
```
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/async/AbstractCollectionTaskTest.java:38]: Codacy Issue found: [Avoid throwing raw exception types.](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5461550)

File: AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerCheckDatabaseListenerTest.java [hunk 3]
```diff
@@ -0,0 +1,177 @@
...
+
+@RunWith(AndroidJUnit4.class)
+public class DeckPickerCheckDatabaseListenerTest extends RobolectricTest {
+
+    private DeckPickerTestImpl impl;
+
+    @Override
+    public void setUp() {
+        super.setUp();
+        //.visible() crashes: Layout state should be one of 100 but it is 10
```
Comment (mikehardy) [inline AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerCheckDatabaseListenerTest.java:42]: this stuff is touchy, this is not something to fix here / it is not actionable - just as knowledge sharing I have an advanceRobolectricLooper method I use in #5151 and it's basically setting Looper mode to PAUSED in robolectric, then after you do something that twiddles state but before (and after) you twiddle UI you ask robolectric to advance the execution loop, and then I sleep for a moment (since we do async things). Not ideal but that's how to turn the crank as it were in robolectric if you want to play with UI stuff

not actionable here because visibility isn't important but maybe useful info going forward

File: AnkiDroid/src/main/res/values/03-dialogs.xml [hunk 4]
```diff
@@ -172,4 +172,8 @@
 
     <!-- Deck Options -->
     <string name="deck_options_corrupt">Failed to process deck options: %s</string>
+
+    <!-- Database Errors-->
+    <string name="database_locked_title">Database Locked</string>
+    <string name="database_locked_summary">The AnkiDroid database is in use by another application. Please close it and reopen the app.</string>
```
Comment (mikehardy) [inline AnkiDroid/src/main/res/values/03-dialogs.xml:178]:
```suggestion
    <string name="database_locked_summary">The AnkiDroid database is in use by another application. Please close the other application then reopen AnkiDroid.</string>
```

ambiguity-- && pedanticness++

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java [hunk 5]
```diff
@@ -270,12 +272,25 @@ public MaterialDialog onCreateDialog(Bundle savedInstanceState) {
                         })
                         .show();
             }
+            case DIALOG_DB_LOCKED: {
+                //If the database is locked, all we can do is ask the user t exit.
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java:276]:
```suggestion
                //If the database is locked, all we can do is ask the user to exit.
```

As long as I have one textual nit that's important might as well throw in the other one I would have otherwise ignore ;-)

I think this was the last commit in the stack, I'd like to rebase not squash so if you could merge this in (ignoring the fact that github makes them committable - it's just a nice presentation to see my suggestion - that'd be `<kiwi>legend</kiwi>`

**Comment by david-allison-1** [comment]
Done & force pushed

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java (hunk 5 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java]: I'm used to rebasing commits in the middle of the stack now, so it's not a bother. Both were at the end

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/testutils/CollectionUtils.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerCheckDatabaseListenerTest.java  1
- AnkiDroid/src/test/java/com/ichi2/async/CollectionTaskCheckDatabaseTest.java  1
- AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java  1
- AnkiDroid/src/main/java/com/ichi2/anki/debug/DatabaseLock.java  1
- AnkiDroid/src/test/java/com/ichi2/async/AbstractCollectionTaskTest.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5461550&bid=17899202)

File: AnkiDroid/src/test/java/com/ichi2/async/AbstractCollectionTaskTest.java [hunk 6]
```diff
@@ -0,0 +1,49 @@
...
+
+@RunWith(AndroidJUnit4.class)
+public abstract class AbstractCollectionTaskTest extends RobolectricTest {
+
+    protected CollectionTask.TaskData execute(int taskType) {
+        CollectionTask task = CollectionTask.launchCollectionTask(taskType);
+        try {
+            return task.execute().get();
+        } catch (Exception e) {
+            throw new RuntimeException(e);
```
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/async/AbstractCollectionTaskTest.java:38]: Codacy Issue found: [Avoid throwing raw exception types.](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5461550)

File: AnkiDroid/src/main/java/com/ichi2/anki/debug/DatabaseLock.java (hunk 1 above)
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/debug/DatabaseLock.java:27]: Codacy Issue found: [The utility class name 'DatabaseLock' doesn't match '[A-Z][a-zA-Z0-9]+(Utils?|Helper|Constants)'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5461550)

File: AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerCheckDatabaseListenerTest.java (hunk 3 above)
Comment (david-allison-1) [reply AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerCheckDatabaseListenerTest.java:42]: I thought I'd replied here, `visible` works for CardBroser/Viewer. Would you like me to remove the line?

P.S: Thanks for the info, for now I try to avoid UI testing as it doesn't add much value if the business logic is well structured, and ties us in to an implementation, sometimes before we've really considered whether it was the right move (especially true given the complexity of DeckPicker).
