### PR TITLE
fix(study-screen): streamline actions

### LINKED ISSUE #19641: [New study screen] Card was modified error when tapping the answer buttons quickly
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Open the new study screen with a few cards to review.
2. Spam the answer buttons or gestures.

Image

### Expected behaviour

No error.

### Debug info

```text
AnkiDroid Version = 2.23.0alpha8 (f9e524a31c98e4f5d922f7b2c5217efe4d350009)  
Backend Version = 0.1.62-anki25.09.2 (25.09.2 3890e12c9e48c028c3f12aa58cb64bd9f8895e30)  
Android Version = 13 (SDK 33)  
ProductFlavor = full  
Device Info = Xiaomi | POCO | mondrian | mondrian_global | 23013PC75G | qcom  
Webview User Agent = Mozilla/5.0 (Linux; Android 13; 23013PC75G Build/TKQ1.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/142.0.7444.106 Mobile Safari/537.36  
ACRA UUID = 4afc3b3f-e93f-4a66-bc71-2b9476ef9eb0  
FSRS = 5.1.0 (Enabled: true)  
Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

I don't remember this happening before. However, I have got this and similar errors in other ways; see https://github.com/ankidroid/Anki-Android/issues/17933#issuecomment-3320359500.

Huh, this's weird; I thought you scrapped the ripple effect for answer buttons PR (#19085):

https://github.com/user-attachments/assets/07b53c33-ee66-4c6d-ba2c-d64960ed6264

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by BrayanDSO**
## Purpose / Description

Doing everything asynchronously and in parallel lead to some concurrency issues, like #19641

## Fixes
* Fixes #19641
* Closes #20289

## Approach

use `executeAction` as the single source of actions from the fragment

that way, most uses of launchCatchingIO got removed, so actions won't run parallelly

then use a mutex to make actions run in order inside `executeAction`

As `executeAction` is supposed to be used only by the View, not in the ViewModel internal logic, it being "synchronic" is alright, I think

## How Has This Been Tested?

Emulator 31 + an auto clicker

https://github.com/user-attachments/assets/5e38b4fc-88ce-4ec9-9f3b-8716f296e7dd

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt [hunk 1]
```diff
@@ -689,6 +704,7 @@ class ReviewerViewModel(
                 ViewerAction.PLAY_MEDIA -> replayMedia()
                 ViewerAction.FLAG_MENU -> {}
             }
+            actionsMutex.unlock()
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt]: This should be in a `finally` block or a lambda which handles unlocking

**Review by david-allison — CHANGES_REQUESTED** [review]
This doesn't look exception-safe.

The rest looks great!

File: AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt (hunk 1 above)
Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt]: Used `withLock`

**Review by david-allison — APPROVED** [review]
LGTM, cheers!

File: AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt [hunk 2]
```diff
@@ -666,66 +679,68 @@ class ReviewerViewModel(
...
+                    ViewerAction.FLAG_TURQUOISE -> setFlag(Flag.TURQUOISE)
+                    ViewerAction.FLAG_PURPLE -> setFlag(Flag.PURPLE)
+                    ViewerAction.TOGGLE_FLAG_RED -> toggleFlag(Flag.RED)
+                    ViewerAction.TOGGLE_FLAG_ORANGE -> toggleFlag(Flag.ORANGE)
+                    ViewerAction.TOGGLE_FLAG_BLUE -> toggleFlag(Flag.BLUE)
+                    ViewerAction.TOGGLE_FLAG_GREEN -> toggleFlag(Flag.GREEN)
+                    ViewerAction.TOGGLE_FLAG_PINK -> toggleFlag(Flag.PINK)
+                    ViewerAction.TOGGLE_FLAG_TURQUOISE -> toggleFlag(Flag.TURQUOISE)
+                    ViewerAction.TOGGLE_FLAG_PURPLE -> toggleFlag(Flag.PURPLE)
+                    ViewerAction.SHOW_ANSWER -> if (!showingAnswer.value) onShowAnswer()
```
Comment (lukstbit) [inline AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerViewModel.kt]:
```suggestion
                    ViewerAction.SHOW_ANSWER -> if (!showingAnswer.value) showAnswerInternal()
```

otherwise we enter a recursive loop.

**Review by lukstbit — DISMISSED** [review]

**Review by lukstbit — APPROVED** [review]
