### PR TITLE
Fix changing the cards order to 'NoOrdering' after toggling to 'Notes'

### LINKED ISSUE #14825: [BUG]: display order bug for notes
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Go to "card browser" then "options" and under "toggle cards/notes" select "notes". Go to "change display order" and choose another option.

### Expected behaviour

The display order should stay as set, like when "cards" is selected in "toggle cards/notes."

### Actual behaviour

When you select "notes", it automatically sets the display order to "by created time" oldest to newest. If you choose another option it doesn't change except by pressing "by created time" again to flip the direction.  This only works until you exit the app or add a new note, and it then flips to oldest to newest again.

### Debug info

```text
AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)

Android Version = 13

ProductFlavor = play

Manufacturer = samsung

Model = SM-P610

Hardware = exynos9611

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-P610 Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/119.0.6045.66 Safari/537.36

ACRA UUID = cc3ec77b-8b96-40ad-99e3-3187c7799494

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by peyman79**
## Purpose / Description
When changing the display ordering for cards and then toggling to notes, the previous ordering will not persist; instead, it displays notes with no specific order (default ordering).

## Fixes
* Fixes #14825

## Approach
The  function doesn't include specific order
The function _findOneCardByNote_ did not affect the user-specified order on the list of cardIds; instead, it always passed the constant value 'NoOrdering' as input to the _findNotes_ function. Furthermore, the _findNotes_ function, as a result, did not take the order value into account when received from the backend.
I modified the functionality of _searchForCards_ to consistently pass the results of _findCards_, regardless of whether it is in card mode or not.

## How Has This Been Tested?
Tested on Galaxy A50 (API 29)

https://github.com/ankidroid/Anki-Android/assets/61017890/29189f00-307e-440f-9a89-5fd34a2694f8

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — CHANGES_REQUESTED** [review]
Thanks for the contribution!

This removes the 'notes' functionality, and there are unit test failures

----

Just to note: we're going to be reworking this area fairly soon after https://github.com/ankidroid/Anki-Android/pull/14843 is merged (https://github.com/ankidroid/Anki-Android/issues/11889), could you also add a unit test for the issue you're fixing, to ensure that we don't add a regression here.

**Review by david-allison — CHANGES_REQUESTED** [review]
review was already provided, code hasn't changed

**Comment by peyman79** [comment]
> Thanks for the contribution!
> 
> This removes the 'notes' functionality, and there are unit test failures
> 
> Just to note: we're going to be reworking this area fairly soon after #14843 is merged (#11889), could you also add a unit test for the issue you're fixing, to ensure that we don't add a regression here.

I fixed #14825 using a different approach. I included 'order by' in the query, ensuring no alteration to note functionality. Also the "notes-only mode returns one card from each note" test is passed now.

File: AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt [hunk 1]
```diff
@@ -409,11 +409,12 @@ open class Collection(
...
     /** Return a list of card ids  */
     @RustCleanup("Remove in V16.") // Not in libAnki
-    fun findOneCardByNote(query: String): List<CardId> {
+    fun findOneCardByNote(query: String, order: SortOrder): List<CardId> {
         // This function shouldn't exist and CardBrowser should be modified to use Notes,
         // so not much effort was expended here
 
-        val noteIds = findNotes(query, SortOrder.NoOrdering())
+        val noteIds = findNotes(query, order)
+        val cardIds = findCards(query, order)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt:417]: I know we're getting rid of this soon, but this change could be faster: return `[(cid, nid)]` from the SQL, order the list by the index of `nid` in the search results (probably converted to a `Map<>` for speed), then return `cid`

That removes what I suspect to be an expensive `ORDER BY` in the SQL, and an unnecessary call to `findCards`

File: AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt [hunk 2]
```diff
@@ -409,24 +409,40 @@ open class Collection(
...
+        cursor.use { cur ->
+            while (cur.moveToNext()) {
+                val id = cur.getLong(cur.getColumnIndex("id"))
+                val nid = cur.getLong(cur.getColumnIndex("nid"))
+                resultList.add(Pair(id, nid))
+            }
+        }
+
+        // sort resultList by nid
+        val sortedResultList = resultList.sortedBy { noteIds.indexOf(it.second) }
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt:442]: This feels O(n^2 log n) (`n log n` sort * `n` for the IndexOf)

Kotlin might be doing something smart here, but I'd prefer something along the lines of (untested):

```kotlin
        val noteIdMap = noteIds.mapIndexed { index, id -> id to index }.toMap()
        val sortedResultList = resultList.sortedBy { noteIdMap[it.second] }
```

File: AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt [hunk 3]
```diff
@@ -409,24 +409,40 @@ open class Collection(
...
+    FROM (
+      SELECT nid, MIN(ord) AS ord
+      FROM cards
+      WHERE nid IN ${Utils.ids2str(noteIds)} 
+      GROUP BY nid
+    ) AS card_with_min_ord
+    JOIN cards AS c ON card_with_min_ord.nid = c.nid AND card_with_min_ord.ord = c.ord
             """.trimMargin()
         )
+        val resultList = mutableListOf<Pair<Long, Long>>()
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt:431]: Optional: slightly nicer with a data class

```kotlin
        data class CardIdToNoteId(val id: Long, val nid: Long)
```

File: AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt [hunk 4]
```diff
@@ -749,6 +749,35 @@ class CardBrowserTest : RobolectricTest() {
...
     }
 
+    /** PR #14859  */
+    @Test
+    fun checkDisplayOrderAfterTogglingCardsToNotes() {
+        // Start the Card Browser with Basic Model
+        ensureCollectionLoadIsSynchronous()
+        var cardBrowserController = Robolectric.buildActivity(CardBrowser::class.java, Intent())
+            .create().start().resume().visible()
+        saveControllerForCleanup(cardBrowserController)
```
Comment (david-allison) [inline AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt:759]: This would be much cleaner using more modern Kotlin:

```
browserWithNoNewCards.apply {
```

File: AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt (hunk 2 above)
Comment (peyman79) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt]: You're right. I tested it out, and it worked fine.

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt [hunk 5]
```diff
@@ -267,21 +267,25 @@ open class CardBrowser :
...
                 }
             }
             getColUnsafe.config.set("sortBackwards", mOrderAsc)
+            getColUnsafe.config.set("browserNoteSortBackwards", mOrderAsc)
             searchCards()
         } else if (which != CARD_ORDER_NONE) {
             // if the same element is selected again, reverse the order
             mOrderAsc = !mOrderAsc
             getColUnsafe.config.set("sortBackwards", mOrderAsc)
+            getColUnsafe.config.set("browserNoteSortBackwards", mOrderAsc)
```
[the remark this answers is not in the document]
Comment (peyman79) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt:270]: I can't understand what you mean. Could you please explain it more?

[the remark this answers is not in the document]
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt:270]: You've introduced a new config variable to the code (which is valid)

It's useful to provide a source to where the variable came from (whether it's AnkiDroid specific or used in Anki Desktop)

If this is added to the commit message, it saves time when people are looking through the git log

**Review by mikehardy — APPROVED** [review]
Nice! Thanks for fixing this
