### PR TITLE
fix: Add validation for empty note type name

### LINKED ISSUE #20476: Adding a note type with empty name causes infinite processing state, pressing back creates a nameless note type
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Open AnkiDroid
2. Go to Settings --> Manage note types
3. Tap + to add a new note type
4. Clear the Name field completely and add an empty space
5. Tap OK
6. App enters infinite processing state
7. Press the back button
8. Observe note type list

### Expected behaviour

Whitespace-only input should be treated as empty. The OK button should 
be disabled OR a validation error should be shown like "Name cannot be empty". 
No processing should begin. Pressing back should not create any note type.

### Debug info

```text
AnkiDroid Version = 2.23.3 (9001068fd4819c6fb66cb8239e7166868ab47859)  
Backend Version = 0.1.62-anki25.09.2 (25.09.2 3890e12c9e48c028c3f12aa58cb64bd9f8895e30)  
Android Version = 16 (SDK 36)  
ProductFlavor = full  
Device Info = Google | google | tokay | tokay | Pixel 9 | tokay  
Webview User Agent = Mozilla/5.0 (Linux; Android 16; Pixel 9 Build/CP1A.260305.018; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/145.0.7632.159 Mobile Safari/537.36  
ACRA UUID = ac8e8176-3cbf-4e47-9620-a6ef58bafa6f  
FSRS = 5.1.0 (Enabled: false)  
Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

Doesn't stop processing:
Image

Makes a note with empty name:

Image

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by chaitanyamedidar**
## Purpose / Description
Added a validation in creating new note type, that disables OK button, if the input is empty.

## Fixes
Fixes #20476 

## Approach
1. Disabling the OK button for whitespace-only names : Previously, the `addTextChangedListener` only checked if the input was not empty. Since a string of spaces (like "   ") is technically not empty, the app would enable the OK button. By adding `.trim()` inside the listener, we strip away all leading and trailing spaces. If the user only types spaces, `trim()` reduces it to an empty string (""), which fails the `isNotEmpty()` check and keeps the OK button correctly disabled.

2. Guarding the Note Type creation : When the OK button is actually clicked, we fetch the text and apply `.trim()` again

## How Has This Been Tested?

Built the app on my physical device:
1. Go to Manage Note Type
2. Click on '+' to add a new note
3. Try adding a note with whitespace-only name

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by chaitanyamedidar** [comment]
@david-allison yes currently I'm also adding validation for renaming the note, then add a test for both. Works?

**Comment by chaitanyamedidar** [comment]
@david-allison waiting for your feedback

File: AnkiDroid/src/test/java/com/ichi2/anki/notetype/AddNewNotesTypeTest.kt [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+import org.robolectric.shadows.ShadowDialog
+import org.robolectric.shadows.ShadowLooper
+
+@RunWith(AndroidJUnit4::class)
+class AddNewNotesTypeTest : RobolectricTest() {
+    private lateinit var activityScenario: ActivityScenario<ManageNotetypes>
+
+    override fun setUp() {
+        super.setUp()
+        ensureCollectionLoadIsSynchronous()
```
Comment (david-allison) [inline AnkiDroid/src/test/java/com/ichi2/anki/notetype/AddNewNotesTypeTest.kt]: consider `startRegularActivity`

File: AnkiDroid/src/test/java/com/ichi2/anki/notetype/ManageNotetypesTest.kt [hunk 2]
```diff
@@ -0,0 +1,86 @@
...
+            activityScenario.onActivity { activity ->
+                val firstNoteType =
+                    activity.viewModel.state.value.noteTypes
+                        .first { it.name == TEST_NOTE_TYPE_NAME }
+                // renameNotetype is private, so we invoke it via reflection
+                val method: Method =
+                    ManageNotetypes::class.java.getDeclaredMethod(
+                        "renameNotetype",
+                        NoteTypeItemState::class.java,
+                    )
```
Comment (david-allison) [inline AnkiDroid/src/test/java/com/ichi2/anki/notetype/ManageNotetypesTest.kt]: make it `@VisibleForTesting`

File: AnkiDroid/src/test/java/com/ichi2/anki/notetype/AddNewNotesTypeTest.kt (hunk 1 above)
Comment (chaitanyamedidar) [reply AnkiDroid/src/test/java/com/ichi2/anki/notetype/AddNewNotesTypeTest.kt]: Done, thank you for this tip!
Switched to `startRegularActivity` to rely on the base class's automatic memory cleanup

Comment (chaitanyamedidar) [reply AnkiDroid/src/test/java/com/ichi2/anki/notetype/AddNewNotesTypeTest.kt]: Didn't realise that `ActivityScenario` could lead to memory leaks in case left open
Is there anything else I should be taking under consideration for next time?

File: .vscode/settings.json [hunk 3]
```diff
@@ -0,0 +1,3 @@
+{
+    "java.compile.nullAnalysis.mode": "disabled"
```
Comment (david-allison) [inline .vscode/settings.json]: ?

File: AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt [hunk 4]
```diff
@@ -236,17 +245,19 @@ class ManageNotetypes : AnkiActivity(R.layout.activity_manage_note_types) {
...
+                            dialog.positiveButton.isEnabled = currentName.isNotEmpty() && isNotADuplicate
                         },
                     )
             // start with the button disabled as dialog shows the initial name
             dialog.positiveButton.isEnabled = false
         }
     }
 
-    private fun deleteNotetype(state: NoteTypeItemState) {
+    @VisibleForTesting(otherwise = PRIVATE)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt]: I believe `PRIVATE` is the default value and can be omitted

File: AnkiDroid/src/test/java/com/ichi2/anki/notetype/AddNewNotesTypeTest.kt [hunk 5]
```diff
@@ -0,0 +1,65 @@
...
+import org.junit.Test
+import org.junit.runner.RunWith
+import org.robolectric.shadows.ShadowDialog
+import org.robolectric.shadows.ShadowLooper
+
+@RunWith(AndroidJUnit4::class)
+class AddNewNotesTypeTest : RobolectricTest() {
+    override fun setUp() {
+        super.setUp()
+        ensureCollectionLoadIsSynchronous()
```
Comment (david-allison) [inline AnkiDroid/src/test/java/com/ichi2/anki/notetype/AddNewNotesTypeTest.kt]: This also shouldn't be necessary, as it's handled inside `startRegularActivity

File: AnkiDroid/src/test/java/com/ichi2/anki/notetype/ManageNotetypesTest.kt [hunk 6]
```diff
@@ -0,0 +1,69 @@
...
+import org.junit.runner.RunWith
+import org.robolectric.shadows.ShadowDialog
+import org.robolectric.shadows.ShadowLooper
+
+@RunWith(AndroidJUnit4::class)
+class ManageNotetypesTest : RobolectricTest() {
+    override fun setUp() {
+        super.setUp()
+        ensureCollectionLoadIsSynchronous()
+        addStandardNoteType(TEST_NOTE_TYPE_NAME, arrayOf("front", "back"), "", "")
```
Comment (david-allison) [inline AnkiDroid/src/test/java/com/ichi2/anki/notetype/ManageNotetypesTest.kt]: move this to the test itself

File: AnkiDroid/src/test/java/com/ichi2/anki/notetype/ManageNotetypesTest.kt [hunk 7]
```diff
@@ -0,0 +1,69 @@
...
+import org.junit.Test
+import org.junit.runner.RunWith
+import org.robolectric.shadows.ShadowDialog
+import org.robolectric.shadows.ShadowLooper
+
+@RunWith(AndroidJUnit4::class)
+class ManageNotetypesTest : RobolectricTest() {
+    override fun setUp() {
+        super.setUp()
+        ensureCollectionLoadIsSynchronous()
```
Comment (david-allison) [inline AnkiDroid/src/test/java/com/ichi2/anki/notetype/ManageNotetypesTest.kt]: remove this, not necessary

File: .vscode/settings.json (hunk 3 above)
Comment (chaitanyamedidar) [reply .vscode/settings.json]: That was supposed to stay untracked, sorry for this

**Comment by chaitanyamedidar** [comment]
@david-allison could you please check it now

**Review by david-allison — APPROVED** [review]
Looks awesome, thanks!

This would be merged a little faster if you squash merged the commits, we typically rebase here, so we don't want 'fixup' commits in the history

**Comment by chaitanyamedidar** [comment]
> Looks awesome, thanks!
> 
> This would be merged a little faster if you squash merged the commits, we typically rebase here, so we don't want 'fixup' commits in the history

Works!

**Comment by chaitanyamedidar** [comment]
Hey @david-allison , sorry for the delay
Additionally tag and subdeck need a validation layer too, @ZornHadNoChoice mentioned it in this issue #20476 itself
I was thinking of creating a separate PR so it would be documented properly since this PR was focused for only note type, what do you think?

**Comment by david-allison** [comment]
Check on the issue, there's a lot of duplicate work going on with these 'Good first issue'

**Comment by chaitanyamedidar** [comment]
Now that I see the files it is fixed, all good from my side
Back to hunting other bugs

**Comment by lukstbit** [comment]
@chaitanyamedidar Could you please rebase your changes on top of the main branch? Right now there's a lot of code which is unrelated to the issue and it's hard to see what was done.

**Comment by chaitanyamedidar** [comment]
Okay, doing it

**Comment by chaitanyamedidar** [comment]
this commit contains only the changes I did, could you check it now @lukstbit
