### PR TITLE
fix onBackPressed  deprecation of CardTemplateEditor

### LINKED ISSUE #14558: Handle ~~"predictive back"~~ ActivityTransitionAnimation deprecation in API34
> [!IMPORTANT]
> This issue is to be included in a research study, and should not be worked on

API34 adds new predictive back behavior, which implies that the transition animation overrides for activity stack change animations now need to know whether the animation override is for activity open or close, whereas we override both as a unit without thought

This needs a solution before the deprecated methods go away, likely in the form of plumbing through (via a new parameter) the idea of whether the call site intended to override open, close, or both animations. For backwards compatibility this will likely need to be a Compat interface (or interfaces) to replace the current implementation

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/pull/14556#discussion_r1364530599_

### PR DESCRIPTION
**Pull request by Prince-kushwaha**
## Purpose / Description
fix onBackPressed  deprecation of CardTemplateEditor

## Fixes
* Fixes #14558

## How Has This Been Tested?
Physical Device

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by lukstbit — CHANGES_REQUESTED** [review]
This looks good. 

One extra thing left over is a call in CardTemplateEditor's _onOptionsItemSelected()_method to the deprecated _onBackPressed()_ that should be replaced with:

_onBackPressedDispatcher.onBackPressed()_

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt [hunk 1]
```diff
@@ -230,20 +238,10 @@ open class CardTemplateEditor :
...
-    @Deprecated("Deprecated in Java")
-    override fun onBackPressed() {
-        if (modelHasChanged()) {
-            showDiscardChangesDialog()
-        } else {
-            super.onBackPressed()
-        }
-    }
-
     @Suppress("DEPRECATION")
```
Comment (lukstbit) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt:241]: Also remove the annotation, the deprecation was fixed.

**Review by lukstbit — CHANGES_REQUESTED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt [hunk 2]
```diff
@@ -970,6 +968,7 @@ open class CardTemplateEditor :
             }
             templateEditor.tempModel = null
             templateEditor.finish()
+            templateEditor.onBackPressedCallback.isEnabled = false
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt:971]: Is this necessary?

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt [hunk 3]
```diff
@@ -132,6 +133,12 @@ open class CardTemplateEditor :
      * This occurs when the view is big enough.
      */
     private var fragmented = false
+    val onBackPressedCallback =
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt:136]: I'd rename to describe what the callback does: `displayDiscardChangesCallback`

**Review by david-allison — APPROVED** [review]
Looks great, cheers!

**Review by lukstbit — APPROVED** [review]
LGTM, thanks for making the changes.
