### PR TITLE
Fix study finish snackbar not appearing in tablet mode

### LINKED ISSUE #19126: Congratulations snackbar doesn't show up after finishing a deck on Tablets
**Reproduction steps**

1. Open a deck
2. Answer all the cards
3. See the "Congratulations" snackbar after finishing the deck

**Expected result**

The snackbar should appear, but it doesn't.

Only happens if the deck picker is "fragmented"

**Debug info**

```text
AnkiDroid Version = 2.23.0alpha2-debug (efc2ec9e176c088a18ed59394acc638cbf9f2e88)  
Backend Version = 0.1.60-anki25.07.5 (25.07.5 7172b2d26684c7ef9d10e249bd43dc5bf73ae00c)  
Android Version = 14 (SDK 34)  
ProductFlavor = full  
Device Info = Google | google | emu64xa | sdk_gphone64_x86_64 | sdk_gphone64_x86_64 | ranchu  
Webview User Agent = Mozilla/5.0 (Linux; Android 14; sdk_gphone64_x86_64 Build/UE1A.230829.050; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/113.0.5672.136 Safari/537.36  
ACRA UUID = c0c3d9c4-eb7b-4d1a-ad83-cb18b6f4e49b  
FSRS = 4.1.1 (Enabled: false)  
Crash Reports Enabled = false
```

### PR DESCRIPTION
**Pull request by lukstbit**
## Purpose / Description

Fixes the linked issue by making StudyOptionsFragment to delegate(through a fragment result) the interaction with the reviewer to its parent activity. This way  DeckPicker can use its own code to handle the study finish when in fragmented mode.

Note: I plan to make more changes to StudyOptionsFragment, it's too complicated for what it's doing.

## Fixes
* Fixes #19126

## How Has This Been Tested?

Ran the tests, checked the behavior in portrait and tablet mode.

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.kt [hunk 1]
```diff
@@ -61,6 +62,14 @@ class StudyOptionsActivity :
                     currentFragment!!.refreshInterface()
             }
         }
+        setFragmentResultListener(StudyOptionsFragment.REQUEST_STUDY_OPTIONS_STUDY) { _, _ ->
+            Timber.d("Opening study screen from study options screen")
+            val reviewer = Reviewer.getIntent(this)
+            // go back to DeckPicker after studying when not in tablet mode
+            reviewer.flags = Intent.FLAG_ACTIVITY_FORWARD_RESULT
+            startActivity(reviewer)
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.kt:70]: that's a nice one

**Review by mikehardy — APPROVED** [review]
LGreatTM - big red diff
