### PR TITLE
Fix #5715: Hide style/script tag content in deck description

### LINKED ISSUE #5715: In deck description, ignore what is in style and script tag
###### Reproduction Steps

1. Set deck description to `<script>a=1</script>`
2. View deck description

###### Expected Result

Deck description should be blank, instead of `a=1`

###### Actual Result
Deck description is shown as `a=1`. Only `<script>` and `</script>` gets removed

###### Debug info
AnkiDroid Version = 2.9.2beta4

Android Version = 4.4.2

ACRA UUID = 34141f01-867f-4ea4-9f19-6625973b167e

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description

Previously, the android libraries handled converting most HTML into a `Spanned`, but `<script>` and `<style>` displayed their inner text as a string.

## Fixes
Fixes #5715

## Approach
Now, we Regex replace the two tags out of the HTML before we use the Android libraries to convert the string into a `Spanned`.

This removes the tags and their content to provide a better description.

## How Has This Been Tested?

* Unit Tested

----

* Tested on my local Android against the test string: `a<script>a=1</script>a <span style="color:red">red</span>`

Result: As expected

## Learning (optional, can help others)

It's likely that we don't need pure HTML parsing for this and we can reuse the converted regex from Anki Desktop. A `<script>` can't contain `</script>` in a string: https://stackoverflow.com/a/22488867.

## Checklist

- [ x ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ x ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ x ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ x ] You have commented your code, particularly in hard-to-understand areas
- [ x ] You have performed a self-review of your own code

### CODE REVIEW

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/StudyOptionsFragmentTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5175499&bid=16988036)

File: AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java [hunk 1]
```diff
@@ -686,6 +688,13 @@ public void run() {
         };
     }
 
+    static Spanned formatDescription(String desc) {
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java]: Codacy Issue found: [Avoid reassigning parameters such as 'desc'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5175499)

Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.java]: Codacy Issue found: [Use explicit scoping instead of the default package private level](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5175499)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/StudyOptionsFragmentTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5175499&bid=16988036)
