### PR TITLE
fix: "Undo" tooltip doesn't show its target

### LINKED ISSUE #18904: "Undo" tooltip doesn't show its target
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Show "Undo" action button on the action bar in the current Study screen
2. Answer a card
3. Long press the undo action button

**Result**
The tooltip just says `Undo`:

Image

### Expected behaviour

The tooltip says `Undo Answer Card` just as the undo action's label in the overflow menu does so:

Image

### Debug info

```text
AnkiDroid Version = 2.22alpha4 (f8cb45e5dafc5c8a0aecaca033927878fcd72bcb)  
Backend Version = 0.1.58-anki25.07.2 (25.07.2 3adcf05ca6d00b32938f439b3e5fc71786b21c26)  
Android Version = 11 (SDK 30)  
ProductFlavor = full  
Device Info = OPPO | OPPO | OP4BAFL1 | CPH2013 | CPH2013 | qcom  
Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/138.0.7204.67 Mobile Safari/537.36  
ACRA UUID = dae56c60-345e-41f3-a616-f02ce05cd8ad  
FSRS = 4.1.1 (Enabled: false)  
Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

The same goes for the other undo targets, for example:

- `Undo Bury`
- `Undo Change Deck`
- `Undo Update Note` 
- and `Undo Stroke` on whiteboard mode

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by snowtimeglass**
## Purpose / Description

Even when Undo is available (i.e., Undo action has its target), the undo action's tooltip just shows `Undo`
in contrast to the label in the overflow menu:

e.g.,
- `Undo Answer Card`
- `Undo Bury`
- `Undo Change Deck`
- `Undo Update Note` 
-  and `Undo Stroke` on whiteboard mode

This PR aims to resolve the inconvenience/inconsistency.

## Fixes
* Fixes #18904

## Approach
Set the the undo action's title to the tooltip after the title is determined.

## How Has This Been Tested?

Checked on a physical device (Android 11)

https://github.com/user-attachments/assets/dbb29889-8fd5-4be3-996a-d7ca61d70703

- Additionally checked the same operations with placing the undo action in the overflow menu. No unexpected results occurred.

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt [hunk 1]
```diff
@@ -864,7 +865,8 @@ open class Reviewer :
                 whiteboard?.reviewerEraserModeIsToggledOn = isEraserMode
 
                 if (getColUnsafe.undoAvailable()) {
-                    //  e.g. Undo Bury, Undo Change Deck, Undo Update Note
+                    // Make the Undo action title to "Undo blah-blah" style:
+                    //  e.g., Undo Answer Card, Undo Bury, Undo Change Deck, Undo Update Note
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt]:
```suggestion
                    // set the undo title to a named action ('Undo Answer Card' etc...)
```

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt [hunk 2]
```diff
@@ -874,6 +876,18 @@ open class Reviewer :
...
+            /*
+             * For Undo button's tooltip
+             */
+            val actionBarShowingUndoButton = undoIcon.actionView
+            // Check if Undo button is shown on Action bar
+            if (actionBarShowingUndoButton != null) {
+                // Set the Undo button's tooltip
+                // according to the Undo action's title selected in the above steps
+                TooltipCompat.setTooltipText(actionBarShowingUndoButton, undoIcon.title)
+            }
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt]:
```suggestion
            // Set the undo tooltip, only if the icon is shown in the action bar
            undoIcon.actionView?.let { undoView ->
                TooltipCompat.setTooltipText(undoView, undoIcon.title)
            }
```

Comment (snowtimeglass) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt:889]: Thank you for your review and the refinements!

**Comment by snowtimeglass** [comment]
Thank you for your review and the refinements! The PR has been changed as suggested.

**Comment by david-allison** [comment]
Let me fix this up, issue on our side

**Review by lukstbit — APPROVED** [review]
Thanks!
