### PR TITLE
Make undo button work in StudyOptions

### LINKED ISSUE #12277: [Bug] an invalid "Undo" button appears on Deck Overview screen
###### Reproduction Steps

0. (Close AnkiDroid, and restart it)
1. Tap any of the decks on "Decks" screen
2. Tap "SHOW ANSWER"
3. Tap any of the answer buttons
4. Go back to "Decks" screen
5. Tap the deck counts area of the deck (the right side area of the deck's row)
image
6. Tap "Undo" button
image
  _Note: If you tap the deck counts area of the deck before the step 1 above, you can confirm that the "undo" button doesn't exist._
image

###### Expected Result
The review above gets undone.
image

###### Actual Result
Nothing happens.  The button doesn't respond when tapped (except for its ripple effect).
image

###### Video
https://user-images.githubusercontent.com/10436072/187922084-a1c27361-300a-4f25-ab71-c65bea67959d.mp4

###### Debug info
```
AnkiDroid Version = 2.16alpha82

Android Version = 10

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; CPH2013 Build/QKQ1.200209.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/80.0.3987.99 Mobile Safari/537.36

ACRA UUID = 69410480-0b9c-401f-ae8d-94da0f29c9dc

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
#11220 seems to be a part of this issue.
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by alyoshenka**
## Purpose / Description

The Undo button in `StudyOptionsFragment` does not work. This issue occurred after creating `RTLActionProvider`, which allows icons to be mirrored for right-to-left languages. This fix makes this undo button work as expected. However, it still does not allow the user to undo the last card in a deck from `StudyOptions`. 

## Fixes

Fixes #12277, I wouldn't say "fixes" because I know this is not an ideal code change. **[Edit: I'm saying it fixes it - Mike H]**

## Approach

I struggled to fix this problem for a long time, and finally threw in the towel on being able to solve it "correctly". I understand my code is not exactly desirable, but I wanted to share my findings and the things I tried to help save others time if they make a cleaner fix in the future.

The Undo button is inflated from `StudyOptionsFragment`, which is hosted by `StudyOptionsActivity`. `RTLActionProvider` takes in an Activity. So, when the Undo button is pressed, `RTLActionProvider` calls `onOptionsItemSelected` on `StudyOptionsActivity`. This doesn't do anything, because the activity has no knowledge of the options in its fragment. All other uses of `RTL...` use Activities, which is why they work as expected.

Changing `RTLActionProvider` to instead use a Fragment is not trivial, because Frags aren't aware of Context.

It was suggested to use `MenuHost/MenuProvider` to redo the menu/actions system. I struggled with this because the menu in `StudyOptionsFragment` uses a `Toolbar` and I couldn't figure out how to set up the actions correctly with `MH/MP` instead (Due to my own skill level). It seemed to me like that would still not solve the underlying issue, though perhaps if the `SOActivity` and `SOFragment` menus were coupled in this way it would work. I struggled finding resources on it because it is a relatively new feature.

My approach here is the simple and "hacky" one: Just make the Activity call the method on the Fragment when it detects an options item click. This feels like bad encapsulation: the Activity shouldn't call down the chain to a function on the Fragment. However I could be wrong here.

## How Has This Been Tested?

- [x] Jacoco Unit Tests
- [x] KTLint checks

1. Open a deck
2. Review any number of cards (except ALL cards)
3. Navigate back to DeckPicker
4. Use the three numbers to the right of the deck name to open StudyOptions
5. Tapping undo button in top menu undoes the last card review, and returns to the Reviewer on that same card

studyoptions_undo

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] ~UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)~
- [x] ~UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)~

### CODE REVIEW

**Comment by criticalAY** [comment]
I am not sure if it's the right solution or not. But wouldn't there be a NPE if the fragment gets detached from the activity(I may be wrong though here in the case above)

**Comment by alyoshenka** [comment]
Not in this case, the `?` protects against that.

**Comment by lukstbit** [comment]
Thank you for taking time to look into this and providing the valuable info. Your code works but I think it's better to avoid the connection to the activity when the code relates to the fragment. We could do this by making RtlCompliantActionProvider to accept a custom handler for menu item click and then supplying a proper handler in StudyOptionsFragment:

```
// in RtlCompliantActionProvider
/**
 * The action to perform when clicking the associated menu item. By default this delegates to
 * the activity's [Activity.onOptionsItemSelected] callback, but a custom action can be set and
 * used instead.
 */
var clickHandler: (Activity, MenuItem) -> Unit = { activity, menuItem ->
    activity.onOptionsItemSelected(menuItem)
}

override fun onCreateActionView(forItem: MenuItem): View {
    ...
    actionView.setOnClickListener {
        if (!forItem.isEnabled) {
            return@setOnClickListener
        }
        clickHandler(mActivity, forItem)
    }
```

This doesn't produce any change to the activities using the action provider, but it would allow us to fix StudyOptionsFragment:

```
private fun configureToolbarInternal(recur: Boolean) {
   ....
   // Switch on or off undo depending on whether undo is available, also sets the proper
  // click target for its ActionProvider
  val undoActionProvider: RtlCompliantActionProvider? = MenuItemCompat.getActionProvider(
      menu.findItem(R.id.action_undo)
  ) as? RtlCompliantActionProvider
  undoActionProvider?.clickHandler = { _, menuItem -> onMenuItemClick(menuItem) }
  if (col == null || !col!!.undoAvailable()) {
```

**Comment by oakkitten** [comment]
Why are we using `RtlCompliantActionProvider` instead of automirrored icons? Maybe make icons automirrored, where appropriate, and remove this clutch?

**Comment by lukstbit** [comment]
@oakkitten Code that already existed and the simplest is to add things on top of it. I wouldn't mind to review a simple PR which removes RtlCompliantActionProvider.

**Comment by oakkitten** [comment]
From [the PR that introduced this](https://github.com/ankidroid/Anki-Android/pull/8261#discussion_r598947527):

> If to undo menu item can/should be shown in the toolbar, its action view should be visible. The default action view is `ActionMenuItemView` which is an internal class in the Android API visible only to the SDK itself. When the icon supplied to `ActionMenuItemView` does have `autoMirrored = true`, it does ignore it and lay the image without mirroring in the case of RTL locals.

> When I looked into `ActionMenuItemView` I found there is no image view at all, the only view is a text view used to do everything. I'm not sure, but I think to `autoMirrored` to work it needs an image view.

**Comment by alyoshenka** [comment]
> Thank you for taking time to look into this and providing the valuable info. Your code works but I think it's better to avoid the connection to the activity when the code relates to the fragment. We could do this by making RtlCompliantActionProvider to accept a custom handler for menu item click and then supplying a proper handler in StudyOptionsFragment:
> 
> ```
> // in RtlCompliantActionProvider
> /**
>  * The action to perform when clicking the associated menu item. By default this delegates to
>  * the activity's [Activity.onOptionsItemSelected] callback, but a custom action can be set and
>  * used instead.
>  */
> var clickHandler: (Activity, MenuItem) -> Unit = { activity, menuItem ->
>     activity.onOptionsItemSelected(menuItem)
> }
> 
> override fun onCreateActionView(forItem: MenuItem): View {
>     ...
>     actionView.setOnClickListener {
>         if (!forItem.isEnabled) {
>             return@setOnClickListener
>         }
>         clickHandler(mActivity, forItem)
>     }
> ```
> 
> This doesn't produce any change to the activities using the action provider, but it would allow us to fix StudyOptionsFragment:
> 
> ```
> private fun configureToolbarInternal(recur: Boolean) {
>    ....
>    // Switch on or off undo depending on whether undo is available, also sets the proper
>   // click target for its ActionProvider
>   val undoActionProvider: RtlCompliantActionProvider? = MenuItemCompat.getActionProvider(
>       menu.findItem(R.id.action_undo)
>   ) as? RtlCompliantActionProvider
>   undoActionProvider?.clickHandler = { _, menuItem -> onMenuItemClick(menuItem) }
>   if (col == null || !col!!.undoAvailable()) {
> ```

Got it, that's a great idea! I'll work on it. Thanks!

**Comment by alyoshenka** [comment]
working_undo_final

I suppose there should also be a toast saying 'Undone "last review"' on this screen as well.

File: AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.kt [hunk 1]
```diff
@@ -60,10 +60,6 @@ class StudyOptionsActivity : NavigationDrawerActivity(), StudyOptionsListener, C
         if (drawerToggle.onOptionsItemSelected(item)) {
             return true
         }
-        if (item.itemId == android.R.id.home) {
```
Comment (lukstbit) [inline AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.kt:63]: This block of code shouldn't be deleted.

**Review by lukstbit — CHANGES_REQUESTED** [review]
As the undo button in StudyOptionsFragment returns to the undone review, I think we don't need the toast.

File: AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.kt (hunk 1 above)
Comment (alyoshenka) [reply AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.kt:63]: Whoops! Thanks for the catch, I accidentally deleted that along with some of my unneeded changes.

**Review by lukstbit — APPROVED** [review]
Approved, thanks.

I also restarted the failing check. It's important to verify locally that tests pass, if  in the CI there's a failure for one of the platforms then it's most likely a flaky test. You can close and reopen the PR to make all checks to run again, but this isn't necessary a reviewer will look at the checks and see it's flaky and rerun it or ignore it.

**Review by mikehardy — APPROVED** [review]
Nice!
