### PR TITLE
fix: unexpected reviewer highlights with keyboard

### LINKED ISSUE #14142: [BUG]: Screen is unexpectedly highlighted with gamepad's UI navigation when answering cards
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Connect a gamepad (I have only tested Bluetooth controllers);
2. Make sure you have set controls to answer cards on AnkiDroid's settings;
3. Review a deck: answer with the buttons you have assigned;
4. After the first answer, the whole screen will have a highlight from Android's gamepad UI navigation.

NOTE: I cannot reproduce this issue with ALL keybindings I set for answering cards, but I tested setting only one button and also setting multiple buttons. Sometimes, reassigning them will cause another keybinding to cause the issue.
I tested face buttons, shoulder buttons, d-pad, and start, in different order of assignments. I couldn't find the steps to reproduce the issue with a particular button, but at least one of them will cause this issue; from my experience, this happens a lot with the d-pad and face buttons.

### Expected behaviour

A new card should appear without highlighting from gamepad's UI navigation.

### Actual behaviour

A new card appears, but the screen is highlighted as a UI element.

### Debug info

```text
AnkiDroid Version = 2.16.0beta5

Android Version = 13

ProductFlavor = play

Manufacturer = motorola

Model = motorola edge 30

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; motorola edge 30 Build/T1RDS33.116-33-3-2; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.196 Mobile Safari/537.36

ACRA UUID = 69ebb9c6-295d-4aa8-9fda-2bca62a28367

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

Video showcasing the issue:
https://github.com/ankidroid/Anki-Android/assets/27153776/afdf99d4-60e2-4c8f-8b91-171f1f571a8d
This was reproduced using the d-pad down button. This usually happens with face buttons as well (I recently managed to make the A button not trigger this issue).

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
The Reviewer window was fully highlighted if using the keyboard to answer a card using 'space'

## Fixes
* Fixes #14142

## Approach
We use `android:colorControlHighlight` to remove this

## How Has This Been Tested?
Briefly tested on my S21 and I saw no UI regressions (Standard reviewer configuration)
⚠️ This is high risk for UI regressions

Also tested in dark mode

## Learning (optional, can help others)
Learning for others: themes are additive

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison** [comment]
> Execution failed for task ':AnkiDroid:mergePlayDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
   > AAPT2 aapt2-8.0.2-9289358-windows Daemon #0: Daemon startup failed
     Please check if you installed the Windows Universal C Runtime.
     This should not happen under normal circumstances, please file an issue if it does.


Looks like a flake: https://github.com/ankidroid/Anki-Android/actions/runs/5861817398/job/15892572084?pr=14231

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt [hunk 1]
```diff
@@ -536,6 +536,7 @@ abstract class AbstractFlashcardViewer :
         restorePreferences()
         mTagsDialogFactory = TagsDialogFactory(this).attachToActivity<TagsDialogFactory>(this)
         super.onCreate(savedInstanceState)
+        this.setTheme(R.style.ThemeOverlay_DisableKeyboardHighlight)
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt:539]: Please add a comment in the code explaining why this is being done.

I believe that this is a problem with the reviewer layout, which has a whole screen element that can be focused with the keyboard `Tab` navigation. But that messy, if I can say so, layout can be untangled later

**Review by BrayanDSO — APPROVED** [review]
Only asked for a comment. LGTM

**Comment by david-allison** [comment]
Comment added. I'd strongly support a better solution. I had a few tries and got nowhere.

**Review by mikehardy — APPROVED** [review]
I don't see myself untangling this further at the moment, if there are regressions the risk has been noted, we can work through them or revert
