### PR TITLE
Fix: DeckPicker-NullPointerException in onQueryTextChange

### LINKED ISSUE #17391: DeckPicker: `onQueryTextChange` - `NullPointerException` on `filter`
https://ankidroid.org/acra/app/1/bug/253121/report/f6ecbbf9-859d-40bb-b281-acbd2572d01a

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Filter.filter(java.lang.CharSequence)' on a null object reference
	at com.ichi2.anki.DeckPicker$setupSearchIcon$2$1.onQueryTextChange(DeckPicker.java:932)
	at androidx.appcompat.widget.SearchView.onTextChanged(SearchView.java:1198)
	at androidx.appcompat.widget.SearchView$10.onTextChanged(SearchView.java:1736)
	at android.widget.TextView.sendOnTextChanged(TextView.java:13051)
	at android.widget.TextView.setText(TextView.java:7784)
	at android.widget.TextView.setText(TextView.java:7596)
	at android.widget.EditText.setText(EditText.java:233)
	at android.widget.TextView.setText(TextView.java:7533)
	at androidx.appcompat.widget.SearchView.onActionViewExpanded(SearchView.java:1312)
	at androidx.appcompat.widget.Toolbar$ExpandedActionViewMenuPresenter.expandItemActionView(Toolbar.java:2748)
	at androidx.appcompat.view.menu.MenuBuilder.expandItemActionView(MenuBuilder.java:1363)
	at androidx.appcompat.view.menu.MenuItemImpl.expandActionView(MenuItemImpl.java:828)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:989)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:974)
	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:620)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:155)
	at android.view.View.performClick(View.java:8037)
	at android.view.View.performClickInternal(View.java:8006)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source)
	at android.view.View$PerformClick.run(View.java:32003)
	at android.os.Handler.handleCallback(Handler.java:996)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:302)
	at android.app.ActivityThread.main(ActivityThread.java:9652)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:601)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1062)

```

### PR DESCRIPTION
**Pull request by Giyutomioka-SS**
## Purpose / Description
Fixes NullPointerException in onQueryTextChange by safely casting the adapter to Filterable before calling the filter method, preventing crashes when the adapter is null or not of the correct type.

## Fixes
* Fixes #17391 

## How Has This Been Tested?
Realme 6 and Emulator

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison** [comment]
Did you manage to reproduce the error?

This seems to convert the crash into a bug

**Comment by Giyutomioka-SS** [comment]
I couldn’t reproduce the crash. Should I add a null check and logging to catch cases where the adapter or filter is unexpectedly null?

**Comment by david-allison** [comment]
We shouldn't rush to a solution

The first step is to understand how the crash occurred, and ideally being able to reproduce it. Once we know this, we'll ideally be able to fix the cause rather than ignore user input

Did you check ACRA for a logcat?

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 1]
```diff
@@ -928,8 +928,8 @@ open class DeckPicker :
                 }
 
                 override fun onQueryTextChange(newText: String): Boolean {
-                    val adapter = recyclerView.adapter as Filterable?
-                    adapter!!.filter.filter(newText)
+                    val adapter = recyclerView.adapter as? Filterable
+                    adapter?.filter?.filter(newText)
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:932]: I think we should add something like `if (adapter == null || adapter.filter == null) { /* some logging */ }`

and some logging should be:
Timber.w of the adapter and adapter.filter null status and type if possible
then a sendExceptionReport saying something like "DeckPicker.onQueryTextChanged with unexpected null adapter. Carefully examine logcat"

I think that's the best we can do at the moment - I can't see how this would ever be null and I was able to exercise the logic myself just not trigger the crash

**Review by mikehardy — CHANGES_REQUESTED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 2]
```diff
@@ -928,8 +928,18 @@ open class DeckPicker :
...
-                    adapter!!.filter.filter(newText)
+                    val adapter = recyclerView.adapter as? Filterable
+                    if (adapter == null || adapter.filter == null) {
+                        Timber.w(
+                            "DeckPicker.onQueryTextChange: adapter is null: %s, filter is null: %s, adapter type: %s",
+                            adapter == null,
+                            adapter?.filter == null,
+                            adapter?.javaClass?.simpleName ?: "Unknown"
+                        )
+                        Timber.e(Exception("DeckPicker.onQueryTextChanged with unexpected null adapter or filter. Carefully examine logcat"))
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:939]: not a Timber.e a sendExceptionReport, so we can see these in ACRA reports and hopefully learn something about them for a real fix

**Review by mikehardy — CHANGES_REQUESTED** [review]
getting closer to something that might move this one forward, but needs to go to our ACRA server for it to be seen

**Review by mikehardy — APPROVED** [review]
That's what I had in mind - doesn't fix the underlying issue but will hopefully get us closer. Thank you

**Comment by mikehardy** [comment]
Going to put this one in as well for 2.19.3, it stops the crash but adds logging and doesn't hide it in acra
