### PR TITLE
Follow proper backstack movement in changelog section

### LINKED ISSUE #8938: [Bug] Custom Tabs back button does not work correctly
###### Reproduction Steps

1. Open Changelog (from settings -> advanced -> at the bottom)
2. Tap on a link in the changelog (for instance our OpenCollective link)
3. Tap back (either the back arrow at top left on my device, or hardware back button

###### Expected Result

You go back to the Changelog (or if you navigated in the 3rd party site, you go back page by page popping the navigation stack)

###### Actual Result

You exit the Changelog entirely

###### Debug info

Source tag v2.15.0

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by ShridharGoel**
## Purpose / Description
Follow proper backstack movement in changelog section.

## Fixes
Fixes #8938 

## Approach
Overridden `onBackPressed()` method to go back in `WebView` if any link has been opened there. Otherwise, go back from the `Open Changelog` section.

## How Has This Been Tested?

Verified the working of the functionality.

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/Info.java [hunk 1]
```diff
@@ -54,6 +54,7 @@
     public static final int TYPE_ABOUT = 0;
     public static final int TYPE_NEW_VERSION = 2;
 
+    WebView mWebView;
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/Info.java:57]:
```suggestion
    private WebView mWebView;
```

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
Looks good, thanks!

**Review by david-allison-1 — APPROVED** [review]
Thanks!

**Review by mikehardy — APPROVED** [review]
nice!

**Comment by mikehardy** [comment]
Ugh I keep rebase merging these and getting a nasty commit history. @ShridharGoel we need to get you trained up on squashing your PR branches and force-pushing them so we can maintain commit history without needing to check for squash merge need :-)
