### PR TITLE
[Modified]: Action buttons for cards changed to OnTouch.

### LINKED ISSUE #4631: Answering right as the auto-advance happens can trigger input for the next card
###### Research
*Enter an [ x ] character to confirm the points below:*

[X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[X] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Ensure your cards auto-advance 
2. Hold down on an answer without lifting your finger
3. the card auto advances
4. lift your finger
5. the new card now has whatever due date type (good, bad, easy, hard) that was meant for the last card.

###### Expected Result
When holding down an answer from a previous card, existing input should be ignored.

###### Actual Result
If a card auto-advances right as you were answering you can get a weird skip effect, where the card you were trying to answer for is failed, the next card senses that you were holding one of the 4 buttons and since you were just lifting your finger as the next card comes in, it is marked with that answer, and moves to the next card.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

### PR DESCRIPTION
**Pull request by shobhi1310**
## Purpose / Description
If a card auto-advances right as you were answering you can get a weird skip effect, where the card you were trying to answer for is failed, the next card senses that you were holding one of the 4 buttons and since you were just lifting your finger as the next card comes in, it is marked with that answer, and moves to the next card.

## Fixes
Fixes #4631 

## Approach
A new function has been created with `OnTouch` listener and `ACTION_DOWN` has been used to save the current instance of card. It will ensure that the options which are chosen for a particular card, the changes will be reflected for that card itself. In the `OnClick` listener the saved card will be compared to the current card, if same only then the required actions are performed.

## How Has This Been Tested?
The work has been tested on physical device (Xiaomi redmi note5 pro).
Steps to test:

1. Ensure your cards auto-advance
2. Hold down on an answer without lifting your finger
3. The card auto advances
4. The action/due date of the card chosen will be applicable for the card on which it was chosen for.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
Implementation looks neat, thanks!

But, as I mentioned in: https://github.com/ankidroid/Anki-Android/issues/4631#issuecomment-810358033

> If possible: save the card on press, and only perform the action if it's the same on release.

We ideally don't want to deviate from how the system handles buttons for the answer buttons

**Comment by shobhi1310** [comment]
If the user keeps button pressed for long or the auto advance time is too less, and what if the user intends to perform an action on the card, as per your comment, the user will not be able to get the intended action as the the point when he releases the button card is not same.

But if we keep `OnTouch` then all the requirements of user are satisfied.

**Comment by david-allison-1** [comment]
> If the user keeps button pressed for long or the auto advance time is too less, and what if the user intends to perform an action on the card, as per your comment, the user will not be able to get the intended action as the the point when he releases the button card is not same.
> 
> But if we keep `OnTouch` then all the requirements of user are satisfied.

That's why I said store a reference to the pressed card, and only perform the action if the card is the same

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 1]
```diff
@@ -434,6 +435,16 @@ public void onClick(View view) {
             displayCardAnswer();
         }
     };
+    private final View.OnTouchListener mGestureEaseHandler = new View.OnTouchListener(){
+
+        @Override
+        public boolean onTouch(View view, MotionEvent event) {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:441]: Just use an `onTouchListener`: combine it with the `OnClickListener` and store `mPrevCard` as a field inside it.

**Review by david-allison-1 — CHANGES_REQUESTED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 2]
```diff
@@ -445,20 +456,22 @@ public void onClick(View view) {
...
-                answerCard(Consts.BUTTON_TWO);
-            } else if (id == R.id.flashcard_layout_ease3) {
-                Timber.i("AbstractFlashcardViewer:: EASE_3 pressed");
-                answerCard(Consts.BUTTON_THREE);
-            } else if (id == R.id.flashcard_layout_ease4) {
-                Timber.i("AbstractFlashcardViewer:: EASE_4 pressed");
-                answerCard(Consts.BUTTON_FOUR);
-            } else {
-                mCurrentEase = 0;
+            if(mPrevCard==mCurrentCard) {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:459]: Spacing - and it's best to invert the if to reduce nesting.

```suggestion
            if (mPrevCard == mCurrentCard) {
```

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 3]
```diff
@@ -189,7 +189,7 @@
 
     /** Maximum time in milliseconds to wait before accepting answer button presses. */
     @VisibleForTesting
-    protected static final int DOUBLE_TAP_IGNORE_THRESHOLD = 200;
+    protected static final int DOUBLE_TAP_IGNORE_THRESHOLD = 50;
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:192]: Why was this changed?

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 4]
```diff
@@ -309,6 +309,7 @@
     private android.content.ClipboardManager mClipboard;
 
     protected Card mCurrentCard;
+//    protected Card mPrevCard;
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:312]: git is our history, no need to leave code commented

```suggestion

```

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 5]
```diff
@@ -435,31 +436,43 @@ public void onClick(View view) {
...
-            } else if (id == R.id.flashcard_layout_ease4) {
-                Timber.i("AbstractFlashcardViewer:: EASE_4 pressed");
-                answerCard(Consts.BUTTON_FOUR);
-            } else {
-                mCurrentEase = 0;
+        public boolean onTouch(View view, MotionEvent event) {
+            if (event.getAction() == MotionEvent.ACTION_DOWN) {
+                mPrevCard = mCurrentCard;
             }
+            view.setOnClickListener(new OnClickListener() {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:446]: No need for a listener - emulate this on the "on release" event: `MotionEvent.ACTION_UP`

Do note: `MotionEvent.ACTION_CANCEL` will need to be considered

**Review by david-allison-1 — CHANGES_REQUESTED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java (hunk 3 above)
Comment (shobhi1310) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:192]: ohh! I was actually experimenting locally with the response time, sorry will remove these.

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java (hunk 5 above)
Comment (shobhi1310) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:446]: I had earlier tried to emulate using `ACTION_UP`, but the double tap feature is getting captured first and auto-advancing of the card also freezes when new card shows up.

@david-allison-1

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java (hunk 3 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:192]: Wasn't fixed

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java (hunk 4 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:312]: Wasn't fixed

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java (hunk 5 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:446]: What have you tried code-wise? Presumably you should only be setting the double-tap variable on release?

**Review by david-allison-1 — CHANGES_REQUESTED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 6]
```diff
@@ -435,31 +440,46 @@ public void onClick(View view) {
...
-                Timber.i("AbstractFlashcardViewer:: EASE_4 pressed");
-                answerCard(Consts.BUTTON_FOUR);
-            } else {
-                mCurrentEase = 0;
+            if (event.getAction() == MotionEvent.ACTION_UP) {
+                long time = SystemClock.elapsedRealtime() - mLastClickTime;
+                duration += time;
+                // Ignore what is most likely an accidental double-tap.
+                if (clickCount == 2 && duration < DOUBLE_TAP_IGNORE_THRESHOLD) {
+                    clickCount = 0;
```
Comment (shobhi1310) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:458]: I have added 2 new variables `clickCount` and `duration` but still it is creating some issues still.

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 7]
```diff
@@ -435,31 +440,46 @@ public void onClick(View view) {
...
-            } else if (id == R.id.flashcard_layout_ease4) {
-                Timber.i("AbstractFlashcardViewer:: EASE_4 pressed");
-                answerCard(Consts.BUTTON_FOUR);
-            } else {
-                mCurrentEase = 0;
+            if (event.getAction() == MotionEvent.ACTION_UP) {
+                long time = SystemClock.elapsedRealtime() - mLastClickTime;
+                duration += time;
+                // Ignore what is most likely an accidental double-tap.
+                if (clickCount == 2 && duration < DOUBLE_TAP_IGNORE_THRESHOLD) {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:457]: I feel this would be much more readable if we went back to using `mLastClickTime`.

Set `mLastClickTime` in this handler, as the original code was doing, and see if that improves things.

Comment (shobhi1310) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:457]: @david-allison-1 
I was checking the `mTimeoutHandler.removeCallbacks(mShowQuestionTask);` . So, `mShowQuestionTask` is supposed to trigger an `onClick` on the again button which creates the auto-advance nature. If I apply `OnTouch` to `mEaseHandler` then even the runnable code needs to be changed.

https://github.com/ankidroid/Anki-Android/blob/5283cfa25155b2bf73cb234b22bfd874002c71ee/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L1931

Comment (shobhi1310) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:457]: Best option would be to create a new `MotionEvent` and pass it into `dispatchTouch` for the runnable. Is it fine?

Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:457]: I still think that's far too complicated. All we should need is:

* A touch listener, replacing the click listener
* Handling `DOWN` and saving the card
* Handling `UP` with the same logic that we have now
  * Plus, do nothing if the card doesn't match

Could you try this design, and if it doesn't work, we'll iterate on it

**Comment by shobhi1310** [comment]
I have made the changes as you requested, do review it once @david-allison-1

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 8]
```diff
@@ -438,31 +438,43 @@ public void onClick(View view) {
...
-                Timber.i("AbstractFlashcardViewer:: EASE_3 pressed");
-                answerCard(Consts.BUTTON_THREE);
-            } else if (id == R.id.flashcard_layout_ease4) {
-                Timber.i("AbstractFlashcardViewer:: EASE_4 pressed");
-                answerCard(Consts.BUTTON_FOUR);
-            } else {
-                mCurrentEase = 0;
+            if (event.getAction() == MotionEvent.ACTION_UP) {
+                // Perform intended action only if the button has been pressed for current card
+                if (mPrevCard == mCurrentCard) {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:452]: This looks much better! Could you invert this `if`

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 9]
```diff
@@ -438,31 +438,43 @@ public void onClick(View view) {
...
+                        answerCard(Consts.BUTTON_TWO);
+                    } else if (id == R.id.flashcard_layout_ease3) {
+                        Timber.i("AbstractFlashcardViewer:: EASE_3 pressed");
+                        answerCard(Consts.BUTTON_THREE);
+                    } else if (id == R.id.flashcard_layout_ease4) {
+                        Timber.i("AbstractFlashcardViewer:: EASE_4 pressed");
+                        answerCard(Consts.BUTTON_FOUR);
+                    } else {
+                        mCurrentEase = 0;
+                    }
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:474]: I think we want to return `true` here?

**Review by david-allison-1 — COMMENTED** [review]
This looks much better! Just a quick refactoring to clean up the code

Main question is about what we want the return value to be, but I think we've got this

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java (hunk 8 above)
Comment (shobhi1310) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:452]: ok, I will put up this condition as `&&` with the previous `if` condition.

**Review by david-allison-1 — APPROVED** [review]
Looks good to me, thanks!!!

**Review by mikehardy — APPROVED** [review]
clever fix, and a clean implementation - thanks @shobhi1310 !

**Comment by mikehardy** [comment]
Hi there!

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for April 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged in April)

Thanks!
