### PR TITLE
Fix: Enable multi-line support for the deck picker footer

### LINKED ISSUE #17100: UI can't be entirely read when text size is big
How to reproduce:

Increase the size of the text on your phone. The exact way to do it depends on the device. On my pixel, it's 
> Settings > Display > Display and text size > Font size > put the slider to the right
(maybe not the exact wording, my device is in French

Then just use the app, and look at all the missing texts. Maybe you'll also need to switch to a language which is more verbose than English, such as French or German. Don't worry if you don't speak the language, the fact that there is text that can't be read or even clicked should still be obvious.

Here is all the issues I found. Please create one PR for each of the issue below, for the ease of review.
Don't ask to be assigned to it, just tell us which issue you're working on, if any.
If you find issues I missed, please add them in comment in this issue.

We'll be able to close this issue when all of the issues listed below are solved.

image

"rename" cover "delete", instead if there is not enough room, it should go to a new line.

2024-09-21-172053_361x811_scrot
Menus should display the entire text of the entry, even if texts multiple lines. 

2024-09-21-172404_361x775_scrot
I guess it's okay here if "ankidroid" can't be read entirely. But the subtitle with the number of cards to review seems like it should take multiple line. Or, if not possible, long pressing on it should show the content in a tooltip. 
This is a general issue that occurs in almost every activity.

Also, the text at the bottom of the screen should be multiple lines.

image
In this case, I think i'd like a bigger button to select the answer.

image
"Navigateur de " and other text should potentially be multi-line if needed.

image
Deck (Paquet de cartes) should potentially be multiline, and probably not take more than, let's say, 40% of the width. This display is nonsense

2024-09-23-010524_373x838_scrot
The browser options should probably be scrollable.

### PR DESCRIPTION
**Pull request by Aditya13s**
## Purpose / Description
The purpose of this change is to allow the footer of the deck picker to display multiple lines of text.

## Fixes
* Part of #17100
* Maybe a fix for https://github.com/ankidroid/Anki-Android/issues/14641

## Approach
The `setSingleLine` method has been removed from the `DeckPicker.kt` file to allow the footer text to display across multiple lines. Additionally, a `.replace` function was implemented to ensure that newline characters in the text from `sched.studiedToday()` are replaced with spaces, preventing any text from being hidden.

## How Has This Been Tested?
This change has been tested using different font sizes and languages.

## Screenshot
multiline_footer

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 1]
```diff
@@ -2090,10 +2090,9 @@ open class DeckPicker :
         dueTree = result
         launchCatchingTask { renderPage(collectionHasNoCards) }
         // Update the mini statistics bar as well
-        reviewSummaryTextView.setSingleLine()
         launchCatchingTask {
             reviewSummaryTextView.text = withCol {
-                sched.studiedToday()
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:2096]: I'd really love a comment to explain the reason of the replace.
Probably something such as:
> the backend returns a string such as 
> "Studied 1 cards in 5 seconds today
> (5s/card)"
> Let's imitate anki, save estate, and put the text on a single line if possible

**Review by Arthur-Milchior — APPROVED** [review]
Thank you very much. I appreciate the improvement.

I'll admit that, having the text below the + symbol is not ideal. It's still readable, and I don't expect that this bug is worth doing more effort to find a better design to solve it!

**Review by BrayanDSO — CHANGES_REQUESTED** [review]
Kind of similar to what was proposed in #16965, so the comments about the screen edges made by `@lukstbit` still stands.

Also, the screenshot in the PR description evidently shows that the text can be hidden by the `Add` button

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt (hunk 1 above)
Comment (Aditya13s) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:2096]: footer
After removing the `reviewSummaryTextView.setSingleLine()` the footer looks like this. So simplest approach which hits my mind is to use `replace()` function.

**Comment by Aditya13s** [comment]
> Kind of similar to what was proposed in #16965, so the comments about the screen edges made by `@lukstbit` still stands.
> 
> Also, the screenshot in the PR description evidently shows that the text can be hidden by the `Add` button

As @Arthur-Milchior mentioned, this bug isn’t worth further effort and can be addressed in #17334, which completes the migration to edge-to-edge.

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt (hunk 1 above)
Comment (Arthur-Milchior) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:2096]: When I say I want a comment, especially if I put the request for change at a specific line of the code, it means that I want the comment to be in the code.
So that the next person that reads the code can figure out what was going on

Comment (Arthur-Milchior) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:2096]: Also what matters in the comment is to note that the backend returns a value with a newline.
Upstream, the value is used in HTML page, so it does not matter. Here, we need to pay attention to it as the newline would be shown by Android's UI

**Comment by Arthur-Milchior** [comment]
@Aditya13s I don't have more authority than @BrayanDSO. I have approved this, but we usually wants to reviewer, and so if the other reivewer does not appreciate, this is up to discussion. 
I'm pretty sure Brayan was able to read what I wrote, and simply disagree. He has good argument I didn't even know about (edge-to-edge).

@BrayanDSO Can I ask what would be your preferred solution regarding the button?
Moving it, by ensuring it's above the text? Having the text width be small enough that it does not overlap with the button? (I'd fear we end up needing 3 lines if we don't allow the text to cover the full width of the screen)
I guess we can use `Rect.intersects` on the rectangle of the text view and the FAB to check whether they intersect, and reduce the width only if it's the case. Not very elegant but it would work.

> can be addressed in https://github.com/ankidroid/Anki-Android/issues/17334, which completes the migration to edge-to-edge.

Yeah, but in this case, there is not even a point of landing your change if we suspect we may need to change the result soon after. We should try to fix #14641 simultaneously, given that it consider the same part of the UI.

To be clear, I still believe that your change is an improvement compared to the current state. After all, the total quantity of missing text is quite smaller. But I prefer to have a single merged change that deals with all the issues related to this text view simultaneously

**Comment by BrayanDSO** [comment]
> Moving it, by ensuring it's above the text?

Yes. I believe that it can be easily done by editing only the layout files. There shouldn't be a need to do it programmatically

**Review by lukstbit — CHANGES_REQUESTED** [review]
> this bug isn’t worth further effort and can be addressed in https://github.com/ankidroid/Anki-Android/issues/17334, which completes the migration to edge-to-edge.

Edge to edge becoming the default affects the interaction between the info text and the screen borders. The bug in the picture isn't related to edge to edge, it's related to the changes you've made in this PR and the interaction between the info text and the fab. So the current "fix" only fixes the issue partially and would result in a new bug report in the near future.

**Comment by Aditya13s** [comment]
Screenshot From 2024-11-12 02-05-42

Setting the CoordinatorLayout elevation of the Floating Action Button (FAB) to -1dp gives the right look, but it makes the FAB unclickable because it ends up behind other views.

**Comment by lukstbit** [comment]
There should be enough space made available for the info text between the screen margin and fab button. It shouldn't be visible below or above the fab button.

**Comment by Aditya13s** [comment]
footer
This is the final output

**Comment by Arthur-Milchior** [comment]
Clearly this result looks nicer. I admit I regret that it moves the FAB even when the text is small. I'd have preferred if we had a way to ensure it remains at the same place if possible.

I admit I really don't know XML layout enough to know how to do that.
I guess we should have a RelativeLayout that contains the `today_stats_text_view` at the bottom, and a layout that contains both the deck list and the fab at the top.
But that needs a serious rewrite of deck_picker.xml

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 2]
```diff
@@ -2090,10 +2092,17 @@ open class DeckPicker :
...
+                // Backend returns studiedToday() with newlines for HTML formatting,so we replace them with spaces.
+                sched.studiedToday().replace("\n", " ")
+            }
+            // Sets the bottom margin of the CoordinatorLayout to 55 pixels if reviewSummaryTextView has more than one line
+            if (reviewSummaryTextView.lineCount > 1) {
+                val coordinatorLayout = findViewById<CoordinatorLayout>(R.id.coordinatorLayout)
+                val layoutParams = coordinatorLayout.layoutParams as ViewGroup.MarginLayoutParams
+                layoutParams.bottomMargin = 55
+                coordinatorLayout.layoutParams = layoutParams
             }
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:2106]: this hardcoded approach may not fit well all the screen sizes. 

Putting the FAB above the footer should be simple with most Android layouts (LinearLayout, CoordinatorLayout, RelativeLayout, ConstraintLayout).

**Review by BrayanDSO — DISMISSED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt (hunk 2 above)
Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:2106]: Definitely not impossible, nor too difficult to justify doing a hack that will fall short soon

**Comment by Aditya13s** [comment]
@BrayanDSO Please review the changes

**Comment by Aditya13s** [comment]
@david-allison needs review

**Comment by david-allison** [comment]
@Aditya13s is it feasible to find another reviewer, this is one I'm not confident about

**Review by lukstbit — CHANGES_REQUESTED** [review]
While this does seem to work, we could end up with a memory leak/crash.

The listener isn't removed so basically runs on every frame drawn(even if most of the time it will not do anything). Even worse, a NEW listener is added EVERY time the decks are changed so we could end up with hundreds of these listeners running.

**Comment by Aditya13s** [comment]
> While this does seem to work, we could end up with a memory leak/crash.
> The listener isn't removed so basically runs on every frame drawn(even if most of the time it will not do anything). Even worse, a NEW listener is added EVERY time the decks are changed so we could end up with hundreds of these listeners running.

Fixed this problem by removing the listener after adjusting the bottom margin.

**Review by lukstbit — COMMENTED** [review]
It doesn't seem to work every time:


https://github.com/user-attachments/assets/1f5650be-6464-4825-a678-570784e83d6b

**Comment by Aditya13s** [comment]
@lukstbit I think moving this to the onStart() function will fix the problem.

**Review by lukstbit — APPROVED** [review]
LGTM, thanks.
