### PR TITLE
Fixed the whiteboard-editor-bug

### LINKED ISSUE #12388: [Bug] Whiteboard editor toolbar overlaps top toolbar when buttons set to appear at top or to not appear
###### Reproduction Steps

1. Go to Settings / Appearance / "Answer buttons position"
2. Select top or none(both have the bug)
3. Go to the decks screen and select one deck as you would do when reviewing
4. When a card appears then go in the top toolbar menu and select  "Whiteboard Editor"(you may have to enable whiteboard first here if it isn't already enabled)

###### Expected Result

The "Whiteboard Editor" toolbar doesn't overlap the top toolbar.

###### Actual Result

The "Whiteboard Editor" toolbar overlaps the top toolbar and makes it hard to see info there or access its menu. See images below:

When answer buttons are set to appear at the top:

Screenshot from 2022-09-13 10-45-20

When answer buttons are set to not appear(when using gestures):

Screenshot from 2022-09-13 10-45-50

Present in the latest alpha([2.16alpha83](https://github.com/ankidroid/Anki-Android/releases/tag/v2.16alpha83)) but this issue was present way before(just got to post the bug report now).

For maintainers: do we have analytics data about this feature(the answer buttons positioning)? Maybe we could remove the positioning options and let the whiteboard editor toolbar sit at the bottom where it works ok? 

*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by Marius1501**
## Purpose / Description
The whiteboard-editor overlapped the toolbar when the answerButtonPosition was set to "top" or "none"

## Fixes
Fixes #12388 

## Approach
The position changes to the bottom when the answerButtonPosition is set to "top" or "none".

##Screenshots
| Top  | None |
| ------------- | ------------- |
| grafik|grafik|

## How Has This Been Tested?

OS: Android 13.0
Device: Pixel 6 Pro

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt [hunk 1]
```diff
@@ -1042,6 +1044,26 @@ open class Reviewer : AbstractFlashcardViewer() {
         updateScreenCounts()
     }
 
+    private fun updateAnswerButtonPosition() {
```
Comment (lukstbit) [inline AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt:1047]: The method name should be `updateWhiteboardEditorPosition`, we indeed reference the `answerButtonPosition` preference but it's not the answer buttons that get their position changed.

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt [hunk 2]
```diff
@@ -1042,6 +1044,26 @@ open class Reviewer : AbstractFlashcardViewer() {
...
+        mPrefAnswerButtonPosition = super.restorePreferences()
```
Comment (lukstbit) [inline AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt:1048]: There's no need to go through `restorePreferences()` just to read that preference, accessing the SharedPreferences directly is faster:

`AnkiDroidApp.getSharedPrefs(this).getString...`

**Review by lukstbit — CHANGES_REQUESTED** [review]
Thanks, looks ok with the two small issues below.

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt [hunk 3]
```diff
@@ -118,6 +118,7 @@ open class Reviewer : AbstractFlashcardViewer() {
 
     // Whiteboard
     var prefWhiteboard = false
+    private var mPrefAnswerButtonPosition: String? = "bottom"
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt:121]: Making `mAnswerButtonsPosition` protected at `AbstractFlashcardViewer` and reusing it would be better to avoid the code duplication

**Review by BrayanDSO — CHANGES_REQUESTED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt (hunk 3 above)
Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt]: Your last change has moved mPrefAnswerButtonPosition to AbstractFlashcardViewer, which isn't what I asked. Three steps:

1. Make mAnswerButtonPosition protected at AbstractFlashcardviewer
2. Replace mPrefAnswerButtonPosition usages with mAnswerButtonPosition
3. Remove mPrefAnswerButtonPosition

Comment (Marius1501) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt]: Sry, now it should be ok. 😄

**Review by BrayanDSO — APPROVED** [review]
