### PR TITLE
Made image HTML identical to AnkiDesktop when inserting

### LINKED ISSUE #5237: BUG Caused by different quotationsmarks surrounding a filepath when adding it on Wndows 10 vs Android
###### Reproduction Steps

1. Add this code snippet to a card that have a field named "Image" on Ankidroid.

<div id="myImg"></div>

<script>
var image = "{{Image}}";

document.getElementById("myImg").innerHTML = image;

</script>

2. Load an image into the cards field named Image and display the card. It will work. Everything will be fine, however.

3. Export the deck with the code from ankidroid to Windows and load a new image, the card will not display, throwing the following error:

SyntaxError: Unexpected identifier

The reason is that when a imagefile is loaded on windows it is given double quotation marks around it path.

In JavaScript you can't have double quotation marks inside double quotation marks. You need to have single or vice versa.

On windows changing the JavaScript code line:

var image = "{{Image}}";

Into using single quotation marks:

var image = '{{Image}}';

Will make it work on windows.

However, now if you export your deck back to Ankidroid your cards will break if you load images into them or make new cards with images on your Android device.

I suspect this inconsistency might be behind other problems people might have.

Solution: The Ankidroid should use same kind of quotation double marks around a file when it loads it.

The reason for using a javascript to place images was that I wanted to have random images displayed on my cards. Such as this:

https://www.reddit.com/r/Anki/comments/6pjuwu/showing_a_random_image_from_a_set_of_images/

###### Expected Result

Display the image

###### Actual Result

Card do not display instead Anki or Ankidroid throws the following message:

SyntaxError: Unexpected identifier

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description
We previously used single quotes for inserting images, which caused issues when quoting the output in JavaScript.

## Fixes
Fixes #5237

## Approach

We use single quotes and no trailing slash, which is the same as AnkiDesktop.

## How Has This Been Tested?

Unit Tests.  
Image insertion still works.

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/ImageFieldTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5242651&bid=17184313)

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/ImageField.java [hunk 1]
```diff
@@ -21,10 +21,14 @@
 
 import com.ichi2.libanki.Collection;
 
+import org.jetbrains.annotations.NotNull;
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/ImageField.java]: jetbrains annotation? that seems odd - have I missed other of these? Seems we should have a system annotations package

Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/ImageField.java]: Default recommended by Android Studio, will convert to AndroidX

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/ImageFieldTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5242651&bid=17184313)

**Comment by mikehardy** [comment]
released in 2.9.6beta4
