### PR TITLE
Fixed alpha issues for FAB menu

### LINKED ISSUE #9341: [Bug] Floating action button change all color
###### Reproduction Steps

1. Install master (5efa59bf0de963a4ecc679cd022c3d8f794caacc)
2. Click on the floating action button (the plus)

###### Expected Result
Either just the menus. Or everything grayed and menu focused

###### Actual Result
Even the menu is grayed.

### PR DESCRIPTION
**Pull request by vp-98**
## Purpose / Description
Clicking on the FAB greyed out the entire layout including the FAB menu options. It was expected that everything but the FAB becomes greyed out. This issue was only seemed to occur with tablets.

## Fixes
Fixes #9341 

## Approach
In DeckPickerFloatingActionMenu.java the `mLinearLayout` has `setAlpha(0.5f)` called to grey out the menu where `mLinearLayout` is `R.id.deckpicker_view`. For tablets, this ID was for the LinearLayout in \res\layout-xlarge\homescreen.xml which held the deckpicker view, the study options fragment and the FAB layout. Since this layout held everything for tablets, calling `setAlpha(0.5f)` changed the entire layout's alpha.

Instead of having `mLinearLayout` refer to the LinearLayout in \res\layout-xlarge\homescreen.xml for tablets in DeckPickerFloatingActionMenu.java, referring `mLinearLayout` to the LinearLayout in layout\deck_picker.xml allows the alpha to be set only to the only the deckpicker view as intended and not the FAB layout.  A new `View` variable is also used to set the alpha for the study FrameLayout if the layout is known to be fragmented without affecting the FAB layout. Now each layout in the x-large screens can have their alpha set independently.

The LinearLayout in \res\layout-xlarge\homescreen.xml and layout\deck_picker.xml have the same ID, therefore the ID for the x-large layout was changed accordingly to allow `mLinearLayout` to refer to the correct layout when calling `view.findViewById()` in DeckPickerFloatingActionMenu.java and `findViewById()` in DeckPicker.java.  

## How Has This Been Tested?
Tested in an emulators on Android Studio.
- Pixel 3A with API 30
- Nexus 10 with API 30

https://user-images.githubusercontent.com/79328598/142258060-2f63c745-8071-499e-957f-88f3ae87f7ee.mp4

https://user-images.githubusercontent.com/79328598/142258079-fa049af8-ec20-4954-816c-fdb97b94cc0e.mp4

https://user-images.githubusercontent.com/79328598/142258140-55d305a2-6371-445c-b305-6df8543d7cab.mp4

## Learning (optional, can help others)
Went through the codebase and used the app for a bit on both a tablet emulator and a phone emulator to get a better understanding of the behavior and the issue.

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java [hunk 1]
```diff
@@ -461,8 +461,10 @@ protected void onCreate(Bundle savedInstanceState) throws SQLException {
         dividerDecorator.setDrawable(divider);
         mRecyclerView.addItemDecoration(dividerDecorator);
 
-        //Add background to Deckpicker activity
-        View view = mFragmented ? findViewById(R.id.deckpicker_view) : findViewById(R.id.root_layout);
+        // Add background to Deckpicker activity
+        //View view = mFragmented ? findViewById(R.id.deckpicker_view) : findViewById(R.id.root_layout);
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java:465]: In general we rely on source control to handle code deletion, we do not leave commented out code - it is either working code, or it's gone
```suggestion
```

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java [hunk 2]
```diff
@@ -1071,7 +1073,6 @@ public void addNote() {
         startActivityForResultWithAnimation(intent, ADD_NOTE, START);
     }
 
-
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java:1074]: You have altered spacing unnecessarily here, please do not mix changes in one commit - if you have a formatting commit, do it all as a separate commit, and keep related functional changes in their own commit(s).

The philosophy is based on the idea that changing software is easy. We merge tens of changes a week, sometimes a day. The hard part is *reviewing* software changes and *testing* software changes so that the changes are right.

Absolutely minimal changes, in separate commits, optimize for review then, and are strongly preferred.

In this specific case (and all the other spacing ones I will mention) please remove the changes entirely, simply drop them - they are unimportant to the fix you've made and just make it hard to review

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java [hunk 3]
```diff
@@ -1233,13 +1234,11 @@ public void displayDowngradeFailedNoSpace() {
         showDialogFragment(DeckPickerNoSpaceToDowngradeDialog.newInstance(formatter, collectionFile));
     }
 
-
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java:1236]: drop this spacing change

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java [hunk 4]
```diff
@@ -1233,13 +1234,11 @@ public void displayDowngradeFailedNoSpace() {
...
     @VisibleForTesting
     protected void displayAnalyticsOptInDialog() {
         showDialogFragment(DeckPickerAnalyticsOptInDialog.newInstance());
     }
 
-
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java:1242]: drop this spacing change

File: AnkiDroid/src/main/res/layout-xlarge/homescreen.xml [hunk 5]
```diff
@@ -1,23 +1,30 @@
...
-                                           android:layout_width="match_parent"
-                                           android:layout_height="match_parent"
-                                           android:fitsSystemWindows="true">
+<androidx.coordinatorlayout.widget.CoordinatorLayout
+    xmlns:android="http://schemas.android.com/apk/res/android"
+    xmlns:app="http://schemas.android.com/apk/res-auto"
+    android:layout_width="match_parent"
+    android:layout_height="match_parent"
+    android:fitsSystemWindows="true">
+
```
Comment (mikehardy) [inline AnkiDroid/src/main/res/layout-xlarge/homescreen.xml:8]: Drop this spacing change - it just adds a lot of noise to the diff during review

File: AnkiDroid/src/main/res/layout-xlarge/homescreen.xml [hunk 6]
```diff
@@ -1,23 +1,30 @@
...
         <LinearLayout
-            android:id="@+id/deckpicker_view"
+            android:id="@+id/deckpicker_xl_view"
             android:layout_width="match_parent"
             android:layout_height="match_parent"
             android:background="?android:attr/colorBackground"
             android:orientation="horizontal">
+
```
Comment (mikehardy) [inline AnkiDroid/src/main/res/layout-xlarge/homescreen.xml:15]: unnecessary spacing change

File: AnkiDroid/src/main/res/layout-xlarge/homescreen.xml [hunk 7]
```diff
@@ -1,23 +1,30 @@
...
             <include layout="@layout/deck_picker"
                 android:layout_width="1dip"
                 android:layout_weight="3"
                 android:layout_height="match_parent"/>
+
```
Comment (mikehardy) [inline AnkiDroid/src/main/res/layout-xlarge/homescreen.xml:20]: drop this change

File: AnkiDroid/src/main/res/layout-xlarge/homescreen.xml [hunk 8]
```diff
@@ -1,23 +1,30 @@
...
             <FrameLayout
                 android:id="@+id/studyoptions_fragment"
                 android:layout_weight="2"
                 android:layout_width="1dip"
                 android:layout_height="match_parent"/>
+
```
Comment (mikehardy) [inline AnkiDroid/src/main/res/layout-xlarge/homescreen.xml:26]: drop this change

File: AnkiDroid/src/main/res/layout-xlarge/homescreen.xml [hunk 9]
```diff
@@ -1,23 +1,30 @@
...
         </LinearLayout>
+
```
Comment (mikehardy) [inline AnkiDroid/src/main/res/layout-xlarge/homescreen.xml:28]: more unnecessary spacing change

File: AnkiDroid/src/main/res/layout/deck_picker.xml [hunk 10]
```diff
@@ -10,7 +10,7 @@
         android:id="@+id/deckpicker_view"
         android:layout_width="match_parent"
         android:layout_height="match_parent"
-        android:orientation="vertical" >
+        android:orientation="vertical">
```
Comment (mikehardy) [inline AnkiDroid/src/main/res/layout/deck_picker.xml:13]: I understand why this is tempting, but it is unimportant for the fix your making - remove this to remove diff noise in the commit

File: AnkiDroid/src/main/res/layout/deck_picker.xml [hunk 11]
```diff
@@ -33,12 +33,12 @@
                         android:id="@+id/files"
                         android:layout_width="match_parent"
                         android:layout_height="match_parent"
+                        android:layout_above="@id/today_stats_text_view"
                         android:clipToPadding="false"
                         android:drawSelectorOnTop="true"
                         android:fastScrollEnabled="true"
                         android:focusable="true"
                         android:paddingBottom="72dp"
-                        android:layout_above="@id/today_stats_text_view"
```
Comment (mikehardy) [inline AnkiDroid/src/main/res/layout/deck_picker.xml:41]: I do not understand why this was moved, it seems unnecessary and likely should be removed as diff noise

File: AnkiDroid/src/main/res/layout/deck_picker.xml [hunk 12]
```diff
@@ -84,6 +84,7 @@
 
             </FrameLayout>
         </androidx.swiperefreshlayout.widget.SwipeRefreshLayout>
+
```
Comment (mikehardy) [inline AnkiDroid/src/main/res/layout/deck_picker.xml:87]: unnecessary spacing change

File: AnkiDroid/src/main/res/layout/homescreen.xml [hunk 13]
```diff
@@ -1,7 +1,10 @@
...
-                                           android:layout_height="match_parent"
-                                           android:fitsSystemWindows="true">
+<androidx.coordinatorlayout.widget.CoordinatorLayout
+    xmlns:android="http://schemas.android.com/apk/res/android"
+    android:layout_width="match_parent"
+    android:layout_height="match_parent"
+    android:fitsSystemWindows="true">
+
     <include layout="@layout/deck_picker"/>
+
```
Comment (mikehardy) [inline AnkiDroid/src/main/res/layout/homescreen.xml:9]: none of these changes are necessary, this would remove an entire file from the diff when dropped as a change

**Review by mikehardy — CHANGES_REQUESTED** [review]
Hey, this looks pretty good! Thanks for posting this.
The video demonstrations are obviously correct, and I was able to understand why the changes you made were necessary, because of your explanation, those are excellent

The only thing I'd like to see different is that the diff is far from minimal. it's a very small change to make the fix, and it is very hard to see it in the noisy diff. I left comments where things could be minimized for faster review

**Review by david-allison-1 — COMMENTED** [review]
Thanks! Mirroring Mike on the spacing changes.

Functionality looks good, I've kicked off CI and will be happy to approve once the changes are made and CI passes.

Do let me know if you need any guidance.

**Comment by vp-98** [comment]
@mikehardy Sorry about the unnecessary space changes! I have committed the changes and dropped all the space changes that were mentioned. Please let me know if I missed (or introduced) a space change in the process,

File: AnkiDroid/src/main/res/layout-xlarge/homescreen.xml [hunk 14]
```diff
@@ -4,7 +4,7 @@
                                            android:layout_height="match_parent"
                                            android:fitsSystemWindows="true">
         <LinearLayout
-            android:id="@+id/deckpicker_view"
+            android:id="@+id/deckpicker_xl_view"
```
[the remark this answers is not in the document]
Comment (vp-98) [reply AnkiDroid/src/main/res/layout-xlarge/homescreen.xml:7]: The reason I had the name change was because in DeckPickerFloatingActionMenu.java, `mLinearLayout` was assigned to `R.id.deckpicker_view`. Both LinearLayouts in \res\layout-xlarge\homescreen.xml and layout\deck_picker.xml had the same ID. The correct one to assign to `mLinearLayout` is the linear layout from layout\deck_picker.xml but the LinearLayout from the x-large file. This LinearLayout included the FAB layout, Deckpicker layout, and the study fragment resulting in the entire screen's alpha to change when using `setAlpha().` The ID change prevents `mLinearLayout` from referring to the wrong layout and only referes to `R.id.deckpicker_view` in the deck_picker.xml.

The linear layout from \res\layout-xlarge\homescreen.xml still needed to be accessed in DeckPicker.java to apply the correct layout if the screen was fragmented so having the unique ID still allows for that to happen.

**Review by david-allison-1 — APPROVED** [review]
Sounds good to me

**Comment by david-allison-1** [comment]
Just want to add, thanks so much for the rigorous documentation! Makes things much easier

**Review by mikehardy — APPROVED** [review]
Now that is one tidy change :-), thanks

**Comment by mikehardy** [comment]
Hi there! November OpenCollective Notice

Apologies for the delay, and if you're already submitted something to OpenCollective for PRs merged in November 2021, you may feel free to ignore this and it will be processed shortly

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for November 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of August)

Thanks!
