### PR TITLE
Fix: Added robust keyboard visibility detection using WindowInsetsCompat.

### LINKED ISSUE #17913: Pressing back to dismiss keyboard closes search
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

- In the browser, search for any term.
- Click any of the search results.
- Press back to exit the note editor.
- Keyboard pops up.
- Press back to dismiss the keyboard.
- The page reloads and the search results go away.

### Expected behaviour

On pressing back, only the keyboard should be dismissed and the search results should be preserved.

Ideally, the keyboard should not pop up at all after exiting the note editor.

### Debug info

```text
2.21 alpha 11
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by Scapesfear**
## Purpose / Description
Ensures that when the keyboard is open, pressing back first closes the keyboard instead of collapsing the search view, using robust keyboard visibility detection with WindowInsetsCompat
## Fixes
* Fixes #17913 
## Approach
Implemented WindowInsetsCompat to accurately detect keyboard visibility. On back press, if the keyboard is open, it is hidden first instead of collapsing the search view..

## How Has This Been Tested?
Samsun Galaxy F23 5G
https://github.com/user-attachments/assets/cc33384c-768f-4bf3-b82b-935c2019f68c

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by Scapesfear** [comment]
> One small improvement: Instead of naming the variable isCardBrowserReloaded, we can replace it with shouldClearSearchFocus for better readability and clarity.

Hi @MrTheMech, thanks for suggestion, actually i named the variable so, because when we come back from any activity to the caller, the caller gets reloaded and thus I named it `isCardBrowserReloaded`.

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt [hunk 1]
```diff
@@ -575,6 +577,19 @@ open class CardBrowser :
...
+    fun isKeyboardVisible(view: View?): Boolean =
+        view?.let {
+            ViewCompat.getRootWindowInsets(it)?.isVisible(WindowInsetsCompat.Type.ime())
+        } ?: false
+
+    private fun hideKeyboard() {
+        Timber.d("hideKeyboard()")
+        searchView?.let { view ->
+            val imm = view.context.getSystemService(Context.INPUT_METHOD_SERVICE) as? InputMethodManager
+            imm?.hideSoftInputFromWindow(view.windowToken, 0)
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt:589]: Out of curiosity, why not use this since we are already using the WindowInsetsCompat: https://developer.android.com/reference/kotlin/androidx/core/view/SoftwareKeyboardControllerCompat#hide()

It may be that using the InputMethodManager directly is the best way, but I'm curious if that was a considered decision or not, and if so, why using InputMethodManager vs the Compat is best

**Review by mikehardy — COMMENTED** [review]
Seems like it should work - one curiosity (that may result in no change...) about choice of method to close the soft keyboard

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt (hunk 1 above)
Comment (Scapesfear) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt:589]: Hi @mikehardy,

hide() is essentially an abstraction over the InputMethodManager approach. Here's the snippet that shows what it does under the hood:

```kotlin
@Override
void hide() {
    if (mView != null) {
        ((InputMethodManager) mView.getContext()
                .getSystemService(Context.INPUT_METHOD_SERVICE))
                .hideSoftInputFromWindow(mView.getWindowToken(), 0);
    }
}
```
I opted for the InputMethodManager method because when I searched for ways to hide the keyboard, this was the most popular solution. I tested it, and it reliably works across various Android versions.

Also, note that the alternative approach using 

```kotlin
view.windowInsetsController?.hide(WindowInsets.Type.ime())
```
 is deprecated.

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt:589]: okay, interesting that there *is* a compat for this when it doesn't seem to be abstracting over API level differences, which is normally what Compat is for. Perhaps it used to and those just fell away as the supported API windows moved to higher android versions

**Review by mikehardy — APPROVED** [review]
LGTM

**Comment by david-allison** [comment]
Hi there @Scapesfear! This is the OpenCollective Notice for PRs merged from [2025-05-01 through 2025-05-31](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2025-05-01..2025-05-31+author%3AScapesfear)

If you are interested in compensation for this work, the process with details is here: https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

We only post one comment per person per month to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for this month

Please understand that our monthly budget is never guaranteed to cover all claims - the cap on payments-per-person may be lower, but we try to make our process as fair and transparent as possible, we just need your understanding.

Thanks!
