### PR TITLE
fix: remove extra undo entry when adding note

### LINKED ISSUE #19508: "Undo Add Note" breaks the undo stack in the decks screen
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Do something in the decks screen like renaming, creating, or deleting a deck.
2. Add a note.

You can undo adding the note from the 3 dot menu, but you can't undo anything before.

### Expected behaviour

You should be able to undo the actions before adding the note.

### Debug info

```text
AnkiDroid Version = 2.23.0alpha8 (f9e524a31c98e4f5d922f7b2c5217efe4d350009)  
Backend Version = 0.1.62-anki25.09.2 (25.09.2 3890e12c9e48c028c3f12aa58cb64bd9f8895e30)  
Android Version = 13 (SDK 33)  
ProductFlavor = full  
Device Info = Xiaomi | POCO | mondrian | mondrian_global | 23013PC75G | qcom  
Webview User Agent = Mozilla/5.0 (Linux; Android 13; 23013PC75G Build/TKQ1.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/141.0.7390.122 Mobile Safari/537.36  
ACRA UUID = 4afc3b3f-e93f-4a66-bc71-2b9476ef9eb0  
FSRS = 5.1.0 (Enabled: true)  
Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by xenonnn4w**
## Purpose / Description
 When undoing the note, the unlabeled entry from `notetypes.save()` would be exposed, causing `undoAvailable()` to return false and hiding previous deck operations from the undo stack.

## Fixes
* Fixes  #19508 

## Approach
Remove `notetypes.save()` from `undoableOp` block as it's redundant - the note already contains notetype information.

## How Has This Been Tested?

https://github.com/user-attachments/assets/dab67e8b-c03e-459a-8d9e-527a9f5a2c62

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by BrayanDSO** [comment]
Tests fail, and that probably means that the fix is wrong.

Please run CI before making a PR. You can run it in your GH branch as well if you don't want to run it locally.

**Comment by xenonnn4w** [comment]
The saveNoteWithProgress() function was calling both notetypes.save() and addNote() inside the same undoableOp block. This created two separate backend undo entries:
- Unlabeled entry from addOrUpdateNotetype()
- Labeled "Undo Add Note" entry

 When undoing the note, the unlabeled entry was exposed, causing undoAvailable() to return false and hiding previous operations.
 Solution:
-  Removed notetypes.save() from saveNoteWithProgress() to create only one undo entry.

  Trade-off:
  This breaks issue #13931 - the notetype's "last used deck" preference is no longer persisted. Users       
  will need to manually select the deck each time they add a note.
  The test NoteEditorTest; decide by note type preference - 13931 has been disabled to accomplish this.

  This is a temporary fix. The proper solution requires backend changes i.e have addNote() automatically update notetype.did,

**Comment by BrayanDSO** [comment]
> The proper solution requires backend changes i.e have addNote() automatically update notetype.did,

So, we should wait for that.

**Comment by xenonnn4w** [comment]
The backend already handles "last used deck" tracking automatically via `defaultDeckForNoteType()`.
Latest commit updates the test to use modern API - all tests passing.
Backend issue closed: https://github.com/ankitects/anki/issues/4434
 **Ready for review!**

File: AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt [hunk 1]
```diff
@@ -154,8 +154,7 @@ class InstantEditorViewModel :
      */
     private suspend fun saveNote(): SaveNoteResult {
         return try {
-            editorNote.notetype.did = deckId!!
-
+            // NOTE: notetype.did is deprecated. Backend tracks default deck automatically.
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantEditorViewModel.kt]: I don't think this comment is necessary

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt [hunk 2]
```diff
@@ -1279,10 +1279,15 @@ class NoteEditorFragment :
         val changes =
             requireActivity().withProgress(resources.getString(R.string.saving_facts)) {
                 undoableOp {
-                    notetypes.save(editorNote!!.notetype)
                     addNote(editorNote!!, deckId)
                 }
             }
+        // NOTE: notetype.did is deprecated and replaced with defaultsForAdding() API.
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt]: ditto

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt [hunk 3]
```diff
@@ -1304,9 +1309,9 @@ class NoteEditorFragment :
             for (f in editFields!!) {
                 updateField(f)
             }
-            // Save deck to noteType
-            Timber.d("setting 'last deck' of note type %s to %d", editorNote!!.notetype.name, deckId)
-            editorNote!!.notetype.did = deckId
+            // NOTE: notetype.did is deprecated. The backend now tracks default deck
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt]: ditto
