### PR TITLE
Image paste clipboard

### LINKED ISSUE #8880: 2.15beta4 crash on image paste
Submitter entered crash comment "can't paste image into note"

```
java.lang.IllegalArgumentException: Prefix string too short
at java.io.File.createTempFile(File.java:1991)
at java.io.File.createTempFile(File.java:2064)
at com.ichi2.anki.NoteEditor.loadImageIntoCollection(NoteEditor.java:4)
at com.ichi2.anki.NoteEditor.onImagePaste(NoteEditor.java:2)
at com.ichi2.anki.NoteEditor.c(Unknown Source:0)
at com.ichi2.anki.k5.onImagePaste(Unknown Source:2)
at com.ichi2.anki.FieldEditText.onImagePaste(FieldEditText.java:1)
at com.ichi2.anki.FieldEditText.lambda$onCreateInputConnection$0(FieldEditText.java:6)
at com.ichi2.anki.FieldEditText.a(Unknown Source:0)
at com.ichi2.anki.o3.onCommitContent(Unknown Source:9)
at androidx.core.view.inputmethod.InputConnectionCompat$1.commitContent(InputConnectionCompat.java:1)
at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:567)
at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:93)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:246)
at android.app.ActivityThread.main(ActivityThread.java:8506)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

### LINKED ISSUE #10240: [Bug] NoteEditor: can't paste recently copied images from clipboard
###### Reproduction Steps

1. Take a screenshot desired content (e.g. from lecture slides - this is my desired workflow where I have slides + AnkiDroid open side-by-side on my phablet)
2. Open the note editor
3. Long press → paste; or Long press → clipboard and select image

###### Expected Result
The image will be pasted (in a similar fashion to that of inserting media via the attachment icon → from gallery). Seems to be relevant to https://github.com/ankidroid/Anki-Android/issues/7566 

###### Actual Result
The image is not pasted and a pop-up saying "something went wrong" appears. 
<details><summary>VIEW SCREENSHOT OF ERROR</summary>
<p>

Screenshot_20220118-105601_AnkiDroid

</p>
</details>

###### Debug info
<details><summary>VIEW DEBUG INFO</summary>
<p>

```
AnkiDroid Version = 2.15.6

Android Version = 11

Manufacturer = samsung

Model = SM-F926W

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-F926W Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/97.0.4692.87 Safari/537.36

ACRA UUID = c1f19acf-8c86-45ea-b826-2045bdf5659c

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

</p>
</details> 

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum - there are a host of related closed topics from when this feature was first being implemented for Android's new clipboard management: https://github.com/ankidroid/Anki-Android/issues/7566 
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by murugu-21**
## Purpose / Description
samsung clipboard returns content uri with id and _data columns only. this breaks existing method to get filename from content uri using MediaColumns.DISPLAY_NAME.

## Fixes
Fixes #10240
Fixes #8880

## Approach
content uri doesn't have MediaStore.MediaColumns.DISPLAY_NAME column in cursor.
When i listed all columns, there was only id and _data.
_data contained original path of file. I found display_name from path through substring.

## How Has This Been Tested?

Images pasted properly on my testing machine.
(test machine is running oneUI 3.1, android 11).

## Learning (optional, can help others)

https://stackoverflow.com/questions/13275007/contentresolver-how-to-get-file-name-from-uri

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.kt [hunk 1]
```diff
@@ -75,10 +75,17 @@ object ContentResolverUtil {
...
         try {
-            contentResolver.query(uri, arrayOf(MediaStore.MediaColumns.DISPLAY_NAME), null, null, null).use { c ->
+            contentResolver.query(uri, null, null, null, null).use { c ->
                 if (c != null) {
                     c.moveToNext()
-                    return c.getString(0)
+                    val mediaIndex = c.getColumnIndex(MediaStore.MediaColumns.DISPLAY_NAME)
+                    if (mediaIndex == -1) {
+                        // uri is content uri not media uri
+                        val dataIndex = c.getColumnIndexOrThrow("_data")
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.kt:84]: should use the constant I think? MediaStore.MediaColumns.DATA

File: AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.kt [hunk 2]
```diff
@@ -75,10 +75,17 @@ object ContentResolverUtil {
...
+                        val path = c.getString(dataIndex)
+                        return path.substring(path.lastIndexOf('/') + 1)
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.kt:86]: How is this approach better than simply asking the Uri for it's last path segment? https://developer.android.com/reference/android/net/Uri#getLastPathSegment()

**Review by mikehardy — CHANGES_REQUESTED** [review]
Hi there! Thanks for posting this up, users will really appreciate the fix.
I have a question about the method of getting that path, and then if this method is used a suggestion to use a constant vs string

File: AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.kt (hunk 2 above)
Comment (murugu-21) [reply AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.kt:86]: since cursor returns string, rather than uri, I resorted to string manipulation.

File: AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.kt (hunk 1 above)
Comment (murugu-21) [reply AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.kt:84]: The constant appears to be depricated. But content uri contains only id and _data columns.

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.kt:84]: That's an important signal! They are trying to tell us something with the deprecation, I'm really glad you mentioned that.
It appears that we need to use different behavior on Android < 29 and Android >= 29
For < 29 we should use DATA, for >= 29, does https://developer.android.com/reference/android/provider/MediaStore.MediaColumns#RELATIVE_PATH work? You mention it *only* has id and _data columns which is just bizarre given the documentation.

I'm afraid _data will go away given they deprecate it, but who knows. If relative_path really doesn't exist even on API29+ then I'm confused but I guess it has to be _data. Would be useful to leave a comment then, in the code, something like:

```java
// use `_data` column label directly, MediaStore.MediaColumns.DATA is deprecated in API29+ but
// the recommended MediaStore.MediaColumns.RELATIVE_PATH does not appear to  be available

File: AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.kt (hunk 2 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.kt:86]: I would do that if possible - I have learned to fear URL handling and will rely on library code for URI parsing / decomposition *at all times* now so as to avoid bugs handling the seemingly infinite variety of acceptable URIs

Comment (murugu-21) [reply AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.kt]: 61949f refactored

File: AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.kt (hunk 1 above)
Comment (murugu-21) [reply AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.kt:84]: this appears to be a samsung specific issue too. gboard clipboard contains MediaStore.MediaColumns.DISPLAY_NAME and works as expected. shall I add that too in the comments?

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.kt:84]: oh why, that's keyboard specific! What a pain! :laughing: - yes, mentioning MediaColumns availability appears to be keyboard-specific, gboard has them but Samsung does not, would be useful

**Comment by mikehardy** [comment]
Also apparently a test issue?

```

com.ichi2.utils.ContentResolverUtilTest > testViaQueryWorking FAILED
    java.lang.AssertionError: 
    Expected: is "filename_from_cursor.jpg"
         but: was "image.jpeg"
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at com.ichi2.utils.ContentResolverUtilTest.testViaQueryWorking(ContentResolverUtilTest.java:51)

```

**Comment by murugu-21** [comment]
The test issue is because of a missing return statement, fixed with 8917d92.

File: AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.kt (hunk 1 above)
Comment (murugu-21) [reply AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.kt:87]: 7cbacd0

**Comment by murugu-21** [comment]
> 🤔 as a developer note, adding that merge commit makes this commit trail immediately really messy. Merge commits are permitted by git, and we can deal with them but it is strongly preferred to pull rebase vs merge so the commits may remain separate and clean. The only way to really merge a pull request back to main branch after you've done a merge commit is to squash.
> 
> Of course, there are 17 different commits here which means the commit trail is already a hash, so a squash merge would have been the only way to merge anyway, but in the future, you might play around with ingesting PR comments as local edits then doing local git rebases to _edit_ your commits (instead of adding new ones) and force-pushing back to your branch. The end result then is just a few (maybe only 1) clean commit that we can rebase merge here. You can look at PRs from Arthur, David or myself with multiple commits in the past to see what that looks like

I am very new to open source and didn't know about rebase vs merge. will do rebase with future pr's.

**Comment by mikehardy** [comment]
Honestly that's the sort of thing that we should have in the development guide, because git knowledge, and our preferences, and how to operate git as a tool like a master requires a lot of explanation of the why first, and then the how. And we have explained it to lots of people but I'm not sure we ever wrote it down? 

@Arthur-Milchior I feel you have spent a lot of time explaining this before, in a lot of detail, in PR comments, @david-allison I've seen a few comments from yourself as well. Is this in our development guide anywhere? I only see this https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#git-workflow but it seems like we could really use a quick explanation of `git rebase`, why we use it (for clean, separate, easy to review commits that can go cleanly into the main tree, vs a squash), and how to use it (a quick example plus pointer to other tutorials?)

This is something we should really really do before GSoC goes any further I think - it will be a huge benefit and may be just as easy as lifting one of your previous PR comments in to the development guide?

File: AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.kt [hunk 3]
```diff
@@ -75,10 +75,21 @@ object ContentResolverUtil {
     private fun getFilenameViaDisplayName(contentResolver: ContentResolver, uri: Uri): String? {
         // 7748: android.database.sqlite.SQLiteException: no such column: _display_name (code 1 SQLITE_ERROR[1]): ...
         try {
-            contentResolver.query(uri, arrayOf(MediaStore.MediaColumns.DISPLAY_NAME), null, null, null).use { c ->
+            contentResolver.query(uri, null, null, null, null).use { c ->
                 if (c != null) {
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.kt:79]: I'd suggest doing 
```
if (c == null){
  return null
}
```
This way we avoid having extra levels of imbrication (I realize that this was not introduced in your PR. But since we are already working in this file, let's improve it even more)

**Review by Arthur-Milchior — COMMENTED** [review]
You stated that you tested this behavior on your current device.
To be clear, with current alpha/main, pasting images fail on your current device ? 
Because ideally, we would want to know that it solves the issue for people whose app was failing, and not only that it keep working for people for which it already work


If you answer yes, then I approve this PR. I'm fine if you ignore my suggestion and fine if you apply it

**Comment by mikehardy** [comment]
It was my understanding from comment back and forth that it not only failed for @murugu-21 , but it fails differently depending on keyboard (the keyboard - which you can change on android - controls the copy/paste buffer and each keyboard exports the paste buffer with different implementations of ContentResolver). I expect that's what we will here anyway, but now I'm on record with my understanding

**Comment by murugu-21** [comment]
> You stated that you tested this behavior on your current device. To be clear, with current alpha/main, pasting images fail on your current device ? Because ideally, we would want to know that it solves the issue for people whose app was failing, and not only that it keep working for people for which it already work
> 
> If you answer yes, then I approve this PR. I'm fine if you ignore my suggestion and fine if you apply it

I can confirm from my testing that current release of ankidroid on playstore does not work with my phone default clipboard implementation (samsung clipboard), but works perfectly with gboard's inbuilt clipboard images. On debugging the current alhpa/main, I was able to find out the reason for samsung clipboard failing is it only implements id and _data columns for content uris, whereas gboard implements the mediacolumns.DISPLAY_NAME field reffered in code to find file name.

File: AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.kt (hunk 3 above)
Comment (murugu-21) [reply AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.kt]: f919b5c
