### PR TITLE
Refactor $PRE_RELEASE to $RELEASE_TYPE & fix SC2088

### LINKED ISSUE #18110: Public releases are not marked as "latest" on github releases page
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

It appears the release script does not mark public releases as "latest" when it makes the new github release

This is expected behavior for all alpha and beta releases - so it should not mark all releases as latest - but for public releases it should

I just manually marked 2.20.1 as latest

### Expected behaviour

public releases should show up as the latest release on the side of this page after the release script is done:
https://github.com/ankidroid/Anki-Android

### Debug info

```text
current main as of March 16 2025
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by Haz3-jolt**
## Purpose / Description
Refactored github-releases in favor of gh cli and fixed a minor SC2088 violation in export PATH.

## Fixes
* Fixes #18110 

## Approach
Refactored to use gh cli, updated the publish.yml to use gh cli.

## How Has This Been Tested?
Will have to test on the fly.

## Learning (optional, can help others)
Checked the github cli documentation:
https://cli.github.com/manual/gh_release_create

Also went through usages of gh cli in code search because documentation is spotty.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: tools/release.sh [hunk 1]
```diff
@@ -162,17 +162,17 @@ export GITHUB_USER="ankidroid"
 export GITHUB_REPO="Anki-Android"
 
 if [ "$PUBLIC" = "public" ]; then
-  PRE_RELEASE=""
+  RELEASE_TYPE="--latest"
 else
-  PRE_RELEASE="--pre-release"
+  RELEASE_TYPE="--pre-release"
```
Comment (mikehardy) [inline tools/release.sh:167]:
```suggestion
  RELEASE_TYPE="--prerelease"
```

From docs (thanks for linking those so I could easily open it to carefully verify everything...), it appears we were getting this wrong before, and it could use a correction as well:

https://cli.github.com/manual/gh_release_create

```
-p, --prerelease
Mark the release as a prerelease
```

That may even be the root cause of the malfunction, as the docs for `--latest` say:

> (default [automatic based on date and version])

...which means if we weren't marking pre-releases as such, it may not have been able to automatically figure out whether a release on an "older" version (e.g. 2.20.1 vs 2.21-alpha5) was latest or not. Just a guess on my part though, and with your change it will all be explicit not automatic / inferred, which is better

**Review by mikehardy — CHANGES_REQUESTED** [review]
one tweak on the prerelease tag based on docs, what do you think?

File: tools/release.sh (hunk 1 above)
Comment (Haz3-jolt) [reply tools/release.sh]: Done!

**Comment by Haz3-jolt** [comment]
> one tweak on the prerelease tag based on docs, what do you think?

Yep, thanks for the catch!

**Review by mikehardy — APPROVED** [review]
This looks good and should conclusively solve it, thanks

**Review by mikehardy — CHANGES_REQUESTED** [review]
currently contains mix of gh cli and github-release params, which won't work as commented above

**Comment by Haz3-jolt** [comment]
Yep I wrongly assume since It's wrapping the REST API endpoint that it is up to date. In fact I think the project is not up to date for a lot of features.

I'll refactor github-release usage to gh.

File: .github/workflows/publish.yml [hunk 2]
```diff
@@ -39,11 +39,14 @@ jobs:
...
-          bunzip2 github-release.bz2
-          chmod 755 ~/bin/github-release
+          (type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
+          && sudo mkdir -p -m 755 /etc/apt/keyrings \
+          && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
+          && cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
+          && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
+          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
+          && sudo apt update \
+          && sudo apt install gh -y
```
Comment (mikehardy) [inline .github/workflows/publish.yml:49]: already installed https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md#cli-tools

File: tools/release.sh [hunk 3]
```diff
@@ -129,18 +129,6 @@ for UCFLAVOR in $UCFLAVORS; do
...
-ABIS='arm64-v8a x86 x86_64 armeabi-v7a'
-for ABI in $ABIS; do
-  cp AnkiDroid/build/outputs/apk/full/release/AnkiDroid-full-"$ABI"-release.apk AnkiDroid-"$VERSION"-"$ABI".apk
-done
-
-# Copy universal APKs for all flavors to cwd
-FLAVORS='full amazon play'
-for FLAVOR in $FLAVORS; do
-  cp AnkiDroid/build/outputs/apk/"$FLAVOR"/release/AnkiDroid-"$FLAVOR"-universal-release.apk AnkiDroid-"$VERSION"-"$FLAVOR"-universal.apk
-done
```
Comment (mikehardy) [inline tools/release.sh:142]: I don't understand why you changed this part, the APK move was tested and working fine
Now the diff below is very hard to read because I need to understand if you perhaps broke the file copying etc (which has tons of variable interpolation) or just the file upload

Can you *just* alter the github-release command to use gh and leave the file movement alone?

File: .github/workflows/publish.yml (hunk 2 above)
Comment (Haz3-jolt) [reply .github/workflows/publish.yml:49]: Oh thanks for the catch!

File: tools/release.sh (hunk 3 above)
Comment (Haz3-jolt) [reply tools/release.sh:142]: We would need to add extra cp lines to rename the file because the gh cli does not allow you to rename the files as a upload param/flag.

Comment (Haz3-jolt) [reply tools/release.sh:142]: or is it fine if i add the extra cp lines to rename and revert the file file copying to before?

Comment (mikehardy) [reply tools/release.sh:142]: strive for a minimal diff

if gh cli doesn't allow us to rename then during the copy from build dir to cwd, name that what gh needs IMHO

Comment (Haz3-jolt) [reply tools/release.sh:142]: So I add the prefixes during the copy from build dir to cwd?

Comment (mikehardy) [reply tools/release.sh:142]: Yeah, I think since we are already moving the file around (to a new name...) might as well do it all at once, for whatever is needed

Then the gh asset upload area is just the upload

**Review by mikehardy — APPROVED** [review]
This all looks reasonable, thank you!
I'll do an alpha shortly that uses and we'll see 👀

**Comment by david-allison** [comment]
Hi there @Haz3-jolt! This is the OpenCollective Notice for PRs merged from [2025-04-01 through 2025-04-30](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2025-04-01..2025-04-30+author%3AHaz3-jolt)
                      
If you are interested in compensation for this work, the process with details is here: https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

We only post one comment per person per month to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for this month

Please understand that our monthly budget is never guaranteed to cover all claims - the cap on payments-per-person may be lower, but we try to make our process as fair and transparent as possible, we just need your understanding.

Thanks!
