### PR TITLE
Fixed "CheckMedia" causing crash

### LINKED ISSUE #10892: [Bug] Crash : Ankidroid crashes on checking media.
###### Reproduction Steps
- Updated from 2.15.6 (Play store ver.) to 2.16alpha58
 and when i opened a card i started getting "failed to load : failed to load ...."

- So i decided to use check media which instantly crashed the app.
- After that i decided to force sync from anki web to ankidroid which also crashed the app.
- Decided to check if my library was corrupted for some reason or not by downloading a parallel of 2.15.6 on which it seemed to work perfectly, updated the parallel to alpha58 and it was also crashing.
- The alpha also doesn't seem to be detecting the backups neither is it creating them properly from what i can tell.

The only one which was good on 16/04 was made by the stable parallel.

- Just to confirm if the problem was from this alpha or from before this I decided to test on alpha 56 parallel and got the same issues uninstalled the parallel and installed alpha 55 parallel and there wasn't a crash this time, decided to update 55 to 56 and test again and there wasn't a crash, same with from 56 to 58.
- ~~Btw I did try to reinstall main alpha58 directly when i was originally getting the crash before the above point happened and the crashes still happened.~~ I thought i did but seems like i hadn't installed it directly and when I just did it seems to work fine on installing directly and this only happens if you update directly from 2.15.6 to 2.16 Alpha56/58/59.
- Have confirmed that it doesn't crash anymore on main after uninstalling 58 and installing 55 then 56 and 58 again after that.
- ~~Backup still don't seem to be being created properly but am not sure yet, so will confirm after I am.~~ It is detecting backups again and the backups are being created properly.

- Also half of this happened while writing this so it might seem like a story.

###### Expected Result

App checks media , directly syncs from anki web to ankidroid , Backup being created properly.

###### Actual Result

App crashes if you have updated directly to alpha 58 or installing alpha58 directly over current library.

###### Debug info
AnkiDroid Version = 2.16alpha58

Android Version = 11

Manufacturer = Xiaomi

Model = Redmi Note 9 Pro Max

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Redmi Note 9 Pro Max Build/RKQ1.200826.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/100.0.4896.88 Mobile Safari/537.36

ACRA UUID = d9199133-a62c-4572-ad4f-899c4d0b5307

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by dorrin-sot**
## Purpose / Description
App crashed if checkmedia was done after an update from v2.15.6

## Fixes
Fixes #10892 

## Approach
Added `READ_EXTERNAL_STORAGE` permision to the permissions list in `DeckPicker::requestStoragePermission`

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java [hunk 1]
```diff
@@ -599,11 +600,13 @@ private boolean applyDeckPickerBackground(View view) throws OutOfMemoryError {
     }
 
     public void requestStoragePermission() {
+        String[] storagePermissions = new String[] {
+                Manifest.permission.READ_EXTERNAL_STORAGE, Manifest.permission.WRITE_EXTERNAL_STORAGE
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java:604]: does it make sense to request READ and WRITE since WRITE contains READ 🤔

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java:604]: never mind - I just read the related issue more closely and see that this is some bizarre case apparently where WRITE does *not* contain READ, contrary to the docs, and that's the whole point of the PR really, sorry!

**Review by mikehardy — APPROVED** [review]
This seems like it should address the issue, thanks so much for pursuing this.
Since I can recreate this also I'll queue it for release in the alpha I do in a little bit and then check it, hopefully it works!

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java (hunk 1 above)
Comment (dorrin-sot) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java:604]: yes because it seems like android has changed something about the permissions so unlike before, they dont automatically grant read permission if user granted write permission.

**Comment by mikehardy** [comment]
Oh crud - you fixed this right as DeckPicker just went java -> kt in #10924 so now this needs a full re-do
Sincere apologies but I guess it's better than contemplating converting DeckPicker to kt ourselves 😆 -  monster file

**Review by mikehardy — CHANGES_REQUESTED** [review]
needs a re-do but in kotlin now

**Comment by mikehardy** [comment]
I'm going to start doing this on the Kotlin version since I want to test it and you've already done all the good work diagnosing + thinking about it. It's a simple re-do - if you're already working on it just let me know, otherwise I'll post a PR that supercedes this one but for credit purposes (not sure if you are a GSoC candidate or not, sorry if I'm just oblivious 😅 ) this and the kotlin version are definitely yours!

**Comment by dorrin-sot** [comment]
Oh I can do it 😁

**Comment by mikehardy** [comment]
Ok! Feel free. My kotlin is terrible, since I have never actually coded kotlin so I was doing it mostly just to exercise the new skill. I'll be very curious if you come up with the same thing I did, I *think* this is reasonable Kotlin?

```diff

diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt b/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.ktindex 7e0500d05..15df27c56 100644
--- a/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
@@ -473,13 +473,13 @@ open class DeckPicker : NavigationDrawerActivity(), StudyOptionsListener, SyncEr
     @KotlinCleanup("remove parameters named _")
     @KotlinCleanup("return early and remove else")
     fun requestStoragePermission() {
+        val storagePermissions = arrayOf(
+            Manifest.permission.READ_EXTERNAL_STORAGE, Manifest.permission.WRITE_EXTERNAL_STORAGE
+        )
         if (mClosedWelcomeMessage) {
             // DEFECT #5847: This fails if the activity is killed.
             // Even if the dialog is showing, we want to show it again.
-            ActivityCompat.requestPermissions(
-                this, arrayOf(Manifest.permission.WRITE_EXTERNAL_STORAGE),
-                REQUEST_STORAGE_PERMISSION
-            )
+            ActivityCompat.requestPermissions(this, storagePermissions, REQUEST_STORAGE_PERMISSION)
         } else {
             Timber.i("Displaying initial permission request dialog")
             // Request storage permission if we don't have it (e.g. on Android 6.0+)
@@ -490,10 +490,7 @@ open class DeckPicker : NavigationDrawerActivity(), StudyOptionsListener, SyncEr
                 .positiveText(R.string.dialog_ok)
                 .onPositive { _: MaterialDialog?, _: DialogAction? ->
                     mClosedWelcomeMessage = true
-                    ActivityCompat.requestPermissions(
-                        this, arrayOf(Manifest.permission.WRITE_EXTERNAL_STORAGE),
-                        REQUEST_STORAGE_PERMISSION
-                    )
+                    ActivityCompat.requestPermissions(this, storagePermissions, REQUEST_STORAGE_PERMISSION)
                 }
                 .cancelable(false)
                 .canceledOnTouchOutside(false)
@@ -719,8 +716,8 @@ open class DeckPicker : NavigationDrawerActivity(), StudyOptionsListener, SyncEr

     override fun onRequestPermissionsResult(requestCode: Int, permissions: Array<String>, grantResults: IntArray) {
         super.onRequestPermissionsResult(requestCode, permissions, grantResults)
-        if (requestCode == REQUEST_STORAGE_PERMISSION && permissions.size == 1) {
-            if (grantResults[0] == PackageManager.PERMISSION_GRANTED) {
+        if (requestCode == REQUEST_STORAGE_PERMISSION && permissions.isNotEmpty()) {
+            if (grantResults.all { it == PackageManager.PERMISSION_GRANTED }) {
                 invalidateOptionsMenu()
                 handleStartup()
             } else {
```

**Comment by dorrin-sot** [comment]
ohh i haven't written any kotlin before either and just saw it's similar to java/react😅. but this is exactly how I was planning to write it 👀

**Comment by dorrin-sot** [comment]
@mikehardy is it ok if I commit it? because it's excatly like yours😅

**Comment by mikehardy** [comment]
Yes please do! It's your solution after all. I was just playing with Kotlin and I got that value out of it :-)

**Comment by mikehardy** [comment]
Be careful with #10928 just going in as well literally just now - but as I was reviewing that I was looking for how it would merge with this...I don't think it will conflict, code changes in separate areas.

**Review by mikehardy — APPROVED** [review]
Looks great, and hey! Kotlin! Thanks a bunch for this @dorrin-sot I've got high hopes it nails the problem on my device (which I've kept "broken" so it's a great test). 🤞

**Comment by mikehardy** [comment]
I have to go to dinner shortly and really really want this in so I just dropped the first (java) commit to fix the lint error and re-pushed, I'm testing this PR locally and if it works I'll merge and we'll get an alpha

**Review by david-allison — APPROVED** [review]

**Comment by mikehardy** [comment]
Boom - local tests all good (I run the same suite of gradle tasks that CI runs)

**Comment by dorrin-sot** [comment]
@mikehardy Could you reoopen this PR too? I added a commit which fixed it for me
