### PR TITLE
Fixed 'Change Column' does not restore state correctly

### LINKED ISSUE #18584: Browser: 'Change Column' does not restore state correctly
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

* Turn on Don't keep Activities' 
* Select 3 columns in browse: `Answer, Tags, Cards`
* Tap 'Tags' to change column
* `Question, Sort Field, Deck` are the first 3 options
* Close and open the window
* `Sort Field, Deck, Tags` are options

### Expected behaviour

* `Question, Sort Field, Deck` are the first 3 options

### Debug info

```text
AnkiDroid Version = 2.21alpha22-debug (4a6858ae080d74078faf18bc3236f9c18f267d12)  
Backend Version = 0.1.54-anki25.02.7 (25.02.7 98253c81cb3c4d203acec48d6eae6b488bf484d0)  
Android Version = 15 (SDK 35)  
ProductFlavor = full  
Device Info = Google | google | caiman | caiman | Pixel 9 Pro | caiman  
Webview User Agent = Mozilla/5.0 (Linux; Android 15; Pixel 9 Pro Build/BP1A.250505.005.A1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/137.0.7151.115 Mobile Safari/537.36  
ACRA UUID = fc78ccdf-7250-4381-94f9-02fb9072c228  
FSRS = 2.0.3 (Enabled: true)  
Crash Reports Enabled = false
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by highyield**
## Purpose / Description
Browser: 'Change Column' does not restore state correctly when 'Don't keep Activities' is turned on

## Fixes
* Fixes #18584

## Approach
I used an onSaveInstanceState function to properly save the state of the List of available columns. This list is later on retrieved in the onCreateDialog function

## How Has This Been Tested?
For testing I used my Android 16 phone. To reproduce the issue, the instructions from the linked issue can be used

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/browser/ColumnSelectionDialogFragment.kt [hunk 1]
```diff
@@ -81,12 +91,22 @@ class ColumnSelectionDialogFragment : DialogFragment() {
...
+                adapter.notifyDataSetChanged()
+            }
+        } else {
+            lifecycleScope.launch {
+                availableColumns =
+                    BundleCompat.getParcelableArrayList(savedInstanceState, AVAILABLE_COLUMNS, ColumnWithSample::class.java)!!.toList()
+                adapter.clear()
+                adapter.addAll(availableColumns)
+                adapter.notifyDataSetChanged()
+            }
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/browser/ColumnSelectionDialogFragment.kt]: most of the logic here is duplicated, the only part that varies is the availableColumns fetch
Could you do just the availableColumns conditional by itself into a local variable, then one lifecycleScope.launch that just uses it?

File: AnkiDroid/src/main/java/com/ichi2/anki/browser/ColumnSelectionDialogFragment.kt [hunk 2]
```diff
@@ -43,7 +43,17 @@ class ColumnSelectionDialogFragment : DialogFragment() {
...
+
+    public override fun onSaveInstanceState(outState: Bundle) {
+        with(outState) {
+            outState.putParcelableArrayList(AVAILABLE_COLUMNS, availableColumns.toCollection(ArrayList()))
+            super.onSaveInstanceState(this)
+        }
+    }
+
     override fun onCreateDialog(savedInstanceState: Bundle?): AlertDialog {
+        super.onCreate(savedInstanceState)
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/browser/ColumnSelectionDialogFragment.kt]: Seems odd to me to have `onCreateDialog` call `onCreate` of super, should it call `onCreateDialog` of super? This seems like a much more general change than persisting columns in the hunk above and reading them in the hunk below. Is it even necessary?

File: AnkiDroid/src/main/java/com/ichi2/anki/browser/ColumnSelectionDialogFragment.kt (hunk 1 above)
Comment (highyield) [reply AnkiDroid/src/main/java/com/ichi2/anki/browser/ColumnSelectionDialogFragment.kt]: Makes sense, also makes it easier to read that way. I'll change it.

File: AnkiDroid/src/main/java/com/ichi2/anki/browser/ColumnSelectionDialogFragment.kt (hunk 2 above)
Comment (highyield) [reply AnkiDroid/src/main/java/com/ichi2/anki/browser/ColumnSelectionDialogFragment.kt]: True, that change is not necessary. I'll remove it.

File: AnkiDroid/src/main/java/com/ichi2/anki/browser/ColumnSelectionDialogFragment.kt (hunk 1 above)
Comment (highyield) [reply AnkiDroid/src/main/java/com/ichi2/anki/browser/ColumnSelectionDialogFragment.kt]: Since `viewModel.previewColumnHeadings(viewModel.cardsOrNotes)` can only be called from within the lifecycleScope.launch statement, I simply moved the conditional into it. Works fine.

**Review by david-allison — APPROVED** [review]
Looks great, thanks!
