### PR TITLE
fix: open nav menu clears search

### LINKED ISSUE #9010: in-progress edits to search string in card browser are lost if navigation drawer opens
I cannot finish editing a search string, because every time I try a window or menu would open, reverting my editions.

[This screenshot video demonstrates the problem](https://youtu.be/j2KWTnxDC2w) 

The problem started recently, I noticed it only today. 

AnkiDroid Version = 2.15.2

Android Version = 10

Manufacturer = samsung

Model = SM-A920F

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; SM-A920F Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.77 Mobile Safari/537.36

ACRA UUID = 1b392f85-2b0c-4491-b153-fdb7fb7b8d34

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description
Opening the nav bar moved from the current search to the previous search

## Fixes
Fixes #9010 

## Approach
We do this with a temporary variable containing the current value
of the search bar.

There was a bug with setting this temporary, which we also fix:

Toggling the navbar called supportInvalidateOptionsMenu
This calls through to SearchView: as follows:

supportInvalidateOptionsMenu => MenuBuilder.clear()
MenuBuilder.clear() => collapseItemActionView(mExpandedItem);
=> onActionViewCollapsed
=> setQuery("", false);

We had a listener on setQuery, which then blanked the temp variable. class: CardBrowserSearchView fixes this, by ignoring these methods if it's triggered by collapse/expand

## How Has This Been Tested?

Unit tests pass, passes on my phone

⚠️ Felt like a significant effort to unit test this so I didn't attempt it. Please request if you want

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/ui/CardBrowserSearchView.kt [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+ * that the value was changed (which appear equivalent to selecting "clear field").
+ */
+class CardBrowserSearchView : SearchView {
+    constructor(context: Context) : super(context)
+    constructor(context: Context, attrs: AttributeSet?) : super(context, attrs)
+    constructor(context: Context, attrs: AttributeSet?, defStyleAttr: Int) : super(context, attrs, defStyleAttr)
+
+    /** Whether setting text should be ignored */
+    @get:JvmName("shouldIgnoreValueChange")
+    var mIgnoreValueChange = false; private set
```
Comment (ShridharGoel) [inline AnkiDroid/src/main/java/com/ichi2/ui/CardBrowserSearchView.kt:34]: Is `private set` required here?

File: AnkiDroid/src/main/java/com/ichi2/ui/CardBrowserSearchView.kt [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+
+    override fun onActionViewCollapsed() {
+        try {
```
Comment (ShridharGoel) [inline AnkiDroid/src/main/java/com/ichi2/ui/CardBrowserSearchView.kt:37]: Can you tell the reason behind using `try` and `finally` here?

File: AnkiDroid/src/main/java/com/ichi2/ui/CardBrowserSearchView.kt [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+
+/**
+ * An expanded SearchView where onActionViewCollapsed/onActionViewExpanded are handled externally
+ * This allows supportInvalidateOptionsMenu to occur, without calling methods which inform the UI
+ * that the value was changed (which appear equivalent to selecting "clear field").
+ */
+class CardBrowserSearchView : SearchView {
+    constructor(context: Context) : super(context)
+    constructor(context: Context, attrs: AttributeSet?) : super(context, attrs)
+    constructor(context: Context, attrs: AttributeSet?, defStyleAttr: Int) : super(context, attrs, defStyleAttr)
```
Comment (ShridharGoel) [inline AnkiDroid/src/main/java/com/ichi2/ui/CardBrowserSearchView.kt:30]: `class CardBrowserSearchView(context: Context) : SearchView(context)`

This can be done instead of writing three constructors.

File: AnkiDroid/src/main/java/com/ichi2/ui/CardBrowserSearchView.kt (hunk 1 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/ui/CardBrowserSearchView.kt:34]: I'm not familiar with Kotlin, is a public setter generated by default? If so, we don't want that

If not, it's not necessary

File: AnkiDroid/src/main/java/com/ichi2/ui/CardBrowserSearchView.kt (hunk 3 above)
Comment (ShridharGoel) [reply AnkiDroid/src/main/java/com/ichi2/ui/CardBrowserSearchView.kt:30]: `class CardBrowserSearchView(context: Context) : SearchView(context)`

This can be used here.

File: AnkiDroid/src/main/java/com/ichi2/ui/CardBrowserSearchView.kt (hunk 2 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/ui/CardBrowserSearchView.kt:37]: If we get an exception, we want the object to be in a valid state

File: AnkiDroid/src/main/java/com/ichi2/ui/CardBrowserSearchView.kt (hunk 1 above)
Comment (ShridharGoel) [reply AnkiDroid/src/main/java/com/ichi2/ui/CardBrowserSearchView.kt:34]: `mIgnoreValueChange` is already public, so setter will not be required.

Comment (ShridharGoel) [reply AnkiDroid/src/main/java/com/ichi2/ui/CardBrowserSearchView.kt:34]: Public setter will be available by default. If `private set` is done, then the setter will become private.

Comment (ShridharGoel) [reply AnkiDroid/src/main/java/com/ichi2/ui/CardBrowserSearchView.kt:34]: > If so, we don't want that

Oh okay, so the setter needs to be private?

Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/ui/CardBrowserSearchView.kt:34]: For encapsulation, the setter should be private

**Comment by david-allison-1** [comment]
I can't reply to your final comment on my phone, but I don't understand the syntax, do you have a reference?

Intuitively, I read that as defining a field in the class, which shouldn't be necessary

And I'm not sure what happens to the other overridden constructors

**Comment by ShridharGoel** [comment]
`class CardBrowserSearchView(context: Context) : SearchView(context)`

This defines the primary constructor having `context` as the parameter. `context` is passed to `SearchView` as the constructor parameter.

> And I'm not sure what happens to the other overridden constructors

Do we need to override them? If yes, then the current code is fine.

The syntax that I wrote was for primary constructors, just a better way of defining them.
https://kotlinlang.org/docs/classes.html#constructors

**Comment by ShridharGoel** [comment]
> Intuitively, I read that as defining a field in the class, which shouldn't be necessary

It does not become a class property unless you write it with the `val` or `var` keywords.

Writing like this in the constructor will make context a property of the class:
`class CardBrowserSearchView(val context: Context)`

**Comment by mikehardy** [comment]
Oh - I just realized that this was part of the Kotlin port. This is the cost of the port in practical terms: I can't pick this across to release-2.15 branch because the Kotlin port is a bigger series of work / PRs - re-targeting this for release-2.16 then. As we port to Kotlin we will need to keep minSdkVersion stable and release public frequently I think to get changes out and deal with the fact we can't cherry-pick back to old branches easily by marching forward quickly...

**Comment by david-allison-1** [comment]
@mikehardy Ah, ah, fair point. Back to Java with this

**Comment by mikehardy** [comment]
I'd rather march forward. release-2.15 has diverged hardly at all we can do 2.16 almost now if we like, and I think as soon as we are done with high-priority stabilization I would just cut 2.16 and put it out as well, with our first Kotlin stuff and just roll forward rapidly 17 18 etc. They just *give* numbers away on the internet :-)

And this was the low-priority / not-a-regression part of the issue logged from the user

**Comment by mikehardy** [comment]
But do as you wish of course :)

**Comment by david-allison-1** [comment]
> But do as you wish of course :)

Already done

**Review by mikehardy — APPROVED** [review]
LGTM - thanks!
