### PR TITLE
checking for null result to avoid class cast exception

### LINKED ISSUE #13974: 2.16.0beta2: java.lang.NullPointerException: null cannot be cast to non-null type kotlin.collections.List<T of com.ichi2.utils.TypedFilter>
```
java.lang.NullPointerException: null cannot be cast to non-null type kotlin.collections.List<T of com.ichi2.utils.TypedFilter>
	at com.ichi2.utils.TypedFilter.publishResults(TypedFilter.kt:8)
	at android.widget.Filter$ResultsHandler.handleMessage(Filter.java:284)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7884)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```
Android 13 sony
https://ankidroid.org/acra/app/1/bug/53861/report/6ab129d8-eccb-43a1-a82d-270eb9dbad86

### PR DESCRIPTION
**Pull request by criticalAY**
## Purpose / Description
The results parameter is declared as nullable (FilterResults?), but we are force unwrapping it (!!) without checking for null. If results is null, a NullPointerException will be thrown.

## Fixes
Fixes  #13974

## Approach
To fix this issue, we should perform a null check before accessing the values property. 

## How Has This Been Tested?

NPE would be avoided by the check hence avoiding the crash

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by criticalAY** [comment]
By adding the null check if (results != null && results.values is List<*>), we ensure that results is not null and that the values property is of type List. If the check passes, we can safely cast results.values to List<T> without encountering a NullPointerException.

**Review by BrayanDSO — APPROVED** [review]
LGTM. Thanks!

File: AnkiDroid/src/main/java/com/ichi2/utils/TypedFilter.kt [hunk 1]
```diff
@@ -49,8 +49,10 @@ abstract class TypedFilter<T>(private val getCurrentItems: (() -> List<T>)) : Fi
     @Suppress("UNCHECKED_CAST")
     override fun publishResults(constraint: CharSequence?, results: FilterResults?) {
         // this is only ever called from performFiltering so we can guarantee the value can be cast to List<T>
-        val list = results!!.values as List<T>
-        publishResults(constraint, list)
+        if (results != null && results.values is List<*>) {
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/main/java/com/ichi2/utils/TypedFilter.kt:52]: I don't want to test if it's a List<*>. 
If it's not a list, I prefer to have a crash report, as something was quite wrong.

**Review by Arthur-Milchior — COMMENTED** [review]
Not a fan I must admit. That indeed would avoid the crash. However, that does not explain why we had a null value in the first place. 
After all, the whole point of this class is to be a properly typed version of Filter, so we should ensure typing is done properly.

As @david-allison did most(all?) the work in this class, I'd be interested in his opinion

**Comment by Arthur-Milchior** [comment]
After spending 20 minutes, I've no idea what's going on. I guess what maybe helpful is to at least catch we got a null value and send a report to AnkiDroid.
If we can't easily solve it, best not to crash. With luck, the absence of filtering will just be reported to us by a user. But at least, if we have a report, we may get interesting details. Ideally, I'd love the constraint, but it may contains sensitive information. So I guess just knowing the length of the constraint (is it null, empty, longer), the length of result in FilteredResult (I assume it'll be 0, but not sure), and the length of `items`, that may help, with some hope, we'll find surprising values here

File: AnkiDroid/src/main/java/com/ichi2/utils/TypedFilter.kt [hunk 2]
```diff
@@ -49,8 +49,10 @@ abstract class TypedFilter<T>(private val getCurrentItems: (() -> List<T>)) : Fi
     @Suppress("UNCHECKED_CAST")
```
[the remark this answers is not in the document]
Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/utils/TypedFilter.kt:49]: there would be an error as  there `Unchecked cast: Any! to List<T>`

**Review by lukstbit — CHANGES_REQUESTED** [review]
These changes do not handle the null related exception as the parameter `FilterResults` can't be null because the Filter class takes great care to make it not null. What's happening is that `filterResults()` is most likely throwing an exception which will make the Filter class to return an empty FilterResults(it has null as the list of results).

So the if clause should check that `results` and `results.values` are not null.

File: AnkiDroid/src/main/java/com/ichi2/utils/TypedFilter.kt (hunk 1 above)
Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/utils/TypedFilter.kt]: waiting for other reviewers

Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/utils/TypedFilter.kt]: We would have a report in the current case too if the application crashes but I am certain this should handle the crash so I am bit not in favour to put try catch here

**Comment by lukstbit** [comment]
@criticalAY The cast `&& results.values is List<*>` is not needed, that's why the `TypedFilter` was created in the first place.

**Comment by criticalAY** [comment]
> @criticalAY The cast `&& results.values is List<*>` is not needed, that's why the `TypedFilter` was created in the first place.

ok

**Review by lukstbit — APPROVED** [review]
LGTM, leaving this open for a bit if Arthur wants to add anything else.
