### PR TITLE
fix: keep sync snackbar anchored correctly

### LINKED ISSUE #20765: FAB/Add button not shown after sync click
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

FAB is not shown once its hidden i.e. user clicks search -> then sync is clicked -> keyboard collapses -> snackbar is shown -> FAB doesnt show

### Expected behaviour

FAB is shown

### Debug info

```text
In latest alpha and even in stable
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by criticalAY**
## Purpose / Description
When the sync toolbar button is tapped while the search action view isexpanded, the keyboard is dismissed (focus leaves the search field) but the action view stays expanded, so the FAB remains hidden. The post-sync snackbar therefore shows unanchored, and the FAB is only restored when the user leaves and returns to the activity.

Also, when search is toggled while a snackbar is already showing, the snackbar's anchor becomes stale, either hovering above a hidden FAB (leaving a gap above the keyboard) or overlapping the FAB when it comes back.

## Fixes
* Fixes  #20765

## Approach
1. `onOptionsItemSelected(R.id.action_sync)` : collapse `toolbarSearchItem` before starting the sync. That fires
   `onMenuItemActionCollapse` -> `showFloatingActionButton()`, so the FAB is back by the time the sync result snackbar appears.
2. `onMenuItemActionExpand`:  after `hideFloatingActionButton()`, null out `activeSnackBar?.anchorView` so a live snackbar drops to sit above the keyboard instead of hovering where the FAB used to be.
3. `onMenuItemActionCollapse`: after `showFloatingActionButton()`, re-anchor `activeSnackBar?.anchorView` to `fabMain` so it sits above the FAB instead of being overlapped by it.

## How Has This Been Tested?
Pixel 10

## Learning (optional, can help others)
NA

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 1]
```diff
@@ -1245,6 +1247,7 @@ open class DeckPicker :
             }
             R.id.action_sync -> {
                 Timber.i("DeckPicker:: Sync button pressed")
+                toolbarSearchItem?.collapseActionView()
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:1250]: Modify the commit message to explain this one

**Review by david-allison — APPROVED** [review]
LGTM

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt (hunk 1 above)
Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:1250]: I am pasting the approach itself from template in commit

**Review by lukstbit — APPROVED** [review]
