### PR TITLE
fix: dispose WebView on PageFragment::onDestroyView 

### LINKED ISSUE #19604: [BUG] ImageOcclusion: Can't access ViewModels from detached fragment
2.23.0beta3

https://ankidroid.org/acra/app/1/bug/361015/report/04ebf166-771b-4dfa-856e-4727a5aaf3a6

```
java.lang.IllegalStateException: Can't access ViewModels from detached fragment
	at androidx.fragment.app.Fragment.getViewModelStore(Fragment.java:428)
	at com.ichi2.anki.pages.ImageOcclusion$special$$inlined$viewModels$default$3.invoke(ImageOcclusion.java:114)
	at com.ichi2.anki.pages.ImageOcclusion$special$$inlined$viewModels$default$3.invoke(ImageOcclusion.java:112)
	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.java:49)
	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.java:35)
	at com.ichi2.anki.pages.ImageOcclusion.getViewModel(ImageOcclusion.kt:50)
	at com.ichi2.anki.pages.ImageOcclusion.access$getViewModel(ImageOcclusion.kt:47)
	at com.ichi2.anki.pages.ImageOcclusion$onCreateWebViewClient$1.onPageFinished(ImageOcclusion.kt:91)
	at WV.u23.e(chromium-TrichromeWebViewGoogle6432.aab-stable-744410633:12)
	at WV.gh.handleMessage(chromium-TrichromeWebViewGoogle6432.aab-stable-744410633:250)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loopOnce(Looper.java:273)
	at android.os.Looper.loop(Looper.java:363)
	at android.app.ActivityThread.main(ActivityThread.java:10060)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
It appears `onPageFinished` was called at a bad time. This is likely due to the WebView not being disposed

## Fixes
* Should fix #19604
* and #19622

## Approach
Dispose the WebView

I included #19611, as I felt expanding `runCatching` was useful, and there was a minor conflict

* https://github.com/ankidroid/Anki-Android/pull/19611

## How Has This Been Tested?
I opened and closed:

* DeckOptions
* Statistics

Pixel 9, API 35 emulator

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt [hunk 1]
```diff
@@ -399,3 +382,29 @@ object CrashReportService {
...
+ * runReportingException("callingMethod", onlyIfSilent = true) {
+ *     doSomethingRisky()
+ * }
+ * ```
+ *
+ * @param origin Data logged to Timber, and provided as the 'origin' field in the error report
+ * @param onlyIfSilent Skip crash report if the crash reporting service is not 'always accept'
+ * @param block Code to execute
+ */
+fun <T> runReportingException(
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt]: I'm probably going to use this a lot, so nitpicking on the name is appreciated. 
`runCatching` is already taken.

`runReporting` potentially?

File: AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt [hunk 2]
```diff
@@ -399,3 +383,37 @@ object CrashReportService {
...
+    origin: String?,
+    onlyIfSilent: Boolean = false,
+    block: () -> T,
+): Result<T> =
+    try {
+        Result.success(block())
+    } catch (e: Throwable) {
+        if (e is CancellationException) throw e
```
Comment (lukstbit) [inline AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt]: Is this possible if the block is not suspendable?

File: AnkiDroid/src/main/java/com/ichi2/anki/workarounds/SafeWebViewLayout.kt [hunk 3]
```diff
@@ -146,6 +161,32 @@ open class SafeWebViewLayout :
...
+    /**
+     * Destroys the internal state of the wrapped [webView]
+     *
+     * No other methods may be called on this WebView after destroy
+     */
+    @MainThread
+    fun safeDestroy() {
+        Timber.d("Destroying WebView")
+
+        runReportingException("safeDestroy", onlyIfSilent = true) {
```
Comment (lukstbit) [inline AnkiDroid/src/main/java/com/ichi2/anki/workarounds/SafeWebViewLayout.kt]: Why two identical calls here?

File: AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt (hunk 1 above)
Comment (lukstbit) [reply AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt]: I would use _runCatchingWithReport_.

The implementation is identical with _runCatching_ the only difference being that we report the exception. It would also make the method more discoverable because when I'm thinking about this usage(try-catch and return Result) I'm going to type _runCatc..._ and see both versions.

**Review by lukstbit — COMMENTED** [review]
Left some comments, but looks good.

File: AnkiDroid/src/main/java/com/ichi2/anki/workarounds/SafeWebViewLayout.kt (hunk 3 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/workarounds/SafeWebViewLayout.kt]: The second call acts as a `try...catch` within a `finally`, to ensure that we try `webView.destroy()` even if the "pre-destroy" operations fail

I'll add a comment

File: AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt (hunk 2 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt]: Gah! I made a mental note of this but didn't implement it, thank you!

File: AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt (hunk 1 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt]: There is a difference: `runCatching` catches `Throwable` (which IMO is nasty/unexpected)

But: I'm onboard if you're happy. I was hoping for something a little less verbose, but this is better than what I have

EDIT: Implemented and added this to the method comment

**Review by lukstbit — APPROVED** [review]
Even better!

**Review by mikehardy — APPROVED** [review]
LGTM
