### PR TITLE
Ensure that both Drawable kt are compatible

### LINKED ISSUE #10173: [Bug] Build Broken
```
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/wildplot/android/rendering/DrawableContainer.kt: (23, 1): Class 'DrawableContainer' is not abstract and does not implement abstract member public abstract fun paint(g: GraphicsWrap?): Unit defined in com.wildplot.android.rendering.interfaces.Drawable
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/wildplot/android/rendering/DrawableContainer.kt: (23, 25): Cannot weaken access privilege 'public' for 'isOnFrame' in 'Drawable'
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/wildplot/android/rendering/DrawableContainer.kt: (23, 37): 'isOnFrame' hides member of supertype 'Drawable' and needs 'override' modifier
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/wildplot/android/rendering/DrawableContainer.kt: (23, 57): Cannot weaken access privilege 'public' for 'isCritical' in 'Drawable'
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/wildplot/android/rendering/DrawableContainer.kt: (23, 69): 'isCritical' hides member of supertype 'Drawable' and needs 'override' modifier
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/wildplot/android/rendering/DrawableContainer.kt: (29, 5): 'paint' overrides nothing
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/wildplot/android/rendering/DrawableContainer.kt: (35, 5): 'isOnFrame' overrides nothing
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/wildplot/android/rendering/DrawableContainer.kt: (39, 5): 'isClusterable' overrides nothing
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/wildplot/android/rendering/DrawableContainer.kt: (43, 5): 'isCritical' overrides nothing
```

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
This was obtained by reverting DrawableContainer translation and retranslating
it.  The translation result was different. Probably because Drawable was already
translated.

I believe a general rule here should be that we should not translate a child
class until its parents are translated.

Fixes #10173

### CODE REVIEW

File: AnkiDroid/src/main/java/com/wildplot/android/rendering/DrawableContainer.kt [hunk 1]
```diff
@@ -16,34 +16,26 @@
...
-class DrawableContainer(private val isOnFrame: Boolean, private val isCritical: Boolean) : Drawable {
+@SuppressLint("NonPublicNonStaticFieldName")
+class DrawableContainer(override val isOnFrame: Boolean, override val isCritical: Boolean) : Drawable {
     private val drawableVector = Vector<Drawable>()
     fun addDrawable(drawable: Drawable) {
         drawableVector.add(drawable)
     }
 
-    override fun paint(g: GraphicsWrap) {
+    override fun paint(g: GraphicsWrap?) {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/wildplot/android/rendering/DrawableContainer.kt:31]: KotlinCleanup: probably shouldn't be nullable

File: AnkiDroid/src/main/java/com/wildplot/android/rendering/DrawableContainer.kt [hunk 2]
```diff
@@ -16,34 +16,26 @@
...
 package com.wildplot.android.rendering
 
+import android.annotation.SuppressLint
 import com.wildplot.android.rendering.graphics.wrapper.GraphicsWrap
 import com.wildplot.android.rendering.interfaces.Drawable
-import java.util.Vector
+import java.util.*
 
-class DrawableContainer(private val isOnFrame: Boolean, private val isCritical: Boolean) : Drawable {
+@SuppressLint("NonPublicNonStaticFieldName")
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/wildplot/android/rendering/DrawableContainer.kt:24]: Likely not necessary

**Review by david-allison-1 — APPROVED** [review]
Fixes #10173 ?

LGTM, comments are optional. Given it's a build failure, merge at will.

**Comment by codingtosh** [comment]
How about, in Drawable.kt, 

```
fun isOnFrame() : Boolean
fun isClusterable() : Boolean
fun isCritical() : Boolean
```

instead of 

```
val isOnFrame: Boolean
val isClusterable: Boolean
val isCritical: Boolean
```

Reconverting DrawableContainer fixes it for DrawableContainer but other files that I have converted are still breaking after Drawable.kt got merged. Also, val introduces slightly different behaviour from the java code as it introduces getters. 

@Arthur-Milchior @david-allison-1 WDYT?

**Comment by david-allison-1** [comment]
> How about, in Drawable.kt,
> 
> ```
> fun isOnFrame() : Boolean
> fun isClusterable() : Boolean
> fun isCritical() : Boolean
> ```
> 
> instead of
> 
> ```
> val isOnFrame: Boolean
> val isClusterable: Boolean
> val isCritical: Boolean
> ```
> 
> Reconverting DrawableContainer fixes it for DrawableContainer but other files that I have converted are still breaking after Drawable.kt got merged. Also, val introduces slightly different behaviour from the java code as it introduces getters.
> 
> @Arthur-Milchior @david-allison-1 WDYT?

Is it possible to use use `@get:JvmName()` to rename the getters?

File: AnkiDroid/src/main/java/com/wildplot/android/rendering/DrawableContainer.kt (hunk 1 above)
Comment (Arthur-Milchior) [reply AnkiDroid/src/main/java/com/wildplot/android/rendering/DrawableContainer.kt]: Done

File: AnkiDroid/src/main/java/com/wildplot/android/rendering/DrawableContainer.kt (hunk 2 above)
Comment (Arthur-Milchior) [reply AnkiDroid/src/main/java/com/wildplot/android/rendering/DrawableContainer.kt:23]: Done (especially since field names became method)

**Comment by Arthur-Milchior** [comment]
I added methods in Drawable.kt as suggested. Thanks @codingtosh.
I'll merge once tests are green
