### PR TITLE
Fix floating point numbers for steps in Deck Options

### LINKED ISSUE #8995: [Bug] Interval after the decimal point is not reflected accurately in the deck option
###### Reproduction Steps

1. Enter 0.1 for the deck option interval
Screenshot_20210528-190651991_1

###### Expected Result

It is displayed as 0.1.

###### Actual Result

Screenshot_20210528-190655061_1

###### Debug info
AnkiDroid Version = 2.16alpha00

Android Version = 10

Manufacturer = asus

Model = ASUS_I01WD

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; ASUS_I01WD Build/QP1A.190711.005; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.77 Mobile Safari/537.36

ACRA UUID = 53fcb5bb-27cb-45eb-86a1-052df39ff3f3

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by Peyman-hme**
## Purpose / Description
`JSONArray` has a `put` method with double input. When we set its input with float variable, it was casted to double and then we may see a number with different value.

## Fixes
Fixes #8995

## Approach
Change `float` variable to `double`.

## How Has This Been Tested?

Emulated device Samsung A50 SDK 28.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/preferences/StepsPreference.java [hunk 1]
```diff
@@ -135,17 +136,17 @@ public static JSONArray convertToJSON(String steps) {
...
+                double d = Double.parseDouble(s);
                 // 0 or less is not a valid step.
-                if (f <= 0) {
+                if (d <= 0) {
                     return null;
                 }
                 // Use whole numbers if we can (but still allow decimals)
-                int i = (int) f;
-                if (i == f) {
+                int i =(int) d;
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/preferences/StepsPreference.java:145]: spacing nitpick, nothing more 
```suggestion
                int i = (int) d;
```

**Review by mikehardy — CHANGES_REQUESTED** [review]
I had the tiniest formatting nitpick
Everything else appears fine, I'll approve the CI run, can you post a screenshot that shows the correct behavior? That would really help us verify it

Thanks!

File: AnkiDroid/src/main/java/com/ichi2/preferences/StepsPreference.java (hunk 1 above)
Comment (Peyman-hme) [reply AnkiDroid/src/main/java/com/ichi2/preferences/StepsPreference.java]: Sure.
Screenshots:
Floating_1

And the result is:

Floating_2

**Review by mikehardy — APPROVED** [review]
A thing of beauty! Thank you!

**Comment by david-allison-1** [comment]
I'd like to take a quick look at this on my phone before a merge

Main concern would be regarding syncing to Anki (whether the rust can cope with higher precision)

And whether this fixes the issue: I don't see how adding more significant digits will help if the number isn't representable in binary

**Review by david-allison-1 — APPROVED** [review]
Surprised: all looks good, cheers!

**Comment by mikehardy** [comment]
Hi there!

Apologies for the delay, and if you're already submitted something to OpenCollective for May 2021 PRs merged, you may feel free to ignore this.

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for May 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged in May)

Thanks!
