### PR TITLE
sync: fix media sync with trailing slash on media sync url

### LINKED ISSUE #6436: Syncing error, type: 404, message:
###### Reproduction Steps

1.  I use [ankicommunity/anki-sync-server][ankisyncserver]
2.  I set the urls of my sync server in the app under **Settings** -> **Advanced** -> **Custom sync server** 
3.  I tap the sync button on the main activity

###### Expected Result

Synchronization success

###### Actual Result

I get the message _"Syncing error, type: 404, message:"_

###### Debug info

My media sync url has a slash (`/`) at the end. Therefore a POST request to `https://my.sync.server/msync//begin` is made. That request fails because of the duplicated slash (`/`).

Relevant log entry of the sync server:

> [2020-06-11 19:57:22,347]:INFO:ankisyncd.http:172.24.0.1 "POST /msync//begin HTTP/1.0" 404 52 

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))
    - I have confirmed, that the issue does occur with the current master

I will provide a merge request by myself soon.

  [ankisyncserver]: https://github.com/ankicommunity/anki-sync-server

### PR DESCRIPTION
**Pull request by kalehmann**
Prevent duplicated slashes in the media sync url

## Purpose / Description

If my Media sync url under **Settings** -> **Advanced** -> **Custom sync server**  ends with a slash, I get a 404 on synchronization because of a duplicate slash (`/`) in the url. 

This PR adds a check, that prevents the duplicate slash.

## Fixes
Fixes #6436

## Approach

I add a check to [`RemoteMediaServer::syncURL`][remotemediaserver] that prevents the second slash from being added to the url if it already ends with an slash.

## How Has This Been Tested?

I installed [ankicommunity/anki-sync-server][ankisyncserver] locally.
Then I added my custom sync server under **Settings** -> **Advanced** -> **Custom sync server**.
My _Media sync url_  ends with a slash (`\`).
When I tap the sync button in the main activity everything synchronizes without an error.

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] ~~You have commented your code, particularly in hard-to-understand areas~~
- [x] You have performed a self-review of your own code

  [ankisyncserver]: https://github.com/ankicommunity/anki-sync-server
  [remotemediaserver]: https://github.com/ankidroid/Anki-Android/blob/bd641a86a179f4a4f2431e110f2f74d732b2002d/AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteMediaServer.java#L69

### CODE REVIEW

**Comment by mikehardy** [comment]
I dunno - I can't see why this is a problem now. It's my understanding that you can have as many `//////` in a row as you like and it's still a valid URI

**Comment by kalehmann** [comment]
According to [RFC 2339] 

>  The path may consist of a sequence of path segments separated by a single slash "/" character.

Therefore the url does not seem valid.

  [rfc2396]: https://www.ietf.org/rfc/rfc2396.txt

**Comment by kalehmann** [comment]
> What if someone accidentally inputs '//' in their sync server URL? Why wouldn't that work without any parsing at all on our end?

I think a user has a better chance of recognizing the duplicated slash as cause of the problem than a single one 🤔

**Comment by kalehmann** [comment]
My intention was to sanitize the users input regardless of the urls last character.

Nevertheless I will update this PR and check the users input when they enter the media sync url.

**Comment by kalehmann** [comment]
@mikehardy can you please review the changes again?

**Comment by mikehardy** [comment]
Hey @kalehmann - thanks - yes I will review

I will still review for the actual code, but you've altered all of the strings. You must not do that, only alter strings in `values/` not in the translations. Those are pulled in automatically from the crowdin platform and are a *full clobber* every time.

Prior to merge you'll need to revert all string changes except those to `values/`

File: AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java [hunk 1]
```diff
@@ -380,6 +384,51 @@ private void initSubscreen(String action, PreferenceContext listener) {
...
+                screen = listener.getPreferenceScreen();
+                Preference syncUrlPreference = screen.findPreference("syncBaseUrl");
+                Preference mSyncUrlPreference = screen.findPreference("syncMediaUrl");
+                syncUrlPreference.setOnPreferenceChangeListener((Preference preference, Object newValue) -> {
+                    String newUrl = newValue.toString();
+                    if (!URLUtil.isValidUrl(newUrl)) {
+                        AlertDialog.Builder builder = new AlertDialog.Builder(this);
+                        builder.setTitle(R.string.custom_sync_server_base_url_invalid);
+                        builder.setPositiveButton(R.string.dialog_ok, null);builder.show();
+
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java:396]:
```suggestion
                        new AlertDialog.Builder(this)
                            .setTitle(R.string.custom_sync_server_base_url_invalid);
                            .setPositiveButton(R.string.dialog_ok, null)
                            .show();

```

File: AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java [hunk 2]
```diff
@@ -380,6 +384,51 @@ private void initSubscreen(String action, PreferenceContext listener) {
...
+                        return false;
+                    }
+
+                    URI uri = URI.create(newUrl);
+                    if (!Pattern.matches(".*[^/]*/$", uri.getPath())) {
+                        AlertDialog.Builder builder = new AlertDialog.Builder(this);
+                        builder.setTitle(R.string.custom_sync_server_base_url_single_slash);
+                        builder.setPositiveButton(R.string.dialog_ok, null);builder.show();
+
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java:405]: same as above - it's a fluent API, use the fluency, and since we don't care about the builder after we use it, it does not need a local variable even I don't believe

File: AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java [hunk 3]
```diff
@@ -380,6 +384,51 @@ private void initSubscreen(String action, PreferenceContext listener) {
...
+                    return true;
+                });
+                mSyncUrlPreference.setOnPreferenceChangeListener((Preference preference, Object newValue) -> {
+                    String newUrl = newValue.toString();
+                    if (!URLUtil.isValidUrl(newUrl)) {
+                        AlertDialog.Builder builder = new AlertDialog.Builder(this);
+                        builder.setTitle(R.string.custom_sync_server_media_url_invalid);
+                        builder.setPositiveButton(R.string.dialog_ok, null);builder.show();
+
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java:417]: same as above - it's a fluent API, use the fluency, and since we don't care about the builder after we use it, it does not need a local variable even I don't believe

File: AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java [hunk 4]
```diff
@@ -380,6 +384,51 @@ private void initSubscreen(String action, PreferenceContext listener) {
...
+                        return false;
+                    }
+
+                    URI uri = URI.create(newUrl);
+                    if (!Pattern.matches(".*[^/]*/$", uri.getPath())) {
+                        AlertDialog.Builder builder = new AlertDialog.Builder(this);
+                        builder.setTitle(R.string.custom_sync_server_media_url_single_slash);
+                        builder.setPositiveButton(R.string.dialog_ok, null);builder.show();
+
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java:426]: same as above - it's a fluent API, use the fluency, and since we don't care about the builder after we use it, it does not need a local variable even I don't believe

File: AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java [hunk 5]
```diff
@@ -380,6 +384,51 @@ private void initSubscreen(String action, PreferenceContext listener) {
...
+                    if (!URLUtil.isValidUrl(newUrl)) {
+                        AlertDialog.Builder builder = new AlertDialog.Builder(this);
+                        builder.setTitle(R.string.custom_sync_server_base_url_invalid);
+                        builder.setPositiveButton(R.string.dialog_ok, null);builder.show();
+
+                        return false;
+                    }
+
+                    URI uri = URI.create(newUrl);
+                    if (!Pattern.matches(".*[^/]*/$", uri.getPath())) {
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java:401]: If the URIUtil already says it is valid, why are we checking something else? It is valid or not, isn't it?
Should the URIUtil be extended to do the complete check, or is the second check unnecessary? (this comment applies to the other instance as well

**Comment by mikehardy** [comment]
Also all of the unit tests are failing for some reason? https://travis-ci.org/github/ankidroid/Anki-Android/builds/698235826

File: AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java (hunk 5 above)
Comment (kalehmann) [reply AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java]: I removed the second with the regex, but therefore I used the code from [`HttpSyncer::syncUrl()`](https://github.com/ankidroid/Anki-Android/blob/4de7795423776b6a63d8215194507ac3ee6c5c28/AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.java#L458) in the `req()` method of the HttpSyncer to build the url.

The line `Uri.parse(syncURL()).buildUpon().appendPath(method)` does all the checks for us, whether there is a slash or not.

**Comment by kalehmann** [comment]
> 
> 
> Also all of the unit tests are failing for some reason? https://travis-ci.org/github/ankidroid/Anki-Android/builds/698235826

My bad, should be fixed now

**Comment by kalehmann** [comment]
>  just want to confirm that this will handle existing user base (who may or may not have slashes in all sorts of configurations) well?

I could not think of any problems here. The main difference in the handling of stored urls is that 

1. no slash is added to the stored media sync url in [RemoteMediaServer::syncUrl](https://github.com/ankidroid/Anki-Android/blob/709732d5630c6184ed0871aa85131f194405fd42/AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteMediaServer.java#L69)
2. [Uri.Builder::appendPath](https://developer.android.com/reference/android/net/Uri.Builder#appendPath(java.lang.String)) is used to build the urls for the request. This method should handle any url fine, regardless of a slash at its end.

As long as nobody requires the duplicated slash for their sync server (which would be weird) everything should be fine.

**Comment by mikehardy** [comment]
I agree with your analysis on that final point - can't imagine anyone *requiring* multiple slashes, so de-duplicating should be fine. Thanks @kalehmann !

**Comment by mikehardy** [comment]
Hello! with the 2.14 release we started accepting donations with the stated goal of accepting money from users (the users' way of saying "Thanks!") to support maintenance and development of AnkiDroid.

We are looking through PRs merged in releases going back to release 2.10 (where we have good record keeping of what's in releases) to let our contributors know.

If you'd like to submit an expense related to your work here, to share in a portion of our hopefully-sustainable monthly disbursement, please read here and do so in the next couple of days:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process

This is our first time handling donations and attempting to compensate anyone with these processes, so please be flexible and patient with us

Thank you for your contribution to AnkiDroid!
