### PR TITLE
fix: Changing Note Type is now an `undoableOp`

### LINKED ISSUE #14885: [Bug] Changing Note Type is not an `undoableOp`
* Blocks #14656

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
* #14885
## Fixes
* Fixes #14885
* Unblocks #14656

## Approach
* Extract `withErrorHandling`
* Allow it to handle `suspend` calls
* expose `OpChanges`
* apply with `undoableOp`
* A few refactorings of nullable parameters

## How Has This Been Tested?
Briefly on an API 33 emulator, the AbstractFlashcardViewer now picks up on the changes, AND undo works.

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
LGTM - asking for a second with more Kotlin-savvy and collection/undo savvy...

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt [hunk 1]
```diff
@@ -869,43 +871,18 @@ class NoteEditor : AnkiActivity(), DeckSelectionListener, SubtitleListener, Tags
...
-                    changeNoteType(oldNotetype, newNotetype)
-                } catch (e2: ConfirmModSchemaException) {
-                    // This should never be reached as we explicitly called modSchemaNoCheck()
-                    throw RuntimeException(e2)
-                }
-            }
-            dialog.setConfirm(confirm)
-            showDialogFragment(dialog)
+    private fun changeNoteType(oldNotetype: NotetypeJson, newNotetype: NotetypeJson) =
+        withErrorHandling {
```
Comment (dae) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:875]: A simpler way would be to reuse userAcceptsSchemaChange in the function that calls this

File: AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt [hunk 2]
```diff
@@ -522,14 +522,16 @@ class Notetypes(val col: Collection) {
...
      * */
     fun change(
         m: NotetypeJson,
         nid: NoteId,
         newModel: NotetypeJson,
         fmap: Map<Int, Int?>,
         cmap: Map<Int, Int?>
-    ) {
+    ): OpChanges {
         col.modSchema()
```
Comment (dae) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt:535]: modSchema() will be superfluous if you switch to the above-mentioned function

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt [hunk 3]
```diff
@@ -869,38 +869,14 @@ class NoteEditor : AnkiActivity(), DeckSelectionListener, SubtitleListener, Tags
...
 
-    /**
-     * Change the note type from oldModel to newModel
-     * @throws ConfirmModSchemaException If a full sync will be required
-     */
-    @Throws(ConfirmModSchemaException::class)
-    private fun changeNoteType(oldNotetype: NotetypeJson?, newNotetype: NotetypeJson?) {
         val noteId = mEditorNote!!.id
-        getColUnsafe.notetypes.change(oldNotetype!!, noteId, newNotetype!!, mModelChangeFieldMap!!, mModelChangeCardMap!!)
+        // may throw ConfirmModSchemaException for a full sync, handled in withErrorHandling
```
Comment (dae) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:876]: stale comment, otherwise looks good
