### PR TITLE
fix: controls settings crash in landscape mode

### LINKED ISSUE #18498: Crash on settings > controls in landscape mode
## Steps

1. Open the app in landscape mode.
2. Settings > Controls

## Behaviour

App crashes in landscape mode. Otherwise, everything goes as expected.

## Debug info

```text
AnkiDroid Version = 2.21alpha17 (38fa45924c5fb02ab483d84bb18c0289f5b9aacd)
Backend Version = 0.1.52-anki25.02.7 (25.02.7 98253c81cb3c4d203acec48d6eae6b488bf484d0)
Android Version = 11 (SDK 30)
ProductFlavor = full
Device Info = realme | realme | RMX2193 | RMX2193 | RMX2193 | mt6768
Webview User Agent = Mozilla/5.0 (Linux; Android 11; RMX2193 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/136.0.7103.127 Mobile Safari/537.36
ACRA UUID = cf265e01-9693-407f-984d-61ddf9698fac
FSRS = 2.0.3 (Enabled: true)
Crash Reports Enabled = true
```

___

I tested this on alpha15 and the issue isn't there (probably has to do with the recent changes brayan made).

### PR DESCRIPTION
**Pull request by BrayanDSO**
since Preferences are RecyclerView items, if the tab layout isn't visible when the view is created, its view won't exist and that leads to a crash.

to configure a preference view dynamically, the alternative is to create an individual preference class

## Fixes
* Fixes #18498

## How Has This Been Tested?

Emulator 35

https://github.com/user-attachments/assets/14452e58-74f2-4d02-84e4-ce9cf9004ae6

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/preferences/ControlsTabPreference.kt [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+        defStyleRes: Int = androidx.preference.R.style.Preference,
+    ) : Preference(context, attrs, defStyleAttr, defStyleRes) {
+        init {
+            layoutResource = R.layout.controls_tab_layout
+        }
+
+        private var onTabSelectedListener: TabLayout.OnTabSelectedListener? = null
+
+        fun setOnTabSelectedListener(listener: TabLayout.OnTabSelectedListener) {
+            onTabSelectedListener = listener
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/preferences/ControlsTabPreference.kt:44]: maybe ignorable comment: after this is called, elements where `onBindViewHolder` was already called for won't be updated with the new value

Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/anki/preferences/ControlsTabPreference.kt:44]: What do you suggest?

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/preferences/ControlsTabPreference.kt:44]: Easiest is:

* move `tabLayout` to a nullable local, and assign to the liseners inside `setOnTabSelectedListener` as well as `onBindViewHolder`
* be sure you're cleaning past listeners - addOnTabSelectedListener isn't `setOnTabSelectedListener`, so non-duplicates are kept around

**Review by david-allison — APPROVED** [review]
Cheers!
