### PR TITLE
fix: missing background color on Anki pages

### LINKED ISSUE #15322: [BUG]: Background color in Anki pages isn't set some times
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

- Enable Black theme
- Open the congrats page of a deck.

### Expected behaviour

The background color is always black.

### Actual behaviour

Sometimes, the background color is grey rather than black.
(To reproduce, try to open and close the page multiple times.)

### Debug info

```text
2.17 alpha 16
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
Sometimes the background color was not set

Cause:
`Uncaught TypeError: Cannot read properties of null (reading 'style')`

Because `document.body` was not set yet

## Fixes
* Fixes #15322

## Approach
Wait until `DOMContentLoaded`

## How Has This Been Tested?
Can no longer reproduce on my API 33 emulator

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/pages/PageWebViewClient.kt [hunk 1]
```diff
@@ -91,3 +93,20 @@ open class PageWebViewClient : WebViewClient() {
         return super.shouldOverrideUrlLoading(view, request)
     }
 }
+
+fun WebView.evaluateAfterDOMContentLoaded(script: String, resultCallback: ValueCallback<String>? = null) {
+    evaluateJavascript(
+        """
+                var codeToRun = function() {
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/pages/PageWebViewClient.kt:100]: nit: you could use `@Language` to give syntax highlighting to it

**Review by BrayanDSO — APPROVED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/pages/PageWebViewClient.kt (hunk 1 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/pages/PageWebViewClient.kt:100]: It looked terrible when I tried

Screenshot 2024-03-10 at 22 18 21

**Review by lukstbit — APPROVED** [review]
