### PR TITLE
Correct Device "Back" Button in Restore From Backup

### LINKED ISSUE #5833: Restore From Backup - Pressing Device "Back" Button should return to Deck Browser
###### Reproduction Steps

1. Open Deck Browser
2. Select "Restore From Backup"
3. Accept the confirmation
4. Press the physical "Back" button on the device.

###### Expected Result

The user returns to the deck browser

###### Actual Result

The user is re-shown the confirmation to restore from backup.

This works correctly when using the "Back" button on the dialog.

###### Debug info
AnkiDroid Version = 2.10alpha50

Android Version = 9

ACRA UUID = 5a0ff95e-d1bb-46d6-9a61-d425ab3ab53d

###### Research
[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
[x] I have searched for similar existing issues here and on the user forum

----

Simple issue for someone to get familiar with the project

### PR DESCRIPTION
**Pull request by Sc-Weng**
## Purpose / Description

Now, AnkiDroid can return to deck browser successfully when visit "Restore From Backup" Dialog while the previous version will return to the confirmation dialog.

## Fixes
Fixes #5833

## Approach
For MaterialDialog, adding a Listener by setOnKeyListener() can moniter system's back key. Rewrite system back key operation by method dismissAllDialogFragments() which make its function same as button "Cancel".

## How Has This Been Tested?

1. Open Deck Browser
2. Select "Restore From Backup"
3. Accept the confirmation
4. Press the physical "Back" button on the device.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java [hunk 1]
```diff
@@ -223,7 +223,16 @@ public MaterialDialog onCreateDialog(Bundle savedInstanceState) {
                                         return true;
                                     });
                 }
-                return builder.show();
+                MaterialDialog materialDialog = builder.build();
+                materialDialog.setOnKeyListener((dialog, keyCode, event) -> {
+                    if (keyCode == KeyEvent.KEYCODE_BACK) {
+                        Timber.i("catch");
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java:229]: Without a bit more specifics on where the log came from, it will be hard to trace, suggest 👇 

```suggestion
                        Timber.i("DIALOG_RESTORE_BACKUP caught hardware back button");
```

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java [hunk 2]
```diff
@@ -223,7 +223,16 @@ public MaterialDialog onCreateDialog(Bundle savedInstanceState) {
...
+                        dismissAllDialogFragments();
+                        return true;
+                    }
+                    return false;
+                });
+                return materialDialog;
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java:235]: It is the responsibility of each of the dialogs to actually show the dialog as well I think? I think you have to do that call? I'm not sure how this would have tested correctly without it but maybe I am missing something so this suggestion may not be correct

```suggestion
                });
                materialDialog.show();
                return materialDialog;
```

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java (hunk 1 above)
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java:229]: Nice to have: Make the log a little more expressive 
```suggestion
                        Timber.i("Back Pressed - Closing 'Restore From Backup'");
```

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java (hunk 2 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java:235]: This is in an `AsyncDialogFragment`: https://developer.android.com/reference/android/app/DialogFragment#onCreateDialog(android.os.Bundle)

Doesn't seem to specify that you need to show the returned dialog, many examples don't, and `show()` is called during `onStart`

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java:235]: Okay - I was basing more off all the other cases showing. Seemed it should be conformant based on other usage locally to this code

**Comment by david-allison-1** [comment]
Hi @Sc-Weng 

We're still getting compilation errors:

https://travis-ci.org/github/ankidroid/Anki-Android/jobs/693155967

```
> Task :AnkiDroid:compileReleaseJavaWithJavac
C:\Users\travis\build\ankidroid\Anki-Android\AnkiDroid\src\main\java\com\ichi2\anki\dialogs\DatabaseErrorDialog.java:228: error: cannot find symbol
                    if (keyCode == KeyEvent.KEYCODE_BACK) {
                                   ^
  symbol:   variable KeyEvent
  location: class DatabaseErrorDialog
C:\Users\travis\build\ankidroid\Anki-Android\AnkiDroid\src\main\java\com\ichi2\anki\dialogs\DatabaseErrorDialog.java:229: error: cannot find symbol
                        Timber.i("DIALOG_RESTORE_BACKUP caught hardware back button");
                        ^
  symbol:   variable Timber
  location: class DatabaseErrorDialog
> Task :AnkiDroid:compileReleaseJavaWithJavac FAILED
```

You can fix this with the Alt+Enter menu in Android Studio

**Comment by Sc-Weng** [comment]
@david-allison-1 I just commit the file with correct import statement, hope it can pass the test this time.
