### PR TITLE
Fix: Media Sync PoisonError, and a couple of media sync issues

### LINKED ISSUE #17382: [Sync] `Result::unwrap()` on an `Err` value: PoisonError { .. } -> Panic at anki/rslib/src/backend/sync.rs:249: called `Option::unwrap()` on a `None` value
https://ankidroid.org/acra/app/1/bug/252979/report/7a438d99-acee-4da5-be87-798e0cee6f29

```
net.ankiweb.rsdroid.BackendException$BackendDbException$BackendDbFileTooOldException: called `Result::unwrap()` on an `Err` value: PoisonError { .. }
	at net.ankiweb.rsdroid.BackendException$BackendFatalError.<init>(BackendException.java:99)
	at net.ankiweb.rsdroid.BackendException$Companion.fromError(BackendException.kt:108)
	at net.ankiweb.rsdroid.BackendKt.unpackResult(Backend.kt:281)
	at net.ankiweb.rsdroid.BackendKt.access$unpackResult(Backend.kt:1)
	at net.ankiweb.rsdroid.Backend.runMethodRaw$lambda$1(Backend.kt:118)
	at net.ankiweb.rsdroid.Backend.withBackend(Backend.kt:131)
	at net.ankiweb.rsdroid.Backend.runMethodRaw(Backend.kt:117)
	at anki.backend.GeneratedBackend.openCollectionRaw(GeneratedBackend.kt:112)
	at anki.backend.GeneratedBackend.openCollection(GeneratedBackend.kt:119)
	at net.ankiweb.rsdroid.Backend.openCollection(Backend.kt:98)
	at net.ankiweb.rsdroid.Backend.openCollection(Backend.kt:57)
	at com.ichi2.libanki.Storage.openDB$AnkiDroid_playRelease(Storage.kt:52)
	at com.ichi2.libanki.Collection.reopen(Collection.kt:213)
	at com.ichi2.libanki.Collection.reopen$default(Collection.kt:210)
	at com.ichi2.libanki.Collection.<init>(Collection.kt:145)
	at com.ichi2.libanki.Storage.collection(Storage.kt:40)
	at com.ichi2.anki.CollectionManager.ensureOpenInner(CollectionManager.kt:245)
	at com.ichi2.anki.CollectionManager.withCol$lambda$1(CollectionManager.kt:118)
	at com.ichi2.anki.CollectionManager$withQueue$3.invokeSuspend(CollectionManager.kt:103)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.java:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)

```

```
--------- beginning of main
11-06 11:52:51.195 I/AnkiDroid(13131): DeckPicker::x::onPause
11-06 11:52:51.196 I/AnkiDroid(13131): DeckPicker::x::onStop
11-06 11:52:51.228 I/AnkiDroid(13131): DeckPicker::x::onViewDestroyed
11-06 11:52:51.228 I/AnkiDroid(13131): DeckPicker::x::onAttach
11-06 11:52:51.229 I/AnkiDroid(13131): DeckPicker::x::onCreate
11-06 11:52:51.236 W/AnkiDroid(13131): x/ java.io.IOException: Cannot run program "sqlite3": error=2, No such file or directory
11-06 11:52:51.236 W/AnkiDroid(13131): 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at java.lang.Runtime.exec(Runtime.java:712)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at java.lang.Runtime.exec(Runtime.java:536)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at java.lang.Runtime.exec(Runtime.java:433)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at com.ichi2.anki.dialogs.DatabaseErrorDialog.onCreateDialog(DatabaseErrorDialog.kt:91)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:925)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:839)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1760)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:547)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:286)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2211)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2106)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2049)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at androidx.fragment.app.FragmentManager.executePendingTransactions(FragmentManager.java:779)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at com.ichi2.anki.AnkiActivity$Companion.showDialogFragment(AnkiActivity.java:702)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at com.ichi2.anki.AnkiActivity$Companion.showDialogFragment(AnkiActivity.java:687)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at com.ichi2.anki.AnkiActivity.showDialogFragment$lambda$4(AnkiActivity.kt:462)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at android.app.Activity.runOnUiThread(Activity.java:7865)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at com.ichi2.anki.AnkiActivity.showDialogFragment(AnkiActivity.kt:461)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at com.ichi2.anki.AnkiActivity.showAsyncDialogFragment(AnkiActivity.kt:489)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at com.ichi2.anki.DeckPicker.onCreate$lambda$13(DeckPicker.kt:473)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at com.ichi2.anki.AnkiActivity.showAsyncDialogFragment(AnkiActivity.kt:473)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at com.ichi2.anki.DeckPicker.showDatabaseErrorDialog(DeckPicker.kt:1697)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at com.ichi2.anki.dialogs.DatabaseErrorDialog.onCreateDialog$lambda$10$lambda$9(DatabaseErrorDialog.kt:196)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at com.ichi2.utils.AlertDialogFacadeKt.listItems$lambda$13(AlertDialogFacade.kt:335)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at androidx.appcompat.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1068)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at android.widget.AdapterView.performItemClick(AdapterView.java:376)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1362)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3658)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at android.widget.AbsListView$3.run(AbsListView.java:4844)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at android.os.Handler.handleCallback(Handler.java:958)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at android.os.Looper.loopOnce(Looper.java:230)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at android.os.Looper.loop(Looper.java:319)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at android.app.ActivityThread.main(ActivityThread.java:8919)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at java.lang.reflect.Method.invoke(Native Method)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
11-06 11:52:51.236 W/AnkiDroid(13131): Caused by: java.io.IOException: error=2, No such file or directory
11-06 11:52:51.236 W/AnkiDroid(13131): 	at java.lang.UNIXProcess.forkAndExec(Native Method)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at java.lang.ProcessImpl.start(ProcessImpl.java:141)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
11-06 11:52:51.236 W/AnkiDroid(13131): 	... 32 more
11-06 11:52:51.236 W/AnkiDroid(13131): 
11-06 11:52:51.236 W/AnkiDroid(13131): java.io.IOException: Cannot run program "sqlite3": error=2, No such file or directory
11-06 11:52:51.236 W/AnkiDroid(13131): 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at java.lang.Runtime.exec(Runtime.java:712)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at java.lang.Runtime.exec(Runtime.java:536)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at java.lang.Runtime.exec(Runtime.java:433)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at com.ichi2.anki.dialogs.DatabaseErrorDialog.onCreateDialog(DatabaseErrorDialog.kt:91)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:925)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:839)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1760)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:547)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:286)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2211)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2106)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2049)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at androidx.fragment.app.FragmentManager.executePendingTransactions(FragmentManager.java:779)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at com.ichi2.anki.AnkiActivity$Companion.showDialogFragment(AnkiActivity.java:702)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at com.ichi2.anki.AnkiActivity$Companion.showDialogFragment(AnkiActivity.java:687)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at com.ichi2.anki.AnkiActivity.showDialogFragment$lambda$4(AnkiActivity.kt:462)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at android.app.Activity.runOnUiThread(Activity.java:7865)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at com.ichi2.anki.AnkiActivity.showDialogFragment(AnkiActivity.kt:461)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at com.ichi2.anki.AnkiActivity.showAsyncDialogFragment(AnkiActivity.kt:489)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at com.ichi2.anki.DeckPicker.onCreate$lambda$13(DeckPicker.kt:473)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at com.ichi2.anki.AnkiActivity.showAsyncDialogFragment(AnkiActivity.kt:473)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at com.ichi2.anki.DeckPicker.showDatabaseErrorDialog(DeckPicker.kt:1697)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at com.ichi2.anki.dialogs.DatabaseErrorDialog.onCreateDialog$lambda$10$lambda$9(DatabaseErrorDialog.kt:196)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at com.ichi2.utils.AlertDialogFacadeKt.listItems$lambda$13(AlertDialogFacade.kt:335)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at androidx.appcompat.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1068)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at android.widget.AdapterView.performItemClick(AdapterView.java:376)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1362)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3658)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at android.widget.AbsListView$3.run(AbsListView.java:4844)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at android.os.Handler.handleCallback(Handler.java:958)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at android.os.Looper.loopOnce(Looper.java:230)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at android.os.Looper.loop(Looper.java:319)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at android.app.ActivityThread.main(ActivityThread.java:8919)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at java.lang.reflect.Method.invoke(Native Method)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
11-06 11:52:51.236 W/AnkiDroid(13131): Caused by: java.io.IOException: error=2, No such file or directory
11-06 11:52:51.236 W/AnkiDroid(13131): 	at java.lang.UNIXProcess.forkAndExec(Native Method)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at java.lang.ProcessImpl.start(ProcessImpl.java:141)
11-06 11:52:51.236 W/AnkiDroid(13131): 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
11-06 11:52:51.236 W/AnkiDroid(13131): 	... 32 more
11-06 11:52:51.275 I/AnkiDroid(13131): DeckPicker::x::onStart
11-06 11:52:51.275 I/AnkiDroid(13131): DeckPicker::x::onResume
11-06 11:52:53.538 I/AnkiDroid(13131): (Re)opening Database: /storage/emulated/0/Android/data/com.ichi2.anki/files/AnkiDroid/collection.anki2
11-06 11:52:53.554 I/AnkiDroid(13131): DeckPicker::onPause
11-06 11:52:53.554 I/AnkiDroid(13131): DeckPicker::x::onPause
11-06 11:52:53.554 I/AnkiDroid(13131): DeckPicker::x::onStop
11-06 11:52:53.554 I/AnkiDroid(13131): DeckPicker::x::onViewDestroyed
11-06 11:52:53.555 I/AnkiDroid(13131): DeckPicker::x::onDestroy
11-06 11:52:53.555 I/AnkiDroid(13131): DeckPicker::x::onDetach
11-06 11:52:53.555 I/AnkiDroid(13131): DeckPicker::x::onDestroy
11-06 11:52:53.555 I/AnkiDroid(13131): DeckPicker::x::onDetach
11-06 11:52:53.555 I/AnkiDroid(13131): DeckPicker::x::onDestroy
11-06 11:52:53.555 I/AnkiDroid(13131): DeckPicker::x::onDetach
11-06 11:52:53.565 E/AnkiDroid(13131): F3/ q7.c: called `Result::unwrap()` on an `Err` value: PoisonError { .. }
11-06 11:52:53.565 E/AnkiDroid(13131): 	at net.ankiweb.rsdroid.BackendException$BackendFatalError.<init>(BackendException.java:99)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at net.ankiweb.rsdroid.BackendException$Companion.fromError(BackendException.kt:108)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at net.ankiweb.rsdroid.BackendKt.unpackResult(Backend.kt:281)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at net.ankiweb.rsdroid.BackendKt.access$unpackResult(Backend.kt:1)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at net.ankiweb.rsdroid.Backend.runMethodRaw$lambda$1(Backend.kt:118)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at net.ankiweb.rsdroid.Backend.withBackend(Backend.kt:131)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at net.ankiweb.rsdroid.Backend.runMethodRaw(Backend.kt:117)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at anki.backend.GeneratedBackend.openCollectionRaw(GeneratedBackend.kt:112)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at anki.backend.GeneratedBackend.openCollection(GeneratedBackend.kt:119)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at net.ankiweb.rsdroid.Backend.openCollection(Backend.kt:98)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at net.ankiweb.rsdroid.Backend.openCollection(Backend.kt:57)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at com.ichi2.libanki.Storage.openDB$AnkiDroid_playRelease(Storage.kt:52)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at com.ichi2.libanki.Collection.reopen(Collection.kt:213)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at com.ichi2.libanki.Collection.reopen$default(Collection.kt:210)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at com.ichi2.libanki.Collection.<init>(Collection.kt:145)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at com.ichi2.libanki.Storage.collection(Storage.kt:40)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at com.ichi2.anki.CollectionManager.ensureOpenInner(CollectionManager.kt:245)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at com.ichi2.anki.CollectionManager.withCol$lambda$1(CollectionManager.kt:118)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at com.ichi2.anki.CollectionManager$withQueue$3.invokeSuspend(CollectionManager.kt:103)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.java:111)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
11-06 11:52:53.565 E/AnkiDroid(13131): 
11-06 11:52:53.565 E/AnkiDroid(13131): net.ankiweb.rsdroid.BackendException$BackendDbException$BackendDbFileTooOldException: called `Result::unwrap()` on an `Err` value: PoisonError { .. }
11-06 11:52:53.565 E/AnkiDroid(13131): 	at net.ankiweb.rsdroid.BackendException$BackendFatalError.<init>(BackendException.java:99)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at net.ankiweb.rsdroid.BackendException$Companion.fromError(BackendException.kt:108)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at net.ankiweb.rsdroid.BackendKt.unpackResult(Backend.kt:281)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at net.ankiweb.rsdroid.BackendKt.access$unpackResult(Backend.kt:1)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at net.ankiweb.rsdroid.Backend.runMethodRaw$lambda$1(Backend.kt:118)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at net.ankiweb.rsdroid.Backend.withBackend(Backend.kt:131)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at net.ankiweb.rsdroid.Backend.runMethodRaw(Backend.kt:117)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at anki.backend.GeneratedBackend.openCollectionRaw(GeneratedBackend.kt:112)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at anki.backend.GeneratedBackend.openCollection(GeneratedBackend.kt:119)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at net.ankiweb.rsdroid.Backend.openCollection(Backend.kt:98)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at net.ankiweb.rsdroid.Backend.openCollection(Backend.kt:57)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at com.ichi2.libanki.Storage.openDB$AnkiDroid_playRelease(Storage.kt:52)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at com.ichi2.libanki.Collection.reopen(Collection.kt:213)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at com.ichi2.libanki.Collection.reopen$default(Collection.kt:210)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at com.ichi2.libanki.Collection.<init>(Collection.kt:145)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at com.ichi2.libanki.Storage.collection(Storage.kt:40)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at com.ichi2.anki.CollectionManager.ensureOpenInner(CollectionManager.kt:245)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at com.ichi2.anki.CollectionManager.withCol$lambda$1(CollectionManager.kt:118)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at com.ichi2.anki.CollectionManager$withQueue$3.invokeSuspend(CollectionManager.kt:103)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.java:111)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
11-06 11:52:53.565 E/AnkiDroid(13131): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
11-06 11:52:53.685 I/AnkiDroid(13131): notification permission: false
11-06 11:52:53.685 I/AnkiDroid(13131): DeckPicker::onResume
```

### LINKED ISSUE #18542: 2.21alpha20: Crash if aborting media sync from notification
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

* Don't keep activities is on 
* new profile
* Sync from AnkiWeb (one way, download)
* move to desktop
* Abort media sync
* Crash Dialog

### Expected behaviour

No crash dialog

### Debug info

```text
AnkiDroid Version = 2.21alpha20-debug (89a5f833b75c1fb3ec55ccb018baf27c0ebb1714)  
Backend Version = 0.1.54-anki25.02.7 (25.02.7 98253c81cb3c4d203acec48d6eae6b488bf484d0)  
Android Version = 15 (SDK 35)  
ProductFlavor = play  
Device Info = Google | google | caiman | caiman | Pixel 9 Pro | caiman  
Webview User Agent = Mozilla/5.0 (Linux; Android 15; Pixel 9 Pro Build/BP1A.250505.005.A1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/137.0.7151.88 Mobile Safari/537.36  
ACRA UUID = 115a143e-8b61-4698-bac9-4a9dbf4d8beb  
FSRS = 2.0.3 (Enabled: true)  
Crash Reports Enabled = false
```

### (Optional) Anything else you want to share?

```
2025-06-16 17:39:00.336  1306-5580  rsdroid                 com.ichi2.anki.debug                 D  anki::media::files: write fname="1000BEW_B01_U05_092.jpg"
2025-06-16 17:39:00.507  1306-1306  DayRolloverHandler      com.ichi2.anki.debug                 V  received android.intent.action.TIME_TICK
2025-06-16 17:39:00.520  1306-1586  DayRolloverHandler      com.ichi2.anki.debug                 I  day cutoff changed 1750129200 -> 1750125600
2025-06-16 17:39:00.520  1306-1586  DayRolloverHandler      com.ichi2.anki.debug                 I  updating study queues
2025-06-16 17:39:00.524  1306-1586  AnkiDroidApp            com.ichi2.anki.debug                 D  ChangeSubscriber - opExecuted called with changes: # anki.collection.OpChanges@7d4149f5
                                                                                                    study_queues: true
2025-06-16 17:39:00.525  1306-1586  DeckPicker...$Companion com.ichi2.anki.debug                 D  Fetching appWidgetIds for provider: com.ichi2.widget.deckpicker.DeckPickerWidget
2025-06-16 17:39:00.526  1306-1586  DeckPicker...$Companion com.ichi2.anki.debug                 D  AppWidgetIds to update: 
2025-06-16 17:39:00.526  1306-1586  CardAnalys...$Companion com.ichi2.anki.debug                 D  Fetching appWidgetIds for provider: com.ichi2.widget.cardanalysis.CardAnalysisWidget
2025-06-16 17:39:00.527  1306-1586  CardAnalys...$Companion com.ichi2.anki.debug                 D  AppWidgetIds to update: 
2025-06-16 17:39:00.828  1306-1306  WM-SystemFgDispatcher   com.ichi2.anki.debug                 I  Stopping foreground work for Intent { act=ACTION_CANCEL_WORK dat=workspec://314c6062-a1cd-41e6-9535-5f0a847cf6e7/... flg=0x10000000 cmp=com.ichi2.anki.debug/androidx.work.impl.foreground.SystemForegroundService bnds=[126,1264][267,1372] (has extras) }
2025-06-16 17:39:00.833  1306-1616  WM-Processor            com.ichi2.anki.debug                 D  Processor cancelling 314c6062-a1cd-41e6-9535-5f0a847cf6e7
2025-06-16 17:39:00.840  1306-1306  WM-SystemFgDispatcher   com.ichi2.anki.debug                 I  Stopping foreground service
2025-06-16 17:39:00.840  1306-1306  WM-SystemFgService      com.ichi2.anki.debug                 D  Shutting down.
2025-06-16 17:39:00.849  1306-1616  WM-Processor            com.ichi2.anki.debug                 D  WorkerWrapper interrupted for 314c6062-a1cd-41e6-9535-5f0a847cf6e7
2025-06-16 17:39:00.854  1306-1587  SyncMediaWorker         com.ichi2.anki.debug                 W  kotlinx.coroutines.JobCancellationException: Job was cancelled; job=JobImpl{Cancelling}@f2f5dd0
2025-06-16 17:39:00.855  1306-1306  WM-SystemJobService     com.ichi2.anki.debug                 D  onStopJob for WorkGenerationalId(workSpecId=314c6062-a1cd-41e6-9535-5f0a847cf6e7, generation=0)
2025-06-16 17:39:00.871  1306-1616  WM-GreedyScheduler      com.ichi2.anki.debug                 D  Cancelling work ID 314c6062-a1cd-41e6-9535-5f0a847cf6e7
2025-06-16 17:39:00.879  1306-1587  SyncMediaWorker         com.ichi2.anki.debug                 D  SyncMediaWorker: cancelling notification
2025-06-16 17:39:00.912  1306-1616  WM-WorkerWrapper        com.ichi2.anki.debug                 I  Work [ id=314c6062-a1cd-41e6-9535-5f0a847cf6e7, tags={ com.ichi2.anki.worker.SyncMediaWorker } ] was cancelled
                                                                                                    androidx.work.impl.WorkerStoppedException
                                                                                                    	at androidx.work.impl.WorkerWrapper.interrupt(WorkerWrapper.kt:348)
                                                                                                    	at androidx.work.impl.Processor.interrupt(Processor.java:439)
                                                                                                    	at androidx.work.impl.Processor.stopAndCancelWork(Processor.java:280)
                                                                                                    	at androidx.work.impl.utils.CancelWorkRunnable.cancel(CancelWorkRunnable.kt:33)
                                                                                                    	at androidx.work.impl.utils.CancelWorkRunnable.access$cancel(CancelWorkRunnable.kt:1)
                                                                                                    	at androidx.work.impl.utils.CancelWorkRunnable$forId$1.invoke$lambda$0(CancelWorkRunnable.kt:76)
                                                                                                    	at androidx.work.impl.utils.CancelWorkRunnable$forId$1.$r8$lambda$c6ckNuSXH3At6SBb4mDMZynE_5I(Unknown Source:0)
                                                                                                    	at androidx.work.impl.utils.CancelWorkRunnable$forId$1$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
                                                                                                    	at androidx.room.RoomDatabase.runInTransaction(RoomDatabase.kt:585)
                                                                                                    	at androidx.work.impl.utils.CancelWorkRunnable$forId$1.invoke(CancelWorkRunnable.kt:76)
                                                                                                    	at androidx.work.impl.utils.CancelWorkRunnable$forId$1.invoke(CancelWorkRunnable.kt:70)
                                                                                                    	at androidx.work.OperationKt.launchOperation$lambda$2$lambda$1(Operation.kt:50)
                                                                                                    	at androidx.work.OperationKt.$r8$lambda$XKAkIiEN7OgIvwuLUZRQpJhjmyE(Unknown Source:0)
                                                                                                    	at androidx.work.OperationKt$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
                                                                                                    	at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
2025-06-16 17:39:00.915  1306-1616  WM-WorkerWrapper        com.ichi2.anki.debug                 D  Status for 314c6062-a1cd-41e6-9535-5f0a847cf6e7 is CANCELLED ; not doing any work
2025-06-16 17:39:00.919  1306-1306  WM-Processor            com.ichi2.anki.debug                 D  Processor 314c6062-a1cd-41e6-9535-5f0a847cf6e7 executed; reschedule = false
2025-06-16 17:39:00.920  1306-1306  WM-GreedyScheduler      com.ichi2.anki.debug                 D  Stopping tracking for WorkGenerationalId(workSpecId=314c6062-a1cd-41e6-9535-5f0a847cf6e7, generation=0)
2025-06-16 17:39:00.922  1306-1616  WM-StopWorkRunnable     com.ichi2.anki.debug                 D  StopWorkRunnable for 314c6062-a1cd-41e6-9535-5f0a847cf6e7; Processor.stopWork = false
2025-06-16 17:39:00.923  1306-1616  WM-StopWorkRunnable     com.ichi2.anki.debug                 D  StopWorkRunnable for 314c6062-a1cd-41e6-9535-5f0a847cf6e7; Processor.stopWork = false
2025-06-16 17:39:00.927  1306-1613  WM-GreedyScheduler      com.ichi2.anki.debug                 D  Cancelling work ID 314c6062-a1cd-41e6-9535-5f0a847cf6e7
2025-06-16 17:39:00.934  1306-1613  WM-NetworkStateTracker  com.ichi2.anki.debug                 D  Unregistering network callback
2025-06-16 17:39:00.942  1306-1587  SnackbarsKt             com.ichi2.anki.debug                 D  displayed snackbar: 'Media sync aborted.'
2025-06-16 17:39:00.943  1306-1306  AndroidRuntime          com.ichi2.anki.debug                 D  Shutting down VM
```

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison**
Special thanks to [Enchantable](https://www.reddit.com/user/Enchantable/) on Reddit for the diagnostic help!

## Purpose / Description

If a media sync is attempted with a closed collection, it raises:

```
Panic at anki/rslib/src/backend/sync.rs:249: called Option::unwrap() on a None
```

Which poisons the collection for all future accesses

```
Result::unwrap() on an Err value: PoisonError { .. }
```

## Fixes
* Fixes #17382
* Fixes #18542
* Fixes Part of #15760

## Approach

Our fix ensures an open collection, and throws if this is not the case, but does NOT use `withCol { }`, as this blocks the queue of operations to the backend until it's completed (even if done in a background thread)

* Dismiss a dialog safely
  *  Fix by a try...catch, which needed to be on the main thread  
* Fix a title
  * Standard `sentence-case` stuff 

## How Has This Been Tested?

**PoisonError**

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncMediaWorker.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncMediaWorker.kt b/AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncMediaWorker.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncMediaWorker.kt	(revision a107a81149f74fd3651c5d22e1557999a5e4fbe7)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncMediaWorker.kt	(date 1750095023225)
@@ -73,9 +73,9 @@
 
             // The collection must be open, but we should not block collection operations while
             // `syncMedia` is executing, the app should be usable during a background media sync
-            CollectionManager.getColUnsafe().backend.syncMedia(auth)
+            CollectionManager.closeCollectionBlocking()
             val backend = CollectionManager.getBackend()
-
+            backend.syncMedia(auth)
             delay(1000) // avoid notifications if sync occurs too quickly
             if (backend.mediaSyncStatus().active) {
                 Timber.i("Showing SyncMediaWorker's notification")
```

**Media sync started**

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncMediaWorker.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncMediaWorker.kt b/AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncMediaWorker.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncMediaWorker.kt	(revision a107a81149f74fd3651c5d22e1557999a5e4fbe7)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncMediaWorker.kt	(date 1750095148658)
@@ -73,6 +73,7 @@
 
             // The collection must be open, but we should not block collection operations while
             // `syncMedia` is executing, the app should be usable during a background media sync
+            CollectionManager.closeCollectionBlocking()
             CollectionManager.getColUnsafe().backend.syncMedia(auth)
             val backend = CollectionManager.getBackend()
``` 

----

image

----

Checked logcat for the Fragment detached error; logged and no longer crashes

Do note that the `window == null || !isShowing` checks were passing, so Timber logs this as `w`

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/utils/HandlerUtils.kt [hunk 1]
```diff
@@ -19,6 +19,7 @@ package com.ichi2.utils
 
 import android.os.Handler
 import android.os.Looper
+import com.ichi2.utils.HandlerUtils.executeFunctionUsingHandler
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/utils/HandlerUtils.kt]: strange there is an import of something in the same file ?

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/utils/HandlerUtils.kt]: Android Studio bug in auto-import. Fixed via changing a comment

**Review by BrayanDSO — APPROVED** [review]
Looks great. Thanks, David
