### PR TITLE
Change the instance cloze builder Regex pattern

### LINKED ISSUE #16784: [BUG]: Instant editor's tapping makes cloze which ignores adjacent characters after symbol in middle of word
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Share the following text with Instant card:
`student's note(s)`
    

2. Tap the words
     

3. Tap the pencil icon button
 

### Expected behaviour

Text in Text field is
`{{c1:student's}} {{c2::note(s)}}`

### Actual behaviour

Text in Text field is
`{{c1:student}}' {{c2::note}}(`

Screen after tapping the finger icon button:

### Debug info

```text
AnkiDroid Version = 2.19alpha10-debug (73dde8aef587460c059e0de622e90eb6742fc1af)

Backend Version = 0.1.39-anki24.06.2 (24.06.2 9b4dd54312de8798a3f2bee07892bb3a488d1f9b)

Android Version = 11 (SDK 30)

ProductFlavor = amazon

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/126.0.6478.134 Mobile Safari/537.36

ACRA UUID = 40e25c84-aa13-4b5b-be29-684c2e325a9d

FSRS Enabled = true

Crash Reports Enabled = false
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by peyman79**
## Purpose / Description
The previous regex pattern for building cloze text ignores all punctuations except for underscores and dashes. As a result, for some texts like `Student's` or `Note(s)`, it only considered the text up to the first punctuation mark.

## Fixes
* Fixes #16784

## Approach
I changed the regex pattern to consider apostrophe and parentheses characters as part of the main cloze text.

## How Has This Been Tested?

To ensure the new code works correctly, I wrote some unit tests. Additionally, I provided a screenshot demonstrating these changes.

Fix cloze builder problem

## Checklist

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [X] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelTest.kt [hunk 1]
```diff
@@ -102,6 +102,22 @@ class InstantEditorViewModelTest : RobolectricTest() {
...
+    }
+
+    @Test
+    fun `buildClozeText handles parentheses punctuation`() = runViewModelTest {
+        val text = "Note(s)"
+        val result = buildClozeText(text)
+
+        assertEquals("{{c1::Note(s)}}", result)
+    }
+
```
Comment (criticalAY) [inline AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelTest.kt:120]: Create a single test for this and I think I already created one use that and introduce these there maybe parameterised if possible

**Review by criticalAY — CHANGES_REQUESTED** [review]
Rebase the PR if possible and one minor change in test rest looks good

File: AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelTest.kt [hunk 2]
```diff
@@ -87,35 +87,24 @@ class InstantEditorViewModelTest : RobolectricTest() {
...
+            "Note(s)" to "{{c2::Note(s)}}",
+            "20%" to "{{c3::20}}%",
+            "hello-world" to "{{c4::hello-world}}",
+            "hello_world" to "{{c5::hello_world}}",
+            "(hello)" to "({{c6::hello}})",
+            "[hello]" to "[{{c7::hello}}]",
+            "{hello}" to "{{{c8::hello}}}",
+            "test," to "{{c9::test}},",
+            "{{c10::test}}," to "test,"
+        )
```
Comment (david-allison) [inline AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelTest.kt:102]: Use a parameterized test rather than a for loop

1. This appears correctly in the IDE
2. In a for loop, only the first failure is flagged

See an example:

https://github.com/ankidroid/Anki-Android/blob/14813c15532eda25d5fdcc8dd03e2e957caf689b/AnkiDroid/src/androidTest/java/com/ichi2/anki/PagesTest.kt

Sadly the Android syntax for parameterized tests isn't great

**Review by david-allison — CHANGES_REQUESTED** [review]
Thanks! One request with the tests, please ping if you need specific help

File: AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelTest.kt (hunk 2 above)
Comment (peyman79) [reply AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelTest.kt:102]: I tried using parameterized tests at first but ran into an error I couldn't figure out.

This my test code block:
```
@ParameterizedTest
    @MethodSource("provideClozeTextCases")
    fun `buildClozeText handles various punctuation cases`(input: String, expected: String)= runViewModelTest{
        val result = buildClozeText(input)
        assertEquals(expected, result)
    }

    companion object {
        @JvmStatic // This annotation is required for MethodSource
        fun provideClozeTextCases(): Stream<Arguments> {
            return Stream.of(
                Arguments.of("Student's", "{{c1::Student's}}"),
                Arguments.of("Note(s)", "{{c1::Note(s)}}"),
                Arguments.of("20%", "{{c1::20}}%"),
                Arguments.of("hello-world", "{{c1::hello-world}}"),
                Arguments.of("hello_world", "{{c1::hello_world}}"),
                Arguments.of("(hello)", "({{c1::hello}})"),
                Arguments.of("[hello]", "[{{c1::hello}}]"),
                Arguments.of("{hello}", "{{{c1::hello}}}"),
                Arguments.of("test,", "{{c1::test}},"),
                Arguments.of("{{c1::test}},", "test,")
            )
        }
    }
```
And this is the error related to this test:
```
'byte[][] net.ankiweb.rsdroid.NativeMethods.openBackend(byte[])'
java.lang.UnsatisfiedLinkError: 'byte[][] net.ankiweb.rsdroid.NativeMethods.openBackend(byte[])'
	at net.ankiweb.rsdroid.NativeMethods.openBackend(Native Method)
	at net.ankiweb.rsdroid.Backend.<init>(Backend.kt:79)
	at net.ankiweb.rsdroid.BackendFactory.getBackend(BackendFactory.kt:39)
	at net.ankiweb.rsdroid.BackendFactory.getBackend$default(BackendFactory.kt:35)
	at com.ichi2.anki.CollectionManager.ensureBackendInner(CollectionManager.kt:198)
	at com.ichi2.anki.CollectionManager.ensureOpenInner(CollectionManager.kt:238)
	at com.ichi2.anki.CollectionManager.withCol$lambda$1(CollectionManager.kt:116)
	at com.ichi2.anki.CollectionManager$withQueue$3.invokeSuspend(CollectionManager.kt:101)
	at _COROUTINE._BOUNDARY._(CoroutineDebugging.kt:42)
	at com.ichi2.anki.instantnoteeditor.InstantEditorViewModel$1.invokeSuspend(InstantEditorViewModel.kt:103)
Caused by: java.lang.UnsatisfiedLinkError: 'byte[][] net.ankiweb.rsdroid.NativeMethods.openBackend(byte[])'
	at net.ankiweb.rsdroid.NativeMethods.openBackend(Native Method)
	at net.ankiweb.rsdroid.Backend.<init>(Backend.kt:79)
	at net.ankiweb.rsdroid.BackendFactory.getBackend(BackendFactory.kt:39)
	at net.ankiweb.rsdroid.BackendFactory.getBackend$default(BackendFactory.kt:35)
	at com.ichi2.anki.CollectionManager.ensureBackendInner(CollectionManager.kt:198)
	at com.ichi2.anki.CollectionManager.ensureOpenInner(CollectionManager.kt:238)
	at com.ichi2.anki.CollectionManager.withCol$lambda$1(CollectionManager.kt:116)
	at com.ichi2.anki.CollectionManager$withQueue$3.invokeSuspend(CollectionManager.kt:101)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:65)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:371)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:21)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:88)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:123)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:52)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:43)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at com.ichi2.anki.instantnoteeditor.InstantEditorViewModel.<init>(InstantEditorViewModel.kt:101)
	at com.ichi2.anki.instanteditor.InstantEditorViewModelTest.runViewModelTest$lambda$0(InstantEditorViewModelTest.kt:199)
	at com.ichi2.anki.instanteditor.InstantEditorViewModelTest$runViewModelTest$2.invokeSuspend(InstantEditorViewModelTest.kt:202)
	at com.ichi2.anki.instanteditor.InstantEditorViewModelTest$runViewModelTest$2.invoke(InstantEditorViewModelTest.kt)
	at com.ichi2.anki.instanteditor.InstantEditorViewModelTest$runViewModelTest$2.invoke(InstantEditorViewModelTest.kt)
	at com.ichi2.testutils.TestClass$runTest$1$1.invokeSuspend(TestClass.kt:240)
	at com.ichi2.testutils.TestClass$runTest$1$1.invoke(TestClass.kt)
	at com.ichi2.testutils.TestClass$runTest$1$1.invoke(TestClass.kt)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$2$1$1.invokeSuspend(TestBuilders.kt:316)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.test.TestDispatcher.processEvent$kotlinx_coroutines_test(TestDispatcher.kt:24)
	at kotlinx.coroutines.test.TestCoroutineScheduler.tryRunNextTaskUnless$kotlinx_coroutines_test(TestCoroutineScheduler.kt:99)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$2$1$workRunner$1.invokeSuspend(TestBuilders.kt:322)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at kotlinx.coroutines.test.TestBuildersJvmKt.createTestResult(TestBuildersJvm.kt:10)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest-8Mi8wO0(TestBuilders.kt:310)
	at kotlinx.coroutines.test.TestBuildersKt.runTest-8Mi8wO0(Unknown Source)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest-8Mi8wO0(TestBuilders.kt:168)
	at kotlinx.coroutines.test.TestBuildersKt.runTest-8Mi8wO0(Unknown Source)
	at com.ichi2.testutils.TestClass.runTest(TestClass.kt:238)
	at com.ichi2.testutils.TestClass.runTest$default(TestClass.kt:227)
	at com.ichi2.anki.instanteditor.InstantEditorViewModelTest.runViewModelTest(InstantEditorViewModelTest.kt:201)
	at com.ichi2.anki.instanteditor.InstantEditorViewModelTest.runViewModelTest$default(InstantEditorViewModelTest.kt:198)
	at com.ichi2.anki.instanteditor.InstantEditorViewModelTest.buildClozeText handles various punctuation cases(InstantEditorViewModelTest.kt:97)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

```

image

Comment (david-allison) [reply AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelTest.kt:102]: With apologies, didn't realise this was such a big ask. Our Android parameterized tests are so much worse than other languages/frameworks

To apply this:

* copy the following
* double tap shift when in Android Studio
* Apply patch from clipboard

```patch
Subject: [PATCH] aa
---
Index: AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelTest.kt b/AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelTest.kt
--- a/AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelTest.kt	(revision 485b200fd558a4c2ca36315b740417a53ecb0e8d)
+++ b/AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelTest.kt	(date 1722254659290)
@@ -23,6 +23,7 @@
 import com.ichi2.anki.instantnoteeditor.InstantEditorViewModel
 import com.ichi2.anki.instantnoteeditor.InstantNoteEditorActivity
 import com.ichi2.anki.instantnoteeditor.SaveNoteResult
+import com.ichi2.testutils.TestClass
 import org.junit.Assert.assertEquals
 import org.junit.Assert.assertTrue
 import org.junit.Test
@@ -86,26 +87,6 @@
         assertTrue(result is SaveNoteResult.Warning)
     }
 
-    @Test
-    fun `buildClozeText handles various punctuation cases`() = runViewModelTest {
-        val testCases = arrayOf(
-            "Student's" to "{{c1::Student's}}",
-            "Note(s)" to "{{c2::Note(s)}}",
-            "20%" to "{{c3::20}}%",
-            "hello-world" to "{{c4::hello-world}}",
-            "hello_world" to "{{c5::hello_world}}",
-            "(hello)" to "({{c6::hello}})",
-            "[hello]" to "[{{c7::hello}}]",
-            "{hello}" to "{{{c8::hello}}}",
-            "test," to "{{c9::test}},",
-            "{{c10::test}}," to "test,"
-        )
-
-        for ((input, expected) in testCases) {
-            val result = buildClozeText(input)
-            assertEquals(expected, result)
-        }
-    }
 
     @Test
     fun buildClozeTextTest() = runViewModelTest {
@@ -188,10 +169,7 @@
     private fun runViewModelTest(
         initViewModel: () -> InstantEditorViewModel = { InstantEditorViewModel() },
         testBody: suspend InstantEditorViewModel.() -> Unit
-    ) = runTest {
-        val viewModel = initViewModel()
-        testBody(viewModel)
-    }
+    ) = runInstantEditorViewModelTest(initViewModel, testBody)
 
     private fun saveNoteResult(result: SaveNoteResult): String? {
         return when (result) {
@@ -205,4 +183,15 @@
             is SaveNoteResult.Warning -> result.message
         }
     }
+
+    companion object {
+        context (TestClass)
+        fun runInstantEditorViewModelTest(
+            initViewModel: () -> InstantEditorViewModel = { InstantEditorViewModel() },
+            testBody: suspend InstantEditorViewModel.() -> Unit
+        ) = runTest {
+            val viewModel = initViewModel()
+            testBody(viewModel)
+        }
+    }
 }
Index: AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelParameterizedTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelParameterizedTest.kt b/AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelParameterizedTest.kt
new file mode 100644
--- /dev/null	(date 1722254623738)
+++ b/AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelParameterizedTest.kt	(date 1722254623738)
@@ -0,0 +1,60 @@
+/*
+ *  Copyright (c) 2024 David Allison <davidallisongithub@gmail.com>
+ *
+ *  This program is free software; you can redistribute it and/or modify it under
+ *  the terms of the GNU General Public License as published by the Free Software
+ *  Foundation; either version 3 of the License, or (at your option) any later
+ *  version.
+ *
+ *  This program is distributed in the hope that it will be useful, but WITHOUT ANY
+ *  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
+ *  PARTICULAR PURPOSE. See the GNU General Public License for more details.
+ *
+ *  You should have received a copy of the GNU General Public License along with
+ *  this program.  If not, see <http://www.gnu.org/licenses/>.
+ */
+
+package com.ichi2.anki.instanteditor
+
+import com.ichi2.anki.RobolectricTest
+import com.ichi2.anki.instanteditor.InstantEditorViewModelTest.Companion.runInstantEditorViewModelTest
+import org.junit.Assert.assertEquals
+import org.junit.Test
+import org.junit.runner.RunWith
+import org.robolectric.ParameterizedRobolectricTestRunner as Parameterized
+
+@RunWith(Parameterized::class)
+class InstantEditorViewModelParameterizedTest : RobolectricTest() {
+    @JvmField // required for Parameter
+    @Parameterized.Parameter(0)
+    var input: String? = null
+
+    @JvmField // required for Parameter
+    @Parameterized.Parameter(1)
+    var expected: String? = null
+
+    @Test
+    fun `buildClozeText punctuation handling`() = runInstantEditorViewModelTest {
+        val result = buildClozeText(input!!)
+        assertEquals(expected, result)
+    }
+
+    companion object {
+        @Parameterized.Parameters(name = "{0} -> {1}")
+        @JvmStatic // required for initParameters
+        fun initParameters(): Collection<Array<out Any>> {
+            return listOf(
+                arrayOf("Student's", "{{c1::Student's}}"),
+                arrayOf("Note(s)", "{{c1::Note(s)}}"),
+                arrayOf("20%", "{{c1::20}}%"),
+                arrayOf("hello-world", "{{c1::hello-world}}"),
+                arrayOf("hello_world", "{{c1::hello_world}}"),
+                arrayOf("(hello)", "({{c1::hello}})"),
+                arrayOf("[hello]", "[{{c1::hello}}]"),
+                arrayOf("{hello}", "{{{c1::hello}}}"),
+                arrayOf("test,", "{{c1::test}},"),
+                arrayOf("{{c1::test}},", "test,")
+            )
+        }
+    }
+}
\ No newline at end of file

```

Comment (peyman79) [reply AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelTest.kt]: It works. Thanks for your help.

**Review by david-allison — APPROVED** [review]
I'll take this through with a squash merge + force push

**Review by david-allison — CHANGES_REQUESTED** [review]
```patch
Index: AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelParameterizedTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelParameterizedTest.kt b/AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelParameterizedTest.kt
--- a/AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelParameterizedTest.kt	(revision 0c1461b1dfb2729a488794576ef8a2205d710934)
+++ b/AnkiDroid/src/test/java/com/ichi2/anki/instanteditor/InstantEditorViewModelParameterizedTest.kt	(date 1722269079797)
@@ -37,6 +37,8 @@
     fun `buildClozeText punctuation handling`() = runInstantEditorViewModelTest {
         val result = buildClozeText(input!!)
         assertEquals(expected, result)
+        val undone = buildClozeText(result)
+        assertEquals("applying buildClozeText twice should not change the input", input, undone)
     }
 
     companion object {

```

-> 

```
Expected :{hello}
Actual   :hello}
```

etc...

**Review by david-allison — APPROVED** [review]
I'm happy if CI is

**Comment by david-allison** [comment]
@peyman79, I've force pushed to change the commit messages/squash and am merging now

Thanks again! In future, strongly encouraged to squash/force push your PRs
