### PR TITLE
Fixed SearchDecks Icon visibility not updating if DeckCount changed

### LINKED ISSUE #11112: [Bug] Search Deck Icon only appears after app restart
###### Reproduction Steps

1. Make Decks until their total count is 10.

###### Expected Result
Search Deck Icon Should appear immediately

###### Actual Result
It needs an app restart to appear

###### Debug info
```
AnkiDroid Version = 2.16alpha60

Android Version = 11

Manufacturer = unknown

Model = Android SDK built for x86

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Android SDK built for x86 Build/RSR1.210210.001.A1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.106 Mobile Safari/537.36

ACRA UUID = 6a83592c-15b2-4fc2-ba97-73f54beb34b8

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by dorrin-sot**
## Purpose / Description
Search Decks Icon would not change (show or unshow) if deck count was changed (added or deleted) unless app was restarted

## Fixes
Fixes #11112

## Approach
Since after DeckList was changed, `renderPage()` will be called, added a deckcount check there and if deckcount was 9 or 10 it would invalidate options menu. Also added the visibility update to `onPrepareOptionsMenu`.

## How Has This Been Tested?
Tested on emulator

https://user-images.githubusercontent.com/59933477/165406059-c0a6c3d9-4da0-483b-9534-1747f4baee35.mov

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 1]
```diff
@@ -2039,6 +2043,12 @@ open class DeckPicker : NavigationDrawerActivity(), StudyOptionsListener, SyncEr
             scrollDecklistToDeck(current)
             mFocusedDeck = current
         }
+
+        // if Deck Count may have changed, update SearchDeck icon Visibility
+        val deckCount = col.decks.count()
+        if (deckCount == 9 || deckCount == 10) {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:2049]: extract the 10 to a constant and compare against that.

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 2]
```diff
@@ -495,6 +495,7 @@ open class DeckPicker : NavigationDrawerActivity(), StudyOptionsListener, SyncEr
     }
 
     override fun onPrepareOptionsMenu(menu: Menu): Boolean {
+        updateSearchDecksIconVisibility(menu)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:498]: We can't do this here as `updateSearchDecksIconVisibility` has a reference to `col`, which may be null

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 3]
```diff
@@ -2039,6 +2043,12 @@ open class DeckPicker : NavigationDrawerActivity(), StudyOptionsListener, SyncEr
             scrollDecklistToDeck(current)
             mFocusedDeck = current
         }
+
+        // if Deck Count may have changed, update SearchDeck icon Visibility
+        val deckCount = col.decks.count()
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:2048]: What happens if the user deletes a node of the deck tree? Or adds A::B::C::D, therefore potentially adding/deleting more than 1 deck

**Review by david-allison — CHANGES_REQUESTED** [review]
It would be ideal to add unit tests to this.

If that's not feasible, add a few `@NeedsTest("")` annotations to the relevant method or class

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt (hunk 3 above)
Comment (dorrin-sot) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:2048]: Oh I wasn't handling that but I made a few changes that would recognize DeckTree adding and deleting more than one deck. Hopefully it passes unit tests so I can commit it 🤞🏻

**Comment by dorrin-sot** [comment]
> It would be ideal to add unit tests to this.

I've been trying to write a few but when I try to create a deck with `CreateDeckDialog` and then call `DeckPicker::updateDeckList()` inside its listener, I can't get the `onPrepareOptionsMenu()` to run (so the visibility won't update and it fails the asserts) 😕

**Comment by dorrin-sot** [comment]
```diff
Index: AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java b/AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java
--- a/AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java	(revision 95531f7647e7cf5835567e2527a6eb3c19233e95)
+++ b/AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java	(date 1651161300163)
@@ -284,6 +291,116 @@
         }
     }
 
+    @Test
+    public void deckCreationMakesSearchDecksIconVisible() {
+        DeckPicker deckPicker = startActivityNormallyOpenCollectionWithIntent(DeckPicker.class, new Intent());
+
+        DeckManager decks = deckPicker.getCol().getDecks();
+
+        AtomicInteger expectedDeckCount = new AtomicInteger(1);
+
+        CreateDeckDialog createDeckDialog = new CreateDeckDialog(deckPicker, R.string.new_deck, CreateDeckDialog.DeckDialogType.DECK, null);
+        createDeckDialog.setOnNewDeckCreated(did -> {
+            deckPicker.updateDeckList();
+            advanceRobolectricLooperWithSleep();
+
+            String deckName = decks.name(did);
+
+            Timber.d("Deck \"%s\" Created", deckName);
+
+            assertThat(deckName + " must be created", deckPicker.getDeckCount(), is(expectedDeckCount.getAndIncrement()));
+            if (deckPicker.getDeckCount() >= 10)
+                assertTrue(deckName + " should be visible", deckPicker.mSearchDecksIcon.isVisible());
+            else
+                assertFalse(deckName + " should be invisible", deckPicker.mSearchDecksIcon.isVisible());
+        });
+        for (int i = 1; i <= 15; i++) {
+            createDeckDialog.createDeck("Deck" + i);
+        }
+
+        advanceRobolectricLooperWithSleep();
+    }
```

**Comment by dorrin-sot** [comment]
> I could be wrong but I thought there was support added recently so you could change the collection path during androidTest tests 🤔 - @Arthur-Milchior may know more, I know this was a real issue for him running androidTests.

ooo what if I change this variable with reflection at the start of tests 😳

**Comment by mikehardy** [comment]
I would discourage getting fancy in tests and relfection change on statics etc is in area I think of as "fancy" :laughing: - better if there is an official (or common) way to slice into the object hierarchy or if you use existing configuration pathways to reconfigure it. I think we already use Rule / grant storage permission so theoretically you could use any directory path in an androidTest and it would work / init a new collection there?

**Comment by dorrin-sot** [comment]
> I would discourage getting fancy in tests and relfection change on statics etc is in area I think of as "fancy" 😆 - better if there is an official (or common) way to slice into the object hierarchy or if you use existing configuration pathways to reconfigure it. I think we already use Rule / grant storage permission so theoretically you could use any directory path in an androidTest and it would work / init a new collection there?

😂
Oh think I found it. There's a `AnkiDroidApp.INSTRUMENTATION_TESTING` that is for setting a specific `androidTest` directory

File: AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java [hunk 4]
```diff
@@ -23,35 +23,96 @@
...
 import static org.junit.Assert.assertThat;
+import static org.junit.Assert.assertTrue;
 import static org.junit.Assume.assumeFalse;
 import static org.junit.Assume.assumeTrue;
 
 @SuppressLint("DirectSystemCurrentTimeMillisUsage")
 public class DeckPickerTest {
+    @Before
+    public void setup() {
+        INSTRUMENTATION_TESTING = true;
```
Comment (david-allison) [inline AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java:75]: Was `NewCollectionPathTestRunner` not feasible here?

File: AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java [hunk 5]
```diff
@@ -99,12 +160,81 @@ public void checkIfStudyOptionsIsDisplayedOnTablet() {
         onView(withId(R.id.studyoptions_fragment)).check(matches(isDisplayed()));
     }
 
+
+    @Test
+    public void deckNormalCreationAndDeletionMakesSearchDecksIconVisible() {
+        int iconId = R.id.deck_picker_action_filter;
```
Comment (david-allison) [inline AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java:165]: can these tests ensure that they're running on an emulator:

`        assumeTrue(InstrumentedTest.isEmulator());`

File: AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java [hunk 6]
```diff
@@ -23,35 +23,96 @@
...
+import static org.junit.Assert.assertTrue;
 import static org.junit.Assume.assumeFalse;
 import static org.junit.Assume.assumeTrue;
 
 @SuppressLint("DirectSystemCurrentTimeMillisUsage")
 public class DeckPickerTest {
+    @Before
+    public void setup() {
+        INSTRUMENTATION_TESTING = true;
+        deleteAllDecks();
```
Comment (david-allison) [inline AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java:76]: I'm not comfortable here, 

* `INSTRUMENTATION_TESTING` is new and not well tested
* It seemingly wasn't set automatically (above comment), which implies something is wrong and it would be useful to diagnose this.
* There's no check in this code to ensure that we're running in an emulator
* We probably don't want this here:
  * It should be under specific tests which require it, AFTER we've checked the user is running on an emulator

**Review by david-allison — CHANGES_REQUESTED** [review]

File: AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java (hunk 4 above)
Comment (dorrin-sot) [reply AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java:75]: I couldnt find any example of that class. is this ok?


```diff
diff --git a/AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java b/AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java
--- a/AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java	(revision 0797f84d7be9a7aa6d9aeac6f503569e93d2dc3c)
+++ b/AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java	(date 1651999314187)
@@ -70,13 +71,6 @@
 
 @SuppressLint("DirectSystemCurrentTimeMillisUsage")
 public class DeckPickerTest {
-    @Before
-    public void setup() {
-        INSTRUMENTATION_TESTING = true;
-        deleteAllDecks();
-    }
-
-
     private void deleteAllDecks() {
         deleteAllNotes();
 
@@ -161,7 +155,11 @@
 
 
     @Test
-    public void deckNormalCreationAndDeletionMakesSearchDecksIconVisible() {
+    public void deckNormalCreationAndDeletionMakesSearchDecksIconVisible() throws ClassNotFoundException, IllegalAccessException, InstantiationException {
+        assumeTrue(InstrumentedTest.isEmulator());
+        NewCollectionPathTestRunner.newApplication(DeckPicker.class, getInstrumentation().getTargetContext());
+        deleteAllDecks();
+
         int iconId = R.id.deck_picker_action_filter;
         ensureIsGone(iconId);
 
@@ -178,7 +176,11 @@
 
 
     @Test
-    public void subdeckCreationAndDeletionMakesSearchDecksIconVisible() {
+    public void subdeckCreationAndDeletionMakesSearchDecksIconVisible() throws ClassNotFoundException, IllegalAccessException, InstantiationException {
+        assumeTrue(InstrumentedTest.isEmulator());
+        NewCollectionPathTestRunner.newApplication(DeckPicker.class, getInstrumentation().getTargetContext());
+        deleteAllDecks();
+
         int iconId = R.id.deck_picker_action_filter;
         ensureIsGone(iconId);
 

```

**Review by david-allison — COMMENTED** [review]
Comments regarding ensuring it's running on an emulator do not seem to have been addressed

**Comment by dorrin-sot** [comment]
> Comments regarding ensuring it's running on an emulator do not seem to have been addressed

Regarding the boolean `INSTRUMENTATION_TEST`, do I just need to move it or do I wait for `NewCollectionPathTest` to be fixed?

**Comment by dorrin-sot** [comment]
unit tests added 😁

**Review by david-allison — APPROVED** [review]

**Comment by david-allison** [comment]
```
> Task :AnkiDroid:lintPlayDebug FAILED
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:147: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki:lint-rules]
    var mSearchDecksIcon: MenuItem? = null
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 errors, 0 warnings
```

Other than that, code is good

**Comment by dorrin-sot** [comment]
Done :)

**Review by david-allison — COMMENTED** [review]
Coming back to this: can you check to see if `deckCount` is the number of decks, or the number of expanded decks

**Comment by dorrin-sot** [comment]
It's only the number of decks expanded. for example here it's 6:
image

**Comment by dorrin-sot** [comment]
Done 😄

**Review by david-allison — CHANGES_REQUESTED** [review]
I'd say it should be the total number of decks. People may want to search for a 'collapsed' deck

**Review by david-allison — APPROVED** [review]

**Review by mikehardy — APPROVED** [review]
all those tests :heart_on_fire:
