### PR TITLE
Fix: Keep the widgets & shortcuts disabled until storage permission is granted 

### LINKED ISSUE #13518: [Bug] Crash if using `Add note` widget or shortcuts before giving storage permission on `full` builds
###### Reproduction Steps

- tested on a `fullDebug` build
1. Don't have or remove the storage permission
2. Add the `Add note` widget to your screen
3. Tap the widget

###### Expected Result

Storage permission is asked correctly

###### Actual Result

Crashes

###### Debug info
Built with main d03d544c on SDK 33 emulator

```
ACRA caught a StorageAccessException for com.ichi2.anki.debug
                                                                                                    com.ichi2.anki.exception.StorageAccessException: No write access to AnkiDroid directory /storage/emulated/0/AnkiDroid
                                                                                                    	at com.ichi2.anki.CollectionHelper$Companion.initializeAnkiDroidDirectory(CollectionHelper.kt:369)
                                                                                                    	at com.ichi2.anki.CollectionManager.createCollectionPath(CollectionManager.kt:242)
                                                                                                    	at com.ichi2.anki.CollectionManager.ensureOpenInner(CollectionManager.kt:221)
                                                                                                    	at com.ichi2.anki.CollectionManager.access$ensureOpenInner(CollectionManager.kt:36)
                                                                                                    	at com.ichi2.anki.CollectionManager$getColUnsafe$1$1.invoke(CollectionManager.kt:276)
                                                                                                    	at com.ichi2.anki.CollectionManager$getColUnsafe$1$1.invoke(CollectionManager.kt:275)
                                                                                                    	at com.ichi2.anki.CollectionManager$withQueue$2.invokeSuspend(CollectionManager.kt:83)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@93ea1b6, Dispatchers.Main.immediate]
```

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### LINKED ISSUE #15686: [Bug] CardBrowser NullPointerException
likely due to no storage permissions

https://ankidroid.org/acra/app/1/bug/134200/report/db73fee5-8b77-4f20-bc05-a2aff3661cbf

```
java.lang.NullPointerException
	at com.ichi2.anki.CardBrowser$onCreate$11.invokeSuspend(SourceFile:117)
	at com.ichi2.anki.CardBrowser$onCreate$11.invoke(SourceFile:2)
	at com.ichi2.anki.CardBrowser$onCreate$11.invoke(SourceFile:1)
	at com.ichi2.anki.CardBrowser$launchCollectionInLifecycleScope$1$1.emit(SourceFile:3)
	at kotlinx.coroutines.flow.StateFlowImpl.collect(SourceFile:206)
	at kotlinx.coroutines.flow.ReadonlyStateFlow.collect(Unknown Source:2)
	at com.ichi2.anki.CardBrowser$launchCollectionInLifecycleScope$1.invokeSuspend(SourceFile:38)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(SourceFile:131)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(SourceFile:3)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(SourceFile:6)
	at kotlinx.coroutines.CoroutineStart.invoke(SourceFile:10)
	at kotlinx.coroutines.AbstractCoroutine.start(SourceFile:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(SourceFile:23)
	at kotlinx.coroutines.BuildersKt.launch(SourceFile:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(SourceFile:13)
	at kotlinx.coroutines.BuildersKt.launch$default(SourceFile:1)
	at com.ichi2.anki.CardBrowser.launchCollectionInLifecycleScope(SourceFile:15)
	at com.ichi2.anki.CardBrowser.onCreate(SourceFile:539)
	at android.app.Activity.performCreate(Activity.java:8000)
	at android.app.Activity.performCreate(Activity.java:7984)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3403)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3594)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2067)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7698)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@eeda772, Dispatchers.Main.immediate]

```

### PR DESCRIPTION
**Pull request by criticalAY**
## Purpose / Description
* Don't enable the shortcuts unless file access is given
* Keep the widgets disabled until the application has storage access

## Fixes
* Fixes #15686
* Fixes #13518

## Approach
Keeping the widgets and shortcuts disabled at install and as soon as file access is granted we can enable them, if storage is cleared the shortcuts will be disabled again but widgets, as they won't through NPE in this case

## How Has This Been Tested?

Tested on Google emulator API 34

Fresh install:
image

After giving out required permissions:
image

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivity.kt [hunk 1]
```diff
@@ -68,6 +73,30 @@ class PermissionsActivity : AnkiActivity() {
 
     fun setContinueButtonEnabled(isEnabled: Boolean) {
         findViewById<AppCompatButton>(R.id.continue_button).isEnabled = isEnabled
+        if (isEnabled) {
+            enableWidgets(this)
+            NavigationDrawerActivity.enablePostShortcut(this)
+        }
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivity.kt:79]: I don't believe this activity is used on `play` builds, therefore the widgets would never be enabled

Alternately, if permission is granted on the Android `App Info` screen

Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivity.kt:79]: Migrating them to IntentHandler should fix it

File: AnkiDroid/src/main/AndroidManifest.xml [hunk 2]
```diff
@@ -516,6 +517,7 @@
         <receiver
             android:name="com.ichi2.widget.AddNoteWidget"
             android:label="@string/menu_add_note"
+            android:enabled="false"
```
Comment (david-allison) [inline AnkiDroid/src/main/AndroidManifest.xml:520]: Does this affect users who had widgets enabled initially?

File: AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivity.kt [hunk 3]
```diff
@@ -68,6 +70,9 @@ class PermissionsActivity : AnkiActivity() {
 
     fun setContinueButtonEnabled(isEnabled: Boolean) {
         findViewById<AppCompatButton>(R.id.continue_button).isEnabled = isEnabled
+        // in case it's not play build
+        if (isEnabled) IntentHandler.enableWidgets(this)
+        NavigationDrawerActivity.enablePostShortcut(this)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionsActivity.kt:75]: Why is this not inside the If statement?

File: AnkiDroid/src/main/AndroidManifest.xml (hunk 2 above)
Comment (criticalAY) [reply AnkiDroid/src/main/AndroidManifest.xml:520]: Scenario 1: user already has app installed and updates, opens the app, intent handler will see that they have permission so it will be kept enabled

Scenario 2: fresh install, widget is disabled in case there is no storage permission 

I will test scenario 1 on my device just in case

Comment (criticalAY) [reply AnkiDroid/src/main/AndroidManifest.xml:520]: It doesn't affect the existing widgets

**Review by david-allison — APPROVED** [review]

**Review by mikehardy — APPROVED** [review]
LGTM - thank you!

**Comment by mikehardy** [comment]
Strange - failed out of the merge queue with something that *is* in the area:


```
com.ichi2.anki.NoteEditorIntentTest > launchActivityWithIntent[emulator-5554 - 11] FAILED 
	java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
	at com.ichi2.anki.NoteEditorIntentTest.launchActivityWithIntent$lambda$0(NoteEditorIntentTest.kt:54)
```

But that NoteEditorIntentTest uses `GrantStoragePermission` so...it should not have been affected. And the PR passed checks when passed, it only failed in the merge queue.

Possible new flake.
