### PR TITLE
fix: SliderPreference - listener added many times

### LINKED ISSUE #16111: [Bug]: SliderPreference - listener is added multiple times
`onBindViewHolder` is called multiple times; `addOnSliderTouchListener` does not remove stale listeners.

Therefore `callChangeListener` is called multiple times.

https://github.com/ankidroid/Anki-Android/blob/55ee1d7f333feb8ffc126fbdadd5c795a2762fc9/AnkiDroid/src/main/java/com/ichi2/preferences/SliderPreference.kt#L106-L128

Each time a change in the slider is made, `onBindViewHolder` is called again, leading to a large number of calls to `callChangeListener`

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
Each move of the slider, another listener was added

This was because `onBindViewHolder` was called multiple times leading to multiple calls of `addOnSliderTouchListener`

## Fixes
* Fixes #16111

## Approach

Define `setOnSliderTouchListenerOnce` and a tag, only set the listener once.

The listener did not use any holder-specific variables, `slider.value` was fine to use

## How Has This Been Tested?
Logcat output change

```diff
set day offset: '5'
set day offset: '4'
- set day offset: '4'
```

## Learning (optional, can help others)
**Learning**

never used `setTag` before; it needs a `R.id`

**Other Considerations**

Since in future a user may decide to use view.addOnSliderTouchListener, we didn't want to call `clearOnSliderTouchListeners()`;

`removeOnSliderTouchListener()` could be used, but it seemed wasteful to remove and then re-add the same listener instance.

Plus, if the instance DID use captured variables, we couldn't call `removeOnSliderTouchListener`

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/preferences/SliderPreference.kt [hunk 1]
```diff
@@ -112,18 +128,8 @@ class SliderPreference(context: Context, attrs: AttributeSet? = null) : Preferen
...
-                override fun onStopTrackingTouch(slider: Slider) {
-                    val sliderValue = slider.value.toInt()
-                    if (callChangeListener(sliderValue)) {
-                        value = sliderValue
-                    }
-                }
-            }
-        )
+        // set the listener once: avoid any method-level closures
+        slider.setOnSliderTouchListenerOnce(onTouchListener)
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/preferences/SliderPreference.kt:132]: Using `clearOnSliderTouchListeners()` then adding the listener back is simpler, I think

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/preferences/SliderPreference.kt:132]: The problem is:

* A user can obtain the `view` and grab the slider
* We can't validate whether other listeners have been added

I'd rather be open to extension, at the expense of a small amount of verbosity here

File: AnkiDroid/src/main/java/com/ichi2/preferences/SliderPreference.kt [hunk 2]
```diff
@@ -62,6 +64,20 @@ class SliderPreference(context: Context, attrs: AttributeSet? = null) : Preferen
...
 
+    // flyweight pattern: all listeners for an instance of the class as the same
+    // We also need to avoid any method-level closures: this callback is unused
+    // the second time `onBindViewHolder` is called
+    private val onTouchListener = object : Slider.OnSliderTouchListener {
+        override fun onStartTrackingTouch(slider: Slider) {}
+
+        override fun onStopTrackingTouch(slider: Slider) {
+            val sliderValue = slider.value.toInt()
+            if (callChangeListener(sliderValue)) {
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/preferences/SliderPreference.kt:75]:
```suggestion
            if (sliderValue != value && callChangeListener(sliderValue)) {
```

different from the original code, but that stop sending unchanged results

**Review by BrayanDSO — APPROVED** [review]

**Review by lukstbit — APPROVED** [review]
Ok.
As a side note, I would have named the file _ids.xml_
