### PR TITLE
Using javascript function to reload current card inside ankidroid webview

### LINKED ISSUE #5826: window.location.reload() opening chrome.
###### Reproduction Steps

 In front side of card adding adding function to button to call 
```
window.location.reload();
```
Or other similar functions to reload webview is opening chrome.

I have to use this in my Anki deck. When user select option then it should refresh in current card.
Not on next card.
Change is get reflected from next card.
I have 

GIF-200317_123959

###### Expected Result
Should refresh current webview when reload () function called from front side of card.

###### Research
*Enter an [ x ] character to confirm the points below:*

I have use the following code in AbstractFlashcardViewer
```
webView.loadUrl("javascript:window.location.reload( true )" );
```
It still open in chrome.

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

###### Question
Is there any security related concerns about this?
Or better approach for this, are available in Ankidroid?

### PR DESCRIPTION
**Pull request by infinyte7**
## Purpose / Description
In my anki deck, I want to refresh current card html page when user update it.

## Fixes
#5826 

## Approach
1. Creating signal for reload
2. Redrawing current card html

## How Has This Been Tested?
1. Add a button 
```
<button onclick="update();">Reload Card</button>
<script>
function update()
{
    reloadPage();  // this function is in card.js
}
</script>
```
2. Clicking on button redraw current card.

( I have tested on my [anki deck](https://github.com/infinyte7/Anki-xiehanzi) to refresh current card. And its working fine.)

## Learning (optional, can help others)
http://tutorials.jenkov.com/android/android-web-apps-using-android-webview.html

## Checklist
_Please, go through these checks before submitting the PR._

- [ x ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ x ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ x ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ x ] You have commented your code, particularly in hard-to-understand areas
- [ x ] You have performed a self-review of your own code

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 1]
```diff
@@ -2831,6 +2831,11 @@ private boolean filterUrl(String url) {
                 mFlipCardLayout.performClick();
                 return true;
             }
+            // card.html reload
+            if (url.startsWith("signal:reload_card_html")) {
+                redrawCard();
+                return true;
+            }
             int signalOrdinal = WebViewSignalParserUtils.getSignalFromUrl(url);
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:2839]: Nice to have: Would be nice to move this inside `getSignalFromUrl` so we can better test this at a later date

Comment (infinyte7) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:2839]: I have tried this
```java
case "signal:reload_card_html": redrawCard();   break;  // card.html reload
```
But compiler is suggesting to change function ``` redrawCard ``` definition to static.
Then it show suggest to changes these function to static
```java
hasLoadedCardContent()
fillFlashcard()
```
