### PR TITLE
fix(deck-picker): hide resizing divider when collection is empty

### LINKED ISSUE #19053: Resizable divider appears inappropriately when deck list is empty in portrait orientation
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Ensure AnkiDroid has no decks (empty deck list)
2. Rotate device to portrait orientation

Image

### Expected behaviour

The resizable divider should be hidden when there are no decks to display

### Debug info

```text
AnkiDroid Version = 2.23.0alpha0-debug (65e10e383aef3692b8222736293a9be77c723ec7)  
Backend Version = 0.1.60-anki25.07.5 (25.07.5 7172b2d26684c7ef9d10e249bd43dc5bf73ae00c)  
Android Version = 13 (SDK 33)  
ProductFlavor = play  
Device Info = Google | google | octopus_cheets | octopus | octopus | bertha  
Webview User Agent = Mozilla/5.0 (Linux; Android 13; octopus Build/R140-16366.0.0; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/138.0.7204.169 Safari/537.36  
ACRA UUID = 1eac5f23-2ced-436d-af43-08c2d544c6b8  
FSRS = 4.1.1 (Enabled: false)  
Crash Reports Enabled = false
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by Haz3-jolt**
## Purpose / Description
- Hides the resizing divider when there or no decks/ collection is empty.

## Fixes
* Fixes #19053 

## Approach
- adds a check to onCollectionStatusChanged to weather the divider should be visible or not.

## How Has This Been Tested?
No decks:
image
Empty deck:
image
Deck with cards:
image

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 1]
```diff
@@ -734,6 +734,15 @@ open class DeckPicker :
             // Hide the background when there are no cards to improve text readability.
             val backgroundView = findViewById<ImageView>(R.id.background)
             backgroundView.visibility = if (isInInitialState) View.GONE else View.VISIBLE
+
+            // Hide the resizing divider when the collection is empty (no decks) or when there are no cards at all
+            val resizingDivider = findViewById<View>(R.id.homescreen_resizing_divider)
+            launchCatchingTask {
+                val hasNoCards = withOpenColOrNull { isEmpty } ?: true
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt]: Can you move this logic to the viewmodel

Comment (Haz3-jolt) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt]: Done!

**Review by david-allison — APPROVED** [review]

**Review by BrayanDSO — APPROVED** [review]
