### PR TITLE
Fixes #6903

### LINKED ISSUE #6903: Sibling buried cards: Crash when counts() called
This occurs on both SchedV1 and V2
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/731f5b68-5751-4be0-a755-8c27c5cb981b

2.13alpha14

```
java.lang.ArrayIndexOutOfBoundsException: length=3; index=-2
at com.ichi2.libanki.sched.Sched.counts(Sched.java:4)
at com.ichi2.anki.AbstractFlashcardViewer.updateScreenCounts(AbstractFlashcardViewer.java:3)
at com.ichi2.anki.AbstractFlashcardViewer.updateForNewCard(AbstractFlashcardViewer.java:1)
at com.ichi2.anki.AbstractFlashcardViewer.fillFlashcard(AbstractFlashcardViewer.java:11)
at com.ichi2.anki.Reviewer.fillFlashcard(Reviewer.java:1)
at com.ichi2.anki.AbstractFlashcardViewer.updateCard(AbstractFlashcardViewer.java:34)
at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:16)
at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:1)
at com.ichi2.anki.Reviewer.displayCardQuestion(Reviewer.java:2)
at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.displayNext(AbstractFlashcardViewer.java:10)
at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.onProgressUpdate(AbstractFlashcardViewer.java:1)
at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:4)
at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:1)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:775)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7682)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
Fixes #6903

Seems that in this case, the overriding of `remove` was not detected, because for a `List<>`; it thought I used
`remove(Object)` instead of the expected `remove(long)`

The second interesting thing here is that the class CardQueue was added last minute, and not tested in my merge branch
as the remaining of the PR.

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
Done in last commit. But I don't like it. I believe in this case that adding that many line of code is really not worth the security it adds. 
I should admit however that it is an interesting exercice to ensure that the same problem does not occurs anywhere else.

File: AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java [hunk 1]
```diff
@@ -139,4 +146,62 @@ public void onPostExecute(TaskData result) {
...
+        assertEquals(queue.size(), nbCard - 3);
+        assertEquals(queue.removeFirstCard().getId(), cids[2]);
+        assertEquals(queue.size(), nbCard - 4);
+        assertEquals(queue.removeFirstCard().getId(), cids[4]);
+        assertEquals(queue.size(), nbCard - 5);
+    }
+
+    @Test
+    public void getCards() {
+        // #6903
```
Comment (mikehardy) [inline AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java:181]: yessss! love seeing a test for it that pokes the problem

File: AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java [hunk 2]
```diff
@@ -128,25 +128,56 @@ public int compareTo(LrnCard o) {
...
+        public int size() {
+            return mQueue.size();
+        }
+
+        protected LinkedList<T> getQueue() {
+            return mQueue;
+        }
+
+        public void shuffle(Random r) {
+            Collections.shuffle(mQueue, r);
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java:171]: Optional: you could implement the interface to remove this method. Likely not worth it

File: AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java [hunk 3]
```diff
@@ -139,4 +146,62 @@ public void onPostExecute(TaskData result) {
         waitForAsyncTasksToComplete();
         assertTrue(executed[0]);
     }
+
+    @Test
+    public void CardQueue() {
+        Collection col = getCol();
+        SchedV2 sched = (SchedV2) col.getSched();
+        SchedV2.SimpleCardQueue queue = sched.new SimpleCardQueue();
+        assertEquals(queue.size(), 0);
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java:155]: Optional: assertThat(queue, hasSize(0));

File: AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java [hunk 4]
```diff
@@ -139,4 +146,62 @@ public void onPostExecute(TaskData result) {
...
+        final int nbCard = 6;
+        long[] cids = new long[nbCard];
+        for (int i = 0; i < nbCard; i++) {
+            Note note = addNoteUsingBasicModel("foo", "bar");
+            ArrayList<Card> cards = note.cards();
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java:160]: Didn't we add getFirstCard for situations like this? Could save a little time per test

File: AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java [hunk 5]
```diff
@@ -139,4 +146,62 @@ public void onPostExecute(TaskData result) {
...
+        queue.remove(cids[3]);
+        assertEquals(queue.size(), nbCard - 3);
+        assertEquals(queue.removeFirstCard().getId(), cids[2]);
+        assertEquals(queue.size(), nbCard - 4);
+        assertEquals(queue.removeFirstCard().getId(), cids[4]);
+        assertEquals(queue.size(), nbCard - 5);
+    }
+
+    @Test
+    public void getCards() {
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java:180]: Could do with better naming

File: AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java [hunk 6]
```diff
@@ -139,4 +146,62 @@ public void onPostExecute(TaskData result) {
         waitForAsyncTasksToComplete();
         assertTrue(executed[0]);
     }
+
+    @Test
+    public void CardQueue() {
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java:151]: Java naming standards, and could do with a more descriptive name

File: AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java [hunk 7]
```diff
@@ -139,4 +146,62 @@ public void onPostExecute(TaskData result) {
...
+        AbstractSched sched = col.getSched();
+        Models models = col.getModels();
+        DeckConfig dconf = col.getDecks().getConf(1);
+        dconf.getJSONObject("new").put("bury", true);
+        final int nbNote = 2;
+        Note[] notes = new Note[nbNote];
+        for (int i = 0; i < nbNote; i++) {
+            Note note  = addNoteUsingBasicAndReversedModel("front", "back");
+            notes[i] = note;
+            Timber.d("note %d has cards %d and %d", i, note.cards().get(0).getId(), note.cards().get(1).getId());
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java:192]: Note.cards() is slow, factor it into one call

File: AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java (hunk 3 above)
Comment (Arthur-Milchior) [reply AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java:155]: Done

File: AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java (hunk 5 above)
Comment (Arthur-Milchior) [reply AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java:180]: siblingCorrectlyBuried

File: AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java (hunk 6 above)
Comment (Arthur-Milchior) [reply AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java:151]: testCardQueue

That's really the whole point, testing this class

File: AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java (hunk 7 above)
Comment (Arthur-Milchior) [reply AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java:192]: Actually, I remove the timber. Used it for debugging. I don't want it anymore

**Comment by Arthur-Milchior** [comment]
Given the size of inner classes, i moved them in their own file

File: AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java (hunk 4 above)
Comment (Arthur-Milchior) [reply AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java]: Indeed. If we really want efficiency however, directly querying the database would be better, since here we create a card object only to get its id.
No way to gets cids from note I thing

**Comment by Arthur-Milchior** [comment]
FYI, since the queue is not a list anymore, the matcher hasSize does not work anymore

**Comment by Arthur-Milchior** [comment]
It would be Collection. And it would require to implements 8 other methods while I don't expect to use them. I don't believe it is worth doing it just to be able to use hasSize

**Comment by mikehardy** [comment]
Okay - we just got an alpha user reporting they can't review and I fear losing participants in the alpha track so I'm going to merge and release this one

**Comment by Arthur-Milchior** [comment]
Were you waiting for something ? 

I'm surprised that they can't review at all. The first card should always be able to be reviewed. But that's really not enough for any normal usage

**Comment by mikehardy** [comment]
I was only waiting to stop sleeping, wake up and get to it, everything was addressed while I was sleeping :-)

**Comment by Arthur-Milchior** [comment]
Makes perfect sens :)
I thought that you meant that if there were not those emergency you would not have merged it, which surprised me.
I understand better now.
