### PR TITLE
Fixes #7013 Fixed deprecated NetworkInfo

### LINKED ISSUE #7013: NetworkInfo deprecated, need new "isConnected" logic
https://developer.android.com/reference/android/net/NetworkInfo

It is unfortunately not a straightforward port, they have de-constructed the network and "do I have a connection?" information into a set of much finer grained objects and states, with async capabilities, and they have done it progressively over a few APIs, so the only non-deprecated APIs don't exist on our whole API skew, and the new APIs require iterating over all sorts of network types and seeing their precise state

### PR DESCRIPTION
**Pull request by mrudultora**
## Purpose / Description
Fixed the deprecated NetworkInfo as it was deprecated.

## Fixes
Fixes #7013

## Approach
By using different methods in APIs greater than or equal to 23.

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/async/Connection.java [hunk 1]
```diff
@@ -556,16 +558,26 @@ public void publishProgress(int id, long up, long down) {
...
 
-    @SuppressWarnings("deprecation") // TODO Tracked in https://github.com/ankidroid/Anki-Android/issues/7013
+    @SuppressWarnings("deprecation")
     public static boolean isOnline() {
         if (sAllowSyncOnNoConnection) {
             return true;
         }
         ConnectivityManager cm = (ConnectivityManager) AnkiDroidApp.getInstance().getApplicationContext()
                 .getSystemService(Context.CONNECTIVITY_SERVICE);
-        if (cm != null) {
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/async/Connection.java:566]: Now that we have multiple conditionals requiring a non-null ConnectionManager, I'd prefer the first check to be a quick-return to simplify the future conditionals and make the code easier to reason about

```java
if (cm == null) {
    // we can't do anything with out a ConnectionManager
    return false;
}

File: AnkiDroid/src/main/java/com/ichi2/async/Connection.java [hunk 2]
```diff
@@ -556,16 +558,26 @@ public void publishProgress(int id, long up, long down) {
...
+
+        /* NetworkInfo is deprecated in API 29 so we have to check separately for higher API Levels */
+        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q && cm != null) {
+            Network network = cm.getActiveNetwork();
+            if (network == null) {
+                return false;
+            }
+            NetworkCapabilities networkCapabilities = cm.getNetworkCapabilities(network);
+            return networkCapabilities != null && (networkCapabilities.hasTransport(NetworkCapabilities.TRANSPORT_WIFI)
+                    || networkCapabilities.hasTransport(NetworkCapabilities.TRANSPORT_CELLULAR));
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/async/Connection.java:577]: I don't understand this part. Why do we care if it is WIFI or CELLULAR specifically? Why isn't BLUETOOTH okay?

I think what we really care about is INTERNET https://developer.android.com/reference/android/net/NetworkCapabilities#NET_CAPABILITY_INTERNET ?

File: AnkiDroid/src/main/java/com/ichi2/async/Connection.java [hunk 3]
```diff
@@ -556,16 +558,26 @@ public void publishProgress(int id, long up, long down) {
         super.publishProgress(id, up, down);
     }
 
-    @SuppressWarnings("deprecation") // TODO Tracked in https://github.com/ankidroid/Anki-Android/issues/7013
+    @SuppressWarnings("deprecation")
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/async/Connection.java:561]: Can we remove this now?

File: AnkiDroid/src/main/java/com/ichi2/async/Connection.java (hunk 2 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/async/Connection.java:577]: Here is how the most popular react-native network information package handles it, some neat tricks in here:

https://github.com/react-native-netinfo/react-native-netinfo/blob/371acf957cb25275395a268fd61a285e60a01acf/android/src/main/java/com/reactnativecommunity/netinfo/NetworkCallbackConnectivityReceiver.java#L83-L105

**Review by mikehardy — CHANGES_REQUESTED** [review]
I think these needs some more detail work per my comments but I *definitely* appreciate the effort - cleaning up deprecation is something users never really think about but they do appreciate that the app keeps running over decade(s)...

File: AnkiDroid/src/main/java/com/ichi2/async/Connection.java (hunk 3 above)
Comment (mrudultora) [reply AnkiDroid/src/main/java/com/ichi2/async/Connection.java:561]: No. Because I tried to remove this and then the build failed. It was not letting me to import `android.net.NetworkInfo`. I was getting a **-Werror**.

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/async/Connection.java:561]: No unfortunately, there is no way to avoid touching deprecated APIs until minSdkVersion moves up past the point where they're needed

**Comment by mrudultora** [comment]
Changes done !

**Review by mikehardy — APPROVED** [review]
Looks good to me thanks!
