### PR TITLE
Make undo icon gray when the icon is unavailable

### LINKED ISSUE #15455: [Bug] Undo icon is not grayed when the icon is unavailable
###### Reproduction Steps

1. Start the app
2. Open a deck
3. See Undo icon in the app bar or in the three dot menu

###### Expected Result
Undo icon is grayed, as the followings in 2.16.5.
image
image

###### Actual Result
Undo icon is not grayed, in contrast to Redo icon.
image
image

###### Debug info
AnkiDroid Version = 2.17beta2 (2412d48c21a51aa13774618c051adbffec5f3d66)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.143 Mobile Safari/537.36

ACRA UUID = df169a4d-29ec-46b6-b114-141ca7e01ba3

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by snowtimeglass**
## Purpose / Description
Make the undo icon "grayed out" appearance when there is no action to undo.

## Fixes
* Fixes #15455

## How Has This Been Tested?
Checked on a physical device (Android 11)

https://github.com/ankidroid/Anki-Android/assets/10436072/e424948d-4e1e-41e3-a23e-cd8056e7a159

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by neeldoshii** [comment]
Looks good!! Can you share how it looks on all the theme after change?

**Comment by mikehardy** [comment]
@neeldoshii

> Looks good!! Can you share how it looks on all the theme after change?

...not a bad idea in general however this is a well-used technique in the code and is Theme-aware since the alteration is an alpha blend, not a color change:

https://github.com/ankidroid/Anki-Android/blob/6cd43069d54ce5e13d9b0bd84f111f7527d7791e/AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt#L42

...as it just changes the opacity, and in a way that other code paths are using, I'm inclined to approve

**Review by mikehardy — APPROVED** [review]

**Review by david-allison — APPROVED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt [hunk 1]
```diff
@@ -754,6 +754,7 @@ open class Reviewer :
                 // so in some languages such as Japanese, which have pre/post-positional particle with the object,
                 // we need to use the string for just "Undo" instead of the string for "Undo %s".
                 undoIcon.title = resources.getString(R.string.undo)
+                undoIcon.iconAlpha = Themes.ALPHA_ICON_DISABLED_LIGHT
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt:757]: The comment above seems like it doesn't relate to this functionality

But it is correct, thanks!
