### PR TITLE
fixed the crash that occured due to `getResources()` error

### LINKED ISSUE #13085: [Bug] Crash: Downloading deck in background
###### Reproduction Steps

1. Download Deck
2. Move App to Background
3. Unknown about anything more - **can't reproduce**

###### Expected Result

* no crash, some UI to show the download is finished, and I should switch back to the app

###### Actual Result

Logcat attached

```
2023-01-09 02:21:11.430 18201-18201 AndroidRuntime          com.ichi2.anki.debug                 E  FATAL EXCEPTION: main
                                                                                                    Process: com.ichi2.anki.debug, PID: 18201
                                                                                                    java.lang.IllegalStateException: Fragment ImportDialog{ea321ae} (722f8382-52c8-40f1-ba40-a1cafea7c624 tag=dialog) not attached to a context.
                                                                                                    	at androidx.fragment.app.Fragment.requireContext(Fragment.java:967)
                                                                                                    	at androidx.fragment.app.Fragment.getResources(Fragment.java:1031)
                                                                                                    	at com.ichi2.anki.dialogs.ImportDialog.getNotificationTitle(ImportDialog.kt:86)
                                                                                                    	at com.ichi2.anki.AnkiActivity.showAsyncDialogFragment(AnkiActivity.kt:510)
                                                                                                    	at com.ichi2.anki.AnkiActivity.showAsyncDialogFragment(AnkiActivity.kt:488)
                                                                                                    	at com.ichi2.anki.DeckPicker.showImportDialog(DeckPicker.kt:1413)
                                                                                                    	at com.ichi2.anki.dialogs.DialogHandler.handleMessage(DialogHandler.kt:56)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8741)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
2023-01-09 02:21:11.437 18201-18201 ACRA                    com.ichi2.anki.debug                 E  ACRA caught a IllegalStateException for com.ichi2.anki.debug
                                                                                                    java.lang.IllegalStateException: Fragment ImportDialog{ea321ae} (722f8382-52c8-40f1-ba40-a1cafea7c624 tag=dialog) not attached to a context.
                                                                                                    	at androidx.fragment.app.Fragment.requireContext(Fragment.java:967)
                                                                                                    	at androidx.fragment.app.Fragment.getResources(Fragment.java:1031)
                                                                                                    	at com.ichi2.anki.dialogs.ImportDialog.getNotificationTitle(ImportDialog.kt:86)
                                                                                                    	at com.ichi2.anki.AnkiActivity.showAsyncDialogFragment(AnkiActivity.kt:510)
                                                                                                    	at com.ichi2.anki.AnkiActivity.showAsyncDialogFragment(AnkiActivity.kt:488)
                                                                                                    	at com.ichi2.anki.DeckPicker.showImportDialog(DeckPicker.kt:1413)
                                                                                                    	at com.ichi2.anki.dialogs.DialogHandler.handleMessage(DialogHandler.kt:56)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8741)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

###### Debug info

AnkiDroid Version = 2.16alpha92

Android Version = 13

Manufacturer = samsung

Model = SM-G991B

Hardware = exynos2100

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-G991B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.128 Mobile Safari/537.36

ACRA UUID = 0d021d4a-396d-41dc-bcf1-5f5ab3cda22a

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by criticalAY**
## Pull Request template
crash fix

## Purpose / Description
this error was caused due to the `resource` method which requires a fragment attached to some activity but when we closed the application the dialog had no activity to attach hence the crash.

## Fixes
Fixes #13085

## Approach
used the application context itself to avoid the crash and access the resources(string in this case)

## How Has This Been Tested?
Tested on oneplus nord ce

https://user-images.githubusercontent.com/48384865/211266804-8ece0aa7-9931-49e3-89a7-415dc66fbcc4.mp4

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by criticalAY** [comment]
I will make one more commit to directly use the `appResources` from the import itself I mean will simplify it

**Comment by criticalAY** [comment]
It is creating the language issue but Brayan  the ` notificationMessage` and `notificationTitle` properties are part of the `AsyncDialogFragment` class, which means that they are not specific to a particular instance of the` ImportDialog` class. As a result, they will not retain their data when the fragment is detached and reattached.

**Comment by criticalAY** [comment]
@BrayanDSO 
test2
, I have taken care of it in the latest commit

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt [hunk 1]
```diff
@@ -507,8 +507,8 @@ open class AnkiActivity : AppCompatActivity, SimpleMessageDialogListener, Collec
             // Store a persistent message to SharedPreferences instructing AnkiDroid to show dialog
             DialogHandler.storeMessage(newFragment.dialogHandlerMessage)
             // Show a basic notification to the user in the notification bar in the meantime
-            val title = newFragment.notificationTitle
-            val message = newFragment.notificationMessage
+            val title = resources.getString(R.string.import_title)
+            val message = resources.getString(R.string.import_interrupted)
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt:511]: `showAsyncDialogFragment` is a generic method used to show a variety of dialogs. This currently hardcodes it to always show the import dialog title and message

**Review by BrayanDSO — CHANGES_REQUESTED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt (hunk 1 above)
Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt:511]: then I think it would be the best to use ViewModel or services, I'll go with that approach

**Comment by criticalAY** [comment]
@BrayanDSO as far as I have researched through the documentation to access the resources we need some context and here in our case there is no context for the fragment to attach to even if we use the ViewModel it is of no use because viewmodels also require some context for initiation say we can store the resource value using ViewModel  inside `onDestory` but we won't we able to retrieve it as there would we no context(as the activity/fragment is not opening), So either we use an if-else condition (here we will have a restriction for the language but the crash would be avoided) or leave it as it is(which is no good either).

Waiting for your response

**Comment by BrayanDSO** [comment]
Can we check if context is null and return on the method or kill the fragment if necesary?

This probably isn't the proper Android way to do things, but I don't have the time to investigate it myself right now.

**Comment by criticalAY** [comment]
Screenshot_2
Test

**Comment by criticalAY** [comment]
@BrayanDSO I think this one should work

**Comment by criticalAY** [comment]
@BrayanDSO could you please look into it whenever you are free

**Comment by criticalAY** [comment]
@david-allison Could you review this PR whenever you are free

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.kt [hunk 2]
```diff
@@ -78,12 +80,12 @@ class ImportDialog : AsyncDialogFragment() {
 
     override val notificationMessage: String
         get() {
-            return resources.getString(R.string.import_interrupted)
+            return asyncMessageContent
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.kt:83]: I'd wager replacing this with `res().getString` is a better approach

**Review by david-allison — CHANGES_REQUESTED** [review]
Not too familiar here, but I feel we have a solution in the base class which will resolve this

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.kt (hunk 2 above)
Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.kt:83]: `res()` was removed in one of the previous PR

**Comment by criticalAY** [comment]
I have already tried this `val res = AnkiDroidApp.appResources` approach it restricts the language from the strings

**Comment by david-allison** [comment]
Sorry this sat, missed the reply

**Comment by criticalAY** [comment]
No issue thanks!

**Review by mikehardy — APPROVED** [review]
LGTM - thanks!
