### PR TITLE
[BugFix]: Restore backups as writable database

### LINKED ISSUE #7083: Restore backup on initial install leaves app in unexpected state
###### Reproduction Steps

1. remove `/sdcard/AnkiDroid` on device (note! This is obviously dangerous, this is a testing device right?)
2. install fresh AnkiDroid (seen in firebase auto-testing lab on 2.14alpha3 release
3. accept storage permission, note empty collection screen, choose "restore from backup" from menu
4. restore from the only backup available
5. hit the '+' button the FAB and add a note, save the note

###### Expected Result

The note should save correctly and become the only note in the collection

###### Actual Result

The database is closed. I'm not sure if the backed up "collection" (from the initial install) is/was invalid and so the collection isn't open, or there is an open failure or something, but the note save won't work

```
09-14 08:32:02.626  7393  7641 E SQLiteLog: (1032) statement aborts at 43: [insert or replace into notes values (?,?,?,?,?,?,?,?,?,?,?)] attempt to write a readonly database
09-14 08:32:02.626  7393  7641 E CollectionTask: doInBackgroundAddNote - RuntimeException on adding note
09-14 08:32:02.626  7393  7641 E CollectionTask: android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at io.requery.android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at io.requery.android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:778)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at io.requery.android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:764)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at io.requery.android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:71)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at io.requery.android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1919)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at io.requery.android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1911)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at com.ichi2.utils.DatabaseChangeDecorator.execSQL(DatabaseChangeDecorator.java:211)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at com.ichi2.libanki.DB.execute(DB.java:330)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at com.ichi2.libanki.Note.flush(Note.java:142)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at com.ichi2.libanki.Note.flush(Note.java:123)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at com.ichi2.libanki.Note.flush(Note.java:119)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at com.ichi2.libanki.Collection.addNote(Collection.java:651)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at com.ichi2.async.CollectionTask.doInBackgroundAddNote(CollectionTask.java:516)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at com.ichi2.async.CollectionTask.actualDoInBackground(CollectionTask.java:361)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:309)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:90)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at java.lang.Thread.run(Thread.java:919)

```

As a side note, the robo-tester in the video I watched got hung up trying to add an AnkiWeb account, so for some reason it is breaking out of the "monkey cage" and getting to that. This occurred because the monkey clicked the sync button

I did see the toast saying "robot detected if you are a human and you see this contact support" so I know the monkey cage was in place, it just has an area where the bars are too wide apart and the animals take over the zoo :-)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description
App crashed after a database write if backups were restored from

## Fixes
Fixes #7083 

## Approach
Simple 1-line fix to move time acquisition to before database locking

## How Has This Been Tested?

🛑 Manually, sadly, I could not get the test to fail on Windows

## Learning

By default, Robolectric assigns you 0 disk space

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

File: AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java [hunk 1]
```diff
@@ -298,13 +306,18 @@ public void onPreExecute() {
 
             @Override
             public void onPostExecute(TaskData result) {
+
+                if (result == null || !result.getBoolean()) {
+                    throw new IllegalArgumentException("Task failed");
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java:311]: This could theoretically fail some tests in CI

Comment (mikehardy) [reply AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java:311]: appears to have worked so far...

**Review by mikehardy — APPROVED** [review]
thanks for the quick fix!
