### PR TITLE
Use system deck picker for package import

### LINKED ISSUE #3420: Import/Export doesn't work in ChromeOS
Originally reported on Google Code with ID 2524

```
It tries to save to sdcard, which is not present in chromebook. Also it opens gmail,
but can't add the attachement.
```

Reported by `pyatasya` on 2015-02-13 22:02:22

### LINKED ISSUE #4834: [Bug] Wrong cryptic path in import message
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Touch Import in Option

###### Expected Result
Maybe, technically it's correct, but message is not user friendly. It reads `sdcard` but in my case it is _not_ the external microSD card but the internal storage (`emulated`).
Creating `AnkiDroid` folder on microSD doesn't make import available but putting apkg in the main storage does.

Same bug in the Settings

###### Actual Result
Appears this message https://github.com/ankidroid/Anki-Android/blob/161ef99ab324eb427bc92586e524e42f68886284/AnkiDroid/src/main/res/values/02-strings.xml#L145
> Place apkg file in directory "/sdcard/AnkiDroid/" ...

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

### LINKED ISSUE #4932: Enhancement: Use standard file picker for package import/export on API>=19
As mentioned by Tim on #3906:
```
It's always been the intention to use ACTION_OPEN_DOCUMENT to import apkgs
on API 19+, just nobody has ever gotten around to it.
```

Feel free to disagree with any of this, but I think the general idea is that if the API level supports it, AnkiDroid should completely bypass the current file selector and instead use [Intent.ACTION_OPEN_DOCUMENT](https://developer.android.com/reference/android/content/Intent#ACTION_OPEN_DOCUMENT) to do collection imports.

Bonus points for using [Intent.ACTION_CREATE_DOCUMENT](https://developer.android.com/reference/android/content/Intent#ACTION_CREATE_DOCUMENT) when exporting an apkg

Some reasonable example code that show how to set the Intent options and open the resulting content:// URI stream:
http://www.zoftino.com/how-to-create-browse-files-option-in-android

### PR DESCRIPTION
**Pull request by mikehardy**
## Purpose / Description
Android provides a nice file picker for Android 4.4+ / KitKat / API19+ - this change defers to that file picker for package selection and only falls back to our internal "picker" for API<19

## Fixes
Fixes #4932 - the enhancement request
Obsoletes / Fixes #4834 - UI issue with regard to how to display filename
Fixes #3420 - Chromebook import/export (it works!)

## Approach
3 commits - review them separately for easy review

1. I decomposed the application IntentHandler, which was already charged with ingesting unknown files with the intention of importing them, so that I could re-use all the sanity checking and processing inside it and avoid code duplication in code pathways dealing with external input

1. Then for API19+ if the user chooses to import decks I simply fire a normal file open intent, tuned for "CATEGORY_OPENABLE" which avoids all the new virtual file / content streaming stuff Android allows but won't work for us, then listen for the result and handle it the same as if a user had picked a file from our internal picker dialog

1. De-lint / codacy commit that doesn't alter functionality at all

## How Has This Been Tested?

I checked it on an API18 and API28 emulator (before and after the system picker) with a valid apkg, an invalid file, and the same apkg twice. Everything seemed fine

## Checklist

I changed unnecessary things in the 3rd commit, but it's how I'm slowly pushing the project to comply with style

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.java [hunk 1]
```diff
@@ -44,106 +47,129 @@ protected void onCreate(Bundle savedInstanceState) {
...
+
+
+    /**
+     * This code is used in multiple places to handle package imports
+     *
+     * @param context for use in resource resolution and path finding
+     * @param intent contains the file to import
+     * @return empty string if successful, otherwise error message
+     */
+    public @NonNull String handleFileImport(Context context, Intent intent) {
```
[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.java]: If you think that's bad, you should have seen it before extract method...

**Comment by timrae** [comment]
I'm guessing this approach probably doesn't actually work in general for files that were manually copied across from a computer to the device?

**Comment by mikehardy** [comment]
I'm not sure I understand - I only checked shared deck downloads but how is a copy different?

**Comment by mikehardy** [comment]
Huh. I rebased and checked and...at least a full collection export with media from my actual device did not go via this method, which is unexpected and not okay. I'll look into it - I know IntentHandler has code for the "replace" case so should have worked...

**Comment by mikehardy** [comment]
Ok, I wasn't handling IMPORT_REPLACE correctly but that was a message-passing issue. I'm still not sure I understand, but I copied my whole collection (via adb) to an emulator from my device and it imported fine, with the replace dialog (after I caught that id in the deck picker case too). Re-pushing in a second with that fix and the rebase

**Comment by timrae** [comment]
> I'm still not sure I understand

I meant that the UI presented by `ACTION_OPEN_DOCUMENT` lets you choose from a list of document providers, rather than letting you actually choose a file from `/sdcard`. I just pulled your branch and took it for a spin, and eventually realized that while the UI does hide it by default, there is an item in the overflow menu which allows you to see `/sdcard`. Considering I only just realized it was there, and only a small fraction of users ever think to check the manual or release notes, I'm worried that it's not going to present a great UX :/

It would be really nice if there were an extra we could pass in the intent to get that UI to show the sdcard by default, or even better to start at a particular location `/sdcard/AnkiDroid` if it exists, but I couldn't find anything online.

**Comment by timrae** [comment]
Or is there....?

https://issuetracker.google.com/issues/72053350

**Comment by mikehardy** [comment]
Ok - I'll see what I can do. For me, it opens right on Downloads, but maybe that's just because my emulator has no apps (e.g. no intent handlers). I think once we start using the file picker everyone is just going to be using Downloads anyway - it's where the system dumps things normally, and if a user put it somewhere else they already know what they are doing. Not arguing for bad UX - just saying getting it to the "system downloads folder" as a default is ideal, to me, with the rest available if possible (good link above)

**Comment by timrae** [comment]
> I think once we start using the file picker everyone is just going to be using Downloads anyway

I think connecting device to computer and copying an apkg across is still the main usage case of this feature... If the file is downloaded from somewhere then the user is most likely going to be importing it via the normal VIEW intent rather than from the menu entry.

>  I'll see what I can do

I've already tested the above, and it works, so please just do that

**Comment by timrae** [comment]
> if a user put it somewhere else they already know what they are doing

I'd like to think I know what I'm doing, and I only just discovered that overflow menu item

**Comment by mikehardy** [comment]
Ok, just added those 3 extras, and re-pushed: advanced fancy mode is now true

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.java [hunk 2]
```diff
@@ -67,8 +70,19 @@ public MaterialDialog onCreateDialog(Bundle savedInstanceState) {
                         .show();
             }
             case DIALOG_IMPORT_SELECT: {
-                // Allow user to choose from the list of available APKG files
-                List<File> fileList = Utils.getImportableDecks(getActivity());
+                List<File> fileList;
+                // for API19+ we come here with the path to a file from a file picker in dialogMessage.
+                String dialogMessage = getArguments().getString("dialogMessage");
+                if ((dialogMessage != null) && dialogMessage.endsWith(".apkg")) {
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.java]: As far as I can tell, this part of the diff is completely unnecessary. Maybe this is a remnant of a previous iteration of your work?

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java [hunk 3]
```diff
@@ -654,6 +655,13 @@ protected void onActivityResult(int requestCode, int resultCode, Intent intent)
         } else if (requestCode == REQUEST_PATH_UPDATE) {
             // The collection path was inaccessible on startup so just close the activity and let user restart
             finishWithoutAnimation();
+        } else if ((requestCode == PICK_APKG_FILE) && (resultCode == RESULT_OK)) {
+            // We reuse the IntentHandler (which handles system requests to open .apkg) to import when user uses file picker
+            IntentHandler apkgHandler = new IntentHandler();
```
[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java]: Ok, I've pulled all the good IntentHandler import logic into ImportUtils instead of just excitedly hijacking it after I found it - in the next push

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.java (hunk 2 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ImportDialog.java]: Yep, was vestigial - nuked

**Comment by mikehardy** [comment]
Just re-pushed

**Comment by mikehardy** [comment]
@timrae  Okay, fingers crossed this one looks good. I did self-review it but who knows what th eyes gloss over when things are too familiar

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java [hunk 4]
```diff
@@ -220,6 +221,12 @@ protected void enableViewAnimation(View view, Animation animation) {
         }
     }
 
+    /** Finish Activity using FADE animation **/
+    public static void finishActivityWithFade(Activity activity) {
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java]: I don't really like having this as a static function, which is why I was pushing to get rid of the `showImportUnsuccessfulDialog()` method, but it's not really worth going through another iteration for
