### PR TITLE
fix: Image Occlusion webView being recreated in orientation changes

### LINKED ISSUE #15392: [BUG]: Image Occlusion: Screen rotation reloads editor, forgetting unsaved changes
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

- 1 open Image Occlusion editor
  - + add, set note type to Image Occlusion, open an image
  - open an existing Image Occlusion note type, click Edit Occlusions
- 2 add a box (or move, resize, delete)
- 3 turn phone

### Expected behaviour

the Image Occlusion editor, image, and boxes resize to the new aspect ratio

### Actual behaviour

the added box is deleted (or the moved box is moved back, the resized box is sized back, the deleted box is added back)

### Debug info

```text
AnkiDroid Version = 2.17alpha17 (866369337a2ee1838b2075a401029c11b0fc33e9)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 11 (SDK 30)

ProductFlavor = play

Manufacturer = FIH

Model = EC1002

Hardware = mt6761

Webview User Agent = Mozilla/5.0 (Linux; Android 11; EC1002 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.143 Safari/537.36

ACRA UUID = c8fe5a3e-6bce-4976-867c-42a883891f6b

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

you're editing in landscape mode and need to answer a call
you're editing in bed, you sit up/lay down/roll over, and unexpectedly lose your many boxes

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by criticalAY**
## Purpose / Description
Allow `SingleFragmentActivity` to survive config changes

## Fixes
* Fixes #15392

## How Has This Been Tested?
Google Pixel 8 emualtor 
Posting emulator ss itself
image
image

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by BrayanDSO — CHANGES_REQUESTED** [review]
This breaks landscape layouts, big/small screen layouts and follow system night mode.

Reading #12832 may help you understand `configChanges` actually works.

Following the `Open–closed principle`, create another activity for that and add only `orientation|screenSize` to it

File: AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+import android.os.Bundle
+import androidx.fragment.app.Fragment
+import kotlin.reflect.KClass
+import kotlin.reflect.jvm.jvmName
+
+/**
+ * ImageOcclusionActivity extends SingleFragmentActivity and serves as the activity for
+ * handling the Image Occlusion editor functionality and the behavior related to screen rotation
+ * in the Image Occlusion editor, where added, moved, resized, or deleted boxes do not properly
+ * adjust to the new aspect ratio.
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt:29]: I can't undestand what you mean here.

**Review by BrayanDSO — CHANGES_REQUESTED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt (hunk 1 above)
Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt:29]: Doc or the file in general ?

Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt:29]: doc

Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt:29]: It means that this activity is for Image occlusion so that it handles the orientation changes when the editor (IO) has moved or resized (mask)

Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt:29]: 1. adding `configChanges=""` without a `onConfigurationChanged` method means that the configuration changes are being **_ignored_**, not handled.
2. the actual issue is that the activity is recreated, which loses the webview state and happens with any activity with a webview. Not something specific to IO masks
3. You don't need to repeat the name of a class in its doc

```suggestion
* Handles adding and editing Image Occlusion cards.
* 
* Based in [SingleFragmentActivity], but with `configChanges="orientation|screenSize"`
* to avoid unwanted activity recreations
```

Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt:29]: `onConfigurationChanged` overrides nothing? I removed that due to this

**Comment by criticalAY** [comment]
> onConfigurationChanged method means that the configuration changes are being ignored, not handled.

Just want to clear my device handles them without this being override? just adding `configChanges` why?

**Comment by BrayanDSO** [comment]
`configChanges=` means that we want to handle the configuration changes ourselves and don't want the system to recreate the activity automatically when the specified configuration are changes.

How to handle configuration changes ourselves? with `onConfigurationChanged`

If we don't use `onConfigurationChanged`, what happens? the configuration change is ignored

**Comment by criticalAY** [comment]
I read a lot of comments and post for some people it works just by putting the configChanges in manifest file ?
https://stackoverflow.com/questions/12131025/android-preventing-webview-reload-on-rotate

**Comment by BrayanDSO** [comment]
> I read a lot of comments and post for some people it works just by putting the configChanges in manifest file ?
https://stackoverflow.com/questions/12131025/android-preventing-webview-reload-on-rotate

It does and I never said it doesn't. I'm trying to explain why it works

**Review by BrayanDSO — APPROVED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+ * Handles adding and editing Image Occlusion cards.
+ *
+ * Based in [SingleFragmentActivity], but with `configChanges="orientation|screenSize"`
+ * to avoid unwanted activity recreations
+ */
+class ImageOcclusionActivity : SingleFragmentActivity() {
+
+    override fun onConfigurationChanged(newConfig: Configuration) {
+        super.onConfigurationChanged(newConfig)
+    }
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt:36]: If a subclass declares an override method that does nothing but calls the super for the method, do you have to actually override the method?

Isn't this the same behavior as not overriding it at all - meaning this shouldn't be here?

**Review by mikehardy — COMMENTED** [review]
Seems like it should work, but obviously seems like the override-that-only-calls-super is redundant?

File: AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt (hunk 2 above)
Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt:36]: This is what I was saying here, 
> I read a lot of comments and post for some people it works just by putting the configChanges in manifest file ?
https://stackoverflow.com/questions/12131025/android-preventing-webview-reload-on-rotate

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt:36]: What I want to hear is "I tested it without the seemingly redundant override-that-only-calls-super and I discovered...." (then some description of your results)

Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt:36]: I tested it out without it too and with it ,and it works fine without it

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt:36]: (because unless I'm misunderstanding how overrides and super calls work, if you override but only call super, you're not doing anything and your override is redundant and unneeded - I need to see experimental results that contradict my understanding, not some stackoverflow faffery :-) )

Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt:36]: ok thanks!

Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionActivity.kt]: Done!!

**Review by mikehardy — APPROVED** [review]
nice, LGTM

**Review by david-allison — APPROVED** [review]
