### PR TITLE
Follow system dark mode

### LINKED ISSUE #5685: Follow Android system-level dark mode settings
Hi. AnkiDroid has an app-specific dark mode that does not follow the system-level configuration present in newer versions of Android. Would you accept a up-to-standard pull request implementing automatically switching night mode on when Android system gets switched to night mode, and automatically switching night mode off when Android system night mode gets switched off?
If nobody has the bandwidth to fix this soonish, I might do it myself or maybe place a bounty on it.

###### Reproduction Steps

1. Start out with AnkiDroid in light mode, system in light mode
2. Turn on Android dark mode (e.g., using the quick settings bar in the notification bar)

###### Expected Result

AnkiDroid should follow the system-level dark mode settings and switch to dark mode.

###### Actual Result

AnkiDroid remains in light mode unless you manually switch it.

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

### PR DESCRIPTION
**Pull request by BrayanDSO**
## Fixes
Fixes #5685

## Approach
Supersedes / Obsoletes #10035 and #5686

- Remove navigation drawer night mode toggle
- Add a `Theme` option where the user can choose the app theme
    - If `Follow system` is selected, app theme will use what is set on `Day` or `Night` theme, depending on user current system mode
    - If any other theme is selected, it will be the app theme and `Day` and `Night` will be disabled
- In API < 29, which don't have a system dark mode option, hide the follow system and day/night modes

Note: `theme_light`, `theme_plain`, `theme_black`, `theme_dark` need to be moved from their arrays. 
This PR is blocked until then. For now, these strings are being duplicated, as settled in Discord.

### API ≥ 29 
On my device, Samsung Galaxy Note 10 Lite SM-N770F/DS, API 30

https://user-images.githubusercontent.com/69634269/158073806-3ed5e6ee-b97e-4f74-a3fc-d2514b7ecf68.mp4

### API < 29
Android Studio Emulator, API 25

https://user-images.githubusercontent.com/69634269/158073593-46f95126-47e4-4b5a-8162-c1df4eafb0fb.mp4

## Learning (optional, can help others)
When trying to figure out the framents flow:
https://developer.android.com/guide/fragments/fragmentmanager
https://developer.android.com/reference/androidx/core/app/TaskStackBuilder (not used, handles activities)

Enums increase the app size
https://developer.android.com/topic/performance/reduce-apk-size#remove-enums

## Strings
Screenshot_20220313-152749_AnkiDroid
Screenshot_20220313-152806_AnkiDroid

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by BrayanDSO** [comment]
A design option to discuss is making `Day theme` and `Night theme` invisible instead of disabled when `Follow system` is not being used. 

I personally prefer making them invisible, but for now they are being disabled because is less disruptive and needs discussion

File: AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt [hunk 1]
```diff
@@ -18,38 +18,43 @@
...
+    private const val APP_THEME_KEY = "appTheme"
+    private const val DAY_THEME_KEY = "dayTheme"
+    private const val NIGHT_THEME_KEY = "nightTheme"
+    private const val NIGHT_MODE_PREFERENCE = "invertedColors"
 
-    // Day themes
-    const val THEME_DAY_LIGHT = 0
-    const val THEME_DAY_PLAIN = 1
+    // Single themes values
+    const val FOLLOW_SYSTEM_MODE = "0"
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt:41]: if this were an int, wouldn't it simplify all the handling of the preference value?

File: AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt [hunk 2]
```diff
@@ -18,38 +18,43 @@
...
+    private const val SINGLE_THEME_LIGHT = 1
+    const val SINGLE_THEME_PLAIN = 2
+    private const val SINGLE_THEME_BLACK = 3
+    const val SINGLE_THEME_DARK = 4
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt:45]: For safety on all of these items you can make them a constrained set of values in a named set, then annotate callers that they should be one of the values in the set

example
https://github.com/ankidroid/Anki-Android/blob/edaf6febd0aaf4c2ce6baea52d7f0a3912b39381/AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt#L133-L135
https://github.com/ankidroid/Anki-Android/blob/edaf6febd0aaf4c2ce6baea52d7f0a3912b39381/AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.kt#L97

strictly necessary? Definitely not, but it is a cool trick and certainly makes all of these magical values a lot safer to handle

**Review by mikehardy — CHANGES_REQUESTED** [review]
I like all of this and I know it's going to be popular with users, except I'm concerned about the type handling of all the constants - left some comments about that, what do you think?

File: AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt (hunk 1 above)
Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt:41]: Yes and no. The scenario is:
1. Themes constants need to be integers because they are used as it in many other classes and changing there would be unnecessary trouble
2. List Preferences can only use strings as values
3. Follow system is not obligated to be either string or integer. It's here as a string because its string-array value is a string and converting both to int just to compare them is unnecessary

The simplest way to solve this is to have a comment explaining why `FOLLOW_SYSTEM_MODE` is a string instead of always having to convert it back from integer to string

**Comment by BrayanDSO** [comment]
Made `Themes` constant names more consistent on d091a77

File: AnkiDroid/src/main/res/values/constants.xml [hunk 3]
```diff
@@ -254,7 +254,24 @@
         <item>@string/full_screen_system</item>
         <item>@string/full_screen_complete</item>
     </string-array>
-
+    <!-- Themes -->
+    <string name="app_theme_key">appTheme</string>
```
Comment (david-allison) [inline AnkiDroid/src/main/res/values/constants.xml:258]: Move the keys to https://github.com/ankidroid/Anki-Android/blob/main/AnkiDroid/src/main/res/values/preferences.xml

**Review by david-allison — COMMENTED** [review]
I've read this through a few times. 

This looks good and I'm really glad we got it through, my main concern is around documentation

* Could you add more documentation on the header of `Themes.kt`, explaining that we have two modes, and the reasoning for these two modes.
* At some point in the far future, API 29 will be a distant memory, when this comes, we want to know why decisions were made, and what we can do to simplify the code. Could you explain your thoughts on how we'd do this (and if we'd do this)?

**Comment by BrayanDSO** [comment]
> * Could you add more documentation on the header of `Themes.kt`, explaining that we have two modes, and the reasoning for these two modes.

I've added more docs. Should be clearer now

https://github.com/ankidroid/Anki-Android/blob/3b53a69ea079ab28dedd089c7152485a0bf6b267/AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt#L29-L38

https://github.com/ankidroid/Anki-Android/blob/3b53a69ea079ab28dedd089c7152485a0bf6b267/AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt#L47-L52

https://github.com/ankidroid/Anki-Android/blob/3b53a69ea079ab28dedd089c7152485a0bf6b267/AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt#L61-L66

https://github.com/ankidroid/Anki-Android/blob/3b53a69ea079ab28dedd089c7152485a0bf6b267/AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt#L73-L82

https://github.com/ankidroid/Anki-Android/blob/3b53a69ea079ab28dedd089c7152485a0bf6b267/AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt#L173-L180


# API 29

> * At some point in the far future, API 29 will be a distant memory, when this comes, we want to know why decisions were made, and what we can do to simplify the code. Could you explain your thoughts on how we'd do this (and if we'd do this)?

https://github.com/ankidroid/Anki-Android/blob/3b53a69ea079ab28dedd089c7152485a0bf6b267/AnkiDroid/src/main/java/com/ichi2/anki/Preferences.kt#L825-L831

Simple, just remove the if block and that's it. No breaks, nor having to upgrade

File: AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt [hunk 4]
```diff
@@ -18,57 +18,86 @@
...
+    private const val APP_BLACK_THEME = "3"
+    const val APP_DARK_THEME = "4"
 
     @kotlin.annotation.Retention(AnnotationRetention.SOURCE)
-    @IntDef(THEME_DAY_LIGHT, THEME_DAY_PLAIN)
-    annotation class DAY_THEME_INTERFACE
+    @StringDef(APP_LIGHT_THEME, APP_PLAIN_THEME, APP_BLACK_THEME, APP_DARK_THEME)
+    annotation class AppTheme
 
     /**
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt:61]:
```suggestion
    /*
```

File: AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt [hunk 5]
```diff
@@ -18,57 +18,86 @@
...
+    // Themes preferences keys
+    private const val APP_THEME_KEY = "appTheme"
+    private const val DAY_THEME_KEY = "dayTheme"
+    private const val NIGHT_THEME_KEY = "nightTheme"
+    private const val NIGHT_MODE_PREFERENCE = "invertedColors"
 
-    // Day themes
-    const val THEME_DAY_LIGHT = 0
-    const val THEME_DAY_PLAIN = 1
+    /** App themes values
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/themes/Themes.kt:47]:
```suggestion
    /* App themes values
```

**Comment by BrayanDSO** [comment]
Could the theme values be unified/simplified? Yes, but that would need a preferences upgrade from the previous values to the new ones

Since it is simpler to handle it now than upgrading, I'd rather reserve a upgrade to a bigger change in the themes infrastructure, like adding an option to create custom themes (which is in my TODO list for the future), so there are not the need to have a lot of settings upgrades

**Review by david-allison — APPROVED** [review]
Beauty!

`/**` is a doc comment for a specific variable

`/*` is a comment for the region in Java. I think this is the same in Kotlin

**Review by mikehardy — APPROVED** [review]
Let's do it! Thanks for this

**Comment by mikehardy** [comment]
This looks like it can go with a rebase merge, is that the intention @BrayanDSO ? That's my preference, but wanted to check if you were aware of any reason the individual commits would fail testing and cause problems for a git bisect

**Comment by BrayanDSO** [comment]
All commits pass all tests and compile. So, yes, a rebase merge is better.

There is just the situation about the strings that need to be moved from the xml arrays.
I had added on the PR text:
> Note: theme_light, theme_plain, theme_black, theme_dark need to be moved from their arrays.
> This PR is blocked until then. For now, these strings are being duplicated, as settled in Discord.

This does not seem something I can do myself, since it's necessary to do language sync (stated [here](https://github.com/ankidroid/Anki-Android/pull/7800#issue-753471802)), and I don't know what impedes this to be automated.

@david-allison said on Discord to ping him to do it, so now I am doing it.

**Comment by david-allison** [comment]
I'm happy for this PR to go in as-is. I'll take the lazy approach for #10554, it's better to get it in soon rather than to block PRs over it.

**Comment by david-allison** [comment]
> The strings will need to be retranslated? If so I'm tempted to take the chance to change the day themes names: `Light` -> `Blue` and `Plain` -> `Gray`. But probably I need permission for that

Bring it up in Discord! 

I like `Gray` (we need to beware of Grey/Gray), I personally prefer `Light`, as it's the opposite of `Dark`.

**Comment by david-allison** [comment]
> The strings will need to be retranslated? 

Depending on when we do a translation sync, I'll try to bring the strings back into CrowdIn

**Comment by mikehardy** [comment]
I just want to pause on this for a moment to make sure course of action is still optimal, after merging #10556 - I'm happy with whatever seems right to you @david-allison so you can orchestrate if needed

**Comment by mikehardy** [comment]
I would actually like to keep colors out of the names if possible. We could change our internal themes or adopt the adaptive theming from material and then having any color name in the theme switch is wrong, when what we're really switching is between light and dark or (more finely) between "really dark or kinda dark" and "normal light or de-saturated/monocrhome light". Colors are orthogonal to me and actually a constraint in that sense

:shrug:

**Comment by mikehardy** [comment]
"Show, don't tell" beats all suggestions

image

**Comment by mikehardy** [comment]
I do like their words though, specifying relative contrast, but *not* specifying colors :)

**Comment by mikehardy** [comment]
> If it is not a simple Light or Dark theme, use colors to identify them since it is the main difference among them

Some do, some don't, I specifically chose an example you'll notice where colors were not used ;-). You chose others. We may just disagree here. I still don't like colors in the names.

Less qualitative and more quantitative though: this is no longer blocked by translations -  #10565 merged

**Comment by BrayanDSO** [comment]
Since the names are not going to need a retranslation anymore with #10565 (thanks David), this can be merged as is. 

This discussion may continue when someone takes up #8710 or any other related issue.

**Comment by BrayanDSO** [comment]
Rebased and tested. Good to go!

**Review by david-allison — CHANGES_REQUESTED** [review]
I've tested this on my device and it looks great! Very happy to merge

Ideally I'd like to rebase merge this, but commit 2 doesn't compile: 

```
e: C:\GitHub\Anki-Android-Git\Anki-Android\AnkiDroid\src\main\java\com\ichi2\anki\Preferences.kt: (77, 32): Unresolved reference: systemIsInNightMode
e: C:\GitHub\Anki-Android-Git\Anki-Android\AnkiDroid\src\main\java\com\ichi2\anki\Preferences.kt: (823, 85): Unresolved reference: app_theme_key
e: C:\GitHub\Anki-Android-Git\Anki-Android\AnkiDroid\src\main\java\com\ichi2\anki\Preferences.kt: (833, 72): Unresolved reference: app_theme_labels
e: C:\GitHub\Anki-Android-Git\Anki-Android\AnkiDroid\src\main\java\com\ichi2\anki\Preferences.kt: (834, 72): Unresolved reference: app_theme_values
e: C:\GitHub\Anki-Android-Git\Anki-Android\AnkiDroid\src\main\java\com\ichi2\anki\Preferences.kt: (840, 39): Unresolved reference: themeFollowsSystem
e: C:\GitHub\Anki-Android-Git\Anki-Android\AnkiDroid\src\main\java\com\ichi2\anki\Preferences.kt: (845, 61): Unresolved reference: FOLLOW_SYSTEM_MODE
e: C:\GitHub\Anki-Android-Git\Anki-Android\AnkiDroid\src\main\java\com\ichi2\anki\Preferences.kt: (846, 63): Unresolved reference: FOLLOW_SYSTEM_MODE
e: C:\GitHub\Anki-Android-Git\Anki-Android\AnkiDroid\src\main\java\com\ichi2\anki\Preferences.kt: (856, 56): Unresolved reference: systemIsInNightMode
e: C:\GitHub\Anki-Android-Git\Anki-Android\AnkiDroid\src\main\java\com\ichi2\anki\Preferences.kt: (863, 57): Unresolved reference: systemIsInNightMode
```

**Comment by mikehardy** [comment]
The rare double-wait :-) - pending merge *and* waiting for feedback.
I'm good to go on it as soon as it's rebased with all commits compiling or if that's just too painful we can squash worst case. Hopefully the rebase works

**Comment by BrayanDSO** [comment]
Forgot to disable the pre-commit hook while rebasing, then whole file got staged (#9390). Sorry for the wait, it should be fixed now.

Is there a non-manual way to see if all commits compile?

**Comment by mikehardy** [comment]
> Is there a non-manual way to see if all commits compile?

I don't think so? :sweat_smile:

**Comment by Arthur-Milchior** [comment]
@BrayanDSO I missed this PR. I just realized on my phone that it was following dark mode. I am extremely thankful to you, it was a small painpoint, but really really great improvement in my nightly usage!
