### PR TITLE
fix: Open DeckPicker if collection path changes

### LINKED ISSUE #8422: [Bug]  Don't Keep Activities - Crash on viewing Settings from Reviewer
###### Reproduction Steps

1. Reviewer
2. Settings
3. Reviewer

```
2021-04-01 06:19:17.118 20515-20515/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 20515
    java.lang.NullPointerException: Attempt to invoke virtual method 'int com.ichi2.libanki.DB.queryScalar(java.lang.String, java.lang.Object[])' on a null object reference
        at com.ichi2.libanki.sched.SchedV2._resetLrnCount(SchedV2.java:1042)
        at com.ichi2.libanki.sched.SchedV2.resetCounts(SchedV2.java:247)
        at com.ichi2.libanki.sched.SchedV2.resetCounts(SchedV2.java:227)
        at com.ichi2.libanki.sched.SchedV2.counts(SchedV2.java:361)
        at com.ichi2.libanki.sched.SchedV2.counts(SchedV2.java:357)
        at com.ichi2.libanki.sched.SchedV2.counts(SchedV2.java:373)
        at com.ichi2.anki.Reviewer.updateScreenCounts(Reviewer.java:931)
        at com.ichi2.anki.Reviewer.updateActionBar(Reviewer.java:924)
        at com.ichi2.anki.AbstractFlashcardViewer.updateForNewCard(AbstractFlashcardViewer.java:1894)
        at com.ichi2.anki.AbstractFlashcardViewer.fillFlashcard(AbstractFlashcardViewer.java:2421)
        at com.ichi2.anki.Reviewer.fillFlashcard(Reviewer.java:970)
        at com.ichi2.anki.AbstractFlashcardViewer.updateCard(AbstractFlashcardViewer.java:2268)
        at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:2038)
        at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:1997)
        at com.ichi2.anki.Reviewer.displayCardQuestion(Reviewer.java:982)
        at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.displayNext(AbstractFlashcardViewer.java:626)
        at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.onProgressUpdate(AbstractFlashcardViewer.java:603)
        at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.onProgressUpdate(AbstractFlashcardViewer.java:591)
        at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:241)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:791)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

###### Expected Result

No Crash

###### Actual Result

Crash

###### Debug info

```
AnkiDroid Version = 2.15alpha37

Android Version = 11

Manufacturer = Google

Model = Pixel 3a

Hardware = sargo

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Pixel 3a Build/RQ2A.210305.006; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/89.0.4389.105 Mobile Safari/537.36

ACRA UUID = 501642ec-39d9-4276-97a3-59a4acbfd30e

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description
Before this change, we performed this check on `onActivityResult`.

This was bad, as we had :
* onCreate -> startCollectionLoading -> onCollectionLoaded
* onActivityResult -> closeCollection -> crash

There was also a bug that `mOldColPath` was not saved via `onSaveInstanceState`, this meant "Don't Keep Activities" would cause accessing the preferences to always reopen the collection

## Fixes
Fixes #8422

## Approach
Instead, open the Deck Picker immediately after the "advanced" Window has been closed, if the collection path has changed

## How Has This Been Tested?

On-device testing with "Don't keep Activities"

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java [hunk 1]
```diff
@@ -164,6 +168,40 @@ public boolean onOptionsItemSelected(MenuItem item) {
...
+            super.onBackPressed();
+        }
+    }
+
+
+    protected void restartWithNewDeckPicker() {
+        // PERF: DB access on foreground thread
+        CollectionHelper.getInstance().closeCollection(true, "Preference Modification: collection path changed");
+        Intent deckPicker = new Intent(this, DeckPicker.class);
+        deckPicker.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP | Intent.FLAG_ACTIVITY_NEW_TASK);
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java:187]: Review: Cargo-Culted this from other instances where we do similar things, unsure if it's correct

File: AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java [hunk 2]
```diff
@@ -164,6 +168,40 @@ public boolean onOptionsItemSelected(MenuItem item) {
         return false;
     }
 
+    @Override
+    public void onBackPressed() {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java:172]: Review: Is there a better method to call?

**Review by david-allison-1 — COMMENTED** [review]
Two questions for reviewers

File: AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java (hunk 1 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java:187]: "Cargo-Culted" :laughing: - I believe this is the correct way to obliterate the Activity stack and launch the one and only thing that should then be on it, precluding any "go back to bad state" possibility

File: AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java (hunk 2 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java:172]: I'm not aware of any...

**Review by mikehardy — APPROVED** [review]
Subtle bug - fix looks good - tally-ho :rocket:
