### PR TITLE
Fix permission handling in Multimedia editor

### LINKED ISSUE #5407: When I refuse recording permission, the application gets stuck.
###### Reproduction Steps

1. Click on the menu
2. Click "card browser"
3. Click the plus sign in the lower right corner
4. Click the plus sign in the upper right corner
5. Click the "Add Attachments" button
6. Click "record audio"
7. Deny permission requests and request no longer to be displayed

###### Expected Result

Just can't perform the recording function.

###### Actual Result

Interface stuck

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

Latest from F-DROID, 2.8.4, EMUI 9.1.1, HUAWEI nova 5 pro

Recorded video see attachment

[anki.zip](https://github.com/ankidroid/Anki-Android/files/3509165/anki.zip)

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description

Editing a note, selecting "Record Audio", with denied & remembered permissions would soft crash the app.

## Fixes
Fixes #5407 

## Approach

Explained in #5407

> Define 3 ***transitions*** (between Multimedia UIs):
>
> * Init - initial load
> * UI - Menu Item is clicked, (changing from "Record Audio" to "Insert Image").
>    * Treat this as cancellable
> * Activity - Pronunciation calls "Record Audio" with a known clip to allow for preview and pronunciation recreation. 
>   * This is invoked by the caller, so there's no way to know whether the previous UI is in a valid state. Treat this is non-cancellable.
>
> ----
>
> * Allow "Record Audio" to fail a transition
>   * UI - Failing will keep the application on the previous multimedia UI.
>     * Requires changes to avoid destroying the previous context until the new context validates.
>   * Init - Cancel the Activity
>   * Activity - Allow access to "Record Audio" without permissions
>* Save the state of a transition to allow the async `onRequestPermissionsResult` to reapply the context.
>* Mark the state as having "permissions requested", so they're not re-requested when calling `recreateEditingUi`
>* Show a toast notification on "Permission Denied"
>* Ensure "Record Audio" can be used without permissions.

## How Has This Been Tested?

* Deny permissions:
* Selecting from the attachment fails and takes you back to the main screen/
* A preview from pronunciation succeeds

Toasts are displayed on permissions issues.

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by david-allison-1** [comment]
I worry this is too complex, I hope splitting this into commits makes it easier to review.

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java [hunk 1]
```diff
@@ -326,4 +374,119 @@ protected void onSaveInstanceState(Bundle outState) {
...
+                    break;
+                case ChangeUIRequest.UI_CHANGE:
+                    break;
+                default:
+                    Timber.e("onControllerCreationFailed: Unhandled state: %s", request.getState());
+                    break;
+            }
+        }
+
+        static void onPostUICreation(ChangeUIRequest request, MultimediaEditFieldActivity activity) {
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java]: Codacy Issue found: [Use explicit scoping instead of the default package private level](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5219270)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 14
           

Complexity increasing per file
==============================
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/utils/Permissions.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5219270&bid=17113029)

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java [hunk 2]
```diff
@@ -326,4 +374,119 @@ protected void onSaveInstanceState(Bundle outState) {
...
+
+        static ChangeUIRequest fieldChange(IField field) {
+            return new ChangeUIRequest(field, EXTERNAL_FIELD_CHANGE);
+        }
+
+        boolean doesRequirePermissionCheck() {
+            return requiresPermissionCheck;
+        }
+
+        void markAsPermissionRequested() {
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java]: Codacy Issue found: [Use explicit scoping instead of the default package private level](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5219270)

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java [hunk 3]
```diff
@@ -326,4 +374,119 @@ protected void onSaveInstanceState(Bundle outState) {
...
+    }
+
+    /**
+     * Class to contain logic relating to decisions made when recreating a UI.
+     * Can later be converted to a non-static class to allow testing of the logic.
+     * */
+    private static final class UIRecreationLogic {
+
+        /** Raised just before the field controller is replaced */
+        static void onPreFieldControllerReplacement(IFieldController previousFieldController) {
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java]: Codacy Issue found: [Use explicit scoping instead of the default package private level](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5219270)

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java [hunk 4]
```diff
@@ -326,4 +374,119 @@ protected void onSaveInstanceState(Bundle outState) {
...
+
+            //Otherwise, clean up the previous screen.
+            previousFieldController.onFocusLost();
+        }
+
+        /**
+         * Raised when we were supplied with a field that could not generate a UI controller
+         * Currently: We used a field for which we didn't know how to generate the UI
+         * */
+        static void onControllerCreationFailed(ChangeUIRequest request, MultimediaEditFieldActivity activity) {
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java]: Codacy Issue found: [Use explicit scoping instead of the default package private level](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5219270)

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java [hunk 5]
```diff
@@ -326,4 +374,119 @@ protected void onSaveInstanceState(Bundle outState) {
...
+
+        boolean doesRequirePermissionCheck() {
+            return requiresPermissionCheck;
+        }
+
+        void markAsPermissionRequested() {
+            requiresPermissionCheck = false;
+        }
+
+        int getState() {
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java]: Codacy Issue found: [Use explicit scoping instead of the default package private level](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5219270)

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java [hunk 6]
```diff
@@ -326,4 +374,119 @@ protected void onSaveInstanceState(Bundle outState) {
...
+
+        static ChangeUIRequest init(IField field) {
+            return new ChangeUIRequest(field, ACTIVITY_LOAD);
+        }
+
+        static ChangeUIRequest uiChange(IField field) {
+            return new ChangeUIRequest(field, UI_CHANGE);
+        }
+
+        static ChangeUIRequest fieldChange(IField field) {
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java]: Codacy Issue found: [Use explicit scoping instead of the default package private level](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5219270)

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java [hunk 7]
```diff
@@ -326,4 +374,119 @@ protected void onSaveInstanceState(Bundle outState) {
...
+            return new ChangeUIRequest(field, EXTERNAL_FIELD_CHANGE);
+        }
+
+        boolean doesRequirePermissionCheck() {
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java]: Codacy Issue found: [Use explicit scoping instead of the default package private level](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5219270)

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java [hunk 8]
```diff
@@ -326,4 +374,119 @@ protected void onSaveInstanceState(Bundle outState) {
...
+
+        public IField getField() {
+            return newField;
+        }
+
+        static ChangeUIRequest init(IField field) {
+            return new ChangeUIRequest(field, ACTIVITY_LOAD);
+        }
+
+        static ChangeUIRequest uiChange(IField field) {
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java]: Codacy Issue found: [Use explicit scoping instead of the default package private level](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5219270)

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java [hunk 9]
```diff
@@ -326,4 +374,119 @@ protected void onSaveInstanceState(Bundle outState) {
...
+                    break;
+                case ChangeUIRequest.ACTIVITY_LOAD:
+                    break;
+                default:
+                    Timber.e("onPostUICreation: Unhandled state: %s", request.getState());
+                    break;
+            }
+        }
+
+        static void onRequiredPermissionDenied(ChangeUIRequest request, MultimediaEditFieldActivity activity) {
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java]: Codacy Issue found: [Use explicit scoping instead of the default package private level](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5219270)

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java [hunk 10]
```diff
@@ -326,4 +374,119 @@ protected void onSaveInstanceState(Bundle outState) {
...
+        private ChangeUIRequest(IField field, int state) {
+            this.newField = field;
+            this.state = state;
+        }
+
+        public IField getField() {
+            return newField;
+        }
+
+        static ChangeUIRequest init(IField field) {
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java]: Codacy Issue found: [Use explicit scoping instead of the default package private level](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5219270)

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java [hunk 11]
```diff
@@ -326,4 +374,119 @@ protected void onSaveInstanceState(Bundle outState) {
...
+        private final IField newField;
+        private final int state;
+        private boolean requiresPermissionCheck = true;
+
+        /** Initial request when activity is created */
+        static final int ACTIVITY_LOAD = 0;
+        /** A change in UI via the menu options. Cancellable */
+        static final int UI_CHANGE = 1;
+        /** A change in UI via access to the activity. Not (yet) cancellable */
+        static final int EXTERNAL_FIELD_CHANGE = 2;
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java]: Codacy Issue found: [Use explicit scoping instead of the default package private level](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5219270)

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java [hunk 12]
```diff
@@ -326,4 +374,119 @@ protected void onSaveInstanceState(Bundle outState) {
...
 
-}
+    /** Intermediate class to hold state for the onRequestPermissionsResult callback */
+    private final static class ChangeUIRequest {
+        private final IField newField;
+        private final int state;
+        private boolean requiresPermissionCheck = true;
+
+        /** Initial request when activity is created */
+        static final int ACTIVITY_LOAD = 0;
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java]: Codacy Issue found: [Use explicit scoping instead of the default package private level](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5219270)

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java [hunk 13]
```diff
@@ -326,4 +374,119 @@ protected void onSaveInstanceState(Bundle outState) {
...
+        int getState() {
+            return state;
+        }
+    }
+
+    /**
+     * Class to contain logic relating to decisions made when recreating a UI.
+     * Can later be converted to a non-static class to allow testing of the logic.
+     * */
+    private static final class UIRecreationLogic {
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java]: Codacy Issue found: [The utility class name 'UIRecreationLogic' doesn't match '[A-Z][a-zA-Z0-9]+(Utils?|Helper)'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5219270)

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java [hunk 14]
```diff
@@ -326,4 +374,119 @@ protected void onSaveInstanceState(Bundle outState) {
...
+    /** Intermediate class to hold state for the onRequestPermissionsResult callback */
+    private final static class ChangeUIRequest {
+        private final IField newField;
+        private final int state;
+        private boolean requiresPermissionCheck = true;
+
+        /** Initial request when activity is created */
+        static final int ACTIVITY_LOAD = 0;
+        /** A change in UI via the menu options. Cancellable */
+        static final int UI_CHANGE = 1;
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java]: Codacy Issue found: [Use explicit scoping instead of the default package private level](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5219270)

**Comment by david-allison-1** [comment]
I'll get on with the auto fixes tomorrow

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/utils/Permissions.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5219270&bid=17113029)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/utils/Permissions.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5219270&bid=17113029)

File: AnkiDroid/src/main/res/values/03-dialogs.xml [hunk 15]
```diff
@@ -139,4 +139,11 @@
     <string name="empty_cards_none">No empty cards</string>
     <string name="empty_cards_count">Cards to delete: %d</string>
     <string name="empty_cards_deleted">Cards deleted: %d</string>
+
```
Comment (mikehardy) [inline AnkiDroid/src/main/res/values/03-dialogs.xml]: There's a conflict here now because #5848 beat it to merge - the perils of moving fast :-)

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java [hunk 16]
```diff
@@ -96,55 +101,80 @@ protected void onCreate(Bundle savedInstanceState) {
...
+        if (field instanceof AudioRecordingField && !Permissions.canRecordAudio(this)) {
+            ActivityCompat.requestPermissions(this, new String[] {Manifest.permission.RECORD_AUDIO},
+                    REQUEST_AUDIO_PERMISSION);
+            return true;
+        }
+
+        // Request permission to use the camera if image field
+        if (field instanceof ImageField && !Permissions.canUseCamera(this)) {
+            ActivityCompat.requestPermissions(this, new String[] {Manifest.permission.CAMERA},
+                    REQUEST_CAMERA_PERMISSION);
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java]: If we're going to have a Permissions object, could we encapsulate the requests in there too?

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java [hunk 17]
```diff
@@ -305,19 +318,21 @@ protected void onActivityResult(int requestCode, int resultCode, Intent data) {
 
 
     public void onRequestPermissionsResult (int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
+        if (mCurrentChangeRequest == null) {
+            throw new IllegalStateException("mCurrentChangeRequest should be set before using cached request");
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java]: This is basically a guaranteed crash right? To be avoided at all costs, it's just making future work. A toast and a fall back to the note editor or anything is better than throwing a RuntimeException if we can avoid it

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java [hunk 18]
```diff
@@ -390,4 +414,29 @@ int getState() {
...
-}
+
+    /**
+     * Class to contain logic relating to decisions made when recreating a UI.
+     * Can later be converted to a non-static class to allow testing of the logic.
+     * */
+    private static final class UIRecreationLogic {
+
+        static void onRequiredPermissionDenied(ChangeUIRequest request, MultimediaEditFieldActivity activity) {
+            switch (request.state)
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java]: I have to admit I'm a fan of Timber.d's for things like this, dumping all pertinent internal state to the logs if it's possible

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java [hunk 19]
```diff
@@ -410,6 +414,14 @@ static ChangeUIRequest fieldChange(IField field) {
             return new ChangeUIRequest(field, EXTERNAL_FIELD_CHANGE);
         }
 
+        boolean doesRequirePermissionCheck() {
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java]: The property accessors are non-standard, can we just do get/set?

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java [hunk 20]
```diff
@@ -433,6 +427,50 @@ int getState() {
      * */
     private static final class UIRecreationLogic {
 
+        /** Raised just before the field controller is replaced */
+        static void onPreFieldControllerReplacement(IFieldController previousFieldController) {
+            //on init, we don't need to do anything
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java]: similarly Timber.d's here and in the other onXXXFailed methods would be nice

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java (hunk 16 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java]: I thought about it, but each screen has an associated tag with permission, and it felt like we shouldn't mix local and global data, and it makes it much harder if for instance we want to request microphone and audio at once later on for a more advanced editor

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/utils/Permissions.java [hunk 21]
```diff
@@ -0,0 +1,24 @@
...
+    private Permissions() { }
+
+    public static boolean canUseCamera(@NonNull Context context) {
+        return hasPermission(context, Manifest.permission.CAMERA);
+    }
+
+    public static boolean canRecordAudio(@NonNull Context context) {
+        return hasPermission(context, Manifest.permission.RECORD_AUDIO);
+    }
+
```
[the remark this answers is not in the document]
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/utils/Permissions.java]: Can do, but will also want to move to a more general package rather than one under the multimedia editor.

I've been burned before by tacking mostly unrelated refactorings into a change as they get much less (if any) testing effort. Breaking storage permissioning would be fatal.

Will get this one done though. Extract method barely breaks.

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java (hunk 16 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java]: that one in particular is the first that will show up with `./gradlew clean uninstallDebug installDebug` and a test click-around, which is the first thing I do for stable releases, so no worries

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java (hunk 19 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java]: I'm not familiar with Java naming conventions. Is it "always use get", or are "is/has/does" ever acceptable for booleans?

Will fix

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java (hunk 16 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java]: I assume the above was desired for the above comment. I'll do that, but will leave this unresolved, will get it done if you still feel it's an issue on review 2

**Comment by david-allison-1** [comment]
Review fixes done.

File: AnkiDroid/src/main/java/com/ichi2/utils/Permissions.java [hunk 22]
```diff
@@ -0,0 +1,39 @@
+package com.ichi2.utils;
+
+import android.Manifest;
+import android.content.Context;
+import android.content.pm.PackageManager;
+
+import androidx.annotation.NonNull;
+import androidx.core.content.ContextCompat;
+
+public class Permissions {
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/utils/Permissions.java]: Codacy Issue found: [The utility class name 'Permissions' doesn't match '[A-Z][a-zA-Z0-9]+(Utils?|Helper)'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5219270)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- AnkiDroid/src/main/java/com/ichi2/utils/Permissions.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5219270&bid=17113029)

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java (hunk 19 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java]: get/set is the gold standard, for booleans you *may* alter to isXXX but get/set is easiest. Lots of Java things use inspection and the JavaBeans spec specified this so that you easily take an unknown object and inspect it and (likely) know how to operate it

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java (hunk 16 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java]: > I assume the above was desired for the [above comment](https://github.com/ankidroid/Anki-Android/pull/5841#discussion_r396043341). I'll do that, but will leave this unresolved, will get it done if you still feel it's an issue on review 2

Yes that was intended for the storage permission refactor - not sure how github flubbed the comment attribution but you got it

**Comment by mikehardy** [comment]
Same as the other - this one looks great just waiting on CI to go through owing to macOS intermittency 💪

**Comment by mikehardy** [comment]
2.10alpha54 released just now has this whenever google delivers it to you

**Comment by mikehardy** [comment]
released in 2.9.6beta4
