### PR TITLE
Manual-Download-link

### LINKED ISSUE #17178: Improve "download failed" message for Shared Decks
From user report: https://www.reddit.com/r/Anki/comments/1fu0cdi/ankidroid_download_failure/

----

If a download fails, we should provide a link to open the deck on the [AnkiWeb site](https://ankiweb.net/shared/decks), so a user may download the file manually

Relevant file:

https://github.com/ankidroid/Anki-Android/blob/main/AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt

### PR DESCRIPTION
**Pull request by disconnect821**
## Purpose / Description
The user can download the deck manually if  download fails.

## Fixes
* Fixes #17178 

## Approach
This change allows users to manually download decks from AnkiWeb through an external browser if the download fails in the in-app WebView. By using an Intent, we redirect users to their preferred browser.

Once the download is initiated, the app pops the fragment stack.

Screen_Recording_20241105_184749_AnkiDroid

## Steps to reproduce the download failed error.

1 : Comment out the downloadFile() function call in the onViewCreated method.
2 : Instead, call checkDownloadStatusAndUnregisterReceiver(false, false).

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner]
(https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by disconnect821** [comment]
#### Task Remaining 

- [ ] Translation of newly added string to every other language.
- [ ] UI changes (The format of the clickable text "Download from AnkiWeb")
- [ ] Other suggested changes.

**Comment by disconnect821** [comment]
Hi @david-allison !  I've opened a draft PR for the issue #17178. Could you review it to see if it meets the desired result, and let me know if there are any changes needed?

File: AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt [hunk 1]
```diff
@@ -474,6 +492,8 @@ class SharedDecksDownloadFragment : Fragment(R.layout.fragment_shared_decks_down
                 context?.let { showThemedToast(it, R.string.something_wrong, false) }
                 // Update UI if download could not be successful
                 tryAgainButton.visibility = View.VISIBLE
+                // Making downloadFromAnkiWeb button visible
+                downloadFromAnkiWeb.visibility = View.VISIBLE
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt:496]: Ensure that the button is not visible if "try again" is pressed

File: AnkiDroid/src/main/res/layout/fragment_shared_decks_download.xml [hunk 2]
```diff
@@ -76,6 +76,22 @@
...
+        android:gravity="center"
+        android:paddingEnd="16dp"
+        android:paddingStart="16dp"
+        android:text="@string/download_deck_from_AnkiWeb"
+        android:textSize="15sp"
+        app:layout_constraintBottom_toTopOf="@id/try_again_deck_download"
+        app:layout_constraintEnd_toEndOf="parent"
+        app:layout_constraintStart_toStartOf="parent"
+        app:layout_constraintTop_toBottomOf="@+id/download_progress"
+        app:layout_constraintVertical_bias="0.958" />
```
Comment (david-allison) [inline AnkiDroid/src/main/res/layout/fragment_shared_decks_download.xml:93]: Probably not what you want. Can you represent this another way?

File: AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt [hunk 3]
```diff
@@ -128,6 +132,20 @@ class SharedDecksDownloadFragment : Fragment(R.layout.fragment_shared_decks_down
             openDownloadedDeck(context)
         }
 
+        // Added the click listener for downloadfromAnkiWeb button
+        downloadFromAnkiWeb.setOnClickListener {
+            Timber.i("Download from AnkiWeb clicked which would lead to AnkiWeb site to download deck manually")
+            downloadManager.remove(downloadId)
+            val browserIntent = Intent(Intent.ACTION_VIEW, Uri.parse(fileToBeDownloaded.url))
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt:139]: You want to open up the deck page, not the direct download URL

The direct download URL may have problems with expired tokens, the deck page should permanently be available

File: AnkiDroid/src/main/res/layout/fragment_shared_decks_download.xml (hunk 2 above)
Comment (disconnect821) [reply AnkiDroid/src/main/res/layout/fragment_shared_decks_download.xml]: Replaced `TextView`  with `Button` and updated constraints accordingly.

Screenshot_20241105_181729_AnkiDroid

File: AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt (hunk 3 above)
Comment (disconnect821) [reply AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt]: Screen_Recording_20241105_184749_AnkiDroid

Created a `getDeckPageUri` function to generate the deck page URI, ensuring proper linking to the deck page as suggested.

File: AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt [hunk 4]
```diff
@@ -128,12 +130,33 @@ class SharedDecksDownloadFragment : Fragment(R.layout.fragment_shared_decks_down
...
             downloadManager.remove(downloadId)
             downloadFile(fileToBeDownloaded)
             cancelButton.visibility = View.VISIBLE
             tryAgainButton.visibility = View.GONE
+            downloadFromAnkiWeb.visibility = View.GONE
+        }
+    }
+
+    private fun getDeckPageUri(orgUrl: String): Uri {
+        val deckIdRegex = "download-deck/(\\d+)".toRegex()
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt:151]: nit: move this outside the function so it's executed once

File: AnkiDroid/src/main/res/layout/fragment_shared_decks_download.xml [hunk 5]
```diff
@@ -76,6 +76,23 @@
...
+        android:background="@color/material_blue_500"
+        android:textColor="@color/white"
+        android:padding="8dp"
+        android:layout_marginBottom="24dp"
+        android:layout_marginStart="24dp"
+        android:layout_marginEnd="24dp"
+        app:layout_constraintStart_toStartOf="parent"
+        app:layout_constraintEnd_toEndOf="parent"
+        app:layout_constraintBottom_toTopOf="@id/try_again_deck_download"
+        android:visibility="gone"
```
Comment (david-allison) [inline AnkiDroid/src/main/res/layout/fragment_shared_decks_download.xml:93]: I couldn't see on the gif, but I'd expect this to either be a material 'text button', or be underline so a user knows it's a link

**Review by david-allison — CHANGES_REQUESTED** [review]
Looks great! Sorry for the slow response, been really busy

File: AnkiDroid/src/main/res/layout/fragment_shared_decks_download.xml (hunk 5 above)
Comment (disconnect821) [reply AnkiDroid/src/main/res/layout/fragment_shared_decks_download.xml]: Screenshot_20241111_171505_AnkiDroid

Updated the button to use the Material text button.

**Review by david-allison — APPROVED** [review]
Looks great, cheers!

**Review by criticalAY — COMMENTED** [review]
Looks good but just one question why not m3 button?

File: AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt [hunk 6]
```diff
@@ -112,12 +116,12 @@ class SharedDecksDownloadFragment : Fragment(R.layout.fragment_shared_decks_down
         importDeckButton = view.findViewById(R.id.import_shared_deck_button)
         tryAgainButton = view.findViewById(R.id.try_again_deck_download)
         checkNetworkInfoText = view.findViewById(R.id.check_network_info_text)
+        downloadFromAnkiWeb = view.findViewById(R.id.download_from_ankiWeb)
 
         val fileToBeDownloaded = arguments?.getSerializableCompat<DownloadFile>(DOWNLOAD_FILE)!!
         downloadManager = (activity as SharedDecksActivity).downloadManager
 
         downloadFile(fileToBeDownloaded)
-
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt:120]: Why do you remove this line? That's not wrong, but I admit I'd have not expected to see changes in part of the code you didn't touch.

File: AnkiDroid/src/main/res/values/02-strings.xml [hunk 7]
```diff
@@ -268,6 +268,7 @@
     <string name="percentage">%s%%</string>
     
     <string name="download_deck">Download deck</string>
+    <string name="download_deck_from_AnkiWeb">Download deck from AnkiWeb</string>
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/main/res/values/02-strings.xml:271]: Not fan of this phrasing to be honest. I can't imagine that the average user would know what ankiweb is. And even if they knew, how does it differ from what they did? After all, we were already on ankiweb website

**Review by Arthur-Milchior — COMMENTED** [review]
Hi,

First, nice to meet you. Thanks for working on this!

First feedback on your PR, if it's not too hard, when you change the behaviour, I'd love that you update the gif in the first message, so that I know what I expect to see.

You implemented what David requested, and I should have commented on the bug report sooner. I admit I'm not entirely convinced this is the best feature we may have for this problem.

I'd expect that, in case of download issue, we'd want to directly send the intent without requesting a user to tap on the button. And have a message stating that the user should must navigate to their download folders. Or otherwise that they can download it manually from this link, and have a button allowing the user to copy the link in the clipboard.
First, because I don't really know a case where the user would not want to go through the browser. And if they always want to go through the browser, let's do it for them. (Admittedly, if they don't yet have any preferred browser, that may be a not optimal experience. I don't know how many people will have opened ankidroid but not a browser. That must exists sometime. I'd expect this is mostly an issue when you are a developer testing on simulator)
More importantly, if it's relatively easy to solve the error through an alternate route, then we can just be silent about the error. I'd expect most users not to care that there was supposed to be a more efficient route that failed. And even if it usually work on their device and that's the first time it failed, it's still no big deal that the route is different for this time.

In the case when we keep with your current implementation, and requiring the user to do the click, I still believe that the button message should be changed

**Comment by disconnect821** [comment]
Sorry for the late response. Thank you for the feedback and suggestions!

1- I understand your suggestion to directly send the intent on download failure and provide a message guiding users to their download folder. However, if we send the intent every time a download fails, wouldn’t that make the 'Try Again' button redundant? The button currently allows users to retry manually, which could still be helpful. Should we consider removing or repurposing it?

2- Adding a button to copy the link to the clipboard feels similar to the `manual download` button, except it adds an extra step for users to paste the link themselves.

Could you please confirm if I’ve understood your approach correctly?

And since we’re redirecting to AnkiWeb in the browser, I agree that the button label should be updated. Instead of `Download From AnkiWeb`,  how about using something like `Open in Browser`  to make it clearer that the user will be redirected outside the WebView? Alternatively, we could use `Download from Browser`, but I think it might cause confusion, as the button is redirecting users to the browser rather than starting a download directly. Please let me know if that works for you.

File: AnkiDroid/src/main/res/layout/fragment_shared_decks_download.xml [hunk 8]
```diff
@@ -105,7 +122,8 @@
         app:layout_constraintBottom_toBottomOf="parent"
         app:layout_constraintStart_toStartOf="parent"
         app:layout_constraintEnd_toEndOf="parent"
-        android:visibility="gone" />
+        android:visibility="gone"
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/main/res/layout/fragment_shared_decks_download.xml:125]: why this change?

**Comment by david-allison** [comment]
This should also handle the case where the import fails due to something like:

* https://github.com/ankidroid/Anki-Android/pull/17574

**Comment by disconnect821** [comment]
The error seems related to server failures.
The "Open in Browser" button addresses this and avoids issues with expiring download tokens and the "Try Again" button is retained to give users the option to retry the download in case of such failures manually.

I’ve also reverted unnecessary changes, such as extra spaces in untouched code, to keep the diff clean and focused on the relevant updates.

**Comment by disconnect821** [comment]
Hey @Arthur-Milchior , @david-allison 
I'd like to know if there are any other failure scenarios we should consider besides the server failures. If not, can we proceed with the current implementation?

File: AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt [hunk 9]
```diff
@@ -128,12 +133,30 @@ class SharedDecksDownloadFragment : Fragment(R.layout.fragment_shared_decks_down
...
             tryAgainButton.visibility = View.GONE
+            openInBrowserButton.visibility = View.GONE
+        }
+    }
+
+    private fun getDeckPageUri(orgUrl: String): Uri {
+        val matchResult = deckIdRegex.find(orgUrl)
+        val deckId = matchResult?.groups?.get(1)?.value
+        return if (deckId != null) {
+            Uri.parse(resources.getString(R.string.shared_deck_info) + deckId)
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt]: I think we could return a String. That would make testing easier, and use a single Uri.parse at call site

**Review by Arthur-Milchior — COMMENTED** [review]
I force pushed as I did only add comment and split a method in two. And put all commits in a single commit

**Review by Arthur-Milchior — APPROVED** [review]
I'd appreciate if you could add some unit test. It's been open long enough, it's a nice feature that seems to work, I'm not blocking.

**Comment by disconnect821** [comment]
@david-allison 
I’ve written tests for `getDeckIdFromDownloadURL` and `getDeckPageUri` in `SharedDecksDownloadFragment`. Out of 5 tests, 3 are passing, but 2 are failing with a `Fragment not attached` error. I’ve already tried using Mockito and ActivityScenario, but the issue persists.

File: AnkiDroid/src/test/java/com/ichi2/anki/SharedDecksDownloadFragmentTest.kt [hunk 10]
```diff
@@ -0,0 +1,45 @@
...
+        assertEquals("1104981491", deckId)
+    }
+
+    @Test
+    fun `test getDeckIdFromDownloadURL with invalid URL`() {
+        val url = "https://ankiweb.net/svc/shared/download-deck/"
+        val deckId = SharedDecksDownloadFragment.getDeckIdFromDownloadURL(url)
+        assertNull(deckId)
+    }
+
```
Comment (disconnect821) [inline AnkiDroid/src/test/java/com/ichi2/anki/SharedDecksDownloadFragmentTest.kt:31]: These 2 test are failing with `fragment is  not attached to a context`

File: AnkiDroid/src/test/java/com/ichi2/anki/SharedDecksDownloadFragmentTest.kt [hunk 11]
```diff
@@ -0,0 +1,45 @@
...
+        assertEquals("https://ankiweb.net/shared/info/1104981491", fragment.getDeckPageUri(url))
+    }
+
+    @Test
+    fun `test getDeckPageUri with invalid deck URL`() {
+        val fragment = SharedDecksDownloadFragment()
+        val url = "https://ankiweb.net/svc/shared/download-deck/"
+        assertEquals("https://ankiweb.net/shared/decks/", fragment.getDeckPageUri(url))
+    }
+}
```
Comment (disconnect821) [inline AnkiDroid/src/test/java/com/ichi2/anki/SharedDecksDownloadFragmentTest.kt:45]: These 2 tests are failing with `fragment is not attached to a context`

Comment (david-allison) [reply AnkiDroid/src/test/java/com/ichi2/anki/SharedDecksDownloadFragmentTest.kt:45]: You'll want to attach it to a context. I believe I introduced AnkiFragmentScenario for this purpose.

If you can't find it within 5 minutes, ping me on Discord. I'm on my phone and don't recall the exact name

**Comment by disconnect821** [comment]
@Arthur-Milchior 
written tests for two functions:

1 -  `getDeckIdFromDownloadURL` – Tests are included and running successfully.
2 - `getDeckPageUri `– Tests are written and marked with `@Ignore` because `AnkiActivityScenario` is not fully implemented to support launching an arbitrary AnkiActivity as of now. This results in an error when attempting to initialize the fragment within the test.

**Comment by Arthur-Milchior** [comment]
I'd still would love if instead of adding more commit you could edit the previous commit, so that we don't have extra work to do when we merge the PR

File: AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt [hunk 12]
```diff
@@ -136,14 +155,37 @@ class SharedDecksDownloadFragment : Fragment(R.layout.fragment_shared_decks_down
...
+        }
+    }
+
+    /**
+     * Given the URI of a deck's download URL such as
+     * https://ankiweb.net/svc/shared/download-deck/1104981491?t=eyJvcCI6InNkZCIsImlhdCI6MTc0MTUyNjQ0OSwianYiOjF9.hr4a_G-LAqMVBAp5_95l60_2lEtYxodGl4DrJ6dT2WI
+     * returns the deck's page URL such as https://ankiweb.net/shared/info/1104981491
+     * If the deck id can't be found, returns the ankiweb's shared deck's main page.
+     */
+    @VisibleForTesting(otherwise = VisibleForTesting.PRIVATE)
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt:181]: Private is the default value, I don't think it's worth adding it. Even if I see we have many of this already

**Review by Arthur-Milchior — COMMENTED** [review]
Nice tests.

I don't know test for activity very well. But I think you are doing too complex tests there.

```patch
Subject: [PATCH] aa
---
Index: AnkiDroid/src/test/java/com/ichi2/anki/SharedDecksDownloadFragmentTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/test/java/com/ichi2/anki/SharedDecksDownloadFragmentTest.kt b/AnkiDroid/src/test/java/com/ichi2/anki/SharedDecksDownloadFragmentTest.kt
--- a/AnkiDroid/src/test/java/com/ichi2/anki/SharedDecksDownloadFragmentTest.kt	(revision f2187165edb56395ea3e354cc59cc9c49683e5b5)
+++ b/AnkiDroid/src/test/java/com/ichi2/anki/SharedDecksDownloadFragmentTest.kt	(date 1742095852167)
@@ -5,6 +5,7 @@
 import androidx.core.os.bundleOf
 import androidx.test.ext.junit.runners.AndroidJUnit4
 import com.ichi2.anki.SharedDecksActivity.Companion.DOWNLOAD_FILE
+import com.ichi2.anki.SharedDecksDownloadFragment.Companion.getDeckPageUri
 import com.ichi2.compat.CompatHelper.Companion.getSerializableCompat
 import com.ichi2.testutils.AnkiFragmentScenario
 import org.junit.Assert.assertEquals
@@ -14,7 +15,7 @@
 import kotlin.test.assertNull
 
 @RunWith(AndroidJUnit4::class)
-class SharedDecksDownloadFragmentTest {
+class SharedDecksDownloadFragmentTest: RobolectricTest() {
     @Test
     fun `test getDeckIdFromDownloadURL with valid URL`() {
         val url = "https://ankiweb.net/svc/shared/download-deck/1104981491?t=some-token"
@@ -38,66 +39,9 @@
         assertNull(deckId, "Expected deckId to be null")
     }
 
-    @Ignore("AnkiActivityScenario is not fully implemented to handle arbitrary AnkiActivity instances")
     @Test
     fun `test getDeckPageUri with valid deck URL`() {
-        val downloadFile =
-            DownloadFile(
-                url = "https://ankiweb.net/svc/shared/download-deck/1104981491?t=some-token",
-                userAgent = "userAgent",
-                contentDisposition = "attachment; filename=test.apkg",
-                mimeType = "application/apkg",
-            )
-
-        // Setting up arguments before launching the fragment
-        val args =
-            bundleOf(
-                DOWNLOAD_FILE to downloadFile,
-            )
-
-        // Launch the fragment with arguments
-        val scenario =
-            AnkiFragmentScenario.launchInContainer(
-                SharedDecksDownloadFragment::class.java,
-                fragmentArgs = args,
-            )
-
-        scenario.onFragment { fragment ->
-            val fileToBeDownloaded = args.getSerializableCompat<DownloadFile>(DOWNLOAD_FILE)!!
-            val url = fileToBeDownloaded.url
-
-            assertEquals("https://ankiweb.net/shared/info/1104981491", fragment.getDeckPageUri(url))
-        }
-    }
-
-    @Ignore("AnkiActivityScenario is not fully implemented to handle arbitrary AnkiActivity instances")
-    @Test
-    fun `test getDeckPageUri with invalid deck URL`() {
-        val downloadFile =
-            DownloadFile(
-                url = "https://ankiweb.net/svc/shared/download-deck/",
-                userAgent = "userAgent",
-                contentDisposition = "attachment; name=test.apkg",
-                mimeType = "application/apkg",
-            )
-
-        // Setting up arguments before launching the fragment
-        val args =
-            bundleOf(
-                DOWNLOAD_FILE to downloadFile,
-            )
-        // Launch the fragment with arguments
-        val scenario =
-            AnkiFragmentScenario.launchInContainer(
-                SharedDecksDownloadFragment::class.java,
-                fragmentArgs = args,
-            )
-
-        scenario.onFragment { fragment ->
-            val fileToBeDownloaded = args.getSerializableCompat<DownloadFile>(DOWNLOAD_FILE)!!
-            val url = fileToBeDownloaded.url
-
-            assertEquals("https://ankiweb.net/shared/decks/", fragment.getDeckPageUri(url))
-        }
+        val url = "https://ankiweb.net/svc/shared/download-deck/1104981491?t=some-token"
+        assertEquals("https://ankiweb.net/shared/info/1104981491", targetContext.getDeckPageUri(url))
     }
 }
Index: AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt b/AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt	(revision f2187165edb56395ea3e354cc59cc9c49683e5b5)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt	(date 1742095575755)
@@ -124,6 +124,24 @@
                 ?.groups
                 ?.get(1)
                 ?.value
+
+
+
+        /**
+         * Given the URI of a deck's download URL such as
+         * https://ankiweb.net/svc/shared/download-deck/1104981491?t=eyJvcCI6InNkZCIsImlhdCI6MTc0MTUyNjQ0OSwianYiOjF9.hr4a_G-LAqMVBAp5_95l60_2lEtYxodGl4DrJ6dT2WI
+         * returns the deck's page URL such as https://ankiweb.net/shared/info/1104981491
+         * If the deck id can't be found, returns the ankiweb's shared deck's main page.
+         */
+        @VisibleForTesting(otherwise = VisibleForTesting.PRIVATE)
+        fun Context.getDeckPageUri(deckDownloadURL: String): String {
+            val deckId = getDeckIdFromDownloadURL(deckDownloadURL)
+            return if (deckId != null) {
+                getString(R.string.shared_deck_info) + deckId
+            } else {
+                getString(R.string.shared_decks_url)
+            }
+        }
     }
 
     override fun onViewCreated(
@@ -158,7 +176,7 @@
         openInBrowserButton.setOnClickListener {
             Timber.i("'Open in Browser' clicked")
             downloadManager.remove(downloadId)
-            openUrl(Uri.parse(getDeckPageUri(fileToBeDownloaded.url)))
+            openUrl(Uri.parse(requireContext().getDeckPageUri(fileToBeDownloaded.url)))
             parentFragmentManager.popBackStack()
         }
 
@@ -172,22 +190,6 @@
         }
     }
 
-    /**
-     * Given the URI of a deck's download URL such as
-     * https://ankiweb.net/svc/shared/download-deck/1104981491?t=eyJvcCI6InNkZCIsImlhdCI6MTc0MTUyNjQ0OSwianYiOjF9.hr4a_G-LAqMVBAp5_95l60_2lEtYxodGl4DrJ6dT2WI
-     * returns the deck's page URL such as https://ankiweb.net/shared/info/1104981491
-     * If the deck id can't be found, returns the ankiweb's shared deck's main page.
-     */
-    @VisibleForTesting(otherwise = VisibleForTesting.PRIVATE)
-    fun getDeckPageUri(deckDownloadURL: String): String {
-        val deckId = getDeckIdFromDownloadURL(deckDownloadURL)
-        return if (deckId != null) {
-            resources.getString(R.string.shared_deck_info) + deckId
-        } else {
-            resources.getString(R.string.shared_decks_url)
-        }
-    }
-
     /**
      * Register broadcast receiver for listening to download completion.
      * Set the request for downloading a deck, enqueue it in DownloadManager, store download ID and
```

seems fine.

The second function you test only need to have a context, not the whole Fragment. And by ensuring the Test class inherits RobolectricTest you can access a context

**Comment by Arthur-Milchior** [comment]
Please add back the tests I deleted but simply testing the little method that returns the URl, that's sufficient.

**Comment by disconnect821** [comment]
@Arthur-Milchior 
I modified the tests and made the necessary changes.
Initially, I was focused on testing without making any changes to `getDeckPageUri`  method which led to a more complex approach. 
I didn’t want to modify the methods being tested, kept trying different ways to make it work, that’s what made the tests more complex than necessary.

One of the issues I was running into was that the ` fragment’s context wasn’t attached properly`.  which caused errors. That added to the complexity, as I kept debugging different ways to handle it

Now it is simplified and working fine.

File: AnkiDroid/src/main/res/values/02-strings.xml [hunk 13]
```diff
@@ -261,6 +261,7 @@
     <string name="percentage">%s%%</string>
     
     <string name="download_deck">Download deck</string>
+    <string name="open_in_browser">Open in Browser</string>
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/main/res/values/02-strings.xml:264]: I'm sorry, I should have seen it sooner.  I'd love if you could add `comment="Label of a button inviting to open ankiweb's shared deck page if automated download failed"`

Indicating it's a button would let the translator know the text should be relatively small. And more importantly, it indicates that it's an action the user can do. Indeed, "Open in browser" could also be a toolbark content stating that something was opened in the browser. And in French, for example, the call to action and the information verbs would not be written in the same way

**Review by Arthur-Milchior — COMMENTED** [review]
Sorry, I missed one change. Once it's done, I'm fine with accepting it

**Comment by disconnect821** [comment]
Rebased all commits into one. 

Thanks for your guidance!

File: AnkiDroid/src/main/res/values/02-strings.xml (hunk 13 above)
Comment (Arthur-Milchior) [reply AnkiDroid/src/main/res/values/02-strings.xml:266]: Please use the `comment` XML tag.

**Review by Arthur-Milchior — APPROVED** [review]
