### PR TITLE
Reimplement CardTemplateEditor with in-memory edits

### LINKED ISSUE #5011: State handling crash between card browser / note editor / template editor
I've seen this show up via ACRA, and the google play console release robot army caught it with video this time so I could figure it out.

###### Reproduction Steps

1. Open the card browser (it's empty in their tests, and they play with searches sometimes but the search was cleared)
2. Click + to add a card, enter text in front and back, template should be Basic
3. click the button bar that says "Card 1" to open the template editor
4. Click the options menu and select add to add a Card to the template, and you can mess with the template or not, but don't save - preview or not but don't save - then click the back button and agree it's okay to lose your progress
5. The Card button bar should say "Cards: Card 1 Card 2" now, but you never saved the second template
6. Click save to add the card, then click back to go back to the browser and it should crash with a JSONException string out of bounds

###### Expected Result

If you don't save the template the unsaved work should go away, you should have only Card 1 and the browser should work fine

###### Actual Result

Crash. I can reproduce this locally.

https://play.google.com/apps/publish/?account=5338425030304417978#PreLaunchReportPlace:p=com.ichi2.anki&appid=4973711737547064258&plrtab=CRASH&plrvc=20900140

FATAL EXCEPTION: AsyncTask #4
Process: com.ichi2.anki, PID: 12740
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:353)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.RuntimeException: org.json.JSONException: Index 1 out of range [0..1)
	at com.ichi2.libanki.Card.template(Card.java:342)
	at com.ichi2.libanki.Card._getQA(Card.java:290)
	at com.ichi2.anki.CardBrowser.updateSearchItemQA(CardBrowser.java:1164)
	at com.ichi2.async.DeckTask.doInBackgroundSearchCards(DeckTask.java:818)
	at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:262)
	at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:69)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more
Caused by: org.json.JSONException: Index 1 out of range [0..1)
	at org.json.JSONArray.get(JSONArray.java:293)
	at org.json.JSONArray.getJSONObject(JSONArray.java:521)
	at com.ichi2.libanki.Card.template(Card.java:337)
	... 11 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.get(ArrayList.java:437)
	at org.json.JSONArray.get(JSONArray.java:287)
	... 13 more

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

### PR DESCRIPTION
**Pull request by mikehardy**
## Purpose / Description
Issue #5011 was especially thorny because to solve it properly meant to alter the way it handled storage by changing it from speculative persistence of edits to persistence of edits only when the user confirmed it.

Previous work altered related code (Previewer, some libanki APIs) to handle working with unsaved data, as well as tracking changes to it, and now it all comes together in this PR

As mentioned in the commit, it does not implement undo. I've done undo in #5113 so I know how, but this PR is already huge, and I believe this PR is still 100% of the feature profile of the previous code so it's not a regression.

This is based on #5150 (which itself chained to #5149 and #5148) so the commit list will whittle down as those are reviewed and merged, or this can go at once.

## Fixes
Fixes #5011, #5600 

## How Has This Been Tested?

The automated testing is extremely thorough - 90% or higher for the new code - because this is a complicated Activity, and very important. I've also clicked around a bunch in an API28 emulator

Further work should include undo, maybe making the "don't orphan notes on template remove" check async, and investigating whether the pager fragment invalidation workaround is still necessary.

### CODE REVIEW

**Comment by mikehardy** [comment]
I'm not aware of a convenient way to view coverage until code is merged but I worked hard on the testing for this one in an attempt to avoid bugs and I felt like it was worth demonstrating. The majority of the missed coverage is JSONException catches.

decktasksavemodelcoverage
previewercoverage
cardtemplatefragmentcoverage
cardtemplateeditorcoverage

**Comment by mikehardy** [comment]
@timrae - just a quick check-in on this one to prioritize work. I stopped before I implemented undo, reasoning that this was not a regression (as "undo" before was really just "discard changes" and with this PR we do that quite well). I'm trying to keep things that block 2.9 to a minimum so I am hoping that not having undo here won't block a 2.9 release, and it can be implemented some other time as long as this correctly fixes the CardTemplateEditor crash / corruption

**Comment by timrae** [comment]
I guess it's ok to not have undo, but you should think about how introducing undo would alter the UX. Dramatically changing the UX on two consecutive versions is not ideal. I haven't really looked at the code yet so I'm not sure how closely it matches with what we previously discussed, but that was something I was considering in that discussion. I'll try to get through this PR by the end of the month, I know it must be frustrating sorry, but life is happening.

**Comment by mikehardy** [comment]
Quite alright I know your life is nuts now. This PR was like having a baby anyway, so leaving it sit for a bit is actually okay 😁. As for undo it would just show up in the options menu like I did with all the reschedule stuff to learn the undo. Nothing else should change. I should probably add a commit before 2.9 for the string so it's in the translation push at least. I will get to undo I just don't want to block a release

**Comment by mikehardy** [comment]
Oh - and should mention that my full goal was to not change the UX much at all - it all appears exactly the same actually. Literally the only difference after my PRs is that when it says "Discard changes?" and you say yes after adding a template or deleting a template, it *actually* discards your changes (since they never went in the DB).

**Comment by mikehardy** [comment]
I just added the undo string so it will be available for 2.9 translators (I'm imagining we'll want to freeze source strings for translations for the release as well, and this one is obvious, so...)

Rebased in the process, it continues to check out in my automated testing

**Comment by timrae** [comment]
I don't think there's any point in adding an undo string without undo
functionality. There's no rule about freezing translations. The rule is
just bug fixes and minor changes only during beta phase.

**Comment by mikehardy** [comment]
> Why exactly are you saving to files? It looks like premature optimisation to me. Can you do it the "normal way" first and then test if works with a very large template?

I documented the research here - https://github.com/ankidroid/Anki-Android/pull/5053#issuecomment-441345060 - the results I found seemed credible and thorough so I did not personally reproduce, though I could attempt to reproduce them if you want? 

My take on it is that I don't personally care but it seemed that for unbounded data there was only one safe choice so I took it. I think the other options will work for most cases but have documented weaknesses on the corners and file storage was the one that seemed like it wouldn't ever crash until java String limits (or device OOM) which would be bigger than any JS bundle I've heard of, so I went to that point, but stopped there.

It's harder than just stuffing it in the Intent but not conceptually challenging, so I felt it wasn't too nasty.

Anyway, that's the thought process. If my analyses was wrong, or if just using one of the other easier approaches is acceptable, easy to replace. Pick one and I'll abide


> I don't think there's any point in adding an undo string without undo functionality. There's no rule about freezing translations

Ah okay - easy to purge that commit obviously. This is an obvious case of premature optimization if there's no i18n freeze :-)

File: AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java [hunk 1]
```diff
@@ -34,16 +44,39 @@
...
+        mIndex = parameters.getInt("index");
+
+        if (mEditedModelFileName != null) {
+            Timber.d("onCreate() loading edited model from %s", mEditedModelFileName);
+            mEditedModel = CardTemplateEditor.getTempModel(mEditedModelFileName);
+        }
+
+        if (mEditedModel != null && mIndex != -1) {
+            Timber.d("onCreate() Previewer started with edited model and template index, displaying blank to preview formatting");
+            mCurrentCard = getDummyCard(mEditedModel, mIndex);
```
[the remark this answers is not in the document]
Comment (timrae) [reply AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java]: Actually, looking at this code I'm starting to feel that we should make a new class for the template previewer to specially handle loading a temporary model. Also I have a long term vision to implement this preview functionality as a fragment inside the same activity as the template editor on large form factor devices (tablets) so this would work towards that long-term vision in addition to making the code cleaner and safer.

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java [hunk 2]
```diff
@@ -353,52 +339,49 @@ public CharSequence getPageTitle(int position) {
...
-            args.putLong("modelId",modelId);
             args.putLong("noteId",noteId);
             f.setArguments(args);
             return f;
         }
 
         @Override
         public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
+            // Storing a reference to the templateEditor allows us to use member variables
+            templateEditor = (CardTemplateEditor)getActivity();
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java]: Maybe just make a convenience function `getModel()` instead of storing this as a member variable. It's much cleaner than handling the lifetime issues. Also, please don't forget the `mVariableName` naming convention for member variables.

**Comment by mikehardy** [comment]
@timrae thanks for the first look - encouraging (related to the size of the change) and I'll assume since you didn't re-comment on storing the temporary data in a file that the chosen data passing style there is okay as a start? Before I address these, just as a question for work style would you like me to just collapse the chunked work (3 PRs) into just this one, or do you want to keep them separate? In hindsight one PR might be best but the attempt was for your review comfort so I'll leave that with you still

**Comment by timrae** [comment]
I don't think there are specific commits that I want to merge separately from the group, so splitting it up is more of a nuisance than a help as it makes it harder to review and keep track of the discussion.

**Comment by mikehardy** [comment]
> splitting it up is more of a nuisance than a help as it makes it harder to review and keep track of the discussion.

agreed now that I see how it looks in practice vs theory. This one is cumulative in git, so trivial to collapse. I'll mop that up as I address (via proposed or actual changes) your comments.

Thanks!

**Comment by timrae** [comment]
> I'll assume since you didn't re-comment on storing the temporary data in a file that the chosen data passing style there is okay as a start?

Let's just say for now I haven't thought of a better way to do it ;)

**Comment by timrae** [comment]
(most likely there isn't one, so feel free to proceed)

**Comment by timrae** [comment]
> I'll mop that up 

By that you mean close the other PRs right?

**Comment by mikehardy** [comment]
> > I'll mop that up
> 
> By that you mean close the other PRs right?

exactly that yes - I don't think any commits need changing per-se, except as needed to address review. In my personal branch history there'll be branch deletes etc but no one needs to care about that

File: AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java [hunk 3]
```diff
@@ -176,4 +221,89 @@ private void updateButtonState() {
...
+            return null;
+        }
+        Note n = getCol().newNote(model);
+        ArrayList<String> fieldNames = Models.fieldNames(model);
+        for (int i = 0; i < fieldNames.size(); i++) {
+            n.setField(i, fieldNames.get(i));
+        }
+        try {
+            JSONObject template = (JSONObject)model.getJSONArray("tmpls").get(ordinal);
+            PreviewerCard card = (PreviewerCard)getCol()._newCard(new PreviewerCard(getCol()), n, template, 1, false);
```
[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java]: I need to think about this one. I understand (I think) the desires. What I need from _newCard is a real Card object (with just a couple bits essentially "mocked out" via the PreviewerCard subclass) that is correctly tied into the rendering infrastructure, which is itself welded hard into Collection etc. But maybe there's another way.

File: AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java]: > I'm starting to feel that we should make a new class for the template previewer to specially handle loading a temporary model.

I did similar with PreviewerCard as a Card subclass, would you be averse to a TemplatePreviewer that was a subclass? I personally don't mind object hierarchies (obviously from my previous submissions) but if that's distasteful I could try some other way to compose the behavior

**Comment by timrae** [comment]
Making a subclass directly from Reviewer is what I had in mind!

File: AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java]: @timrae I just pushed commit https://github.com/ankidroid/Anki-Android/pull/5151/commits/d9f6a393e7874351ea957d2248bbeb09b7ceae20 that did CardTemplatePreviewer as a subclass of Previewer (not directly subclassing AbstractFlashcardViewer). There is still back/forward functionality, and all the UI setup (no gestures, etc etc) that was common in both, it seemed to me that CardTemplatePreviewer is just giving Previewer the extra power to view completely ephemeral models, but is otherwise a regular previewer, so I felt like it fit. Curious for your take on that or if you don't like it

[the remark this answers is not in the document]
Comment (timrae) [reply AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java]: >  it seemed to me that CardTemplatePreviewer is just giving Previewer the extra power to view completely ephemeral models, but is otherwise a regular previewer

> Curious for your take on that or if you don't like it

Well, I don't see it that way. The Previewer takes a list of card ids and shows buttons for scrolling through all the cards in the list. The template previewer is for previewing a single ephemeral card, and will never show the scrolling buttons. I see them as two different Activities with different non-overlapping purposes, and different GUI / APIs. I also see the possibility of the two diverging further in the future as highly likely (as I mentioned above).

It's not really a big deal at all, but note I would have preferred for you to ask for clarification on the reasons why I explicitly said to inherit from AbstractFlashcardViewer and not Previewer, rather than jumping straight into implementing it the opposite way.

Anyway, probably your design is OK for now, and at least the code is separated out into a different class now, so thanks for taking care of that.

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java [hunk 4]
```diff
@@ -454,71 +444,72 @@ public void onCreateOptionsMenu(Menu menu, MenuInflater inflater) {
...
                         final JSONObject template = tmpls.getJSONObject(position);
                         // Don't do anything if only one template
                         if (tmpls.length() < 2) {
-                            UIUtils.showThemedToast(getActivity(), res.getString(R.string.card_template_editor_cant_delete), false);
+                            UIUtils.showThemedToast(templateEditor, res.getString(R.string.card_template_editor_cant_delete), false);
+                            return true;
+                        }
+
+                        // Make sure we won't leave orphaned notes if we do delete the template
+                        if (Models.isRemTemplateSafe(col, templateEditor.mEditedModel, position) == null) {
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java]: SQL query on the GUI thread

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java [hunk 5]
```diff
@@ -129,6 +100,9 @@ protected void onCreate(Bundle savedInstanceState) {
         if (savedInstanceState == null) {
             // get model id
             mModelId = getIntent().getLongExtra("modelId", -1L);
+            mEditedModel = null;
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java]: Why do you need to set them to null again?

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java [hunk 6]
```diff
@@ -257,23 +231,30 @@ public void onPageScrollStateChanged(final int position) { /* do nothing */ }
...
                 .content(R.string.discard_unsaved_changes)
                 .positiveText(R.string.dialog_ok)
                 .negativeText(R.string.dialog_cancel)
                 .onPositive((dialog, which) -> {
                     Timber.i("TemplateEditor:: OK button pressed to confirm discard changes");
-                    getCol().getModels().update(CardTemplateEditor.this.mModelBackup);
-                    getCol().getModels().flush();
-                    getCol().reset();
+                    clearTempModelFiles(this);
+                    mEditedModelFileName = null;
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java]: I don't think it's necessary to set these to null here is it? When I see code written that is usually omitted, it makes me think that there's some special reason for setting the value to null, like a static variable somewhere. That doesn't seem to be the case here, and it looks really weird and arbitrarily superfluous to me.

**Comment by timrae** [comment]
I started reviewing this and noticed that several comments from my previous review haven't been addressed. Are you still working on this, or did you forget to address them?

**Comment by mikehardy** [comment]
I have only addressed the subclass issue so far, the rest must be addressed still, yes. The su class was a big structural item so I wanted feedback earlier as I have less time now

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java [hunk 7]
```diff
@@ -301,12 +282,17 @@ public void selectTemplate(int idx) {
     // INNER CLASSES
     // ----------------------------------------------------------------------------
 
+
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java]: I feel this requires a comment

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java [hunk 8]
```diff
@@ -212,8 +187,15 @@ protected void onCollectionLoaded(Collection col) {
         super.onCollectionLoaded(col);
         // Create the adapter that will return a fragment for each of the three
         // primary sections of the activity.
-        mTemplateAdapter = new TemplatePagerAdapter(getSupportFragmentManager());
-        mTemplateAdapter.setModel(col.getModels().get(mModelId));
+        mTemplateAdapter = getNewTemplatePagerAdapter(getSupportFragmentManager());
+        if (mEditedModel == null) {
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java]: What's the purpose of this null check? Under what situation would this not be null? I think this requires a comment or ideally a more self-documenting coding style

**Comment by mikehardy** [comment]
I can see your point, my coding it and pushing it by itself first was explicitly so we could see it concretely and double check. I'm not attached to either way and it should be easy to snip previewer out of the inheritance chain and see that next - this is sort of a way point on the way to that oitent8end state anyway. The rest of the feedback was much more straightforward so I feel like I can address it all now 

-Mike


-----Original Message-----

**Comment by timrae** [comment]
Yeah I know that was your intention, and you're welcome to do whatever works for you, but once there is an implementation which is "good enough", the motivation to spend further time changing or discussing it disappears, even if it may not optimal. Especially in open-source, where everyone is a volunteer.

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java [hunk 9]
```diff
@@ -776,4 +742,149 @@ private String newCardName(JSONArray templates) {
             return name;
         }
     }
+
+
+    /**
+     * Template deletes shift card ordinals in the database. To operate without saving, we must keep track to apply in order.
+     * In addition, we don't want to persist a template add just to delete it later, so we combine those if they happen
+     */
+    public void addTemplateChange(ChangeType type, int ordinal) {
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java]: This seems a bit overcomplicated to me to be honest... Why don't you just compact the changes in the async task when you save the model? Is there some specific functionality that is enabled by this extra complication?

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java]: True - and this was the most difficult part of the implementation for me. One of my first versions did the compaction during save but it was just actually more complicated there because if you don't compact the moment you might have added a duplicate you have to track where the additions happened as well and things get really nasty. I had a tested + working implementation of that but it was nasty compared with what shook out here as I altered it to compact-on-add. The "specific functionality" that is enabled is that users can successfully delete a template that they added during the same edit session (i.e., add ephemeral template, delete it - or even add 3 then delete the second one) - a baseline expectation I think.

**Comment by mikehardy** [comment]
> I took another quick look this evening. I'm starting a new job tomorrow so the last one week was kind of your window of opportunity for fast action on this 😆 but I'll try to be a bit more responsive than the past few months.

Well, sorry I wasn't able to take advantage of it but congrats on the new job! I have just a week or so before my startup goes into a pilot with a prototype so the timing didn't line up unfortunately. I will respond to all of these but I haven't been responsive on new features no, just minding support while the day job is busy...but it'll get done

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java (hunk 9 above)
Comment (timrae) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java]: > The "specific functionality" that is enabled is that users can successfully delete a template that they added during the same edit session

That should be possible without doing the "compacting" process at all, it would just make an add call and then a delete call to libanki right?

The harder functionality to enable would be to allow adding and deleting without requiring a full sync. That's much harder, and:

1. It's not possible with the old implementation
2. Correct me if I'm wrong, but I believe it's not possible on the Anki desktop implementation.
3. From my brief reading of your code, I'm not convinced it even works in your implementation. Have you tested it? Presumably the full sync check would have to happen when a save is requested rather than when a delete is requested. This adds a whole other layer of complexity which I feel is outside the scope of this PR.

If it really turns out to be necessary, I think you'll need to refactor the "differential change" storage out into a proper data structure, as I think it makes it too hard to understand the flow at the moment.

**Comment by timrae** [comment]
> Well, sorry I wasn't able to take advantage of it but congrats on the new job! I have just a week or so before my startup goes into a pilot with a prototype

Thanks! That's awesome, good luck man, I hope the pilot is well received!

**Comment by mikehardy** [comment]
Still working through the pilot launch over here so I haven't circled around but I will. In the meantime I was handling a dependency update to the Acra+analytics stuff and wanted to test it to make sure it was working. While doing that I saw this crash in analytics that wasn't in acralyzer (easily possible depending on what's enabled by the user):

https://analytics.google.com/analytics/web/#/report/app-content-crashes/a125800786w184475040p181795472/_u.date00=20181201&_u.date01=20190325&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.appVersion:20900166,analytics.exceptionDescription:android.os.TransactionTooLargeException:%20data%20parcel%20size%202361796%20bytes

Someone tried to pass 202,361,796 bytes through a Parcel somehow. Those are the backing store for the Bundles in saveInstanceState or when you send data in an intent, so I think the file storage idea is write even if that size is clearly insane. I'd suppose I need to add a spinner and do it in the background, seeing this, but at least it won't crash?

Also you had posited above that doing a add+delete of same template without a full sync would be a justifier for the compaction - and I think I actually did implement it that way, or if not I should enable it, as yes - that's what makes it worthwhile. I don't call into libanki for saves to backing store until the user actually saves, then I compact and store. So it's definitely possible.

Anyway, you left a bunch of review that looked on target as I saw it come in and it's on me to address it. Cheers

**Comment by mikehardy** [comment]
Some progress: Resolved conflicts, responded to "CardTemplatePreviewer should inherit from Previewer directly" request and we're close to back on track

I still have not responded to the rest of the review, so with the exception of seeing what CardTemplatePreviewer looks like now (the current last commit) there is nothing review-worthy

File: AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java [hunk 10]
```diff
@@ -800,12 +800,15 @@ private Card _newCard(Note note, JSONObject template, int due) {
 
 
     private Card _newCard(Note note, JSONObject template, int due, boolean flush) {
-        Card card = new Card(this);
+        return _newCard(new Card(this), note, template, due, flush);
+    }
+
+    public Card _newCard(Card card, Note note, JSONObject template, int due, boolean flush) {
```
[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java]: My next commit will alter naming convention, and add a descriptive comment about what exactly is going on here, and why

File: AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java]: I couldn't think of a good way around this one

File: AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java [hunk 11]
```diff
@@ -32,18 +34,23 @@
...
 
     @Override
     protected void onCreate(Bundle savedInstanceState) {
         Timber.d("onCreate()");
         super.onCreate(savedInstanceState);
 
-        mCardList = getIntent().getLongArrayExtra("cardList");
-        mIndex = getIntent().getIntExtra("index", -1);
-        if (mCardList.length == 0 || mIndex < 0 || mIndex > mCardList.length - 1) {
+        Bundle parameters = savedInstanceState;
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java]: It was never logged as a bug, but Previewer still needs this work in the lifecycle methods or it crashed across Activity restarts (app background / death, re-foreground). I found it while exercising all the code in the area and fixed it before we split CardTemplatePreviewer from Previewer. Worth keeping I think, and tested via robolectric

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java (hunk 6 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java]: If those aren't cleared, then the edits to the model are still present in the object, whereas the user specifically requested to discard them

Added
```java
                    // Clear the edited model from any cache files, and clear it from this objects memory to discard changes

```

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java (hunk 7 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java]: Added a comment - there are some nasty bugs with regard to testing pagers and fragments, I spent a fair bit of time collaborating with the robolectric team on them and the end result is that with a little plumbing pass through and some overrides I could get coverage all over this object even though it's pretty UI intensive. 

Added

```java
    // Testing Android apps is hard, and pager adapters in fragments is nearly impossible.
    // In order to make this object testable we have to allow for some plumbing pass through
```

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java (hunk 2 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java]: I altered it to mVariableName - I tried all varieties of hooking these together but something about the CardTemplateFragment being a static factory gave me bizarre results at all turns. I'd prefer to let this one sit, especially since I'm testing lifecycle and it works

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java (hunk 4 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java]: :scream:  - so, should be a DeckTask async? can we log this as a defect but not perturb the PR anymore? it's already massive and by my take it was on the GUI thread prior - the PR is not increasing badness

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java [hunk 12]
```diff
@@ -651,8 +595,15 @@ public void run() {
...
                 };
+                Runnable cancel = new Runnable() {
+                    @Override
+                    public void run() {
+                        templateEditor.dismissAllDialogFragments();
+                    }
+                };
                 d.setConfirm(confirm);
-                ((AnkiActivity) getActivity()).showDialogFragment(d);
+                d.setCancel(cancel);
```
[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java]: definitely - done

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java (hunk 9 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java]: I can do this as a separate change, but this is the core of the PR really. The rest is just an interesting idea, this is what makes it happen.

The whole point of the PR is to not touch persistence until editing is complete. To do otherwise corrupts the data model. Those were real bugs, this was the real root cause.

So if I edit without persistence, then I feed adds and deletes into libanki at the end, I have to track the original state, the current editing state, and in order to get the final editing state as the thing libanki has at the end I have to track every add/delete made in order so I feed it to libanki in the correct order (imagine add 2 cards, edit 1, delete 2nd, add a 3rd, edit the 3rd - it's in the 2nd slot though,...etc)

The first thing I did was add a test that expressed what I wanted: https://github.com/ankidroid/Anki-Android/pull/5151/files#diff-15acb98a47acf7f1ea6dd43d49947f94R159

Then as I attempted to do what you want, it was terrible. The data structure required was a mess and the logic around it was also terrible. Now the data structure is pretty lean and the logic is even just a bit simpler.

So I'm comfortable saying this is a clean way to do in-memory card template edits.

If you want it separate, that's fine. Please be prescriptive on separate how, like an internal class, or a separate class, or ?

If we want to support add/delete cycles without sync, that should be possible but it was not the focus of this PR

The whole focus here was to stop corrupting databases when people added or removed a card template then "discarded changes" thinking everything was fine

**Comment by mikehardy** [comment]
@timrae okay I think I've addressed all the comments. I'd really like this one to land before 2.9, otherwise the work we did on database corruption cleaning from 2.8 -> 2.9 will be needed again as the existing CardTemplateEditor can still corrupt databases. I think it could go as is and the testing added supports that

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java (hunk 6 above)
Comment (timrae) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java]: Fair enough, the object is just about to be destroyed anyway, so it looks a bit weird to me, but each to their own.

**Comment by timrae** [comment]
I'm half-way through reviewing this, I finally remembered the main point of the original bug, after going back to my [comment from 6 months ago](https://github.com/ankidroid/Anki-Android/pull/5053#issuecomment-432888220), and now the code is starting to make more sense:

> It seems the current simplistic approach of reverting to the model backup is incorrect for the case where card templates have been added or deleted, because it doesn't handle undoing of the cards which are generated / deleted.

I'll hopefully get a chance to finish reviewing tomorrow

**Comment by mikehardy** [comment]
Exactly! It’s a great deal of data structure, partially persisted (existing templates) partially ephemeral (anything you add) with a desire to preview using existing display infra and desire to discard all changes? this was a real hairball, hacked up just because I was on an anti-crash crusade. If it hadn’t also been a data corruptor I might have left it, as it was so much effort vs things that would have greater user impact, but I couldn’t leave the corruption alone

File: AnkiDroid/src/main/java/com/ichi2/libanki/Models.java [hunk 13]
```diff
@@ -827,7 +823,26 @@ public boolean remTemplate(JSONObject m, JSONObject template) throws ConfirmModS
     }
 
 
-    public void _updateTemplOrds(JSONObject m) {
+    /**
+     * Extracted from remTemplate so we can test if removing a template is safe without actually removing it
+     * Verifies all notes with this template have at least two cards, to guard against creating orphaned notes
+     * @return null if not safe, long[] of card ids to delete if it is safe
+     */
+    public static @Nullable long[] isRemTemplateSafe(Collection col, JSONObject m, int ord) throws JSONException {
```
[the remark this answers is not in the document]
Comment (timrae) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Models.java]: Or even better, make this private, and make a better public interface:

```java
public bool isRemTemplateSafe(long modelId, int ord) { 
```

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java [hunk 14]
```diff
@@ -454,71 +446,72 @@ public void onCreateOptionsMenu(Menu menu, MenuInflater inflater) {
...
                         final JSONObject template = tmpls.getJSONObject(position);
                         // Don't do anything if only one template
                         if (tmpls.length() < 2) {
-                            UIUtils.showThemedToast(getActivity(), res.getString(R.string.card_template_editor_cant_delete), false);
+                            UIUtils.showThemedToast(mTemplateEditor, res.getString(R.string.card_template_editor_cant_delete), false);
+                            return true;
+                        }
+
+                        // Make sure we won't leave orphaned notes if we do delete the template
+                        if (Models.isRemTemplateSafe(col, mTemplateEditor.mEditedModel, position) == null) {
```
[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java]: Hmm - I'll see if I can poke at that idea with a test and reason through it. Might have something there

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java [hunk 15]
```diff
@@ -0,0 +1,223 @@
...
+
+        showBackIcon();
+        // Ensure navigation drawer can't be opened. Various actions in the drawer cause crashes.
+        disableDrawerSwipe();
+        startLoadingCollection();
+    }
+
+    @Override
+    protected void onResume() {
+        super.onResume();;
```
[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java]: silly - removed

File: AnkiDroid/src/main/java/com/ichi2/libanki/Models.java (hunk 13 above)
[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Models.java]: 'bool' doesn't exist in Java, but your html textarea API design is still on point ;-). Committing this change in a moment

**Comment by timrae** [comment]
@mikehardy 

Do you need some help with this? I want to release another alpha version after merging this, and then do feature freeze and move it into the beta channel.

**Comment by mikehardy** [comment]
Yeah - I need to extract the data structure as requested (it's a good request - I agree and want to do it) and as part of that add some cumulative tracking of deletes so that for the N+1th delete if it fails the Models.isSafeToDelete to delete check I can handle it even though deletes 1...N didn't trigger it. 

I just have about 36 hours of productive time left before I start travel and what worries me is that if I do this and submit it I'll end up dropping some crash bug like the database versioning one in your lap while I'm literally on Bolivian salt flats and can't fix it. If you accept that risk I can give it a shot, I just want to apologize in advance as my normal responsiveness will be absent until Aug 8 or so

**Comment by mikehardy** [comment]
perhaps the correctness error first with time available - checking deletes cumulatively - then the more stylistic extraction separately? to prioritize available time?

**Comment by mikehardy** [comment]
Sorry - to spam, but I'm gearing up for the multi-delete check now. My first goal was to see how to probe it with a test so I'd know I was doing it right. I think I'm already testing it https://github.com/ankidroid/Anki-Android/pull/5151/files#diff-15acb98a47acf7f1ea6dd43d49947f94R245 - I'm going to try to blow it up in an emulator because your review comment - that it would fail - seems correct, but I appear to be testing it and it is responding correctly. So, I'll report back in a bit when I've checked that case. If it passes there aren't (known) correctness issues, just the unreadability

**Comment by timrae** [comment]
Is the toast showing up through that specific call to libanki though? Or is it showing up through another code path, for example a more simple check to make sure the number of templates doesn't reduce to zero? From looking at that SQL query, the conditions for that function triggering are not totally obvious, so a simple test might not be enough.

**Comment by mikehardy** [comment]
@timrae check my just-pushed-now commit for my first take on avoiding orphans even though the database is unaware of other pending deletes.

Not backed by a unit test but passes an emulator click-around and seems like it snipes that particular issue if it’s an okay approach?

I left a note about the abstraction, I wanted to get to correctness + acceptable style first

The algorithms aren’t the most pleasant so I commented the whole way through it

**Comment by timrae** [comment]
@dae 

I'm sorry if I've already asked this before, but in Anki Desktop, under what conditions would [this check](https://github.com/dae/anki/blob/master/aqt/clayout.py#L206) not trigger (i.e. the model has more than 1 template), but the call to `remTemplate()` on line 215 would fail and we'd see the following message?

```Removing this card type would cause one or more notes to be deleted. Please create a new card type first.```?

It would seem to me that could only happen if a note had less cards than the model had cards, which should only happen in the case of a corrupted database.

**Comment by dae** [comment]
In a note type with two card templates, some notes may only use card 1, and some may only use card 2. If you delete the 2nd template, it will cause the notes that only use card 2 to disappear.

**Comment by timrae** [comment]
Ah yeah, I totally forgot about the selective generation feature. Thank you!

@mikehardy
So the unit test would then be to make a model with two fields `Enable1` and `Enable2`

**Comment by mikehardy** [comment]
Okay - I'll work on a unit test, and it still needs extraction. But from a functional perspective I wrote out test cases on the algorithm and did old-school with visual inspection on intentional logging and I think it's correct at this point. Which is to say, I think it's functionally (though not stylistically) ready for merge, but unfortunately I'm out of time on this one - I have 12 waking hours left before I travel for a month and 2 day job items left on my list so I've got to prioritize them. Your option on doing this now or waiting for later - I'm fine either way but can't put more effort in just now. As much as I love a good unit test ;-)

**Comment by mikehardy** [comment]
ACRA just recorded an error for someone where the parcel size was too large when it was 1.3MB https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/a19b5608-f972-4a0e-b5c4-d87f6f61b370 - what does this mean? It means the file-saving style of passing things is vital - people put unbounded amounts of data in their templates and it actually will crash. Previously I was implementing it that way out of an abundance of caution but now I've seen the crash...

**Comment by timrae** [comment]
I've started taking a look at this today. So far I've just rebased onto master and did an initial sanity check.

https://github.com/timrae/Anki-Android/tree/template-editor-v2

I found one bug...

1. Manage note types
1. Long click on any model
1. Choose edit cards
1. Click preview button

--> Crashes instead of showing a dummy card

**Comment by mikehardy** [comment]
interesting - there are still comments I hadn't addressed so it needs a pretty thorough scrubbing still. Thanks for the bug report

**Comment by mikehardy** [comment]
@timrae fixed that one - I was attempting to avoid sending the model unless it had already been edited, but the CardTemplatePreviewer needs it all the time. https://github.com/ankidroid/Anki-Android/pull/5151/commits/8e12c2601b421ef09c71627c1f6e986ec2746df8

This PR is fully rebased against master now, same as the PR I sent against your fork/branch with this work

I believe the bulk of the pending work was to peel the card add/edit tracking+compaction off into it's own object with API and data structure internal

**Comment by mikehardy** [comment]
@timrae You had mentioned that it is hard to figure out where things are, requiring full re-reads, and as I pick this up again it definitely is. After a full re-read, this is the full status as of 20191105:

- we need to extract the temporary model with compact-on-add logic from CardTemplateEditor: https://github.com/ankidroid/Anki-Android/pull/5151#discussion_r297921873

- we need a unit test to make sure we only delete safely, current unit test is not *quite* tickling a very subtle case: https://github.com/ankidroid/Anki-Android/pull/5151#issuecomment-507889028

- not a regression as existing code does same, but there's a SQL query on GUI thread noted: https://github.com/ankidroid/Anki-Android/pull/5151#discussion_r262546714

I am not aware of any other item or discussion pending on this

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           

Complexity increasing per file
==============================
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java  6
- AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/PreviewerTest.java  2
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  8
- AnkiDroid/src/test/java/com/ichi2/anki/TestPreviewer.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/NonPagingCardTemplateEditor.java  1
- AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java  1
- AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java  7
         

Complexity decreasing per file
==============================
+ AnkiDroid/src/main/java/com/ichi2/libanki/Card.java  -2
+ AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java  -2
         

Clones added
============
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688&bid=10073006)

**Comment by mikehardy** [comment]
I extracted the in-memory model work to a TemporaryModel object with an API roughly as you proposed @timrae - thoughts?

**Comment by timrae** [comment]
@mikehardy 

I think at this point it might be prudent for us to take a bit of a step back and discuss whether this is really what we want. I apologize in advance as this probably feels like I'm stabbing you in the nuts saying this after you've done all this work, but at this point I'm basically the gatekeeper between the AnkiDroid codebase and the cold infinite void, so here goes...

We have here, 27 commits, 700+ new lines of code (excluding tests), and despite having spent several days of work going through the code in some detail multiple times over the past 12 months, I still don't really understand it, and I have no idea whether or not it's correct (I see there are quite a lot of unit tests, but I haven't checked them). Based on experience I would be willing to wager that A) There's a high possibility this PR is introducing some new bug(s), and B) I'm not going to be able to fix them, and C) 12 months from now, you won't remember very much and might struggle as well.

Had I imagined reviewing this PR was going to be this exhausting, I almost certainly would have put my foot down harder, and pushed for the vastly simpler approach that I was previously advocating for: blocking adding/removing templates when there are unsaved changes to the model, and making it clear that add/remove operations are irreversible. It might be interesting to look at analytics data, but I assume only a very small number of users regularly use this feature on AnkiDroid, so it does feel to me like we've spent a disproportionate amount of time here on handling the edge cases of a very minor feature.

Now I'm not saying that I'm against merging this PR, I am about 30% through the code review and am willing to finish it off as I want to see this bug fixed, but I am saying that once it's in, you'll need to support it long-term, and you'll likely be on your own there, so I want to double-check with you whether or not merging this is really what you want?

**Comment by mikehardy** [comment]
The unit tests are actually a good way to review it, as they have nearly full coverage on the affected code, and they show exactly what should work and why (via comments and assertions).

I am also certain that there will be something uncovered, but with the previous problem the testing support actually makes things pretty easy to fix - same situation as Mathjax basically, since Adam Wolf developed the feature with testing concurrently, bugs just involve adding whatever new case to the test suite and the bug is usually obvious. That was the point of all the requery Sqlite / robolectric stuff before - so this whole feature had support in that way, and a year from now the tests will serve as my guide. They did for that previous bug as well.

Which is all to say, I'm comfortable supporting it, and near as I can tell it works, so I don't like the idea of what is to me a worse UX (where edits have different types - adds/deletes vs text changes) and we have to handle all the messaging etc required.

Usage analytics indicate it is not a commonly used feature, no, either add/remove or edit really. But from a database corruption standpoint it stood out as one of the primary causes so I'm motivated to fix, and since from my perspective the code's working with the current UX I'd still like to see it in.

From an understanding standpoint it's just doing two main things:
1- models when edited are kept separate from the Collection / not saved until the user really wants to save. This implies they are now passed around via file (to avoid overflowing all the other message-passing options)
2- when the user saves, template add/deletes must be "re-played" as separate actions into the collection so that the resulting ordinal shifts in the model in the database caused by each add/delete are correct and in-order

Item 1 required lots of little changes in order for Models to not touch the database when that wasn't wanted, and to save/load from a file

Item 2 required a data structure and logic for add/delete tracking/replay

The tests show (and exercise) the same

File: AnkiDroid/src/main/java/com/ichi2/libanki/Models.java [hunk 16]
```diff
@@ -890,7 +887,45 @@ public boolean remTemplate(JSONObject m, JSONObject template) throws ConfirmModS
...
+                ordString += ", ";
+            }
+            ordString += ords[i];
+        }
+        String sql = "select c.id from cards c, notes f where c.nid=f.id and mid = " +
+                modelId + " and ord in (" + ordString + ")";
+        Timber.d("getCardIdsForModel sql = %s", sql);
+        long[] cids = Utils.toPrimitive(mCol.getDb().queryColumn(Long.class, sql, 0));
+        // all notes with this template must have at least two cards, or we could end up creating orphaned notes
+        sql = "select nid, count() from cards where nid in (select nid from cards where id in " +
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Models.java]: I feel like we previously discussed this, but I am really struggling to see how this algorithm could be correct tbh... AFAICT previously the algorithm was saying that *if every note of the model has at least two cards, then removing any one template would not lead to orphaned notes*. Now it seems you are applying the exact same query and somehow intending to extrapolate that to say *if every note of the model has at least two cards, then removing any N templates would not lead to orphaned notes*, which is nonsense isn't it?

Maybe you need more test cases for this, unless I am missing something...?

File: AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java [hunk 17]
```diff
@@ -21,9 +22,14 @@
 import android.os.Bundle;
 import android.view.View;
 
+import com.ichi2.libanki.Card;
 import com.ichi2.libanki.Collection;
 import com.ichi2.themes.Themes;
+import com.ichi2.utils.JSONObject;
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java:28]: Codacy Issue found: [Avoid unused imports such as 'com.ichi2.utils.JSONObject'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 4
           

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/NonPagingCardTemplateEditor.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/PreviewerTest.java  2
- AnkiDroid/src/test/java/com/ichi2/anki/TestPreviewer.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  8
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java  6
- AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java  7
- AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java  1
         

Clones added
============
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688&bid=10073006)

File: AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java [hunk 18]
```diff
@@ -21,9 +22,14 @@
...
 
+import java.util.ArrayList;
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java:30]: Codacy Issue found: [Avoid unused imports such as 'java.util.ArrayList'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688)

File: AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java [hunk 19]
```diff
@@ -21,9 +22,14 @@
...
+
+import androidx.annotation.Nullable;
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java:32]: Codacy Issue found: [Avoid unused imports such as 'androidx.annotation.Nullable'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688)

File: AnkiDroid/src/main/java/com/ichi2/libanki/Models.java [hunk 20]
```diff
@@ -22,11 +22,14 @@
...
 import android.database.Cursor;
 import android.util.Pair;
+import androidx.annotation.Nullable;
+import timber.log.Timber;
 
 import com.ichi2.anki.exception.ConfirmModSchemaException;
 import com.ichi2.utils.Assert;
 
 import com.ichi2.utils.JSONArray;
+import com.ichi2.utils.JSONException;
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Models.java:32]: Codacy Issue found: [Avoid unused imports such as 'com.ichi2.utils.JSONException'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  8
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java  6
- AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java  1
- AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/NonPagingCardTemplateEditor.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/PreviewerTest.java  2
- AnkiDroid/src/test/java/com/ichi2/anki/TestPreviewer.java  1
- AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java  7
         

Clones added
============
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688&bid=10073006)

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java (hunk 14 above)
[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java]: I have flagged (and am working on) the case where through selective generation we need to be very careful that we don't delete templates too quickly, but I think failing the check / saying it is not safe to remove based solely on what is already in the database is more strict than also checking if added in-memory templates would generate cards that would let it pass. Said in another way: checking only in-database generated cards to make sure we're safe might generate false-negatives (we say not safe to delete but you actually are because of an added template) but will not generate false-positives (we say it is safe to delete but it is actually not)

Rather than generate more code that can figure out what cards would speculatively be generated an added template, I'm going to leave a note that this corner case is not handled and leave it be unless I hear from users it's important. I can't imagine that many will stack up a bunch of ephemeral edits that have interrelated selectively generated cards

File: AnkiDroid/src/main/java/com/ichi2/libanki/Models.java (hunk 16 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Models.java:806]: This is still (but again after rebasing and rechecking everything) the last point of work - your comment is right and I have aggregated the previous response from dae about selective generation etc. To say: I've attempted to be a steel trap not losing any of the feedback and I'll solve this before merging for sure

File: AnkiDroid/src/main/java/com/ichi2/libanki/Models.java [hunk 21]
```diff
@@ -736,7 +736,9 @@ public void addTemplateModChanged(JSONObject m, JSONObject template)  {
      * @throws ConfirmModSchemaException 
      */
     public boolean remTemplate(JSONObject m, JSONObject template) throws ConfirmModSchemaException {
-        assert (m.getJSONArray("tmpls").length() > 1);
+        if (m.getJSONArray("tmpls").length() <= 1) {
+            return false;
+        };
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Models.java:741]: Codacy Issue found: [An empty statement (semicolon) not part of a loop](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 1
           

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/NonPagingCardTemplateEditor.java  1
- AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java  7
- AnkiDroid/src/test/java/com/ichi2/anki/TestPreviewer.java  1
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java  6
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  8
- AnkiDroid/src/test/java/com/ichi2/anki/PreviewerTest.java  2
- AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java  1
         

Clones added
============
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688&bid=10073006)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 1
           

Complexity increasing per file
==============================
- AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/NonPagingCardTemplateEditor.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/PreviewerTest.java  2
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java  6
- AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java  7
- AnkiDroid/src/test/java/com/ichi2/anki/TestPreviewer.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  8
         

Clones added
============
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688&bid=10073006)

File: AnkiDroid/src/main/java/com/ichi2/libanki/Models.java (hunk 21 above)
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Models.java:741]: Codacy Issue found: [An empty statement (semicolon) not part of a loop](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 1
           

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/TestPreviewer.java  1
- AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java  1
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java  6
- AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java  7
- AnkiDroid/src/test/java/com/ichi2/anki/PreviewerTest.java  2
- AnkiDroid/src/test/java/com/ichi2/anki/NonPagingCardTemplateEditor.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  8
         

Clones added
============
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688&bid=10073006)

File: AnkiDroid/src/main/java/com/ichi2/libanki/Models.java [hunk 22]
```diff
@@ -729,7 +729,9 @@ public void addTemplateModChanged(JSONObject m, JSONObject template)  {
...
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Models.java:734]: Codacy Issue found: [An empty statement (semicolon) not part of a loop](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688)

**Comment by mikehardy** [comment]
I've trimmed it from 28 commits to 17 and peeled the robolectric upgrade out of this (#5997) which helped a lot in cleaning it up. Still want to do some preening on the commit history, and I've noted the current failure to handle selective generation, it's still the last functional todo.

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java  1
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java  6
- AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/PreviewerTest.java  2
- AnkiDroid/src/test/java/com/ichi2/anki/NonPagingCardTemplateEditor.java  1
- AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java  7
- AnkiDroid/src/test/java/com/ichi2/anki/TestPreviewer.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  9
         

Clones added
============
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688&bid=10073006)

File: AnkiDroid/src/main/java/com/ichi2/libanki/Models.java (hunk 22 above)
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Models.java:734]: Codacy Issue found: [An empty statement (semicolon) not part of a loop](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688)

File: AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java [hunk 23]
```diff
@@ -0,0 +1,354 @@
...
+
+import com.afollestad.materialdialogs.DialogAction;
+
+import org.junit.Assert;
+import org.junit.Test;
+import org.junit.runner.RunWith;
+import org.robolectric.Robolectric;
+import org.robolectric.android.controller.ActivityController;
+import org.robolectric.annotation.LooperMode;
+import org.robolectric.Shadows;
```
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java:33]: Codacy Issue found: [Avoid unused imports such as 'org.robolectric.Shadows'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688)

File: AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java [hunk 24]
```diff
@@ -0,0 +1,354 @@
...
+        Assert.assertEquals(new JSONObject("{foo: bar}").toString(), tempModel.toString());
+
+        // Make sure clearing works
+        Assert.assertEquals(1, TemporaryModel.clearTempModelFiles());
+        Timber.i("The following logged NoSuchFileException is an expected part of verifying a file delete.");
+        Assert.assertNull("tempModel not correctly deleted", TemporaryModel.getTempModel(tempModelPath));
+    }
+
+    @Test
+    public void testEditTemplateContents() throws Exception {
```
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java:78]: Codacy Issue found: [The method 'testEditTemplateContents()' has an NPath complexity of 256](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688)

File: AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java [hunk 25]
```diff
@@ -0,0 +1,21 @@
+package com.ichi2.anki;
+
+public class TestCardTemplatePreviewer extends CardTemplatePreviewer {
+    boolean mShowingAnswer = false;
```
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java:4]: Codacy Issue found: [Use explicit scoping instead of the default package private level](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/PreviewerTest.java  2
- AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/TestPreviewer.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  9
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java  6
- AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java  7
- AnkiDroid/src/test/java/com/ichi2/anki/NonPagingCardTemplateEditor.java  1
- AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java  1
         

Clones added
============
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688&bid=10073006)

File: AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java [hunk 26]
```diff
@@ -0,0 +1,353 @@
...
```
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java:77]: Codacy Issue found: [The method 'testEditTemplateContents()' has an NPath complexity of 256](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 6
           

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java  1
- AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java  8
- AnkiDroid/src/test/java/com/ichi2/anki/PreviewerTest.java  2
- AnkiDroid/src/test/java/com/ichi2/anki/TestPreviewer.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/NonPagingCardTemplateEditor.java  1
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java  6
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  9
- AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/TemporaryModelTest.java  4
         

Clones added
============
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688&bid=10073006)

File: AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java [hunk 27]
```diff
@@ -26,9 +26,11 @@
 import com.ichi2.anki.AnkiDroidApp;
 import com.ichi2.anki.BackupManager;
 import com.ichi2.anki.CardBrowser;
+import com.ichi2.anki.CardTemplateEditor;
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java:29]: Codacy Issue found: [Avoid unused imports such as 'com.ichi2.anki.CardTemplateEditor'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688)

File: AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java [hunk 28]
```diff
@@ -0,0 +1,269 @@
...
+
+import com.ichi2.utils.JSONObject;
+
+import timber.log.Timber;
+
+import static android.os.Looper.getMainLooper;
+import static org.robolectric.Shadows.shadowOf;
+
+import static com.ichi2.anki.TemporaryModel.ChangeType.ADD;
+import static com.ichi2.anki.TemporaryModel.ChangeType.DELETE;
```
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java:48]: Codacy Issue found: [Avoid unused imports such as 'com.ichi2.anki.TemporaryModel.ChangeType.DELETE'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688)

File: AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java [hunk 29]
```diff
@@ -0,0 +1,269 @@
...
+import java.util.ArrayList;
+
+import com.ichi2.utils.JSONObject;
+
+import timber.log.Timber;
+
+import static android.os.Looper.getMainLooper;
+import static org.robolectric.Shadows.shadowOf;
+
+import static com.ichi2.anki.TemporaryModel.ChangeType.ADD;
```
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java:47]: Codacy Issue found: [Avoid unused imports such as 'com.ichi2.anki.TemporaryModel.ChangeType.ADD'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688)

File: AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java [hunk 30]
```diff
@@ -0,0 +1,269 @@
...
+import org.junit.runner.RunWith;
+import org.robolectric.Robolectric;
+import org.robolectric.android.controller.ActivityController;
+import org.robolectric.annotation.LooperMode;
+import org.robolectric.shadows.ShadowActivity;
+import org.robolectric.shadows.ShadowIntent;
+import org.robolectric.shadows.ShadowToast;
+
+import java.io.Serializable;
+import java.util.ArrayList;
```
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java:38]: Codacy Issue found: [Avoid unused imports such as 'java.util.ArrayList'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688)

File: AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java [hunk 31]
```diff
@@ -0,0 +1,269 @@
...
+import org.junit.Test;
+import org.junit.runner.RunWith;
+import org.robolectric.Robolectric;
+import org.robolectric.android.controller.ActivityController;
+import org.robolectric.annotation.LooperMode;
+import org.robolectric.shadows.ShadowActivity;
+import org.robolectric.shadows.ShadowIntent;
+import org.robolectric.shadows.ShadowToast;
+
+import java.io.Serializable;
```
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java:37]: Codacy Issue found: [Avoid unused imports such as 'java.io.Serializable'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688)

File: AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java [hunk 32]
```diff
@@ -0,0 +1,269 @@
...
+
+
+@RunWith(AndroidJUnit4.class)
+@LooperMode(LooperMode.Mode.PAUSED)
+public class CardTemplateEditorTest extends RobolectricTest {
+
+    private static int robolectricQuiesceMillis = 200;
+
+    @Test
+    public void testEditTemplateContents() throws Exception {
```
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java:58]: Codacy Issue found: [The method 'testEditTemplateContents()' has an NPath complexity of 256](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.java  2
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java  6
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  9
- AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java  1
- AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java  8
- AnkiDroid/src/test/java/com/ichi2/anki/TemporaryModelTest.java  4
- AnkiDroid/src/test/java/com/ichi2/anki/NonPagingCardTemplateEditor.java  1
         

Clones added
============
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688&bid=10073006)

File: AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java (hunk 32 above)
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java:58]: Codacy Issue found: [The method 'testEditTemplateContents()' has an NPath complexity of 256](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688)

File: AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java (hunk 30 above)
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java:38]: Codacy Issue found: [Avoid unused imports such as 'java.util.ArrayList'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688)

File: AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java (hunk 28 above)
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java:48]: Codacy Issue found: [Avoid unused imports such as 'com.ichi2.anki.TemporaryModel.ChangeType.DELETE'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688)

File: AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java (hunk 29 above)
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java:47]: Codacy Issue found: [Avoid unused imports such as 'com.ichi2.anki.TemporaryModel.ChangeType.ADD'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688)

File: AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java (hunk 31 above)
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java:37]: Codacy Issue found: [Avoid unused imports such as 'java.io.Serializable'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  9
- AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java  8
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java  6
- AnkiDroid/src/test/java/com/ichi2/anki/TemporaryModelTest.java  4
- AnkiDroid/src/test/java/com/ichi2/anki/NonPagingCardTemplateEditor.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.java  2
         

Clones added
============
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688&bid=10073006)

File: AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java [hunk 33]
```diff
@@ -0,0 +1,263 @@
...
```
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java:52]: Codacy Issue found: [The method 'testEditTemplateContents()' has an NPath complexity of 256](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/TemporaryModelTest.java  4
- AnkiDroid/src/test/java/com/ichi2/anki/NonPagingCardTemplateEditor.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java  1
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java  6
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.java  2
- AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java  8
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  9
         

Clones added
============
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688&bid=10073006)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.java  2
- AnkiDroid/src/test/java/com/ichi2/anki/TemporaryModelTest.java  4
- AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java  8
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  9
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java  6
- AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/NonPagingCardTemplateEditor.java  1
         

Clones added
============
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688&bid=10073006)

File: AnkiDroid/src/main/java/com/ichi2/libanki/Models.java [hunk 34]
```diff
@@ -771,7 +772,49 @@ public boolean remTemplate(JSONObject m, JSONObject template) throws ConfirmModS
...
 
-    public void _updateTemplOrds(JSONObject m) {
+    /**
+     * Easily test if removing one or more templates is safe without actually removing them
+     * Verifies all notes with these templates have at least two cards, to guard against creating orphaned notes
+     * @return false if not safe, true if it is safe
+     */
+    public boolean isRemTemplatesSafe(long modelId, int[] ords) {
+        // to make sure the compound effect of all the pending deletes is taken into account?
+        if (getCardIdsForModel(modelId, ords) == null) {
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Models.java:782]: Codacy Issue found: [Avoid unnecessary if..then..else statements when returning booleans](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java  6
- AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/NonPagingCardTemplateEditor.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.java  2
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  9
- AnkiDroid/src/test/java/com/ichi2/anki/TemporaryModelTest.java  4
- AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java  8
         

Clones added
============
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688&bid=10073006)

File: AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java [hunk 35]
```diff
@@ -0,0 +1,357 @@
...
+     * with Enable1 and Enable2 respectively set to "y".
+     * Then you try to delete one of the templates and it should fail
+     *
+     * (question: but I thought deleting one should work - still one card left to maintain the note,
+     * and second template delete should fail since we finally get to a place where no cards are left?
+     * I am having trouble creating selectively generated cards though - I can do one optional field but not 2 ugh)
+     *
+     */
+    @Test
+    public void testDeleteTemplateWithSelectivelyGeneratedCards() {
```
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java:256]: Codacy Issue found: [Avoid really long methods.](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java  1
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java  6
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  9
- AnkiDroid/src/test/java/com/ichi2/anki/TemporaryModelTest.java  4
- AnkiDroid/src/test/java/com/ichi2/anki/NonPagingCardTemplateEditor.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.java  2
- AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java  8
         

Clones added
============
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688&bid=10073006)

File: AnkiDroid/src/main/java/com/ichi2/libanki/Models.java [hunk 36]
```diff
@@ -771,7 +772,50 @@ public boolean remTemplate(JSONObject m, JSONObject template) throws ConfirmModS
...
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Models.java:782]: Codacy Issue found: [Avoid unnecessary if..then..else statements when returning booleans](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688)

File: AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java [hunk 37]
```diff
@@ -0,0 +1,404 @@
...
```
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java:258]: Codacy Issue found: [Avoid really long methods.](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688)

File: AnkiDroid/src/main/java/com/ichi2/libanki/Models.java [hunk 38]
```diff
@@ -771,7 +772,50 @@ public boolean remTemplate(JSONObject m, JSONObject template) throws ConfirmModS
...
+        int preDeleteNoteCount = mCol.getDb().queryScalar(noteCountPreDeleteSql);
+        Timber.d("preDeleteNoteCount is %s", preDeleteNoteCount);
+        // FIXME not sure about this one - want to make sure I only count notes, but link them correctly
+        String noteCountPostDeleteSql = "select count(n.id) from cards c, notes n where c.nid=n.id and n.mid = " + modelId + " and c.id not in (" + cardIdsToDeleteSql + ")";
+        int postDeleteNoteCount = mCol.getDb().queryScalar(noteCountPostDeleteSql);
+        Timber.d("postDeleteNoteCount would be %s", postDeleteNoteCount);
+
+        if (preDeleteNoteCount != postDeleteNoteCount) {
+            Timber.d("There will be orphan notes if these cards are deleted.");
+            return null;
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Models.java:811]: @timrae **finally** had time to fix this last bit of CardTemplateEditor. Strategy for avoiding orphan notes on attempted deletes of selective generation card templates is pretty simple. 

1. Get the card ids you would delete
1. Count all notes for the model
1. Count the notes left if you don't include notes that only had those cards
1. Disallow delete if the note count isn't the same

The strategy is simple at least but I'm not convinced on the SQL yet, it passes the initial bit of testing but I have a fair bit more study to put into it If you can think of anything wrong with the strategy though, let me know, otherwise I'll have this sewn up shortly

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Models.java:811]: Here's the probe, though the link may be unstable if I force-push https://github.com/ankidroid/Anki-Android/pull/5151/files#diff-15acb98a47acf7f1ea6dd43d49947f94R258

Comment (timrae) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Models.java:811]: I'm afraid I won't be of much help when it comes to SQL, the strategy sounds reasonable to me but what would I know 😆. I would get Damien to double check your SQL and logic when you think it's ready, since it's diverging pretty drastically from libanki.

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Models.java:811]: Ok - per Tim's suggestion then, @dae may I ask what your thoughts are here? The context is one we discussed long ago and I'm finally trying to button down: 

1. user attempting to delete a card template in a model
1. the card template is involved in selective card generation (like the basic with optional reverse model)
1. there are notes using the selective generation so deleting the template would orphan them, we need to deny the deletion

I am moving the Android CardTemplateEditor to work with the templates in memory to avoid various problems with speculatively persisting edits that are then unsaved, so it is possible I have to check whether a combination of deletes at the same time is okay, vs the original check which was for a single ordinal.

So my strategy is to 1. get card ids to delete 2. get current note count 3. get note count not including notes that only exist with this cards

I've implemented it like so. It seems to work, but maybe I'm crazy? I would love another set of eyes on it if you have time:

```java
        String cardIdsToDeleteSql = "select c2.id from cards c2, notes n2 where c2.nid=n2.id and n2.mid = " +
                modelId + " and c2.ord  in " + Utils.ids2str(ords);
        long[] cids = Utils.toPrimitive(mCol.getDb().queryColumn(Long.class, cardIdsToDeleteSql, 0));
        Timber.d("cardIdsToDeleteSql was '" + cardIdsToDeleteSql + "' and got %s", Utils.ids2str(cids));
        Timber.d("getCardIdsForModel found %s cards to delete for model %s and ords %s", cids.length, modelId, Utils.ids2str(ords));

        // all notes with this template must have at least two cards, or we could end up creating orphaned notes
        String noteCountPreDeleteSql = "select count() from notes where mid = " + modelId;
        int preDeleteNoteCount = mCol.getDb().queryScalar(noteCountPreDeleteSql);
        Timber.d("noteCountPreDeleteSql was '%s'", noteCountPreDeleteSql);
        Timber.d("preDeleteNoteCount is %s", preDeleteNoteCount);
        // FIXME not sure about this one - want to make sure I only count notes, but link them correctly
        String noteCountPostDeleteSql = "select count(n.id) from cards c, notes n where c.nid=n.id and n.mid = " + modelId + " and c.id not in (" + cardIdsToDeleteSql + ")";
        Timber.d("noteCountPostDeleteSql was '%s'", noteCountPostDeleteSql);
        int postDeleteNoteCount = mCol.getDb().queryScalar(noteCountPostDeleteSql);
        Timber.d("postDeleteNoteCount would be %s", postDeleteNoteCount);

        if (preDeleteNoteCount != postDeleteNoteCount) {
            Timber.d("There will be orphan notes if these cards are deleted.");
            return null;
        }
        Timber.d("Deleting these cards will not orphan notes.");

```

It results in SQL like so in case you want to play with it against a collection

```

2020-04-21 16:31:10.745 7802-7802/com.ichi2.anki D/Models: cardIdsToDeleteSql was 'select c2.id from cards c2, notes n2 where c2.nid=n2.id and n2.mid = 1513054203170 and c2.ord  in (0)' and got (1504215231180, 1504215235035, 1504215250272, 1504215257078, 1504215262623, 1504215282698, 1587504599134, 1587504617281)
2020-04-21 16:31:10.746 7802-7802/com.ichi2.anki D/Models: getCardIdsForModel found 8 cards to delete for model 1513054203170 and ords (0)
2020-04-21 16:31:10.751 7802-7802/com.ichi2.anki D/Models: noteCountPreDeleteSql was 'select count() from notes where mid = 1513054203170'
2020-04-21 16:31:10.751 7802-7802/com.ichi2.anki D/Models: preDeleteNoteCount is 8
2020-04-21 16:31:10.751 7802-7802/com.ichi2.anki D/Models: noteCountPostDeleteSql was 'select count(n.id) from cards c, notes n where c.nid=n.id and n.mid = 1513054203170 and c.id not in (select c2.id from cards c2, notes n2 where c2.nid=n2.id and n2.mid = 1513054203170 and c2.ord  in (0))'
2020-04-21 16:31:10.769 7802-7802/com.ichi2.anki D/Models: postDeleteNoteCount would be 1
2020-04-21 16:31:10.769 7802-7802/com.ichi2.anki D/Models: There will be orphan notes if these cards are deleted.
```

I can't make it fail any more in testing so I'm going to clean up the commit history here then likely merge it unless I hear it's terrible for some reason (hopefully not!). Cheers

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.java  2
- AnkiDroid/src/test/java/com/ichi2/anki/TemporaryModelTest.java  4
- AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  9
- AnkiDroid/src/test/java/com/ichi2/anki/NonPagingCardTemplateEditor.java  1
- AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java  8
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java  6
         

Clones added
============
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688&bid=10073006)

File: AnkiDroid/src/main/java/com/ichi2/libanki/Models.java [hunk 39]
```diff
@@ -771,7 +772,53 @@ public boolean remTemplate(JSONObject m, JSONObject template) throws ConfirmModS
...
 
-    public void _updateTemplOrds(JSONObject m) {
+    /**
+     * Easily test if removing one or more templates is safe without actually removing them
+     * Verifies all notes with these templates have at least two cards, to guard against creating orphaned notes
+     * @return false if not safe, true if it is safe
+     */
+    public boolean isRemTemplatesSafe(long modelId, int[] ords) {
+        // to make sure the compound effect of all the pending deletes is taken into account?
+        if (getCardIdsForModel(modelId, ords) == null) {
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Models.java:782]: Codacy Issue found: [Avoid unnecessary if..then..else statements when returning booleans](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688)

File: AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java [hunk 40]
```diff
@@ -0,0 +1,404 @@
...
```
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java:258]: Codacy Issue found: [Avoid really long methods.](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  9
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.java  2
- AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java  8
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java  6
- AnkiDroid/src/test/java/com/ichi2/anki/TemporaryModelTest.java  4
- AnkiDroid/src/test/java/com/ichi2/anki/NonPagingCardTemplateEditor.java  1
         

Clones added
============
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688&bid=10073006)

File: AnkiDroid/src/main/java/com/ichi2/libanki/Models.java [hunk 41]
```diff
@@ -22,6 +22,9 @@
 import android.content.ContentValues;
 import android.database.Cursor;
 import android.util.Pair;
+import androidx.annotation.Nullable;
+import androidx.annotation.VisibleForTesting;
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Models.java:26]: Codacy Issue found: [Avoid unused imports such as 'androidx.annotation.VisibleForTesting'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688)

**Comment by mikehardy** [comment]
@david-allison-1 I just flagged you to check this out as well. It's a bit gnarly but I can say at least that I can't make it fail anymore. Only 15 months after starting on this one perhaps we can merge it in, it's the last deck corruption issue I'm aware of so I'd like to get it in 2.10

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 42]
```diff
@@ -151,7 +151,7 @@
     public static final int EASE_4 = 4;
 
     /** Maximum time in milliseconds to wait before accepting answer button presses. */
-    private static final int DOUBLE_TAP_IGNORE_THRESHOLD = 200;
+    protected static final int DOUBLE_TAP_IGNORE_THRESHOLD = 200;
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:154]: Can we flag these as `@VisibleForTesting` if they're only changed to allow access from unit tests

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/NonPagingCardTemplateEditor.java  1
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java  6
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  9
- AnkiDroid/src/test/java/com/ichi2/anki/TemporaryModelTest.java  4
- AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java  8
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.java  2
- AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java  1
         

Clones added
============
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688&bid=10073006)

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java (hunk 42 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:154]: Yes - I wasn't even aware of that trick in 2018 when I started this odyssey :rofl: - it was my first foray into *all* of it (android, robolectric, annotations etc etc). I'll wait though and "listen" for any other feedback so I can get it on swell foop

File: AnkiDroid/src/main/java/com/ichi2/libanki/Models.java (hunk 38 above)
Comment (dae) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Models.java:800]: I believe that fixme sql may count the same note id multiple times if multiple ordinals are deleted - is that what you intended?

This approach feels a bit difficult to reason about, and I worry that orphaned notes may slip through. I am thinking of changing the way Anki handles this case, and it may be an approach you wish to take as well. Instead of attempting to detect and abort in this case, we just need to ensure at the end of the operation that all notes have at least one card. You could accomplish this by adding a card with ord 0 to any notes that have been left cardless, since we guarantee there will always be at least one template. The card would appear empty during review, and the user can decide whether they want to adjust the template, add extra content to the note so it's no longer empty, or remove the notes with the Empty Cards routine.

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Models.java:800]: @dae so if the possible future approach were taken, there would basically be two passes "just delete without worrying about it" then a "generate cards" step which essentially preened the collection and for notes without cards generated empty-field cards for ord 0?

That would certainly reduce the complexity in this area a lot, and make the collection in general a bit more self-healing by design. I think the above approach works (assuming the SQL is good) but if you switched to that approach I'd happily migrate to it in a follow-on

@david-allison-1 it is too complex and I'm not 100% on my proposed SQL yet, so I would welcome improvement. I'll work through your suggestion and see if it is better

Thank you both for the attention!

File: AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java [hunk 43]
```diff
@@ -0,0 +1,395 @@
...
+    /**
+     * Get the model temporarily saved into the file represented by the given path
+     * @return JSONObject holding the model, or null if there was a problem
+     */
+    public static @Nullable JSONObject getTempModel(@NonNull String tempModelFileName) {
+        Timber.d("getTempModel() fetching tempModel %s", tempModelFileName);
+        try (ByteArrayOutputStream target = new ByteArrayOutputStream()) {
+            CompatHelper.getCompat().copyFile(tempModelFileName, target);
+            return new JSONObject(target.toString());
+        } catch (IOException | JSONException e) {
```
[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java:188]: agreed, thanks

File: AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java [hunk 44]
```diff
@@ -0,0 +1,395 @@
...
+
+
+@SuppressWarnings({"PMD.AvoidThrowingRawExceptionTypes"})
+public class TemporaryModel {
+
+    public enum ChangeType { ADD, DELETE }
+    public static final String INTENT_MODEL_FILENAME = "editedModelFilename";
+    private ArrayList<Object[]> mTemplateChanges = new ArrayList<>();
+    private String mEditedModelFileName = null;
+    private JSONObject mEditedModel;
```
[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java:48]: agreed, thanks

File: AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java [hunk 45]
```diff
@@ -0,0 +1,395 @@
...
+                // Is previous change a delete? Lower ordinal than current change?
+                if ((previousChange[1] == ChangeType.DELETE) && ((int)previousChange[0] <= (int)currentChange[0])) {
+                    // If so, that is the case where things shift. It means our ordinals moved and original ord is higher
+                    ordinalAdjustment++;
+                }
+            }
+
+            // We know how many times ordinals smaller than the current were deleted so we have the total adjustment
+            // Save this pending delete into an expanded array at it's original / db-relative position
+            deletedDbOrds = Arrays.copyOf(deletedDbOrds, deletedDbOrds.length + 1);
```
[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java:331]: Meaning, the return signature of the method, and all internals should work with non-primitives? the ordinal is an int and that would mean lots of unboxing/boxing which to me is less clear?

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java (hunk 42 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:154]: done will commit shortly

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java [hunk 46]
```diff
@@ -249,21 +243,28 @@ public void onPageScrollStateChanged(final int position) { /* do nothing */ }
     }
 
     public boolean modelHasChanged() {
-        JSONObject newModel = getCol().getModels().get(mModelId);
-        return mModelBackup != null && !mModelBackup.toString().equals(newModel.toString());
+        JSONObject oldModel = getCol().getModels().get(mModelId);
```
[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java:246]: agreed, thank you

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java [hunk 47]
```diff
@@ -249,21 +243,28 @@ public void onPageScrollStateChanged(final int position) { /* do nothing */ }
...
+    @VisibleForTesting
+    public MaterialDialog showDiscardChangesDialog() {
+        MaterialDialog discardDialog = DiscardChangesDialog.getDefault(this)
                 .onPositive((dialog, which) -> {
                     Timber.i("TemplateEditor:: OK button pressed to confirm discard changes");
-                    getCol().getModels().update(CardTemplateEditor.this.mModelBackup);
-                    getCol().getModels().flush();
-                    getCol().reset();
+                    // Clear the edited model from any cache files, and clear it from this objects memory to discard changes
+                    TemporaryModel.clearTempModelFiles();
```
[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java:261]: That would be an upstream MaterialDialog thing for double-tap protection on the dialog, or android system UI for the menu item. I checked TemporaryModel.clearTempModelFiles and made sure it was idempotent on this method without throwing thought. Seems fine? It is actually self-healing (it will clean up old orphaned edited models in case the app was killed during a previous edit)

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java [hunk 48]
```diff
@@ -291,12 +292,18 @@ public void selectTemplate(int idx) {
     // INNER CLASSES
     // ----------------------------------------------------------------------------
 
+    // Testing Android apps is hard, and pager adapters in fragments is nearly impossible.
+    // In order to make this object testable we have to allow for some plumbing pass through
+    protected TemplatePagerAdapter getNewTemplatePagerAdapter(FragmentManager fm) {
```
[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java:297]: agreed, thanks

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java [hunk 49]
```diff
@@ -323,180 +330,185 @@ public long getItemId(int position) {
...
-                mCss.addTextChangedListener(templateEditorWatcher);
-                mBack.addTextChangedListener(templateEditorWatcher);
-                // Enable menu
-                setHasOptionsMenu(true);
-            } catch (JSONException e) {
-                throw new RuntimeException(e);
-            }
+            TemporaryModel tempModel = mTemplateEditor.getTempModel();
+            // Load template
+            final JSONObject template = mTemplateEditor.getTempModel().getTemplate(position);
```
[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java:379]: just testing that you were paying attention of course, you passed! 🤦

File: AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java (hunk 45 above)
[the remark this answers is not in the document]
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java:331]: Definitely no gain from impacting the external signature. Sorry for the lack of clarity.

I'd have only said internally. Convert to an array when finished in the loop. 

Comment was more for code clarity and correctness than performance (we're definitely not on the hot path here), but changing to an ArrayList would perform `log(n)` vs `n` array copies, and would likely be faster, even with the unboxing overhead.

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java [hunk 50]
```diff
@@ -323,180 +330,185 @@ public long getItemId(int position) {
...
                     Timber.i("CardTemplateEditor:: Delete template button pressed");
                     Resources res = getResources();
                     int position = getArguments().getInt("position");
-                    JSONArray tmpls = model.getJSONArray("tmpls");
-                    final JSONObject template = tmpls.getJSONObject(position);
+                    final JSONObject template = tempModel.getTemplate(position);
                     // Don't do anything if only one template
-                    if (tmpls.length() < 2) {
-                        UIUtils.showThemedToast(getActivity(), res.getString(R.string.card_template_editor_cant_delete), false);
+                    if (tempModel.getTemplateCount() < 2) {
```
[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java:456]: "blocked in the UI", honestly I don't like that they are toasts. This feels more dialog-y to me. What do you think of a conversion to Dialog?

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java [hunk 51]
```diff
@@ -323,180 +330,185 @@ public long getItemId(int position) {
...
+                        UIUtils.showThemedToast(mTemplateEditor, res.getString(R.string.card_template_editor_cant_delete), false);
                         return true;
                     }
+
+                    // For existing templates, make sure we won't leave orphaned notes if we delete the template
+                    //
+                    // Note: we are in-memory, so the database is unaware of previous but unsaved deletes.
+                    // If it we were deleting a template we just added, we don't care. If not, then for every
```
[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java:464]: I write good

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java (hunk 50 above)
[the remark this answers is not in the document]
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java:456]: Ideally disabling the UI element so the code path won't happen if there's only 1 template.

As per dialog/toast, I don't intend to bikeshed. Whichever you prefer.

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java [hunk 52]
```diff
@@ -323,180 +330,185 @@ public long getItemId(int position) {
...
+                    // template delete queued up, we check the database to see if this delete in combo with any other
+                    // pending deletes could orphan cards
+                    if (!tempModel.isTemplatePendingAdd(position)) {
+                        int[] currentDeletes = tempModel.getDeleteDbOrds(position);
+                        // TODO - this is a SQL query on GUI thread - should see a DeckTask conversion ideally
+                        if (col.getModels().getCardIdsForModel(tempModel.getModelId(), currentDeletes) == null) {
```
[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java:470]: legibility in CardTemplateEditor? Are you insane man?!?
(agreed, extracted)

File: AnkiDroid/src/main/java/com/ichi2/libanki/Models.java [hunk 53]
```diff
@@ -771,7 +772,39 @@ public boolean remTemplate(JSONObject m, JSONObject template) throws ConfirmModS
     }
 
 
-    public void _updateTemplOrds(JSONObject m) {
+    /**
+     * Extracted from remTemplate so we can test if removing templates is safe without actually removing them
+     * Verifies all notes with these templates have at least two cards, to guard against creating orphaned notes
+     * @return null if not safe, long[] of card ids to delete if it is safe
+     */
+    public @Nullable long[] getCardIdsForModel(long modelId, int[] ords) {
```
[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Models.java:780]: whole javadoc needed some ❤️

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java (hunk 50 above)
[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java:456]: I am going to switch these to dialogs then. They are such hard stops and the message is so important in order to successfully continue I think a dialog fits better. But I better understand your intention now so if there are less than 2 templates I'll set the menu item to invisible as well so it's simply not possible

File: AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java [hunk 54]
```diff
@@ -1391,14 +1393,52 @@ private TaskData doInBackgroundRemoveTemplate(TaskData... params) {
...
      */
     private TaskData doInBackgroundSaveModel(TaskData... params) {
         Timber.d("doInBackgroundSaveModel");
         Collection col = CollectionHelper.getInstance().getCol(mContext);
         Object [] args = params[0].getObjArray();
         JSONObject model = (JSONObject) args[0];
+        ArrayList<Object[]> templateChanges = (ArrayList<Object[]>)args[1];
+        JSONObject  oldModel = col.getModels().get(model.getLong("id"));
+
+        // TODO need to save all the cards that will go away, for undo
```
[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java:1406]: Yep - just to note that there was no undo functionality prior so it was out of scope so I'm definitely not going there now. First just to get this re-shaping in so we stop corrupting databases or overflowing Bundle space on large template edits etc...

File: AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java [hunk 55]
```diff
@@ -832,6 +832,13 @@ private Card _newCard(Note note, JSONObject template, int due, boolean flush) {
 
     private Card _newCard(Note note, JSONObject template, int due, int parameterDid, boolean flush) {
         Card card = new Card(this);
+        return getNewLinkedCard(card, note, template, due, parameterDid, flush);
+    }
+
+    // This contains the original libanki implementation of _newCard, with the added parameter that
+    // you pass the Card object in. This allows you to work on 'Card' subclasses that may not have
+    // actual backing store (for instance, if you are previewing unsaved changes on templates)
+    public Card getNewLinkedCard(Card card, Note note, JSONObject template, int due, int parameterDid, boolean flush) {
```
[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java:841]: agreed, done

File: AnkiDroid/src/main/java/com/ichi2/libanki/Models.java (hunk 38 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Models.java:800]: @david-allison-1 your SQL is a clearer expression of the intent and appears to work vs existing test harness, I'm going to put it in. May do a follow-on PR with alternate strategy from Damien pending his thoughts on whether he is really going to alter Anki upstream to do that

File: AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java (hunk 45 above)
[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java:331]: ok - pushing this in a moment

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java [hunk 56]
```diff
@@ -38,23 +41,20 @@
 import android.view.inputmethod.InputMethodManager;
 import android.widget.EditText;
 
+import com.afollestad.materialdialogs.MaterialDialog;
 import com.ichi2.anim.ActivityTransitionAnimation;
 import com.ichi2.anki.dialogs.ConfirmationDialog;
 import com.ichi2.anki.dialogs.DiscardChangesDialog;
+import com.ichi2.anki.dialogs.SimpleMessageDialog;
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java:48]: Codacy Issue found: [Avoid unused imports such as 'com.ichi2.anki.dialogs.SimpleMessageDialog'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.java  2
- AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  9
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java  6
- AnkiDroid/src/test/java/com/ichi2/anki/NonPagingCardTemplateEditor.java  1
- AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java  8
- AnkiDroid/src/test/java/com/ichi2/anki/TemporaryModelTest.java  4
         

Complexity decreasing per file
==============================
+ AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java  -1
         

Clones added
============
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688&bid=10073006)

**Comment by mikehardy** [comment]
>     * I add a card type and two are created.
>     * I add again, another 2 are created.

Dang, that all used to work of course. It was an artifact of the refactor to TemporaryModel from a few months ago in combination with not enough assertions on execution state in the tests

I added assertions on template count which quickly reproduced it, and eliminated the double-addition that was corrupting state.

Looks like it works now for me, latest push.

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.java  2
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  9
- AnkiDroid/src/test/java/com/ichi2/anki/TemporaryModelTest.java  4
- AnkiDroid/src/test/java/com/ichi2/anki/NonPagingCardTemplateEditor.java  1
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java  6
- AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java  8
- AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java  1
         

Complexity decreasing per file
==============================
+ AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java  -1
         

Clones added
============
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688&bid=10073006)

**Comment by david-allison-1** [comment]
Minor UI quibble: the dividing line between `Styling` and `Back template` should be outside the scrolling box for `Styling`

File: AnkiDroid/src/main/java/com/ichi2/libanki/Models.java (hunk 38 above)
Comment (timrae) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Models.java:803]: Is it necessary for it to go upstream in order to implement in AnkiDroid? We're already diverging significantly from upstream here.

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Models.java:803]: @timrae for me yes, this code changes SQL queries and some interfaces, but preserves behavior as close as possible with existing ecosystem. Allowing templates to orphan notes then creating dummy notes is different behavior. That's a separate line to cross for me. I foresee lower support load (allowing assumption code here is correct) because this PR fixes a few bugs some of which result in collection corruption. If I changed behavior vs ecosystem I foresee a steady trickle of "why is it doing that" support issues. I like the idea of the change but I'd like to wait until it would be ecosystem consistent

**Comment by mikehardy** [comment]
Great - thanks for the feedback - yes it's a dummy card all the time now but that's easy to fix and even dovetails with work on #5705 - I'll get that shortly

The crash is an "of course! :facepalm: " realization. I'll see what I can do there and let you know when it's ready for re-test

Thanks again for working through this with me

**Comment by mikehardy** [comment]
@david-allison-1 I can't reproduce your crash, I'd love to see the logcat of it next time if you can. The code is pretty chatty in the logs right now and that would help pinpoint it. I'm looking at transaction stuff now regardless...

**Comment by david-allison-1** [comment]
> @david-allison-1 I can't reproduce your crash, I'd love to see the logcat of it next time if you can. The code is pretty chatty in the logs right now and that would help pinpoint it. I'm looking at transaction stuff now regardless...

I was getting multiple different crashes. Will send over a logcat in 20

**Comment by mikehardy** [comment]
w.r.t 
> The UI is still operational when saving

That isn't a regression at least. I didn't change the code there so it's likely possible in 2.9.6?

The code does

```java
                final InputMethodManager imm = (InputMethodManager) mTemplateEditor.getSystemService(Context.INPUT_METHOD_SERVICE);
                imm.hideSoftInputFromWindow(getView().getWindowToken(), 0);

```

So the UI should not be operational until the AsyncTask returns and postExecute calls finish on the activity. Or did you do a hardware back button? Exact steps to reproduce would help

**Comment by david-allison-1** [comment]
Very likely that it's also a bug in 2.9.6, I haven't looked too much into the template editor before as I knew you were fixing.

Haven't been able to replicate that exact crash. Will send in an email due to the size.

I'm using the software "back" button to cause these issues, not the system "back" button

**Comment by david-allison-1** [comment]
> ```java
> imm.hideSoftInputFromWindow(getView().getWindowToken(), 0);
> ```

Isn't this just hiding the soft keyboard? Not disabling the UI

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java  8
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  9
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.java  2
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java  6
- AnkiDroid/src/test/java/com/ichi2/anki/TemporaryModelTest.java  4
- AnkiDroid/src/test/java/com/ichi2/anki/NonPagingCardTemplateEditor.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java  1
         

Complexity decreasing per file
==============================
+ AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java  -1
         

Clones added
============
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688&bid=10073006)

**Comment by mikehardy** [comment]
Yeah, so that was a complete mess but in a productive way. 

Your prompt about transactions led to a discovery there was a collision between the work here from eons ago and the more recent #5590 work. I wasn't handling the new style well at all so multiple things were failing, and quietly to boot. I added transactions and much better error handling.

And I was easily able to reproduce what you saw when I worked with a larger / less responsive collection. The UI was not blocked sufficiently and hitting the back button was a disaster yes. So I switched it to be more like the sync dialog - I pop a non-cancellable modal now and we should avert that disaster.

Pushed in little commits so you can see it, and I think it's ready again? 😓

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  9
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.java  2
- AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/NonPagingCardTemplateEditor.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/TemporaryModelTest.java  4
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java  6
- AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java  8
         

Complexity decreasing per file
==============================
+ AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java  -1
         

Clones added
============
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688&bid=10073006)

**Comment by mikehardy** [comment]
Still intending to plumb through card-under-edit contents for preview but want to get verification it's not a crash test dummy any more in parallel

File: AnkiDroid/src/main/java/com/ichi2/libanki/Models.java [hunk 57]
```diff
@@ -771,7 +772,42 @@ public boolean remTemplate(JSONObject m, JSONObject template) throws ConfirmModS
...
+    /**
+     * Extracted from remTemplate so we can test if removing templates is safe without actually removing them
+     * This method will either give you all the card ids for the ordinals sent in related to the model sent in *or*
+     * it will return null if the result of deleting the ordinals is unsafe because it would leave notes with no cards
+     *
+     * @param modelId long id of the JSON model
+     * @param ords array of ints, each one is the ordinal a the card template in the given model
+     * @return null if deleting ords would orphan notes, long[] of related card ids to delete if it is safe
+     */
+    public @Nullable long[] getCardIdsForModel(long modelId, int[] ords) {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Models.java:784]: Could we add another test case here:

* Card 1 with notes
* Add Card 2 (default ({{Back}} on front behaviour, no conditionals)
* Save and exit
* Edit Card Templates
* Delete Card 1
* Error message stating can't delete due to orphaned notes (although none should be orpahned)

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java [hunk 58]
```diff
@@ -323,180 +287,174 @@ public long getItemId(int position) {
...
                 }
                 case R.id.action_preview: {
                     Timber.i("CardTemplateEditor:: Preview model button pressed");
-                    // Save the model if necessary
-                    if (modelHasChanged()) {
-                        col.getModels().save(model, false);
-                    }
                     // Create intent for the previewer and add some arguments
-                    Intent i = new Intent(getActivity(), Previewer.class);
+                    Intent i = new Intent(mTemplateEditor, CardTemplatePreviewer.class);
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java:436]: Needs double tap protection, creates duplicates with the same name, also nonfatal error in logcat

<details>

```
2020-04-24 10:46:43.580 10092-10092/com.ichi2.anki D/NoteEditor: onActivityResult() with request/result: 3/0
2020-04-24 10:46:43.833 10092-10782/com.ichi2.anki W/CursorWindow: Window is full: requested allocation 96 bytes, free space 40 bytes, window size 2097152 bytes
2020-04-24 10:46:44.463 10092-10104/com.ichi2.anki I/com.ichi2.anki: NativeAlloc concurrent copying GC freed 333535(7MB) AllocSpace objects, 11(1536KB) LOS objects, 49% free, 13MB/26MB, paused 172us total 160.104ms
2020-04-24 10:46:44.606 10092-10782/com.ichi2.anki D/Collection: [1587721604] Sched.java:_updateCutoff(): 2384,  1587787200
2020-04-24 10:46:44.645 10092-10782/com.ichi2.anki I/Collection: flush - Saving information to DB...
2020-04-24 10:46:44.676 10092-10092/com.ichi2.anki D/NoteEditor: onActivityResult() template edit return - current card exists
2020-04-24 10:46:44.678 10092-10092/com.ichi2.anki D/NoteEditor: updateCards()
2020-04-24 10:46:44.680 10092-10092/com.ichi2.anki D/NoteEditor: updateCards() template count is 5
2020-04-24 10:46:44.682 10092-10092/com.ichi2.anki D/Note: load()
2020-04-24 10:46:44.702 10092-10092/com.ichi2.anki D/UsageAnalytics: sendAnalyticsScreenView(): NoteEditor
2020-04-24 10:46:44.703 10092-10092/com.ichi2.anki D/UsageAnalytics: getOptIn() status: false
2020-04-24 10:46:44.704 10092-10092/com.ichi2.anki D/DialogHandler: Reading persistent message
2020-04-24 10:46:44.708 10092-10092/com.ichi2.anki I/Choreographer: Skipped 67 frames!  The application may be doing too much work on its main thread.
2020-04-24 10:46:44.727 10092-10433/com.ichi2.anki D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
2020-04-24 10:46:44.730 10092-10092/com.ichi2.anki D/CollectionTask: enabling garbage collection of mPreviousTask...
2020-04-24 10:46:44.755 10092-10092/com.ichi2.anki I/ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time
2020-04-24 10:46:44.759 10092-10092/com.ichi2.anki W/InputMethodManager: startInputReason = 1
2020-04-24 10:46:44.820 10092-10433/com.ichi2.anki W/libEGL: EGLNativeWindowType 0x760de22010 disconnect failed
2020-04-24 10:46:44.834 10092-10433/com.ichi2.anki W/libEGL: EGLNativeWindowType 0x760e14a010 disconnect failed
2020-04-24 10:46:44.856 10092-10092/com.ichi2.anki D/ViewRootImpl[CardTemplateEditor]: surface should not be released
2020-04-24 10:46:44.873 10092-10092/com.ichi2.anki D/ActivityThread: Remove activity client record, r= ActivityRecord{67bc302 token=android.os.BinderProxy@6af4033 {com.ichi2.anki/com.ichi2.anki.CardTemplateEditor}} token= android.os.BinderProxy@6af4033
2020-04-24 10:46:44.892 10092-10092/com.ichi2.anki E/WindowManager: android.view.WindowLeaked: Activity com.ichi2.anki.CardTemplateEditor has leaked window DecorView@14223d5[CardTemplateEditor] that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:627)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:389)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:131)
        at android.app.Dialog.show(Dialog.java:531)
        at com.afollestad.materialdialogs.MaterialDialog.show(MaterialDialog.java:464)
        at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:2189)
        at com.ichi2.themes.StyledProgressDialog.show(StyledProgressDialog.java:72)
        at com.ichi2.themes.StyledProgressDialog.show(StyledProgressDialog.java:60)
        at com.ichi2.anki.CardTemplateEditor$CardTemplateFragment$2.onPreExecute(CardTemplateEditor.java:501)
        at com.ichi2.async.CollectionTask$TaskListener.onPreExecute(CollectionTask.java:1697)
        at com.ichi2.async.CollectionTask.onPreExecute(CollectionTask.java:369)
        at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:649)
        at android.os.AsyncTask.execute(AsyncTask.java:596)
        at com.ichi2.async.CollectionTask.launchCollectionTask(CollectionTask.java:146)
        at com.ichi2.anki.TemporaryModel.saveToDatabase(TemporaryModel.java:137)
        at com.ichi2.anki.CardTemplateEditor$CardTemplateFragment.onOptionsItemSelected(CardTemplateEditor.java:454)
        at androidx.fragment.app.Fragment.performOptionsItemSelected(Fragment.java:2733)
        at androidx.fragment.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManagerImpl.java:2758)
        at androidx.fragment.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:411)
        at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:390)
        at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:228)
        at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:64)
        at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
        at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:779)
        at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
        at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:975)
        at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:623)
        at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
        at android.view.View.performClick(View.java:6659)
        at android.view.View.performClickInternal(View.java:6631)
        at android.view.View.access$3100(View.java:790)
        at android.view.View$PerformClick.run(View.java:26187)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

</details>

File: AnkiDroid/src/main/java/com/ichi2/libanki/Models.java (hunk 57 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Models.java:784]: Great suggestion on the extra test focusing completely on deletes. Found a subtle but critical SQL error in note deletion, meaning cards were not being deleted correctly - it was not successfully executing the SQL that shifted the ordinals in the database, which would make it appear (over time in non-ephemeral/non-robolectric-in-memory collections) that you had cards attached to ordinals they should not have been.

So I could not reproduce your exact problem, but it was definitely not correctly deleting, and the test showed that.

I can't reproduce any problems in this area anymore by actual clicking or with the new test

Pushing that in next batch

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java (hunk 58 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java:436]: `mTemplateEditor.findViewById(R.id.action_confirm).setEnabled(false);` before doing work now, tested -> working

And oh *man* that hoses up a database good when you successfully reproduce that one. Pointed a bystander bug hiding under the rug with regard to which templates were being selected in the pager though, which is nice.

**Comment by mikehardy** [comment]
> I think this'll be the last one.
> 
> * It feels a lot faster to add and delete cards in this one, I'm not sure if that implies an issue.

I dunno - it's definitely adding and removing cards. In fact with the logcat spew logging the card ids via Timber.d it was somewhat slow but I stopped that, so it should be even faster?

> * Issue with either card generation, or note orphan checking (or you just can't delete ord 0).

I think this was built-up corruption from failure to ordinal shift on remaining cards after delete

> * Requires double-tap protection on commit.

Oh my yes

Still haven't fixed your divider-in-wrong-spot comment, or plumbed through ephemeral NoteEditor data to CardTemplatePreviewer but correctness before UI stuff and this took longer than I was expecting. Such a complicated UI and data model oof

Pushing these changes now

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java  6
- AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java  8
- AnkiDroid/src/test/java/com/ichi2/anki/NonPagingCardTemplateEditor.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.java  2
- AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/TemporaryModelTest.java  4
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  4
         

Clones added
============
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688&bid=10073006)

**Comment by david-allison-1** [comment]
Let's not bother with the Vertical Line in this PR, I had a quick look. It'll be more complex and time consuming than it's worth, this PR doesn't touch that part of the UI, and it's much better to focus on correctness of functionality

File: AnkiDroid/src/main/java/com/ichi2/libanki/Models.java (hunk 57 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Models.java:787]: This doesn't appear to be resolved.

* Basic Note type: 1 card template
* Add Card 2 and Card 3
* Save and Exit
* Edit 
* Delete Card 1 
* Can't be deleted

**Comment by mikehardy** [comment]
Can you verify that all those reports came after doing an overwrite sync? The previous testing definitely corrupted things and while I haven't tested app kill during background task, I can't reproduce add/delete cycle failures anymore

**Comment by david-allison-1** [comment]
> Can you verify that all those reports came after doing an overwrite sync? The previous testing definitely corrupted things and while I haven't tested app kill during background task, I can't reproduce add/delete cycle failures anymore

The corruption was under a new collection from a backup of my primary collection in the `/AnkiDroid` directory. I'll reconfirm the toast error.

**Comment by david-allison-1** [comment]
Replicated the toast bug as well under the new collection.

**Comment by mikehardy** [comment]
> Could you see a strategy in either adding more tests, or modifying the existing tests to ensure that we won't get regressions in this area of the code?

My general strategy is when a bug shows up I add a test to poke it so I have it under the scope, then I fix the bug to make the test pass.

And in areas like this where things are really fiddly I sometimes go one step farther and try to right a state-dumping test method that exposes as much of the internal state as possible, then a state comparison method that I assert on in the test. e.g. TemporaryModelTest.assertTemplateChangesEqual

This area might need that sort of inspection. Might be the best way to keep straight all the view layers wedged in (Activity, SlidingTabLayout, ViewPager, Fragment etc, with their own awful hacks) along with the template as it is persisted in the collection, in the temp file, and as it lives in memory. I don't feel like it's off the rails but it shouldn't go through 3 rounds of "crashed it easily" testing

**Comment by mikehardy** [comment]
Ironically, all the robolectric and database swapping infrastructure was put in specifically so I could do the tests to support the fiddly-ness in this area. I was terrified of touching it without test support given how nasty it is!

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java [hunk 59]
```diff
@@ -602,7 +605,10 @@ private void addNewTemplateWithCheck(final JSONObject model) {
             } catch (ConfirmModSchemaException e) {
                 ConfirmationDialog d = new ConfirmationDialog();
                 d.setArgs(getResources().getString(R.string.full_sync_confirmation));
-                Runnable confirm = () -> addNewTemplate(model);
+                Runnable confirm = () -> {
+                    mTemplateEditor.getCol().modSchemaNoCheck();
```
[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java:621]: I did not look deeply into it yet but I have also put this in the back of my mind. I believe (needs verification) that if a collection has never been synced that these ConfirmModSchemaExceptions will not be thrown ever when you call Collection.modSchema, which means that for automated testing purposes if you want to test those branches you need to somehow tell Collection to behave like it is in sync currently so it'll throw them

This is something that simply inspecting the results of unit test coverage should have shown me as well - last couple rounds I have not looked closely - had I done so I would have seen I wasn't hitting both sides of that branch and as it's important I would have checked

File: AnkiDroid/src/main/java/com/ichi2/libanki/Models.java (hunk 57 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Models.java:787]: Can't reproduce this anymore with current changes pushing in a moment

File: AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java [hunk 60]
```diff
@@ -0,0 +1,444 @@
...
+        Assert.assertNotNull("Cannot delete template?", getCol().getModels().getCardIdsForModel(collectionBasicModelOriginal.getLong("id"), new int[] {1}));
+        Assert.assertNull("Can delete both templates?", getCol().getModels().getCardIdsForModel(collectionBasicModelOriginal.getLong("id"), new int[] {0, 1}));
+    }
+
+
+    /**
+     * Normal template deletion - with no selective generation should of course work
+     */
+    @Test
+    public void testDeleteTemplateWithGeneratedCards() {
```
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java:327]: Codacy Issue found: [Avoid really long methods.](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/TemporaryModelTest.java  4
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  2
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java  7
- AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/NonPagingCardTemplateEditor.java  1
- AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java  8
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.java  2
         

Clones added
============
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688&bid=10073006)

File: AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java [hunk 61]
```diff
@@ -0,0 +1,444 @@
...
+import org.robolectric.Robolectric;
+import org.robolectric.android.controller.ActivityController;
+import org.robolectric.annotation.LooperMode;
+import org.robolectric.shadows.ShadowActivity;
+import org.robolectric.shadows.ShadowIntent;
+
+import com.ichi2.libanki.Note;
+import com.ichi2.utils.JSONObject;
+
+import java.util.ArrayList;
```
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java:39]: Codacy Issue found: [Avoid unused imports such as 'java.util.ArrayList'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688)

**Comment by mikehardy** [comment]
There was still a fundamental problem that your scenario exposed and had luckily (for it's existence) hidden just on the periphery of the unit tests I had already - I had quite a few combinations of adds/deletes but until now all of the additions in the tests were not followed by deletes that weren't set to cancel out an add, so I had no add-followed-by-delete combos going through the save logic.

Adding that in exposed a confusion in the save logic between indices in the change list vs ordinals, so I added a couple tests that poked it, fixed the logic + added a bunch more logging then added a pile more assertions in the tests to more strictly verify internal state.

I can't make it crash anymore and everything in the transcript from Timber reads correctly. May still be missing a case but it's not just moving issues around, the test library against it is only growing...

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/TemporaryModelTest.java  4
- AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.java  2
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  2
- AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/NonPagingCardTemplateEditor.java  1
- AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java  8
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java  7
         

Clones added
============
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688&bid=10073006)

File: AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java [hunk 62]
```diff
@@ -0,0 +1,444 @@
...
+        Assert.assertNull("Can delete both templates?", getCol().getModels().getCardIdsForModel(collectionBasicModelOriginal.getLong("id"), new int[] {0, 1}));
+    }
+
+
+    /**
+     * Normal template deletion - with no selective generation should of course work
+     */
+    @SuppressLint("PMD.ExcessiveMethodLength")
+    @Test
+    public void testDeleteTemplateWithGeneratedCards() {
```
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java:327]: Codacy Issue found: [Avoid really long methods.](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/NonPagingCardTemplateEditor.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.java  2
- AnkiDroid/src/test/java/com/ichi2/anki/TemporaryModelTest.java  4
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java  7
- AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java  8
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  2
         

Clones added
============
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688&bid=10073006)

**Comment by mikehardy** [comment]
Preview of unsaved NoteEditor changes, as they go through CardTemplateEditor is implemented as part of #6063 (which is based on this PR and I just updated to the current state here)

So assuming this doesn't crash, and preview of note edits is handled there (or will be, after review) - there should be no outstanding issues with this. But not crashing or corrupting is of course the big one.

**Comment by mikehardy** [comment]
Strange, I know I performed that sequence (Add/Add/Save/Delete/Delete/Save/Browser) on both small note-generating and large note-generating models. But I'll check it out of course

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java [hunk 63]
```diff
@@ -451,6 +451,10 @@ public boolean onOptionsItemSelected(MenuItem item) {
                 case R.id.action_confirm:
                     Timber.i("CardTemplateEditor:: Save model button pressed");
                     if (modelHasChanged()) {
+                        View confirmButton = mTemplateEditor.findViewById(R.id.action_confirm);
+                        if (confirmButton != null) {
+                            confirmButton.setEnabled(false);
```
[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java:456]: Unversioned unmaintained dependency? I won't even consider that.
A click time one or even just a counter or something would be fine for now. Should generalize later but if I'm worrying about double-clicks in code that never protected against double-clicks but did corrupt, I'm going to focus more on the corruption

**Comment by mikehardy** [comment]
Still looking at the other nits but I extended the test case to process multiple deletes of existing templates at the same time, which exposed the problem you saw, then I fixed it. Nothing complex this time the last commit shows it

Bonus is that robolectric support for template paging appears to have matured. I was able to remove an entire testing hack to workaround previously poor paging

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java  8
- AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  2
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.java  2
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java  7
- AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/TemporaryModelTest.java  4
         

Clones added
============
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688&bid=10073006)

File: AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java [hunk 64]
```diff
@@ -352,6 +399,38 @@ private void dumpChanges() {
...
+        // In order to save the changes into the database, the ordinals in the changelist must correspond to the
+        // ordinals in the database (for deletes) or the correct index in the changes array (for adds)
+        // It is not possible to know what those will be until the user requests a save, so they are stored in the
+        // change list as-is until the save time comes, then the adjustment is made all at once
+        for (int i = 0; i < changes.size(); i++) {
+            Object[] change = changes.get(i);
+            Object[] adjustedChange = {change[0], change[1]};
+            switch ((ChangeType)adjustedChange[1]) {
+                case ADD:
+                    adjustedChange[0] = TemporaryModel.isChangePendingAdd(this, i);
```
[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java:421]: The names were very specifically changed to match functionality. isChangePendingAdd checks the internal changelist at that position to see if it is a pending (and thus maybe compactable) template addition, isOrdinalPendingAdd does similar but from the UI's sliding tab layout ordinal perspective. So I may be misreading but on my read I disagree and see no action

[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java:421]: less change is more atm for me, I need to get this stabilized and focus on my dayjob for a bit so nothing non-essential will get priority for a bit. Plenty of scope for refactoring after, I just want to stop corrupting people's database and crashing with the current released implementation

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java (hunk 63 above)
[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java:453]: I added one more commit that should handle the case of multiple queued clicks prior to click handler getting control

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java  7
- AnkiDroid/src/test/java/com/ichi2/anki/TemporaryModelTest.java  4
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  2
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java  1
- AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java  8
- AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.java  2
- AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java  1
         

Clones added
============
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688&bid=10073006)

**Comment by mikehardy** [comment]
No problem - I personally never run with 'Don't Keep Activities' but I do have test coverage of the onCreate/onSaveInstanceState so whatever is happening should be easy to expose. I'll check it out

File: AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java [hunk 65]
```diff
@@ -0,0 +1,447 @@
...
+        // Try to delete the template again, but there's only one
+        Assert.assertTrue("Unable to click?", shadowTestEditor.clickMenuItem(R.id.action_delete));
+        advanceRobolectricLooper();
+        Assert.assertEquals("Did not show dialog about deleting only card?",
+                getResourceString(R.string.card_template_editor_cant_delete),
+                getDialogText(true));
+        Assert.assertEquals("Change already in database?", collectionBasicModelOriginal.toString().trim(), getCurrentDatabaseModelCopy(modelName).toString().trim());
+
+        // Kill and restart the Activity, make sure model edit is preserved
+        // The saveInstanceState test would be useful but we can't run it without Robolectric ViewPager support
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java:159]: nit: commented code

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java [hunk 66]
```diff
@@ -0,0 +1,227 @@
...
+
+import androidx.annotation.Nullable;
+import timber.log.Timber;
+
+/**
+ * The card template previewer intent must supply one or more cards to show and the index in the list from where
+ * to begin showing them. Special rules are applied if the list size is 1 (i.e., no scrolling
+ * buttons will be shown).
+ */
+public class CardTemplatePreviewer extends AbstractFlashcardViewer {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java:39]: Nice to have for another PR: Allow the user to flip between front/back.

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java:39]: Ironically, if there is only one template, and you add a second one, it auto-flips it for you. Not documented anywhere.

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java  1
- AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java  8
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  2
- AnkiDroid/src/test/java/com/ichi2/anki/TemporaryModelTest.java  4
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java  7
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.java  2
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java  1
         

Clones added
============
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688&bid=10073006)

File: AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java [hunk 67]
```diff
@@ -0,0 +1,474 @@
...
+        int[] deletedDbOrdInts = new int[deletedDbOrds.size()];
+        for (int i = 0; i < deletedDbOrdInts.length; i++) {
+            deletedDbOrdInts[i] = (deletedDbOrds.get(i));
+        }
+        return deletedDbOrdInts;
+    }
+
+
+    private void dumpChanges() {
+        ArrayList<Object[]> adjustedChanges = getAdjustedTemplateChanges();
```
[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java:384]:
```java
if (!BuildConfig.DEBUG) {
  // ...
}
```
is as close as we can get

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java [hunk 68]
```diff
@@ -249,21 +199,28 @@ public void onPageScrollStateChanged(final int position) { /* do nothing */ }
     }
 
     public boolean modelHasChanged() {
-        JSONObject newModel = getCol().getModels().get(mModelId);
-        return mModelBackup != null && !mModelBackup.toString().equals(newModel.toString());
+        JSONObject oldModel = getCol().getModels().get(mModelId);
+        return getTempModel() != null && !getTempModel().getModel().toString().equals(oldModel.toString());
```
[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java:209]: took a quick peek at this but you have to pass Context and check for null and at that point it's a push I think

**Comment by david-allison-1** [comment]
A conditional on the build type isn't great as it means we can't affect the
variable with a runtime log config change. Best to leave it as-is IMO.
Surprising Timber doesn't have it hidden somewhere, but thanks.

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java (hunk 66 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java:39]: sorry - I was referring to CardTemplateEditor, for CardTemplatePreviewer that would be nice
Tim was very strongly for separation between Previewer and CardTemplatePreviewer, and that's one of the things that did not carry over but would be trivial

File: AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java (hunk 64 above)
[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java:421]: Ah I see what you mean. It's a lot of signal to cram into a return value. But I'll go for verbose and clear so I just named it the world-conquering getAdjustedAddOrdinalAtChangeIndex

File: AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java [hunk 69]
```diff
@@ -0,0 +1,474 @@
...
+            ChangeType changeType = (ChangeType)change[1];
+            Timber.d("compactTemplateChanges() examining change entry %s / %s", ordinal, changeType);
+
+            // Only make adjustments after the ordinal we want to delete was added
+            if (!postChange) {
+                if (ordinal == addedOrdinalToDelete && changeType == ChangeType.ADD) {
+                    Timber.d("compactTemplateChanges() found our entry at index %s", i);
+                    // Remove this entry to start compaction, then fix up the loop counter since we altered size
+                    postChange = true;
+                    mTemplateChanges.remove(i);
```
[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java:455]: I don't want to go there on this one, I have to reverse through the loop, while compacting it.
The whole thing is more than mildly distasteful but it does work. There may be a completely different approach and this thing can burn as it should

**Comment by mikehardy** [comment]
Did quite a few of the nits and can't make it do anything unexpected anymore with save activities off

Fundamentally it's that the Fragment relationship with the Activity is a bit janky and the Fragments were losing their way on save/resume. I clear the menu forcefully now when they draw it (a hack, but functional) and for delete/preview where current ordinal is required from UI I take greater care in tracking it in the Activity itself, and refer to that when needed.

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/TemporaryModelTest.java  4
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  2
- AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java  1
- AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java  8
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.java  2
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java  7
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java  1
         

Clones added
============
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688&bid=10073006)

**Comment by mikehardy** [comment]
> A conditional on the build type isn't great as it means we can't affect the variable with a runtime log config change. Best to leave it as-is IMO. Surprising Timber doesn't have it hidden somewhere, but thanks.

Fully agreed in principle but something so debuggy as a "dumpChanges" state printing function seems like it deserves it. And also I have never seen a runtime Timber configuration change. More importantly I already pushed with it and you can probably imagine the fatigue with this PR

**Comment by david-allison-1** [comment]
Got a repro:

New Collection: 

* Add 2 cards to "Basic". Save
* Open Card 3 in the Card Browser
* Delete Card 3
* Delete Card 2
* Add Card
* Save
* Crash

**Comment by mikehardy** [comment]
> Got a repro! Logging improvements are a godsend 🙏
> 
> New Collection:
> 
>     * Add 2 cards to "Basic". Save
> 
>     * Open Card 3 in the Card Browser
> 
>     * Delete Card 3
> 
>     * Delete Card 2
> 
>     * Add Card
> 
>     * Save
> 
>     * Crash

Thanks - just about to check this now. Still with don't save activities or just normal execution now? (should work with either of course, but curious)

**Comment by david-allison-1** [comment]
Good question! Just under "Don't Keep Activities". Probably an issue in the `NoteEditor`'s restoration function.

**Comment by mikehardy** [comment]
Oh my goodness, NoteEditor is a bit of a mess. It was losing it's mind across Activity restarts and the onCreate pathway was executed in that scenario before onActivityResult, which caused the crash yes. Not CardTemplateEditor related per se, but I fixed it

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java  7
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.java  2
- AnkiDroid/src/test/java/com/ichi2/anki/TemporaryModelTest.java  4
- AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java  1
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  2
- AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java  8
         

Clones added
============
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688&bid=10073006)

**Comment by mikehardy** [comment]
All of this is existing mess. I want to revert my last commit and queue an issue for NoteEditor not working separately or this will cascade into another mess of work here, and I'm done with it. Yay or nay?

**Comment by david-allison-1** [comment]
> All of this is existing mess. I want to revert my last commit and queue an issue for NoteEditor not working separately or this will cascade into another mess of work here, and I'm done with it. Yay or nay?

I'm more than done with this.

Agreed on reverting NoteEditor and adding a defect ticket. On the other two: they're CardTemplateEditor, but they're hard to trigger.

2020-04-29-2 is almost certainly a harmless lifecycle-based crash. I'd be happy with this going in with a defect ticket.

The other (2020-04-29-3) I'll want to look into before approving. Intuition tells me it's a UI-based state mismatch. which could be benign, or could be an issue given that the UI has an active role in deciding business logic inputs.

**Comment by mikehardy** [comment]
I took a peek and yes, that'll be in CardTemplateEditor but I am deeply saddened to see it is in the Fragment management. That stuff is difficult. My current understanding is that the each Fragment contains a template and that rather than recycle them or even really keep them fully coherent with the underlying model, we spawn new ones all the time and the old ones are left to die - and that's in the normal add/delete case. Then when you throw in lifecycle stop/start and spawn more + old ones are still around it gets nasty. At any rate, I don't want to spider out into NoteEditor work but in CardTemplateEditor 'Don't Save Activities' is just a quick way to test niche-but-real use cases so I'll work through it

**Comment by mikehardy** [comment]
>  [sequence where you delete-existing/add-pending/delete-pending at the same ordinal]
>     * States that there is 1 card in the database which will be deleted, even though it's an in-memory template.

Nice one! Added a quick test for that and only calculate "template in use count" for an ordinal if it's not pending add now.

**Comment by mikehardy** [comment]
>     * Visual: Note Editor: "Cards: Card 1" no longer appears when adding a new note. (With Keep Activities) - still clickable, and still visible when editing.

I thought better of just spitting the dummy here since it was so close. I'm a bit more surgical now about how I bail on the current card not existing so it works for this case too. I'd already done the mental work on it, and it's easy to see the failure so... try to keep it fixed.

**Comment by david-allison-1** [comment]
> > Visual: Note Editor: "Cards: Card 1" no longer appears when adding a new note. (With Keep Activities) - still clickable, and still visible when editing.
> 
> I thought better of just spitting the dummy here since it was so close. I'm a bit more surgical now about how I bail on the current card not existing so it works for this case too. I'd already done the mental work on it, and it's easy to see the failure so... try to keep it fixed.

I'm more than happy to move all the `NoteEditor` stuff into another later PR, it reduces the surface area to test and verify. `NoteEditor` is another beast to be tamed, but it's only a crash, not corruption, and it's very rare.

**Comment by david-allison-1** [comment]
> The other (2020-04-29-3) I'll want to look into before approving. Intuition tells me it's a UI-based state mismatch. which could be benign, or could be an issue given that the UI has an active role in deciding business logic inputs.

Repro Steps:

* State: 1 card, Don't Keep Activities
* Add Card
* onCreate/destroy via leaving app
* Delete Card
* Select Card 1 without touching action bar
* onCreate/destroy via leaving app

**Comment by mikehardy** [comment]
Yeah - even niftier is that if you edit the fragments (say delete Card 2 then add a new ord 2 with '2new' in the template etc, after a lifecycle you'll sometimes see the old contents pop up. It's all fragment lifecycle mess. Thanks for the minimal repro though, that helps, the one I had was a bit more fluffy

**Comment by mikehardy** [comment]
Going to migrate to ViewPager2, it will take a minute but should be well worth it to untangle the current UI snarl at the same time we get correct save/resume behavior

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  2
- AnkiDroid/src/test/java/com/ichi2/anki/TemporaryModelTest.java  4
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.java  2
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java  2
- AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java  8
- AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java  1
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java  7
         

Clones added
============
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  21
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=2682688&bid=10073006)

**Comment by mikehardy** [comment]
Hey @david-allison-1 check the last two commits here - the first fixes your incorrect card count issue, and the second works around the pager/fragment activity restart mess

I am really hesitant to migrate to ViewPager2 within this PR and with the time I have available right now. I think I found a workable temporary solution for the stale Fragments that we orphan and cause this problem across Activity restarts. Now I pop them all off the back stack so they shouldn't show up in the UI anymore, and I shunt related exceptions for the stale ones so they don't blow up Activity restart

It is distasteful but does result in correct behavior in my testing

If this is good enough I'd to go with it and unblock 2.10beta

**Comment by mikehardy** [comment]
Alright, then that's my last attempt for this pile of __ for 2.10. Rescheduling it

**Comment by mikehardy** [comment]
Can't seem to make any of that terrible stuff happen with ViewPager2 anymore. A couple of the bizarre don't-keep-activity-lifecycles fragment staleness things were still happening after cleaning out all of the previous view/tab/pager/model adapter, but when I re-added in ordinal shifts so that the view wouldn't have id collisions from the ordinals, they all went away.

Solid? Could be.

**Comment by mikehardy** [comment]
Side note - I can do a ViewPager2 transition on Stats now as well and delete the whole SlidingTabLayout object / clean things out there too. ViewPager2 boils the code down nicely compared with the 2013-era paging

**Comment by mikehardy** [comment]
I have seen the OOM you mention and have that on my investigate list. Not sure what the deal is there. I see the empty cards bar on add note, investigating... I remember that happening before and thought I got it but the rebase to current when I started work was 420 commits (!?) and NoteEditor doesn't have good coverage (yet)

**Comment by mikehardy** [comment]
Investigating OOMs but just pushed a commit that adds test cover to NoteEditor for that failure and fixes it. At this point I'm back to "I think it's correct" but of course Travis going OOM is a blocker in parallel with whatever testing you can do

**Comment by mikehardy** [comment]
OOMs fixed. This is just "needs second review" then "pending merge" in my book. Hopefully your testing reveals nothing :-)

**Comment by mikehardy** [comment]
OMG this is done. @timrae CardTemplateEditor no longer corrupts data, in the end we needed to wait this long for Google to release ViewPager2 in Oct 2019 for it to really work across Activity restarts anyway, so it makes sense it took this long ;-)

**Comment by timrae** [comment]
A heroic effort, congrats!! :)

**Comment by Arthur-Milchior** [comment]
Congratulation. One year and a half PR. I admire you for dealing wit it until it got merged !

> The majority of the missed coverage is JSONException catches.

I hope it is not even true anymore, so, as David above, I can put a smiley with hearty-eyes because some of my improvements are used too

**Comment by mikehardy** [comment]
This PR and all the ones that spun out of it are literally how I learned Android development. Celebrating tonight haha Thanks for the help on the way @timrae @david-allison-1
