### PR TITLE
Clarified Sync Error Message

### LINKED ISSUE #10000: [Bug] Clarify media sync error message
###### Reproduction Steps

1. Start a sync on a new device for a collection with a lot of media
2. Not sure. Probably do something such as remove internet access, move to a connection that requires condition (e.g. hotel, public transit)... Ensuring that media stop syncing, not requested by user
3. Look at error message

###### Expected Result
Let the user know what did occur and what can be done.

###### Actual Result
Screenshot_20211217-065334

###### Debug info
You can for example let the user know the number of media that were downloaded and uploaded. You can also let them know that a new sync will sync more medias and they can do it until all media are synced.
If for some reason no media were synced at all but we were expecting to sync media, then let the user know that we tried to download or upload data but failed. They may try again or ask for help.

Good luck with making all of this small. But I believe more actionable advices and more explanation are needed

### PR DESCRIPTION
**Pull request by puranjayK**
## Purpose / Description
To clarify the sync error message to the user

## Fixes
Fixes #10000 

## Approach
Used the progress value of upload and download to clarify the user about when the sync stopped.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by Arthur-Milchior — COMMENTED** [review]
Hi,

Thanks a lot for your first contribution. That's great to see indication that some down/up load took place.

I fear this is quite far from what I imagined. Indeed, for a user who is not used to computer internals, they still would not know what to do, nor what did occur. Let's concentrate on both part separately. 

As I suggested in the issue, we can explain to the user they can retry; maybe they need a stable internet connection, or to wait because ankiweb is buggy, or something. The action, even if it fail, was not useless, and even if it took many tries and failed in the way, it's still worth syncing again and again. But the user do not know that with the information they have, so we need to let them know it makes sens.
To show it actually makes sens, I believe the best way is to tell them how many medias were downloaded or uploaded. So they know something did really occur. Ideally they should also know what remains to do, so that they can judge the progress. After all, if they can only upload two medias at a time and they have 2000 medias to upload, something is very wrong. If they have 2000 medias to upload and they can do 500 before their connection broke, it will "only" take four tries, which is more reasonnable for them.
Even better, I think, would be to only mention download/upload depending on when the process failed. So they get only the relevant informations. After all if they always see (0 download) but it is only because there is actually nothing to download, this information is useless and scary. If they always see (0 upload) because upload only occur when downloads are done, this information is also useless (we didn't even try to upload anything) and scary.


Most of the informations are either available in the media syncer. And you can add more properties if necessary to store all of the data you need to have access to. You'll need to look at MediaSyncer's sync function to look at when upload/download did occur to take care of it. And also log the number of expected download and upload.

Sorry if it's more complex than you expected. I still believe it can be a good first contribution, but I also fear you'll need to do a little more work on it first.

File: AnkiDroid/src/main/java/com/ichi2/async/Connection.java [hunk 1]
```diff
@@ -578,6 +578,8 @@ public void publishProgress(String message) {
     @SuppressWarnings("deprecation") // #7108: AsyncTask
     public void publishProgress(int id, long up, long down) {
         super.publishProgress(id, up, down);
+        kBytesSent =up/1024;
```
[the remark this answers is not in the document]
Comment (puranjayK) [reply AnkiDroid/src/main/java/com/ichi2/async/Connection.java]: Done.

[the remark this answers is not in the document]
Comment (puranjayK) [reply AnkiDroid/src/main/java/com/ichi2/async/Connection.java]: Done.

**Comment by puranjayK** [comment]
> Hi,
> 
> Thanks a lot for your first contribution. That's great to see indication that some down/up load took place.
> 
> I fear this is quite far from what I imagined. Indeed, for a user who is not used to computer internals, they still would not know what to do, nor what did occur. Let's concentrate on both part separately.
> 
> As I suggested in the issue, we can explain to the user they can retry; maybe they need a stable internet connection, or to wait because ankiweb is buggy, or something. The action, even if it fail, was not useless, and even if it took many tries and failed in the way, it's still worth syncing again and again. But the user do not know that with the information they have, so we need to let them know it makes sens. To show it actually makes sens, I believe the best way is to tell them how many medias were downloaded or uploaded. So they know something did really occur. Ideally they should also know what remains to do, so that they can judge the progress. After all, if they can only upload two medias at a time and they have 2000 medias to upload, something is very wrong. If they have 2000 medias to upload and they can do 500 before their connection broke, it will "only" take four tries, which is more reasonnable for them. Even better, I think, would be to only mention download/upload depending on when the process failed. So they get only the relevant informations. After all if they always see (0 download) but it is only because there is actually nothing to download, this information is useless and scary. If they always see (0 upload) because upload only occur when downloads are done, this information is also useless (we didn't even try to upload anything) and scary.
> 
> Most of the informations are either available in the media syncer. And you can add more properties if necessary to store all of the data you need to have access to. You'll need to look at MediaSyncer's sync function to look at when upload/download did occur to take care of it. And also log the number of expected download and upload.
> 
> Sorry if it's more complex than you expected. I still believe it can be a good first contribution, but I also fear you'll need to do a little more work on it first.

Thank you so much for the clarification. I'll definitely look into it. 
I was able to reproduce this issue only when the upload / download was almost / totally completed. It would be helpful if you could tell on how should I reproduce it in other situations as well (if any).

**Comment by Arthur-Milchior** [comment]
I believe that the easiest way to really stop syncing is:
* add a lot of heavy media, so that trying will take dozens of second
* during the media sync, move to plane mode to remove internet access

An even easier way to do throw an exception during media sync is to hard code it. Modify the MediaSync's sync method, and throw an exception after one or two media downloaded/uploaded. (of course, this should not be comitted)

But anyway, I don't believe that it's really important to test the code as it is right now. First show the information that are useful for the user in case of problem, as I described above*. Once the feature is implemented, it'll make more sent to actually look at whether we get the right error message.

*Or suggest something even better, or disagree and explain why my idea is not as good as I think it is. I am never asking you to just obey, all contributors are welcome to have opinions and disagree. We just want to know why you do so. In this case, if you think your current message is better than my suggestion, I'd love to know why.

File: AnkiDroid/src/main/java/com/ichi2/async/Connection.java [hunk 2]
```diff
@@ -482,7 +482,7 @@ private Payload doInBackgroundSync(Payload data) {
                     Timber.i("Sync - Performing media sync");
                     ret = mediaClient.sync();
                     if (ret == null || ret.first == null) {
-                        mediaError = AnkiDroidApp.getAppResources().getString(R.string.sync_media_error);
+                        mediaError = AnkiDroidApp.getAppResources().getString(R.string.sync_media_error)+ "\n\n" + AnkiDroidApp.getAppResources().getString(R.string.sync_up_down_size,kBytesSent,kBytesReceived);
```
Comment (ShridharGoel) [inline AnkiDroid/src/main/java/com/ichi2/async/Connection.java:485]:
```suggestion
                        mediaError = AnkiDroidApp.getAppResources().getString(R.string.sync_media_error) + "\n\n" + AnkiDroidApp.getAppResources().getString(R.string.sync_up_down_size, kBytesSent, kBytesReceived);
```

File: AnkiDroid/src/main/java/com/ichi2/async/Connection.java [hunk 3]
```diff
@@ -507,7 +507,7 @@ private Payload doInBackgroundSync(Payload data) {
                         data.resultType = USER_ABORTED_SYNC;
                         data.result = new Object[]{e};
                     }
-                    mediaError = AnkiDroidApp.getAppResources().getString(R.string.sync_media_error) + "\n\n" + e.getLocalizedMessage();
+                    mediaError = AnkiDroidApp.getAppResources().getString(R.string.sync_media_error) + "\n\n" + e.getLocalizedMessage() + "\n\n"+ AnkiDroidApp.getAppResources().getString(R.string.sync_up_down_size,kBytesSent,kBytesReceived);
```
Comment (ShridharGoel) [inline AnkiDroid/src/main/java/com/ichi2/async/Connection.java:510]:
```suggestion
                    mediaError = AnkiDroidApp.getAppResources().getString(R.string.sync_media_error) + "\n\n" + e.getLocalizedMessage() + "\n\n" + AnkiDroidApp.getAppResources().getString(R.string.sync_up_down_size, kBytesSent, kBytesReceived);
```

**Review by ShridharGoel — CHANGES_REQUESTED** [review]
Small formatting changes

**Comment by puranjayK** [comment]
> Hi,
> 
> Thanks a lot for your first contribution. That's great to see indication that some down/up load took place.
> 
> I fear this is quite far from what I imagined. Indeed, for a user who is not used to computer internals, they still would not know what to do, nor what did occur. Let's concentrate on both part separately.
> 
> As I suggested in the issue, we can explain to the user they can retry; maybe they need a stable internet connection, or to wait because ankiweb is buggy, or something. The action, even if it fail, was not useless, and even if it took many tries and failed in the way, it's still worth syncing again and again. But the user do not know that with the information they have, so we need to let them know it makes sens. To show it actually makes sens, I believe the best way is to tell them how many medias were downloaded or uploaded. So they know something did really occur. Ideally they should also know what remains to do, so that they can judge the progress. After all, if they can only upload two medias at a time and they have 2000 medias to upload, something is very wrong. If they have 2000 medias to upload and they can do 500 before their connection broke, it will "only" take four tries, which is more reasonnable for them. Even better, I think, would be to only mention download/upload depending on when the process failed. So they get only the relevant informations. After all if they always see (0 download) but it is only because there is actually nothing to download, this information is useless and scary. If they always see (0 upload) because upload only occur when downloads are done, this information is also useless (we didn't even try to upload anything) and scary.
> 
> Most of the informations are either available in the media syncer. And you can add more properties if necessary to store all of the data you need to have access to. You'll need to look at MediaSyncer's sync function to look at when upload/download did occur to take care of it. And also log the number of expected download and upload.
> 
> Sorry if it's more complex than you expected. I still believe it can be a good first contribution, but I also fear you'll need to do a little more work on it first.

I had 45 media files on AnkiWeb server. I reinstalled Ankidroid (delete the folder in root) and then logged in and synced.
1                                    |                2                    |          3
:-------------------------:|:-------------------------:|:-------------------------:
 |  | 

1.  I switched off all internet access in the mid of the sync (around 25 media files were downloaded).
2.  Then I enabled internet connection and synced again. while adding 7 media files. On syncing the remaining 20 media files were downloaded and then the upload began. In the mid of the upload, I turned off internet again (around 5 files had been uploaded by that point).
3.  Finally I switched on the internet and synced again and the remaining 2 files got uploaded.

File: AnkiDroid/src/main/java/com/ichi2/async/Connection.java [hunk 4]
```diff
@@ -77,6 +77,16 @@
      * the process will be paused and the sync can fail due to timing conflicts with AnkiWeb.
      */
     private final PowerManager.WakeLock mWakeLock;
+    private long kBytesReceived, kBytesSent;
+    private long filesDownloaded=0;
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/async/Connection.java:81]: https://github.com/ankidroid/Anki-Android/wiki/Code-style

```suggestion
    private long filesDownloaded = 0;
```

Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/async/Connection.java:81]: Can these be moved to `MediaSyncer`, they're not a responsibility of the connection.

File: AnkiDroid/src/main/java/com/ichi2/async/Connection.java [hunk 5]
```diff
@@ -77,6 +77,16 @@
      * the process will be paused and the sync can fail due to timing conflicts with AnkiWeb.
      */
     private final PowerManager.WakeLock mWakeLock;
+    private long kBytesReceived, kBytesSent;
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/async/Connection.java:80]: Should be split into two variables

File: AnkiDroid/src/main/java/com/ichi2/async/Connection.java [hunk 6]
```diff
@@ -507,7 +517,7 @@ private Payload doInBackgroundSync(Payload data) {
                         data.resultType = USER_ABORTED_SYNC;
                         data.result = new Object[]{e};
                     }
-                    mediaError = AnkiDroidApp.getAppResources().getString(R.string.sync_media_error) + "\n\n" + e.getLocalizedMessage();
+                    mediaError = AnkiDroidApp.getAppResources().getString(R.string.sync_media_error) + "\n\n" + e.getLocalizedMessage() + "\n\n" + AnkiDroidApp.getAppResources().getString(R.string.sync_media_downloaded_count,filesDownloaded)  + "\n\n" + "Uploaded "+filesUploaded+ " media files";
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/async/Connection.java:520]:
```suggestion
                    mediaError = AnkiDroidApp.getAppResources().getString(R.string.sync_media_error) + "\n\n" + e.getLocalizedMessage() + "\n\n" + AnkiDroidApp.getAppResources().getString(R.string.sync_media_downloaded_count, filesDownloaded)  + "\n\n" + "Uploaded "+ filesUploaded + " media files";
```

Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/async/Connection.java:520]: This needs to be extracted to a string

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
Few comments, nothing major

File: AnkiDroid/src/main/java/com/ichi2/async/Connection.java (hunk 5 above)
Comment (puranjayK) [reply AnkiDroid/src/main/java/com/ichi2/async/Connection.java:80]: I have removed these as they aren't needed anymore

File: AnkiDroid/src/main/java/com/ichi2/async/Connection.java (hunk 4 above)
Comment (puranjayK) [reply AnkiDroid/src/main/java/com/ichi2/async/Connection.java:81]: I'll need their value in Connection.java because the value is displayed in a connection error

Comment (puranjayK) [reply AnkiDroid/src/main/java/com/ichi2/async/Connection.java:81]: Done

File: AnkiDroid/src/main/java/com/ichi2/async/Connection.java (hunk 6 above)
Comment (puranjayK) [reply AnkiDroid/src/main/java/com/ichi2/async/Connection.java]: Done.

File: AnkiDroid/src/main/java/com/ichi2/async/Connection.java (hunk 4 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/async/Connection.java]: I'm fairly sure these can be moved, you should have access to `MediaSyncer` from the catch block

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
I still feel the variables can be moved to `MediaSyncer`

File: AnkiDroid/src/main/java/com/ichi2/async/Connection.java (hunk 4 above)
Comment (puranjayK) [reply AnkiDroid/src/main/java/com/ichi2/async/Connection.java]: Yup, got it

**Comment by puranjayK** [comment]
> I still feel the variables can be moved to `MediaSyncer`

PTAL, I have made the changes

File: AnkiDroid/src/main/java/com/ichi2/libanki/sync/MediaSyncer.java [hunk 7]
```diff
@@ -197,6 +206,7 @@ public MediaSyncer(Collection col, RemoteMediaServer server, Connection con) {
                                                        AnkiDroidApp.getAppResources().getString(R.string.sync_media_changes_count), toSend));
 
                     JSONArray changes = mServer.uploadChanges(zip);
+                    mUploadCount = changes.getInt(0);
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/libanki/sync/MediaSyncer.java:209]: I'd have expected `mUploadCount += processedCnt` here. Is there a reason we're resetting the variable?

**Review by david-allison-1 — COMMENTED** [review]
One question.

Could you update the screenshot on the PR? It looks out of date

File: AnkiDroid/src/main/java/com/ichi2/async/Connection.java [hunk 8]
```diff
@@ -507,7 +507,9 @@ private Payload doInBackgroundSync(Payload data) {
                         data.resultType = USER_ABORTED_SYNC;
                         data.result = new Object[]{e};
                     }
-                    mediaError = AnkiDroidApp.getAppResources().getString(R.string.sync_media_error) + "\n\n" + e.getLocalizedMessage();
+                    mediaError = AnkiDroidApp.getAppResources().getString(R.string.sync_media_error) + "\n\n" + e.getLocalizedMessage()
+                            + "\n\n" + AnkiDroidApp.getAppResources().getString(R.string.sync_media_downloaded_count, mediaClient.getDownloadCount())
+                            + "\n\n" + AnkiDroidApp.getAppResources().getString(R.string.sync_media_uploaded_count, mediaClient.getUploadCount());
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/async/Connection.java:512]: I think one `\n` would be better here

```suggestion
                            + "\n" + AnkiDroidApp.getAppResources().getString(R.string.sync_media_uploaded_count, mediaClient.getUploadCount());
```

File: AnkiDroid/src/main/java/com/ichi2/async/Connection.java (hunk 3 above)
Comment (puranjayK) [reply AnkiDroid/src/main/java/com/ichi2/async/Connection.java]: Done.

File: AnkiDroid/src/main/java/com/ichi2/async/Connection.java (hunk 2 above)
Comment (puranjayK) [reply AnkiDroid/src/main/java/com/ichi2/async/Connection.java]: These variables were not needed, hence I deleted them

**Comment by puranjayK** [comment]
1                                    |                2                    |          3
:-------------------------:|:-------------------------:|:-------------------------:
   |  | 

1. In the mid of the upload, I turned off internet again (around 4 files had been uploaded by that point). Finally I switched on the internet and synced again and the remaining  files got uploaded.
2. I switched off all internet access in the mid of the sync (around 39 media files were downloaded).
3. Then I enabled internet connection and synced again. On syncing the remaining media files were downloaded.

**Comment by david-allison-1** [comment]
Hi, the screenshots don't seem to match the review comments I made.

**Comment by puranjayK** [comment]
> Hi, the screenshots don't seem to match the review comments I made.

Sorry, I missed the review comments. I'll make the updates and post the screenshots

File: AnkiDroid/src/main/java/com/ichi2/libanki/sync/MediaSyncer.java (hunk 7 above)
Comment (puranjayK) [reply AnkiDroid/src/main/java/com/ichi2/libanki/sync/MediaSyncer.java:209]: Yup this would make more sense.

File: AnkiDroid/src/main/java/com/ichi2/async/Connection.java (hunk 8 above)
Comment (puranjayK) [reply AnkiDroid/src/main/java/com/ichi2/async/Connection.java]: @david-allison-1 Can you give me a feedback on this

Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/async/Connection.java]: Sounds good to me

**Comment by puranjayK** [comment]
1                                    |                2                    |          3
:-------------------------:|:-------------------------:|:-------------------------:
 |  | 

1.  I switched off all internet access at the start of the sync (no media files were downloaded / uploaded).
2.  Then I enabled internet connection and synced again. On syncing 11 media files were downloaded and then I turned off internet again.
3.  Finally I switched on the internet , while adding 7 media files and synced again and the remaining files got downloaded and the upload started. I switched off the internet when 3 media files were uploaded.

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
We no longer show the error message on the dialog

**Comment by puranjayK** [comment]
> This no longer shows the error message on the dialog

I thought you asked me to remove that completely

**Comment by puranjayK** [comment]
1                                    |                2                    |       
:-------------------------:|:-------------------------:
 |  

@david-allison-1 PTAL

**Comment by david-allison-1** [comment]
> 1                                    |                2                    |       
> :-------------------------:|:-------------------------:
>  |  
> 
> @david-allison-1 PTAL

Could you switch the error message to be last in 2.

Looks good aside from that

**Comment by puranjayK** [comment]
> Could you switch the error message to be last in **2** and add a single newline between the message, upload and download strings (not a gap, just so each string starts in a new line)
> 
> Looks good aside from that


@david-allison-1 PTAL

**Comment by Arthur-Milchior** [comment]
@puranjayK There is a conflict that need to be resolved in MediaSyncer.java, sorry. Could you please resolve it and push again.

The test failed, but I read
> Platform error occurred when running the UTP test suite

It seems the issue was with the test system and not your code itself, so hopefully, once the test run again with the conflict merged, it'll work.

Thanks a lot for all of those updates. I believe all of those message will be really clearer!

**Comment by puranjayK** [comment]
> @puranjayK There is a conflict that need to be resolved in MediaSyncer.java, sorry. Could you please resolve it and push again.
> 
> The test failed, but I read
> 
> > Platform error occurred when running the UTP test suite
> 
> It seems the issue was with the test system and not your code itself, so hopefully, once the test run again with the conflict merged, it'll work.
> 
> Thanks a lot for all of those updates. I believe all of those message will be really clearer!

  

@Arthur-Milchior PTAL. 
- [x] Fixed the merge conflicts
- [x] Rebuilt the project
- [x] Tested the error and uploaded the screenshot for the same

File: AnkiDroid/src/main/res/values/04-network.xml [hunk 9]
```diff
@@ -81,6 +81,7 @@
     <string name="sync_media_find">Finding changed media…</string>
     <string name="sync_media_no_changes">No changes to media files</string>
     <string name="sync_media_success">Media synced</string>
+    <string name="sync_media_partial">Media sync partially completed: %d media files downloaded.\n%d media files uploaded.</string>
```
Comment (david-allison-1) [inline AnkiDroid/src/main/res/values/04-network.xml:84]:
```suggestion
    <string name="sync_media_partial">Media sync partially completed:\n%d media files downloaded.\n%d media files uploaded.</string>
```

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
Sounds like we're there after this one!

**Review by david-allison-1 — APPROVED** [review]
LGTM

**Comment by Arthur-Milchior** [comment]
I assume we squash everything. Or do you want to clean the PR up and do a sequence of atomic commits? Given it's only 16 lines, i don't believe it's useful

**Review by Arthur-Milchior — APPROVED** [review]

**Comment by david-allison** [comment]
squash + manually cleanup commit message seems like the best

**Comment by Arthur-Milchior** [comment]
> This branch cannot be rebased due to conflicts

Sorry, it seems it needs you manually remerge it again

**Comment by Arthur-Milchior** [comment]
Oh actually, you'll need to squash it all yourself, because the reason it's blocking, I believe, is because github can't deal with intermediate commits here
