### PR TITLE
fix: crash on Check Media

### LINKED ISSUE #13527: [BUG]: Check Media causing crash
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Deck Picker 
2. Check Media

### Expected behaviour

Media check result dialog is shown

### Actual behaviour

Crash

### Debug info

```text
Alpha95-debug
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
A lateinit callback wasn't defined

## Fixes
- Fixes #13527
- Fixes #13529

## Approach
Define the callback

## How Has This Been Tested?
API 33 emulator

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt [hunk 1]
```diff
@@ -116,7 +115,7 @@ class PermissionManager private constructor(
         if (permissions.requiresPermissionDialog) {
             this.launchPermissionDialog()
         } else {
-            callback.invoke(PermissionsRequestResults.allGranted(permissions))
+            callback.invoke(permissions.toPermissionsRequestRawResult()!!)
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt:118]: the !! works because the same condition which results in null value here is the first branch of the conditional so can't hit this else, LGTM

**Review by mikehardy — APPROVED** [review]
Nice

**Review by lukstbit — APPROVED** [review]
LGTM!

File: AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt (hunk 1 above)
Comment (oakkitten) [reply AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt:118]: When I was reviewing the initial PR and ran into this crash, I “fixed” this by simply saying `callback(permissions.permissions)`. Can I ask why this needs an additional method? It seems to do the same thing
