### PR TITLE
Fix time rounding errors

### LINKED ISSUE #6894: Wrong due time displayed when more than 1h29min due time left
###### Reproduction Steps
Have (at least) 1h30min due time left.

###### Expected Result
1h30min displayed

###### Actual Result
2h30min displayed

###### Debug info
AnkiDroid Version = 2.12.1
Android version = 10

###### Research
- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))
It seems to systematically happen when there is (really) more than 1h29min due time left.
Screenshot_1_AnkiDroid_2_12_1
Screenshot_2_AnkiDroid_2_12_1

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description
1h30 currently renders as 2h30

## Fixes
Fixes  #6894

## Approach
Use math.floor instead of math.round

## How Has This Been Tested?

Unit Tested

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

File: AnkiDroid/src/test/java/com/ichi2/libanki/UtilsIntegrationTest.java [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+import org.robolectric.annotation.Config;
+
+import androidx.annotation.CheckResult;
+import androidx.test.ext.junit.runners.AndroidJUnit4;
+
+import static org.hamcrest.MatcherAssert.assertThat;
+import static org.hamcrest.Matchers.is;
+
+@RunWith(AndroidJUnit4.class)
+@Config(application = NullApplication.class, qualifiers = "en")
```
Comment (mikehardy) [inline AnkiDroid/src/test/java/com/ichi2/libanki/UtilsIntegrationTest.java:18]: Neat trick!

**Comment by mikehardy** [comment]
Can't be putting that in 2.14 though, 2.13 hasn't even had the branch cut yet?
