### PR TITLE
fix: use android import for crash report dialog

### LINKED ISSUE #16604: [BUG]: Project debug build gives an crash error on each build
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

Build the project -> Launch the app

### Expected behaviour

No error

### Actual behaviour

Log: 
```
Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                                                        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:902)
                                                                                                        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:865)
                                                                                                        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:748)
                                                                                                        at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:99)
                                                                                                        at androidx.appcompat.app.AlertController.installContent(AlertController.java:232)
                                                                                                        at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:278)
                                                                                                        at android.app.Dialog.dispatchOnCreate(Dialog.java:461)
                                                                                                        at android.app.Dialog.show(Dialog.java:339)
                                                                                                        at com.ichi2.anki.analytics.AnkiDroidCrashReportDialog.onCreate(AnkiDroidCrashReportDialog.kt:57)
```

### Debug info

```text
On main branch
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by shrutigitte**
## Purpose / Description
use android import for crash report dialog instead of androidx as crash report acitivity is a external dependecy activity and using androidx requires theme.appCompat

## Fixes
* Fixes #16604 

## How Has This Been Tested?
Locally tested on emulator

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by criticalAY — CHANGES_REQUESTED** [review]
CI failed, you need to update the lint file and add this file as exception there

**Review by david-allison — APPROVED** [review]
Needs a follow-up issue for a test

and the lint needs to be ignored with a reason

```
  /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.kt:20: Error: Use androidx.appcompat.app.AlertDialog instead of android.app.AlertDialog [AvoidAlertDialogUsage from com.ichi2.anki:lint-rules]
  import android.app.AlertDialog
```

**Review by mikehardy — COMMENTED** [review]
Hasn't shipped in the release-2.18 branch so this does not need a pick

Can't approve with lint failing tho

**Review by criticalAY — APPROVED** [review]
Looks good now!

File: AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.kt [hunk 1]
```diff
@@ -1,3 +1,4 @@
+//noinspection AvoidAlertDialogUsage see #16605
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.kt:1]: Is it possible to move this next to the import?

Comment (shrutigitte) [reply AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.kt:1]: no it cannot be because it would not be in lexical order

'''
Imports must be ordered in lexicographic order without any empty lines in-between with "java", "javax", "kotlin" and aliases in the end -- no autocorrection due to comments in the import list [90m(import-ordering)[0m
'''

**Comment by david-allison** [comment]
LGTM, @shrutigitte Could you squash the commits so we can add this to the merge queue?

**Review by david-allison — APPROVED** [review]

**Comment by shrutigitte** [comment]
done

**Review by lukstbit — APPROVED** [review]
Thanks for the fix!
While the _noinspection_ comment worked on suppressing the lint violation, I think it is better to use the lint rules system that we built so I added the required lint code.
