### PR TITLE
Deck toggles should not show when inapplicable in a search

### LINKED ISSUE #18278: Expand/collapse icon not rendering immediately when adding subdeck
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Go to deck picker
2. Create subdeck

https://github.com/user-attachments/assets/13c59d57-b12e-4cf6-9e6d-39563ffe4469

### Expected behaviour

Expand/collapse icon rendering immediately when adding subdeck

### Debug info

```text
AnkiDroid Version = 2.21alpha13-debug (2f221db614c82f86e71baf2a1ac905df2570f3d6)
Backend Version = 0.1.51-anki25.02 (25.02 038d85b1d9e1896e93a3e4a26f600c79ddc33611)
Android Version = 13 (SDK 33)
ProductFlavor = amazon
Device Info = OPPO | OPPO | OP532FL1 | CPH2341 | CPH2341 | qcom
Webview User Agent = Mozilla/5.0 (Linux; Android 13; CPH2341 Build/TP1A.220624.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/136.0.7103.60 Mobile Safari/537.36
ACRA UUID = 6f49c98d-56ae-4c38-9357-4637ee097a27
FSRS = 2.0.3 (Enabled: false)
Crash Reports Enabled = false
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### LINKED ISSUE #18379: Collapse/uncollapse icons show during search even when not usable
Suppose you have a deck `Science::Math::Algebra::Group`

If you search for "Algebra", then the little icon on the left of the deck shows that "Science"  is not collapsed, "Math" is collapsed, and "Algebra" is not collapsed.

The button on the left of "Algebra" will allow to indeed collapse on uncollapsed subdecks. The button on the left of "Science" and "Math" will be ignored.

We should remove the buttons whose actions are ignored. That is, "Science" and "Math" should not show any button to collapse/uncollapse. 

_Originally posted by @Arthur-Milchior in https://github.com/ankidroid/Anki-Android/pull/18298#pullrequestreview-2831503938_

### PR DESCRIPTION
**Pull request by gautambhetanabhotla**
## Purpose / Description
When searching for decks in the main menu, parents of matching decks are also rendered but their expand/collapse toggles were unnecessary as the toggles don't work during a search. This PR aims to not render those toggles at all.

### Before
image

### After
image

Note that toggles for matching decks and their children are still active and functional.

## Fixes
* Fixes #18278
* Fixes #18379 

## Approach
Created a new property for `DeckNode`, namely `var matchingSearchOrChild: Boolean`. This is set to `true` for all decks matching the search query or having an ancestor which matches the query. Only these decks have active and functioning toggles. The other visible decks will not have their toggles rendered. This requires updating the diff checker for the list adapter to also check for update in the `matchingSearchOrChild` property. Since both lists hold a reference to the same node, the diff checker cannot catch a change in this property. Hence I tracked changes in `DeckNode` itself by adding a `previouslyMatchingSearchOrChild` property. Every time the search query changes, `previouslyMatchingSearchOrChild` takes on the value of `matchingSearchOrChild` and the latter gets adjusted according to the deck's name and the query.

## How Has This Been Tested?

Manual tests on
1. An android device
2. An android emulator (medium phone API 35)

## Learning (optional, can help others)
A significant pitfall I faced in this process was that the `filterAndFlatten` (which returns a list of `DeckNode`s and their children matching the search query) could not be modified to simply return a list of _copies_ of the original `DeckNode`s, as the toggle functionality (when the search bar isn't active) checks the `collapsed` property of the original node. Duplicating it caused problems. On the other hand, simply updating the boolean did not trigger the diff checker, leading to the list not re-rendering to show the correct result. I had also considered inserting a dummy `DeckNode`  right before returning the list to manually trigger the diff checker but decided to go with the 2 boolean approach as described previously.

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckNode.kt [hunk 1]
```diff
@@ -51,6 +51,18 @@ data class DeckNode(
...
+    /**
+     * @return Whether the node matches the search query in the deck picker,
+     * or is a child of such a node.
+     * Such nodes will have the expand/collapse button rendered next to them,
+     * as those are the only nodes that can be expanded/collapsed when there is
+     * a search query. There are 2 of these variables to properly maintain previous
+     * and current state of the match. This is because the diff checker cannot catch
+     * these changes as both the old and new lists contain references to the same node.
+     */
+    var previouslyMatchingSearchOrChild: Boolean = true
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckNode.kt]: We want to make `DeckNode` immutable. The fact that it's mutable introduces a few bugs which we need to resolve.

Could you either store these variables outside the class, or make them immutable and rebuild the tree (implementer's choice, dependent upon performance)?

**Review by david-allison — CHANGES_REQUESTED** [review]
Great code! One implementation change requested

File: AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckNode.kt (hunk 1 above)
Comment (gautambhetanabhotla) [reply AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckNode.kt]: Hi, I did have that in mind. However, seeing as the `DeckNode` class was already mutable (due to the presence of `var collapsed`) and the fact that expand/collapse toggle functionality in the home screen (when there is no search query present) requires this mutability to be functional, making this immutable would also require the expand/collapse functionality to be refactored, which I feel is out of the scope of this particular issue and could be taken up in another issue.

That being said, I am still willing to work on this if required. Awaiting your response.

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckNode.kt]: We need to fix `collapsed`, but that's out of scope for this issue (agreed)

Adding additional mutable properties will make this fix harder.

Is it feasible to: 

* add a method which the filtering uses, producing an immutable version of `DeckNode` (`DisplayDeckNode`?) with `canCollapse: Boolean`
  * I believe this would also fix https://github.com/ankidroid/Anki-Android/issues/18278

Comment (gautambhetanabhotla) [reply AnkiDroid/src/main/java/com/ichi2/libanki/sched/DeckNode.kt]: My current implementation does fix #18278 as well, I had tested it. I will try implementing the immutable version.

File: AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/DisplayDeckNode.kt [hunk 2]
```diff
@@ -0,0 +1,127 @@
...
+            node.did,
+            node.fullDeckName,
+            node.lastDeckNameComponent,
+            node.collapsed,
+            node.children.any(),
+            node.depth,
+            node.filtered,
+            node.newCount,
+            node.lrnCount,
+            node.revCount,
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/DisplayDeckNode.kt]: Add names to arguments (Android Studio supports this with Alt+Enter on the first argument)

**Review by david-allison — CHANGES_REQUESTED** [review]
* squash commit 1 and 2 and force push
* Minor request regarding adding named arguments

Then looks EXCELLENT.

Thank you!

File: AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/DisplayDeckNode.kt (hunk 2 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/DisplayDeckNode.kt]: Screenshot 2025-06-05 at 23 35 12

**Comment by gautambhetanabhotla** [comment]
Thank you so much @david-allison for helping out! <3

**Review by david-allison — APPROVED** [review]
You had 3 commits... now 1.

See if you can split them out into 2:

* extract DisplayDeckNode and fix #18278
* Add matchesSearchOrChild and fix #18379

But... it's your first contribution, rally high quality and I don't want to nitpick this. Looks good to go in!

**Review by mikehardy — APPROVED** [review]
LGTM - thank you! - re-pushed after dropping the merge commit and rebasing to remove the conflict. 1 commit is fine I think, let's get this in

**Comment by david-allison** [comment]
Hi there @gautambhetanabhotla! This is the OpenCollective Notice for PRs merged from [2025-06-01 through 2025-06-30](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2025-06-01..2025-06-30+author%3Agautambhetanabhotla)
                      
If you are interested in compensation for this work, the process with details is here: https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

We only post one comment per person per month to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for this month

Please understand that our monthly budget is never guaranteed to cover all claims - the cap on payments-per-person may be lower, but we try to make our process as fair and transparent as possible, we just need your understanding.

Thanks!
