### PR TITLE
Correcting5516

### LINKED ISSUE #5516: [2.9 ACRA] crash in DeckTask.doInBackgroundRenderBrowserQA
This  might be data related?

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/79e230f5-d99c-4b9c-8518-9db2caaf9920

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:354)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IndexOutOfBoundsException: Index: 446, Size: 0
at java.util.ArrayList.get(ArrayList.java:437)
at com.ichi2.async.DeckTask.doInBackgroundRenderBrowserQA(DeckTask.java:9)
at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:29)
at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
... 4 more
``````

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
## Purpose / Description
Avoid changing a list used in asynchrone process. Which I believe to be the cause of bug #5516 
And seems to be good practice anyway

## Fixes
#5516 

## Approach
Instead of changing the content of the list, new lists are created and the variable is set to the new list when they are fixed. 

## How Has This Been Tested?
In the browser, I did try to create a new search. I did delete a card from the browser. I saw that everything worked as expected.

I can't test whether this bug can still occur, because I can't reproduce it easily. As I explained in the LONG commit message, this bug can occurs only by accident, if the list is cleared between two successive test of an if. So there is no way to check this can definitively not occur again 

## Learning (optional, can help others)
I should take serious note of my search (as I did in the long commit). Because otherwise I forget some paths and misses some places the objet is used.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by mikehardy** [comment]
I have touched this area as part of a quicker hack to try to avoid this in #5789 but I think creating separate lists is the real fix.

My only concern (and why I didn't do it for a fix intended for 2.9.x) is that we may duplicate so much information that we have memory pressure? So I'd like to see this tested against a massive collection which by coincidence @Arthur-Milchior I believe you have? Could you make sure you do a search in the browser and then scroll around to see how this change works massive cloned lists being rendered? Bonus points for making the search happen a few times (but maybe just searching for 'a', then 'b' etc)

If it all works then I will merge this is the more definitive fix for 2.10

**Comment by Arthur-Milchior** [comment]
I did a push to remove the merge conflict

**Comment by Arthur-Milchior** [comment]
Normally, when you change the list, there is no reference to the previous list anywhere, so it could be garbage collected quickly. I'll test if it reassure you. I would not have expected a problem here

**Comment by mikehardy** [comment]
Something went wrong with the conflict resolution and now this doesn't compile? https://travis-ci.org/ankidroid/Anki-Android/jobs/659265224#L241

Even with small things doing at least a `./gradlew jacocoUnitTestReport` (in case you don't have an emulator or connected device) is advisable just in case...

I would like to know that this has been tested with a large collection just to make sure. It *should* be fine yes

File: AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java [hunk 1]
```diff
@@ -892,13 +892,15 @@ private TaskData doInBackgroundRenderBrowserQA(TaskData... params) {
...
-            if (i >= 0 && i < items.size() && items.get(i).get("answer") == null) {
-                // Extract card item
-                Card c = col.getCard(Long.parseLong(items.get(i).get("id"), 10));
-                // Update item
-                CardBrowser.updateSearchItemQA(mContext, items.get(i), c);
-                float progress = (float) i / n * 100;
-                publishProgress(new TaskData((int) progress));
+            if (i >= 0 && i < items.size()) {
+                Map<String, String> card = items.get(i);
+                if (c.get("answer") == null) {
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java]: I think c is referenced before it is defined, I think it should be `card`

**Comment by Arthur-Milchior** [comment]
I just tested by looking for all letters from A to I. It didn't crash.
Showing a result was long, but it's really often long to load. Probably because I've got 186k cards

File: AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java (hunk 1 above)
Comment (Arthur-Milchior) [reply AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java]: Corrected

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java [hunk 2]
```diff
@@ -1161,7 +1161,7 @@ private void searchCards() {
         }
         if (colIsOpen() && mCardsAdapter!= null) {
             // clear the existing card list
-            getCards().clear();
+            mCards = new ArrayList<Map<String, String>>();
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java]: This change in particular seems really low-risk to put in 2.9.5 as a cherry-pick to try to close #5516 more - @Arthur-Milchior could this commit be picked independently in your opinion? It seems like yes to me but I value your opinion

Comment (Arthur-Milchior) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java]: Seems fine to me
