### PR TITLE
fix(import): import CSV/TSV files

### LINKED ISSUE #17866: User report: Can't see or open CSVs
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

Exact steps unknown

https://www.reddit.com/r/Anki/comments/1i8b5p3/best_way_to_easily_create_flashcards_on_ankidroid/

User is on Discord and responsive: https://discord.com/channels/368267295601983490/701939078786187315/1332453507789357116

Requested a screenshot of the file in the location, and a screenshot of AnkiDroid not picking it up

Image
Image
Image

### Expected behaviour

The CSV file is visible

### Debug info

```text
AnkiDroid Version = 2.20.1 (e32a82c33646807ea19623c9c88be38965bc07e6)
Backend Version = 0.1.48-anki24.11 (24.11 c47638ca36f99dd4f3b81ae82d964aec66e392e0)
Android Version = 13 (SDK 33)
ProductFlavor = play
Manufacturer = Google
Model = zork
Hardware = bertha
Webview User Agent = Mozilla/5.0 (Linux; Android 13; zork Build/R133-16151.13.0; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/131.0.6778.260 Safari/537.36
ACRA UUID = 2869b58f-542e-4631-b1a7-ec59807d7558
FSRS = 1.4.3 (Enabled: false)
Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

While testing, I was having huge problems with 'saving' CSVs in Google Drive, but they didn't appear in the folder I saved them in.

I don't trust files on Android at all

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
CSV files from Gmail on my S21 (Android 14) are `text/csv`

`text/tsv` is also used when coming from Gmail

## Fixes
* Fixes #17866 (maybe)

## Approach
* handle `text/csv`
* handle `text/tsv`

## How Has This Been Tested?

S21 on Android 14: I can see the Android Dev Build as an import option a few more times for CSVs

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt [hunk 1]
```diff
@@ -299,6 +299,14 @@ class IntentHandler : AbstractIntentHandler() {
         private const val CLIPBOARD_INTENT = "com.ichi2.anki.COPY_DEBUG_INFO"
         private const val CLIPBOARD_INTENT_EXTRA_DATA = "clip_data"
 
+        private val textMimeTypes =
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt:302]: those values are both here and in `ImportFileSelectionFragment`, which makes easier to forget to add a value to some of them (this one doesn't have `text/plain`, but the other does).

Extracting the list to somewhere and reusing it in both places would be better IMO

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt:302]: Any chance we could extract this to an issue that I'll deal with next week? 

I'd like user feedback ASAP, and I'm unable to dedicate all but the bare minimum this weekend

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt:302]: issue extracted as

- #17875

**Review by mikehardy — APPROVED** [review]
Let's go - will build an alpha today so we can get feedback
