### PR TITLE
fix: Sync no longer on leave study/background 

### LINKED ISSUE #19854: Sync is triggered when leaving the study screen
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

Study for at least 10 minutes then leave the study screen. A sync is triggered.

This happens in both the old and new study screens.

I think it also happens outside the study screen, for example by putting the app in the background for a second.

This didn't happen in v2.22.3.

### Expected behaviour

"Sync automatically on app start/exit if the last sync was more than 10 minutes ago."

### Debug info

```text
AnkiDroid Version = 2.23.0 (4f768aa0be34e254d65fd4ebe19781b84e8efc37)  
Backend Version = 0.1.62-anki25.09.2 (25.09.2 3890e12c9e48c028c3f12aa58cb64bd9f8895e30)  
Android Version = 13 (SDK 33)  
ProductFlavor = play  
Device Info = Xiaomi | POCO | mondrian | mondrian_global | 23013PC75G | qcom  
Webview User Agent = Mozilla/5.0 (Linux; Android 13; 23013PC75G Build/TKQ1.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/143.0.7499.115 Mobile Safari/537.36  
ACRA UUID = 3792582f-98ac-430e-ae42-4ace0156bf29  
FSRS = 5.1.0 (Enabled: true)  
Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by Giyutomioka-SS**
## Purpose / Description
After returning from the study screen, onStartupResponse() was re-firing on every resume and triggering an unexpected sync. This fix prevents that by consuming the startup response after it's handled.

## Fixes
* Fixes #19854

## Approach
When DeckPicker comes back to the foreground (e.g. after studying), the startup response flow re-emits and runs the startup code again, including auto-sync. The permissions branch already prevented this by clearing the response after use, but the success branch didn't. So after a long study session, coming back would trigger a sync again. Added the same "clear after use" line to the success branch so startup only runs once.

## How Has This Been Tested?
Manually confirmed returning to deck list after study no longer triggers an unexpected sync.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by Giyutomioka-SS** [comment]
Need some more thoughts and views on finding point 2. Does this need to be solved, or is it okay as it is now? :)

    Sync when returning to the deck list after studying 
    
    If the user returns to the deck list after a long study (e.g. 10+ min), a sync can start when 
    DeckPicker is recreated (e.g. after being destroyed in study): startup runs onFinishedStartup() 
    → automaticSync() (foreground). That path already uses the 10‑minute check, so sync only 
    runs when the interval has passed.

**Review by david-allison — COMMENTED** [review]
Great diagnostics!!

Is it feasible to handle this inside the ViewModel? 

Could you also add a test, or a `@NeedsTest`

File: AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/DeckPickerViewModel.kt [hunk 1]
```diff
@@ -79,6 +79,13 @@ class DeckPickerViewModel :
     OnErrorListener {
     val flowOfStartupResponse = MutableStateFlow<StartupResponse?>(null)
 
+    /**
+     * Clears the current startup response so it is only handled once.
+     */
+    fun consumeStartupResponse() {
+        flowOfStartupResponse.value = null
+    }
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/DeckPickerViewModel.kt]: I'd expect something along the lines of a SharedFlow with `replay = 0` [or a Channel], is there a reason this triggered on a call from the consumer (DeckPicker)

Comment (Giyutomioka-SS) [reply AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/DeckPickerViewModel.kt]: With SharedFlow `replay = 0` the startup event was sometimes emitted in handleStartup() (called from onCreate) before the collector was active (collector only starts at RESUMED), so the event was lost and startup (and logs) didn’t run on cold start / after kill.

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/DeckPickerViewModel.kt]: Ah, comment this for now, remove the `ViewModel` method and revert to your previous implementation.

DeckPicker needs a lot of work with the logic. We'll get through most of it this year.

Cheers! I'll approve afterwards.

Comment (Giyutomioka-SS) [reply AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/DeckPickerViewModel.kt]: Do you think we should add an activity-level test for this?

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/DeckPickerViewModel.kt]: Definitely

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 2]
```diff
@@ -804,6 +804,7 @@ open class DeckPicker :
                 }
 
                 is StartupResponse.Success -> {
+                    viewModel.flowOfStartupResponse.value = null // Prevent duplicate startup on re-resume
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt]: You did some investigation, and found we can't move this to the viewmodel yet

Could you add a comment, or a test?

**Review by david-allison — APPROVED** [review]
Thanks so much!!

**Comment by Giyutomioka-SS** [comment]
> BEAUTY

Hehe thanks 😁
