### PR TITLE
Bugfix/18670 cursor position retention

### LINKED ISSUE #18670: Template editor should retain where the cursor was
How to reproduce:
* open a card,
* open the note editor
* open the template edito
* tap at some place in the middle of the front template
* select the back of the card
* select the front of the card

Expected:
* the cursor (or ideally the selection) should be the same as before

Actual:
* cursor is back at position 0

How to reproduce:
* tap at some place in the middle of the front template
* select another card
* select back the first card

Expected:
* the cursor (or ideally the selection) should be the same as before

Actual:
* The cursor is missing. Still, if you type on a physical keyboard, it seems to register the touch

This is even more surprising that there are values such as `tabToCursorPosition` that seems to indicate that at some point we expected to recall where each cursor where. But this value makes little sense, as it contains one entry by index, and we should have also an entry for CSS, and a different entry for start and stop.

This value seems to be used only in `TemplatePagerAdapter`, but only during CreateFragment, not when the pages are loaded back later.

### PR DESCRIPTION
**Pull request by Aryan171**
## Purpose / Description
- Remembering and showing the cursor position while switching views in card template editor
- Adding different cursor position for different views in the card template editor

## Fixes
* Fixes #18670 

## Approach
In the card template editor when switching from front to back to css. The cursor position was not retained, this was due to faulty cursor position updation. This issue was solved by saving the cursor position when the editor view was changed and not when the text was changed.  Also only a single cursor position was stored per card, which is not enough for all the three views i.e. front, back and css. This was taken care of by storing a HashMap<Int, Int> for every card instead of a card.

## How Has This Been Tested?
On an Android 15 phone

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by Aryan171** [comment]
Closed the last PR due to some missed updates. This one contains the complete and corrected changes.

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt [hunk 1]
```diff
@@ -137,8 +138,13 @@ open class CardTemplateEditor :
...
 
-    // the position of the cursor in the editor view
-    private var tabToCursorPosition: HashMap<Int, Int?> = HashMap()
+    /**
+     * Stores the cursor position for each editor window (front, style, back) within each card template.
+     * The outer HashMap's key is the card template's ordinal (position).
+     * The inner HashMap's key is the editor window ID (e.g., R.id.front_edit).
+     * The value is the cursor position within that editor window.
+     */
+    private var tabToCursorPositions: HashMap<Int, HashMap<Int, Int>> = HashMap()
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt:147]: This would be more readable if you made private typealiases for the Ints

**Review by mikehardy — APPROVED** [review]
this looks good to me, thanks!

noting squash merge intention for maintainers

**Comment by mikehardy** [comment]
This doesn't cherry-pick cleanly and I'd prefer not to hand-hack the diff for a non-crash fix
This will release with 2.22

**Comment by david-allison** [comment]
Hi there @Aryan171! This is the OpenCollective Notice for PRs merged from [2025-07-01 through 2025-07-31](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2025-07-01..2025-07-31+author%3AAryan171)
                      
If you are interested in compensation for this work, the process with details is here: https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

We only post one comment per person per month to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for this month

Please understand that our monthly budget is never guaranteed to cover all claims - the cap on payments-per-person may be lower, but we try to make our process as fair and transparent as possible, we just need your understanding.

Thanks!
