### PR TITLE
Fix: Tell the users why card type deletion fails when this would orphan note.

### LINKED ISSUE #16789: Tell the users why card type deletion fails when this would orphan note
An orphan note is a note that has no card. For example if you have a basic and reverse card, with only the front filled, and you delete the first card type, then the note has no card left.
In AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt, when the user tries to delete a card type, if that would cause orphan, we stop the user from doing it, thanks to `deletionWouldOrphanNote`
Except that the user does not know why it failed.
We should add a simple message dialog explaining that some note would not have any card anymore.

You can imitate the lines above, where the user gets a message stating that there is a single card type and so it can't be deleted

(I should note that, in anki, we can create orphan. There is no warning. The orphan first disappear from the browser if it's opened, and then reappear if you close and reopen it.
Honestly, I prefer the way ankidroid handle it, but if a maintainer prefer to imitate anki, fine)

### PR DESCRIPTION
**Pull request by Sahil-Mandal15**
## Purpose / Description
To show a dialog when the user tries to delete a card type that would orphan note.

## Fixes
* Fixes #16789 

## Approach
The issue fix involves creating a AlertDialog that is shown when the user tries to delete a card type that would  orphan note.

## How Has This Been Tested?

Device: Realme 10 pro+
Model: RMX3686
API Level: 34-ext12

## Screenshot of the Screen with the fix
orphanotefix

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt [hunk 1]
```diff
@@ -869,7 +883,7 @@ open class CardTemplateEditor : AnkiActivity(), DeckSelectionListener {
                     // It is possible but unlikely that a user has an in-memory template addition that would
                     // generate cards making the deletion safe, but we don't handle that. All users who do
                     // not already have cards generated making it safe will see this error message:
-                    templateEditor.showSimpleMessageDialog(resources.getString(R.string.card_template_editor_would_delete_note))
+                    //   templateEditor.showSimpleMessageDialog(resources.getString(R.string.card_template_editor_would_delete_note)) // Implemented in the deleteCardTemplate
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt:886]: Don't comment out lines, we have `git` history and can remove them without worry.

File: AnkiDroid/src/main/res/values/02-strings.xml [hunk 2]
```diff
@@ -423,4 +423,8 @@ opening the system text to speech settings fails">
     <string name="play_recording">Play</string>
     <string name="next_recording">Next</string>
 
+    <!--  AlertDialog in the deleteCardTemplate  -->
+    <string name="orphan_note_title">Cannot Delete Card Type</string>
+    <string name="orphan_note_message">Deleting this card type would leave notes without a card type. Please delete the notes first.</string>
```
Comment (david-allison) [inline AnkiDroid/src/main/res/values/02-strings.xml:428]: This doesn't strike me as correctly worded, @Arthur-Milchior?

My understanding is that the issue is that deleting the card type would cause:

* A user has a note with 2 card templates, 1 of which produced a card, and one of which does not
* If a user deletes the card template which produced a card, they have a note with no cards

I'd go with

> Deleting this card type produces notes which have no cards

----

I don't think we want to inform the user of the next course of action here. Telling them to delete their notes is drastic. The expected action is "don't do this"

**Review by david-allison — CHANGES_REQUESTED** [review]

**Comment by david-allison** [comment]
Thanks! In addition to my request, there's a couple of test/lint checks to fix

File: AnkiDroid/src/main/res/values/02-strings.xml (hunk 2 above)
Comment (brishtibheja) [reply AnkiDroid/src/main/res/values/02-strings.xml:428]: The word "produce" is confusing. How about "Deleting this card type will leave your notes without any cards"?

Comment (david-allison) [reply AnkiDroid/src/main/res/values/02-strings.xml:428]: Much better, cheers!

File: AnkiDroid/src/main/res/values/02-strings.xml [hunk 3]
```diff
@@ -423,4 +423,8 @@ opening the system text to speech settings fails">
     <string name="play_recording">Play</string>
     <string name="next_recording">Next</string>
 
+    <!--  AlertDialog in the deleteCardTemplate  -->
+    <string name="orphan_note_title">Cannot Delete Card Type</string>
+    <string name="orphan_note_message">Deleting this card type will leave some notes without any cards.</string>
```
Comment (david-allison) [inline AnkiDroid/src/main/res/values/02-strings.xml:428]:
```suggestion
    <string name="orphan_note_message">Deleting this card type will leave some notes without any cards</string>
```

File: AnkiDroid/src/main/res/values/02-strings.xml [hunk 4]
```diff
@@ -423,4 +423,8 @@ opening the system text to speech settings fails">
     <string name="play_recording">Play</string>
     <string name="next_recording">Next</string>
 
+    <!--  AlertDialog in the deleteCardTemplate  -->
+    <string name="orphan_note_title">Cannot Delete Card Type</string>
```
Comment (david-allison) [inline AnkiDroid/src/main/res/values/02-strings.xml:427]:
```suggestion
    <string name="orphan_note_title">Cannot delete card type</string>
```

**Review by david-allison — APPROVED** [review]
Nitpicks, looks good to me!

**Review by david-allison — CHANGES_REQUESTED** [review]
```
CardTemplateEditorTest > testDeleteTemplateWithSelectivelyGeneratedCards FAILED
    org.opentest4j.AssertionFailedError: Did not show dialog about deleting only card? ==> expected: <Removing this card type would cause one or more notes to be deleted. Please create and save a new card type first.> but was: <Deleting this card type will leave some notes without any cards>
        at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at app//org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
        at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1156)
        at app//kotlin.test.junit5.JUnit5Asserter.assertEquals(JUnitSupport.kt:32)
        at com.ichi2.anki.CardTemplateEditorTest.testDeleteTemplateWithSelectivelyGeneratedCards(CardTemplateEditorTest.kt:267)
```

and needs a lint fix

**Comment by Sahil-Mandal15** [comment]
can you help me with the fix as this is my first PR.

**Comment by david-allison** [comment]
Sure!

Tap 'details' on the failing check:

Screenshot 2024-08-07 at 18 25 17


https://github.com/ankidroid/Anki-Android/actions/runs/10288505701/job/28474098641?pr=16840

```
  /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/01-core.xml:149: Error: The resource R.string.card_template_editor_would_delete_note appears to be unused [UnusedResources]
      <string name="card_template_editor_would_delete_note">Removing this card type would cause one or more notes to be deleted. Please create and save a new card type first.</string>
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

----

Apply this patch by copying it, double-tapping shift in Android Studio and selecting 'apply patch from clipboard'

```patch
Index: AnkiDroid/src/main/res/values/01-core.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/res/values/01-core.xml b/AnkiDroid/src/main/res/values/01-core.xml
--- a/AnkiDroid/src/main/res/values/01-core.xml	(revision da8bd8e03e75d6b356bc20949d3869e35ffb9a8d)
+++ b/AnkiDroid/src/main/res/values/01-core.xml	(date 1723052089534)
@@ -146,7 +146,6 @@
         <item quantity="one">Delete the “%2$s” card type, and its %1$d card?</item>
         <item quantity="other">Delete the “%2$s” card type, and its %1$d cards?</item>
     </plurals>
-    <string name="card_template_editor_would_delete_note">Removing this card type would cause one or more notes to be deleted. Please create and save a new card type first.</string>
     <string name="card_template_editor_save_error">Unable to save card template changes: %s</string>
     <string name="template_for_current_card_deleted">The card type for the current card was deleted.</string>

```

**Review by david-allison — APPROVED** [review]

**Comment by Sahil-Mandal15** [comment]
Thanks for the help. I did the same and i guess i fixed it.

**Comment by david-allison** [comment]
Great stuff, thanks so much!

**Comment by Sahil-Mandal15** [comment]
Thanks to you for showing patience.

**Review by mikehardy — APPROVED** [review]
LGTM - sorry this sat so long
