### PR TITLE
fix: issues with sound playing unexpectedly

### LINKED ISSUE #14414: [BUG]: audio plays randomly with Ankidroid in the background if the app is not closed normally
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

After switching away from the app (without "properly" exiting via Back Key, or swiping the app away from Overview/Recents button), after a random period of time, Ankidroid will play the card's audio even with the app in the background.  It also seems to play multiple times, cutting off to repeat itself.

### Expected behaviour

no audio playing when not in foreground.

### Actual behaviour

audio plays with app in the background

### Debug info

```text
AnkiDroid Version = 2.16.4 (67fd45a351c44c46c844aa35a402b98a2a487f68)
Android Version = 11
ProductFlavor = full
Manufacturer = Google
Model = Pixel 4a (5G)
Hardware = bramble
Webview User Agent = Mozilla/5.0 (Linux; Android 11; Pixel 4a (5G) Build/RD1A.200810.022.A4; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.106 Mobile Safari/537.36
ACRA UUID = edc1cf0a-73f9-4d8a-b7c2-9808416b612f
New schema = false
Scheduler = std2
Crash Reports Enabled = true
DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### LINKED ISSUE #14480: [Bug] Front of card not shown when returning to AnkiDroid from the background
###### Reproduction Steps

1.  Launch ankidroid app, open a card with audio. 
2. Change to another app, or push ankidroid to the background by going back to the home screen 
3. The audio file with the card will keep on replaying. Sometimes it repeats itself without finishing the previous time
4. When returning to the ankidroid app, the words on the front of the card is gone from the view. 

###### Expected Result
The audio file should not play in the background. 

The front of the card should be displayed. 

###### Actual Result
Audio file plays repeatedly in the background, and the card view is bugged 

The front of the card is also not displayed when returning to the app

###### Debug info

AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)
Android Version = 11
ProductFlavor = play
Manufacturer = Xiaomi
Model = Redmi Note 8
Hardware = qcom
Webview User Agent = Mozilla/5.0 (Linux; Android 11; Redmi Note 8 Build/RKQ1.201004.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/117.0.0.0 Mobile Safari/537.36
ACRA UUID 842fe7cf-0e14-44a4-abc6-3e5ddbe8d583
New schema = false
Scheduler = std2
Crash Reports Enabled = true
DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### LINKED ISSUE #14496: [BUG]: Card audio plays unexpectedly when changing deck options
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

* Enable new backend
* Have cards with audio on the front that need to be studied today
* Long press on deck
* Select deck options
* Make any adjustment
* Save

### Expected behaviour

Options are saved

### Actual behaviour

Options are saved, and the audio is played from the next card needing to be studied, even though that card is not displayed (still in deck viewer)

### Debug info

```text
AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)

Android Version = 12

ProductFlavor = full

Manufacturer = samsung

Model = SM-G970U

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-G970U Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36

ACRA UUID = 9e04916e-4ad1-45aa-b58c-9624d0eb41b6

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

It's not just the deck options that causes this, I think I remember it happening when toggling the new backend, too.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### LINKED ISSUE #14616: [BUG]: Sound doesn't stop when the reviewer screen goes to another one
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Play an audio file on the card
2. Tap "Show answer" before it ends 

### Expected behaviour

The playback stops.

### Actual behaviour

The playback keeps playing.

### Debug info

```text
AnkiDroid Version = 2.17alpha2 (19ad510c0a44c4fa140394363a0df3bd8ab177d8)

Android Version = 11

ProductFlavor = play

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/117.0.0.0 Mobile Safari/537.36

ACRA UUID = 460ff45d-dade-406e-b1ac-56d9175ebdb5

Crash Reports Enabled = true


DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

- The same is true for:
  - "Suspend", 
  - "Bury"
  - "Delete note" -> "Delete"
  - Show the home screen of the system
  - Show another app screen

- Originally reported at https://github.com/ankidroid/Anki-Android/issues/14494#issuecomment-1784107346

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### LINKED ISSUE #14788: [BUG]: Review code keeps running after review is finished, even after turning the screen off
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Finish a deck review on a card that has some audio and that will re-appear in a minute or so (Using Again button, followed by Hard button usually does the trick)

2. After finishing this card, you will be dumped back to deck list.

3. Turn the screen off

4. Wait a minute

### Expected behaviour

Nothing should happen. Review has been finished and screen is off, so AnkiDroid should stay put.

### Actual behaviour

After a minute of screen being off, you will suddenly hear an audio for a card that you were reviewing before. When you turn on the screen, you will notice that AnkiDroid started review on its own.

I would argue that this is a double bug in one:

1. AnkiDroid should not start any reviews on its own from the deck list. It should not do anything until user manually taps on a deck.
2. AnkiDroid should most definitely not make any sounds when screen is off.

### Debug info

```text
AnkiDroid Version = 2.17alpha5 (4fc8af92973d8d502e0139d0dd5372415444ca1f)

Android Version = 13

ProductFlavor = play

Manufacturer = Google

Model = Pixel 7 Pro

Hardware = cheetah

Webview User Agent = Mozilla/5.0 (Linux; Android 13; Pixel 7 Pro Build/TQ3A.230901.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/119.0.6045.163 Mobile Safari/537.36

ACRA UUID = 85314e7b-0d43-4b96-a861-e60e9dd7f848

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

Same root cause (code running in the background when it shouldn't) likely also causes #14709 and #14614

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison**
## Fixes
* Fixes #14414
* Fixes #14616
* Fixes #14496
* Fixes #14788
* Probably Fixes #14480

## Approach
* code to stop sounds from playing if the activity is in the wrong state
  * I suspect this occurs after a WebView OOM in the background 
* defer `opChanges` handling to after `onResume()`
* fix `Sounds.kt` breakage

## How Has This Been Tested?
* Add audio to a note
* Change to the answer
* Audio now stops playing

----

* switch to card browser
* switch back

No audio is played

----

* switch to card browser
* mark a note
* audio is played after returning to card viewer

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
subtle - especially the second commit, but appears to what it intends to do

Certainly squashes a nest of bugs

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt [hunk 1]
```diff
@@ -2519,10 +2555,9 @@ abstract class AbstractFlashcardViewer :
     }
 
     override fun opExecuted(changes: OpChanges, handler: Any?) {
-        if ((changes.studyQueues || changes.noteText || changes.card) && handler !== this) {
-            Timber.d("opExecuted: redraw")
-            launchCatchingTask { updateCardAndRedraw() }
-        }
+        if (handler === this) return
+        refreshRequired = ViewerRefresh.updateState(refreshRequired, changes)
+        refreshIfRequired()
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt:2560]: this part is curious - if the method is called with no parameters, then the default for `isResuming` in `refreshIfRequired` will be false, so it will fall into the "maybe log, but always just nop / return" conditional case won't it?

So is this call to `refreshIfRequired` always reduced to a nop with no parameter isResuming true specified?

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt:2560]: The condition is: "is not resuming AND the state is not RESUMED"

if the state is resumed, OR if the state is not resumed , but it's called from `onResume` then `refreshIfRequired` executes immediately

This needs more documentation or a rewrite in the logic to make it more clear.

Anything in your perspective?

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt:2560]: I think it is just difficult for me personally to mentally do the double-negation then boolean AND, feels like a tortured way to squeeze an early-return out of it.

This is one where I think especially since the return branch really does nothing it could be the inverse and read more easily

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt [hunk 2]
```diff
@@ -579,6 +589,26 @@ abstract class AbstractFlashcardViewer :
...
+            }
+            return
+        }
+        // refresh
+        refreshRequired?.let {
+            Timber.d("refreshIfRequired: redraw")
+            // if changing code, re-evaluate `refreshRequired = null` in `updateCardAndRedraw`
+            launchCatchingTask { updateCardAndRedraw() }
+            refreshRequired = null
+        }
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt:611]: Just a stab at inversing the boolean, not sure spacing is correct and may have borked the actual conditional test 

```suggestion
        // refresh if we are already resumed or we are resuming
        if (isResuming || lifecycle.currentState.isAtLeast(Lifecycle.State.RESUMED)) {
          refreshRequired?.let {
              Timber.d("refreshIfRequired: redraw")
              // if changing code, re-evaluate `refreshRequired = null` in `updateCardAndRedraw`
              launchCatchingTask { updateCardAndRedraw() }
              refreshRequired = null
          }
        } else {
            if (refreshRequired != null) {
                Timber.d("deferred refresh as activity was not STARTED")
            }
            return
        }
```

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt]: Sorry! I did the work before seeing this comment. Re-pushed as the following, which I feel is a little neater (no `else { if }` and no `return`

```kotlin
        if (isResuming || lifecycle.currentState.isAtLeast(RESUMED)) {
            refreshRequired?.let {
                Timber.d("refreshIfRequired: redraw")
                // if changing code, re-evaluate `refreshRequired = null` in `updateCardAndRedraw`
                launchCatchingTask { updateCardAndRedraw() }
                refreshRequired = null
            }
        } else if (refreshRequired != null) {
            // onResume() will execute this method
            Timber.d("deferred refresh as activity was not STARTED")
        }
```

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt]: yeah, that doesn't hurt my head when I read it,  +1

**Review by mikehardy — APPROVED** [review]
re-approving now that it's even clearer - got a bunch of fixes queued up for next alpha, I'm going to merge this in and I am mentally pointing towards a new alpha new - pending backend release ingestion / i18n sync / dependencies / anything else that can merge...
