### PR TITLE
fix(study-screen): copying to clipboard 

### LINKED ISSUE #20719: New study screen is blocking some of the JavaScript features
See https://forums.ankiweb.net/t/new-study-screen-is-blocking-some-of-the-javascript-features/67530.

[Brayan asked for this issue](https://forums.ankiweb.net/t/new-study-screen-official-thread/67394/131?u=zornhadnochoice).

### PR DESCRIPTION
**Pull request by BrayanDSO**
## Purpose / Description

fixes an issue in a (too) hacky notetype that creates an invisible text area and uses a deprecated HTML method to copy stuff to the clipboard

https://forums.ankiweb.net/t/new-study-screen-is-blocking-some-of-the-javascript-features/67530

Instead of using a `window.location.href`, which stops the event propagation, I used POST requests

Now, communicating from the JS code to the Kotlin code is mixed between `window.location.href` GET requests and POST requests, so it should be discussed whether the old requests should be migrated to POST requests as well

## Fixes
* Fixes #20719

## How Has This Been Tested?

Emulator 37

[Screen_recording_20260422_071636.webm](https://github.com/user-attachments/assets/87491c65-8f83-497b-bc3b-3867817bb997)

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — APPROVED** [review]
LGTM, split off the thought into an issue

File: AnkiDroid/src/main/assets/scripts/ankidroid-reviewer.js [hunk 1]
```diff
@@ -31,13 +31,47 @@ globalThis.ankidroid.onTypeAnswerKeyDown = function (event) {
     }
 };
 
-document.addEventListener("focusin", event => {
-    window.location.href = `ankidroid://focusin`;
-});
+// ============================================================================
+// Event listeners
+// ============================================================================
```
Comment (criticalAY) [inline AnkiDroid/src/main/assets/scripts/ankidroid-reviewer.js:36]: Is this a comment from AI? This is unusual

Comment (BrayanDSO) [reply AnkiDroid/src/main/assets/scripts/ankidroid-reviewer.js:36]: I did use AI for trying to get a solution, but it didn't give me any that worked without any caveats. Using POST requests was my idea. Not sure if it's useful to note that AI couldn't help me.

The comment sections were made because I put the listeners under an IIFE, and I used an IIFE because I didn't want the `isTextInput` method to be public.

The poor description is post-implementation documentation laziness. I'll make them more descriptive.

**Review by criticalAY — APPROVED** [review]
