### PR TITLE
Fix #8229 [Bug] {{cloze:Text}} ignores repeated words and just check first of them

### LINKED ISSUE #8229: [Bug] {{cloze:Text}} ignores repeated words and just check first of them
AnkiDroid ver 2.14.6
1. in card filed I use "This is {{c1::test}} which is containing {{c1::test}} word twice"
2. in Front and Back template I have "{{cloze:Field_name}}"
3. now when I Type answer like "test, test" in front and tap the answer:

I expect this: 
test, test (Check mark)

but I wee this:
test, test (first highlighted in green and second in red followed by downside arrow on next line and after that shows answer like the following line)
test (one time, so It recognize it as false answer and there is no check button)

### PR DESCRIPTION
**Pull request by LittleFish33**
## Purpose / Description
Fix #8229 [Bug] {{cloze:Text}} ignores repeated words and just check first of them

## Fixes
Fixes  #[8229](https://github.com/ankidroid/Anki-Android/issues/8229)

## Approach
In the original file, the project uses `set<String>` to save the correct answer to use for {{type::cloze::NN}} fields (refer to the `private String contentForCloze(String txt, int idx) ` function in AbstractFlashcardViewer.java). In this case, {{cloze:Text}} ignores repeated words because there cannot be duplicate elements in a set. While in the Desktop version, close is handled by:
```python
# https://github.com/ankitects/anki/blob/main/qt/aqt/reviewer.py
# lines 500-516
def _contentForCloze(self, txt: str, idx: int) -> str:
    matches = re.findall(r"\{\{c%s::(.+?)\}\}" % idx, txt, re.DOTALL)
    if not matches:
        return None

    def noHint(txt: str) -> str:
        if "::" in txt:
            return txt.split("::")[0]
        return txt

    matches = [noHint(txt) for txt in matches]
    uniqMatches = set(matches)
    if len(uniqMatches) == 1:
        txt = matches[0]
    else:
        txt = ", ".join(matches)
    return txt
```
Therefore, I use `ArrayList<String>` to make it consistent with the Desktop version. Unit test has been added.

## How Has This Been Tested?

working well on my pixel phone

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 1]
```diff
@@ -843,13 +842,23 @@ private String contentForCloze(String txt, int idx) {
...
         StringBuilder resultBuilder = new StringBuilder();
-        for (String match : matches) {
-            resultBuilder.append(prefix);
-            resultBuilder.append(match);
-            prefix = ", ";
+        // Make it consistent with the Desktop version (see issue #8229)
+        if (uniqMatches.size() == 1){
+            resultBuilder.append(matches.get(0));
+        } else {
+            for (String match : matches) {
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:857]: You may just want to use https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#join(java.lang.CharSequence,java.lang.Iterable) to avoid to write the loop

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 2]
```diff
@@ -843,13 +842,23 @@ private String contentForCloze(String txt, int idx) {
...
+
         // Now do what the pythonic ", ".join(matches) does in a tricky way
         String prefix = "";
         StringBuilder resultBuilder = new StringBuilder();
-        for (String match : matches) {
-            resultBuilder.append(prefix);
-            resultBuilder.append(match);
-            prefix = ", ";
+        // Make it consistent with the Desktop version (see issue #8229)
+        if (uniqMatches.size() == 1){
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:854]: There is no need for special case, the existing code was already ensuring that the prefix was empty the first time so that commas where added only with element 2 and forward

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 3]
```diff
@@ -824,14 +824,13 @@ String typeAnsAnswerFilter(String buf, String userAnswer, String correctAnswer)
...
-    private String contentForCloze(String txt, int idx) {
+    @VisibleForTesting
+    protected String contentForCloze(String txt, int idx) {
         @SuppressWarnings("RegExpRedundantEscape") // In Android, } should be escaped
         Pattern re = Pattern.compile("\\{\\{c" + idx + "::(.+?)\\}\\}");
         Matcher m = re.matcher(txt);
-        Set<String> matches = new LinkedHashSet<>(); // Size can't be known in advance
-        // LinkedHashSet: make entries appear only once, like Anki desktop (see also issue #2208), and keep the order
-        // they appear in.
+        ArrayList<String> matches = new ArrayList<>();
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:832]: NIT: The type may be simply `List<String>` or even `Iterable<String>`. I like for type to indicates only what we need to use instead of containing the concrete type used.

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 4]
```diff
@@ -843,13 +842,23 @@ private String contentForCloze(String txt, int idx) {
             }
             matches.add(groupOne);
         }
+
+        Set<String> uniqMatches = new LinkedHashSet<>(matches);
+        // LinkedHashSet: make entries appear only once, like Anki desktop (see also issue #2208), and keep the order
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:847]: This comment do not indicate anymore the reason for using a set. 
You can instead state "Allow to check whether there are distinct strings"

You can use a HashSet, you don't need it to be linked at all anymore.

I find it inelegant. Instead, you could just have checked whether a string is distinct from the first string of the set. However, you're porting upstream code, so I guess we can keep this code for consistency.

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 5]
```diff
@@ -843,13 +842,23 @@ private String contentForCloze(String txt, int idx) {
...
+        // they appear in.
+
         // Now do what the pythonic ", ".join(matches) does in a tricky way
         String prefix = "";
         StringBuilder resultBuilder = new StringBuilder();
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:852]: If for some reason you can't use String.join as suggested below, then you should at least move the StringBuilder inside the else branch. There is no reason to construct a StringBuilder in the if branch. Instead, you could just have a String variable which is assigned directly to `matches.get(0)`

File: AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.java [hunk 6]
```diff
@@ -372,6 +372,21 @@ public void testEditingCardChangesTypedAnswerOnDisplayAnswer() {
...
 
 
+    @Test
+    public void testClozeWithRepeatedWords() {
+        // 8229
+        NonAbstractFlashcardViewer nafv = getViewer();
+
+        String buf1 = "This is {{c1::test}} which is containing {{c1::test}} word twice";
+        String expectedOutput1 = "test";
+        assertEquals(expectedOutput1, nafv.contentForCloze(buf1, 1));
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.java:382]: I don't think it's really useful to introduce the extra variables `expectedOutput`, it's short and do not increase readability.

Concerning `buf1` and `buf2` I don't really see the point either, and at least thing a more descriptive variable name should be used

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 7]
```diff
@@ -824,14 +824,13 @@ String typeAnsAnswerFilter(String buf, String userAnswer, String correctAnswer)
      * @param idx The index of the cloze to use
      * @return A string with a comma-separeted list of unique cloze strings with the correct index.
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:825]: remove "unique" as it is not always the case anymore. Instead you'll need to write a longer intro to this javadoc

**Review by Arthur-Milchior — COMMENTED** [review]
Thanks for this PR, and for doing the job of looking upstream and documenting. I've got a few remarks on the code, and mostly a remark on the commit.

I'd like your commit title to be easy to understand without context. When we'll look at all git history and the git blame of this file, we won't know what #8229 is. This message even seems to indicate that the change you introduce is that now we'll ignore other words.

Instead, you can state:
> contentForCloze takes repeated strings into accounts

A link to upstream commits which introduced this feature would really help. And also a quick description in English of the two cases we have to consider. It's really not intuitive to me and being able to really understand just by reading the commit may be extremely useful.

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java (hunk 2 above)
Comment (LittleFish33) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:854]: The special case here is to keep the logic consistent with the desktop version, although it seems a bit silly. I think the bottom line is to make sure that the logic is consistent between desktop and android versions (see  [#8229](https://github.com/ankidroid/Anki-Android/issues/8229) for details). Although another solution is to change the logic in desktop and android together.

**Comment by Arthur-Milchior** [comment]
@LittleFish33 Do you intend to still work on it ?

You don't have to answer quickly, just wanted to know whether you'll update

**Comment by LittleFish33** [comment]
@Arthur-Milchior Sorry, I would like to work on it. but I'm not sure how to deal with this problem. Because in my opinion, it is very important to keep the consistency with the desktop version. I'm waiting for an explicit reply.

> There is no need for special case, the existing code was already ensuring that the prefix was empty the first time so that commas where added only with element 2 and forward. 

> The special case here is to keep the logic consistent with the desktop version, although it seems a bit silly. I think the bottom line is to make sure that the logic is consistent between desktop and android versions (see [#8229](https://github.com/ankidroid/Anki-Android/issues/8229) for details). Although another solution is to change the logic in desktop and android together.

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java (hunk 2 above)
Comment (Arthur-Milchior) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:854]: Oops, sorry I missed this message.

On #8229 dae confirmed that it was the way things are intended, so it's fine by me actually. Really surprising, but it's okay to keep this. 
My other comments are still valid.

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java (hunk 1 above)
Comment (LittleFish33) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:857]: When I use `String.join()`, I get an error, `call requires level 26(current min is 21)`. Therefore, to use `String.join`, I need to add an annotation, `@RequiresApi(api = Build.VERSION_CODES.O)`. I think this is there is the reason why the original code uses for loop.

Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:857]: Common issue! Use `android.text.TextUtils.join`

Comment (LittleFish33) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java]: Has updated the code.

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 8]
```diff
@@ -843,15 +844,15 @@ private String contentForCloze(String txt, int idx) {
...
-        StringBuilder resultBuilder = new StringBuilder();
-        for (String match : matches) {
-            resultBuilder.append(prefix);
-            resultBuilder.append(match);
-            prefix = ", ";
+
+        Set<String> uniqMatches = new HashSet<>(matches); // Allow to check whether there are distinct strings
+
+        // Make it consistent with the Desktop version (see issue #8229)
+        if (uniqMatches.size() == 1){
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:851]: Sorry!

```suggestion
        if (uniqMatches.size() == 1) {
```

**Review by david-allison-1 — APPROVED** [review]
Minor nitpick, code is clean, and a test! Looks good to go from my end. Thanks!!!

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java (hunk 1 above)
Comment (Arthur-Milchior) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java]: My bad, I didn't know about it. It seems instead https://developer.android.com/reference/android/text/TextUtils#join(java.lang.CharSequence,%20java.lang.Iterable) should have been used

Comment (Arthur-Milchior) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java]: I'm late. Thanks

**Review by Arthur-Milchior — APPROVED** [review]

**Review by mikehardy — APPROVED** [review]
Nice!

**Comment by mikehardy** [comment]
Hi there!

Just a friendly notice (one per person for PRs merged in March, regardless of PR quantity) that we try to process OpenCollective payments monthly - it's time for March 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

Thanks!
