### PR TITLE
Fix app crashing if deck from shortcut does not exist anymore

### LINKED ISSUE #12910: [Bug]application crashes due to invalid shortcut
###### Reproduction Steps

1. Create a deck shortcut
2. delete the deck
3. click the shortcut

###### Expected Result
The shortcut is removed as soon as the deck is removed from the collection

###### Actual Result
Shortcut is not removed and results in a crash

###### Debug info
AnkiDroid Version = 2.16alpha90

Android Version = 12

Manufacturer = Google

Model = sdk_gphone64_x86_64

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 12; sdk_gphone64_x86_64 Build/SE1A.220630.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.114 Mobile Safari/537.36

ACRA UUID = 788ac1c2-9dfe-4386-a6c5-ca62fa05ac23

New schema = true

Scheduler = std3

Crash Reports Enabled = false

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by RobozinhoD**
## Fixes
Fixes #12910

## Approach
Return early if the deck does not exist anymore (col.decks.select(did) was doing the crashes)

## How Has This Been Tested?

1. Long press a deck
2. Create shortcut
3. Delete the deck
4. Open the shortcut
5. Don't see any crashes

Reviewer.kt is too big and clumped, if I may say so, to me to deal with it right now so I left some TODOs. Not crashing is already some progress to me 😁

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by BrayanDSO** [comment]
Tested here and it doesn't crash anymore, and fine by me having the TODOs. 

Please remember to peel issues for the TODOs after this get a second approval

**Review by BrayanDSO — APPROVED** [review]

**Comment by criticalAY** [comment]
Nice to see it getting fixed but as I mentioned on DC we should have a snackbar/toast for now till we fix the shortcut itself because in the present scenario it's just opening the application and doing nothing.
@BrayanDSO waiting for response

**Comment by BrayanDSO** [comment]
Do you mean Discord by DC? Didn't know people did this abbreaviation. Anyway, haven't found anything about snackbar/toast  there nor on the issue, so I don't know exactly what you are proposing.

> in the present scenario it's just opening the application and doing nothing

Here at least, it opens the app on the specified deck so the user can start studying. If the deck was deleted, `@`RobozinhoD's fix makes it to open the default deck instead. This is not the ideal, of course, but they already added a TODO to fix it, which should be peeled into an issue. As the PR author manifested that they only want to do this change, the PR looks fine. Any step forward, like avoiding crashes, is welcomed.

**Comment by criticalAY** [comment]
> Do you mean Discord by DC? Didn't know people did this abbreaviation. Anyway, haven't found anything about snackbar/toast there nor on the issue, so I don't know exactly what you are proposing.
> 
> > in the present scenario it's just opening the application and doing nothing
> 
> Here at least, it opens the app on the specified deck so the user can start studying. If the deck was deleted, `@`RobozinhoD's fix makes it to open the default deck instead. This is not the ideal, of course, but they already added a TODO to fix it, which should be peeled into an issue. As the PR author manifested that they only want to do this change, the PR looks fine. Any step forward, like avoiding crashes, is welcomed.

ok fine as the main issue is of the shortcut

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt [hunk 1]
```diff
@@ -297,6 +297,14 @@ open class Reviewer : AbstractFlashcardViewer() {
         val did = extras.getLong("deckId", Long.MIN_VALUE)
         Timber.d("selectDeckFromExtra() with deckId = %d", did)
 
+        // deckId does not exist, load default (#12910)
+        // TODO delete deck shortcut if the deck does not exist anymore
+        // TODO don't start reviewing the default deck if a shortcut for a deleted deck is launched
+        if (col.decks.get(did, _default = false) == null) {
+            Timber.d("selectDeckFromExtra() deckId '%d' doesn't exist", did)
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt:304]: I suggest this is actually much higher - it should be a warn level log. My rule of thumb for logs is:
- error: this is something terrible, we probably cannot recover and for data safety should exit the app / log a report in our crash system
- warn: this is something terrible, but we can recover and operate normally. Log above info at least so that if it does crash later it shows up in our crash report system's logcat extract
- info: this is interesting enough that if there is a crash we want to see it in crash system logcat report
- debug: only useful for developers
- verbose: only useful for developers inspecting an area deeply

A crash would be error, this avoids a crash but is a serious problem (for the user at least) and we recover, so warn

```suggestion
            Timber.w("selectDeckFromExtra() deckId '%d' doesn't exist", did)
```

**Review by mikehardy — APPROVED** [review]
I think the change is good also - I went and committed the trivial log level change so I can merge this in, I love merging crash fixes!

As mentioned elsewhere, please create a tracking issue (or issues?) for the TODOs. It does not imply that you must do them (it's open source, we're volunteers, no worries) but will keep them in the list. Thanks!
