### PR TITLE
Issue7748/paste image failure

### LINKED ISSUE #7748: Pasting Images: Fails if can't get filename
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/3453b92e-3a46-4a22-86b2-fc930f50e1d3

Not sure how to get the extension, but this can easily be caught: https://github.com/ankidroid/Anki-Android/blob/97d779b94069540a4799badfef4a0b8c0a35daaa/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java#L1544-L1548
```
android.database.sqlite.SQLiteException: no such column: _display_name (code 1 SQLITE_ERROR[1]): , while compiling: SELECT _display_name FROM ClipboardImageTable WHERE (id=855) ORDER BY _data
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:179)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
at android.content.ContentResolver.query(ContentResolver.java:809)
at android.content.ContentResolver.query(ContentResolver.java:759)
at android.content.ContentResolver.query(ContentResolver.java:717)
at com.ichi2.anki.NoteEditor.loadImageIntoCollection(NoteEditor.java:1)
at com.ichi2.anki.NoteEditor.onImagePaste(NoteEditor.java:2)
at com.ichi2.anki.NoteEditor.v(Unknown Source:0)
at com.ichi2.anki.e5.onImagePaste(Unknown Source:2)
at com.ichi2.anki.FieldEditText.onImagePaste(FieldEditText.java:1)
at com.ichi2.anki.FieldEditText.a(FieldEditText.java:6)
at com.ichi2.anki.x2.onCommitContent(Unknown Source:9)
at androidx.core.view.inputmethod.InputConnectionCompat$1.commitContent(InputConnectionCompat.java:1)
at android.widget.TextView.commitImage(TextView.java:17342)
at android.widget.TextView.pasteClipBoardData(TextView.java:16748)
at android.widget.TextView.access$4300(TextView.java:438)
at android.widget.TextView$TextViewClipboardEventListener$1.run(TextView.java:16676)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7094)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

### PR DESCRIPTION
**Pull request by mikehardy**
## Purpose / Description

Even if for some reason ContentResolver throws while fetching DISPLAY_NAME from MediaColumns, continue attempting to paste the image

## Fixes
Fixes #7748
Related #7754 - this stopped app from crashing +1

## Approach
Eat the underlying SQLiteException and return null, calling method tests for null (I checked all callers, there is only one caller...) and if it is null it will try a secondary method. Second level calling method eats Exception so no crash is possible still

## How Has This Been Tested?

Untested, just code inspection (only one caller to null check, all exceptions still eaten to prevent crash)

## Learning (optional, can help others)

There is no understanding of when or why pasting images can cause a query for DISPLAY_NAME on the pasted image to fail, but it is happening in Android 11, so this could be peeled out as a separate issue for low-priority investigation

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.java [hunk 1]
```diff
@@ -78,12 +82,15 @@ private static String getFilenameViaMimeType(ContentResolver contentResolver, Ur
...
         // 7748: android.database.sqlite.SQLiteException: no such column: _display_name (code 1 SQLITE_ERROR[1]): ...
         try (Cursor c = contentResolver.query(uri, new String[] { MediaStore.MediaColumns.DISPLAY_NAME }, null, null, null)) {
-            c.moveToNext();
-            filename = c.getString(0);
+            if (c != null) {
+                c.moveToNext();
+                return c.getString(0);
+            }
+        } catch (SQLiteException e) {
+            Timber.w(e, "getFilenameViaDisplayName ContentResolver query failed.");
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.java:92]: Can we also report this to acra?

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
One query. Good otherwise

File: AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.java (hunk 1 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.java:92]: I debated that. What I want to do is create a new issue where someone can do a deep dive on what's going on here, but at this point it's just ACRA noise for us. It's definitely in Android 11 so it means this is a real failure, but as ACRA report it is no longer actionable I think - let me create a new issue with contents of investigation, but then I'd rather it not go to ACRA anymore. We know it happens, we no longer crash, and now we have reports from existing instrumentation, I think ACRA has served it's purpose here?

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.java:92]: @david-allison-1 #8937 logged to continue the effort

Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/utils/ContentResolverUtil.java:92]: OK

**Review by david-allison-1 — APPROVED** [review]

**Comment by mikehardy** [comment]
@Arthur-Milchior not sure if you're around - but if you give this a review and it looks good I can include it in release shortly
