### PR TITLE
Test: Check if Illegal Characters at the start of Fields get handled

### LINKED ISSUE #8612: Create unit test verifying illegal characters (like '##') may not be used in field names
#8388 is the original issue, and #8389 fixes it, but a unit test that verifies those illegal characters can't be entered would be nice to have

The strategies below could work.

You could also extend Robolectric test, get the dialog "open" (virtually) and attempt to enter an illegal field, verifying it fails.

---------

First attempt would be to extract `TaskManager.launchCollectionTask(new CollectionTask.AddField(mMod, fieldName), listener);` to a method and override it in a test.

If that's difficult, a "TODO" in a test class to write a test for this issue would be fine

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/issues/8389#issuecomment-809842496_

### PR DESCRIPTION
**Pull request by dorrin-sot**
## Purpose / Description
There didn't exist a test that checked if illegal characters would be omitted from the start of field names

## Fixes
Fixes #8612 

## Approach
Iterated through an array of illegal characters and for each of them opened a Dialog and EditText Virtually, set the text of the EditText to an invalid fieldName and clicked the confirm button of the Dialog. When the button of the Dialog is pressed, a refactored method `ModelFieldEditor::addField(EditText)` or `ModelFieldEditor::renameField(EditText)` gets called depending on which test method we are on.

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java [hunk 1]
```diff
@@ -0,0 +1,155 @@
...
+
+@RunWith(AndroidJUnit4.class)
+public class ModelFieldEditorTest extends RobolectricTest {
+    /**
+     * Tests if field names with illegal characters get removed from beginning of field names when adding field
+     */
+    @Test
+    public void testIllegalCharactersInFieldName_addField() {
+        // iterate through the forbidden characters and test
+        for (String forbidden : new String[] {"#", "^", "/", " ", "\t"}) {
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java:32]: These tests would be better as `@Parameterized`, therefore we can see individual failures, rather than one failure which would potentially hide others

File: AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java [hunk 2]
```diff
@@ -0,0 +1,155 @@
+package com.ichi2.anki;
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java:1]: Could you add a copyright header?

File: AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java [hunk 3]
```diff
@@ -0,0 +1,155 @@
...
+
+    /**
+     * Assert that model's fields doesn't contain the forbidden field name
+     *
+     * @param forbiddenFieldName The forbidden field name to identify
+     */
+    private void testForIllegalCharacters(String forbiddenFieldName) {
+        List<String> modelFields = getCurrentDatabaseModelCopy("Basic").getFieldsNames();
+        String fieldName = getCurrentDatabaseModelCopy("Basic").getFieldsNames()
+                .get(modelFields.size() - 1);
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java:63]: I think this was your intention
```suggestion
        String fieldName = modelFields.get(modelFields.size() - 1);
```

File: AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java [hunk 4]
```diff
@@ -0,0 +1,155 @@
...
+
+        assertThat("forbidden character detected!", !fieldName.equals(forbiddenFieldName));
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java:65]: Might need to check the syntax, but this gives a better error message
```java
        assertThat("forbidden character detected!", fieldName, not(equalTo(forbiddenFieldName));
```

File: AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java [hunk 5]
```diff
@@ -0,0 +1,155 @@
...
+                        );
+
+                        // add or rename field
+                        if (isForAddField) {
+                            modelFieldEditor.addField(fieldNameInput);
+                        } else {
+                            modelFieldEditor.renameField(fieldNameInput);
+                        }
+                    } catch (ConfirmModSchemaException exception) {
+                        exception.log();
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java:126]: throw the exception - test failures are good, they indicate problems

File: AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java [hunk 6]
```diff
@@ -0,0 +1,155 @@
...
+            Map.Entry<Long, Model> idModel = iterator.next();
+            long id = idModel.getKey();
+            Model model = idModel.getValue();
+
+            if (model.getString("name").equals(modelName)) {
+                return id;
+            }
+        }
+        return 0;
+    }
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java:154]: Optional. Regardless, I'd question why you're using an iterator + `while` over a foreach loop

```java
        return getCol().getModels().getModels().entrySet()
                .stream()
                .filter(kvp -> kvp.getValue().getString("name").equals(modelName))
                .map(Map.Entry::getKey) // get the ID
                .findFirst()
                .orElse(0L);
```

File: AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java [hunk 7]
```diff
@@ -242,6 +238,25 @@ private void addFieldDialog() {
     }
 
 
+    @VisibleForTesting
+    void addField(EditText mFieldNameInput) throws ConfirmModSchemaException {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java:242]: `fieldName`

File: AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java [hunk 8]
```diff
@@ -242,6 +238,25 @@ private void addFieldDialog() {
     }
 
 
+    @VisibleForTesting
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java:241]:
```java
    @VisibleForTesting(otherwise = VisibleForTesting.NONE)
```

File: AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java [hunk 9]
```diff
@@ -408,6 +423,12 @@ private void dismissProgressBar() {
         mProgressDialog = null;
     }
 
+    @VisibleForTesting
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java:426]:
```java
    @VisibleForTesting(otherwise = VisibleForTesting.NONE)
```

File: AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java (hunk 7 above)
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java:242]: I find it useful to move the `VisibleForTesting` methods to the bottom of the class if they're unused - helps move them out of thought when reading the code, it took me a double-take to see what was happening in this change due

File: AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java [hunk 10]
```diff
@@ -0,0 +1,155 @@
...
+@RunWith(AndroidJUnit4.class)
+public class ModelFieldEditorTest extends RobolectricTest {
+    /**
+     * Tests if field names with illegal characters get removed from beginning of field names when adding field
+     */
+    @Test
+    public void testIllegalCharactersInFieldName_addField() {
+        // iterate through the forbidden characters and test
+        for (String forbidden : new String[] {"#", "^", "/", " ", "\t"}) {
+            String fieldName = setupInvalidFieldName(forbidden, true);
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java:33]: (optional): I'd be tempted to swap this boolean for an enum: `ADD_FIELD|RENAME_FIELD`

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
Really clean, thanks!

----

Are there other designs that we can use for the method extraction? I worry that the code inside `confim` is structurally far from the code in `try`, whereas in reality they're doing the same things.

Maybe we want the `modSchema` outside the method, or passed in as a runnable?

```
Runnable confirm = () -> {
                            mCol.modSchemaNoCheck();
                            TaskManager.launchCollectionTask(new CollectionTask.AddField(mMod, fieldName), listener);
                            dismissContextMenu();
                        };
```

----

Other than that, few nitpicks and we're good to go. Feel free to disagree with anything, a PR is a discussion.

File: AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java (hunk 6 above)
Comment (dorrin-sot) [reply AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java:153]: Oh, I did try to use Stream functions via `Stream.of(models)` but for some reason it wouldn't work. I'll fix it right now!

File: AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java (hunk 7 above)
Comment (dorrin-sot) [reply AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java:242]: oh ok sorry. Do I move other `VisibleForTesting` methods from other classes to bottom too or is `ModelFieldEditor` good enough?

Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java:242]: Just the ones you're working on is fine - it's an optional preference of mine, ignore if you disagree

Comment (dorrin-sot) [reply AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java:242]: I don't understand. Do I move the `String fieldName` to the parameters instead of `EditText mFieldNameInput`?

Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java:242]: Sorry... this was a mistake, remove the `m` prefix from the variable and it's good to go

File: AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java (hunk 5 above)
Comment (dorrin-sot) [reply AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java:125]: Can I ask how do I replicate a `ConfirmModSchemaException` to make sure my assertion works properly?

File: AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java [hunk 11]
```diff
@@ -408,7 +424,6 @@ private void dismissProgressBar() {
         mProgressDialog = null;
     }
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java:426]: nit: could you revert irrelevant spacing changes

File: AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java [hunk 12]
```diff
@@ -0,0 +1,193 @@
...
+import static com.ichi2.anki.FieldOperationType.ADD_FIELD;
+import static com.ichi2.anki.FieldOperationType.RENAME_FIELD;
+import static org.hamcrest.MatcherAssert.assertThat;
+import static org.hamcrest.Matchers.equalTo;
+import static org.hamcrest.Matchers.not;
+
+@RunWith(ParameterizedRobolectricTestRunner.class)
+public class ModelFieldEditorTest extends RobolectricTest {
+    private static final String[] mForbiddenCharacters = new String[] {"#", "^", "/", " ", "\t"};
+    private String mForbiddenCharacter;
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java:46]: Could also define it with a `@Parameterized.Parameter()` annotation and remove the constructor

File: AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java [hunk 13]
```diff
@@ -0,0 +1,193 @@
...
+     * Tests if field names with illegal characters get removed from beginning of field names when renaming field
+     */
+    @Test
+    public void testIllegalCharactersInFieldName_renameField() {
+        // Assertion fails in case of a ConfirmModSchemaException being thrown
+        AnkiAssert.assertDoesNotThrow(() -> {
+            String fieldName = setupInvalidFieldName(mForbiddenCharacter, RENAME_FIELD);
+
+            testForIllegalCharacters(fieldName);
+        });
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java:84]: That code was designed for an overzealous code analyzer that we no longer user

```suggestion
        String fieldName = setupInvalidFieldName(mForbiddenCharacter, RENAME_FIELD);

        testForIllegalCharacters(fieldName);
```

**Review by david-allison-1 — APPROVED** [review]
Looks great! Minor optional changes

File: AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java (hunk 13 above)
Comment (mikehardy) [reply AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java:84]: I still use codacy ;-), that said, it could always be tweaked - we define(d) it's rule set

File: AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java (hunk 12 above)
Comment (dorrin-sot) [reply AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java:46]: I'm not sure why but when I remove the constructor I get this error : `Caused by: java.lang.IllegalStateException: Provided 1 parameters, but only found fields for parameters: []`

Comment (david-allison-1) [reply AnkiDroid/src/test/java/com/ichi2/anki/ModelFieldEditorTest.java:46]: It definitely works (see other examples in the codebase), but it's not vital

**Review by david-allison-1 — APPROVED** [review]
Still LGTM

**Comment by Arthur-Milchior** [comment]
Hi @dorrin-sot 

Please note you'll need to rebase your branch on top of master as there is conflict with current evrsion. Very sorry for this extra work

**Review by mikehardy — APPROVED** [review]
LGTM and a squash merge actually does appear to work...

**Comment by mikehardy** [comment]
Hi there!

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for April 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged in April)

Thanks!
