### PR TITLE
Duplicate Due column Fix

### LINKED ISSUE #17892: Duplicate Due column
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

I don't know how to reproduce the bug but just after installing 2.21alpha10, the Browser showed duplicate Due columns.

### Expected behaviour

No duplicate columns.

### Debug info

```text
2.21 alpha 10
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by dorrin-sot**
## Purpose / Description
The columns sometimes were not distinct in CardBrowser.

## Fixes
* Fixes #17892

## Approach
I modified `BrowserColumnCollection::load` to return only distinct columns.

## How Has This Been Tested?
I wrote a unit test to override the CardBrowser columns in SharedPreferences so it has duplicate values and checked its distinctness afterward.

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/browser/BrowserColumnCollection.kt [hunk 1]
```diff
@@ -63,7 +63,7 @@ class BrowserColumnCollection(
                     val value = mode.defaultColumns()
                     value.split(SEPARATOR_CHAR).map { CardBrowserColumn.fromColumnKey(it) }
                 }
-            return BrowserColumnCollection(columns)
+            return BrowserColumnCollection(columns.distinct())
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/main/java/com/ichi2/anki/browser/BrowserColumnCollection.kt:66]: There is one thing that was not clear to me while reviewing your PR, which is, whether the problem was getting corrected in the preferences too.
I now realize that it's the case, because, when you save the preferences, they were constructed using this function.

So, what I'd appreciate is that you change this PR so that it contains a single commit, and this commit would explain exactly what is the impact. In particular, it would state something such as:

> For some unknown reason, some user ended up with duplicate column. While it should not be possible, this commit allows to deal nicely with this case. Indeed, when creating the `BrowserColumnCollection`, we ensure that columns are distinct. As a side effect, if the user change the set of column, this commit ensure that the duplication is removed, as the `BroswerColumnCollection` that is used to save the preference would have been constructed without duplicate

**Review by Arthur-Milchior — APPROVED** [review]
Pretty nice commit, thanks a lot.
My only regret is that it was not clear why it was indeed the right commit. In particular, I didn't know that it ensured that the preference would be corrected the next time the user change it as a side effect of your commit.

So, I approve the code and the test, still, I'd really want that your commit message, now and in the future, be more descriptive please. That you help reviewers understand what you did, why it works, what impact it has, without us having to look in details at the code you didn't touch

File: AnkiDroid/src/main/java/com/ichi2/anki/browser/BrowserColumnCollection.kt (hunk 1 above)
Comment (dorrin-sot) [reply AnkiDroid/src/main/java/com/ichi2/anki/browser/BrowserColumnCollection.kt:66]: Hi There! So what you're suggesting is that I also update the SharedPreferences to remove the side effect? Or is that done automatically?

Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/browser/BrowserColumnCollection.kt:66]:
```suggestion
            // shared preferences had duplicate columns for unknown reasons
            // this removes duplicates on load, any saves will be de-duplicated
            return BrowserColumnCollection(columns.distinct())
```

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/browser/BrowserColumnCollection.kt:68]: I added a comment, tagging this squash merge

**Review by mikehardy — APPROVED** [review]
LGTM, thank you!

**Comment by mikehardy** [comment]
squashed locally and re-pushed so I can use merge queue

**Comment by david-allison** [comment]
Hi there @dorrin-sot! This is the OpenCollective Notice for PRs merged from [2025-04-01 through 2025-04-30](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2025-04-01..2025-04-30+author%3Adorrin-sot)
                      
If you are interested in compensation for this work, the process with details is here: https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

We only post one comment per person per month to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for this month

Please understand that our monthly budget is never guaranteed to cover all claims - the cap on payments-per-person may be lower, but we try to make our process as fair and transparent as possible, we just need your understanding.

Thanks!
