### PR TITLE
test: ensure org.json is not bundled

### LINKED ISSUE #20857: Regression test: ensure that `org.json` comes from `android.jar`
See

* https://github.com/ankidroid/Anki-Android/issues/20852
* https://github.com/ankidroid/Anki-Android/pull/20856

### PR DESCRIPTION
**Pull request by david-allison**
> [!NOTE]
> Assisted-by: Claude Opus 4.7 - initial test, rewritten a few times. Comments are my own

## Fixes
* Fixes #20857

## How Has This Been Tested?
Tested on:

4d51a45cefa031ebe8a520ad77996bcb47498273 - pass
c95416cfa1ad3fc1094a013d66173e492ce9af3b - fail

## Learning (optional, can help others)

`DexFile` is deprecated since API 26 but still functional

Reflection on `BaseDexClassLoader.pathList` is possible, but requires multiple lint suppressions on private APIs.

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by lukstbit — APPROVED** [review]

File: AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/OrgJsonNotBundledTest.kt [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+ *  the terms of the GNU General Public License as published by the Free Software
+ *  Foundation; either version 3 of the License, or (at your option) any later
+ *  version.
+ *
+ *  This program is distributed in the hope that it will be useful, but WITHOUT ANY
+ *  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
+ *  PARTICULAR PURPOSE. See the GNU General Public License for more details.
+ *
+ *  You should have received a copy of the GNU General Public License along with
+ *  this program.  If not, see <http://www.gnu.org/licenses/>.
```
Comment (BrayanDSO) [inline AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/OrgJsonNotBundledTest.kt:14]: random comment: there's two spaces before `If not`. In other headers as well

**Review by BrayanDSO — APPROVED** [review]

File: AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/OrgJsonNotBundledTest.kt (hunk 1 above)
Comment (david-allison) [reply AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/OrgJsonNotBundledTest.kt:14]: Interesting. Original source was likely:

https://softwarefreedom.org/resources/2007/gpl-non-gpl-collaboration.html#x1-40002.2
