### PR TITLE
fix: invalid file issue on pasting file

### LINKED ISSUE #17388: MediaRegistration: File is invalid
https://ankidroid.org/acra/app/1/bug/253470/report/6ce47815-c82e-48f5-90c3-c6f84d992e25

* #8880

```
com.ichi2.anki.exception.UserSubmittedException: File is invalid issue:8880
	at com.ichi2.anki.exception.ManuallyReportedException.<init>(ManuallyReportedException.java:22)
	at com.ichi2.anki.CrashReportService.sendExceptionReport(CrashReportService.java:261)
	at com.ichi2.anki.MediaRegistration.onPaste(MediaRegistration.java:176)
	at com.ichi2.anki.NoteEditor.onPaste(NoteEditor.kt:1893)
	at com.ichi2.anki.NoteEditor.populateEditFields$lambda$53(NoteEditor.kt:1634)
	at com.ichi2.anki.FieldEditText.onPaste(FieldEditText.kt:174)
	at com.ichi2.anki.FieldEditText.onTextContextMenuItem(FieldEditText.kt:149)
	at android.widget.Editor$TextActionModeCallback.onActionItemClicked(Editor.java:4713)
	at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onActionItemClicked(DecorView.java:2654)
	at com.android.internal.view.FloatingActionMode$3.onMenuItemSelected(FloatingActionMode.java:98)
	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:787)
	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:151)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:934)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:924)
	at com.android.internal.view.FloatingActionMode.lambda$setFloatingToolbar$0$FloatingActionMode(FloatingActionMode.java:128)
	at com.android.internal.view.-$$Lambda$FloatingActionMode$LU5MpPuKYDtwlFAuYhXYfzgLNLE.onMenuItemClick(Unknown Source:2)
	at com.android.internal.widget.FloatingToolbar$FloatingToolbarPopup$2.onClick(FloatingToolbar.java:477)
	at android.view.View.performClick(View.java:7225)
	at android.view.View.performClickInternal(View.java:7202)
	at android.view.View.access$3500(View.java:805)
	at android.view.View$PerformClick.run(View.java:27682)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7438)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:989)
```

### PR DESCRIPTION
**Pull request by criticalAY**
## Purpose / Description
- https://github.com/ankidroid/Anki-Android/issues/17388
When some invalid or corrupted file is being pasted in the field then it might cause the issue, though I tried to reproduce it with various types of  files such as pdf but can not get it, so putting a try catch and send report to ACRA

## Fixes
* Fixes #17388

## How Has This Been Tested?
Local build, try-catch should do the work

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt [hunk 1]
```diff
@@ -171,7 +172,18 @@ class FieldEditText : FixedEditText, NoteService.NoteField {
...
         } else {
-            pasteListener!!.onPaste(this, mediaUri, description)
+            try {
+                pasteListener!!.onPaste(this, mediaUri, description)
+            } catch (ex: NullPointerException) {
+                Timber.w(ex, "Failed to paste media")
+                showSnackbar(context.getString(R.string.multimedia_editor_something_wrong))
+                false
+            } catch (e: Exception) {
+                CrashReportService.sendExceptionReport("File is invalid issue:8880", "FieldEditText:: onPaste URI of file:$mediaUri")
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt:182]: after the recent issue with email addresses I'm worried about including user content like the URI here

and similar to the other issue about dispatching touches, I'm just not sure what the action would be here for someone that sees this in acrarium and tries to work on the stack trace as an issue. Is it actionable? I don't think so really - if pasting files isn't working at all, we'll get issue reports and I think that's sufficient vs having exception reports in the crash database

I'd +1 this with a delete of the crash report line

**Review by mikehardy — CHANGES_REQUESTED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt [hunk 2]
```diff
@@ -171,7 +172,17 @@ class FieldEditText : FixedEditText, NoteService.NoteField {
...
+                pasteListener!!.onPaste(this, mediaUri, description)
+            } catch (ex: NullPointerException) {
+                Timber.w(ex, "Failed to paste media")
+                showSnackbar(context.getString(R.string.multimedia_editor_something_wrong))
+                false
+            } catch (e: Exception) {
+                Timber.w(e, "Failed to paste media")
+                showSnackbar(context.getString(R.string.multimedia_editor_something_wrong))
+                false
+            }
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt:185]: these are functionally identical blocks now aren't they? propose collapse

```suggestion
            } catch (e: Exception) {
                Timber.w(e, "Failed to paste media")
                showSnackbar(context.getString(R.string.multimedia_editor_something_wrong))
                false
            }
```

**Review by mikehardy — CHANGES_REQUESTED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt (hunk 2 above)
Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt:185]: Earlier this was sending report to ACRA, my bad will fix it

**Review by mikehardy — APPROVED** [review]
great, thanks for fixing a crash, users will appreciate it

**Review by lukstbit — APPROVED** [review]
Thanks!
