### PR TITLE
fix: runtime error handling in custom scheduling 

### LINKED ISSUE #15035: [Bug] customSchedulingJs issue: Cannot study Filtered Decks
###### Reproduction Steps

1. Create a Filtered Deck with rescheduling enabled
2. Open it to study it
3. Click on "Show Answer" 

###### Expected Result

The card is flipped to the back side.

###### Actual Result

The card is not flipped and the front continues being shown.

###### Debug info
Tested on 2.17alpha12 (anki 23.10.1 / fac9e0ee), arm64-v8a version.
Did not occur on alpha8.
It started occuring at least since alpha10. Did not test on alpha9.

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
* our custom scheduling code handled syntax error, but not runtime errors

* Cause: https://github.com/ankidroid/Anki-Android/pull/14899

## Fixes
* Fixes #15035

## Approach
* define a URL
* access the URL via: `window.location.href = "state-mutation-error:"`
* set `statesMutated` if the URL is accessed

## How Has This Been Tested?
API 33 emulator, and tests added

## Learning (optional, can help others)

* https://faqs.ankiweb.net/the-2021-scheduler.html#add-ons-and-custom-scheduling
* Custom Study defines a different set of properties, hence the failure
* Python escaping: https://stackoverflow.com/q/5466451/

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
Nice one - good test refactor + test, and obviously the fix to get scheduling terminating condition going for these cases

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt [hunk 1]
```diff
@@ -2456,6 +2456,9 @@ abstract class AbstractFlashcardViewer :
                 }
                 return true
             }
+            if (url.startsWith("state-mutation-error:")) {
+                onStateMutationError()
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt:2460]: ! Needed to return true here
