### PR TITLE
fix: Prevent deck creation on 'Enter' key when deck name already exists

### LINKED ISSUE #17044: Deck picker "enter" key should not create the deck when the "ok" button is disabled
This is a follow-up to #16690 fixed by #16704 by @MinusMallard .

How to reproduce:
* open the deck picker
* create a deck A
* open "add deck"
* type name "A"
* press enter

Actual result:
* the view close, the snackbar tells the deck is created. No deck is created.

Expected result:
* A snackbar telling that the name already exists
* the dialog remain open

### PR DESCRIPTION
**Pull request by Giyutomioka-SS**
## Purpose / Description
Ensure that pressing the "Enter" key does not create a deck when the deck name already exists, providing a snackbar notification and keeping the dialog open for user correction.

## Fixes
* Fixes #17044 

## How Has This Been Tested?
Realme 6 (API-30) and Emulator

## Screen Recording
https://github.com/user-attachments/assets/cc83a20c-6def-4a39-90bd-a185c37b6e27

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by Arthur-Milchior — APPROVED** [review]
Nice touch for the snackbar. Thanks a lot.
I think a short length would be far enough. Implementer choice.

I also think if we can't create the deck, we should return false. The shortcut was not actually used.

I don't know if the returned value is used by anything, so I won't block on this.

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt [hunk 1]
```diff
@@ -97,7 +97,12 @@ class CreateDeckDialog(
             val inputField = dialog.getInputField()
             inputField.setOnEditorActionListener { _, actionId, event ->
                 if (actionId == EditorInfo.IME_ACTION_DONE || event?.keyCode == KeyEvent.KEYCODE_ENTER) {
-                    onPositiveButtonClicked()
+                    // Check if the positive button is enabled
+                    if (dialog.positiveButton.isEnabled) {
+                        onPositiveButtonClicked()
+                    } else {
+                        dialog.getInputTextLayout().showSnackbar(context.getString(R.string.deck_already_exists), Snackbar.LENGTH_LONG)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt:104]: Technically not the correct message if the input box is empty.

Implementer's choice: do you want to fix this, or are you happy to merge as is?

**Review by david-allison — APPROVED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt (hunk 1 above)
Comment (Giyutomioka-SS) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt:104]: But the input is not empty; it has the same name as an existing deck, so I think the message is correct. If not, I can change it, no problem, but then it will require a new string and its translations.

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt:104]: Good to go if I misunderstood: I presumed there could be multiple reasons why the positive button isn't enabled:

* The input is empty
* the deck is a duplicate

Comment (Giyutomioka-SS) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt]: Thanks for the clarification, It's done.

**Comment by david-allison** [comment]
> https://github.com/ankidroid/Anki-Android/actions/runs/11149038356

Strings are clear. Let's go
