### PR TITLE
fix: intro sync storage permission

### LINKED ISSUE #20884: `full`: "Sync from AnkiWeb" doesn't work
The permissions dialog should be shown instead

Image

### PR DESCRIPTION
**Pull request by criticalAY**
## Purpose / Description
Open storage permission screen from intro activity when sync is clicked

## Fixes
* Fixes #20884

## Approach
NA

## How Has This Been Tested?
Pixel Fold Emulator API 35

## Learning (optional, can help others)
NA

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/test/java/com/ichi2/anki/IntroductionActivityTest.kt [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+import org.junit.runner.RunWith
+import org.robolectric.Shadows.shadowOf
+import kotlin.test.assertNotNull
+
+@RunWith(AndroidJUnit4::class)
+class IntroductionActivityTest : RobolectricTest() {
+    @Test
+    fun `Sync without storage permission opens PermissionsActivity, not AccountActivity`() =
+        runTest {
+            withDeniedPermissions(INTERNET) {
```
Comment (david-allison) [inline AnkiDroid/src/test/java/com/ichi2/anki/IntroductionActivityTest.kt:48]: Why `INTERNET`?

File: AnkiDroid/src/test/java/com/ichi2/anki/IntroductionActivityTest.kt [hunk 2]
```diff
@@ -0,0 +1,64 @@
...
+import kotlinx.coroutines.test.runTest
+import org.hamcrest.MatcherAssert.assertThat
+import org.hamcrest.Matchers.equalTo
+import org.hamcrest.Matchers.not
+import org.junit.Test
+import org.junit.runner.RunWith
+import org.robolectric.Shadows.shadowOf
+import kotlin.test.assertNotNull
+
+@RunWith(AndroidJUnit4::class)
```
Comment (david-allison) [inline AnkiDroid/src/test/java/com/ichi2/anki/IntroductionActivityTest.kt:40]: nit: I like a link to the class in a doc-comment:

`/** Tests [IntroductionActivity] */`

**Review by david-allison — APPROVED** [review]
LGTM, unusual test

File: AnkiDroid/src/test/java/com/ichi2/anki/IntroductionActivityTest.kt (hunk 1 above)
Comment (criticalAY) [reply AnkiDroid/src/test/java/com/ichi2/anki/IntroductionActivityTest.kt:48]: Added a comment to explain it also added more tests

**Review by mikehardy — APPROVED** [review]
LGTM - is this something that seems appropriate for 2.24 release? seems it might be - if yes action is add "queued for cherry-pick to stable branch" label

**Comment by david-allison** [comment]
It would have been 2.24.1 (not a regression in the 2.24 series & close to launch date), but if you're happy with 2.24.0, even better!
