### PR TITLE
fix: Note Editor: "No image found on clipboard" Snackbar is not shown if the initial note type is 'Image Occlusion'

### LINKED ISSUE #19643: Note Editor: "No image found on clipboard" Snackbar is not shown if the initial note type is 'Image Occlusion'
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Store no image in the clipboard
1. "Add"
2. Select "Image Occlusion" for "Type"
3. Go back to Deck picker screen
4. "+" -> "Add"
5. "Paste from clipboard"

**Result**

https://github.com/user-attachments/assets/ebe19599-9ac6-4f56-9ee7-c1293c16a17c

### Expected behaviour

The error message snackbar is shown:

Image

### Debug info

```text
AnkiDroid Version = 2.23.0beta3 (5457f48e80c00ee28ae5edc91569facb6b7f75bf)  
Backend Version = 0.1.62-anki25.09.2 (25.09.2 3890e12c9e48c028c3f12aa58cb64bd9f8895e30)  
Android Version = 15 (SDK 35)  
ProductFlavor = full  
Device Info = OPPO | OPPO | OP5A0BL1 | CPH2603 | CPH2603 | mt6877  
Webview User Agent = Mozilla/5.0 (Linux; Android 15; CPH2603 Build/AP3A.240617.008; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/142.0.7444.102 Mobile Safari/537.36  
ACRA UUID = d97e1cf1-0e91-4b03-9120-f9f5fde09bbc  
FSRS = 5.1.0 (Enabled: false)  
Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by snowtimeglass**
## Purpose / Description
The "No image found on clipboard" Snackbar is invisible when the note editor is initially loaded with Image Occlusion note type.

## Fixes
* Fixes #19643

## Approach
Show the Snackbar via the Activity root view

## How Has This Been Tested?

Tested on a physical device (Android 15 / SDK 35)

https://github.com/user-attachments/assets/7ca89e21-c8da-4871-8164-634b72079cad

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — CHANGES_REQUESTED** [review]
Okay, so let's dig into why this occurs:

https://github.com/ankidroid/Anki-Android/blob/3cf75c889d4fe5c88d2b654874a5a1fabbf27b84/AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt#L240-L251

`baseSnackbarBuilder = NoteEditorFragment...`
`snackbarBuilder = null`


`baseSnackbarBuilder => snackbar.anchorView.isVisible = false`

It would be better to handle this in `View.showSnackbar` so it works for all cases.

Maybe:

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt b/AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt	(revision 80b7a5c23191b38cb0ea078ff9aee55cbd77989b)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt	(date 1764417971548)
@@ -21,12 +21,15 @@
 import androidx.annotation.RequiresApi
 import androidx.annotation.StringRes
 import androidx.coordinatorlayout.widget.CoordinatorLayout
+import androidx.core.view.isVisible
 import androidx.fragment.app.DialogFragment
 import androidx.fragment.app.Fragment
 import com.google.android.material.snackbar.Snackbar
 import com.google.android.material.snackbar.onAttachedToWindow2
 import com.ichi2.anki.BuildConfig
+import com.ichi2.anki.CrashReportService
 import com.ichi2.anki.R
+import com.ichi2.anki.exception.ManuallyReportedException
 import com.ichi2.anki.showThemedToast
 import timber.log.Timber
 
@@ -208,6 +211,21 @@
         snackbar.snackbarBuilder()
     }
 
+    if (snackbar.anchorView?.isVisible == false) {
+        val errorMessage = "While trying to show a snackbar, anchorView was not visible"
+        if (BuildConfig.DEBUG) {
+            throw IllegalArgumentException(errorMessage)
+        }
+        Timber.w(errorMessage)
+        CrashReportService.sendExceptionReport(
+            ManuallyReportedException(errorMessage),
+            "View.showSnackbar",
+            onlyIfSilent = true
+        )
+        
+        snackbar.anchorView = null
+    }
+
     snackbar.show()
 }
```

Then fix this specific instance of the bug in https://github.com/ankidroid/Anki-Android/blob/5ca54d3e66844b1c3b723bac5f4a1f97fa614d64/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt#L481

```patch
Index: AnkiDroid/src/main/java/com/ichi2/utils/ViewUtils.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/utils/ViewUtils.kt b/AnkiDroid/src/main/java/com/ichi2/utils/ViewUtils.kt
--- a/AnkiDroid/src/main/java/com/ichi2/utils/ViewUtils.kt	(revision 80b7a5c23191b38cb0ea078ff9aee55cbd77989b)
+++ b/AnkiDroid/src/main/java/com/ichi2/utils/ViewUtils.kt	(date 1764418239233)
@@ -23,6 +23,7 @@
 import android.view.MotionEvent
 import android.view.View
 import androidx.core.view.OnReceiveContentListener
+import androidx.core.view.isVisible
 import androidx.draganddrop.DropHelper
 
 /** @see View.performClick */
@@ -153,3 +154,10 @@
 fun View.isRtl() = isRtl(resources)
 
 fun isRtl(res: Resources): Boolean = res.configuration.layoutDirection == View.LAYOUT_DIRECTION_RTL
+
+/**
+ * Executes [block] if [View.isVisible] is `true`
+ */
+fun View.ifVisible(block: (View) -> Unit) {
+    if (this.isVisible) block(this)
+}
\ No newline at end of file
Index: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt	(revision 80b7a5c23191b38cb0ea078ff9aee55cbd77989b)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt	(date 1764418239250)
@@ -174,6 +174,7 @@
 import com.ichi2.utils.NoteFieldDecorator
 import com.ichi2.utils.TextViewUtil
 import com.ichi2.utils.configureView
+import com.ichi2.utils.ifVisible
 import com.ichi2.utils.message
 import com.ichi2.utils.negativeButton
 import com.ichi2.utils.neutralButton
@@ -477,8 +478,8 @@
             }
 
     override val baseSnackbarBuilder: SnackbarBuilder = {
-        if (sharedPrefs().getBoolean(PREF_NOTE_EDITOR_SHOW_TOOLBAR, true)) {
-            anchorView = requireView().findViewById<Toolbar>(R.id.editor_toolbar)
+        requireView().findViewById<Toolbar>(R.id.editor_toolbar).ifVisible { 
+            anchorView = it 
         }
     }
 

 ```

**Comment by snowtimeglass** [comment]
Thank you. The PR has been changed.

Tested again on a physical device above and it works expectedly.

File: AnkiDroid/src/main/java/com/ichi2/utils/ViewUtils.kt [hunk 1]
```diff
@@ -153,3 +154,9 @@ private fun Float.dpToPx(context: Context): Int = (this * context.resources.disp
 fun View.isRtl() = isRtl(resources)
 
 fun isRtl(res: Resources): Boolean = res.configuration.layoutDirection == View.LAYOUT_DIRECTION_RTL
+
+fun <T : View> T.ifVisible(block: (T) -> Unit) {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/utils/ViewUtils.kt]: Optionally add docs

**Comment by snowtimeglass** [comment]
Can I rather transfer the position of main author to you?

**Comment by david-allison** [comment]
If you wish

File: AnkiDroid/src/main/java/com/ichi2/utils/ViewUtils.kt (hunk 1 above)
Comment (snowtimeglass) [reply AnkiDroid/src/main/java/com/ichi2/utils/ViewUtils.kt]: Added.

**Comment by snowtimeglass** [comment]
I’d like to follow the usual practice. What would you recommend I do next?

**Comment by david-allison** [comment]
If you rebase/amend the commits, you can change the 'author' of the git commit

Should be able to find a few articles after a quick Google

**Comment by david-allison** [comment]
`Co-authored-by` can also be used to give yourself credit

**Comment by snowtimeglass** [comment]
I may not have noticed your implication yet. If anything I did isn't aligned with common practice or your expectations, please feel free to let me know.

**Comment by david-allison** [comment]
By changing the author, you're not giving yourself any credit.

You can optionally fix this, if you care

https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

**Comment by snowtimeglass** [comment]
> By changing the author, you're not giving yourself any credit.

Haven't I succeeded in giving myself a co-author credit yet?

---

image

---

image

---

image

https://github.com/ankidroid/Anki-Android/pull/19644/commits/0dda552833ee8f9782f41d3f64c33d00f54cfa3c

**Comment by david-allison** [comment]
The screenshots are small on my phone. Looks perfect! I'll confirm later

**Comment by david-allison** [comment]
The screenshots are small on my phone. Looks perfect! I'll confirm later

**Comment by david-allison** [comment]
@snowtimeglass I this this is fine to merge, so I've undrafted it, please let me know if changes are required on your side

File: AnkiDroid/src/main/java/com/ichi2/utils/ViewUtils.kt [hunk 2]
```diff
@@ -153,3 +154,10 @@ private fun Float.dpToPx(context: Context): Int = (this * context.resources.disp
 fun View.isRtl() = isRtl(resources)
 
 fun isRtl(res: Resources): Boolean = res.configuration.layoutDirection == View.LAYOUT_DIRECTION_RTL
+
+/**
+ * Executes [block] if [View.isVisible] is `true`
+ */
+fun View.ifVisible(block: (View) -> Unit) {
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/utils/ViewUtils.kt]: I don't feel that this extension method is necessary.

It only checks a single property. It doesn't do any transformation, additional checks, etc.

Writing "if (myView.isVisible) {}" produces the same effect.

Doing it to use the `View` scope doesn't help much as well IMO. It's too much syntactic sugar, and that adds makes the codebase more complex for new developers that aren't used to our custom methods. Even veterans would forget that this exists.

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/utils/ViewUtils.kt]: Personally, it feels similar to "ifEmpty" or "ifBlank" from core Kotlin 

I don't feel strongly. Let's remove it if you don't like it

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/utils/ViewUtils.kt]: In addition: in this case it means that the view needs to be defined as a variable: 

```
val view = findViewById
if (view.isVisible) {
    // ....
}
```

Becomes

```
findViewById().ifVisible {
  // use it
}
```

Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/utils/ViewUtils.kt]: > "ifEmpty" or "ifBlank" from core Kotlin. 

1) Both are standard Kotlin methods. People may know them from other repositories, so they don't need to learn them, If they don't know them, after learning they can use them in other places besides AnkiDroid. I'm not argumenting against having our own custom extension methods, but I do emphasize that the standard Kotlin methods weight more than our own.
2) Their inner logic is more complex than using the value of a single boolean property like `isVisible`.

> in this case it means that the view needs to be defined as a variable

should be solved by viewBinding in most cases

**Comment by david-allison** [comment]
@BrayanDSO I have fixed this and force pushed
