### PR TITLE
use `SaveInstanceState` to avoid crash in export file when Activity is recreated

### LINKED ISSUE #14795: [BUG]: Background activity getting destroyed and recreated due to low memory causes an error when performing an EXPORT
### Checked for duplicates?

- [X] This issue is not a duplicate

#### Environment Setup:

To mimick low memory situation, turn on the following developer option for the device

Developer Options -> Don't keep activities

#### Steps to Reproduce:

1. From the Decks home screen, select Export collection from the menu

2. On the upcoming "Export read" dialog, click "Save to"

3. Select a place to save the file and select SAVE

4. AnkiDroid crashes

### Expected behaviour

After saving is complete the app should return to the _Decks_ home screen.

### Actual behaviour

After returning from the save dialog, the app crashes

### Debug info

- version: 2.17alpha6
- ran on emulator (Pixel 7 API 33)

Ultimately the error that I was seeing was

```text
kotlin.UninitializedPropertyAccessException: lateinit property mExportFileName has not been initialized
```
`mExportFileName` is from `ActivityExportingDelegate`. 

If `DeckPicker` gets killed in the background because of low memory then the `onCreate` for `DeckPicker` will be called again after returning from the export dialogs. 

The `onCreate` in `DeckPicker` creates a new instance of `ActivityExportingDelegate`. However, `mExportFileName` only gets initialized during the save process, so when `ActivityExportingDelegate` gets recreated again _after_ the save process, `mExportFileName` no longer has a value. That explained the `UninitializedPropertyAccessException` when we try and use `mExportFileName` when returning to `DeckPicker`

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by criticalAY**
## Purpose / Description
Remove the lateinit var and use shared pref and nullable string to avoid crash in case the developer's option is turned on

## Fixes
Fixes #14795 

## How Has This Been Tested?
google emulator
[Screen_recording_20231124_152918.webm](https://github.com/ankidroid/Anki-Android/assets/48384865/1aa91e06-7686-425b-b674-044d768accb0)

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by criticalAY** [comment]
I came across this when I was reproducing #14795, and regarding this issue we can use shared prefs to overcome it what say? 
I can update this PR only if the reviewer agrees to this updating the message and commits do let me know

**Comment by lukstbit** [comment]
Is this really needed? I've tested the collection/apkg export and the SnackBar appears where it should, above the FAB.

**Comment by criticalAY** [comment]
image
This was in case the "dont keep activity" was turned on by the user but after fixing the crash I noticed it still persist I am updating the PR to fix the crash first

**Comment by criticalAY** [comment]
> Edit, forgot: I'm working on #14604 and I might be able to delete ActivityExportingDelegate, so you shouldn't spend time on #14795 .

ok, leaving it for now then 👍

**Comment by criticalAY** [comment]
@lukstbit any updates on the issue?

File: AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt [hunk 1]
```diff
@@ -60,7 +61,7 @@ import java.util.function.Supplier
 class ActivityExportingDelegate(private val activity: AnkiActivity, private val collectionSupplier: Supplier<Collection>) : ExportDialogListener, ExportReadyDialogListener {
     val mDialogsFactory: ExportDialogsFactory
     private val mSaveFileLauncher: ActivityResultLauncher<Intent>
-    private lateinit var mExportFileName: String
+    private var mExportFileName: String? = null
```
Comment (lukstbit) [inline AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt:64]: This can be deleted as we don't really this property, we could simply use the shared preferences.

File: AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt [hunk 2]
```diff
@@ -201,8 +202,12 @@ class ActivityExportingDelegate(private val activity: AnkiActivity, private val
             return
         }
 
+        activity.getSharedPreferences("file_prefs", Context.MODE_PRIVATE)
```
Comment (lukstbit) [inline AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt:205]: `activity.sharedPrefs.edt { putString() }`

File: AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt [hunk 3]
```diff
@@ -215,6 +220,8 @@ class ActivityExportingDelegate(private val activity: AnkiActivity, private val
     }
 
     private fun saveFileCallback(result: ActivityResult) {
+        val sharedPreferences = activity.getSharedPreferences("file_prefs", Context.MODE_PRIVATE)
+        mExportFileName = sharedPreferences.getString(EXPORT_FILE_NAME_KEY, null)
```
Comment (lukstbit) [inline AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt:224]: `val localFile = activity.sharedPrefs().getString(EXPORT_FILE_NAME_KEY, "") ?: ""`

then the other usages of mExportFileName can be update to take this value.

File: AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt [hunk 4]
```diff
@@ -277,7 +284,7 @@ class ActivityExportingDelegate(private val activity: AnkiActivity, private val
      * This will allow to check whether a recent export was made, hence scoped storage migration is safe.
      */
     private fun saveSuccessfulCollectionExportIfRelevant() {
```
Comment (lukstbit) [inline AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt:286]: Method should be changed to receive the path as a parameter.

**Review by lukstbit — CHANGES_REQUESTED** [review]
I've implemented the changes I wanted but it didn't touched the mExportFileName related issue. So this PR is needed, I left some reviews notes on this.

File: AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt (hunk 2 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt:205]: We should also exclude this from ACRA

File: AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt (hunk 3 above)
Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt:224]: This still creates a need for a `val` so why not to use it as a lateint only

**Comment by david-allison** [comment]
Minor: we should remove the name from ACRA reports in the method: `createAcraCoreConfigBuilder`

File: AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt (hunk 1 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt:63]: this comment has not been addressed @criticalAY - and it appears if it were addressed (by removing the var) there would be a compilation error below in `saveSuccessfulCollectionExportIfRelevant` which is assuming that mExportFileName is set and non-null (via a dangerous `!!`) but never sets it as far as I can see?

File: AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt [hunk 5]
```diff
@@ -215,6 +216,7 @@ class ActivityExportingDelegate(private val activity: AnkiActivity, private val
     }
 
     private fun saveFileCallback(result: ActivityResult) {
+        mExportFileName = activity.sharedPrefs().getString(EXPORT_FILE_NAME_KEY, "")
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt:219]: what happens if it is empty for whatever reason?

File: AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt [hunk 6]
```diff
@@ -236,7 +238,7 @@ class ActivityExportingDelegate(private val activity: AnkiActivity, private val
             activity.contentResolver.openFileDescriptor(uri!!, "w").use { pfd ->
                 if (pfd != null) {
                     FileOutputStream(pfd.fileDescriptor).use { fileOutputStream ->
-                        CompatHelper.compat.copyFile(mExportFileName, fileOutputStream)
+                        CompatHelper.compat.copyFile(mExportFileName!!, fileOutputStream)
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt:241]: if the var was removed above and it was just a val local then you wouldn't need the dangerous !!

File: AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt [hunk 7]
```diff
@@ -246,7 +248,7 @@ class ActivityExportingDelegate(private val activity: AnkiActivity, private val
                     return false
                 }
             }
-            if (deleteAfterExport && !File(mExportFileName).delete()) {
+            if (deleteAfterExport && !File(mExportFileName!!).delete()) {
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt:251]: likewise - if the var was removed above and it was just a val local then you wouldn't need the dangerous !!

File: AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt [hunk 8]
```diff
@@ -277,7 +279,7 @@ class ActivityExportingDelegate(private val activity: AnkiActivity, private val
      * This will allow to check whether a recent export was made, hence scoped storage migration is safe.
      */
     private fun saveSuccessfulCollectionExportIfRelevant() {
-        if (::mExportFileName.isInitialized && !mExportFileName.endsWith(".colpkg")) return
+        if (!mExportFileName!!.endsWith(".colpkg")) return
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt:282]: we are in a new method here, and the activity may be recreated, but I don't see the filename fetched from prefs and initialized again?

If lukstbit had been handled instead of just resolved and closed without handling, then it would be a method parameter (non-null...) and you wouldn't need the dangerous !! on a var that I think is not initialized at this point

File: AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt (hunk 4 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt:281]: this was not handled.

File: AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt (hunk 8 above)
Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt:282]: there is still a risk of it being null (it is 99.9% sure though it won't be null) as `getString(EXPORT_FILE_NAME_KEY, "")` automatically assigns null value to the pref in case it is null.

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt:282]: I thought it automatically assigned `""` to the pref in case it is null.
This doesn't seem to actually address the substance of my comment tho?

Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt:282]: i am pushing the changes for that part I have used elvis operator though in case

Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt]: we can't escape the evil "!!" here  ` if (!mExportFileName!!.endsWith(".colpkg")) return`

File: AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt (hunk 4 above)
Comment (lukstbit) [reply AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt:280]: This method is called from two other methods, in one the path is available and could be passed directly and in the other method, saveFileCallback you could retrieve the filename from preferences and pass it to saveSuccessfillColl... and also to exportToProvider() which would allow us to avoid exportfilename?:"".

**Comment by david-allison** [comment]
Is it feasible to use `savedInstanceState` here instead of preferences?

**Comment by criticalAY** [comment]
> Is it feasible to use `savedInstanceState` here instead of preferences?

I guess that creates the need for extra calls from the activity where we are using this class, we can avoid that by using the prefs here itself

**Comment by criticalAY** [comment]
Using saved state now instead shared pref

File: AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt [hunk 9]
```diff
@@ -246,11 +258,11 @@ class ActivityExportingDelegate(private val activity: AnkiActivity, private val
                     return false
                 }
             }
-            if (deleteAfterExport && !File(mExportFileName).delete()) {
-                Timber.w("Failed to delete temporary export file %s", mExportFileName)
+            if (deleteAfterExport && !File(fileExportPath?:"").delete()) {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt:261]: We should likely close the dialog/fail if the path is null.

`File("").delete()` is almost certainly a no-op, but it's a scary line of code

**Review by david-allison — CHANGES_REQUESTED** [review]
one issue regarding invalid states, rest looks great, thanks!

**Review by david-allison — APPROVED** [review]
Looks great, thanks!

**Comment by mikehardy** [comment]
At some point @criticalAY you're going to need to learn how to use git rebase and clean up your commits - this should be a one commit PR, I have no idea why there are 9 different commits most with same title

image

**Comment by criticalAY** [comment]
> At some point @criticalAY you're going to need to learn how to use git rebase and clean up your commits - this should be a one commit PR, I have no idea why there are 9 different commits most with same title
> 
> image

Give me a moment, will do it

File: AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt [hunk 10]
```diff
@@ -83,7 +83,7 @@ object CrashReportService {
     private fun createAcraCoreConfigBuilder(): CoreConfigurationBuilder {
         val builder = CoreConfigurationBuilder()
             .withBuildConfigClass(com.ichi2.anki.BuildConfig::class.java) // AnkiDroid BuildConfig - Acrarium#319
-            .withExcludeMatchingSharedPreferencesKeys("username", "hkey")
+            .withExcludeMatchingSharedPreferencesKeys("username", "hkey", "file_prefs")
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt:86]: Is this still a thing? Seems related to the previous design that was saved preferences based, but now you're using the bundle passed between previous-killed-activity and newly-resumed-activity ?

**Review by mikehardy — CHANGES_REQUESTED** [review]

**Review by mikehardy — APPROVED** [review]
This looks clean + correct to me know and also "lighter" using the saved instance state style. It's changed a lot and with the rebase + push I'm going to ask for one more approval but I think it's smooth sailing. Thanks!

File: AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt [hunk 11]
```diff
@@ -214,6 +216,16 @@ class ActivityExportingDelegate(private val activity: AnkiActivity, private val
         mSaveFileLauncher.launch(saveIntent)
     }
 
+    fun onSaveInstanceState(outState: Bundle) {
+        outState.putString(EXPORT_FILE_NAME_KEY, fileExportPath)
+    }
+
+    fun onRestoreInstanceState(savedInstanceState: Bundle?) {
+        savedInstanceState?.let { savedState ->
+            fileExportPath = savedState.getString(EXPORT_FILE_NAME_KEY)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt:225]: Nit: can be simplified to `?.`

File: AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt [hunk 12]
```diff
@@ -231,12 +243,12 @@ class ActivityExportingDelegate(private val activity: AnkiActivity, private val
...
         }
         val uri = intent.data
-        Timber.d("Exporting from file to ContentProvider URI: %s/%s", mExportFileName, uri.toString())
+        Timber.d("Exporting from file to ContentProvider URI: %s/%s", fileExportPath, uri.toString())
         try {
             activity.contentResolver.openFileDescriptor(uri!!, "w").use { pfd ->
                 if (pfd != null) {
                     FileOutputStream(pfd.fileDescriptor).use { fileOutputStream ->
-                        CompatHelper.compat.copyFile(mExportFileName, fileOutputStream)
+                        CompatHelper.compat.copyFile(fileExportPath ?: "", fileOutputStream)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt:251]: Can we make the variable lateinit if it's not possible, or handle this correctly?

`""` being passed to a file operation is scary

File: AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt [hunk 13]
```diff
@@ -60,7 +61,7 @@ import java.util.function.Supplier
 class ActivityExportingDelegate(private val activity: AnkiActivity, private val collectionSupplier: Supplier<Collection>) : ExportDialogListener, ExportReadyDialogListener {
     val mDialogsFactory: ExportDialogsFactory
     private val mSaveFileLauncher: ActivityResultLauncher<Intent>
-    private lateinit var mExportFileName: String
+    private var fileExportPath: String? = null
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt:64]: as per other comments, we should keep this as lateinit, and continue to guard in the few paths where it may be uninitialised

**Review by david-allison — CHANGES_REQUESTED** [review]
Sorry, another round due to the use of `""` as a path

File: AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt [hunk 14]
```diff
@@ -214,6 +216,14 @@ class ActivityExportingDelegate(private val activity: AnkiActivity, private val
         mSaveFileLauncher.launch(saveIntent)
     }
 
+    fun onSaveInstanceState(outState: Bundle) {
+        outState.putString(EXPORT_FILE_NAME_KEY, fileExportPath)
+    }
+
+    fun onRestoreInstanceState(savedInstanceState: Bundle?) {
+        fileExportPath = savedInstanceState?.getString(EXPORT_FILE_NAME_KEY).toString()
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt:224]: Sorry! this is incorrect now we've moved to `lateinit`, `null.toString() == "null"`

```kotlin
        val restoredValue = savedInstanceState?.getString(EXPORT_FILE_NAME_KEY) ?: return
        fileExportPath = restoredValue
```

**Review by david-allison — APPROVED** [review]

**Comment by david-allison** [comment]
https://github.com/ankidroid/Anki-Android/labels/squash-merge

**Comment by criticalAY** [comment]
there was a linting error causing the code quality failure so the latest commit fixes that nothing else
