### PR TITLE
fix(shared-decks): crash on checking progress

### LINKED ISSUE #19812: [BUG] Shared Deck Download: column `local_filename` is not allowed in queries
2.23.0

Xiaomi Redmi Note 12 Pro 5G

https://ankidroid.org/acra/app/1/bug/366992/report/9b3e6eb1-363c-4180-ac35-126ad8a5d623

```
java.lang.IllegalArgumentException: column local_filename is not allowed in queries
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:481)
	at android.content.ContentResolver.query(ContentResolver.java:1219)
	at android.content.ContentResolver.query(ContentResolver.java:1151)
	at android.content.ContentResolver.query(ContentResolver.java:1107)
	at android.app.DownloadManager$Query.runQuery(DownloadManager.java:1491)
	at android.app.DownloadManager.query(DownloadManager.java:1716)
	at android.app.DownloadManager.query(DownloadManager.java:1703)
	at com.ichi2.anki.SharedDecksDownloadFragment.checkDownloadProgress(SharedDecksDownloadFragment.kt:433)
	at com.ichi2.anki.SharedDecksDownloadFragment.access$checkDownloadProgress(SharedDecksDownloadFragment.kt:61)
	at com.ichi2.anki.SharedDecksDownloadFragment$downloadProgressChecker$2$1.run(SharedDecksDownloadFragment.java:398)
	at com.ichi2.anki.SharedDecksDownloadFragment.startDownloadProgressChecker(SharedDecksDownloadFragment.kt:411)
	at com.ichi2.anki.SharedDecksDownloadFragment.downloadFile(SharedDecksDownloadFragment.kt:229)
	at com.ichi2.anki.SharedDecksDownloadFragment.onViewCreated(SharedDecksDownloadFragment.kt:162)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3152)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:608)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:286)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2214)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2109)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2052)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:703)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8303)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1074)
```

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
`query` produced:
`java.lang.IllegalArgumentException: column local_filename is not allowed in queries`

on a Xiaomi Redmi Note 12 Pro 5G

## Fixes
* Fixes #19812

## Approach
`try ... catch`

## How Has This Been Tested?

Screenshot 2025-12-15 at 14 35 04

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt b/AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt	(revision b1002bd2f0f1b582856f0161f4ec772686821b31)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt	(date 1765784020220)
@@ -422,6 +422,10 @@
         isProgressCheckerRunning = false
     }
 
+    fun aa(): Cursor {
+        throw IllegalArgumentException("column local_filename is not allowed in queries")
+    }
+
     /**
      * Checks download progress and sets the current progress in ProgressBar.
      */
@@ -431,7 +435,7 @@
 
         val cursor =
             try {
-                downloadManager.query(query)
+                aa()
             } catch (_: Exception) {
                 // 19812: column local_filename is not allowed in queries
                 downloadPercentageText.text = getString(R.string.download_percentage_unknown)

```

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt [hunk 1]
```diff
@@ -429,7 +429,15 @@ class SharedDecksDownloadFragment : Fragment(R.layout.fragment_shared_decks_down
         val query = DownloadManager.Query()
         query.setFilterById(downloadId)
 
-        val cursor = downloadManager.query(query)
+        val cursor =
+            try {
+                downloadManager.query(query)
+            } catch (_: Exception) {
```
Comment (lukstbit) [inline AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt]: Maybe we should just catch _IllegalArgumentException_ so we don't hide anything else.

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt]: Hmm... okay

**Comment by david-allison** [comment]
@mikehardy This one contains strings... will wait for your opinion on how this will affect the release before merging

**Comment by lukstbit** [comment]
@david-allison You could also consider using _TR.syncDownloadingFromAnkiweb()_(_Downloading from AnkiWeb..._) as an alternative to the new string.

**Comment by david-allison** [comment]
Great catch, thanks!!!

**Comment by mikehardy** [comment]
Fwiw new strings are fine and cherry picking works - results in a non fatal lint warning which seems justified to see but doesn't fail ci or publish.  String sync after removing strings is not currently cherry pickable but could be with a (non-existent) filter to drop removal chunks on the pick

File: AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt [hunk 2]
```diff
@@ -429,7 +430,15 @@ class SharedDecksDownloadFragment : Fragment(R.layout.fragment_shared_decks_down
         val query = DownloadManager.Query()
         query.setFilterById(downloadId)
 
-        val cursor = downloadManager.query(query)
+        val cursor =
+            try {
+                downloadManager.query(query)
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt:435]: There is a second usage in this file, won't it have the same problem?

https://github.com/david-allison/Anki-Android/blob/8738e2e5a66287b1591b15b44fc9a3676b86d0c0/AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt#L296-L298

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt:435]: Already wrapped in a `try...catch`. We're shifting from a hard crash to a `failed...try again` (with an offer to download using the web browser), which feels acceptable

If that `query()` fails, I don't believe we can check the download status to see if it succeeded.

https://github.com/ankidroid/Anki-Android/blob/8738e2e5a66287b1591b15b44fc9a3676b86d0c0/AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt#L322-L329

Probably warrants an issue to improve the error handling further, I'm open to this blocking the PR if you'd prefer I also tackled it here, but it feels like scope creep
