### PR TITLE
fix: localizations not being added to values-iw

### LINKED ISSUE #9451: hebrew values-he folder from crowdin needs duplication into values-iw - both are apparently needed
for working hebrew translation- please change the folder name of the hebrew translation in res to "values-iw". now it's dosn't works.
thanks

### PR DESCRIPTION
**Pull request by kpdyer16**
## Purpose / Description
Some devices rely on hebrew translations being in the `values-heb` resource directory and others rely on the translations being in `values-iw`. The solution seems to be to have those values duplicated into `values-iw` in addition to `values-heb`.

## Fixes
* Fixes #9451 

## Approach
_How does this change address the problem?_
This change reuses the same algorithm used for updating localization resources, with the addition of writing the contents of `values-he` to both `values-heb` and `values-iw`. The only difference now is that `androidLanguage` becomes an array of `androidLanguages`. `androidLanguage` originally represents the destination to copy to, so we iterate through this array to copy the current languages source files to the destinations we set. What this _should_ do is provide the necessary localization files for the devices that rely on them. This is mentioned in the issue, but it's the suggested solution here https://stackoverflow.com/a/8843293/9910298.

## How Has This Been Tested?

I haven't tested if this fixes the issue for the device in question. However, I have tested on my machine that it produces a `values-iw` directory with the correct contents. I've diffed it with `values-heb` and confirmed they're identical. 
Note: I used an old download of the Crowdin localization files, and there were a few things missing from it that the update script is built to throw an error if missing, e.g. the `values-sc` directory, and the `20-search-preference.xml` located in each localization directory. For those, I copied over those specific resources to the temp directory and it worked just fine after that. Let me know if the testing needs to be more rigorous.

## Learning (optional, can help others)
I'm somewhat familiar with Jest tests, and as I began to write tests for my changes, I noticed a few key problems to solve.

1. The working directory for my tests are different than the update script I was working with. This matters because the update script relies on relative paths to do its work. This is possible to fix with [process.chdir()](https://nodejs.org/api/process.html#processchdirdirectory)
2. Even if we were to run the update scripts as is in our tests, the cleanup would be awful since it mutates the files we're working with, and possibly slow, since it involves I/O operations.

A potential solution is to mock the filesystem module `fs` in our tests with an in-memory filesystem like [memfs](https://www.npmjs.com/package/memfs). An in memory filesystem mock would allow us to test certain features with granularity (i.e. throw an error if a necessary file is missing, or test if values-he is correctly duplicated in my case).

The tradeoff is that there is a lot of setup involved. I'm thinking it might be doable if we kept a rough json object, or wrote a builder that properly generates the contents of a typical download from Crowdin, but that can be discussed in more detail. 

_Links to blog posts, patterns, libraries or addons used to solve this problem_
- (Tried using this pattern here) https://stackoverflow.com/questions/74841423/how-to-mock-file-system-with-memfs-in-nodejs
- (I was going to mock the relative directories instead if we go with an in mem filesystem. it would look cleaner imo) https://jestjs.io/docs/mock-functions#mocking-partials
- (necessary context for mocking `fs`) https://jestjs.io/docs/manual-mocks#mocking-node-modules

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison** [comment]
Just as an FYI: your StackOverflow link leaks your user Id -> username

`https://stackoverflow.com/a/8843293/` does not contain your user ID

File: tools/localization/src/update.ts [hunk 1]
```diff
@@ -180,59 +180,61 @@ export async function updateI18nFiles() {
...
 
         switch (language) {
             case "yu":
-                androidLanguage = "yue";
+                androidLanguages = ["yue"];
                 break;
 
             case "he":
-                androidLanguage = "heb";
+                androidLanguages = ["heb", "iw"];
```
Comment (david-allison) [inline tools/localization/src/update.ts:197]: nit: add a comment explaining this issue/linking here

It would be useful to know if/when we can remove this code.

**Review by david-allison — APPROVED** [review]
Looks great!

https://github.com/ankidroid/Anki-Android/pull/16316/files?w=1 shows minimal changes

Solution is how I'd do this

**Review by Aditya13s — APPROVED** [review]

**Review by mikehardy — APPROVED** [review]
This looks good to me pending adding the comment, I'm going to do that then try a strings sync so we can get this in for 2.18

File: tools/localization/src/update.ts (hunk 1 above)
Comment (mikehardy) [inline tools/localization/src/update.ts:197]:
```suggestion
                // some Android phones use values-heb, some use values-iw - issue 9451
                // the only way for Hebrew to work on all devices is to duplicate settings
                androidLanguages = ["heb", "iw"];
```

**Comment by mikehardy** [comment]
Results look great! #16339
