### PR TITLE
Fix: play audio-only fils with video extension as audio

### LINKED ISSUE #15872: [BUG]: audio-only webm file is displayed with `<video>`
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Add the .apkg (from the zip attached). It contains 1 card with 1 audio (.webm) - OR just insert the attached audio on a card. 
2. Preview the card or get it during a review.

- [bug-audio.zip](https://github.com/ankidroid/Anki-Android/files/14577670/bug-audio.zip) (.apkg inside a zip, since github refuse that I upload the apkg directly)
- [audio.webm](https://github.com/ankidroid/Anki-Android/assets/8039130/cbee38b7-c2f1-4d4d-9ebf-85c5ac0be862)

### Expected behaviour

Expected the audio player to
1. autoplay the audio (for now it does not)
2. the three dot menu > "replay audio" during review to works (nothing happens for now)
3. to not have such a large UI displayed for the audio. A single play/pause like before was really cool, but maybe the change was a feature.

### Actual behaviour

Here is how the audio player is shown.

### Debug info

```text
AnkiDroid Version = 2.17.5 (1c1aa94ec466f37d33fd2f75020d9f9021ac811e)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 12 (SDK 31)

ProductFlavor = play

Manufacturer = Xiaomi

Model = M2002J9G

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; M2002J9G Build/SKQ1.211006.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.64 Mobile Safari/537.36

ACRA UUID = c376c16e-c3b2-4d06-83c9-fa6d4d143664

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

- I saw someone else on reddit posted the same issue as me today: https://www.reddit.com/r/Anki/comments/1bcq51m/mpeg_files_in_ankidroid/
- I was on beta program, tried to downgrade to non-beta but same thing keep happening.
- I realized after writing the whole issue that my audio file was named .webm but is probably a .mp3 actually. I have checked the same with true .webm file, the same happens.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison**
## Description
A number of video extension may only contain audio In these cases, we should show a play button

Thanks to Brayan for starting this off

## Fixes
* Fixes #15872 

## How Has This Been Tested?
API 23 emulator and API 33 emulator using 
[15872-repros.colpkg.zip](https://github.com/ankidroid/Anki-Android/files/14592076/15872-repros.colpkg.zip)

Unit tests use the same files

## Learning (optional, can help others)

I attempted to use MediaMetadataRetriever:

```kotlin
MediaMetadataRetriever().let {
    it.setDataSource(file.path)
    it.extractMetadata(MediaMetadataRetriever.METADATA_KEY_HAS_VIDEO)
}
```

but it fails on API 23 with:

```
java.lang.RuntimeException: setDataSource failed: status = 0x80000000
at android.media.MediaMetadataRetriever.setDataSource(Native Method)
```

Sources:
* anki-15872-valid-1.mp4 -> https://github.com/chromium/chromium/blob/main/third_party/blink/web_tests/external/wpt/media/movie_5.mp4
* anki-15872-audio-only.webm -> https://github.com/chromium/chromium/blob/main/third_party/blink/web_tests/external/wpt/media/test-a-128k-44100Hz-1ch.webm
* anki-15872-audio-only.mp4 -> https://github.com/chromium/chromium/blob/main/third_party/blink/web_tests/external/wpt/media-source/mp4/test-a-128k-44100Hz-1ch.mp4

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by mikehardy** [comment]
Hmm

```

com.ichi2.anki.libanki.SoundTest > audioOnlyMp4IsDetected[emulator-5554 - 11] FAILED 
	java.lang.AssertionError: mp4 should be audio only
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:26)

com.ichi2.anki.libanki.SoundTest > audioOnlyWebmIsDetected[emulator-5554 - 11] FAILED 
	java.lang.AssertionError: webm should be audio only
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:26)
```

re-running on the off chance it is flaky

**Comment by david-allison** [comment]
Broke `ComaptV29` in a refactor thank goodness for unit tests

File: AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt [hunk 1]
```diff
@@ -387,3 +398,16 @@ fun getFileUri(path: String): URI {
...
 }
+
+@VisibleForTesting
+fun isVideo(file: File): Boolean {
+    // if it's video-only, then it's video
+    if (file.extension in VIDEO_ONLY_EXTENSIONS) return true
+    // if neither video only nor video & audio, then it's not video
+    if (file.extension !in AUDIO_OR_VIDEO_EXTENSIONS) return false
+
+    if (!file.exists()) return true
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt:409]: if the file doesn't exist, it can't be a video

File: AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt [hunk 2]
```diff
@@ -311,19 +312,29 @@ class TemplateManager {
...
-        } else {
-            match.value
+        when (extension) {
+            in VIDEO_ONLY_EXTENSIONS -> {
+                val path = Paths.get(mediaDir, fileName).toString()
+                toVideoTag(path)
+            }
+            in AUDIO_OR_VIDEO_EXTENSIONS -> {
+                val file = File(mediaDir, fileName)
+                // do not check for existence
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt:330]: may as well remove this comment, and add in `isVideo` doc that it would return false if the file doesn't exist

**Review by BrayanDSO — CHANGES_REQUESTED** [review]

File: AnkiDroid/src/androidTest/java/com/ichi2/anki/libanki/SoundTest.kt [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+import androidx.test.ext.junit.runners.AndroidJUnit4
+import com.ichi2.anki.tests.InstrumentedTest
+import com.ichi2.anki.tests.Shared
+import com.ichi2.annotations.NeedsTest
+import com.ichi2.libanki.isVideo
+import org.hamcrest.MatcherAssert.assertThat
+import org.junit.Test
+import org.junit.runner.RunWith
+
+@NeedsTest("")
```
[the remark this answers is not in the document]
Comment (david-allison) [reply AnkiDroid/src/androidTest/java/com/ichi2/anki/libanki/SoundTest.kt]: Initially I was going to leave testing for a valid file. No longer needed

**Review by mikehardy — APPROVED** [review]
lgtm - @BrayanDSO I think your requests have been addressed? I don't them in current iteration

File: AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt [hunk 4]
```diff
@@ -387,3 +397,24 @@ fun getFileUri(path: String): URI {
...
+        return null
+    }
+
+    if (file.extension in VIDEO_ONLY_EXTENSIONS) return false
+
+    // file.extension is in AUDIO_OR_VIDEO_EXTENSIONS
+    if (!file.exists()) return null
+
+    // Also check that there is a video thumbnail, as some formats like mp4 can be audio only
+    val isVideo = CompatHelper.compat.hasVideoThumbnail(file.absolutePath) ?: return null
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt:418]: this will make harder to remove `android` from libanki later, but it's the best alternative for now

**Review by BrayanDSO — APPROVED** [review]
Looks great
