### PR TITLE
Fix changing the GUI language from the system default

### LINKED ISSUE #4729: GUI Language Settings are partly ignored
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps
0. Application's Language set to Language DIFFERENT to System's (Screenshot - Settings). In this case - System's language - Russian, AnkiDroid - English

1. Start Ankidroid (from closed state, not from background)
2. Check and note that some GUI elements are correctly displayed in selected GUI language (screenshot 1)
3. Check other places - like "Debug" info page - or start learning\reviewing cards - and check "Answer" buttons - note that they are not using the correct GUI language - they are using phone's "System" language (screenshots 2 and 3)
4. The issue is fixed upon returning to application's Main screen and opening up Menu (screenshots 4 and 5)
5. Upon closing the app (completely, not leaving it in background) and re-launching it - the issue reappears

###### Expected Result
Application should respect selected GUI language at all times

###### Actual Result
There are bugs in Application's GUI, forcing it to revert to System's language under some circumstances

###### Debug info
AnkiDroid Version = 2.8.2
Android Version = 7.0
ACRA UUID = 97cb4c7f-7bd4-469e-86a2-ebeffa03a8f0

###### Screenshots
[Screenshots.zip](https://github.com/ankidroid/Anki-Android/files/1453678/Screenshots.zip)

### PR DESCRIPTION
**Pull request by Arthus**
## Purpose / Description
If you currently change the language in AnkiDroid, the change won't really take effect in the GUI. Nearly all strings will still be in the Android system's default language.

With this PR I provide my partially working solution, as I seem to not get any further and want to provide the code so I can get some feedback and/or someone else can have a look at it.
This is also intended as an answer to Mike Hardy, who talked to me in the forums: https://groups.google.com/d/msg/anki-android/m3fhLy2RcZg/2Z-XDNx_BwAJ

## Fixes
Partially fixes #4729 
API levels 24 and lower will be fully localized. The language setting is applied to the whole application.
API level 25 and above will be localized on the main screen (DeckPicker, Settings) but the chosen GUI language won't apply to other activities.

## Approach
For APIs <= 24 the application's configuration is updated to the correct language:
   function UpdateContextWithLanguage -> call updateConfiguration()

For APIs > 24 the previous solution is deprecated. Instead the configuration should be changed during attachBase(). But the current solution can't be applied to attachBase() of AnkiDroidApp. The saved configuration seems to not be available when AnkiDroidApp's attachBase() is called, but is required to know, what language the GUI should be using.
By applying the solution of API <=24 to API > 24, the whole GUI has the right language (but this is deprecated!) This might not not be the "right way to do it", but should work.
Overwriting all attachBase() functions for all Anki activities might also work, but I haven't tried that.

## How Has This Been Tested?
As this is only a have working draft, this has only been tested very superficially by using the Android emulators. (APIs: 15, 19, 25, 29)
Starting the app, opening the settings, changing the language, closing & opening the App, opening some menus.
On some devices, a single card was created and learned.

No crashes or abnormal behavior were experienced during testing.

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.java [hunk 1]
```diff
@@ -16,7 +16,10 @@
 
 package com.ichi2.ui;
 
+import android.annotation.TargetApi;
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.java:19]: Codacy Issue found: [Avoid unused imports such as 'android.annotation.TargetApi'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5497616)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 6
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5497616&bid=18017719)

File: AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.java [hunk 2]
```diff
@@ -16,7 +16,10 @@
...
+import android.content.Context;
 import android.content.res.Configuration;
+import android.os.Build;
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.java:22]: Codacy Issue found: [Avoid unused imports such as 'android.os.Build'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5497616)

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 3]
```diff
@@ -336,23 +347,60 @@ public static void deleteACRALimiterData(Context context) {
         context.getFileStreamPath("ACRA-limiter.json").delete();
     }
 
+    /**
+     *  Returns a Context with the correct, saved language, to be attached using attachBase(). For old APIs directly sets language using deprecated functions
+     *
+     * @param remoteContext The base context offered by attachBase() to be passed to super.attachBase(). Can be modified here to set correct GUI language.
+     */
+    @SuppressWarnings("deprecation")
+    public static Context UpdateContextWithLanguage(Context remoteContext){
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:356]: Codacy Issue found: [The static method name 'UpdateContextWithLanguage' doesn't match '[a-z][a-zA-Z0-9]*'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5497616)

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 4]
```diff
@@ -19,33 +19,31 @@
 package com.ichi2.anki;
 
 import android.annotation.SuppressLint;
+import android.annotation.TargetApi;
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:22]: Codacy Issue found: [Avoid unused imports such as 'android.annotation.TargetApi'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5497616)

File: AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java [hunk 5]
```diff
@@ -15,9 +15,12 @@
  ****************************************************************************************/
 package com.ichi2.anki;
 
+import android.annotation.TargetApi;
+import android.content.Context;
 import android.content.Intent;
 import android.graphics.Color;
 import android.os.AsyncTask;
+import android.os.Build;
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java:23]: Codacy Issue found: [Avoid unused imports such as 'android.os.Build'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5497616)

File: AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java [hunk 6]
```diff
@@ -15,9 +15,12 @@
  ****************************************************************************************/
 package com.ichi2.anki;
 
+import android.annotation.TargetApi;
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java:18]: Codacy Issue found: [Avoid unused imports such as 'android.annotation.TargetApi'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5497616)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5497616&bid=18017719)

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 7]
```diff
@@ -209,6 +218,8 @@ public void onCreate() {
         // Get preferences
         SharedPreferences preferences = getSharedPrefs(this);
 
+        UpdateContextWithLanguage(getApplicationContext());
```
[the remark this answers is not in the document]
Comment (Arthus) [reply AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java]: Was fixed before you commented. :)

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 8]
```diff
@@ -190,6 +191,14 @@ private void setAcraConfigBuilder(CoreConfigurationBuilder acraCoreConfigBuilder
         ACRA.init(this, acraCoreConfigBuilder);
     }
 
+    @Override
+    protected void attachBaseContext(Context base) {
+        //Switch comments below to crash on App start (getSharedPrefs() fails with NullPointerException),
+        //but theoretically this should set the GUI language for the whole application on startup
+
+        //super.attachBaseContext(UpdateContextWithLanguage(base));
+        super.attachBaseContext(base);
```
[the remark this answers is not in the document]
Comment (Arthus) [reply AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:199]: Afaik attachBase is always called before onCreate. And it can only be called once.

I'm not even sure, if this is the best way to do it.
By changing line 229 in AnkiStatsTaskHandler.java from
`                Resources res = collection.getContext().getResources();`
to
`                Resources res = AnkiDroidApp.updateContextWithLanguage(collection.getContext()).getResources();`
you can obviously fix the language of the "studied_cards_today" string, but I can'f find out, why the application's context doesn't apply to the collection's context (when is it created, etc)

Someone with more experience in the code base might be able fix this faster than me.

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 9]
```diff
@@ -228,7 +239,7 @@ public void onCreate() {
             UsageAnalytics.setDryRun(true);
         }
 
-        setLanguage(preferences.getString(Preferences.LANGUAGE, ""));
+        //setLanguage(preferences.getString(Preferences.LANGUAGE, ""));
```
[the remark this answers is not in the document]
Comment (Arthus) [reply AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java]: Done

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 10]
```diff
@@ -336,23 +347,60 @@ public static void deleteACRALimiterData(Context context) {
...
+                //first element of setLocales() is automatically setLocal()
+                newConfig.setLocales(newLocaleList);
+            } else {
+                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1){
+                    //API level >=17 but <24
+                    newConfig.setLocale(newLocale);
+                } else {
+                    //Legacy, API level < 17
+                    newConfig.locale = newLocale;
+                    }
```
[the remark this answers is not in the document]
Comment (Arthus) [reply AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java]: In fact, most of the function was indented wrong. Should be fixed all together

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 11]
```diff
@@ -336,23 +346,60 @@ public static void deleteACRALimiterData(Context context) {
...
-        Configuration config = getInstance().getResources().getConfiguration();
-        Locale newLocale = LanguageUtil.getLocale(localeCode);
-        config.locale = newLocale;
-        getInstance().getResources().updateConfiguration(config, getInstance().getResources().getDisplayMetrics());
+    public static Configuration getLanguageConfig(Configuration remoteConfig) {
+        Configuration newConfig = new Configuration(remoteConfig);
+        Locale newLocale = LanguageUtil.getLocale(getSharedPrefs(AnkiDroidApp.getInstance()).getString(Preferences.LANGUAGE, ""));
+
+            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
+                String strLocallist;
```
[the remark this answers is not in the document]
Comment (Arthus) [reply AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java]: Fixed

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java [hunk 12]
```diff
@@ -54,12 +54,21 @@
     protected void onCreate(Bundle savedInstanceState) {
         // The hardware buttons should control the music volume
         setVolumeControlStream(AudioManager.STREAM_MUSIC);
+
+        AnkiDroidApp.updateContextWithLanguage(this);
+        //attachBaseContext(AnkiDroidApp.GetBaseContextWithLanguage(getBaseContext()));
```
[the remark this answers is not in the document]
Comment (Arthus) [reply AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java]: Yup, done.

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 13]
```diff
@@ -336,23 +347,60 @@ public static void deleteACRALimiterData(Context context) {
...
 
+    /**
+     *  Returns a Context with the correct, saved language, to be attached using attachBase(). For old APIs directly sets language using deprecated functions
+     *
+     * @param remoteContext The base context offered by attachBase() to be passed to super.attachBase(). Can be modified here to set correct GUI language.
+     */
+    @SuppressWarnings("deprecation")
+    public static Context UpdateContextWithLanguage(Context remoteContext){
+        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N_MR1){
+            return remoteContext.createConfigurationContext(getLanguageConfig(remoteContext.getResources().getConfiguration()));
```
[the remark this answers is not in the document]
Comment (Arthus) [reply AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java]: Good idea, done.

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 14]
```diff
@@ -336,23 +346,60 @@ public static void deleteACRALimiterData(Context context) {
...
+    public static Configuration getLanguageConfig(Configuration remoteConfig) {
+        Configuration newConfig = new Configuration(remoteConfig);
+        Locale newLocale = LanguageUtil.getLocale(getSharedPrefs(AnkiDroidApp.getInstance()).getString(Preferences.LANGUAGE, ""));
+
+            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
+                String strLocallist;
+                strLocallist = newLocale.toString()+",";
+                // +Locale.getDefault().toString()+","+"";
+                //strLocallist = "de,fr,en";
+                if (!strLocallist.contains(Locale.getDefault().toString()))
```
[the remark this answers is not in the document]
Comment (Arthus) [reply AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java]: Cleaned it up and commented the remaining code.
I'm not even sure if this is really needed, but doing some "push_front" on the default locale instead of completely overwriting it, seemed the right thing to do.

**Comment by Arthus** [comment]
Hi,

today I worked on it a little more and I think I may have resolved the outstanding issues. On the emulators all APIs get translated.
I also experienced the crash you described and I fixed it. With several languages, including Chinese (Taiwan) (zh_TW) and pt_rBR, it works fine.

I will do some cleanup and push a new version. Propably on friday.

**Comment by david-allison-1** [comment]
No rush @Arthus, and thanks for your patience. 

Sorry I didn't get around to a full review at an earlier time, but I'm looking forward to the fixes.

**Comment by mikehardy** [comment]
I'm really excited about this as well - please be patient with us for a bit though, we've been working really hard to get 2.10 shipped and now that it's out we're handling the inevitable regressions with the limited time we have available. This is too good to sit for too long though - so hold tight and we'll get there :-)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5497616&bid=18017719)

**Comment by Arthus** [comment]
Ok, I pushed a new version. Now, for all APIs (16 to 28) the choosen language is applied to the complete app. I couldn't find any places that are not translated.
Also I can't reproduce any crashes, no matter how crazy I change the language in the app and/or system.

There are a few points, that need to be discussed:
1) I was able to load the configuration during AnkiDroidApp.attachBaseContext() (the way it is "meant" to be done. But this has a drawback: As this is only called once during app startup, you would always have to restart the App, so the new language gets applied.
I solved this now, by dynamically updating the application context when getAppResources() is called, so this always returns the resources for the currently chosen language.
When this is done, the attachBaseContex() overwrite becomes unnecessary, because, even if it is not done, every getAppResources() will always return the correct strings. 
This saves code and I currently see no advantage in overwriting attachBaseContext() in AnkiDroidApp.

2) Is there a way to reset the language setting when upgrading the app? Of course I could write something, but maybe there's already some infrastructure I could use.
There might be users, that have changed the setting to something crazy. But because the setting is not working, they might not notice, they have changed it some time ago themselves. If the setting gets applied now correctly, they might report this as a regression.
I'm not sure if it's worth the time/code, but when upgrading to a version, that applies the language setting correctly, we could reset the language preference to its default on the first run.

**Comment by david-allison-1** [comment]
@mikehardy Lint checks appear broken on unmodified methods: Ref: #6186

https://travis-ci.org/github/ankidroid/Anki-Android/jobs/687795158

<details>

```
/home/travis/build/ankidroid/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java:470: Error: Unknown nullability; explicitly declare as @Nullable or @NonNull to improve Kotlin interoperability; see https://android.github.io/kotlin-guides/interop.html#nullability-annotations [UnknownNullness]
    public DialogHandler getDialogHandler() {
           ~~~~~~~~~~~~~
/home/travis/build/ankidroid/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:568: Error: Unknown nullability; explicitly declare as @Nullable or @NonNull to improve Kotlin interoperability; see https://android.github.io/kotlin-guides/interop.html#nullability-annotations [UnknownNullness]
        protected void log(int priority, String tag, @NonNull String message, Throwable t) {
                                         ~~~~~~
/home/travis/build/ankidroid/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:568: Error: Unknown nullability; explicitly declare as @Nullable or @NonNull to improve Kotlin interoperability; see https://android.github.io/kotlin-guides/interop.html#nullability-annotations [UnknownNullness]
        protected void log(int priority, String tag, @NonNull String message, Throwable t) {
                                                                              ~~~~~~~~~
/home/travis/build/ankidroid/Anki-Android/AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.java:110: Error: Unknown nullability; explicitly declare as @Nullable or @NonNull to improve Kotlin interoperability; see https://android.github.io/kotlin-guides/interop.html#nullability-annotations [UnknownNullness]
    public void onConfigurationChanged(Configuration newConfig) {
```
</details>

**Comment by Arthus** [comment]
Yeah, it also reports some places, that I haven't even touched. So is it a problem with Lint?

On another note: First, it's no problem that things are moving slow right now. In fact, I'm grateful that I don't have to rush, learning things. I just hope, you will excuse the horrible code I might upload. :)

Finally, is there a reason, the minimum API version only got pushed to 16? If the minimum version was at least 17, I could remove a legacy code path from the PR. And ofc the bold move would propably be to go to API 19 (Android 4.4), which I think is the oldest version, that most apps support.
Do you have a statistic, how many devices with APIs 16-18 currently run AnkiDroid?

**Comment by mikehardy** [comment]
- the lint checks are somewhat unrelated apparently I still have some work to do on #6186 
- if a user has set the system language to something off and it gets applied correctly now I'm okay with that. An uninstall/reinstall will fix them I believe, with no collection loss
- the api16 minimum has the user count #5665 I believe, but from top of my head it's a few thousand that still use API16, and easily tens of thousands through API19. I see no compelling reason to cut these folks off right now, I only bumped to 16 because some of our upstream Google library dependencies have it set as their minimum, and API15 can't sync with AnkiWeb anyway so there's a big functionality drop. It needs to be something like that to move it I think as this app (in my mind) should work on the cheapest crappiest hand-me-down phone an aspiring doctor can find in the developing world - those are real users we have

**Comment by david-allison-1** [comment]
> Yeah, it also reports some places, that I haven't even touched. So is it a problem with Lint?

Not your problem at all, lint changes were implemented yesterday, and they need some more work

> On another note: First, it's no problem that things are moving slow right now. In fact, I'm grateful that I don't have to rush, learning things. I just hope, you will excuse the horrible code I might upload. :)

The effort is much appreciated, but please ping me if you're at all getting frustrated by the speed of replies. 

> Finally, is there a reason, the minimum API version only got pushed to 16? If the minimum version was at least 17, I could remove a legacy code path from the PR. And ofc the bold move would propably be to go to API 19 (Android 4.4), which I think is the oldest version, that most apps support.
> Do you have a statistic, how many devices with APIs 16-18 currently run AnkiDroid?

Roughly 8000

> Ok, I pushed a new version. Now, for all APIs (16 to 28) the choosen language is applied to the complete app. I couldn't find any places that are not translated.
> Also I can't reproduce any crashes, no matter how crazy I change the language in the app and/or system.

Fantastic!!! Thank you so much

----

> 
> There are a few points, that need to be discussed:
> 
> 1. I was able to load the configuration during AnkiDroidApp.attachBaseContext() (the way it is "meant" to be done) But this has a drawback: As this method is only called once during app startup, you would always have to restart the App, for the new language to get applied.
>    I solved this now, by dynamically updating the application context when getAppResources() is called, so this always returns the resources for the currently chosen language.
>    When this is done, the attachBaseContex() overwrite becomes unnecessary, because, even if it is not done, every getAppResources() will always return the correct strings.
>    This saves code and I currently see no advantage in overwriting attachBaseContext() in AnkiDroidApp.

I also had a look and got `attachBaseContext` working, but agreed.


> 2. Is there a way to reset the language setting when upgrading the app? Of course I could write something, but maybe there's already some infrastructure in place that could be used.
>    I could imagine the following situation arises:
>    There might be users, that have changed the language setting to something crazy. But because the setting is not working, they might not notice, they have changed it some time ago themselves. If the setting gets applied now correctly, they might report this as a regression, because after an update, their App is suddenly in the "wrong" language.
>    I'm not sure if it's worth the time/code, but when upgrading to a version, that applies the language setting correctly, we could reset the language preference to its default on the first run.

I don't think this will be worth the code.

> 3. Performance impact of modified getAppResources(): With my new version, everytime this method is called, the whole "updateContextWithLanguage()" path is used to update sInstance's Resources and return them.
>    I could implement a second version of updateContextWithLanguage() to do something like
>    sInstance = updateContextWithLanguage(this);
>    everytime the language is changed. This means more code.
> 
> I could implement another variable like sResources in AnkiDroidApp, so we additionally save a prepared a prepared resource that gets returned by getAppResources(), this means a little more memory usage.
> 
> I can do it like I have done it in the current version, calling updateContextWithLanguage() often, this means more calls, more processing, less performance.
> 
> Any preferences from you here? Do you know a good way, to measure the impact?

The Android Studio Profiler, or timing via logcat messages `Timber.d`. If it's significant, we should probably deal with it, if not, mark it as a comment with a `NICE_TO_HAVE:` prefix.

I think we might have an issue here, but it's best to measure and compare.

As much as they're hated, I'd be happy with a global or a singleton here if we need the performance - it's updated in one place and is global data. I don't think it's much code at all to add

----

I really appreciate the thoroughness of the comments and the thought that's gone into this feature, thank you :)

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 15]
```diff
@@ -26,26 +26,23 @@
 import android.content.SharedPreferences;
 import android.content.res.Configuration;
 import android.content.res.Resources;
+import android.os.Build;
 import android.os.Environment;
+import android.os.LocaleList;
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:31]: Could you revert these line changes? This is a complex PR that we'll likely need to look at in detail, and it's best to avoid line noise to focus on what matters.

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 16]
```diff
@@ -190,6 +190,14 @@ private void setAcraConfigBuilder(CoreConfigurationBuilder acraCoreConfigBuilder
         ACRA.init(this, acraCoreConfigBuilder);
     }
 
+    @Override
+    protected void attachBaseContext(Context base) {
+        //Switch comments below to crash on App start (getSharedPrefs() fails with NullPointerException),
+        //but theoretically this should set the GUI language for the whole application on startup
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:196]: We can get this working, and probably should as there are references:

https://github.com/ankidroid/Anki-Android/blob/3858c3f02b8a992d121a51236ddcd4366096b214/AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java#L1066

* Extract `getSharedPrefs(AnkiDroidApp.getInstance())` in `getLanguageConfig()` to a parameter (Ctrl+Alt+P)
* Extract `getSharedPrefs(AnkiDroidApp.getInstance())` in `updateContextWithLanguage` to a local variable (Ctrl+Alt+V)
* Extract method: updateContextWithLanguage(Context, SharedPreferences) : Ctrl+Alt+M
* Call `updateContextWithLanguage(base, getSharedPrefs(base))` here

I think there's slight value in this. as the majority of users will not have updated their preferences, and it makes us consistent with the typical manner of updating preferences

If you decide to do this, do note here about the fact that a language change won't affect this, and that other techniques are used to handle this.

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 17]
```diff
@@ -209,6 +217,8 @@ public void onCreate() {
         // Get preferences
         SharedPreferences preferences = getSharedPrefs(this);
 
+        updateContextWithLanguage(getApplicationContext());
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:220]: If the above comment is implemented. this line no longer needs to exist

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 18]
```diff
@@ -300,7 +309,7 @@ public static String getCacheStorageDirectory() {
     }
 
     public static Resources getAppResources() {
-        return sInstance.getResources();
+        return updateContextWithLanguage(sInstance).getResources();
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:312]: Probably best to cache here, as it's heavily used and should be fast (profiling was discussed in the comments, but I'd err on the side of speed here.

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 19]
```diff
@@ -336,23 +345,59 @@ public static void deleteACRALimiterData(Context context) {
...
     }
 
+    /**
+     *  Returns a Context with the correct, saved language, to be attached using attachBase(). For old APIs directly sets language using deprecated functions
+     *
+     * @param remoteContext The base context offered by attachBase() to be passed to super.attachBase(). Can be modified here to set correct GUI language.
+     */
+    @SuppressWarnings("deprecation")
+    public static Context updateContextWithLanguage(Context remoteContext){
+        Configuration langConfig = getLanguageConfig(remoteContext.getResources().getConfiguration());
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:355]: Can we wrap this in a try..catch, send an exception report on failure: `            AnkiDroidApp.sendExceptionReport(e, [context string]);`, and return `remoteContext`

Example issue: a user previously had `zh_TW` in their config, I don't /think/ this would crash, but we should assume that user data is unexpectedly bad.

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 20]
```diff
@@ -336,23 +345,59 @@ public static void deleteACRALimiterData(Context context) {
...
      */
     @SuppressWarnings("deprecation") // Tracked as #4729 in github
-    public static void setLanguage(String localeCode) {
-        Configuration config = getInstance().getResources().getConfiguration();
-        Locale newLocale = LanguageUtil.getLocale(localeCode);
-        config.locale = newLocale;
-        getInstance().getResources().updateConfiguration(config, getInstance().getResources().getDisplayMetrics());
+    private static Configuration getLanguageConfig(Configuration remoteConfig) {
+        Configuration newConfig = new Configuration(remoteConfig);
+        Locale newLocale = LanguageUtil.getLocale(getSharedPrefs(AnkiDroidApp.getInstance()).getString(Preferences.LANGUAGE, ""));
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:372]: Line is too long, and duplicated at the bottom of the PR, could you combine these, extract to `LanguageUtil` and maybe extract some variables (Ctrl+Alt+V).

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 21]
```diff
@@ -336,23 +345,59 @@ public static void deleteACRALimiterData(Context context) {
...
+
+        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
+            //Build list of locale strings, separated by commas: newLocale as first element
+            String strLocaleList = newLocale.toLanguageTag();
+            //if Anki locale from settings is no equal to system default, add system default as second item
+            //LocaleList must not contain language tags twice, will crash otherwise!
+            if (!strLocaleList.contains(Locale.getDefault().toLanguageTag()))
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:379]: nit; Could you add braces to be consistent with the codebase

File: AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java [hunk 22]
```diff
@@ -45,15 +39,18 @@
...
-
 import com.ichi2.utils.JSONException;
 import com.ichi2.utils.JSONObject;
 
 import java.util.ArrayList;
-import java.util.Arrays;
-import java.util.List;
 import java.util.Locale;
 
+import androidx.appcompat.app.ActionBar;
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java:48]: nit: Likewise, could these changes be reverted

File: AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.java [hunk 23]
```diff
@@ -44,6 +47,12 @@ protected void onCreate(Bundle savedInstanceState) {
         getDelegate().installViewFactory();
         getDelegate().onCreate(savedInstanceState);
         super.onCreate(savedInstanceState);
+        AnkiDroidApp.updateContextWithLanguage(this);
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.java:50]: Are both of these lines required? I'd have expected we'd only need the `attachBaseContext`

File: AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.java [hunk 24]
```diff
@@ -58,9 +58,10 @@ public static Locale getLocale(String localeCode) {
             // If no code provided use the app language.
         }
         if (TextUtils.isEmpty(localeCode)) {
-            locale = Locale.getDefault();
             // Fall back to (system) default only if that fails.
-        } else if (localeCode.length() > 2) {
+            localeCode = Locale.getDefault().toString();
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.java:62]: (optional) - It would be useful to add a couple of unit tests here (if possible - cultures can be a pain) as the functionality has changed.

Mostly to document the new intent of the code

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 25]
```diff
@@ -336,23 +345,59 @@ public static void deleteACRALimiterData(Context context) {
...
+     *
+     * @param remoteContext The base context offered by attachBase() to be passed to super.attachBase(). Can be modified here to set correct GUI language.
+     */
+    @SuppressWarnings("deprecation")
+    public static Context updateContextWithLanguage(Context remoteContext){
+        Configuration langConfig = getLanguageConfig(remoteContext.getResources().getConfiguration());
+        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N_MR1){
+            return remoteContext.createConfigurationContext(langConfig);
+        } else {
+            remoteContext.getResources().updateConfiguration(langConfig,remoteContext.getResources().getDisplayMetrics());
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:359]: nitpick: add a space after the comma: `langConfig, remoteContext.`

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java [hunk 26]
```diff
@@ -34,14 +25,21 @@
...
 import com.ichi2.compat.customtabs.CustomTabsHelper;
 import com.ichi2.libanki.Collection;
 import com.ichi2.themes.Themes;
 import com.ichi2.utils.AdaptionUtil;
 
+import androidx.appcompat.app.AppCompatActivity;
+import androidx.browser.customtabs.CustomTabsIntent;
+import androidx.core.app.NotificationCompat;
+import androidx.core.content.ContextCompat;
+import androidx.fragment.app.DialogFragment;
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java:39]: Likewise, could you revert the import changes

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java [hunk 27]
```diff
@@ -59,12 +57,19 @@
     protected void onCreate(Bundle savedInstanceState) {
         // The hardware buttons should control the music volume
         setVolumeControlStream(AudioManager.STREAM_MUSIC);
+        AnkiDroidApp.updateContextWithLanguage(this);
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java:60]: Could you explain in `attachBaseContext` or `updateContextWithLanguage` if this duplication is necessary, it seems superfluous

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java (hunk 19 above)
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:355]: It would be useful to over-document this method, (reasons for usage, why we sometimes don't use the return value) as it's something that'll confuse people unfamiliar with this matter.

**Comment by mikehardy** [comment]
The unrelated lint CI failure should be fixed by #6202 once I have that shaped up and merged - then you can rebase against it or we can manually run the emulator checks (I just checked: that is possible / I can do that) in order to get "CI approval" on this, it won't block the effort here.

**Comment by mikehardy** [comment]
(my lint-related CI change seemed correct first time, I just merged it - so you may rebase from updated master now, or we can just manually work this one through as is, either way works for me)

File: AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.java [hunk 28]
```diff
@@ -35,32 +36,42 @@
...
+    }
+
     /**
      * Returns the {@link Locale} for the given code or the default locale, if no code is given.
      *
      * @param localeCode The locale code of the language
      * @return The {@link Locale} for the given code
      */
-    public static Locale getLocale(String localeCode) {
+    public static Locale getLocale(String localeCode, SharedPreferences prefs) {
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.java:63]: Codacy Issue found: [Avoid reassigning parameters such as 'localeCode'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5497616)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5497616&bid=18017719)

**Comment by mikehardy** [comment]
I just added a pile of new locales that were targetted for translation in crowdin but had never been included in the app (!), so this will be more fun to test shortly :-) #6217

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 29]
```diff
@@ -336,23 +335,74 @@ public static void deleteACRALimiterData(Context context) {
...
+     * @param remoteContext The base context offered by attachBase() to be passed to super.attachBase().
+     *                      Can be modified here to set correct GUI language.
+     */
+    @SuppressWarnings("deprecation")
+    public static Context updateContextWithLanguage(Context remoteContext){
+        SharedPreferences preferences;
+        //sInstance (returned by getInstance() ) set during application OnCreate()
+        //if getInstance() is null, the method is called during applications attachBaseContext()
+        // and preferences need mBase directly (is provided by remoteContext during attachBaseContext())
+        if (getInstance()  != null) {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:351]:
```suggestion
        if (getInstance() != null) {
```

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 30]
```diff
@@ -336,23 +335,74 @@ public static void deleteACRALimiterData(Context context) {
...
+            preferences = getSharedPrefs(getInstance().getBaseContext());
+        } else {
+            preferences = getSharedPrefs(remoteContext);
+        }
+        Configuration langConfig = getLanguageConfig(remoteContext.getResources().getConfiguration(), preferences);
+        //API level >= 25: supported since API 17
+        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1){
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:358]:
```suggestion
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
```

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 31]
```diff
@@ -336,23 +335,74 @@ public static void deleteACRALimiterData(Context context) {
...
      */
     @SuppressWarnings("deprecation") // Tracked as #4729 in github
-    public static void setLanguage(String localeCode) {
-        Configuration config = getInstance().getResources().getConfiguration();
-        Locale newLocale = LanguageUtil.getLocale(localeCode);
-        config.locale = newLocale;
-        getInstance().getResources().updateConfiguration(config, getInstance().getResources().getDisplayMetrics());
+    private static Configuration getLanguageConfig(Configuration remoteConfig, SharedPreferences prefs) {
+        Configuration newConfig = new Configuration(remoteConfig);
+        Locale newLocale = LanguageUtil.getLocale(prefs.getString(Preferences.LANGUAGE, ""),prefs);
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:376]:
```suggestion
        Locale newLocale = LanguageUtil.getLocale(prefs.getString(Preferences.LANGUAGE, ""), prefs);
```

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 32]
```diff
@@ -336,23 +335,74 @@ public static void deleteACRALimiterData(Context context) {
...
+        //API level >= 25
+        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
+            //Build list of locale strings, separated by commas: newLocale as first element
+            String strLocaleList = newLocale.toLanguageTag();
+            //if Anki locale from settings is no equal to system default, add system default as second item
+            //LocaleList must not contain language tags twice, will crash otherwise!
+            if (!strLocaleList.contains(Locale.getDefault().toLanguageTag())) {
+                strLocaleList = strLocaleList+","+Locale.getDefault().toLanguageTag();
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:384]:
```suggestion
                strLocaleList = strLocaleList + "," + Locale.getDefault().toLanguageTag();
```

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 33]
```diff
@@ -336,23 +335,74 @@ public static void deleteACRALimiterData(Context context) {
...
+            }
+
+            LocaleList newLocaleList = LocaleList.forLanguageTags(strLocaleList);
+            //first element of setLocales() is automatically setLocal()
+            newConfig.setLocales(newLocaleList);
+        } else {
+            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1){
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:391]:
```suggestion
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
```

File: AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java [hunk 34]
```diff
@@ -226,7 +226,7 @@ protected String doInBackground(Object... params) {
                         cur.close();
                     }
                 }
-                Resources res = collection.getContext().getResources();
+                Resources res = mTextView.getResources();
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java:229]: (unsure) Is using the `AnkiDroidApp` resources here better?

File: AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.java [hunk 35]
```diff
@@ -35,32 +36,42 @@
...
     }
 
+    /**
+     * Returns the {@link Locale} for the given code or the default locale, if no preferences are given.
+     *
+     * @return The {@link Locale} for the given code
+     */
+    public static Locale getLocale(String localeCode) {
+        SharedPreferences prefs = AnkiDroidApp.getSharedPrefs(AnkiDroidApp.getInstance().getBaseContext());
+        return getLocale(localeCode,prefs);
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.java:54]:
```suggestion
        return getLocale(localeCode, prefs);
```

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 36]
```diff
@@ -336,23 +335,74 @@ public static void deleteACRALimiterData(Context context) {
...
+    /**
+     *  Returns a Context with the correct, saved language, to be attached using attachBase().
+     *  For old APIs directly sets language using deprecated functions
+     *
+     * @param remoteContext The base context offered by attachBase() to be passed to super.attachBase().
+     *                      Can be modified here to set correct GUI language.
+     */
+    @SuppressWarnings("deprecation")
+    public static Context updateContextWithLanguage(Context remoteContext){
+        SharedPreferences preferences;
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:347]: My main concern is error handling here, could this method be wrapped in a try..catch..send error report and return the original context if this fails.

Comment (Arthus) [reply AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:347]: Can do that, but I'm unsure, which exceptions we should catch? All? This is (as far as I looked up) considered bad practice. And as long as we don't know, which exceptions might occur, we can't narrow it down.

Do you have a specific reason why you want a try-catch block here? Do you want it as a temporary measure, so when things get rolled out and it fails for 1% or the users, the impact gets reduced and the block gets removed later on, when no crashes occur?

If you want a exception handler here, I can add it.

File: AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java (hunk 34 above)
Comment (Arthus) [reply AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java:229]: mTextView is assigned when doInBackground is called from a parameter, and used in onPostExecute without any checks. If there were cases, when it wasn't provided correctly, I think this class would crash all the time, so I think it should be save to use it here.

As to why this is better than AnkiDroidApp's resources: mTextView's resources are created/updated with the correct language, when the DeckViewer gets refreshed. So this way we save:
1) The import of AnkiDroidApp into the file.
2) The need to update AnkiDroidApp's resources with the correct language during runtime.

**Comment by Arthus** [comment]
I'm finally able to comment on the latest revision (Had a struggle with Git when I tried to upload and even got only 2h of sleep that night... )
Will fix those space nits in the next push.

Commented on the request for an exception handler in updateContextWithLanguage(): If you can provide more information on the extent of the wished try-catch block, I can surely do that.

As to, why I still had the updateContextWithLanguage() calls in OnCreate etc in the last version: That's where they were supposed to be called in old API versions. I didn't notices, that even for APIs <17 the calls in attachBaseContext() would still work, so they were obviously unnecessary.

The current version comes with a catch: When the language is changed, nearly everything is translated correctly. A user can immediately use the app with the choosen language. Because I removed the updated/cached version of AnkiDroidApp's resources, the pop-up when you are asked to login to AnkiWeb is _not_ translated until the App is restarted. I think this is a tradeoff that's worth it. We save the need to cache the resources. When I tried that/thought about it, I noticed, that it would already be difficult the always make sure, that AnkiDroidApp's cached resources are always up to date. I couldn't find much information, on when those resources can actually change. (Can they change at all, when they are not updates manually? Is it enough to update them in onConfigurationUpdate()? Would we need to update the cache every X seconds?
Now the App is translated 95% immediately after changing the preferences and 100% after restarting the App.

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java (hunk 36 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:347]: TL;DR: Yes, but discussion is valuable, this is my opinion, and disagreements are more than welcome

* Java has a distinction between `Exception` and `Error`. Typically, you shouldn't try to catch an `Error` (OutOfMemoryError for example). 
* You shouldn't catch and ignore exceptions that you can't resolve, so somewhere higher up the stack will handle them
* You should handle exceptions individually, as you have the most context as to what's gone wrong and can take specific corrective action
* In this case, we can't easily anticipate all of the exceptions that will be thrown, and the list of exceptions that may be thrown is large.
* It's unlikely that any of the exceptions that we catch have a specific corrective action to be taken
* Throwing would crash the app, which is a serious issue if it occurs on startup. Even more serious as the base context may be attached before our error handler is initialised

----

In our case:

* We're at the point in the stack where we have a reasonable default to return on any exception
* The catch block is very unlikely to be executed
* If the catch block is executed, we call `AnkiDroidApp.sendExceptionReport(e, "updateContextWithLanguage");`
  * This allows us to diagnose the crash, the user will be notified of the problem, or the app will work as normal for them
  * This will do nothing before ACRA is set up, but we'll get an exception report on the second call
* It's a lot of effort to enumerate the possible exceptions which can be thrown
  * Even if we did, it's unlikely that any of them have a reasonable corrective action to take over the generic: "Return the `context` that we were provided with".
* It's reasonable for the contract of the method to state that the input will be returned if there is a failure.


----

Counterpoints:

* A `catch Exception` will catch `DeadSystemException`, but we're dead in the water anyway if this occurs.

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:347]: Catching Exception is not a bad practice, you are reading information from people that have studied a lot I think, but not programmed in the real world.

If you don't catch Exception the app will crash here, which is terrible. It's as simple as that.

Further, as David mentioned, no one else can handle any errors coming out of here better than we can, so you catch everything and return a reasonable default.

Programming is pragmatic not dogmatic. Catching Exception is fine. Catching Error *sometimes* is fine. Exponential cost algorithms are sometimes fine. Not failing fast is sometimes fine. It all depends on the cost/benefit in the area you are programming in.

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5497616&bid=18017719)

File: AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.java [hunk 37]
```diff
@@ -51,25 +52,36 @@ public static Locale getLocale() {
...
+
     /**
      * Returns the {@link Locale} for the given code or the default locale, if no code is given.
      *
      * @param localeCode The locale code of the language
      * @return The {@link Locale} for the given code
      */
     @NonNull
-    public static Locale getLocale(@Nullable String localeCode) {
+    public static Locale getLocale(@Nullable String localeCode, @NonNull SharedPreferences prefs) {
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.java:73]: Codacy Issue found: [Avoid reassigning parameters such as 'localeCode'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5497616)

Comment (Arthus) [reply AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.java:73]: This is not a new issue.

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 38]
```diff
@@ -337,23 +336,82 @@ public static void deleteACRALimiterData(Context context) {
...
+            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
+                return remoteContext.createConfigurationContext(langConfig);
+            } else {
+                //API level < 25:
+                remoteContext.getResources().updateConfiguration(langConfig, remoteContext.getResources().getDisplayMetrics());
+                return remoteContext;
+            }
+        } catch (Exception e) {
+            Timber.e(e, "failed to update context with new language");
+            sendExceptionReport(e,"AnkiDroidApp.updateContextWithLanguage");
```
Comment (Arthus) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:370]: This has currently no effect if the exception is thrown during AnkiDroidApp's attachBaseContext() as ACRA is not initialized/configured until AnkiDroidApp.OnCreate()

File: AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java [hunk 39]
```diff
@@ -842,11 +843,13 @@ private String replaceStringIfNumeric(String str, String value) {
...
     private void initializeLanguageDialog(PreferenceScreen screen) {
         ListPreference languageSelection = (ListPreference) screen.findPreference(LANGUAGE);
+        Locale currentAppLocale = LanguageUtil.getLocale(AnkiDroidApp.getSharedPrefs(AnkiDroidApp.getInstance())
+                .getString(Preferences.LANGUAGE, ""));
         if (languageSelection != null) {
             Map<String, String> items = new TreeMap<>();
             for (String localeCode : LanguageUtil.APP_LANGUAGES) {
                 Locale loc = LanguageUtil.getLocale(localeCode);
-                items.put(loc.getDisplayName(), loc.toString());
+                items.put(loc.getDisplayName(currentAppLocale), loc.toString());
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java:852]: @david-allison-1 separately there is #6252 - seems like we should just put it in here. I understand we're working on sorting that one, I wonder (since the whole area was broken anyway) if we couldn't at least get this functionality in so language switching works at all and then worry about sorting it after? Having this not be in the locale's language means users may become trapped in an accidental but not-decipherable language though, so I'd vote to put loc in here personally

```suggestion
                items.put(loc.getDisplayName(loc), loc.toString());
```

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java (hunk 38 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:370]: Interesting - good point on that one. Well, at least we won't crash :-)

File: AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.java [hunk 40]
```diff
@@ -51,25 +52,36 @@ public static Locale getLocale() {
...
+            localeCode = prefs.getString(Preferences.LANGUAGE, "");
             // If no code provided use the app language.
         }
         if (TextUtils.isEmpty(localeCode)) {
-            locale = Locale.getDefault();
             // Fall back to (system) default only if that fails.
-        } else if (localeCode.length() > 2) {
+            localeCode = Locale.getDefault().toString();
+        }
+        if (localeCode.length() > 2) {
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.java:84]: Oh this is interesting - the 'fil' language code is three letters, and there may be others. Man, locale stuff has really moved along since this area of the code saw some attention.

To be clear, this is not a regression here. It should not be addressed here. But I'll note it in an issue I have going separately #6256

File: AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java (hunk 39 above)
[the remark this answers is not in the document]
Comment (Arthus) [reply AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java:852]: I've already seen that PR and I think I also have a solution for the sorting of the list. It's not as difficult as the post on stackoverflow makes it look. ;)

[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java:852]: @Arthus - do you want to handle that in a follow-on commit right here (quickly, but no pressure you can say no!) or do you want to collaborate on 6252? It's not a regression here, so if you say "no, I will collaborate on 6252" (or anything but 
"yes I'll do it here") then I'll say this is good to go for now, and I'll merge it in

File: AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.java (hunk 40 above)
Comment (Arthus) [reply AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.java:84]: Yeah, there are a lot "interesting" things in Android's locale handling, e.g. the differences in toString() and toLanguageTag().

The change here takes into account that the returned string from Locale.getDefault().toString() can also be more than 2 characters long. toString() returns some Android style language code using underscores _. The constructor of Locale expects ISO 639 style language codes (those actually have 3 characters by default) or "a Language subtag" (whatever this means, could support the result of toString, could not. Not properly documented in the SDK).

File: AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java (hunk 39 above)
Comment (Arthus) [reply AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java:852]: I already answered @david-allison-1 in this regard. I've seen that PR and I think I know a simple solution for the outstanding sorting part of the language list. I just wanted to finish this PR first before taking on more tasks.

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java:852]: Okay great - this is going in then, thanks so much for fixing this, it's a big item for a lot of people

[the remark this answers is not in the document]
Comment (Arthus) [reply AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java:852]: I have just pushed a new commit, fixing the language list, but you were too fast. :D Should I create a new PR? Or do you want to merge/discuss it in #6252 first and merge from there?

[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java:852]: Over on 6252 :-)

**Comment by mikehardy** [comment]
Hello! with the 2.14 release we started accepting donations with the stated goal of accepting money from users (the users' way of saying "Thanks!") to support maintenance and development of AnkiDroid.

We are looking through PRs merged in releases going back to release 2.10 (where we have good record keeping of what's in releases) to let our contributors know.

If you'd like to submit an expense related to your work here, to share in a portion of our hopefully-sustainable monthly disbursement, please read here and do so in the next couple of days:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process

This is our first time handling donations and attempting to compensate anyone with these processes, so please be flexible and patient with us

Thank you for your contribution to AnkiDroid!
