### PR TITLE
fix: crash if exporting deck name containing "'"

### LINKED ISSUE #13717: [Bug] Deck Export fails if name contains apostrophe
Message: i tried to export a deck but an error happen that won't let me do it

```
android.database.sqlite.SQLiteException: error while compiling: "ATTACH '/storage/emulated/0/Android/data/com.ichi2.anki/cache/export/Life's skill-20230421181612.anki2' AS DST_DB": DbError { info: "SqlInputError { error: Error { code: Unknown, extended_code: 1 }, msg: \"near \\\"s\\\": syntax error\", sql: \"ATTACH '/storage/emulated/0/Android/data/com.ichi2.anki/cache/export/Life's skill-20230421181612.anki2' AS DST_DB\", offset: 74 }", kind: Other }
	at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.<init>(StreamingProtobufSQLiteCursor.kt:51)
	at net.ankiweb.rsdroid.database.RustSupportSQLiteDatabase.query(RustSupportSQLiteDatabase.kt:2)
	at net.ankiweb.rsdroid.database.RustSupportSQLiteDatabase.execSQL(RustSupportSQLiteDatabase.kt:2)
	at net.ankiweb.rsdroid.database.RustSupportSQLiteDatabase.execSQL(RustSupportSQLiteDatabase.kt:1)
	at com.ichi2.utils.DatabaseChangeDecorator.execSQL(DatabaseChangeDecorator.kt:1)
	at com.ichi2.libanki.AnkiExporter.exportInto(AnkiPackageExporter.kt:89)
	at com.ichi2.libanki.AnkiPackageExporter.exportFiltered(AnkiPackageExporter.kt:13)
	at com.ichi2.libanki.AnkiPackageExporter.exportInto(AnkiPackageExporter.kt:67)
	at com.ichi2.anki.export.ActivityExportingDelegate$exportApkgOrColpkgLegacy$1$1$1.invoke(ActivityExportingDelegate.kt:5)
	at com.ichi2.anki.export.ActivityExportingDelegate$exportApkgOrColpkgLegacy$1$1$1.invoke(ActivityExportingDelegate.kt:1)
	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:3)
	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:1)
	at com.ichi2.anki.CollectionManager$withQueue$2.invokeSuspend(CollectionManager.kt:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:119)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:15)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:29)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)
Caused by: net.ankiweb.rsdroid.BackendException$BackendDbException: DbError { info: "SqlInputError { error: Error { code: Unknown, extended_code: 1 }, msg: \"near \\\"s\\\": syntax error\", sql: \"ATTACH '/storage/emulated/0/Android/data/com.ichi2.anki/cache/export/Life's skill-20230421181612.anki2' AS DST_DB\", offset: 74 }", kind: Other }
	at net.ankiweb.rsdroid.BackendException$BackendDbException$Companion.fromDbError(BackendException.kt:73)
	at net.ankiweb.rsdroid.BackendException$Companion.fromError(BackendException.kt:160)
	at net.ankiweb.rsdroid.BackendKt.unpackResult(Backend.kt:38)
	at net.ankiweb.rsdroid.BackendKt.access$unpackResult(Backend.kt:1)
	at net.ankiweb.rsdroid.Backend$runMethodRaw$1.invoke(Backend.kt:2)
	at net.ankiweb.rsdroid.Backend$runMethodRaw$1.invoke(Backend.kt:1)
	at net.ankiweb.rsdroid.Backend.withBackend(Backend.kt:13)
	at net.ankiweb.rsdroid.Backend.runMethodRaw(Backend.kt:16)
	at anki.backend.GeneratedBackend.runDbCommandProtoRaw(GeneratedBackend.kt:9)
	at anki.backend.GeneratedBackend.runDbCommandProto(GeneratedBackend.kt:26)
	at net.ankiweb.rsdroid.Backend.fullQueryProto(Backend.kt:20)
	at net.ankiweb.rsdroid.database.Session.fullQueryProto(Session.kt:8)
	at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.<init>(StreamingProtobufSQLiteCursor.kt:21)
	... 20 more
```

* 2.16alpha97
* https://ankidroid.org/acra/app/1/bug/45903/report/031fd479-1af5-4677-8314-67281be1f95c

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
Fixes an error when exporting a deck

## Fixes
Fixes #13717

## Approach
Prepared Statements

## How Has This Been Tested?
Tested on API 30 Emulator. 

* Exported
* Deleted Deck
* Imported
* Card was imported

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.kt [hunk 1]
```diff
@@ -143,7 +143,7 @@ open class AnkiExporter(col: Collection, did: DeckId?, val includeSched: Boolean
         // flexible
         dst.close()
         Timber.d("Attach DB")
-        col.db.database.execSQL("ATTACH '$path' AS DST_DB")
+        col.db.database.execSQL("ATTACH ? AS DST_DB", arrayOf(path))
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.kt:146]: `'?'` didn't work, unexpected. This did.

**Review by mikehardy — APPROVED** [review]
better SQL, yes
