### PR TITLE
Fix #5778 - Scheduling doesn't respect max intervals

### LINKED ISSUE #5778: Mature Cards are being marked as Young+Learn for non-"Again" reviews
###### Reproduction Steps

1. Note of mature count of a deck.
2. Review mature cards, and be sure to review with different responses (Hard/Good/Easy)
3. Go back and observe that mature card count has actually decreased.

[Example Video](https://freya.best.moe/AnkiDroid%20Maturity%20Error.mp4)
In the video above, the deck has artificially limited to a max interval of 22 days (where 21 days or more is considered mature). I responded with hard, good, and easy, and noticed that the mature card count had actually decreased over time. I was able to reproduce this for the entirety of the deck; this video is a demonstration of concept.

###### Expected Result

Mature cards retain their mature status.

###### Actual Result

Mature cards are being switched to "young+learn" status.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

I took this video with this data:
```
AnkiDroid Version = 2.9.3

Android Version = 10

ACRA UUID = 6202ce4c-24e3-4f72-b046-ed3cd465ea8f
```

I also verified it exists on:
```
AnkiDroid Version = 2.9.4

Android Version = 10

ACRA UUID = 6202ce4c-24e3-4f72-b046-ed3cd465ea8f
```
Device: Samsung Galaxy S10E

###### Additional Notes

The incorrect marking only seems to occur from AnkiDroid's client side. I was able to recover the "mature" status again after reviewing on separate devices (Anki on Windows, Macbook, iPhone, and AnkiWeb).

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

### PR DESCRIPTION
**Pull request by Kyrielight**
## Purpose / Description
This PR brings in changes in the function at line 695 of the desktop Anki scheduler that aren't in Anki-Android: https://github.com/ankitects/anki/blob/master/pylib/anki/sched.py#L695

In other words, this is a minor code change to fix a scheduling bug where cards would be given a smaller interval than shown on the review buttons. This could occur because having a low maximum interval changes the new ivl level that is updated in the database (despite a different interval being shown to the user on the "again/hard/okay/easy" buttons during review, because the calculation logic is separate).

## Fixes
Fixes #5778

## Approach
I copied over changes from the desktop Anki repository that updates the card's new Ivl from just being an idealIvl calculation to also checking if the maxIvl sets a different level (else Anki changes the interval at some other point). This is the same URL linked above from the desktop repo.

## How Has This Been Tested?
For a given deck that has mature cards that need to be reviewed, change the deck's maximum interval period to 22 days. Then, review a card (the review buttons should all say 22 days). After review, check the card's new interval to make sure it is 22 days, and not a lower number like 19.

Note: This assumes your interval modifier is at 100%. If it is not, change it to that.

Tested on a Samsung Galaxy S10E, Android 10, latest master as of writing.

## Learning (optional, can help others)
I originally noticed a bug in a previous deck (a writeup of the problem is in https://github.com/ankidroid/Anki-Android/issues/5778). Upon further investigation, I noticed that it was only cards near my deck's maximum interval limit of 22 days that were randomly getting changed to lower intervals (despite all review buttons saying 22 days): 

image
 
Further testing revealed that it wasn't rating dependent - any rating lower, equal, or higher than the previous intervals were still getting corrupted intervals. Because the intervals shown to me on the buttons _were_ the correct intervals, and the desktop clients were all fine, I became suspicious that Anki Android (and also AnkiMobile iOS, incidentally which has the same bug) might have some different calculation logic occurring at interval update (suggesting the intervals are calculated twice).

Checking the desktop logic [here](https://github.com/ankitects/anki/blob/master/pylib/anki/sched.py#L695
) (line 695) and comparing it to the Anki-Android equivalent function (see the diff for this PR) indeed confirmed that the logic for calculating intervals at _update time_ had not been updated; hence this explained why desktop and AnkiWeb clients weren't having issues, while the mobile app was.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

Descriptive commit message: Intend to squash commits and use this PR as title.

### CODE REVIEW

**Comment by mikehardy** [comment]
@Kyrielight excellent! Thank you so much for porting this fix over - it looks straightforward enough, but as a second set of eyes @Arthur-Milchior has been doing a massive amount of libanki porting work recently so I'm curious for his thoughts. In general though I don't see any reason not to merge this after I double-check myself

**Comment by Arthur-Milchior** [comment]
I don't see any problem with the code. Seems to be a correct port. Note that I only read and didn't test

File: AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java [hunk 1]
```diff
@@ -1500,8 +1500,16 @@ private long _daysLate(Card card) {
 
 
     private void _updateRevIvl(Card card, int ease) {
-        int idealIvl = _nextRevIvl(card, ease);
-        card.setIvl(_adjRevIvl(card, idealIvl));
+        try {
+            int idealIvl = _nextRevIvl(card, ease);
+            JSONObject conf = _revConf(card);
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java]: Here's my only question before merge - I understand going into JSON always has the possibility of throwing JSONException, but what is the real risk of _revConf throwing here? Is it every possible for that to happen?

I've been fixing crash bugs a lot, and some are weird corner cases, so I want to make sure. A more defensive structure might be to get idealIvl and adjRevIvl first (outside of try/catch) so we have existing behavior at least as a fallback, then inside the try/catch you could try to fetch the _revConf and do the Math.min to adjust the value, logging if there is a problem but not crashing. What do you think?

Comment (Arthur-Milchior) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java]: _revConf is always the conf of the original deck, not the filtered one.
Original conf are supposed to always have a value maxIvl. It's never deleted in anki code. Of course, bug could occur if an add-on did something bad, or a beta version. But that should not be the case.

**Comment by mikehardy** [comment]
Thanks for the extra insight @Arthur-Milchior - I'm inclined to merge then. I don't mind the PR naming so much. I just re-checked the upstream PR (this does match it perfectly), I checked android API availability of Math.max (no problem) and the analysis seems fine. I'll merge and we'll see

Thanks @Kyrielight for fixing this and Arthur for the help on review

**Comment by mikehardy** [comment]
2.10alpha47 is published with this and will be available when google is done processing it 🚀
