### PR TITLE
Fix note editor deck change

### LINKED ISSUE #17415: [BUG]: Card Browser - Toggle Notes -> Changing deck in Note Editor only modifies one card
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Create 2 decks, Test 1 and Test 2
2. Create a cloze note e.g. {{c1::Hello}} {{c2::World}}! in the Test 1 deck
3. Go to the Card Browser on AnkiDroid, click on the 3 dots, click on Options, and set Toggle Notes
4. Search for Hello World! on the search bar.
5. If you notice, when you click in the arrow and change Sort Field to Question, only one card will appear. 
6. ⚠️ Click on the note/card and change the deck from Test 1 to Test 2.
7. Now, if you go back to the main screen or you go back to the Card Browser and set Toggle Cards again, you’ll see that only one card changed deck.
### Expected behaviour

1. I expected to change all cards of the notes of its original deck at once
2. I expected that the decks name of the cards on the browser desktop would be the name I setted, and not (1) or (2)

### Debug info

```text
AnkiDroid Version = 2.18.4 (f867da96b8304edaebd0361326316bc7514f8cde)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 13 (SDK 33)

ProductFlavor = play

Manufacturer = samsung

Model = SM-A226BR

Hardware = mt6833

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-A226BR Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/130.0.6723.86 Mobile Safari/537.36

ACRA UUID = d549ca88-5110-4f4d-9b75-1f1552dc6095

FSRS Enabled = true

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

Reported here https://forums.ankiweb.net/t/bug-report-notes-arent-in-the-deck-where-they-supposed-to-be/51355/6

In it there is more context

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by KT-1114**
## Purpose / Description
When the user modifies a note's deck from the Note Editor, only the chosen card is transferred to the selected deck. The sibling cards remain in the same deck. This PR fixes this issue so that changing the deck updates all the sibling cards as well.

## Fixes
* Fixes #17415

## Approach
The deck-change logic in `NoteEditorFragment.saveNote()` used to pass a single-item list with just the ID of the active card: `setDeck(listOf(currentEditedCard!!.id), deckId)`. 

I modified this to use `editorNote!!.cardIds(this@undoableOp)` to retrieve card IDs of the sibling cards, then pass the complete list to `setDeck()`, making sure that all sibling cards are moved together.

## How Has This Been Tested?

**1. Automated Regression Test (Robolectric):**
Added `moveNoteToDifferentDeckMovesAllCards` in the Note Editor tests.
- Creates a "Basic (and reversed card)" note in Deck 1.
- Opens the editor in edit mode and selects Deck 2.
- Saves the note and asserts that both `cards[0].did` and `cards[1].did` equal Deck 2's ID.

**2. Manual Testing:**
- Device: Samsung Galaxy A54
- Created a basic and reversed type note.
- Opened the reviewer and selected the edit note option.
- Changed the deck from Test to Test 2.
- Verified in the browser that all associated cards moved to the Test 2 deck.

https://github.com/user-attachments/assets/be270ad3-ab9d-458d-bea0-2dad35dd72b0

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (N/A - Backend logic only)
-[ ] UI Changes: You have tested your change using the Google Accessibility Scanner (N/A)

### CODE REVIEW

**Review by david-allison — CHANGES_REQUESTED** [review]
The note editor is most often opened in 'card' mode, either from the Reviewer or the Card Browser. In this case, only the selected card(s) should be updated.

I don't believe your code handles this case.

**Comment by KT-1114** [comment]
Yes I had this doubt while fixing. I thought of adding a dialogue to inform user how many cards will be affected by this change. But that needed adding strings and crowdin updates so I thought I would ask if I should add that after these changes are approved.

But if the user expects only the selected card to be moved as normal behavior than I think I should I ask user if they want to move all the siblings or just the selected one. Should I move forward with that?

**Comment by david-allison** [comment]
To me: extend the note editor to accept: 

* A note ID
* an optional list of Card IDs, verified to be from the same note 

Then we can handle deck updates correctly

**Comment by KT-1114** [comment]
Got it. To confirm the implementation, here is what I will do -
1. Update the `NoteEditorFragment.kt` to accept a optional `LongArray` of `affectedCardIds`.
2. Update the existing ways to launch the NoteEditor from the `NoteEditorLauncher.kt` by adding the `affectedCardIds`. I will add them based on the context of calling like Note mode or Card mode.

I will be ready to fix any issue on this in future.

**Comment by david-allison** [comment]
Seems sensible, do you still want to take this on?

**Comment by KT-1114** [comment]
Yes. Will it be challenging? From the complexity of Launcher and the whole architecture it seems so. 
I am ready to handle this and I love solving architectural and design challenges.

I can give regular updates and always be in contact for guidance/queries via a dedicated medium.

Should I go on?

**Comment by david-allison** [comment]
Shouldn't be too bad, but don't over-extend yourself

**Comment by KT-1114** [comment]
Hi @david-allison I realized that using a simple flag for note mode would do the work and will be simpler solution.

**Comment by david-allison** [comment]
What happens when the user has 2 cards selected [of the same note]. Both of those should be updated

**Comment by KT-1114** [comment]
https://github.com/user-attachments/assets/0f593ddd-37f9-43eb-868c-59ae3bb83f95
version 2.24.0alpha10

Like this? Or am I misunderstanding?

**Comment by david-allison** [comment]
A user can also edit the deck of that selection via the note editor

**Comment by KT-1114** [comment]
I could not run all the tests as my laptop is unable to handle the load. If this is the expected fix than I will add the test case for it. I have attached the screen recording of test I did.

https://github.com/user-attachments/assets/b3fbdffa-a9fd-4271-bfb9-3fcd3c4f5197

**Comment by david-allison** [comment]
Ahaa! My Legion Go dies due to the thermals of Android Studio.

CI is fine in this case, on your fork or on Anki-Android

I've got a pending series of changes which will make the test load lighter, but it'll take a while to see it through

File: AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/NoteEditorLauncher.kt [hunk 1]
```diff
@@ -167,19 +167,50 @@ sealed interface NoteEditorLauncher : Destination {
...
      * @property cardId The selected card ID, or null when editing a note.
      * @property animation The animation direction.
+     * @property inCardBrowserActivity True if opened within Card Browser Activity.
+     * @property affectedCardIds Optional array of card IDs to apply deck changes to.
      */
     data class EditSelection(
         val cardId: CardId?,
         val animation: ActivityTransitionAnimation.Direction,
         val inCardBrowserActivity: Boolean = false,
+        val affectedCardIds: LongArray? = null,
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/NoteEditorLauncher.kt]: I don't understand the difference between 'cardId' and 'affectedCardIds', can we combine them?

File: AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/NoteEditorLauncher.kt [hunk 2]
```diff
@@ -167,19 +167,50 @@ sealed interface NoteEditorLauncher : Destination {
...
+            return true
+        }
+
+        override fun hashCode(): Int {
+            var result = cardId?.hashCode() ?: 0
+            result = 31 * result + animation.hashCode()
+            result = 31 * result + inCardBrowserActivity.hashCode()
+            result = 31 * result + (affectedCardIds?.contentHashCode() ?: 0)
+            return result
+        }
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/NoteEditorLauncher.kt]: I don't think this is necessary, does the `data class` fail to handle equality?

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt [hunk 3]
```diff
@@ -301,6 +301,9 @@ class NoteEditorFragment :
     private val noteEditorActivity
         get() = requireAnkiActivity() as? NoteEditorActivity
 
+    // List of affected cards (siblings) when editing notes.
+    private var affectedCardIds: LongArray? = null
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt]:
```suggestion
    private val affectedCardIds: LongArray?
        get() = arguments?.getLongArray(EXTRA_AFFECTED_CARD_IDS)
```

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt [hunk 4]
```diff
@@ -1374,15 +1378,29 @@ class NoteEditorFragment :
             // changed did? this has to be done first as remFromDyn() involves a direct write to the database
             if (currentEditedCard != null && currentEditedCard!!.currentDeckId() != deckId) {
                 reloadRequired = true
-                undoableOp { setDeck(listOf(currentEditedCard!!.id), deckId) }
+
+                // Determine which cards to move based on the provided affectedCardIds,
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt]: This needs a test

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt [hunk 5]
```diff
@@ -1374,15 +1378,29 @@ class NoteEditorFragment :
...
+                // falling back to just the current card if none were passed.
+                val cardIdsToMove =
+                    if (affectedCardIds?.isNotEmpty() == true) {
+                        affectedCardIds!!.toList()
+                    } else {
+                        listOf(currentEditedCard!!.id)
+                    }
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt]: consider extracting this to a method

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt [hunk 6]
```diff
@@ -133,11 +133,31 @@ open class CardBrowser :
...
+                            .cards(col)
+                            .map { it.id }
+                            .toLongArray()
+                    } else {
+                        null // Fallback to single card edit default.
+                    }
+                } catch (e: Exception) {
+                    Timber.w(e, "Error fetching affected card IDs")
+                    null
+                }
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt]: * This should be in the ViewModel
* This should handle mulitselect in CARDS mode as well
  * Add a TODO here
* This should be unit tested. I want to push for coverage on the CardBrowserViewModel 
* Don't worry about try... catch. Use `launchCatchingTask` in the UI if necessary

**Review by david-allison — CHANGES_REQUESTED** [review]
Cheers!

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt (hunk 4 above)
Comment (KT-1114) [reply AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt]: Okay.

File: AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/NoteEditorLauncher.kt (hunk 2 above)
Comment (KT-1114) [reply AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/NoteEditorLauncher.kt]: I was testing out a few things so had to write a custom one. As of now it is redundant and the case were we need this is not reachable as the card browser will never launch the editor in that way. 

On removing this Android Studio shows warning 
`Property with 'Array' type in a 'data' class: it is recommended to override 'equals()' and 'hashCode()' `

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt (hunk 6 above)
Comment (KT-1114) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt]: Okay will move it.
Will add TODO.

There is one thing I still don't understand. Can a user select multiple cards and edit them? I don't see any option to edit note in multi select mode.

Okay.

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt]: Not currently, but we shouldn't block this

**Comment by KT-1114** [comment]
Extremely sorry for the delay that too for small changes. 
Regarding cardId vs affectedCardIds:

- I think the `cardId` is primarily used to load the note data.
- `affectedCardIds` is used to determine which cards are to be moved.

File: AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt [hunk 7]
```diff
@@ -304,6 +302,23 @@ class CardBrowserViewModel(
 
     suspend fun queryAllSelectedNoteIds() = selectedRows.queryNoteIds(this.cardsOrNotes)
 
+    // Get ids of affected cards (siblings). Used when in Note mode.
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt]: Improve the comment, and have it use `/** ... */`

File: AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt [hunk 8]
```diff
@@ -304,6 +302,23 @@ class CardBrowserViewModel(
...
+    suspend fun getAffectedCardIds(): List<CardId>? {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt]: I don't understand the functionality from the description and/or the method name, affected by what?

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt [hunk 9]
```diff
@@ -127,20 +127,15 @@ open class CardBrowser :
...
-                    cardId,
-                    Direction.DEFAULT,
-                    fragmented,
-                ).also {
-                    Timber.i("editNoteLauncher: %s", it)
-                }
+                    cardId = cardId,
+                    animation = Direction.DEFAULT,
+                    inCardBrowserActivity = fragmented,
+                    affectedCardIds = null, // TODO: You will need to fetch this from ViewModel
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt]: Was this AI generated?

**Review by david-allison — CHANGES_REQUESTED** [review]
Some feedback from my last review wasn't addressed, I'm drafting this so it's out the notification queue. Please un-draft it when feedback is addressed

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt (hunk 9 above)
Comment (KT-1114) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt]: The TODO was re-written using AI.

**Comment by KT-1114** [comment]
Note: In this fix if the deck is same as the first note of card at the time of saving no card's deck will be updated. If cards are in different decks and user wants to move them to same deck as the 1st card the user needs to move all the cards to some other deck and then change again.

File: AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/NoteEditorLauncher.kt [hunk 10]
```diff
@@ -165,18 +165,22 @@ sealed interface NoteEditorLauncher : Destination {
...
     /**
      * Opens the NoteEditor for the current selection (card or note).
-     * @property cardId The selected card ID, or null when editing a note.
+     * @property cardIds The selected card ID when editing a card, or the IDs of cards of the same note when editing a note.
      * @property animation The animation direction.
+     * @property inCardBrowserActivity True if opened within Card Browser Activity.
      */
     data class EditSelection(
-        val cardId: CardId?,
+        val cardIds: List<CardId>,
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/NoteEditorLauncher.kt:173]: Looks unusual, but fine.

You've changed a nullable `CardId` to a list of `CardId`, but you call `.first()`, which means an empty list crashes

It looks like `cardId` was never null, so this works

File: AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt [hunk 11]
```diff
@@ -663,6 +663,74 @@ class NoteEditorTest : RobolectricTest() {
...
+
+    @Test
+    fun `changing deck with single card id moves only that card`() =
+        runTest {
+            // Create a note with 2 cards (Basic and Reversed)
+            val noteType = col.notetypes.basicAndReversed
+            val note = Note.fromNotetypeId(col, noteType.id)
+            note.setField(0, "Front")
+            note.setField(1, "Back")
+            col.addNote(note, Consts.DEFAULT_DECK_ID)
```
Comment (david-allison) [inline AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt]:
```suggestion
            val note = addBasicAndReversedNote()
```

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt [hunk 12]
```diff
@@ -123,25 +123,18 @@ open class CardBrowser :
...
-                .EditSelection(
-                    cardId,
-                    Direction.DEFAULT,
-                    fragmented,
-                ).also {
-                    Timber.i("editNoteLauncher: %s", it)
-                }
-        }
+    private suspend fun editNoteLauncher(): NoteEditorLauncher? {
+        val cardIds = viewModel.getCardIdsForNoteEditor()
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt:129]: The method may return an empty list, and passing this to `EditSelection` will crash

**Review by david-allison — CHANGES_REQUESTED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt (hunk 12 above)
Comment (KT-1114) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt:129]: I think returning null will not cause any problem.
```suggestion
        val cardIds = viewModel.getCardIdsForNoteEditor()
        
        if (cardIds.isEmpty()) {
            Timber.w("EditSelection skipped: card list is empty")
            return null
        }
```

File: AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt (hunk 11 above)
Comment (KT-1114) [reply AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt]: Will update  both tests.

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt (hunk 12 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt:129]: Implementer's choice! You also have the ability to return null, if you move the validation into`EditSelection`

File: AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/NoteEditorLauncher.kt [hunk 13]
```diff
@@ -165,18 +165,22 @@ sealed interface NoteEditorLauncher : Destination {
 
     /**
      * Opens the NoteEditor for the current selection (card or note).
-     * @property cardId The selected card ID, or null when editing a note.
+     * @property cardIds The selected card ID when editing a card, or the IDs of cards of the same note when editing a note.
      * @property animation The animation direction.
+     * @property inCardBrowserActivity True if opened within Card Browser Activity.
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/NoteEditorLauncher.kt:170]: Note that this throws if `cardIds` is empty

**Review by david-allison — APPROVED** [review]
Cheers!

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt (hunk 12 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt:129]: seems it's fine as-is with the empty list check below, merge-able, going to merge

**Review by mikehardy — APPROVED** [review]
Nice work here - thank you!
