### PR TITLE
Bug fix - Gesture navigation overriding Slider

### LINKED ISSUE #20397: Previewer: Gesture navigation overrides interacting with the Slider
https://github.com/ankidroid/Anki-Android/blob/2c29b476fd2afc7597be47e5256b18abbdc077c5/AnkiDroid/src/main/res/layout/previewer.xml#L53-L66

<center>
Image
</center>

When the slider is in active use, gesture navigation from the edges over the slider control should be disabled, otherwise this makes it difficult to begin using the slider.

### PR DESCRIPTION
**Pull request by lonewolf2208**
## Purpose / Description
 Dragging the Previewer slider from the screen edges can trigger Android’s back gesture instead of moving the slide .

## Fixes
* Fixes #20397

## Approach
I initially tried [requestDisallowInterceptTouchEvent()](https://developer.android.com/reference/android/view/ViewGroup#requestDisallowInterceptTouchEvent(boolean))  while dragging the slider, but that did not fully solve the issue because the system back gesture could still win before the slider started  tracking the touch.

The final fix uses `ViewCompat.setSystemGestureExclusionRects()` on the slider bounds, and refreshes that rect after layout changes. That prevents edge back gestures from taking over when the user starts dragging from either end of the slider.

## How Has This Been Tested?

Tested the changes manually -

| After | Before |
|--------|--------|
| <video src="https://github.com/user-attachments/assets/75b71b7e-f775-489e-85fc-7bffa7a4004f"> | <video src="https://github.com/user-attachments/assets/4a6bc42f-32fa-41f2-b3e8-84d8eba5d5bd"> |

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt [hunk 1]
```diff
@@ -133,9 +136,15 @@ class PreviewerFragment :
 
         binding.slider.apply {
             valueTo = cardsCount.toFloat()
+            doOnLayout {
```
Comment (lonewolf2208) [inline AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt:139]: Set the gesture exclusion area once the slider has its final size

File: AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt [hunk 2]
```diff
@@ -133,9 +136,15 @@ class PreviewerFragment :
...
+                updateSliderGestureExclusion(this)
+            }
+            addOnLayoutChangeListener { _, _, _, _, _, _, _, _, _ ->
```
Comment (lonewolf2208) [inline AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt:142]: Update the exclusion area again if the slider layout changes later

**Review by david-allison — APPROVED** [review]
This is excellent, thank you!!!

----

I was concerned that this would block gestures while the indicator was away from the edges.

**vertical phone** ✅ 
If the indicator is not touching an edge, no matter how close to the edge a user taps, the toggle moves to the extremity, so navigation gestures should not occur 

**horizontal phone** ✅
Swiping on the notch performs a navigation gesture

File: AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt (hunk 1 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt:139]: Prefer code comments, rather than GitHub comments

If it's useful for reviewers, it'll be useful for future maintainers in the codebase

**Review by BrayanDSO — APPROVED** [review]

**Comment by BrayanDSO** [comment]
Looks great. Thanks
