### PR TITLE
Preventing OR search query from bypassing RestrictOnDeck

### LINKED ISSUE #8027: [Bug] Using "OR" in search when filtered to one deck gives unexpected results
###### Reproduction Steps

1. Go to the Card browser
2. Select a deck from the drop down (example: `deck:Default`)
3. Press search, and enter a search containing the "or" operand (example: `card:1 OR card:2`)

###### Expected Result

All search results are from the chosen deck, including results matching either case.
Example: Functioning like a search on desktop Anki of `deck:Default (card:1 OR card:2)`

###### Actual Result

Results from the left-hand side of the OR are from the selected deck, but the right-hand side is searching **all** decks.
Example: Functioning like a search on desktop Anki of `deck:Default card:1 OR card:2`

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by ritvij14**
## Purpose / Description
Till now if we opened the CardBrowser and tried searching cards using OR, we see that the results from the left-hand side of the OR are from the selected deck, but the right-hand side is searching all decks.

## Fixes
Fixes #8027 
## Approach
This adds `()` in the search string by default. This way the query is always enclosed in brackets and RestrictOnDeck is not bypassed.

## How Has This Been Tested?

Tested it on my Redmi Note 8 pro

image

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by ritvij14** [comment]
In the test case, I selected Deck 1, and the search, without brackets, would return 2 cards instead of 1.

Part of output on running the test-
```
V/Finder: Search query 'deck:"Deck 1" (world or hello)' is compiled as 'select c.id from cards c, notes n where c.nid=n.id and ((c.did in (1596783600460) or c.odid in (1596783600460)) and (((n.sfld like ? escape '\' or n.flds like ? escape '\')) or ((n.sfld like ? escape '\' or n.flds like ? escape '\'))))  ORDER BY n.sfld COLLATE NOCASE, c.ord'.
D/BackendV1Impl: Rust: fullQueryProto select c.id from cards c, notes n where c.nid=n.id and ((c.did in (1596783600460) or c.odid in (1596783600460)) and (((n.sfld like ? escape '\' or n.flds like ? escape '\')) or ((n.sfld like ? escape '\' or n.flds like ? escape '\'))))  ORDER BY n.sfld COLLATE NOCASE, c.ord
D/BackendV1Impl: cancelCurrentProtoQuery
D/CollectionTask$SearchCards: The search found 1 cards
```

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java [hunk 1]
```diff
@@ -1500,9 +1500,18 @@ private void searchCards() {
             mSearchItem.expandActionView();
         }
         if (mSearchTerms.contains("deck:")) {
-            searchText = mSearchTerms;
+            int position;
+            if (mSearchTerms.charAt(5) == '\"') {
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java:1504]: I doubt it work. If you search "FOO deck:Bar" then the first character is not at position 5.

the othe problem (which is not due), is that if you search for `"a card containing deck: literally"` then it'll detect this as a deck: query while it is actually a literal search. Probably worth making an issue of it

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java [hunk 2]
```diff
@@ -1500,9 +1500,18 @@ private void searchCards() {
             mSearchItem.expandActionView();
         }
         if (mSearchTerms.contains("deck:")) {
-            searchText = mSearchTerms;
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java:1503]: please copy the search term. If the `mSearchTerm` change while the function run, that would potentially create bug

File: AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java [hunk 3]
```diff
@@ -509,6 +509,23 @@ public void rescheduleUndoTest() {
         assertUndoContains(b, R.string.deck_conf_cram_reschedule);
     }
 
+    @Test
+    public void checkSearchString() {
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java:513]: So this test was failing before? It would be nice to put a small comment with the bug report number

**Review by Arthur-Milchior — COMMENTED** [review]
I believe you don't need such a complex logic. You can always add parenthesis, even if you don't add "deck:" in the search it will still works

File: AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java (hunk 3 above)
Comment (ritvij14) [reply AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java:513]: No, it wasn't failing before. I had to update the string because I have selected "Deck 1" before starting my search, so if I had kept hello before OR, it would pass anyway, as the query for a particular deck works fine for the left of the OR but not the right, so I changed the string.

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java (hunk 2 above)
Comment (ritvij14) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java:1503]: Ok got it

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java (hunk 1 above)
Comment (ritvij14) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java:1504]: Ok understood. So for now I should just remove this part of logic and simply add parenthesis all around the string even if it has deck right?

Comment (ritvij14) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java:1504]: Ok understood. So for now I should just remove this part of logic and simply add parenthesis all around the string even if it has "deck:" right?

Comment (Arthur-Milchior) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java:1504]: I believe it would make sens.

File: AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java (hunk 3 above)
Comment (Arthur-Milchior) [reply AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java:513]: Sorry, I was not clear. 

I meant, if you write this test on top of master and nothing else, does the test succeed.

What we want and need is a test that fails without your changes and succeed with

Comment (ritvij14) [reply AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java:513]: Oh ok, I got it. Yes, the test is failing if we just use the master code. In that case, 2 cards are being returned.

And ok I will add the issue number on top of the test case in a comment.

File: AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java [hunk 4]
```diff
@@ -509,6 +509,24 @@ public void rescheduleUndoTest() {
         assertUndoContains(b, R.string.deck_conf_cram_reschedule);
     }
 
+    /** 8027 */
+    @Test
+    public void checkSearchString() {
+        Card c1 = addNoteUsingBasicModel("Hello", "John").firstCard();
+        c1.flush();
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java:516]: I don't think you need this line

File: AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java [hunk 5]
```diff
@@ -509,6 +509,24 @@ public void rescheduleUndoTest() {
...
+        long deck = addDeck("Deck 1");
+        getCol().getDecks().select(deck);
+        Card c2 = addNoteUsingBasicModel("New", "world").firstCard();
+        c2.setDid(deck);
+        c2.flush();
+
+        CardBrowser cardBrowser = getBrowserWithNoNewCards();
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java:523]: Could you assert that the card browser has a selected deck here

File: AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java [hunk 6]
```diff
@@ -509,6 +509,24 @@ public void rescheduleUndoTest() {
...
+        cardBrowser.searchCards("world or hello");
+        advanceRobolectricLooperWithSleep();
+
+        assertThat("tagged card should be returned", cardBrowser.getCardCount(), is(1));
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java:527]:
```suggestion
        assertThat("Results should only be from the selected deck", cardBrowser.getCardCount(), is(1));
```
```suggestion
        assertThat("tagged card should be returned", cardBrowser.getCardCount(), is(1));
```

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
Looks good to me, a few slight nitpicks on tests

**Comment by ritvij14** [comment]
Changes done.

File: AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java [hunk 7]
```diff
@@ -509,6 +509,24 @@ public void rescheduleUndoTest() {
         assertUndoContains(b, R.string.deck_conf_cram_reschedule);
     }
 
+    /** 8027 */
+    @Test
+    public void checkSearchString() {
+        Card c1 = addNoteUsingBasicModel("Hello", "John").firstCard();
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java:515]:
```suggestion
       addNoteUsingBasicModel("Hello", "John");
```

**Review by david-allison-1 — APPROVED** [review]
One nitpick, but looks good to me!

**Comment by david-allison-1** [comment]
Note to maintainers: squash merge

**Review by mikehardy — APPROVED** [review]
Nice! With added test support even +1

**Comment by mikehardy** [comment]
Hi there!

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for April 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged in April)

Thanks!
