### PR TITLE
fix: "Invalid input: card was modified"

### LINKED ISSUE #12946: [Bug] V3 Scheduler: "Invalid input: card was modified" while answering card
###### Reproduction Steps
1. Start reviewing cards.
2. Click the show answer button.
3. Rate the card as good.

###### Expected Result
The next card is shown.

###### Actual Result
Sometimes, the following error is shown instead.

IMG_20221210_085645

Note that this error occurs very rarely, maybe about once a week.

###### Debug info
AnkiDroid Version = 2.16alpha91

Android Version = 7.0

Manufacturer = motorola

Model = Moto C Plus

Hardware = mt6735

Webview User Agent = Mozilla/5.0 (Linux; Android 7.0; Moto C Plus Build/NRD90M.03.045; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/107.0.5304.141 Mobile Safari/537.36

ACRA UUID = c6a580cb-02cc-4970-b7a5-24615e6542e1

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
Cause: answering the card too quickly, which caused two executions of `answerCard()`

## Fixes
* Fixes #12946

## Approach
Define and use `preventSimultaneousExecutions`

## How Has This Been Tested?
* calling `answerCard(EASE_4)` twice and ensuring no error
* throwing an exception inside the method and ensuring it's unlocked
   * technically not perfect due to `launchCatchingTask`
* adding a log statement afterwards and ensuring the call is not blocking
* Unit tests

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/test/java/com/ichi2/anki/utils/OnlyOnceTest.kt [hunk 1]
```diff
@@ -0,0 +1,91 @@
...
+
+    private fun preventMultipleExecutions(function: () -> Unit) {
+        preventSimultaneousExecutions(UNIT_TEST) {
+            testScope.launch() {
+                function()
+            }
+        }
+    }
+
+    private suspend fun preventMultipleExecutionsBlocking(function: () -> Unit) = suspendCoroutine {
```
Comment (lukstbit) [inline AnkiDroid/src/test/java/com/ichi2/anki/utils/OnlyOnceTest.kt:80]: I'm not fond of the custom CoroutineScope plus the usage of AnkiDroidApp.applicationScope(which I'm assuming you used because runTest was failing due to the exception being thrown). You could combine the two methods into one and use the scope from runTest:

```
// catch the exception here otherwise the test scope will catch it and throw it, safe as we expect the exception
context(CoroutineScope)
    private fun preventMultipleExecutions(shouldCatchException: Boolean = false, function: () -> Unit) {
        preventSimultaneousExecutions(UNIT_TEST) {
            launch {
                if (shouldCatchException) {
                    runCatching { function() }
                } else {
                    function()
                }
            }
        }
    }
```

We have control over the coroutine execution inside runTest with _advanceUntilIdle()_. For example for the first test:

```
@Test
    fun `single run works`() = runTest {
        var i = 0
        preventMultipleExecutions { i++ }
        advanceUntilIdle() // the test scheduler should run any coroutine started until now so the assertion sees the correct state
        assertThat(i, equalTo(1))
    }
```

**Review by lukstbit — APPROVED** [review]
I didn't manage to reproduce the issue but I think it's worth trying this fix. 
I'm fine with the code, even with the tests(I think they could be improved so I left a(non blocking) comment below to consider).

File: AnkiDroid/src/test/java/com/ichi2/anki/utils/OnlyOnceTest.kt (hunk 1 above)
Comment (david-allison) [reply AnkiDroid/src/test/java/com/ichi2/anki/utils/OnlyOnceTest.kt:80]: Context: I started with `AnkiDroidApp.applicationScope.launch`, then didn't want the `Main.immediate` which caused execution until completion on the parallel execution test

I'll change approaches, I wasn't a fan of the `.sleep()`

**Review by mikehardy — APPROVED** [review]
should do the trick
