### PR TITLE
Fix "Access denied" errors after upgrading from 2.15.6

### LINKED ISSUE #13598: [BUG]: move to scoped storage - access denied
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. have AnkiDroid 2.15.6 with a note including a media file
2. Sync
3. Delete the note (do not sync)
4. Update to 2.16.alpha97 play build
5. Move storage

### Expected behaviour

Storage is moved

### Actual behaviour

Error, access denied
Screenshot_20230412_215921_AnkiDroid

### Debug info

```text
AnkiDroid Version = 2.16alpha97

Android Version = 13

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-A225F Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/111.0.5563.116 Mobile Safari/537.36

ACRA UUID = 0f75984c-f461-4a77-8831-85940f55f223

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by BrayanDSO**
selectAnkiDroidFolder() didn't handle the case of the user keeping the legacy storage permissions on an Android 11+ device

## Fixes
Fixes #13598 

## Approach
Check if the user has the legacy storage permissions on selectAnkiDroidFolder(). I'd refactor the method a little bit more, but got some problems fixing the tests if I refactored, perhaps because of a problem between mockkito and JUnit, and didn't think that it was worth the time

## How Has This Been Tested?

On a SDK 33 emulator
1. Build and install Ankidroid 2.15.6 (ensure that its applicationId is com.ichi2.anki.debug if you are using a debug version, or use com.ichi2.anki as your applicationId on the 3rd step)
2. Open the app and give the storage permission
3. Build and install this PR (`play` flavor)
4. Tested if the access denied errors persist:
    - Start a migration
    - Add a image or drawing on the note editor

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by BrayanDSO** [comment]
Haven't tested, but I'm reasonably sure that the problem of opening the app first time after an upgrade by a shortcut will persist, as permissions are only requested on InitialActivity/DeckPicker. Related to #13518

As fixing it isn't the goal of this PR, and won't be a common case, I think that this can be merged

**Comment by lukstbit** [comment]
@BrayanDSO With these changes there's a recursion happening in CollectionHelper.getCurrentAnkiDroidDirectory()(the else clause calls getCurrentAnkiDroidDirectory).

File: AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt [hunk 1]
```diff
@@ -281,7 +282,8 @@ class StartupStoragePermissionManager private constructor(
 
         fun selectAnkiDroidFolder(context: Context): AnkiDroidFolder {
             return selectAnkiDroidFolder(
-                canManageExternalStorage = Permissions.canManageExternalStorage(context)
+                canManageExternalStorage = Permissions.canManageExternalStorage(context),
+                hasLegacyStoragePermissions = isLegacyStorage(context, false) == true
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.kt:286]: nit: use a named arg

**Review by david-allison — APPROVED** [review]
