### PR TITLE
Fix "AnkiDroid directory is inaccessible" Bug

### LINKED ISSUE #5097: AnkiDroid Directory not able to be accessed
###### Reproduction Steps

1. Open AnkiDroid
2. Open advanced settings
3. Close advanced settings
4. That's it

When reinstalled it works perfectly fine and as soon as advance settings are opened it won't get access to the directory. 
I have tried moving the data around and adjusting the file path but it won't let me change it. 
If i try leaving the settings it either does nothing or closed the app. 

That's the video of what is happening: 
https://drive.google.com/file/d/1i_kQQniYP3Zn-TD-EhT6RS7cd6E1okMf/view?usp=drivesdk

###### Expected Result
Sorry i clearly don't know how this work just open the issues as asked. Hope i can help
Ask me for further details

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

### LINKED ISSUE #5510: [2.9 ACRA] crash creating CardBrowser options menu
Somehow the Collection can be null while creating the Card Browser options menu?

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/72712c17-04a8-4011-911f-9bef4dff37a6

```
java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONObject com.ichi2.libanki.Collection.getConf()' on a null object reference
at com.ichi2.anki.CardBrowser.onCreateOptionsMenu(CardBrowser.java:9)
at android.app.Activity.onCreatePanelMenu(Activity.java:3568)
at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:1)
at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:1)
at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2)
at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:1)
at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:5)
at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:1)
```

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description

This bug has been pervasive for some time, and I logically believe that this change fixes it, although I haven't verified this empirically.

A user accessing "Advanced Settings" would obtain an error: `directory_inaccessible`

This was caused by entering the settings, which set a hardcoded default value `sdcard/AnkiDroid` without validation which did not match `getDefaultAnkiDroidDirectory()`

This immediately kicks the user out the app and leaves them in a crash loop. They don't know what the actual value is meant to be (as they never saw the UI, so they can't easily fix it)

## Fixes
Fixes #5097 
Fixes #5510

Partially Addresses #5346 (option can still be set if somehow preferences is the first entered screen, but I think that's logically impossible)

## Approach
We fix this by setting the preference when we try to access `deckPath` and the value is unset.

## How Has This Been Tested?

Not Tested 🛑 

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

File: AnkiDroid/src/test/java/com/ichi2/preferences/PreferenceExtensionsTest.java [hunk 1]
```diff
@@ -0,0 +1,86 @@
...
+    @Test
+    public void missingKeySetsPreference() {
+        getForMissingKey();
+        Mockito.verify(mockEditor).putString(MISSING_KEY, LAMBDA_RETURN);
+        Mockito.verify(mockEditor).apply();
+    }
+
+    @SuppressWarnings("unused")
+    @Test
+    public void noExceptionIfKeyExists() {
```
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/preferences/PreferenceExtensionsTest.java]: Codacy Issue found: [JUnit tests should include assert() or fail()](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5198455)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/preferences/PreferenceExtensionsTest.java  2
- AnkiDroid/src/main/java/com/ichi2/preferences/PreferenceExtensions.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5198455&bid=17049179)

File: AnkiDroid/src/main/java/com/ichi2/preferences/PreferenceExtensions.java [hunk 2]
```diff
@@ -0,0 +1,32 @@
+package com.ichi2.preferences;
+
+import android.content.SharedPreferences;
+
+import androidx.annotation.CheckResult;
+import androidx.annotation.NonNull;
+
+/** Extension methods over the SharedPreferences class */
+public class PreferenceExtensions {
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/preferences/PreferenceExtensions.java]: Codacy Issue found: [The utility class name 'PreferenceExtensions' doesn't match '[A-Z][a-zA-Z0-9]+(Utils?|Helper)'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5198455)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/preferences/PreferenceExtensionsTest.java  2
- AnkiDroid/src/main/java/com/ichi2/preferences/PreferenceExtensions.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5198455&bid=17049179)

File: AnkiDroid/src/main/java/com/ichi2/preferences/PreferenceExtensions.java (hunk 2 above)
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/preferences/PreferenceExtensions.java]: Codacy Issue found: [The utility class name 'PreferenceExtensions' doesn't match '[A-Z][a-zA-Z0-9]+(Utils?|Helper)'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5198455)

File: AnkiDroid/src/test/java/com/ichi2/preferences/PreferenceExtensionsTest.java [hunk 3]
```diff
@@ -0,0 +1,86 @@
...
+    @Test
+    public void missingKeySetsPreference() {
+        getForMissingKey();
+        Mockito.verify(mockEditor).putString(MISSING_KEY, LAMBDA_RETURN);
+        Mockito.verify(mockEditor).apply();
+    }
+
+    @SuppressWarnings("unused")
+    @Test
+    public void noLambdaExceptionIfKeyExists() {
```
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/preferences/PreferenceExtensionsTest.java]: Codacy Issue found: [JUnit tests should include assert() or fail()](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5198455)

Comment (david-allison-1) [reply AnkiDroid/src/test/java/com/ichi2/preferences/PreferenceExtensionsTest.java]: What's the best way to deal with this? I can't see an `assert.pass()`

File: AnkiDroid/src/main/java/com/ichi2/preferences/PreferenceExtensions.java (hunk 2 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/preferences/PreferenceExtensions.java]: Any suggestions? Also, is this class in the correct place?

File: AnkiDroid/src/test/java/com/ichi2/preferences/PreferenceExtensionsTest.java [hunk 4]
```diff
@@ -0,0 +1,86 @@
...
+    private SharedPreferences.Editor mockEditor;
+
+    private String getOrSetString(String key, PreferenceExtensions.Supplier<String> supplier) {
+        return PreferenceExtensions.getOrSetString(mMockReferences, key, supplier);
+    }
+
+    @Before
+    public void setUp() {
+        Mockito.when(mMockReferences.contains(VALID_KEY)).thenReturn(true);
+        Mockito.when(mMockReferences.getString(VALID_KEY, "")).thenReturn(VALID_RESULT);
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/preferences/PreferenceExtensionsTest.java]: replace "" with `anyString()`

File: AnkiDroid/src/main/java/com/ichi2/preferences/PreferenceExtensions.java (hunk 2 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/preferences/PreferenceExtensions.java]: Interesting - some of these rules are old, but if not too onerous easier to just go with it - I think it's saying you need to call it PreferenceExtensionsUtils or PreferenceExtensionsHelper

I don't have a strong opinion here though, it may be ignored - I couldn't find it in here anywhere https://github.com/ankidroid/Anki-Android/tree/master/docs/code_conventions so I should go alter codacy really so this doesn't flag

File: AnkiDroid/src/test/java/com/ichi2/preferences/PreferenceExtensionsTest.java (hunk 3 above)
Comment (mikehardy) [reply AnkiDroid/src/test/java/com/ichi2/preferences/PreferenceExtensionsTest.java]: you could put it in a try catch and in the catch fail?

File: AnkiDroid/src/main/java/com/ichi2/preferences/PreferenceExtensions.java (hunk 2 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/preferences/PreferenceExtensions.java]: I'd rather not have `Extensions` and an additional suffix. `Utils` and `Helper` are a superset of `Extensions`. `SharedPreferenceUtils`/`SharedPreferenceHelper` would fit the bill, I don't really mind, just don't know Java conventions

**Comment by mikehardy** [comment]
I'm pretty busy today but this is obviously exciting. I'll review it as soon as I get a chance. You're systematically eradicating a pile of bugs that have been troubling users for so long - thank you.

**Comment by david-allison-1** [comment]
@mikehardy No worries at all. I'm very used to waiting for PRs. I'm aware that I'm overloading you right now, so don't feel any pressure to get to them in what you'd normally consider to be a timely manner (and prioritise others as well).

If it gets to be a real problem, all I'd ask for is a "Awaiting Reviewee" label (or similar) so I know where my action items are.

File: AnkiDroid/src/test/java/com/ichi2/preferences/PreferenceExtensionsTest.java (hunk 3 above)
Comment (david-allison-1) [reply AnkiDroid/src/test/java/com/ichi2/preferences/PreferenceExtensionsTest.java]: Better to add in a helper class

File: AnkiDroid/src/main/java/com/ichi2/preferences/PreferenceExtensions.java (hunk 2 above)
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/preferences/PreferenceExtensions.java]: Since the auto-review removed the discussion (and didn't flag it a second time).

I don't like the `Extensions[Helper/Util]` suffix as `Extensions` is a subset of both. Happy to go with `[Shared]Preference[Utils/Extensions]`. Don't know the esosystem well enough to have a preference.

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/preferences/PreferenceExtensions.java]: I couldn't find any rule for the naming convention anyway, and don't consider it important, if it did not re-flag that actually matches my failure to locate why it flagged in the first place. resolved -> works for me

**Comment by mikehardy** [comment]
I want to get this in the 2.9.x series but it's obviously pretty fundamental to the app, so this will marinate in alpha and then a beta for a little bit and we'll need to keep our eyes peeled. Hopefully there's no unexpected side effects and it just crushes the bug :crossed_fingers: - thanks for the fix + test!

File: AnkiDroid/src/main/java/com/ichi2/preferences/PreferenceExtensions.java [hunk 5]
```diff
@@ -0,0 +1,32 @@
...
+            //the default Is never returned. The value might be able be optimised, but the Android API should be better.
+            return target.getString(key, "");
+        }
+        String supplied = supplier.get();
+        target.edit().putString(key, supplied).apply();
+        return supplied;
+    }
+
+    /** TODO: Move this to Supplier in API 24 */
+    @FunctionalInterface
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/preferences/PreferenceExtensions.java]: 🐞 `@FunctionalInterface` is apparently only available in API 24. I don't quite understand this, so I'm not sure if it's a bug, but flagging for testing.

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/preferences/PreferenceExtensions.java]: Hmm - I'm sure we'll get reports about that then - for the alphas I kick things out pretty quickly but for the betas and stable I locally test as well just in case, on API16 (lowest that can sync) and API-current. Best bet is for you to use Android Studio's AVD manager and make an API16 emulator to check, and keep it handy

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/preferences/PreferenceExtensions.java]: Android Studio 4 has more desugaring support (which brings Java 8 features to the old JVMs on old Android APIs) https://developer.android.com/studio/preview/features/#j8-desugar but you'd have to check to see if that worked. Best not to move toolchains on a stable branch either so that's not something I really want to contemplate in order to pick this to 2.9
