### PR TITLE
fix[Audio Insert]: Make audio files selectable

### LINKED ISSUE #9321: [Bug] Audio files cannot be added
###### Reproduction Steps

1. Add Note
2. Add Audio Clip
3. Click on LIBRARY
4. Select a music file

###### Expected Result
Any music file can be selected. 

###### Actual Result
(API Level 26): Music files except for .ogg files (for eg: .mp3 file) are greyed out & cannot be selected
(API Level 30): All files are greyed out including .ogg & .mp3 files

API 26 - Samsung Galaxy S7 (Physical Device):
The 3 .ogg files are selectable, but the .mp3 file isn't
api26_greyed_out

API 30 - Pixel 4 XL (Emulator):
greyed_out

One of these files is a .ogg file, the other is a .mp3 file

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by farjadilyas**
## Purpose / Description
Audio files were not selectable from the System File Picker while adding an audio clip to a Note.

## Fixes
Fixes #9321.

## Approach
- No documentation on specifying multiple disjoint MIME types with
  ```Intent.ACTION_GET_CONTENT```

- ```Intent.ACTION_OPEN_DOCUMENT```'s documentation suggests passing ```*/*``` to
  ```setType()```, and specifying the desired disjoint MIME types in an array
  for the intent extra ```Intent.EXTRA_MIME_TYPE```. This suggestion works for
  ```Intent.ACTION_GET_CONTENT``` as well & is the one used to make audio
  files selectable so that they can be imported while adding an audio
  clip.

## How Has This Been Tested?
Tested on:
- Samsung Galaxy S7 API 26 (Physical Device)
- Pixel 4 XL API 30 (Emulator)

 Steps:
1. Add Note
2. Add Audio Clip
3. Click on LIBRARY
4. Audio files in the directory being viewed should be selectable, i.e., shouldn't be greyed out

## Learning (optional, can help others)
[Accepted answer](https://stackoverflow.com/a/23426753/12844135) on StackOverflow led to ```Intent.ACTION_OPEN_DOCUMENT``` documentation, which agreed with the accepted answer & worked with ```Intent.ACTION_GET_CONTENT``` as well.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
Subtle, and that's about what I expected after reading the stackoverflow link earlier, but nothing beats actually *testing* it to make sure (on device, it's the only way really) - thanks!

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioClipFieldController.java [hunk 1]
```diff
@@ -61,8 +61,8 @@ public void createUI(Context context, LinearLayout layout) {
         mBtnLibrary.setText(mActivity.getText(R.string.multimedia_editor_image_field_editing_library));
         mBtnLibrary.setOnClickListener(v -> {
             Intent i = new Intent();
-            i.setType("audio/*");
-            String[] extraMimeTypes = { "application/ogg" }; // #9226 allows ogg on Android 8
+            i.setType("*/*");
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioClipFieldController.java:64]: I've tried for a while, and can't get an API 26 emulator to display anything on a screen. I'll try again tomorrow.

Could you test:

* API 21 - does this change mean that a user can now select any file (if extra mime types isn't respected, it'll default to this)
   * check a .jpg for example

Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioClipFieldController.java:64]: It feels that the second line change (adding `audio/*` to the array) will be all that's necessary, it's an implementation detail of the file picker, and I'm fairly confident that `*/*` will be a functional change on some.

Comment (farjadilyas) [reply AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioClipFieldController.java:64]: Getting the correct result on a Pixel XL API 21 Emulator. A user can't select any file, checked with .jpg and .mp4. It does allow the user to select a .ogg video file (the first selectable file from the top) in addition to music files (the three selectable files at the bottom).

api21_correct_eg

Comment (farjadilyas) [reply AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioClipFieldController.java:64]: Same result on Pixel XL API 26 Emulator

api26_correct

Only allows audio files to be selectable but also allows .ogg video files, which was the original behavior I think.

Comment (farjadilyas) [reply AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioClipFieldController.java:64]: Can confirm that just the second line change (adding ```audio/*``` to the array) yields the correct results on API 21, 26 & 30 Emulators. Will make that change and push.

**Review by david-allison-1 — APPROVED** [review]
Thanks for cleaning up my mess. Looks good to me!

**Review by mikehardy — APPROVED** [review]
:zap: !
