### PR TITLE
Fixes 6770

### LINKED ISSUE #6770: SchedV1: Undo does not reset new count
###### Reproduction Steps

1. 3 cards available
2. Study a new card, flip and answer good
3. 2 cards available
4. Undo

###### Expected Result

5. 3 cards are in "new"

###### Actual Result

5. 2 cards are in "new"

###### Debug info
2.13alpha7

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
## Fixes
#6770 

## Approach

I added a comment explaining what exactly `count()` is doing. I.e. Returning the number of cards to see today in each category, not counting the card sent to the reviewer.  This means that, by considering `mCurrentCard` I was over correcting because the counter already considered current card. I thus removed this over correction and added explanations about what exactly counts are and what they means in a normal use of the scheduler.

## How Has This Been Tested?

Trying to reproduce #6770 and also trying to to undo reviews/burying when the number of cards is limited by the set of cards and not by the deck's limit.

## Learning (optional, can help others)

`counts` and various counts make really no sens; but I was supposed to know it already.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
Once upstream tests are merged and I can reuses the part of the tests that are already existing, I'll be willing to add more tests. Right now, I don't see a point of adding new tests from scratch while I can have already working tests that I can uses when the upstream tests are merged

**Comment by david-allison-1** [comment]
Shouldn't we keep the upstream tests as they are, and add new tests as new methods?

**Comment by Arthur-Milchior** [comment]
Those tests as are relevant upstream as they are on AnkiDroid, so ideally, I hope to also add them upstream. However, it would be simpler if I can do both at the same time so the change are synchronized.

Dealing with conflicting change is already complex when Github can show me the merge conflicts. If I need to have synchronization over two repos, I really want the two PR to be as similar as possible.

**Comment by mikehardy** [comment]
It seems a commit to the upstream tests PR that verifies this and has `#6770` somewhere in the commit comment (so github links it easily) would easily meet the request for a test then?

**Comment by Arthur-Milchior** [comment]
Regression test added

File: AnkiDroid/src/main/java/com/ichi2/libanki/Card.java [hunk 1]
```diff
@@ -451,6 +451,7 @@ public int getQueue() {
 
 
     public void setQueue(@Consts.CARD_QUEUE int queue) {
+        Assert.that(queue != Consts.QUEUE_TYPE_DAY_LEARN_RELEARN, "Day");
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Card.java:454]: Why has this been added?

File: AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java [hunk 2]
```diff
@@ -481,13 +483,15 @@ protected void _answerLrnCard(Card card, int ease) {
                 card.setQueue(Consts.QUEUE_TYPE_LRN);
                 if (!mLrnQueue.isEmpty() && mRevCount == 0 && mNewCount == 0) {
                     long smallestDue = mLrnQueue.getFirst().getDue();
-                    card.setDue(Math.max(card.getDue(), smallestDue + 1));
+                    long maxDue = Math.max(card.getDue(), smallestDue + 1);
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java]: Nit: These refactorings don't seem relevant to the change

File: AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java [hunk 3]
```diff
@@ -2898,6 +2926,16 @@ protected boolean currentCardIsInQueueWithDeck(int queue, long did) {
         // mCurrentCard may be set to null when the reviewer gets closed. So we copy it to be sure to avoid NullPointerException
         Card currentCard = mCurrentCard;
         List<Long> currentCardParentsDid = mCurrentCardParentsDid;
-        return currentCard != null && currentCard.getQueue() == queue && currentCardParentsDid != null && currentCardParentsDid.contains(did);
+        if (currentCard == null) {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java:2929]: This seems to have changed since the last time I reviewed. Is this part of the bugfix?

File: AnkiDroid/src/main/java/com/ichi2/libanki/Card.java (hunk 1 above)
Comment (Arthur-Milchior) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Card.java:454]: I thought I added it in another branch. I don't know how it ended here. Clearly I should remove it

File: AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.java [hunk 4]
```diff
@@ -142,4 +149,47 @@ public void ensureDeckTree() {
...
+    public void ensureUndoCorrectCounts() {
+        Collection col = getCol();
+        AbstractSched sched = col.getSched();
+        Deck deck = col.getDecks().get(1);
+        DeckConfig dconf = col.getDecks().getConf(1);
+        dconf.getJSONObject("new").put("perDay", 10);
+        JSONArray newCount = deck.getJSONArray("newToday");
+        for (int i = 0; i < 20; i++) {
+            Note note = col.newNote();
+            note.setField(0, "a");
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.java:163]: For future: I've added `addNoteUsingBasicModel` inside `RobolectricTest`

File: AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java [hunk 5]
```diff
@@ -156,5 +161,48 @@ public void ensureDeckTree() {
...
+        }
+        sched.reset();
+        assertThat(col.cardCount(), is(20));
+        assertThat(sched.counts()[0], is(10));
+        Card card = sched.getCard();
+        assertThat(sched.counts()[0], is(9));
+        assertThat(sched.counts(card)[0], is(10));
+        sched.answerCard(card, 3);
+        sched.getCard();
+        CollectionTask.launchCollectionTask(UNDO,
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java:186]: I've added `waitForTask(UNDO, timeout);` which should cut down on code here

File: AnkiDroid/src/main/java/com/ichi2/libanki/Card.java (hunk 1 above)
Comment (Arthur-Milchior) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Card.java]: Removed. I used it to try to debug #6768 but it seems it was useless anyway

File: AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java (hunk 2 above)
Comment (Arthur-Milchior) [reply AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java]: I removed all the changes that were due to another branch. I don't really understand how they made it to this branch

File: AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java (hunk 3 above)
Comment (Arthur-Milchior) [reply AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java]: Absolutely not. It's part of the branch I used to debug another problem. I didn't think it would split unto multiple commit. I don't get it

File: AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java (hunk 5 above)
Comment (Arthur-Milchior) [reply AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java:186]: I don't think it fit. I actually want to take the card in onProgressUpdate and it does not seems there is a way to do it using only waitForTask

File: AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.java (hunk 4 above)
Comment (Arthur-Milchior) [reply AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.java:163]: Thanks. Used it while I was making the changes

File: AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java (hunk 5 above)
Comment (Arthur-Milchior) [reply AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java:184]: For context, when you undo, progressUpdate is used to send a card to the reviewer. Then the reviewer uses this card and send it to counts() to get the counts it actually displays. So it is actually required to do onProgressUpdate to check whether the code actually works

**Comment by Arthur-Milchior** [comment]
Conflict removed

**Comment by mikehardy** [comment]
@Arthur-Milchior I left detailed comments in my request-changes note though: your test is using twice the code (duplicated in SchedV2Test and SchedTest) to do half the work (it's not getting the V2 scheduler in the SchedV2Test, so it's just testing V1 again).

Move the test to AbstractSchedTest and you will use half the code (only in one spot now...) to do twice the work (it's parameterized over the two schedulers automatically)

**Comment by Arthur-Milchior** [comment]
I fear I did miss your comment while I was writting mine (and rebasing)

**Comment by mikehardy** [comment]
pinged David for review again since he'd lodged a note but it's good to go from my perspective

File: AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java [hunk 6]
```diff
@@ -85,4 +90,47 @@ public void testUndoResetsCardCountsToCorrectValue() throws InterruptedException
...
+                    @Override
+                    public void onProgressUpdate(TaskData data) {
+                        card = data.getCard();
+                    }
+
+
+                    @Override
+                    public void onPostExecute(TaskData result) {
+                        assertThat(sched.counts()[0], is(9));
+                        assertThat(sched.counts(card)[0], is(10));
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java:132]: Can you add an assertion that this code is executed? Guarantees about how multithreaded code execute can change over time with testing framework changes, and knowing explicitly that a test is broken gives value in this case

Comment (mikehardy) [reply AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java:132]: Interesting - you mean like, a member variable that starts false, you set it to true in onPostExecute and then assert it is true... where?

Comment (Arthur-Milchior) [reply AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java:132]: It was executed on my computer, that is sure because the test did fail when it was applied before the fix. That does not mean it also works on travis.

I guess I can copy the code from waitForTask and wait one second and see whether the inner code was executed. It means that one second will be lost each times test are executed, which is quite often. I would hope for better way to exists

Comment (david-allison-1) [reply AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java:132]: I added a `waitForAsyncTasksToComplete` - it has more semantic meaning and may be helpful

Comment (Arthur-Milchior) [reply AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java:132]: What should I do ? Call it twice to ensure that two tests are exectued ? The code does not seems clear to me right now

Comment (david-allison-1) [reply AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java:132]: Hmm... leave a boolean as a local: `boolean onPostExecuteCalled = false`, set it at the end of `onPostExecute()`

Call `waitForAsyncTasksToComplete`  then assert the boolean has been set.

Use Android Studio auto refactorings to convert the boolean into an `AtomicBoolean`

Comment (Arthur-Milchior) [reply AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java:134]: Done. Thanks

**Comment by Arthur-Milchior** [comment]
Why are you requesting my review of my PR? a misclick ?

**Comment by Arthur-Milchior** [comment]
Rebased onto a version without the flakyness as corrected in https://github.com/ankidroid/Anki-Android/pull/6816#event-3623170146

**Comment by Arthur-Milchior** [comment]
Conflict removed

**Comment by mikehardy** [comment]
Made it's way through review and conflicts and Travis! Yay
