### PR TITLE
fix: suppressed stack trace when error in coroutine occurs.

### LINKED ISSUE #12238: Improve/document debugging Coroutine errors
I had an issue where the following line call was throwing due to the exception below:

https://github.com/ankidroid/Anki-Android/blob/9f050a6041d53cfb200fab39deee4e457f35a631/AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt#L135

```
com.ichi2.anki.exception.StorageAccessException: No write access to AnkiDroid directory /storage/emulated/0/AnkiDroid
        at com.ichi2.anki.CollectionHelper.initializeAnkiDroidDirectory(CollectionHelper.java:255)
```

This raised an `AlertDialog`, but nowhere in the stack trace was there a reference to the method/lambda/class which caused the exception. It was frustrating to track down the responsible call.

https://github.com/ankidroid/Anki-Android/blob/c69218e6ad452f859eb72e8a9a1806104bda5650/AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt#L109-L116

I would ideally like to see: `AdvancedSettingsFragment.kt:135` somewhere in the AlertDialog, OR the stack trace of the calling code somewhere in Android Studio

### PR DESCRIPTION
**Pull request by divyansh-dxn**
Reason: The leading string in `Timber.e("caught: %s %s", exc, extraInfo)` caused  stack trace to be suppressed.

## Fixes
Fixes #12238

https://user-images.githubusercontent.com/69595691/187378845-4a4b2198-4f1f-4c72-a862-beabe6f35665.mp4

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt [hunk 1]
```diff
@@ -57,15 +57,17 @@ suspend fun <T> FragmentActivity.runCatchingTask(
     try {
         return block()
     } catch (exc: CancellationException) {
-        // do nothing
+        Timber.w(exc)
+        // Rethrowing cancellation exception to notify the parent
+        throw exc
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt:62]: This is a functional change and should be explained, ideally in a separate commit. 

All other paths ignore the exception

**Review by david-allison — CHANGES_REQUESTED** [review]
LGTM! One issue with the functional change, which I believe should be in a separate PR: I don't believe it affects the listed issue.

File: AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt (hunk 1 above)
Comment (divyansh-dxn) [reply AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt]: Okay will make a new PR, probably with some more enhancement.

**Review by david-allison — APPROVED** [review]
