### PR TITLE
Legacy template

### LINKED ISSUE #8978: [Bug] Custom delimiters break in v2.15.x of AnkiDroid
Apologies if this is raised elsewhere, since it's all punctuation it's very difficult to search for.

Essentially my problem is about custom delimiters, I have a lot of jinja templates in my questions and answers (mostly for Ansible) so I use custom delimiters with `{{=<% %>=}}` which AnkiDroid previously handled fine but the latest update (2.15.0) breaks this behaviour. This behaviour in Anki is documented here: https://apps.ankiweb.net/docs/manual20.html#latex-conflicts

###### Reproduction Steps
1. Have a template like this for back of a card with custom delimiters:
```
{{=<% %>=}}

<%FrontSide%>

<hr id=answer>

<section>
<%Back__pk%>
</section>
```

###### Expected Result
Card displays properly 

###### Actual Result
image

###### Debug info
Refer to the [support page](image) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](image) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
Fixes #8978

I could have factorized legacy_handlebar_token and new_handlebar_token, but I don't think it would have improved
readability a lot, and clearly would not have improved the speed as it would require more parameter/function call.

### CODE REVIEW

File: AnkiDroid/src/test/java/com/ichi2/libanki/template/TokenizerTest.java [hunk 1]
```diff
@@ -74,158 +100,557 @@ public void test_classify_handle() {
     }
 
     @Test
-    public void test_handlebar_token() {
-        assertThat(handlebar_token("{{#foo}} bar"),
+    public void test_new_handlebar_token() {
+        assertThat(new_handlebar_token("{{#foo}} bar"),
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/libanki/template/TokenizerTest.java:104]: could you refactor this rename into a new commit? It's affected 500 lines and makes it hard to see any test changes

Comment (david-allison-1) [reply AnkiDroid/src/test/java/com/ichi2/libanki/template/TokenizerTest.java:104]: Nevermind - code changes were mostly real, little impact

File: AnkiDroid/src/main/java/com/ichi2/libanki/template/Tokenizer.java [hunk 2]
```diff
@@ -230,17 +272,36 @@ public boolean equals(@Nullable Object obj) {
...
+    @VisibleForTesting
+    protected static @Nullable IResult legacy_handlebar_token(@NonNull String template) {
+        if (template.length() < 2 || template.charAt(0) != '<' || template.charAt(1) != '%') {
+            return null;
+        }
+        int end = template.indexOf("%>");
+        if (end == -1) {
+            return null;
+        }
+        String content = template.substring(2, end);
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/libanki/template/Tokenizer.java:288]:
```suggestion
        String content = template.substring("<%".length(), end);
```

Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/libanki/template/Tokenizer.java:288]: optional - submitter's choice (couple places that this could be done - not added comments)

File: AnkiDroid/src/main/java/com/ichi2/libanki/template/Tokenizer.java [hunk 3]
```diff
@@ -230,17 +272,36 @@ public boolean equals(@Nullable Object obj) {
...
+        @NonNull Token handlebar = classify_handle(content);
+        return new IResult(handlebar, template.substring(end+2));
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/libanki/template/Tokenizer.java:290]:
```suggestion
        return new IResult(handlebar, template.substring(end + 2));
```

File: AnkiDroid/src/main/java/com/ichi2/libanki/template/Tokenizer.java [hunk 4]
```diff
@@ -34,16 +34,27 @@
...
-    private @Nullable boolean mFailed;
+    private boolean mFailed = false;
+
+    /**
+     * Whether we consider <% and %> as handlebar
+     */
+    private final boolean mLegacy;
 
     Tokenizer(@NonNull String template) {
+        mLegacy = template.startsWith(ALT_HANDLEBAR_DIRECTIVE);
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/libanki/template/Tokenizer.java:54]: Is this only `startsWith`? Anything else valid (such as spaces, or is that pulled out in the parsing stage)?

**Review by david-allison-1 — DISMISSED** [review]
LGTM, only nits. Very well-tested

File: AnkiDroid/src/test/java/com/ichi2/libanki/template/TokenizerTest.java [hunk 5]
```diff
@@ -32,17 +34,41 @@
...
+                Matchers.is(new Tokenizer.IResult(
+                        new Tokenizer.Token(Tokenizer.TokenKind.TEXT, "foo"),
+                        "{{bar}}plop")));
+        assertThat(text_token("foo{bar}plop", true),
+                Matchers.is(new Tokenizer.IResult(
+                        new Tokenizer.Token(Tokenizer.TokenKind.TEXT, "foo{bar}plop"),
+                        "")));
+
+        assertThat(text_token("<%neasiet%>", true), is(nullValue()));
+        assertThat(text_token("foo<%bar%>plop", true),
```
Comment (mikehardy) [inline AnkiDroid/src/test/java/com/ichi2/libanki/template/TokenizerTest.java:68]: This is in violation of [RFC3092.2.2](https://datatracker.ietf.org/doc/html/rfc3092#section-2) in that plop is not on the list and baz is the correct 3rd metasyntactic variable

But I'll let it slide.

**Review by mikehardy — APPROVED** [review]
Seems fine this time as well but I missed the need for .trim() on the last big tokenizer PR as well :-). I'm sure it's good

**Comment by mikehardy** [comment]
David had some things that seemed either informative or optional but might prompt a revision
I'm okay with merge after those are thought about

File: AnkiDroid/src/test/java/com/ichi2/libanki/template/TokenizerTest.java (hunk 5 above)
Comment (Arthur-Milchior) [reply AnkiDroid/src/test/java/com/ichi2/libanki/template/TokenizerTest.java:68]: Thanks, I did not know this RFC

File: AnkiDroid/src/main/java/com/ichi2/libanki/template/Tokenizer.java (hunk 4 above)
Comment (Arthur-Milchior) [reply AnkiDroid/src/main/java/com/ichi2/libanki/template/Tokenizer.java:54]: I'll add javadoc stating explicitly that the string should trimmed.

The rust code is `if template.trim_start().starts_with(ALT_HANDLEBAR_DIRECTIVE)`

File: AnkiDroid/src/test/java/com/ichi2/libanki/template/TokenizerTest.java (hunk 5 above)
Comment (mikehardy) [reply AnkiDroid/src/test/java/com/ichi2/libanki/template/TokenizerTest.java:68]: Probably because it was released on April 1st (April Fools' Day in the US ;-) ) - it's just for fun

Comment (mikehardy) [reply AnkiDroid/src/test/java/com/ichi2/libanki/template/TokenizerTest.java:68]: we'll have to implement sync-by-IP-over-Avian-Carriers next if we pay too much attention !

**Comment by Arthur-Milchior** [comment]
@mikehardy @david-allison-1 it needs a second review because it was really rewritten.

**Review by david-allison-1 — COMMENTED** [review]
Why was this rewritten? It seemed fine the first time

**Comment by Arthur-Milchior** [comment]
Your remark
> Is this only startsWith? Anything else valid (such as spaces, or is that pulled out in the parsing stage)?

was right. It was a bug. Not detected by tests.

I tried to change the tests and realized that they were very complex, containing a lot of duplication.
So I factorized tests, ensuring that they get easier to read, and that they can be generalized for both "new" and "legacy_and_new" version of the methods, which catch the bug you found and avoid to repeat code with slightly different variation.

No, I don't think the first version was good, when I re read it, I found a lot of copy paste, which is really not a good idea

**Comment by mikehardy** [comment]
Hey @Arthur-Milchior - I've merged in + cherry-picked-to-release-2.15 the two related PRs where you peeled out all of the NF stuff I believe? Should shrink this down quite a bit

**Comment by Arthur-Milchior** [comment]
Rebased

File: AnkiDroid/src/main/java/com/ichi2/libanki/template/Tokenizer.java [hunk 6]
```diff
@@ -167,17 +193,35 @@ public boolean equals(@Nullable Object obj) {
...
+        @VisibleForTesting
+        public @NonNull IResult new_to_legacy() {
+            return new IResult(mToken.new_to_legacy(), Tokenizer.new_to_legacy(mRemaining));
+        }
+    }
 
     /**
      * @param template The part of the template that must still be lexed
-     * @return The longest prefix without {{, or null if it's empty.
+     * @param legacy whether to <% is accepted as an handlebar
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/libanki/template/Tokenizer.java:205]:
```suggestion
     * @param legacy whether <% is accepted as a handlebar
```

File: AnkiDroid/src/main/java/com/ichi2/libanki/template/Tokenizer.java [hunk 7]
```diff
@@ -34,6 +34,9 @@
  * Due to the way iterator work in java, it's easier for the class to keep track of the template
  */
 public class Tokenizer implements Iterator<Tokenizer.Token> {
+    @VisibleForTesting
+    public static String ALT_HANDLEBAR_DIRECTIVE = "{{=<% %>=}}";
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/libanki/template/Tokenizer.java:38]: Could you add a little more documentation on the variable. Specifically that it's used as a marker, and is only valid at the start

File: AnkiDroid/src/main/java/com/ichi2/libanki/template/Tokenizer.java [hunk 8]
```diff
@@ -43,7 +46,21 @@
...
+     */
+    private final boolean mLegacy;
+
+
+    /**
+     * @param template A question or answer template.
+     */
     Tokenizer(@NonNull String template) {
+        String trimmed = template.trim();
+        mLegacy = trimmed.startsWith(ALT_HANDLEBAR_DIRECTIVE);
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/libanki/template/Tokenizer.java:60]: I'll question `.startsWith` due to the tokenisation process, but you know best.

**Review by david-allison-1 — COMMENTED** [review]
I've read it, I don't feel confident with my review (my knowledge of the templating engine is close to 0 after the 2,15 changes), but this seems sensible from an outside perspective.

I think a little more documentation on the nature of this feature would be useful, both in a textual description, and a link to the Anki Manual where it's described

File: AnkiDroid/src/main/java/com/ichi2/libanki/template/Tokenizer.java (hunk 8 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/libanki/template/Tokenizer.java:60]: I'm actually not sure how it works if it starts with what looks like the whole encapsulating prefix + suffix without it being a regex allowing for the token in between prefix and suffix, but I'm still reading through and ... the test appears to probe it pretty thoroughly

**Review by mikehardy — APPROVED** [review]
the NF transformations leading to the last commit all seemed fine - thank you for splitting them apart so they were easy to follow, and the last commit where the fix happens does seem functional based on the tests that are probing it, but it does seem to be a bit of magic in the same line David mentioned about the startsWith. On the whole, I'm going to go with the testing which appears to cover all cases

File: AnkiDroid/src/main/java/com/ichi2/libanki/template/Tokenizer.java (hunk 8 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/libanki/template/Tokenizer.java:60]: See the sample: https://github.com/ankidroid/Anki-Android/issues/8978 - it's the whole token

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/libanki/template/Tokenizer.java:60]: got it! thanks @david-allison-1

File: AnkiDroid/src/main/java/com/ichi2/libanki/template/Tokenizer.java (hunk 7 above)
Comment (Arthur-Milchior) [reply AnkiDroid/src/main/java/com/ichi2/libanki/template/Tokenizer.java]: done

File: AnkiDroid/src/main/java/com/ichi2/libanki/template/Tokenizer.java (hunk 8 above)
Comment (Arthur-Milchior) [reply AnkiDroid/src/main/java/com/ichi2/libanki/template/Tokenizer.java:66]: It used to accept a more general regexp. However, it seems this feature was never actually used, and people kept using the example given in the old documentation, always using <% and %> as alternative handlebar. When Anki moved to rust, this was finally fixed and became the only acceptable alternative, which simplifies the parsing process.

At least, that's the way I remember things

**Review by david-allison-1 — APPROVED** [review]
LGTM, I'd have thought this would have taken on a conflict due to the typo fix "kind" PR
