### PR TITLE
Fetch new card for review after reschedule, Fixes #5167

### LINKED ISSUE #5167: Rescheduling doesn't work (?)
###### Reproduction Steps

1. Review a card
2. Choose "Scheduling" - "new card plan" (I don't know the English term, I'm using German)
3. Type in new interval xxx days (there is "0/4" written below the text field, what does that mean??) and press OK

###### Expected Result

Card should be re-scheduled and disappear from review screen

###### Actual Result

Card remains in review screen and I need to press one of the 3 answer buttons. So the previously typed in rescheduling interval will be overwritten (probably).

Actually I couldn't check the new interval because AnkiDroid lacks a field for that in the card browser (Anki desktop shows the due date, AnkiDroid not)

So this issue combines 2 things:
1) after scheduling a card during reviews, the card should no longer be seen. Moreover, provide an explanation what that "0/4" below the interval text field means.

2) please provide a field in the card browser (or an entry in the context menu) that shows the current interval/due date for that card.

###### Debug info
AnkiDroid Version = 2.9alpha54

Android Version = 8.1.0

ACRA UUID = f2d13677-d957-460e-9f8e-33ca6f832c17

###### Research
*Enter an [ x ] character to confirm the points below:*

[  x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[X  ] I have searched for similar existing issues here and on the user forum

### PR DESCRIPTION
**Pull request by mikehardy**
## Purpose / Description
My rescheduling PR #5113 was correctly rescheduling, except the part where you have to then get a new card into the Reviewer.

This revises that work so that after performing the rescheduling actions you get a new card as well

## Fixes
Fixes #5167 

## Approach
The AbstractFlashcardViewer already had an "answer notes" handler with all the infrastructure to display new cards or not based on DeckTask.TaskData values, and there was a "dismiss notes" handler that called in to it.

Since the rescheduling is just a special form of "dismiss notes" everything already lined up well. I just needed to take my "schedule notes" handler and chain in to the existing "dismiss notes"->"answer notes" handlers and everything worked.

## How Has This Been Tested?
I tested it on an API27 emulator only. However, it is using the existing dismiss notes infrastructure int the same style as the current usage, so it should be fine?

### CODE REVIEW

**Comment by mikehardy** [comment]
@timrae another really quick one where I got lucky with a bug and the solution was already implemented so long as I hooked into it correctly...

**Comment by mikehardy** [comment]
@timrae This one would potentially address #5183 (which I just closed with a reference to here) and is a quick win if you want to scan it...otherwise as it's a +15 -4 diff using all existing infrastructure to make a bug fix on an accepted feature I'll put it in my sleep-a-bit-more-then-merge queue otherwise. With fingers crossed per usual...

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java [hunk 1]
```diff
@@ -87,12 +87,19 @@ protected int getToastResourceId() {
 
         @Override
         public void onPreExecute() {
-            Timber.d("Reviewer::ScheduleDeckTaskListener() onPreExecute");
+            mDismissCardHandler.onPreExecute();
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java]: This is a bit unusual hooking directly into another Async task's callbacks. Did you see this somewhere else in the code? A cleaner way would be to refactor out new methods with good names describing what they do.

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java]: I thought the same - but chaining into another handler is a pattern that exists, so I just copied it from another handler. As a bug fix (and with the two other big refactors queued up) I wanted minimal code motion for all of our sake.

mDismissCardHandler (which I use here) calls into mAnswerCardHandler and the combination of the two is the behavior I want - here's where that happens - https://github.com/ankidroid/Anki-Android/blob/aef92fc1a595be33bca0ca8977aade0b920bbeee/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L440

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java]: I could refactor if you want of course, but then it won't be +15 -4 comments/spelling changes included :)

Comment (timrae) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java]: > chaining into another handler is a pattern that exists

I don't think it's a very good pattern, it seems like a recipe for bugs. Let's say someone changes something in the dismiss handler, it will most likely not be clear to them that will have unintended consequences in other handlers. Whereas if it's refactored into a function it's immediately clear that "this code is probably used in multiple places"

Comment (timrae) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java]: > I could refactor if you want of course, but then it won't be +15 -4

Yeah please do. It's totally fine and encouraged to have a slightly larger diff  when the extra lines improve readability.

**Comment by mikehardy** [comment]
@timrae hopefully this is more obvious for future code explorers - the commit messages in the current version explain tell the tale, 1 for the refactor, 1 for the bugfix
