### PR TITLE
Fix leech snackbar overlapping answer buttons

### LINKED ISSUE #12606: [Bug] "Card marked as leech" snackbar shows on top of answer buttons
###### Reproduction Steps
1. Tap again during review so the card is marked as leech

###### Expected Result
The snackbar appears above answer buttons like other snackbars

###### Actual Result
The snackbar covers answer buttons

###### Debug info
AnkiDroid Version = 2.16alpha86

Android Version = 12

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-A225F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/105.0.5195.136 Mobile Safari/537.36

ACRA UUID = 6cf7bbad-e282-47db-ad26-f6170967fa55

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by yellowjello**
## Purpose / Description
The snackbar that show when a card becomes a leech would overlap with the answer buttons.

This PR fixes the issue by showing the snackbar above the answer buttons.

## Fixes
Fixes #12606

## Approach
Use a variation of the approach suggested by @oakkitten in the issue.

`showSnackbar` is an extension function, so we can't override it, but we can make an interface that an Activity can implement to specify default configuration for a snackbar and `showSnackbar` can take this configuration into account.

Instead of specifying an anchor view as originally suggested, I've opted to use a `SnackbarBuilder` instead so that we can have more flexibility without really increasing the complexity.

I've also removed code for explicitly setting the snackbar above the answer buttons, since a regular `showSnackbar` will do the job now.

## How Has This Been Tested?

Tested leech, undo, bury, and suspend snackbars on both the old and new backends in emulator.

Screenshot of leech snackbar being fixed:
Screenshot 2023-03-05 at 2 35 45 PM

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt [hunk 1]
```diff
@@ -1822,32 +1824,15 @@ abstract class AbstractFlashcardViewer :
         closeReviewer(RESULT_ABORT_AND_SYNC, true)
     }
 
-    /** Displays a snackbar which does not obscure the answer buttons  */
-    private fun showSnackbarAboveAnswerButtons(
-        text: CharSequence,
-        duration: Int = Snackbar.LENGTH_LONG,
-        snackbarBuilder: SnackbarBuilder? = null
-    ) {
-        // BUG: Moving from full screen to non-full screen obscures the buttons
```
Comment (yellowjello) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt:1831]: Not sure if we want to retain this comment somewhere.

**Comment by david-allison** [comment]
@oakkitten - this one's snackbar-design related. Thoughts would be great when you have time

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt (hunk 1 above)
Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt:1831]: I believe that this can be extracted into a github issue

File: AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt [hunk 2]
```diff
@@ -98,7 +109,14 @@ fun Activity.showSnackbar(
     val view: View? = findViewById(R.id.root_layout)
 
     if (view != null) {
-        view.showSnackbar(text, duration, snackbarBuilder)
+        var defaultSnackbarBuilder: SnackbarBuilder? = null
+        if (this is SnackbarConfigurationProvider) {
+            defaultSnackbarBuilder = this.defaultSnackbarBuilder
+        }
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt:115]: nit: to avoid using a var
```suggestion
        val defaultSnackbarBuilder = if (this is SnackbarConfigurationProvider) {
            this.defaultSnackbarBuilder
        } else {
            null
        }
```

**Review by BrayanDSO — APPROVED** [review]
I really like the design. LGTM. Left only a nit

File: AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt (hunk 2 above)
Comment (yellowjello) [reply AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt]: Good idea!

File: AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt [hunk 3]
```diff
@@ -31,6 +31,17 @@ import timber.log.Timber
...
+/**
+ * An activity can implement this interface to specify a
+ * default configuration for snackbars shown in the activity.
+ */
+interface SnackbarConfigurationProvider {
+    /**
+     * The SnackbarBuilder that will be run to provide a base configuration for snackbars shown.
+     */
+    val defaultSnackbarBuilder: SnackbarBuilder?
+}
```
Comment (oakkitten) [inline AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt:43]: A couple of nitpicks.

* I suggest that interfaces that end in `Provider` should have the only method or field that returns what's it's supposed to provide named exactly like the interface, sans “provider”. E.g. interface `SpoiledMilkProvider` should either have `fun getSpoiledMilk()` (or `obtain` or `make` if applicable) or `val spoiledMilk` and should never have `val badMilk` or anything else.
* Why nullable? Non-nullable would be slightly simpler.
* Not a fan of the word “default” here, “default” implies that it is _an alternative_ to a more specific thing. If specified, the more specific thing replaces the default thing, and is not combined with it, like in this case. Perhaps “base” would be better:
  ```kt
  interface BaseSnackbarBuilderProvider {
      val baseSnackbarBuilder: SnackbarBuilder
  }
  ```

P.S. In the end, I personally would consider go with what I initially suggested:

```kt
interface AnchorViewForSnackbarProvider {
    val anchorViewForSnackbar: View?
}
```

Why? This is a less versatile interface, but it's more specific and I just don't know what else you could use a base snackbar builder for. Also, you will avoid the somewhat awkward

```kt
override val defaultSnackbarBuilder: SnackbarBuilder = { ... }
```

File: AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt [hunk 4]
```diff
@@ -98,7 +109,15 @@ fun Activity.showSnackbar(
     val view: View? = findViewById(R.id.root_layout)
 
     if (view != null) {
-        view.showSnackbar(text, duration, snackbarBuilder)
+        val defaultSnackbarBuilder = if (this is SnackbarConfigurationProvider) {
+            this.defaultSnackbarBuilder
+        } else {
+            null
+        }
```
Comment (oakkitten) [inline AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt:116]: This can be simplified to
```kt
val defaultSnackbarBuilder = (this as? SnackbarConfigurationProvider)?.defaultSnackbarBuilder
```

File: AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt [hunk 5]
```diff
@@ -98,7 +109,15 @@ fun Activity.showSnackbar(
...
+        view.showSnackbar(text, duration) {
+            defaultSnackbarBuilder?.let { it() }
+            snackbarBuilder?.let { it() }
```
Comment (oakkitten) [inline AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt:119]: Nit: I would slightly prefer this here:
```kt
snackbarBuilder?.invoke(this)
```
or maybe even better:
```kt
if (snackbarBuilder != null) { snackbar.snackbarBuilder() }
```

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt [hunk 6]
```diff
@@ -1822,32 +1824,15 @@ abstract class AbstractFlashcardViewer :
...
-        showSnackbar(text, duration) {
-            snackbarBuilder?.let { it() }
-
+    override val defaultSnackbarBuilder: SnackbarBuilder?
+        get() = {
```
Comment (oakkitten) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt:1828]: I don't think you need a getter here

**Review by oakkitten — COMMENTED** [review]
I'm not a fan of only `Activity.showSnackbar` checking if `this` is `SnackbarConfigurationProvider`. A fragment should be able to provide an anchor view as well.

File: AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt (hunk 5 above)
Comment (yellowjello) [reply AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt]: I don't have too much opinion on this, so I changed it to use the `invoke` option. But I agree that consistency is the most important thing.

File: AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt (hunk 4 above)
Comment (yellowjello) [reply AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt]: Good to know!

File: AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt (hunk 3 above)
Comment (yellowjello) [reply AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt]: > Not a fan of the word “default” here, “default” implies that it is an alternative to a more specific thing. If specified, the more specific thing replaces the default thing, and is not combined with it, like in this case. Perhaps “base” would be better

I thought about using "base" but I originally decided against it since it might give a connotation that it is a base class. But looking at the class names in the codebase, it seems that most of the time for base classes (with very few exceptions), the word "base" is added to the end instead, so using base as the front is not as confusing as I originally thought.

I've updated to use your suggested naming.

> P.S. In the end, I personally would consider go with what I initially suggested

Another benefit to using a `SnackbarBuilder` beyond just being able to configure more stuff is the ability to dynamically specify the anchor view (due to `SnackbarBuilder` being a function), which is exactly the use case in the reviewer since it needs to switch between the "show answer" button and the answer buttons.

With the the anchor view version of the interface, we will have to use a getter, which is not a big deal, but it is a trade-off.

**Comment by yellowjello** [comment]
> I'm not a fan of only `Activity.showSnackbar` checking if `this` is `SnackbarConfigurationProvider`. A fragment should be able to provide an anchor view as well.

Right - I've just added support for fragments as well. If both a fragment and activity setting is present, the fragment will take precedence since it will be applied later.

File: AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt [hunk 7]
```diff
@@ -31,6 +31,17 @@ import timber.log.Timber
...
+/**
+ * An activity/fragment can implement this interface to specify a
+ * default configuration for snackbars shown in the activity/fragment.
+ */
+interface BaseSnackbarBuilderProvider {
+    /**
+     * The SnackbarBuilder that will be run to provide a base configuration for snackbars shown.
+     */
+    val baseSnackbarBuilder: SnackbarBuilder
+}
```
Comment (oakkitten) [inline AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt:43]: Just thoughts

> Another benefit to using a SnackbarBuilder beyond just being able to configure more stuff is the ability to dynamically specify the anchor view (due to SnackbarBuilder being a function), which is exactly the use case in the reviewer since it needs to switch between the "show answer" button and the answer buttons.

> With the the anchor view version of the interface, we will have to use a getter, which is not a big deal, but it is a trade-off.

I suppose you'd have to use an getter either way (you wouldn't have a view at construction time), but I would not consider this as a trade-off. This would be the same as

```kt
interface AnchorViewForSnackbarProvider {
    fun getAnchorViewForSnackbar(): View?
}
```

but more Kotlin-like. In the case of goin the more versatile way, I would prefer to not have an interface that returns a function (a `SnackbarBuilder`), but instead an interface with a single function that takes a `Snackbar`. Hard to come up with a good name here, but perhaps something like um...

```kt
interface SnackbarConfigurer {
    fun configureSnackbar(snackbar: Snackbar)
}
```

But on the second thought, though, this is almost the same as `SnackbarBuilder`, so now we'd have the same concept represented via two different names, which I am vehemently against.

So at the end of the day I'd say the best two options that I like are the aforementioned more specific

```kt
interface AnchorViewForSnackbarProvider {
    val anchorViewForSnackbar: View?
}
```
and your variant, which, while leading to a slightly awkward

```kt
override val defaultSnackbarBuilder: SnackbarBuilder = { ... }
```
doesn't introduce new names. So if you don't like getters this is fine by me. 👍

**Review by oakkitten — APPROVED** [review]
Sorry for the wait. Posted a few thoughts for closure, but I like the changes 👍

(Disclaimer: I didn't run the code)

**Review by BrayanDSO — APPROVED** [review]
I’m considering oakkitten’s approval as the second one. Thanks for the contribuition!
