### PR TITLE
Forward port to new OkHttp4 dependency

### LINKED ISSUE #5223: Deprecation - OkHttp 3.13.x is out but only for Android API21+ / 5+
Future versions of the OkHttp dependency will only support API21+ which we are probably one major version away from moving to as a minSdkVersion. They are backporting critical items to 3.12.x through December 2020 so this isn't a serious issue but it is something to remember.

### LINKED ISSUE #7465: Sync dialog always displays 0 bytes downloaded
###### Reproduction Steps

1. Press synchronization icon
2. Look at dialog
3. Sync succeeds but reports 0 bytes downloaded

###### Expected Result

Sync reports a non-zero number when downloading changes like new decks.

###### Actual Result

Sync reports zero bytes.

###### Debug info

AnkiDroid Version = 2.13.5

Android Version = 11

ACRA UUID = 7711c2bd-3fb4-46ef-9f9d-28911d96e09c

Scheduler = std

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

###### Screenshot

Screenshot_20201024-145042

### PR DESCRIPTION
**Pull request by mikehardy**
## Purpose / Description

Modern versions of OkHttp are available now that we have a minSdkVersion >= 21

## Fixes

Fixes #5223 
Fixes #7465

## Approach

- I maintained the TLS1.2 workaround, but reduced it to Samsung only as they are the only reported failures with API21, everyone else at API21 works, and this may be removed next minSdkVersion bump
- I did a fair amount of cleaning, in little commits
- I forward-ported to the new APIs - very very simple changes
- I added correct traffic counting of response bodies, and added request/response header length to traffic counts

## How Has This Been Tested?

local androidTest runs (it does exercise the connection actually, plus API21 and API30 emulators with a test collection, it all worked and traffic counts look good now!

## Learning (optional, can help others)

It is maybe possible to convert all the counting to a network intercepter but for streaming uploads it did not look any less complicated to wrap the network and count there than it does right now where we wrap the request body and the response return to count. It could be considered better organization but it's a much larger change so I went with the smaller change.

If anyone is curious in the future, you'd want to sort-of adapt their Logging intercepter (Kotlin example: https://github.com/square/okhttp/blob/master/okhttp-logging-interceptor/src/main/kotlin/okhttp3/logging/HttpLoggingInterceptor.kt) but it would need a lot of adaption, which is why I left it.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/libanki/sync/Tls12SocketFactory.java [hunk 1]
```diff
@@ -57,7 +56,7 @@
 
 
     public static OkHttpClient.Builder enableTls12OnPreLollipop(OkHttpClient.Builder client) {
-        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP_MR1) {
+        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP_MR1 && "Samsung".equals(Build.MANUFACTURER)) {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/libanki/sync/Tls12SocketFactory.java:59]: Could I have a source for this? It feels unsafe given that it was working well beforehand

I intuit that there will be other manufacturers other than Samsung which we'll affect

File: AnkiDroid/src/main/java/com/ichi2/anki/web/HttpFetcher.java [hunk 2]
```diff
@@ -62,12 +95,7 @@ public static String fetchThroughHttp(String address, String encoding) {
             requestBuilder.url(address).get();
             Request httpGet = requestBuilder.build();
 
-            OkHttpClient.Builder clientBuilder = new OkHttpClient.Builder();
-            Tls12SocketFactory.enableTls12OnPreLollipop(clientBuilder)
-                    .connectTimeout(Connection.CONN_TIMEOUT, TimeUnit.SECONDS)
-                    .writeTimeout(Connection.CONN_TIMEOUT, TimeUnit.SECONDS)
-                    .readTimeout(Connection.CONN_TIMEOUT, TimeUnit.SECONDS);
-            OkHttpClient client = clientBuilder.build();
+            OkHttpClient client = getOkHttpBuilder(true).build();
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/web/HttpFetcher.java:98]: This seems to be a change in behavior (no agent -> fake one)

File: AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.java [hunk 3]
```diff
@@ -217,6 +220,15 @@ public Response req(String method, InputStream fobj, int comp) throws UnknownHtt
                         (httpResponse.handshake() != null ? httpResponse.handshake().tlsVersion() : "unknown"));
 
 
+                // Count downstream traffic including headers
+                bytesReceived.addAndGet(httpResponse.headers().byteCount());
+                try {
+                    bytesReceived.addAndGet(httpResponse.body().contentLength());
+                } catch (NullPointerException npe) {
+                    Timber.d(npe, "Unexpected null response body");
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.java:228]: Is this NPE avoidable? We don't want exceptions in a tight loop

File: AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.java [hunk 4]
```diff
@@ -201,11 +201,14 @@ public Response req(String method, InputStream fobj, int comp) throws UnknownHtt
...
             requestBuilder.url(parseUrl(url));
 
+            // Set our request up to count upstream traffic including headers
             requestBuilder.post(new CountingFileRequestBody(tmpFileBuffer, ANKI_POST_TYPE.toString(), num -> {
                 bytesSent.addAndGet(num);
                 publishProgress();
             }));
             Request httpPost = requestBuilder.build();
+            bytesSent.addAndGet(httpPost.headers().byteCount());
+            publishProgress();;
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.java:211]: two semicolons - can't suggest here

File: AnkiDroid/src/main/java/com/ichi2/anki/web/HttpFetcher.java [hunk 5]
```diff
@@ -152,7 +151,7 @@ public static String downloadFileToSdCardMethod(String UrlToFile, Context contex
             if ("GET".equals(method)) {
                 requestBuilder.get();
             } else {
-                requestBuilder.post(RequestBody.create(null, new byte[0]));
+                requestBuilder.post(RequestBody.create(new byte[0], null));
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/main/java/com/ichi2/anki/web/HttpFetcher.java:154]: I've honestly no idea what this does. Unless I need to spend time looking at a lot and lot of docs to get the context, there seems to be no way for me to approve or even constructively comment such a change.

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/web/HttpFetcher.java:154]: This was the application of the forward-porting comment in the deprecation notice from the underlying library, applied directly https://github.com/square/okhttp/blob/6333cd2d31fdb7c7120ffc61738a353f6063034a/okhttp/src/main/kotlin/okhttp3/RequestBody.kt#L182-L193

```kotlin
    @JvmStatic
    @Deprecated(
        message = "Moved to extension function. Put the 'content' argument first to fix Java",
        replaceWith = ReplaceWith(
            expression = "content.toRequestBody(contentType)",
            imports = ["okhttp3.RequestBody.Companion.toRequestBody"]
        ),
        level = DeprecationLevel.WARNING)
    fun create(
      contentType: MediaType?,
      content: ByteString
    ): RequestBody = content.toRequestBody(contentType)
```

File: AnkiDroid/src/main/java/com/ichi2/anki/web/HttpFetcher.java [hunk 6]
```diff
@@ -47,11 +48,43 @@
...
+                .connectTimeout(Connection.CONN_TIMEOUT, TimeUnit.SECONDS)
+                .writeTimeout(Connection.CONN_TIMEOUT, TimeUnit.SECONDS)
+                .readTimeout(Connection.CONN_TIMEOUT, TimeUnit.SECONDS);
+
+        if (fakeUserAgent) {
+            clientBuilder.addNetworkInterceptor(chain -> chain.proceed(
+                    chain.request()
+                            .newBuilder()
+                            .header("Referer", "com.ichi2.anki")
+                            .header("User-Agent", "Mozilla/5.0 ( compatible ) ")
```
[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/web/HttpFetcher.java:69]: I don't know but in my experience websites will show you content you don't want like "this site is best viewed in ..." or a desktop version or something. This is used in the pronunciation activity file downloads so I imagine it was added for that reason.

But, the change is non-functional in that the only cases that would get the fake agent before get them now, so I don't have to know or care since I'm not changing behavior.

File: AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.java (hunk 3 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.java:228]: The catch was only added to satisfy Android Studio lint. The odds of the body being null are I think zero in practice.

File: AnkiDroid/src/main/java/com/ichi2/libanki/sync/Tls12SocketFactory.java (hunk 1 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/libanki/sync/Tls12SocketFactory.java:59]: It's apocryphal but widely known. I implemented the hack in the first place after a lot of research - here's the best ref I can find https://stackoverflow.com/a/45202944/9910298

I'm comfortable saying that the last need for this hack is on Android 5.0 exactly, with vendor Samsung.

File: AnkiDroid/src/main/java/com/ichi2/anki/web/HttpFetcher.java (hunk 2 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/web/HttpFetcher.java:98]: That is true and one of the reasons this was not NF.

1)  This control flow is only hit when doing similar things (pronunciation downloads etc) as the other version that faked the user agent. 

2) the only place we "leak" real AnkiDroid version numbers etc is interacting with Anki Sync

3) the logic for OkHttpClient build was copied and different in all places but I wanted to centralize

So, I took this as case 1 above that we were not interacting with AnkiWeb so we should send a fake user agent as we do in other web interaction of that case so it's uniform

I think it will work fine.

File: AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.java (hunk 4 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.java]: Nice! :eagle: :eyes: 
Fixed + pushed.

**Comment by mikehardy** [comment]
I think I addressed all the comments - obviously if anything goes wrong on this one I'll patch it up...
