### PR TITLE
Card browser show even on close

### LINKED ISSUE #7017: [2.13alpha25] Card Browser does not refresh after edit/crashes
###### Reproduction Steps

1. Card Browser with Deck selected, no search
2. Select a card
3. Press "Back" button on device

###### Expected Result

4. Results are shown

###### Actual Result

4. No results are shown

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
There is currently the following problem in ankidroid:
* Search for a big number of card
* quickly change app on android. The window should not be displayed anymore
* wait some time
* come back to AnkiDroid

It should show the list of card, or being processing. Instead it shows
there are 0 card found.

This is because, when the app change, onStop is called, and this
cancel the search. Instead, the cancellation should occur in
onDestroy, whene there the search is not used anymore.

I also allow to cancel another background task if it is not useful anymore.

Testing it on my phone

Fixes #7017

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java [hunk 1]
```diff
@@ -676,8 +676,6 @@ private void openNoteEditorForCurrentlySelectedNote() {
     protected void onStop() {
         Timber.d("onStop()");
         // cancel rendering the question and answer, which has shared access to mCards
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java:678]: this comment seems related, and a little like a warning. what does shared access to mCards mean now if we continue using it in between onStop and onDestroy ? I am not sure it means anything and the change otherwise seems like it should be okay though

Comment (Arthur-Milchior) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java:678]: The comment was introduced in 4743f60db6cfe8b7f9d5e91c977fcb0848703fb4
At this time, the comment was in another method, and it has been copy/pasted here with the cancellation in in eee250ac3a1be04b109ca04c462dc2c97196724c
@timrae do you remember whether this comment you wrote in 2014 is supposed to warn us again anything ?

mCards is a list of card. Here, a card is a map from column entry to their value, there seems to be no reason to worry that anything has access to this map. And even if the list gets changed at some point, a lot of change occured recently which ensure that we have no exception if a concurrent change occured on the list.

I should note however that it was a mistake to leave this comment instead of copying it

**Comment by Arthur-Milchior** [comment]
Rebased because of conflict. Remove the comment, it was mostly useless, since it states that CancelTasks is cancelling the task

**Comment by mikehardy** [comment]
@Arthur-Milchior the rebase from the constants / definitions looks like it needs a tweak - it's got compile errors that are clearly from that

**Comment by david-allison-1** [comment]
Could you give more details of how this was tested? Especially if it was tested after `onStop`,

**Comment by Arthur-Milchior** [comment]
What I tested is simply the bug I described above.

**Comment by Arthur-Milchior** [comment]
I tested before rebasing on master and having the ints replaced by consts

**Comment by Arthur-Milchior** [comment]
Which means I did test leaving ankidroid and coming back, but I didn't try to edit anything in the collection

**Comment by mikehardy** [comment]
I like the implementation now, much cleaner just using the existing signalling for cancel / return value / postExecute task style, my only quibble at this point is that there's a "tmp" commit in the commit list? :-) smiling because you're the master of rebase now I think, this is unusual

**Comment by Arthur-Milchior** [comment]
Done

It was supposed to be a fixup of previous commit. Strange

**Comment by mikehardy** [comment]
@david-allison-1 

> Could you give more details of how this was tested? Especially if it was tested after `onStop`, mostly when the transition to the note editor is made. I feel there's a good chance that we could get some issues if a card template was deleted for example.

I think the test would be something like starting with a copy of this:

https://github.com/ankidroid/Anki-Android/blob/c3fed78e6e31ccc23b9b1dbf84abe0ec0e89cc32/AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java#L337-L345

Then setting up an Intent like this:
https://github.com/ankidroid/Anki-Android/blob/c3fed78e6e31ccc23b9b1dbf84abe0ec0e89cc32/AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.java#L305

Then starting the NoteEditor with this https://github.com/ankidroid/Anki-Android/blob/c3fed78e6e31ccc23b9b1dbf84abe0ec0e89cc32/AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java#L165

And then calling .pause().stop().destroy() on the CardBrowser controller?


And asserting what? you seem to have a hunch here

**Comment by david-allison-1** [comment]
> And asserting what? you seem to have a hunch here

I'm under the impression that there may be a crash if the search returns a card ID that was deleted while the search results are being constructed. This is what the code is guarding against.

I believe that this PR introduces an unlikely path where this could happen (note editor card template editor -> delete card template).

If we're going to introduce this potential bug, we should ensure that the card browser will handle a deleted card correctly.

**Comment by Arthur-Milchior** [comment]
I get your point and it seems to be a realistic risk. That would also be a risk if the API allows to edit the collection from outside.

I believe we should wait until https://github.com/ankidroid/Anki-Android/pull/6372 is merged (or rejected), because dealing with card which disappear will probably be simpler when there is CardCache

**Comment by mikehardy** [comment]
Mmm interesting. Yeah I see from CardTemplateEditor that when it deletes cards from NoteEditor, as long as NoteEditor's current card is fine it just continues

https://github.com/ankidroid/Anki-Android/blob/a16a795805914c33ab7a0988b762d4d97e2e200b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java#L1162-L1184

I just added this magic from NoteEditor to tell the CardBrowser that it should invalidate itself and research on return:

https://github.com/ankidroid/Anki-Android/blob/a16a795805914c33ab7a0988b762d4d97e2e200b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java#L1054-L1056

Maybe to be defensive, CardBrowser should just never trust state after delegating out to NoteEditor and should always invalidate itself/cancel tasks/research. For instance right now if you went CardBrowser -> NoteEditor -> CardTemplateEditor -> CardBrowserAppearance you are clearly interested in changing the way things look in the card browser right? But I don't think it will actually refresh when you return.

If you did that there is no need to wait on other PRs, harden the search against cards disappearing while it is working (just self-cancel, I'd suggest) and on return from NoteEditor always re-issue the search task ?

**Comment by Arthur-Milchior** [comment]
Merge conflict removed

**Comment by Arthur-Milchior** [comment]
I didn't expect to close it, that was an accident. And I don't know why the "reopen" button is not available

**Comment by mikehardy** [comment]
Something happened with the merge - if you hover over the "Reopen and comment" button it will tell you there are no new commits on the branch, from this PR's perspective it is the empty set

**Comment by Arthur-Milchior** [comment]
I took an older version of the PR and added it back. Not sure what did occur. Anyway, it's still waiting for  #6372

**Comment by Arthur-Milchior** [comment]
Conflict resolved

**Comment by mikehardy** [comment]
This one has a conflict now but mostly it's waiting on resolution of the idea in this comment https://github.com/ankidroid/Anki-Android/pull/6611#issuecomment-653815157

Where it seems 

>  "CardBrowser should just never trust state after delegating out to NoteEditor and should always invalidate itself/cancel tasks/research"

**Comment by Arthur-Milchior** [comment]
Actually, in the note editor state that the task was cancelled, no reason to invalidate I believe. Otherwise, it's already invalidating and doing a new search. That's the purpose of the call to `search` after the edit note activity

**Comment by Arthur-Milchior** [comment]
This solve the first remark of https://github.com/ankidroid/Anki-Android/issues/7017#issuecomment-687238128 . Actually both errors are similar: I don't believe `onStop` should kill the list and the background processing that occurs. If the window is reopened, no need to redo the computation. Similarly, if we open the editor, no need to redo the computation unless the card is edited (and when the card was edited, the bug did not occur)


I've manually tested deleting a card type shown in the result set, and this did not lead to a bug.

File: AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java [hunk 2]
```diff
@@ -1879,6 +1879,10 @@ public TaskData doInBackgroundCheckCardSelection(TaskData param) {
         boolean hasUnsuspended = false;
         boolean hasUnmarked = false;
         for (CardBrowser.CardCache c: checkedCards) {
+            if (isCancelled()) {
+                Timber.v("doInBackgroundCheckCardSelection: cancelled.");
+                return null;
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java:1884]: this did not ever return null before, should annotate the method as `@Nullable` now to see what falls out from that (if anything)

There is still the general idea from previous comments that I do not believe has been tested:

from @david-allison-1:

> I believe that this PR introduces an unlikely path where this could happen (note editor card template editor -> delete card template).
> 
> If we're going to introduce this potential bug, we should ensure that the card browser will handle a deleted card correctly.

from me: 

> Maybe to be defensive, CardBrowser should just never trust state after delegating out to NoteEditor and should always invalidate itself/cancel tasks/research. For instance right now if you went CardBrowser -> NoteEditor -> CardTemplateEditor -> CardBrowserAppearance you are clearly interested in changing the way things look in the card browser right? But I don't think it will actually refresh when you return.

Comment (Arthur-Milchior) [reply AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java:1884]: > (note editor card template editor -> delete card template).

I just wrote that
> I've manually tested deleting a card type shown in the result set, and this did not lead to a bug.

This mean I (manually, I admit it) tested this path.

> CardBrowser should just never trust state after delegating out to NoteEditor

I answered here

>Actually, if the note editor state that the task was cancelled, no reason to invalidate I believe. Otherwise, it's already invalidating and doing a new search. That's the purpose of the call to search after the edit note activity

That is; I admit that you are generally quite right. If anything was done in card editor, the list should be rebuilt from scratch. And that is exactly what is already occurring. However, I would believe that if no change were made in the card editor, then there is no reason to recompute the list. This seems especially important because it's easy to just misclick. Computing a search is expensive for big collection and slow phone, I'd like to avoid misclick to loose seconds.

If you disagree and think that even when the card editor state there is no change, we should still recompute, I can do it. But I'd prefer to see you answer my remark first, to know that you have considered this compromise and rejected it

Comment (Arthur-Milchior) [reply AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java:1884]: > this did not ever return null before, should annotate the method as `@Nullable` now to see what falls out from that (if anything)

Right. I added @Nullable.

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java (hunk 1 above)
Comment (timrae) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java:699]: Shared access in this case just meant that libanki had a reference to mCards and was concurrently modifying that data structure on the deck task thread, so you have to be careful. The code base might have changed significantly since then though.

File: AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java (hunk 2 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java:1884]: Okay - if you tested it, my approval is still on here and we can merge it and go for 2.13-release branch cut

Comment (Arthur-Milchior) [reply AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java:1884]: The reason the test works is because if there is a change in the card type, it is also noted as a change in the card, and so requires the search to be done from scratch
