### PR TITLE
fix(copy-debug-info): crash if Context is null 

### LINKED ISSUE #18527: 2.21alpha18: copyStackTraceAndDebugInfo - Fragment not attached to a context
```
java.lang.IllegalStateException: Fragment F{a8637e7} (1a2c688e-f918-44b5-aa9b-1bf0abf89ba1) not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:977)
	at com.ichi2.anki.dialogs.DatabaseErrorDialog.copyStackTraceAndDebugInfo(DatabaseErrorDialog.kt:429)
	at com.ichi2.anki.dialogs.DatabaseErrorDialog.access$copyStackTraceAndDebugInfo(DatabaseErrorDialog.kt:84)
	at com.ichi2.anki.dialogs.DatabaseErrorDialog$copyStackTraceAndDebugInfo$1.invokeSuspend(DatabaseErrorDialog.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:257)
	at android.os.Looper.loop(Looper.java:342)
	at android.app.ActivityThread.main(ActivityThread.java:9634)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:619)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:929)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [r0{Cancelling}@4c25232, Dispatchers.Main.immediate]
```

### PR DESCRIPTION
**Pull request by david-allison**
## Fixes
* Fixes #18527

## Approach
use `AnkiDroidApp.context`

## How Has This Been Tested?

* Tested copy debug info
* Tested with the following, still copies

```patch
Subject: [PATCH] fix(copy-debug-info): crash if Context is null

Fixes 18527
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/AsyncDialogFragment.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/AsyncDialogFragment.kt b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/AsyncDialogFragment.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/AsyncDialogFragment.kt	(revision bdf1b3eb5a1c5eeec293fa67380476ede1d73d18)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/AsyncDialogFragment.kt	(date 1750164167116)
@@ -50,7 +50,7 @@
      */
     protected fun getSafeContext(): Context =
         try {
-            requireContext()
+            AnkiDroidApp.instance
         } catch (e: Exception) {
             Timber.w(e, "Error getting context; using AnkiDroidApp")
             AnkiDroidApp.instance
Index: AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt b/AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt	(revision bdf1b3eb5a1c5eeec293fa67380476ede1d73d18)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt	(date 1750164157928)
@@ -175,6 +175,8 @@
                 bundle.getString(KEY_EXPORT_PATH) ?: error("Missing required exportPath!"),
             )
         }
+
+        showDatabaseErrorDialog(DatabaseErrorDialogType.DIALOG_DB_ERROR, CustomExceptionData("AA"))
     }
 
     override fun onStart() {
```

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/AsyncDialogFragment.kt [hunk 1]
```diff
@@ -42,4 +43,16 @@ abstract class AsyncDialogFragment : AnalyticsDialogFragment() {
...
+    /**
+     * Return the {@link Context} this fragment is currently associated with.
+     * Uses [AnkiDroidApp.instance] if [requireContext] fails
+     */
+    protected fun getSafeContext(): Context =
+        try {
+            requireContext()
+        } catch (e: Exception) {
+            Timber.w(e, "Error getting context; using AnkiDroidApp")
+            AnkiDroidApp.instance
```
Comment (lukstbit) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/AsyncDialogFragment.kt:56]: If it's safe to use the application context why not use it directly instead of adding the method?

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/AsyncDialogFragment.kt:56]: I'd prefer as a general rule prefer the attached context when possible (we've had past i18n issues from using the Application Context).

Reviewer's choice; minor concern, but I wouldn't add a method if we just use `AnkiDroidApp.instance`

**Review by lukstbit — APPROVED** [review]

**Review by mikehardy — APPROVED** [review]
LGTM - and agreed to try the most adjacent context first, only falling back if necessary. I remember the dynamic i18n in-app language selection "some UI doesn't get the new language" issues...
