### PR TITLE
Tex instead of error

### LINKED ISSUE #4597: Display latex code as fallback if image not exists
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[X] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Open a card that has not been rendered with anki desktop before

###### Expected Result
Show latex formula as plaintext code

###### Actual Result
Broken image, no text

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
## Purpose / Description
If you add some LaTeX code to ankidroid and the image is not yet compiled, you just see an error because image is not loaded.
Instead of a broken image, showing the original LaTeX seems to be a good solution.
2020-05-22-113604_480x854_scrot

## Fixes
FIxes #4597

## Approach
By keeping the LaTeX

## How Has This Been Tested?

Opening ankidroid, creating a card with some LaTeX code `[$]3[/3]` (on a collection which does not already have it, and ensuring that I see "$3$" (which is indeed correct LaTeX) instead of a broken image.

## Learning (optional, can help others)
This idea seems straightforward. It would have helped me a lot. But for some reason, I never thought of it before seeing @dreamflasher's idea while I was looking for another bug report.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/libanki/LaTeX.java [hunk 1]
```diff
@@ -96,7 +97,11 @@ private static String _imgLink(String latex, JSONObject model) {
         }
 
         String fname = "latex-" + Utils.checksum(txt) + "." + ext;
-        return "<img class=latex src=\"" + fname + "\">";
+        if (new File(col.getMedia().dir(), fname).exists()) {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/libanki/LaTeX.java:100]: Maybe: https://github.com/ankidroid/Anki-Android/blob/4740941a4e5885f21b331748199d47fd5ca61204/AnkiDroid/src/main/java/com/ichi2/libanki/Media.java#L531-L533

File: AnkiDroid/src/main/java/com/ichi2/libanki/LaTeX.java [hunk 2]
```diff
@@ -87,7 +88,7 @@ public static String mungeQA(String html, Collection col, JSONObject model) {
     /**
      * Return an img link for LATEX.
      */
-    private static String _imgLink(String latex, JSONObject model) {
+    private static String _imgLink(String latex, JSONObject model, Collection col) {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/libanki/LaTeX.java:91]: Nit: Could you pass in `Media` here to reduce the API surface area

**Comment by david-allison-1** [comment]
Maybe better for another PR. Not blocking this going in, but while we're in the area

It'd be useful to perform this operation when we're viewing LaTeX in the card browser as well.

https://github.com/ankidroid/Anki-Android/blob/6e34663ba9d09dc8b023230811c3185b72ee7eec/AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java#L1060

**Comment by david-allison-1** [comment]
Maybe better for another PR. Not blocking this going in, but while we're in the area

It'd be useful to perform this operation when we're viewing LaTeX in the card browser as well.

https://github.com/ankidroid/Anki-Android/blob/6e34663ba9d09dc8b023230811c3185b72ee7eec/AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java#L1060

File: AnkiDroid/src/main/java/com/ichi2/libanki/LaTeX.java (hunk 1 above)
Comment (Arthur-Milchior) [reply AnkiDroid/src/main/java/com/ichi2/libanki/LaTeX.java:100]: Ooups. I should have looked for this before reimplementing it. Sorry

File: AnkiDroid/src/main/java/com/ichi2/libanki/LaTeX.java (hunk 2 above)
Comment (Arthur-Milchior) [reply AnkiDroid/src/main/java/com/ichi2/libanki/LaTeX.java:91]: okay

**Comment by Arthur-Milchior** [comment]
> Maybe better for another PR. Not blocking this going in, but while we're in the area
> 
> It'd be useful to perform this operation when we're viewing LaTeX in the card browser as well.
> 
> https://github.com/ankidroid/Anki-Android/blob/0af4632f1400a4a9dbd6fd9732011aea8ff73442/AnkiDroid/src/main/java/com/ichi2/libanki/Card.java#L276

I don't understand your request. Here is already what occurs in the browser
2020-05-22-205654_480x854_scrot

**Comment by Arthur-Milchior** [comment]
Oh okay, ahving the same result when we are in the browser and the card exists, since the browser does not show card content. Would make sens.
