### PR TITLE
fix: use default constructor / factory + Arguments init style

### LINKED ISSUE #17381: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.CardBrowser}: com.ichi2.anki.exception.UserSubmittedException: Unable to instantiate fragment X3.h: could not find Fragment constructor
https://ankidroid.org/acra/app/1/bug/253877/report/5a4b008d-427b-4876-a085-0095795f52b8

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.CardBrowser}: com.ichi2.anki.exception.UserSubmittedException: Unable to instantiate fragment X3.h: could not find Fragment constructor
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4014)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4167)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:99)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2628)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:222)
	at android.os.Looper.loop(Looper.java:314)
	at android.app.ActivityThread.main(ActivityThread.java:8661)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
Caused by: com.ichi2.anki.exception.UserSubmittedException: Unable to instantiate fragment X3.h: could not find Fragment constructor
	at androidx.fragment.app.Fragment$InstantiationException.<init>(Fragment.java:577)
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:692)
	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:663)
	at com.ichi2.utils.ExtendedFragmentFactory.instantiate(ExtendedFragmentFactory.kt:50)
	at com.ichi2.anki.dialogs.tags.TagsDialogFactory.instantiate(TagsDialogFactory.kt:27)
	at com.ichi2.utils.ExtendedFragmentFactory.instantiate(ExtendedFragmentFactory.kt:50)
	at com.ichi2.anki.export.ExportDialogsFactory.instantiate(ExportDialogsFactory.java:32)
	at androidx.fragment.app.FragmentState.instantiate(FragmentState.java:87)
	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:92)
	at androidx.fragment.app.FragmentManager.restoreSaveStateInternal(FragmentManager.java:2846)
	at androidx.fragment.app.FragmentManager.attachController(FragmentManager.java:3005)
	at androidx.fragment.app.FragmentController.attachHost(FragmentController.java:117)
	at androidx.fragment.app.FragmentActivity.lambda$init$3(FragmentActivity.java:139)
	at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.kt:84)
	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.kt:331)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:216)
	at com.ichi2.anki.AnkiActivity.onCreate(AnkiActivity.kt:114)
	at com.ichi2.anki.CardBrowser.onCreate(CardBrowser.kt:367)
	at android.app.Activity.performCreate(Activity.java:8886)
	at android.app.Activity.performCreate(Activity.java:8851)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1467)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3996)
	... 12 more
Caused by: java.lang.NoSuchMethodException: X3.h.<init> []
	at java.lang.Class.getConstructor0(Class.java:3395)
	at java.lang.Class.getConstructor(Class.java:2487)
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:677)
	... 29 more
```

### PR DESCRIPTION
**Pull request by mikehardy**
## Purpose / Description

this allows Fragment lifecycle save/restore to work seemlessly and that fixes crashes on Activity restarts

~~**NOTE THAT IF THIS STYLE IS OKAY - A FEW OTHER DIALOGS NEED FIXES IN SAME STYLE**~~

[edit: turns out this was the only easy one like this - so just one commit]

## Fixes

* Fixes #17381

## Approach

Used the approach mentioned here https://stackoverflow.com/a/51831137/9910298

- Stop providing params to constructor, so there is a default constructor as required by default Fragment factory
- Start providing params as a Bundle set in to Fragment.arguments via a static newInstance method
- Access all params via Fragment.arguments
- Handle optionally missing arguments with warnings+defaults

## How Has This Been Tested?

- Enable developer option Don't Keep Activities
- Go to Card Browser, open Actions Menu "Options"
- Background AnkiDroid, resume AnkiDroid --> crash without patch
- With patch check all toggles + background/foreground permutations

Everything seems to work

[browser-options-crashfix.webm](https://github.com/user-attachments/assets/d7d9441e-fd7a-41ee-af9f-79452ecf8a85)

## Learning (optional, can help others)

Now we don't just have Activity lifecycle problems, we have Fragment lifecycle problems. Great

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by mikehardy** [comment]
Repeating my note here - this PR will grow with more commits fixing other dialogs if this style is okay

NOTE THAT IF THIS STYLE IS OKAY - A FEW OTHER DIALOGS NEED FIXES IN SAME STYLE

**Review by BrayanDSO — APPROVED** [review]
Fully agreed with empty constructors for Fragments and passing stuff with arguments. Following the Android way of things is normally the most sane alternative.

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt [hunk 1]
```diff
@@ -80,4 +101,15 @@ class BrowserOptionsDialog(private val cardsOrNotes: CardsOrNotes, private val i
...
+
+    companion object {
+        fun newInstance(cardsOrNotes: CardsOrNotes, isTruncated: Boolean): BrowserOptionsDialog {
+            val args = Bundle()
+            args.putBoolean("cardsOrNotes", (cardsOrNotes == CardsOrNotes.CARDS))
+            args.putBoolean("isTruncated", isTruncated)
+            val fragment = BrowserOptionsDialog()
+            fragment.arguments = args
+            return fragment
+        }
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt:113]: More kotlinesque
```suggestion
        fun newInstance(cardsOrNotes: CardsOrNotes, isTruncated: Boolean): BrowserOptionsDialog {
            val args = bundleOf(
                "cardsOrNotes" to (cardsOrNotes == CardsOrNotes.CARDS),
                "isTruncated" to isTruncated
            )
            return BrowserOptionsDialog().apply {
                arguments = args
            }
        }
```

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt:113]: I always appreciate the Kotlin taste pointers, thanks

**Comment by mikehardy** [comment]
Okay, going to take that preliminary note of approval for the style, Kotlin-ify it, and try another Dialog Fragment or two

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt [hunk 2]
```diff
@@ -26,42 +26,64 @@ import android.widget.RadioButton
...
         val newTruncate = dialogView.findViewById<CheckBox>(R.id.truncate_checkbox).isChecked
 
-        if (newTruncate != isTruncated) {
+        if (newTruncate != getIsTruncated()) {
             viewModel.setTruncated(newTruncate)
         }
     }
 
+    private fun getCardsOrNotes(): CardsOrNotes {
+        val cardsOrNotesBoolean = arguments?.getBoolean("cardsOrNotes")
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt:56]: Oh, also please extract these key strings into constants

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt [hunk 3]
```diff
@@ -80,4 +102,16 @@ class BrowserOptionsDialog(private val cardsOrNotes: CardsOrNotes, private val i
             this.create()
         }
     }
+
+    companion object {
+        fun newInstance(cardsOrNotes: CardsOrNotes, isTruncated: Boolean): BrowserOptionsDialog {
+            val args = bundleOf(
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt:108]: I'd add in a `Timber.i` here

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt [hunk 4]
```diff
@@ -80,4 +102,16 @@ class BrowserOptionsDialog(private val cardsOrNotes: CardsOrNotes, private val i
             this.create()
         }
     }
+
+    companion object {
+        fun newInstance(cardsOrNotes: CardsOrNotes, isTruncated: Boolean): BrowserOptionsDialog {
```
Comment (lukstbit) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt:107]: You can write this more concise like:
```
fun newInstance(cardsOrNotes: CardsOrNotes, isTruncated: Boolean) =
    BrowserOptionsDialog().apply {
        arguments = bundleOf(...
```

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt [hunk 5]
```diff
@@ -26,42 +26,64 @@ import android.widget.RadioButton
...
+import androidx.core.os.bundleOf
 import androidx.fragment.app.activityViewModels
 import com.google.android.material.dialog.MaterialAlertDialogBuilder
 import com.ichi2.anki.R
 import com.ichi2.anki.browser.CardBrowserViewModel
 import com.ichi2.anki.model.CardsOrNotes
 import timber.log.Timber
 
-class BrowserOptionsDialog(private val cardsOrNotes: CardsOrNotes, private val isTruncated: Boolean) : AppCompatDialogFragment() {
+class BrowserOptionsDialog() : AppCompatDialogFragment() {
```
Comment (lukstbit) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt:37]: Also delete the (), they produce and IDE warning.

**Review by lukstbit — APPROVED** [review]
Yes, dialogs with constructor parameters that don't use a fragment factory should be refactored.

**Comment by mikehardy** [comment]
Turns out there was only one other DialogFragment with a problem like this (no default constructor) and it has a Factory but it must just not get installed correctly every time. I'm not going to add that commit here, I'll work it in a separate PR

So this is ready to go

I've adopted all the feedback to make this more Kotlin-y (and extract string constants) - thank you!

Three people approved but there were enough little changes from the feedback I think at least one other person should take a final look before merge so I am repinging the reviewers but hopefully (since it is a simple change) it's easy and done

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt [hunk 6]
```diff
@@ -26,21 +26,24 @@ import android.widget.RadioButton
...
 
     private val viewModel: CardBrowserViewModel by activityViewModels()
 
     private val positiveButtonClick = { _: DialogInterface, _: Int ->
-        @IdRes val selectedButtonId = dialogView.findViewById<RadioGroup>(R.id.select_browser_mode).checkedRadioButtonId
-        val newCardsOrNotes = if (selectedButtonId == R.id.select_cards_mode) CardsOrNotes.CARDS else CardsOrNotes.NOTES
+        @IdRes val selectedButtonId =
+            dialogView.findViewById<RadioGroup>(R.id.select_browser_mode).checkedRadioButtonId
+        val newCardsOrNotes =
+            if (selectedButtonId == R.id.select_cards_mode) CardsOrNotes.CARDS else CardsOrNotes.NOTES
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt:46]: Note: this is now just a spacing change

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt [hunk 7]
```diff
@@ -51,6 +54,25 @@ class BrowserOptionsDialog(private val cardsOrNotes: CardsOrNotes, private val i
         }
     }
 
+    private val cardsOrNotes by lazy {
+        when (arguments?.getBoolean("cardsOrNotes")) {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt:58]: Shouldn't this use the constant?

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt [hunk 8]
```diff
@@ -51,6 +54,25 @@ class BrowserOptionsDialog(private val cardsOrNotes: CardsOrNotes, private val i
...
+            null -> {
+                // Default case, and what we'll do if there were no arguments supplied
+                Timber.w("BrowserOptionsDialog instantiated without configuration.")
+                CardsOrNotes.CARDS
+            }
+        }
+    }
+
+    private val isTruncated by lazy {
+        arguments?.getBoolean("isTruncated") ?: run {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt:70]: ditto

**Review by david-allison — CHANGES_REQUESTED** [review]
Minor improvement with constants I believe, code is good

Although I stated that the styles of `getter` was inconsistent, I prefer them the way they are now.

The following looks ugly to me

```kotlin
    private val isTruncated by lazy {
        when (arguments?.getBoolean("isTruncated")) {
            true -> true
            false -> false
            null -> {
                Timber.w("BrowserOptionsDialog instantiated without configuration.")
                false
            }
        }
   
```

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt (hunk 7 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt:58]: 🤦  gah

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt (hunk 8 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt:70]: 🤦 🤦

**Review by david-allison — APPROVED** [review]
