### PR TITLE
Card Browser: "Search All Decks" button if no results

### LINKED ISSUE #5159: Alter CardBrowser search from context-menu intent to search in all decks
###### Reproduction Steps

1. Right click any text on the device
2. Select the "Card Browser" option to search for the text in AnkiDroid

###### Expected Result

All decks are searched and result is shown

###### Actual Result

Only the "current selected deck" is shown

Happening on the alphas from around 2018/11/28 at least, reported on mailing list by @anthropos888

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description
Allow a user to search all decks if there was no results for a search

This is makes the 'Card Browser' context menu item much more effective.

## Fixes
Fixes #5159 (I feel it's in a better manner, but your call).

## Approach
We use a snackbar: 
image

## How Has This Been Tested?

Tested on my device

⛔ Please reject this and ask me to add a few unit tests (in a direction of your choosing).

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5571122&bid=18267699)

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java [hunk 1]
```diff
@@ -1676,17 +1690,65 @@ public void onProgressUpdate(TaskData... values) {
...
+        }
     };
 
+    boolean hasSelectedAllDecks() {
+        Long lastDeckId = getLastDeckId();
+        return lastDeckId != null && lastDeckId == ALL_DECKS_ID;
+    }
+
+
+    void searchAllDecks() {
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java:1726]: Codacy Issue found: [Use explicit scoping instead of the default package private level](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5571122)

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java [hunk 2]
```diff
@@ -857,9 +865,15 @@ private void updatePreviewMenuItem() {
         if (mPreviewItem == null) {
             return;
         }
-        mPreviewItem.setVisible(getCards().size() > 0);
+        mPreviewItem.setVisible(getCardCount() > 0);
     }
 
+    /** Returns the number of cards that are visible on the screen */
+    int getCardCount() {
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java:872]: Codacy Issue found: [Use explicit scoping instead of the default package private level](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5571122)

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java [hunk 3]
```diff
@@ -1676,17 +1690,65 @@ public void onProgressUpdate(TaskData... values) {
...
+                            root,
+                            null);
+                } else {
+                    UIUtils.showSimpleSnackbar(CardBrowser.this, getSubtitleText(), true);
+                }
+            }
+        }
     };
 
+    boolean hasSelectedAllDecks() {
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java:1720]: Codacy Issue found: [Use explicit scoping instead of the default package private level](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5571122)

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java [hunk 4]
```diff
@@ -1676,17 +1690,65 @@ public void onProgressUpdate(TaskData... values) {
...
+        //all we need to do is select all decks
+        selectAllDecks();
+    }
+
+    /**
+     * Returns the current deck name, "All Decks" if all decks are selected, or "Unknown"
+     * Do not use this for any business logic, as this will return inconsistent data
+     * with the collection.
+     */
+    String getSelectedDeckNameForUi() {
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java:1736]: Codacy Issue found: [Use explicit scoping instead of the default package private level](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5571122)

**Comment by david-allison-1** [comment]
RE: Explicit scoping - these fix the synthetic accessor lint issues, but I'll make them public

**Comment by mikehardy** [comment]
I thought we killed synthetic accessor as a check? I'd rather have explicit scoping, if it's a tradeoff.

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java [hunk 5]
```diff
@@ -1699,11 +1701,54 @@ private void handleSearchResult() {
             Timber.i("CardBrowser:: Completed doInBackgroundSearchCards Successfully");
             updateList();
             if ((mSearchView != null) && !mSearchView.isIconified()) {
-                UIUtils.showSimpleSnackbar(CardBrowser.this, getSubtitleText(), true);
+                if (getCardCount() == 0 && !hasSelectedAllDecks()) {
+                    View root = CardBrowser.this.findViewById(R.id.root_layout);
+                    UIUtils.showSnackbar(CardBrowser.this,
+                            getString(R.string.card_browser_no_cards_in_deck, getSelectedDeckNameForUi()),
+                            LENGTH_INDEFINITE,
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java:1708]: I hesitate on this choice - is it occluding / hiding elements by being on top of them? If so the material guidelines used to state transient elements should never be permanent, and indefinite length is actually sort of new here. Maybe 2*LONG but not permanent? Or if it is not hiding anything (and actually, it may not be) then this is okay, but any new set of results or another search  should dismiss it

**Comment by mikehardy** [comment]
This is a great idea though, a much more useful user experience I agree

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java (hunk 5 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java:1708]: Today I learned, let's use `CardBrowser.SNACKBAR_DURATION` (8000)?

**Comment by david-allison-1** [comment]
> I thought we killed synthetic accessor as a check? I'd rather have explicit scoping, if it's a tradeoff.

Synthetic accessor (the lint check) has been removed, but still appears in my IDE, and I have no issue with following the guideline if it's reasonable, as there is a perf gain to get.

But, the Codacy "method is package private" is triggered if the suggested lint refactoring is taken. In these cases, I'm fine with public methods on the business logic side of things.

**Comment by mikehardy** [comment]
As a tooling idea, I believe if we were to use a lint.xml and reference it in gradle instead of the in-gradle config, then AndroidStudio would pick it up and we would have perfect consistency between lint-in-Travis-CI-lintDebug and IDE-while-editing

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java (hunk 5 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java:1708]: 8000 would certainly be transient so wouldn't ever really have a problem and then you won't have to worry about dismissing. Still might be strange if they do any other search and the snackbar stays there, but they'll be racing an 8 second timer at that point. Possible some people could win but not by much. 8's fine by me

**Comment by david-allison-1** [comment]
@mikehardy Any preference on adding unit tests?

**Comment by mikehardy** [comment]
implementor's choice, it's marked pending merge already I'll merge it as is. Might focus elsewhere if you're sure this works in your testing

**Comment by david-allison-1** [comment]
Putting my quality hat on, I'd have liked it to be tested, but there's a few hundred other issues to get around to. Let's merge.
