### PR TITLE
Fixed Cloze Card Preview

### LINKED ISSUE #9005: [Bug] Cannot view cloze note with many cards in the editing screen
###### Reproduction Steps

1. Click on a card
2. Click the view button 
Screenshot_2021-05-29-17-09-09-26_a9eef3a2a561b80d5c76daebd0f9a14c

###### Expected Result
The card is shown

###### Actual Result
Cannot view the card and the screen reads "A card could not be generated"
Screenshot_2021-05-29-17-02-29-48

###### Debug info
AnkiDroid Version = 2.15.1

Android Version = 10

Manufacturer = Realme

Model = RMX1853

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; RMX1853 Build/QKQ1.190918.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.77 Mobile Safari/537.36

ACRA UUID = fe9d70b1-b495-4a7d-b77f-3842fa3e875b

Scheduler = std

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by prateek-singh-3212**
## Purpose / Description
 This PR Fixes the error which occur while opening the card which is having cloze text from card browser. 

## Fixes
 Fixes #9005

## Approach
I Changed the ordinal to 0 for all the cloze cards.

## How Has This Been Tested?

Tested on Samsung Galaxy M51, android 11 (Samsung One UI 3.1)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by prateek-singh-3212** [comment]
This PR fixes the error which we are encountering. But I have seen new type of card loading issue while testing. 
I am attaching the video of that issue.


https://user-images.githubusercontent.com/76490368/120347935-56566280-c31a-11eb-82f4-c83068adc83a.mp4

In this I am not able to see the cloze for any card except 1st card i.e It is always showing cloze in first card only.
I have tried to solve this but I am unable to find out how anki is detecting that display 'cloze icon while rewieing 2nd card' ? anyone Please tell me . I hope that i have crearly explained the issue. If not then please tell me.

**Comment by ShridharGoel** [comment]
@prateek-singh-3212 Currently AnkiDroid only shows preview for the first card. Refer: #7941.
This is the reason because of which only one cloze symbol is visible.

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java [hunk 1]
```diff
@@ -280,6 +280,9 @@ protected Card getCard(Collection col, long cardListIndex) {
             n.setField(i, fieldNames.get(i));
         }
         try {
+            if (model.isCloze()) {
```
Comment (ShridharGoel) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java:283]: A comment can be added here explaining the issue because of which this has been done.

Comment (ShridharGoel) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java:283]: Also, this can be moved outside the `try` block.

**Comment by ShridharGoel** [comment]
@prateek-singh-3212 Are you planning to add an unit test for this?

**Comment by david-allison-1** [comment]
This is from the previewer (card browser - now editor), rather than from the note editor directly. Two similar, but unrelated issues

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java (hunk 1 above)
Comment (prateek-singh-3212) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java:283]: Yes, Sure

**Comment by prateek-singh-3212** [comment]
> @prateek-singh-3212 Are you planning to add an unit test for this?

Yes, I am thinking that unit test will be great for this issue.

**Comment by david-allison-1** [comment]
Tested manually and it's good. I'd like to see this in 2.15.3 (with the caveat that the change to get this fully working will be in 2.15.4).

Happy to see a unit test in a separate PR to allow this to get in, or a unit test here if you have time today.

**Review by david-allison-1 — APPROVED** [review]
See comment: unit test to follow up would be great, but would like to see this in 2.15.3 if possible. Happy to see a test here, or as a follow up PR if this gets merged before a test is added

(Added the comment so an issue can be created directly from it)

**Comment by prateek-singh-3212** [comment]
I have implemented changes as suggested by @ShridharGoel .

-  Implemented if statement outside the try block.
- Added Comment which describes the reason to implement this.

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java [hunk 2]
```diff
@@ -279,6 +279,15 @@ protected Card getCard(Collection col, long cardListIndex) {
         for (int i = 0; i < fieldNames.size() && i < n.getFields().length; i++) {
             n.setField(i, fieldNames.get(i));
         }
+
+        /**
+         * This is used when the card type is cloze. We have to set the ordinal to 0 as we are
+         * setting the 0 for all cards of a particular note type in are database.
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java:285]: Also sorry for the review

Comment the why, not the what. Maybe move the first sentence to the header of the method

```
This method generates a note from a sample model, or fails if invalid. It does not currently have knowledge of field content

A cloze uses the same model. Its content (not provided in params) determines validity of an ordinal
```

**Review by david-allison-1 — CHANGES_REQUESTED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java (hunk 2 above)
Comment (prateek-singh-3212) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java:285]: Done

**Review by david-allison-1 — APPROVED** [review]
A thing of beauty!

**Review by mikehardy — APPROVED** [review]
Just in time for 2.15.3 :-)
