### PR TITLE
Use "Undo" instead of "Undo %s" for the item of "Undo" if there is no string of undone target

### LINKED ISSUE #12853: The string of ”Undo” is displayed unnaturally in Japanese and some languages
###### Reproduction Steps

1. "Settings" ->"Appearance" -> "App bar buttons" -> "Undo" -> "Menu only"
2. Tap a deck on Deck picker screen
3. Tap the three dot icon on Reviewer screen, and check the string of the item of "Undo" 
image

4. "Settings"->"Language"->"日本語" (Japanese)
5. Tap the three dot icon on Reviewer screen, and check the string of the item of "Undo" again

###### Expected Result
The following Japanese string, `元に戻す`, translated from `Undo` is used.
https://github.com/ankidroid/Anki-Android/blob/9ac9e6e3047184d79a4044129254f2ee96a4f8bc/AnkiDroid/src/main/res/values/01-core.xml#L76
https://github.com/ankidroid/Anki-Android/blob/9ac9e6e3047184d79a4044129254f2ee96a4f8bc/AnkiDroid/src/main/res/values-ja/01-core.xml#L92

###### Actual Result
The following Japanese string, `を元に戻す`,  translated from `Undo %s` is used.
https://github.com/ankidroid/Anki-Android/blob/9ac9e6e3047184d79a4044129254f2ee96a4f8bc/AnkiDroid/src/main/res/values/01-core.xml#L74
https://github.com/ankidroid/Anki-Android/blob/9ac9e6e3047184d79a4044129254f2ee96a4f8bc/AnkiDroid/src/main/res/values-ja/01-core.xml#L90

image
Unlike in many languages such as English, "Undo" and _the "Undo" part of "Undo %s"_ are translated differently in Japanese. There is a postpositional particle ("を") for the object, but the object itself is missing on the "Undo" item in Japanese above, which is clearly unnatural.

###### Debug info
AnkiDroid Version = 2.16alpha89

Android Version = 11

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36

ACRA UUID = 7fa108ed-8b79-4927-9c5a-09dd92f52b04

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by snowtimeglass**
## Purpose / Description
Use just "Undo" instead of "Undo %s" for the item of "Undo" if there is no string of undone target.
image
image

https://github.com/ankidroid/Anki-Android/blob/9ac9e6e3047184d79a4044129254f2ee96a4f8bc/AnkiDroid/src/main/res/values/01-core.xml#L76
https://github.com/ankidroid/Anki-Android/blob/9ac9e6e3047184d79a4044129254f2ee96a4f8bc/AnkiDroid/src/main/res/values-ja/01-core.xml#L92
https://github.com/ankidroid/Anki-Android/blob/9ac9e6e3047184d79a4044129254f2ee96a4f8bc/AnkiDroid/src/main/res/values/01-core.xml#L74
https://github.com/ankidroid/Anki-Android/blob/9ac9e6e3047184d79a4044129254f2ee96a4f8bc/AnkiDroid/src/main/res/values-ja/01-core.xml#L90
## Fixes
Fixes #12853

## Approach
Separate cases by presence/absence of string of undone target on Reviewer.kt

## How Has This Been Tested?
Checked on a physical device
image

image

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt [hunk 1]
```diff
@@ -748,7 +748,11 @@ open class Reviewer : AbstractFlashcardViewer() {
         undoIcon.setEnabled(undoEnabled).iconAlpha = alphaUndo
         undoIcon.actionView!!.isEnabled = undoEnabled
         if (colIsOpen()) { // Required mostly because there are tests where `col` is null
-            undoIcon.title = resources.getString(R.string.studyoptions_congrats_undo, col.undoName(resources))
+            if (col.undoName(resources) !="") {
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt:751]: There are some lint errors. 

And I believe that `if (col.undoAvailable())` can be used

And a comment on code to why this is necessary would be nice

**Review by BrayanDSO — CHANGES_REQUESTED** [review]
The japanese I learned on Anki now is helping me solve bugs on Anki. There are some odd circles on life indeed

**Comment by snowtimeglass** [comment]
Glad to hear you have learned Japanese :+1: 
What a nice circle. It probably circulates neither by chance nor by destiny but by your good will. It makes AnkiDroid and the world better, thanks.

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt (hunk 1 above)
Comment (snowtimeglass) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt]: Thanks for your advice! I've rewritten them.

**Review by BrayanDSO — APPROVED** [review]
LGTM

**Review by BrayanDSO — CHANGES_REQUESTED** [review]
Oops. There are still some lint errors. ktlintFormat should have solved these

**Comment by snowtimeglass** [comment]
Thanks for pointing it out. Sorry, I'm still unfamiliar with the procedure. I fixed some lint errors just now.

**Review by BrayanDSO — APPROVED** [review]

**Review by lukstbit — APPROVED** [review]
There's no complete circle for me as I don't learn japanese with Anki, but changes LGTM. Thanks!
