### PR TITLE
CropException fix

### LINKED ISSUE #12768: [Bug] Report generated when cropping image and pressed back
###### Reproduction Steps

1.  open a collection
2. edit note
3.  add a image
4. select image from gallery
5. press crop(do nothing after that)
6. press back

###### Expected Result
should get back to edit image section

###### Actual Result
crash report is generated

###### Debug info
AnkiDroid Version = 2.16alpha89

Android Version = 12

Manufacturer = Google

Model = sdk_gphone64_x86_64

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 12; sdk_gphone64_x86_64 Build/SE1A.220630.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.114 Mobile Safari/537.36

ACRA UUID = 246da304-f39d-4cd2-9fc7-d1bc0bd83ad0

New schema = true

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by criticalAY**
## Pull Request template
Preventing the report generation due to the crop Exception that was generated when back was pressed.

## Purpose / Description
This PR will fix the report generation issue that was arising due to Canhub's `CropException` . The report was generated when we used to enter the crop image option and pressed back without doing anything. This issue was reported by some user and I found it on ACRA and then reproduced it, also the same was reported by other users as well. The reports are of no action to take on as the Exception is put by Canhub Dev. and can be countered by catching it, they have knowingly put it there but it is of no relevance to us

## Fixes
Fixes #12768

## How Has This Been Tested?
After committing the changes the exception is no more reported

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc) : - Can be reproduced by going through the issue mentioned above.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by mikehardy — CHANGES_REQUESTED** [review]
This could be correct but you've deleted the entire PR template.
I want to know what the motivation is for this PR (a brief synopsis of the issue perhaps)
I want to know *why* this is the correct fix
I want to know *how* you test this to know that this is the correct fix

Something like "Crop exceptions were generating lots of exception reports in ACRA and it seemed most of them were not actionable"

Along with "It turns out that if you do XYZ then you get a CropException because of ABC, but there is nothing we can do about it. However if you do JKL it is a real exception of type FOO so we still want to pay attention to those"

Along with "So based on that, this PR just logs exceptions of type CropException but for the rest we still send a report via ACRA"

**Comment by criticalAY** [comment]
> This could be correct but you've deleted the entire PR template. I want to know what the motivation is for this PR (a brief synopsis of the issue perhaps) I want to know _why_ this is the correct fix I want to know _how_ you test this to know that this is the correct fix
> 
> Something like "Crop exceptions were generating lots of exception reports in ACRA and it seemed most of them were not actionable"
> 
> Along with "It turns out that if you do XYZ then you get a CropException because of ABC, but there is nothing we can do about it. However if you do JKL it is a real exception of type FOO so we still want to pay attention to those"
> 
> Along with "So based on that, this PR just logs exceptions of type CropException but for the rest we still send a report via ACRA"

Will do that

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt [hunk 1]
```diff
@@ -212,7 +212,11 @@ class BasicImageFieldController : FieldControllerBase(), IFieldController {
                 // cropImage can give us more information. Not sure it is actionable so for now just log it.
                 val error: String = cropResult.error?.toString() ?: "Error info not available"
                 Timber.w(error, "cropImage threw an error")
-                CrashReportService.sendExceptionReport(error, "cropImage threw an error")
+                if ("com.canhub.cropper.CropException" in error) {
+                    Timber.i("CropException caught")
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt:216]: I think we could at least log the exception with the Timber message, that way since it is 'i' level it will show up even in release mode builds, and if someone is affected by this they can generate a manual exception report that *should* still have the exception in it from logcat, allowing us to still investigate in depth with an affected user in case we are incorrect in the analysis that these do not matter

```suggestion
                    Timber.i("CropException caught, seemingly nothing to do", error)
```

**Review by mikehardy — CHANGES_REQUESTED** [review]
Huh - that's a very terse exchange on the upstream repo: https://github.com/CanHub/Android-Image-Cropper/issues/527 - but ... it does not seem like it is useful for us to do anything with the exception at the moment.

I proposed a tiny change where we just also log the exception in the Timber call, just in case

What do you think?

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt (hunk 1 above)
Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt:216]: ok will amend it

**Comment by criticalAY** [comment]
> Huh - that's a very terse exchange on the upstream repo: [CanHub/Android-Image-Cropper#527](https://github.com/CanHub/Android-Image-Cropper/issues/527) - but ... it does not seem like it is useful for us to do anything with the exception at the moment.
> 
> I proposed a tiny change where we just also log the exception in the Timber call, just in case
> 
> What do you think?

I am also putting a comment there so when in future Canhub gets rid of this issue or finds a way to handle it correctly then we can remove this particular condition

**Comment by mikehardy** [comment]
This is a small enough change it can work as a test bed for git commands.
Let's get this thing rebased and squashed down to a single clean commit so we can start having clean commit histories on your PRs.

There are GUIs that do this, but I use git from the command line. Here are the commands I would run:

```bash
git rebase -i HEAD~3   # "hey git, let's interactively rebase the last three commits"
# this will open your configured text editor, probably vi(?) with "pick" in front of each commit
# delete pick from the second and third commits and put "s" instead, for "squash"
# save and exit the editor, now git will try to follow your instructions
# you should get a commit message edit window where you are prompted to combine all the messages into one, do that, save+exit
git push --force-with-lease
```

In this case since it's just a squash of 3 commits into 1 it's really easy, mostly just asking git to do it then editing the message, then pushing the result back out

Try it out and let's see how it looks.

**Review by mikehardy — APPROVED** [review]
This looks great to me, and I've looked into the upstream repo and everything.
Only pausing now (but with approval on the code) to see if we can get a rebased version of the commits for practice

**Comment by criticalAY** [comment]
I think I messed up the rebasing :(

**Comment by criticalAY** [comment]
@mikehardy finally did it, Thanks!

**Review by mikehardy — COMMENTED** [review]
My only quibble now is that the commit message itself contains no useful information, it says

"squash merge commits" when it should say something like:

"stop logging exception reports for CropExceptions" as a title with a message internally like "They were logged previously for analysis to see if they were useful. They do not appear useful now that we have seen them. Logging them to ACRA just seems like clutter"

This can be done with a `git rebase -i HEAD~1` and the "reword" interactive rebase command. It will bring up an editor where you can rewrite the commit title + message to whatever you want.

Then you have to force push again of course. But you'll be good at it after this! It's a really useful skill

**Comment by criticalAY** [comment]
Thanks! and done

**Review by mikehardy — APPROVED** [review]
A thing of beauty :-)

**Review by lukstbit — CHANGES_REQUESTED** [review]
To answer your question from Discord, this is a bug I introduced when I migrated the library to use the new activity result APIs :(. Your code works, but it will swallow all exceptions related to cropping not just the one thrown when user hits back. So I'm proposing these changes:

```
// condition can be removed if #12768 get fixed by Canhub
if (cropResult.error is CropException.Cancellation) {
     Timber.i("Crop cancelled by user, seemingly nothing to do")
} else {
      CrashReportService.sendExceptionReport(error, "cropImage threw an error")
}
```

This way we only ignore the Cancellation exception(user hits back), but we send a report for the other exceptions(like FailedToDecodeImage or FailedToLoadBitmap).

**Comment by mikehardy** [comment]
> CropException.Cancellation

This is even better, I did not realize there were sub-exceptions / finer ways to differentiate. I like it

**Comment by criticalAY** [comment]
> (cropResult.error is CropException.Cancellation)

Thanks for responding, I caught all the cropping exceptions true and this can further be simplified thankyou for pointing that out

**Comment by criticalAY** [comment]
> > CropException.Cancellation
> 
> This is even better, I did not realize there were sub-exceptions / finer ways to differentiate. I like it

I didn't know that I can use the crop result itself to refine it, I tried though but wasn't able to do that and Luksbit suggested the exact thing. Kudos to him :)

**Review by lukstbit — APPROVED** [review]
Nice!
