### PR TITLE
Instrumentation tests for click on counts layout in DeckPicker

### LINKED ISSUE #9056: Regression tests: 2.15.3 crash on startup
2.15.4 is rolling out now and is already available here @burbilog please confirm it works for you? It should - if not there is something else going on: https://github.com/ankidroid/Anki-Android/releases/tag/v2.15.4

Action plan for 2.15.5 on this one:

- There must be a test that fails on 2.15.3 (and it should fail on master as well?) via starting the study options fragment from deck picker via the review counts (to prove this can't happen again - this has been problematic in the past)
- then fix the navigation drawer preference PR on master and enable the test
- merge that fix PR
- cherry-pick the navigation drawer gesture preference back to release-2.15 and the fix PR for it as well

Sound about right @david-allison-1 ?

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/issues/9052#issuecomment-853378139_

### PR DESCRIPTION
**Pull request by ShridharGoel**
Fixes #9056

### CODE REVIEW

**Comment by ShridharGoel** [comment]
Test failed currently as expected. Once #9057 is merged, it will pass.

**Comment by ShridharGoel** [comment]
Test failed currently as expected. Once #9057 is merged, it will pass.

File: AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+import static org.junit.Assert.assertTrue;
+
+public class DeckPickerTest {
+
+   @Rule
+   public ActivityScenarioRule<DeckPicker> mActivityRule = new ActivityScenarioRule<>(DeckPicker.class);
+
+   @Test
+   public void checkIfClickOnCountsLayoutOpensStudyOptions() {
+      onView(withId(R.id.counts_layout)).perform(click());
```
Comment (david-allison-1) [inline AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java:22]: I think this will fail if run on a tablet

**Comment by ShridharGoel** [comment]
This requires changes currently, hence marking as draft.

File: AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java (hunk 1 above)
Comment (ShridharGoel) [reply AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java]: Updated.

File: AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java [hunk 2]
```diff
@@ -0,0 +1,100 @@
...
+
+        createDeckWithCard();
+
+        // Check if currently open Fragment is StudyOptionsFragment
+        onView(withId(R.id.studyoptions_fragment)).check(matches(isDisplayed()));
+    }
+
+    public void createDeckWithCard() {
+        // Create a new deck
+        onView(withId(R.id.fab_main)).perform(click());
```
Comment (david-allison-1) [inline AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java:83]: If I'm understanding this correctly, this will perform the action on a physical device which is connected.

There was a PR I discussed fixing this with a custom test runner (around a year ago), otherwise we should recode this, and at worst case: relegate it to running on emulators

Comment (ShridharGoel) [reply AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java:83]: I had tested this on emulators (both mobile and tablet) and it had worked fine. Did not check the test on a physical device though.

Comment (ShridharGoel) [reply AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java:83]: Verified on real device as well, the test ran properly.

Comment (ShridharGoel) [reply AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java:83]: Verified on physical device as well, the test ran properly.

Comment (david-allison-1) [reply AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java:83]: The issue is that the test will create decks on a physical device, which is not what a user would want. Is this not happening?

Comment (ShridharGoel) [reply AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java:83]: Yes, that will happen. So, should we delete the newly created deck through the test itself?

Comment (david-allison-1) [reply AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java:83]: The easiest thing to do is to not execute the test on a physical device:

* if it's an emulator create a deck
* If not, `assumeTrue` that it already has a deck, 

https://github.com/ankidroid/Anki-Android/blob/d9d30108b84df843e90bde2cebf7167586624fd7/AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.java#L146-L154

Otherwise, you'll still need to ensure that deleting the deck isn't a destructive action (asserts along the way that the deck didn't exist before the test)

Comment (david-allison-1) [reply AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java:83]: We do need a TestRunner which can run instrumentation tests on a device without affecting the collection. I'll add in an issue for this now. Arthur & I had a quick discussion about this on a PR around a year ago, but no progress was made past the discussion

Comment (mikehardy) [reply AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java:83]: > The easiest thing to do is to not execute the test on a physical device:

I think this is the best path forward for this one so we can close it out for now - check for emulator, only do collection manipulation on emulator

Comment (ShridharGoel) [reply AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java:90]: Updated.

Comment (ShridharGoel) [reply AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java:90]: Updated.

Comment (mikehardy) [reply AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java:90]: The `assumeTrue()` test for `generic` fingerprint seem good to me! thanks

**Comment by mikehardy** [comment]
I will pull this locally and check it - I think it was the last item to check for 2.15.5, if it's working I'll start picking remaining items to branch and prepare for that release. Also we don't have CI support for emulator tests right now (sadly) so I can verify it's all good locally

File: AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java [hunk 3]
```diff
@@ -0,0 +1,107 @@
...
+    public ActivityScenarioRule<DeckPicker> mActivityRule = new ActivityScenarioRule<>(DeckPicker.class);
+
+    @Rule
+    public GrantPermissionRule mRuntimePermissionRule =
+            GrantPermissionRule.grant(Manifest.permission.WRITE_EXTERNAL_STORAGE);
+
+    @Test
+    public void checkIfClickOnCountsLayoutOpensStudyOptionsOnMobile() {
+        // Run the test only on emulator.
+        assumeTrue(Build.FINGERPRINT.contains("generic"));
```
Comment (david-allison-1) [inline AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java:58]: `InstrumentedTest.isEmulator()` is better here - might want to make it `public static`

**Comment by mikehardy** [comment]
I ran `./gradlew jacocoTestReport` on  the gamut of API21-API30 phone emulators plus a Pixel C API30 tablet emulator

It fails on most of them, I think it's a timing thing - when I see the test in action it is quite involved! I actually like that, it exercises quite a bit of functionality on the emulator, but - it appears that the emulator tests are somehow running in parallel so other tests are messing with the activity state (starting new activities etc) while this one is trying to run.

That's vague because I haven't investigated it further, but this one needs another look with `./gradlew jacocoAndroidTestReport` on the command line being one success criteria that is currently failng

This is *not* an easy instrumented test, I'm excited to see it go in and not surprised (now that I see what it's doing) that it still needs some work to shape it up

**Comment by ShridharGoel** [comment]
@mikehardy This test is dependent on the crash fix related to study options. I have rebased over master now, please check it again.

**Comment by mikehardy** [comment]
Hmm - the emulator tests are working again (in the sense that the emulator itself is no longer crashing on startup, so tests *can* run) but this test still has problems.

**Comment by mikehardy** [comment]
I re-ran the emulator test. This test definitely does not work as is

```

com.ichi2.anki.DeckPickerTest > checkIfClickOnCountsLayoutOpensStudyOptionsOnMobile[TestingAVD(AVD) - 11] FAILED 
	java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
```

**Comment by mikehardy** [comment]
I pulled this branch and fixed it so I could get this test in
- with the new test dependency bump, we need to force resolve androidx.test:core to 1.4.0 because of a google issue I linked in the build file
- the test was not stable for re-runs on the same device so it made it work on a unique deck each run
- the test needed to sleep just a bit while the study options fragment started, or it was racy and sometimes lost / flaked

This looks good to go, to me now

**Review by mikehardy — APPROVED** [review]
I reviewed this and fixed it up a bit myself so obviously I approve, marked for a second look though

**Comment by mikehardy** [comment]
Note when picking to release-2.15: the dependency resolutionStrategy should likely be removed as the dependencies were not bumped to the versions that had compatibility problems on release-2.15

File: AnkiDroid/build.gradle [hunk 4]
```diff
@@ -245,6 +245,7 @@ dependencies {
     configurations.all {
         resolutionStrategy {
             force 'org.jetbrains:annotations:21.0.1'
+            force 'androidx.test:core:1.4.0' // Pending fix here: https://issuetracker.google.com/issues/189353863
```
Comment (mikehardy) [inline AnkiDroid/build.gradle:248]: to be specific on review, without this the fragment-testing library loads the 1.3.0 version of androidx.test:core which then depends on android.test:monitor 1.3.0 which does not have a method signature that espresso's  new version depends on (they are all cross-dependent and released as a batch). Google was just waiting on official versions of everything to be released and they were released just a couple days ago. This should be very temporary.

File: AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java [hunk 5]
```diff
@@ -0,0 +1,122 @@
...
+
+        // For mobile. If it is not a mobile, then test will be ignored.
+        assumeTrue(!isScreenSw600dp());
+
+        String testString = System.currentTimeMillis() + "";
+        createDeckWithCard(testString);
+
+        // Go to RecyclerView item having "Test Deck" and click on the counts layout
+        onView(withId(R.id.files)).perform(RecyclerViewActions.actionOnItem(hasDescendant(withText("TestDeck" + testString)), clickChildViewWithId(R.id.counts_layout)));
+        sleep(1000);
```
Comment (mikehardy) [inline AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java:70]: without this, the studyoptions fragment sometimes loses the "load and become active" race vs the assertion below. It actually won it some times so sleeping a full second is generous. This should be quite stable

Comment (david-allison-1) [reply AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java:70]: Could you move this comment to a code comment

File: AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java [hunk 6]
```diff
@@ -0,0 +1,122 @@
...
+        // Check if currently open Activity is StudyOptionsActivity
+        Activity activity = getActivityInstance();
+        boolean b = (activity instanceof StudyOptionsActivity);
+        assertTrue(b);
```
Comment (david-allison-1) [inline AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java:74]: Written in the box, needs validation
```java
    assertThat(getActivityInstance(), instanceOf(StudyOptionsActivity.class))
```

**Review by david-allison-1 — COMMENTED** [review]
Two minor comments, then LGTM, merge at will

**Comment by mikehardy** [comment]
good thoughts both thanks - will ingest + re-push then merge pending CI

File: AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java (hunk 6 above)
Comment (mikehardy) [reply AnkiDroid/src/androidTest/java/com/ichi2/anki/DeckPickerTest.java]: other than missing a trailing semi-colon you have unlocked the "writes correct code in html textareas" achievement

**Comment by mikehardy** [comment]
@ShridharGoel this was really close to working - only needed a couple tiny tweaks for merge, and now it's in.  It should really help us keep a problematic area from breaking again in the future and will make me confident in releasing 2.15.5 with the full-screen navigation drawer change. Thanks a lot for making this

**Comment by david-allison-1** [comment]
```
com.ichi2.anki.DeckPickerTest > checkIfClickOnCountsLayoutOpensStudyOptionsOnMobile[TestingAVD(AVD) - 11] FAILED 
	androidx.test.espresso.base.RootViewPicker$RootViewWithoutFocusException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root:
	Root{application-window-token=android.view.ViewRootImpl$W@2ed062a, window-token=android.view.ViewRootImpl$W@2ed062a, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION fmt=RGBA_8888 wanim=0x10302fe
```

**Comment by mikehardy** [comment]
Yeah - I've actually been doing nothing but working through androidTest / study options chunder the last few hours, they're flaky on Android 5/5.1/7/7.1/8 right now plus what you saw. I have some fixes coming.

Oh, it also just crashes on a tablet on first run, cf #9204 :weary:

**Comment by ShridharGoel** [comment]
@mikehardy Thanks for updating this.
