### PR TITLE
NoteEditor: Allow Exit before collection load

### LINKED ISSUE #6158: Note Editor - Crash on Back Pressed before Collection Loaded
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/64b68d49-b295-4363-8bc8-002eb9d7ee55

AnkiDroid 2.10 (and earlier, judging from the code)

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.widget.AdapterView.getSelectedItemPosition()' on a null object reference
at com.ichi2.anki.NoteEditor.getCurrentlySelectedModel(NoteEditor.java:1)
at com.ichi2.anki.NoteEditor.hasUnsavedChanges(NoteEditor.java:2)
at com.ichi2.anki.NoteEditor.closeCardEditorWithCheck(NoteEditor.java:1)
at com.ichi2.anki.NoteEditor.onBackPressed(NoteEditor.java:2)
at android.app.Activity.onKeyUp(Activity.java:2782)
at com.ichi2.anki.NoteEditor.onKeyUp(NoteEditor.java:11)
at android.view.KeyEvent.dispatch(KeyEvent.java:2707)
at androidx.core.view.KeyEventDispatcher.activitySuperDispatchKeyEventPre28(KeyEventDispatcher.java:11)
at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:4)
at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:3)
at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:4)
at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:1)
at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:2)
at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:322)
at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4543)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4514)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3969)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4022)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3988)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3996)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3969)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4022)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3988)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4117)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3996)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4174)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3969)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4022)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3988)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3996)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3969)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4022)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3988)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4150)
at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4311)
at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2377)
at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1973)
at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1964)
at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2354)
at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:323)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:6316)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
```

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description
Fix NullPointerException if back is pressed before the collection is loaded

## Fixes
Fixes #6158 

## Approach
Don't crash

## How Has This Been Tested?
TDD: Red, Green, Commit, Push

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

File: AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.java [hunk 1]
```diff
@@ -120,6 +121,13 @@ public void clozeNoteWithClozeInWrongFieldDoesNotSave() {
         assertThat(getCardCount(), is(initialCards));
     }
 
+    @Test
+    public void verifyStartupAndCloseWithNoCollectionDoesNotCrash() {
```
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.java:125]: Codacy Issue found: [JUnit tests should include assert() or fail()](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5517275)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/NullCollectionNoteEditor.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5517275&bid=18077996)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/NullCollectionNoteEditor.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5517275&bid=18077996)

**Comment by mikehardy** [comment]
@david-allison-1 unrelated CI hiccup. Re-kicked it - are you able to do that on travis? Have you tried? I anticipate it will go green and I'll merge + pick though

**Comment by david-allison-1** [comment]
@mikehardy Haven't tried. Are you comfortable with the organisation access permission?

image

**Comment by mikehardy** [comment]
Yes, I'm comforted by the read-only-ness, and you wouldn't believe the amount of horsepower they contribute for us - I feel they are benevolent:
https://travis-ci.org/github/ankidroid?tab=insights (~40,000mins/mo)
https://travis-ci.com/github/mikehardy?tab=insights (~5-10,000mins/mo)
