### PR TITLE
Reload Note.model from db when returning to NoteEditor from CardTemplateEditor

### LINKED ISSUE #5011: State handling crash between card browser / note editor / template editor
I've seen this show up via ACRA, and the google play console release robot army caught it with video this time so I could figure it out.

###### Reproduction Steps

1. Open the card browser (it's empty in their tests, and they play with searches sometimes but the search was cleared)
2. Click + to add a card, enter text in front and back, template should be Basic
3. click the button bar that says "Card 1" to open the template editor
4. Click the options menu and select add to add a Card to the template, and you can mess with the template or not, but don't save - preview or not but don't save - then click the back button and agree it's okay to lose your progress
5. The Card button bar should say "Cards: Card 1 Card 2" now, but you never saved the second template
6. Click save to add the card, then click back to go back to the browser and it should crash with a JSONException string out of bounds

###### Expected Result

If you don't save the template the unsaved work should go away, you should have only Card 1 and the browser should work fine

###### Actual Result

Crash. I can reproduce this locally.

https://play.google.com/apps/publish/?account=5338425030304417978#PreLaunchReportPlace:p=com.ichi2.anki&appid=4973711737547064258&plrtab=CRASH&plrvc=20900140

FATAL EXCEPTION: AsyncTask #4
Process: com.ichi2.anki, PID: 12740
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:353)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.RuntimeException: org.json.JSONException: Index 1 out of range [0..1)
	at com.ichi2.libanki.Card.template(Card.java:342)
	at com.ichi2.libanki.Card._getQA(Card.java:290)
	at com.ichi2.anki.CardBrowser.updateSearchItemQA(CardBrowser.java:1164)
	at com.ichi2.async.DeckTask.doInBackgroundSearchCards(DeckTask.java:818)
	at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:262)
	at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:69)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more
Caused by: org.json.JSONException: Index 1 out of range [0..1)
	at org.json.JSONArray.get(JSONArray.java:293)
	at org.json.JSONArray.getJSONObject(JSONArray.java:521)
	at com.ichi2.libanki.Card.template(Card.java:337)
	... 11 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.get(ArrayList.java:437)
	at org.json.JSONArray.get(JSONArray.java:287)
	... 13 more

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

### PR DESCRIPTION
**Pull request by mikehardy**
## Purpose / Description
Fix a crash where CardTemplateEditor corrupts Note.model.templates leaving a reference to a non-existent template in the Note

## Fixes
#5011 

## Approach

Commit 1 triggers database integrity check with next build because this bug generated persistent corruption that integrity check does fix

Commit 2 adds Logging and ACRA send if integrity check finds problems so we can track that. Only the first 10 (if there are that many) so it's not overwhelming amounts of data to transmit though (just in case)

Commit 3 is the real fix:
CardTemplateEditor edits the model in the database directly, persisting speculative edits even before user clicks save. If user discards a template addition or subtraction, CardTemplateEditor saves a pre-edit backup copy of the model before returning.

Problem is the model.templates state bleeds into Notes.model.templates somehow, so the fix is that when NoteEditor gets the control back from CardTemplateEditor it NoteEditor calls a new Note.reloadModel() hook to reload Note.model from the database directly, where CardTemplateEditor does always leave the correct state.

## How Has This Been Tested?

Emulators, lots of clicking around...

### CODE REVIEW

**Comment by mikehardy** [comment]
Once this looks good to you as an approach, I'll forward port to 2.9 - otherwise I'll rework till it's good

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java [hunk 1]
```diff
@@ -1065,6 +1068,9 @@ else if (fieldEditText.hasFocus()) {
                 if (resultCode == RESULT_OK) {
                     mReloadRequired = true;
                 }
+                // rebuild the model post-template-edit so we get the correct number of cards
+                Timber.d("onActivityResult() template edit - reloading model");
+                mEditorNote.reloadModel();
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java]: This is the fix. Reload the model from database every time.

File: AnkiDroid/src/main/java/com/ichi2/libanki/Note.java [hunk 2]
```diff
@@ -113,6 +116,10 @@ public void load() {
         }
     }
 
+    public void reloadModel() {
+        mModel = mCol.getModels().get(mMid);
+    }
+
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Note.java]: This is a new hook the fix relies on. That's the whole fix

File: AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java [hunk 3]
```diff
@@ -1509,6 +1509,17 @@ public long fixIntegrity() {
         // if any problems were found, force a full sync
         if (problems.size() > 0) {
             modSchemaNoCheck();
+
+            // Let's track database corruption problems - AcraLimiter should quench it if it's a torrent
+            // We don't want a data-usage disaster though, so limit to 10 items of corruption?
+            String additionalInfo = "";
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java]: Can you please refactor this out into a separate function?

Comment (timrae) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java]: > what do you think?

Nah... For libanki I always lean towards making the code look as similar to the python as possible.

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java]: great point - I have the v2 scheduler port in the back of my mind and the closer the better. extract this method, and done. re-push with that in a bit

**Comment by mikehardy** [comment]
@timrae just re-pushed clean commits with problem logging extracted - if this looks good and you merge, I'll do the same with the forward-port to master to match

**Comment by mikehardy** [comment]
Not sure if AnkiDroid has done this before, but it would be neat to see a 2.8.5 official release to a tiny percentage via Play Console release settings (or maybe betas first, then a tiny percentage) after wiping acralyzer, at some time where I could watch for errors and holler to turn it off it was a dud for some reason. Maybe tomorrow morning your time / evening my time? Or Monday morning for you / Sunday night for me? Just brainstorming on how to get these last changes out in a way I can support well since it's otherwise stable and they're my changes...Don't want to blow up daily study for all the med-school students in the world at the same time

**Comment by timrae** [comment]
Yes, I can do a staged rollout. Can you create some release notes please?

**Comment by mikehardy** [comment]
Done I think? PR in the docs repo
