### PR TITLE
review count in deck picker

### LINKED ISSUE #14600: [BUG]: Decks screen doesn't display the number of cards reviewed
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Use AnkiDroid version 2.17alpha2

### Expected behaviour

The bottom of the decks screen should show the number of cards reviewed on that day (as in 2.16.5).

### Actual behaviour

This is not displayed.

### Debug info

```text
AnkiDroid Version = 2.17alpha2 (19ad510c0a44c4fa140394363a0df3bd8ab177d8)

Android Version = 13

ProductFlavor = full

Webview User Agent = Mozilla/5.0 (Linux; Android 13; moto g62 5G Build/T1SSIS33.1-75-7-1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/118.0.0.0 Mobile Safari/537.36

ACRA UUID = d808c2e4-92ce-40db-9491-1fdcb75b1f50

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by soCallmeAdityaKumar**
## Purpose / Description
Day Reviewed cards count was not displayed at the bottom of the home screen

## Fixes
#14600 

## How Has This Been Tested?
074710cb-a7b7-4ce7-9183-d34ed11b20c7

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by BrayanDSO** [comment]
Hi. In the PR layout there is a `How has this been tested section`. Please don't erase it and try filling it. Preferentially with a screenshot showing the results

**Comment by soCallmeAdityaKumar** [comment]
> Hi. In the PR layout there is a `How has this been tested section`. Please don't erase it and try filling it. Preferentially with a screenshot showing the results

@BrayanDSO i have added the screenshot

**Comment by user1823** [comment]
This doesn't look nice. In 2.16, the text was in a single line.

**Comment by BrayanDSO** [comment]
> This doesn't look nice. In 2.16, the text was in a single line.

Agreed. Please fix that @soCallmeAdityaKumar

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 1]
```diff
@@ -1828,7 +1828,10 @@ open class DeckPicker :
         launchCatchingTask { renderPage(collectionIsEmpty) }
         // Update the mini statistics bar as well
         launchCatchingTask {
-            withCol { mReviewSummaryTextView.text = sched.studiedToday() }
+            withCol {
+                mReviewSummaryTextView.text = sched.studiedToday()
+                mReviewSummaryTextView.setSingleLine()
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt]: Can you set the textview to use a singleLine in the XML?

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 2]
```diff
@@ -1827,8 +1827,11 @@ open class DeckPicker :
         dueTree = result
         launchCatchingTask { renderPage(collectionIsEmpty) }
         // Update the mini statistics bar as well
+        mReviewSummaryTextView.setSingleLine()
         launchCatchingTask {
-            withCol { sched.studiedToday() }
+            withCol {
+                mReviewSummaryTextView.text = sched.studiedToday()
```
Comment (lukstbit) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:1833]: withCol runs its lambda on a background thread so the text shouldn't be updated there:

`mReviewSummaryTextView.text = withCol { sched.studiedToday() }`

**Review by lukstbit — CHANGES_REQUESTED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt (hunk 1 above)
Comment (soCallmeAdityaKumar) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt]: If i use ```android:singleLine="true"``` or ```android:maxLines="1"``` then only "Studied 1 card...." is shown

**Review by lukstbit — APPROVED** [review]
LGTM, thanks!

**Review by BrayanDSO — APPROVED** [review]
LGTM. Thanks!
