### PR TITLE
fix: prevent memory leak in SharedDecksActivity by destroying WebView

### LINKED ISSUE #19965: Memory leak in SharedDecksActivity (suspected WebView Context issue)
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Open AnkiDroid.
2. Navigate to "Get Shared Decks" (SharedDecksActivity).
3. Press the back button to return to the DeckPicker.
4. Repeat steps 1-3 multiple times (e.g., 10-20 times).
5. Inspect the memory usage using the Android Studio Profiler.

**Observation**
The memory usage keeps increasing.
Instances of SharedDecksActivity are not being garbage collected.
The heap dump suggests that UiModeManager holds a reference to the WebView, which in turn holds the Activity Context.

Image

Image

I did it 7 times

Image

I did it 24 times

Image

### Expected behaviour

SharedDecksActivity should be garbage collected after it is destroyed.

### Debug info

```text
AnkiDroid Version = 2.24.0alpha0-debug (120ae9e3e1cc9d74ae1cd9c93f87cf18d6a122d9)  
Backend Version = 0.1.62-anki25.09.2 (25.09.2 3890e12c9e48c028c3f12aa58cb64bd9f8895e30)  
Android Version = 14 (SDK 34)  
ProductFlavor = play  
Device Info = Google | google | emu64xa | sdk_gphone64_x86_64 | sdk_gphone64_x86_64 | ranchu  
Webview User Agent = Mozilla/5.0 (Linux; Android 14; sdk_gphone64_x86_64 Build/UE1A.230829.036.A4; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/113.0.5672.136 Mobile Safari/537.36  
ACRA UUID = cb9112dd-e24d-4e60-b2e8-a126d16276e7  
FSRS = 5.1.0 (Enabled: false)  
Crash Reports Enabled = false

AnkiDroid Version = 2.24.0alpha0-debug (120ae9e3e1cc9d74ae1cd9c93f87cf18d6a122d9)  
Backend Version = 0.1.62-anki25.09.2 (25.09.2 3890e12c9e48c028c3f12aa58cb64bd9f8895e30)  
Android Version = 15 (SDK 35)  
ProductFlavor = play  
Device Info = Google | google | emu64xa | sdk_gphone64_x86_64 | sdk_gphone64_x86_64 | ranchu  
Webview User Agent = Mozilla/5.0 (Linux; Android 15; sdk_gphone64_x86_64 Build/AE3A.240806.036; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/141.0.7390.122 Mobile Safari/537.36  
ACRA UUID = d3ddc623-c774-4c20-b707-be5792040f43  
FSRS = 5.1.0 (Enabled: false)  
Crash Reports Enabled = false
```

### (Optional) Anything else you want to share?

I have been investigating this issue and I would like to share my findings and a potential solution for review.

My Analysis:
It seems that defining the WebView in the XML layout causes it to be initialized with the Activity Context. This appears to prevent the Activity from being garbage collected because system services (like UiModeManager) keep a reference to the WebView.
Also there is no onDestory function in SharedDecksActivity.

Experimental Fix:
I tried modifying the code to instantiate the WebView programmatically using the Application Context instead of the Activity Context.
Added onDestroy(): Explicitly calling webView.stopLoading(), clearing the webViewClient, and calling webView.destroy().

Replaced <WebView> in XML with a FrameLayout container.
Initialized WebView(applicationContext) in onCreate and added it to the container.
Cleaned up the WebView in onDestroy.
Result:
In my tests (API 34, 35), this change stopped the memory leak.

Request for Review:
As I am a student and new to this codebase, I am not entirely sure if using applicationContext for the WebView might introduce other side effects (e.g., theming or dialog issues).

Could you please review if this approach is correct/safe?

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by largeblueberry**
## Purpose / Description
This PR addresses the memory leak issues in SharedDecksActivity related to WebView usage, as identified in #19965.

Following the experimental fix suggestions, I implemented the `onDestroy()` method in SharedDecksActivity  and incorporated the cleanup logic based on the pattern found in SafeWebViewLayout.safeDestroy()

## Fixes
* Fixes #19965 

## Approach
The focus of this change is to ensure that the WebView  is properly disposed of when the Activity is destroyed. I ported the cleanup sequence from SafeWebViewLayout:

- Stopped ongoing loading and cleared the WebView by loading `about:blank`.
- Nullified `WebChromeClient` and `OnScrollChangeListener` to break reference cycles.
- Detached the WebView from its parent `ViewGroup` before final destruction.
- Wrapped the `destroy()` call in `runCatchingWithReport` for safe execution and logging.

## How Has This Been Tested?

To verify the fix, I navigated between SharedDecksActivity and DeckPicker 10 times consecutively.

**Result**:

API 34: Some leaks still persist, but these are attributed to the Context issue as discussed in the issue thread.
However, the specific leaks related to improper WebView teardown have been significantly mitigated.

API 35: leaks are fully resolved with this cleanup in place.

API 34

Image

API 35

Image

## Learning (optional, can help others)
Confirmed that applying the SafeWebViewLayout.safeDestroy() pattern directly within an Activity's onDestroy() is an effective experimental approach to mitigate WebView-related memory leaks in AnkiDroid.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt [hunk 1]
```diff
@@ -265,6 +266,29 @@ class SharedDecksActivity : AnkiActivity(R.layout.activity_shared_decks) {
         }
         return super.onOptionsItemSelected(item)
     }
+
+    override fun onDestroy() {
+        val webView = binding.webView
+
+        Timber.d("Destroying WebView")
+
+        runCatchingWithReport("safeDestroy", onlyIfSilent = true) {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt]: This duplicates the following, see if there's a better abstraction which you could use: 

https://github.com/ankidroid/Anki-Android/blob/cb64d936bf46f49ff1f142c66f1650f03294699e/AnkiDroid/src/main/java/com/ichi2/anki/workarounds/SafeWebViewLayout.kt#L169-L189

**Comment by largeblueberry** [comment]
I've refactored the code to centralize the WebView destruction logic into a static method within 'SafeWebViewLayout.'
This avoids code duplication while ensuring 'SharedDecksActivity' also benefits from the safe destruction process as suggested. Thanks for the feedback!"

**Comment by largeblueberry** [comment]
"Following your suggestion, I replaced the standard `WebView` with `com.ichi2.anki.workarounds.SafeWebViewLayout` and updated the ViewBinding to resolve compilation errors.

However, when I ran the app and navigated from `DeckPicker` to `SharedDecksActivity`, the app crashed with the following error:

**`java.lang.IllegalStateException: SafeWebViewLayout must be used within a Fragment`**

It seems `SafeWebViewLayout` was designed specifically for Fragments (it calls `findFragment()` in `onAttachedToWindow`).
Since `SharedDecksActivity` is an Activity, using this layout directly causes an issue.

Given this constraint, do you think I should refactor `SafeWebViewLayout` to support Activities as well, or would it be better to stick with `WebView` for this specific case?"

SafeWebviewLayout is only for fragment

File: AnkiDroid/src/main/java/com/ichi2/anki/workarounds/SafeWebViewLayout.kt [hunk 2]
```diff
@@ -194,6 +177,36 @@ open class SafeWebViewLayout :
                 LayoutParams.MATCH_PARENT,
                 LayoutParams.MATCH_PARENT,
             )
+
+        /**
+         * Static helper to destroy any WebView safely.
+         * Can be used by other Activities that don't use SafeWebViewLayout directly.
+         */
+        @JvmStatic
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/workarounds/SafeWebViewLayout.kt]: This shouldn't be necessary

File: AnkiDroid/src/main/java/com/ichi2/anki/workarounds/SafeWebViewLayout.kt [hunk 3]
```diff
@@ -194,6 +177,36 @@ open class SafeWebViewLayout :
...
+        fun destroyWebView(
+            webView: WebView?,
+            parent: ViewGroup?,
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/workarounds/SafeWebViewLayout.kt]: should this default to ` currentWebView.parent as? ViewGroup`

File: AnkiDroid/src/main/java/com/ichi2/anki/workarounds/SafeWebViewLayout.kt [hunk 4]
```diff
@@ -194,6 +177,36 @@ open class SafeWebViewLayout :
                 LayoutParams.MATCH_PARENT,
                 LayoutParams.MATCH_PARENT,
             )
+
+        /**
+         * Static helper to destroy any WebView safely.
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/workarounds/SafeWebViewLayout.kt]: reword - it's not static

Explain the 'what', usage is obvious given the method signature, so should be removed.

Look to the `safeDestroy` method for suggestions

**Review by david-allison — CHANGES_REQUESTED** [review]

**Comment by largeblueberry** [comment]
Thanks for the feedback, David! I've updated the code to address your suggestions:
Simplified the call site in SharedDecksActivity by using Kotlin's default parameters for the parent view.
Improved KDoc to focus on the "what" and "why" as suggested, and removed the unnecessary @JvmStatic.

File: AnkiDroid/src/main/java/com/ichi2/anki/workarounds/SafeWebViewLayout.kt [hunk 5]
```diff
@@ -194,6 +177,36 @@ open class SafeWebViewLayout :
...
+                webView?.apply {
+                    stopLoading()
+                    loadUrl("about:blank")
+                    webChromeClient = null
+                    // remove listeners this class exposes
+                    setOnScrollChangeListener(null)
+                }
+
+                // remove WebView from parent view
+                parent?.removeView(webView)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/workarounds/SafeWebViewLayout.kt]: Call `Timber.w` if `parent` is `null`

**Comment by david-allison** [comment]
I have squash merged and force pushed this to make it easier to merge.

If there are review comments, I'm happy to take responsibility for them, since I force pushed

Cheers!

**Review by BrayanDSO — APPROVED** [review]
