### PR TITLE
fix: "Background" toggle not working

### LINKED ISSUE #15036: [BUG]: Toggle button not working in SwitchPreferenceCompat ( Select Image )
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Go to Settings
2. Go to Appearance
3. Click on toggle button of `Select image`

### Expected behaviour

Toggle button is working

### Actual behaviour

Toggle button not working

https://github.com/ankidroid/Anki-Android/assets/65113071/f918921d-3358-4244-bb59-e9cf9bd86b30

### Debug info

```text
AnkiDroid Version = 2.17alpha12-debug (3c81b124d2ca555d48e82e0f2d31d8ed13d3b662)

Backend Version = 0.1.32-anki23.10.1 (23.10.1 fac9e0ee1436ba5ac3366c72dd9394a6e692b1cf)

Android Version = 13 (SDK 33)

ProductFlavor = amazon

Manufacturer = realme

Model = RMX3521

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; RMX3521 Build/RKQ1.211119.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.43 Mobile Safari/537.36

ACRA UUID = 9de0c19e-e369-4b82-8bf5-41b5c4917f2d

Crash Reports Enabled = false
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by SanjaySargam**
## Purpose / Description
Toggle button not working in SwitchPreferenceCompat ( Select Image )

## Fixes
* Fixes #15036 

## Approach
use `setOnPreferenceChangeListener` instead `onPreferenceClickLlistner`

## How Has This Been Tested?

Physical Device ( Realme 9 )

https://github.com/ankidroid/Anki-Android/assets/65113071/2019dc16-bd28-419a-a619-7d870b1156da

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by criticalAY** [comment]
I suggest having a simple option like this rather than a toggle button

**Comment by SanjaySargam** [comment]
Sounds cool!

**Comment by SanjaySargam** [comment]
Should I use `Preference` instead of `SwitchPreferenceCompat`

**Comment by criticalAY** [comment]
IMO what we can do is that we can have a reset image button instead of this switch in case user selects a image and if they doesn't select anything then disable that button

**Comment by SanjaySargam** [comment]
> IMO what we can do is that we can have a reset image button instead of this switch in case user selects a image and if they doesn't select anything then disable that button

To simplify this, we can have a `Preference` if the user didn't select image then title "Select Image" else "Remove Image" with specific functionality
I'm happy to know what your thought 
@david-allison @criticalAY

**Comment by SanjaySargam** [comment]
> IMO what we can do is that we can have a reset image button instead of this switch in case user selects a image and if they doesn't select anything then disable that button

@david-allison
Happy to know what your thoughts on this?

**Comment by david-allison** [comment]
It's only shown for a small fraction of our users, and isn't a practical problem. 

If the fix needed no debate, I'd happily accept it.

But, since there's a discussion which might go on for a while, we should shift our focus to our current list of higher priority issues

**Comment by david-allison** [comment]
I like the concept of `Preference` + 'wallpaper' icon

**Comment by SanjaySargam** [comment]
> I like the concept of `Preference` + 'wallpaper' icon

And what about reset image button as said by @criticalAY ?

**Comment by david-allison** [comment]
> And what about reset image button as said by @criticalAY ?

I feel this makes it a little too easy to perform a destructive action in a single click

I'd rather the user could either select an image, or remove the image

**Comment by SanjaySargam** [comment]
https://github.com/ankidroid/Anki-Android/assets/65113071/598e7025-a29f-4612-ba5e-369eb4275a29

**Comment by david-allison** [comment]
Let's bring this to #ankidroid-design for discussion and list the conclusions here. I don't want extra work

I would:

* Change the icon so it doesn't imply adding, we're either adding or removing
* If the action to select is cancelled, ask the user if they want to keep/remove the current background

**Review by david-allison — CHANGES_REQUESTED** [review]
Quick discussion didn't feel like bikeshedding, I'll approve once:

* Icon is changed
* The text is always "select"
* Cancelling the selection asks the user if they want to keep the current image

"Keep/Discard" dialog. Primary action is keep

**Comment by SanjaySargam** [comment]
> * Cancelling the selection asks the user if they want to keep the current image
> * "Keep/Discard" dialog. Primary action is keep


Both points are similar right?
From my understanding, if the user wants to remove the image then only dialog will show for confirmation. 
Correct me if I'm wrong

**Comment by david-allison** [comment]
> > * Cancelling the selection asks the user if they want to keep the current image
> > * "Keep/Discard" dialog. Primary action is keep
> 
> Both points are similar right? From my understanding, if the user wants to remove the image then only dialog will show for confirmation. Correct me if I'm wrong

Thanks for confirming: that's correct

* User Selects Image
* OK -> Image is selected
* Cancel
   * If no image is set -> cancel
   * If an image is set ->
       *  Dialog is shown with 'keep/cancel'

**Comment by SanjaySargam** [comment]
Changes done

- [ ] Icon is changed
- [x] The text is always "select"
- [x] Cancelling the selection asks the user if they want to keep the current image
- [x] "Keep/Discard" dialog. Primary action is keep

I don't found the perfect vector asset for wallpaper icon. 
What to do now ?

**Comment by david-allison** [comment]
So sorry this sat! Android studio forgot my icons and was extremely slow to download

`image` looks good to me:

Screenshot 2024-02-07 at 03 49 17

**Review by david-allison — CHANGES_REQUESTED** [review]
This needs to be rebased on `main`

The commit message heading should be improved

**Comment by SanjaySargam** [comment]
Commit message:-  "use Preference instead of SwitchPreferenceCompat"

is this ok ?

**Comment by SanjaySargam** [comment]
> This needs to be rebased on main

`git rebase main image`
using this command right ?

**Comment by david-allison** [comment]
```
git checkout main
git pull upstream main
git checkout image
```

**Review by david-allison — CHANGES_REQUESTED** [review]
The prompt should ask the user if they want to remove the image after they cancel the dialog

They should not be prompted on the 'happy path' of replacing the image

**Comment by david-allison** [comment]
Thanks! I tested it already before making the comment

If a user has a selected image:

* If they tap the preference
* Then an image selection dialog appears
   * If the user selects an image, the image is used
   * If the user does not select an image, ask the user if they want to remove the current image

File: AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt [hunk 1]
```diff
@@ -16,54 +16,56 @@
...
-        backgroundImage = requirePreference<SwitchPreferenceCompat>("deckPickerBackground")
-        backgroundImage!!.onPreferenceClickListener = Preference.OnPreferenceClickListener {
-            if (backgroundImage!!.isChecked) {
-                try {
-                    backgroundImageResultLauncher.launch("image/*")
-                    backgroundImage!!.isChecked = true
-                } catch (ex: Exception) {
-                    Timber.e("%s", ex.localizedMessage)
-                }
+        mBackgroundImage = requirePreference<Preference>("deckPickerBackground")
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt:56]: rename to `backgroundImage`

File: AnkiDroid/src/main/res/values/02-strings.xml [hunk 2]
```diff
@@ -199,6 +199,7 @@
     <!-- Deckpicker Background -->
     <string name="background_image_title">Background</string>
     <string name="choose_an_image">Select image</string>
+    <string name="remove_image">Remove selected image</string>
```
Comment (david-allison) [inline AnkiDroid/src/main/res/values/02-strings.xml:202]: I feel this should end in a `?`

**Review by david-allison — CHANGES_REQUESTED** [review]
Bad conflict resolution, look through the diff produced here and fix the conflict with ea8ceeace16b715f782849ba7a5e45cdb6c2a342

```
> Task :AnkiDroid:lintPlayDebug FAILED
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/03-dialogs.xml:176: Error: The resource R.string.image_dimensions_too_large appears to be unused [UnusedResources]
    <string name="image_dimensions_too_large">Image dimensions are too large (%1$d × %2$d)</string>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

File: AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt [hunk 3]
```diff
@@ -153,21 +151,54 @@ class AppearanceSettingsFragment : SettingsFragment() {
...
+                    if (imgFile.delete()) {
+                        showSnackbar(R.string.background_image_removed)
+                    } else {
+                        showSnackbar(R.string.error_deleting_image)
+                    }
+                } else {
+                    showSnackbar(R.string.background_image_removed)
+                }
+            }
+            negativeButton(R.string.dialog_no, null)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt:186]: better to have an empty lambda here rather than null

**Review by david-allison — CHANGES_REQUESTED** [review]
Please do more testing in future. A user can no longer set a background image, presumably as `deckPickerBackground` is no longer set.

Besides this, the spec still isn't met. 

There's no need for a yes/no `AlertDialog`. This should be handled when the image result is obtained.

As stated above:

* If the user taps the preference, then an image selection dialog appears
    * If the user selects an image, the image is used
    * If the user does not select an image, ask the user if they want to remove the current image

File: AnkiDroid/src/main/res/values/02-strings.xml [hunk 4]
```diff
@@ -199,6 +199,7 @@
     <!-- Deckpicker Background -->
     <string name="background_image_title">Background</string>
     <string name="choose_an_image">Select image</string>
+    <string name="remove_image">Remove selected image ?</string>
```
Comment (david-allison) [inline AnkiDroid/src/main/res/values/02-strings.xml:202]:
```suggestion
    <string name="remove_image">Remove selected image?</string>
```

**Comment by SanjaySargam** [comment]
@david-allison Really sorry for this. As you said image selection dialog, I thought we have to show a dialog

**Review by david-allison — CHANGES_REQUESTED** [review]
This still doesn't set the `deckPickerBackground` preference and therefore doesn't work on a new install.

* Install AnkiDroid
* Set background
* No background appears

File: AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt [hunk 5]
```diff
@@ -153,21 +146,50 @@ class AppearanceSettingsFragment : SettingsFragment() {
...
+        return imgFile.exists()
+    }
+
+    private fun showRemoveDialog() {
+        val currentAnkiDroidDirectory =
+            CollectionHelper.getCurrentAnkiDroidDirectory(requireContext())
+        val imgFile = File(currentAnkiDroidDirectory, "DeckPickerBackground.png")
+        AlertDialog.Builder(requireContext()).show {
+            title(R.string.remove_image)
+            positiveButton(R.string.dialog_yes) {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt:162]: Material dialog 2 guidelines: prefer to state what the action does, rather than yes/no

Screenshot 2024-02-10 at 05 42 47

In this case: remove/cancel

**Review by david-allison — COMMENTED** [review]
Code is MUCH cleaner, almost there once the dialog buttons and the bug are fixed, thanks!!!

File: AnkiDroid/src/main/res/values/02-strings.xml (hunk 4 above)
Comment (david-allison) [reply AnkiDroid/src/main/res/values/02-strings.xml:202]: On second thought, probably better with the following as it's more concise

```
    <string name="remove_background_image">Remove background?</string>
```

**Comment by SanjaySargam** [comment]
> This still doesn't set the deckPickerBackground preference and therefore doesn't work on a new install.

I couldn't able to figure it out. Will you please guide me to resolve this

**Comment by david-allison** [comment]
Pseudocode:

`prefs.edit { setBoolean("key", true) }` when the image should be enabled. False otherwise

**Comment by SanjaySargam** [comment]
> Pseudocode:
> 
> `prefs.edit { setBoolean("key", true) }` when the image should be enabled. False otherwise

I tried this, but nothing happens

**Comment by david-allison** [comment]
Figure out why setting `deckPickerBackground` doesn't work

**Comment by SanjaySargam** [comment]
@david-allison Now it's working fine

**Review by david-allison — CHANGES_REQUESTED** [review]
Untested:

* `Timber.w` should be used
* `deckPickerBackground` was set in the wrong place - should be enabled and disabled conditionally based on whether the user wants to add an image
* renamed `showRemoveDialog`, the method needs more context as it's not inside `BackgroundImage`
* Moved code to `BackgroundImage`

```patch
Subject: [PATCH] improve background image selection
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/BackgroundImage.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/BackgroundImage.kt b/AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/BackgroundImage.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/BackgroundImage.kt	(revision b014d52f7c37c1ea1901d5f8e6b7ede2d0362106)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/BackgroundImage.kt	(revision fddced8fc13d961eed4b0037708f9d431d4bb60a)
@@ -20,9 +20,12 @@
 import android.graphics.BitmapFactory
 import android.net.Uri
 import android.provider.MediaStore
+import androidx.core.content.edit
+import com.ichi2.anki.AnkiDroidApp
 import com.ichi2.anki.CollectionHelper
 import com.ichi2.anki.R
 import com.ichi2.anki.preferences.AppearanceSettingsFragment
+import com.ichi2.anki.preferences.sharedPrefs
 import com.ichi2.anki.snackbar.showSnackbar
 import java.io.File
 import java.io.FileInputStream
@@ -40,6 +43,19 @@
      */
     const val MAX_BITMAP_SIZE: Long = 100 * 1024 * 1024
 
+    /**
+     * @see shouldBeShown
+     */
+    var enabled: Boolean
+        get() = AnkiDroidApp.instance.sharedPrefs().getBoolean("deckPickerBackground", false)
+        set(value) {
+            AnkiDroidApp.instance.sharedPrefs().edit {
+                putBoolean("deckPickerBackground", value)
+            }
+        }
+
+    fun shouldBeShown(context: Context) = enabled && getImageFile(context) != null
+
     sealed interface FileSizeResult {
         data object OK : FileSizeResult
 
@@ -83,6 +99,7 @@
                 showSnackbar(R.string.background_image_applied)
             }
         }
+        this.enabled = true
     }
 
     data class Size(val width: Int, val height: Int)
@@ -96,4 +113,26 @@
         bmp.recycle()
         return Size(width = w, height = h)
     }
+
+    /**
+     * @return `true` if the image no longer exists. `false` if an error occurred
+     */
+    fun remove(context: Context): Boolean {
+        val imgFile = getImageFile(context)
+        enabled = false
+        if (imgFile == null) {
+            return true
+        }
+        return imgFile.delete()
+    }
+
+    /** @return a [File] referencing the image, or `null` if the file does not exist */
+    private fun getImageFile(context: Context): File? {
+        val currentAnkiDroidDirectory = CollectionHelper.getCurrentAnkiDroidDirectory(context)
+        val imgFile = File(currentAnkiDroidDirectory, "DeckPickerBackground.png")
+        if (!imgFile.exists()) {
+            return null
+        }
+        return imgFile
+    }
 }
Index: AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt b/AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt	(revision b014d52f7c37c1ea1901d5f8e6b7ede2d0362106)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/preferences/AppearanceSettingsFragment.kt	(revision fddced8fc13d961eed4b0037708f9d431d4bb60a)
@@ -19,12 +19,10 @@
 import androidx.activity.result.contract.ActivityResultContracts
 import androidx.appcompat.app.AlertDialog
 import androidx.core.app.ActivityCompat
-import androidx.core.content.edit
 import androidx.preference.ListPreference
 import androidx.preference.Preference
 import androidx.preference.SwitchPreferenceCompat
 import anki.config.ConfigKey
-import com.ichi2.anki.CollectionHelper
 import com.ichi2.anki.CollectionManager
 import com.ichi2.anki.CollectionManager.withCol
 import com.ichi2.anki.R
@@ -42,7 +40,6 @@
 import com.ichi2.utils.show
 import com.ichi2.utils.title
 import timber.log.Timber
-import java.io.File
 
 class AppearanceSettingsFragment : SettingsFragment() {
     private var backgroundImage: Preference? = null
@@ -57,11 +54,8 @@
         backgroundImage!!.onPreferenceClickListener = Preference.OnPreferenceClickListener {
             try {
                 backgroundImageResultLauncher.launch("image/*")
-                this.requireContext().sharedPrefs().edit {
-                    putBoolean("deckPickerBackground", true)
-                }
             } catch (ex: Exception) {
-                Timber.e("%s", ex.localizedMessage)
+                Timber.w(ex)
             }
             true
         }
@@ -150,28 +144,14 @@
         }
     }
 
-    private fun imageIsSelected(): Boolean {
-        val currentAnkiDroidDirectory =
-            CollectionHelper.getCurrentAnkiDroidDirectory(requireContext())
-        val imgFile = File(currentAnkiDroidDirectory, "DeckPickerBackground.png")
-        return imgFile.exists()
-    }
-
-    private fun showRemoveDialog() {
-        val currentAnkiDroidDirectory =
-            CollectionHelper.getCurrentAnkiDroidDirectory(requireContext())
-        val imgFile = File(currentAnkiDroidDirectory, "DeckPickerBackground.png")
+    private fun showRemoveBackgroundImageDialog() {
         AlertDialog.Builder(requireContext()).show {
             title(R.string.remove_background_image)
             positiveButton(R.string.dialog_remove) {
-                if (imgFile.exists()) {
-                    if (imgFile.delete()) {
-                        showSnackbar(R.string.background_image_removed)
-                    } else {
-                        showSnackbar(R.string.error_deleting_image)
-                    }
-                } else {
-                    showSnackbar(R.string.background_image_removed)
+                if (BackgroundImage.remove(requireContext())) {
+                    showSnackbar(R.string.background_image_removed)
+                } else {
+                    showSnackbar(R.string.error_deleting_image)
                 }
             }
             negativeButton(R.string.dialog_keep)
@@ -180,8 +160,8 @@
 
     private val backgroundImageResultLauncher = registerForActivityResult(ActivityResultContracts.GetContent()) { selectedImage ->
         if (selectedImage == null) {
-            if (imageIsSelected()) {
-                showRemoveDialog()
+            if (BackgroundImage.shouldBeShown(requireContext())) {
+                showRemoveBackgroundImageDialog()
             } else {
                 showSnackbar(R.string.no_image_selected)
             }
```

**Review by david-allison — APPROVED** [review]

**Review by mikehardy — APPROVED** [review]
LGTM - thank you! Strings PR in flight but will need a refresh for this one #15602
