### PR TITLE
fixed automatic creation of deck with name 'All decks'

### LINKED ISSUE #10800: [Bug] Card Browser - "All Decks" Appears twice
###### Reproduction Steps

1. Open Card Browser
2. Open Deck Selection

###### Expected Result

3. "All Decks" should appear once

###### Actual Result

3. "All Decks" appears twice

###### Debug info
```
AnkiDroid Version = 2.16alpha55

Android Version = 11

Manufacturer = Google

Model = Pixel 3a

Hardware = sargo

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Pixel 3a Build/RQ3A.211001.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/100.0.4896.79 Mobile Safari/537.36

ACRA UUID = 3e7c4ead-530d-4748-9f4f-622f9f619871

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by divyansh-dxn**
## Purpose / Description
Bug fix

## Fixes
Fixes #10800

## How Has This Been Tested?
Unit tested and on Realme 6i API 30

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

https://user-images.githubusercontent.com/69595691/180502839-0d325cfa-6746-46be-85ee-3888c5d18a76.mp4

https://user-images.githubusercontent.com/69595691/180502805-03d28cf0-8db2-48a1-8497-47328592f9dd.mp4

### CODE REVIEW

**Comment by BrayanDSO** [comment]
I don't think the toast is necessary. Just doing nothing if the user long tap All Decks is fine to me

**Comment by divyansh-dxn** [comment]
I thought it would be confusing if nothing happened on long click because everything else in the list has long click. 
Let's wait for someone else's feedback then will do.

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt [hunk 1]
```diff
@@ -227,21 +228,22 @@ open class DeckSelectionDialog : AnalyticsDialogFragment() {
...
-                    showSubDeckDialog(deckName)
-                    true
+                deckTextView.apply {
+                    text = deck.displayName
+                    setOnClickListener {
+                        selectDeckByNameAndClose(deck.name)
+                    }
+                    setOnLongClickListener { // creating sub deck with parent deck path
+                        if (deck.deckId == DeckSpinnerSelection.ALL_DECKS_ID) {
+                            showThemedToast(context, "You cannot create a subdeck for all decks", true)
```
Comment (lukstbit) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt:241]: Personally I'm ok with the toast because the row displays a visual indicator when long pressed. 
If you keep the toast, please extract the string to a resource string.

**Review by lukstbit — CHANGES_REQUESTED** [review]

File: AnkiDroid/src/main/res/values/01-core.xml [hunk 2]
```diff
@@ -136,6 +136,7 @@
     <string name="rebuild_cram_label">Rebuild</string>
     <string name="empty_cram_label">Empty</string>
     <string name="create_subdeck">Create subdeck</string>
+    <string name="cannot_create_subdeck_for_all_decks">You cannot create a subdeck for all decks</string>
```
Comment (divyansh-dxn) [inline AnkiDroid/src/main/res/values/01-core.xml:139]: extracted the string, but wasn't sure where to properly put it. Suggest if any changes required.

Comment (lukstbit) [reply AnkiDroid/src/main/res/values/01-core.xml:139]: This is a dialog and we have a 03-dialogs strings file so I would move it there(maybe with a comment above it `<!-- Deck selection dialog -->`)

**Review by lukstbit — CHANGES_REQUESTED** [review]

**Review by lukstbit — APPROVED** [review]

**Review by mikehardy — APPROVED** [review]
This works for me - thanks all, for the fix and for the reviews

Maintainers note - I want to get a translations sync in before merging this so it's clean in the translations

So, blocked merge waiting on #11911
