### PR TITLE
Fix `setDid()` when did is null

### LINKED ISSUE #10434: [Bug] Crashing when tapping Add note
###### Reproduction Steps

1. Tap `Add Note`

###### Expected Result

The add note screen should appear

###### Actual Result

It crashes

###### Debug info
```
AnkiDroid Version = 2.16alpha48

Android Version = 11

Manufacturer = samsung

Model = SM-N770F

Hardware = exynos9810

Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-N770F Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.58 Mobile Safari/537.36

ACRA UUID = e7a03b0c-3285-489b-8bcd-aa1e128e2eb5

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### Error log on android studio
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 23259
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.NoteEditor}: com.ichi2.utils.JSONException: org.json.JSONException: Value null at did of type org.json.JSONObject$1 cannot be converted to long
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3846)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4022)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8653)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: com.ichi2.utils.JSONException: org.json.JSONException: Value null at did of type org.json.JSONObject$1 cannot be converted to long
        at com.ichi2.utils.JSONObject.getLong(JSONObject.java:345)
        at com.ichi2.anki.NoteEditor.setDid(NoteEditor.java:1834)
        at com.ichi2.anki.NoteEditor.onCollectionLoaded(NoteEditor.java:578)
        at com.ichi2.anki.AnkiActivity.startLoadingCollection(AnkiActivity.java:384)
        at com.ichi2.anki.NoteEditor.onCreate(NoteEditor.java:438)
        at android.app.Activity.performCreate(Activity.java:8207)
        at android.app.Activity.performCreate(Activity.java:8191)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3819)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4022) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.app.ActivityThread.main(ActivityThread.java:8653) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 
     Caused by: org.json.JSONException: Value null at did of type org.json.JSONObject$1 cannot be converted to long
        at org.json.JSON.typeMismatch(JSON.java:101)
        at org.json.JSONObject.getLong(JSONObject.java:528)
        at com.ichi2.utils.JSONObject.getLong(JSONObject.java:343)
        at com.ichi2.anki.NoteEditor.setDid(NoteEditor.java:1834) 
        at com.ichi2.anki.NoteEditor.onCollectionLoaded(NoteEditor.java:578) 
        at com.ichi2.anki.AnkiActivity.startLoadingCollection(AnkiActivity.java:384) 
        at com.ichi2.anki.NoteEditor.onCreate(NoteEditor.java:438) 
        at android.app.Activity.performCreate(Activity.java:8207) 
        at android.app.Activity.performCreate(Activity.java:8191) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3819) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4022) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.app.ActivityThread.main(ActivityThread.java:8653) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 
D/UsageAnalytics: sendAnalyticsException() description/fatal: org.json.JSONException: Value null at did of type org.json.JSONObject$1 cannot be converted to long/true
I/ACRA: ACRA is disabled for com.ichi2.anki - forwarding uncaught Exception on to default ExceptionHandler
I/Process: Sending signal. PID: 23259 SIG: 9
Disconnected from the target VM, address: 'localhost:2478', transport: 'socket'
```

For some reason, the did on my collection was null, so it crashes at `getLong()`. I'll push the fix

### PR DESCRIPTION
**Pull request by BrayanDSO**
## Fixes
Fixes #10434

## Approach
Check if "did" property in model is not null before trying to get its value

## How Has This Been Tested?

Tested on my device (where the problem first happened) (Samsung Galaxy Note 10 Lite SM-N770F/DS, API 30)

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [X] You have performed a self-review of your own code
- [X] You have commented your code, particularly in hard-to-understand areas
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java [hunk 1]
```diff
@@ -1830,7 +1830,7 @@ private void setDid(Note note) {
                      */
                     mCurrentDid = 1;
                 }
-            } else {
+            } else if (!model.isNull("did")) {
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java:1833]: This solve your issue, no doubt about it. However, that clearly do not solve the underlying issue, which is that a model has no did.

Ideally, I'd love if you would create in Model a method `getDid(default=1L) : Long` that would return the property did if it is set, otherwise default value, and use it everywhere. In this case you'd use `mCurrentDid` as default.
It would ensure the problem is solved everywhere

Please wait until a second reviewer validate my suggestion before doing so.

**Review by mikehardy — CHANGES_REQUESTED** [review]
~~I think we discussed on discord, but dropping it here - as far as we know this is corrupt data relative to something we consider to be an invariant (that deck id is never null), so this should not be null-checked it should prompt the "help user run check database to fix corrupt collection" flow~~ [edited to note it's not corrupt data! v11 schema allows null on deck id, "Today I learned..."]

**Review by mikehardy — APPROVED** [review]
LGTM, follows conversation from linked issue (informed by Damien) with regard to nullability on deck id in schema v11+, thanks @BrayanDSO !

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java (hunk 1 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java]: discussed on linked issue, we learned deck id is now nullable in v11+ schema, so this PR in current form appears to be minimal + correct to handle that
