### PR TITLE
Labels added to dayOffset preference dialog seekbar

### LINKED ISSUE #8417: [Bug] Start of New Day - Preference text is truncated
###### Reproduction Steps

1. Preferences - Reviewing

###### Expected Result

2. Preference text is not truncated

###### Actual Result

3. Preference text is truncated

image

###### Debug info
```
AnkiDroid Version = 2.15alpha34

Android Version = 11

Manufacturer = Google

Model = Pixel 3a

Hardware = sargo

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Pixel 3a Build/RQ2A.210305.006; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/89.0.4389.105 Mobile Safari/537.36

ACRA UUID = 2f93c96f-11ae-45bd-b314-b1236df15be0

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by Arnold2381**
## Purpose / Description
Mentioned first https://github.com/ankidroid/Anki-Android/issues/8417#issuecomment-816953643

## Fixes
Fixes #8417 

## Approach
A new view was added for the labels.

Added two string resources in the file
image

## How Has This Been Tested?
Physical device

image

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by prateek-singh-3212 — COMMENTED** [review]
Everything looks good to me.

File: AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.java [hunk 1]
```diff
@@ -141,4 +157,21 @@ protected void onPrepareDialogBuilder(AlertDialog.Builder builder) {
         builder.setPositiveButton(null, null);
         builder.setTitle(null);
     }
+
+    private void addLabelsBelowSeekBar() {
+        String labels[]={mXLabel,mYLabel};
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.java:162]:
```suggestion
        String labels[] = {mXLabel,mYLabel};
```

File: AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.java [hunk 2]
```diff
@@ -141,4 +157,21 @@ protected void onPrepareDialogBuilder(AlertDialog.Builder builder) {
...
+        for (int count = 0; count < 2; count++) {
+            TextView textView = new TextView(mContext);
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.java:164]: We have a custom TextView class which fixes crashes in the default Android implementation

```
            TextView textView = new FixedTextView(mContext);
```

File: AnkiDroid/src/main/res/xml/preferences_reviewing.xml [hunk 3]
```diff
@@ -37,7 +37,9 @@
             android:summary="@string/day_offset_summ"
             android:title="@string/day_offset_with_description"
             app:interval="1"
-            app:min="0" />
+            app:min="0"
+            app:xlabel="Midnight"
```
Comment (david-allison-1) [inline AnkiDroid/src/main/res/xml/preferences_reviewing.xml:41]: Extract these to string resources to allow translation

https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#adding-translations

**Review by david-allison-1 — COMMENTED** [review]
Looks fantastic! Nothing wrong with the code structure, a few nitpicks and good to go

**Comment by Arnold2381** [comment]
@david-allison-1 I have also added the screenshot of the file name in which I have added the string value as mentioned in the dev guide in the PR template.

File: AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.java [hunk 4]
```diff
@@ -141,4 +158,22 @@ protected void onPrepareDialogBuilder(AlertDialog.Builder builder) {
         builder.setPositiveButton(null, null);
         builder.setTitle(null);
     }
+
+    private void addLabelsBelowSeekBar() {
+        String labels[] = {mContext.getString(R.string.xlabel_dayoffset_seekbar),
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.java:163]: You should be using `mXLabel` and `mYLabel` here

Comment (Arnold2381) [reply AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.java:163]: When I used that and set the text as `mXlabel` and `mYlabel` in text view it's giving as id's @2134571.

File: AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.java [hunk 5]
```diff
@@ -141,4 +158,22 @@ protected void onPrepareDialogBuilder(AlertDialog.Builder builder) {
...
+                mContext.getString(R.string.ylabel_dayoffset_seekbar)};
+        for (int count = 0; count < 2; count++) {
+            TextView textView = new FixedTextView(mContext);
+            textView.setText(labels[count]);
+            textView.setGravity(Gravity.LEFT);
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.java:168]:
```suggestion
            textView.setGravity(Gravity.START);
```

File: AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.java (hunk 4 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.java:163]:
```java
        String labels[] = { mContext.getString(mXLabel), mContext.getString(mYLabel)};
```

File: AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.java [hunk 6]
```diff
@@ -33,7 +35,8 @@
     private final int mMin;
     private final int mInterval;
     private int mValue = 0;
-
+    private final String mXLabel;
+    private final String mYLabel;
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.java:39]:
```suggestion
    @StringRes
    private final int mXLabel;
    @StringRes
    private final int mYLabel;
```

File: AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.java [hunk 7]
```diff
@@ -44,6 +47,8 @@ public SeekBarPreference(Context context, AttributeSet attrs) {
         mMax = attrs.getAttributeIntValue(androidns, "max", 100);
         mMin = attrs.getAttributeIntValue(AnkiDroidApp.XML_CUSTOM_NAMESPACE, "min", 0);
         mInterval = attrs.getAttributeIntValue(AnkiDroidApp.XML_CUSTOM_NAMESPACE, "interval", 1);
+        mXLabel = attrs.getAttributeValue(AnkiDroidApp.XML_CUSTOM_NAMESPACE, "xlabel");
+        mYLabel = attrs.getAttributeValue(AnkiDroidApp.XML_CUSTOM_NAMESPACE, "ylabel");
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.java:51]: Note: This would be better implemented as stated: https://stackoverflow.com/questions/46689210/android-how-to-use-string-resource-from-xml-file-in-property-of-customized-pref

```suggestion
        mXLabel = attrs.getAttributeResourceValue(AnkiDroidApp.XML_CUSTOM_NAMESPACE, "xlabel", 0);
        mYLabel = attrs.getAttributeResourceValue(AnkiDroidApp.XML_CUSTOM_NAMESPACE, "ylabel", 0);
```

File: AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.java [hunk 8]
```diff
@@ -66,6 +71,18 @@ protected View onCreateDialogView() {
         layout.addView(mSeekBar, new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,
                 LinearLayout.LayoutParams.WRAP_CONTENT));
 
+
+        if (mXLabel != null && mYLabel != null) {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.java:75]:
```suggestion
        if (mXLabel != 0 && mYLabel != 0) {
```

File: AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.java (hunk 6 above)
Comment (Arnold2381) [reply AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.java:39]: Thanks for this!! I was finding this only. But couldn't. I tried converting it into `int` was crashing.

File: AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.java (hunk 5 above)
Comment (Arnold2381) [reply AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.java:168]: I think it should be better if kept as `LEFT` because then I have to change the params things too. is there a specific reason you mentioned `START`?

Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.java:168]: What happens with a RTL locale? Presumably the seekbar is reversed, we also want to reverse the labels if this is the case

Comment (Arnold2381) [reply AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.java:168]: Yea got it! Ok, I will make it work!!

Comment (Arnold2381) [reply AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.java:168]: @david-allison-1 is this okay? I enabled RTL and checked
image

Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.java:168]: Looks great! 23 -> 11 and 0 -> midnight

Comment (Arnold2381) [reply AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.java:168]: Yess!

**Review by david-allison-1 — APPROVED** [review]
Lovely stuff, thanks!

**Review by mikehardy — APPROVED** [review]
LGTM - I resolved the conflict related to #8586 which results in a little bit of a hash of a commit history on the exact PR here but it was one clean commit to begin with so squashing it back to one clean commit seems identical - ready to merge...

**Comment by mikehardy** [comment]
This is the PR that just does not want to merge. While waiting for CI to go green on the last conflict resolution I did, it took another conflict from #8651 

Resolved, CI chewing again

**Comment by mikehardy** [comment]
Got it merged before anything else could perturb it :-) :rocket:

**Comment by Arnold2381** [comment]
Accomplishment 😅😅
Thanks @mikehardy !!
