### PR TITLE
recreate DeckPicker activity on Deleting collection from app settings

### LINKED ISSUE #13477: [BUG] Deck picker menu items vanish after deleting collection on manage space activity
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Have the app opened in the deck picker
2. Go to the system settings > AnkiDroid > Storage > Manage space
3. Tap delete collection
4. Go back to ankidroid

### Expected behaviour

Menu items are shown correctly

### Actual behaviour

Menu items vanish and only reappear after opening another activity then going back

### Debug info

```text
AnkiDroid Version = 2.16alpha94

Android Version = 13

Manufacturer = samsung

Model = SM-N770F

Hardware = exynos9810

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-N770F Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/111.0.5563.57 Mobile Safari/537.36

ACRA UUID = a5fa24bf-3151-4233-894d-b6a56e1095a3

New schema = true

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

2.16alpha94 from the GH releases page

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by criticalAY**
## Purpose / Description
Used shared pref to recreate the deck picker activity as soon as the collections are cleared using app settings
This Activity actually needed a recreation on clearing the collection as if not it was frozen until we visit the other activity and come back to it. Refresh or InvalidateOptionMenu would not work here 

## Fixes
Fixes #13477

## Approach
Used Shared Prefs

## How Has This Been Tested?
Tested on Oneplus Nord CE

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by criticalAY** [comment]
Meaning exit the application?

**Comment by criticalAY** [comment]
and if we suddenly kill the application and relaunch it would not it be an issue for the user?

**Comment by BrayanDSO** [comment]
> and if we suddenly kill the application and relaunch it would not it be an issue for the user?

There is a chance that the user went directly to the manage space activity without the app opened previously

**Comment by criticalAY** [comment]
But we shouldn't really trust the users we have, they tend to do unexpected things

**Comment by criticalAY** [comment]
In context to what you said that the user might go to the app settings without opening the application

**Comment by criticalAY** [comment]
Ok so I guess this should work fine then

File: AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt [hunk 1]
```diff
@@ -307,13 +308,19 @@ class ManageSpaceFragment : SettingsFragment() {
...
+                    finishAllActivities()
                 }
             }
         } else {
             showSnackbarIfCalculatingOrError(size)
         }
     }
 
+    private fun finishAllActivities() {
+        activity?.finishAffinity()
```
Comment (oakkitten) [inline AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt:320]: What's the role of this?

**Review by oakkitten — COMMENTED** [review]
The option “Delete everything” includes the text,

> Note: this action will close the window

https://github.com/ankidroid/Anki-Android/blob/0a6a378732064cd8be94a5c84348c25ae860da7b/AnkiDroid/src/main/res/values/10-preferences.xml#L449-L455

Perhaps we want a similar note here?

Also, since that fixes it, probably remove the according TODO here:

https://github.com/ankidroid/Anki-Android/blob/a06e727f6094541b763e2dc18a300edb3e17fd26/AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt#L289-L292

File: AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt (hunk 1 above)
Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt:320]: That was to finish the current Activity without causing an error and then exit the system

Comment (oakkitten) [reply AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt:317]: The next line is `exitProcess(0)`, I'm not sure if this one makes a difference. Also the method says “finish all activities”, and only one is finished...

Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt]: Umm you are right I am simplifying the code, Thanks!

File: AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt [hunk 2]
```diff
@@ -286,10 +287,6 @@ class ManageSpaceFragment : SettingsFragment() {
 
     /************************************* Delete collection **************************************/
 
-    // TODO: Finish other AnkiDroid activities when the collection is deleted.
-    //   Note that this might be not quite trivial, as the activities might be visible to user.
-    //   One way would be to have the activities register broadcast receivers that perform finish;
-    //   Another would be maintaining weak references to them. Would be nice to find a better way.
```
Comment (oakkitten) [inline AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/ManageSpaceFragment.kt:292]: I suggest replacing with:

```kt
    // While we are in this activity, we may have other activities opened.
    // These activities might be visible to user, e.g. when using Split screen mode.
    // When the collection is deleted, whatever these activities are showing may become invalid.
    // To fix that, ideally we should refresh or finish these activities,
    // however, as this task is not trivial, we opt for killing the process instead.
    // One major downside here is that killing the process makes this activity, 
    // and possibly even the settings app, vanish without animation.
```

**Review by oakkitten — APPROVED** [review]
Got a few nitpicks but otherwise 👍

**Review by BrayanDSO — APPROVED** [review]
considering oakkitten's approval as the second one. Pending merge after sync translation

**Comment by mikehardy** [comment]
@BrayanDSO strings are clear right now - both in crowdin and from merged PRs, they are perfectly ready for any thing to go through - have at it!
