### PR TITLE
Deck Picker: Convert the dialog to a Toast

### LINKED ISSUE #7680: Deck Picker: "rename custom study" message obscured
###### Reproduction Steps

1. Create a deck named "Custom study session"
2. Deck - Custom Study - Review Ahead - OK

###### Expected Result

3. Dialog should appear

###### Actual Result

3. Dialog is obscured by going back one menu item

----

String in question:

https://github.com/ankidroid/Anki-Android/blob/ae4f898db8084ff3cba2ce67d8aca2b0c68ca300/AnkiDroid/src/main/res/values-da/01-core.xml#L165

Usage:

https://github.com/ankidroid/Anki-Android/blob/7f675720d139477d05c6e553d8a41d15e09e94e0/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java#L436-L451

Ideal solution: convert the dialog to a toast.

### PR DESCRIPTION
**Pull request by bguneys**
## Purpose / Description
After creating a new deck and opening a dialog menu by long tapping on the recently created deck, then tapping "Custom Study" option on the menu and tapping "Review ahead" option on the newly opened menu and then typing a number greater than 1 as days and tapping "OK" button, an alert dialog with text message "Rename the existing custom study deck first" appears but immediately gets obscured at the back of an another dialog menu.

## Fixes
Fixes #7680 

## Approach
Show a Toast message converting Dialog to Toast.

## How Has This Been Tested?
Android 9

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] Strings resources: All strings added as resources are unique or contain a comment for seemingly duplicate strings to explain the difference between both resources

### CODE REVIEW

**Comment by bguneys** [comment]
Screenshot_20201114-224047_AnkiDroid2

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java [hunk 1]
```diff
@@ -436,10 +438,9 @@ private void createCustomStudySession(JSONArray delays, Object[] terms, Boolean
             Timber.i("Found deck: '%s'", customStudyDeck);
             if (cur.getInt("dyn") != 1) {
                 Timber.w("Deck: '%s' was non-dynamic", customStudyDeck);
-                new MaterialDialog.Builder(getActivity())
-                    .content(R.string.custom_study_deck_exists)
-                    .negativeText(R.string.dialog_cancel)
-                    .build().show();
+                Toast toast = Toast.makeText(getActivity(), R.string.custom_study_deck_exists, Toast.LENGTH_SHORT);
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java:441]: We have `UIUtils.showThemedToast` which should cut down on the code here.

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
Looks good from an implementation POV, thanks!!!!

One quick code quality improvement and we're good to go

**Review by david-allison-1 — APPROVED** [review]
Looks good to me, thanks!!

**Comment by bguneys** [comment]
Thanks for the reply. I added `UIUtils.showThemedToast` but then Toast message is showing at the center of the Activity. Would this be ok for UI design? If not, is there any implementation could you advise to have Toast message showing at the bottom of the screen?

Screenshot3

**Comment by david-allison-1** [comment]
> r the reply. I added `UIUtils.showThemedToast` but then Toast message is showing at the center of the Activity. Would this be ok for UI design? If not, is there any implementation could you advise to have Toast message showing at the bottom of the screen?

That's strange... I haven't seen that happen before with `showThemedToast`. 

I'll take a quick look, give me 5 minutes

It'd be better at the bottom (in which case: revert and leave a comment).

**Comment by david-allison-1** [comment]
I've checked out the code and the toast appears on the bottom on my API 25 emulator.

It'd be best to include your fix (setting gravity) in `UIUtils.showThemedToast`, so we get consistent behaviour - as far as I'm aware, it  was intended to always be at the bottom of the screen.

@mikehardy Tagging to confirm this seems sensible with you.

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java [hunk 2]
```diff
@@ -27,11 +27,13 @@
 import android.text.Editable;
 import android.text.TextUtils;
 import android.text.TextWatcher;
+import android.view.Gravity;
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java:30]: Why this import?

**Review by Arthur-Milchior — COMMENTED** [review]
Thanks for fixing a problem. One small question.

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java (hunk 2 above)
Comment (bguneys) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java]: When I first added `Toast` to show the message, Toast message showed up at the center of the screen in my Samsung Galaxy S8 phone (Android 9). I thought maybe it was because I was creating `Toast` inside DialogFragment, so I wanted to set Toast message position at the bottom of the screen by using `setGravity()` method as a quick fix. This is why `Gravity` import was added. But @david-allison-1 reminded me to use `UIUtils.showThemedToast`. So I replaced my first `Toast` implementation and deleted `setGravity()` method. But I forgot to remove unused imports. In the latest commit ([7e3453b](https://github.com/ankidroid/Anki-Android/pull/7687/commits/7e3453ba76ac39f42d75e04e3d5b2823c1def18b)) I removed both `Gravity` and `Toast` imports  which are unused.

**Review by mikehardy — APPROVED** [review]
Thanks @bguneys! this LGTM and I think if toast display is not gravity bottom then that's a separate issue, a follow up is fine so we can get this in now since we haven't had other reports of unexpected toast gravity

**Comment by mikehardy** [comment]
Hello! with the 2.14 release we started accepting donations with the stated goal of accepting money from users to support maintenance and development of AnkiDroid

This PR was included in 2.14, and if you'd like to submit an expense to share in a portion of our hopefully-sustainable monthly disbursement, please read here and do so in the next couple of days:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process

This is our first time handling donations and attempting to compensate anyone with these processes, so please be flexible and patient with us

Thank you for your contribution to AnkiDroid!
