### PR TITLE
fix: multimedia URI `SecurityException`

### LINKED ISSUE #18660: 2.21: Image import from WhatsApp fails
@criticalAY if you have capacity, this would be a great one to look into. A crash report appears

Otherwise, needs triage to see if this occurred in 2.20

### PR DESCRIPTION
**Pull request by criticalAY**
## Purpose / Description
When app like WhatsApp shares a file using an Intent, it typically passes a content:// URI (from its ContentProvider) and grants temporary URI permissions for:
- The specific component receiving the intent.
- Only during that activity's lifecycle — not globally or across app components like fragments in our case the MultimediaImageFragment

Its(Whatsapp) MediaProvider is not exported — meaning no other app can directly query it unless explicitly granted permission via intent.

So to fix this we needed to immediately internalizing the URI  in the Activity that received the intent.

## Fixes
* Fixes  #18660

## Approach
By copying the image to internal storage (file://), we ensure persistent access without permission issues across fragments and then in fragment(MultimediaImageFragment) we check if we need to internalize it or not to avoid internalizing it again

## How Has This Been Tested?
Vivo V338

## Learning (optional, can help others)
That we either need to pass the permission or cache the uri where(to activity or fragment recieving it) the image is shared 

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt [hunk 1]
```diff
@@ -531,12 +530,29 @@ class MultimediaImageFragment : MultimediaFragment(R.layout.fragment_multimedia_
...
+     * If the URI is already a file URI, it is directly converted to a [File] object.
+     *
+     * @param uri The URI to resolve.
+     * @return The corresponding [File], or `null` if the URI is invalid or unsupported.
+     */
+    private fun resolveUriToFile(uri: Uri): File? {
+        return when (uri.scheme) {
+            ContentResolver.SCHEME_CONTENT -> internalizeUri(uri)
+            ContentResolver.SCHEME_FILE -> File(uri.path ?: return null)
+            else -> null
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt]: I believe `FileUtils.internalizeUri` should work on other URIs, not just `SCHEME_CONTENT`

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt [hunk 2]
```diff
@@ -610,10 +630,45 @@ class NoteEditor :
...
+     * @return The name of the cached file, or `null` if the operation failed.
+     */
+    private fun copyUriToInternalCache(uri: Uri): String? {
+        return try {
+            val inputStream = requireContext().contentResolver.openInputStream(uri) ?: return null
+
+            val destFile =
+                File(
+                    requireContext().cacheDir,
+                    ContentResolverUtil.getFileName(requireContext().contentResolver, uri),
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt]: Confirm this is safe from directory traversal attacks

**Review by david-allison — CHANGES_REQUESTED** [review]
Bug fixed! Couple of questions and it's good to go

File: AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt (hunk 1 above)
Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt]: Trueee will change

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt (hunk 2 above)
Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt]: ~Ohh no its not safe, is there any existing sanitization method~

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt [hunk 3]
```diff
@@ -610,10 +630,52 @@ class NoteEditor :
...
+            val canonicalDestFile = destFile.canonicalFile
+
+            if (!canonicalDestFile.path.startsWith(canonicalCacheDir.path)) {
+                Timber.w("Rejected path due to directory traversal risk: $fileName")
+                return null
+            }
+
+            destFile.outputStream().use { output ->
+                inputStream.copyTo(output)
+            }
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:669]: This part I don't understand - and when I say I don't understand, what I mean is, I don't understand:
- why are we doing the actual file copy here in NoteEditor when we have file copies all over the place and an implementation in Compat
- most particularly, why is NoteEditor concerned about directory traversal risk, i.e., important security concerns with file handling?

I feel like in the multimedia area there is already a proliferation of inlined file copying and I really do not like it

We have the Compat methods for a reason, since there is a break at API26 for how we do copies, and any security concerns should *always* be centralized in shared utility methods

Would love to see any necessary bits (path traversal check?) added to a shared utility method (and I suggest it already exists in Compat) and this should simply do the setup ("what's my source?", "what's my destination?") then delegate to the Compat method for the copy

One level higher even, don't we *already* have file internalizers from Content URIs? Feels like pasting images, importing collections, they will all have the same need to internalize a URI (that is, they already do the source/destination setup) and likely have this code or a version of this code, and will have the same concerns with URI permissions and path traversal and everything. That sort of thing shouldn't proliferate, there should be one implementation only with all others just using it

**Review by mikehardy — COMMENTED** [review]
I love that the cause of the problem is identified, but I have serious concerns about file internalization implementation proliferation as noted

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt (hunk 3 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:669]: I'm going to merge this PR because I want to do another beta tomorrow, but I'd like to continue this conversation and ideally there's a follow-on PR that is just focused on "consolidation of ContentResolver/File URI -> internalized file URI code"

Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:669]: I will make an issue so that we don't loose the convo sorry I was busy with stuff its in my TODO
