### PR TITLE
Replaces usages of `MaterialDialog` with `AlertDialog` on most preferences classes

### LINKED ISSUE #12669: [Bug] Unwanted vertical line on Material Dialog titles when launched from preferences
###### Reproduction Steps

1. In `DevOptionsFragment`, allow the "Enable developer options" to be shown in Debug mode (see patch)
2. Select "Enable Developer Options" to disable them. A Dialog should appear

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/preferences/DevOptionsFragment.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/preferences/DevOptionsFragment.kt b/AnkiDroid/src/main/java/com/ichi2/anki/preferences/DevOptionsFragment.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/preferences/DevOptionsFragment.kt	(revision 9703ac7bb2effe4e7ec7a6a4de630df1bf0fe908)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/preferences/DevOptionsFragment.kt	(date 1665872231649)
@@ -39,14 +39,12 @@
         val enableDevOptionsPref = requirePreference<SwitchPreference>(R.string.dev_options_enabled_by_user_key)
         // If it is a DEBUG build, hide the preference to disable developer options
         // If it is a RELEASE build, configure the preference to disable dev options
-        if (BuildConfig.DEBUG) {
-            enableDevOptionsPref.isVisible = false
-        } else {
-            enableDevOptionsPref.setOnPreferenceChangeListener { _, _ ->
-                showDisableDevOptionsDialog()
-                false
-            }
+
+        enableDevOptionsPref.setOnPreferenceChangeListener { _, _ ->
+            showDisableDevOptionsDialog()
+            false
         }
+
         // Make it possible to test crash reporting
         requirePreference<Preference>(getString(R.string.pref_trigger_crash_key)).setOnPreferenceClickListener {
             Timber.w("Crash triggered on purpose from advanced preferences in debug mode")
```

###### Expected Result

A normal Material Dialog is seen

###### Actual Result

There is a vertical line to the right of the `s` in the title's TextView, this fades after a few seconds (ignore the other lines - due to screenshotting on macOS from an emulator)

Screenshot 2022-10-15 at 23 30 16

###### Debug info
Tested when this file was introduced (9703ac7bb2effe4e7ec7a6a4de630df1bf0fe908) on and `main`

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by BrayanDSO**
## Fixes
Fixes #12669
Related #13315

## Approach
Replaces most usages of `MaterialDialog` with `AlertDialog` on preferences classes, except Custom sync server preferences as they are handled on #12367

`Controls` screen preferences haven't been changed

## How Has This Been Tested?

Open each one of the changed dialogs on their respective preferences

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by oakkitten** [comment]
I think we could investigate rolling out our own tiny API for dialogs, similar to snackbar APIs, if only to guarantee that `show()` is called at the end.

Also, I mentioned it elsewhere, since we have quite a few places where dialogs open other dialogs, we could use coroutines to flatten the callbacks. Here's [one article](https://federicokt.medium.com/smarter-dialogs-with-coroutines-b83e1d0e06a0)

**Review by mikehardy — APPROVED** [review]
Just as a pre-emptive vote of confidence since I've been on record on the Material vs Alert dialog thing. I'll happily see the MaterialDialog dependency drop and the transformations in these commits look trivial. If all of the tech issues are solved, I think this is mostly a step sideways but also a bit of a step forwards and is worth it

**Comment by lukstbit** [comment]
@BrayanDSO Fix one conflict, get an approve for free!

**Comment by BrayanDSO** [comment]
I really like getting things for free 😁

File: AnkiDroid/src/main/java/com/ichi2/anki/preferences/DevOptionsFragment.kt [hunk 1]
```diff
@@ -83,13 +83,12 @@ class DevOptionsFragment : SettingsFragment() {
      * Shows dialog to confirm if developer options should be disabled
      */
     private fun showDisableDevOptionsDialog() {
-        MaterialDialog(requireContext()).show {
-            title(R.string.disable_dev_options)
-            positiveButton(R.string.dialog_ok) {
+        AlertDialog.Builder(requireContext())
```
Comment (lukstbit) [inline AnkiDroid/src/main/java/com/ichi2/anki/preferences/DevOptionsFragment.kt:86]: This dialog also needs a `show()` call.

**Review by lukstbit — CHANGES_REQUESTED** [review]
One small issue below.
Squash on merging?

**Comment by BrayanDSO** [comment]
Squash, please

File: AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt [hunk 2]
```diff
@@ -57,12 +58,10 @@ class AdvancedSettingsFragment : SettingsFragment() {
...
                 } catch (e: StorageAccessException) {
                     Timber.e(e, "Could not initialize directory: %s", newPath)
-                    MaterialDialog(requireContext()).show {
-                        title(R.string.dialog_collection_path_not_dir)
-                        positiveButton(R.string.dialog_ok) {
-                            dismiss()
-                        }
-                        negativeButton(R.string.reset_custom_buttons) {
+                    AlertDialog.Builder(requireContext()).show {
+                        setTitle(R.string.dialog_collection_path_not_dir)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt:62]: Implementer's choice:
Consider using the Facade in this PR to avoid line noise `setTitle()` -> `title()` means an unchanged line on the diff

**Review by david-allison — APPROVED** [review]
Approve with one optional request. Implementer's choice

File: AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt (hunk 2 above)
Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt:62]: Good point. Will do it if I need to upgrade other dialogs. For now, changing this PR would take me some minutes and wouldn't create any reward, so I'd rather spare me the work

**Review by lukstbit — APPROVED** [review]
Great!
