### PR TITLE
Clear ACRA on cancel, use ACRA data for rate limit

### LINKED ISSUE #8379: [Bug] Send Bug Report - Can't re-submit if cancelled
###### Reproduction Steps

1. Help - Get Help - Send troubleshooting report
2. Cancel

###### Expected Result

* I can send a report again

###### Actual Result

* I need to wait

###### Debug info
```
AnkiDroid Version = 2.15alpha34

Android Version = 11

Manufacturer = Google

Model = Pixel 3a

Hardware = sargo

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Pixel 3a Build/RQ2A.210305.006; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/89.0.4389.105 Mobile Safari/537.36

ACRA UUID = 2f93c96f-11ae-45bd-b314-b1236df15be0

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by mikehardy**
## Purpose / Description

If the user canceled, they should not be limited in the future

## Fixes
Fixes #8379
Supercedes #8432

## Approach
- the limiter should have the best source of info for rate limiting, not an internal static timestamp thing
- the limiter stores report timestamps when generated, not approved though, so clear on cancel
- I snuck in some access limitation changes to de-lint AndroidStudio in the area

Currently doing something distasteful in order to access the limiter data but it I have positive confirmation from upstream that the next version of ACRA allows it with no reflection:

https://github.com/ACRA/acra/issues/843#issuecomment-820784697

```java
long mostRecentTimestamp = LimiterData.load(this).getReportMetadata().stream()
    .filter(report -> report.getExceptionClass().equals(UserSubmittedException.class.getName()))
    .mapToLong(report -> report.getTimestamp().getTimeInMillis())
    .max().orElse(-1);
```

I will file a separate issue to update to ACRA 5.8.0 with that information and a pointer to this code to remove the reflection

## How Has This Been Tested?

Oh, so much clicking and log watching on an API30 emulator

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by mikehardy** [comment]
Filing this now because I was in the ACRA area for another reason, and this was a 2.15 issue. Trying to nail down 2.15 issues...

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java [hunk 1]
```diff
@@ -277,20 +280,54 @@ protected void onClicked(AnkiActivity activity) {
...
+        private long getTimestampOfLastReport(AnkiActivity activity) {
+            long mostRecentTimestamp = -1;
+            try {
+                // The ACRA LimiterData holds a timestamp for every generated report
+                LimiterData limiterData = LimiterData.load(activity);
+                Field limiterDataListField = limiterData.getClass().getDeclaredField("list");
+                limiterDataListField.setAccessible(true);
+                List<LimiterData.ReportMetadata> limiterDataList = (List<LimiterData.ReportMetadata>)limiterDataListField.get(limiterData);
+                for (LimiterData.ReportMetadata report : limiterDataList) {
+                    if (report.getExceptionClass().equals(UserSubmittedException.class.getName())) {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java:300]: Could you invert these `if`s into `continue` for readability

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java [hunk 2]
```diff
@@ -277,20 +280,54 @@ protected void onClicked(AnkiActivity activity) {
...
+                        Method timestampMethod = report.getClass().getDeclaredMethod("getTimestamp");
+                        timestampMethod.setAccessible(true);
+                        Calendar timestamp = (Calendar)timestampMethod.invoke(report);
+                        if (timestamp.getTimeInMillis() > mostRecentTimestamp) {
+                            mostRecentTimestamp = timestamp.getTimeInMillis();
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java:305]: I think we can `break;` here

**Review by david-allison-1 — APPROVED** [review]
LGTM, just nits

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java (hunk 2 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java:305]: Good thinking - it's even better than that, we don't need to track+ratchet up, ACRA limiter makes sure there is only ever one with that class, so once we found it just return period, and at the end return -1 if we never find it

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java (hunk 1 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java:300]: Yeah, I'm leaning towards quick return / less indent style everywhere as well - done

**Comment by mikehardy** [comment]
Good nits - made it better, I did those and re-tested it locally, I'll merge once it's in. Almost have gradle 7 done - everything works locally but I want to merge this then do a release to make sure that gradle machinery is still working as well
