### PR TITLE
Disable the save button and previewer button if note type is `Image occlusion`

### LINKED ISSUE #15025: [BUG]: "Save" makes an error on Add screen when the note type is Image Occlusion
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Open the app
2. "+" -> "Add"
3. Select "Image Occlusion" in "Type:"
4. "Save"

### Expected behaviour

No error.

### Actual behaviour

Error

### Debug info

```text
AnkiDroid Version = 2.17alpha12 (3c81b124d2ca555d48e82e0f2d31d8ed13d3b662)

Backend Version = 0.1.32-anki23.10.1 (23.10.1 fac9e0ee1436ba5ac3366c72dd9394a6e692b1cf)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/118.0.0.0 Mobile Safari/537.36

ACRA UUID = df169a4d-29ec-46b6-b114-141ca7e01ba3

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

It might be good to disable (gray) or hide the "Save" button in this case from the start.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by criticalAY**
## Purpose / Description
When in image occlusion mode hide the save button as the note is already saved when adding the image and the user is notified 

## Fixes
* Fixes #15025

## How Has This Been Tested?
tested on google emulator 
image

image

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison** [comment]
'Preview' should be fixed rather than removed - a card should be able to be generated

More importantly, I'd like the 'back' button to warn the user about losing changes when in Image Occlusion

And to see if we can do anything to make the 'add' button more prominent. It's not intuitive in its current position

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt [hunk 1]
```diff
@@ -995,6 +996,7 @@ class NoteEditor : AnkiActivity(), DeckSelectionListener, SubtitleListener, Tags
                 }
             }
         }
+        menu.findItem(R.id.action_save).isVisible = !currentNotetypeIsImageOcclusion()
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:999]: nit: extract this to a method: `canSaveNoteType()` or `canSave()`

**Review by david-allison — CHANGES_REQUESTED** [review]

**Review by david-allison — CHANGES_REQUESTED** [review]
```
NoteEditorTest > verifyStartupAndCloseWithNoCollectionDoesNotCrash FAILED
    net.ankiweb.rsdroid.BackendException$BackendDbException$BackendDbLockedException: 
        at com.ichi2.anki.CollectionManager.ensureOpenInner(CollectionManager.kt:229)
        at com.ichi2.anki.CollectionManager.access$ensureOpenInner(CollectionManager.kt:39)
        at com.ichi2.anki.CollectionManager$getColUnsafe$1$1.invoke(CollectionManager.kt:287)
        at com.ichi2.anki.CollectionManager$getColUnsafe$1$1.invoke(CollectionManager.kt:286)
        at com.ichi2.anki.CollectionManager.blockForQueue(CollectionManager.kt:266)
        at com.ichi2.anki.CollectionManager.access$blockForQueue(CollectionManager.kt:39)
        at com.ichi2.anki.CollectionManager$getColUnsafe$1.invoke(CollectionManager.kt:286)
        at com.ichi2.anki.CollectionManager$getColUnsafe$1.invoke(CollectionManager.kt:285)
        at com.ichi2.anki.CollectionManager.logUIHangs(CollectionManager.kt:302)
        at com.ichi2.anki.CollectionManager.getColUnsafe(CollectionManager.kt:285)
        at com.ichi2.anki.AnkiActivity.getGetColUnsafe(AnkiActivity.kt:[138](https://github.com/ankidroid/Anki-Android/actions/runs/7261580314/job/19783061508?pr=15030#step:9:139))
        at com.ichi2.anki.NoteEditor.getCurrentlySelectedNotetype(NoteEditor.kt:1973)
        at com.ichi2.anki.NoteEditor.currentNotetypeIsImageOcclusion(NoteEditor.kt:1998)
        at com.ichi2.anki.NoteEditor.onCreateOptionsMenu(NoteEditor.kt:999)
        at android.app.Activity.onCreatePanelMenu(Activity.java:4343)
        at androidx.activity.ComponentActivity.onCreatePanelMenu(ComponentActivity.java:520)
        at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3442)
        at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:458)
        at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:58)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at org.robolectric.shadows.ShadowPausedLooper$IdlingRunnable.doRun(ShadowPausedLooper.java:573)
        at org.robolectric.shadows.ShadowPausedLooper$ControlRunnable.run(ShadowPausedLooper.java:536)
        at org.robolectric.shadows.ShadowPausedLooper.executeOnLooper(ShadowPausedLooper.java:629)
        at org.robolectric.shadows.ShadowPausedLooper.idle(ShadowPausedLooper.java:104)
        at org.robolectric.shadows.ShadowPausedLooper.idleIfPaused(ShadowPausedLooper.java:177)
        at org.robolectric.android.controller.ActivityController.visible(ActivityController.java:232)
        at org.robolectric.android.internal.RoboMonitoringInstrumentation.lambda$startActivitySyncInternal$0(RoboMonitoringInstrumentation.java:134)
        at org.robolectric.shadows.ShadowInstrumentation.runOnMainSyncNoIdle(ShadowInstrumentation.java:1201)
        at org.robolectric.android.internal.RoboMonitoringInstrumentation.startActivitySyncInternal(RoboMonitoringInstrumentation.java:120)
        at org.robolectric.android.internal.LocalActivityInvoker.startActivityForResult(LocalActivityInvoker.java:47)
        at org.robolectric.android.internal.LocalActivityInvoker.startActivityForResult(LocalActivityInvoker.java:53)
        at androidx.test.core.app.ActivityScenario.launchInternal(ActivityScenario.java:360)
        at androidx.test.core.app.ActivityScenario.launchActivityForResult(ActivityScenario.java:273)
        at com.ichi2.anki.NoteEditorTest.verifyStartupAndCloseWithNoCollectionDoesNotCrash(NoteEditorTest.kt:184)
```

**Comment by david-allison** [comment]
Oh, you're absolutely correct. Preview makes no sense if no image has been added

**Comment by criticalAY** [comment]
Will make changes to it even the test failed going to the gym right now

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt [hunk 2]
```diff
@@ -650,7 +650,12 @@ class NoteEditor : AnkiActivity(), DeckSelectionListener, SubtitleListener, Tags
         }
         when (keyCode) {
             KeyEvent.KEYCODE_NUMPAD_ENTER, KeyEvent.KEYCODE_ENTER -> if (event.isCtrlPressed) {
-                launchCatchingTask { saveNote() }
+                // disable it in case of image occlusion
+                if (addNote && !canSave()) {
+                    launchCatchingTask { saveNote() }
+                } else {
+                    launchCatchingTask { saveNote() }
+                }
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:658]: This is equivalent to `launchCatchingTask { saveNote() }`

**Review by david-allison — CHANGES_REQUESTED** [review]
Issue with the logic:

```
if (anything) {
  doIt()
} else {
   doIt()
}
```

can be simplified to `doIt()`, as the `else` is exhaustive

**Comment by criticalAY** [comment]
> can be simplified to doIt(), as the else is exhaustive

Right! sorry about that

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt [hunk 3]
```diff
@@ -1004,6 +1011,11 @@ class NoteEditor : AnkiActivity(), DeckSelectionListener, SubtitleListener, Tags
         return super.onCreateOptionsMenu(menu)
     }
 
+    fun canSave(): Boolean {
+        // we can further extend it if required refer :https://github.com/ankidroid/Anki-Android/pull/15030#discussion_r1431330266
+        return currentNotetypeIsImageOcclusion()
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:1016]: move `addNote` into here

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt [hunk 4]
```diff
@@ -1004,6 +1011,11 @@ class NoteEditor : AnkiActivity(), DeckSelectionListener, SubtitleListener, Tags
         return super.onCreateOptionsMenu(menu)
     }
 
+    fun canSave(): Boolean {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:1014]: This is inverted. `currentNotetypeIsImageOcclusion()` means that we can't save, not that we can save

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt [hunk 5]
```diff
@@ -1004,6 +1011,11 @@ class NoteEditor : AnkiActivity(), DeckSelectionListener, SubtitleListener, Tags
...
+        // we can further extend it if required refer :https://github.com/ankidroid/Anki-Android/pull/15030#discussion_r1431330266
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:1015]: no need for the comment

**Review by david-allison — CHANGES_REQUESTED** [review]

**Comment by david-allison** [comment]
Overall:

```kotlin
    private fun canSave(): Boolean = when {
        addNote && currentNotetypeIsImageOcclusion() -> false
        else -> true
    }
```

**Review by david-allison — APPROVED** [review]
Looks good

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt [hunk 6]
```diff
@@ -677,7 +680,9 @@ class NoteEditor : AnkiActivity(), DeckSelectionListener, SubtitleListener, Tags
             KeyEvent.KEYCODE_P -> {
                 if (event.isCtrlPressed) {
                     Timber.i("Ctrl+P: Preview Pressed")
-                    performPreview()
+                    if (canSave()) {
+                        performPreview()
+                    }
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:685]: `canSave()` returns false if in edit mode, so this means that the card can't be previewed in edit mode, which is a regression.

Also, this is really odd to read. Why something can only be previewed if it can be saved? So, I suggest to rename the method

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt [hunk 7]
```diff
@@ -1013,12 +1025,16 @@ class NoteEditor : AnkiActivity(), DeckSelectionListener, SubtitleListener, Tags
             }
             R.id.action_preview -> {
                 Timber.i("NoteEditor:: Preview button pressed")
-                performPreview()
+                if (canSave()) {
+                    performPreview()
+                }
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:1030]: ditto

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt [hunk 8]
```diff
@@ -1013,12 +1025,16 @@ class NoteEditor : AnkiActivity(), DeckSelectionListener, SubtitleListener, Tags
...
                 return true
             }
             R.id.action_save -> {
                 Timber.i("NoteEditor:: Save note button pressed")
-                launchCatchingTask { saveNote() }
+                if (canSave()) {
+                    launchCatchingTask { saveNote() }
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:1036]: by the way this is repeated here and above, shouldn't `saveNote()` check if it `canSave` instead of the caller doing it?

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt [hunk 9]
```diff
@@ -1004,6 +1011,11 @@ class NoteEditor : AnkiActivity(), DeckSelectionListener, SubtitleListener, Tags
         return super.onCreateOptionsMenu(menu)
     }
 
+    private fun canSave(): Boolean = when {
+        addNote && currentNotetypeIsImageOcclusion() -> false
+        else -> true
+    }
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:1017]: nit: IMO if/else would be clearer than `when` if there is only a single conditional branch like this

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt [hunk 10]
```diff
@@ -2025,6 +2041,7 @@ class NoteEditor : AnkiActivity(), DeckSelectionListener, SubtitleListener, Tags
         override fun onItemSelected(parent: AdapterView<*>?, view: View?, pos: Int, id: Long) {
             // If a new column was selected then change the key used to map from mCards to the column TextView
             // Timber.i("NoteEditor:: onItemSelected() fired on mNoteTypeSpinner");
+            invalidateMenu()
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:2044]: add a comment explaining why `invalidateMenu()` is necessary here

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt (hunk 9 above)
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:1017]: add a doc to the method explaining why image occlusion notetypes "can't be saved"

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt [hunk 11]
```diff
@@ -1004,6 +1011,11 @@ class NoteEditor : AnkiActivity(), DeckSelectionListener, SubtitleListener, Tags
         return super.onCreateOptionsMenu(menu)
     }
 
+    private fun canSave(): Boolean = when {
+        addNote && currentNotetypeIsImageOcclusion() -> false
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:1015]: why added notes can't be saved?

**Review by BrayanDSO — CHANGES_REQUESTED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt (hunk 8 above)
Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:1036]: this option is not visible but just the test were failing and other other reason is the keyboard shortcut

Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:1041]: Hence it is never called through the menu

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt (hunk 9 above)
Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt]: both work the same and in case we need to extent it in future we will already have the structure so this works fine I guess

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt [hunk 12]
```diff
@@ -981,13 +986,15 @@ class NoteEditor : AnkiActivity(), DeckSelectionListener, SubtitleListener, Tags
         menuInflater.inflate(R.menu.note_editor, menu)
         if (addNote) {
             menu.findItem(R.id.action_copy_note).isVisible = false
+            menu.findItem(R.id.action_save).isVisible = allowSaveAndPreview()
+            menu.findItem(R.id.action_preview).isVisible = allowSaveAndPreview()
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:990]: allowSaveAndPreview() value should be stored into a variable or use a scoped function to avoid running the method twice

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt [hunk 13]
```diff
@@ -1004,6 +1011,16 @@ class NoteEditor : AnkiActivity(), DeckSelectionListener, SubtitleListener, Tags
         return super.onCreateOptionsMenu(menu)
     }
 
+    /**
+     * When using the options such as image occlusion we don't need the menu's save/preview
+     * option to save/preview the card as it has a built in option and the user is notified
+     * when the card is saved successfully
+     * **/
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:1018]:
```suggestion
     */
```

**Review by BrayanDSO — CHANGES_REQUESTED** [review]

**Review by BrayanDSO — APPROVED** [review]
