### PR TITLE
Lint fixed preferences title length

### LINKED ISSUE #8534: Add CrowdIn and lint rules for Preference Title Length
We should ideally add either/or:

* A lint rule to ensure that preference text in English does not exceed a limit
* Hints for CrowdIn to ensure that our translators do not hit the same issue

We may possibly allow the text to be multiline, I'd be against this, as it's a title and should be succinct.

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/issues/8417#issuecomment-811310435_

### PR DESCRIPTION
**Pull request by prateek-singh-3212**
## Purpose / Description
A lint rule to ensure that preference text in English does not exceed a limit and Hints for CrowdIn to ensure that our translators do not hit the same issue
## Fixes
  Fixes #8534

## Approach
Looped through all the xml files and stored the data in set and hashmap. Then analyzed the data through if else

## How Has This Been Tested?
not tested on a physical device. Done unit testing and run lint checks on terminal
## Learning (optional, can help others)
Android dev submit on Lint: https://www.youtube.com/watch?v=ffH-LD5uP4s&t=808s
Lint explanation in brief (Recommended for a developer who is new to lint ): https://youtu.be/wFe0WZm_xm8
Google GIT Lint Examples : https://android.googlesource.com/platform/tools/base/+/studio-master-dev/lint/libs/lint-checks

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java [hunk 1]
```diff
@@ -0,0 +1,104 @@
...
+            Document doc = dBuilder.parse(input);
+            doc.getDocumentElement().normalize();
+            NodeList nList = doc.getElementsByTagName(TAG_STRING);
+            for (int i = 0; i < nList.getLength(); i++) {
+                Node node = nList.item(i);
+                Element element1 = (Element) node;
+                if (element1.getAttribute(ATTR_NAME).equals(find)) {
+                    String title = node.getTextContent();
+                    stringLengthChecker(context, element, title);
+                }
```
Comment (david-allison-1) [inline lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java:91]: We should do this another way, I'll explain in the top-level comment

File: lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.java [hunk 2]
```diff
@@ -0,0 +1,97 @@
...
+                .run()
+                .expectErrorCount(1)
+                .expect("res/xml/preference_general_invalid.xml:14: Error: Character Length should be less than limit(32) [FixedPreferencesTitleLength]\n" +
+                        "        <CheckBoxPreference\n" +
+                        "        ^\n" +
+                        "1 errors, 0 warnings");
+    }
+
+
+    @Test
```
Comment (david-allison-1) [inline lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.java:88]: tests are great!

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
Great testing! This is currently inefficient O(n^2), with a big constant factor, and we can do better:  (O(n) with minimal constants)

We should also check for the `maxLength=""` attribute on the strings: https://support.crowdin.com/file-formats/android-xml/

----

Current algorithm

* For each `android:title` element:
   * Get the key
   * Load preferences.xml (slow)
   * Loop through `preferences.xml` to find the key
     * Flag if invalid  (O(n))

What we should be doing:

* Loop through each preference title and store each `key` in a `titles: Set<String>`
* Loop through the English preference string file and store the keys in a map: `key (String) -> StringLocation/Element` (I'm unsure, maybe both, maybe the StringLocation if you can get it from the element)
   * Only add to this list if it's known to be bad (> 32 chars || has no maxLength) - this will be most elements

When all files have been analysed:

* Loop through the titles
* Look up the key in the map from key -> title/location
   * If it doesn't exist, it's good
   * If it does exist, throw out an error:
      * If it's > 32 chars
      * If it doesn't have a maxLength=32 attribute

Let me know if you need more guidance on the above

https://github.com/ankidroid/Anki-Android/blob/1543f0f900be78cdf4f80a881e1f0f86e326f113/lint-rules/src/main/java/com/ichi2/anki/lint/rules/DuplicateCrowdInStrings.java#L152-L153

https://github.com/ankidroid/Anki-Android/blob/1543f0f900be78cdf4f80a881e1f0f86e326f113/lint-rules/src/main/java/com/ichi2/anki/lint/rules/DuplicateCrowdInStrings.java#L97

The two lines above should be useful in seeing the structure that we should be aiming for

File: lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesCrowdInTitleLength.java [hunk 3]
```diff
@@ -0,0 +1,28 @@
+package com.ichi2.anki.lint.rules;
+
+import com.android.tools.lint.detector.api.Implementation;
+import com.android.tools.lint.detector.api.Issue;
+import com.android.tools.lint.detector.api.ResourceXmlDetector;
+import com.android.tools.lint.detector.api.Scope;
+import com.google.common.annotations.VisibleForTesting;
+import com.ichi2.anki.lint.utils.Constants;
+
+public class FixedPreferencesCrowdInTitleLength extends ResourceXmlDetector {
```
Comment (david-allison-1) [inline lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesCrowdInTitleLength.java:10]: I think this can be deleted?

File: lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java [hunk 4]
```diff
@@ -0,0 +1,104 @@
...
+    @Nullable
+    @Override
+    public Collection<String> getApplicableElements() {
+        return XmlScannerConstants.ALL;
+    }
+
+
+    @Override
+    public void visitElement(XmlContext context, Element element) {
+        if ("xml".equals(context.file.getParentFile().getName()) && element.hasAttribute(ATTR_TITLE)) {
```
[the remark this answers is not in the document]
Comment (prateek-singh-3212) [reply lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java:63]: It is checking 2 conditions:
1. If the current file is parent file of XML folder.(We can remove this because I have assigned that folderType == ResourceFolderType.XML in appliesTo method).
2. Scanning all the elements of XML file and checks that element contains android:title attribute If yes then go ahead.

File: lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java [hunk 5]
```diff
@@ -0,0 +1,104 @@
...
+    private static final String EXPLANATION = "Characters length is greater then limit(32). Character size greater than" +
+            "limit will impact the devices whose screen size is small. Please refactor the Title";
+    private static final Implementation implementation = new Implementation(FixedPreferencesTitleLength.class, Scope.RESOURCE_FILE_SCOPE);
+    public static final Issue ISSUE = Issue.create(
+            ID,
+            DESCRIPTION,
+            EXPLANATION,
+            Constants.ANKI_TIME_CATEGORY,
+            Constants.ANKI_TIME_PRIORITY,
+            Constants.ANKI_TIME_SEVERITY,
```
[the remark this answers is not in the document]
Comment (prateek-singh-3212) [reply lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java:43]: Okay

**Comment by prateek-singh-3212** [comment]
> Great testing! This is currently inefficient O(n^2), with a big constant factor, and we can do better: (O(n) with minimal constants)
> 
> We should also check for the `maxLength=""` attribute on the strings: https://support.crowdin.com/file-formats/android-xml/
> 
> Current algorithm
> 
>     * For each `android:title` element:
>       
>       * Get the key
>       * Load preferences.xml (slow)
>       * Loop through `preferences.xml` to find the key
>         
>         * Flag if invalid  (O(n))
> 
> 
> What we should be doing:
> 
>     * Loop through each preference title and store each `key` in a `titles: Set<String>`
> 
>     * Loop through the English preference string file and store the keys in a map: `key (String) -> StringLocation/Element` (I'm unsure, maybe both, maybe the StringLocation if you can get it from the element)
>       
>       * Only add to this list if it's known to be bad (> 32 chars || has no maxLength) - this will be most elements
> 
> 
> When all files have been analysed:
> 
>     * Loop through the titles
> 
>     * Look up the key in the map from key -> title/location
>       
>       * If it doesn't exist, it's good
>       * If it does exist, throw out an error:
>         
>         * If it's > 32 chars
>         * If it doesn't have a maxLength=32 attribute
> 
> 
> Let me know if you need more guidance on the above
> 
> https://github.com/ankidroid/Anki-Android/blob/1543f0f900be78cdf4f80a881e1f0f86e326f113/lint-rules/src/main/java/com/ichi2/anki/lint/rules/DuplicateCrowdInStrings.java#L152-L153
> 
> https://github.com/ankidroid/Anki-Android/blob/1543f0f900be78cdf4f80a881e1f0f86e326f113/lint-rules/src/main/java/com/ichi2/anki/lint/rules/DuplicateCrowdInStrings.java#L97
> 
> The two lines above should be useful in seeing the structure that we should be aiming for

Okay, I have noted down all the points you described above. For now, I am not having any doubt but in the future, if I have any doubt then I will let you know.

File: lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesCrowdInTitleLength.java (hunk 3 above)
Comment (prateek-singh-3212) [reply lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesCrowdInTitleLength.java:10]: This file is part of the current issue and I am working on it.

**Comment by david-allison-1** [comment]
> Hi David,
> I am working on lint issue. I am unable to understand that why you to told to (>32 chars || has no maxLength).

Because those are all the badly named preferences.

We don't know which ones are titles at that point (there's a chance we analyze the `strings` file before the `preference` XML), so all we can do is collect the invalid strings, and later filter them to the list of invalid titles

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
Much nicer!

Main point: since the lint check is working, let's extract the limit and increase it to 42

File: lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java [hunk 6]
```diff
@@ -0,0 +1,121 @@
...
+    public void afterCheckEachProject(@NotNull Context context) {
+        for (String title : xmlData) {
+            if (! valuesData.containsKey(title)) {
+                continue;
+            }
+
+           /* 1. Checks the element has maxLength and checks that maxLength equals 32
+              2. Checks the String has more than 32 characters or not
+            */
+            if ((valuesData.get(title).getFirst().hasAttribute(ATTR_MAX_LENGTH) &&
```
[the remark this answers is not in the document]
Comment (prateek-singh-3212) [reply lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java:113]: Sure

File: lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java [hunk 7]
```diff
@@ -0,0 +1,121 @@
...
+                    !valuesData.get(title).getFirst().getAttribute(ATTR_MAX_LENGTH).equals("32") ||
```
[the remark this answers is not in the document]
Comment (prateek-singh-3212) [reply lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java:114]: Okay

File: lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java [hunk 8]
```diff
@@ -0,0 +1,121 @@
...
+                    valuesData.get(title).getFirst().getTextContent().length() >= 32)) {
+                context.report(ISSUE, valuesData.get(title).getSecond().resolve(), " "+title +" " +!valuesData.get(title).getFirst().getAttribute(ATTR_MAX_LENGTH).equals("32") + " " +( valuesData.get(title).getFirst().getTextContent().length() >= 32));
```
[the remark this answers is not in the document]
Comment (prateek-singh-3212) [reply lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java:116]: @david-allison-1 are we expecting all the (Title )strings in preferences.xml file to have maxLength=32 attribute?

[the remark this answers is not in the document]
Comment (david-allison-1) [reply lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java:116]: Yes, but let's increase the limit to 42

[the remark this answers is not in the document]
Comment (prateek-singh-3212) [reply lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java:116]: Okay, I'll change the limit to 42.

File: lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.java [hunk 9]
```diff
@@ -30,7 +31,6 @@
         issues.add(DirectCalendarInstanceUsage.ISSUE);
         issues.add(DirectDateInstantiation.ISSUE);
         issues.add(DirectGregorianInstantiation.ISSUE);
-        issues.add(DirectSnackbarMakeUsage.ISSUE);
```
Comment (david-allison-1) [inline lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.java:33]: This shouldn't be removed

File: lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java [hunk 10]
```diff
@@ -0,0 +1,142 @@
...
+
+public class FixedPreferencesTitleLength extends ResourceXmlDetector implements XmlScanner {
+
+    @VisibleForTesting
+    static final String ID = "FixedPreferencesTitleLength";
+    private static final int FIXED_LENGTH = 42;
+    @VisibleForTesting
+    static final String DESCRIPTION = String.format("Preference titles should be less than %d characters", FIXED_LENGTH);
+    // Around 42 is a hard max on emulators, likely smaller in reality, so use a buffer
+    private static final String EXPLANATION = "A title with more than 32 characters may fail to display on smaller screens";
```
Comment (david-allison-1) [inline lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java:51]: Concat this string 

```suggestion
    private static final String EXPLANATION = "A title with more than 32 characters may fail to display on smaller screens";
```

File: lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java [hunk 11]
```diff
@@ -0,0 +1,142 @@
...
+            xmlData.add(stringName);
+            return;
+        }
+
+        /* 1. This condition checks that current file has values as a parent file.
+           2. Checks the name of present working file(10-preferences.xml) and ignore the rest of files in values.
+           3. It skips the resources  tag in xml file.
+           4. Add to this list if it's known to be bad (> 32 chars || has no maxLength)
+         */
+        if ("values".equals(context.file.getParentFile().getName()) &&
```
Comment (david-allison-1) [inline lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java:97]: Use one `if` for each of these three conditionals into an and return early if they're not hit

File: lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java [hunk 12]
```diff
@@ -0,0 +1,142 @@
...
+    @Override
+    public boolean appliesTo(ResourceFolderType folderType) {
+        return (folderType == ResourceFolderType.XML || folderType == ResourceFolderType.VALUES);
+    }
+
+
+    @Override
+    public void afterCheckEachProject(@NotNull Context context) {
+        for (String title : xmlData) {
+            if (! valuesData.containsKey(title)) {
```
Comment (david-allison-1) [inline lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java:119]:
```suggestion
            if (!valuesData.containsKey(title)) {
```

File: lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java [hunk 13]
```diff
@@ -0,0 +1,142 @@
...
+                    context.report(ISSUE, stringData.getSecond().resolve(), message);
+                }
+            } else {
+                String message = String.format(Locale.ENGLISH, "Preference title '%s' is missing \"maxLength=%d\" attribute", title, FIXED_LENGTH);
+                context.report(ISSUE, stringData.getSecond().resolve(), message);
+            }
+
+            if (element.getTextContent().length() >= FIXED_LENGTH) {
+                String message = String.format(Locale.ENGLISH, "Preference title '%s' must be less than %d characters (currently %d)", title, FIXED_LENGTH, element.getTextContent().length());
+                context.report(ISSUE, stringData.getSecond().resolve(), message);
```
Comment (david-allison-1) [inline lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java:138]: I think you likely want two issues with different IDs here

File: lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java [hunk 14]
```diff
@@ -0,0 +1,142 @@
...
+import java.util.HashSet;
+import java.util.Locale;
+import java.util.Map;
+import java.util.Set;
+
+public class FixedPreferencesTitleLength extends ResourceXmlDetector implements XmlScanner {
+
+    @VisibleForTesting
+    static final String ID = "FixedPreferencesTitleLength";
+    private static final int FIXED_LENGTH = 42;
```
Comment (david-allison-1) [inline lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java:47]: rename (possibly `PREFERENCE_TITLE_MAX_LENGTH`)

I'd use 41 and perform a `>` (or a `<=`)

Let's change `maxLength=41`, as that should fix this

File: lint-rules/src/main/java/com/ichi2/anki/lint/utils/Constants.java [hunk 15]
```diff
@@ -2,7 +2,6 @@
 
 import com.android.tools.lint.detector.api.Category;
 import com.android.tools.lint.detector.api.Severity;
```
Comment (david-allison-1) [inline lint-rules/src/main/java/com/ichi2/anki/lint/utils/Constants.java:4]: try to avoid spacing changes

Comment (david-allison-1) [inline lint-rules/src/main/java/com/ichi2/anki/lint/utils/Constants.java:4]: try to avoid spacing changes

File: lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java [hunk 16]
```diff
@@ -0,0 +1,142 @@
...
+            if (! valuesData.containsKey(title)) {
+                continue;
+            }
+
+            Pair<Element, Location.Handle> stringData = valuesData.get(title);
+            Element element = stringData.getFirst();
+
+            if (element.hasAttribute(ATTR_MAX_LENGTH)) {
+                if (!element.getAttribute(ATTR_MAX_LENGTH).equals(FIXED_LENGTH)) {
+                    String message = String.format(Locale.ENGLISH, "Preference title '%s' is having maxLength=%s it should contain maxLength=%d", title, element.getAttribute(ATTR_MAX_LENGTH), FIXED_LENGTH);
```
Comment (david-allison-1) [inline lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java:128]:
```suggestion
                    String message = String.format(Locale.ENGLISH, "Preference title '%s' has maxLength=%s instead of maxLength=%d", title, element.getAttribute(ATTR_MAX_LENGTH), FIXED_LENGTH);
```

File: lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java [hunk 17]
```diff
@@ -0,0 +1,142 @@
...
+                    context.report(ISSUE, stringData.getSecond().resolve(), message);
+                }
+            } else {
+                String message = String.format(Locale.ENGLISH, "Preference title '%s' is missing \"maxLength=%d\" attribute", title, FIXED_LENGTH);
+                context.report(ISSUE, stringData.getSecond().resolve(), message);
```
Comment (david-allison-1) [inline lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java:133]: Optional: Adding a `LintFix` here would be useful if possible, as it will allow us to automate fixing the lint errors

**Review by david-allison-1 — COMMENTED** [review]
Looking good!

You'll need a pull request, or a rebase + commit before the current set of commits fixing the lint errors. 

Would you like me to take this on?

**Comment by prateek-singh-3212** [comment]
> Would you like me to take this on?

Thanks for asking. I am not having any problem in doing work on this PR. I hope that I am not annoying you by requesting you to review the code. I will clean the commit history and then push the final changes.

Sorry I am bit busy today that's why I am unable to reply.

**Comment by david-allison-1** [comment]
> > Would you like me to take this on?
> 
> Thanks for asking. I am not having any problem in doing work on this PR. I hope that I am not annoying you by requesting you to review the code. I will clean the commit history and then push the final changes.
> 
> Sorry I am bit busy today that's why I am unable to reply.

Not at all - happy to do this :)

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
There's quite a few irrelevant changes in the diff. Could you revert these (typically via `git rebase`) and rebase your branch onto master to get rid of these.

File: lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.java (hunk 9 above)
Comment (david-allison-1) [reply lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.java:33]: This is still removed

**Review by david-allison-1 — COMMENTED** [review]
Just to note: ping me and follow up via PM in Discord when it's ready for review. 

I still feel a few comments are pending. I really appreciate the effort and can't wait to see this in. It'll massively improve the app for our translators

**Comment by prateek-singh-3212** [comment]
> ping me and follow up via PM in Discord when it's ready for review.

Sure,

>I still feel a few comments are pending. I really appreciate the effort and can't wait to see this in. It'll massively improve the app for our translators

Sorry, I am working on this whenever I am getting free time. I will let you know whenever it is ready for review  😊

**Comment by prateek-singh-3212** [comment]
@david-allison-1 please suggest a new Title for the following:

 `    <string name="day_offset_with_description">Start of next day (0 is midnight, 23 is 11PM)</string>`[url](https://github.com/ankidroid/Anki-Android/blob/6d68424cd48ab0a702da949bd49a70eeb05f0dfd/AnkiDroid/src/main/res/values/10-preferences.xml#L160)

`    <string name="deck_conf_deck_description">Deck description (affects current deck only)</string>`[url](https://github.com/ankidroid/Anki-Android/blob/6d68424cd48ab0a702da949bd49a70eeb05f0dfd/AnkiDroid/src/main/res/values/10-preferences.xml#L205)

`    <string name="deck_conf_reminders_enabled">Enable reminder notifications for decks in this deck group</string>`[url](https://github.com/ankidroid/Anki-Android/blob/6d68424cd48ab0a702da949bd49a70eeb05f0dfd/AnkiDroid/src/main/res/values/10-preferences.xml#L269)

**Comment by david-allison-1** [comment]
@prateek-singh-3212 hold off until other maintainers have chimed in

* Enable notifications for this deck group
* Deck description (current deck only)
* Start of next day 

The final one is to be fixed properly in #8417

@mikehardy @Arthur-Milchior @infinyte7  - opinions on the above?

**Comment by prateek-singh-3212** [comment]
> @prateek-singh-3212, do these work for you?

Yes, it is absolutely fine.

**Comment by mikehardy** [comment]
@david-allison-1 those all look great to me as shortenings

File: lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java [hunk 18]
```diff
@@ -0,0 +1,162 @@
...
+        for (String title : xmlData) {
+            if (!valuesData.containsKey(title)) {
+                continue;
+            }
+
+            Pair<Element, Location.Handle> stringData = valuesData.get(title);
+            Element element = stringData.getFirst();
+
+            if (element.hasAttribute(ATTR_MAX_LENGTH)) {
+                if (!element.getAttribute(ATTR_MAX_LENGTH).equals(Integer.toString(PREFERENCE_TITLE_MAX_LENGTH))) {
```
Comment (Arthur-Milchior) [inline lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java:147]: I find this kind of nested if hard to read.

I'd appreciate in this case if you could do:
* if no max_length
* elseif wrong max_length

File: lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java [hunk 19]
```diff
@@ -0,0 +1,162 @@
...
+    static final String ID_TITLE_LENGTH = "FixedPreferencesTitleLength";
+    @VisibleForTesting
+    static final String ID_MAX_LENGTH = "PreferencesTitleMaxLengthAttr";
+    private static final int PREFERENCE_TITLE_MAX_LENGTH = 41;
+    @VisibleForTesting
+    static final String DESCRIPTION_TITLE_LENGTH = String.format("Preference titles should be less than %d characters", PREFERENCE_TITLE_MAX_LENGTH);
+    @VisibleForTesting
+    static final String DESCRIPTION_MAX_LENGTH = String.format("Preference titles should contain maxLength=\"%d\" attribute", PREFERENCE_TITLE_MAX_LENGTH);
+    // Around 42 is a hard max on emulators, likely smaller in reality, so use a buffer
+    private static final String EXPLANATION_TITLE_LENGTH = "A title with more than 41 characters may fail " +
```
Comment (Arthur-Milchior) [inline lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java:55]: So that the rule do not appear to be arbitrary, I'd like that the text message explain where this 41 come from. Whether it is only manual testing or whether there is a source. Probably good in the commit message too.

Comment (Arthur-Milchior) [reply lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java:55]: Other question, does this limit make sens in all languages? I am ignorant, and I can easily imagine things go wrong with non latin-based language. I don't expect RTL to be more of a problem in itself. However, I'm not sure that the notion of counting letters as a hint for space make as much sens in all locales. 
I'm not even sure that UTF-8 character that takes more than one byte, could you add test for that please?

**Review by Arthur-Milchior — COMMENTED** [review]
I didn't know it was an issue, thanks a lot for solving it. A few extra thought.

I wonder whether it's a first time where the documents are videos instead of text. I must admit that it praticable guarantee that I will not go look at them. But that's a question of personal preferences.
If you have any documents about title's best practice, it would be appreciated too.

File: lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java (hunk 18 above)
Comment (prateek-singh-3212) [reply lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java:147]: sure, I will change this nesting.

**Comment by infinyte7** [comment]
Also look good to me.

File: lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java (hunk 19 above)
Comment (prateek-singh-3212) [reply lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java:55]: >  where this 41 come from. Whether it is only manual testing or whether there is a source.

I came from manual testing. Tested on the 2.8-inch device by David.
Reference: https://github.com/ankidroid/Anki-Android/issues/8417#issuecomment-816308255

Comment (prateek-singh-3212) [reply lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java:55]: > Other question, does this limit make sens in all languages? I am ignorant, and I can easily imagine things go wrong with non latin-based language. I don't expect RTL to be more of a problem in itself. 


To be honest I didn't have that much idea about crowdin. How it deals with non-latin based Languages but I found some resources related to it hope it helps.
References: https://support.crowdin.com/file-formats/android-xml/#custom-attributes
https://support.crowdin.com/files-management/ (String Editing)

Comment (prateek-singh-3212) [reply lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java:55]: > I'm not even sure that UTF-8 character that takes more than one byte, could you add test for that please?

Sure, I will add a test of UTF-8 characters.

File: lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java [hunk 20]
```diff
@@ -0,0 +1,164 @@
...
```
Comment (david-allison-1) [inline lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java:57]: Please concat or format the 41 here

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
This looks great!

Could you rebase and reorder the two commits (so we don't have a commit which fails the lint check in the history)

After that, more than happy to approve, looks great!

File: lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java (hunk 20 above)
Comment (prateek-singh-3212) [reply lint-rules/src/main/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLength.java:57]: Okay,  😅

**Comment by prateek-singh-3212** [comment]
@david-allison-1 Should I squash both commits?

**Comment by david-allison-1** [comment]
No, two commits are good, just reorder them

**Review by david-allison-1 — APPROVED** [review]
Beautiful! Maintainers: Rebase & merge

**Comment by oakkitten** [comment]
why not simply allow multiline titles? i realize that it's against the guidelines, but it doesn't look bad at all and allows having titles that make sense. it's sometimes hard to make a sensible title in e.g. russian when the first line fits only two words. 

also you don't have to worry about devices with smaller screens/larger "display size" settings, languages with longer words that might not break well (e.g. german) or languages with wider letters (e.g. russian) etc

File: lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.java [hunk 21]
```diff
@@ -0,0 +1,133 @@
...
+            "    <string name=\"app_name\">app_name</string>\n" +
+            "    <string name=\"pref_cat_general_summ\">pref_cat_general_summ</string>\n" +
+            "<!--Not contains maxLength attribute but having value 55-->\n" +
+            "    <string name=\"button_sync\" maxLength=\"55\">button_sync</string>\n" +
+            "<!--This is correct because it contains maxLength=41 and character length is less than 42-->\n" +
+            "    <string name=\"sync_account\" maxLength=\"41\">sync_account</string>\n" +
+            "    <string name=\"sync_account_summ_logged_out\">sync_account_summ</string>\n" +
+            "    <string name=\"sync_fetch_missing_media_summ\">sync_fetch_missing</string>\n" +
+            "<!--Not contains maxLength=41 attribute but character length is greater than 32 and contains UTF-8 character-->\n" +
+            "    <string name=\"more_characters_than_limit\"  maxLength=\"41\">This String contains character more than limit \u00A3</string>\n" +
```
Comment (Arthur-Milchior) [inline lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.java:52]: I fear I was misunderstood here.
What I cared about is a string of, let's say, 30 characters with only wide characters. For example 30 copies of `\u00A3` takes 60 bytes in UTF-8 but is only 30 character long. So what I wanted to check is whether this was correctly counted and that the test still find this to be a valid string

**Review by Arthur-Milchior — APPROVED** [review]
Same as David: beautiful work.
I'll merge it as it's clearly an improvement. However, I fear my test regarding UTF-8 was not understood properly. I'd appreciate if you can correct it and create a new PR with it. It's not blocking, so this clearly can be merged.

@oakkitten Thanks for your input. Do you have more context about it? A screenshot, or a text explaining the decision to go against the guideline? Or even the guideline itself, I don't know it actually, only that it seems to make sens to keep title short and on a single line

If there is a need to go against the guideline, justified somehow, for example by a translator, we can always reconsider or grant an exception. Still seems better to at least warn when this occur

**Comment by oakkitten** [comment]
i'm not quite sure if read an actual guideline somewhere or just assumed it to be one as api-wise titles are single-line by default.

anyhow, here's a screenshot from Gmail where you can see that they do multiline titles, and also that another option not doing multiline titles fails to fit



as you can hopefully see the green part looks just fine. trying to cram everything into one line can lead to poor results and in some cases like this just fails to work

**Comment by Arthur-Milchior** [comment]
Thanks a lot for the screenshot.

I guess we'll see whether we get to see if it raises any issues with translators or when creating new strings. We have mostly short title but it's hard to predict whether something will need a lot of space to translate

**Comment by oakkitten** [comment]
btw there are some current AnkiDroid preference titles that don't fit my screen and are ellipsized, and i'm not even using the largest "display size" setting. E.g. "share usage statistics" doesn't fit, and in translation it's these same three words, just in russian. i guess you can make it just "usage statistics" and then clarify in the summary what it's about. but a good checkable preference title must be a verb phrase imo

**Comment by Arthur-Milchior** [comment]
Thanks for this feedback @oakkitten. I didn't understand that it was already a problem in your language.

Ideally, you can go on crowdin and correct it, but we surely should find a way to automatize it to let translators in all languages know what should be done

File: lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.java (hunk 21 above)
Comment (prateek-singh-3212) [reply lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.java:52]: Okay, I misunderstood your explanation but now it is clear I will make a new PR shortly.

**Comment by oakkitten** [comment]
"share usage statistics" is a good setting name, i wouldn't want to change it. i would rather i can read the entire text.

you can tell that some translators are trying to fit text inside all single line UI elements. e.g.

> Notifications → Notify when → More than 10 cards due

becomes

> Notifications → Show which ones → When >10 cards

This does fit a single line but without the “due” it makes no sense.

(to be frank, a few settings are quite confusing in english as well. e.g.

* New card position. this implies there's some list of cards and when you create a new card this controls where it is placed. i'm guessing this is absolutely not what this setting is about
* Learn ahead limit. i have no idea what this is
* Timebox time limit. same.
* App bar buttons. i think AnkiDroid is the only app i've got that calls the toolbar "app bar"
* Day theme → Plain. what does a plain theme mean? the regular theme is pretty plain too. “grayscale” might be more descriptive
* "Center align. Center the content of cards vertically". the title here gives no useful information. the summary has the needed information and is a full sentence. Why not change summary to title, and remove summary altogether? It feels like every preference in AnkiDroid has to have a summary, even if it adds no value
* "Disable Single-Field Edit Mode. Allows 'Cloze Deletion' context menu when in landscape mode". i.. just don't understand any of this

and i can go on...)

**Comment by mikehardy** [comment]
Hi there!

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for April 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged in April)

Thanks!
