### PR TITLE
NF: Correct `reps` documentation

### LINKED ISSUE #6830: Number of reps increased in Card Content Provider get card
###### Reproduction Steps

1. activate time box
1. Start reviewing
1. In CardContentProvider, uses SCHEDULE and asks for `n` cards.
1. On AnkiDroid wait until the end of the time box and review a card
1. You'll be told you have reviewed `n+1` cards.

###### Expected Result
It will state that 0 cards have been seen today

###### Actual Result
The scheduler will state that `n` cards have been reviewed today, while actually no cards have been answered yet

###### Research

This is due to the fact that the increase occurs on `getCards` instead of being on `answerCards`. This is also the case upstream, but upstream there is now CardContentProvider; instead there are add-ons, and add-on user can deal with it however they want (probably ignoring totally this question), while CardContentProvider users are not supposed to deal with it

This is also interesting to note that SchedV2.mReps is only used in the timebox and literally nowhere else. The main screen uses a revlog query to check  the numbero f acrds seen today. I would suggest doing the same thing for timebox, but upstream uses revs here and I know we follow upstream

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
`reps` used to have a different meaning than today. I'd actually love to rename this variable, but it's the name used in upstream, so I guess it would not be accepted.

I considered adding more information, such as the fact that in practice, it mostly means that this value is reset when ankidroid restart, with maybe some exceptions. Or that we should only care about the difference between values at different point in time and not about the actual value of this variable. But actually it does not matter. It's only used for timebox and has 3 occurrences in the codebase. Any more documentation would be overkill.

Fixed #6830. Well actually, it was fixed in
7a65160e0e23e20080091a30abdd4c05fc610e06 long ago, but the documen tation did not reflect that. So let's claim I just fixed a 5 yo bug!

### CODE REVIEW

**Comment by david-allison** [comment]
> reps used to have a different meaning than today. I'd actually love to rename this variable, but it's the name used in upstream, so I guess it would not be accepted.

Rename it, it's deprecated upstream

I'd prefer something which relates it to its intended usage in the timebox.

File: AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt [hunk 1]
```diff
@@ -209,8 +209,8 @@ open class Scheduler(
             QueuedCards.Queue.UNRECOGNIZED, null -> TODO("unrecognized queue")
         }
 
-    /** @return Number of repetitions today. Note that a repetition is the fact that the scheduler sent a card, and not the fact that the card was answered.
-     * So buried, suspended, ... cards are also counted as repetitions.
+    /**
+     * Number of card answered since this scheduler object was created.
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt:213]:
```suggestion
     * Number of calls to [answerCard] since creation of this scheduler object.
```

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt:213]: `number of card answered` is incorrect grammatically => "number of cards answered"

**Comment by Arthur-Milchior** [comment]
Seriously.
For once that I pay special attention to follow upstream in order not to get nitted, I've to change the name:p

**Review by BrayanDSO — APPROVED** [review]

File: AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt [hunk 2]
```diff
@@ -209,10 +209,11 @@ open class Scheduler(
...
         }
 
-    /** @return Number of repetitions today. Note that a repetition is the fact that the scheduler sent a card, and not the fact that the card was answered.
-     * So buried, suspended, ... cards are also counted as repetitions.
+    /**
+     * Number of [answerCard] was called since this scheduler object was created.
+     * Note that when the user undo a review, this number is not decremented.
      */
-    var reps: Int = 0
+    var numberOfAnswerRecorded: Int = 0
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt:216]: I'm not an english native, but I find this a little odd to read. Not blocking, but I'll leave the final decision of merging to somebody else

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt:216]: `numberOfAnswersRecorded` is the correction

@BrayanDSO does the fix still sound odd?

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt:216]: numberOfAnswersRecorded is the correct one to my "ears"

**Review by mikehardy — APPROVED** [review]
@Arthur-Milchior just no getting this through without little naming battles 😆 
If you push a commit that uses `numberOfAnswersRecorded` I'd say merge at will

**Review by mikehardy — APPROVED** [review]
I believe if there are naming nits and they are the only thing holding something back, it's okay to just finish them and push them and merge, so Arthur hopefully you agree - I pushed a change with the consensus numberOfAnswersRecorded name and I'm queueing this for merge

so none of us have to pay any more attention to it :-)

Cheers
