### PR TITLE
Note editor cloze more available

### LINKED ISSUE #6494: Cloze deletion popup does not seem to work on Xiaomi
###### Reproduction Steps

1. Use a Xiaomi device
2. Highlight text in the edit note screen on cloze type note
3. Look for the cloze deletion entry on the text popup

###### Expected Result

Cloze deletion option exists in the popup

###### Actual Result

No ability to add a cloze deletion

###### Debug info

User reports (lots of them!) on google play store. It appears we have finally narrowed it to Xiaomi (at least Redmi Note 8) devices.

###### Research

Perhaps the absolutely awful Xiaomi API support and broken power management features are to blame https://dontkillmyapp.com/xiaomi - I asked a user to try mitigation but they did not report conclusive results - I don't have a Xiaomi to try because who would be a broken Android implementation?

Perhaps the ability to do cloze deletion could be duplicated in the paperclip menu so it doesn't rely on system APIs that Xiaomi cripples?

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by mikehardy**
## Purpose / Description
We have been getting terrible reviews, all focused on cloze deletion, from Vietnam.

I just couldn't figure it out.

Finally it turns out it's Xiaomi devices! They apparently just don't do action mode callbacks well.

Also we didn't set action mode callbacks for lower APIs so anything below API23 was out of luck too.

This PR adds cloze as an option on the paperclip menu so it's usable everywhere now.

## Fixes
Fixes #6494 

## Approach
If it's a cloze type card, make a cloze menu item visible on the paperclip menu, and hook that to all the existing cloze insertion code

## How Has This Been Tested?
For both cloze and non-cloze card types, on an API29 and API22 emulator, verify that cloze deletion is visible when it should be on the paperclip menu, and that it works.

I will note there is some crap behavior on API22 where your text selection goes away when any other activity on the screen happens, but that also happened when I tried context menus, so we just can't win there. At least users can actually get a properly formatted set of cloze brackets automatically now.

## Learning (optional, can help others)
Xiaomi is a terrible Android vendor. Seriously, they implement multiple Android APIs incorrectly, over years, with no fixes.

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by mikehardy** [comment]
I will cherry-pick this to release-2.11 post-merge. We get a negative review on this every 1-2 days, and I don't feel taking existing cloze code (which would be dangerous to change) and just hooking it in one more place on the UI (which is trivial) is too risky.

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java [hunk 1]
```diff
@@ -1816,7 +1816,7 @@ private void convertSelectedTextToCloze(FieldEditText textBox) {
         String clozeOpenBracket = "{{c" + (nextClozeIndex) + "::";
 
         // Update text field with updated text and selection
-        textBox.setText(beforeText + clozeOpenBracket + selectedText + "}}" + afterText);
+        textBox.setText(String.format("%s%s%s}}%s", beforeText, clozeOpenBracket, selectedText, afterText));
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java:1834]: This is mostly pointless but it killed an i18n lint warning without disabling the warning :shrug:
