### PR TITLE
fix(split-cardbrowser): list is empty when toggling to notes only mode

### LINKED ISSUE #19924: [Split Browser] : java.util.NoSuchElementException: List is empty when toggling Card/Notes
I got an exception changing to notes only mode. My be related.

```
2025-12-13 21:55:20.521 13278-13278 CardBrowserViewModel    com.ichi2.anki.debug                 I  Toggle select all / none
2025-12-13 21:55:20.521 13278-13278 CardBrowserViewModel    com.ichi2.anki.debug                 D  selecting none
2025-12-13 21:55:20.523 13278-13278 CardBrowse...lectedRows com.ichi2.anki.debug                 D  refreshed selected rows
2025-12-13 21:55:20.523 13278-13278 CardBrowser             com.ichi2.anki.debug                 D  onSelectionChanged
2025-12-13 21:55:20.523 13278-13278 CardBrowser             com.ichi2.anki.debug                 D  updateMultiselectMenu()
2025-12-13 21:55:22.015 13278-13306 chi2.anki.debug         com.ichi2.anki.debug                 I  Explicit concurrent mark compact GC freed 1390KB AllocSpace bytes, 0(0B) LOS objects, 49% free, 16MB/33MB, paused 268us,2.142ms total 47.843ms
2025-12-13 21:55:22.116 13278-13306 LeakCanary              com.ichi2.anki.debug                 D  Not showing notification: already requested missing POST_NOTIFICATIONS permission.
2025-12-13 21:55:24.157 13278-13306 chi2.anki.debug         com.ichi2.anki.debug                 I  Explicit concurrent mark compact GC freed 628KB AllocSpace bytes, 0(0B) LOS objects, 49% free, 16MB/32MB, paused 169us,1.925ms total 38.856ms
2025-12-13 21:55:24.259 13278-13306 LeakCanary              com.ichi2.anki.debug                 D  Not showing notification: already requested missing POST_NOTIFICATIONS permission.
2025-12-13 21:55:25.928 13278-13278 WindowOnBackDispatcher  com.ichi2.anki.debug                 W  sendCancelIfRunning: isInProgress=false callback=android.widget.PopupWindow$PopupDecorView$$ExternalSyntheticLambda1@c00aad9
2025-12-13 21:55:26.302 13278-13306 chi2.anki.debug         com.ichi2.anki.debug                 I  Explicit concurrent mark compact GC freed 456KB AllocSpace bytes, 0(0B) LOS objects, 49% free, 16MB/32MB, paused 173us,1.602ms total 40.681ms
2025-12-13 21:55:26.405 13278-13306 LeakCanary              com.ichi2.anki.debug                 D  Not showing notification: already requested missing POST_NOTIFICATIONS permission.
2025-12-13 21:55:27.388 13278-13278 CardBrowser             com.ichi2.anki.debug                 D  onSelectionChanged
2025-12-13 21:55:27.389 13278-13278 CardBrowser             com.ichi2.anki.debug                 D  updateMultiselectMenu()
2025-12-13 21:55:27.390 13278-13278 CardBrowser             com.ichi2.anki.debug                 D  end multiselect mode
2025-12-13 21:55:27.419 13278-13278 CardBrowser             com.ichi2.anki.debug                 D  onCreateOptionsMenu()
2025-12-13 21:55:27.429 13278-13278 CardBrowser             com.ichi2.anki.debug                 D  onSelectionChanged
2025-12-13 21:55:27.429 13278-13278 CardBrowser             com.ichi2.anki.debug                 D  updateMultiselectMenu()
2025-12-13 21:55:28.444 13278-13306 chi2.anki.debug         com.ichi2.anki.debug                 I  Explicit concurrent mark compact GC freed 525KB AllocSpace bytes, 0(0B) LOS objects, 49% free, 16MB/32MB, paused 157us,1.289ms total 35.826ms
2025-12-13 21:55:28.546 13278-13306 LeakCanary              com.ichi2.anki.debug                 D  Not showing notification: already requested missing POST_NOTIFICATIONS permission.
2025-12-13 21:55:30.586 13278-13306 chi2.anki.debug         com.ichi2.anki.debug                 I  Explicit concurrent mark compact GC freed 670KB AllocSpace bytes, 0(0B) LOS objects, 49% free, 16MB/33MB, paused 190us,1.201ms total 36.242ms
2025-12-13 21:55:30.688 13278-13306 LeakCanary              com.ichi2.anki.debug                 D  Not showing notification: already requested missing POST_NOTIFICATIONS permission.
2025-12-13 21:55:30.967 13278-13278 NoteEditorFragment      com.ichi2.anki.debug                 D  NoteEditor::onMenuItemSelected
2025-12-13 21:55:30.967 13278-13278 CardBrowse...$setupMenu com.ichi2.anki.debug                 D  CardBrowserFragment::onMenuItemSelected
2025-12-13 21:55:30.968 13278-13278 BrowserOpt...$Companion com.ichi2.anki.debug                 I  BrowserOptionsDialog::newInstance
2025-12-13 21:55:30.969 13278-13278 NoteEditorFragment      com.ichi2.anki.debug                 D  NoteEditor::onMenuItemSelected
2025-12-13 21:55:30.969 13278-13278 WindowOnBackDispatcher  com.ichi2.anki.debug                 W  sendCancelIfRunning: isInProgress=false callback=android.widget.PopupWindow$PopupDecorView$$ExternalSyntheticLambda1@146f82c
2025-12-13 21:55:30.972 13278-13278 FragmentLifecycleLogger com.ichi2.anki.debug                 I  CardBrowser::BrowserOptionsDialog::onAttach
2025-12-13 21:55:30.973 13278-13278 FragmentLifecycleLogger com.ichi2.anki.debug                 I  CardBrowser::BrowserOptionsDialog::onCreate
2025-12-13 21:55:31.011 13278-13278 FragmentLifecycleLogger com.ichi2.anki.debug                 I  CardBrowser::BrowserOptionsDialog::onViewCreated
2025-12-13 21:55:31.021 13278-13278 FragmentLifecycleLogger com.ichi2.anki.debug                 I  CardBrowser::BrowserOptionsDialog::onStart
2025-12-13 21:55:31.021 13278-13278 FragmentLifecycleLogger com.ichi2.anki.debug                 I  CardBrowser::BrowserOptionsDialog::onResume
2025-12-13 21:55:31.321 13278-13375 HWUI                    com.ichi2.anki.debug                 D  endAllActiveAnimators on 0xb40000721d9eb580 (MenuPopupWindow$MenuDropDownListView) with handle 0xb40000715d97f950
2025-12-13 21:55:32.737 13278-13306 chi2.anki.debug         com.ichi2.anki.debug                 I  Explicit concurrent mark compact GC freed 1527KB AllocSpace bytes, 0(0B) LOS objects, 49% free, 17MB/34MB, paused 207us,1.635ms total 46.439ms
2025-12-13 21:55:32.838 13278-13306 LeakCanary              com.ichi2.anki.debug                 D  Not showing notification: already requested missing POST_NOTIFICATIONS permission.
2025-12-13 21:55:33.905 13278-13278 CardBrowse...rdsOrNotes com.ichi2.anki.debug                 I  setting mode to NOTES
2025-12-13 21:55:33.905 13278-13278 WindowOnBackDispatcher  com.ichi2.anki.debug                 W  sendCancelIfRunning: isInProgress=false callback=android.app.Dialog$$ExternalSyntheticLambda2@a22453d
2025-12-13 21:55:33.910 13278-13375 HWUI                    com.ichi2.anki.debug                 D  endAllActiveAnimators on 0xb40000721dbc7510 (RippleDrawable) with handle 0xb40000715da0c230
2025-12-13 21:55:33.914 13278-13278 CardBrowse...mnHeadings com.ichi2.anki.debug                 D  updated headings for 4 columns
2025-12-13 21:55:33.914 13278-13278 CardBrowserFragment     com.ichi2.anki.debug                 D  column names changed
2025-12-13 21:55:33.914 13278-13278 CardBrowserFragment     com.ichi2.anki.debug                 D  setting up column ColumnHeading(label=Sort Field, ankiColumnKey=noteFld)
2025-12-13 21:55:33.915 13278-13278 CardBrowserFragment     com.ichi2.anki.debug                 D  setting up column ColumnHeading(label=Cards, ankiColumnKey=template)
2025-12-13 21:55:33.916 13278-13278 CardBrowserFragment     com.ichi2.anki.debug                 D  setting up column ColumnHeading(label=Due, ankiColumnKey=cardDue)
2025-12-13 21:55:33.917 13278-13278 CardBrowserFragment     com.ichi2.anki.debug                 D  setting up column ColumnHeading(label=Deck, ankiColumnKey=deck)
2025-12-13 21:55:33.918 13278-13278 CardBrowserViewModel    com.ichi2.anki.debug                 D  loading columns for NOTES mode
2025-12-13 21:55:33.918 13278-13278 CardBrowserViewModel    com.ichi2.anki.debug                 D  updating active columns
2025-12-13 21:55:33.920 13278-13278 CardBrowser             com.ichi2.anki.debug                 D  search state: Searching
2025-12-13 21:55:33.920 13278-13278 CardBrowse...mnHeadings com.ichi2.anki.debug                 D  updated headings for 4 columns
2025-12-13 21:55:33.921 13278-13278 CardBrowserFragment     com.ichi2.anki.debug                 D  column names changed
2025-12-13 21:55:33.921 13278-13278 CardBrowserFragment     com.ichi2.anki.debug                 D  setting up column ColumnHeading(label=Sort Field, ankiColumnKey=noteFld)
2025-12-13 21:55:33.922 13278-13557 CardBrowse...chForCards com.ichi2.anki.debug                 D  performing search: ''
2025-12-13 21:55:33.923 13278-13278 CardBrowserFragment     com.ichi2.anki.debug                 D  setting up column ColumnHeading(label=Note Type, ankiColumnKey=note)
2025-12-13 21:55:33.923 13278-13557 CardBrowse...chForCards com.ichi2.anki.debug                 D  Search returned 4 card(s)
2025-12-13 21:55:33.923 13278-13278 CardBrowserFragment     com.ichi2.anki.debug                 D  setting up column ColumnHeading(label=Cards, ankiColumnKey=template)
2025-12-13 21:55:33.924 13278-13278 CardBrowserFragment     com.ichi2.anki.debug                 D  setting up column ColumnHeading(label=Tags, ankiColumnKey=noteTags)
2025-12-13 21:55:33.924 13278-13278 CardBrowserFragment     com.ichi2.anki.debug                 D  columns changed
2025-12-13 21:55:33.939 13278-13278 FragmentLifecycleLogger com.ichi2.anki.debug                 I  CardBrowser::BrowserOptionsDialog::onPause
2025-12-13 21:55:33.939 13278-13278 FragmentLifecycleLogger com.ichi2.anki.debug                 I  CardBrowser::BrowserOptionsDialog::onStop
2025-12-13 21:55:33.939 13278-13278 LeakCanary              com.ichi2.anki.debug                 D  Watching instance of android.widget.ScrollView (com.ichi2.anki.dialogs.BrowserOptionsDialog received Fragment#onDestroyView() callback (references to its views should be cleared to prevent leaks)) with key 5519fc4b-6e67-469f-a137-6e4164f814c6
2025-12-13 21:55:33.940 13278-13278 FragmentLifecycleLogger com.ichi2.anki.debug                 I  CardBrowser::BrowserOptionsDialog::onViewDestroyed
2025-12-13 21:55:33.940 13278-13278 LeakCanary              com.ichi2.anki.debug                 D  Watching instance of androidx.lifecycle.SavedStateHandlesVM (androidx.lifecycle.SavedStateHandlesVM received ViewModel#onCleared() callback) with key ddb1a680-bbf4-4b6e-b4f3-f38e79d24741
2025-12-13 21:55:33.940 13278-13278 LeakCanary              com.ichi2.anki.debug                 D  Watching instance of leakcanary.internal.ViewModelClearedWatcher (leakcanary.internal.ViewModelClearedWatcher received ViewModel#onCleared() callback) with key 3afe93c2-3959-4c6e-825d-c9b5cbd8c177
2025-12-13 21:55:33.940 13278-13278 LeakCanary              com.ichi2.anki.debug                 D  Watching instance of androidx.loader.app.LoaderManagerImpl$LoaderViewModel (androidx.loader.app.LoaderManagerImpl$LoaderViewModel received ViewModel#onCleared() callback) with key a619cd09-887e-4792-9069-89729f1d4145
2025-12-13 21:55:33.940 13278-13278 LeakCanary              com.ichi2.anki.debug                 D  Watching instance of com.ichi2.anki.dialogs.BrowserOptionsDialog (com.ichi2.anki.dialogs.BrowserOptionsDialog received Fragment#onDestroy() callback) with key c21611d1-a276-4cc3-a19d-5519b434d40d
2025-12-13 21:55:33.940 13278-13278 FragmentLifecycleLogger com.ichi2.anki.debug                 I  CardBrowser::BrowserOptionsDialog::onDestroy
2025-12-13 21:55:33.940 13278-13278 FragmentLifecycleLogger com.ichi2.anki.debug                 I  CardBrowser::BrowserOptionsDialog::onDetach
2025-12-13 21:55:33.941 13278-13278 CardBrowser             com.ichi2.anki.debug                 D  search state: Completed
2025-12-13 21:55:33.942 13278-13278 CardBrowse...fterSearch com.ichi2.anki.debug                 I  CardBrowser:: Completed searchCards() Successfully
2025-12-13 21:55:33.943 13278-13278 CardBrowser             com.ichi2.anki.debug                 D  updateList
2025-12-13 21:55:33.944 13278-13278 CardBrowser             com.ichi2.anki.debug                 D  onSelectionChanged
2025-12-13 21:55:33.944 13278-13278 CardBrowser             com.ichi2.anki.debug                 D  updateMultiselectMenu()
2025-12-13 21:55:33.961 13278-13278 CoroutineHelpersKt      com.ichi2.anki.debug                 E  java.util.NoSuchElementException: List is empty.
                                                                                                    	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:221)
                                                                                                    	at com.ichi2.anki.browser.CardOrNoteId.toCardId_impl$lambda$0(CardOrNoteId.kt:42)
                                                                                                    	at com.ichi2.anki.browser.CardOrNoteId.$r8$lambda$bxkjGAhWtD0G-4MOEwFHY5dBQno(Unknown Source:0)
                                                                                                    	at com.ichi2.anki.browser.CardOrNoteId$$ExternalSyntheticLambda1.invoke(D8$$SyntheticClass:0)
                                                                                                    	at com.ichi2.anki.CollectionManager.withCol$lambda$1(CollectionManager.kt:146)
                                                                                                    	at com.ichi2.anki.CollectionManager.$r8$lambda$ffr4nUlMOyAvThaKA2WuJlnLaPU(Unknown Source:0)
                                                                                                    	at com.ichi2.anki.CollectionManager$$ExternalSyntheticLambda10.invoke(D8$$SyntheticClass:0)
                                                                                                    	at com.ichi2.anki.CollectionManager$withQueue$3.invokeSuspend(CollectionManager.kt:128)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
2025-12-13 21:55:33.961 13278-13278 CoroutineHelpersKt      com.ichi2.anki.debug                 E  	at com.ichi2.anki.CoroutineHelpersKt.launchCatchingTask$default(CoroutineHelpers.kt:222)
                                                                                                    	at com.ichi2.anki.CardBrowser.redrawAfterSearch(CardBrowser.kt:1187)
                                                                                                    	at com.ichi2.anki.CardBrowser.setupFlows$searchStateChanged(CardBrowser.kt:538)
                                                                                                    	at com.ichi2.anki.CardBrowser.setupFlows$searchStateChanged$30(CardBrowser.kt:596)
                                                                                                    	at com.ichi2.anki.CardBrowser.access$setupFlows$searchStateChanged$30(CardBrowser.kt:111)
                                                                                                    	at com.ichi2.anki.CardBrowser$setupFlows$8.invoke(CardBrowser.kt:596)
                                                                                                    	at com.ichi2.anki.CardBrowser$setupFlows$8.invoke(CardBrowser.kt:596)
                                                                                                    	at com.ichi2.anki.AnkiActivity$launchCollectionInLifecycleScope$1$1$1.emit(AnkiActivity.kt:766)
                                                                                                    	at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:397)
                                                                                                    	at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:19)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:995)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:248)
                                                                                                    	at android.os.Looper.loop(Looper.java:338)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:9067)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:932)
```

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/pull/19790#pullrequestreview-3574416888_

### PR DESCRIPTION
**Pull request by sanjaysargam**
## Purpose / Description
java.util.NoSuchElementException: List is empty when toggling Card/Notes

## Fixes
* Fixes #19924

## Approach
Moved logic to ViewModel with safe handling

## How Has This Been Tested?
Chromebook

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt [hunk 1]
```diff
@@ -170,6 +170,21 @@ class CardBrowserViewModel(
     // card that was clicked (not marked)
     var currentCardId: CardId = 0
 
+    /**
+     * Safely determines the current card ID to display in the note editor.
+     */
+    suspend fun safeGetCurrentCardId(): CardId {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt]: Why use 0 instead of null?

**Comment by sanjaysargam** [comment]
> This doesn't seem to be handling the outcome of https://github.com/ankidroid/Anki-Android/issues/19805

Could you elaborate it?

File: AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt (hunk 1 above)
Comment (sanjaysargam) [reply AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt]: The code expects a CardId (which is a Long), and 0 lets us avoid changing everything to nullable types.  0 serves as our 'no card' sentinel that maintains non-null types

**Comment by sanjaysargam** [comment]
> 'No row/no selected row' is a valid state for the browser (for example: if a query produces no rows) and we should handle this.

I already handles right? or am I missed anything?

File: AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt (hunk 1 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt]: Use 'null' if it can be null

**Review by david-allison — CHANGES_REQUESTED** [review]
`currentCardId` being non-null is a bad abstraction.

It was added in Java in: 

* https://github.com/ankidroid/Anki-Android/pull/4839

and should be nullable now we're in Kotlin (if it even needs to continue to exist)

File: AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt [hunk 2]
```diff
@@ -168,7 +168,22 @@ class CardBrowserViewModel(
     val cardsOrNotes get() = flowOfCardsOrNotes.value
 
     // card that was clicked (not marked)
-    var currentCardId: CardId = 0
+    var currentCardId: CardId? = null
+
+    /**
+     * Safely determines the current card ID to display in the note editor.
+     */
+    suspend fun safeGetCurrentCardId(): CardId? {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt]: EDIT: Ignore this, I have a later suggestion which would change this to `updateCurrentCardId`

----

It's unusual to have `currentCardId`, with `safeGetCurrentCardId` not using it.

* Could we better define the concept
* Could we unify these?

File: AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt [hunk 3]
```diff
@@ -168,7 +168,22 @@ class CardBrowserViewModel(
     val cardsOrNotes get() = flowOfCardsOrNotes.value
 
     // card that was clicked (not marked)
-    var currentCardId: CardId = 0
+    var currentCardId: CardId? = null
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt:171]: Implementation note:

One of my future plans is to separate out `CardBrowserViewModel` and `CardBrowserFragmentViewModel`

This is obviously a concern of the activity, as it relates to coordinating the note editor and browser fragments

File: AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt [hunk 4]
```diff
@@ -168,7 +168,22 @@ class CardBrowserViewModel(
...
+
+    /**
+     * Safely determines the current card ID to display in the note editor.
+     */
+    suspend fun safeGetCurrentCardId(): CardId? {
+        // Early return if no cards available
+        if (cards.isEmpty()) return 0
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt]: Shouldn't this be `null`?

File: AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt [hunk 5]
```diff
@@ -565,7 +580,7 @@ class CardBrowserViewModel(
     }
 
     // on a row tap
-    fun openNoteEditorForCard(cardId: CardId) {
+    fun openNoteEditorForCard(cardId: CardId?) {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt]: Update this comment to explain what passing in a `null` CardId here means.

This wants a method rename, passing in a `null` ID would presumably close the editor?

File: AnkiDroid/src/main/java/com/ichi2/anki/browser/CardOrNoteId.kt [hunk 6]
```diff
@@ -39,9 +39,9 @@ value class CardOrNoteId(
 
     // TODO: We use this for 'Edit Note' or 'Card Info'. We should reconsider whether we ever want
     //  to move from NoteId to CardId. Our move to 'Notes' mode wasn't well thought-through
-    suspend fun toCardId(type: CardsOrNotes): CardId =
+    suspend fun toCardId(type: CardsOrNotes): CardId? =
         when (type) {
             CardsOrNotes.CARDS -> cardOrNoteId
-            CardsOrNotes.NOTES -> withCol { cardIdsOfNote(cardOrNoteId).first() }
+            CardsOrNotes.NOTES -> withCol { cardIdsOfNote(cardOrNoteId).firstOrNull() }
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/browser/CardOrNoteId.kt:52]: This needs a heavy comment, here and on `cardIdsOfNote` explaining how a note can have no cards

(I expect that it's a bug elsewhere and that we should treat this as an exception, rather than an expected case)

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt [hunk 7]
```diff
@@ -713,19 +713,19 @@ open class CardBrowser :
      * We use the Card ID to specify the preview target  */
     @NeedsTest("note edits are saved")
     @NeedsTest("I/O edits are saved")
-    fun openNoteEditorForCard(cardId: CardId) {
+    fun openNoteEditorForCard(cardId: CardId?) {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt]: further comment on what `null` means

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt [hunk 8]
```diff
@@ -713,19 +713,19 @@ open class CardBrowser :
...
         viewModel.openNoteEditorForCard(cardId)
     }
 
     /**
      * In case of selection, the first card that was selected, otherwise the first card of the list.
      */
-    private suspend fun getCardIdForNoteEditor(): CardId {
+    private suspend fun getCardIdForNoteEditor(): CardId? {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt:742]: AWESOME!!!

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt [hunk 9]
```diff
@@ -1146,7 +1146,7 @@ open class CardBrowser :
             // Hide note editor frame if deck is empty and fragmented
             binding.noteEditorFrame?.visibility =
                 if (fragmented && !isDeckEmpty) {
-                    viewModel.currentCardId = (viewModel.focusedRow ?: viewModel.cards[0]).toCardId(viewModel.cardsOrNotes)
+                    viewModel.currentCardId = viewModel.safeGetCurrentCardId()
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt]: Since this is only called in one place, why not move the setter into the `viewModel`?

File: AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt [hunk 10]
```diff
@@ -154,7 +154,7 @@ class CardBrowserViewModelTest : JvmTest() {
                 assertThat("Deck should be changed", col.getCard(cardId).did, equalTo(newDeck))
             }
 
-            val hasSomeDecksUnchanged = cards.any { row -> col.getCard(row.toCardId(cardsOrNotes)).did != newDeck }
+            val hasSomeDecksUnchanged = cards.any { row -> row.toCardId(cardsOrNotes)?.let { col.getCard(it) }?.did != newDeck }
```
Comment (david-allison) [inline AnkiDroid/src/test/java/com/ichi2/anki/browser/CardBrowserViewModelTest.kt]: define a test-only `requireCardId`

We want to fail if this is null

File: AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt (hunk 4 above)
Comment (sanjaysargam) [reply AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt]: oh  missed it

File: AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt (hunk 5 above)
Comment (sanjaysargam) [reply AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt]: > passing in a null ID would presumably close the editor

it's crashing right now. I'll handle it

File: AnkiDroid/src/main/java/com/ichi2/anki/browser/CardOrNoteId.kt (hunk 6 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/browser/CardOrNoteId.kt:52]: Add a small comment with an explanation to see `cardIdsOfNote`

File: AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt (hunk 2 above)
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt]: This is no longer a `get` if it mutates the value

**Review by david-allison — CHANGES_REQUESTED** [review]
SO MUCH BETTER!

One method name/implementation issue.

A unit test on the ViewModel side would be ideal.

I'm questioning the domain modelling assumptions that a note may not have cards (we should probably expose this as a warning that the user needs to check database).

Probably add in a TODO to think about this.

File: AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/NoteEditorLauncher.kt [hunk 11]
```diff
@@ -169,7 +169,7 @@ sealed interface NoteEditorLauncher : Destination {
      * @property animation The animation direction.
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/NoteEditorLauncher.kt]: This needs a name change, or a new class. 

Logically, passing in a `null` card to edit a card doesn't sit well with me

File: libanki/src/main/java/com/ichi2/anki/libanki/Collection.kt [hunk 12]
```diff
@@ -683,6 +683,20 @@ class Collection(
...
+     * IMPORTANT:
+     * A note may not always have cards.
+     *
+     * This can happen in cases like:
+     * - The note type has no card templates (empty cards).
+     * - Cards were deleted but the note still exists (orphaned notes).
+     *
+     * TODO: Notes without cards likely indicate an invalid or corrupted collection state.
+     *  We currently handle this gracefully by returning an empty list,
+     *  we may want to surface this as a warning or integrity check for the user.
```
Comment (david-allison) [inline libanki/src/main/java/com/ichi2/anki/libanki/Collection.kt]: Move this TODO out of `libanki`, 

I missed that this was library code. Handing the issue is an application-level concern

**Review by david-allison — APPROVED** [review]
Cheers!

File: AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/NoteEditorLauncher.kt [hunk 13]
```diff
@@ -164,12 +164,12 @@ sealed interface NoteEditorLauncher : Destination {
...
-     * Represents editing a card in the NoteEditor.
-     * @property cardId The ID of the card to edit.
+     * Opens the NoteEditor for the current selection (card or note).
+     * @property cardId The selected card ID, or null when editing a note.
      * @property animation The animation direction.
      */
-    data class EditCard(
-        val cardId: CardId,
+    data class EditSelection(
+        val cardId: CardId?,
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/NoteEditorLauncher.kt:172]: wouldn't a null cardId make the note editor crash?

https://github.com/ankidroid/Anki-Android/blob/f0459b726c3b01c7e5357bafa0ad432cfda1d955/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt#L750

Comment (sanjaysargam) [reply AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/NoteEditorLauncher.kt:172]: in fragmented mode, then it will not crash because we are hiding noteEditorFrame. And in non-fragmented mode, it is crashing but I don't think there will be such edge case.

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/NoteEditorLauncher.kt:172]: The Note Editor **should** be extended to support either a NoteId or a CardId, to support 'notes' mode.

* https://github.com/ankidroid/Anki-Android/issues/17415

Comment (sanjaysargam) [reply AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/NoteEditorLauncher.kt:172]: > The Note Editor **should** be extended to support either a NoteId or a CardId, to support 'notes' mode.
> 
> * [[BUG]: Card Browser - Toggle Notes -> Changing deck in Note Editor only modifies one card #17415](https://github.com/ankidroid/Anki-Android/issues/17415)

Having separate PR for this works right ?

Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/NoteEditorLauncher.kt:172]: > but I don't think there will be such edge case.

There will. Merging a known crash source isn't acceptable. Specially since the split browser is still a dev option.
