### PR TITLE
Fix database corruption dialog

### LINKED ISSUE #19092: Database corruption no longer shows `DIALOG_LOAD_FAILED`: `SqliteFailure`; `DatabaseCorrupt`; `database disk image is malformed`
See screenshot at:

https://www.reddit.com/r/MedSchoolAnkiIndia/comments/1mpr10h/what_does_this_even_mean/

The error must still be displayed as we want it when users send a screenshot. But start with a localized message 

Something as vague as "An error occurred. Tap Ok to resume using ankidroid." That would already be a slight improvement.

May be also adding a second button "restore" that would display the same menu as when we can't open the collection, offering to full download, redtore backup, do a check, etx...

### PR DESCRIPTION
**Pull request by Alex7D3**
This avoids a `SQLiteDatabaseCorruptException` escaping and ensures the correct dialog is displayed rather than a generic error dialog

## Purpose / Description
Accessing the collection with methods like `CollectionManger::withCol` or `CollectionManager::getColUnsafe` will attempt to open the database. When the file is corrupt this throws a `SQLiteDatabaseCorruptException`. In `DeckPicker`, `withCol` throws the error which is caught by a `launchCatchingTask` and a generic error dialog is displayed rather than the intended one.

## Fixes
* Fixes #19092
## Approach
Rather than accessing the collection object directly, to avoid opening the database the collection file is accessed from `CollectionManager`, and `BackupManager::repairCollection` was changed slightly to accommodate this.

Note that the logic in `repairCollection` does not guarantee the dialog will always appear even if the file is still corrupt (in my testing at least). For example if `return repairedFile.renameTo(colFile)`  succeeds and returns true, no dialog message will appear but **the database could still be corrupt and prevent the decks from loading.**

I am not sure what the course of action is here, maybe a stronger condition for `repairCollection`?

## How Has This Been Tested?
I am not sure if there is a better way to do this, there probably is. I couldn't find an integration test that corrupts the database, just unit tests (if there isn't maybe this is something worth having).

I copied
`Anki-Android-Backend/rsdroid-instrumented/src/androidTest/assets/initial_version_2_12_1_corrupt_regular.anki2`
into 
`AnkiDroid/src/main/assets/`.
This file is a corrupt collection used for a backend unit test. Then I modified `DeckPicker::handleStartup` temporarily for testing:
```diff
private fun handleStartup() {
    val context = AnkiDroidApp.instance

    val environment: AnkiDroidEnvironment =
        object : AnkiDroidEnvironment {
            private val folder = selectAnkiDroidFolder(context)

            override fun hasRequiredPermissions(): Boolean = folder.hasRequiredPermissions(context)

            override val requiredPermissions: PermissionSet
                get() = folder.permissionSet

            override fun initializeAnkiDroidFolder(): Boolean = CollectionHelper.isCurrentAnkiDroidDirAccessible(context)
        }
+   val dir = getCurrentAnkiDroidDirectory(context)
+   val targetDb = File(dir, "collection.anki2")
+   this.assets.open("initial_version_2_12_1_corrupt_regular.anki2").use { input ->
+       targetDb.outputStream().use { output ->
+           input.copyTo(output)
+       }
+   }
    viewModel.handleStartup(environment = environment)
}
```
and temporarily modified `BackupManager::repairCollection` to **always return false** to guarantee the dialog would appear during testing.

- Automated test suite
- Manually on Emulator
- Pixel 6 Pro API 31

[Screencast from 12-05-2025 05:57:47 AM.webm](https://github.com/user-attachments/assets/a6d4a891-320a-49df-8fae-553d503ead1a)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by Alex7D3** [comment]
Potential solution? Perhaps there is a cleaner way... but this works without making too many changes.
Also doesn't address repairing but we can deal with that in a separate issue after.

File: AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt [hunk 1]
```diff
@@ -204,6 +206,11 @@ suspend fun <T> FragmentActivity.runCatching(
                 if (callerTrace != null) Timber.e(callerTrace)
                 showError(exc.localizedMessage!!, exc.toCrashReportData(this))
             }
+            is SQLiteException -> {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt]: This isn't a corruption exception, this is a generic SQL exception.

Database corruption should be handled differently than a potentially transient error

(Could you provide a test case - this branch of the code is important, and is unlikely to occur often in our testing)

File: AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt [hunk 2]
```diff
@@ -204,6 +206,11 @@ suspend fun <T> FragmentActivity.runCatching(
...
+                Timber.e(exc, errorMessage)
+                if (callerTrace != null) Timber.e(callerTrace)
+                DatabaseErrorDialog.ShowDatabaseErrorDialog.fromMessage(CollectionLoadingErrorDialog().toMessage())
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt:213]: `databaseCorruptFlag` may want to be set here

File: AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt (hunk 1 above)
Comment (Alex7D3) [reply AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt]: Ahh makes sense, thanks for guiding me on this. So change `SQLiteException` to `SQLiteCorruptException` here and set the corrupt flag to get the unique dialog?
Maybe not in this issue but I'm wondering if other SQLite exception types should be handled here as well.
I'll add a test for the corrupt scenario.

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt]: Can I confirm that the testing steps are still accurate?

If so, what exception is thrown?

For now, the main issue we want to handle is the corrupt collection, expanding the scope of the issue means things will sit for longer

Comment (Alex7D3) [reply AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt]: > Can I confirm that the testing steps are still accurate?

Yes, the temporary way I have been testing works consistently, but better to have a proper test case written for the scenario so I'll add one.

> If so, what exception is thrown?

`SQLiteDatabaseCorruptException` is always thrown. For reference, it seems to originate from [here](https://github.com/ankidroid/Anki-Android-Backend/blob/0d0d54d5fb1cae299061150b2314404406d3b85f/rsdroid/src/main/java/net/ankiweb/rsdroid/Backend.kt#L111).

> For now, the main issue we want to handle is the corrupt collection, expanding the scope of the issue means things will sit for longer

Yeah, more just my thoughts/suggestions for the future. Focused on the corruption issue here.

**Comment by Alex7D3** [comment]
Found out there was another area that needs to handle the exception in `InitialActivity`. This makes sure the dialog appears on app launch (startup failure handling in `DeckPicker::onCreate`). Changes in `CoroutineHelpers` is to handle everywhere else (such as after attempting a repair).

File: AnkiDroid/src/androidTest/java/com/ichi2/anki/dialogs/DatabaseCorruptDialogTest.kt [hunk 3]
```diff
@@ -0,0 +1,91 @@
...
+            )
+        onView(withText(corruptMsg))
+            .inRoot(isDialog())
+            .check(matches(isDisplayed()))
+    }
+
+    @After
+    fun cleanupCorruptColFile() {
+        CollectionManager.closeCollectionBlocking()
+        if (!testContext.deleteDatabase(targetColFile.path)) {
```
Comment (david-allison) [inline AnkiDroid/src/androidTest/java/com/ichi2/anki/dialogs/DatabaseCorruptDialogTest.kt]: Why `deleteDatabase`?

**Comment by Alex7D3** [comment]
> One query on the test, the rest looks good to go
> 
> You created a file, `deleteOnExit()` for normal handling, and deleting it manually in the teardown method seems appropriate

Maybe good to add `mkdirs()` as well

File: AnkiDroid/src/androidTest/java/com/ichi2/anki/dialogs/DatabaseCorruptDialogTest.kt (hunk 3 above)
Comment (Alex7D3) [reply AnkiDroid/src/androidTest/java/com/ichi2/anki/dialogs/DatabaseCorruptDialogTest.kt]: I read that this method deletes some metadata files along with the db file. I think it just seemed more idiomatic in the moment but we can take it or leave it and use `File.delete()` too.

**Comment by Alex7D3** [comment]
> Looks good, thanks!

Thank you!
