### PR TITLE
catch and report TTS errors

### LINKED ISSUE #5468: TTS output failed without error message (fix described inside)
**POSSIBLE WORKAROUNDS**:

- delete the offline TTS files and re-install them
- delete the updates to the google TTS engine

--

###### Reproduction Steps

1. have cards with TTS synthesis configured

###### Expected Result

expected to hear TTS output of note

###### Actual Result

nothing happes, just silence without error message

###### Debug info

System is Android 9, Security Patch level August 2019.
I connected ADB and got the following output on logcat while the problem happened:

```
10-14 20:57:38.252 31066 13975 W TTS.Dispatcher: No network voice found, will fall back to local immediately
10-14 20:57:38.252 31066 13975 I TTS.ControllerWrapper: Initializing de-de-x-nfh-lstm-embedded from disk
10-14 20:57:38.253 31066 13975 E TTS.ControllerWrapper: Unable to open project file.
10-14 20:57:38.253 31066 13975 E TTS.ControllerWrapper: java.io.FileNotFoundException: /data/user_de/0/com.google.android.tts/files/superpacks/de-de/de-de-x-nfh-r9/pipeline (No such file or directory)
10-14 20:57:38.253 31066 13975 E TTS.ControllerWrapper:         at java.io.FileInputStream.open0(Native Method)
10-14 20:57:38.253 31066 13975 E TTS.ControllerWrapper:         at java.io.FileInputStream.open(FileInputStream.java:231)
10-14 20:57:38.253 31066 13975 E TTS.ControllerWrapper:         at java.io.FileInputStream.<init>(FileInputStream.java:165)
10-14 20:57:38.253 31066 13975 E TTS.ControllerWrapper:         at java.io.FileInputStream.<init>(FileInputStream.java:112)
10-14 20:57:38.253 31066 13975 E TTS.ControllerWrapper:         at bxs.a(PG:162)
10-14 20:57:38.253 31066 13975 E TTS.ControllerWrapper:         at bxs.b(PG:174)
10-14 20:57:38.253 31066 13975 E TTS.ControllerWrapper:         at bxs.a(PG:200)
10-14 20:57:38.253 31066 13975 E TTS.ControllerWrapper:         at bxt.b(PG:151)
10-14 20:57:38.253 31066 13975 E TTS.ControllerWrapper:         at bxt.a(PG:7)
10-14 20:57:38.253 31066 13975 E TTS.ControllerWrapper:         at com.google.android.tts.service.GoogleTTSService.onLoadVoice(PG:351)
10-14 20:57:38.253 31066 13975 E TTS.ControllerWrapper:         at android.speech.tts.TextToSpeechService$LoadVoiceItem.playImpl(TextToSpeechService.java:1250)
10-14 20:57:38.253 31066 13975 E TTS.ControllerWrapper:         at android.speech.tts.TextToSpeechService$SpeechItem.play(TextToSpeechService.java:819)
10-14 20:57:38.253 31066 13975 E TTS.ControllerWrapper:         at android.speech.tts.TextToSpeechService$SynthHandler$1.run(TextToSpeechService.java:583)
10-14 20:57:38.253 31066 13975 E TTS.ControllerWrapper:         at android.os.Handler.handleCallback(Handler.java:873)
10-14 20:57:38.253 31066 13975 E TTS.ControllerWrapper:         at android.os.Handler.dispatchMessage(Handler.java:99)
10-14 20:57:38.253 31066 13975 E TTS.ControllerWrapper:         at android.os.Looper.loop(Looper.java:192)
10-14 20:57:38.253 31066 13975 E TTS.ControllerWrapper:         at android.os.HandlerThread.run(HandlerThread.java:65)
10-14 20:57:38.253 31066 13975 E TTS.LocalSynthesizer: Failed initializing controller with voice de-de-x-nfh-lstm-embedded
10-14 20:57:38.254 14684 18841 D PackageManagerServiceUtilsZTE: ZSW isallow3rdAppSendProtectdBroadcast packageName com.google.android.tts
10-14 20:57:38.279 31066 13975 I TTS.GoogleTTSServiceImp: Synthesis request for locale deu-DEU and name de-DE-language
10-14 20:57:38.280 31066 13975 I TTS.GoogleTTSServiceImp: TTS dispatch: de-de-x-nfh-lstm-embedded
10-14 20:57:38.280 31066 13975 I TTS.ControllerWrapper: Initializing de-de-x-nfh-lstm-embedded from disk
10-14 20:57:38.281 31066 13975 E TTS.ControllerWrapper: Unable to open project file.
10-14 20:57:38.281 31066 13975 E TTS.ControllerWrapper: java.io.FileNotFoundException: /data/user_de/0/com.google.android.tts/files/superpacks/de-de/de-de-x-nfh-r9/pipeline (No such file or directory)
10-14 20:57:38.281 31066 13975 E TTS.ControllerWrapper:         at java.io.FileInputStream.open0(Native Method)
10-14 20:57:38.281 31066 13975 E TTS.ControllerWrapper:         at java.io.FileInputStream.open(FileInputStream.java:231)
10-14 20:57:38.281 31066 13975 E TTS.ControllerWrapper:         at java.io.FileInputStream.<init>(FileInputStream.java:165)
10-14 20:57:38.281 31066 13975 E TTS.ControllerWrapper:         at java.io.FileInputStream.<init>(FileInputStream.java:112)
10-14 20:57:38.281 31066 13975 E TTS.ControllerWrapper:         at bxs.a(PG:162)
10-14 20:57:38.281 31066 13975 E TTS.ControllerWrapper:         at bxs.b(PG:174)
10-14 20:57:38.281 31066 13975 E TTS.ControllerWrapper:         at bxs.a(PG:200)
10-14 20:57:38.281 31066 13975 E TTS.ControllerWrapper:         at bxt.b(PG:151)
10-14 20:57:38.281 31066 13975 E TTS.ControllerWrapper:         at bxt.a(PG:10)
10-14 20:57:38.281 31066 13975 E TTS.ControllerWrapper:         at com.google.android.tts.service.GoogleTTSService.onSynthesizeText(PG:212)
10-14 20:57:38.281 31066 13975 E TTS.ControllerWrapper:         at android.speech.tts.TextToSpeechService$SynthesisSpeechItem.playImpl(TextToSpeechService.java:1033)
10-14 20:57:38.281 31066 13975 E TTS.ControllerWrapper:         at android.speech.tts.TextToSpeechService$SpeechItem.play(TextToSpeechService.java:819)
10-14 20:57:38.281 31066 13975 E TTS.ControllerWrapper:         at android.speech.tts.TextToSpeechService$SynthHandler$1.run(TextToSpeechService.java:583)
10-14 20:57:38.281 31066 13975 E TTS.ControllerWrapper:         at android.os.Handler.handleCallback(Handler.java:873)
10-14 20:57:38.281 31066 13975 E TTS.ControllerWrapper:         at android.os.Handler.dispatchMessage(Handler.java:99)
10-14 20:57:38.281 31066 13975 E TTS.ControllerWrapper:         at android.os.Looper.loop(Looper.java:192)
10-14 20:57:38.281 31066 13975 E TTS.ControllerWrapper:         at android.os.HandlerThread.run(HandlerThread.java:65)
10-14 20:57:38.281 31066 13975 E TTS.LocalSynthesizer: Failed initializing controller with voice de-de-x-nfh-lstm-embedded
10-14 20:57:38.281 31066 13975 E TTS.LocalSynthesizer: Synthesizer failed to initialize: de-de-x-nfh-lstm-embedded
10-14 20:57:38.282 31066 13975 E TTS.GoogleTTSServiceImp: Synthesis failure with error status code: -4
10-14 20:57:38.282 31066 13975 W PlaybackSynthesisRequest: done() was called before start() call
```

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

I also found that on `Settings / System / Languages & Input / text-to-speech output / options / Install voice data` the playback for the installed language fails. This problem happened on different phones.
**Deleting the offline speech and re-installing fixed the issue.**

This problem report is here to document the problem in case others are facing it again. It would also have helped if Anki could have produced some error message telling me to check for a problem inside Android. Would the error code -4 mentioned in the log have been available to Anki?

I am fine if the developers close this without further action, as the purpose of documenting the problem is not related to Anki is now documented including a fix. I unfortunately only noticed it with Anki as I don't use TTS elsewhere, 

You could as well treat it as a request to add more error handling around the TTS engine code.

### PR DESCRIPTION
**Pull request by stephankn**
## Purpose / Description
implement onError() to report a Toast with some hints to the user
in case the TTS engine returns an error.

From API 21 upwards we would also have the error code available
for further details on what happened.

## Fixes
fixes #5468

## Approach
report a Toast

## How Has This Been Tested?
Tested on emulator

## Checklist
- [X] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java [hunk 1]
```diff
@@ -293,8 +293,14 @@ public void onDone(String arg0) {
...
                         @Override
                         @Deprecated
-                        public void onError(String arg0) {
-                            // do nothing
+                        public void onError(String utteranceId) {
+                            Timber.v("Andoid TTS failed. Check logcat for error. Indicates a problem with Android TTS engine.");
+                            new Handler(mReviewer.get().getMainLooper()).post(new Runnable() {
+                                @Override
+                                public void run() {
+                                    Toast.makeText(mReviewer.get(), "TTS failed. Check Android settings.", Toast.LENGTH_LONG).show();
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java]: Our toasts are usually resource strings as well - and perhaps you could say "Check AnkiDroid FAQ" - as we can update it and we already have an entry there with 2 different answers - both of which seem to work for different people

File: AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java [hunk 2]
```diff
@@ -293,8 +293,14 @@ public void onDone(String arg0) {
                         }
                         @Override
                         @Deprecated
-                        public void onError(String arg0) {
-                            // do nothing
+                        public void onError(String utteranceId) {
+                            Timber.v("Andoid TTS failed. Check logcat for error. Indicates a problem with Android TTS engine.");
+                            new Handler(mReviewer.get().getMainLooper()).post(new Runnable() {
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java]: I think it would be more readable if you used `runOnUiThread()` with a lambda:

```java
mReviewer.get().runOnUiThread(() -> { ... });
```

File: AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java (hunk 1 above)
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java]: Please don't hardcode strings, they should be put as resources so they can be translated.
For example here you can use the existing string `R.string.no_tts_available_message` which is used elsewhere in the same file, or you can define a new string if needed.

See here for more info:

https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#ankidroid-source-code-overview-where-to-find-what

https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#handling-translations

Comment (stephankn) [reply AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java]: The Toast has very limited space. This message is already quite long compared to others. I understand that a resource string would be beneficial, also for translation purposes. I'm going to change it. Can you suggest a short message? "Android TTS failed. Check FAQ.", could do it., what do you think?

File: AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java (hunk 2 above)
Comment (stephankn) [reply AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java]: Sure. Easier readable means easier maintenance. I'm going to change it.

File: AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java (hunk 1 above)
Comment (timrae) [reply AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java]: Maybe we should show a snackbar with a URL pointing to the FAQ instead of a Toast then

**Comment by stephankn** [comment]
> Too bad that we don't get the error code. Theoretically it should be available on higher APIs, however when I inspected the [Android source code](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/speech/tts/TextToSpeech.java#2139), it seemed that the non-deprecated callback is never called. Maybe I'm just looking in the wrong place? :/

I guess I ended up at the same location than you when checking the source code. This was the point when I told to myself "I don't understand the API deprecation concept of Android".
Probably we would have to override the calling code as well, depending on the API level?
I feel uncomfortable doing that change.

The error codes are probably not that important anyways. At this point you already know that the problem happened outside of the scope of Anki. If simply re-installing the TTS does not help, then Android TTS needs to be debugged. Maybe attaching the phone to a PC and reading the logs with ADB is the way to go then. But as said, this is beyond the scope of Anki, as TTS is globally broken.

File: AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java (hunk 1 above)
Comment (timrae) [reply AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java]: See `UIUtils.showSnackbar()` for a convenience function for showing a snackbar

Comment (timrae) [reply AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java]: In this case I think the existing string `R.string.no_tts_available_message`, together with `R.string.help` for the snackbar button would be sufficient.

**Comment by stephankn** [comment]
please review again. Travis fail does not sound related to my change.

**Comment by mikehardy** [comment]
agreed re: Travis - that's an area of current work for me, I'm manually shepherding CI status on this PR to both see what flakes on it and make sure it goes green

**Comment by mikehardy** [comment]
Travis was suffering through a "Major Outage" on their Google Compute Engine services, which is where our builds are routed in their system, complicating matters. CI's green now

File: AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java [hunk 3]
```diff
@@ -293,8 +295,15 @@ public void onDone(String arg0) {
...
                         @Deprecated
-                        public void onError(String arg0) {
-                            // do nothing
+                        public void onError(String utteranceId) {
+                            Timber.v("Andoid TTS failed. Check logcat for error. Indicates a problem with Android TTS engine.");
+
+                            final Uri helpUrl = Uri.parse(mReviewer.get().getString(R.string.link_faq_tts));
+                            final AnkiActivity ankiActivity = (AnkiActivity) mReviewer.get();
+                            ankiActivity.mayOpenUrl(helpUrl);
+                            UIUtils.showSnackbar(ankiActivity, R.string.no_tts_available_message, false, R.string.help,
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java]: Don't you have to run this on the UI thread like you were doing before? The documentation for the utterance listener says that these callbacks can happen on any thread.

Comment (stephankn) [reply AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java]: It is certainly called from a worker thread in this situation.

The Toast needed to be deferred to the UI thread. A Snackbar does this already internally.
So it is safe to be called like this.

I found this explanation on Stack Overflow: https://stackoverflow.com/a/37919601/3795504
