### PR TITLE
fix: error on POST request if app is backgrounded

### LINKED ISSUE #15679: [Bug] : congrats.html: Error: 500: Fragment `CongratsPage` not attached to an activity.
https://ankidroid.org/acra/app/1/bug/134025/report/f80a003f-bbda-4d57-8e1f-23036d59796d

```
com.ichi2.anki.exception.ManuallyReportedException: http://127.0.0.1:38927/backend/web/congrats.html#night: Error: 500: Fragment CongratsPage{537dc9d} (ea0a94d5-23b0-4aa5-8b98-c82e7dffb5fd) not attached to an activity.
	at com.ichi2.anki.CrashReportService.sendExceptionReport(SourceFile:1)
	at com.ichi2.anki.pages.PageChromeClient.onJsAlert(SourceFile:107)
	at WV.c6.run(chromium-TrichromeWebViewGoogle6432.aab-beta-631200342:138)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
If a screen is backgrounded, `requireActivity()` throws `IllegalStateException("Fragment " + this + " not attached to an activity.")`

The request which caused this was `/_anki/congratsInfo` which occurred every minute

This was returned to the screen and caused a messagebox to appear

And one messagebox per minute eventually exceeded the system window limit

Causing
* #15659

## Fixes
* Fixes #15679
* Fixes #15659

## Approach
Allow a `null` activity

## How Has This Been Tested?
⚠️ I can no loner reproduce this, but feel the reasoning is locally sonud

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt [hunk 1]
```diff
@@ -78,7 +79,11 @@ suspend fun handleCollectionPostRequest(methodName: String, bytes: ByteArray): B
     }
 }
 
-suspend fun FragmentActivity.handleUiPostRequest(methodName: String, bytes: ByteArray): ByteArray? {
+suspend fun FragmentActivity?.handleUiPostRequest(methodName: String, bytes: ByteArray): ByteArray? {
+    if (this == null) {
+        Timber.w("ignored UI request '%s' due to screen/app being backgrounded", methodName)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt:84]: since I can't reproduce this, I don't know if it's because `CongratsScreen` is backgrounded due to the `DeckOptions` being active, or because the app was backgrounded after the fact

I feel the message is clear enough

File: AnkiDroid/src/main/java/com/ichi2/anki/pages/AnkiServer.kt [hunk 2]
```diff
@@ -65,6 +65,7 @@ open class AnkiServer(
             }
             newChunkedResponse(data)
         } catch (exc: Exception) {
+            Timber.w(exc, "buildResponse failure")
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/pages/AnkiServer.kt:68]: This would have helped with diagnostics

File: AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt [hunk 3]
```diff
@@ -88,7 +88,7 @@ abstract class PageFragment : Fragment(R.layout.page_fragment), PostRequestHandl
         } else {
             throw IllegalArgumentException("unhandled request: $uri")
         }
-        return requireActivity().handleUiPostRequest(methodName, bytes)
+        return activity.handleUiPostRequest(methodName, bytes)
             ?: handleCollectionPostRequest(methodName, bytes)
             ?: throw IllegalArgumentException("unhandled method: $methodName")
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt:93]: Logically, this could crash here in a scenario that a Ui request is made, but it returned null

File: AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt (hunk 1 above)
Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt:84]: Why this and not using `activity?.handleUiPostRequest` which behaves the same?

**Review by BrayanDSO — COMMENTED** [review]
As of now, note that this will create silent bugs. But is good enough for now

File: AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt (hunk 1 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt:84]: (I feel I misunderstand the comment)

I explicitly want a `Timber` and don't see how `activity?.handleUiPostRequest` would mange this

Open to alternatives

**Comment by david-allison** [comment]
Potential alternative which warns less

```kotlin
Index: AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt b/AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt	(revision 1f7d918320370d78def75a88568ddc0912567c82)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt	(date 1709036297021)
@@ -80,14 +80,18 @@
 }
 
 suspend fun FragmentActivity?.handleUiPostRequest(methodName: String, bytes: ByteArray): ByteArray? {
-    if (this == null) {
-        Timber.w("ignored UI request '%s' due to screen/app being backgrounded", methodName)
-        return null
+    suspend fun handleNullReceiver(block: suspend FragmentActivity.() -> ByteArray): ByteArray? {
+        if (this == null) {
+            Timber.w("ignored UI request '%s' due to screen/app being backgrounded", methodName)
+            return null
+        }
+        return block()
     }
+
     return when (methodName) {
-        "searchInBrowser" -> searchInBrowser(bytes)
-        "updateDeckConfigs" -> updateDeckConfigsRaw(bytes)
-        "addImageOcclusionNote" -> {
+        "searchInBrowser" -> handleNullReceiver { searchInBrowser(bytes) }
+        "updateDeckConfigs" -> handleNullReceiver { updateDeckConfigsRaw(bytes) }
+        "addImageOcclusionNote" -> handleNullReceiver {
             val data = withCol { addImageOcclusionNoteRaw(bytes) }
             undoableOp { OpChanges.parseFrom(data) }
             launchCatchingTask {
@@ -98,7 +102,7 @@
             }
             data
         }
-        "updateImageOcclusionNote" -> {
+        "updateImageOcclusionNote" -> handleNullReceiver {
             val data = withCol {
                 updateImageOcclusionNoteRaw(bytes)
             }

```

**Comment by david-allison** [comment]
Any further action you'd like me to take on this?

**Comment by BrayanDSO** [comment]
> Any further action you'd like me to take on this?

Send a report instead of crashing in the comment I made about unhandled method

**Comment by david-allison** [comment]
The exception is caught:

https://github.com/ankidroid/Anki-Android/blob/45a8c5753da1622e92be03e0fd404bdcb32e6f54/AnkiDroid/src/main/java/com/ichi2/anki/pages/AnkiServer.kt#L62-L70

What would you like returned to the WebView in case of failure?

**Review by BrayanDSO — APPROVED** [review]
Got it. LGTM

**Comment by BrayanDSO** [comment]
> As of now, note that this will create silent bugs. 

for that, there could be a enqueing for the webview reload request (which is what calls `congratsInfo`) to run when the lifecycle is at least `onStart`. If there is more than one request, ignore the older ones
