### PR TITLE
Fix(Whiteboard): Side System Gesture Exclusion

### LINKED ISSUE #20346: [New study screen] Make whiteboard `Hide toolbar` feature compatible with system navigation gestures
In the whiteboard of the new study screen, there is a `Hide toolbar` option, which hides the whiteboard toolbar and can be reverted by swiping it back.

The issue is that the "swipe back" gesture may conflict with system gestures.

So, we should exclude the toolbar area from the system gesture area.

See https://developer.android.com/develop/ui/views/touch-and-input/gestures/gesturenav#back-gestures for reference

### PR DESCRIPTION
**Pull request by LUwUcifer**
## Purpose / Description
When whiteboard toolbar is docked to the sides and collapsed, swiping right will not cause the app to exit

## Fixes
* Fixes #20346 

## Approach
Calls systemGestureExclusionRects function within an overriden onLayout function within the whiteboardToolbar to include the whiteboard as an excluded Rect, it should be noted that since the toolbar has a starting margin of 8dp, swiping in that area would still cause the screen to exit

## How Has This Been Tested?

Tested on a local device as well as an Emulated Medium Phone API 36.1

## Learning (optional, can help others)
Previous usages of the function setSystemGestureExclusionRects in other repositories on github heavily influenced the written code

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [X] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/whiteboard/WhiteboardToolbar.kt [hunk 1]
```diff
@@ -66,6 +69,29 @@ class WhiteboardToolbar : LinearLayout {
...
+
+    override fun onLayout(
+        changed: Boolean,
+        left: Int,
+        top: Int,
+        right: Int,
+        bottom: Int,
+    ) {
+        super.onLayout(changed, left, top, right, bottom)
+        if (Build.VERSION.SDK_INT >= 29 && changed) {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/whiteboard/WhiteboardToolbar.kt]: The version check shouldn't be necessary: https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:core/core/src/main/java/androidx/core/view/ViewCompat.java;l=2990-2995?q=setSystemGestureExclusionRects

The following should do

```kotlin
        if (!changed) return
        boundingBox.set(left, top, right, bottom)
        ViewCompat.setSystemGestureExclusionRects(this, exclusions)
```

**Comment by LUwUcifer** [comment]
Ah oops I force pushed without adding mb

**Comment by LUwUcifer** [comment]
should be fine now @david-allison thanks for the insight

**Review by BrayanDSO — CHANGES_REQUESTED** [review]
The UX is still not good here. Most of times the back gesture is still triggered when the whiteboard is on the left or right

**Comment by LUwUcifer** [comment]
@BrayanDSO (Apologies for the late response) that likely arises from the 8dp margin that exists on the sides, this can be easily fixed through 
```
when(currentAlignment){
            ToolbarAlignment.LEFT -> boundingBox.set(left - 8.dp.toPx(context), top, right, bottom)
            ToolbarAlignment.RIGHT -> boundingBox.set(left, top, right + 8.dp.toPx(context), bottom)
            ToolbarAlignment.BOTTOM -> boundingBox.set(0,0,0,0)
        }
```
However I am unsure if this is the cleanest way to go about this, would it be better practice to increase the scope of the margin variable and input that here, get insets from view, or hard-code it? Any other suggestions are also welcome

I ran this on my local device and it seems to work well, however swiping from the leftmost still has the gestures enabled
https://medium.com/androiddevelopers/gesture-navigation-handling-visual-overlaps-4aed565c134c (Mandatory System Gesture Insets)
I believe it is due to the mandatory inset being 0, it still functions if you swipe starting from the edge

**Comment by LUwUcifer** [comment]
I have otherwise confirmed the exclusionrect is working as intended through timber logs

**Comment by LUwUcifer** [comment]
small unrelated question but before using timber I was trying to use Toast and the notification wasn't showing up, any ideas why that might be?

**Comment by BrayanDSO** [comment]
> get insets from view,

how that would look in the code?

**Comment by LUwUcifer** [comment]
The simplest way afaik is 
```
View.marginLeft \\or simply marginLeft works too
```

I tried these two methods and both worked for edited margins

```
        val view = findViewById<View>(R.id.whiteboard_toolbar)
        val lp = view.layoutParams as MarginLayoutParams
        val leftMargin = lp.leftMargin
        Timber.tag(TAG).i(leftMargin.toString())
        
        Timber.tag(TAG).i(marginLeft.toString())
```

**Comment by LUwUcifer** [comment]
in this scenario, if the margins are ever edited in fragment_whiteboard.xml, the changes are reflected here

**Comment by BrayanDSO** [comment]
go for that
