### PR TITLE
fix(note-editor): Deck for "new cards: decide by note type"

### LINKED ISSUE #19733: "Deck for new cards/Decide by note type" is ignored
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

Set General/Deck for new cards to "Decide by note type".
From the home screen, hit the FAB and choose "Add'.
Change the deck dropdown to something else.
Add the card.
Go back to the main screen and choose "Add" again. 

### Expected behaviour

The Deck will default to the current deck, not to the deck that the most recent note of that note type was added to.

Changing note type will appropriately change the deck, but the default is incorrect.

### Debug info

```text
AnkiDroid Version = 2.23.0beta5 (49df20dba80a379e53ff939b98d842932ec6a263)  
Backend Version = 0.1.62-anki25.09.2 (25.09.2 3890e12c9e48c028c3f12aa58cb64bd9f8895e30)  
Android Version = 16 (SDK 36)  
ProductFlavor = play  
Device Info = Google | google | caiman | caiman | Pixel 9 Pro | caiman  
Webview User Agent = Mozilla/5.0 (Linux; Android 16; Pixel 9 Pro Build/BP3A.251105.015; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/143.0.7499.34 Mobile Safari/537.36  
ACRA UUID = ee97bee6-3ef4-4b61-b2b9-9b6db2190e04  
FSRS = 5.1.0 (Enabled: true)  
Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

Worked in a sideloaded parallel version of 2.22.3. Seems to be new behavior in the beta. Seems to also happen with anything that opens the note creation screen (shortcuts and intents).

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### LINKED ISSUE #19750: [BUG] 'Change deck depending on notetype' not handled when switching note types
Things are still not working correctly when using the _"Change deck depending on notetype"_ option. Changing notetypes while inside the editor erases the previously set deck and we revert to _Default_, desktop changes decks depending on selected notetypes while inside the add screen. This is also a regression from 2.22 where the proper decks were restored based on notetype selection.

Decide by notetype -> Go to add -> select a notetype and add to a deck -> select another notetype and add to another deck -> switch to the first used notetype -> deck is now Default

_Originally posted by @lukstbit in https://github.com/ankidroid/Anki-Android/pull/19734#pullrequestreview-3564131730_

**Related**

* https://github.com/ankidroid/Anki-Android/pull/19734#pullrequestreview-3564131730_
* https://github.com/ankidroid/Anki-Android/issues/19733

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
Introduced in 2644a6d3d5b3304df1e1681a4e609af301e17f86

* decide by note type was broken

## Fixes
* Fixes #19733
* Fixes #19750

## Approach
* Related: #19650

## How Has This Been Tested?

* Using user-provided collection
* Changed deck
* Added a new note
* Exited
* Entered
* Previously selected deck was maintained

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison** [comment]
IMO: too close to the release window to block. Save for a quick 2.23.1

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt [hunk 1]
```diff
@@ -818,20 +820,14 @@ class NoteEditorFragment :
...
-                // check if this is the actual deck selected
-                val currentSelectedDeckId = col.decks.selected()
-                if (currentSelectedDeckId != Consts.DEFAULT_DECK_ID) {
-                    deckId = currentSelectedDeckId
-                }
-            }
-            // Also guard against adding to a filtered deck in which case revert to 'Default'
+            // When adding and if we didn't receive a valid deck id or it's the 'Default' deck,
+            // use the recommended deck for adding
+            deckId = deckId.ifZero { col.defaultsForAdding().deckId }
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt:826]: honestly didn't even know about this feature "default deck for note adds" much less that it was upstream rust and available until reviewing last couple PRs...

**Comment by mikehardy** [comment]
This one will be cherry-picked and I feel like I understand it but asking for second set of eyes from @lukstbit since they authored the original chunk and a second set of eyes is always good for a cherry pick to a stable release...

**Review by lukstbit — CHANGES_REQUESTED** [review]
Much better than my original code because I completely missed this feature and I didn't account for it in any way:(

Things are still not working correctly when using the _"Change deck depending on notetype"_ option. Changing notetypes while inside the editor erases the previously set deck and we revert to _Default_, desktop changes decks depending on selected notetypes while inside the add screen. This is also a regression from 2.22 where the proper decks were restored based on notetype selection.

Decide by notetype -> Go to add -> select a notetype and add to a deck -> select another notetype and add to another deck -> switch to the first used notetype -> deck is now Default

**Comment by lukstbit** [comment]
I'm fine with this going in, the issue I mentioned existed in the previous(2.23) code as well.

**Comment by lukstbit** [comment]
Potential fix:

```diff
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt
index a4141bfed8..40ba4fbd02 100644
--- a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt
@@ -2788,7 +2788,7 @@ class NoteEditorFragment :
 
         // Update deck
         if (!getColUnsafe.config.getBool(ConfigKey.Bool.ADDING_DEFAULTS_TO_CURRENT_DECK)) {
-            deckId = noteType.did
+            deckId = getColUnsafe.defaultsForAdding().deckId
         }
 
         refreshNoteData(FieldChangeType.changeFieldCount(shouldReplaceNewlines()))
```

**Comment by david-allison** [comment]
Drafting. Thanks! 

I'd like to spend a little more time on correctness/testing before this goes in.

**Comment by david-allison** [comment]
I have written two tests and applied @lukstbit's test, which fixes the second issue. Thank you for the thorough review!
