### PR TITLE
NumberFormatException fixed

### LINKED ISSUE #8843: Crash 2.15beta - NumberFormatException on IncrementNumberRangePreference
stack trace

```
java.lang.NumberFormatException: For input string: ""
at java.lang.Integer.parseInt(Integer.java:620)
at java.lang.Integer.parseInt(Integer.java:643)
at com.ichi2.preferences.IncrementerNumberRangePreference.updateEditText(IncrementerNumberRangePreference.java:1)
at com.ichi2.preferences.IncrementerNumberRangePreference.lambda$initialize$1(IncrementerNumberRangePreference.java:1)
at com.ichi2.preferences.IncrementerNumberRangePreference.b(Unknown Source:0)
at com.ichi2.preferences.a.onClick(Unknown Source:2)
at android.view.View.performClick(View.java:6897)
at android.widget.TextView.performClick(TextView.java:12693)
at android.view.View$PerformClick.run(View.java:26101)
at android.os.Handler.handleCallback(Handler.java:789)
```

logcat was empty

How can it happen? No idea but it can happen - can't call parseInt without catching NumberFormatException and using a sensible default...

### PR DESCRIPTION
**Pull request by yasin459**
## Pull Request template
Fixes #8843
## Purpose / Description
_an error appear when you try to increment limit in deck option from null to sth

## Fixes
added a try catch and put default value 0 for value in "IncrementerNumberRangePreference.updateEditText"

## Approach
_How does this change address the problem?_

## How Has This Been Tested?
i tried manually

## Learning (optional, can help others)
help of a friend

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreference.java [hunk 1]
```diff
@@ -122,7 +122,12 @@ private void initialize() {
      * @param isIncrement Indicator for whether to increase or decrease the value.
      */
     private void updateEditText(boolean isIncrement) {
-        int value = Integer.parseInt(mEditText.getText().toString());
+        int value ;
+        try {
+            value=Integer.parseInt(mEditText.getText().toString());
+        } catch (NumberFormatException e){
+            value=0;
+        }
```
Comment (Akshay0701) [inline AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreference.java:130]:
```suggestion
        int value;
        try {
            value = Integer.parseInt(mEditText.getText().toString());
        } catch (NumberFormatException e) {
            value = 0;
        }
```

**Review by Akshay0701 — CHANGES_REQUESTED** [review]
That's good, Congratulation on your First PR, And Thank You! @yasin459,

There are few nits I mentioned,

And I suggest you go through
https://github.com/ankidroid/Anki-Android/wiki/Code-style,

**Review by mikehardy — APPROVED** [review]
Tiny space changes that @Akshay0701 spotted, I committed those and this looks great

**Comment by mikehardy** [comment]
first attempt through unit tests on CI failed because of a flaky unrelated test, restarted...

File: AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreference.java [hunk 2]
```diff
@@ -122,7 +122,12 @@ private void initialize() {
      * @param isIncrement Indicator for whether to increase or decrease the value.
      */
     private void updateEditText(boolean isIncrement) {
-        int value = Integer.parseInt(mEditText.getText().toString());
+        int value;
+        try {
+            value = Integer.parseInt(mEditText.getText().toString());
+        } catch (NumberFormatException e) {
+            value = 0;
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreference.java:129]: Question: This defaults the value to 0, but is this always what we want?

I'm unsure if there's a concrete example, but as a quick analogy, this could move the "default backups" from `8` as the default, to `0`.

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreference.java:129]: a good point, I had thought that but did not consider really important cases like backups - investigating under what condition this actually happens (is this going from "no pref" to "some pref" and it passes through null/empty and crashes? and we may have a system default? or is this "user manually fiddled with a setting and we're just trying to recover but we may have a valid prior value in prefs?"

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreference.java:129]: These appear to get an original value at all times, but the user may just clobber it and enter anything.
I'll alter this to save original and restore in case of NumberFormatException - will push that in just a moment as I'm packing a beta up right now and don't want to delay since I'm not sure when I'll have a chance again

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreference.java]: Pushed, please examine :pray:

**Review by david-allison-1 — APPROVED** [review]
Tempted to ask for an exception report on the `This should not be possible`, and/or a log in both catch blocks. But implementer's choice

Good to go otherwise

**Comment by mikehardy** [comment]
I think that one is a literally impossibility - I don't think we have had a single case of someone persisting an incorrect type (somehow) through the preferences system (which is typed, for storage) and then re-inflating that into some mal-typed initialization for the preference change. I just figured while I was in there covering all the bases I could cover even unreachable ones. I'm going to merge and I'll eat my words later if necessary

**Comment by mikehardy** [comment]
Hi there!

Apologies for the delay, and if you're already submitted something to OpenCollective for May 2021 PRs merged, you may feel free to ignore this.

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for May 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged in May)

Thanks!
