### PR TITLE
fixed the The anki card menu can't be found from the search bar..

### LINKED ISSUE #18050: Missing search results in settings
The ""anki card" menu" can't be found from the search bar. Neither typing "anki" nor "context"

Also, in French, search "carte" shows some things that does not contains the word "carte", such as

Image

AnkiDroid Version = 2.21alpha13 (86145585b3bb251b13ec31d14920485b13c31c46)
Backend Version = 0.1.50-anki25.02 (25.02 038d85b1d9e1896e93a3e4a26f600c79ddc33611)
Android Version = 15 (SDK 35)
ProductFlavor = play
Device Info = Google | google | husky | husky | Pixel 8 Pro | husky
Webview User Agent = Mozilla/5.0 (Linux; Android 15; Pixel 8 Pro Build/AP4A.250205.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/133.0.6943.137 Mobile Safari/537.36
ACRA UUID = 1ee1be7e-8149-4589-aca8-f45e0b56a2a5
FSRS = 2.0.3 (Enabled: false)
Crash Reports Enabled = true

### PR DESCRIPTION
**Pull request by Pankajkumar2608**
## Purpose / Description  
**Issue**: The "Anki Card" menu does not appear in the settings search results when users type "anki" or "context".  
**Root Cause**:  
- The preference used `tools:title` and `tools:summary` (design-time attributes) instead of `android:title` and `android:summary` (runtime attributes).  
- Search indexing relied on runtime attributes, which were missing.  

## Fixes  
Resolves missing search results for "Anki Card" menu. Resolve part of #18050.  

## Approach  
1. **Replace `tools:` with `android:` attributes**:  
   - Use `android:title` and `android:summary` to ensure the text is available at runtime.  
   - Link to string resources containing searchable keywords like "Anki" and "context".  
2. **Update string resources**:  
   - Define `anki_card_menu_title` and `anki_card_menu_summary` in `strings.xml` with relevant keywords.  
3. **Enable summary indexing**:  
   - Configure `SearchConfiguration` to index summaries (if not already enabled).  

## How Has This Been Tested?  
**Steps**:  
1. Build the app and navigate to **Settings > General**.  
2. Use the search bar and type "anki" or "context".  
3. Verify that the "Anki Card" menu appears in results.  

**Test Configuration**:  
- Device: RealMe C25Y (Android 11, API 30)  

## Learning (optional, can help others)  
- **`tools:` vs `android:` Attributes**: Learned that `tools:` attributes are stripped at compile time and only for Android Studio previews.  
- **Search Indexing**: Understood how `SearchConfiguration` relies on runtime attributes (titles, keys, summaries) for indexing.  

## Checklist  
- [x] You have a descriptive commit message with a short title (e.g., "Fix search indexing for Anki Card menu").  
- [x] Code comments added to clarify the use of `android:title`/`android:summary` over `tools:`.  
- [x] Self-reviewed code changes for XML and string resources.  
- [x] UI changes: Screenshots attached showing the "Anki Card" menu in search results.  
- [x] Tested accessibility with Google Accessibility Scanner (no regressions found).

### CODE REVIEW

**Review by criticalAY — CHANGES_REQUESTED** [review]
Heya! thanks
But this change does not address the issue, the `tools` is meant for devs to see the string in xml view, you need to fix the issue as these strings are coming from backend

**Comment by devyk100** [comment]
@criticalAY **Also I suppose this would fail for other language translations as well.
_Example:_**
**Only helps in layout preview inside Android Studio.**
WhatsApp Image 2025-03-06 at 19 39 09_46627381
**This works only for English now, other languages would fail, example.**
WhatsApp Image 2025-03-06 at 19 39 11_a7a56bb0
WhatsApp Image 2025-03-06 at 19 39 10_1d4eeede
**As this wasnt translated, and appears in English**
WhatsApp Image 2025-03-06 at 19 44 37_86fdd22c

**Where as the original translation inside the general preferences is this**
WhatsApp Image 2025-03-06 at 19 39 10_e0d8cf5b

I suppose this is because it is a hardcoded string

**Comment by Pankajkumar2608** [comment]
@devyk100 yep working on the issue to solve it properly not in a particular language.

**Comment by Arthur-Milchior** [comment]
Thanks.
I didn't know the difference between `android:title` and `tools:title`.
I guess every hard codde string should be a tools:title, so that the app can be a little bit smaller. With the exception of dev preferences, where we actually have a reason to want everything in English in the app.

So, in your fix, maybe you could add

```patch
Subject: [PATCH] aa
---
Index: lint-rules/src/test/java/com/ichi2/anki/lint/rules/HardcodedPreferenceKeyTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/lint-rules/src/test/java/com/ichi2/anki/lint/rules/HardcodedPreferenceKeyTest.kt b/lint-rules/src/test/java/com/ichi2/anki/lint/rules/HardcodedPreferenceKeyTest.kt
--- a/lint-rules/src/test/java/com/ichi2/anki/lint/rules/HardcodedPreferenceKeyTest.kt	(revision 19df388a4c3c9fae08b795f38dd2a1f42fabaa4f)
+++ b/lint-rules/src/test/java/com/ichi2/anki/lint/rules/HardcodedPreferenceKeyTest.kt	(date 1741305771100)
@@ -47,7 +47,7 @@
             android:title="@string/pref_cat_general"
             android:key="@string/pref_general_screen_key">
             <Preference
-                android:title="foo"
+                tools:title="foo"
                 android:summary="bar"/>
             <ListPreference
                 android:defaultValue="@string/empty_string"
Index: AnkiDroid/src/main/res/xml/preferences_reviewer.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/res/xml/preferences_reviewer.xml b/AnkiDroid/src/main/res/xml/preferences_reviewer.xml
--- a/AnkiDroid/src/main/res/xml/preferences_reviewer.xml	(revision 19df388a4c3c9fae08b795f38dd2a1f42fabaa4f)
+++ b/AnkiDroid/src/main/res/xml/preferences_reviewer.xml	(date 1741305497871)
@@ -1,6 +1,7 @@
 <?xml version="1.0" encoding="utf-8"?>
 <androidx.preference.PreferenceScreen xmlns:android="http://schemas.android.com/apk/res/android"
-    xmlns:app="http://schemas.android.com/apk/res-auto">
+    xmlns:app="http://schemas.android.com/apk/res-auto"
+    xmlns:tools="http://schemas.android.com/tools">
 
     <ListPreference
         android:defaultValue="@string/hide_system_bars_none_value"
@@ -29,7 +30,7 @@
         />
 
     <Preference
-        android:title="Menu actions"
+        tools:title="Menu actions"
         android:key="@string/reviewer_menu_settings_key" />
 
     <ListPreference
Index: lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.kt b/lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.kt
--- a/lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.kt	(revision 19df388a4c3c9fae08b795f38dd2a1f42fabaa4f)
+++ b/lint-rules/src/test/java/com/ichi2/anki/lint/rules/FixedPreferencesTitleLengthTest.kt	(date 1741305440990)
@@ -91,10 +91,10 @@
     @Language("XML")
     val preferenceWithHardcodedTitle = """
         <PreferenceScreen xmlns:android="http://schemas.android.com/apk/res/android"
-            android:title="Dev options"
+            tools:title="Dev options"
             android:key="@string/pref_dev_options_screen_key">
             <SwitchPreferenceCompat
-                android:title="New congrats screen"
+                tools:title="New congrats screen"
                 android:key="@string/new_congrats_screen_pref_key"
                 android:defaultValue="false"/>
         </PreferenceScreen>"""
```

**Comment by Arthur-Milchior** [comment]
I think that instead of generating the string from two substrings as in https://github.com/ankidroid/Anki-Android/blob/19df388a4c3c9fae08b795f38dd2a1f42fabaa4f/AnkiDroid/src/main/java/com/ichi2/anki/preferences/GeneralSettingsFragment.kt#L73 we should just have a string whose englishh is going to be "'Anki card' menu", so that Translator have freedom to translate as best as they want.

However, the search `tools:title=[^@]` shows there are plenty of other cases where we use a hard coded tool, such as `show_audio_play_buttons_key`, because the string is actually obtained from the Anki's backend. So we'll still have the problem of finding how to add those strings to the search result.

**Comment by Pankajkumar2608** [comment]
@criticalAY  can you go through the pr again.

File: AnkiDroid/src/main/java/com/ichi2/anki/preferences/HeaderFragment.kt [hunk 1]
```diff
@@ -135,6 +135,18 @@ class HeaderFragment :
                     .withResId(R.xml.preferences_controls)
                     .addBreadcrumb(activity.getString(R.string.pref_cat_controls))
                     .addBreadcrumb(setDuePreferenceTitle)
+                /** Index the system wide menu items - dynamically */
+                indexItem()
+                    .withKey(activity.getString(R.string.anki_card_external_context_menu_key))
+                    .withTitle(activity.getString(R.string.card_browser_enable_external_context_menu, "Anki Card"))
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/preferences/HeaderFragment.kt:141]: Can you get the translated string for "Anki Card", rather than hard coding it?

**Review by david-allison — CHANGES_REQUESTED** [review]
Thanks!

File: AnkiDroid/src/main/res/xml/preferences_general.xml [hunk 2]
```diff
@@ -71,12 +71,16 @@
...
+                android:summary="@string/card_browser_enable_external_context_menu_summary"
+                android:title="@string/card_browser_enable_external_context_menu"/>
             <SwitchPreferenceCompat
                 android:id="@+id/card_browser_external_context_menu"
                 android:defaultValue="false"
                 android:key="@string/card_browser_external_context_menu_key"
                 tools:title="‘Card Browser’ Menu"
-                tools:summary="Enables the ‘Card Browser’ context menu globally"/>
+                tools:summary="Enables the ‘Card Browser’ context menu globally"
+                android:summary="@string/card_browser_enable_external_context_menu_summary"
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/main/res/xml/preferences_general.xml:83]: Why did you add this string here? It contains a %s, it should not be used as is. That seems plain wrong.
Same below and above

**Review by Arthur-Milchior — COMMENTED** [review]
Your correction seems to work, but only for the two keys I mentioned in my bug.
I'd love two things.

1. have a general solution. That deals with all preferences that don't have a hard coded string. A search for `tools:title` show there are three more in the preferences.  And one "tools:summary".

2. Be able to detect new cases. Because may be in a few years we'll add an extra preference whose entry is generated instead of being hard coded in the XML. And we'll forget that we need to change the header.

This second part can be done in a different PR if needed. But if you don't do it in this PR, I'll need you to at least create a TODO and note that the issue we're dealing with is not fixed.

I see many problems to attack this problem. I'm not sure exactly which one is the best. If you're here for GSoC, I prefer to let you ponder how to solve this second part. If you've no idea, please come on discord and we can discuss alternatives.

(To be clear, the first part alone would be enough forme to consider that you fulfill the requirement to have submitted code (even if I will still need to see a PR with tests). But the second part, which would probably include test, and which requires more decision to be future-proof, would be a better proof of your skills!

File: AnkiDroid/src/main/java/com/ichi2/anki/preferences/HeaderFragment.kt [hunk 3]
```diff
@@ -135,6 +135,18 @@ class HeaderFragment :
                     .withResId(R.xml.preferences_controls)
                     .addBreadcrumb(activity.getString(R.string.pref_cat_controls))
                     .addBreadcrumb(setDuePreferenceTitle)
+                /** Index the system wide menu items - dynamically */
```
[the remark this answers is not in the document]
Comment (Pankajkumar2608) [reply AnkiDroid/src/main/java/com/ichi2/anki/preferences/HeaderFragment.kt:138]: I recognize the need for improvement and apologize for the current state. I will address this in the next commit with more thorough commenting.

**Comment by Pankajkumar2608** [comment]
@david-allison can you review the pr again i fixed the changes that you wanted in it. 
also i am thinking about raising a new issue to address the arthur issues about indexing of more tools.

File: AnkiDroid/src/main/res/xml/preferences_general.xml [hunk 4]
```diff
@@ -71,7 +71,7 @@
                 android:defaultValue="true"
                 android:key="@string/anki_card_external_context_menu_key"
                 tools:title="‘Anki Card’ Menu"
-                tools:summary="Enables the ‘Anki Card’ context menu globally"/>
+                tools:summary="Enables the ‘Anki Card’ context menu globally" />
```
Comment (david-allison) [inline AnkiDroid/src/main/res/xml/preferences_general.xml:74]: revert: line noise

File: AnkiDroid/src/main/res/values/10-preferences.xml [hunk 5]
```diff
@@ -94,7 +94,7 @@
     <string name="gestures_corner_tap_bottom_left" maxLength="41">Touch bottom left</string>
     <string name="gestures_corner_tap_bottom_right" maxLength="41">Touch bottom right</string>
     <string name="gestures_shake" maxLength="41">Shake device</string>
-    <string name="card_browser_enable_external_context_menu">‘%s’ Menu</string>
+    <string name="card_browser_enable_external_context_menu" maxLength="41">‘%s’ Menu</string>
```
Comment (david-allison) [inline AnkiDroid/src/main/res/values/10-preferences.xml:97]: I'm fine keeping this

**Review by david-allison — COMMENTED** [review]
One nitpick of a nitpick, then let's squash this and get it in.

Cheers!

**Comment by criticalAY** [comment]
As Brayan said the behaviour is because of the library that we are using I am gonna raise a issue there but for now we can keep this change as it solves the issue

**Comment by Pankajkumar2608** [comment]
@david-allison removed the noise from code.

**Review by david-allison — APPROVED** [review]
@Pankajkumar2608 Cheers! Waiting for a second reviewer

This will be a little easier/faster to merge if you squash + force push the commits, but we're fine to handle this on a first contribution

**Review by criticalAY — APPROVED** [review]
Nice!

File: AnkiDroid/src/main/res/xml/preferences_general.xml (hunk 2 above)
Comment (Arthur-Milchior) [reply AnkiDroid/src/main/res/xml/preferences_general.xml]: Sorry, I meant "@string/card_browser_enable_external_context_menu_summary" should not appear as part of "android:summary", as it will contains the "%s".
Anyway it was removed

**Comment by Arthur-Milchior** [comment]
> 1. have a general solution. That deals with all preferences that don't have a hard coded string. A search for `tools:title` show there are three more in the preferences.  And one "tools:summary".

I'm sorry but this part was ignored. I'm not okay with merging this change. 
Did you search for "tools:summary" and "tools:title" in the codebase's prefernece files?

I found `tools:summary="On next sync, force changes in one direction" `
And when I search "next" in the app I can't find this setting.

I found `tools:title="Show play buttons on cards with audio"`
And when I search "play" in the app I can't find this setting.

And same with `card_browser_external_context_menu`s's  `tools:title="‘Card Browser’ Menu"`.

As I mentioned, my original bug were examples of settings' entries that could not be found. I'm happy your PR fixed those particular entries, and now they can be found.
But I really want that we fix all entries at once and that we don't have to create a new PR later to add the extra entries

**Comment by Arthur-Milchior** [comment]
merging as discussed by @david-allison on discord

**Comment by david-allison** [comment]
Hi there @Pankajkumar2608! This is the OpenCollective Notice for PRs merged from [2025-03-01 through 2025-03-31](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2025-03-01..2025-03-31+author%3APankajkumar2608)
                      
If you are interested in compensation for this work, the process with details is here: https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

We only post one comment per person per month to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for this month

Please understand that our monthly budget is never guaranteed to cover all claims - the cap on payments-per-person may be lower, but we try to make our process as fair and transparent as possible, we just need your understanding.

Thanks!
