### PR TITLE
Diagnose and avoid crash for deck with no terms

### LINKED ISSUE #5959: [ACRA 2.9] No value for 'terms' - blocks Custom Study.
Saw this in 2.10alpha, but found a report for 2.9.5.

Worrying, as this likely blocks custom study.

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/6acb298b-607f-4006-96f6-ac793a1e0f9c

```
java.lang.RuntimeException: org.json.JSONException: No value for terms
at com.ichi2.anki.dialogs.CustomStudyDialog.createCustomStudySession(CustomStudyDialog.java:26)
at com.ichi2.anki.dialogs.CustomStudyDialog.a(CustomStudyDialog.java:5)
at com.ichi2.anki.dialogs.g.onClick(Unknown Source:12)
at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:7)
at android.view.View.performClick(View.java:7201)
at android.view.View.performClickInternal(View.java:7170)
at android.view.View.access$3500(View.java:806)
at android.view.View$PerformClick.run(View.java:27562)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7682)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: org.json.JSONException: No value for terms
at org.json.JSONObject.get(JSONObject.java:399)
at org.json.JSONObject.getJSONArray(JSONObject.java:594)
at com.ichi2.anki.dialogs.CustomStudyDialog.createCustomStudySession(CustomStudyDialog.java:19)
... 14 more
```

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description

Logging to diagnose the cause of #5959

Also, displays a crash report rather then crashing.

## Fixes
Fixes #5959 (at least, fixes the crash, but not the cause)

## Approach
Logging, and an exception report/toast if an issue is found.

## How Has This Been Tested?

On my device, custom study still works

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java [hunk 1]
```diff
@@ -450,11 +456,12 @@ private void createCustomStudySession(JSONArray delays, Object[] terms, Boolean
             dyn.put("delays", JSONObject.NULL);
         }
         JSONArray ar = dyn.getJSONArray("terms");
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java:458]: We currently crash here. It's almost certainly the case where `cur` exists (possibly getting a corrupt custom study deck from AnkiWeb), but it's hard to know without logging.

**Comment by mikehardy** [comment]
This released as 2.10alpha65 as soon as google is done processing it
