### PR TITLE
Fix crash in RemoveAccountFragment by implementing OnWebViewRecreatedListener

### LINKED ISSUE #19561: [BUG] 'RemoveAccountFragment' crashes on open: must implement OnWebViewRecreatedListener
2.23beta1

https://ankidroid.org/acra/app/1/bug/359271/report/42ff96a0-06e5-488d-8ae7-aff7e256237a

```
java.lang.IllegalStateException: Fragment 'RemoveAccountFragment' must implement OnWebViewRecreatedListener
	at com.ichi2.anki.workarounds.SafeWebViewLayout.onAttachedToWindow(SafeWebViewLayout.kt:140)
	at android.view.View.dispatchAttachedToWindow(View.java:23298)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3613)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3620)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3620)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5479)
	at android.view.ViewGroup.addView(ViewGroup.java:5257)
	at android.view.ViewGroup.addView(ViewGroup.java:5192)
	at androidx.fragment.app.FragmentStateManager.addViewToContainer(FragmentStateManager.java:902)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:585)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:286)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2214)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2109)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2052)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:703)
	at android.os.Handler.handleCallback(Handler.java:995)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loopOnce(Looper.java:288)
	at android.os.Looper.loop(Looper.java:393)
	at android.app.ActivityThread.main(ActivityThread.java:9569)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1010)
```

This one also needs a regression test

### PR DESCRIPTION
**Pull request by sanjaysargam**
## Purpose / Description
RemoveAccountFragment was crashing on open because SafeWebViewLayout requires the host to implement OnWebViewRecreatedListener

## Fixes
* Fixes #19561

## Approach
Implement  listener and reinitialize WebView when recreated to avoid fragment crash

## How Has This Been Tested?
Physical Device (Redmi 9 Pro 5G)

- Triggered a forced WebView crash using chrome://crash after a 2-second delay
- Confirmed onRenderProcessGone is called and the WebView is destroyed + recreated correctly.
- Verified the fragment receives onWebViewRecreated and reloads the original URL.
- Ensured the app stays stable with no crashes.
- Added Timber logs to trace the full recovery flow.
image

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by BrayanDSO** [comment]
Based on the video, I assume that you just opened the fragment and probably didn't understand the issue.

The fragment opens correctly even without this change. This is a onRenderProcessGone issue.

And you aren't properly implementing onWebViewRecreatedListener. The webview isn't configured correctly on it

**Comment by sanjaysargam** [comment]
> The fragment opens correctly even without this change

It was crashing in debug apk

**Comment by david-allison** [comment]
In a real crash, the WebView process is dead (either due to a bug, or via the OOM-killer) and the called code likely won't reinitialize the new `WebView` in the same way that the standard `onCreate` flow did

running `loadUrl("chrome://crash")` after a `delay()` gets you close enough to figure out how the WebView handles the issue when `onRenderProcessGone` is called

----

Aside: we should document this

File: AnkiDroid/src/main/java/com/ichi2/anki/pages/RemoveAccountFragment.kt [hunk 1]
```diff
@@ -80,60 +83,69 @@ class RemoveAccountFragment : Fragment(R.layout.page_fragment) {
...
+            override fun shouldOverrideUrlLoading(
+                view: WebView?,
+                request: WebResourceRequest?,
+            ): Boolean {
+                @Suppress("DEPRECATION")
+                return shouldOverrideUrlLoading(view, request?.url.toString())
+            }
+
+            @Deprecated(
+                "Deprecated in java, still needed for API 23",
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/pages/RemoveAccountFragment.kt]: minSdk is now 24, so no need to keep this

**Review by BrayanDSO — APPROVED** [review]

**Comment by david-allison** [comment]
> [!IMPORTANT]
> We are trialling an increase to Open Collective payments, invoices submitted more than **two weeks** after the date you receive this message may not be eligible for this increase.

Hi there @sanjaysargam! This is the OpenCollective Notice for PRs **merged** from [2025-11-01 through 2025-11-30](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2025-11-01..2025-11-30+author%3Asanjaysargam)

If you are interested in compensation for this work, the process with details is here: https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

We only post one comment per person per month to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for this month

Please understand that our monthly budget is never guaranteed to cover all claims - the cap on payments-per-person may be lower, but we try to make our process as fair and transparent as possible, we just need your understanding.

Thanks!
