### PR TITLE
Fix(custom study): removed suplerfluous screen for no tag decks

### LINKED ISSUE #18479: Onboarding/UX: Handle 'Custom Study by card state or tag' when there are no tags
This 'Custom Study' screen is superfluous:

----

https://github.com/ankidroid/Anki-Android/labels/Good%20First%20Issue%21

* Relevant classes: `TagLimitFragment.kt`; `CustomStudyDialog.kt`
* Either 
  * If there are no tags, change the text (`sentence_choose_tags`) in `CustomStudyDialog` and skip the tag selection screen 
    * define an extension method `fun Tags.count()` by counting the result of `Tags.all()`
  * OR suggest another appropriate UX

### PR DESCRIPTION
**Pull request by ShaanNarendran**
## Purpose / Description
This fixes the select tag screen opening even when a deck may not be tagged, this was superfluous.

## Fixes
* Fixes #18479 

## Approach
Used the existing method inside launchCatchingTask but changed the way the query works, now it checks for cards with at least 1 tag within a deck and returns that result, we then use that to check whether to immediately launch custom study or show the select tag screen.

## How Has This Been Tested?
Tested via the emulator, didn't make any ui changes so haven't recorded a video for this but works as expected.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt [hunk 1]
```diff
@@ -388,17 +389,20 @@ class CustomStudyDialog : AnalyticsDialogFragment() {
...
                                 val currentDeckname = decks.name(viewModel.deckId)
                                 val search = SearchNode.newBuilder().setDeck(currentDeckname).build()
-                                val query = buildSearchString(listOf(search))
+                                val query = buildSearchString(listOf(search)) + " -tag:none"
                                 findNotes(query)
                             }
+                        if (nids.isEmpty()) {
+                            launchCustomStudy(contextMenuOption, n)
+                            return@launchCatchingTask
+                        }
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt:409]: Add a comment

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt [hunk 2]
```diff
@@ -388,17 +389,20 @@ class CustomStudyDialog : AnalyticsDialogFragment() {
                             withCol {
                                 val currentDeckname = decks.name(viewModel.deckId)
                                 val search = SearchNode.newBuilder().setDeck(currentDeckname).build()
-                                val query = buildSearchString(listOf(search))
+                                val query = buildSearchString(listOf(search)) + " -tag:none"
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt]: At least:

* pass two strings into `buildSearchString`, rather than concatenating them

Ideally:

* Build a negated SearchNode for the tag query

**Review by david-allison — CHANGES_REQUESTED** [review]
Cheers!

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt (hunk 2 above)
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt]: Add a comment explaining why

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt [hunk 3]
```diff
@@ -386,19 +387,28 @@ class CustomStudyDialog : AnalyticsDialogFragment() {
...
-                                val search = SearchNode.newBuilder().setDeck(currentDeckname).build()
-                                val query = buildSearchString(listOf(search))
+                                val currentDeckName = decks.name(viewModel.deckId)
+                                val deckNode = SearchNode.newBuilder().setDeck(currentDeckName).build()
+                                // build a tag node for cards in the deck having tag:none
+                                val tagNode = SearchNode.newBuilder().setTag("none").build()
+                                // negating the tag node
+                                val negatedNode = SearchNode.newBuilder().setNegated(tagNode).build()
+                                // search the deck for cards with at least 1 tag
+                                val query = buildSearchString(listOf(deckNode, negatedNode))
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt]: use a meaningful name, not `negatedNode`, use `noTags` or similar

EDIT: use `buildList { }` to skip the variable names

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt [hunk 4]
```diff
@@ -386,19 +387,28 @@ class CustomStudyDialog : AnalyticsDialogFragment() {
                     launchCatchingTask {
                         val nids =
                             withCol {
-                                val currentDeckname = decks.name(viewModel.deckId)
-                                val search = SearchNode.newBuilder().setDeck(currentDeckname).build()
-                                val query = buildSearchString(listOf(search))
+                                val currentDeckName = decks.name(viewModel.deckId)
+                                val deckNode = SearchNode.newBuilder().setDeck(currentDeckName).build()
+                                // build a tag node for cards in the deck having tag:none
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt]: Explain the why, not what's occurring

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt [hunk 5]
```diff
@@ -386,19 +387,28 @@ class CustomStudyDialog : AnalyticsDialogFragment() {
...
+                                val tagNode = SearchNode.newBuilder().setTag("none").build()
+                                // negating the tag node
+                                val negatedNode = SearchNode.newBuilder().setNegated(tagNode).build()
+                                // search the deck for cards with at least 1 tag
+                                val query = buildSearchString(listOf(deckNode, negatedNode))
                                 findNotes(query)
                             }
+                        // if no cards with at least 1 tag are found, launch custom study
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt]:
```suggestion
                        // skip tag selection if there's no tags to select
```

**Review by david-allison — CHANGES_REQUESTED** [review]
Last one I think, thanks!!

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt (hunk 4 above)
Comment (ShaanNarendran) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt]: is the new comment fine?

**Review by david-allison — APPROVED** [review]
There's a builder syntax for `searchNode` which may be useful, but this is complex and optional to get this PR merged. I'd avoid it unless you're keen

We'll do better here in the future, and very few people are producing search strings

**Comment by david-allison** [comment]
See my implementation in the 'off-topic' comment here for an example of the builder syntax:

* https://github.com/ankidroid/Anki-Android/pull/19677#issuecomment-3609160045

Not the DSL, things like: 

```kotlin
searchNode { this.tag = value }
```

**Comment by ShaanNarendran** [comment]
> See my implementation in the 'off-topic' comment on #19677 for an example of the builder syntax:
> 
> * [Add implementation for buildSearchString and groupSearches backend methods #19677 (comment)](https://github.com/ankidroid/Anki-Android/pull/19677#issuecomment-3609160045)
> 
> Not the DSL, things like: `searchNode { this.tag = value }`

let me see if I can use this, better to make it ideal now so there's less work later on

**Comment by david-allison** [comment]
We'd be replacing the code no matter which implementation you pick, your call!

**Comment by ShaanNarendran** [comment]
> We'd be replacing the code no matter which implementation you pick, your call!

Oh, then I'm happy with what I've done for now. It does seem a bit complex, so maybe I'll look at it in the future again when we replace the code. EDIT: If the pr is mergeable, I'd love to get it merged

**Comment by ShaanNarendran** [comment]
Not sure why a test is failing, I'll have a look in a while

**Comment by david-allison** [comment]
Probably flaky, I'll rerun

**Comment by ShaanNarendran** [comment]
> What if we extract search logic into a helper function ?

I could do this, but it'd be quite small right wouldn't it be easier for readability just to keep it here?

**Comment by sanjaysargam** [comment]
> I could do this, but it'd be quite small right wouldn't it be easier for readability just to keep it here?

I'll wait for another reviewer opinion on this

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt [hunk 6]
```diff
@@ -386,19 +387,34 @@ class CustomStudyDialog : AnalyticsDialogFragment() {
                     launchCatchingTask {
                         val nids =
                             withCol {
-                                val currentDeckname = decks.name(viewModel.deckId)
-                                val search = SearchNode.newBuilder().setDeck(currentDeckname).build()
-                                val query = buildSearchString(listOf(search))
-                                findNotes(query)
+                                val currentDeckName = decks.name(viewModel.deckId)
+                                val deckNode = SearchNode.newBuilder().setDeck(currentDeckName).build()
```
Comment (sanjaysargam) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt]: `deckNode` unused variable

**Comment by david-allison** [comment]
Fine as it is IMO

**Review by BrayanDSO — APPROVED** [review]
