### PR TITLE
 Hide card template add/delete for cloze model 

### LINKED ISSUE #6015: When editing card type of a Cloze-based note type, the user  is allowed to add more cards types. This is invalid for cloze models
###### Reproduction Steps
tap:
1. Manage note types
2. Long press on a cloze based model
3. Edit card types
4. Hamburger button in top right
5. Add

User will be prompted about a full sync, then the can add many card types to a cloze model.

###### Expected Result
The card type editor should check if the model is based on the cloze model (i.e. if type ==1 in the [models json object](https://github.com/ankidroid/Anki-Android/wiki/Database-Structure#models-jsonobjects)) and it should not show the add/delete menu items

###### Actual Result

Screenshot_2020-04-15-13-26-31
Cards 2-4 are invalid here as cloze models can only have 1 card type

I haven't checked to see what happens after syncing, but I imagine desktop would report a corrupt database.
###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

### PR DESCRIPTION
**Pull request by mikehardy**
## Purpose / Description
The cloze template can't have cards added to it or deleted from it, so we should block that in the CardTemplateEditor

## Fixes
Fixes #6015 

## Approach
During options menu inflate, set those options to invisible for cloze type

## How Has This Been Tested?
API28 emulator with this branch on it, I attempted to edit a cloze template pre-patch and I could (an error) then with the patch I could no longer add/delete (fixed!) but I could add/delete on other template types.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/libanki/Models.java [hunk 1]
```diff
@@ -22,6 +22,9 @@
 import android.content.ContentValues;
 import android.database.Cursor;
 import android.util.Pair;
+import androidx.annotation.Nullable;
+import androidx.annotation.VisibleForTesting;
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Models.java:26]: Codacy Issue found: [Avoid unused imports such as 'androidx.annotation.VisibleForTesting'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5398132)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  9
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.java  2
- AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java  8
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java  6
- AnkiDroid/src/test/java/com/ichi2/anki/TemporaryModelTest.java  4
- AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/NonPagingCardTemplateEditor.java  1
         

Clones added
============
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5398132&bid=17694119)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java  6
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.java  2
- AnkiDroid/src/main/java/com/ichi2/anki/TemporaryModel.java  8
- AnkiDroid/src/test/java/com/ichi2/anki/TemporaryModelTest.java  4
- AnkiDroid/src/test/java/com/ichi2/anki/TestCardTemplatePreviewer.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  9
- AnkiDroid/src/test/java/com/ichi2/anki/NonPagingCardTemplateEditor.java  1
         

Clones added
============
- AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.java  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5398132&bid=17694119)

**Comment by mikehardy** [comment]
The only reason this PR was based against 5151 was because I thought 5151 would go in - I just peeled it off that stack and adapted to current master so it can go in - it's trivial, no reason to hold it up

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java [hunk 2]
```diff
@@ -427,6 +427,13 @@ private void updateCss() {
         @Override
         public void onCreateOptionsMenu(Menu menu, MenuInflater inflater) {
             inflater.inflate(R.menu.card_template_editor, menu);
+
+            if (mModel.getInt("type") == 1) {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java:431]: Use `Consts.MODEL_CLOZE`. Sadly can't make this a suggestion as it also needs an import

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java:431]: ah yes - saw the same thing "magic constant" and didn't know if it existed or not. Should have been less lazy and taken action on the thought

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java]: done! thanks
