### PR TITLE
fix: decode media names before inserting into the database

### LINKED ISSUE #17972: Check Media Deletes Used Files
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Added some pictures from Wikipedia which had a comma in their names. Example: `Hopi_Pueblo_(Native_American)._Dancing_Shoes,_late_19th_century.jpg`

The comma in the name seems to get converted to `%2C` when you add them to your cards.

2. Using "Check Media" shows the file using `,` instead of `%2C` and it's marked as unused.

### Expected behaviour

The files were being used in my cards.

### Debug info

```text
AnkiDroid Version = 2.21alpha11 (b0d7b48431676f1ee721b4cae16065d50af0425a)
Backend Version = 0.1.49-anki25.01rc1 (25.01rc1 b65fa693dacbd92c0bdd2a8c3800d0827432d108)
Android Version = 11 (SDK 30)
ProductFlavor = full
Device Info = realme | realme | RMX2193 | RMX2193 | RMX2193 | mt6768
Webview User Agent = Mozilla/5.0 (Linux; Android 11; RMX2193 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/132.0.6834.163 Mobile Safari/537.36
ACRA UUID = cf265e01-9693-407f-984d-61ddf9698fac
FSRS = 2.0.2 (Enabled: true)
Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by Sahil06012002**
### Issue:

**Check Media** shows incorrect values when media filenames contain special characters (spaces, %, &, =, etc.) on Android, while the desktop version works as expected.

### Cause:

According to the [Anki manual](https://docs.ankiweb.net/media.html#media) (https://docs.ankiweb.net/media.html#media), filenames with spaces or special characters appear differently in the HTML editor compared to how they are stored on disk. For example, `hello 100%.jpg` is displayed as `hello%20100%25.jpg` in the editor.

HTML encoding is likely applied because certain characters have special meanings in URLs and HTML syntax. Without proper encoding, the card rendering engine may fail to locate or display media files with special characters in their names.

For instance, if a file named `test,.jpg` is referenced in a card, it gets encoded as `test%2C.jpg` in the editor for proper rendering, while the actual file on disk remains `test,.jpg`.

### Observations:

- When adding a card using the **desktop version**, the original filename is stored in the `collection.anki2` database (`notes` table).
- When adding media via **Android**, the filename is stored in an encoded format.
Scrrenshot of the notes table :
synv_ev

This discrepancy causes the `check_media` function to return incorrect results for media files added from Android when their names include special characters.

## Approach

Now, while adding card in a deck `addNote()` function is called
https://github.com/Sahil06012002/Anki-Android/blob/fb3eec394463e19f0b3db3fdaa5b6b1eb156879a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt#L1198
that stores the note in the database.

Decoding the media filenames before storing them in the database resolves the issue.
Before calling `addNote(editorNote!!, deckId)`, the `fields` parameter in `editorNote` is updated to replace encoded filenames with their decoded versions :
https://github.com/Sahil06012002/Anki-Android/blob/fb3eec394463e19f0b3db3fdaa5b6b1eb156879a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt#L2579 .

## Fixes
* Fixes #17972

## How Has This Been Tested?
- Tested on a **physical device (Android 12)**.
- Attached a video demonstrating the fix in 
https://github.com/user-attachments/assets/721fba7e-07d0-4523-a851-3f8bfc7f6910

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt [hunk 1]
```diff
@@ -2575,7 +2575,8 @@ class NoteEditor :
 
     private fun updateField(field: FieldEditText?): Boolean {
         val fieldContent = field!!.text?.toString() ?: ""
-        val correctedFieldContent = NoteService.convertToHtmlNewline(fieldContent, shouldReplaceNewlines())
+//      Decode the file name when preparing data for saveNote() to handle special characters correctly
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:2578]: the `//` should follow the surrounding indent

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt [hunk 2]
```diff
@@ -2575,7 +2575,8 @@ class NoteEditor :
...
+        val correctedFieldContent = Uri.decode(NoteService.convertToHtmlNewline(fieldContent, shouldReplaceNewlines()))
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:2579]: Won't this affect any kind of encoded content the user has added?

**Review by BrayanDSO — COMMENTED** [review]
A description of the issue and how this fix it would be appreciated. You also said that you had thought about other ways to fix it. What are they?

**Comment by Sahil06012002** [comment]
> A description of the issue and how this fix it would be appreciated. You also said that you had thought about other ways to fix it. What are they?

I have updated the PR description for better clarity.

Regarding the second question, modifying the editorNote parameter anywhere before passing it to addNote() would effectively resolve the issue. Initially, I tried to fix it by updating the fields parameter in NoteEditor.kt at https://github.com/ankidroid/Anki-Android/blob/248488166f416d736728f62874f127a45a4c01dd/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt#L1198 as follows:

```
editorNote!!.fields.replaceAll { Uri.decode(it) }
addNote(editorNote!!, deckId)
```
But, this introduces an extra iteration, which is unnecessary. If needed, we can update editorNote at any suitable point before calling addNote() to optimize the fix.

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt (hunk 2 above)
Comment (Sahil06012002) [reply AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:2579]: I'm not aware of any instances where users would intentionally add encoded content, but this is something to consider. If necessary, we might need to ensure that only media filenames are decoded rather than applying decoding to all fields.

Do you know of any cases where users might intentionally add encoded content?

Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:2579]: From memory, no. But in Anki there are always someone doing stuff like that

Comment (Sahil06012002) [reply AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:2579]: Hey @BrayanDSO , quick question:
Since the field containing the encoded media file name will always have an HTML  tag, would it be a good idea to identify fields using this tag and decode only those?
```
if (correctedFieldContent.contains("<img", ignoreCase = true)){
val correctedFieldContent = Uri.decode(NoteService.convertToHtmlNewline(fieldContent, shouldReplaceNewlines()))
}
```
Although, I think using contains on the fields is might introduce an additional overhead but I can't seem to find any quick solution for this one. I would appreciate any suggestions here.

**Comment by Sahil06012002** [comment]
While rendering a card on Android, the encoding function is called from the backend:

https://github.com/ankidroid/Anki-Android/blob/19df388a4c3c9fae08b795f38dd2a1f42fabaa4f/AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/AndroidCardRenderContext.kt#L54

The method encodes media file names for rendering the HTML. This implies that encoding media file names during card creation should not be necessary.

Based on the comments in the backend code as well :

https://github.com/ankitects/anki/blob/63c2a09ef6760890c03be4bd83f613c03c512d1f/rslib/src/text.rs#L577

the media file names are **not** encoded when adding a card in the desktop version and the database contains the actual file name contrary to current implementation of android version. I confirmed this by checking the database as mentioned earlier and also by exporting a card in plain text format, which resulted in:

```
#separator:tab
#html:true
"<img src=""txm 232.jpeg"">"	test&nbsp;
"<img src=""test,hello.jpeg"">"
```

**Proposed Fix :** 

Instead of decoding media file names before storing them in the database, a better solution would be to **avoid encoding them when adding cards** in the first place, since they are already encoded during rendering. I have already made the necessary changes in the commit, and I kindly ask you to review and verify it.

This change will cause a slight difference in the UI. Previously, when an image was attached from the gallery, the encoded file name was saved in the text field. With this fix, the actual file name will be displayed in the text field.

Additionally,In my opinion if encoding media file names is necessary anywhere in the code base, instead of using `Uri.encode()` as seen here:
https://github.com/ankidroid/Anki-Android/blob/19df388a4c3c9fae08b795f38dd2a1f42fabaa4f/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/ImageField.kt#L83

we should use the following function to maintain consistency:

https://github.com/ankidroid/Anki-Android/blob/19df388a4c3c9fae08b795f38dd2a1f42fabaa4f/AnkiDroid/src/main/java/com/ichi2/libanki/Media.kt#L85

**Review by Arthur-Milchior — COMMENTED** [review]
Thanks for this PR. 

Can you please send the commit(s) as you want it/them in the repo. So please, squash them and ensure the description is stating exactly what you are doing and what you do it.

This really needs a regression test. Can you please add one?

And the biggest issue. What will occur to notes that were created with the current version of ankidroi?
Indeed, suppose that:
* you create a card with today buggy version of ankidroid. You add an image with a comma in its name as in the original bug,
* you update ankidroid so that your PR is incorporated,
* you show a card of the note
* you use check media

Is the image still correctly displayed in the reviewer? Is the media still detected as unused in the "check media" ? I don't understand the reviewer enough to know what to expect for the first case. However, I suspect that we'll still offer to delete the media as unused while it's used, because nothing in your code seems to have any impact over the "unused media" feature.

And while it's great that we'll stop introducing buggy entry in the notes, we should ideally be able to deal with all notes that were created in the buggy version of ankidroid, so that we don't break cards of our users.

It'd be also nice that you test a card created with today version of ankidroid on anki desktop. Ensuring that anki desktop does not detect the media as unused.  If it does, we'll need to discuss with Damien Elmes what we want to do about it, but ideally, we'd need to update anki so that it does not remove used media that were created by our users when we had a bug

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/ImageField.kt [hunk 3]
```diff
@@ -80,8 +79,10 @@ class ImageField :
         @NeedsTest("files with HTML illegal chars can be imported and rendered")
         fun formatImageFileName(file: File): String =
```
[the remark this answers is not in the document]
Comment (Sahil06012002) [reply AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/ImageField.kt:80]: The "else" condition was already present, possibly as a fallback, and I haven't made any changes to that part. Would you like me to take a look at it?

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/IField.kt [hunk 4]
```diff
@@ -45,7 +45,7 @@ interface IField : Serializable {
     /**
      * Returns the formatted value for this field. Each implementation of IField should return in a format which will be
      * used to store in the database
-     *
+     * - The formatted value now contains the actual file name instead of the encoded name.
```
[the remark this answers is not in the document]
Comment (Sahil06012002) [reply AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/IField.kt:48]: Earlier, the formattedValue held the encoded file name within the  tag because of its setter behavior in the ImageField.kt file that implements the IField.kt interface. In this commit, it has been updated to contain the actual file name.

I added this comment for this particular commit, but it doesn’t align with the codebase actually, I’ll be removing it in the next commit.

**Comment by Sahil06012002** [comment]
> Thanks for this PR.
> 
> Can you please send the commit(s) as you want it/them in the repo. So please, squash them and ensure the description is stating exactly what you are doing and what you do it.
> 
> This really needs a regression test. Can you please add one?
> 
> And the biggest issue. What will occur to notes that were created with the current version of ankidroi? Indeed, suppose that:
> 
> * you create a card with today buggy version of ankidroid. You add an image with a comma in its name as in the original bug,
> * you update ankidroid so that your PR is incorporated,
> * you show a card of the note
> * you use check media
> 
> Is the image still correctly displayed in the reviewer? Is the media still detected as unused in the "check media" ? I don't understand the reviewer enough to know what to expect for the first case. However, I suspect that we'll still offer to delete the media as unused while it's used, because nothing in your code seems to have any impact over the "unused media" feature.
> 
> And while it's great that we'll stop introducing buggy entry in the notes, we should ideally be able to deal with all notes that were created in the buggy version of ankidroid, so that we don't break cards of our users.
> 
> It'd be also nice that you test a card created with today version of ankidroid on anki desktop. Ensuring that anki desktop does not detect the media as unused. If it does, we'll need to discuss with Damien Elmes what we want to do about it, but ideally, we'd need to update anki so that it does not remove used media that were created by our users when we had a bug


- When a card is added in the buggy version of AnkiDroid, using the "Check Media" tool results in the following:
    - **Missing:** The encoded media name (as this is what gets referenced with the card in the database).
    - **Unused:** The actual media name (since this is present in the media folder but isn't referenced by any card).

This behavior is consistent across:

- The current app version
- The app including this PR
- The desktop version (we’ll need to discuss with Damien Elmes)

This PR does not address the existing issue with the "Check Media" feature. After this PR, the tool will still display the previous buggy entries.

To resolve this, we could update the database to store the actual file name instead of the encoded version, or we could explore a better fix..

- In the app including this PR, the card containing the (,) in the file name which was added from the current version of the app is visible in the reviewer. The reviewer requires the encoded file name to render the HTML, so there is no issue.
- When adding cards from the app in this PR, the "Check Media" feature works fine in both the Android and desktop versions.

PS: We are not altering the results from the "Check Media" function; we are simply displaying them as they are.

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/ImageField.kt [hunk 5]
```diff
@@ -80,8 +79,10 @@ class ImageField :
...
             if (file.exists()) {
-                val encodedName = Uri.encode(file.name)
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/ImageField.kt:83]: If you use git blame and check the commit that introduced this, it tried to fix https://github.com/ankidroid/Anki-Android/issues/15844. Since you are reverting the change, please check if this has created a regression

**Review by BrayanDSO — CHANGES_REQUESTED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/ImageField.kt (hunk 5 above)
Comment (Sahil06012002) [reply AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/ImageField.kt:83]: @BrayanDSO  , I checked, and it seems that the current PR reintroduces the issue. Reverting the change has caused the regression. I'll look into this further.

**Review by mikehardy — DISMISSED** [review]
I think the Anki upstream issue mentioned as blocker ("Anki Desktop does not display media correctly if it contains literal escape characters, e.g. `name%20.jpg`") is not our problem and no solution here should be concerned with it.

The basic expectations we have to meet are:
- Check media compares raw filenames in collection with raw filenames on storage, so the filename in the collection needs to be exactly as it is on disc - all producers of values that go in collection need to meet this expectation -- no encoding in collection
- All renders of the filename must be encoded in order for the HTML content to be valid -- all use of filenames from collection for render need escaping

So this PR needs to take the approach of meeting + enforcing that expectation

I propose two methods/properties/whatever to get/set media filenames that meet these expectations (disk filename -> render filename, render filename -> disk filename) and all previous access is altered to be a compile error (made internal, private or removed). Then all producers/consumers of media filenames will be forced to use the new paths that meet the encode/decode expectations

Will probably touch quite a few areas of the codebase but should centralize the encode/decode work and make sure the whole codebase handles things correctly

**Comment by BrayanDSO** [comment]
AFAIK, `Check media` comes from the backend and gets the `used` media based on the cards' HTML. The issue probably only occurs because we use the backend code, and the backend has this issue within it. I'm not sure we can properly fix it, and if we can, it'll probably be more hacky and troublesome than fixing it directly in the backend.

For now, I'm okay with exchanging #15844 for #17972. The latter is a destructive bug, while the former is also present in Anki Desktop.

**Comment by mikehardy** [comment]
@BrayanDSO silly me - I was thinking that this was a field on an object we could fence off access to, not some Quixotic HTML parsing exercise. Poor analysis on my part. Agreed then on exchanging 15844 for 17972

**Review by BrayanDSO — APPROVED** [review]
Force pushed the fix, which reverts b6bc456f022ab8c46cd2b4351d2847a7c7e6a0fb.

As I said before, it exchanges https://github.com/ankidroid/Anki-Android/issues/15844 for https://github.com/ankidroid/Anki-Android/issues/17972 so we match what Anki desktop does

**Review by david-allison — APPROVED** [review]
I'll leave this as https://github.com/ankidroid/Anki-Android/labels/Needs%20Second%20Approval, but good to go from me. Thanks!

**Review by mikehardy — APPROVED** [review]
Wish there was a more complete fix, but okay with this one given what I know now

**Comment by mikehardy** [comment]
Argh, so close, fixing locally then will re-add to queue after push - it was a change while this PR was in flight and the merge queue caught it. Showed up only after rebasing to very current main


```
> Task :AnkiDroid:ktlintMainSourceSetCheck FAILED
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/ImageField.kt:24:1 Unused import
```

**Comment by david-allison** [comment]
Hi there @Sahil06012002! This is the OpenCollective Notice for PRs merged from [2025-06-01 through 2025-06-30](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2025-06-01..2025-06-30+author%3ASahil06012002)
                      
If you are interested in compensation for this work, the process with details is here: https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

We only post one comment per person per month to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for this month

Please understand that our monthly budget is never guaranteed to cover all claims - the cap on payments-per-person may be lower, but we try to make our process as fair and transparent as possible, we just need your understanding.

Thanks!
