### PR TITLE
Don't show `Full sync` option if not logged on database error dialog

### LINKED ISSUE #7326: Database Error: Don't show "Full Sync From Server" if user does not have AnkiWeb Account

### LINKED ISSUE #10394: [Bug] Full sync button don't work properly on Incompatible Database dialog
###### Reproduction Steps

1. Have a newer scheme `collection.anki2`
2. Tap `Full sync from server` without being logged

Demo:
https://user-images.githubusercontent.com/69634269/155589058-7fc833e3-6cb7-4a3e-86cb-fb51639d8797.mp4

###### Expected Result

A message saying something like `You aren't logged, thus you can't sync`

###### Actual Result

It stays in a eternal loading, as shown in the demo video

###### Debug info
```
AnkiDroid Version = 2.16alpha45

Android Version = 11

Manufacturer = samsung

Model = SM-N770F

Hardware = exynos9810

Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-N770F Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/98.0.4758.101 Mobile Safari/537.36

ACRA UUID = 7b43f97d-f42d-432b-808c-dcee88875a39

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by BrayanDSO**
## Fixes
Fixes #7326, Fixes #10394

## Approach
- Only add the option if the user is logged in

### Incompatible database
- Be unlogged
- Use a collection.anki2 with a scheme newer than 11 (from Anki desktop)
- Open the app
Result:
Screenshot_20220228-201206_AnkiDroid

### Error handling dialog
With no backups on backups folder, did the following:
https://user-images.githubusercontent.com/69634269/156079204-ed1e84ef-edde-4204-a429-a1d68ad11428.mp4

Did the same processes logged and the `Full sync from server` option shows accordingly

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
LGTM - thanks!

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt [hunk 1]
```diff
@@ -319,7 +327,7 @@ class DatabaseErrorDialog : AsyncDialogFragment() {
                         _: DialogAction? ->
                         exit()
                     }
-                    .items(*options) // .itemsColor(ContextCompat.getColor(requireContext(), R.color.material_grey_500))
+                    .items(*options.toTypedArray()) // .itemsColor(ContextCompat.getColor(requireContext(), R.color.material_grey_500))
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt:330]: Can you test this, `items` should take a `Collection<T>`

```
                    .items(options)
```

**Review by david-allison — COMMENTED** [review]
one nitpick for readability

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt (hunk 1 above)
Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt:330]: It works, thanks

**Review by david-allison — APPROVED** [review]
Beauty! Awaiting CI
