### PR TITLE
Access correct cursor window size when configuring collection chunk size

### LINKED ISSUE #7031: sCursorWindowSize not found in emulator
I got no error on master when I opened the "phone.zip" version.
When I tried to opened the other file, I got an error which is worrysome but seems unrelated

```
W/Collection: Unable to get window size from requery cursor.
    java.lang.NoSuchFieldException: No field sCursorWindowSize in class Lio/requery/android/database/CursorWindow; (declaration of 'io.requery.android.database.CursorWindow' appears in /data/app/com.ichi2.anki-Iwraig6P2ye9T686I-zoUA==/base.apk)
        at java.lang.Class.getDeclaredField(Native Method)
        at com.ichi2.libanki.Collection.getChunk(Collection.java:313)
        at com.ichi2.libanki.Collection.loadColumn(Collection.java:332)
        at com.ichi2.libanki.Collection.load(Collection.java:289)
        at com.ichi2.libanki.Collection.<init>(Collection.java:187)
        at com.ichi2.libanki.Storage.Collection(Storage.java:68)
        at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:122)
        at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:106)
        at com.ichi2.anki.services.BootService.getColSafe(BootService.java:87)
        at com.ichi2.anki.services.BootService.onReceive(BootService.java:50)
        at com.ichi2.anki.AnkiDroidApp.onCreate(AnkiDroidApp.java:274)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

_Originally posted by @Arthur-Milchior in https://github.com/ankidroid/Anki-Android/issues/6383#issuecomment-687906437_

### PR DESCRIPTION
**Pull request by mikehardy**
## Purpose / Description

We attempt to dynamically set the database cursor window chunk size we use for large text loading from sqlite, for performance reasons, but we were accessing the wrong field when attempting to do so

## Fixes

Fixes #7031 

## Approach

I use the correct field name when reflecting, exactly as @david-allison-1 pointed out with no change really, but with actual testing to make 100% sure :-)

## How Has This Been Tested?

The emulator was able to reproduce the problem, and now reproduces correct behavior:

> 2020-09-07 11:17:13.819 5569-5569/com.ichi2.anki D/Collection: Reflectively discovered database default cursor window size 2097152

## Learning (optional, can help others)

Even the simplest things can be screwed up! Haha - seriously though, I swear I tested this and saw it work, but here we are. Even Android Studio highlighted that it was a problem. An easy fix at least.

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java [hunk 1]
```diff
@@ -310,9 +310,10 @@ private int getChunk() {
         String db_name = ((DatabaseChangeDecorator) db).getWrapped().getClass().getName();
         if ("io.requery.android.database.sqlite.SQLiteDatabase".equals(db_name)) {
             try {
-                Field cursorWindowSize = io.requery.android.database.CursorWindow.class.getDeclaredField("sCursorWindowSize");
+                Field cursorWindowSize = io.requery.android.database.CursorWindow.class.getDeclaredField("sDefaultCursorWindowSize");
                 cursorWindowSize.setAccessible(true);
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java:314]: Can you also verify that this is non-negative, it's guaranteed not to be currently, but future refactorings introduce this risk.

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
Quick additional sanity check

File: AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java (hunk 1 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java:314]: yeah - good point

**Review by david-allison-1 — APPROVED** [review]
LGTM, thanks!

File: AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java (hunk 1 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java:314]: Just in case, I went one integer farther: if the window size is not greater than 0 it is effectively useless (not just != -1). So I check for a value > 0, and if not I make a warning and use the default now. Better?
