### PR TITLE
Note Editor - Fix Tab Order

### LINKED ISSUE #7433: NoteEditor: Tabbing fails on API 19 emulator
Worked on my phone, but the emulator doesn't work any more

Cycles between all elements in the ConstraintLayout

### PR DESCRIPTION
**Pull request by david-allison-1**
## Fixes
Fixes #7433

## Approach
Set IDs manually, so we can add a valid tab ordering on IDs for API < 26

## How Has This Been Tested?

API 30 emulator: passed

API 25, and 16 emulators, required different fixes, now pass

CI tests: Failing on API 25 and 30 - worked locally, so ignored.

## Learning (optional, can help others)
API 26 introduces navigation clusters which means the layout works out the box with a single `focusForward` change to the layout.

https://developer.android.com/about/versions/oreo/android-8.0#kbnc

Sending input is complex to do correctly over all SDK versions (events can be dropped if an activity is reset).

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)

### CODE REVIEW

File: AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTest.java [hunk 1]
```diff
@@ -0,0 +1,125 @@
...
+        /*
+        java.lang.AssertionError: Activity never becomes requested state "[DESTROYED]" (last lifecycle transition = "PAUSED")
+        at androidx.test.core.app.ActivityScenario.waitForActivityToBecomeAnyOf(ActivityScenario.java:301)
+         */
+        assumeThat("Test fails on Travis API 25", Build.VERSION.SDK_INT, not(is(25)));
+        /*
+        java.lang.AssertionError:
+        Expected: is "a"
+         */
+        assumeThat("Test fails on Travis API 30", Build.VERSION.SDK_INT, not(is(30)));
```
Comment (mikehardy) [inline AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTest.java:73]: Interesting - I wonder how API31 / S will go for us :-)

**Review by mikehardy — APPROVED** [review]
You will be the master of keyboard navigation and accelerators :-)

**Comment by mikehardy** [comment]
Seems to be flaky?

```
Starting 150 tests on test(AVD) - 7.1.1

com.ichi2.anki.NoteEditorTest > testTabOrder[test(AVD) - 7.1.1] FAILED 

	java.lang.AssertionError: Activity never becomes requested state "[DESTROYED]" (last lifecycle transition = "PAUSED")

	at androidx.test.core.app.ActivityScenario.waitForActivityToBecomeAnyOf(ActivityScenario.java:301)

> Task :AnkiDroid:connectedDebugAndroidTest FAILED

FAILURE: Build failed with an exception.

```

Not sure if it is API25 specific or not but it's happened twice now and I noted it was API25 only the second time before restarting

**Comment by david-allison-1** [comment]
> Seems to be flaky?
> 
> ```
> Starting 150 tests on test(AVD) - 7.1.1
> 
> com.ichi2.anki.NoteEditorTest > testTabOrder[test(AVD) - 7.1.1] FAILED 
> 
> 	java.lang.AssertionError: Activity never becomes requested state "[DESTROYED]" (last lifecycle transition = "PAUSED")
> 
> 	at androidx.test.core.app.ActivityScenario.waitForActivityToBecomeAnyOf(ActivityScenario.java:301)
> 
> > Task :AnkiDroid:connectedDebugAndroidTest FAILED
> 
> FAILURE: Build failed with an exception.
> ```
> 
> Not sure if it is API25 specific or not but it's happened twice now and I noted it was API25 only the second time before restarting

This should be disabled on API 25:

```
 assumeThat("Test fails on Travis API 25", Build.VERSION.SDK_INT, not(is(25)));
```

**Comment by mikehardy** [comment]
really wierd - definitely saw the failure a couple times and had the suspicion it was API specific. :thinking:

**Comment by mikehardy** [comment]
Well, it's sort of perma-broken there. No idea why it wouldn't work but it's been like that for 4 builds - I'm going to leave it at this point https://travis-ci.com/github/ankidroid/Anki-Android/jobs/405455923

**Comment by mikehardy** [comment]
Same error different build https://travis-ci.com/github/ankidroid/Anki-Android/jobs/405805607

Also a different API https://travis-ci.com/github/ankidroid/Anki-Android/jobs/405805602

```
Starting 150 tests on test(AVD) - 4.4.2

com.ichi2.anki.NoteEditorTest > testTabOrder[test(AVD) - 4.4.2] FAILED 

	java.lang.AssertionError:

	Expected: is "a"

> Task :AnkiDroid:connectedDebugAndroidTest FAILED
```

**Comment by david-allison-1** [comment]
Let's revert if it's causing problems, I'd put in a fair amount of time and thought it was solid in Travis, but there's no point in having it if it's flaky.
