### PR TITLE
fixIntegrity Refactor / Instrument+continue if field count fix fails

### LINKED ISSUE #5852: Make sure database check is robust
2.9.6 has a database check set for the userbase as part of #5823 

The first rule should be to do no harm so a database check should not result in a crash on a collection that was otherwise allowing reviews

Nevertheless I have seen two crashes via acralyzer during the database check for 2.9.6beta3 and now is an opportunity to make the fixIntegrity routine more robust as the majority of the beta testers have not updated to beta3 yet (meaning beta4 could see changes and better results)

Please note the line numbers within AnkiDroid are off because there is some unfixed between ACRA + D8/R8 that is not preserving the line numbers correctly, but it should be possible to puzzle out what's happening

```

03-22 05:56:08.859 I/AnkiDroid(25716): executing VACUUM statement
--
3 | 03-22 05:57:21.262 E/SQLiteLog(25716): (1034) os_unix.c:36228: (4) full_fsync(/sdcard/AnkiDroid/collection.anki2-journal) -
4 | 03-22 05:57:21.404 E/SQLiteLog(25716): (1034) statement aborts at 1: [VACUUM] disk I/O error
5 | 03-22 05:57:21.458 E/AnkiDroid(25716): DeckTask/ previously running task failed with exception: 14


java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:309)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
Caused by: android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 1034)
at io.requery.android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
at io.requery.android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:7)
at io.requery.android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:3)
at io.requery.android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:4)
at io.requery.android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:3)
at io.requery.android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1)
at com.ichi2.libanki.DB.execute(DB.java:6)
at com.ichi2.libanki.DB.execute(DB.java:1)
at com.ichi2.libanki.Collection.optimize(Collection.java:3)
at com.ichi2.libanki.Collection.fixIntegrity(Collection.java:118)
at com.ichi2.async.DeckTask.doInBackgroundCheckDatabase(DeckTask.java:5)
at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:45)
at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:295)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 4 more
```

```

03-22 09:03:53.157 I/AnkiDroid(18910): showStartupScreensAndDialogs() running integrityCheck()
--
2 | 03-22 09:03:53.237 I/AnkiDroid(18910): flush - Saving information to DB...
3 | 03-22 09:04:18.264 E/AnkiDroid(18910): Collection/ doInBackgroundCheckDatabase - RuntimeException on marking card


java.lang.IllegalStateException: Couldn't read row
at io.requery.android.database.CursorWindow.nativeGetString(Native Method)
at io.requery.android.database.CursorWindow.getString(CursorWindow.java:1)
at io.requery.android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:2)
at com.ichi2.libanki.Collection.fixIntegrity(Collection.java:36)
at com.ichi2.async.DeckTask.doInBackgroundCheckDatabase(DeckTask.java:5)
at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:45)
at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)
```

Ideally the work in fixIntegrity:
-  should be compartmentalized as much as possible,
-  if there is any possible way to recover we should
-  if there is any information at all we can show the user we should

All this may already be the case but with 2 problems out of 418 installs so far I don't like our odds as that could potentially scale to 7,177 problems out of our 1.5million users

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description

We added an additional database check inside `fixIntegrity`, which required that all users perform a database check.

This flagged that there were crash bugs in `fixIntegrity`

## Fixes
Fixes #5852 

## Approach

We modify each check into tasks, and perform each task in its own transaction, rather than running all in the same transaction.

## How Has This Been Tested?

* Check Integrity still works for me

* Added in an additional task which threw an exception. Exception was caught, logged and the process continued as expected.

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by david-allison-1** [comment]
Intended for this to be a draft, but misclicked. Can't see a way to convert it.

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5223804&bid=17127165)

File: AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java [hunk 1]
```diff
@@ -1606,182 +1608,44 @@ public long fixIntegrity(DeckTask.ProgressCallback progressCallback) {
         File file = new File(mPath);
         ArrayList<String> problems = new ArrayList<>();
         long oldSize = file.length();
-        int currentTask = 1;
+        final int[] currentTask = {1};
         int totalTasks = (mModels.all().size() * 4) + 21; // a few fixes are in all-models loops, the rest are one-offs
+        Runnable notifyProgress = () -> fixIntegrityProgress(progressCallback, currentTask[0]++, totalTasks);
+        FunctionalInterfaces.Consumer<FunctionalInterfaces.FunctionThrowable<Runnable, List<String>, JSONException>> executeIntegrityTask =
+                (FunctionalInterfaces.FunctionThrowable<Runnable, List<String>, JSONException> function) -> {
+                    try {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java]: This allows us to perform pre, and post- actions around any check.

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5223804&bid=17127165)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5223804&bid=17127165)

File: AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java [hunk 2]
```diff
@@ -1852,25 +1852,35 @@ public long fixIntegrity(DeckTask.ProgressCallback progressCallback) {
...
+                        if (flds.charAt(i) == 0x1f) {
+                            fldsCount++;
+                        }
                     }
+                    if (fldsCount + 1 != m.getJSONArray("flds").length()) {
+                        ids.add(id);
+                    }
+                } catch (IllegalStateException ex) {
+                    // DEFECT: Theory that is this an OOM is discussed in #5852
+                    AnkiDroidApp.sendExceptionReport(ex, "deleteNotesWithWrongFieldCounts");
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java]: I don't think this will advance us on the "it's an OOM / fields value greater than limit" theory unless you include the total row count and the row you are on. Idea being that if it's a non-zero row count but we are on the first row every time, there's something structural going on, but if any of them are non-zero it indicates that things are mostly working but there are problematic rows out there and it's much more likely it's the overflow similar to the templates which needed a conversion to chunk loading

Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java]: I'm logging with `Timber.d` above. 

But: I intended to ask whether it was OK to perform this inside a `while` loop, and if so, would including different parameters inside the context cause an issue with deduplication?

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java]: If the message is different it will likely not de-duplicate, but...I think more info will be worth it in this case. (does it happen for every row for a person? only one row?). People don't normally have that many templates and we'll learn fast on a beta release I think.

Timber.d will not log debug in release builds, it will be Timber.i and up only on release builds:

https://github.com/ankidroid/Anki-Android/blob/a2f8c09475c240d98e9373076ffdacc9683d05bd/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java#L204-L213

and the ProductionCrashReportTree.log impl:

https://github.com/ankidroid/Anki-Android/blob/a2f8c09475c240d98e9373076ffdacc9683d05bd/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java#L503-L509

Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java]: Thanks for the context (RE: Logging)

Each row in the cursor is a note, not a template. That's a little more fatal if we get it wrong.

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5223804&bid=17127165)

File: AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java (hunk 2 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java]: > If the message is different it will likely not de-duplicate, but...I think more info will be worth it in this case. 

Looks like it will

ACRA states that it's per stack trace

A quick glance at the code seems to agree. CUSTOM_DATA is a separate field.

https://github.com/ACRA/acra/blob/7e47a2e6f8fd8e9a3b3b7de83f5d54baefb62c97/acra-javacore/src/main/java/org/acra/ReportField.java#L81-L89

And it uses `getStacktrace` 

https://github.com/ACRA/acra/blob/4e2357a9390b7de6d8fd1ae41e167f62270e1606/acra-limiter/src/main/java/org/acra/config/LimitingReportAdministrator.java#L82-L89

Which is set to the `STACK_TRACE`

https://github.com/ACRA/acra/blob/4e2357a9390b7de6d8fd1ae41e167f62270e1606/acra-limiter/src/main/java/org/acra/config/LimiterData.java#L102-L103

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java]: I see what you mean - first they should be Timber.i in order to make sure we get them, then perhaps altering the structure so we Timber.i some general information about row count and that we're starting this work unit. Then we Timber.i with information about what row we are on if one of the rows threw an Exception and we save that we had >= 1 row with a problem as a boolean, and then when the cursor is exhausted we Timber.i that the work unit is done and we send an exception report if problem rows were >= 1. That way we'd only ever get one report, and the report should have a sufficient history of how the while loop unfolded

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5223804&bid=17127165)

**Comment by david-allison-1** [comment]
This feels like it's become too long. The last batch of changes removes the wrapping transaction around all the tasks, and instead wraps each task in a transaction.

At this point, I'd click "ready for review".

File: AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java [hunk 3]
```diff
@@ -1606,196 +1609,71 @@ public long fixIntegrity(DeckTask.ProgressCallback progressCallback) {
...
+        }
+        executeIntegrityTask.consume(this::deleteNotesWithMissingCards);
+        executeIntegrityTask.consume(this::deleteCardsWithMissingNotes);
+        executeIntegrityTask.consume(this::removeOriginalDuePropertyWhereInvalid);
+        executeIntegrityTask.consume(this::removeDynamicPropertyFromNonDynamicDecks);
+        executeIntegrityTask.consume(this::removeDeckOptionsFromDynamicDecks);
+        executeIntegrityTask.consume(this::rebuildTags);
+        executeIntegrityTask.consume(this::updateFieldCache);
+        executeIntegrityTask.consume(this::fixNewCardDuePositionOverflow);
+        executeIntegrityTask.consume((callback) -> resetNewCardInsertionPosition());
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java]: this one and ensureModelsAreNotEmpty stood out to me because they did not actually use the callback and did not seem to advance progress at all - is that correct? slightly larger question - is progress advancing correctly and terminating on a complete ratio still? (that was manually balanced before and I got it wrong the first couple times, myself

File: AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java [hunk 4]
```diff
@@ -1606,196 +1609,71 @@ public long fixIntegrity(DeckTask.ProgressCallback progressCallback) {
...
-            } catch (JSONException e) {
-                throw new RuntimeException(e);
-            } finally {
-                mDb.getDatabase().endTransaction();
+                };
+        try {
+            mDb.getDatabase().beginTransaction();
+            save();
+            notifyProgress.run();
+            if (!"ok".equals(mDb.queryString("PRAGMA integrity_check"))) {
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java]: Just saw that nowadays we can probably use this instead https://developer.android.com/reference/androidx/sqlite/db/SupportSQLiteDatabase#isDatabaseIntegrityOk() - not sure it existed before?

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java]: could maybe be made into a standard consumer that way?

**Comment by david-allison-1** [comment]
> Because it's so fundamental I just re-re-read it super closely again. a couple tiny things I'm curious about

I don't expect this to go in in a hurry. I have no intentions of rushing this through.

File: AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java (hunk 4 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java]: It's not a consumer as I wanted to keep the "if this fails, return -1 and stop" logic. If we don't want to keep that, then we can turn it into a "regular" integrity check.

I'll take a look through the source of the API, but should be fine to use

File: AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java (hunk 3 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java]: Models: 

https://github.com/ankidroid/Anki-Android/blob/2dd867f87f1f410504681d667ab208731bc78131/AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java#L1793-L1796

InsertionPosition:

https://github.com/ankidroid/Anki-Android/blob/2dd867f87f1f410504681d667ab208731bc78131/AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java#L1746-L1754

Happy to add in a check and update the count.

I've only extracted methods, so the number of checks won't change. 

There will be an undercount now, if certain tasks throw exceptions.

File: AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java (hunk 4 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java]: https://android.googlesource.com/platform/frameworks/base.git/+/43a17654cf4bfe7f1ec22bd8b7b32daccdf27c09/core/java/android/database/sqlite/SQLiteDatabase.java#2632 - LGTM

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java]: Careful - note we use requery which is an external sqlite implementation (so that we have reliable sqlite behavior back to the age dinosaurs roamed) - but still LGTM https://github.com/requery/sqlite-android/blob/master/sqlite-android/src/main/java/io/requery/android/database/sqlite/SQLiteDatabase.java#L2370

File: AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java (hunk 3 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java]: > Happy to add in a check and update the count.

Nothing like cleaner code to make previous defects / inconsistencies a bit more obvious. As long as this chunk is getting an overhaul (and I think correctly assuming that this won't be onerous at all) making them all consistent seems like the right way to go to me

> There will be an undercount now, if certain tasks throw exceptions.

Hmm - just a nit at this point, but structurally, if we are going to continue anyway we should advance the count. Only fully bubbling up a stop-the-check exception should stop it otherwise it should make it to completion

Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java]: I'll add it in as a defect for now, I can see this moving to a declarative style where we'll remove the need for the manual `totalTasks` count at the same time as fixing this.

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java]: works for me - then no change and it's final review + merge with a reference to a new issue?

Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java]: On that aspect, yes.

Got about 3 review changes to push (integrity check, comment and fix progress notifications), will @ you when done. Logcat just died for me, so may be a few minutes.

**Comment by david-allison-1** [comment]
@mikehardy final changes pushed, ready for re-re-review ;)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5223804&bid=17127165)

**Comment by mikehardy** [comment]
2.10alpha55 is out with the fix, as soon as Google is done processing it and starts delivery...

**Comment by mikehardy** [comment]
Actually, I just bumped the database version check to alpha56 and released a quick follow-on in order to exercise - it occurred to me after release that if we didn't run the thing it wouldn't matter much!

**Comment by mikehardy** [comment]
released in 2.9.6beta4 with db check code bumped up on hotfix-2.9.6 branch to match so it will run again
