### PR TITLE
Fix for empty search results and wrong card count

### LINKED ISSUE #8975: [Bug] Card Browser "Search All Decks" not returning correct results
###### Reproduction Steps

Thr bug appeared after yesterday's update.

1. I am in the card browser menu of a deck on Anki Droid.
2. I search for a word.
3. There are no matches.
4. A button appears at the bottom to search all decks.
5. I click it and it returns no results (unlike before the update) even though it should return a result. 
6. If I click the menu on top which now says "All Decks" I can see only some 170 or so cards are included in this fictional "All Decks" folder and not the total of 4000 that I have. 
7. If I choose again manually "All Decks - 4000 cards", from the dropdown now the result of the search is correctly displayed. 

###### Expected Result

Before the update the "Search all decks" would return a result. On the top under All Decks was written the corect number of the total cards. 

###### Actual Result
No result is returned unless manually switched to All Decks from the drop down menu on top. The number of cards displayed under the  All Decks on top is wrong and is a much smaller number, again unless manually switched to All Decks. 

###### Debug info

AnkiDroid Version = 2.15.2

Android Version = 11

Manufacturer = samsung

Model = SM-G998B

Hardware = exynos2100

Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-G998B Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.210 Mobile Safari/537.36

ACRA UUID = 34e4a61d-0029-4993-babd-17ea0e5a2781

Scheduler = std

Crash Reports Enabled = true

DatabaseV2 Enabled = true

Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by ShridharGoel**
## Purpose / Description
Fix for empty search results and wrong card count.

## Fixes
Fixes #8975 

## Approach
Setting `mRestrictOnDeck` to an empty String and calling `searchCards()` method inside `selectAllDecks()`.
 
## How Has This Been Tested?

Verified that the bug has been fixed.

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java [hunk 1]
```diff
@@ -853,7 +853,9 @@ private void toggleMark() {
     @VisibleForTesting
     void selectAllDecks() {
         mDeckSpinnerSelection.selectDropDownItem(0);
-        saveLastDeckId(Stats.ALL_DECKS_ID);
+        mRestrictOnDeck = "";
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java:856]: Could you add a test for this? The Card Browser is hairy right now (buggy, and complex code), and the more test coverage we have, the better chance we have for refactoring it into something workable later

Comment (ShridharGoel) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java:856]: Added.

Comment (ShridharGoel) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java:856]: Added.

Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java:856]: Looks good! Let me test locally. Please ping me if this isn't reviewed in 24 hours

**Comment by david-allison-1** [comment]
Is this a regression:

* Search All Decks
* Select a card
* The keyboard opens and closes almost immediately

**Comment by ShridharGoel** [comment]
> Is this a regression:
> 
> * Search All Decks
> * Select a card
> * The keyboard opens and closes almost immediately

This is happening on the current master as well, when search results are present for the currently selected deck. I'll handle this in a separate PR.

**Comment by ShridharGoel** [comment]
> Is this a regression:
> 
> * Search All Decks
> * Select a card
> * The keyboard opens and closes almost immediately

Just checked, this is happening on the current master as well, when search results are present for the currently selected deck. I'll handle this in a separate PR.

**Review by david-allison-1 — APPROVED** [review]
LGTM

**Review by mikehardy — APPROVED** [review]
nice!
