### PR TITLE
open collective link opening fix

### LINKED ISSUE #12720: [Bug] Changelog style applies to Open Collective if opened via link click
###### Reproduction Steps

1. About -> Changelog -> Stable Changelog -> "Thank you" link to Open Collective
2. OC opens in the WebView

###### Expected Result

Either:

* Open Collective opens in a 'Chrome' browser window
* Styles are unchanged

###### Actual Result

* Open Collective appears with colored links from the CSS
Screenshot 2022-10-23 at 13 28 23

###### Debug info

AnkiDroid Version = 2.16alpha88

Android Version = 12

Manufacturer = unknown

Model = Android SDK built for arm64

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 12; Android SDK built for arm64 Build/SE1A.220621.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.114 Mobile Safari/537.36

ACRA UUID = 319004e4-1ceb-4aa1-867a-afe72be08340

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by criticalAY**
## Purpose / Description
[Bug] Changelog style applies to Open Collective if opened via link click
Fixes #12720
 changes 

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by criticalAY** [comment]
> 

I thought of it but I am not a html expert so didn't wanted to experiment but l will give it a try

**Comment by criticalAY** [comment]
Don't we have to use css for that ?

**Comment by BrayanDSO** [comment]
> Don't we have to use css for that ?

Yes. You can use CSS (and javascript) inside a HTML document

**Comment by criticalAY** [comment]
lemme try

**Comment by criticalAY** [comment]
I tried using js but doing so doesn't get the work done, href links doesn't work in that case 
`  /* The order of below javascript code must not change (this order works both in debug and release mode)
//                                 *  or else it will break in any one mode.
//                                 */`

there was this comment

**Comment by criticalAY** [comment]
though I referred https://developer.android.com/develop/ui/views/layout/webapps/webview#EnablingJavaScript:~:text=All%20links%20the,of%20Activity. for the usage of this methods and found it relevant

**Comment by criticalAY** [comment]
David could you please take a glimpse whenever you are free @david-allison

File: AnkiDroid/src/main/java/com/ichi2/anki/Info.kt [hunk 1]
```diff
@@ -115,6 +117,19 @@ class Info : AnkiActivity() {
...
+                    override fun shouldOverrideUrlLoading(
+                        view: WebView?,
+                        request: WebResourceRequest?
+                    ): Boolean {
+                        if (request?.url.toString() == "https://docs.ankidroid.org/changelog.html" || request?.url.toString() == "https://github.com/ankidroid/Anki-Android/commits/main") {
+                            return false
+                        }
+                        Intent(Intent.ACTION_VIEW, Uri.parse(request?.url.toString())).apply {
+                            startActivity(this)
+                        }
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/Info.kt:130]: Thoughts on using `openUrl` here instead?

File: AnkiDroid/src/main/java/com/ichi2/anki/Info.kt [hunk 2]
```diff
@@ -115,6 +117,19 @@ class Info : AnkiActivity() {
                                 "document.body.style.setProperty(\"background\", \"" + background + "\");"
                         )
                     }
+
+                    override fun shouldOverrideUrlLoading(
+                        view: WebView?,
+                        request: WebResourceRequest?
+                    ): Boolean {
+                        if (request?.url.toString() == "https://docs.ankidroid.org/changelog.html" || request?.url.toString() == "https://github.com/ankidroid/Anki-Android/commits/main") {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/Info.kt:125]: This could do with a comment explaining why we're special-casing two URLs.

We may want to extract these to constants to ensure the logic here is consistent if the values change

File: AnkiDroid/src/main/java/com/ichi2/anki/Info.kt (hunk 1 above)
Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/Info.kt:130]: I did but the official doc suggest not using that while returning true as this unnecessarily cancels the current load and starts a new load with the same URL

**Comment by criticalAY** [comment]
the test:

https://user-images.githubusercontent.com/48384865/212636323-8e78e9ad-6574-41c7-9204-110810c36b82.mp4

**Comment by criticalAY** [comment]
@david-allison could you review this PR as it has been pending for months now

**Review by david-allison — CHANGES_REQUESTED** [review]
Needs to check if the user has a web browser:

https://github.com/ankidroid/Anki-Android/blob/ffa4c3be55ea869ef5fc4368ee5c7e54f32906d4/AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt#L422

**Review by david-allison — APPROVED** [review]

**Review by mikehardy — APPROVED** [review]
Nice
