### PR TITLE
Fix: Enter triggers OK without extra press

### LINKED ISSUE #18340: Wrong password require to "enter" tap to dismiss
How to reproduce:
* don't have an ankiweb account on ankidroid
* try to sync
* from the sync page, enter an email and a wrong password
* when the error message appear, type "enter"

Expected: 
* enter is equivalent to tapping on "ok" and close the alert

Actual:
* pressing enter cause "ok" to become selected. A second press on "enter" will close the alert

### PR DESCRIPTION
**Pull request by samirsuroshe18**
## Purpose / Description
When an alert dialog appears after entering incorrect credentials in the sync page, pressing the Enter key only selects the "OK" button instead of triggering it. This PR modifies the behavior so that pressing Enter directly triggers the positive button action, making the user experience more intuitive.

## Fixes
* Fixes #18340

## Approach

Added an extension function setupEnterKeyHandler() to handle Enter key presses in AlertDialogs
Modified the existing show() extension function to apply this handler to all dialogs created through the builder pattern
The handler detects Enter key presses and simulates a click on the positive button if it exists and is enabled

## How Has This Been Tested?

Manually verified with the following steps:

Without an AnkiWeb account on AnkiDroid
Attempted to sync
From the sync page, entered an email and wrong password
When error message appeared, pressed Enter key

#### 🎥 Before the Fix
<details>
  <summary>Click to expand</summary>

[failure.webm](https://github.com/user-attachments/assets/742512ca-e722-4be7-a097-119e5e430614)

</details>

#### 🎥 After the Fix
<details>
  <summary>Click to expand</summary>

https://github.com/user-attachments/assets/303ec6ee-bc26-41f1-9ab5-dc3e5f2df881

</details>

Before the fix, Enter key only selected the "OK" button requiring a second press.
After the fix, Enter key immediately dismisses the dialog.

## Learning
The default behavior of AlertDialogs in Android is to only select but not trigger buttons when Enter is pressed. This is a common UI pattern that needs explicit handling to improve user experience

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt [hunk 1]
```diff
@@ -144,7 +145,27 @@ fun AlertDialog.Builder.cancelable(cancelable: Boolean): AlertDialog.Builder = t
  */
 inline fun AlertDialog.Builder.show(block: AlertDialog.Builder.() -> Unit): AlertDialog {
     this.apply { block() }
-    return this.show()
+    val dialog = this.show()
+    return dialog.setupEnterKeyHandler()
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt]: For reviewer 2 to confirm, but I'd rather explicitly opt-in to this on a per-dialog basis, OR find a way to make this a standard default via accessibility

This use of `setOnKeyListener` overrides any listeners which we set in calling code, which isn't intuitive to me.

Comment (samirsuroshe18) [reply AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt]: Thanks for the feedback! You're absolutely right about setOnKeyListener potentially overriding existing listeners — that could definitely lead to unexpected behavior.

To address this, I’m planning to go with an opt-in approach by modifying the show() function to accept an optional parameter:

`fun AlertDialog.Builder.show(enableEnterKeyHandler: Boolean = false)`

This way, setupEnterKeyHandler() will only be applied when explicitly requested, preserving backward compatibility and avoiding side effects in existing dialogs.

Let me know if this direction works for you, and I’ll update the PR accordingly.

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt]: Sounds great!

**Review by mikehardy — APPROVED** [review]
LGTM - pending merge, needs squash so has to wait for merge queue to be empty

**Comment by mikehardy** [comment]
I'm in the middle of a merge festival and the isn't going to empty until long after I've moved to other things so I rebased this one to squash it locally then force-pushed that, so I can put it in the auto queue

**Comment by david-allison** [comment]
Hi there @samirsuroshe18! This is the OpenCollective Notice for PRs merged from [2025-06-01 through 2025-06-30](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2025-06-01..2025-06-30+author%3Asamirsuroshe18)
                      
If you are interested in compensation for this work, the process with details is here: https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

We only post one comment per person per month to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for this month

Please understand that our monthly budget is never guaranteed to cover all claims - the cap on payments-per-person may be lower, but we try to make our process as fair and transparent as possible, we just need your understanding.

Thanks!
