### PR TITLE
fix: add note in split browser

### LINKED ISSUE #19864: Add Note button not functional in Split CardBrowser
> Also, the Add note button does not do anything right now, when side-by-side cardBrowser noteEditor exists. 
> 
> I think it's best if we let the save note button save the note, but let the add note button launch noteEditor activity, and leave the current editor to just focus on editing. 

 _Originally posted by @Haz3-jolt in [#19805](https://github.com/ankidroid/Anki-Android/issues/19805#issuecomment-3671280843)_

### PR DESCRIPTION
**Pull request by sanjaysargam**
## Purpose / Description
launch note editor activity on add note even if fragmented

## Fixes
* Fixes #19864

## Approach
Remove if `fragmented` case

## How Has This Been Tested?
Chromebook

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt [hunk 1]
```diff
@@ -122,7 +122,7 @@ open class CardBrowser :
      */
     @get:VisibleForTesting
     val addNoteLauncher: NoteEditorLauncher
-        get() = createAddNoteLauncher(viewModel, fragmented)
+        get() = createAddNoteLauncher(viewModel)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt:125]: This argument (`inCardBrowserActivity`) is no longer used

```patch
Subject: [PATCH]
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/NoteEditorLauncher.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/NoteEditorLauncher.kt b/AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/NoteEditorLauncher.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/NoteEditorLauncher.kt	(revision 1062c4df8b1582e3b9a92f05ce0624ee6d006704)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/NoteEditorLauncher.kt	(date 1765532439195)
@@ -104,15 +104,14 @@
      * @property viewModel The view model containing data from the card browser.
      */
     data class AddNoteFromCardBrowser(
-        val viewModel: CardBrowserViewModel,
-        val inCardBrowserActivity: Boolean = false,
+        val viewModel: CardBrowserViewModel
     ) : NoteEditorLauncher {
         override fun toBundle(): Bundle {
             val fragmentArgs =
                 bundleOf(
                     NoteEditorFragment.EXTRA_CALLER to NoteEditorCaller.CARDBROWSER_ADD.value,
                     NoteEditorFragment.EXTRA_TEXT_FROM_SEARCH_VIEW to viewModel.searchTerms,
-                    NoteEditorFragment.IN_CARD_BROWSER_ACTIVITY to inCardBrowserActivity,
+                    NoteEditorFragment.IN_CARD_BROWSER_ACTIVITY to false,
                 )
             if (viewModel.lastDeckId?.let { id -> id > 0 } == true) {
                 fragmentArgs.putLong(NoteEditorFragment.EXTRA_DID, viewModel.lastDeckId!!)
Index: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt b/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt	(revision 1062c4df8b1582e3b9a92f05ce0624ee6d006704)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt	(date 1766241781170)
@@ -1358,9 +1358,8 @@
 
         @VisibleForTesting
         fun createAddNoteLauncher(
-            viewModel: CardBrowserViewModel,
-            inCardBrowserActivity: Boolean = false,
-        ): NoteEditorLauncher = NoteEditorLauncher.AddNoteFromCardBrowser(viewModel, inCardBrowserActivity)
+            viewModel: CardBrowserViewModel
+        ): NoteEditorLauncher = NoteEditorLauncher.AddNoteFromCardBrowser(viewModel)
     }
 }
```
