### PR TITLE
fix(custom-study): defer loading of 'customStudyDefaults'

### LINKED ISSUE #18416: Opening custom study menu is slow
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

- Long press any deck in the deck picker
- Select custom study
- The custom study menu appears after a delay. (about 1 second)

### Expected behaviour

The custom study menu should appear instantly.

### Debug info

```text
2.21 alpha 16

I was able to reproduce the bug in 2.21 alpha 6 too but not in 2.20.0
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description

Speeds up dialog appearance

This takes > 100ms on my phone, and was reported to take >1s on larger collections

## Fixes
* Fixes #18416

## Approach
* load 'defaults' async
  * if it loads before we build the initial dialog, no change
  * if it loads after the initial dialog, if appropriate, update the UI to disable 'increase limit' options
* if a 'increase limit' option is clicked
  * wait for defaults to load, and inform the user if unavailable

## How Has This Been Tested?
Tested with `delay(5_000)` inside loadCustomStudyDefaults

* menu items were made unavailable
* Clicking the item worked if valid
* Clicking the item showed a snackbar if invalid, dialog was still usable

## Learning (optional, can help others)
Issue introduced in caadde7034cd4bc559f5e424e8a786f7ba1ecca1

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
LGTM (enough going on, marked for second...)

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt [hunk 1]
```diff
@@ -608,15 +675,40 @@ class CustomStudyDialog : AnalyticsDialogFragment() {
...
 
     companion object {
-        fun createInstance(
+        /**
+         * @see CustomStudyDefaults
+         *
+         * Singleton; initialized when the main screen is loaded
+         * This exists so we don't need to pass an unbounded object between fragments
+         */
+        private lateinit var deferredDefaults: Deferred<CustomStudyDefaults>
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt:684]: Would a viewModel have some kind of problem?

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt:684]: It would work, but I can't find a suitable "home" for a view model here

The scope is the initial dialog, which closes itself and launches another dialog

Moving it to the activity means that we need a cleanup and reset mechanism, which seemed nasty
