### PR TITLE
Moved cursor to end in NumberRangePreferenceCompat

### LINKED ISSUE #13799: [BUG]:  Move cursor to end in NumberRangePreferenceCompat
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Go to Preference Screen which contains NumberRangePreferenceCompat. For example, 
ReviewingSettingsFragment
2.  Click on Preference which has NumberRangePreferenceCompat

### Expected behaviour

The cursor should be at the end of the input text

### Actual behaviour

The cursor is at the front of input text

### Debug info

```text
AnkiDroid Version = 2.16.0beta1-debug

Android Version = 10

ProductFlavor = amazon

Manufacturer = Google

Model = Android SDK built for x86

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 10; Android SDK built for x86 Build/QSR1.210802.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/74.0.3729.185 Mobile Safari/537.36

ACRA UUID = b2a4663f-820a-4966-a08c-9f4d18693934

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by SanjaySargam**
## Purpose / Description
It's become inconvenient for the user to relocate the cursor to end every time

## Fixes
Fixes #13799

## Approach
called `setFocusAndOpenKeyboard()` function which is already there in AndroidUiUtils

## How Has This Been Tested?

Tested on Emulator (Pixel 5 API 29)

https://user-images.githubusercontent.com/65113071/236374491-d1ae3dce-4821-4abd-952c-687f86d5c8b8.mp4

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by lukstbit — COMMENTED** [review]
There's no need to create a method for one line of code. Inline the call.

**Comment by SanjaySargam** [comment]
> There's no need to create a method for one line of code used once. Inline the call.

Ok

File: AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreferenceCompat.kt [hunk 1]
```diff
@@ -173,6 +174,8 @@ constructor(
 
             // Clone the existing filters so we don't override them, then append our one at the end.
             editText.filters = arrayOf(*editText.filters, InputFilter.LengthFilter(numberRangePreference.maxDigits))
+
+            setFocusAndOpenKeyboard(editText) { editText.setSelection(editText.text.length) }
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/preferences/NumberRangePreferenceCompat.kt:178]: `super.onBindDialogView()` already does this (hence why default text preferences put the cursor at the ended), but the selection is changed after the inputType or the filters are changed (I haven't checked which or if both)

So I propose something like this:
```kotlin
        override fun onBindDialogView(view: View) {
            editText = view.findViewById(android.R.id.edit)!!

            // Only allow integer input
            editText.inputType = InputType.TYPE_CLASS_NUMBER

            // Clone the existing filters so we don't override them, then append our one at the end.
            editText.filters = arrayOf(*editText.filters, InputFilter.LengthFilter(numberRangePreference.maxDigits))

            super.onBindDialogView(view)
        }
```

**Review by BrayanDSO — CHANGES_REQUESTED** [review]

**Review by BrayanDSO — APPROVED** [review]

**Review by lukstbit — APPROVED** [review]
