### PR TITLE
Autofocus keyboard in Resume State only when "type in answer" checked ✅

### LINKED ISSUE #14404: [BUG]: first time entering a deck  "focus type in answer" is not honored
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

uncheck `settings> advanced> workarounds > focus type in answer`

go to a deck with a type in field, first time keyboard shows. After you dismiss it, it wont show again

### Expected behaviour

I would expect to never show the keyboard unless i press on the field

### Actual behaviour

keyboard shows

### Debug info

```text
AnkiDroid Version = 2.16.4
Android Version = 12
ProductFlavor = full
Hardware = qcom
New schema = false
Scheduler = std2
Crash Reports Enabled = true
DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by SanjaySargam**
## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
* Fixes #14404 

## Approach
This issue was introduced due to #13451 . 
Check whether the field is autoFocus EditText or not

## How Has This Been Tested?

Physical Device ( Realme 9 )

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt [hunk 1]
```diff
@@ -193,7 +193,7 @@ open class Reviewer :
             else -> answerTimer.resume()
         }
         super.onResume()
-        if (answerField != null) {
+        if (typeAnswer?.autoFocusEditText() == true) {
             answerField!!.focusWithKeyboard()
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt:197]: This removes the check for `answerField != null`, could you change the line to:

`answerField?.focusWithKeyboard()`

**Review by david-allison — CHANGES_REQUESTED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt (hunk 1 above)
Comment (SanjaySargam) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt:197]: Ok

**Review by david-allison — APPROVED** [review]

**Review by BrayanDSO — APPROVED** [review]
