### PR TITLE
Fix `DeckPicker#searchDecksIcon` flash

### LINKED ISSUE #11842: [Bug] Search icon flashes after syncing
###### Reproduction Steps

1. Have 10 or more decks
2. Tap sync
3. Wait the sync completion

###### Expected Result

Search icon doesn't change (assuming there are 10+ decks after sync)

###### Actual Result

Search icon flashes

[untitled.webm](https://user-images.githubusercontent.com/69634269/178474460-25e38eb2-9313-424d-88b0-122a5c58352a.webm)

###### Debug info
AnkiDroid Version = 2.16alpha73

Android Version = 7.1.1

Manufacturer = Google

Model = Android SDK built for x86

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 7.1.1; Android SDK built for x86 Build/NYC; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/69.0.3497.100 Mobile Safari/537.36

ACRA UUID = 209703e1-d092-4835-8cf8-bb99f7179fc4

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by dorrin-sot**
## Fixes
Fixes #11842

## How Has This Been Tested?

https://user-images.githubusercontent.com/59933477/179100402-4a8c2dfe-cb2d-4ea3-b02a-c5ac247c412e.mov

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 1]
```diff
@@ -634,12 +635,15 @@ open class DeckPicker :
...
         return super.onCreateOptionsMenu(menu)
     }
 
     private fun updateSearchDecksIconVisibility() {
-        searchDecksIcon?.isVisible = colIsOpen() && col.decks.count() >= 10
+        searchDecksIcon?.isVisible = try {
+            col.decks.count() >= 10
+        } catch (e: Exception) {
+            false
+        }
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:646]: Can you please add a comment here stating what kind of error this can throw and why it should be catch?

**Review by BrayanDSO — COMMENTED** [review]
FWIW, I've cherry-picked this to my local AnkiDroid build and have been using it for ~3 weeks now and it works perfectly.

**Review by david-allison — CHANGES_REQUESTED** [review]
I believe that this will crash if the collection cannot be opened (for example: corruption).

**Review by david-allison — APPROVED** [review]
Actually... mirroring @BrayanDSO's comment. This will work in all cases, but a comment would be much appreciated

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 2]
```diff
@@ -634,12 +635,16 @@ open class DeckPicker :
                 menu.findItem(R.id.action_undo).title = undo
             }
         }
-        updateSearchDecksIconVisibility()
         return super.onCreateOptionsMenu(menu)
     }
 
+    // Try setting it to `col.decks.count() >= 10`. If there was any issue (e.g. corrupt collection), set it to false
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:641]:
```suggestion
    /**
      * Show [searchDecksIcon] if there are more than 10 decks.
      * Otherwise, hide it if there are less than 10 decks 
      * or if a exception is thrown while getting the decks count (e.g. corrupt collection)
      */
```

Using a javadoc here may be more useful, as the user will be able to see this description while hovering the method on the IDE

**Review by BrayanDSO — CHANGES_REQUESTED** [review]

**Comment by BrayanDSO** [comment]
> /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:642:1 Unexpected indentation (6) (should be 5)
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:643:1 Unexpected indentation (6) (should be 5)
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:643:59 Trailing space(s)
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:643:60 Unnecessary long whitespace
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:644:1 Unexpected indentation (6) (should be 5)
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:645:1 Unexpected indentation (6) (should be 5)

My suggestion had one more space than necessary, not it needs a fix, I'm sorry

**Review by BrayanDSO — APPROVED** [review]

**Review by lukstbit — APPROVED** [review]
