### PR TITLE
Only restricted devices require system browser

### LINKED ISSUE #6109: Failed to load online content in 2.10beta2
After updating to the newest version I found the online pictures in my cards failed to load. At first I thought it was because of the poor internet connection, but the synchronizing function works well. And when I copied the content to 2.9.6, it showed successfully. I think there's something wrong here.

### PR DESCRIPTION
**Pull request by mikehardy**
## Purpose / Description
#5913 implements a system-app-only requirement for the web browser on restricted learning devices, but implements it in a way that imposes that restriction even for non-restricted browsers

## Fixes
#6109 - non-restricted device could not load web content

## Approach
This makes the "is the browser a system app?" check only apply on restricted devices

I also added copyright header, fixed whitespace, and changed the variable + method names to contain the feature's intent in the name

## How Has This Been Tested?

- Local `./gradlew jacocoTestReport` on this one after visual inspection a few times
- API28 emulator get shared decks with Chrome installed: worked (correct)
- API28 emulator w/Chrome disabled: got a toast saying no browser (correct)
- API28 emulator w/Chrome disabled, Firefox installed as user: worked (correct)

## Learning (optional, can help others)
Nothing special, just that code review is both valuable and still very faulty. Missed this when it went through the first time

## Checklist

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.java [hunk 1]
```diff
@@ -23,23 +41,16 @@ public static boolean hasWebBrowser(Context context) {
...
-                if (isSystemApp(pacagename, pm)) {
-                    sHasWebBrowser = true;
-                    break;
-                }
-            }
+        sHasWebBrowser = false;
+        for (ResolveInfo ri : list) {
+            sHasWebBrowser = !isRestrictedLearningDevice() || isSystemApp(ri.activityInfo.packageName, pm);
+            break;
         }
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.java:48]: @david-allison-1 with apologies for the noisiness of the diff, this is the actual logic change - does it look right to you now? (only applying the "is it a system web browser?" check if we are restricted

It did pass local testing but I'm going to pick this to 2.10-release immediately after merge so a second set of eyes is 🥇

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.java:48]: Note the system API to queryIntentActivities is guaranteed to return empty list / nonnull, that's important :)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           

Complexity decreasing per file
==============================
+ AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.java  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5482009&bid=17964771)

File: AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.java [hunk 2]
```diff
@@ -23,23 +41,16 @@ public static boolean hasWebBrowser(Context context) {
...
-                String pacagename = ri.activityInfo.packageName;
-                if (isSystemApp(pacagename, pm)) {
-                    sHasWebBrowser = true;
-                    break;
-                }
-            }
+        sHasWebBrowser = false;
+        for (ResolveInfo ri : list) {
+            sHasWebBrowser = !isRestrictedLearningDevice() || isSystemApp(ri.activityInfo.packageName, pm);
+            break;
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.java:47]: Codacy Issue found: [Avoid using a branching statement as the last in a loop.](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5482009)

File: AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.java (hunk 1 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.java]: Codacy left me a comment that was actually right and pointed out a flaw. I just re-pushed

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5482009&bid=17964771)

File: AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.java [hunk 3]
```diff
@@ -23,23 +41,24 @@ public static boolean hasWebBrowser(Context context) {
...
-            for (ResolveInfo ri:list) {
-                String pacagename = ri.activityInfo.packageName;
-                if (isSystemApp(pacagename, pm)) {
-                    sHasWebBrowser = true;
-                    break;
-                }
+        sHasWebBrowser = false;
+        for (ResolveInfo ri : list) {
+            // If we aren't a restricted device, any browser will do
+            if (!isRestrictedLearningDevice()) {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.java:47]: (optional): Could be extracted out of the loop for clarity.

File: AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java [hunk 4]
```diff
@@ -133,7 +133,7 @@ public void onBuildHeaders(List<Header> target) {
         Iterator iterator = target.iterator();
         while (iterator.hasNext()) {
             Header header = (Header)iterator.next();
-            if ((header.titleRes == R.string.pref_cat_advanced) && AdaptionUtil.hasReducedPreferences()){
+            if ((header.titleRes == R.string.pref_cat_advanced) && AdaptionUtil.isRestrictedLearningDevice()){
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java:136]: spacing on the `{`

File: AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.java (hunk 3 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.java:47]: cannot actually, we must know we have at least one entry in the list before true is ever returned, so it has to be in the loop signifying we have size() >= 1

File: AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java (hunk 4 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java:136]: Aw dang. Fixed a couple of those but this will have to sit. Next time...

Thank you for double-checking though, I do appreciate it even though I short-circuited a bit. Could've always done a beta4 np if there was something goofy in here

File: AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.java (hunk 3 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.java:47]: Would be useful in a clarifying comment then (for next time) 😉
