### PR TITLE
fix: crash & overlapping sounds if quickly changing cards in Previewer 

### LINKED ISSUE #15103: [BUG]: Sound player crashes if changing cards really fast
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Android 34 emulator, with the [🗍 1000 Basic English Words](https://ankiweb.net/shared/info/1243388349) deck:

1. Open the default previewer with many cards with audios (like the example above)
2. Change cards really fast with the slider

[big bang.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/c56c7a74-e955-4eaa-abdc-cc4a9bb21b1d)

### Expected behaviour

Nothing crashes

### Actual behaviour

Things crash

### Debug info

```text
AnkiDroid Version = 2.17alpha14-debug (e5138964c3b822c8d3dd40c81bb64c56dc5b9b17)

Backend Version = 0.1.32-anki23.10.1 (23.10.1 fac9e0ee1436ba5ac3366c72dd9394a6e692b1cf)

Android Version = 14 (SDK 34)

ProductFlavor = full

Manufacturer = Google

Model = sdk_gphone64_x86_64

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 14; sdk_gphone64_x86_64 Build/UE1A.230829.036; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/113.0.5672.136 Mobile Safari/537.36

ACRA UUID = e26f3b42-5e3f-4325-9324-f5c71a9b5fda

Crash Reports Enabled = false
```

### (Optional) Anything else you want to share?

FWIW, the new previewer slider doesn't update the note until the user releases it. It probably won't take long before I push the PR making it the default

Not sure if this will happen in normal conditions (i.e. people not reviewing superfast)

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### LINKED ISSUE #15133: [BUG]: TTS doesn't stop when next card is shown
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1) review a card where the anser is read out with TTS
2) Anser card to load the next card

### Expected behaviour

TTS stops, like in all Ankidroid versions before.

### Actual behaviour

TTS remains to read out the previous answer, even though the next question is shown. That's confusing.

### Debug info

```text
AnkiDroid Version = 2.17alpha14 (0717daab11cd9669997aea6a421ec94689120cb6)

Backend Version = 0.1.32-anki23.10.1 (23.10.1 fac9e0ee1436ba5ac3366c72dd9394a6e692b1cf)

Android Version = 12 (SDK 31)

ProductFlavor = play

Manufacturer = motorola

Model = moto g(60)s

Hardware = mt6785

Webview User Agent = Mozilla/5.0 (Linux; Android 12; moto g(60)s Build/S3RLS32.114-25-13; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.144 Mobile Safari/537.36

ACRA UUID = 751875a7-f00b-41fe-90b1-2bcc6af0617f

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
* #15103
* I then found that after fixing it, I could get two sounds playing at the same time
* I then found that after transient errors, sounds didn't play

## Fixes
* Fixes #15103
* Fixes #15133

## Approach
* Gate `resume` calls with a check on the completion status of the continuation
* Check the active status of the continuation before executing slow operations
* set `playSoundsJob` correctly
* use `RETRY_AUDIO` as a crutch
* maintain a list of `currentUtterance/cancelledUtterances` in the TTS class

## How Has This Been Tested?
API 33 emulator

## Learning (optional, can help others)
The Previewer is a GREAT stress test of the workings of the Sound Player

* Obvious, but `resumeWithException` can't be called if `resume()` was called
* There is a lot of nuance to the MediaPlayer - `RETRY_AUDIO` is a crutch which completely fixes the issues
* TTS: `speak()`, then `stop()` won't stop audio if we are before `onStart()`
  * But if we're AFTER playing a different set of audio, it will stop that 

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/SoundPlayer.kt [hunk 1]
```diff
@@ -297,6 +296,16 @@ class SoundPlayer(
         return player
     }
 
+    /** Ensures that only one [playSoundsJob] is running at once */
+    private suspend fun playSoundsJob(block: suspend CoroutineScope.() -> Unit) {
```
Comment (ShridharGoel) [inline AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/SoundPlayer.kt:300]: We can also create a generic `cancelPreviousAndRun` method in the future,

**Comment by david-allison** [comment]
After a retest, issue 2 is still unresolved

**Review by BrayanDSO — APPROVED** [review]
nice

**Review by mikehardy — APPROVED** [review]
Wow - what a snarl of issues. All fixes LGTM
