### PR TITLE
fix(sync): reduce notification update rate

### LINKED ISSUE #19546: Media sync: too many notification updates
```
13:22:30.435   531-2425  NotificationService      E  Package enqueue rate is 5.0687265. Shedding 0|com.ichi2.anki.debug|123|null|10199. package=com.ichi2.anki.debug
```

### PR DESCRIPTION
**Pull request by BrayanDSO**
make it slower, but still fast enough to be responsive

## Fixes
* Fixes #19546

## How Has This Been Tested?

I haven't. The logic is straightforward

## Learning (optional, can help others)

Android has some kind of notification rate limit. I haven't found any official documentation about the exact limit.

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncMediaWorker.kt [hunk 1]
```diff
@@ -120,7 +120,7 @@ class SyncMediaWorker(
                 val notificationText = syncProgress.run { "$added $removed $checked" }
                 notify(getProgressNotification(notificationText))
             }
-            delay(100)
+            delay(600)
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncMediaWorker.kt]: I'm open to other delays.

I haven't put much thought into this. It just seemed reasonable to me.

**Comment by BrayanDSO** [comment]
- Added a NOTIFICATION_MIN_DELAY_MS constant
- Reduced the sync workers' delay to 500ms (2x a second seems ok to me)
- added a very very simple test to guarantee that the workers delay is higher than the min delay

File: AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncMediaWorker.kt [hunk 2]
```diff
@@ -174,6 +174,7 @@ class SyncMediaWorker(
     companion object {
         private const val HKEY_KEY = "hkey"
         private const val ENDPOINT_KEY = "endpoint"
+        const val NOTIFICATION_UPDATE_RATE_MS = 500L
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncMediaWorker.kt:177]: nit: delay should accept `500.milliseconds`
