### PR TITLE
Fixes #4759 'Custom study: Don't show "increase new card limit" when no new cards'

### LINKED ISSUE #4759: Custom study: Don't show "increase new card limit" when no new cards
###### Research
[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. On the main screen, long-press a deck and select "User-defined learning"

###### Expected Result

If there are 0 "new cards", the menu item "Increase limit for new cards" is not shown.

###### Actual Result

The menu item "Increase limit for new cards" is shown even when it doesn't make sense.

### PR DESCRIPTION
**Pull request by 4D17Y4**
## Purpose / Description
Removed increase new card limit when no new cards

## Fixes
Fixes #4759

## Approach
Added a condition check to check if there are no new cards.

## How Has This Been Tested?

Tested on Nokia 6.1+ (physical) , android 10 stock version.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java [hunk 1]
```diff
@@ -345,6 +345,11 @@ private void customStudyFromTags(List<String> selectedTags, int option) {
         switch (dialogId) {
             case CONTEXT_MENU_STANDARD:
                 // Standard context menu
+                if (col.getSched().newCount()==0) {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java:348]: This would be more maintainable if you generate the list, and then remove the element based on a condition, this means both lists don't need to be kept in sync by a developer

Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java:348]:
```suggestion
                if (col.getSched().newCount() == 0) {
```

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
Thanks!!! 

(optional): A unit test here would be great

Could you change the pull request title to something that makes sense without context of the change

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java (hunk 1 above)
Comment (4D17Y4) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java:348]: Sure I'll switch.
I am planning on making a new temporary array and copying the content after checking for the condition.
Any changes ?

Comment (4D17Y4) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java:348]: I'll fix it,
thanks for review.

**Comment by 4D17Y4** [comment]
@david-allison-1  should I be worried about the failing checks, though I've looked into it and they doesn't seem relevant here.

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java (hunk 1 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java:348]: Use an `ArrayList` rather than an array, as it makes removal easier. Convert to an array when you return it.

**Comment by david-allison-1** [comment]
> @david-allison-1 should I be worried about the failing checks, though I've looked into it and they doesn't seem relevant here.

Yeah, you're fine, we moved our CI from Travis to GitHub which has made the tests much more flaky. We're snowed under with all the new contributors right now, but we will be getting CI back up to 100% soon.

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java (hunk 1 above)
Comment (4D17Y4) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java]: Done, Thanks

**Comment by 4D17Y4** [comment]
Hey @david-allison-1 ,
In the Regression test, 
Should I be comparing the list in dialog or just validating the count is sufficient ?

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java [hunk 2]
```diff
@@ -342,30 +342,60 @@ private void customStudyFromTags(List<String> selectedTags, int option) {
...
+                add(MORE_OPTIONS);
+            }
+        };
+
         switch (dialogId) {
             case CONTEXT_MENU_STANDARD:
                 // Standard context menu
-                return new int[] {CUSTOM_STUDY_NEW, CUSTOM_STUDY_REV, CUSTOM_STUDY_FORGOT, CUSTOM_STUDY_AHEAD,
-                        CUSTOM_STUDY_RANDOM, CUSTOM_STUDY_PREVIEW, CUSTOM_STUDY_TAGS};
+                dialogOptions.remove(Integer.valueOf(DECK_OPTIONS));
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java:363]: Sorry to be annoying, I meant an `ArrayList` in this case statement, I think we lose maintainability by having a list for the entire function

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java [hunk 3]
```diff
@@ -342,30 +342,60 @@ private void customStudyFromTags(List<String> selectedTags, int option) {
...
+                dialogOptions.remove(Integer.valueOf(CUSTOM_STUDY_NEW));
+                dialogOptions.remove(Integer.valueOf(CUSTOM_STUDY_REV));
+                dialogOptions.remove(Integer.valueOf(MORE_OPTIONS));
+                break;
             default:
+                dialogOptions.clear();
                 break;
         }
-        return null;
+        int [] list = new int[dialogOptions.size()];
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java:393]: We have a function: `integerListToArray`

**Review by david-allison-1 — COMMENTED** [review]
RE: Your question -  ideally verifying that the item isn't present

For a mock, whatever is easiest to read and will return a count of 0.

Aim for less coupling, but it doesn't need to be perfect

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java (hunk 2 above)
Comment (4D17Y4) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java:363]: This solves it, I was thinking as I changed list for whole function I should check for all cases.
I'll make the requested changes.
Thanks.

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java (hunk 3 above)
Comment (4D17Y4) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java]: done.

File: AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java [hunk 4]
```diff
@@ -69,6 +70,22 @@ public void learnAheadCardsRegressionTest() {
...
+    public void increaseNewCardLimitRegressionTest(){
+        // #8338 - Regression Test
+        CustomStudyDialog standard = CustomStudyDialog.newInstance(CustomStudyDialog.CONTEXT_MENU_STANDARD,2);
+
+        FragmentScenario<CustomStudyDialogForTesting> scenarioStandard = getDialogScenario(standard);
+
+        scenarioStandard.onFragment(f ->{
+            MaterialDialog dialog = (MaterialDialog)f.getDialog();
+            assertThat(dialog,notNullValue());
+            assertThat(dialog.getItems(), Matchers.not(Matchers.hasItem("Modify today’s new card limit")));
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java:85]: Use the string for `R.string.custom_study_increase_new_limit`, and ensure that the test is running under English - therefore translation updates won't cause problems with the test

```java
    @Config(qualifiers = "en")
```

**Review by david-allison-1 — COMMENTED** [review]
Really clean, one note in the test and good to go. Thanks so much!!

**Comment by 4D17Y4** [comment]
Done ;)

**Review by david-allison-1 — APPROVED** [review]
Great! Thanks for the quick fixes, code's really clean, thank you!

**Comment by david-allison-1** [comment]
```

com.ichi2.anki.dialogs.CustomStudyDialogTest > increaseNewCardLimitRegressionTest FAILED
    java.lang.NullPointerException
        at com.ichi2.libanki.Decks.select(Decks.java:1081)
        at com.ichi2.anki.dialogs.CustomStudyDialog.onCreateDialog(CustomStudyDialog.java:114)
        at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:648)
        at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:562)
        at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1654)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:493)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1971)
        at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:305)
        at androidx.fragment.app.testing.FragmentScenario$Companion$internalLaunch$2.perform(FragmentScenario.kt:618)
        at androidx.fragment.app.testing.FragmentScenario$Companion$internalLaunch$2.perform(FragmentScenario.kt:401)
        at androidx.test.core.app.ActivityScenario.lambda$onActivity$2$ActivityScenario(ActivityScenario.java:660)
        at androidx.test.core.app.ActivityScenario$$Lambda$4.run(Unknown Source)
        at androidx.test.core.app.ActivityScenario.onActivity(ActivityScenario.java:670)
        at androidx.fragment.app.testing.FragmentScenario$Companion.internalLaunch$fragment_testing_release(FragmentScenario.kt:592)
        at androidx.fragment.app.testing.FragmentScenario$Companion.launch(FragmentScenario.kt:477)
        at androidx.fragment.app.testing.FragmentScenario$Companion.launch$default(FragmentScenario.kt:476)
        at androidx.fragment.app.testing.FragmentScenario.launch(FragmentScenario.kt)
        at com.ichi2.anki.dialogs.CustomStudyDialogTest.getDialogScenario(CustomStudyDialogTest.java:96)
        at com.ichi2.anki.dialogs.CustomStudyDialogTest.increaseNewCardLimitRegressionTest(CustomStudyDialogTest.java:8
```

**Comment by 4D17Y4** [comment]
I'll fix it in some time.

**Comment by david-allison-1** [comment]
> I'll fix it in some time.

No rush, you should also be able to check the tests on your local machine, or enable GitHub actions on your fork

**Comment by 4D17Y4** [comment]
Hey @david-allison-1 ,
I might need your help here im getting the same error on running regression test as in #8064 on my local machine, tried so hard to figure out why im getting this error but no success. Due to the same reason I'm unable to debug this regression test ;(

**Comment by david-allison-1** [comment]
A flaky test is something that we need to rerun, Apologies, we moved to GitHub actions recently, and the test runners are much more problematic than our old ones. We do have a PR in which should fix these, but it'll take time to get over the finish line

**Comment by david-allison-1** [comment]
Okay, this is a failure. The first stage is to run the test under the debugger and set breakpoints to see where the problem lies.

**Comment by david-allison-1** [comment]
I've had a look into this.

Getting this test to work will require rearchitecting the class to use `FragmentFactory`, after this, we can use `FragmentScenario` without needing to override `getAnkiActivity()`

Could you add `@Ignore("#8406")` to the test, and let's get this in

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java [hunk 5]
```diff
@@ -69,14 +69,20 @@
...
     @VisibleForTesting
     static final int CUSTOM_STUDY_AHEAD = 103;
-    private static final int CUSTOM_STUDY_RANDOM = 104;
-    private static final int CUSTOM_STUDY_PREVIEW = 105;
-    private static final int CUSTOM_STUDY_TAGS = 106;
+    @VisibleForTesting
+    static final int CUSTOM_STUDY_RANDOM = 104;
+    @VisibleForTesting
+    static final int CUSTOM_STUDY_PREVIEW = 105;
+    @VisibleForTesting
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java:84]: And revert these `@VisibleForTesting` changes - shouldn't be necessary.

Comment (4D17Y4) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java]: Done

**Comment by 4D17Y4** [comment]
Thanks @david-allison-1 ; )

**Review by david-allison-1 — APPROVED** [review]
Looks good to me, thanks! Maintainers: squash & merge

File: AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java [hunk 6]
```diff
@@ -71,6 +75,26 @@ public void learnAheadCardsRegressionTest() {
     }
 
 
+    @Test
+    @Ignore("#8406")
+    @Config(qualifiers = "en")
+    public void increaseNewCardLimitRegressionTest(){
+        // #8338 - Regression Test
+        CustomStudyDialog standard = CustomStudyDialog.newInstance(CustomStudyDialog.CONTEXT_MENU_STANDARD,1);
```
Comment (mikehardy) [inline AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java:83]:
```suggestion
        CustomStudyDialog standard = CustomStudyDialog.newInstance(CustomStudyDialog.CONTEXT_MENU_STANDARD, 1);
```

File: AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java [hunk 7]
```diff
@@ -71,6 +75,26 @@ public void learnAheadCardsRegressionTest() {
...
+
+        FragmentScenario<CustomStudyDialogForTesting> scenarioStandard = getDialogScenario(standard);
+
+        scenarioStandard.moveToState(Lifecycle.State.STARTED);
+
+        scenarioStandard.onFragment(f ->{
```
Comment (mikehardy) [inline AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java:89]:
```suggestion
        scenarioStandard.onFragment(f -> {
```

File: AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java [hunk 8]
```diff
@@ -71,6 +75,26 @@ public void learnAheadCardsRegressionTest() {
...
+            MaterialDialog dialog = (MaterialDialog)f.getDialog();
+            assertThat(dialog,notNullValue());
+            assertThat(dialog.getItems(), Matchers.not(Matchers.hasItem(getResourceString(R.string.custom_study_increase_new_limit))));
+        });
+
```
Comment (mikehardy) [inline AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java:94]:
```suggestion
```

**Review by mikehardy — CHANGES_REQUESTED** [review]
LGTM - I read the note about the fragment testing difficulties, it's tracked nicely

My comments are all nitpicks then - just spacing. I'll commit them in a batch then squash+merge

**Review by mikehardy — APPROVED** [review]

**Comment by mikehardy** [comment]
Hi there!

Just a friendly notice (one per person for PRs merged in March, regardless of PR quantity) that we try to process OpenCollective payments monthly - it's time for March 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

Thanks!
