### PR TITLE
fix: lateinit property of questions and answers not initialised

### LINKED ISSUE #16302: [BUG] 2.18 CardMediaPlayer: lateinit property answers has not been initialized
https://ankidroid.org/acra/app/1/bug/164437/report/0fef5282-563b-4de5-9d34-dc3ff1d7dd49

```
kotlin.UninitializedPropertyAccessException: lateinit property answers has not been initialized
	at com.ichi2.anki.cardviewer.CardMediaPlayer.playAllSoundsInternal(SourceFile:134)
	at com.ichi2.anki.cardviewer.CardMediaPlayer.access$playAllSoundsInternal(SourceFile:1)
	at com.ichi2.anki.cardviewer.CardMediaPlayer$playAllSoundsForSide$2.invokeSuspend(SourceFile:47)
	at com.ichi2.anki.cardviewer.CardMediaPlayer$playAllSoundsForSide$2.invoke(SourceFile:2)
	at com.ichi2.anki.cardviewer.CardMediaPlayer$playAllSoundsForSide$2.invoke(SourceFile:1)
	at com.ichi2.anki.cardviewer.CardMediaPlayer$playSoundsJob$2.invokeSuspend(SourceFile:65)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:129)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(SourceFile:4)
	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(SourceFile:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(SourceFile:15)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(SourceFile:29)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:1)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@67d0427, Dispatchers.IO]
```

### PR DESCRIPTION
**Pull request by david-allison**
`isAfterRecreation = true` -> sounds were not loaded

This was triggered if "Don't keep activities" was set

## Fixes
* Fixes #16302
* Fixes #16305

## Approach
Load sounds if `isAfterRecreation`
## How Has This Been Tested?
Manually on my S21:

* Enable don't keep activities
* reproduce the crash with an audio-only card
  * Either:
    * Being on the front and flipping the card
    * Being on the back
  * Then close + open the app  
 
Fix the code by adding `loadAndPlaySounds`

Crashes were no longer reproducible

## Learning (optional, can help others)
S21 seems to be very buggy with gesture nav + Don't keep activities, was difficult to get to the app picker

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]

**Review by lukstbit — APPROVED** [review]
Ok.

As an observation you can't add a sound in the note editor with _Don't keep activities_(probably other multimedia as well).

File: AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt [hunk 1]
```diff
@@ -72,9 +73,13 @@ class PreviewerViewModel(previewerIdsFile: PreviewerIdsFile, firstIndex: Int, ca
     ********************************************************************************************* */
 
     /** Call this after the webView has finished loading the page */
+    @NeedsTest("16302 - a sound-only card on the back/flipped with 'don't kee activities'")
     override fun onPageFinished(isAfterRecreation: Boolean) {
         if (isAfterRecreation) {
-            launchCatchingIO { showCard(showAnswerOnReload) }
+            launchCatchingIO {
+                showCard(showAnswerOnReload)
+                loadAndPlaySounds()
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt:81]: I can't test this now, but I believe that this now stops and restarts audio in configuration changes (i.e. night mode changes

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt:81]: It does

**Comment by david-allison** [comment]
I want to go through this before merging - saw an error on my phone which may be related

File: AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt (hunk 1 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt]: I was interested in testing this myself but was unsure what the exact card contents are that trigger this.
Do you need to have an autoplay? Or just a sound?

I see you commented below that you want a pause so I'll desist for the moment, but I'm curious on the reproduction

**Comment by mikehardy** [comment]
tagging with author reply just to have a hold on it as requested (so I don't forget, really...)

**Comment by david-allison** [comment]
Good to go

File: AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt (hunk 1 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt]: Any audio on the front of a card

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt]: This thread is resolved, but I'll leave it unmarked due to other discussions

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt]: > Any audio on the front of a card

ah okay, mine was on back

**Review by mikehardy — APPROVED** [review]
I still could not recreate before this PR 🤔 
I can't see how this patch would do harm though, and my read of it is that it should fix things
