### PR TITLE
Fix: DeckPicker - opExecuted failed

### LINKED ISSUE #19689: [BUG] DeckPicker - opExecuted failed - You can't request ViewModel before onCreate call.
2.23beta4

https://ankidroid.org/acra/app/1/bug/363616/report/668fe165-625a-4051-a7ca-dd2877837ba1

```
java.lang.IllegalStateException: Your activity is not yet attached to the Application instance. You can't request ViewModel before onCreate call.
	at androidx.activity.ComponentActivity.getViewModelStore(ComponentActivity.kt:535)
	at com.ichi2.anki.DeckPicker$special$$inlined$viewModels$default$2.invoke(DeckPicker.java:78)
	at com.ichi2.anki.DeckPicker$special$$inlined$viewModels$default$2.invoke(DeckPicker.java:78)
	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:49)
	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:35)
	at com.ichi2.anki.DeckPicker.getViewModel(DeckPicker.kt:253)
	at com.ichi2.anki.DeckPicker.opExecuted(DeckPicker.kt:2433)
	at com.ichi2.anki.observability.ChangeManager.notifySubscribers(ChangeManager.kt:87)
	at com.ichi2.anki.observability.ChangeManager.notifySubscribers$AnkiDroid_fullRelease(ChangeManager.kt:119)
	at com.ichi2.anki.DayRolloverHandler.handleDayRollover(DayRolloverHandler.kt:115)
	at com.ichi2.anki.DayRolloverHandler.handleTimeChange(DayRolloverHandler.kt:106)
	at com.ichi2.anki.DayRolloverHandler.access$handleTimeChange(DayRolloverHandler.kt:54)
	at com.ichi2.anki.DayRolloverHandler$handleTimeChange$1.invokeSuspend(DayRolloverHandler.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.java:113)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
```

### PR DESCRIPTION
**Pull request by criticalAY**
## Purpose / Description
Fixes a startup crash caused by a race condition where DeckPicker received ChangeManager events before the Activity was attached to the Application.

This occurred because the subscription happened in the init block (or immediately upon instantiation), and background events triggered opExecuted on a background thread. This caused an attempt to access the ViewModel before onCreate completed, resulting in (posted by David and is on ACRA)
`java.lang.IllegalStateException: Your activity is not yet attached to the Application instance.`

## Fixes
* Fixes #19689

## Approach
Lifecycle-Aware Subscriptions: Introduced subscribeToChangeManager extension functions for LifecycleOwner

## How Has This Been Tested?
I added a new Robolectric regression test to verify the fix and prevent regression.

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/observability/ChangeManager.kt [hunk 1]
```diff
@@ -67,6 +69,17 @@ object ChangeManager {
         subscribers.add(WeakReference(subscriber))
     }
 
+    fun unsubscribe(subscriber: Subscriber) {
+        val iterator = subscribers.iterator()
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/observability/ChangeManager.kt]: Does this work?

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/observability/ChangeManager.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/observability/ChangeManager.kt b/AnkiDroid/src/main/java/com/ichi2/anki/observability/ChangeManager.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/observability/ChangeManager.kt	(revision 0c8ad38a5d7a97b34ff235d84139e340e662aeae)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/observability/ChangeManager.kt	(date 1764980548766)
@@ -70,14 +70,7 @@
     }
 
     fun unsubscribe(subscriber: Subscriber) {
-        val iterator = subscribers.iterator()
-        while (iterator.hasNext()) {
-            val ref = iterator.next()
-            val underlying = ref.get()
-            if (underlying == null || underlying === subscriber) {
-                subscribers.remove(ref)
-            }
-        }
+        subscribers.removeWeakReferences { it == null || it === subscriber }
     }
 
     private fun notifySubscribers(
@@ -175,3 +168,7 @@
         },
     )
 }
+
+private fun <T> MutableList<WeakReference<T>>.removeWeakReferences(block: (T?) -> Boolean) {
+    this.removeAll { block(it.get()) }
+}
\ No newline at end of file
```

File: AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerLifecycleTest.kt [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+
+    @Test
+    fun ensureSubscriptionWaitsForOnCreate() {
+        val controller = Robolectric.buildActivity(DeckPicker::class.java)
+
+        Assert.assertEquals(0, ChangeManager.subscriberCount)
+
+        controller.create()
+
+        Assert.assertTrue(ChangeManager.subscriberCount > 0)
```
Comment (david-allison) [inline AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerLifecycleTest.kt]: Hamcrest has a `greaterThan`

File: AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerLifecycleTest.kt [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+    }
+
+    @After
+    fun tearDown() {
+        ChangeManager.clearSubscribers()
+    }
+
+    @Test
+    fun ensureSubscriptionWaitsForOnCreate() {
+        val controller = Robolectric.buildActivity(DeckPicker::class.java)
```
Comment (david-allison) [inline AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerLifecycleTest.kt]: We should see if we can add a regression test alongside this test:

* notify the DeckPicker of an event (`studyQueues` changed) before `onCreate`
* it should raise a crash report before this change, and pass after

**Review by david-allison — CHANGES_REQUESTED** [review]
Your commit messages are truncated.

I requested a test, 

If this isn't done, reference in the commit message that the event accessing the `ViewModel` before `onCreate` triggered a failure

Code looks good, cheers!

File: AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerLifecycleTest.kt [hunk 4]
```diff
@@ -0,0 +1,72 @@
...
+    }
+
+    @After
+    fun tearDown() {
+        ChangeManager.clearSubscribers()
+    }
+
+    @Test
+    fun ensureSubscriptionWaitsForOnCreate() {
+        Mockito.mockStatic(CrashReportService::class.java).use { mockedService ->
```
Comment (lukstbit) [inline AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerLifecycleTest.kt]: This doesn't test anything, _buildActivity()_ goes through the state and _onCreate()_ will be called(and make the ViewModel available) long before the call to _notifySubscribers()_.

A simple test that fails for the crash in the linked issue is:

```kotlin
@Test
fun `receiving opExecuted call doesn't crash if ViewModel is not yet initialized`() {
    // just create the activity, no lifecycle methods are invoked yet and ViewModel is not available
    DeckPicker()
    // Calling notifySubscribers() now would crash as the ViewModel was not initialized:
    //
    // java.lang.IllegalStateException: Your activity is not yet attached to the Application
    // instance. You can't request ViewModel before onCreate call.
    ChangeManager.notifySubscribers(opChanges { studyQueues = true }, null)
}
```

Also please put this test in DeckPickerTest, there's no need to create a file just for this.

File: AnkiDroid/src/main/java/com/ichi2/anki/observability/ChangeManager.kt [hunk 5]
```diff
@@ -143,3 +149,26 @@ object ChangeManager {
             studyQueues = true
         }
 }
+
+/**
+ * Automatically subscribes to ChangeManager in onCreate and unsubscribes in onDestroy.
+ * This ensures no events are received when the view is dead.
+ */
+fun LifecycleOwner.subscribeToChangeManager(subscriber: ChangeManager.Subscriber) {
```
Comment (lukstbit) [inline AnkiDroid/src/main/java/com/ichi2/anki/observability/ChangeManager.kt]: All methods in the android sdk that take a `LifecycleOwner` or `Lifecycle.State` take it as the first parameter of the method, not as a receiver. This method should also be placed in ChangeManager so it's more discoverable:

```kotlin
/**
 * Register a subscriber to be notified of changes.The subscriber will be be active when the
 * state of the [LifecycleOwner]'s lifecycle is at least [Lifecycle.State.CREATED] and until the
 * [LifecycleOwner] is destroyed.
 */
fun subscribe(owner: LifecycleOwner, subscriber: Subscriber) {
    owner.lifecycle.addObserver(
        object : DefaultLifecycleObserver {
            override fun onCreate(owner: LifecycleOwner) {
                subscribe(subscriber)
            }

            override fun onDestroy(owner: LifecycleOwner) {
                unsubscribe(subscriber)
                owner.lifecycle.removeObserver(this)
            }
        },
    )
}
```

Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/observability/ChangeManager.kt]: In onCreate, subscribeToChangeManager(this) reads like a sentence describing the capability of the Activity, whereas ChangeManager.subscribe(this, this) feels a bit more verbose and redundant. I’d prefer to keep the extension to reduce boilerplate in our Activities, unless you feel strongly that discoverability on the ChangeManager object is more important.

File: AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt [hunk 6]
```diff
@@ -88,6 +91,16 @@ class DeckPickerTest : RobolectricTest() {
         setIntroductionSlidesShown(true)
     }
 
+    @Test
+    fun `receiving opExecuted call doesn't crash if ViewModel is not yet initialized`() {
+        DeckPicker()
```
Comment (lukstbit) [inline AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt:98]: Add a comment here along the lines: _Manually instantiated so it's just initialized but doesn't go through its' lifecycle callbacks_. While reading this code it's not immediately obvious why would we directly instantiate an activity.

File: AnkiDroid/src/main/java/com/ichi2/anki/observability/ChangeManager.kt (hunk 5 above)
Comment (lukstbit) [reply AnkiDroid/src/main/java/com/ichi2/anki/observability/ChangeManager.kt]: I do feel that having the method in ChangeManager is better, I value the importance of the method being easily discoverable and under the same namespace. The call site _(this, this)_ is not great but we can always(and probably should) use named parameter: _(owner: this, subscriber: this)_.

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/observability/ChangeManager.kt]: How about expanding 'subscribe':

```kotlin
fun subscribe(subscriber: Subscriber, owner: LifecycleOwner? = subscriber as? LifecycleOwner) {
```

Which takes away the mental overhead of needing to remember use a separate method on a lifecycle-aware component

Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/observability/ChangeManager.kt]: > I do feel that having the method in ChangeManager is better, I value the importance of the method being easily discoverable and under the same namespace. The call site (this, this) is not great but we can always(and probably should) use named parameter: (owner: this, subscriber: this).

I would prefer the modern approach but since I had the solution how you and David are proposing (Me and David discussed it before this PR) earlier but later switched to this one I dont mind doing it your way, I am okay with it as the solution will still do that same things so works for me cool!

File: AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt [hunk 7]
```diff
@@ -88,6 +91,19 @@ class DeckPickerTest : RobolectricTest() {
...
+    fun `receiving opExecuted call doesn't crash if ViewModel is not yet initialized`() {
+        // Instantiate DeckPicker directly to simulate a state where the object exists,
+        // but Android lifecycle callback (onCreate) have not yet executed.
+        DeckPicker()
+
+        try {
+            ChangeManager.notifySubscribers(opChanges { studyQueues = true }, null)
+        } catch (e: IllegalStateException) {
+            Assert.fail("Crash detected! ${e.message}")
+        }
```
Comment (david-allison) [inline AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt]:
```suggestion
        assertDoesNotThrow { ChangeManager.notifySubscribers(opChanges { studyQueues = true }, null) }
```

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 8]
```diff
@@ -432,7 +432,7 @@ open class DeckPicker :
     var createMenuJob: Job? = null
 
     init {
-        ChangeManager.subscribe(this)
+        ChangeManager.subscribe(this, this)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt]:
```suggestion
        ChangeManager.subscribe(this)
```

**Review by david-allison — CHANGES_REQUESTED** [review]
LGTM, with a few nitpicks

* Please edit the commit message, 
    * There should be a blank line between the title and the body, otherwise it's treated as one large title
    * Please Add `Fixes 19689`
    * Optional: `Co-authored-by: David Allison <62114487+david-allison@users.noreply.github.com>`

**Review by david-allison — APPROVED** [review]
Thanks so much!

**Review by mikehardy — COMMENTED** [review]
nice - scrutinized it pretty closely. I'm going to branch off the beta5 release commit and this will be the first official cherry-pick for release-2.23 branch, making it in for 2.23.0
