### PR TITLE
BugFix: Handle crash obtaining hitTest

### LINKED ISSUE #7262: Crash: WebView - getHitTestResult
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/61344b7e-dbeb-47da-91d0-0e3cd5c16e95

```
java.lang.NullPointerException: Attempt to read from field 'int zA0.a' on a null object reference
at com.android.webview.chromium.WebViewChromium.getHitTestResult(chromium-Monochrome.aab-stable-418310173:12)
at android.webkit.WebView.getHitTestResult(WebView.java:1190)
at com.ichi2.anki.AbstractFlashcardViewer$LinkDetectingGestureDetector.b(AbstractFlashcardViewer.java:4)
at com.ichi2.anki.l.onTouch(Unknown Source:2)
at android.view.View.dispatchTouchEvent(View.java:12510)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3024)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2705)
at com.ichi2.anki.AbstractFlashcardViewer$LinkDetectingGestureDetector.a(AbstractFlashcardViewer.java:1)
at com.ichi2.anki.k.consume(Unknown Source:6)
at com.ichi2.anki.AbstractFlashcardViewer.n(AbstractFlashcardViewer.java:1)
at com.ichi2.anki.p.apply(Unknown Source:4)
at com.ichi2.anki.AbstractFlashcardViewer.processCardFunction(AbstractFlashcardViewer.java:3)
at com.ichi2.anki.AbstractFlashcardViewer.processCardAction(AbstractFlashcardViewer.java:1)
at com.ichi2.anki.AbstractFlashcardViewer$LinkDetectingGestureDetector.executeTouchCommand(AbstractFlashcardViewer.java:9)
at com.ichi2.anki.AbstractFlashcardViewer$MyGestureDetector.onSingleTapConfirmed(AbstractFlashcardViewer.java:2)
at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:300)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6718)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

Needs a try..catch

### PR DESCRIPTION
**Pull request by david-allison**
`NullPointerException` from here

Fixes #7262

Untested

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 1]
```diff
@@ -2982,8 +2982,14 @@ public void onWebViewCreated(@NonNull WebView webView) {
...
 
-                WebView card = (WebView) webViewAsView;
-                HitTestResult result = card.getHitTestResult();
+                WebView cardWebView = (WebView) webViewAsView;
+                HitTestResult result;
+                try {
+                    result = cardWebView.getHitTestResult();
+                } catch (Exception e) {
+                    Timber.w(e, "Cannot obtain HitTest result");
+                    return true;
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:2991]: return true means handle the touch - I feel this is the correct move.

**Review by mikehardy — APPROVED** [review]
LGTM
