### PR TITLE
fix: previewer crash when cast to CardTemplatePreviewer

### LINKED ISSUE #14928: [Bug] Card preview crash
###### Reproduction Steps

1. Enter `Card browser`
2. Click the icon in the upper right corner
3. Click `Preview`

###### Expected Result

Normal display

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.17alpha9 (ee2a3ba67baeb24f8c5e42c55fadd7d980ba3fe4)

Android Version = 12 (SDK 31)

ProductFlavor = full

Manufacturer = Xiaomi

Model = M2006J10C

Hardware = mt6889

Webview User Agent = Mozilla/5.0 (Linux; Android 12; M2006J10C Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.88 Mobile Safari/537.36

ACRA UUID = 756393f7-4e9a-4237-bf56-cce7e9108797

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by BrayanDSO**
## Fixes
* Fixes #14928

## Approach
handle class inheritors better

## How Has This Been Tested?

Open the previewer and don't crash

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
I like it - roots the problem out in a more general way, thanks

File: AnkiDroid/src/main/java/com/ichi2/anki/ReviewerServer.kt [hunk 1]
```diff
@@ -16,21 +16,16 @@
...
 
-class ReviewerServer(activity: FragmentActivity, val mediaDir: String) : AnkiServer(activity) {
+class ReviewerServer(activity: AbstractFlashcardViewer, private val mediaDir: String) : AnkiServer(activity) {
     var reviewerHtml: String = ""
-    private val jsApi = if (activity is Reviewer) {
-        reviewer().javaScriptFunction()
-    } else {
-        cardTemplatePreviewer().javaScriptFunction()
-    }
+    private val jsApi = activity.javaScriptFunction()
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/ReviewerServer.kt:28]: @krmanik What was the intention here? Was this explicitly designed to avoid enabling the API on the `Previewer`?

**Review by david-allison — COMMENTED** [review]
One question

File: AnkiDroid/src/main/java/com/ichi2/anki/ReviewerServer.kt (hunk 1 above)
Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/anki/ReviewerServer.kt:28]: In terms of code, this doesn't change functionality besides not crashing, so this kind of stuff can be discussed later if we need to release a new alpha

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/ReviewerServer.kt:28]: I think that may have been the intention, but my question is...why wouldn't you want the API to work on the previewer? Shouldn't the API always work as long as the JS code is correct?

Agreed we can discuss on a new alpha though, this is a crash *every time someone uses the Previewer* which is a high priority

**Review by david-allison — APPROVED** [review]
Approving, with potential follow-up on whether this works in the Previewer

File: AnkiDroid/src/main/java/com/ichi2/anki/ReviewerServer.kt (hunk 1 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/ReviewerServer.kt:28]: I can imagine not wanting to rate the card in the previewer

Comment (krmanik) [reply AnkiDroid/src/main/java/com/ichi2/anki/ReviewerServer.kt:28]: > @krmanik What was the intention here? Was this explicitly designed to avoid enabling the API on the `Previewer`?

The intention was to prevent API that modify card content like mark card, flag card etc. So, in case of previewer default value returned, but now check is implemented in JS API so the fix in this PR can be done.

**Comment by david-allison** [comment]
I'm going to rebase this onto `main` to make CI green

**Comment by david-allison** [comment]
Merge queue merged this too early, it should be fine. Linking merge queue PR: https://github.com/ankidroid/Anki-Android/pull/14896
