### PR TITLE
fix(widgets): refresh after day cutoff

### LINKED ISSUE #14372: [BUG]: Widget doesn't always display card number
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

- I go through all of my cards on day 1, so when I close the app, I don't have a number indicated on the widget.
- When a day 2 starts, the widget appears, still without any indication of the cards I have left to do.
- I have to open the app once for the widget to update and display "35" cards left in "10" minutes.

### Expected behaviour

Before the last updates, I would have the number of cards for the day indicated on the widget every morning, even without opening the app.

### Actual behaviour

I need to open the app once to fetch the number of cards I need to study on a given day.

### Debug info

```text
AnkiDroid Version = 2.16.4 (67fd45a351c44c46c844aa35a402b98a2a487f68)

Android Version = 12

ProductFlavor = play

Manufacturer = vivo

Model = V2023

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; V2023 Build/SP1A.210812.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.114 Mobile Safari/537.36

ACRA UUID = f9196442-d0c2-4b24-99d1-bdd65070dcbf

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

This is the only regression I've noticed since the updates. Good job to the dev team! 

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison**
> [!NOTE]
> Assisted-by: Claude Opus 4.7 - initial implementation, was heavily refactored

## Purpose / Description
Before this change, widgets depended on `ACTION_TIME_TICK` OR `android:updatePeriodMillis`.

If the app was closed, `ACTION_TIME_TICK` did not fire.

`android:updatePeriodMillis` is sometimes blocked by OEMs, and AlarmManager, and it's not guaranteed to execute on the hour.

## Fixes
* Fixes #14372

## Approach
`AlarmManager.setWindow` reduces this discrepancy to 10 minutes (the reasonable minimum for setWindow), and is less likely to be blocked.

⚠️ It's fine for this to fire alongside other mechanisms, which work better when the app is open (`ACTION_TIME_TICK`)

## How Has This Been Tested?

```diff
 ---------------------------- PROCESS STARTED (10276) for package com.ichi2.anki.debug ----------------------------
17:10:00.462 WM-ForceStopRunnable     D  Performing cleanup operations.
17:10:00.474 Compatibil...geReporter  D  Compat change id reported: 160794467; UID 10213; state: ENABLED
17:10:00.475 WM-ForceStopRunnable     D  Application was force-stopped, rescheduling.
17:10:00.490 WM-PackageManagerHelper  D  Skipping component enablement for androidx.work.impl.background.systemalarm.RescheduleReceiver
17:10:00.511 ACRA                     I  ACRA is enabled for com.ichi2.anki.debug, initializing...
17:10:00.532 AnkiDroid                D  Startup - Application Start
17:10:00.533 AnkiDroidApp             I  Timber config: DEBUG
17:10:00.533 UsageAnalytics           I  initialize()
17:10:00.533 UsageAnalytics           D  App tracking id 'tid' = UA-125800786-1
17:10:00.540 WebViewFactory           I  Loading com.google.android.webview version 109.0.5414.123 (code 541412334)
17:10:00.542 ziparchive               W  Unable to open '/data/app/~~vXK58OHzI9vwltSMqHUJtQ==/com.google.android.trichromelibrary_541412334-CB-KlrByVXO4EHhZPnsnaw==/TrichromeLibrary.dm': No such file or directory
17:10:00.542 ziparchive               W  Unable to open '/data/app/~~vXK58OHzI9vwltSMqHUJtQ==/com.google.android.trichromelibrary_541412334-CB-KlrByVXO4EHhZPnsnaw==/TrichromeLibrary.dm': No such file or directory
17:10:00.542 chi2.anki.debug          W  Entry not found
17:10:00.542 nativeloader             D  Configuring classloader-namespace for other apk /data/app/~~vXK58OHzI9vwltSMqHUJtQ==/com.google.android.trichromelibrary_541412334-CB-KlrByVXO4EHhZPnsnaw==/TrichromeLibrary.apk. target_sdk_version=33, uses_libraries=ALL, library_path=/data/app/~~QQxb022gmUKTqMVRgLXkfw==/com.google.android.webview-5Hm-_eOq8T2dbUtiPOvEZw==/lib/arm64:/data/app/~~QQxb022gmUKTqMVRgLXkfw==/com.google.android.webview-5Hm-_eOq8T2dbUtiPOvEZw==/WebViewGoogle.apk!/lib/arm64-v8a:/data/app/~~vXK58OHzI9vwltSMqHUJtQ==/com.google.android.trichromelibrary_541412334-CB-KlrByVXO4EHhZPnsnaw==/TrichromeLibrary.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand
17:10:00.544 nativeloader             D  Configuring classloader-namespace for other apk /data/app/~~QQxb022gmUKTqMVRgLXkfw==/com.google.android.webview-5Hm-_eOq8T2dbUtiPOvEZw==/WebViewGoogle.apk. target_sdk_version=33, uses_libraries=, library_path=/data/app/~~QQxb022gmUKTqMVRgLXkfw==/com.google.android.webview-5Hm-_eOq8T2dbUtiPOvEZw==/lib/arm64:/data/app/~~QQxb022gmUKTqMVRgLXkfw==/com.google.android.webview-5Hm-_eOq8T2dbUtiPOvEZw==/WebViewGoogle.apk!/lib/arm64-v8a:/data/app/~~vXK58OHzI9vwltSMqHUJtQ==/com.google.android.trichromelibrary_541412334-CB-KlrByVXO4EHhZPnsnaw==/TrichromeLibrary.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand
17:10:00.550 chi2.anki.debug          W  Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (unsupported, reflection, allowed)
17:10:00.550 chi2.anki.debug          W  Accessing hidden method Landroid/os/Trace;->traceBegin(JLjava/lang/String;)V (unsupported, reflection, allowed)
17:10:00.550 chi2.anki.debug          W  Accessing hidden method Landroid/os/Trace;->traceEnd(J)V (unsupported, reflection, allowed)
17:10:00.550 chi2.anki.debug          W  Accessing hidden method Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V (unsupported, reflection, allowed)
17:10:00.550 chi2.anki.debug          W  Accessing hidden method Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (unsupported, reflection, allowed)
17:10:00.552 cr_WVCFactoryProvider    I  Loaded version=109.0.5414.123 minSdkVersion=29 isBundle=false multiprocess=true packageId=2
17:10:00.556 cr_VariationsUtils       I  Failed reading seed file "/data/user/0/com.ichi2.anki.debug/app_webview/variations_seed_new"
17:10:00.556 cr_VariationsUtils       I  Failed reading seed file "/data/user/0/com.ichi2.anki.debug/app_webview/variations_seed"
17:10:00.558 cr_LibraryLoader         I  Successfully loaded native library
17:10:00.558 cr_CachingUmaRecorder    I  Flushed 9 samples from 9 histograms.
17:10:00.576 Compatibil...geReporter  D  Compat change id reported: 183155436; UID 10213; state: ENABLED
17:10:00.638 chromium                 E  [ERROR:simple_version_upgrade.cc(152)] Failed to write a new fake index.
17:10:00.638 chromium                 E  [ERROR:simple_version_upgrade.cc(152)] Failed to write a new fake index.
17:10:00.642 Compatibil...geReporter  D  Compat change id reported: 214741472; UID 10213; state: ENABLED
17:10:00.650 GoogleAnalyticsImpl      I  Not participating in analytics sample (sample percentage vs random: 10 30)
17:10:00.650 UsageAnalytics           D  Chaining to uncaughtExceptionHandler (org.chromium.base.JavaExceptionReporter@8e2840d)
17:10:00.650 UsageAnalytics           I  setOptIn(): from false to false
17:10:00.650 GoogleAnalyticsImpl      I  Not participating in analytics sample (sample percentage vs random: 10 54)
17:10:00.650 UsageAnalytics           D  setOptIn() optIn / sAnalytics.config().enabled(): false/false
17:10:00.651 UsageAnalytics           I  setDryRun(): true, warning dryRun is experimental
17:10:00.651 ThrowableFilterService   I  initialize()
17:10:00.652 ThrowableFilterService   D  Chaining to uncaughtExceptionHandler (com.ichi2.anki.analytics.UsageAnalytics$$ExternalSyntheticLambda0@66e11d3)
17:10:00.653 AnkiDroidApp$onCreate    I  AnkiDroidApp: listing debug info
17:10:00.656 TestUtils                D  isRunningAsUnitTest: false
17:10:00.658 NotificationChannelsKt   I  Creating notification channel with id/name: General Notifications/AnkiDroid
17:10:00.660 NotificationChannelsKt   I  Creating notification channel with id/name: Synchronization/Synchronization
17:10:00.660 NotificationChannelsKt   I  Creating notification channel with id/name: Review Reminders/Review Reminders
17:10:00.674 AnkiDroidApp             I  AnkiDroidApp: Starting Services
17:10:00.674 DayRolloverHandler       D  listening for rollover events
17:10:00.679 WidgetAlarmKt            D  Restoring 1 alarms for DeckPickerWidget
17:10:00.679 WidgetAlarmKt            V  Creating a new recurring alarm PendingIntent for widget ID: AppWidgetId(id=3)
17:10:00.683 WidgetAlarmKt            D  Restoring 1 alarms for CardAnalysisWidget
17:10:00.684 WidgetAlarmKt            V  Creating a new recurring alarm PendingIntent for widget ID: AppWidgetId(id=4)
17:10:00.685 TtsVoices                D  launching job
17:10:00.686 TtsVoices$...LocalesJob  D  executing job
17:10:00.686 TtsVoices                V  begin TTS creation
+ 17:10:00.689 DayRollove...eBroadcast  I  DayRolloverAlarm received com.ichi2.widget.ACTION_ROLLOVER
17:10:00.691 AnkiDroidApp             D  ChangeSubscriber - opExecuted called with changes: # anki.collection.OpChanges@7d4149f5
                                         study_queues: true
17:10:00.692 DeckPicker...$Companion  D  Fetching appWidgetIds for provider: com.ichi2.widget.deckpicker.DeckPickerWidget
17:10:00.693 TextToSpeech             I  Sucessfully bound to com.google.android.tts
17:10:00.696 DeckPicker...$Companion  D  AppWidgetIds to update: AppWidgetId(id=3)
17:10:00.700 TextToSpeech             I  Connected to TTS engine
17:10:00.700 CardAnalys...$Companion  D  Fetching appWidgetIds for provider: com.ichi2.widget.cardanalysis.CardAnalysisWidget
17:10:00.701 CardAnalys...$Companion  D  AppWidgetIds to update: AppWidgetId(id=4)
17:10:00.702 TextToSpeech             I  Setting up the connection to TTS engine...
17:10:00.704 WidgetStatus             D  WidgetStatus.update(): updating
17:10:00.704 Compatibil...geReporter  D  Compat change id reported: 171228096; UID 10213; state: ENABLED
17:10:00.720 Backend                  D  Opening rust backend with lang=[en-US]
17:10:00.726 rsdroid                  I  rsdroid::logging: rsdroid logging enabled
17:10:00.736 TtsVoices$createTts      V  TTS creation success
17:10:00.762 Media                    V  dir /storage/emulated/0/Android/data/com.ichi2.anki.debug/files/AnkiDroid/collection.media
17:10:00.762 Collection               I  (Re)opening Database: Path(path=/storage/emulated/0/Android/data/com.ichi2.anki.debug/files/AnkiDroid/collection.anki2)
17:10:00.780 MetaDB                   V  Opening MetaDB
17:10:00.782 AnkiDroidApp$onCreate    I  AnkiDroid Version = 2.24.0beta1-debug (8749e374bab346d8bb3c7fb80301e7517b7b0b06)  
                                         Backend Version = 0.1.64-anki25.09.2 (25.09.2 3890e12c9e48c028c3f12aa58cb64bd9f8895e30)  
                                         Android Version = 13 (SDK 33)  
                                         ProductFlavor = play  
                                         Device Info = Google | google | emu64a | sdk_gphone64_arm64 | sdk_gphone64_arm64 | ranchu  
                                         WebView Info = [com.google.android.webview | 541412334]: Mozilla/5.0 (Linux; Android 13; sdk_gphone64_arm64 Build/TE1A.240213.009; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/109.0.5414.123 Mobile Safari/537.36  
                                         ACRA UUID = 7be52d95-7b34-457d-bfdd-5d7fb723cd35  
                                         FSRS = 5.1.0 (Enabled: false)  
                                         Crash Reports Enabled = false
17:10:00.785 MetaDB                   D  MetaDB:: Cached small widget status
17:10:00.785 WidgetStatus             I  triggering small widget UI update
17:10:00.785 AnkiDroidW...ateService  D  updating small widget UI
17:10:00.788 WidgetStat...tUpdateJob  V  launchUpdateJob completed
17:10:00.790 Notificati...$Companion  I  NotificationService: OnStartCommand
17:10:00.863 TtsVoices$...LocalesJob  D  65 TTS Voices available
17:10:00.864 TextToSpeech             I  Disconnected from TTS engine
```

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/widget/DayRolloverAlarm.kt [hunk 1]
```diff
@@ -0,0 +1,162 @@
...
+                0,
+                Intent(this, DayRolloverAlarm::class.java).apply { this.action = action },
+                PendingIntent.FLAG_UPDATE_CURRENT,
+                false,
+            )
+    }
+}
+
+/** @see AlarmManager.setWindow */
+private fun AlarmManager.setWindowSafe(
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/widget/DayRolloverAlarm.kt:129]: please add to the method doc that `safe` here means that it catches any exceptions

**Review by BrayanDSO — COMMENTED** [review]
How this overlaps with `DayRolloverHandler`? The classes look a bit similar

**Comment by david-allison** [comment]
`DayRolloverHandler` handles the case when the app is open and performs one check per minute.

This handles the case where the app is closed, scheduled in a window after the rollover occurs.

**Comment by BrayanDSO** [comment]
Should the classes be joined?

**Comment by david-allison** [comment]
No. `ACTION_TIME_TICK` can't be handled in the Manifest

**Review by BrayanDSO — APPROVED** [review]

**Comment by david-allison** [comment]
(updated docs)

File: AnkiDroid/src/main/java/com/ichi2/widget/DayRolloverAlarm.kt [hunk 2]
```diff
@@ -0,0 +1,164 @@
...
+                PendingIntent.FLAG_UPDATE_CURRENT,
+                false,
+            )
+    }
+}
+
+/**
+ * [AlarmManager.setWindow] implementation which catches exceptions.
+ */
+private fun AlarmManager.setWindowSafe(
```
Comment (ericli3690) [inline AnkiDroid/src/main/java/com/ichi2/widget/DayRolloverAlarm.kt:129]: This duplicates `catchAlarmManagerExceptions` in AlarmManagerService. Optimally, the logic for using AlarmManager should be centralized in the namesake AlarmManagerService.

File: AnkiDroid/src/main/java/com/ichi2/widget/DayRolloverAlarm.kt [hunk 3]
```diff
@@ -0,0 +1,164 @@
...
+
+/**
+ * Launches [block] on [Dispatchers.IO], reporting exceptions to ACRA.
+ *
+ * @param origin origin in the crash report
+ */
+private fun CoroutineScope.launchCatchingIoWithReport(
+    origin: String,
+    block: suspend () -> Unit,
+) {
```
Comment (ericli3690) [inline AnkiDroid/src/main/java/com/ichi2/widget/DayRolloverAlarm.kt:153]: Should this be moved to a more general utility file for working with coroutines? Perhaps `CoroutineHelpers.kt`?

**Review by ericli3690 — APPROVED** [review]
From my read-through this looks pretty great! Two nits :)

File: AnkiDroid/src/main/java/com/ichi2/widget/DayRolloverAlarm.kt (hunk 3 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/widget/DayRolloverAlarm.kt:153]: I'm happy with it being private until it's necessary, I suspect it's not going to be heavily used as we rarely use `applicationScope`

File: AnkiDroid/src/main/java/com/ichi2/widget/DayRolloverAlarm.kt (hunk 2 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/widget/DayRolloverAlarm.kt:129]: `catchAlarmManagerExceptions` shows a toast, I'd rather have a silent failure here. I've force pushed to catch a general exception setting the alarm

**Review by lukstbit — APPROVED** [review]
