### PR TITLE
Use backend for adding notes

### LINKED ISSUE #12608: [Bug] List of tags is not updated after adding a new tag
_Originally posted by @pavreh in https://github.com/ankidroid/Anki-Android/issues/12472#issuecomment-1272503486_

###### Reproduction Steps
1. Have a new instalation of AnkiDroid
2. Use the new backend
3. Add a note with a tag
4. Card Browser - Filter by tag

###### Expected Result
The tag can be selected.

###### Actual Result
The list of tags is empty. The tag appears in the list after Check database. 

###### Debug info
AnkiDroid Version = 2.16alpha86

Android Version = 12

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-A225F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/105.0.5195.136 Mobile Safari/537.36

ACRA UUID = 6cf7bbad-e282-47db-ad26-f6170967fa55

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by dae**
- Ensures tags are registered correctly
- Enables undoing of adds
- Also disables automatic backups when testing under robolectric, since it causes race conditions in the tests.

Closes #12608

### CODE REVIEW

File: AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.kt [hunk 1]
```diff
@@ -343,16 +344,24 @@ class ModelTest : RobolectricTest() {
         // a cloze model with no clozes is not empty
         note.setItem("Text", "nothing")
         assertEquals(1, col.addNote(note))
+        if (!BackendFactory.defaultLegacySchema) { note.id = 0 }
```
Comment (ShridharGoel) [inline AnkiDroid/src/test/java/com/ichi2/libanki/ModelTest.kt:347]: Consider creating a method inside `test_cloze` for this since this is duplicated multiple times.

**Review by BrayanDSO — APPROVED** [review]
LGTM

**Review by mikehardy — APPROVED** [review]
These look good to me, thanks Damien
