### PR TITLE
Fix Type Answer Diff for combining marks not showing up

### LINKED ISSUE #10665: [Bug] Type answer diff doesn't highlight incorrect combining marks
###### Reproduction Steps

1. Create a note expecting the text အချိန် to be typed.
2. During review, type the answer အခ်ျန် instead.

###### Expected Result
The difference is highlighted:
(Anki Desktop)
Anki_Desktop_အချိန်_အခ်ျန်

###### Actual Result
(AnkiDroid)
AnkiDroid_အချိန်_အခ်ျန်
(Judging from the clipped appearance of the circle in ချိ, I suspect that AnkiDroid is actually trying to highlight the same spans as Anki Desktop, but the text renderer (web view?) doesn't have the ability to style combining marks separately and instead merges them with the base character. Inserting zero-width non-joiners between spans that should be colored differently would prevent that.)

###### Debug info
AnkiDroid Version = 2.15.6

Android Version = 11

Manufacturer = Xiaomi

Model = Mi A1

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Mi A1 Build/RQ3A.211001.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.73 Mobile Safari/537.36

ACRA UUID = 34f0aeab-5cd6-40e3-89ea-689f57d2d46a

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by dorrin-sot**
## Purpose / Description
Fix bug

## Fixes
Fixes #10665 

## Approach
Added a Non-Breaking Space (NBSP) to start of all `aDiff.text`s whose unicode category start with "M" (e.g. non-Spacing marks). [This is exactly how ankidesktop handles this issue](https://github.com/ankitects/anki/blob/638286a3fcbcaaa3d95fbcb1bc2dd32c4b97a749/qt/aqt/reviewer.py#L715)

## How Has This Been Tested?
Emulator: 
image

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by dorrin-sot** [comment]
This is how anki desktop handles this:

https://github.com/ankitects/anki/blob/638286a3fcbcaaa3d95fbcb1bc2dd32c4b97a749/qt/aqt/reviewer.py#L715

**Review by david-allison — CHANGES_REQUESTED** [review]
Could you add a unit test 

AND

Run the unit test you added with this and `SCHEMA_VERSION` set to 16:

https://github.com/ankidroid/Anki-Android/blob/599c50575148ed8259cf8eda7fd858244f773a62/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java#L82-L90

We will be removing this functionality shortly, and I want to ensure we don't revert this when moving to the new method.

**Comment by dorrin-sot** [comment]
@david-allison 
Like this?

```diff
diff --git a/AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt b/AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
@@ -106,7 +106,7 @@
 
     // deck schema & syncing vars
     @JvmField
-    var SCHEMA_VERSION = 11
+    var SCHEMA_VERSION = 16
 
     /** The database schema version that we can downgrade from  */
     const val SCHEMA_DOWNGRADE_SUPPORTED_VERSION = 16
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java b/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
@@ -87,7 +87,7 @@
      *
      * Set this and {@link com.ichi2.libanki.Consts#SCHEMA_VERSION} to 16.
      */
-    public static boolean TESTING_USE_V16_BACKEND = false;
+    public static boolean TESTING_USE_V16_BACKEND = true;
 
     public static final String XML_CUSTOM_NAMESPACE = "http://arbitrary.app.namespace/com.ichi2.anki";
```

File: AnkiDroid/src/main/java/com/ichi2/utils/DiffEngine.kt [hunk 1]
```diff
@@ -70,9 +71,18 @@ open class DiffEngine {
             return "<span class=\"typeMissed\">" + escapeHtml(`in`) + "</span>"
         }
 
+        @JvmStatic
+        fun escapeLoneMarks(`in`: String): String {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/utils/DiffEngine.kt:75]: nit: rename the variable to avoid backticks

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/utils/DiffEngine.kt:75]: Could you add a doc-comment here, this would be difficult for the next user to understand

**Review by david-allison — APPROVED** [review]
Tentatively approving, with the expectation that a comment is added. Thanks so much!

Sorry about the delay - life's really busy right now

**Comment by david-allison** [comment]
Forgot to reply, that's perfect!

**Comment by mikehardy** [comment]
:disappointed: took a conflict while waiting - apologies, been quite busy myself playing catch-up after the GSoC barrage over here :-)

**Comment by dorrin-sot** [comment]
Cherry-picked the kt-migrate commits and added the test back as kotlin :)

**Review by mikehardy — APPROVED** [review]
LGTM! thanks for plowing through the conflicts and all that, honestly this is the busiest repository I work on including the react-native repository :sweat_smile: - you have to be persistent to get a change committed in here!
