### PR TITLE
fix(card-template-editor): change Ctrl+A to Ctrl+N

### LINKED ISSUE #18271: Select All in Template Editor Adds a Card Type
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Install FUTO keyboard: https://keyboard.futo.org/
2. Open Ankidroid.
3. From the menu, tap **Manage note types**.
4. While editing a template, use FUTO to "Select all". (Can be found if you long tap `a`).

### Expected behaviour

This somehow triggers "Add" (option for adding new card types). And I'm shown the warning pop-up that says "This will add x cards." What's more, this even happens in a cloze note type (adding a card type to this isn't normally possible).

### Debug info

```text
AnkiDroid Version = 2.21alpha15 (c9c58c3efb8adf535fdfb4a7237ae56a870fafef)
Backend Version = 0.1.52-anki25.02 (25.02 038d85b1d9e1896e93a3e4a26f600c79ddc33611)
Android Version = 11 (SDK 30)
ProductFlavor = full
Device Info = realme | realme | RMX2193 | RMX2193 | RMX2193 | mt6768
Webview User Agent = Mozilla/5.0 (Linux; Android 11; RMX2193 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/135.0.7049.100 Mobile Safari/537.36
ACRA UUID = cf265e01-9693-407f-984d-61ddf9698fac
FSRS = 2.0.3 (Enabled: true)
Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison**
Ctrl+A is standardised as 'select all'

Also stops the new command working on a cloze note

Added in 87e2a79b676c6309496317141340d6db52e82fa5

* Fixes #18271

## How Has This Been Tested?
⚠️  untested

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by ShridharGoel — APPROVED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt [hunk 1]
```diff
@@ -380,8 +380,8 @@ open class CardTemplateEditor :
                 Timber.i("Ctrl+I: Insert field from keypress")
                 currentFragment.showInsertFieldDialog()
             }
-            KeyEvent.KEYCODE_A -> {
-                Timber.i("Ctrl+A: Add card template from keypress")
+            KeyEvent.KEYCODE_PLUS -> {
+                Timber.i("Ctrl+Plus: Add card template from keypress")
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt:384]: Keyboards without a numpad normally don't have a `+` key. And most tablet and portable keyboards don't have a numpad, so they can't trigger the shortcut.

I suggest using `Ctrl+N` because that's the default shortcut for adding New stuff

**Review by BrayanDSO — APPROVED** [review]
