### PR TITLE
fix: startup with `getExternalFilesDir` corrupt on upgraded device

### LINKED ISSUE #19652: [BUG]: startup crash - getExternalFilesDir unexpectedly returned null. Media state: removed
2.23.0beta3

* `getExternalFilesDir` is null
* Collection path is set
* `CollectionHelper.initializeAnkiDroidDirectory` throws `StorageAccessException`

https://ankidroid.org/acra/app/1/bug/362178/report/968c2402-f20d-4984-b5b5-3781a4feb340

```
java.lang.RuntimeException: Unable to create application com.ichi2.anki.AnkiDroidApp: y9.b: getExternalFilesDir unexpectedly returned null. Media state: removed
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:8635)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2792)
	at android.os.Handler.dispatchMessage(Handler.java:115)
	at android.os.Looper.loopOnce(Looper.java:298)
	at android.os.Looper.loop(Looper.java:408)
	at android.app.ActivityThread.main(ActivityThread.java:9952)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:613)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1074)
Caused by: y9.b: getExternalFilesDir unexpectedly returned null. Media state: removed
	at com.ichi2.anki.exception.SystemStorageException$Companion.build(SystemStorageException.kt:52)
	at com.ichi2.anki.CollectionHelper.getAppSpecificExternalAnkiDroidDirectory(CollectionHelper.kt:231)
	at com.ichi2.anki.CollectionHelper.getDefaultAnkiDroidDirectory(CollectionHelper.kt:186)
	at com.ichi2.anki.AnkiDroidApp.onCreate(AnkiDroidApp.kt:218)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1401)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:8627)
	... 9 more
```

* Related: https://github.com/ankidroid/Anki-Android/issues/13207

### PR DESCRIPTION
**Pull request by david-allison**
> [!IMPORTANT]
> Please check logic carefully here
> To my understanding, this would not block any previously apps from starting up

## Purpose / Description

If the collection path is set, then our error handling threw an exception

**Situation:**
* `getExternalFilesDir` is null
* Collection path is set
* `CollectionHelper.initializeAnkiDroidDirectory` throws `StorageAccessException`

and the AnkiDroid Directory is in `getExternalFilesDir`

## Fixes
* Fixes #19652

## Approach
Fix by catching the exception and failing - the selected directory is not writable and storage permissions are likely corrupted

## How Has This Been Tested?
Unit tested

## Learning (optional, can help others)
I asked a few AIs about how to run code before `Application.onCreate` and they came up with a number of solutions which didn't work

`Files.createTempDirectory` isn't deleted when the tests end

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by mikehardy** [comment]
> I asked a few AIs about how to run code before Application.onCreate and they came up with a number of solutions which didn't work

A Provider in AndroidManifest with a well-chosen priority should be created and have `onCreate` called before the Application object gets control

firebase-android-sdk and react-native-firebase use this in order to set up a few things (Crashlytics crash reporting in react-native-firebase case, some other things at the lower firebase-android-sdk level) in order to do this. Seems to work 

https://github.com/invertase/react-native-firebase/blob/c4959a1dcba577a8f6f0f87c16e5d247169cd383/packages/crashlytics/android/src/main/AndroidManifest.xml#L9-L13

Although this appears to be a problem space android team addressed now with a library (still gets first startup but now you can control timing of 3rd party startups in Providers to mitigate app launch time impact) https://developer.android.com/topic/libraries/app-startup#startup-initialize

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt [hunk 1]
```diff
@@ -288,6 +266,51 @@ open class AnkiDroidApp :
         TtsVoicesFieldFilter.ensureApplied()
     }
 
+    /**
+     * Manually initializes the collection directory and `.nomedia` if
+     * [Permissions.hasLegacyStorageAccessPermission] is set
+     *
+     * On failure, sets [fatalInitializationError] to [torageError][FatalInitializationError.StorageError]
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt]:
```suggestion
     * On failure, sets [fatalInitializationError] to [storageError][FatalInitializationError.StorageError]
```

**Review by mikehardy — APPROVED** [review]
seems imminently reasonable, nice
just a typo in the kdoc

**Comment by david-allison** [comment]
> [!IMPORTANT]
> We are trialling an increase to Open Collective payments, invoices submitted more than **two weeks** after you receive this message may not be eligible for this increase.

Hi there @david-allison! This is the OpenCollective Notice for PRs **merged** from [2025-11-01 through 2025-11-30](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2025-11-01..2025-11-30+author%3Adavid-allison)

If you are interested in compensation for this work, the process with details is here: https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

We only post one comment per person per month to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for this month

Please understand that our monthly budget is never guaranteed to cover all claims - the cap on payments-per-person may be lower, but we try to make our process as fair and transparent as possible, we just need your understanding.

Thanks!
