### PR TITLE
NoteEditor: Fix newlines when previewing

### LINKED ISSUE #6460: CardTemplatePreviewer, Previewer, Reviewer handle newlines differently
###### Reproduction Steps

1. Open a note (with newlines I suspect) in NoteEditor
2. Hit the Preview button (opens CardTemplatePreviewer)
3. Compare with result of reviewing the same card

###### Expected Result

Newlines handled the same

###### Actual Result

Newlines handled differently?

This is reported from https://github.com/ankidroid/Anki-Android/pull/6063#issuecomment-643788306

Needs investigation

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### LINKED ISSUE #6834: Preview: Newlines not converted to line breaks
###### Reproduction Steps

1. Add Note
2. Enter "aa\naa" (where \n is a literal linebreak)
3. Preview

###### Expected Result

4. aa(newline)aa

###### Actual Result

4. aa aa

###### Debug info
2.12, also in latest alpha

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description
When saving a note, we convert a newline to `<br>`
We should do the same for Previewing

## Fixes
Fixes #6834
Fixes #6460

## Approach
Convert newline to `<br>`
## How Has This Been Tested?

Tested on my phone - now shows as it would in reviewer.

## Learning
Trivial fix, probably was a misstep to let it through as a defect, as defects are rarely looked back at.

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java [hunk 1]
```diff
@@ -1631,6 +1642,11 @@ private boolean updateField(FieldEditText field) {
     }
 
 
+    private String convertToHtmlNewline(String fieldData) {
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java:1645]:
```suggestion
    private String convertToHtmlNewline(@NonNull String fieldData) {
```

Maybe? (I think that's the right annotation - it's being called with no null check, so seems safer)

Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java:1645]: Got to be - would throw otherwise

**Comment by david-allison-1** [comment]
Requesting squash with only first commit message once CI passes

**Comment by mikehardy** [comment]
@david-allison-1 take the honors - I'll cut another alpha tomorrow evening my time (24hrs from now) plenty time for CI to masticate
