### PR TITLE
Ignore revlog.ease == 0 in stats, Fixes #8008

### LINKED ISSUE #8008: [Bug] Extra bar in statistics graph
###### Reproduction Steps

1. Open ANKIDroid
2. Go to Statistics
3. Go to 

###### Expected Result
The marked in the actual reesult shouldn't be there.

###### Actual Result
image

###### Debug info
AnkiDroid Version = 2.14.2

Android Version = 10

ACRA UUID = 6741e8ea-fe6c-4c57-9f40-47b4f7e61073

Scheduler = std2

Crash Reports Enabled = true

###### Research
- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))
- ALso, I tried to look through various options (month, year, deck life), restrating the phone and clearing the cache. Nothing seems to fix it.

### PR DESCRIPTION
**Pull request by mikehardy**
## Purpose / Description

Upstream has started logging revlog.ease = 0 on manual reschedules from the deck browser

We are not doing that (and still not doing that after this PR) but we do need to ignore them in stats or we get unsightly extra 0 columns and skewed today/overview stats

This adds an 'ease > 0' to all the where clauses, should fix it?

## Fixes
Fixes #8008

## Approach

Simple SQL where clause addition

## How Has This Been Tested?

Relatively untested but if we generate an alpha it appears that @dummifiedme has a collection that reproduces the issue.

## Learning (optional, can help others)

Pays to watch the ankitects/anki repo, which I have not been doing...

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java [hunk 1]
```diff
@@ -1154,6 +1160,10 @@ public boolean calculateAnswerButtons(AxisType type) {
         if (days > 0) {
             lims.add("id > " + ((mCol.getSched().getDayCutoff() - (days * SECONDS_PER_DAY)) * 1000));
         }
+
+        // Anki Desktop logs a '0' ease for manual reschedules, ignore them https://github.com/ankidroid/Anki-Android/issues/8008
+        lims.add("ease > 0");
+
         if (lims.size() > 0) {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java:1167]: minor: no longer necessary

File: AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java [hunk 2]
```diff
@@ -272,6 +275,9 @@ private String getRevlogFilter(AxisType timespan,boolean inverseTimeSpan){
             lims.add(lim);
         }
 
+        // Anki Desktop logs a '0' ease for manual reschedules, ignore them https://github.com/ankidroid/Anki-Android/issues/8008
+        lims.add("ease > 0");
+
         if (!lims.isEmpty()) {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java:281]: Ditto - always true

**Review by david-allison-1 — COMMENTED** [review]
Was a grep for `from revlog` performed?

I'll do a second pass, but intuition says this may throw off the "Estimated Time" calculations

**Comment by david-allison-1** [comment]
We'll also need an ecosystem compatibility ticket to perform the same action (although it'll probably be covered by Rust).

**Comment by mikehardy** [comment]
Thanks for the quick look! I did not do a grep, just followed the commit on #8008 and removed it from same places upstream removed it (today, overview, answer buttons)

I don't think we'll need a ticket as Rust scheduler is where the 0's are inserted, so we'll get it for...I hesitate to type "free" ;-) with anki rustlib scheduler adoption

**Comment by mikehardy** [comment]
re-pushed

**Review by david-allison-1 — COMMENTED** [review]
I feel `sched(v2).eta` also needs this treatment, but would understand if this is better done in another PR.

**Comment by mikehardy** [comment]
I'd prefer zero scheduler motion, any time spent in review or possible debugging or even thinking about it is better spent on the shift to rust IMHO

**Review by david-allison-1 — APPROVED** [review]
LGTM then

**Comment by mikehardy** [comment]
ok - will release an alpha with this one and any other merges I can scare up, to see if it's fixed for original reporter, thanks @david-allison-1

**Comment by mikehardy** [comment]
@dummifiedme if you could try the latest alpha we should have normal looking statistics again, I would love to hear confirmation. If you want to make sure you don't have issues you can just install the '.A' release in parallel for a quick check: https://github.com/ankidroid/Anki-Android/releases/tag/v2.15alpha21
