### PR TITLE
apiVersioning and developerContact implementation for AnkiDroid functions call from WebView 

### LINKED ISSUE #6328: implement AbstractFlashcardViewer / Javascript API versioning
###### Reproduction Steps

1. alter the functionality in AnkiDroid's Javascript interface for a new version
2. open a card with template based on advanced javascript functionality (e.g. #6307)

###### Expected Result

Some indication that your card template isn't working correctly, and that there is a real reason, and ideally who to contact and maybe how to fix it yourself

###### Actual Result

Card might just break, no idea why

From @david-allison-1 in https://github.com/ankidroid/Anki-Android/pull/6307#pullrequestreview-421444031 I liked this idea a lot:

> If we go down this route, we will want a method which will enable this complex functionality. Maybe not for this PR, but we should flesh out the plans, or we'll get hit by bad reviews that we can't do much about.
>
>    Something along the lines of: Define an "init" function, which accepts an API version number, and will toggle AbstractFlashcardViewer functions/signals in a forwards/backwards compatible manner.

So perhaps something like:

- add an "ankidroidJsStatus" to AbstractFlashcardViewer
- initialize that with contents of a 'ankidroidJsInit(int apiVersion, string developerContact)'
- inject a warning in review below the reviewer minibar / top of card if any parts of the interface were used with either no init or a deprecated API, including a link to a wiki page for more info - bonus points if it is dismissable for the entirety of a review session
- a wiki page explaining that we're adding to the interface and need to be able to version it to manage change over time, plus the exact changes (ideally copy-pastable for users) to get rid of the warning

Or similar, I'm more vague on the last points, anything reasonable to do versioning with user / developer notification of changes and ability to self help is welcome

### PR DESCRIPTION
**Pull request by infinyte7**
## Purpose / Description
This is implementation for api versioning for usage of AnkiDroid native functions in WebView.

## Fixes
Fixes #6328

## Approach
Getting api version & developer contact from card developer, then allow them to call the above functions implementation. 

## How Has This Been Tested?
Tested on Emulator
Calling this function before calling #6307  implemented functions
```javascript
<script>
   var jsApi = {"version" : "0.0.1", "developer" : "dev@mail.com"};

   var apiStatus = AnkiDroidJS.init(JSON.stringify(jsApi));
   console.log(apiStatus);
   
   api = JSON.parse(apiStatus);
   
   if (api['markCard']) {
      console.log("API mark card available");
   }   

   if (api['toggleFlag']) {
      console.log("API toggle flag available");
   }   
</script>
```
```apiStatus``` contain ```enabled/disabled``` status of api in ```true/false``` (boolean value).

## Learning (optional, can help others)
https://stackoverflow.com/questions/51513715/node-js-rest-api-versioning-the-right-way
https://stackoverflow.com/questions/32228300/how-to-prevent-my-snackbar-text-from-being-truncated-on-android

## Checklist
_Please, go through these checks before submitting the PR._

- [ x ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ x ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ x ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ x ] You have commented your code, particularly in hard-to-understand areas
- [ x ] You have performed a self-review of your own code

### CODE REVIEW

**Comment by infinyte7** [comment]
This is clean PR for api versioning earlier one have conflicts. This may not have conflicts.

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 1]
```diff
@@ -188,6 +191,13 @@
 
     // ETA
     private int eta;
+    // JavaScript Versioning
+    protected String mCardSuppliedApiVersion = "";
+    protected String mCardSuppliedDeveloperContact  = "";
+
+    private static final String sCurrentJsApiVersion = "1.0.0";
+    // JS api list enable/disable status
+    private HashMap<String, Boolean> jsApiListMap = new HashMap<String, Boolean>();
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:200]:
```suggestion
    private HashMap<String, Boolean> mJsApiListMap = new HashMap<String, Boolean>();
```

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 2]
```diff
@@ -3158,27 +3168,35 @@ private boolean filterUrl(String url) {
...
-                    case "orange": executeCommand(COMMAND_TOGGLE_FLAG_ORANGE);
-                        return true;
-                    case "green": executeCommand(COMMAND_TOGGLE_FLAG_GREEN);
-                        return true;
-                    case "blue": executeCommand(COMMAND_TOGGLE_FLAG_BLUE);
-                        return true;
-                    default:
-                        Timber.d("No such Flag found.");
-                        return true;
+                if (jsApiListMap.get("toggleFlag")) {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3180]: nit: invert the if with `showDeveloperContact()` inside the block, and return early to reduce nesting.

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 3]
```diff
@@ -3419,6 +3437,62 @@ void handleUrlFromJavascript(String url) {
...
+        int majorCurrentApiVersion = Integer.parseInt(currentApiVersion[0]);
+        int minorCurrentApiVersion = Integer.parseInt(currentApiVersion[1]);
+        int patchCurrentApiVersion = Integer.parseInt(currentApiVersion[2]);
+
+        if (versionSupplied.length <= 2) {
+            UIUtils.showThemedToast(AbstractFlashcardViewer.this, getString(R.string.valid_js_api_version, sCurrentJsApiVersion), false);
+            return false;
+        }
+
+        if (versionSupplied.length == 3) {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3478]: invert the if and return early to reduce nesting

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 4]
```diff
@@ -3419,6 +3437,62 @@ void handleUrlFromJavascript(String url) {
...
+            int majorVersionSupplied = Integer.parseInt(versionSupplied[0]);
+            int minorVersionSupplied = Integer.parseInt(versionSupplied[1]);
+            int patchVersionSupplied = Integer.parseInt(versionSupplied[2]);
+
+            if (majorVersionSupplied == majorCurrentApiVersion && minorVersionSupplied == minorCurrentApiVersion && patchVersionSupplied == patchCurrentApiVersion) {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3483]: Might be worth extracting this parsing/logic to a class. Implementer's choice.

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java (hunk 1 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:200]: Wouldn't a `HashSet<String>` be better here,

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java (hunk 4 above)
Comment (infinyte7) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java]: Extracted to a class.

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java (hunk 3 above)
Comment (infinyte7) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java]: I have changed it. May be better than previous one.

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java (hunk 2 above)
Comment (infinyte7) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java]: Updated

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java (hunk 1 above)
Comment (infinyte7) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java]: I don't know which one is better. But ```HashSet``` can also be implemented.

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 5]
```diff
@@ -3449,6 +3468,77 @@ void handleUrlFromJavascript(String url) {
...
+        snackbar.show();
+    }
+
+    /*
+     *AnkiDroid JavaScript API Class for major, minor, patch version eg: 1.2.3
+     * major version : 1
+     * minor version : 2
+     * patch version : 3
+     */
+    private class JsApiVersionClass {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3501]: You could extract a lot of the logic in `requireApiVersion` to here as well.

* Static builder which takes a string, and converts it into a version
* Comparable<> or similar, which takes two versions and returns which is larger.

This would significantly cut down on the logic in `requireApiVersion`

Comment (infinyte7) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java]: I implemented using this 
https://stackoverflow.com/questions/198431/how-do-you-compare-two-version-strings-in-java/27891752#Another%20solution%20for%20this%20old%20post%20(for%20those%20that%20it%20might%20help)%20:

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 6]
```diff
@@ -3493,49 +3493,89 @@ private void showDeveloperContact() {
...
+                return false;
+            }
+
+            return this.compareTo((Version) that) == 0;
+        }
+    }
+
+    private boolean requireApiVersion(String apiVer) {
+
+        Version mVersionCurrent = new Version(sCurrentJsApiVersion);
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3568]: much nicer - could convert `sCurrentJsApiVersion` to a `Version`

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 7]
```diff
@@ -3493,49 +3493,89 @@ private void showDeveloperContact() {
...
+        Version mVersionSupplied = new Version(apiVer);
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3569]: What if this throws?

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 8]
```diff
@@ -3493,49 +3493,89 @@ private void showDeveloperContact() {
...
+
+        if (mVersionCurrent.equals(mVersionSupplied)) {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3571]: extract the result of `compareTo` above the ifs, then you only need to call it once

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 9]
```diff
@@ -3493,49 +3493,89 @@ private void showDeveloperContact() {
...
-    }
+    public class Version implements Comparable<Version> {
 
-    /*
-     *Supplied api version must be equal to current api version to call mark card, toggle flag functions etc.
-     */
-    private boolean requireApiVersion(String apiVer) {
-        String[] versionSupplied = apiVer.split("\\.");
-        String[] currentApiVersion = sCurrentJsApiVersion.split("\\.");
+        private String version;
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3506]:
```suggestion
        private final String mVersion;
```

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 10]
```diff
@@ -3493,49 +3493,89 @@ private void showDeveloperContact() {
...
+        public final String get() {
+            return this.version;
+        }
 
-        mJsCurrentVersion.major = Integer.parseInt(currentApiVersion[0]);
-        mJsCurrentVersion.minor = Integer.parseInt(currentApiVersion[1]);
-        mJsCurrentVersion.patch = Integer.parseInt(currentApiVersion[2]);
+        public Version(String version) {
+            if (version == null) {
+                throw new IllegalArgumentException("Version can not be null");
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3514]: turn this into a static factory method `createInstance` which will return null on failure. This means you get a simple constructor that does no work and doesn't throw.

Make sure you handle a null return, as the code currently doesn't handle exceptions

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 11]
```diff
@@ -3493,49 +3493,89 @@ private void showDeveloperContact() {
...
+        @Override
+        public int compareTo(Version that) {
+            if (that == null) {
+                return 1;
+            }
 
-            mJsSuppliedVersion.major = Integer.parseInt(versionSupplied[0]);
-            mJsSuppliedVersion.minor = Integer.parseInt(versionSupplied[1]);
-            mJsSuppliedVersion.patch = Integer.parseInt(versionSupplied[2]);
+            String[] thisParts = this.get().split("\\.");
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3529]: Might as well move the conversion to an int array into the constructor for speed.

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 12]
```diff
@@ -3493,49 +3493,89 @@ private void showDeveloperContact() {
...
+            String[] thatParts = that.get().split("\\.");
+            int length = Math.max(thisParts.length, thatParts.length);
 
-            if (mJsCurrentVersion.major > mJsSuppliedVersion.major || mJsCurrentVersion.minor > mJsSuppliedVersion.minor || mJsCurrentVersion.patch > mJsSuppliedVersion.patch) {
-                UIUtils.showThemedToast(AbstractFlashcardViewer.this, getString(R.string.update_js_api_version, sCurrentJsApiVersion), false);
-                return false;
-            } else if (mJsCurrentVersion.major == mJsSuppliedVersion.major && mJsCurrentVersion.minor == mJsSuppliedVersion.minor && mJsCurrentVersion.patch == mJsSuppliedVersion.patch) {
+            for (int i = 0; i < length; i++) {
+                int thisPart = i < thisParts.length ? Integer.parseInt(thisParts[i]) : 0;
+                int thatPart = i < thatParts.length ? Integer.parseInt(thatParts[i]) : 0;
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3535]: This can fail due to overflow

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java (hunk 7 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3569]: Not a member variable - no need for the m prefix
```suggestion
        Version versionSupplied = new Version(apiVer);
```

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 13]
```diff
@@ -3493,49 +3493,89 @@ private void showDeveloperContact() {
...
+    }
+
+    private boolean requireApiVersion(String apiVer) {
+
+        Version mVersionCurrent = new Version(sCurrentJsApiVersion);
+        Version mVersionSupplied = new Version(apiVer);
+
+        if (mVersionCurrent.equals(mVersionSupplied)) {
+            return true;
+        } else if (mVersionCurrent.compareTo(mVersionSupplied) == 1) {   // mCurrent > mSupplied
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3573]: Technically, this should be `> 0`, and the next should be `< 0`

**Comment by infinyte7** [comment]
I will update it as suggested.

**Comment by mikehardy** [comment]
Hey guys, SemVer is actually kind of complicated. We can just re-use this library, it already implements the Comparable interface as well: https://github.com/zafarkhaja/jsemver

Let's do that and not add code we don't need to

**Comment by infinyte7** [comment]
I have implemeted it. It is far more easier than my implementation. But I have leaned new things. Thanks

**Comment by mikehardy** [comment]
Yeah, I think there is value in really looking deeply at semver to understand how much they really pack into it and how as even a very small problem domain it is *still* hard to get right! Then just using (and contributing to) a general-purpose library is the right way to go in in the end :)

**Comment by infinyte7** [comment]
Are there any improvements to this?

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 14]
```diff
@@ -3449,6 +3470,49 @@ void handleUrlFromJavascript(String url) {
...
+        snackbar.show();
+    }
+
+    /**
+     * Supplied api version must be equal to current api version to call mark card, toggle flag functions etc.
+     */
+    private boolean requireApiVersion(String apiVer) {
+
+        Version mVersionCurrent = Version.valueOf(sCurrentJsApiVersion);
+        Version mVersionSupplied = Version.valueOf(apiVer);
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3503]: Do you need validation here? What happens with an invalid version?

File: AnkiDroid/src/main/res/values/02-strings.xml [hunk 15]
```diff
@@ -274,6 +274,14 @@
     <!-- in options menu & Navigation Drawer -->
     <string name="ankidroid_turn_on_fullscreen_nav_drawer">Please turn on fullscreen to use Show Navigation Drawer using JavaScript.</string>
     <string name="ankidroid_turn_on_fullscreen_options_menu">Please turn on fullscreen to use Show Options Menu using JavaScript.</string>
+
+    <string name="api_version_developer_contact">This card uses unsupported AnkiDroid features. Contact the deck creator at %s, or view the wiki to resolve this manually.</string>
+    <string name="api_version_no_developer_contact">This card uses unsupported AnkiDroid features. View the wiki to resolve this manually.</string>
+    <string name="invalid_json_data">Card provided invalid data. %s</string>
+    <string name="valid_js_api_version">Please provide a valid JavaScript API. Current API version is %s</string>
+    <string name="update_js_api_version">Please update JavaScript API version. Current API version is %s</string>
```
Comment (david-allison-1) [inline AnkiDroid/src/main/res/values/02-strings.xml:282]: We'll need to go through these strings and make them user-friendly. Can't think about how to do this right now.

Possibly with error codes that can be given to a developer.

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java (hunk 14 above)
Comment (infinyte7) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3503]: I think apiVer passed to valueof so may be Sem Ver library may have internal check for invalid input.

File: AnkiDroid/src/main/res/values/02-strings.xml (hunk 15 above)
Comment (infinyte7) [reply AnkiDroid/src/main/res/values/02-strings.xml:282]: So error code should also defined.

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java (hunk 14 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3503]: What happens? Does it throw an exception? If not, which code path would it take?

File: AnkiDroid/src/main/res/values/02-strings.xml (hunk 15 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/res/values/02-strings.xml:282]: We need some way of telling a user "something went wrong, it's not AnkiDroid's fault, please contact the deck author", but with additional information for the deck author to handle.

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 16]
```diff
@@ -3449,6 +3470,49 @@ void handleUrlFromJavascript(String url) {
...
+
+        if (mVersionCurrent.equals(mVersionSupplied)) {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3505]: @mikehardy - I don't know enough about semVer to handle this one, but what do we want here? We're going to get a lot of API version increases, and at what point do we want to say "break all API clients"

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3505]: great question. So semVer allows for "compatible version range specification".
You always assume the requested version range will work

Ranges may be unbounded, saying just "anything higher than X.Y.Z is good". In practice most ranges are like that.

You just do a quick match and and if the requested API range is within our current API range, it's good to go. If it is not, then you say "Current AnkiDroid Javascript API is incompatible with the range requested by your template. Contact the author XXX or click here for more info" (or similar)

This link https://nodesource.com/blog/semver-a-primer/ has a good explanation of "Semver Ranges" with examples of how they are specified and what they mean.

Semver by itself is actually not useful without the range specification and comparison. 

Thank goodness the library I pointed to implements it already or it would be nasty :-) https://github.com/zafarkhaja/jsemver#semver-expressions-api-ranges

Comment (infinyte7) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3505]: I will update in between ranges.

File: AnkiDroid/src/main/res/values/02-strings.xml (hunk 15 above)
Comment (infinyte7) [reply AnkiDroid/src/main/res/values/02-strings.xml:282]: Okay, I will update it

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java (hunk 14 above)
Comment (infinyte7) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3503]: Exception handling to be implemented.

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 17]
```diff
@@ -3449,6 +3474,99 @@ void handleUrlFromJavascript(String url) {
...
+
+            Version mVersionCurrent = Version.valueOf(sCurrentJsApiVersion);
+            Version mVersionSupplied = Version.valueOf(apiVer);
+
+            /*
+            * if api major version equals to supplied major version then return true and also check for minor version and patch version
+            * show toast for update and contact developer if need updates
+            * otherwise return false
+            */
+            if (mVersionCurrent.equals(mVersionSupplied)) {
```
Comment (infinyte7) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3535]: Need improvements

**Comment by infinyte7** [comment]
I have implemented better condition for checking sem ver. Any improvements?

**Comment by mikehardy** [comment]
Thanks @infinyte7 - I'll scan through again when I get a chance, much appreciated

**Comment by infinyte7** [comment]
I get null reference error when not initialized. I will put it ready to review when complete.

**Comment by infinyte7** [comment]
In the demo,
1. When not initialized
2. When supplied correct api version & developer contact
3. When supplied api version lower  than minimum required
4. When supplied api version upper than current version 

api_demo

**Comment by infinyte7** [comment]
Hope to see it in AnkiDroid 2.13

**Comment by mikehardy** [comment]
Wow, watching that is all basically amazing. Great demo, thanks for grabbing that and posting it.
I'll review this as soon as I get a chance, the functionality we dreamed up all seems to be there!

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 18]
```diff
@@ -3450,6 +3481,87 @@ void handleUrlFromJavascript(String url) {
...
 
+    /*
+     * see 02-strings.xml
+     * Show Error code when mark card or flag card unsupported
+     * 1 - mark card
+     * 2 - flag card
+     *
+     * show developer contact if js api used in card is deprecated
+     */
+    private void showDeveloperContact(int errorCode) {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3492]: ErrorCode would be better behind either an enum or an IntDef

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 19]
```diff
@@ -3189,11 +3203,28 @@ private boolean filterUrl(String url) {
             }
             // mark card using javascript
             if (url.startsWith("signal:mark_current_card")) {
-                executeCommand(COMMAND_MARK);
+                if (mJsApiListMap.get("markCard") == null) {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3206]: Can we extract this pattern to a method - it'll cut down on repetition and focus on what we need

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 20]
```diff
@@ -3450,6 +3481,87 @@ void handleUrlFromJavascript(String url) {
...
+     * see 02-strings.xml
+     * Show Error code when mark card or flag card unsupported
+     * 1 - mark card
+     * 2 - flag card
+     *
+     * show developer contact if js api used in card is deprecated
+     */
+    private void showDeveloperContact(int errorCode) {
+        String errorMsg = "";
+        switch (errorCode) {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3494]: Might want to extract this to a method - can significantly cut down on code as you can return without a `break`

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 21]
```diff
@@ -3450,6 +3481,87 @@ void handleUrlFromJavascript(String url) {
...
+     * Supplied api version must be equal to current api version to call mark card, toggle flag functions etc.
+     */
+    private boolean requireApiVersion(String apiVer, String apiDevContact) {
+        try {
+
+            if (TextUtils.isEmpty(apiDevContact)) {
+                return false;
+            }
+
+            Version mVersionCurrent = Version.valueOf(sCurrentJsApiVersion);
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3537]: These throw:

```
     * @throws IllegalArgumentException if the input string is {@code NULL} or empty
     * @throws ParseException when invalid version string is provided
     * @throws UnexpectedCharacterException is a special case of {@code ParseException}
```

Do we want to handle any of these explicitly?

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 22]
```diff
@@ -3189,11 +3203,28 @@ private boolean filterUrl(String url) {
             }
             // mark card using javascript
             if (url.startsWith("signal:mark_current_card")) {
-                executeCommand(COMMAND_MARK);
+                if (mJsApiListMap.get("markCard") == null) {
+                    showDeveloperContact(1);
+                    return true;
+                } else if (mJsApiListMap.get("markCard")) {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3209]: Might want to consider extracting the magic constants

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 23]
```diff
@@ -3498,6 +3610,52 @@ protected void showTagsDialog() {
...
+                    mCardSuppliedDeveloperContact  = data.optString("developer", "");
+                }
+
+            } catch (JSONException j) {
+                UIUtils.showThemedToast(AbstractFlashcardViewer.this, getString(R.string.invalid_json_data, j.getLocalizedMessage()), false);
+            }
+
+            String apiStatusJson = "";
+
+            if (requireApiVersion(mCardSuppliedApiVersion, mCardSuppliedDeveloperContact)) {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3647]: This uses the previous values if an exception is thrown

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 24]
```diff
@@ -3498,6 +3610,52 @@ protected void showTagsDialog() {
...
+                enableJsApi();
+                apiStatusJson = sGson.toJson(mJsApiListMap);
+            } else {
+                disableJsApi();
+                apiStatusJson = sGson.toJson(mJsApiListMap);
+                return String.valueOf(apiStatusJson);
+            }
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3654]: Extract the following outside both branches of the if, they're identical on both sides

```
apiStatusJson = sGson.toJson(mJsApiListMap);
return String.valueOf(apiStatusJson);
```

File: AnkiDroid/src/main/res/values/02-strings.xml [hunk 25]
```diff
@@ -279,4 +279,19 @@
...
+    <string name="invalid_json_data">Card provided invalid data. %s</string>
+    <string name="valid_js_api_version">Invalid AnkiDroid JS API version. Contact developer %s, or view wiki</string>
+    <string name="update_js_api_version">AnkiDroid JS API update available. Contact developer %s, or view wiki</string>
+    <string name="reviewer_invalid_api_version_visit_documentation">View</string>
+    <string name="update_js_api_patch_version">AnkiDroid JS API patch update available. Contact developer %s, or view wiki.</string>
+    <string name="update_js_api_minor_version">AnkiDroid JS API minor update available. Contact developer %s, or view wiki.</string>
+    <string name="js_api_not_implemented">JS API not implemented to current deck. View wiki.</string>
+
+    <!-- Error codes for AnkiDroid JS API-->
+    <string name="anki_js_unknown_error">(Error Code:0)</string>
```
Comment (david-allison-1) [inline AnkiDroid/src/main/res/values/02-strings.xml:293]: You can combine these into one string: 

`(Error Code: %d)`

and provide optional strings as additional strings.

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 26]
```diff
@@ -189,6 +194,15 @@
 
     // ETA
     private int eta;
+    // JavaScript Versioning
+    protected String mCardSuppliedApiVersion = "";
+    protected String mCardSuppliedDeveloperContact  = "";
```
[the remark this answers is not in the document]
Comment (infinyte7) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:202]: It should be checked on each card because if card edited in middle of deck review and previous persistence data will help to complete the review. But after closing and opening the deck and it will show error.

[the remark this answers is not in the document]
Comment (infinyte7) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:202]: Also it can be implemented as in javascript by deck developer to stop execution every time of ```init()```

```javascript
<script>
var apiEnabled = false;

if (!apiEnabled) {
var jsApi = {"version" : "0.0.1", "developer" : "dev@mail.com"};

var apiStatus = AnkiDroidJS.init(JSON.stringify(jsApi));

var api = JSON.parse(apiStatus);

if (api['markCard'] && api['toggleFlag']) {
       apiEnabled = true;
}

console.log(apiStatus);
}
</script>
```

And storing ```apiEnabled``` in persistence data help in stopping again execution of ```init()```.

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java (hunk 18 above)
Comment (infinyte7) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3508]: This part need help.

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java (hunk 21 above)
Comment (infinyte7) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3539]: Should it also be put in ```try catch``` block? 
Because ```sCurrentJsApiVersion``` and ```apiVer``` is set to ```"0.0.1"``` and ```""```.

Comment (infinyte7) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3539]: This part need help.

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 27]
```diff
@@ -3481,6 +3489,14 @@ void handleUrlFromJavascript(String url) {
         }
     }
 
+    // Check if value null
+    private boolean isAnkiApiNull(String api) {
+        if (mJsApiListMap.get(api) == null) {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3494]:
```suggestion
        return mJsApiListMap.get(api) == null;
```

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java (hunk 18 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3508]: I don't think we need it now we're no longer switching on errorCode

File: AnkiDroid/src/main/res/values/02-strings.xml [hunk 28]
```diff
@@ -290,8 +290,5 @@
     <string name="js_api_not_implemented">JS API not implemented to current deck. View wiki.</string>
 
     <!-- Error codes for AnkiDroid JS API-->
-    <string name="anki_js_unknown_error">(Error Code:0)</string>
-    <string name="anki_js_not_implemented">(Error Code:1)</string>
-    <string name="anki_js_mark_card_not_supported">(Error Code:2)</string>
-    <string name="anki_js_flag_card_not_supported">(Error Code:3)</string>
+    <string name="anki_js_error_code">(Error Code:%d)</string>
```
Comment (david-allison-1) [inline AnkiDroid/src/main/res/values/02-strings.xml:293]:
```suggestion
    <string name="anki_js_error_code">(Error Code: %d)</string>
```

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java (hunk 21 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3539]: Where we set the value we can guarantee it's not going to crash. We need to ensure we know what we're doing if the user supplies us with invalid values

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java (hunk 20 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java]: No need - was removed in a later PR

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java (hunk 21 above)
Comment (infinyte7) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3533]: In this case the code is wrapped in ```try catch``` block twice. So there is still need to check for that?

[AbstractFlashcardViewer.java#L3632](https://github.com/ankidroid/Anki-Android/blob/401cddc3e3b263d56fdc356270be221056016516/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L3632)

[AbstractFlashcardViewer.java#L3527](https://github.com/ankidroid/Anki-Android/blob/401cddc3e3b263d56fdc356270be221056016516/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L3527)

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java (hunk 23 above)
Comment (infinyte7) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java]: Yes, but also show error that ```invalid data provided```.

**Comment by infinyte7** [comment]
Are there any improvement to these implementations?

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 29]
```diff
@@ -193,6 +198,20 @@
 
     // ETA
     private int eta;
+    // JavaScript Versioning
+    protected String mCardSuppliedApiVersion = "";
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:202]: I think this can be a local variable

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 30]
```diff
@@ -193,6 +198,20 @@
...
+    protected String mCardSuppliedDeveloperContact  = "";
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:203]: This isn't reset when a new card is shown

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 31]
```diff
@@ -3665,6 +3670,9 @@ private void enableJsApi() {
 
         @JavascriptInterface
         public String init(String jsonData) {
+            // initialize api
+            initJsApi();
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3674]: The problem is that `init` isn't guaranteed to be called by the next card, could this also be called on `displayCardQuestion`

Comment (infinyte7) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java]: ```init()``` in ```displayCardQuestion``` will called even it not needed. 
Should one option added to reviewer to toggle api ```init```?

Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java]: I'm not sure that I understand, but what's currently there looks good from an implementation perspective.

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 32]
```diff
@@ -3489,6 +3529,78 @@ void handleUrlFromJavascript(String url) {
...
+                    return true;
+                } else {
+                    return false;
+                }
+            } else {
+                UIUtils.showThemedToast(AbstractFlashcardViewer.this, getString(R.string.valid_js_api_version, mCardSuppliedDeveloperContact), false);
+                return false;
+            }
+        } catch (Exception e) {
+          Timber.i(e, "requireApiVersion::exception");
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3599]:
```suggestion
          Timber.w(e, "requireApiVersion::exception");
```

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 33]
```diff
@@ -3531,12 +3643,58 @@ protected void showTagsDialog() {
         showDialogFragment(dialog);
     }
 
+    // list of api that can be accessed
+    private final String[] sApiList = {"toggleFlag", "markCard"};
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3647]: Would be better at the top of the class

**Comment by david-allison-1** [comment]
Needs a rebase onto current master to fix the CI failure. master was broken for a short while

**Comment by infinyte7** [comment]
To be updated

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 34]
```diff
@@ -3531,12 +3643,58 @@ protected void showTagsDialog() {
...
+            mJsApiListMap.put(sApiList[i], false);
+        }
+    }
+
  /*
  Javascript Interface class for calling Java function from AnkiDroid WebView
 see card.js for available functions
  */
+    // list of api that can be accessed
+    private final String[] sApiList = {"toggleFlag", "markCard"};
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3661]:
```suggestion
    private final String[] mApiList = {"toggleFlag", "markCard"};
```

This isn't static and though Hungarian Notation isn't great we are at consistent at the moment, should be member variable (and then all usage will need change to match)

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 35]
```diff
@@ -3531,12 +3643,58 @@ protected void showTagsDialog() {
...
+
     public class JavaScriptFunction {
 
+        private final Gson sGson = new Gson();
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3665]:
```suggestion
        private final Gson mGson = new Gson();
```

Same notation comment as above - should be marked as member variable and usage altered to match

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 36]
```diff
@@ -3658,16 +3658,16 @@ private void jsApiInit() {
 see card.js for available functions
  */
     // list of api that can be accessed
-    private final String[] sApiList = {"toggleFlag", "markCard"};
+    private final String[] mApiList = {"toggleFlag", "markCard"};
 
     public class JavaScriptFunction {
 
-        private final Gson sGson = new Gson();
+        private final Gson mGson = new Gson();
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3665]: Wouldn't be a problem with making this static

Comment (infinyte7) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3665]: Android Studio is suggesting to make ```JavaScriptFunction``` static.

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3665]: If it works either way (static or member) that's fine, so long as it's consistent one way or another.
I prefer non-static as it's easier to test it if we need/want to later to inspect something. Static makes
testing hard in my experience, so I'll merge it like this
