### PR TITLE
 fix: batch shortcut disabling to avoid TransactionTooLargeException

### LINKED ISSUE #19800: App crashes with `TransactionTooLargeException` when deleting deck with many subdecks
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

When attempting to delete a deck that contains many subdecks/children, the app crashes with a `TransactionTooLargeException`. The crash occurs because `disableDeckAndChildrenShortcuts()` tries to disable all deck shortcuts in a single Binder IPC transaction, which exceeds Android's 1MB limit.

## Steps to reproduce:
   1. Create or import a deck with many subdecks (hundreds or thousands)
   2. Long-press on the parent deck to open context menu
   3. Select "Delete deck"
   4. App crashes immediately

### Expected behaviour

The deck should be deleted successfully without crashing.

## Actual behavior:
   App crashes with java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 3555756 bytes

### Debug info

```text
Logcat:

     java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 3555756 bytes
         at android.content.pm.ShortcutManager.disableShortcuts(ShortcutManager.java:388)
         at androidx.core.content.pm.ShortcutManagerCompat.disableShortcuts(ShortcutManagerCompat.java:608)
         at com.ichi2.anki.DeckPicker.disableDeckAndChildrenShortcuts(DeckPicker.kt:2255)
         at com.ichi2.anki.DeckPicker.handleContextMenuSelection(DeckPicker.kt:888)
     Caused by: android.os.TransactionTooLargeException: data parcel size 3555756 bytes
         at android.os.BinderProxy.transactNative(Native Method)
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by xenonnn4w**
## Purpose / Description
 Fix crash when deleting a deck with many subdecks due to `TransactionTooLargeException.`

## Fixes
* Fixes #19800 

## Approach
 When deleting a deck, `disableDeckAndChildrenShortcuts()` was calling `ShortcutManagerCompat.disableShortcuts()` with all deck IDs at once. For decks with many children, this exceeded Android's 1MB Binder IPC transaction limit (~3.5MB in this case).

The fix batches the shortcut disabling into chunks of 100 IDs at a time, keeping each transaction well under the limit.

## How Has This Been Tested?

Tested by deleting a deck with a large number of subdecks(that i created through the developer options) that previously caused the crash.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 1]
```diff
@@ -2252,7 +2252,12 @@ open class DeckPicker :
         // Get the DeckId and all child DeckIds
         val deckTreeDids = dueTree?.find(did)?.map { it.did.toString() } ?: listOf()
         val errorMessage: CharSequence = getString(R.string.deck_shortcut_doesnt_exist)
-        ShortcutManagerCompat.disableShortcuts(this, deckTreeDids, errorMessage)
+        // Batch the shortcut disabling to avoid TransactionTooLargeException
+        // when dealing with decks that have many children
+        val batchSize = 100
+        deckTreeDids.chunked(batchSize).forEach { batch ->
+            ShortcutManagerCompat.disableShortcuts(this, batch, errorMessage)
+        }
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt]: We should write our own wrapper here.

* move implementation details out of the DeckPicker
* Other exceptions are thrown, which should be handled

File: AnkiDroid/src/main/java/com/ichi2/anki/utils/ShortcutUtils.kt [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+    fun disableShortcuts(
+        context: Context,
+        shortcutIds: List<String>,
+        disabledMessage: CharSequence,
+    ) {
+        if (shortcutIds.isEmpty()) return
+
+        shortcutIds.chunked(BATCH_SIZE).forEach { batch ->
+            runCatching { ShortcutManagerCompat.disableShortcuts(context, batch, disabledMessage) }
+                .onFailure { e -> Timber.w(e, "Failed to disable shortcuts batch") }
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/utils/ShortcutUtils.kt:53]: Use `runCatchingWithReport` so we're notified of failures

**Review by david-allison — CHANGES_REQUESTED** [review]
One minor request, but looks awesome!

**Review by BrayanDSO — APPROVED** [review]
Looks great
