### PR TITLE
fix(card-browser): fix crash on note deletion 

### LINKED ISSUE #20556: Browse: Crash on Delete Note
* Create Note
* Study it via Study Screen
* Select it
* Delete Note
* Crash

----

```
13:29:45.039 ACRA                     E  ACRA caught a BackendNotFoundException for com.ichi2.anki.debug (Fix with AI)
                                         net.ankiweb.rsdroid.exceptions.BackendNotFoundException: Your database appears to be in an inconsistent state. Please use the Check Database action. No such card: '1567726272938'
                                         	at net.ankiweb.rsdroid.BackendException$Companion.fromError(BackendException.kt:193)
                                         	at net.ankiweb.rsdroid.BackendKt.unpackResult(Backend.kt:317)
                                         	at net.ankiweb.rsdroid.BackendKt.access$unpackResult(Backend.kt:1)
                                         	at net.ankiweb.rsdroid.Backend.runMethodRaw$lambda$1(Backend.kt:133)
                                         	at net.ankiweb.rsdroid.Backend.$r8$lambda$rLALQVYPlbbEmpwIB7kwMA6SO_U(Unknown Source:0)
                                         	at net.ankiweb.rsdroid.Backend$$ExternalSyntheticLambda2.invoke(D8$$SyntheticClass:0)
                                         	at net.ankiweb.rsdroid.Backend.withBackend(Backend.kt:145)
                                         	at net.ankiweb.rsdroid.Backend.runMethodRaw(Backend.kt:132)
                                         	at anki.backend.GeneratedBackend.getCardRaw(GeneratedBackend.kt:302)
                                         	at anki.backend.GeneratedBackend.getCard(GeneratedBackend.kt:309)
                                         	at com.ichi2.anki.libanki.Card.load(Card.kt:135)
                                         	at com.ichi2.anki.libanki.Card.<init>(Card.kt:127)
                                         	at com.ichi2.anki.libanki.Collection.getCard(Collection.kt:595)
                                         	at com.ichi2.anki.browser.CardBrowserViewModel$launchSearchForCards$2$3.invokeSuspend$lambda$0$0(CardBrowserViewModel.kt:1272)
                                         	at com.ichi2.anki.browser.CardBrowserViewModel$launchSearchForCards$2$3.$r8$lambda$iF2G8qMlU9OrzN2cSYESe0QF0HA(Unknown Source:0)
                                         	at com.ichi2.anki.browser.CardBrowserViewModel$launchSearchForCards$2$3$$ExternalSyntheticLambda1.invoke(D8$$SyntheticClass:0)
                                         	at com.ichi2.anki.CollectionManager.withCol$lambda$0(CollectionManager.kt:146)
                                         	at com.ichi2.anki.CollectionManager.$r8$lambda$YWF2-7xOSLjf6_Rj2swd1g-bkIA(Unknown Source:0)
                                         	at com.ichi2.anki.CollectionManager$$ExternalSyntheticLambda9.invoke(D8$$SyntheticClass:0)
                                         	at com.ichi2.anki.CollectionManager$withQueue$3.invokeSuspend(CollectionManager.kt:128)
                                         	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
                                         	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
                                         	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
                                         	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
                                         	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
                                         	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
                                         	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
                                         	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
                                         	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@267be54, Dispatchers.Main.immediate]
```

----

AnkiDroid Version = 2.24.0alpha10 (https://github.com/ankidroid/Anki-Android/commit/00d60d12413e19be766565cd711d1a7408413876)
Backend Version = 0.1.63-anki25.09.2 (25.09.2 3890e12c9e48c028c3f12aa58cb64bd9f8895e30)
Android Version = 16 (SDK 36)
ProductFlavor = full
Device Info = Google | google | caiman | caiman | Pixel 9 Pro | caiman
WebView Info = [com.google.android.webview | 768011903]: Mozilla/5.0 (Linux; Android 16; Pixel 9 Pro Build/CP1A.260305.018; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/146.0.7680.119 Mobile Safari/537.36
ACRA UUID = 4df92614-8644-42e8-a797-27985368923c
FSRS = 5.1.0 (Enabled: true)
Crash Reports Enabled = true

### PR DESCRIPTION
**Pull request by david-allison**
> [!NOTE]
> Assisted-by: Claude Opus 4.6; see commit messages; all code self-reviewed

## Purpose / Description
* NOTES mode
* 'Browse' a card
* Delete the Card
* Crash as `cardIdToBeScrolledTo` is invalid

## Fixes
* Fixes #20556

## Approach
* Remove `cardIdToBeScrolledTo` after use
* Validate the target card

----

* optimization: Don't call `viewModelScope.launch { searchJob?.join() }` if there's nothing to be done
* fix a double-search bug
* some test refactoring

## Learning
* https://github.com/ankidroid/Anki-Android/commit/b825f75f4119f2dddcd7f4f3b776ecd891fd172f
* https://github.com/ankidroid/Anki-Android/pull/19687

## How Has This Been Tested?
Unit tested only

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/test/java/com/ichi2/testutils/TestChangeSubscriber.kt [hunk 1]
```diff
@@ -56,6 +56,23 @@ suspend fun ensureOpsExecuted(
...
 
+/**
+ * Ensures that [ChangeManager.notifySubscribers] is called with [handler] as the handler
+ */
+suspend fun ensureOpWithHandler(
+    handler: Any,
+    block: suspend () -> Unit,
+) {
+    val handlerAccessor = ExtractOpHandler()
+    ChangeManager.subscribe(handlerAccessor)
```
Comment (criticalAY) [inline AnkiDroid/src/test/java/com/ichi2/testutils/TestChangeSubscriber.kt:67]: Just curious do we need to unsubscribe (try-finally)?

**Review by criticalAY — CHANGES_REQUESTED** [review]
Looks nice and clean to me just one question rest is all good imo

File: AnkiDroid/src/test/java/com/ichi2/testutils/TestChangeSubscriber.kt (hunk 1 above)
Comment (david-allison) [reply AnkiDroid/src/test/java/com/ichi2/testutils/TestChangeSubscriber.kt:67]: * No, it uses a `WeakReference` which is cleaned up
  * This is actually why we use a class, rather than a lambda, as the lambda can be cleaned up too early. 

https://github.com/ankidroid/Anki-Android/blob/22c565c3bec6caae2ce5f1c0b8d7f9b8519ec1e3/AnkiDroid/src/main/java/com/ichi2/anki/observability/ChangeManager.kt#L76-L86

* There's a precondition in the setup of RobolectricTest which cleans up any stragglers

https://github.com/ankidroid/Anki-Android/blob/4d263990fe55f7d79c0014263552fdf519983b1e/AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.kt#L151
