### PR TITLE
fix(browser): use delta-based scrolling for fast scroller

### LINKED ISSUE #19841: Dragging the scrollbar isn't intuitive when there are few cards
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Make a deck of ~30 cards.
2. Open the browser.
3. Drag the scrolbar.

You need to move your finger to the very bottom of the scrollbar to move it.

**It's best to see this recording:**

https://github.com/user-attachments/assets/800edfc2-dc9f-400a-b9df-0bce673907b7

### Expected behaviour

The scrollbar moves as you move your finger, depending on how much the finger has moved, not on where it is on the screen.

### Debug info

```text
AnkiDroid Version = 2.23.1 (3f3133b496b531383e9a6494f5a7704634935308)  
Backend Version = 0.1.62-anki25.09.2 (25.09.2 3890e12c9e48c028c3f12aa58cb64bd9f8895e30)  
Android Version = 13 (SDK 33)  
ProductFlavor = full  
Device Info = Xiaomi | POCO | mondrian | mondrian_global | 23013PC75G | qcom  
Webview User Agent = Mozilla/5.0 (Linux; Android 13; 23013PC75G Build/TKQ1.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/142.0.7444.171 Mobile Safari/537.36  
ACRA UUID = 4afc3b3f-e93f-4a66-bc71-2b9476ef9eb0  
FSRS = 5.1.0 (Enabled: false)  
Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by xenonnn4w**
## Purpose / Description
The fast scroller in the Card Browser was unintuitive when there are few cards. When dragging the scrollbar, users needed to move their finger to the very bottom of the scrollbar to move it, rather than being able to drag from wherever they grabbed it.

## Fixes
* Fixes #19841

## Approach
The issue was caused by using absolute position calculation for scrolling. When the user touched the handle, it would calculate `scrollProportion = touchY / barHeight` and jump to that position using `scrollToPosition()`. With few cards, the handle is large, and touching anywhere on it would cause it to jump based on the touch coordinate rather than staying where grabbed.

Restored the original delta-based scrolling approach from the upstream library (pluscubed/recycler-fast-scroll):
- Calculate the **delta** (change) in Y position from the last touch event
- Convert that delta to a scroll amount using `computeVerticalScrollRange()`
- Use `scrollBy()` instead of `scrollToPosition()` to scroll by the relative delta

i.e. handle now stays where you grab it and moves proportionally as you drag.

## How Has This Been Tested?

1. Open the Card Browser
2. Drag the scrollbar handle from the middle of the handle
3. Verified the handle moves with your finger immediately (instead of requiring you to drag to the bottom first)

## Learning (optional, can help others)
The original upstream library code is available at:
https://github.com/pluscubed/recycler-fast-scroll/blob/3de76812553a77bfd25d3aea0a0af4d96516c3e3/library/src/main/java/com/pluscubed/recyclerfastscroll/RecyclerFastScroller.java

insight is that fast scrollers should use relative/delta-based movement rather than absolute positioning, so the handle "sticks" to where the user grabs it.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/ui/RecyclerFastScroller.kt [hunk 1]
```diff
@@ -216,16 +216,18 @@ class RecyclerFastScroller
                                 val newHandlePressedYAdjustedToInitial =
                                     newHandlePressedY + (initialBarHeight - barHeight)
 
-                                val scrollProportion = newHandlePressedYAdjustedToInitial / initialBarHeight
-                                val targetPosition =
-                                    (scrollProportion * recyclerViewAdapter.itemCount)
-                                        .toInt()
-                                        .coerceIn(0, recyclerViewAdapter.itemCount - 1)
+                                val deltaPressedYFromLastAdjustedToInitial =
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/ui/RecyclerFastScroller.kt]: Please comment this a little more, it works, but the logic could do with clarification

Comment (xenonnn4w) [reply AnkiDroid/src/main/java/com/ichi2/anki/ui/RecyclerFastScroller.kt]: Got that, for me was kind of easy due to high school physics; a lot of integration still in my major 😭 . Will update both commit message and code.

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/ui/RecyclerFastScroller.kt]: It's been a while since University, thanks for your patience :D
