### PR TITLE
Fixes #8294 Fixed select many wrt configuration changes

### LINKED ISSUE #8294: [Bug] Select Many not consistent with configuration changes
###### Reproduction Steps
As stated here https://github.com/ankidroid/Anki-Android/pull/8278#discussion_r598113467 the variables are not saved and restored. Its a special case of #3654

###### Expected Result
Select many feature should work fine on changing orientation.

###### Actual Result
It's not storing the last selected position so causing inconsistencies.

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by mrudultora**
## Purpose / Description
Select many was not working fine on changing orientation.

## Fixes
Fixes #8294 

## Approach
Saved and restored variables `mLastSelectedPosition` and `mInMultiSelectMode`

## How Has This Been Tested?
Tested on real device (Redmi Note 7S and API29).

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by kartikeysaran — APPROVED** [review]
Lgtm !

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java [hunk 1]
```diff
@@ -1456,6 +1456,8 @@ public void onSaveInstanceState(Bundle savedInstanceState) {
         savedInstanceState.putInt("mOldCardTopOffset", mOldCardTopOffset);
         savedInstanceState.putBoolean("mShouldRestoreScroll", mShouldRestoreScroll);
         savedInstanceState.putBoolean("mPostAutoScroll", mPostAutoScroll);
+        savedInstanceState.putInt("mLastSelectedPosition", mLastSelectedPosition);
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java:1459]: It would be nice if you could remove replace strings by `private finale String` variables. That's unrelated to this PR of course, but would decrease the risk of typos in string in general

**Review by Arthur-Milchior — APPROVED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java (hunk 1 above)
Comment (Arthur-Milchior) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java:1459]: If you have selected multiple cards and change the screen orientation, does selection remain ? I don't see how it could be the case since the list of cards can be saved in this function

Comment (mrudultora) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java:1459]: The selection remains intact on changing orientation.

Comment (mrudultora) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java:1459]: > It would be nice if you could remove replace strings by `private finale String` variables. That's unrelated to this PR of course, but would decrease the risk of typos in string in general
> 

Should I do this? Actually, previously all the strings were used directly. So, should I make the changes for every string ?

Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java:1459]: Please don't, this will conflict with https://github.com/ankidroid/Anki-Android/pull/8066

**Review by david-allison-1 — APPROVED** [review]
Looks good to me!

**Review by mikehardy — APPROVED** [review]
Nice! Thank you
