### PR TITLE
fix: Navigate Up versus Close

### LINKED ISSUE #17609: [BUG]:  Navigate Up versus Close
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Click on the + icon.
2. Click on "get shared decks"
3. Click on any of the links that appear.
4. Click close button.

### Expected behaviour

It's either the icon or the behaviour that is not wrong. The cross mark isn't closing the screen but only going back.

### Debug info

```text
2.21 alpha2
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by Prince-kushwaha**
## Fixes
* Fixes #17609 

## How Has This Been Tested?

Physical Device

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by lukstbit — CHANGES_REQUESTED** [review]
This breaks the home icon.
The changes required for fixing the issue:

- replace the current (x) with the platform UP arrow icon (<-) so we match the platform UI
- on clicking that icon we should leave the screen completely
- don't break the home toolbar icon

**Review by lukstbit — APPROVED** [review]
Thanks!

File: AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt [hunk 1]
```diff
@@ -285,6 +282,8 @@ class SharedDecksActivity : AnkiActivity() {
         if (item.itemId == R.id.home) {
             shouldHistoryBeCleared = true
             webView.loadUrl(resources.getString(R.string.shared_decks_url))
+        } else if (item.itemId == android.R.id.home) {
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt:285]: I feel like this needs an explanation - as someone unfamiliar with this area of code, I'm unclear how-and-why `R.id.home` is different from `android.R.id.home`

But it appears that difference is critical to this PR

Could you add a comment on line `item.itemId == R.id.home` explaining what that item is, then a comment on the second one explaining what that is and why it's different from the first one?

I recognize this may be simple and well-understood to anyone else but for me at least, I need the comments to understand it

**Review by mikehardy — CHANGES_REQUESTED** [review]
request for comments explaining

File: AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt (hunk 1 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt:285]: For reference: 

`home` is our icon with the "home page" which takes you back to the main deck search page

`android.home` is the standard 'arrow' button taking you to the previous screen

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt:285]: that sounds like it could be the reference I'm looking for in the comment so it is a lot less of a "hmm?" for anyone that sees it

Comment (Prince-kushwaha) [reply AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksActivity.kt]: // R.id.home refers to a custom 'home' menu item defined in your app resources (res/menu/...)
 // android.R.id.home refers to the system-provided "up" button in the app toolbar
.

**Review by mikehardy — APPROVED** [review]
Thanks for adding the comment - didn't mean to be picky it was just subtle and I thought a comment addition would be really easy + help in the future. I appreciate it anyway

Cheers

**Comment by mikehardy** [comment]
Thought this was pickable for a 2.20.1 release and gave it a shot but it relies on other changes already being in place from #17579 and those don't pick cleanly at all, so no cherry-pick for this one
