### PR TITLE
fix(deck-options): close any open modals on back button

### LINKED ISSUE #17196: Deck Options: "Back" should close popup windows
The hardware back button should close the popup, rather than the settings

Unsure about the behavior of the app bar button

Image

### PR DESCRIPTION
**Pull request by david-allison**
Previously the back button only handled navigation to the manual

Now it also closes any modals which are open and requires another back press to close

* Fixes #17196

## Approach
* Add a JavaScriptInterface
* Test for Bootstrap open & close commands

## How Has This Been Tested?

* Pressing 'back' with no modal open -> "save changes"
* Pressing 'back' with modal open -> modal closes

⚠️ I was unable to test on API 23 due to an outdated WebView

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
Nifty - lots of cross-layer fun here - this works for me

File: AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt [hunk 1]
```diff
@@ -60,9 +62,61 @@ class DeckOptions : PageFragment() {
...
+    }
+
+    override fun onWebViewCreated(webView: WebView) {
+        // addJavascriptInterface needs to happen before loadUrl
+        webView.addJavascriptInterface(ModalJavaScriptInterfaceListener(), "ankidroid")
+        Timber.d("Added JS Interface: 'ankidroid")
+    }
+
     override fun onCreateWebViewClient(savedInstanceState: Bundle?): PageWebViewClient {
         requireActivity().onBackPressedDispatcher.addCallback(this, onBackSaveCallback)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/pages/DeckOptions.kt:117]: On second thought: this needs further testing: 

* What happens if a user is on an external page linked from a modal

**Comment by david-allison** [comment]
* If a user is on a manual page
  * The modal is closed and the callback should be disabled
  * the back button should take priority going back in the browser

**Review by lukstbit — APPROVED** [review]
