### PR TITLE
Resolves accessiblity issue in toolbar hamburger icon

### LINKED ISSUE #7570: Make use of unused Navigation Drawer String
`02-string.xml`: `drawer_open` and `drawer_open`

Make use of these for content descriptions on the hamburger button to open and close the drawer.

### LINKED ISSUE #10786: [Bug] The name of "≡" button isn't correct
Thanks to developers.

###### Reproduction Steps
1. Open any of `Decks` / `Card browser` / `Statistics` / `Study` screens
2. Long press `≡` button
 

###### Expected Result
A string which expresses the button's feature, for example, "Open drawer", gets shown. 

###### Actual Result
The string, "Navigate up", gets shown. It doesn't express the button's feature.
image

###### Sidenote
- The string, "Navigate up", is originally used for the following button.
image
- The string has probably been lost on Crowdin for some reason. 

###### Debug info
```
AnkiDroid Version = 2.16alpha56

Android Version = 9

Manufacturer = OPPO

Model = CPH1983

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 9; CPH1983 Build/PKQ1.190519.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.73 Mobile Safari/537.36

ACRA UUID = 69410480-0b9c-401f-ae8d-94da0f29c9dc

Scheduler = std2

Crash Reports Enabled = true


DatabaseV2 Enabled = true
```
###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by Propo41**
## Purpose / Description
- resolves #10786 
- Added a test to check if the invertCode function works by correctly inverting the color codes from white to black

## Fixes
- fixes #10786 
- fixes #7570

[Before]
162765578-906445ab-627f-4312-a65e-f70974ffb722

[After]
277826953_1160124364762908_4251923265400219823_n

## Approach
It adds the content description of the hamburger icon by adding the descriptions to the ActionBarToggle initialization

## How Has This Been Tested?
Manual testing by long pressing on the hamburger icon.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java [hunk 1]
```diff
@@ -57,6 +57,7 @@
 
 import androidx.drawerlayout.widget.DrawerLayout;
 import timber.log.Timber;
+
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java:60]: could you revert these unnecessary line changes, they add noise to the diff

File: AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java [hunk 2]
```diff
@@ -106,15 +108,21 @@ public void setContentView(@LayoutRes int layoutResID) {
         setContentView(closableDrawerLayout);
     }
 
-    private @LayoutRes int getNavigationDrawerLayout() {
+
+    private @LayoutRes
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java:112]: ditto

**Review by david-allison — CHANGES_REQUESTED** [review]
Thanks!!!

Some changes requested to ensure the commit only. shows relevant changes

CI fails:

```
> Task :AnkiDroid:lintPlayDebug FAILED
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/02-strings.xml:27: Error: Duplicate string value "Open drawer", used in ankidroid_navigation_drawer_open, drawer_open [DuplicateCrowdInStrings from com.ichi2.anki.lint]
    <string tools:ignore="UnusedResources" name="drawer_open">Open drawer</string>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/02-strings.xml:278: Duplicates value in drawer_open. Add a comment attribute on both strings to explain this duplication
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/02-strings.xml:28: Error: Duplicate string value "Close drawer", used in ankidroid_navigation_drawer_close, drawer_close [DuplicateCrowdInStrings from com.ichi2.anki.lint]
    <string tools:ignore="UnusedResources" name="drawer_close">Close drawer</string>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/02-strings.xml:279: Duplicates value in drawer_close. Add a comment attribute on both strings to explain this duplication
2 errors, 0 warnings
```

File: AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java (hunk 1 above)
Comment (Propo41) [reply AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java:60]: on it

**Comment by Propo41** [comment]
@david-allison hey, can you shed some light on why the checks are failing? I removed the unnecessary indents.

File: AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java [hunk 3]
```diff
@@ -13,7 +13,7 @@
  * You should have received a copy of the GNU General Public License along with         *
  * this program.  If not, see <http://www.gnu.org/licenses/>.                           *
  ****************************************************************************************/
-package com.ichi2.anki;
+package com.ichi2.anki;
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java:16]: revert: spacing change

File: AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java [hunk 4]
```diff
@@ -139,7 +139,7 @@ protected void initNavigationDrawer(View mainView) {
         }
         // ActionBarDrawerToggle ties together the the proper interactions
         // between the sliding drawer and the action bar app icon
-        mDrawerToggle = new ActionBarDrawerToggle(this, mDrawerLayout, 0, 0) {
+        mDrawerToggle = new ActionBarDrawerToggle(this, mDrawerLayout, R.string.drawer_open, R.string.drawer_close) {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java:142]: This is great!

File: AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java [hunk 5]
```diff
@@ -180,7 +180,7 @@ public static void enablePostShortcut(@NonNull Context context) {
         if (Build.VERSION.SDK_INT < Build.VERSION_CODES.N_MR1) {
             return;
         }
-        
+
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java:183]: spacing change: revert

File: AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java [hunk 6]
```diff
@@ -493,4 +493,4 @@ public boolean onKeyDown(int keyCode, KeyEvent event) {
 
         return super.onKeyDown(keyCode, event);
     }
-}
+}
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java:496]: spacing change: revert

File: AnkiDroid/src/test/java/com/ichi2/themes/HtmlColorsTest.kt [hunk 7]
```diff
@@ -28,4 +28,9 @@ class HtmlColorsTest {
         // An invalid color code should not be changed.
         assertThat(invertColors(" color:DLE "), `is`(" color:DLE "))
     }
+    @Test
+    fun testCorrectColorInversion() {
```
Comment (david-allison) [inline AnkiDroid/src/test/java/com/ichi2/themes/HtmlColorsTest.kt:32]: Split this off into another branch, aim to keep a PR to one "topic"

File: AnkiDroid/src/main/res/values/02-strings.xml [hunk 8]
```diff
@@ -24,8 +24,8 @@
 
     <!-- #7570: We should use these strings again -->
     <!-- Navigation drawer strings -->
-    <string tools:ignore="UnusedResources" name="drawer_open">Open drawer</string>
-    <string tools:ignore="UnusedResources" name="drawer_close">Close drawer</string>
+    <string name="drawer_open">Open drawer</string>
+    <string name="drawer_close">Close drawer</string>
```
Comment (david-allison) [inline AnkiDroid/src/main/res/values/02-strings.xml:28]: Awesome!

**Review by david-allison — CHANGES_REQUESTED** [review]
Functionality looks great!

Few refactorings and it can go in.

The spacing changes are much less of a problem in our Kotlin code, one of the reasons we migrated.

File: AnkiDroid/src/test/java/com/ichi2/themes/HtmlColorsTest.kt (hunk 7 above)
Comment (Propo41) [reply AnkiDroid/src/test/java/com/ichi2/themes/HtmlColorsTest.kt]: alright

File: AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java (hunk 6 above)
Comment (Propo41) [reply AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java:496]: I really can't seem to find how to revert this.

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java:496]: @Propo41 What OS are you using?

@mikehardy any advice here? Seems like a line ending issue. Maybe `core.autocrlf` related, but I'm lost

Comment (Propo41) [reply AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java:496]: I'm using windows.

Comment (Propo41) [reply AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java:496]: Should I fork the repo again and do the changes from scratch and make a new PR instead?

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java:496]: nono, this should be fixable. It's incredibly rare to need to send in a new PR, let alone re-fork the repo.

I'd bring this to Discord to see if anyone has suggestions. I didn't have this issue on my Windows PC

Comment (Propo41) [reply AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java:496]: > nono, this should be fixable. It's incredibly rare to need to send in a new PR, let alone re-fork the repo.
> 
> I'd bring this to Discord to see if anyone has suggestions. I didn't have this issue on my Windows PC

Alright. But I was hoping to proceed with the GSOC proposal this season, and it would really help if I could do the merge process quickly.

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java:496]: No ideas sorry I would need to know the exact steps taken to reach this state and the exact steps of any experiments. I personally detest working on windows for code specifically because of CRLF/LF issues for this reason - it's so hard.

Comment (Propo41) [reply AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java:496]: > No ideas sorry I would need to know the exact steps taken to reach this state and the exact steps of any experiments. I personally detest working on windows for code specifically because of CRLF/LF issues for this reason - it's so hard.

I guess creating a new PR  and starting fresh would be a quicker approach? Even if I could fix this, I would have to squash a whole list of commits!

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java:496]: To maintain perspective: Squashing a whole list of commits should be considered zero cost on your part. Interactive rebase, squashing etc: your goal should be to get so good at doing those things that it has zero cost. I don't even consider those things in my thought process when I am deciding how to proceed with things.

So, squash away. No problem.

The problem is perhaps related to checkout of the file etc. I do not ever consider creating a new PR (based on my above perspective) but you might need to do a fresh local checkout with the autocrlf idea David mentioned above. You may need to use your favorite package manager (like choco) to install dos2unix or similar and play with running it through that. I don't know...

Comment (Propo41) [reply AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java:496]: Alright thanks! I'll give it a try

File: AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java (hunk 5 above)
Comment (Propo41) [reply AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java]: fixed

File: AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java (hunk 6 above)
Comment (Propo41) [reply AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java]: @david-allison The line ending issue has been fixed. Never gonna use windows again for git! Is it mandatory to squash the commits? I'm having some serious difficulty in the squashing process. After I did the squash in vim, all the commits (including others) had my name on it @.@

**Review by david-allison — APPROVED** [review]
Looks great, thanks!

File: AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java (hunk 6 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java]: We can do it, but you should learn.

Inside Android Studio:

* Select all the commits in the `Git` window
* Right click -> Squash

OR:

* Select the first commit to squash
* Right click - interactively rebase
* select all the commits to squash

Inside git:

`git rebase -i HEAD~5` where 5 is the number of commits that you MAY want to squash.
`git commit --amend` if you want to squash instead of make a new commit
`git push --force-with-lease` - if you've changed commits and want to update your PR 

You should learn (especially as it's a vital skill), and will need to for larger contributions to the repo, but for the first few contributions, it's fine to spend time gaining confidence with other things.

Comment (Propo41) [reply AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java]: Thanks, I'll play around with this in a dummy repo to understand how it works.

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java]: There's a lot of people that would strongly disagree, but the IntelliJ (Android Studio) GUI tools for rebasing are great and give a good mental model of how the process works

Comment (Propo41) [reply AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java]: Yeah seems like it gives a better visualization!

**Review by mikehardy — APPROVED** [review]
Nice! Thanks a bunch for this, we can *always* use accessibility help
