### PR TITLE
Various CardTemplateEditor fixes

### LINKED ISSUE #5011: State handling crash between card browser / note editor / template editor
I've seen this show up via ACRA, and the google play console release robot army caught it with video this time so I could figure it out.

###### Reproduction Steps

1. Open the card browser (it's empty in their tests, and they play with searches sometimes but the search was cleared)
2. Click + to add a card, enter text in front and back, template should be Basic
3. click the button bar that says "Card 1" to open the template editor
4. Click the options menu and select add to add a Card to the template, and you can mess with the template or not, but don't save - preview or not but don't save - then click the back button and agree it's okay to lose your progress
5. The Card button bar should say "Cards: Card 1 Card 2" now, but you never saved the second template
6. Click save to add the card, then click back to go back to the browser and it should crash with a JSONException string out of bounds

###### Expected Result

If you don't save the template the unsaved work should go away, you should have only Card 1 and the browser should work fine

###### Actual Result

Crash. I can reproduce this locally.

https://play.google.com/apps/publish/?account=5338425030304417978#PreLaunchReportPlace:p=com.ichi2.anki&appid=4973711737547064258&plrtab=CRASH&plrvc=20900140

FATAL EXCEPTION: AsyncTask #4
Process: com.ichi2.anki, PID: 12740
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:353)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.RuntimeException: org.json.JSONException: Index 1 out of range [0..1)
	at com.ichi2.libanki.Card.template(Card.java:342)
	at com.ichi2.libanki.Card._getQA(Card.java:290)
	at com.ichi2.anki.CardBrowser.updateSearchItemQA(CardBrowser.java:1164)
	at com.ichi2.async.DeckTask.doInBackgroundSearchCards(DeckTask.java:818)
	at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:262)
	at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:69)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more
Caused by: org.json.JSONException: Index 1 out of range [0..1)
	at org.json.JSONArray.get(JSONArray.java:293)
	at org.json.JSONArray.getJSONObject(JSONArray.java:521)
	at com.ichi2.libanki.Card.template(Card.java:337)
	... 11 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.get(ArrayList.java:437)
	at org.json.JSONArray.get(JSONArray.java:287)
	... 13 more

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

### PR DESCRIPTION
**Pull request by mikehardy**
## Purpose / Description
These are various CardTemplateEditor fixes, including one crash bug on returning from CardTemplateEditor if the user deleted the template that generated the card the user was on in NoteEditor.

## Fixes
Does not fix the main CardTemplateEditor problem, but that fix will be based off this

## Approach

1.  add better message-passing communication between the three of NoteEditor, DeckTask, and CardTemplateEditor - this lets them communicate the current card and the action being taken amongst themselves
1.  from NoteEditor, when you go to CardTemplateEditor, it sends the current card now so the right tab is focused (improvement)
1.  in NoteEditor, if we return from a template add, we just reload and go. If we come from a template delete we see if it was the card we were on and if it was we snackbar a notice and exit back to CardBrowser with a reload triggered
1.  It also handles the hardware back button in CardTemplateEditor but at this point that's the smallest part.

*This includes a new string in 01-core.xml (right now)*

## How Has This Been Tested?

Extensive emulator use on all the use cases here, plus a full emulator (API15-28) fleet test on automated tests including UI tests. Seems to work

## Learning (optional, can help others)

It's more clear to me now that Intents (and our TaskData) forward and backward either async or not are just fancy arguments to disconnected method calls.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by mikehardy** [comment]
I just self-reviewed this again and I couldn't see anything to change, would love if one of you @timrae  @eginhard had time to look into it - the "return if template deleted" style we agreed on seems to work well and the code is much easier to think about

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java [hunk 1]
```diff
@@ -1123,13 +1129,41 @@ else if (fieldEditText.hasFocus()) {
...
+                    mEditorNote.reloadModel();
+
+                    switch (resultType) {
+                        case CardTemplateEditor.CARD_TEMPLATE_ADDED:
+                            // rebuild the model post-template-edit so we get the correct number of cards
+                            Timber.d("onActivityResult() template edit successful card template add");
+                            updateCards(mEditorNote.model());
+                            break;
+                        case CardTemplateEditor.CARD_TEMPLATE_DELETED:
+                            Timber.d("onActivityResult() template edit successful card template delete");
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java]: Can you just do `mEditorNote.cards().contains(card)`? I'm unsure whether or not they'll have the same hash code, but I suspect they do, or if not we could probably override the hash code to give the card id.

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java [hunk 2]
```diff
@@ -1123,13 +1129,41 @@ else if (fieldEditText.hasFocus()) {
...
-                if (resultCode == RESULT_OK) {
+                String resultType = data.getStringExtra("result_type");
+                if ((resultCode == RESULT_OK) && (resultType != null)) {
+
+                    // Something changed in the model - reload it and update ourselves
                     mReloadRequired = true;
+                    mEditorNote.reloadModel();
+
+                    switch (resultType) {
+                        case CardTemplateEditor.CARD_TEMPLATE_ADDED:
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java]: It doesn't seem these return codes provide much value, since `!currentCardStillExists` implies `CARD_TEMPLATE_DELETED`...?

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java [hunk 3]
```diff
@@ -1123,13 +1129,41 @@ else if (fieldEditText.hasFocus()) {
...
+                            // rebuild the model post-template-edit so we get the correct number of cards
+                            Timber.d("onActivityResult() template edit successful card template add");
+                            updateCards(mEditorNote.model());
+                            break;
+                        case CardTemplateEditor.CARD_TEMPLATE_DELETED:
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java]: Missing brace again

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java]: sorry - will fix the braces on the switch statements

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java [hunk 4]
```diff
@@ -244,6 +269,21 @@ public void onPageScrollStateChanged(final int position) {
         }
         // Close collection opening dialog if needed
         Timber.i("CardTemplateEditor:: Card template editor successfully started for model id %d", mModelId);
+
+        // Set the tab to the current card if a card id was provided
+        if (mCardId != -1L) {
```
[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java]: best reason "why not" is I'm still getting the data model fixed in my head, and the mix of deck->conf->models and cards = note+model etc not being second nature yet leads to convoluted thinking. This helps straighten it out though and I'm getting there. this and the notes below all seem right on, I'll go through it again with these in mind and re-push. Thanks for the review!

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java (hunk 1 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java]: I implemented .equals using .getId() and .hashCode() with the recommended long -> int mapping and this works well

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java (hunk 2 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java]: no, as I boiled it down incrementally the return codes reduced easily and removed the need for the associated intent creation/setting that passed the message here. Still needed part of the message passing through deck task as the templates were modified in the background so we could exit card template editor on template delete, but one new message pass is better than two

**Comment by mikehardy** [comment]
A lot smaller diff now, and fixed a bonus error I just noticed where if you were in card template editor on card4, then deleted card2 and card3, we'd array overrun trying to figure out which card number to underline. A card reload on template edit return when the current card still exists fixes that. @timrae ready one more time :-). Thanks for your patience

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java [hunk 5]
```diff
@@ -94,13 +98,24 @@ public void onProgressUpdate(DeckTask.TaskData... values) {
...
+                    }
+                    case CARD_TEMPLATE_DELETED:
+                        setResult(RESULT_OK);
+                        finishWithoutAnimation();
+                        break;
+                    default:
+                        break;
                 }
-            } else if (result.getString() != null && result.getString().equals("removeTemplateFailed")) {
+            } else if (CARD_TEMPLATE_DELETED.equals(result.getString())) {
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java]: This line of the diff looks suspicious (failed template removal code path becomes successful template removal code path), can you please double check and explain what's going on?

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java [hunk 6]
```diff
@@ -65,12 +65,16 @@
...
+
+    public static final String CARD_TEMPLATE_ADDED = "CARD_TEMPLATE_ADDED";
+    public static final String CARD_TEMPLATE_DELETED = "CARD_TEMPLATE_DELETED";
     private TemplatePagerAdapter mTemplateAdapter;
     private JSONObject mModelBackup = null;
     private ViewPager mViewPager;
     private SlidingTabLayout mSlidingTabLayout;
     private long mModelId;
     private long mNoteId;
+    private int mOrdId;
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java]: It's kind of unnecessary to keep `mOrdId` as a member variable but I guess it  doesn't hurt that much

**Comment by timrae** [comment]
I can't find my comment on the commit so posting it directly into the thread again

>> We don't need to exit the template editor when a template is deleted, we just need to close the note editor when a template is deleted, right?

> That was the first 2 attempts to patch this, but because adding and editing are speculatively persisted staying in the template editor is either inconsistent UI on back button taps with non delete changes or the ability to resurrect deleted templates - and then all the corner cases the earlier patch attempt failed on. Just exiting was what we came up with after that. Or am I misunderstanding?

I was just intending to saying that we should exit the note editor when the current edited card no longer exists without saying anything about the card template editor. What would be required to keep the template editor open after a deletion and why?

**Comment by timrae** [comment]
I can't find my comment on the commit so posting it directly into the thread again

>> We don't need to exit the template editor when a template is deleted, we just need to close the note editor when a template is deleted, right?

> That was the first 2 attempts to patch this, but because adding and editing are speculatively persisted staying in the template editor is either inconsistent UI on back button taps with non delete changes or the ability to resurrect deleted templates - and then all the corner cases the earlier patch attempt failed on. Just exiting was what we came up with after that. Or am I misunderstanding?

I was just intending to saying that we should exit the note editor when the current edited card no longer exists without saying anything about the card template editor. What would be required to keep the template editor open after a deletion and why?

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java (hunk 5 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java]: Couldn't help looking at this. They both handle the same case "delete note failed". This is if the result was false (so something failed), and it was template delete. The switch on L101 is closed by L117, so this is no longer in the success path.

Comment (timrae) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java]: Ah right I see, I don't like the past tense in the label though... I might prefer the old explicit way of passing each case separately (i.e. `removeTemplateFailed`), but if there is a good reason to change then I think dropping the past tense and using `CARD_TEMPLATE_DELETE` and `CARD_TEMPLATE_ADD` would look  much more readable in this fail path.

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java (hunk 6 above)
Comment (timrae) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java]: comomete? lol

**Comment by timrae** [comment]
>> I was just saying that we should close the note editor when the current card no longer exists, I didn't intend to say anything about the card template editor. What exactly would be required to keep the template editor open after card deletion, and why? I think that would definitely be too jarring of a UX.

> Maintain the ability to restore the deleted template and reverse all side-effects of the speculatively-persisted delete in case the user elects to discard changes on exit, while meeting all Android lifecycle requirements.

It sounds like you're conflating "keeping the card template editor open" with "providing undo functionality". Anki Desktop does provide undo functionality for this operation, so I think that should be the long-term goal (and shouldn't be much harder than providing undo for card browser multi-select deletes I don't think?), but as a first step for the hotfix, perhaps we could just disable the back button to force users to hit the check button after a deletion if undo is currently broken.

> You opt to delete a template, it gives you a stern dialog confirmation (this is key to me, it feels more serious than most of our exit dialogs even), and you see the NoteEditor with a card button bar that has one less card (if current card exists), or a toast explaining why then a card browser in the correct state

I think exiting the note editor is still the correct action even if we keep the template editor open, for the reasons I previously mentioned

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java (hunk 6 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java]: complete. typing on mobile is fun

**Comment by mikehardy** [comment]
> It sounds like you're conflating "keeping the card template editor open" with "providing undo functionality". 

They are conflated in the current UI. And obviously I'm not sure how to de-couple them well.

> as a first step for the hotfix, perhaps we could just disable the back button to force users to hit the check button after a deletion if undo is currently broken.

Handling the combination of possible actions over time before we get to a delete is important. What to show?

- A message when you go to delete a template that other changes will no longer be discardable if they proceed? 
- A message that you can discard other things but not the template delete? 
- Disallow delete if there are other unsaved changes, then a message that template deletes are final and require a save after? 

All of this to me is more complex but the same as the delete being final and going back to note editor, although now that I think about it, I'm not handling the other model changes as I save and exit.

Maybe this:
- if you attempt to delete a template while the model has changed, you are directed to save the model first
- when you delete a template, you are told it is immediate and won't be discarded with other changes if you continue editing

I just checked the assertion it wouldn't be much harder than undo for multi-select delete and I disagree - the cases are different because the intent of the "undo" is reversed. If I understand correctly that lifecycle things may cause in-memory state to be lost, then the undo linked list in collection is unreliable. Losing a user-confirmed multi-select delete seems okay, but relying on it for unconfirmed changes in CardTemplateEditor seems different to me

If we do the above dialog sequence gating people to be fully saved before and after a template delete, then perhaps adding undo to template deletes using the current undo DeckTask is okay because the user expectation is different if it isn't possible.

I think the conflation is template edits, and template add/deletes - the more I've churned on this PR the less sense it makes to me as a UX

**Comment by timrae** [comment]
I finally got a chance to take a look through the code in order to understand the issue better. It seems the current simplistic approach of reverting to the model backup is incorrect for the case where card templates have been added or deleted, because it doesn't handle undoing of the cards which are generated / deleted.

It seems that in Anki Desktop, card template changes are undoable only after exiting the card template editor (via the undo menu), and in this case template add/delete operations are also supported. I think we could provide this same kind of undo functionality / UX via the Linked List (accepting that the list would disappear if the process is killed), but that's obviously a new feature separate from the current issue. 

Regardless of the above, I think the current "reset" option (the back arrow) is still useful for the case where no card templates have been added / deleted; we just need to make it clear to the user that those operations are handled separately.

One way that we could do that is perhaps as follows:

* If the user tries to add/delete a template while the model is different from the backup, we show them a message saying that they need to save the model before the operation can be completed (via pressing the tick button and exiting the editor)

* We show a clear message when adding/deleting templates that the operation cannot be undone

* After a model has been added/deleted, we update the model backup to the new model, so that pressing the back arrow exits without asking about unsaved changes. 

Due to the last point, the user could edit a template which they just added, but pressing the back arrow would revert the changes they made without actually deleting the new template. Similarly, the user could make changes to a template after deletion, but only the changes would be reverted (not the actual template deletion). This is a bit awkward, but I can't really see a better way right now, and at least it should work. Adding undo for template add/deletes might help to make it less awkward.

**Comment by timrae** [comment]
By the way, can you please separate the exiting of the note editor when the currently selected card no longer exists into a separate commit? This is a completely separate issue from the one we're currently discussing.

**Comment by mikehardy** [comment]
Thanks for looking into it deeply, your conclusions match mine which I think is a good sign - for my understanding anyway. Should help this not churn anymore for sure. I can re-shape this to match your suggestions and yes - I can separate things

**Comment by timrae** [comment]
> We show a clear message when adding/deleting templates that the operation cannot be undone

I guess the message is not really important when adding templates because the action is trivial to "undo" by deleting the template

**Comment by mikehardy** [comment]
> I guess the message is not really important when adding templates because the action is trivial to "undo" by deleting the template

Yes - it still conflates the types of things in my mental model - editing structure vs editing content, but add is much easier to tear down then delete so you can fudge it.

**Comment by timrae** [comment]
Thinking about the future direction of the UX a bit more, I think we need to eventually unify the "content change" undo with the "structural change" undo, which means moving the content change undo to the linked list (and giving up persistence over process kills). I think it's slightly sad to lose this but it's better than making a horribly awkward bifurcated undo system.

Given the above long term direction, it might make sense to just go straight to the linked list approach in this PR, and instead of updating the model backup when the user changes the structure, pop the content edit item off the linked list.

It's just an idea, feel free to disregard it if you prefer the original interim-approach I suggested the other day. Or let me know if my explanation isn't clear.

**Comment by mikehardy** [comment]
I think you're right if the intention is to perform like Anki Desktop and they allow structural undo. I haven't gotten to re-shaping this yet so it's probably the same amount of work, and hey...haven't working with the LinkedList/Undo, why not?

**Comment by timrae** [comment]
You never know, maybe as you get halfway into the implementation you decide to just go all the way and add structural change undos to the linked list in this PR ;)

**Comment by mikehardy** [comment]
Preparing to do this with undo capability, I just did a full inventory of Anki Desktop behavior:

- It assumes a change just by opening the editor: If you open the template editor at all - just open + close - it triggers availability of "undo card types" in Anki Desktop, with no differentiation between content or structural changes
- It advises card count changes with a popup: If you add or remove a card type in the template editor, it throws a dialog saying "This will create %d cards. Proceed?" or "Delete the 'Card %d' card type, and it's %d cards?" with the ordinal and card count interpolated, *then* it triggers the full sync warning as a second popup
- It does not speculatively persist template adds or deletes: If you add a card type in template editor and accept the warnings, then immediately delete the card type without removing, it says it will remove 0 cards, implying a template does not create them until you close...
- removing a card type (even if it is the current card type in the template editor) keeps you in the template editor but just switches to the next card type
- if you remove multiple card types at the same time in template editor, undo will undo all removes at the same time
- there is no "save" or anything, you just make a bunch of changes (confirming where necessary) then "close" or "x" out - and those two ways to close the template editor are equivalent
- Undo capability seems to be limited to one "card types" undo, if you change 2 things (add a card type then close + remove a card type then close) you can undo once only (and you'll be back to the state after adding the card type

So as I'm looking at it, what seems easy to agree on for behavior is:
1. All activity in template editor except close or back keeps the user in the template editor
1. any template / card type add or remove needs a popup showing how many cards you will create or delete, and the full sync warning, but it should not persist speculatively - it only persists the work as you close. This means save (and later undo) will be one big batch equivalent to the entire time you were in the template editor.
1. any open of the editor will be assumed to create a change of some sort, and on close the change will be persisted with an undo capability

What I'm not sure on is the undo - one-template-edit-only or multiple? I'm new to undo in AnkiDroid but it looks to me like Anki Desktop only ever supports one undo, while AnkiDroid supports a stack. So I suppose this is just a platform difference and I shouldn't try to limit template edit undo to once only in AnkiDroid.

**Comment by timrae** [comment]
> It does not speculatively persist template adds or deletes: If you add a card type in template editor and accept the warnings, then immediately delete the card type without removing, it says it will remove 0 cards, implying a template does not create them until you close...

That may be true for the generated / deleted cards (I'd need to check), but I don't think it's true for the non-structural changes. As far as I remember, "speculative persistence" is a necessary evil to support the preview feature. Also, the undo mechanism in desktop works completely differently from AnkiDroid, and desktop doesn't "have to" deal with the process being suddenly killed, so it's not as simple as just mimicking desktop.

**Comment by mikehardy** [comment]
> As far as I remember, "speculative persistence" is a necessary evil to support the preview feature

I suspect you are right, and know that's a sore point - it's the first thing I'm going to verify - if it's possible to send the Previewer an unsaved template for display somehow (while respecting there are limits to the sizes of things that can be sent in various directions). If I can crack that I try to move forward the way I want, if not, then I'll just have to deal with it

I suspected as much w.r.t. undo, that they were pretty different, but I think it was still useful to infer when desktop saved or not, and to see what it considered a unit of work

Nice to hear from you btw - if your timeline resembles what I remember your life must be nuts right now! Good luck

**Comment by mikehardy** [comment]
I confirmed using Intent.extras is not a valid solution because [Intent extras have tested out to have a ~500Kb limit](https://www.neotechsoftware.com/blog/android-intent-size-limit) and this data is unbounded

A shared preference is a common choice, but [single value in shared preference appears to be limited to 1.42MB](https://stackoverflow.com/a/43080588/9910298). That seems like a really big template, but it's user-supplied unbounded data

Options remaining to send non-database unbounded data are to store it in memory in the Application class, or save it to a file and return it.

Of those options, Application class storage has problems across app kill/restarts, so file storage is best, even though it needs cleanup in certain cases. I'm going to pursue this avenue

**Comment by mikehardy** [comment]
@timrae It seems difficult to carry a big commit queue in a single PR (and it's discouraged in our development guidelines). I'd like to have these bite-size commits considered for merge as an independent unit since they fix real issues by themselves, while the "real" template editor fix is in development on a branch I will base off this one.

**Comment by mikehardy** [comment]
@timrae I'm getting close to having the "real" CardTemplateEditor fix (which is a child branch of this) ready and it will depend on this. I tried to limit the changes here to the things that I believe were discussed and had consensus

**Comment by timrae** [comment]
You've tested this right?

**Comment by mikehardy** [comment]
> I think the "please select a different card part" is unnecessary

Okay - I can remove that bit - one line of logic delete and one string removal

> You've tested this right?

Yes a bunch, but it's been a while and you just made me paranoid so I pulled it again and ran through everything. It appeared to work fine for every path I tapped through on it.

In addition for the child branch with the "real" template editor fix I'm flexing all the new Robolectric unit test power we've merged in, and I'm testing the snot out of it so it's about to have full coverage and not just rely on my clicking

**Comment by mikehardy** [comment]
I just rebased, made the mentioned change (no snackbar when returning from NoteEditor if CardTemplateEditor deleted the card NoteEditor was working on) and re-pushed

**Comment by timrae** [comment]
I never intended to say don't show a snackbar, just that the last part of the string should be omitted

**Comment by mikehardy** [comment]
:bulb: - re-pushed with a string edit there vs a string delete

**Comment by timrae** [comment]
Can you edit the first commit instead of making a new one please?

**Comment by mikehardy** [comment]
I've only done the semi-magical rebase -i once before so I was avoiding it but you're right and it is/was good practice. @timrae re-pushed with edited 1st commit instead of 6th layered on

**Comment by mikehardy** [comment]
I agree and will redouble on the standards. I have to admit I'm pretty impressed with git having gone from zero on this year. I grew up on rcs at the start then quickly cvs but it lasted so long I stopped thinking of what it should be vs what it was. The -p arguments in particular are fantastic
