### PR TITLE
Load prefs (which uses Col) post-colIsOpen()

### LINKED ISSUE #5072: Crash on Reviewer start - NullPointerException restoring preferences
###### Reproduction Steps

1. Open AnkiDroid to the Reviewer directly (e.g., via a notification or widget)
2. 
3. 

###### Expected Result

Reviewer starts on current card for the deck and you proceed

###### Actual Result

Crash, seemingly because onCreate() in this pathway touches the Collection during restorePreferences() (since some preferences are stored in the Collection.conf), but collection loading is async and onCollectionLoaded() hasn't been called yet

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/9964d8fb-0eab-4d4a-a0f6-403350bbbf60

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.Reviewer}: java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONObject com.ichi2.libanki.Collection.getConf()' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2632)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2698)
at android.app.ActivityThread.access$1000(ActivityThread.java:195)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1533)
at android.os.Handler.dispatchMessage(Handler.java:111)
at android.os.Looper.loop(Looper.java:207)
at android.app.ActivityThread.main(ActivityThread.java:5856)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1026)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:887)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONObject com.ichi2.libanki.Collection.getConf()' on a null object reference
at com.ichi2.anki.AbstractFlashcardViewer.restorePreferences(AbstractFlashcardViewer.java:1803)
at com.ichi2.anki.Reviewer.restorePreferences(Reviewer.java:397)
at com.ichi2.anki.AbstractFlashcardViewer.onCreate(AbstractFlashcardViewer.java:856)
at android.app.Activity.performCreate(Activity.java:6285)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2585)
```

### PR DESCRIPTION
**Pull request by mikehardy**
## Purpose / Description
AbstractFlashcardViewer.restorePreferences() loads a few prefs from the collection but is called from onCreate() not onCollectionLoaded(), so it's touching the database on the UI thread

## Approach
I just moved the collection-touching items from the restorePreferences() call to a collection-prefs-specific method I call from onCollectionLoaded()

### CODE REVIEW

**Comment by timrae** [comment]
> restorePreferences() loads a few prefs from the collection but is called from onCreate() not onCollectionLoaded(), *so it's in a race with the async collection load*

First of all, Collection loading is always triggered at the end of `onCreate()`, so there's no race, they are run in series. The worst that could happen here should just be that we open the Collection on the UI thread and get an ANR.

Secondly, even if there were two threads simultaneously calling `CollectionHelper.getCol()`, it's `synchronized`, so one of the threads would acquire a mutex first, create the new Collection instance, and return. Next, the other thread would acquire the mutex, see that a Collection is already open, and return it without creating a new instance. This is how that class is designed anyway; feel free to make a thread safety unit test with a bunch of threads competing to open the Collection. The only way `null` should be returned is due to an inaccessible file.

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 1]
```diff
@@ -814,7 +814,6 @@ protected void onCreate(Bundle savedInstanceState) {
         Timber.d("onCreate()");
         // Create the extensions as early as possible, so that they can be offered events.
         mExtensions = new ReviewerExtRegistry(getBaseContext());
-        restorePreferences();
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java]: Now `mPrefFullscreenReview` is used before it's loaded

**Comment by mikehardy** [comment]
The control flow around this issue has changed a bit since collection load moved into the sub-classes but there is still this sequence:

- Reviewer.onCreate() calls
- super.onCreate() calls
- restorePreferences() calls
- getCol().getConf() and it is before
- Reviewer.onCreate() calls startLoadingCollection()

So any AbstractFlashcardViewer Activity will load the collection in getCol().getConf() as part of onCreate(), yes, and that should be avoided.

However that leaves the problem if the null return from getCol() in restorePreferences(). And I agree it's not racy, and I agree it should have loaded fine so this doesn't actually address #5072 

I think this is another case similar to #5074 prefs crash where there is an unexpected path to getCol() use that didn't go through the DeckPicker startup where directory validity and everything were checked, since exceptions rooted in that are the only way getCol() returns null, right?

If I were to generalize I'd say that the app seems to expect it will start from DeckPicker, but there are other possible entry points, including this one.

Maybe the startup code that's in DeckPicker to do collection protection etc should be in AnkiDroidApp so even if you start the Reviewer directly, we'll be protected?

**Comment by timrae** [comment]
Shouldn't we be addressing the corruption issue first and getting the hotfix out before the November deadline?

**Comment by mikehardy** [comment]
Yep - the actual fix is a trivial bit of code (I think?) but if you want it to be cherry-pickable I'll need to separate it to a specific commit from #5103 

It's right here:
https://github.com/ankidroid/Anki-Android/pull/5103/files#diff-f9eb49024e00e573fa669ba5539ae510R1753

**Comment by mikehardy** [comment]
And I will fix template editor next - they were in a queue in my mind and honestly I needed a break from that thing!

**Comment by timrae** [comment]
It seems the deadline was November 1, so we already missed our chance to put out a hotfix it seems

**Comment by mikehardy** [comment]
Well, that's not expected and makes me a bit sad, but according to google play console, we have 55 installs on active devices for those APIs. Versus just under a million in total. Can't win them all?

**Comment by mikehardy** [comment]
@timrae this is re-ready for re-view, pretty trivial change at this point

**Comment by timrae** [comment]
I thought I had already merged this actually, I must be going senile

**Comment by mikehardy** [comment]
I wanna thumbs up the merge but can't have that mixed in with senility ;-). Thanks Tim
