### PR TITLE
fix(CardBrowser): Wrong deck selected on open

### LINKED ISSUE #15072: [BUG]: Browser shows cards from all decks, not only those from selected deck
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

- On the decks page, select a deck.
- Open the Card Browser.
- Press the back button to return to the Decks page.
- Reopen the Card Browser.

### Expected behaviour

The browser shows the cards only from the selected deck.

### Actual behaviour

The browser shows cards from all decks. However, it still shows the name of the selected deck at the top.

Note that the behaviour is correct when first opening the browser after selecting the deck, but not in the subsequent attempts.

### Debug info

```text
2.17 alpha 13

Issue persists in alpha 14
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison**
We weren't calling searchCards() after viewModel.launch

* Fixes #15072

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt [hunk 1]
```diff
@@ -503,6 +503,11 @@ open class CardBrowser :
                 invalidateOptionsMenu()
             }
             .launchIn(lifecycleScope)
+
+        viewModel.initCompletedFlow
+            .flowWithLifecycle(lifecycle, Lifecycle.State.STARTED)
+            .onEach { searchCards() }
```
Comment (lukstbit) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt:509]: This does a double search(for false the initial value + for true when initialization is completed), shouldn't the search be done only when the value is true?

**Review by lukstbit — CHANGES_REQUESTED** [review]

**Review by mikehardy — APPROVED** [review]
ok - lgtm

**Review by lukstbit — APPROVED** [review]
