### PR TITLE
Fixes #8287 Fail CI if Analytics string constants are changed

### LINKED ISSUE #8287: Fail CI if Analytics string constants are changed
If analytics strings/categories are changed, then we cannot compare them between versions.

The likely issue here is some usages of `.getClassName()`

Context:

If this goes in, we should add an issue to enforce this via a lint check 

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/pull/8257#discussion_r596467326_

### PR DESCRIPTION
**Pull request by mrudultora**
## Purpose / Description
Strings used in analytics must not change. So, CI must be failed if changes are made to those.

## Fixes
Fixes #8287 

## Approach
Added a custom annotation `@AnalyticsConstant` and fetched the fields via reflection and checked them with hardcoded fields in the unit test.

## How Has This Been Tested?
Ran the test in Android Studio.

## Learning (optional, can help others)
• Working with Annotations.
• Working with Java Reflection.
• If anyone wants to learn about Parameterized test then this PR would be helpful.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+
+    @Test
+    public void checkAnalyticsString() {
+        UsageAnalytics.Actions actions = new UsageAnalytics.Actions();
+        Field[] field;
+        field = actions.getClass().getDeclaredFields();
+        for (int i = 0; i < field.length; i++) {
+            if (field[i].isAnnotationPresent(AnalyticsConstant.class)) {
+                try {
+                    assertThat(field[i].get(actions), is(listOfConstantFields.get(i)));
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java:71]: This enforces an order, which I don't think is intended

File: AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+        listOfConstantFields.add("Opened Discord");
+        listOfConstantFields.add("Opened Facebook");
+        listOfConstantFields.add("Opened Twitter");
+        listOfConstantFields.add("Exception Report");
+        listOfConstantFields.add("aedict");
+        listOfConstantFields.add("leo");
+        listOfConstantFields.add("colordict");
+        listOfConstantFields.add("fora");
+        listOfConstantFields.add("nciku");
+        listOfConstantFields.add("eijiro");
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java:59]: I don't think we get a failure if a new constant is added without an entry here

File: AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java [hunk 3]
```diff
@@ -0,0 +1,78 @@
...
+    }
+
+
+    @Test
+    public void checkAnalyticsString() {
+        UsageAnalytics.Actions actions = new UsageAnalytics.Actions();
+        Field[] field;
+        field = actions.getClass().getDeclaredFields();
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java:67]: It might be best to globally check for usages of the annotation. I think I've added a helper method to do this

**Review by david-allison-1 — COMMENTED** [review]
Thanks! Little refining, then the app is much safer to develop for

File: AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java (hunk 2 above)
Comment (mrudultora) [reply AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java:59]: We get an exception **ArrayIndexOutOfBoundsException**.

File: AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (mrudultora) [reply AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java:71]: So for parameterized test per constant should I fetch each field with directly using a name ?

Comment (mrudultora) [reply AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java:71]: Ya that's true.

File: AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java (hunk 3 above)
Comment (mrudultora) [reply AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java:67]: Could you add that method or helper class here?

Comment (david-allison-1) [reply AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java:67]: Appears I was mistaken, apologies

File: AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (david-allison-1) [reply AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java:71]: For paramaterized tests: reflect and return the list of strings as the parameter, then check against the array in the test

**Comment by mikehardy** [comment]
No pressure - I'm just scanning the queue and labeled this as waiting for feedback which is our label for "PR author has something to do before reviewers scan again"

**Comment by mrudultora** [comment]
@david-allison-1 Changes done !

• Added two nested classes (as I wanted one of them to be parameterized and other to be non-parameterized).
• Added a javadoc to explain the need of implemeting in this way.
• Works in every case (if new values added or if the current values changed).

File: AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java [hunk 4]
```diff
@@ -0,0 +1,124 @@
...
+            listOfConstantFields.add("fora");
+            listOfConstantFields.add("nciku");
+            listOfConstantFields.add("eijiro");
+            return listOfConstantFields;
+        }
+
+
+        @Test
+        public void checkAnalyticsString() {
+            assertEquals("There is no such string in Actions class, thus returning null.", analyticsString, getStringFromReflection(analyticsString));
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java:78]: What does the message mean to a developer, how are they meant to fix this?

What are the failure cases
What does a dev need to do in each case

**Review by david-allison-1 — COMMENTED** [review]
Looks good, just dev documentation to go

File: AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java (hunk 4 above)
Comment (mrudultora) [reply AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java:78]: This message means that, the string we searched for in the Actions class is not present there.

File: AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java [hunk 5]
```diff
@@ -0,0 +1,124 @@
...
+        }
+
+    }
+
+
+    public static class AnalyticsConstantsFieldLengthTest {
+
+        @Test
+        public void fieldSizeEqualsListOfConstantFields() {
+            assertEquals("Add the new constant here also in the list listOfConstantFields", listOfConstantFields.size(), getFieldSize());
```
[the remark this answers is not in the document]
Comment (mrudultora) [reply AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java:108]: Nice question. Did not thought about that. In that case, we have to remove that from list `listOfConstantsField`.

[the remark this answers is not in the document]
Comment (mrudultora) [reply AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java:108]: But, would we remove the strings ?

**Comment by mrudultora** [comment]
The test is failing on CI, but passing on local machine. Any reason ?
```
com.ichi2.anki.analytics.AnalyticsConstantsTest > com.ichi2.anki.analytics.AnalyticsConstantsTest$AnalyticsConstantsFieldLengthTest.fieldSizeEqualsListOfConstantFields FAILED
    java.lang.AssertionError: Add the new constant here also in the list listOfConstantFields expected:<28> but was:<29>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at com.ichi2.anki.analytics.AnalyticsConstantsTest$AnalyticsConstantsFieldLengthTest.fieldSizeEqualsListOfConstantFields(AnalyticsConstantsTest.java:108)

```

File: AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (david-allison-1) [reply AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java:108]: We would, but don't leave it to chance

**Comment by david-allison-1** [comment]
> The test is failing on CI, but passing on local machine. Any reason ?
> 
> ```
> com.ichi2.anki.analytics.AnalyticsConstantsTest > com.ichi2.anki.analytics.AnalyticsConstantsTest$AnalyticsConstantsFieldLengthTest.fieldSizeEqualsListOfConstantFields FAILED
>     java.lang.AssertionError: Add the new constant here also in the list listOfConstantFields expected:<28> but was:<29>
>         at org.junit.Assert.fail(Assert.java:89)
>         at org.junit.Assert.failNotEquals(Assert.java:835)
>         at org.junit.Assert.assertEquals(Assert.java:647)
>         at com.ichi2.anki.analytics.AnalyticsConstantsTest$AnalyticsConstantsFieldLengthTest.fieldSizeEqualsListOfConstantFields(AnalyticsConstantsTest.java:108)
> ```

Unsure - have added to my TODO list, let me know if you figure it out

File: AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (mrudultora) [reply AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java:108]: I would add an if-else check. I think this would work.

**Comment by mrudultora** [comment]
>  just dev documentation to go

Umm, would you please clarify this?

**Comment by mrudultora** [comment]
Here is the image of passing on local machine.

Untitled

**Comment by david-allison-1** [comment]
> > just dev documentation to go

Oh - clarifying the error messages to ensure future developers need to know what to do, and don't do something wrong

**Comment by mrudultora** [comment]
Added the dev documentation explaining the meaning of messages shown if tests failed. Also, explained the meaning of Enclosed runner and why it's used here.

File: AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java [hunk 6]
```diff
@@ -0,0 +1,141 @@
...
+         * This method is used to get the size of fields in Actions Class.
+         * Because whenever a new constant is added in Actions Class but not added to the list present in this
+         * class (listOfConstantFields) the test must fail.
+         */
+        public static int getFieldSize() {
+            UsageAnalytics.Actions actions = new UsageAnalytics.Actions();
+            Field[] field;
+            field = actions.getClass().getDeclaredFields();
+            return field.length;
+        }
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java:139]: This is untested (so therefore lazy). I need to get CI working on my repo. If this doesn't work, I'll put in more effort.

```suggestion
        public static long getFieldSize() {
            return Arrays.stream(UsageAnalytics.class.getDeclaredFields())
                    .filter(x -> x.isAnnotationPresent(AnalyticsConstant.class))
                    .count();
        }
```

**Comment by mrudultora** [comment]
@david-allison-1 Unit Tests passed this time. To be honest, I didn't understand why they passed this time. Please throw some light on this lazy loading part.

**Comment by david-allison-1** [comment]
> @david-allison-1 Unit Tests passed this time. To be honest, I didn't understand why they passed this time. Please throw some light on this lazy loading part.

Lazy (bad) coding - not testing my work

There was a separate hidden field when run under CI.

The code that I wrote filters the list to only values which have the annotation, which removes that hidden field

**Comment by mrudultora** [comment]
Thanks for this info ;-)

File: AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.java [hunk 7]
```diff
@@ -358,46 +358,75 @@ public static boolean isEnabled() {
     }
 
 
-
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.java:361]: unnecessary spacing

File: AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java (hunk 4 above)
Comment (david-allison-1) [reply AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java:89]: We want the assertion message to give an actionable message to the developer about how they can fix the issue.

If someone adds a constant and sees `"There is no such string in Actions class, thus returning null."` in the test output, then you haven't explained to them how to fix it. For something like this, be as verbose as you need to

File: AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java [hunk 8]
```diff
@@ -0,0 +1,141 @@
...
+
+    }
+
+
+    public static class AnalyticsConstantsFieldLengthTest {
+
+        @Test
+        public void fieldSizeEqualsListOfConstantFields() {
+            if (getFieldSize() > listOfConstantFields.size()) {
+                assertEquals("Add the new constant here also in the list listOfConstantFields", listOfConstantFields.size(), getFieldSize());
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java:120]:
```suggestion
                assertEquals("Add the newly added analytics constant to AnalyticsConstantsTest.listOfConstantFields. NOTE: Constants should not be renamed as we cannot compare these in analytics", listOfConstantFields.size(), getFieldSize());
```

File: AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java [hunk 9]
```diff
@@ -0,0 +1,141 @@
...
+            } else if (getFieldSize() < listOfConstantFields.size()) {
+                assertEquals("Remove the constant from the list listOfConstantFields", listOfConstantFields.size(), getFieldSize());
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java:122]:
```suggestion
                assertEquals("If a constant is removed, it should be removed from AnalyticsConstantsTest.listOfConstantFields. NOTE: Constants should not be renamed as we cannot compare these in analytic", listOfConstantFields.size(), getFieldSize());
```

**Review by david-allison-1 — COMMENTED** [review]
A few suggestions - left one for you as I don't want to dictate string constants

**Comment by mrudultora** [comment]
I have changed the messages (2 of them are same as suggested by David). I think these messages now, would help devs clearly understand the reason of test failure.

File: AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java [hunk 10]
```diff
@@ -0,0 +1,144 @@
...
+
+
+        /**
+         * The message here means that the string being checked cannot be found in Actions class.
+         * If encountered with this message, re-check the list present here and constants in Actions class, to resolve
+         * the test failure.
+         */
+        @Test
+        public void checkAnalyticsString() {
+            assertEquals("There is no such string in Actions class, thus returning null. Re-check if you renamed any string in the analytics string constants of Actions class or AnalyticsConstantsTest.listOfConstantFields. If so, revert them as those string constants must not change as they are compared in analytics.",
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java:89]:
```suggestion
            assertEquals("Re-check if you renamed any string in the analytics string constants of Actions class or AnalyticsConstantsTest.listOfConstantFields. If so, revert them as those string constants must not change as they are compared in analytics.",
```

**Review by david-allison-1 — COMMENTED** [review]
One nit, then looks good to go

**Review by david-allison-1 — APPROVED** [review]
LGTM, thanks!

File: AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java (hunk 6 above)
Comment (david-allison-1) [reply AnkiDroid/src/test/java/com/ichi2/anki/analytics/AnalyticsConstantsTest.java]: > One thing is missing here. ( `UsageAnalytics.Actions.class` )

🤦 yes, that's what I get for laziness, thanks!

**Review by mikehardy — APPROVED** [review]
Nice! That should keep analytics comparisons nicely within the lines, thank you
