### PR TITLE
fix(image-occlusion): support updating a note's deck

### LINKED ISSUE #19426: (2.23.0alpha6) Changing the deck in the "Deck" field of the Image Occlusion editor doesn't make the new note to be added to the selected deck
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Share an image in File Explorer
2. Select "Anki", then select "Image Occlusion"
3. Select a deck while in the Image Occlusion editor
4. The new note is stored in the last deck that was studied instead of the deck that was selected in the Image Occlusion editor

The two videos below show the described behavior. 

**In the first video below**, I select "my-deck-1" to study. Then, switch to a file explorer and share an image with Anki using the option "Image Occlusion". In the Image Occlusion editor, I add a rectangle and then change the deck to "my-deck-4". Then, I press the check button on the top right corner to create the note. When I go back to the home screen, you can see that the note counter for my-deck-1 increased from 3 to 4. This was because the Image Occlusion note was added to "my-deck-1". Afterwards, I open the "Card browser" to show that the Image Occlusion card was actually added to "my-deck-1".

**In the second video below,** I followed the same steps, but instead of studying "my-deck-1". I studied "my-deck-3" which caused the card to be added "my-deck-3" instead of "my-deck-4" which was selected in the Image Occlusion editor.

https://github.com/user-attachments/assets/1a7e941f-c893-4783-944b-427d59041a03

https://github.com/user-attachments/assets/2af7c800-2d09-4864-8e7f-010a896b7d0e

### Expected behaviour

The new note should be added to the deck that was selected in the deck field of  the Image Occlusion editor.

### Debug info

```text
AnkiDroid Version = 2.23.0alpha6 (6673f13960a09f168c09bfac24a8b154c27c7882)  
Backend Version = 0.1.62-anki25.09.2 (25.09.2 3890e12c9e48c028c3f12aa58cb64bd9f8895e30)  
Android Version = 12 (SDK 31)  
ProductFlavor = full  
Device Info = samsung | samsung | a02q | a02qub | SM-A025M | qcom  
Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-A025M Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/140.0.7339.207 Mobile Safari/537.36  
ACRA UUID = 92a3c85e-777b-4683-9f59-2ca1928942b2  
FSRS = 5.1.0 (Enabled: false)  
Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

Selecting a deck in the Image Occlusion editor was added by https://github.com/ankidroid/Anki-Android/pull/19259

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### LINKED ISSUE #19605: Image Occlusion: cannot edit deck of a card
We edit using `UpdateImageOcclusionNote`, which does not include a deck ID

https://github.com/ankitects/anki/blob/5614d20bedcc4dd268136d389ad796b404a69d2c/proto/anki/image_occlusion.proto#L88-L94

Although the deck spinner is visible on the screen, we do nothing with it other than set the current deck.

----

We have some use cases:

* A user wants to edit a card when studying
* A user wants to edit a selection of cards from the same note [Card Browser - CARDS]
* A user wants to edit a note [Card Browser - NOTES]
  * ❓ What does it mean to edit the deck of a note, is a user aware of this? 
  * Do we care, given the user can use 'change deck'?
  * => Do what we did before the deck selection was moved to the IO screen

Note: A user can remove the cards they are editing (by removing masks). 

Each of these use cases needs to handle this eventuality

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
From the Reviewer, I could not edit the deck of an image occlusion note

This functionality was not implemented on `ImageOcclusion`. Only editing the deck of 'add' was supported, and the 'edit deck' functionality of `NoteEditorFragment` was hidden

In future, we can handle this inImageOcclusion, BUT:

There are 3 cases:
* A user wants to edit a card when studying
* A user wants to edit a selection of cards from the same note [Card Browser - CARDS]
* A user wants to edit a note [Card Browser - NOTES]
  * What does it mean to edit the deck of a note, is a user aware of this?

And a user can remove the cards they are editing (by removing masks).

Since we don't yet have full control over the process of adding an occlusion note, I decided it was a risk to take the time to implement this, and went for a simple fix

## Fixes
* Fixes #19605
* Fixes #19426

## Approach

Beforehand, I refactored the Image Occlusion screen: 
* Moving to a discriminated union, to make invalid states non-representable
* Moving to flows, to reduce 

Then:
* Enable editing the deck in NoteEditorFragment if in edit mode
* Disable editing the deck in ImageOcclusion if in edit mode

## How Has This Been Tested?

Pixel 9 API 35 emulator:

* Add Image Occlusion note by 'share' & change deck from default
  * ✅ Deck is set on note
  * ✅ Current deck is not changed
* Add Image Occlusion note by 'add'
  * ✅ Deck is set on note
  * ✅ Current deck is not changed
* Edit Image Occlusion note in 'Review'
  * ✅ Deck is settable in Note Editor
  * ✅ Deck is not settable in Image Occlusion Editor
* Edit Image Occlusion note in 'Review' - removing current mask
  * ✅ 'No cloze 1 found on card ...'
* Edit Image Occlusion card in 'Card Browser'
  * ✅ Deck is changeable in Note Editor
* Edit Image Occlusion note in 'Card Browser'
  * ⚠️ Known buggy: https://github.com/ankidroid/Anki-Android/issues/17415

Screenshot 2025-11-24 at 20 52 55

Screenshot 2025-11-24 at 20 53 03

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/pages/ImageOcclusion.kt [hunk 1]
```diff
@@ -120,28 +128,44 @@ class ImageOcclusion :
...
+        fun onDeckNameChanged(name: String) {
+            deckNameView.text = name
+        }
 
+        viewModel.deckNameFlow?.launchCollectionInLifecycleScope(::onDeckNameChanged) ?: run {
+            deckNameView.isVisible = false
+        }
+    }
+
+    // TODO: Move this to an extension method once we have context parameters
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/pages/ImageOcclusion.kt:143]: We should probably add these via an override for `ktlint.version` on the ktLint gradle plugin

It's been a while

File: AnkiDroid/src/main/java/com/ichi2/anki/pages/viewmodel/ImageOcclusionViewModel.kt [hunk 2]
```diff
@@ -21,80 +21,141 @@ import android.os.Parcelable
...
-    val oldDeckId: Long
+    val deckNameFlow =
+        selectedDeckIdFlow?.map { did -> withCol { decks.name(did) } }
 
     /**
      * A [JSONObject] containing options for initializing the WebView. This includes
      * the type of operation ("add" or "edit"), and relevant IDs and paths.
      */
-    val webViewOptions: JSONObject
+    val webViewOptions: JSONObject = args.toWebViewOptions()
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/pages/viewmodel/ImageOcclusionViewModel.kt]: inline this and make args public

File: AnkiDroid/src/main/java/com/ichi2/anki/pages/ImageOcclusion.kt (hunk 1 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/pages/ImageOcclusion.kt:143]: * https://github.com/ankidroid/Anki-Android/issues/19614

**Comment by lukstbit** [comment]
> From the Reviewer, I could not edit the deck of an image occlusion note

Unless I'm missing something this isn't possible on desktop either(we can only modify the masks). If this is the case I don't think we should diverge.

We don't quite follow desktop as we don't allow the user to save without any occlusions set but on desktop it just results in an empty card.

**Comment by david-allison** [comment]
We supported editing the deck in 2.22, I'd rather avoid the regression

As far as I understand the code, It's the backend rejecting the note with 0 occlusions.

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt [hunk 3]
```diff
@@ -2751,22 +2752,28 @@ class NoteEditorFragment :
...
+                        0
+                    }
+                ImageOcclusionArgs.Add(
+                    noteTypeId = noteTypeId,
+                    imagePath = imagePath,
+                    deckId = deckId,
+                )
+            } else {
+                ImageOcclusionArgs.Edit(
+                    noteId = editorNote?.id!!,
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt]:
```suggestion
                    noteId = editorNote!!.id,
```

File: AnkiDroid/src/main/java/com/ichi2/anki/pages/viewmodel/ImageOcclusionViewModel.kt [hunk 4]
```diff
@@ -23,50 +23,75 @@ import androidx.lifecycle.ViewModel
...
-    val webViewOptions: JSONObject =
-        JSONObject().apply {
-            put("kind", args.kind)
-            if (args.kind == "add") {
-                put("imagePath", args.imagePath)
-                put("notetypeId", args.id)
-            } else {
-                put("noteId", args.id)
-            }
+    fun toWebViewOptions() =
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/pages/viewmodel/ImageOcclusionViewModel.kt]: I know that this is following the original code name and that I were one of the people that approved the initial naming, but when I read `WebView`, I think about the `WebView` object itself and its configuration (`.settings`, `webViewClient`, etc).

In this case, the options here are related to the IO `Page`, which is a term used in Android (`onPageStarted`, `onPageFinished`, `onPageCommitVisible`) and is actually the place where this is called (`onPageFinished`).

```suggestion
    /**
     * A [JSONObject] containing options for loading the Image Occlusion page. This includes
     * the type of operation ("add" or "edit"), and relevant IDs and paths.
     */
    val webViewOptions: JSONObject =
        JSONObject().apply {
            put("kind", args.kind)
            if (args.kind == "add") {
                put("imagePath", args.imagePath)
                put("notetypeId", args.id)
            } else {
                put("noteId", args.id)
            }
    fun toImageOcclusionSetupOptions() =
```
(method name could be better)

**Review by BrayanDSO — COMMENTED** [review]
partial review

File: AnkiDroid/src/main/java/com/ichi2/anki/pages/viewmodel/ImageOcclusionViewModel.kt (hunk 4 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/pages/viewmodel/ImageOcclusionViewModel.kt]: Thanks, not my code, but agreed

https://github.com/ankitects/anki/blob/5614d20bedcc4dd268136d389ad796b404a69d2c/ts/routes/image-occlusion/lib.ts#L20 for the source

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/pages/viewmodel/ImageOcclusionViewModel.kt]: I used `toImageOcclusionMode` to match upstream

File: AnkiDroid/src/main/java/com/ichi2/anki/pages/ImageOcclusion.kt [hunk 5]
```diff
@@ -44,6 +44,21 @@ import com.ichi2.anki.startDeckSelection
...
+ *
+ * @see ImageOcclusionViewModel
+ * @see ImageOcclusion.getIntent
+ *
+ * https://github.com/ankitects/anki/blob/main/proto/anki/image_occlusion.proto
+ *
+ * **Paths**
+ * `/image-occlusion/$PATH`
+ * `/image-occlusion/$NOTE_ID`
+ */
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/pages/ImageOcclusion.kt:65]: The links aren't clickable.

Also, putting the `@see` blocks in the middle leaves the rest unrendered in the IDE popup

```suggestion
/**
 * Page provided by the backend, for a user to add or edit an image occlusion (IO) note
 *
 * IO: Like an image-based cloze: hide parts of an image, revealed on the back
 * ([docs](https://docs.ankiweb.net/editing.html#image-occlusion) and 
 * [source](https://github.com/ankitects/anki/blob/main/proto/anki/image_occlusion.proto)).
 *
 * When adding, a user may select the deck of the note
 *
 * **Paths**
 * `/image-occlusion/$PATH`
 * `/image-occlusion/$NOTE_ID`
 *
 * @see ImageOcclusionViewModel
 * @see ImageOcclusion.getIntent
 */
```

File: AnkiDroid/src/main/java/com/ichi2/anki/pages/ImageOcclusion.kt [hunk 6]
```diff
@@ -120,28 +131,44 @@ class ImageOcclusion :
...
 
+        viewModel.deckNameFlow?.launchCollectionInLifecycleScope(::onDeckNameChanged) ?: run {
+            deckNameView.isVisible = false
+        }
+    }
+
+    // TODO: Move this to an extension method once we have context parameters
+    private fun <T> Flow<T>.launchCollectionInLifecycleScope(block: suspend (T) -> Unit) {
+        lifecycleScope.launch {
+            lifecycle.repeatOnLifecycle(Lifecycle.State.RESUMED) {
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/pages/ImageOcclusion.kt:146]: why RESUMED?

File: AnkiDroid/src/main/java/com/ichi2/anki/pages/ImageOcclusion.kt [hunk 7]
```diff
@@ -120,28 +131,44 @@ class ImageOcclusion :
...
+        fun onDeckNameChanged(name: String) {
+            deckNameView.text = name
+        }
 
+        viewModel.deckNameFlow?.launchCollectionInLifecycleScope(::onDeckNameChanged) ?: run {
+            deckNameView.isVisible = false
+        }
+    }
+
+    // TODO: Move this to an extension method once we have context parameters
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/pages/ImageOcclusion.kt:143]: this is an extension method. I guess that you mean that it should be a static extension method that can be used by any class.

When that happens, a `state` parameter should be added as well and rename the method to something shorter

File: AnkiDroid/src/main/java/com/ichi2/anki/pages/viewmodel/ImageOcclusionViewModel.kt [hunk 8]
```diff
@@ -98,18 +90,30 @@ class ImageOcclusionViewModel(
...
 
-    var selectedDeckIdFlow = MutableStateFlow(args.originalDeckId)
+    private val addArgs: ImageOcclusionArgs.Add? = args as? ImageOcclusionArgs.Add
+
+    /**
+     * The currently selected deck ID
+     *
+     * Only valid in 'ADD' mode
+     */
+    var selectedDeckIdFlow: MutableStateFlow<DeckId>? =
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/pages/viewmodel/ImageOcclusionViewModel.kt]:
```suggestion
    val selectedDeckIdFlow: MutableStateFlow<DeckId>? =
```

File: AnkiDroid/src/main/java/com/ichi2/anki/pages/ImageOcclusion.kt [hunk 9]
```diff
@@ -104,7 +103,7 @@ class ImageOcclusion :
                 url: String?,
             ) {
                 super.onPageFinished(view, url)
-                viewModel.webViewOptions.let { options ->
+                viewModel.args.toImageOcclusionMode().let { options ->
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/pages/ImageOcclusion.kt:107]: optional nit: it's possible to make `args` private and only expose a method that returns the "image occlusion mode"

**Review by BrayanDSO — COMMENTED** [review]
optional patch:

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/pages/viewmodel/ImageOcclusionViewModel.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/pages/viewmodel/ImageOcclusionViewModel.kt b/AnkiDroid/src/main/java/com/ichi2/anki/pages/viewmodel/ImageOcclusionViewModel.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/pages/viewmodel/ImageOcclusionViewModel.kt	(revision 5009b6d0611de089f275b442cdcb1a110639810f)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/pages/viewmodel/ImageOcclusionViewModel.kt	(date 1764266698775)
@@ -90,7 +90,7 @@
     val args: ImageOcclusionArgs =
         checkNotNull(savedStateHandle[IO_ARGS_KEY]) { "$IO_ARGS_KEY required" }
 
-    private val addArgs: ImageOcclusionArgs.Add? = args as? ImageOcclusionArgs.Add
+    private val originalDeckId: DeckId? = (args as? ImageOcclusionArgs.Add)?.originalDeckId
 
     /**
      * The currently selected deck ID
@@ -98,7 +98,7 @@
      * Only valid in 'ADD' mode
      */
     var selectedDeckIdFlow: MutableStateFlow<DeckId>? =
-        addArgs?.let { args -> MutableStateFlow(args.originalDeckId) }
+        originalDeckId?.let { MutableStateFlow(it) }
 
     /**
      * The currently selected deck name
@@ -132,8 +132,8 @@
      */
     fun onSaveOperationCompleted() {
         Timber.i("save operation completed")
-        if (addArgs != null) {
-            resetTemporaryDeckOverride(addArgs)
+        if (originalDeckId != null) {
+            resetTemporaryDeckOverride(originalDeckId)
         }
     }
 
@@ -142,9 +142,9 @@
      *
      * Only for [ImageOcclusionArgs.Add] mode
      */
-    private fun resetTemporaryDeckOverride(args: ImageOcclusionArgs.Add) {
+    private fun resetTemporaryDeckOverride(originalDeckId: DeckId) {
         // no need to reset if the DeckId was unchanged
-        if (args.originalDeckId == selectedDeckIdFlow?.value) return
+        if (originalDeckId == selectedDeckIdFlow?.value) return
 
         // reset to the previous deck that the backend "saw" as selected, this
         // avoids other screens unexpectedly having their working decks modified
@@ -152,7 +152,7 @@
         // adds an occluded image via 'Share'
         viewModelScope.launch {
             Timber.i("resetting temporary deck override")
-            withCol { backend.setCurrentDeck(args.originalDeckId) }
+            withCol { backend.setCurrentDeck(originalDeckId) }
         }
     }
 ```

File: AnkiDroid/src/main/java/com/ichi2/anki/pages/ImageOcclusion.kt (hunk 6 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/pages/ImageOcclusion.kt:146]: Explained and to be dealt with in
* https://github.com/ankidroid/Anki-Android/issues/19632

File: AnkiDroid/src/main/java/com/ichi2/anki/pages/viewmodel/ImageOcclusionViewModel.kt (hunk 8 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/pages/viewmodel/ImageOcclusionViewModel.kt]: To confirm: this was IDE lint?

I likely need to reinstall Android Studio

File: AnkiDroid/src/main/java/com/ichi2/anki/pages/ImageOcclusion.kt (hunk 9 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/pages/ImageOcclusion.kt:107]: Reviewer's choice, I don't mind, mildly against:

* The JSONObject generation belongs on the `ImageOcclusionArgs` class
* `args` is immutable, so I'm fine with it being public
* a delegate/accessor property on `ImageOcclusionViewModel` duplicates the docs, and doesn't feel like it adds value

**Comment by david-allison** [comment]
Thanks so much for the patch!!

File: AnkiDroid/src/main/java/com/ichi2/anki/pages/ImageOcclusion.kt (hunk 7 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/pages/ImageOcclusion.kt:143]: https://github.com/ankidroid/Anki-Android/issues/19614#issuecomment-3587076833 for tracking

File: AnkiDroid/src/main/java/com/ichi2/anki/pages/viewmodel/ImageOcclusionViewModel.kt (hunk 8 above)
Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/anki/pages/viewmodel/ImageOcclusionViewModel.kt]: > To confirm: this was IDE lint?

Nope

**Review by BrayanDSO — APPROVED** [review]

**Review by mikehardy — APPROVED** [review]
Can't see anything that looks off, let's go
