### PR TITLE
fix: Deck selection row is visible on initial load for note editor with Image Occlusion

### LINKED ISSUE #19416: Deck selection row is visible on initial load for note editor with Image Occlusion
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Open the app
2. "+" -> "Add"
3. Switch "Type:" from others to "Image Occlusion" 
    Image

 
-----
Note: the row for selecting deck is expectedly invisible above by the change from:
 - #19259 

> If we are moving to selecting the deck in this screen then we should hide the deck selection in the        NoteEditorFragment when the notetype is image occlusion.

  _Originally posted in https://github.com/ankidroid/Anki-Android/pull/19259#pullrequestreview-3267026761_

-----

4. Go back to Deck picker screen
5. "+" -> "Add"

**Result**

The row for selecting deck is visible (and changing deck here isn't reflected in the saved note)

Image
 

### Expected behaviour

The row for selecting deck is invisible.

Image

            

### Debug info

```text
AnkiDroid Version = 2.23.0alpha6 (6673f13960a09f168c09bfac24a8b154c27c7882)  
Backend Version = 0.1.62-anki25.09.2 (25.09.2 3890e12c9e48c028c3f12aa58cb64bd9f8895e30)  
Android Version = 15 (SDK 35)  
ProductFlavor = full  
Device Info = OPPO | OPPO | OP5A0BL1 | CPH2603 | CPH2603 | mt6877  
Webview User Agent = Mozilla/5.0 (Linux; Android 15; CPH2603 Build/AP3A.240617.008; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/143.0.7499.3 Mobile Safari/537.36  
ACRA UUID = 2b37baa9-a2cb-42fe-bc23-cd5dd6ad8547  
FSRS = 5.1.0 (Enabled: false)  
Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by snowtimeglass**
## Purpose / Description
The row for selecting deck in the note editor is unexpectedly visible when the editor is initially loaded with Image Occlusion note type.
image

-----

## Fixes
* Fixes #19416

## Approach
(Updated)
Move the process of the visibility to the end of `setNote()`

## How Has This Been Tested?

Checked on a physical device (Android 15)
(Confirmed again after the updated approach)
image

## Checklist

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt [hunk 1]
```diff
@@ -563,6 +563,14 @@ class NoteEditorFragment :
             viewLifecycleOwner,
             Lifecycle.State.RESUMED,
         )
+        view.post {
```
Comment (lukstbit) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt]: Why is this needed?

Comment (snowtimeglass) [reply AnkiDroid/src/main/java/com/ichi2/anki/NoteEditorFragment.kt]: It is intended to ensure that the visibility process is performed after the current note type and the value of `currentNotetypeIsImageOcclusion()` have been determined.

For simplification, I'll change the way.

**Review by lukstbit — APPROVED** [review]
Works, thanks!
