### PR TITLE
fix(previewer): update after IO changes

### LINKED ISSUE #18405: Preview doesn't update after IO edits
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Browser > Preview cards.
2. Tap the pencil icon.
3. Tap "Edit occlusions" and edit the masks in an IO note.
4. Tap OK. Go back.

### Expected behaviour

In the preview screen (the one we open from the browser) the cards aren't updated. Note that all cards are live updated in the previwer except this editing masks case.

### Debug info

```text
AnkiDroid Version = 2.21alpha15 (c9c58c3efb8adf535fdfb4a7237ae56a870fafef)
Backend Version = 0.1.52-anki25.02 (25.02 038d85b1d9e1896e93a3e4a26f600c79ddc33611)
Android Version = 11 (SDK 30)
ProductFlavor = full
Device Info = realme | realme | RMX2193 | RMX2193 | RMX2193 | mt6768
Webview User Agent = Mozilla/5.0 (Linux; Android 11; RMX2193 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/136.0.7103.60 Mobile Safari/537.36
ACRA UUID = cf265e01-9693-407f-984d-61ddf9698fac
FSRS = 2.0.3 (Enabled: true)
Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by BrayanDSO**
Handle changes with opExecuted instead of using an activity result

Similar to https://github.com/ankidroid/Anki-Android/pull/18273/commits/ad778b9f02042acc92b076231b1d9af2ec3301a4

## Fixes
* Fixes #18405

## How Has This Been Tested?

Emulator 35:
1. Have an Image Occlusion Note
2. Go to the Browser and preview an Image occlusion note
3. Edit the note
4. See the changes

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt [hunk 1]
```diff
@@ -247,6 +238,32 @@ class PreviewerViewModel(
             TypeAnswer.removeTags(text)
         }
 
+    override fun opExecuted(
+        changes: OpChanges,
+        handler: Any?,
+    ) {
+        Timber.v("PreviewerViewModel::opExecuted")
```
Comment (lukstbit) [inline AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerViewModel.kt]: Maybe worth adding the _changes_ parameter here?

**Review by lukstbit — APPROVED** [review]
LGTM

**Review by david-allison — APPROVED** [review]
