### PR TITLE
fix: unable to crop shared images

### LINKED ISSUE #17361: [BUG]: Can't Crop Shared Image
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Open a PDF file in this app: https://play.google.com/store/apps/details?id=com.flyersoft.moonreaderp
2. From the kebab menu on top right, share a screenshot of the page to AnkiDroid. The screenshot shows up fine.
Image

3. Now, click on top-right crop icon. This appears:
Image

### Expected behaviour

I should've been able to crop but instead I get a error message. I've tried with sharing images from my gallery and no issues.

### Debug info

```
AnkiDroid Version = 2.19.1 (6953d60532ee2762d29b06fd1d76e69203ad8455)

Backend Version = 0.1.43-anki24.06.3 (24.06.3 d678e39350a2d243242a69f4e22f5192b04398f2)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = realme

Model = RMX2193

Hardware = mt6768

Webview User Agent = Mozilla/5.0 (Linux; Android 11; RMX2193 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/130.0.6723.58 Mobile Safari/537.36

ACRA UUID = cf265e01-9693-407f-984d-61ddf9698fac

FSRS = 0.6.4 (Enabled: true)

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by criticalAY**
## Purpose / Description
- https://github.com/ankidroid/Anki-Android/issues/17361
The image when shared to AnkiDroid directly doesn't grant Uri permission as the photo is coming from other app, so we internalise the URI and then use the image, hence fixing the crop issue as it needs Uri with correct permission to edit it

## Fixes
* Fixes #17361

## How Has This Been Tested?
Tested on Google Emulator API 35

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaUtils.kt [hunk 1]
```diff
@@ -189,4 +192,26 @@ object MultimediaUtils {
...
     }
+
+    /**
+     * Copies an image from an external URI to the app's cache directory and retains the original filename and extension.
+     *
+     * @param context The context used to access the content resolver and cache directory.
+     * @param externalUri The URI of the external image to be copied.
+     * @return A local URI pointing to the newly created file in the cache directory, or null if the URI cannot be read.
+     */
+    fun getLocalUriFromExternalUri(context: Context, externalUri: Uri): Uri? {
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaUtils.kt:203]: I feel like I've written this function before - doesn't this exist already? Both in image handling in general and re-used for deck/collection import ?

Also, you made a PR but did not include in the PR description any information about how you reproduced, what the root cause of the issue is, the approach etc - so as a reviewer I am left to reconstruct all that in my mind just via presentation of code vs knowing the context you have already had to work through

**Review by mikehardy — CHANGES_REQUESTED** [review]
I strongly suspect the file internalization logic exists somewhere already and some effort was expended on de-duplicating it once or a few times already

File: AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt [hunk 2]
```diff
@@ -276,12 +276,24 @@ class MultimediaImageFragment : MultimediaFragment(R.layout.fragment_multimedia_
...
             handleSelectedImageOptions()
         }
     }
 
+    private fun processExternalImage(uri: Uri?): Uri? {
+        val localFile = uri?.let { internalizeUri(it) }
+        if (localFile != null) {
+            return Uri.fromFile(localFile)
+        } else {
+            Timber.e("Failed to internalize URI: $uri")
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt:292]: nit: e to me is "catastrophic", like the app needs to restart
w is "this would have been an error but we handled it and current task may be broken but we're moving on

I think this is a w

These are documented by the way, so you can choose appropriately: https://github.com/ankidroid/Anki-Android/wiki/Code-style#log-levels

Provisional approve assuming you'll get that, so if next person is +1, that's good for me!

Thanks

**Review by mikehardy — APPROVED** [review]
will assume the log level alteration is easy and completed

**Review by david-allison — DISMISSED** [review]
* use `?.let { } so a nullable parameter isn't required
* `internalizeUrl` already logs when returning `null`, so the additional log isn't required

I think the following patch goes 'too far' in conciseness, but food for thought

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt b/AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt	(revision 2e692c794b5048c098884b1760be7e1ccb576aaa)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/multimedia/MultimediaImageFragment.kt	(date 1731275398964)
@@ -274,26 +274,18 @@
     }
 
     private fun handleImageUri() {
+        fun processExternalImage(uri: Uri): Uri? = internalizeUri(uri)?.let { Uri.fromFile(it) }
+        
         if (imageUri != null) {
             view?.findViewById<TextView>(R.id.no_image_textview)?.visibility = View.GONE
 
-            val internalUri = processExternalImage(imageUri)
+            val internalUri = imageUri?.let { processExternalImage(it) }
             handleSelectImageIntent(internalUri)
         } else {
             handleSelectedImageOptions()
         }
     }
 
-    private fun processExternalImage(uri: Uri?): Uri? {
-        val localFile = uri?.let { internalizeUri(it) }
-        if (localFile != null) {
-            return Uri.fromFile(localFile)
-        } else {
-            Timber.e("Failed to internalize URI: $uri")
-            return null
-        }
-    }
-
     private fun handleSelectedImageOptions() {
         when (selectedImageOptions) {
             ImageOptions.GALLERY -> {
```

**Comment by criticalAY** [comment]
@david-allison Applied the changes, now good to go

**Review by mikehardy — APPROVED** [review]
applies suggested change from David completely
