### PR TITLE
Handle DeckConfig."timer" as boolean

### LINKED ISSUE #6089: Crash when clicking on deck options
###### Reproduction Steps

1. Press and hold on a deck.
2. Click on "Options"

###### Expected Result

Should go to the options menu for that deck. I have a couple of decks that do not exhibit this behaviour and they are in the same options group.

###### Actual Result

The program crashes.

###### Debug info

AnkiDroid Version = 2.9.6
Android Version = 6.0.1
ACRA UUID = 2715152f-1201-4c3b-882e-8b2535d4be30

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

### PR DESCRIPTION
**Pull request by david-allison-1**
## Notes

Value is written (only other grep for "timer"): https://github.com/ankidroid/Anki-Android/blob/5d0eb69ca943b646a1141ba808e7426e443202e5/AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java#L270

I've previously tested the options, and no other crashes were found on other properties.

## Purpose / Description
Anki 2.1.24 converted this to an boolean, reverted in 2.1.25, but we need to coerce it back to avoid a crash.

## Fixes
Fixes #6089

## Approach
Fallback to boolean parsing if integer parsing fails. Remove unused method

## How Has This Been Tested?

On my device, both on 2.1.24 collection and my normal collection

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/libanki/DeckConfig.java [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+ this program.  If not, see <http://www.gnu.org/licenses/>.
+ */
+
+package com.ichi2.libanki;
+
+import com.ichi2.utils.JSONObject;
+
+import androidx.annotation.Nullable;
+
+public class DeckConfig {
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/libanki/DeckConfig.java:23]: Codacy Issue found: [The utility class name 'DeckConfig' doesn't match '[A-Z][a-zA-Z0-9]+(Utils?|Helper|Constants)'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5450235)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- AnkiDroid/src/main/java/com/ichi2/libanki/DeckConfig.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5450235&bid=17869932)

**Comment by david-allison-1** [comment]
> But...this is a problem with deck timer and also was a problem somewhere else.
> What do you think about not having OOP machinery here (DeckConfig etc) and just having a Utils.handleConfigBoolean(String) or similar that would accept either 1/0 or true/false and would handle the coercion in the way the rest of the ecosystem apparently does (auto-magically), then upstream could do whatever they want and we'll be more resilient to this

Ideally not, as that makes it /much/ harder for upstream to test whether they're going to break legacy AnkiDroid clients that can't upgrade (for API deprecation reasons, or using another app store).

In this case, the schema contract has already been temporarily broken, so I'm happy (ish) with adding a fix for it.

If this were to go into a coordinated non-point release, then I'd be fine with it, but relaxing constraints on certain clients while keeping them on others is a recipe for bugs.

Your call on this one though. Genuinely

**Comment by mikehardy** [comment]
Hadn't thought of the API skew and clients orphaned without updates. Strong argument. For instance if Anki Desktop wasn't aware of this and proceeded then <= API15 would already be broken with no hope for fix, and soon API15 itself (when we bump to API16 w/ #5665 ) etc. Ok, I'm convinced. Will re-read with a detailed view for possible merge and pick to 2.9.x

**Comment by mikehardy** [comment]
Released as 2.9.7 (currently sitting on beta track, will promote if it seems to work) and 2.10alpha73

**Comment by mikehardy** [comment]
This is promoted to production, 2.9.7 is rolling out to everyone now.
What's the end game for #6090 - seems like that should still merge for 2.10?

**Comment by david-allison-1** [comment]
@mikehardy Let's consider it a crash fix, so 2.10 is fine for me, your call.
