### PR TITLE
fix(previewer): media config not initialized

### LINKED ISSUE #19729: Previewer: kotlin.UninitializedPropertyAccessException: lateinit property config has not been initialized
https://github.com/ankidroid/Anki-Android/actions/runs/20076406192/job/57591859986

```
PreviewerViewModelTest > next, slider and previous navigation integration FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:87)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.junit.Assert.assertTrue(Assert.java:53)
        at com.ichi2.anki.previewer.PreviewerViewModelTest$next, slider and previous navigation integration$1.invokeSuspend(PreviewerViewModelTest.kt:203)
        at com.ichi2.anki.previewer.PreviewerViewModelTest$next, slider and previous navigation integration$1.invoke(PreviewerViewModelTest.kt)
        at com.ichi2.anki.previewer.PreviewerViewModelTest$next, slider and previous navigation integration$1.invoke(PreviewerViewModelTest.kt)
        at com.ichi2.anki.libanki.testutils.AnkiTest.runTestInner$suspendImpl(AnkiTest.kt:336)
        at com.ichi2.anki.libanki.testutils.AnkiTest.runTestInner(AnkiTest.kt)
        at com.ichi2.anki.libanki.testutils.InMemoryAnkiTest.runTestInner(InMemoryAnkiTest.kt:36)
        at com.ichi2.anki.libanki.testutils.AnkiTest$runTest$1$1.invokeSuspend(AnkiTest.kt:329)
        at com.ichi2.anki.libanki.testutils.AnkiTest$runTest$1$1.invoke(AnkiTest.kt)
        at com.ichi2.anki.libanki.testutils.AnkiTest$runTest$1$1.invoke(AnkiTest.kt)
        at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$2$1$1.invokeSuspend(TestBuilders.kt:317)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
        at kotlinx.coroutines.test.TestDispatcher.processEvent$kotlinx_coroutines_test(TestDispatcher.kt:24)
        at kotlinx.coroutines.test.TestCoroutineScheduler.tryRunNextTaskUnless$kotlinx_coroutines_test(TestCoroutineScheduler.kt:99)
        at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$2$1$workRunner$1.invokeSuspend(TestBuilders.kt:326)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:263)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:94)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:70)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at kotlinx.coroutines.test.TestBuildersJvmKt.createTestResult(TestBuildersJvm.kt:10)
        at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest-8Mi8wO0(TestBuilders.kt:309)
        at kotlinx.coroutines.test.TestBuildersKt.runTest-8Mi8wO0(Unknown Source)
        at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest-8Mi8wO0(TestBuilders.kt:167)
        at kotlinx.coroutines.test.TestBuildersKt.runTest-8Mi8wO0(Unknown Source)
        at com.ichi2.anki.libanki.testutils.AnkiTest.runTest(AnkiTest.kt:328)
        at com.ichi2.anki.libanki.testutils.InMemoryAnkiTest.runTest(InMemoryAnkiTest.kt:36)
        at com.ichi2.anki.libanki.testutils.AnkiTest.runTest$default(AnkiTest.kt:317)
        at com.ichi2.anki.previewer.PreviewerViewModelTest.next, slider and previous navigation integration(PreviewerViewModelTest.kt:178)
```

### PR DESCRIPTION
**Pull request by BrayanDSO**
## Fixes
* Fixes #19729

## Approach

used a nullable config and empty av tags lists instead of lateinit properties.

This avoids crashes. There's still the rare chance  of the previewer requesting a sound before it's loaded, which would result in playing nothing. Making that foolproof requires a bigger refactor, which I intend to do later

## How Has This Been Tested?

Flaky hammer™: https://github.com/BrayanDSO/Anki-Android/actions/runs/21093913315

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt [hunk 1]
```diff
@@ -1470,7 +1470,7 @@ abstract class AbstractFlashcardViewer :
             Timber.w("media is not played as the activity is inactive")
             return
         }
-        if (!cardMediaPlayer.config.autoplay && !doMediaReplay) return
+        if (cardMediaPlayer.config?.autoplay != true && !doMediaReplay) return
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt:1473]: Asking for some attention on the condition fixes of `AbstractFlashcardViewer`
