### PR TITLE
fix(study-screen): timer not stopping

### LINKED ISSUE #19768: [New Study Screen]: On-screen timer does not pause when AnkiDroid is in the background
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

The on-screen timer works as expected if AnkiDroid is in use when the maximum answer seconds is reached. It does not pause if the Recent Apps or Home buttons are pressed during a review and AnkiDroid is left running in the background. 

The total study time doesn't appear to be affected by the seemingly longer review times, so this might be a visual bug.

Image

Here's an instance where I stepped away from AnkiDroid and came back to a 90 minute review time. For reference, the maximum answer seconds for this deck is 180.

### Expected behaviour

The on-screen timer should pause when the Recent Apps or Home buttons are pressed during a review, which is the old study screen behaviour.

### Debug info

```text
AnkiDroid Version = 2.23.0 (4f768aa0be34e254d65fd4ebe19781b84e8efc37)  
Backend Version = 0.1.62-anki25.09.2 (25.09.2 3890e12c9e48c028c3f12aa58cb64bd9f8895e30)  
Android Version = 15 (SDK 35)  
ProductFlavor = play  
Device Info = samsung | samsung | a15 | a15nsxx | SM-A155F | mt6789  
Webview User Agent = Mozilla/5.0 (Linux; Android 15; SM-A155F Build/AP3A.240905.015.A2; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/142.0.7444.171 Mobile Safari/537.36  
ACRA UUID = f0945afc-35ac-4ac2-bf8e-6b40f101546a  
FSRS = 5.1.0 (Enabled: true)  
Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by BrayanDSO**
## Purpose / Description

The timer code was hard to follow due to how it tried to deal with configuration changes.

so I refactored the whole logic so the View is as dumb as possible and all the state is managed by `AnswerTimer` and the ViewModel

that also made possible to make unit tests

## Fixes
* Fixes #19768

## How Has This Been Tested?

Emulator 36

https://github.com/user-attachments/assets/4f7b9f6a-bf40-4ee5-a5dc-569ad38696fa

https://github.com/user-attachments/assets/490e1299-eb8c-4584-ad67-468112f8b2f5

## Learning (optional, can help others)

first timing using a [DefaultLifecycleObserver](https://developer.android.com/reference/androidx/lifecycle/DefaultLifecycleObserver)

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/AnswerTimerView.kt [hunk 1]
```diff
@@ -16,33 +16,25 @@
...
     context: Context,
     attributeSet: AttributeSet?,
 ) : Chronometer(context, attributeSet) {
-    var limitInMs = Int.MAX_VALUE
-    private var elapsedMillisBeforeStop = 0L
+    private var limitInMs: Int = Int.MAX_VALUE
     private var isRunning = false
 
     init {
         setOnChronometerTickListener {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/AnswerTimerView.kt:34]: This is still safe to not dispose explicitly
