### PR TITLE
fix: Disable "force full sync" preference when user is not logged in

### LINKED ISSUE #13374: Disable the "force full sync" preference if the user is not logged in
It doesn't make sense to force a full sync if the user can't sync

### PR DESCRIPTION
**Pull request by pratyaksh1610**
## Purpose / Description

Disabled "force full sync" preference when user is not logged in.

## Fixes
Fixes #13374 

## Approach
First checked if the user is logged in or not and enabled/disabled the preference accordingly.

## Before

https://user-images.githubusercontent.com/76740999/222242830-ca0e7a55-ce50-47aa-a1de-bc7a5fff981e.mp4

## After

https://user-images.githubusercontent.com/76740999/222242855-9e45aded-4261-401c-af71-45bc9dabd0c0.mp4

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/preferences/SyncSettingsFragment.kt [hunk 1]
```diff
@@ -73,10 +76,16 @@ class SyncSettingsFragment : SettingsFragment() {
             .ifEmpty { getString(R.string.sync_account_summ_logged_out) }
     }
 
+    private fun updateForceFullSync() {
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/preferences/SyncSettingsFragment.kt:79]:
```suggestion
    private fun updateForceFullSyncEnabledState() {
```

File: AnkiDroid/src/main/java/com/ichi2/anki/preferences/SyncSettingsFragment.kt [hunk 2]
```diff
@@ -39,6 +39,9 @@ class SyncSettingsFragment : SettingsFragment() {
         // AnkiWeb Account
         updateSyncAccountSummary()
 
+        // Enable/disable force full sync
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/preferences/SyncSettingsFragment.kt:42]:
```suggestion
        // Enable/disable force full sync if the user is logged in or not
```

**Review by BrayanDSO — COMMENTED** [review]
only nits

**Review by david-allison — COMMENTED** [review]
I approve once the above comments are addressed

File: AnkiDroid/src/main/java/com/ichi2/anki/preferences/SyncSettingsFragment.kt (hunk 1 above)
Comment (pratyaksh1610) [reply AnkiDroid/src/main/java/com/ichi2/anki/preferences/SyncSettingsFragment.kt]: Done

File: AnkiDroid/src/main/java/com/ichi2/anki/preferences/SyncSettingsFragment.kt (hunk 2 above)
Comment (pratyaksh1610) [reply AnkiDroid/src/main/java/com/ichi2/anki/preferences/SyncSettingsFragment.kt]: Done

**Review by BrayanDSO — APPROVED** [review]
Comments addressed. So I'm including David's approval, based on their comment
