### PR TITLE
Remove possibility of TagsDialog NullPointerException

### LINKED ISSUE #6174: [ACRA 2.10] - NullPointerException: TagsDialogListener
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/32723929-52d0-44f1-8f43-27d74ba2bc0c

```
java.lang.NullPointerException: Attempt to invoke interface method 'void com.ichi2.anki.dialogs.TagsDialog$TagsDialogListener.onPositive(java.util.List, int)' on a null object reference
at com.ichi2.anki.dialogs.TagsDialog.a(TagsDialog.java:3)
at com.ichi2.anki.dialogs.p1.onClick(lambda)
at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:7)
at android.view.View.performClick(View.java:6257)
at android.widget.TextView.performClick(TextView.java:11149)
at android.view.View$PerformClick.run(View.java:23705)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6780)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1500)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1390)
```

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description

An ACRA crash occurred as the listener was null.

Visually, this should never have occurred as the listener is set on the next line. It might not be possible to trigger by a human, but it's fixable

## Fixes
Fixes #6174

## Approach
Move the listener from a setter to a constructor parameter

## How Has This Been Tested?

Tested functionality on my phone, no visible change.

Effectively nonfunctional but I'd like to confirm this in an alpha release

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TagsDialog.java [hunk 1]
```diff
@@ -53,7 +53,8 @@
 
     private String mPositiveText;
     private String mDialogTitle;
-    private TagsDialogListener mTagsDialogListener = null;
+    @NonNull
+    private TagsDialogListener mTagsDialogListener;
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/TagsDialog.java:57]: Codacy Issue found: [Fields should be declared at the top of the class, before any method declarations, constructors, initializers or inner classes.](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5524070)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5524070&bid=18099683)

**Comment by mikehardy** [comment]
released in 2.11alpha5
