### PR TITLE
fix: prevent deck overlap by skipping redundant scroll for visible items

### LINKED ISSUE #19193: On Deck picker screen, decks visually overlap just after being tapped
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Make multiple decks which can't be seen wholly without scrolling.
   Image Image

2. Tap a decks that is not vertically centered and can be scrolled toward the center
   Image

 Result:
   Scrolling animation occurs, and some of the labels often overlap on my device:
   Image Image

https://github.com/user-attachments/assets/6ad976da-525c-45df-afe0-9f3a9b65de9d

### Expected behaviour

No overlapping. It looks cluttered.
Preferably, no scrolling-animation itself, as in 2.22.3 or below. The animation seems unnecessary and a bit distracting in this timing.

### Debug info

```text
AnkiDroid Version = 2.23.0alpha1 (4a620e654701c42db64b82c29832caea5f4bc0df)  
Backend Version = 0.1.60-anki25.07.5 (25.07.5 7172b2d26684c7ef9d10e249bd43dc5bf73ae00c)  
Android Version = 9 (SDK 28)  
ProductFlavor = full  
Device Info = OPPO | OPPO | OP47CFL1 | CPH1983 | CPH1983 | qcom  
Webview User Agent = Mozilla/5.0 (Linux; Android 9; CPH1983 Build/PKQ1.190519.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/138.0.7204.179 Mobile Safari/537.36  
ACRA UUID = 9245e5c8-0637-4154-9532-8b7459bbbd7f  
FSRS = 4.1.1 (Enabled: false)  
Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

- The overlapping has been reproduced in a device with Android 11
- Not reproduced in a device with Android 14

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting)) (2.23.0alpha3)

### PR DESCRIPTION
**Pull request by Ayush-Patel-56**
## Purpose / Description
Fixes visual overlapping of deck names/counts when a deck is tapped.

## Fixes
* Fixes #19193

## Approach
Skips the programmatic centering scroll if the deck is already visible to the user. This avoids a layout conflict between the scroll and the adapter's repaint.

## How Has This Been Tested?
Verified on Android 11 (API 30) emulator. Taps on visible decks are now smooth without glitches, and secondary focus (returning from reviewer) still centers correctly.

https://github.com/user-attachments/assets/e3e7a056-bd60-4bcf-997c-45d3cdf817fa

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison** [comment]
What's the debug info of the emulator you used to test? 

Tapping an empty deck should show the congrats screen successfully

**Comment by Ayush-Patel-56** [comment]
Debug Info: 
```
AnkiDroid Version = 2.24.0alpha7-debug (3d021cd09255a320a9d02fc8051d10456d1c783a)  
Backend Version = 0.1.63-anki25.09.2 (25.09.2 3890e12c9e48c028c3f12aa58cb64bd9f8895e30)  
Android Version = 11 (SDK 30)  
ProductFlavor = play  
Device Info = Google | google | generic_x86_arm | sdk_gphone_x86 | sdk_gphone_x86 | ranchu  
WebView Info = [com.google.android.webview | 410410681]: Mozilla/5.0 (Linux; Android 11; sdk_gphone_x86 Build/RSR1.240422.006; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.106 Mobile Safari/537.36  
ACRA UUID = 79647706-b83f-40d9-8d1a-6f2068b16230  
FSRS = 5.1.0 (Enabled: false)  
Crash Reports Enabled = false
```


Congrats Screen: I have verified the Congrats Screen on both a emulator (API 30) and a modern device.
- The white screen was a pre-existing issue on the emulator (API 30)  (it happened on main too).
- On a modern device, the "Congratulations! You have finished this deck for now" message appears perfectly.

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 1]
```diff
@@ -783,6 +783,11 @@ open class DeckPicker :
 
         fun onFocusedDeckChanged(deckId: DeckId?) {
             val position = deckId?.let { viewModel.findDeckPosition(it) } ?: 0
+            val firstVisible = decksLayoutManager.findFirstVisibleItemPosition()
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt]: Explain why this occurs to a reader.

* Add a comment, 
* Optionally add a `LinearLayoutManager.positionIsVisible(position: Int)` method so the intent of the code is obvious

```kotlin
if (decksLayoutManager.positionIsVisible(position)) {
    return
}
```

Comment (Ayush-Patel-56) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt]: Added the positionIsVisible helper to LinearLayoutManager.kt as suggested. Also put in a short comment explaining the issue.
