### PR TITLE
Crash fix due to `EditTextPreference` search field in CustomStudyDeck

### LINKED ISSUE #13581: [BUG]: Custom Study Settings Search Field causes crash
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Create a custom study deck
2. Open settings for custom study deck
3. Alter search field param Example remove `prop` or change it to `prp` or something else
4. Press back

### Expected behaviour

User is taken back to the previous activity

### Actual behaviour

Crash

### Debug info

```text
AnkiDroid Version = 2.16alpha97-debug

Android Version = 8.1.0

Manufacturer = Google

Model = Android SDK built for x86

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 8.1.0; Android SDK built for x86 Build/OSM1.180201.037; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/69.0.3497.100 Mobile Safari/537.36

ACRA UUID = f325816f-f0bc-406e-8135-e979ad8459f8

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by criticalAY**
## Purpose / Description
I am allowing the user to only see the search text for the deck and properties they selected which I think is the right thing to do as the text if altered and not matched with the required one causes an issue as I said on Discord 
There is another but that would require to creation of two new fields one for the deck and one for the property, deck field would be fine but the property field would be a mess as there are lists and limits or even text which are accepted as properties.

## Fixes
Fixes #13581

## How Has This Been Tested?

Tested on oneplus nord ce
Screenshot_35

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by BrayanDSO** [comment]
This setting shouldn’t be disabled. The user is supposed to be able to change their filtered decks queries as they please.

**Comment by criticalAY** [comment]
A slight mistake while changing the query causes a crash

**Comment by BrayanDSO** [comment]
Why not fix the crash instead of disabling functionality?

**Comment by criticalAY** [comment]
Umm I know from where the crash is occurring so ok can try to handle the crash itself

File: AnkiDroid/src/main/java/com/ichi2/libanki/sched/BaseSched.kt [hunk 1]
```diff
@@ -262,7 +264,11 @@ abstract class BaseSched(val col: Collection) {
      * @param did The deck to rebuild. 0 means current deck.
      */
     open fun rebuildDyn(did: DeckId) {
-        col.newBackend.backend.rebuildFilteredDeck(did)
+        try {
+            col.newBackend.backend.rebuildFilteredDeck(did)
+        } catch (e: BackendException) {
+            Timber.e(e, "Error rebuilding filtered deck: Invalid search query")
+        }
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/libanki/sched/BaseSched.kt:271]: this ignores the issue instead of fixing it

**Review by BrayanDSO — CHANGES_REQUESTED** [review]

**Comment by criticalAY** [comment]
we can not make this behave like other edit text preferences and display an error in the dialog itself but the best thing I can come up with is that comparing the string with regex and allowing and not allowing the user to depending on the syntax it works fine

**Comment by criticalAY** [comment]
I need little help here as the deck name can be anything so I want to update the regex but I am not able to fix it

**Comment by BrayanDSO** [comment]
If you see how it works on Anki Desktop, custom study decks are just filtered decks. The user should be able to use ANY query, not only queries with "deck:"

**Comment by criticalAY** [comment]
> If you see how it works on Anki Desktop, custom study decks are just filtered decks. The user should be able to use ANY query, not only queries with "deck:"

So this deck also needs to be removed then there only needs a check for some `foo1:"abc" foo2:xyz` basically the quotes and the colon

**Comment by criticalAY** [comment]
ok so now this would allow taking any string but would make sure that there is `" "` and two `:` in their respective places

**Comment by BrayanDSO** [comment]
As I said, Anki desktop accepts any queries, which include empty queries. I don't think that a RegEx should be used here

**Comment by criticalAY** [comment]
The logcat says it is related to the backend but we need to handle ti in some way either try-catch or modify the regex, do you have another solution that would suit better here?

**Comment by BrayanDSO** [comment]
Do you have the stacktrace?

**Comment by criticalAY** [comment]
yes wait

**Comment by criticalAY** [comment]
@BrayanDSO logcat stackstrace
```
net.ankiweb.rsdroid.BackendException$BackendSearchException: Invalid search: ⁨an opening double quote `"` was found, but there was no second one to close it. If you want to search for a literal `"`, prepend a backslash: `\"`.⁩
                                                                                                    	at net.ankiweb.rsdroid.BackendException$Companion.fromError(BackendException.kt:118)
                                                                                                    	at net.ankiweb.rsdroid.BackendKt.unpackResult(Backend.kt:323)
                                                                                                    	at net.ankiweb.rsdroid.BackendKt.access$unpackResult(Backend.kt:1)
                                                                                                    	at net.ankiweb.rsdroid.Backend$runMethodRaw$1.invoke(Backend.kt:130)
                                                                                                    	at net.ankiweb.rsdroid.Backend$runMethodRaw$1.invoke(Backend.kt:129)
                                                                                                    	at net.ankiweb.rsdroid.Backend.withBackend(Backend.kt:157)
                                                                                                    	at net.ankiweb.rsdroid.Backend.runMethodRaw(Backend.kt:129)
                                                                                                    	at anki.backend.GeneratedBackend.rebuildFilteredDeckRaw(GeneratedBackend.kt:1375)
                                                                                                    	at anki.backend.GeneratedBackend.rebuildFilteredDeck(GeneratedBackend.kt:1385)
                                                                                                    	at com.ichi2.libanki.sched.BaseSched.rebuildDyn(BaseSched.kt:265)
                                                                                                    	at com.ichi2.libanki.sched.SchedV2.rebuildDyn(SchedV2.kt:1796)
                                                                                                    	at com.ichi2.anki.FilteredDeckOptions.closeWithResult(FilteredDeckOptions.kt:261)
                                                                                                    	at com.ichi2.ui.AppCompatPreferenceActivity.onOptionsItemSelected(AppCompatPreferenceActivity.kt:298)
```

**Comment by BrayanDSO** [comment]
Desktop behavior:
image

I suggest try-catching the error and showing a dialog, as the desktop app does

**Comment by criticalAY** [comment]
I am updating the PR template with the new tested screenshot

File: AnkiDroid/src/main/res/values/02-strings.xml [hunk 2]
```diff
@@ -218,6 +218,8 @@
     <string name="sched_has_buried">Some related or buried cards were delayed until tomorrow</string>
     <string name="tag_editor_add_feedback">Touch “%2$s” to confirm adding “%1$s”</string>
     <string name="tag_editor_add_feedback_existing">Existing tag “%1$s” selected</string>
+    <string name="wrong_search_query">An opening double quote \" was found, but there was no second one to close it. If you want to search for a literal \", prepend a backslash: \\ \".</string>
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/res/values/02-strings.xml:221]: This text is the same found on the BackendException message, so get it from there

File: AnkiDroid/src/main/res/values/02-strings.xml [hunk 3]
```diff
@@ -218,6 +218,8 @@
...
+    <string name="search_filter_error">Search filter error</string>
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/res/values/02-strings.xml:222]: unnecessary

**Review by BrayanDSO — CHANGES_REQUESTED** [review]

File: AnkiDroid/src/main/res/values/02-strings.xml (hunk 2 above)
Comment (criticalAY) [reply AnkiDroid/src/main/res/values/02-strings.xml:221]: The error message contains the backend error..... Then the actual string

File: AnkiDroid/src/main/res/values/02-strings.xml (hunk 3 above)
Comment (criticalAY) [reply AnkiDroid/src/main/res/values/02-strings.xml:222]: Completely remove the title you mean?

Comment (BrayanDSO) [reply AnkiDroid/src/main/res/values/02-strings.xml:222]: or use a generic "Error" title, your choice

File: AnkiDroid/src/main/res/values/02-strings.xml (hunk 2 above)
Comment (BrayanDSO) [reply AnkiDroid/src/main/res/values/02-strings.xml:221]: When rebuilding a filtered deck with the new backend enabled, the shown message looks fine to me though

image

If are speaking about the "Invalid search:" string, I believe that it's a lot better to keep it instead of "duplicating" a string and add more work to the translators

File: AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt [hunk 4]
```diff
@@ -295,7 +298,12 @@ abstract class AppCompatPreferenceActivity<PreferenceHack : AppCompatPreferenceA
     @Deprecated("Deprecated in Java")
     override fun onOptionsItemSelected(item: MenuItem): Boolean {
         if (item.itemId == android.R.id.home) {
-            closeWithResult()
+            try {
+                closeWithResult()
+            } catch (e: BackendException) {
+                showSearchError(e)
+            }
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt:305]: You repeat this twice, maybe this could be extracted into a function?

Soft-approve after it. 

No major refactors are worth it because this class should be gone when we get rid of DeckOptions.kt (after the new backend is the default) and the filtered deck options screen either is migrated to the new androidx preferences library or someone implements a Svelte filtered deck screens that can be reused here (on my TODO list, actually because I can't find a filtered deck option on my iPad and would get rid of this task on AnkiDroid).

File: AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt [hunk 5]
```diff
@@ -304,12 +312,28 @@ abstract class AppCompatPreferenceActivity<PreferenceHack : AppCompatPreferenceA
...
+    private fun showSearchError(error: BackendException) {
+        Timber.e("Backend search exception")
+        val builder = AlertDialog.Builder(this)
+        builder.setTitle(getString(R.string.pref__widget_text__error))
+        builder.setMessage(error.message)
+        builder.setPositiveButton(getString(R.string.dialog_ok)) { dialog, _ ->
+            dialog.dismiss()
+        }
+        val dialog = builder.create()
+        dialog.show()
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt:334]:
```suggestion
            AlertDialog.Builder(this).show {
                setTitle(getString(R.string.pref__widget_text__error))
                setMessage(error.message)
                setPositiveButton(getString(R.string.dialog_ok)) { dialog, _ ->
                    dialog.dismiss()
                }
            }
```

**Review by BrayanDSO — CHANGES_REQUESTED** [review]

File: AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt (hunk 4 above)
Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt:305]: Umm yes its being used twice so we can but it is going to be removed soon so sure

**Comment by lukstbit** [comment]
@criticalAY In one of the review comments Brayan requested that you use the `show {}` extension method. Please use that, there's no reason to have:

```
AlertDialog.Builder().apply { 
      ...
     show()
}
```

when you can write 

```
AlertDialog.Builder().show { 
   ...
}
```

**Comment by criticalAY** [comment]
> @criticalAY In one of the review comments Brayan requested that you use the `show {}` extension method. Please use that, there's no reason to have:
> 
> ```
> AlertDialog.Builder().apply { 
>       ...
>      show()
> }
> ```
> 
> when you can write 
> 
> ```
> AlertDialog.Builder().show { 
>    ...
> }
> ```

I'm aware of that but we can't directly use `show` here I already tried that before making this PR and after Brayan suggested just to be sure.

**Comment by lukstbit** [comment]
> we can't directly use show here I already tried that before making this PR

Why we can't use the `show {}` extension method here?

**Comment by criticalAY** [comment]
> > we can't directly use show here I already tried that before making this PR
> 
> Why we can't use the `show {}` extension method here?

It was a import error, sorry, fixed it

File: AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt [hunk 6]
```diff
@@ -304,12 +306,27 @@ abstract class AppCompatPreferenceActivity<PreferenceHack : AppCompatPreferenceA
...
         if (keyCode == KeyEvent.KEYCODE_BACK && event.repeatCount == 0) {
             Timber.i("DeckOptions - onBackPressed()")
-            closeWithResult()
+            closedWithResult()
             return true
         }
         return super.onKeyDown(keyCode, event)
     }
 
+    private fun closedWithResult() {
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt:315]: I think it's confusing having very similar names such as closeWithResult() and closedWithResult()

Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt:315]: what else do you want me to rename it to?

Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt:315]: tryResult

Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt:315]: Yeah, tryCloseWithResult is fine enough

Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt:315]: Ok

File: AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt [hunk 7]
```diff
@@ -304,12 +306,27 @@ abstract class AppCompatPreferenceActivity<PreferenceHack : AppCompatPreferenceA
...
             return true
         }
         return super.onKeyDown(keyCode, event)
     }
 
+    private fun tryCloseWithResult() {
+        try {
+            closeWithResult()
+        } catch (e: BackendException) {
+            Timber.e("Backend search exception")
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt:319]:
```suggestion
            Timber.e(e, "Backend exception while trying to finish a AppCompatPreferenceActivity")
```

**Review by BrayanDSO — APPROVED** [review]
Lgtm, thanks!

**Review by lukstbit — APPROVED** [review]
