### PR TITLE
Fix: Widget - Missing storage permission causing NPE and crashing app

### LINKED ISSUE #13518: [Bug] Crash if using `Add note` widget or shortcuts before giving storage permission on `full` builds
###### Reproduction Steps

- tested on a `fullDebug` build
1. Don't have or remove the storage permission
2. Add the `Add note` widget to your screen
3. Tap the widget

###### Expected Result

Storage permission is asked correctly

###### Actual Result

Crashes

###### Debug info
Built with main d03d544c on SDK 33 emulator

```
ACRA caught a StorageAccessException for com.ichi2.anki.debug
                                                                                                    com.ichi2.anki.exception.StorageAccessException: No write access to AnkiDroid directory /storage/emulated/0/AnkiDroid
                                                                                                    	at com.ichi2.anki.CollectionHelper$Companion.initializeAnkiDroidDirectory(CollectionHelper.kt:369)
                                                                                                    	at com.ichi2.anki.CollectionManager.createCollectionPath(CollectionManager.kt:242)
                                                                                                    	at com.ichi2.anki.CollectionManager.ensureOpenInner(CollectionManager.kt:221)
                                                                                                    	at com.ichi2.anki.CollectionManager.access$ensureOpenInner(CollectionManager.kt:36)
                                                                                                    	at com.ichi2.anki.CollectionManager$getColUnsafe$1$1.invoke(CollectionManager.kt:276)
                                                                                                    	at com.ichi2.anki.CollectionManager$getColUnsafe$1$1.invoke(CollectionManager.kt:275)
                                                                                                    	at com.ichi2.anki.CollectionManager$withQueue$2.invokeSuspend(CollectionManager.kt:83)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@93ea1b6, Dispatchers.Main.immediate]
```

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### LINKED ISSUE #15686: [Bug] CardBrowser NullPointerException
likely due to no storage permissions

https://ankidroid.org/acra/app/1/bug/134200/report/db73fee5-8b77-4f20-bc05-a2aff3661cbf

```
java.lang.NullPointerException
	at com.ichi2.anki.CardBrowser$onCreate$11.invokeSuspend(SourceFile:117)
	at com.ichi2.anki.CardBrowser$onCreate$11.invoke(SourceFile:2)
	at com.ichi2.anki.CardBrowser$onCreate$11.invoke(SourceFile:1)
	at com.ichi2.anki.CardBrowser$launchCollectionInLifecycleScope$1$1.emit(SourceFile:3)
	at kotlinx.coroutines.flow.StateFlowImpl.collect(SourceFile:206)
	at kotlinx.coroutines.flow.ReadonlyStateFlow.collect(Unknown Source:2)
	at com.ichi2.anki.CardBrowser$launchCollectionInLifecycleScope$1.invokeSuspend(SourceFile:38)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(SourceFile:131)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(SourceFile:3)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(SourceFile:6)
	at kotlinx.coroutines.CoroutineStart.invoke(SourceFile:10)
	at kotlinx.coroutines.AbstractCoroutine.start(SourceFile:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(SourceFile:23)
	at kotlinx.coroutines.BuildersKt.launch(SourceFile:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(SourceFile:13)
	at kotlinx.coroutines.BuildersKt.launch$default(SourceFile:1)
	at com.ichi2.anki.CardBrowser.launchCollectionInLifecycleScope(SourceFile:15)
	at com.ichi2.anki.CardBrowser.onCreate(SourceFile:539)
	at android.app.Activity.performCreate(Activity.java:8000)
	at android.app.Activity.performCreate(Activity.java:7984)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3403)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3594)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2067)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7698)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@eeda772, Dispatchers.Main.immediate]

```

### PR DESCRIPTION
**Pull request by criticalAY**
## Purpose / Description
* #15698 PR tried to fix the widget issue but it introduced a bug in lower API (Android<=10) which I revert in   #15747
Here in this PR instead of disabling the widgets from manifest file, I updated the flow which is
* The shortcuts are not enabled until the storage access is granted using a return statement in the same function
* Widgets are enabled by default but if user tries to access the widget i.e. open it without storage permission then they are taken to storage permission screen. For existing user having the widgets(we can't update the existing widget that are already added) placing a check in the respective activities to handle the cases and showing a relevant toast that storage permission is missing 
* No existing widget is deleted 
* Not bound to any API level 

## Fixes
* Fixes #13518
* Fixes #15686

## How Has This Been Tested?
[widget_new_device.webm](https://github.com/ankidroid/Anki-Android/assets/48384865/a1c20b3d-33ff-42fd-a38f-0ba044c93e29)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt [hunk 1]
```diff
@@ -354,6 +354,16 @@ open class CardBrowser :
         tagsDialogFactory = TagsDialogFactory(this).attachToActivity<TagsDialogFactory>(this)
         exportingDelegate = ActivityExportingDelegate(this) { getColUnsafe }
         super.onCreate(savedInstanceState)
+        if (!IntentHandler.grantedStoragePermissions(this)) {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt:357]: This feels like it should be functionally equivalent to the check below, could you see if `hasCollectionStoragePermissions` can be updated?

File: AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt [hunk 2]
```diff
@@ -126,7 +126,7 @@ class IntentHandler : Activity() {
      */
     @NeedsTest("clicking a file in 'Files' to import")
     private fun performActionIfStorageAccessible(reloadIntent: Intent, action: String?, block: () -> Unit) {
-        if (!ScopedStorageService.isLegacyStorage(this) || hasStorageAccessPermission(this) || Permissions.isExternalStorageManagerCompat()) {
+        if (grantedStoragePermissions(this)) {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt:129]: ditto with the above comment

File: AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt [hunk 3]
```diff
@@ -74,6 +75,10 @@ class AnkiDroidWidgetSmall : AppWidgetProvider() {
 
         override fun onStart(intent: Intent, startId: Int) {
             Timber.i("SmallWidget: OnStart")
+            if (!grantedStoragePermissions(this)) {
+                Timber.i("Opening AnkiDroid Small widget without storage access")
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt:79]: This feels like a `Timber.w`

Inform the developer that the function stopped

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt:79]: I believe this needs to be handled on more than `onStart`

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt [hunk 4]
```diff
@@ -494,8 +504,14 @@ class NoteEditor : AnkiActivity(), DeckSelectionListener, SubtitleListener, Tags
                 currentEditedCard = col.getCard(id)
                 editorNote = currentEditedCard!!.note(getColUnsafe)
             }
-            CALLER_STUDYOPTIONS, CALLER_DECKPICKER, CALLER_REVIEWER_ADD, CALLER_CARDBROWSER_ADD, CALLER_NOTEEDITOR ->
+            CALLER_STUDYOPTIONS, CALLER_DECKPICKER, CALLER_REVIEWER_ADD, CALLER_CARDBROWSER_ADD, CALLER_NOTEEDITOR -> {
+                if (!IntentHandler.grantedStoragePermissions(this)) {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:508]: Why is this needed if `finish() + return` is called inside `onCreate`

**Review by david-allison — CHANGES_REQUESTED** [review]

**Comment by mikehardy** [comment]
May not make it into 2.17.4 but if not, 2.17.5 would be nice - will rework milestone names after the 2.17.2 release pipeline failure unexpectedly burnt a number

**Comment by criticalAY** [comment]
@david-allison I made some changes (nitpicks in the recent push) I hope you are through them?

**Comment by david-allison** [comment]
Re-reviewed after the push, still good to go

**Comment by mikehardy** [comment]
🤔 ominous sign

```

com.ichi2.anki.FieldEditLineTest > testSaveRestore[emulator-5554 - 11] FAILED 
	java.lang.NullPointerException: Cannot run onActivity since Activity has been destroyed already
	at androidx.test.internal.util.Checks.checkNotNull(Checks.java:45)

com.ichi2.anki.FieldEditLineTest > testSetters[emulator-5554 - 11] FAILED 
	java.lang.NullPointerException: Cannot run onActivity since Activity has been destroyed already
	at androidx.test.internal.util.Checks.checkNotNull(Checks.java:45)
```

re-running.

**Comment by criticalAY** [comment]
Looking into it

**Comment by criticalAY** [comment]
Let's wait for the CI to run this time, here is to hoping noting is wrong this time

**Comment by criticalAY** [comment]
I think we will have to update the test as we return early, so no merge today

**Comment by criticalAY** [comment]
@david-allison @mikehardy Removed one test as in CardBrowser replaced certain outdated code, apart from that we skip the method i.e. instrumented test or unit test

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt [hunk 5]
```diff
@@ -487,11 +488,25 @@ abstract class AbstractFlashcardViewer :
...
+            return
+        }
+    }
+
     // ----------------------------------------------------------------------------
     // ANDROID METHODS
     // ----------------------------------------------------------------------------
     override fun onCreate(savedInstanceState: Bundle?) {
         restorePreferences()
+        checkAndHandleStoragePermissions(savedInstanceState)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt:509]: This no longer returns early, as the return is extracted to the method

Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt:509]: If we call `restorePreferences()` after this we can return early

Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt]: One more mistake I found, I made changes to Abstract flashcard class idk why but it was supposed to be Reviewer

**Comment by criticalAY** [comment]
Updated test
Screen_recording_20240305_034627.webm

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt [hunk 6]
```diff
@@ -344,27 +343,38 @@ open class CardBrowser :
         }
     }
 
+    /**
+     * Checks if storage permissions are granted. If not, shows a toast message,
+     * finishes the activity, and displays a dialog for permissions in case of [wasLoadedFromExternalTextActionItem].
+     * This method should be called before calling super.onCreate(savedInstanceState).
+     */
+    private fun checkAndHandleStoragePermissions(savedInstanceState: Bundle?): Boolean {
+        if (!grantedStoragePermissions(this) && !AdaptionUtil.isRunningAsUnitTest) {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt:352]: Flip the if and return early

File: AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt [hunk 7]
```diff
@@ -381,41 +377,6 @@ class CardBrowserTest : RobolectricTest() {
         return cardBrowser.getPropertiesForCardId(cardId).card.userFlag()
     }
 
-    @Test
-    fun startupFromCardBrowserActionItemShouldEndActivityIfNoPermissions() {
```
Comment (david-allison) [inline AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt:385]: Can you fix this test rather then remove it (mock the new method to fail)

**Comment by mikehardy** [comment]
Question: why didn't `./gradlew jacocoTestReport` see this on your machine prior to posting the PR?

File: AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt (hunk 7 above)
Comment (criticalAY) [reply AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt:385]: Done!

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt (hunk 6 above)
Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt:357]: I messed up the commit message and will update it and apply this suggestion once I'm home

**Comment by criticalAY** [comment]
> Question: why didn't ./gradlew jacocoTestReport see this on your machine prior to posting the PR?

Will do in future commits

**Comment by criticalAY** [comment]
Reason for not returning early: the super call gets executed which prevents the actual onCreate body from being executed hence reverting it,
`./gradlew jacocoTestReport` passed all tests except Tablet as the emulator it ran a test on was a Pixel 8 device

**Review by david-allison — APPROVED** [review]
I'll leave it to reviewer 2 to suggest changes to calling `super.onCreate()` from inside those methods, it's unusual and will lead to bugs

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt b/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt	(revision 33fda02ce126762fd1fe4ac5512634fd6a5accd5)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt	(date 1709645946821)
@@ -349,17 +349,17 @@
      * This method should be called before calling super.onCreate(savedInstanceState).
      */
     private fun checkAndHandleStoragePermissions(savedInstanceState: Bundle?): Boolean {
-        if (!grantedStoragePermissions(this) && !AdaptionUtil.isRunningAsUnitTest) {
-            super.onCreate(savedInstanceState)
-            Timber.w("'Card Browser' Action item pressed before storage permissions granted.")
-            if (wasLoadedFromExternalTextActionItem()) {
-                // we need to do this as DeckPicker still contains app init logic/upgrade logic
-                displayDeckPickerForPermissionsDialog()
-            }
-            finish()
-            return false
-        }
-        return true
+        if (grantedStoragePermissions(this) || AdaptionUtil.isRunningAsUnitTest) {
+            return true
+        }
+        super.onCreate(savedInstanceState)
+        Timber.w("'Card Browser' Action item pressed before storage permissions granted.")
+        if (wasLoadedFromExternalTextActionItem()) {
+            // we need to do this as DeckPicker still contains app init logic/upgrade logic
+            displayDeckPickerForPermissionsDialog()
+        }
+        finish()
+        return false
     }
 
     override fun onCreate(savedInstanceState: Bundle?) {
```

**Comment by criticalAY** [comment]
The only reason to have super call here is because tag factory class is init before super call in `onCreate` that's why we need to check storage access before that other there isn't any need

**Comment by criticalAY** [comment]
Returning early at both classes now

**Comment by mikehardy** [comment]
This is problematic for me as a comment:

> I'll leave it to reviewer 2 to suggest changes to calling super.onCreate() from inside those methods, it's unusual and will lead to bugs

In combination with the frequent need for followups and fixups and reverts and such on previous work

I haven't reviewed deeply enough to say one way or the other but I'm concerned about general level of quality in the past and I'm looking to merge + cherry-pick fixes for the release branch - given history and this comment I pass on spending time on this one until maybe some future date I have time

Though any other reviewer that has time to look, obviously please do

**Review by david-allison — CHANGES_REQUESTED** [review]
* don't log in a getter
* Each of the 3 scenarios: CardBrowswr, Reviewer & NoteEditor had the same general concept: storage permissions has not been granted, so don't start the activity. This was extracted to `AnkiActivity`
  *  It seemed easier to log a generic 'activity finishing' message than providing a specific message per activity 
* CardBrowser needed the `ViewModel` to be conditionally initalized if storage permissions were granted

```patch
Subject: [PATCH] chore(log): CardBrowserViewModel

The logs helps with diagnostics when the collection is inaccessible
---
Index: AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt b/AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt
--- a/AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt	(revision b1f87895395df8436e442eebd1bb87737acfc969)
+++ b/AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.kt	(date 1709819584379)
@@ -147,23 +147,6 @@
             Timber.d("isRunningAsUnitTest: %b", true)
             return true
         }
-
-    /**
-     * Checks if the code is running as part of an Android instrumentation test.
-     * This property detects if the Espresso testing library is available on the classpath,
-     * which indicates that the code is being executed within an Android instrumentation test.
-     */
-    val isRunningAsAndroidTest: Boolean
-        get() {
-            try {
-                Class.forName("androidx.test.espresso.Espresso")
-            } catch (ignored: ClassNotFoundException) {
-                Timber.d("isRunningAsAndroidTest: %b", false)
-                return false
-            }
-            Timber.d("isRunningAsAndroidTest: %b", true)
-            return true
-        }
 }
 
 val isRobolectric get() = Build.FINGERPRINT?.startsWith("robolectric") ?: false
Index: AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt b/AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt
--- a/AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt	(revision b1f87895395df8436e442eebd1bb87737acfc969)
+++ b/AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.kt	(date 1709818646800)
@@ -388,7 +388,7 @@
             mockkObject(AdaptionUtil)
             mockkObject(IntentHandler)
 
-            every { grantedStoragePermissions(any()) } returns false
+            every { grantedStoragePermissions(any(), any()) } returns false
             every { AdaptionUtil.isRunningAsUnitTest } returns false
 
             val browserController = Robolectric.buildActivity(CardBrowser::class.java).create()
Index: AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt b/AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt
--- a/AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt	(revision b1f87895395df8436e442eebd1bb87737acfc969)
+++ b/AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.kt	(date 1709818717712)
@@ -39,7 +39,7 @@
 class AnkiDroidWidgetSmall : AppWidgetProvider() {
     override fun onUpdate(context: Context, appWidgetManager: AppWidgetManager, appWidgetIds: IntArray) {
         Timber.d("SmallWidget: onUpdate")
-        if (!grantedStoragePermissions(context)) {
+        if (!grantedStoragePermissions(context, showToast = false)) {
             Timber.w("Opening AnkiDroid Small widget without storage access")
             return
         }
Index: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt	(revision b1f87895395df8436e442eebd1bb87737acfc969)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt	(date 1709819452184)
@@ -353,14 +353,12 @@
         tagsDialogFactory = TagsDialogFactory(this).attachToActivity<TagsDialogFactory>(this)
         mediaRegistration = MediaRegistration(this)
         super.onCreate(savedInstanceState)
+        if (!ensureStoragePermissions()) {
+            return
+        }
         fieldState.setInstanceState(savedInstanceState)
         setContentView(R.layout.note_editor)
         val intent = intent
-        if (!IntentHandler.grantedStoragePermissions(this) && !AdaptionUtil.isRunningAsAndroidTest) {
-            Timber.w("No storage access")
-            finish()
-            return
-        }
         if (savedInstanceState != null) {
             caller = savedInstanceState.getInt("caller")
             addNote = savedInstanceState.getBoolean("addNote")
Index: AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt b/AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt	(revision b1f87895395df8436e442eebd1bb87737acfc969)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt	(date 1709818646778)
@@ -126,7 +126,7 @@
      */
     @NeedsTest("clicking a file in 'Files' to import")
     private fun performActionIfStorageAccessible(reloadIntent: Intent, action: String?, block: () -> Unit) {
-        if (grantedStoragePermissions(this)) {
+        if (grantedStoragePermissions(this, showToast = true)) {
             Timber.i("User has storage permissions. Running intent: %s", action)
             block()
         } else {
@@ -267,7 +267,7 @@
             return !isInvalidViewIntent(intent)
         }
 
-        fun grantedStoragePermissions(context: Context, showToast: Boolean = true): Boolean {
+        fun grantedStoragePermissions(context: Context, showToast: Boolean): Boolean {
             val granted = !ScopedStorageService.isLegacyStorage(context) || hasStorageAccessPermission(context) || Permissions.isExternalStorageManagerCompat()
 
             if (!granted && showToast) {
Index: AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt b/AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt	(revision b1f87895395df8436e442eebd1bb87737acfc969)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt	(date 1709818646796)
@@ -420,7 +420,7 @@
         const val EXTRA_STARTED_WITH_SHORTCUT = "com.ichi2.anki.StartedWithShortcut"
 
         fun enablePostShortcut(context: Context) {
-            if (!IntentHandler.grantedStoragePermissions(context, false)) {
+            if (!IntentHandler.grantedStoragePermissions(context, showToast = false)) {
                 Timber.w("No storage access, not enabling shortcuts")
                 return
             }
Index: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt b/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt	(revision b1f87895395df8436e442eebd1bb87737acfc969)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt	(date 1709819452189)
@@ -168,28 +168,14 @@
         FlashCardViewerResultCallback()
     )
 
-    /**
-     * Checks if storage permissions are granted. If not, shows a toast message,
-     * finishes the activity, This method should be called before calling super.onCreate(savedInstanceState).
-     */
-    private fun checkAndHandleStoragePermissions(savedInstanceState: Bundle?): Boolean {
-        if (IntentHandler.grantedStoragePermissions(this) || AdaptionUtil.isRunningAsUnitTest) {
-            return true
-        }
-        super.onCreate(savedInstanceState)
-        Timber.w("'Study' Action item pressed before storage permissions granted.")
-        finish()
-        return false
-    }
-
     override fun onCreate(savedInstanceState: Bundle?) {
         if (showedActivityFailedScreen(savedInstanceState)) {
             return
         }
-        if (!checkAndHandleStoragePermissions(savedInstanceState)) {
+        super.onCreate(savedInstanceState)
+        if (!ensureStoragePermissions()) {
             return
         }
-        super.onCreate(savedInstanceState)
         colorPalette = findViewById(R.id.whiteboard_editor)
         answerTimer = AnswerTimer(findViewById(R.id.card_time))
         textBarNew = findViewById(R.id.new_number)
Index: AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt b/AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt	(revision b1f87895395df8436e442eebd1bb87737acfc969)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt	(date 1709819452192)
@@ -544,6 +544,24 @@
         finish()
     }
 
+
+    /**
+     * If storage permissions are not granted, shows a toast message and finishes the activity.
+     *
+     * This should be called AFTER a call to `super.`[onCreate]
+     *
+     * @return `true`: activity may continue to start, `false`: [onCreate] should stop executing
+     * as storage permissions are mot granted
+     */
+    fun ensureStoragePermissions(): Boolean {
+        if (IntentHandler.grantedStoragePermissions(this, showToast = true)) {
+            return true
+        }
+        Timber.w("finishing activity. No storage permission")
+        finish()
+        return false
+    }
+
     companion object {
         const val DIALOG_FRAGMENT_TAG = "dialog"
 
Index: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt b/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt	(revision b1f87895395df8436e442eebd1bb87737acfc969)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt	(date 1709819452176)
@@ -40,7 +40,6 @@
 import com.ichi2.anim.ActivityTransitionAnimation.Direction
 import com.ichi2.anki.CollectionManager.TR
 import com.ichi2.anki.CollectionManager.withCol
-import com.ichi2.anki.IntentHandler.Companion.grantedStoragePermissions
 import com.ichi2.anki.Previewer.Companion.toIntent
 import com.ichi2.anki.browser.CardBrowserColumn
 import com.ichi2.anki.browser.CardBrowserColumn.Companion.COLUMN1_KEYS
@@ -343,38 +342,19 @@
         }
     }
 
-    /**
-     * Checks if storage permissions are granted. If not, shows a toast message,
-     * finishes the activity, and displays a dialog for permissions in case of [wasLoadedFromExternalTextActionItem].
-     * This method should be called before calling super.onCreate(savedInstanceState).
-     */
-    private fun checkAndHandleStoragePermissions(savedInstanceState: Bundle?): Boolean {
-        if (grantedStoragePermissions(this) || AdaptionUtil.isRunningAsUnitTest) {
-            return true
-        }
-        super.onCreate(savedInstanceState)
-        Timber.w("'Card Browser' Action item pressed before storage permissions granted.")
-        if (wasLoadedFromExternalTextActionItem()) {
-            // we need to do this as DeckPicker still contains app init logic/upgrade logic
-            displayDeckPickerForPermissionsDialog()
-        }
-        finish()
-        return false
-    }
-
     override fun onCreate(savedInstanceState: Bundle?) {
         if (showedActivityFailedScreen(savedInstanceState)) {
             return
         }
-        if (!checkAndHandleStoragePermissions(savedInstanceState)) {
-            return
-        }
-        // must be called after showedActivityFailedScreen
-        viewModel = createViewModel()
-
         tagsDialogFactory = TagsDialogFactory(this).attachToActivity<TagsDialogFactory>(this)
         exportingDelegate = ActivityExportingDelegate(this) { getColUnsafe }
         super.onCreate(savedInstanceState)
+        if (!ensureStoragePermissions()) {
+            return
+        }
+        // must be called once we have an accessible collection
+        viewModel = createViewModel()
+
         launchOptions = intent?.toCardBrowserLaunchOptions() // must be called after super.onCreate()
         setContentView(R.layout.card_browser)
         initNavigationDrawer(findViewById(android.R.id.content))
@@ -829,23 +809,6 @@
         }
     }
 
-    private fun displayDeckPickerForPermissionsDialog() {
-        // TODO: Combine this with class: IntentHandler after both are well-tested
-        val deckPicker = Intent(this, DeckPicker::class.java)
-        deckPicker.action = Intent.ACTION_MAIN
-        deckPicker.addCategory(Intent.CATEGORY_LAUNCHER)
-        deckPicker.flags = Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TASK
-        startActivity(deckPicker)
-        finish()
-        this.setResult(RESULT_CANCELED)
-    }
-
-    private fun wasLoadedFromExternalTextActionItem(): Boolean {
-        val intent = this.intent ?: return false
-        // API 23: Replace with Intent.ACTION_PROCESS_TEXT
-        return "android.intent.action.PROCESS_TEXT".equals(intent.action, ignoreCase = true)
-    }
-
     private fun updatePreviewMenuItem() {
         previewItem?.isVisible = viewModel.rowCount > 0
     }
Index: AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.kt b/AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.kt
--- a/AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.kt	(revision b1f87895395df8436e442eebd1bb87737acfc969)
+++ b/AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.kt	(date 1709818717714)
@@ -39,7 +39,7 @@
 
     override fun onUpdate(context: Context, appWidgetManager: AppWidgetManager, appWidgetIds: IntArray) {
         super.onUpdate(context, appWidgetManager, appWidgetIds)
-        if (!IntentHandler.grantedStoragePermissions(context)) {
+        if (!IntentHandler.grantedStoragePermissions(context, showToast = false)) {
             Timber.w("Opening AddNote widget without storage access")
             return
         }

```

**Review by david-allison — APPROVED** [review]
Round 2, let's try this one again

File: AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.kt [hunk 8]
```diff
@@ -38,6 +39,10 @@ class AddNoteWidget : AppWidgetProvider() {
 
     override fun onUpdate(context: Context, appWidgetManager: AppWidgetManager, appWidgetIds: IntArray) {
         super.onUpdate(context, appWidgetManager, appWidgetIds)
+        if (!IntentHandler.grantedStoragePermissions(context, showToast = false)) {
```
Comment (lukstbit) [inline AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.kt:42]: This change makes this instance of the AddNoteWidget to not start the NoteEditor:

- install app(no permission yet)
- add the AddNoteWidget to the screen(at this point the actual initialization in onUpdate is ignored(including starting NoteEditor on click)), the app does not crash so it's a plus
- go through the app and offer the permission
- click on the AddNoteWidget and see that it starts DeckPicker(standard intent?) not the NoteEditor(because of the permission not being available, its action wasn't set and the widget doesn't update itself so onUpdate is not called again)
- if you add another AddNoteWidget that works correctly as it picks the new permissions

To be honest I'm not sure how to fix this.

Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.kt:42]: I placed this code in the service first, where it worked fine but now here its buggy again, let me see to it, this issue is taking forever now lmao but okay...

Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.kt:42]: The intent is never placed hence the issue, can resolve it using a broadcast receiver

Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.kt:42]: Fixed it

**Comment by criticalAY** [comment]
https://github.com/ankidroid/Anki-Android/assets/48384865/894952d9-6917-4577-b634-86c3ad676d72

File: AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.kt (hunk 8 above)
Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.kt:42]: I have provided the updated test below

File: AnkiDroid/src/main/AndroidManifest.xml [hunk 9]
```diff
@@ -554,6 +554,13 @@
             </intent-filter>
         </receiver>
 
+        <receiver android:name="com.ichi2.widget.WidgetPermissionReceiver"
```
Comment (david-allison) [inline AnkiDroid/src/main/AndroidManifest.xml:557]: I'd propose splitting out the widget-related changes into a separate PR, there's more complexity being added here, and the activity- related changes can be merged immediately

Comment (criticalAY) [reply AnkiDroid/src/main/AndroidManifest.xml:557]: Ok 🆗

**Review by lukstbit — APPROVED** [review]
Ok, with the expectation of a follow up PR for the widget update.

**Comment by criticalAY** [comment]
There is some electricity issue here today, so as soon as it's fixed I'll drop a PR
