### PR TITLE
fix: handle unencoded `#` in file paths

### LINKED ISSUE #15963: [BUG]: Can't display images with `#` in filenames
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Add a card including an image file containing `#` (hashtag) in its filename

   ---
   

   ---
   

   ---
   

   ---

3. Show the card in reviewer or previewer

### Expected behaviour

The image is shown, as on 2.16.5.

(2.16.5)

### Actual behaviour

The broken-image icon is shown, and the image isn't shown.

### Debug info

```text
AnkiDroid Version = 2.17.6 (568538896be943818ca793dd2635822265712def)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 11 (SDK 30)

ProductFlavor = play

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.119 Mobile Safari/537.36

ACRA UUID = df169a4d-29ec-46b6-b114-141ca7e01ba3

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

- Originally reported in Anki Forum:
https://forums.ankiweb.net/t/ankiweb-and-ankidroid-do-not-display-images-containing-pound-hashtag-sharp-symbol/42444/1
  and dae has commented there.

- As reported there, this issue occurs on AnkiWeb, too. 
   image
So, strictly speaking, this is not a bug specific to AnkiDroid, but some approach specific to AnkiDroid may be needed, I'm not sure though.

- This issue doesn't occur on Anki Desktop (as reported in Anki Forum) and on AnkiMobile.
- The `#` is shown as `%23` on the editor of Anki Desktop (as reported in Anki Forum). 
   image
   > \> Windows changes it back to a # in the sort field, but the HTML text remains unchanged
   >
   > This happens because Anki stores filenames without encoding on disk (legacy reasons), but needs to encode them before they’re shown in the editor.

   (dae)

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting)) (2.18alpha6)

### PR DESCRIPTION
**Pull request by BrayanDSO**
For "legacy reasons" (https://forums.ankiweb.net/t/ankiweb-and-ankidroid-do-not-display-images-containing-pound-hashtag-sharp-symbol/42444/5), anki accepts unencoded `#` in file paths, although that is an URL syntax breakage.

## Fixes
* Fixes #15963

## Approach

I broke the URL syntax by adding the URL fragment as well while parsing the file source

## How Has This Been Tested?

Emulator 34: opened this deck https://ankiweb.net/shared/info/789434294

## Learning (optional, can help others)

Anki sometimes complicates its life more than it should.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt [hunk 1]
```diff
@@ -363,9 +363,18 @@ fun parseSourcesToFileScheme(content: String, mediaDir: String): String {
                 continue
             }
             if (attrUri.scheme != null) continue
-
-            val path = Paths.get(mediaDir, attrUri.path).toString()
-            val newUri = getFileUri(path)
+            attrUri.userInfo
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt:366]: I don't understand this line

Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt]: And voilà, it's gone like a magic trick. You never saw that line

**Review by david-allison — APPROVED** [review]

**Review by krmanik — APPROVED** [review]
