### PR TITLE
Fix color scheme for empty cards report dialog

### LINKED ISSUE #17982: Empty cards dialog has white background in Black theme
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

- Enable Black theme
- Have an empty card in your collection
- Click Check -> Empty cards from the deck picker

### Expected behaviour

A dark background is expected but a white background is shown instead.

### Debug info

```text
AnkiDroid 2.21 alpha 12
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by lukstbit**
## Purpose / Description

Replaced the previous implementation using an _WebView_ with a _TextView_ using _HtmlCompat_ and text spans for the click behavior. Also added a test to prevent unexpected backend changes to the html report structure that we expect.

<details>
<summary>How it looks with the fix</summary>

Screenshot from 2025-02-15 12-24-46
Screenshot from 2025-02-15 12-24-24
Screenshot from 2025-02-15 12-24-05
Screenshot from 2025-02-15 12-23-46
Screenshot from 2025-02-15 12-22-57
Screenshot from 2025-02-15 12-22-37
Screenshot from 2025-02-15 12-22-16
Screenshot from 2025-02-15 12-21-12

</details>

## Fixes
* Fixes #17982

## How Has This Been Tested?

Ran the tests, checked all themes, checked the expected behavior.

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/EmptyCardsDialogFragment.kt [hunk 1]
```diff
@@ -198,24 +183,62 @@ class EmptyCardsDialogFragment : DialogFragment() {
...
+        val spannableReport =
+            SpannableStringBuilder(HtmlCompat.fromHtml(report, HtmlCompat.FROM_HTML_MODE_LEGACY))
+        ankiNidPattern.findAll(spannableReport).forEach { result ->
+            // for an entry like [anki:nid:1234] we should have 4 groups: the entire match(
+            // [anki:nid:1234]) and the three groups we defined: '[anki:nid:', '1234', ']'
+            if (result.groups.size != 4) return@forEach
+            val matchedPrefix = result.groups[1] ?: return@forEach
+            val matchedNid = result.groups[2] ?: return@forEach
+            val nid = matchedNid.value.toLongOrNull() ?: return@forEach
+            val matchedSuffix = result.groups[3] ?: return@forEach
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/EmptyCardsDialogFragment.kt:202]: This felt complex enough to be a class

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/EmptyCardsDialogFragment.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/EmptyCardsDialogFragment.kt b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/EmptyCardsDialogFragment.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/EmptyCardsDialogFragment.kt	(revision 5b49b5fad6ea1b7fb0dff40dad1963c30dec3159)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/EmptyCardsDialogFragment.kt	(date 1739623318102)
@@ -57,6 +57,7 @@
 import com.ichi2.anki.launchCatchingTask
 import com.ichi2.anki.ui.internationalization.toSentenceCase
 import com.ichi2.anki.withProgress
+import com.ichi2.libanki.NoteId
 import com.ichi2.libanki.emptyCids
 import com.ichi2.utils.message
 import com.ichi2.utils.positiveButton
@@ -187,34 +188,63 @@
      * just the nid as a [ClickableSpan] which will trigger a [CardBrowser] search for that nid.
      */
     private fun EmptyCardsReport.asActionableReport(): SpannableStringBuilder {
-        // https://github.com/ankitects/anki/blob/de7a693465ca302e457a4767c7f213c76478f0ee/qt/aqt/emptycards.py#L56-L60
-        @Suppress("RegExpRedundantEscape")
-        val ankiNidPattern = Regex("(\\[anki:nid:)(\\d+)(\\])")
         val spannableReport =
             SpannableStringBuilder(HtmlCompat.fromHtml(report, HtmlCompat.FROM_HTML_MODE_LEGACY))
-        ankiNidPattern.findAll(spannableReport).forEach { result ->
-            // for an entry like [anki:nid:1234] we should have 4 groups: the entire match(
-            // [anki:nid:1234]) and the three groups we defined: '[anki:nid:', '1234', ']'
-            if (result.groups.size != 4) return@forEach
-            val matchedPrefix = result.groups[1] ?: return@forEach
-            val matchedNid = result.groups[2] ?: return@forEach
-            val nid = matchedNid.value.toLongOrNull() ?: return@forEach
-            val matchedSuffix = result.groups[3] ?: return@forEach
+        AnkiNidTag.parseFromReport(spannableReport).forEach { tag ->
             // make nid clickable
             spannableReport.setSpan(
-                BrowserSearchByNidSpan(requireContext(), nid),
-                matchedNid.range.first,
-                matchedNid.range.last + 1,
+                BrowserSearchByNidSpan(requireContext(), tag.nid),
+                tag.matchedNid.range.first,
+                tag.matchedNid.range.last + 1,
                 Spanned.SPAN_EXCLUSIVE_EXCLUSIVE,
             )
-            // remove suffix
-            spannableReport.delete(matchedSuffix.range.first, matchedSuffix.range.last + 1)
-            // remove prefix
-            spannableReport.delete(matchedPrefix.range.first, matchedPrefix.range.last + 1)
+
+            spannableReport.delete(tag.matchedSuffix)
+            spannableReport.delete(tag.matchedPrefix)
         }
         return spannableReport
     }
 
+    private fun SpannableStringBuilder.delete(group: MatchGroup) {
+        delete(group.range.first, group.range.last + 1)
+    }
+
+    /**
+     * Represents a Regex over `[anki:nid:1234]`
+     *
+     * @param matchedPrefix `[anki:nid:
+     * @param matchedNid `1234`
+     * @param nid `1234`
+     * @param matchedSuffix `]`
+     */
+    private class AnkiNidTag(
+        val matchedPrefix: MatchGroup,
+        val matchedNid: MatchGroup,
+        val nid: NoteId,
+        val matchedSuffix: MatchGroup,
+    ) {
+
+        companion object {
+            // https://github.com/ankitects/anki/blob/de7a693465ca302e457a4767c7f213c76478f0ee/qt/aqt/emptycards.py#L56-L60
+            @Suppress("RegExpRedundantEscape")
+            private val ankiNidPattern = Regex("(\\[anki:nid:)(\\d+)(\\])")
+
+            fun parseFromReport(report: SpannableStringBuilder): List<AnkiNidTag> {
+                return ankiNidPattern.findAll(report).mapNotNull { result ->
+                    // for an entry like [anki:nid:1234] we should have 4 groups: the entire match(
+                    // [anki:nid:1234]) and the three groups we defined: '[anki:nid:', '1234', ']'
+                    if (result.groups.size != 4) return@mapNotNull null
+                    val matchedPrefix = result.groups[1] ?: return@mapNotNull null
+                    val matchedNid = result.groups[2] ?: return@mapNotNull null
+                    val nid = matchedNid.value.toLongOrNull() ?: return@mapNotNull null
+                    val matchedSuffix = result.groups[3] ?: return@mapNotNull null
+
+                   AnkiNidTag(matchedPrefix, matchedNid, nid, matchedSuffix)
+                }.toList()
+            }
+        }
+    }
+
     /**
      * A specialized [ClickableSpan] that on click will open the [CardBrowser] and initiate a
      * search with the passed [nid].
```

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/EmptyCardsDialogFragment.kt [hunk 2]
```diff
@@ -198,24 +183,62 @@ class EmptyCardsDialogFragment : DialogFragment() {
...
+     * @see CardBrowser
+     */
+    private class BrowserSearchByNidSpan(
+        val context: Context,
+        val nid: Long,
+    ) : ClickableSpan() {
+        override fun onClick(widget: View) {
+            val browserSearchIntent = Intent(context, CardBrowser::class.java)
+            browserSearchIntent.putExtra("search_query", "nid:$nid")
+            browserSearchIntent.putExtra("all_decks", true)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/EmptyCardsDialogFragment.kt:231]: nit: Feels like it should be a class to document the CardBrowser public API

**Review by david-allison — APPROVED** [review]
LGTM, optional nitpicks

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/EmptyCardsDialogFragment.kt (hunk 1 above)
Comment (lukstbit) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/EmptyCardsDialogFragment.kt]: Thanks for the patch. I had to do one change, returning the sequence in _parseFromReport()_. If we use the terminal _toList()_ then the ranges are fixed and when we later try to delete the SpannableString doesn't resize so we overshoot the indexes and crash.

Initially I thought about a delete helper, but decided against it as I usually consider it for >= 3 usages, especially for these one line methods.

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/EmptyCardsDialogFragment.kt (hunk 2 above)
Comment (lukstbit) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/EmptyCardsDialogFragment.kt:261]: It's out of scope.

We have a class for this but it's used internally: _CardBrowserLaunchOptions.SearchQueryJs_. I'm not in favor of this, there's only the search query plus an optional booleans, seems verbose to introduce a class for this.

But I think there should be documentation for CardBrowser at least linking to CardBrowserLaunchOptions if not adding some words about it.

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/EmptyCardsDialogFragment.kt:261]: 👍 We need tighter contracts for inter-activity communication, but not for this PR

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/EmptyCardsDialogFragment.kt (hunk 1 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/EmptyCardsDialogFragment.kt]: I probably err on the 'too many extension methods' camp, but those were pretty hairy lines, yet the concept was very simple

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/EmptyCardsDialogFragment.kt [hunk 3]
```diff
@@ -198,24 +184,91 @@ class EmptyCardsDialogFragment : DialogFragment() {
...
+        val matchedNid: MatchGroup,
+        val nid: NoteId,
+        val matchedSuffix: MatchGroup,
+    ) {
+        companion object {
+            // https://github.com/ankitects/anki/blob/de7a693465ca302e457a4767c7f213c76478f0ee/qt/aqt/emptycards.py#L56-L60
+            @Suppress("RegExpRedundantEscape")
+            private val ankiNidPattern = Regex("(\\[anki:nid:)(\\d+)(\\])")
+
+            fun parseFromReport(report: SpannableStringBuilder): Sequence<AnkiNidTag> {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/EmptyCardsDialogFragment.kt:232]: document why this needs to be a sequence

**Review by david-allison — APPROVED** [review]
Approval still stands

**Review by BrayanDSO — APPROVED** [review]
Really good. I tried using `ClickableSpan` in the last PR, but didn't manage in the first try. Great job!
