### PR TITLE
Moved cursor to end in TagsDialog

### LINKED ISSUE #13841: [BUG]: Move cursor to end in TagsDialog
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Go to NoteEditor
2. Click on Tag
3. Rename the Tag

### Expected behaviour

The cursor must at the end of EditText

### Actual behaviour

The cursor is at start
tag

### Debug info

```text
AnkiDroid Version = 2.16.0beta1-debug

Android Version = 13

ProductFlavor = amazon

Manufacturer = Google

Model = sdk_gphone64_x86_64

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 13; sdk_gphone64_x86_64 Build/TE1A.220922.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.71 Mobile Safari/537.36

ACRA UUID = 31240e53-bc26-41a8-b8d0-c4c90159c405

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by gayatriii0803**
## Purpose / Description
The cursor is at start of input text. The user has to move the cursor to end manually.

## Fixes
Fixes #13841

## Approach
called `setFocusandOpenKeyboard()` method

## How Has This Been Tested?

Tested on Emulator ( Pixel 5 API 33 )
tag2

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by SanjaySargam — APPROVED** [review]
LGTM!!!

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt [hunk 1]
```diff
@@ -269,6 +270,7 @@ class TagsDialog : AnalyticsDialogFragment {
             // utilize the addTagFilter to append '::' properly by appending a space to prefixTag
             inputET.setText("$prefixTag ")
         }
+        setFocusAndOpenKeyboard(inputET) { inputET.setSelection(inputET.text.length) }
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt:273]: Is `setFocusAndOpenKeyboard()` necessary here? Didn't seem like it when I tested it
```suggestion
       inputET.setSelection(inputET.text.length)
```

Comment (gayatriii0803) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt]: ok

**Review by BrayanDSO — APPROVED** [review]
LGTM. Thanks!

**Review by lukstbit — APPROVED** [review]
