### PR TITLE
fix: make note type updates undoable

### LINKED ISSUE #19235: Editing the template from the note editor then returning to the study screen doesn’t update it.
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Open the new study screen.
2. Go to the note editor and edit the template.
3. Going back to study screen, it's not updated.

### Expected behaviour

The new study screen should update to include the changes done to the template.

### Debug info

```text
AnkiDroid Version = 2.23.0alpha4 (fb3fadbdebac9b191096a739e730d47ad9f6db09)  
Backend Version = 0.1.61-anki25.09 (25.09 539054c34dccf8b89ca7ea9c9c40ecaf172de759)  
Android Version = 13 (SDK 33)  
ProductFlavor = full  
Device Info = Xiaomi | POCO | mondrian | mondrian_global | 23013PC75G | qcom  
Webview User Agent = Mozilla/5.0 (Linux; Android 13; 23013PC75G Build/TKQ1.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/139.0.7258.158 Mobile Safari/537.36  
ACRA UUID = b9d03d9a-5af9-4e67-987e-cc15799171e2  
FSRS = 5.1.0 (Enabled: true)  
Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by BrayanDSO**
## Purpose / Description

it also notifies subscribers about the operation, so screens like the reviewer can react to it

## Fixes
* Fixes #19235

## Approach

I searched an "update method" in upstream that returned `OpChanges`, then used it

## How Has This Been Tested?

Emulator 34

[Screen_recording_20251121_185449.webm](https://github.com/user-attachments/assets/8a4b572f-d60b-4e7d-ad14-4071ccacfe34)

https://github.com/user-attachments/assets/19690fe8-5979-4cd7-95fb-2083e43950f6

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateNotetype.kt [hunk 1]
```diff
@@ -99,23 +100,22 @@ class CardTemplateNotetype(
...
-        col: Collection,
+    suspend fun saveNoteType(
         notetype: NotetypeJson,
         templateChanges: ArrayList<TemplateChange>,
     ) {
         Timber.d("saveNoteType")
-        val oldNoteType = col.notetypes.get(notetype.id)
+        val oldNoteType = withCol { notetypes.get(notetype.id) }
 
         // TODO: make undoable
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateNotetype.kt]: .

File: AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt [hunk 2]
```diff
@@ -288,7 +288,8 @@ class ContentProviderTest : InstrumentedTest() {
         var noteType: NotetypeJson? = createBasicNoteType()
         val noteTypeId = noteType!!.id
         // Add the note
-        val noteTypeUri = ContentUris.withAppendedId(FlashCardsContract.Model.CONTENT_URI, noteTypeId)
+        val noteTypeUri =
```
Comment (david-allison) [inline AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt]: revert or move to refactor commit - spacing change

File: AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt [hunk 3]
```diff
@@ -297,8 +298,14 @@ class ContentProviderTest : InstrumentedTest() {
                 put(FlashCardsContract.CardTemplate.NAME, TEST_NOTE_TYPE_CARDS[testIndex])
                 put(FlashCardsContract.CardTemplate.QUESTION_FORMAT, TEST_NOTE_TYPE_QFMT[testIndex])
                 put(FlashCardsContract.CardTemplate.ANSWER_FORMAT, TEST_NOTE_TYPE_AFMT[testIndex])
-                put(FlashCardsContract.CardTemplate.BROWSER_QUESTION_FORMAT, TEST_NOTE_TYPE_QFMT[testIndex])
-                put(FlashCardsContract.CardTemplate.BROWSER_ANSWER_FORMAT, TEST_NOTE_TYPE_AFMT[testIndex])
+                put(
```
Comment (david-allison) [inline AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt]: ditto

File: AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt [hunk 4]
```diff
@@ -344,7 +351,8 @@ class ContentProviderTest : InstrumentedTest() {
         val noteTypeId = noteType!!.id
         val initialFieldsArr = noteType.fields
         val initialFieldCount = initialFieldsArr.length()
-        val noteTypeUri = ContentUris.withAppendedId(FlashCardsContract.Model.CONTENT_URI, noteTypeId)
+        val noteTypeUri =
```
Comment (david-allison) [inline AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt]: .

File: libanki/src/main/java/com/ichi2/anki/libanki/Notetypes.kt [hunk 5]
```diff
@@ -518,14 +518,6 @@ class Notetypes(
         }
     }
 
-    fun remTemplate(
```
Comment (david-allison) [inline libanki/src/main/java/com/ichi2/anki/libanki/Notetypes.kt:516]: nit: Also acceptable to move this as an extension method on `AnkiTest` to reduce changes in this commit - depending on how upstream updated the tests

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateNotetype.kt [hunk 6]
```diff
@@ -99,23 +100,22 @@ class CardTemplateNotetype(
...
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateNotetype.kt]: is this `TODO` still current? Needs a little more context otherwise

File: AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt [hunk 7]
```diff
@@ -193,7 +194,7 @@ suspend fun <T> FragmentActivity.runCatching(
                 Timber.w(exc, errorMessage)
                 exc.localizedMessage?.let { showSnackbar(it) }
             }
-            is BackendNetworkException, is BackendSyncException, is StorageAccessException -> {
+            is BackendNetworkException, is BackendSyncException, is StorageAccessException, is BackendCardTypeException -> {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt:197]: I'd prefer to move all of this validation into `CrashReportData::shouldReportException`

https://github.com/ankidroid/Anki-Android/blob/4e50cdfb63e3e58cb4d2037010edbb51caec60d9/AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt#L651-L656

File: AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt [hunk 8]
```diff
@@ -444,6 +448,8 @@ class CardTemplateEditorTest : RobolectricTest() {
 
             // Add a template - click add, click confirm for card add, click confirm again for full sync
             addCardType(testEditor, shadowTestEditor)
+            // the templates must be different
+            testEditor.tempNoteType!!.getTemplate(2).qfmt += "foo"
```
Comment (david-allison) [inline AnkiDroid/src/test/java/com/ichi2/anki/CardTemplateEditorTest.kt]: nit: `"foo"` looked like test code which was left in, `"different_template"` maybe

File: AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt (hunk 7 above)
Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt:197]: I'm not sure where all of that is best placed, so I'll leave that for now

File: libanki/src/main/java/com/ichi2/anki/libanki/Notetypes.kt (hunk 5 above)
Comment (BrayanDSO) [reply libanki/src/main/java/com/ichi2/anki/libanki/Notetypes.kt:516]: In this case, I prefer using the separate methods

File: AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt (hunk 7 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt:197]: * https://github.com/ankidroid/Anki-Android/issues/19577

**Review by lukstbit — APPROVED** [review]
LGTM, thanks!
