### PR TITLE
fix: Issue returning 1000 results from database

### LINKED ISSUE #8055: [Bug] Imports of > 1000 notes fail
```
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$4.done(AsyncTask.java:399)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:929)
Caused by: net.ankiweb.rsdroid.BackendFatalError: panic with no info
at net.ankiweb.rsdroid.RustBackendImpl.validateResult(RustBackendImpl.java:2)
at net.ankiweb.rsdroid.BackendV1Impl.getPage(BackendV1Impl.java:6)
at net.ankiweb.rsdroid.BackendMutex.getPage(BackendMutex.java:2)
at net.ankiweb.rsdroid.database.Session.getPage(Session.java:1)
at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.getNextPage(StreamingProtobufSQLiteCursor.java:3)
at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.moveToNext(StreamingProtobufSQLiteCursor.java:2)
at com.ichi2.libanki.Collection._fieldData(Collection.java:3)
at com.ichi2.libanki.Collection.updateFieldCache(Collection.java:5)
at com.ichi2.libanki.Collection.updateFieldCache(Collection.java:2)
at com.ichi2.libanki.importer.Anki2Importer._importNotes(Anki2Importer.java:69)
at com.ichi2.libanki.importer.Anki2Importer._import(Anki2Importer.java:11)
at com.ichi2.libanki.importer.Anki2Importer.run(Anki2Importer.java:3)
at com.ichi2.libanki.importer.AnkiPackageImporter.run(AnkiPackageImporter.java:58)
at com.ichi2.async.CollectionTask$ImportAdd.task(CollectionTask.java:6)
at com.ichi2.async.CollectionTask$ImportAdd.task(CollectionTask.java:1)
at com.ichi2.async.CollectionTask.actualDoInBackground(CollectionTask.java:14)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:2)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:1)
at android.os.AsyncTask$3.call(AsyncTask.java:378)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
... 5 more
```

https://github.com/david-allison-1/Anki-Android-Backend/blob/edbac00d3c3992796400b68f81ef4bef8c1a2a15/rslib-bridge/src/lib.rs#L448-L458

Logs:

```
IntentHandler/ User requested to view a file
Intent: Intent { dat=[REDACTED] flg=0x43 }. Data: none
Attempting to read content from intent.
AnkiActivity::onStart - DeckPicker
AnkiActivity::onResume - DeckPicker
Dispatching persistent message: 2
Handling Message: ImportAddDialog
Updating deck list UI
uncompress collection.anki2
uncompress media
Opening rust backend. Server: false. Langs: 'en', path:
Opening Collection: '/storage/emulated/0/AnkiDroid/tmpzip/collection.anki2' '' '' ''
Opening Collection Log
Rust: transaction begin
flush - Saving information to DB...
Rust: executeGetRowsAffected UPDATE col SET ls=?,crt=?,dty=?,mod=?,scm=?,usn=?,conf=?
Rust: transaction commit
ExecuteCommand: closeCollection
Closing Collection Log
Collection closed
Opening rust backend. Server: false. Langs: 'en', path:
Opening Collection: '/storage/emulated/0/AnkiDroid/tmpzip/collection.anki2' '' '' ''
Opening Collection Log
Rust: transaction begin
Preparing Import
Importing notes
Rust: transaction rollback
DB/ Not in a transaction. Cannot end transaction.
ExecuteCommand: closeCollection
Closing Collection Log
Collection closed
```

### PR DESCRIPTION
**Pull request by david-allison-1**
Caused by an issue paging exactly 1000 items by the new database code

Fixes #8055

See:

https://github.com/david-allison-1/Anki-Android-Backend/issues/28
https://github.com/david-allison-1/Anki-Android-Backend/commit/7c5037079bb31f1c80b55a995bd06b5a2fc0381d

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)

### CODE REVIEW

**Comment by david-allison-1** [comment]
Hold off on merging if we're going to temporarily revert the Rust. There will be more to do before the linked issue is sorted, but this is a step in the right direction.

There was a test failure on a previous run. I don't feel it was related.

**Comment by mikehardy** [comment]
I don't want to revert unless it turns into some massive disaster. I'm okay with alpha not being to import for a little bit.

**Comment by david-allison-1** [comment]
Re-pushed and ready to go

File: AnkiDroid/src/main/java/com/ichi2/libanki/backend/RustDroidBackend.java [hunk 1]
```diff
@@ -56,4 +57,15 @@ public boolean databaseCreationCreatesSchema() {
...
+
+
+    @Override
+    public void debugEnsureNoOpenPointers() {
+        AdBackend.DebugActiveDatabaseSequenceNumbersOut result = mBackend.getBackend().debugActiveDatabaseSequenceNumbers(0);
+        int sequenceNumbers = result.getSequenceNumbersCount();
+          if (sequenceNumbers > 0) {
+              String numbers = result.getSequenceNumbersList().toString();
+              throw new IllegalStateException("Contained unclosed sequence numbers: " + numbers);
+          }
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/libanki/backend/RustDroidBackend.java:69]: Something odd happened with the indents here they are all +2 spaces to right
Code looks fairly good though - could be tightened up by just saying `if (result.getSequenceNumbersCount())` though, since otherwise the variable `sequenceNumbers` is never re-used

**Review by mikehardy — APPROVED** [review]
one minor comment to tidy up code but nothing actually wrong, just polish
after fixup LGTM + merge + and hit the release button :-)

**Comment by david-allison-1** [comment]
```
Run $ANDROID_HOME/platform-tools/adb devices
List of devices attached
emulator-5554	device

cmd: Failure calling service settings: Broken pipe (32)
Error: Process completed with exit code 224.
0s
Run gzip -9 adb-log.txt
gzip: can't stat: adb-log.txt (adb-log.txt): No such file or directory
Error: Process completed with exit code 1.
```

rerunning emulator tests
