### PR TITLE
Correcting Hyperlink Color In About Section

### LINKED ISSUE #12595: Inconsistent colour of hyperlinks
###### Reproduction Steps

Hyperlinks should follow a color scheme.

1. Settings -> About
2. Settings -> About -> Open changelog

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

highlight_links
link_colour_must+be_same

### PR DESCRIPTION
**Pull request by TomerPacific**
## Purpose / Description
It can be observed that in the About section, the hyperlink colors are not consistent.

## Fixes
Fixes #12595 

## Approach
By adding a specific attribute for anchor link colors, we can access this attribute based on the theme (light/dark)

## How Has This Been Tested?
I have used an emulated device and saw the anchor link colors in light and dark theme (screenshots attached).

## Learning (optional, can help others)
Not relevant

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [X] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

## Screenshots
qemu-system-x86_64_2PssWR9hIK

qemu-system-x86_64_g58hSbVzHM

### CODE REVIEW

**Comment by mikehardy** [comment]
Thanks for the first PR! I edited the description above (check it out) to explicitly say `Fixes #<number>` so github auto-connects the issue and PR and will close the issue when merged. We'll see what Brayan thinks of the PR

File: AnkiDroid/src/main/java/com/ichi2/anki/Info.kt [hunk 1]
```diff
@@ -85,6 +86,10 @@ class Info : AnkiActivity() {
         val typedArray = theme.obtainStyledAttributes(intArrayOf(android.R.attr.colorBackground, android.R.attr.textColor))
         val backgroundColor = typedArray.getColor(0, -1)
         val textColor = String.format("#%06X", 0xFFFFFF and typedArray.getColor(1, -1)) // Color to hex string
+
+        val anchorTextThemeColor: Int = ThemeUtils.getThemeAttrColor(this, R.attr.anchorTextColor)
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/Info.kt:90]: Could you use `colorAccent` as the color attr? This is the default on the About section so the color is consistent

**Review by BrayanDSO — CHANGES_REQUESTED** [review]
Hello there. Thanks for the contribution! Left a comment

File: AnkiDroid/src/main/java/com/ichi2/anki/Info.kt (hunk 1 above)
Comment (TomerPacific) [reply AnkiDroid/src/main/java/com/ichi2/anki/Info.kt:90]: @BrayanDSO  - Got it. So I am going to delete the custom attribute I created.

Comment (TomerPacific) [reply AnkiDroid/src/main/java/com/ichi2/anki/Info.kt]: @BrayanDSO  - I made several more commits per your comment.

**Review by BrayanDSO — APPROVED** [review]
*L*ooks
*G*ood
*T*o
*M*e

---

Note for the future (not related to your PR, but as a general comment for the repository): it would be nice to have an util method to convert colors to HEX. There are some other places on the app that do this same conversion

File: AnkiDroid/src/main/java/com/ichi2/anki/Info.kt [hunk 2]
```diff
@@ -85,6 +86,10 @@ class Info : AnkiActivity() {
         val typedArray = theme.obtainStyledAttributes(intArrayOf(android.R.attr.colorBackground, android.R.attr.textColor))
         val backgroundColor = typedArray.getColor(0, -1)
         val textColor = String.format("#%06X", 0xFFFFFF and typedArray.getColor(1, -1)) // Color to hex string
+
+        val anchorTextThemeColor: Int = ThemeUtils.getThemeAttrColor(this, R.attr.colorAccent)
+        val anchorTextColor: String = String.format("#%06X", 0xFFFFFF and anchorTextThemeColor)
```
Comment (n1snt) [inline AnkiDroid/src/main/java/com/ichi2/anki/Info.kt:91]: I think the data type declared here is redundant and can be removed as it will return Int & String by default.

**Review by n1snt — CHANGES_REQUESTED** [review]

**Review by n1snt — COMMENTED** [review]
Another suggestion would be to avoid having 6 commits just to have 1 change in a file.
You can delete/merge all the commits using `git rebase`

File: AnkiDroid/src/main/java/com/ichi2/anki/Info.kt (hunk 2 above)
Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/anki/Info.kt:91]: IMHO, this is a matter of personal taste and a overall low value discussion and efforts, so I'd go with implementer's choice.

Comment (n1snt) [reply AnkiDroid/src/main/java/com/ichi2/anki/Info.kt:91]: Yeah. Not something it should be blocked upon.

Comment (TomerPacific) [reply AnkiDroid/src/main/java/com/ichi2/anki/Info.kt]: @n1snt  - Removed type declaration.

**Review by n1snt — APPROVED** [review]

**Comment by TomerPacific** [comment]
@BrayanDSO  - Failed attempt at rebasing. Trying again.

**Comment by TomerPacific** [comment]
@BrayanDSO - I think I did it (first time rebasing for me).

File: AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt [hunk 3]
```diff
@@ -138,15 +137,15 @@ abstract class AppCompatPreferenceActivity<PreferenceHack : AppCompatPreferenceA
...
         }
 
         override fun getInt(key: String, defValue: Int): Int {
-            return this.getString(key, Integer.toString(defValue))!!.toInt()
+            return this.getString(key, defValue.toString())!!.toInt()
         }
 
         override fun getLong(key: String, defValue: Long): Long {
-            return this.getString(key, java.lang.Long.toString(defValue))!!.toLong()
+            return this.getString(key, defValue.toString())!!.toLong()
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt:148]: these changes aren't related to the PR. Perhaps you got it while rebasing the branch

**Review by BrayanDSO — CHANGES_REQUESTED** [review]

**Comment by BrayanDSO** [comment]
> [BrayanDSO](https://github.com/BrayanDSO) - I think I did it (first time rebasing for me).

Rebasing is a very handy skill to have. Thanks for the initiative.

File: AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt (hunk 3 above)
Comment (TomerPacific) [reply AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt:148]: @BrayanDSO  - Yes, I think it is related to the rebase. Do I just revert these?

Comment (TomerPacific) [reply AnkiDroid/src/main/java/com/ichi2/ui/AppCompatPreferenceActivity.kt]: @BrayanDSO - Yes, I think it is related to the rebase. Reverting those changes.

**Comment by TomerPacific** [comment]
@BrayanDSO ?

**Review by BrayanDSO — APPROVED** [review]
LGTM. Thanks

**Review by david-allison — APPROVED** [review]
