### PR TITLE
fix: insert field adds fields to the wrong card type

### LINKED ISSUE #19304: Insert field sometimes adds fields to the wrong card type
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Edit the template of a basic note type.
2. Add a card type.
3. Switch to Card 1.
4. Switch back to Card 2.
5. Try to insert fields.

Alternatively:

1. Edit the template of a basic and reversed note type.
2. Switch to Card 2 then back to Card 1.
3. Try to insert fields.

https://github.com/user-attachments/assets/85280749-bd19-4abe-aead-ad1e7d05e1a1

### Expected behaviour

The field replacement should be inserted in the current card type's template.

### Debug info

```text
AnkiDroid Version = 2.23.0alpha4 (fb3fadbdebac9b191096a739e730d47ad9f6db09)  
Backend Version = 0.1.61-anki25.09 (25.09 539054c34dccf8b89ca7ea9c9c40ecaf172de759)  
Android Version = 13 (SDK 33)  
ProductFlavor = full  
Device Info = Xiaomi | POCO | mondrian | mondrian_global | 23013PC75G | qcom  
Webview User Agent = Mozilla/5.0 (Linux; Android 13; 23013PC75G Build/TKQ1.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/140.0.7339.208 Mobile Safari/537.36  
ACRA UUID = b9d03d9a-5af9-4e67-987e-cc15799171e2  
FSRS = 5.1.0 (Enabled: true)  
Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by thedroiddiv**
## Purpose / Description
fix: insert field adds fields to the wrong card type

## Fixes
* Fixes #19304 

### Issue
When setting up the fragment result listener in CardTemplateFragment, all fragments use the same request key (REQUEST_FIELD_INSERT). This causes a conflict because:
- ViewPager2 keeps multiple fragments alive in memory simultaneously
- Each fragment registers a listener with the identical request key
- When a new fragment registers its listener, it overwrites the previous fragment's listener due to same key
- Consequently, when InsertFieldDialog sets a fragment result, only the most recently registered listener (typically the last fragment) receives the callback, not the currently visible fragment

### Solution
Make each fragment's result listener unique by incorporating the card index into the request key:
- Pass card index to the dialog: Modify InsertFieldDialog.newInstance() to accept and store a cardIndex parameter
- Generate unique request keys: Append the card index to create unique keys
- Use matching keys for listener and result

## How Has This Been Tested?
Manually Tested
Added unit test to simulate this behaviour
Passes existing tests

https://github.com/user-attachments/assets/a88986c5-5c6d-449b-a2c5-13b044ced2d9

https://github.com/user-attachments/assets/d0bed901-2d7c-4416-b710-29ef47ece786

## Learning (optional, can help others)
Listeners are stored as Map<Key, Listener>
https://android.googlesource.com/platform/frameworks/support/+/androidx-master-dev/fragment/fragment/src/main/java/androidx/fragment/app/FragmentManager.java#1214

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/InsertFieldDialog.kt [hunk 1]
```diff
@@ -86,17 +88,33 @@ class InsertFieldDialog : DialogFragment() {
...
-        const val REQUEST_FIELD_INSERT = "request_field_insert"
+        private const val REQUEST_FIELD_INSERT = "request_field_insert"
+
+        /**
+         * Other fragments sharing the activity can use this with
+         * [androidx.fragment.app.FragmentManager.setFragmentResultListener] to get a result back.
+         *
+         * Adding [cardIndex] ensures unique request key for each card.
+         */
+        fun requestKey(cardIndex: Int): String = "${REQUEST_FIELD_INSERT}_$cardIndex"
```
Comment (thedroiddiv) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/InsertFieldDialog.kt]: I feel like the this key generation couples the `InsertFieldDialog` to a `Card`, maybe we should make this a responsibility of the caller to generate a unique key. 
Or instead of using the name `cardIndex` use some neutral name for the unique identifier of the key. 

Requesting other's comments :)

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt [hunk 2]
```diff
@@ -729,7 +728,9 @@ open class CardTemplateEditor :
         )
         fun showInsertFieldDialog() {
             templateEditor.fieldNames?.let { fieldNames ->
-                templateEditor.showDialogFragment(InsertFieldDialog.newInstance(fieldNames))
+                val cardIndex = requireArguments().getInt(CARD_INDEX)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt]: nit: this would be nice as a get-based property

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt [hunk 3]
```diff
@@ -810,8 +811,11 @@ open class CardTemplateEditor :
                     }
                 },
             )
-            parentFragmentManager.setFragmentResultListener(REQUEST_FIELD_INSERT, viewLifecycleOwner) { key, bundle ->
-                if (key == REQUEST_FIELD_INSERT) {
+
+            val cardIndex = requireArguments().getInt(CARD_INDEX)
+            val requestKey = InsertFieldDialog.requestKey(cardIndex)
+            parentFragmentManager.setFragmentResultListener(requestKey, viewLifecycleOwner) { key, bundle ->
+                if (key == requestKey) {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt]: Is this line necessary? I would have expected that passing in `requestKey` to `setFragmentResultListener` would imply that `key == requestKey`

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/InsertFieldDialog.kt (hunk 1 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/InsertFieldDialog.kt]: This dialog would also be useful in the 'Browser Appearance' window, so I'd prefer to move the responsibility to the caller.

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt [hunk 4]
```diff
@@ -810,8 +811,11 @@ open class CardTemplateEditor :
                     }
                 },
             )
-            parentFragmentManager.setFragmentResultListener(REQUEST_FIELD_INSERT, viewLifecycleOwner) { key, bundle ->
-                if (key == REQUEST_FIELD_INSERT) {
+
+            val cardIndex = requireArguments().getInt(CARD_INDEX)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt]: nit: add a comment

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt (hunk 3 above)
Comment (thedroiddiv) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt]: Yes, indeed passing unique key ensures that the result is returned to the same listener with that key. Will remove this redundant check. 

https://android.googlesource.com/platform/frameworks/support/+/androidx-master-dev/fragment/fragment/src/main/java/androidx/fragment/app/FragmentManager.java#1162

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/InsertFieldDialog.kt (hunk 1 above)
Comment (thedroiddiv) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/InsertFieldDialog.kt]: Done.

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt [hunk 5]
```diff
@@ -522,6 +521,12 @@ open class CardTemplateEditor :
         private val refreshFragmentHandler = Handler(Looper.getMainLooper())
         private lateinit var editorEditText: FixedEditText
 
+        // Index of this card template fragment in ViewPager
+        private var cardIndex = 0
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt]: my one nitpick is that this would be better as `get() = requireArguments().getInt(CARD_INDEX)`

**Review by lukstbit — APPROVED** [review]
LGTM, thanks!
Note: I squashed the three commits mainly because the first one is a failing test(also the third commit looks like an iteration of the previous code).

Related to the key, not important, but I would have used the original single key and passed the card index. In the end we have a single type of request(to insert a field) but with different data, what field and in which card to insert it.

**Comment by thedroiddiv** [comment]
> Related to the key, not important, but I would have used the original single key and passed the card index. In the end we have a single type of request(to insert a field) but with different data, what field and in which card to insert it.

I actually did that initially, check out this comment. 
https://github.com/ankidroid/Anki-Android/pull/19367#discussion_r2463890255

**Comment by david-allison** [comment]
Hi there @thedroiddiv! This is the OpenCollective Notice for PRs merged from [2025-10-01 through 2025-10-31](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2025-10-01..2025-10-31+author%3Athedroiddiv)

If you are interested in compensation for this work, the process with details is here: https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

We only post one comment per person per month to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for this month

Please understand that our monthly budget is never guaranteed to cover all claims - the cap on payments-per-person may be lower, but we try to make our process as fair and transparent as possible, we just need your understanding.

Thanks!
