### PR TITLE
fix(sync): invalid endpoint

### LINKED ISSUE #18776: [2.22alpha1] Media Sync Error: "Invalid sync server specified. Please check the preferences."
@BrayanDSO This occurred when redownloading my production collection using the alpha from Obtainium

I believe:
* Log in
* Deny notification permission 
* Tap sync
* Accept notification permission

https://ankidroid.org/acra/app/1/bug/316595/report/626370f5-613f-4029-ae45-87ceeeecec1a

```
W  h/ x7.d: Invalid sync server specified. Please check the preferences.
        	at J5.C.b(SourceFile:362)
        	at leakcanary.ActivityWatcher.l0(ActivityWatcher.kt:23)
        	at anki.backend.GeneratedBackend.syncMediaRaw(GeneratedBackend.kt:17)
        	at anki.backend.GeneratedBackend.syncMedia(GeneratedBackend.kt:21)
        	at com.ichi2.anki.worker.SyncMediaWorker.doWork(SyncMediaWorker.kt:76)
        	at androidx.work.CoroutineWorker$startWork$1.x(CoroutineWorker.kt:29)
        	at androidx.work.CoroutineWorker$startWork$1.g(CoroutineWorker.kt:13)
        	at androidx.work.ListenableFutureKt$launchFuture$1$2.x(ListenableFuture.kt:37)
        	at kotlin.collections.builders.ListBuilder$BuilderSubList$Itr.j(ListBuilder.kt:9)
        	at V6.E.run(SourceFile:117)
        	at kotlin.text.Charsets.run(Charsets.kt:96)
        
        x7.d: Invalid sync server specified. Please check the preferences.
        	at J5.C.b(SourceFile:362)
        	at leakcanary.ActivityWatcher.l0(ActivityWatcher.kt:23)
        	at anki.backend.GeneratedBackend.syncMediaRaw(GeneratedBackend.kt:17)
        	at anki.backend.GeneratedBackend.syncMedia(GeneratedBackend.kt:21)
        	at com.ichi2.anki.worker.SyncMediaWorker.doWork(SyncMediaWorker.kt:76)
        	at androidx.work.CoroutineWorker$startWork$1.x(CoroutineWorker.kt:29)
        	at androidx.work.CoroutineWorker$startWork$1.g(CoroutineWorker.kt:13)
        	at androidx.work.ListenableFutureKt$launchFuture$1$2.x(ListenableFuture.kt:37)
        	at kotlin.collections.builders.ListBuilder$BuilderSubList$Itr.j(ListBuilder.kt:9)
        	at V6.E.run(SourceFile:117)
        	at kotlin.text.Charsets.run(Charsets.kt:96)
```

This did not appear in the logs/errors. I am not using a custom sync server

> 2394d51f233eaba6279daf1c1cc5e5461da17a48 ⚠️

```
AnkiDroid Version = 2.22alpha1 (2394d51f233eaba6279daf1c1cc5e5461da17a48)  
Backend Version = 0.1.54-anki25.02.7 (25.02.7 98253c81cb3c4d203acec48d6eae6b488bf484d0)  
Android Version = 15 (SDK 35)  
ProductFlavor = full  
Device Info = Google | google | caiman | caiman | Pixel 9 Pro | caiman  
Webview User Agent = Mozilla/5.0 (Linux; Android 15; Pixel 9 Pro Build/BP1A.250505.005.A1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/137.0.7151.115 Mobile Safari/537.36  
ACRA UUID = a3946376-3893-4e6c-afab-52a90f851de2  
FSRS = 2.0.3 (Enabled: true)  
Crash Reports Enabled = true
```

----

https://github.com/ankitects/anki/blob/a83a6b5928c6563d12e7b66d4f7b7b2f51b6f22b/rslib/src/backend/sync.rs#L79-L97

### PR DESCRIPTION
**Pull request by BrayanDSO**
## Fixes
* Fixes #18776

## Approach

Properly show the error in the notification

## How Has This Been Tested?

Use this patch to trigger the error:
```patch
Subject: [PATCH] improvement(sync): include error message in notification
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncMediaWorker.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncMediaWorker.kt b/AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncMediaWorker.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncMediaWorker.kt	(revision 3a6ae8b8ae276226f9a397452cee51f0e36c4929)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncMediaWorker.kt	(date 1751726537550)
@@ -66,9 +66,7 @@
             val auth =
                 syncAuth {
                     hkey = inputData.getString(HKEY_KEY)!!
-                    inputData.getString(ENDPOINT_KEY)?.let {
-                        endpoint = it
-                    }
+                    endpoint = ""
                 }
 
             // The collection must be open, but we should not block collection operations while
```

Emulator API 36:

https://github.com/user-attachments/assets/acda5d18-f66a-477f-8c17-f0bd3287cbaf

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt [hunk 1]
```diff
@@ -106,7 +107,12 @@ fun getEndpoint(context: Context): String? {
         } else {
             null
         }
-    return currentEndpoint ?: customEndpoint
+    val resolvedEndpoint = currentEndpoint ?: customEndpoint
+    return if (resolvedEndpoint != null && resolvedEndpoint.toHttpUrlOrNull() == null) {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt]: * This obscures an error in setting `CUSTOM_SYNC_URI`
  * And means that `null` (AnkiWeb) is used

Could we just handle the 'known bad' for now: `""`, we can then expose it better in the UI (I wasn't getting notifications of the sync failure)

**Review by david-allison — COMMENTED** [review]
as above

**Review by david-allison — CHANGES_REQUESTED** [review]
requesting changes

**Comment by BrayanDSO** [comment]
The error is now exposed in the UI

**Review by david-allison — CHANGES_REQUESTED** [review]
This doesn't fix the bug (I presume we're passing in `""`). 

Changes are correct, but a user can't fix the problematic configuration.

**Comment by BrayanDSO** [comment]
Okay, if  `""` comes from AnkiWeb/Backend/Somewhere, use `null`.

If the comes from custom sync preferences, show the error message so they fix it in preferences.

**Review by david-allison — APPROVED** [review]
Cheers!

**Comment by david-allison** [comment]
Let's get this in if it sits for more than an hour
