### PR TITLE
fix: Use flags from col, dynamically loading them into the menu

### LINKED ISSUE #16204: Display Renamed Flags
https://github.com/ankitects/anki/commit/9816227b5caa86d7edbcaec7b9697aefbfead2a7

```python
    def rename_flag(self, item: SidebarItem, new_name: str) -> None:
        labels = self.col.get_config("flagLabels", {})
        labels[str(item.id)] = new_name
        self.col.set_config("flagLabels", labels)
        item.name = new_name
        self.refresh()
```

### PR DESCRIPTION
**Pull request by criticalAY**
## Purpose / Description
* Display Renamed Flags #16204 
This PR removes the static menu item - flags, from the menu and dynamically load the flag data which allow the user to access the renamed flags if they did rename them in Anki desktop 

## Fixes
* Fixes #16204

## Approach
Loaded flag from col

## How Has This Been Tested?
Anki ->
image

AnkiDroid -> 
image

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by criticalAY — COMMENTED** [review]
The strings also differ in AnkiDroid i.e. the `flag` after them but I am not focusing on that here, and if we wish to reuse `addFlags` then I am all ears

**Review by david-allison — COMMENTED** [review]
CI issue

**Comment by criticalAY** [comment]
I just want to test id this test is really causing the issue, if not then I will revert the commit

File: AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt [hunk 1]
```diff
@@ -53,6 +53,7 @@ import kotlin.test.junit5.JUnit5Asserter.assertNotNull
 
 @RunWith(AndroidJUnit4::class)
 class ReviewerTest : RobolectricTest() {
+    @Ignore("flaky")
```
Comment (david-allison) [inline AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt:56]: Remove this test, we do it better elsewhere

```
E/ACRA: ACRA caught a BackendDbLockedException for com.ichi2.anki.debug
net.ankiweb.rsdroid.BackendException$BackendDbException$BackendDbLockedException: 
	at com.ichi2.anki.CollectionManager.ensureOpenInner(CollectionManager.kt:225)
	at com.ichi2.anki.CollectionManager.access$ensureOpenInner(CollectionManager.kt:39)
	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:101)
	at com.ichi2.anki.CollectionManager$withCol$2.invoke(CollectionManager.kt:100)
	at com.ichi2.anki.CollectionManager$withQueue$2.invokeSuspend(CollectionManager.kt:86)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineId(9), "coroutine#9":StandaloneCoroutine{Cancelling}@14b99530, Dispatchers.Main.immediate]
W/ACRA: 
org.acra.collector.CollectorException: Error while retrieving LOGCAT data:Cannot run program "logcat": error=2, No such file or directory
	at org.acra.collector.BaseReportFieldCollector.collect(BaseReportFieldCollector.kt:60)
	at org.acra.data.CrashReportDataFactory.collect$lambda$10$lambda$9(CrashReportDataFactory.kt:69)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.io.IOException: Cannot run program "logcat": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at org.acra.collector.LogCatCollector.collectLogCat(LogCatCollector.kt:74)
	at org.acra.collector.LogCatCollector.collect(LogCatCollector.kt:103)
	at org.acra.collector.BaseReportFieldCollector.collect(BaseReportFieldCollector.kt:56)
	... 6 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 10 more
W/ACRA: 
org.acra.collector.CollectorException: Error while retrieving BUILD data:Cannot invoke "Object.getClass()" because "obj" is null
	at org.acra.collector.BaseReportFieldCollector.collect(BaseReportFieldCollector.kt:60)
	at org.acra.data.CrashReportDataFactory.collect$lambda$10$lambda$9(CrashReportDataFactory.kt:69)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "obj" is null
	at java.base/java.lang.reflect.Field.checkAccess(Field.java:1103)
	at java.base/java.lang.reflect.Field.get(Field.java:423)
	at org.acra.collector.ReflectionCollector$Companion.collectConstants(ReflectionCollector.kt:104)
	at org.acra.collector.ReflectionCollector$Companion.access$collectConstants(ReflectionCollector.kt:92)
	at org.acra.collector.ReflectionCollector.collect(ReflectionCollector.kt:45)
	at org.acra.collector.BaseReportFieldCollector.collect(BaseReportFieldCollector.kt:56)
	... 6 more
```

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt [hunk 2]
```diff
@@ -849,7 +818,7 @@ open class Reviewer :
         onboarding.onCreate()
 
         increaseHorizontalPaddingOfOverflowMenuIcons(menu)
-        tintOverflowMenuIcons(menu, skipIf = { isFlagResource(it.itemId) })
+        tintOverflowMenuIcons(menu)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt:821]: This feels like a race condition - continue to skip the flags

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt [hunk 3]
```diff
@@ -900,6 +912,16 @@ open class CardBrowser :
             undoSnackbar != null && undoSnackbar!!.isShown -> undoSnackbar!!.dismiss()
         }
 
+        val flag = Flag.entries.find { it.ordinal == item.itemId }
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt:915]: Use different IDs for multiselect and normal select, otherwise this can get nasty

**Review by david-allison — CHANGES_REQUESTED** [review]
Thanks!

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt [hunk 4]
```diff
@@ -900,6 +926,15 @@ open class CardBrowser :
...
+        flag?.let {
+            when (item.groupId) {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt:931]: Use the constant values in the when

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt [hunk 5]
```diff
@@ -692,12 +667,26 @@ open class Reviewer :
...
     }
 
+    private val flagTitles = mutableSetOf<String>()
+
+    private fun addFlags(subMenu: SubMenu?) {
+        lifecycleScope.launch {
+            val flagNames = getFlagData(this@Reviewer)
+            flagNames.forEach { (flag, pair) ->
+                val (title, drawableRes) = pair
+                subMenu?.add(Menu.NONE, flag.ordinal, Menu.NONE, title)?.setIcon(drawableRes)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt:677]: It might be useful to add arg names for the `NONE` values

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt [hunk 6]
```diff
@@ -849,11 +821,14 @@ open class Reviewer :
...
 
         increaseHorizontalPaddingOfOverflowMenuIcons(menu)
-        tintOverflowMenuIcons(menu, skipIf = { isFlagResource(it.itemId) })
-
+        tintOverflowMenuIcons(menu, skipIf = { isFlagItem(it) })
         return super.onCreateOptionsMenu(menu)
     }
 
+    private fun isFlagItem(menuItem: MenuItem): Boolean {
+        return flagTitles.contains(menuItem.title.toString())
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt:829]: Is there another way to handle this with an immutable value?

Minor concern about titles changing either due to a rename of the flag, or a language change

**Review by david-allison — CHANGES_REQUESTED** [review]
Thanks! Should be the last round

I'd also encourage adding a follow-up issue to change the strings from `Red flag` to `Red` as is used upstream

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt (hunk 5 above)
Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt:677]: The none is set for group id and order and we don't care about them here, so I don' think it is required here

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt (hunk 6 above)
Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt:829]: Can try with item id

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt (hunk 5 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt:677]: It probably isn't needed, but it's useful to have the argument names listed for documentation (if possible)

Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt:677]: ok gotchu

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt [hunk 7]
```diff
@@ -900,6 +926,15 @@ open class CardBrowser :
...
+                Mode.SINGLE_SELECT.value -> filterByFlag(it)
+                else -> updateFlagForSelectedRows(it)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt:933]: `Mode.MULTI_SELECT`, then another `else` branch returning

**Review by david-allison — APPROVED** [review]
Thanks! One more to go

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt (hunk 7 above)
Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt]: Done!

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt [hunk 8]
```diff
@@ -350,6 +352,11 @@ open class Reviewer :
         if (drawerToggle.onOptionsItemSelected(item)) {
             return true
         }
+        val flag = Flag.entries.find { it.ordinal == item.itemId }
+        flag?.let {
+            onFlag(currentCard, it)
+            return true
+        }
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt:359]: Unnecessary refactor + removes logs + doesn't make it more readable, just shorter + slight performance cost

File: AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt [hunk 9]
```diff
@@ -188,18 +198,15 @@ class PreviewerFragment :
     }
 
     override fun onMenuItemClick(item: MenuItem): Boolean {
+        val flag = Flag.entries.find { it.ordinal == item.itemId }
+        flag?.let {
+            viewModel.setFlag(it)
+            return true
+        }
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt:205]: ditto

File: AnkiDroid/src/main/res/menu/card_browser_multiselect.xml [hunk 10]
```diff
@@ -25,37 +25,7 @@
...
-          android:icon="@drawable/ic_flag_pink"/>
-      <item
-          android:id="@+id/action_flag_six"
-          android:title="@string/menu_flag_card_six"
-          android:icon="@drawable/ic_flag_turquoise"/>
-      <item
-          android:id="@+id/action_flag_seven"
-          android:title="@string/menu_flag_card_seven"
-          android:icon="@drawable/ic_flag_purple"/>
+          <!--  flags are dynamically added -->
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/res/menu/card_browser_multiselect.xml:28]:
```suggestion
          <!-- flags are dynamically added -->
```

File: AnkiDroid/src/main/res/menu/card_browser.xml [hunk 11]
```diff
@@ -38,37 +38,7 @@
...
-                android:icon="@drawable/ic_flag_pink"/>
-            <item
-                android:id="@+id/action_select_flag_six"
-                android:title="@string/menu_flag_card_six"
-                android:icon="@drawable/ic_flag_turquoise"/>
-            <item
-                android:id="@+id/action_select_flag_seven"
-                android:title="@string/menu_flag_card_seven"
-                android:icon="@drawable/ic_flag_purple"/>
+            <!--  flags are dynamically added -->
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/res/menu/card_browser.xml:41]:
```suggestion
            <!-- flags are dynamically added -->
```

File: AnkiDroid/src/main/res/menu/previewer.xml [hunk 12]
```diff
@@ -27,37 +27,7 @@
...
-                android:icon="@drawable/ic_flag_pink"/>
-            <item
-                android:id="@+id/action_flag_six"
-                android:title="@string/menu_flag_card_six"
-                android:icon="@drawable/ic_flag_turquoise"/>
-            <item
-                android:id="@+id/action_flag_seven"
-                android:title="@string/menu_flag_card_seven"
-                android:icon="@drawable/ic_flag_purple"/>
+            <!--  flags are dynamically added -->
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/res/menu/previewer.xml:30]:
```suggestion
            <!-- flags are dynamically added -->
```

File: AnkiDroid/src/main/res/menu/reviewer.xml [hunk 13]
```diff
@@ -58,37 +58,7 @@
...
-                android:icon="@drawable/ic_flag_pink"/>
-            <item
-                android:id="@+id/action_flag_six"
-                android:title="@string/menu_flag_card_six"
-                android:icon="@drawable/ic_flag_turquoise"/>
-            <item
-                android:id="@+id/action_flag_seven"
-                android:title="@string/menu_flag_card_seven"
-                android:icon="@drawable/ic_flag_purple"/>
+            <!--  flags are dynamically added -->
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/res/menu/reviewer.xml:61]:
```suggestion
            <!-- flags are dynamically added -->
```

File: AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt [hunk 14]
```diff
@@ -15,11 +15,26 @@
...
+import android.content.Context
 import androidx.annotation.ColorRes
 import androidx.annotation.DrawableRes
+import com.ichi2.anki.CollectionManager.withCol
 import com.ichi2.libanki.Card
 import com.ichi2.libanki.CardId
 import com.ichi2.libanki.Collection
+import org.json.JSONObject
+
+// this is not part of the enum as getFlagNames should be used to handle overrides
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt:27]: add a `defaultNameRes` property to the enum instead of using a hashmap

File: AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt [hunk 15]
```diff
@@ -39,3 +54,28 @@ enum class Flag(val code: Int, @DrawableRes val drawableRes: Int, @ColorRes val
...
+}
+
+private fun JSONObject.getStringOrNull(key: String): String? {
+    if (!has(key)) return null
+    return try {
+        getString(key)
+    } catch (_: Exception) {
+        null
+    }
+}
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt:81]: This method would be better placed in a `JSONObject` file inside the `com.ichi2.anki.utils.ext` package

File: AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt [hunk 16]
```diff
@@ -39,3 +54,28 @@ enum class Flag(val code: Int, @DrawableRes val drawableRes: Int, @ColorRes val
...
+ * @return A map where each Flag enum is associated with a pair containing its name as a string and its corresponding drawable resource ID.
+ */
+suspend fun getFlagData(context: Context): Map<Flag, Pair<String, Int>> {
+    val overrides = withCol { config.getObject("flagLabels", JSONObject()) }
+    return Flag.entries.associateWith { flag ->
+        val flagName = overrides.getStringOrNull(flag.code.toString()) ?: context.getString(flagToName[flag]!!)
+        val drawableResId = flag.drawableRes
+        flagName to drawableResId
+    }
+}
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt:72]: This method complicate things more than it should. You already have the flag and the drawableRes. The only thing that you want to get is the flag name.

So you could use a getName method inside the `Flag` enum:
```kotlin
    suspend fun getName(resources: Resources): String {
        val overrides = withCol { config.getObject("flagLabels", JSONObject()) }
        return overrides.getStringOrNull(code.toString()) ?: resources.getString(flagToName[this]!!)
    }
```
and replace the `getFlagData` loops with:
```kotlin
for (flag in Flag.entries) {
    val title = flag.getName(resources)
    submenu?.add(Menu.NONE, flag.ordinal, Menu.NONE, title)?.setIcon(flag.drawableRes)
}
```

File: AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt [hunk 17]
```diff
@@ -48,17 +48,10 @@ import org.json.JSONArray
...
 import kotlin.test.junit5.JUnit5Asserter.assertNotNull
 
 @RunWith(AndroidJUnit4::class)
 class ReviewerTest : RobolectricTest() {
-    @Test
-    fun verifyStartupNoCollection() {
-        enableNullCollection()
-        ActivityScenario.launch(Reviewer::class.java)
-            .use { scenario -> scenario.onActivity { reviewer: Reviewer -> assertFailsWith<Exception> { reviewer.getColUnsafe } } }
-    }
```
Comment (BrayanDSO) [inline AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.kt:61]: This removal should be in another commit or at least in the commit description. Somebody reading your code shouldn't need to read David's comment to get why this is being removed

**Review by BrayanDSO — CHANGES_REQUESTED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt (hunk 8 above)
Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt:359]: Not resolved or had an explanation from the author (this isn't the first time that this happens with you)

File: AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt (hunk 9 above)
Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt:203]: Not resolved or had an explanation from the author

**Review by BrayanDSO — CHANGES_REQUESTED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt (hunk 8 above)
Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt:359]: Apologies, missed it, how do we expect to handle the menu item click? and we can add a generic log here.

Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt:359]: The alternatives aren't going to be easier, so just re-add the log

Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt]: Done! thankyou for pointing out my oversight will keep in mind  for future reviews

File: AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt [hunk 18]
```diff
@@ -198,6 +199,7 @@ class PreviewerFragment :
     override fun onMenuItemClick(item: MenuItem): Boolean {
         val flag = Flag.entries.find { it.ordinal == item.itemId }
         flag?.let {
+            Timber.i("PreviewerFragment:: $it")
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt:202]: Specify that this is under onMenuItemClick. Same for the reviewer call

File: AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt [hunk 19]
```diff
@@ -188,18 +197,16 @@ class PreviewerFragment :
     }
 
     override fun onMenuItemClick(item: MenuItem): Boolean {
+        val flag = Flag.entries.find { it.ordinal == item.itemId }
+        flag?.let {
+            Timber.i("PreviewerFragment:: onOptionItemSelected Flag - $it clicked")
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt:202]: Wrong method name

Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt:202]: Ahhhhhh I am soooo sorryyyy :(

File: AnkiDroid/src/main/res/menu/previewer.xml [hunk 20]
```diff
@@ -27,37 +27,7 @@
         android:icon="@drawable/ic_flag_transparent"
         app:showAsAction="always" >
         <menu>
-            <item
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/res/menu/previewer.xml:30]: Actually, can't just the titles be added dynamically? Removing them makes harder to preview in the XML layout previewer

**Review by BrayanDSO — CHANGES_REQUESTED** [review]

File: AnkiDroid/src/main/res/menu/previewer.xml (hunk 20 above)
Comment (criticalAY) [reply AnkiDroid/src/main/res/menu/previewer.xml:30]: That makes things not dynamic but just some portion of it, and I suspect it will make thing messy

Comment (BrayanDSO) [reply AnkiDroid/src/main/res/menu/previewer.xml:30]: So that's a yes that doesn't break XML previews. I trust that you can solve it without doing a mess

Comment (criticalAY) [reply AnkiDroid/src/main/res/menu/previewer.xml:30]: We can do that, but the current code doesn't break the xml preview 
i.e. 
image

Comment (BrayanDSO) [reply AnkiDroid/src/main/res/menu/previewer.xml:30]: Oh, my bad. Looks good then. Thanks!

**Review by BrayanDSO — APPROVED** [review]
