### PR TITLE
Fix: IllegalArgumentException on with progress dialog dimiss

### LINKED ISSUE #15445: [Bug] [2.17alpha2] DeckPicker not attached to window manager
```
Stacktrace (No mapping found)
java.lang.IllegalArgumentException: View=DecorView@1caa981[DeckPicker] not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:690)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:581)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:196)
	at android.app.Dialog.dismissDialog(Dialog.java:793)
	at android.app.Dialog.dismiss(Dialog.java:769)
	at com.ichi2.anki.CoroutineHelpersKt$withProgressDialog$2.invokeSuspend(SourceFile:212)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(SourceFile:7)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(SourceFile:16)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:50)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:110)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8855)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

https://ankidroid.org/acra/app/1/bug/124831/report/444bfe87-a317-4ba1-b11f-83a14594182c

### PR DESCRIPTION
**Pull request by criticalAY**
## Purpose / Description
`withProgress` dialog might throw IllegalArgumentException if the dialog is not shown and dismiss is called.
Stracktrace pointed at DeckPicker which was calling with progress having context from DeckPicker,
```View=DecorView@1caa981[DeckPicker] not attached to window manager: ```
This message indicates that the DecorView with the identifier 1caa981 (associated with a DeckPicker) is not currently attached to the window manager.

## Fixes
* Fixes #15445 

## How Has This Been Tested?

Adding a condition to check whether the dialog is showing before dismissing it  fixes the issue.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt [hunk 1]
```diff
@@ -352,7 +352,9 @@ suspend fun <T> withProgressDialog(
         op(dialog)
     } finally {
         dialogJob.cancel()
-        dialog.dismiss()
+        if (dialog.isShowing) {
+            dialog.dismiss()
+        }
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt:357]: This should be wrapped in. try...catch as well, there's a rare race condition here

**Review by david-allison — CHANGES_REQUESTED** [review]
Thanks!

File: AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt [hunk 2]
```diff
@@ -352,14 +353,24 @@ suspend fun <T> withProgressDialog(
...
     }
 }
 
+private fun dismissDialogIfShowing(dialog: Dialog) {
+    try {
+        if (dialog.isShowing) {
+            dialog.dismiss()
+        }
+    } catch (e: Exception) {
+        Timber.v(e)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt:370]: use `.w`

**Review by david-allison — APPROVED** [review]

**Review by david-allison — APPROVED** [review]
It was good, now it's even better, thanks!

**Review by lukstbit — APPROVED** [review]
Thanks!
