### PR TITLE
Fix #19968: Note type search is case sensitive and can't be deleted quickly

### LINKED ISSUE #19968: Note type search is case sensitive and can't be deleted quickly
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Got to manage note types.
2. Search for "basic".
3. Try deleting the search text by long pressing the delete button on the keyboard.

It won't show the Basic note type due to case sensitivity. Also, only one character will be deleted at a time.

https://github.com/user-attachments/assets/a95b1af9-994a-4d43-9507-8b64cf194dc3

### Expected behaviour

Case insensitive + quickly delete the characters when long pressing the delete key.

### Debug info

```text
AnkiDroid Version = 2.23.1 (3f3133b496b531383e9a6494f5a7704634935308)  
Backend Version = 0.1.62-anki25.09.2 (25.09.2 3890e12c9e48c028c3f12aa58cb64bd9f8895e30)  
Android Version = 13 (SDK 33)  
ProductFlavor = full  
Device Info = Xiaomi | POCO | mondrian | mondrian_global | 23013PC75G | qcom  
Webview User Agent = Mozilla/5.0 (Linux; Android 13; 23013PC75G Build/TKQ1.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/143.0.7499.115 Mobile Safari/537.36  
ACRA UUID = 4afc3b3f-e93f-4a66-bc71-2b9476ef9eb0  
FSRS = 5.1.0 (Enabled: true)  
Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

Two tiny bugs hopefully fit in a single issue.

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by Ayush-Patel-56**
## Purpose / Description
Fixes two issues in the "Manage note types" screen:
1.  **Case Sensitivity:** The search filter was case-sensitive, making it hard to find types like "Basic" if typing "basic".
2.  **Typing Interruption:** The search input was being reset loosely on every state update, interrupting the soft keyboard loop and preventing the "long press delete" key from working effectively.

## Fixes
* Fixes #19968

## Approach
- Updated the search filter to use `ignoreCase = true`.
- Added a check to the `SearchView` binding to only update the query text if it has actually changed. This prevents the keyboard/input loop from being reset unnecessarily.

## How Has This Been Tested?
I tested this manually on an emulator:
1.  **Search Test:** Typed "bAsIc" (mixed case) and verified it correctly found "Basic" (see attached video).
2.  **Delete Test:** Typed a long string and long-pressed the backspace key. Verified that deletion is now rapid and smooth without interruption.

https://github.com/user-attachments/assets/e416a071-9f13-4372-81d6-f47252d476ec

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by ShaanNarendran** [comment]
The commit you pushed is for fixing android studio warnings, should force push again with the right commit

**Comment by david-allison** [comment]
Thanks! Please add a test

File: AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt [hunk 1]
```diff
@@ -177,7 +177,9 @@ class ManageNotetypes : AnkiActivity(R.layout.activity_manage_note_types) {
             val searchMenuItem =
                 findViewById<Toolbar>(R.id.toolbar).menu?.findItem(R.id.search_item)
             val searchView = searchMenuItem?.actionView as? AccessibleSearchView
-            searchView?.setQuery(state.searchQuery, false)
+            if (searchView?.query.toString() != state.searchQuery) {
```
Comment (sanjaysargam) [inline AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt:181]: add a comment

File: AnkiDroid/src/test/java/com/ichi2/anki/notetype/ManageNoteTypesViewModelTest.kt [hunk 2]
```diff
@@ -209,6 +209,22 @@ class ManageNoteTypesViewModelTest : RobolectricTest() {
...
 
+    @Test
+    fun `filtering is case insensitive`() =
+        runTest {
+            val name = "MixedCaseNoteType"
+            addStandardNoteType(name, arrayOf("front", "back"), "", "")
+            val viewModel = ManageNoteTypesViewModel()
+            viewModel.filter(name.lowercase())
+            var currentlyDisplayed = viewModel.noteTypes.filter { it.shouldBeDisplayed }
+            assertEquals(1, currentlyDisplayed.size)
```
Comment (sanjaysargam) [inline AnkiDroid/src/test/java/com/ichi2/anki/notetype/ManageNoteTypesViewModelTest.kt]: is it important? 
Can you explain this ?

**Review by sanjaysargam — CHANGES_REQUESTED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt (hunk 1 above)
Comment (Ayush-Patel-56) [reply AnkiDroid/src/main/java/com/ichi2/anki/notetype/ManageNotetypes.kt:181]: added the comment here

File: AnkiDroid/src/test/java/com/ichi2/anki/notetype/ManageNoteTypesViewModelTest.kt (hunk 2 above)
Comment (Ayush-Patel-56) [reply AnkiDroid/src/test/java/com/ichi2/anki/notetype/ManageNoteTypesViewModelTest.kt]: Yeah, we need this test. It prevents the search from becoming case-sensitive again in the future. Right now if you search for "basic" or "BASIC" it finds the "Basic" note type - this test makes sure that keeps working.

**Comment by sanjaysargam** [comment]
squash your commits into one

**Comment by Ayush-Patel-56** [comment]
> squash your commits into one

now my commits are squashed into one

File: gradle/wrapper/gradle-wrapper.properties [hunk 3]
```diff
@@ -1,6 +1,6 @@
 distributionBase=GRADLE_USER_HOME
 distributionPath=wrapper/dists
-distributionUrl=https\://services.gradle.org/distributions/gradle-9.2.1-bin.zip
+distributionUrl=https\://services.gradle.org/distributions/gradle-8.12.1-bin.zip
```
Comment (sanjaysargam) [inline gradle/wrapper/gradle-wrapper.properties]: unwanted change. please undo this

**Comment by Haz3-jolt** [comment]
@Ayush-Patel-56 please rewrite the PR to use our template, it is quite hard to otherwise, paste outputs of your test results but ideally screenshots or even a screen recording. 

It is hard to review without these.

**Comment by Ayush-Patel-56** [comment]
> @Ayush-Patel-56 please rewrite the PR to use our template, it is quite hard to otherwise, paste outputs of your test results but ideally screenshots or even a screen recording.
> 
> It is hard to review without these.

@Haz3-jolt Thanks for the guidance! I've updated the PR description to follow the template and attached a screen recording demonstrating the fix (case-insensitive search and smooth deletion).

File: AnkiDroid/src/test/java/com/ichi2/anki/notetype/ManageNoteTypesViewModelTest.kt [hunk 4]
```diff
@@ -159,6 +159,20 @@ class ManageNoteTypesViewModelTest : RobolectricTest() {
...
+        runTest {
+            val testName = "MixedCaseName"
+            addStandardNoteType(testName, arrayOf("front", "back"), "", "")
+            val viewModel = ManageNoteTypesViewModel()
+            viewModel.filter("mixedcasename")
+            val currentlyDisplayed =
+                viewModel.state.value.noteTypes
+                    .filter { it.shouldBeDisplayed }
+            assertThat(currentlyDisplayed, hasSize(1))
+            assertEquals(testName, currentlyDisplayed[0].name)
```
Comment (david-allison) [inline AnkiDroid/src/test/java/com/ichi2/anki/notetype/ManageNoteTypesViewModelTest.kt]: `testName` would be better than `currentlyDisplayed[0].name`

Comment (Ayush-Patel-56) [reply AnkiDroid/src/test/java/com/ichi2/anki/notetype/ManageNoteTypesViewModelTest.kt]: Thanks! I see your point. Since you approved the PR, do you want me to push a commit to change that assertion style, or is it fine as-is for this PR?

Comment (david-allison) [reply AnkiDroid/src/test/java/com/ichi2/anki/notetype/ManageNoteTypesViewModelTest.kt]: implementer's choice.

Preferred that you squash merge/amend & force push rather then adding a new commit

Comment (Ayush-Patel-56) [reply AnkiDroid/src/test/java/com/ichi2/anki/notetype/ManageNoteTypesViewModelTest.kt]: > implementer's choice.
> 
> Preferred that you squash merge/amend & force push rather then adding a new commit

Done! I updated the test assertion as suggested and force-pushed the changes.

**Comment by david-allison** [comment]
@Ayush-Patel-56 Thanks again!!!!

Please avoid merge commits in the history

When you want to get things up to date, rebase onto main, then force push the branch (force pushes to your own branches are strongly encouraged).

Our goal is to 'rebase merge' each PR, so unnecessary commits shouldn't make it to GitHub

See: https://github.com/ankidroid/Anki-Android/blob/main/CONTRIBUTING.md#handling-requests-for-changes

For your first few PRs, we're fine to squash merge in Android Studio, but it makes things flow faster if you take it on (this lefts us add it to the merge queue immediately, rather than needing to mess around with pulling your branch and making changes)

**Comment by Ayush-Patel-56** [comment]
> @Ayush-Patel-56 Thanks again!!!!
> 
> Please avoid merge commits in the history
> 
> When you want to get things up to date, rebase onto main, then force push the branch (force pushes to your own branches are strongly encouraged).
> 
> Our goal is to 'rebase merge' each PR, so unnecessary commits shouldn't make it to GitHub
> 
> See: https://github.com/ankidroid/Anki-Android/blob/main/CONTRIBUTING.md#handling-requests-for-changes
> 
> For your first few PRs, we're fine to squash merge in Android Studio, but it makes things flow faster if you take it on (this lefts us add it to the merge queue immediately, rather than needing to mess around with pulling your branch and making changes)

Thanks @david-allison for this information, I'll look into it in further issues.

**Comment by Ayush-Patel-56** [comment]
squash merge done !

**Comment by david-allison** [comment]
`fix(ManageNoteTypes): make searching case-insensitive`

Having "deletion" there is unusual

**Comment by Ayush-Patel-56** [comment]
> `fix(ManageNoteTypes): make searching case-insensitive`
> 
> Having "deletion" there is unusual

Thanks! Just to clarify, should I change the PR title or commit message to exactly fix(ManageNoteTypes): make searching case-insensitive? I included 'deletion' because this PR also fixes the backspace/delete key issue.

**Comment by david-allison** [comment]
commit message is permanent and should be designed for the long-term

We can and will fixup GitHub titles after the fact, but it should be edited as well. The title is better than the commit message title, so lower priority

**Comment by Ayush-Patel-56** [comment]
> commit message is permanent and should be designed for the long-term
> 
> We can and will fixup GitHub titles after the fact, but it should be edited as well. The title is better than the commit message title, so lower priority

Done! I've updated the commit message to be cleaner: fix(ManageNoteTypes): Make search case-insensitive and moved the deletion fix explanation to the body.
