### PR TITLE
Fixes #5404: Fix AnkiStatsTaskHandler's AsyncTasks' memory leaks & singleton pattern

### LINKED ISSUE #5404: Misuse of AsyncTask
###### Reproduction Steps
In com.ichi2.anki.stats. AnkiStatsTaskHandler
The problems is:
1. It holds strong reference to the GUI element of View or Activity, which can lead to memory leak when the Activity is destroyed and the AsyncTask did not finish.
```
private class CreateChartTask extends AsyncTask<View, Void, PlotSheet>
private ChartView mImageView;
//....
private class CreateStatisticsOverview extends AsyncTask<View, Void, String>
private WebView mWebView;
```
###### Expected Result
```
private class CreateChartTask extends AsyncTask<View, Void, PlotSheet>
private WeakReference<ChartView> mImageView;
//....
private class CreateStatisticsOverview extends AsyncTask<View, Void, String>
private WeakReference<WebView > mWebView;
```

### PR DESCRIPTION
**Pull request by farjadilyas**
## Purpose / Description
AsyncTasks in AnkiStatsTaskHandler are non-static & hold references to View objects. This can lead to potential memory leaks.

## Fixes
Fixes #5404 

## Approach

- It replaces the strong references to view objects in AsyncTasks with WeakReferences
- Turns the extended AsyncTasks into static inner classes
- Checks if a weakly referenced object isn't null before using. Attempts to update UI only if view objects exist.

## How Has This Been Tested?
-  Tested on SAMSUNG SM-A805F API 29 (Physical Device)
- Pixel 3a XL API 27 (Emulator)
- Pixel 2 API 24 (Emulator)

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
No UI changes

### CODE REVIEW

**Comment by farjadilyas** [comment]
I have only made changes to CreateChartTask for now. If this seems like the right approach, I can go ahead and make the changes for the other two AsyncTask inner classes in AnkiStatsTaskHandler.java & other non-static inner classes extending AsyncTask

File: AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java [hunk 1]
```diff
@@ -78,34 +85,41 @@ public static DeckPreviewStatistics createReviewSummaryStatistics(Collection col
...
                     return null;
                 } else {
                     Timber.d("Starting CreateChartTask, type: %s", mChartType.name());
                 }
-                mImageView = (ChartView) params[0];
-                mProgressBar = (ProgressBar) params[1];
-                ChartBuilder chartBuilder = new ChartBuilder(mImageView, mCollectionData,
+                mImageView = new WeakReference<>((ChartView) params[0]);
+                mProgressBar = new WeakReference<>((ProgressBar) params[1]);
+                ChartBuilder chartBuilder = new ChartBuilder(mImageView.get(), collectionData,
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java:122]: Don't use `mImageView.get()`, just in case - extract the concrete reference and use that.

File: AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java [hunk 2]
```diff
@@ -130,7 +130,7 @@ public void onNothingSelected(AdapterView<?> parent) {
         mActionBarSpinner.setVisibility(View.VISIBLE);
 
         // Setup Task Handler
-        mTaskHandler = new AnkiStatsTaskHandler(col);
+        mTaskHandler = AnkiStatsTaskHandler.getInstance(col);
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java:133]: Could you explain this change?

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
This looks good to me, aside from the comments:

* Could you change the commit message header to 50 chars
* Could you stick the additional information that you added to the PR template into the commit message body

File: AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java (hunk 2 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java:133]: Nevermind - I see: `new AnkiStatsTaskHandler()` was setting `sInstance`

**Comment by Arthur-Milchior** [comment]
Do we know why it was using AsyncTask directly and not a CollectionTask ? Especially since both uses the same executor, the default one.

Seems good really. My question is really about current code, not about this PR

**Comment by farjadilyas** [comment]
> Do we know why it was using AsyncTask directly and not a CollectionTask ? Especially since both uses the same executor, the default one.
> 
> Seems good really. My question is really about current code, not about this PR

That's a good point! I haven't been able to figure out why CollectionTask wasn't used since it can basically replace AsyncTask. I implemented one of the AsyncTasks: CreateChartTask using CollectionTask and it works just fine. Should we move to use CollectionTask instead of the 3 AsyncTasks in AnkiStatsTaskHandler since extending the Task class is more understandable than extending the AsyncTask class itself? 

Also, since ```mContext``` in CollectionTask is only used in doInBackground() & getContext() isn't used, we can make it a local variable and get rid of the Lint warning: 'This field leaks a Context object'.

**Review by david-allison-1 — APPROVED** [review]
Looks good to me, thanks!

File: AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java [hunk 3]
```diff
@@ -236,10 +269,12 @@ protected void onCancelled() {
 
         @Override
         protected void onPostExecute(String todayStatString) {
-            if (todayStatString != null && mIsRunning) {
-                mTextView.setText(todayStatString);
-                mTextView.setVisibility(View.VISIBLE);
-                mTextView.invalidate();
+            TextView textView = mTextView.get();
+
+            if (todayStatString != null && mIsRunning && textView != null) {
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java:274]:
```suggestion
            if ((todayStatString != null) && mIsRunning && (textView != null)) {
```

File: AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java [hunk 4]
```diff
@@ -168,23 +197,26 @@ protected void onCancelled() {
 
         @Override
         protected void onPostExecute(String html) {
-            if (html != null && mIsRunning) {
+            WebView webView = mWebView.get();
+            ProgressBar progressBar = mProgressBar.get();
+
+            if (html != null && mIsRunning && webView != null && progressBar != null) {
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java:203]:
```suggestion
            if ((html != null) && mIsRunning && (webView != null) && (progressBar != null)) {
```

File: AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java [hunk 5]
```diff
@@ -120,41 +136,54 @@ protected void onCancelled() {
...
         protected void onPostExecute(PlotSheet plotSheet) {
-            if (plotSheet != null && mIsRunning) {
-                mImageView.setData(plotSheet);
-                mProgressBar.setVisibility(View.GONE);
-                mImageView.setVisibility(View.VISIBLE);
-                mImageView.invalidate();
+            ChartView imageView = mImageView.get();
+            ProgressBar progressBar = mProgressBar.get();
+
+            if (plotSheet != null && mIsRunning && imageView != null && progressBar != null) {
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java:142]:
```suggestion
            if ((plotSheet != null) && mIsRunning && (imageView != null) && (progressBar != null)) {
```

File: AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java [hunk 6]
```diff
@@ -120,41 +136,54 @@ protected void onCancelled() {
...
 
         @Override
         protected String doInBackground(View... params) {
             //make sure only one task of CreateChartTask is running, first to run should get sLock
             //only necessary on lower APIs because after honeycomb only one thread is used for all asynctasks
             sLock.lock();
+            Collection collectionData = mCollectionData.get();
             try {
-                if (!mIsRunning) {
+                if (!mIsRunning || collectionData == null) {
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java:175]:
```suggestion
                if (!mIsRunning || (collectionData == null)) {
```

File: AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java [hunk 7]
```diff
@@ -78,34 +85,43 @@ public static DeckPreviewStatistics createReviewSummaryStatistics(Collection col
...
 
         @Override
         protected PlotSheet doInBackground(View... params) {
             //make sure only one task of CreateChartTask is running, first to run should get sLock
             //only necessary on lower APIs because after honeycomb only one thread is used for all asynctasks
             sLock.lock();
+            Collection collectionData = mCollectionData.get();
             try {
-                if (!mIsRunning) {
+                if (!mIsRunning || collectionData == null) {
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java:114]:
```suggestion
                if (!mIsRunning || (collectionData == null)) {
```

**Review by mikehardy — CHANGES_REQUESTED** [review]
All of my comments are trivial - the PR itself is good, just spacing or explicit parentheses items, nothing important.

It seems like there was some unfinished conversation around using CollectionTask - that seems like it could make a good follow-on PR if you are interested, but since this has been reviewed by everyone already and all that's left is trivial formatting stuff, probably best to just polish this and get it in

Thank you!

**Comment by mikehardy** [comment]
maintainer note: happy for anyone to merge after my batch of trivial nitpicks is handled

**Review by mikehardy — APPROVED** [review]
Nice! And the rebase / force-push for clean commit history +1
