### PR TITLE
CardViewer - Fix crash viewing card after close

### LINKED ISSUE #6446: Ankidroid stopped working / crashed (I do not remember exact error message) after accidently pressing two different buttons
On couple of occassions I came across a bug that resulted in app crashing/terminating. Before crashing there was this error message I put into the title (that I do not remember precisely).

The bug occured when I accidentally pressed "easy" button in the app while reviewing cards and "back" button on the phone, both at the same time (as highlighted in the picture).

However I am not able to reproduce this bug when I try to, so I guess it is not determined just by me pressing those two different buttons at the same time, but also by some randomness.

I am having a bit older smartphone - S3 mini and using the latest version of Ankidroid. However I have been coming across this issue for a very long time. First time maybe over one year ago, if not even earlier. In terms of periodicity, I would say this bug happens to me maybe once a week. Sorry for not bringing it up earlier, it did not cause me a lot of pain in life, but after having seen it already quite a lot of time (in total), I wanted to give a shout about it.

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description

`loadDataWithBaseURL` throws a `NullPointerException` if called after onDestroy

https://stackoverflow.com/questions/28856883/java-nullpointer-exception-from-webview-in-android-webkit-webviewclassic-loaddat

## Fixes
Fixes #6446

## Approach
Detect if `onDestroy()` was called, and stop rendering if that happeend,

## How Has This Been Tested?

API 16 emulator (hit the `Timber.w` with no crashes) and Android 9 device.

## Learning

⚠️ Please read: https://developer.android.com/reference/android/app/Activity#isDestroyed() - mentions "final onDestroy" - This goes against my knowledge of the lifecycle.

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 1]
```diff
@@ -2603,6 +2603,17 @@ public MyWebView(Context context) {
             super(context);
         }
 
+
+        @Override
+        public void loadDataWithBaseURL(@Nullable String baseUrl, String data, @Nullable String mimeType, @Nullable String encoding, @Nullable String historyUrl) {
+            if (!AbstractFlashcardViewer.this.wasDestroyed()) {
+                super.loadDataWithBaseURL(baseUrl, data, mimeType, encoding, historyUrl);
+            } else {
+                Timber.w("Now loading card - Activity is in the process of being destroyed.");
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:2612]:
```suggestion
                Timber.w("Not loading card - Activity is in the process of being destroyed.");
```
