### PR TITLE
fix: Card Browser Search History removals

### LINKED ISSUE #14989: [Bug] CardBrowser: Deleting search history is broken
Relevant code

https://github.com/ankidroid/Anki-Android/blob/49dc7bdfac924756a1e31421ed297888a2612c66/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt#L307-L315

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
* high priority compared to my other `CardBrowser` refactorings
* #14989

## Fixes
* Fixes #14989

## Approach
* test the problem
* fix the problem
* refactor the problem
* Fix a bug encountered while testing a pure `JvmTest` and explain why it occurred

## How Has This Been Tested?
Unit tests added, one manual test

## Learning (optional, can help others)
I actually wasn't planning on refactoring this aspect of the CardBrowser

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt [hunk 1]
```diff
@@ -306,6 +307,38 @@ class CardBrowserViewModel(
...
+        Timber.d("saving user search")
+        var alreadyExists = false
+        updateSavedSearches {
+            if (get(searchName) != null) {
+                alreadyExists = true
+            } else {
+                set(searchName, searchTerms)
+            }
+        }
+        return if (alreadyExists) SaveSearchResult.ALREADY_EXITS else SaveSearchResult.SUCCESS
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt:339]: Typo

**Review by mikehardy — APPROVED** [review]
pending typo fix noted, approval though

**Review by BrayanDSO — APPROVED** [review]
