### PR TITLE
CardBrowser: Multiple Selection Fixes

### LINKED ISSUE #5464: Missing option to select all cards if none is selected
After you select a card in the Card Browser, the option to select all is available, but it is not if a card is not selected.

I've checked the discussion about the multiselect issue (https://github.com/ankidroid/Anki-Android/issues/2339), but there was not mention about it.
It should be an easy fix and more intuitive for the users.

I'm using the 2.9Beta12 version.

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description

The Card Browser could not display "Select All" and "Select None" at the same time

The Card Browser did not display "Select All" when no cards were selected

When "Select None" was clicked, the browser remained in Multi-Select Mode

When no cards are *available*, "Select All" should not be visible. *Edited*

## Fixes
Fixes #5464

## Approach

We add in additional items in the layout:

* New "Select All" in the unselected mode
* Differentiate "Select All" and "Select None" in mutliselect mode.

We combine all previous state changes into a function which takes the current state into account, and sets the "Selection Buttons" to the correct states.

## How Has This Been Tested?

Both on my device, and via unit test

* 0 item deck
* Normal Decks
* Deleting cards so they become 0 item decks
* Adding items to 0 item decks
* Moving items out of 1 item decks

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

File: AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java [hunk 1]
```diff
@@ -0,0 +1,158 @@
+package com.ichi2.anki;
+
+import android.content.Intent;
+import android.view.View;
```
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java]: Codacy Issue found: [Avoid unused imports such as 'android.view.View'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5254252)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java  3
- AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5254252&bid=17216495)

File: AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java [hunk 2]
```diff
@@ -0,0 +1,158 @@
...
+import org.robolectric.Robolectric;
+import org.robolectric.android.controller.ActivityController;
+import org.robolectric.shadows.ShadowActivity;
+
+import javax.annotation.CheckReturnValue;
+
+import androidx.test.ext.junit.runners.AndroidJUnit4;
+import timber.log.Timber;
+
+import static android.view.HapticFeedbackConstants.LONG_PRESS;
```
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java]: Codacy Issue found: [Avoid unused imports such as 'android.view.HapticFeedbackConstants.LONG_PRESS'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5254252)

File: AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java [hunk 3]
```diff
@@ -0,0 +1,158 @@
+package com.ichi2.anki;
+
+import android.content.Intent;
+import android.view.View;
+import android.widget.AdapterView;
+import android.widget.ListAdapter;
```
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java]: Codacy Issue found: [Avoid unused imports such as 'android.widget.ListAdapter'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5254252)

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java [hunk 4]
```diff
@@ -717,7 +721,6 @@ public void onClick(View v) {
             // multi-select mode
             getMenuInflater().inflate(R.menu.card_browser_multiselect, menu);
             showBackIcon();
-            updateMultiselectMenu();
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java]: performed in `onSelectionChanged`

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java [hunk 5]
```diff
@@ -1438,7 +1463,6 @@ private void removeNotesView(Card[] cards) {
         protected void actualPostExecute(DeckTask.TaskData result) {
             Card[] cards = (Card[]) result.getObjArray();
             updateCardsInList(Arrays.asList(cards), null);
-            updateMultiselectMenu();
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java]: `updateCardsInList` -> `upadateList` -> `onSelectionChanged`

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java [hunk 6]
```diff
@@ -1798,28 +1821,47 @@ private void onCheck(int position, View cell) {
...
-            mActionBarTitle.setText(Integer.toString(mCheckedCardPositions.size()));
+    private void onSelectAll() {
+        for (int i = 0; i < mCards.size(); i++) {
+            mCheckedCardPositions.add(i);
         }
+        onSelectionChanged();
     }
 
-    private void onCheckAll() {
-        boolean all = mCheckedCardPositions.size() < getCards().size();
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java]: This button had two purposes, we split it into onSelectAll and onSelectNone

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java  3
- AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5254252&bid=17216495)

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java [hunk 7]
```diff
@@ -1825,20 +1830,25 @@ private void onCheck(int position, View cell) {
...
-            mCheckedCardPositions.clear();
+    private void onSelectAll() {
+        for (int i = 0; i < mCards.size(); i++) {
+            mCheckedCardPositions.add(i);
         }
+        onSelectionChanged();
+    }
+
+    private void onSelectNone() {
+        mCheckedCardPositions.clear();
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java]: I've seen in one other place that async tasks are sometimes working on CardBrowser member variables, and a clear causes NPEs and ConcurrentModExceptions - how would you feel about changing this from .clear() to creating a new empty object? Feels like a defensive programming improvement to me

**Comment by mikehardy** [comment]
The only thing I take issue with (other than my defensive programming thought) is this statement:

> When no cards are selected, "Select All" should not be visible.

I believe that is the way it works now, so this PR has fidelity with current behavior. But...why should it work that way? If I'm going to "select all" (as a real use case) it's almost always this in my mind: "search for the cards I want (maybe a whole deck or whatever)" then "select all". The fact I have to long-press first is already a subtle UX thing and for this (common I think?) use case it's just an extra step.

Seems like Select All should be there in all cases except when all are already selected?

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java (hunk 7 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java]: I don't particularly like it as it doesn't deal with the root cause 

> The only thing I take issue with (other than my defensive programming thought) is this statement:
> 
> > When no cards are selected, "Select All" should not be visible.
> 
> I believe that is the way it works now, so this PR has fidelity with current behavior. But...why should it work that way? If I'm going to "select all" (as a real use case) it's almost always this in my mind: "search for the cards I want (maybe a whole deck or whatever)" then "select all". The fact I have to long-press first is already a subtle UX thing and for this (common I think?) use case it's just an extra step.
> 
> Seems like Select All should be there in all cases except when all are already selected?

Sorry... "When no cards are *available*". (No search results).

**Comment by david-allison-1** [comment]
> Seems like Select All should be there in all cases except when all are already selected?

Mis-specification. I'll edit. When no cards are *available*.

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java (hunk 7 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java]: Is there a reason we're not using a concurrent structure for this instead?

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java]: no reason in particular :-), in general because concurrency is hard - and simply throwing the old object on the GC (either now, or when async task is finished) seems so easy...

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java  3
- AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5254252&bid=17216495)

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java (hunk 7 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java]: Flipped to a concurrent structure. Doesn't look too painful in this instance

**Comment by david-allison-1** [comment]
Pending fix on the following. This won't be saved by thread safety.

https://github.com/ankidroid/Anki-Android/blob/d3a6c61ac791d48fe2c684a6302640237968814a/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java#L358-L365

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java  3
- AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5254252&bid=17216495)

**Comment by david-allison-1** [comment]
> Looks good to me - this will make a lot more sense to users, thanks - hopefully fix a crash too. Ready for merge and release when I do the next alpha?

Good to go

**Comment by mikehardy** [comment]
gotta fix 'em all ;-)
