### PR TITLE
Make available current card's and deck's details in WebView

### LINKED ISSUE #6306: Is there better way to get values from Deck to WebView?
###### Reproduction Steps

I have added following codes to AnkiDroid.

[card.js](https://github.com/infinyte7/Anki-Android/blob/master/AnkiDroid/src/main/assets/scripts/card.js#L78)
<br>``` view.loadUrl ```
[AbstractFlashcardViewer.java](https://github.com/infinyte7/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L3159)

Added custom card layout using css and js to deck template.
[Anki-Custom-Card-Layout](https://github.com/infinyte7/Anki-Custom-Card-Layout)

demo

###### Expected Result
Is there a better way to following values without using ```setTimeout ```.
```
Deck Title,
ETA,
New, Learn, Review Card Counts
Mark,
four button or three button is there 
```
I get values ( cards count, title, mark, eta ) but by using ```setTimeout ``` function of ```javascript```.

###### Actual Result
WebView should get values without using ``` setTimeout ```.

###### Reason
It will help in card creation with custom layout.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x ] I have searched for similar existing issues here and on the user forum
- [ x ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by infinyte7**
## Purpose / Description
This PR make available the following details about cards
```
New Card Count
Learn Card Count
Review Card Count
ETA
Mark
Flag
```
Also following functions available to make any design of button using css and calling using JS
```
showAnswer()
buttonAnswerEase1()
buttonAnswerEase2()
buttonAnswerEase3()
buttonAnswerEase4()
ankiMarkCard()
ankiToggleFlag()
``` 
Usage of ```ankiToggleFlag()```
```
ankiToggleFlag('none')
ankiToggleFlag('red')
ankiToggleFlag('orange')
ankiToggleFlag('green')
ankiToggleFlag('blue')
```
Using numeric values
```
ankiToggleFlag(0)   // none
ankiToggleFlag(1)   // red
ankiToggleFlag(2)   // orange
ankiToggleFlag(3)   // green
ankiToggleFlag(4)   // blue
```
Using above and css & js, following type of card can be designed
https://github.com/infinyte7/Anki-Custom-Card-Layout

## Fixes
Fixes #6306

## Approach
_How does this change address the problem?_
Using JavascriptInterface.

## How Has This Been Tested?
[Sample Deck](https://github.com/infinyte7/Anki-Custom-Card-Layout/blob/master/HSK1.apkg) can be used for testing (Contents in deck may be changed to get it work)

1. Turn on Gestures in AnkiDroid or use immersive mode
2. Map all Swipe getures to No Action
3. Turn on Full Screen
4. Add following to card 

To make available following details to AnkiDroid WebView, add it to Front / Back side of Card in ```<script>``` tag. 
```
 <script>
        console.log(AnkiDroidJS.ankiGetNewCardCount());
        console.log(AnkiDroidJS.ankiGetLrnCardCount());
        console.log(AnkiDroidJS.ankiGetRevCardCount());
        console.log(AnkiDroidJS.ankiGetCardMark());
        console.log(AnkiDroidJS.ankiGetCardFlag());
        console.log(AnkiDroidJS.ankiGetETA());
 </script>
```
5. Now use those values to redesign the card templates.

## Demo
anki_js_demo

## Learning (optional, can help others)
https://developer.android.com/reference/android/webkit/JavascriptInterface
https://stackoverflow.com/questions/21173888/how-to-pass-non-primitive-object-from-java-to-js-by-android-addjavascriptinterfa
https://stackoverflow.com/questions/175739/built-in-way-in-javascript-to-check-if-a-string-is-a-valid-number
https://grid.layoutit.com/
https://codepen.io/
https://www.w3schools.com/

## Checklist
_Please, go through these checks before submitting the PR._

- [ x ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ x ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ x ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ x ] You have commented your code, particularly in hard-to-understand areas
- [ x ] You have performed a self-review of your own code

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 1]
```diff
@@ -3022,6 +3040,34 @@ private boolean filterUrl(String url) {
                 redrawCard();
                 return true;
             }
+            // mark card using javascript
+            if (url.startsWith("signal:mark_current_card")) {
```
Comment (infinyte7) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3044]: Is there way to implement switch() here?

**Comment by infinyte7** [comment]
I have implemented as suggested.

**Comment by mikehardy** [comment]
A strong "maybe" on all of those. Take a stand and be very specific about exactly what it should be. I would plead with you to focus on the concrete pain points you see right now or problems you have seen actually happen as opposed to theoretical - for instance, the signal handling is quote verbose in Java and doesn't have parameters, so the actual message passing could be better. And, e.g. I have experience namespace pollution issues so I asked for that one.

I'm inclined to mark all of these somehow as exploratory, with a Wiki page targetted at a new class of developer we will have asking for testing, thoughts, and understanding as the API may have completely breaking changes as we learn through use. A specific mention that if you use the APIs and are not willing to collaborate and both propose and accept breaking changes you should wait, but otherwise please join the party.

I am biased strongly towards working code (which this is) vs ivory tower design delay, so think hard, propose changes if needed, then let's get it out there

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 2]
```diff
@@ -3135,6 +3181,13 @@ public void onPageFinished(WebView view, String url) {
             drawFlag();
             drawMark();
             view.loadUrl("javascript:onPageFinished();");
+
+            // cards count, deckname, estimated time, mark, flag to be accessible in AnkiDroid WebView
+            view.loadUrl("javascript:ankiGetCardCount(" + newCount.toString() +  "," + lrnCount.toString() + "," + revCount.toString()  + ")" );
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3186]: Can these be changed to `JavascriptInterface` methods: https://developer.android.com/reference/android/webkit/JavascriptInterface

We're currently open to accidental XSS which will break cards JS

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 3]
```diff
@@ -176,6 +176,22 @@
 
     protected static final int MENU_DISABLED = 3;
 
+    // Deckname
+    private String title;
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:180]: This needed to happen for a long time.

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 4]
```diff
@@ -176,6 +176,22 @@
 
     protected static final int MENU_DISABLED = 3;
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:178]:
```suggestion
    // TODO: Consider extracting to ViewModel
```

File: AnkiDroid/src/main/assets/scripts/card.js [hunk 5]
```diff
@@ -99,6 +99,62 @@ function reloadPage() {
...
+// Card Mark
+function ankiGetCardMark(ankiMark) {
+   window.ankiMark = ankiMark;
+}
+
+/**
+* card flagged or not
+* (none = 0, red = 1, orange = 2, green = 3 blue = 4)
+**/
+function ankiGetCardFlag(ankiFlagStatus) {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/assets/scripts/card.js:133]: `onCardFlag`

File: AnkiDroid/src/main/assets/scripts/card.js [hunk 6]
```diff
@@ -99,6 +99,62 @@ function reloadPage() {
...
+   window.ankiDeckName = ankiDeckName;
+}
+
+// Get estimated time
+function ankiGetETA(ankiETA) {
+   window.ankiETA = ankiETA;
+}
+
+// Card Mark
+function ankiGetCardMark(ankiMark) {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/assets/scripts/card.js:125]: `onCardMark`

File: AnkiDroid/src/main/assets/scripts/card.js [hunk 7]
```diff
@@ -99,6 +99,62 @@ function reloadPage() {
...
+    window.ankiRevCount = ankiRevCount;
+}
+
+// Get Current Deck Name
+function ankiGetDeckName(ankiDeckName) {
+   window.ankiDeckName = ankiDeckName;
+}
+
+// Get estimated time
+function ankiGetETA(ankiETA) {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/assets/scripts/card.js:120]: Move to a field substitution if possible

File: AnkiDroid/src/main/assets/scripts/card.js [hunk 8]
```diff
@@ -99,6 +99,62 @@ function reloadPage() {
     window.location.href = "signal:reload_card_html";
 }
 
+// Mark current card
+function ankiMarkCard() {
+    window.location.href = "signal:mark_current_card";
+}
+
+// Get new card, learn card, review card counts in ankidroid webview. It will be accessible via javascript
+function ankiGetCardCount(ankiNewCount, ankiLrnCount, ankiRevCount) {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/assets/scripts/card.js:108]: This has semantic differences between SchedV1 and SchedV2. We also want to include relearn count. 

This would be better as an object so we can add more properties without breaking the API contract.

There's a few Anki addons that do thing similar to this already (and probably the same thing), we should follow their naming scheme.

File: AnkiDroid/src/main/assets/scripts/card.js [hunk 9]
```diff
@@ -99,6 +99,62 @@ function reloadPage() {
...
+    window.ankiNewCount = ankiNewCount;
+    window.ankiLrnCount = ankiLrnCount;
+    window.ankiRevCount = ankiRevCount;
+}
+
+// Get Current Deck Name
+function ankiGetDeckName(ankiDeckName) {
+   window.ankiDeckName = ankiDeckName;
```
Comment (david-allison-1) [inline AnkiDroid/src/main/assets/scripts/card.js:116]: Should be in `{{Deck}}`

File: AnkiDroid/src/main/assets/scripts/card.js [hunk 10]
```diff
@@ -99,6 +99,62 @@ function reloadPage() {
...
+* card flagged or not
+* (none = 0, red = 1, orange = 2, green = 3 blue = 4)
+**/
+function ankiGetCardFlag(ankiFlagStatus) {
+    window.ankiFlagStatus = ankiFlagStatus;
+}
+
+// Flag the card from AnkiDroid Webview using JavaScript
+function ankiToggleFlagRed() {
+    window.location.href = "signal:card_toggle_flag_red";
```
Comment (david-allison-1) [inline AnkiDroid/src/main/assets/scripts/card.js:139]: Merge all the flag signals into one, similar to `signal:typeblurtext:xxx`

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 11]
```diff
@@ -3022,6 +3040,34 @@ private boolean filterUrl(String url) {
                 redrawCard();
                 return true;
             }
+            // mark card using javascript
+            if (url.startsWith("signal:mark_current_card")) {
+                onMark(mCurrentCard);
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3045]: use `executeCommand` here, as this provides protection for when the card is null/controls are disabled

File: AnkiDroid/src/main/assets/scripts/card.js (hunk 9 above)
Comment (infinyte7) [reply AnkiDroid/src/main/assets/scripts/card.js]: yes, {{Deck}} return the deckname

File: AnkiDroid/src/main/assets/scripts/card.js (hunk 8 above)
Comment (infinyte7) [reply AnkiDroid/src/main/assets/scripts/card.js]: For relearn card one function may be added in Javascript Interface

**Comment by infinyte7** [comment]
Using JavaScript Interface, there is need to use ```setTimeout()```.

File: AnkiDroid/src/main/assets/scripts/card.js [hunk 12]
```diff
@@ -99,6 +99,16 @@ function reloadPage() {
...
 }
 
+// Mark current card
+function ankiMarkCard() {
+    window.location.href = "signal:mark_current_card";
+}
+
+// Toggle flag on card from AnkiDroid Webview using JavaScript
+function ankiToggleFlag(flag) {
+    window.location.href = "flag:" + flag;
```
Comment (david-allison-1) [inline AnkiDroid/src/main/assets/scripts/card.js:109]: Add a `signal:` prefix to maintain consistency

File: AnkiDroid/src/main/assets/scripts/card.js [hunk 13]
```diff
@@ -99,6 +99,16 @@ function reloadPage() {
     window.location.href = "signal:reload_card_html";
 }
 
+// Mark current card
+function ankiMarkCard() {
+    window.location.href = "signal:mark_current_card";
+}
+
+// Toggle flag on card from AnkiDroid Webview using JavaScript
+function ankiToggleFlag(flag) {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/assets/scripts/card.js:108]: This needs to document what the flag command accepts. I would have assumed that it accepts 0..4

It would be better to accept both the numeric constants, and the string values.

Comment (infinyte7) [reply AnkiDroid/src/main/assets/scripts/card.js:111]: It can be done using this and adding case for mFlagInt.
int mFlagInt = Integer.parseInt(mFlag);

But passing the color name is look good to me.

Comment (david-allison-1) [reply AnkiDroid/src/main/assets/scripts/card.js:111]: Keep the input code in `AbstractFlashCardViewer` consistent (either as strings, or ints), and coerce the data in Javascript.

I'm not a JS dev, but there should be an easy way to determine if an input is a string or a number.

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 14]
```diff
@@ -3022,6 +3034,30 @@ private boolean filterUrl(String url) {
...
+                    case "red": executeCommand(COMMAND_TOGGLE_FLAG_RED);
+                        return true;
+                    case "orange": executeCommand(COMMAND_TOGGLE_FLAG_ORANGE);
+                        return true;
+                    case "green": executeCommand(COMMAND_TOGGLE_FLAG_GREEN);
+                        return true;
+                    case "blue": executeCommand(COMMAND_TOGGLE_FLAG_BLUE);
+                        return true;
+                    default:
+                        return true;
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3057]: Could you log: `Timber.i` that this was ignored

**Comment by infinyte7** [comment]
It is working as expected.
捕获

File: AnkiDroid/src/main/assets/scripts/card.js [hunk 15]
```diff
@@ -109,7 +109,21 @@ function ankiMarkCard() {
     See AnkiDroid Manual for Usage
 */
 function ankiToggleFlag(flag) {
-    window.location.href = "signal:" + flag;
+    var flagVal = isNaN(flag);
```
Comment (david-allison-1) [inline AnkiDroid/src/main/assets/scripts/card.js:112]: I'm not in my comfort zone, but I don't feel this is correct (ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN - Confusing special-case behavior), as it's checking for the IEEE-754 NaN, rather than performing a type coercion.

`Number.isInteger()` seems like a better option, but I'll defer to @mikehardy 's javascript knowledge

Comment (infinyte7) [reply AnkiDroid/src/main/assets/scripts/card.js:112]: May be there will be better implementation for this. 
but using this 
```javascript
Number.isInteger(123)    // return true
Number.isInteger('123')  // return false
Number.isInteger('red')  // return false
```
Using ```NaN```
```javascript
isNaN(123)   // return false
isNaN('123')   // return false
isNaN('123')   // return true
```
Benefits of this,  if user passed value as ```  "1" or 1 ``` for red flag. The card will be flagged with red flag .

**Comment by infinyte7** [comment]
I have made an AnkiDroid deck for this.

https://github.com/infinyte7/Anki-Custom-Card-Layout

**Comment by infinyte7** [comment]
For getting nextTime1, nextTime2, nextTime3, nextTime4.
I have added this.
```java
@JavascriptInterface
public String ankiGetNextTime1() { return (String) mNext1.getText(); }

@JavascriptInterface
public String ankiGetNextTime2() { return (String) mNext2.getText(); }
        
@JavascriptInterface
public String ankiGetNextTime3() { return (String) mNext3.getText(); }

@JavascriptInterface
public String ankiGetNextTime4() { return (String) mNext4.getText(); }
```
This will help when answerButtonEase4 is called from webview and present then answerButtonEase3 will be called.

In WebView 
```javascript
function button4Clicked() {
     if (AnkiDroidJS.ankiGetNextTime4() == "") {
          answerButtonEase3();
     } else {
          answerButtonEase4();
     }
}
``` 
Should I add those to this PR?

File: AnkiDroid/src/main/assets/scripts/card.js [hunk 16]
```diff
@@ -99,6 +99,32 @@ function reloadPage() {
     window.location.href = "signal:reload_card_html";
 }
 
+// Mark current card
+function ankiMarkCard() {
+    window.location.href = "signal:mark_current_card";
+}
+
+/* Toggle flag on card from AnkiDroid Webview using JavaScript
+    none, red, orange, green, blue
```
Comment (david-allison-1) [inline AnkiDroid/src/main/assets/scripts/card.js:108]:
```suggestion
    possible values: "none", "red", "orange", "green", "blue"
```

**Comment by david-allison-1** [comment]
@infinyte7, I don't disagree, but it'd be better to move the additional changes into a separate PR, so we can get this into the codebase as soon as possible after @mikehardy has had a look.

I think we also need to consider how to best display "Good/(Hard)/Again/Easy" to developers.

**Comment by infinyte7** [comment]
The all button get exposed to card developer. 
And they have to decide which button to show and hide using this
```javascript
if (AnkiDroidJS.ankiGetNextTime1() == "") {
    document.getElementById('button1').style.display ="hidden";
}

if (AnkiDroidJS.ankiGetNextTime2() == "") {
    document.getElementById('button2').style.display ="hidden";
}

if (AnkiDroidJS.ankiGetNextTime3() == "") {
    document.getElementById('button3').style.display ="hidden";
}

if (AnkiDroidJS.ankiGetNextTime4() == "") {
    document.getElementById('button4').style.display ="hidden";
}
```

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5611736&bid=18384462)

File: AnkiDroid/src/main/assets/scripts/card.js [hunk 17]
```diff
@@ -99,6 +99,32 @@ function reloadPage() {
...
+    var flagVal = Number.isInteger(flag);
+
+    if (flagVal) {
+        switch (flag) {
+            case 0: window.location.href = "signal:flag_none"; break;
+            case 1: window.location.href = "signal:flag_red"; break;
+            case 2: window.location.href = "signal:flag_orange"; break;
+            case 3: window.location.href = "signal:flag_green"; break;
+            case 4: window.location.href = "signal:flag_blue"; break;
+            default: console.log('No Flag Found'); break;
```
Comment (timrae) [inline AnkiDroid/src/main/assets/scripts/card.js:121]: Codacy Issue found: [Strings must use doublequote.](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5611736)

Comment (timrae) [inline AnkiDroid/src/main/assets/scripts/card.js:121]: Codacy Issue found: [Unexpected console statement.](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5611736)

**Comment by mikehardy** [comment]
This change looks good - I'll merge it and put it in the next alpha
I logged #6328 to capture the need to do some API versioning
