### PR TITLE
fix: Auto advance doesn't work until the card is flipped once

### LINKED ISSUE #18705: Auto advance doesn't work until the card is flipped once
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

On 2.21.0beta4 or higher (2.22alpha1),

1. Make sure that Auto Advance is enabled in Deck options of the deck
    
2. Select `Toggle auto advance` in Study screen menu
   - Then `Auto Advance enabled` snackbar is shown
　
3. Wait for the auto advance action until the specified time has passed

**Result**
- Nothing happens.
　

- The auto advance action starts only after the card is manually flipped (i.e., switched from the front side to the back side, or from the back side to the front side of the next card) once.

https://github.com/user-attachments/assets/af5f4d6d-ca36-44e9-a58c-a93370bcbc96

### Expected behaviour

The specified action (e.g., Show Answer) is automatically done.

### Debug info

```text
AnkiDroid Version = 2.21.0beta4 (3b5489b76c7aa9944f5d62212fa3e09aca35941d)  
Backend Version = 0.1.54-anki25.02.7 (25.02.7 98253c81cb3c4d203acec48d6eae6b488bf484d0)  
Android Version = 11 (SDK 30)  
ProductFlavor = full  
Device Info = OPPO | OPPO | OP4BAFL1 | CPH2013 | CPH2013 | qcom  
Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/138.0.7204.45 Mobile Safari/537.36  
ACRA UUID = e30e37ae-b4ea-46cc-ab64-0e3d3fd0e16f  
FSRS = 2.0.3 (Enabled: false)  
Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by snowtimeglass**
## Purpose / Description
On 2.21.0beta4 or higher (2.22alpha1), Auto advance feature doesn't work (start) until the user manually flips the card once.

This PR intends to fix the issue.

## Fixes
* Fixes #18705

## Approach
Add auto advance scheduling process into "toggle auto advance" action

## How Has This Been Tested?

Checked on a physical device (Android 11)

**Before**

https://github.com/user-attachments/assets/93d3775b-b69e-4d6b-be3e-20c7ae0ff5eb

------

**After**

https://github.com/user-attachments/assets/4c889dd6-e0b2-4f52-9643-de65cef22f33

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt [hunk 1]
```diff
@@ -1677,6 +1677,18 @@ open class Reviewer :
         if (automaticAnswer.isDisabled) {
             Timber.i("Enabling auto advance")
             automaticAnswer.enable()
+
+            // Reset a flag (`hasPlayedSounds`) to false,
+            // for the following procedure scheduling automatic display
+            automaticAnswer.simulateCardFlip()
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt]: could you move this code inside `automaticAnswer` - then you don't need to write an explanation

Comment (snowtimeglass) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt]: @david-allison
I'm sorry, but I still don't catch specifically where you would like the code to be moved to in `automaticAnswer`, and how that move would work. Could you please elaborate a bit more?

(In my current understanding, the flag (`hasPlayedSounds`) usually serves to prevent double execution of `scheduleAutomaticDisplay...` method in `automaticAnswer` when the flag is `True`. This code in `Reviewer` above resets it to `False` at the time the user enables Auto advance.)

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt]: untested

```patch
Subject: [PATCH] aa
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/reviewer/AutomaticAnswer.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/reviewer/AutomaticAnswer.kt b/AnkiDroid/src/main/java/com/ichi2/anki/reviewer/AutomaticAnswer.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/reviewer/AutomaticAnswer.kt	(revision f84512a208ba41a174a2731fed0c60da4fcc28b8)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/reviewer/AutomaticAnswer.kt	(date 1751247698836)
@@ -164,6 +164,20 @@
         stopShowQuestionTask()
     }
 
+
+    fun reEnable(isDisplayingAnswer: Boolean) {
+        isDisabled = false
+        // required for the 'schedule' methods to work
+        hasPlayedSounds = false
+
+        // Schedule automatic display
+        if (isDisplayingAnswer) {
+            scheduleAutomaticDisplayQuestion()
+        } else {
+            scheduleAutomaticDisplayAnswer()
+        }
+    }
+
     /** Stop any "Automatic show answer" tasks in order to avoid race conditions */
     fun onDisplayQuestion() {
         if (!settings.autoAdvanceIfShowingQuestion) return
Index: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt b/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt	(revision f84512a208ba41a174a2731fed0c60da4fcc28b8)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt	(date 1751247677160)
@@ -1675,20 +1675,8 @@
 
     private fun toggleAutoAdvance() {
         if (automaticAnswer.isDisabled) {
-            Timber.i("Enabling auto advance")
-            automaticAnswer.enable()
-
-            // Reset a flag (`hasPlayedSounds`) to false,
-            // for the following procedure scheduling automatic display
-            automaticAnswer.simulateCardFlip()
-
-            // Schedule automatic display
-            if (isDisplayingAnswer) {
-                automaticAnswer.scheduleAutomaticDisplayQuestion()
-            } else {
-                automaticAnswer.scheduleAutomaticDisplayAnswer()
-            }
-
+            Timber.i("Re-enabling auto advance")
+            automaticAnswer.reEnable(isDisplayingAnswer)
             showSnackbar(TR.actionsAutoAdvanceActivated())
         } else {
             Timber.i("Disabling auto advance")
```

Comment (snowtimeglass) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt]: Thank you, I've caught what you mean: creating a new function. I'll try it.

Comment (snowtimeglass) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt]: I've tested the debug app with your code, and it worked as expected. Thanks.

-----

To make sure, wouldn't the current `enable()` lose one and only occasion to be used (except for tests) if the `reEnable()` is created and used as such? (In other words, isn't the content of `reEnable()` above for rewriting `enable()`?
image

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt]: I'm fine keeping `enable`, we'll be removing this code soon

Comment (snowtimeglass) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt]: Then, I'll push the tested change above with rebase.

**Review by mikehardy — APPROVED** [review]
seems reasonable - pending final look from David

**Review by david-allison — APPROVED** [review]

**Comment by david-allison** [comment]
Hi there @snowtimeglass! This is the OpenCollective Notice for PRs merged from [2025-06-01 through 2025-06-30](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2025-06-01..2025-06-30+author%3Asnowtimeglass)
                      
If you are interested in compensation for this work, the process with details is here: https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

We only post one comment per person per month to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for this month

Please understand that our monthly budget is never guaranteed to cover all claims - the cap on payments-per-person may be lower, but we try to make our process as fair and transparent as possible, we just need your understanding.

Thanks!
