### PR TITLE
Fix "Check Pronunciation" Keyboard Shortcut usage

### LINKED ISSUE #7780: Improvements: Update 2.15: Check Pronunciation shortcut
### Reproduction Steps: **Record not always works**
1. Press "Shift + V"
2. Release "Shift" before "V" triggers the play action

###### Expected Result
Recording is triggered, as intended to do so

###### Actual Result
Plays the recorded audio

(Maybe the listener sits on keyup?)

---

### Reproduction Steps: **Recording > Play / Play > Recording**
1] Press "Shift + V" (must release "shift" before "v", see previous issue reproduction)
2] While recording press "V"
  or
1] Press " V"
2] While playing press "Shift + V"

###### Expected Result
Current state is stopped and the desired state is triggered.

###### Actual Result
The previous state has to be stopped with the same keyboard shortcut before an different state can be activated.
eg. i have to press "Shift + V" again while recording to stop it, then its possible to press "V" for playing

---
### Improvement: **Keyboard layout**
**Description:** Because the phone is limited in display space it should have an different keyboard layout as the desktop version.

**Current situations:**
* Pressing an recording shortcut reduce screen content
* Record and Play should be easily accessible on the phone
* An shortcut for "Stop" as its not possible to start an recording from the start

**UX Solutions:**
* "V" show record buttons (+ resets current playing recorded audio) + start the recording
* "Shift + V" stops current playing and hiddes the buttons
* "B" plays/pause the recording
* "Shift + B" stops the playing

###### Reference
#7732 
#7733 
https://docs.ankiweb.net/#/studying?id=editing-and-more
Point **Record Own Voice**

Anki source code, record own voice
https://github.com/ankitects/anki/blob/98a4a1927a8e781a1c0b4a297caa8e86134ac027/qt/aqt/reviewer.py#L743-L744

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description
I added keyboard shortcuts to "Check Pronunciation", but they had a few issues:

* (long time) - shortcuts were on keyUp, not keyDown, this meant Shift + V did the wrong thing if `Shift` was released before `V`
* Pressing the "record" shortcut did work if playing
* Pressing the "play" shortcut did not work if recording

## Fixes
Fixes #7780 

## Approach
* ⚠️ Shortcuts are now on KeyDown - may need `AbstractFlashcardViewer`/`Reviewer` auditing
* Record stops "Play"
* Play stops "Record"

Also: 

* Abstracted out dependencies from `AudioView` and did end-to-end tests

## How Has This Been Tested?

Unit tested and tested on my phone with keyboard

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison-1** [comment]
To note: A UX improvement suggested at the end of the issue was not completed

**Comment by david-allison-1** [comment]
Needs emulator test fixing

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioView.java [hunk 1]
```diff
@@ -422,4 +422,22 @@ public void update() {
     public interface OnRecordingFinishEventListener {
         void onRecordingFinish(View v);
     }
+
+
+    @VisibleForTesting(otherwise = VisibleForTesting.NONE)
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioView.java:450]: just out of curiosity doesn't Android Studio complain at you if you say 'NONE' as the alternative on the visible for testing annotation, since that's the default? I recollect it warned me about it so I've been leaving them empty. This is not actionable or worth changing, I'm just curious

Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioView.java:450]: `VisibleForTesting.PRIVATE` is the default

**Review by mikehardy — APPROVED** [review]
Strategy seems sound, that is onKeyDown seems correct when I think of how other programs behave, test infra is fantastic!

**Comment by david-allison-1** [comment]
Pending on CI - emulator tests may still have an issue

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioView.java (hunk 1 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/AudioView.java:450]: Oh wow, just had a look at the docs. Didn't realize 'NONE' was even an option. Stronger than private obviously. Thanks!

**Comment by mikehardy** [comment]
all green :rocket:
