### PR TITLE
AnkiDroid to use flag names like anki

### LINKED ISSUE #16222: [BUG]: AnkiDroid to use Flag names like Anki
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

While working on #16218 I noticed that the flag names used in AnkiDroid doesn't match that of Anki, 

### Expected behaviour

Same names as Anki

### Actual behaviour

Different string values

### Debug info

```text
Not needed
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by Giyutomioka-SS**
## Purpose / Description
AnkiDroid to use Flag names like Anki 

## Fixes
* Fixes #16222 

## How Has This Been Tested?
On Realme 6 & Emulator

## Screen Recording
https://github.com/ankidroid/Anki-Android/assets/91668590/67718564-a5d6-44c6-b6cb-7f6b2ae89f30

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt [hunk 1]
```diff
@@ -29,28 +29,27 @@ enum class Flag(
...
-    TURQUOISE(6, R.drawable.ic_flag_turquoise, R.color.flag_turquoise, R.string.menu_flag_card_six),
-    PURPLE(7, R.drawable.ic_flag_purple, R.color.flag_purple, R.string.menu_flag_card_seven);
+    NONE(0, R.drawable.ic_flag_transparent, null, TR.browsingNoFlag()),
+    RED(1, R.drawable.ic_flag_red, R.color.flag_red, TR.actionsFlagRed()),
+    ORANGE(2, R.drawable.ic_flag_orange, R.color.flag_orange, TR.actionsFlagOrange()),
+    GREEN(3, R.drawable.ic_flag_green, R.color.flag_green, TR.actionsFlagGreen()),
+    BLUE(4, R.drawable.ic_flag_blue, R.color.flag_blue, TR.actionsFlagBlue()),
+    PINK(5, R.drawable.ic_flag_pink, R.color.flag_pink, TR.actionsFlagPink()),
+    TURQUOISE(6, R.drawable.ic_flag_turquoise, R.color.flag_turquoise, TR.actionsFlagTurquoise()),
+    PURPLE(7, R.drawable.ic_flag_purple, R.color.flag_purple, TR.actionsFlagPurple());
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt:41]: Store a reference to the function, not the result of the function. 

`defaultNameRes` should be `() -> String`

This means it works when a user has changed languages in the settings

**Review by david-allison — CHANGES_REQUESTED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt (hunk 1 above)
Comment (Giyutomioka-SS) [reply AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt:41]: Shouldn't it be like this: TR::browsingNoFlag ?

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt]: Yep, sounds corect

File: AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt [hunk 2]
```diff
@@ -29,28 +29,27 @@ enum class Flag(
     val code: Int,
     @DrawableRes val drawableRes: Int,
     @ColorRes val browserColorRes: Int?,
-    private val defaultNameRes: Int
+    private val defaultNameRes: () -> String
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt:32]:
```
    private val defaultBackendName: () -> String
```

File: AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt [hunk 3]
```diff
@@ -29,28 +29,27 @@ enum class Flag(
...
      * the default name resource ID is used to fetch the name from the application resources.
      *
-     * @param resources The Resources object used to access application resources.
      * @return The name associated with the flag, either fetched from overrides or default resources.
      */
-    suspend fun getName(resources: Resources): String {
+    suspend fun getName(): String {
         val overrides = withCol { config.getObject("flagLabels", JSONObject()) }
-        return overrides.getStringOrNull(code.toString()) ?: resources.getString(defaultNameRes)
+        return overrides.getStringOrNull(code.toString()) ?: defaultNameRes()
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt:52]: handle `defaultNameRes` throwing (if the backend is not open for some reason)

**Review by david-allison — CHANGES_REQUESTED** [review]
Looks great! Needs to handle errors, other than that, the other comment is a nitpick and this is good to go

**Comment by criticalAY** [comment]
`'byte[][] net.ankiweb.rsdroid.NativeMethods.openBackend(byte[])'`
Unit test are likely to fail again

**Comment by Giyutomioka-SS** [comment]
@david-allison, Unit tests are failing again. What should be done?

**Comment by Aditya13s** [comment]
@Giyutomioka-SS Remove the code or resource which are not in use.

**Comment by david-allison** [comment]
Ping me in 24h, feel free to pick up another issue in the meantime

**Comment by Giyutomioka-SS** [comment]
@david-allison

**Comment by Giyutomioka-SS** [comment]
> Ping me in 24h, feel free to pick up another issue in the meantime

@david-allison

**Comment by david-allison** [comment]
@Giyutomioka-SS with apologies, my laptop died today. 

Try our Discord for now, I'll be a while to get back to normal

**Comment by Giyutomioka-SS** [comment]
@david-allison please don’t apologize, machines can give up anytime, and i always keep a tab on anki discord just don’t talk much😂

**Comment by david-allison** [comment]
Feel free to ping the channel for help/a review, it's what we're here for!

**Comment by mikehardy** [comment]
Not sure why, but the backend is not being found?

```

        Caused by:
        java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: 'byte[][] net.ankiweb.rsdroid.NativeMethods.openBackend(byte[])' [in thread "ForkJoinPool-1-worker-1"]
            at net.ankiweb.rsdroid.NativeMethods.openBackend(Native Method)
            at net.ankiweb.rsdroid.Backend.<init>(Backend.kt:79)
            at net.ankiweb.rsdroid.BackendFactory.getBackend(BackendFactory.kt:39)
            at net.ankiweb.rsdroid.BackendFactory.getBackend$default(BackendFactory.kt:37)
            at com.ichi2.anki.CollectionManager.ensureBackendInner(CollectionManager.kt:183)
            at com.ichi2.anki.CollectionManager.access$ensureBackendInner(CollectionManager.kt:39)
            at com.ichi2.anki.CollectionManager$getBackend$1$1.invoke(CollectionManager.kt:132)
            at com.ichi2.anki.CollectionManager$getBackend$1$1.invoke(CollectionManager.kt:132)
            at com.ichi2.anki.CollectionManager$withQueue$2.invokeSuspend(CollectionManager.kt:86)
            at _COROUTINE._BOUNDARY._(CoroutineDebugging.kt:42)
            at com.ichi2.anki.CollectionManager$getBackend$1.invokeSuspend(CollectionManager.kt:132)
```

I looked at the commit history - it should be squashed - no reason for 5 commits - so I recommend learning how `git rebase` works and perhaps doing a `git rebase -i HEAD~5` then changing `pick` on commits 2 through 5 to `squash` and after getting your local branch cleaned up like that so it is a single commit doing a `git push --force-with-lease` to push your cleaned-up local branch back out to github for this PR - that will kick off CI again and perhaps the linker problem will be solved?

If it is not solved by that, then I would also do a `git add remote upstream git@github.com:ankidroid/Anki-Android`, then a `git fetch upstream`, then a `git rebase upstream/main` on your branch to pull in all upstream changes to make sure the backend dependency is correct and again `git push --force-with-lease` to push those changes back out to github so the PR is updated. That will run CI again and hopefully the problem will be solved?

**Comment by criticalAY** [comment]
@david-allison @Giyutomioka-SS It is blocked until I come up with the right code to handle the flag names, as the previous commit I made related to flag names was reverted

**Comment by BrayanDSO** [comment]
>  It is blocked until I come up with the right code to handle the flag names,

I don't see a reason for blocking this one. It doesn't matter which PR goes first, as long as is works and doesn't break CI

**Comment by criticalAY** [comment]
This PR uses a method which was reverted to fix the CI failure and that is the reason for the conflicts, but if you intend to replace strings only then go ahead, @Giyutomioka-SS remember to find and replace the strings at all places now

**Comment by Giyutomioka-SS** [comment]
@BrayanDSO @david-allison @criticalAY is this good now ??

**Comment by criticalAY** [comment]
Looks good to me

**Review by criticalAY — APPROVED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt [hunk 4]
```diff
@@ -819,6 +821,28 @@ open class CardBrowser :
         }
     }
 
+    private fun setFlagTitles(menu: Menu) {
+        menu.findItem(R.id.action_select_flag_zero).title = TR.browsingNoFlag()
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt:825]: Can these be moved to be properties of `Flag`: ``Flag.RED.displayName()`

**Review by david-allison — CHANGES_REQUESTED** [review]
Implementer's choice: One request to remove duplication, rest looks good

Thanks!

**Review by david-allison — CHANGES_REQUESTED** [review]
This is no longer using the backend


displayName should be a method

**Comment by criticalAY** [comment]
On my phone but there should be a better way than the current code to achieve the same result @Giyutomioka-SS instead of overriding it for all the strings

**Comment by Giyutomioka-SS** [comment]
> On my phone but there should be a better way than the current code to achieve the same result @Giyutomioka-SS instead of overriding it for all the strings

In that case, I guess backend need to provides the display name along with other flag information.

**Comment by Giyutomioka-SS** [comment]
> On my phone but there should be a better way than the current code to achieve the same result @Giyutomioka-SS instead of overriding it for all the strings

Unit tests are failing if I am using TR this way in Flag.kt should I revert this to the previous commit it works fine.

File: AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt [hunk 5]
```diff
@@ -17,19 +17,20 @@ package com.ichi2.anki
...
-    BLUE(4, R.drawable.ic_flag_blue, R.color.flag_blue),
-    PINK(5, R.drawable.ic_flag_pink, R.color.flag_pink),
-    TURQUOISE(6, R.drawable.ic_flag_turquoise, R.color.flag_turquoise),
-    PURPLE(7, R.drawable.ic_flag_purple, R.color.flag_purple);
+enum class Flag(val code: Int, @DrawableRes val drawableRes: Int, @ColorRes val browserColorRes: Int?, val displayName: String) {
+    NONE(0, R.drawable.ic_flag_transparent, null, TR.browsingNoFlag()),
+    RED(1, R.drawable.ic_flag_red, R.color.flag_red, TR.actionsFlagRed()),
+    ORANGE(2, R.drawable.ic_flag_orange, R.color.flag_orange, TR.actionsFlagOrange()),
+    GREEN(3, R.drawable.ic_flag_green, R.color.flag_green, TR.actionsFlagGreen()),
+    BLUE(4, R.drawable.ic_flag_blue, R.color.flag_blue, TR.actionsFlagGreen()),
```
Comment (criticalAY) [inline AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt:30]: Green flag for Blue?

File: AnkiDroid/src/main/res/menu/card_browser.xml [hunk 6]
```diff
@@ -40,34 +41,34 @@
         <menu>
             <item
                 android:id="@+id/action_select_flag_zero"
-                android:title="@string/menu_flag_card_zero"/>
+                tools:title="No Flag"/>
             <item
                 android:id="@+id/action_select_flag_one"
-                android:title="@string/menu_flag_card_one"
+                tools:title="Red Flag"
```
Comment (criticalAY) [inline AnkiDroid/src/main/res/menu/card_browser.xml:47]: Optional: Remove flag after the flag names so that it is consistent with Anki, though this is dev only

**Review by criticalAY — CHANGES_REQUESTED** [review]
Will approve after the blue flag name is corrected

**Review by david-allison — APPROVED** [review]
Cheers

**Review by david-allison — CHANGES_REQUESTED** [review]
Tests are failing

**Review by david-allison — CHANGES_REQUESTED** [review]
I believe:

<details>


```patch
Subject: [PATCH] feat: Toggle Bury

Issue 14163
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt b/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt	(revision 9fb827d72dcbb33cfc10761fbed02216a09f0181)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt	(date 1715982065094)
@@ -851,14 +851,14 @@
     }
 
     private fun setFlagTitles(menu: Menu) {
-        menu.findItem(R.id.action_flag_zero).title = Flag.NONE.displayName
-        menu.findItem(R.id.action_flag_one).title = Flag.RED.displayName
-        menu.findItem(R.id.action_flag_two).title = Flag.ORANGE.displayName
-        menu.findItem(R.id.action_flag_three).title = Flag.GREEN.displayName
-        menu.findItem(R.id.action_flag_four).title = Flag.BLUE.displayName
-        menu.findItem(R.id.action_flag_five).title = Flag.PINK.displayName
-        menu.findItem(R.id.action_flag_six).title = Flag.TURQUOISE.displayName
-        menu.findItem(R.id.action_flag_seven).title = Flag.PURPLE.displayName
+        menu.findItem(R.id.action_flag_zero).title = Flag.NONE.displayName()
+        menu.findItem(R.id.action_flag_one).title = Flag.RED.displayName()
+        menu.findItem(R.id.action_flag_two).title = Flag.ORANGE.displayName()
+        menu.findItem(R.id.action_flag_three).title = Flag.GREEN.displayName()
+        menu.findItem(R.id.action_flag_four).title = Flag.BLUE.displayName()
+        menu.findItem(R.id.action_flag_five).title = Flag.PINK.displayName()
+        menu.findItem(R.id.action_flag_six).title = Flag.TURQUOISE.displayName()
+        menu.findItem(R.id.action_flag_seven).title = Flag.PURPLE.displayName()
     }
 
     @SuppressLint("RestrictedApi")
Index: AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt b/AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt	(revision 9fb827d72dcbb33cfc10761fbed02216a09f0181)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerFragment.kt	(date 1715982065097)
@@ -206,14 +206,14 @@
     }
 
     private fun setFlagTitles(menu: Menu) {
-        menu.findItem(R.id.action_flag_zero).title = Flag.NONE.displayName
-        menu.findItem(R.id.action_flag_one).title = Flag.RED.displayName
-        menu.findItem(R.id.action_flag_two).title = Flag.ORANGE.displayName
-        menu.findItem(R.id.action_flag_three).title = Flag.GREEN.displayName
-        menu.findItem(R.id.action_flag_four).title = Flag.BLUE.displayName
-        menu.findItem(R.id.action_flag_five).title = Flag.PINK.displayName
-        menu.findItem(R.id.action_flag_six).title = Flag.TURQUOISE.displayName
-        menu.findItem(R.id.action_flag_seven).title = Flag.PURPLE.displayName
+        menu.findItem(R.id.action_flag_zero).title = Flag.NONE.displayName()
+        menu.findItem(R.id.action_flag_one).title = Flag.RED.displayName()
+        menu.findItem(R.id.action_flag_two).title = Flag.ORANGE.displayName()
+        menu.findItem(R.id.action_flag_three).title = Flag.GREEN.displayName()
+        menu.findItem(R.id.action_flag_four).title = Flag.BLUE.displayName()
+        menu.findItem(R.id.action_flag_five).title = Flag.PINK.displayName()
+        menu.findItem(R.id.action_flag_six).title = Flag.TURQUOISE.displayName()
+        menu.findItem(R.id.action_flag_seven).title = Flag.PURPLE.displayName()
     }
 
     private fun setBackSideOnlyButtonIcon(menu: Menu, isBackSideOnly: Boolean) {
Index: AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt b/AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt	(revision 9fb827d72dcbb33cfc10761fbed02216a09f0181)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/Flag.kt	(date 1715982602616)
@@ -18,19 +18,31 @@
 import androidx.annotation.ColorRes
 import androidx.annotation.DrawableRes
 import com.ichi2.anki.CollectionManager.TR
+import com.ichi2.anki.CollectionManager.withCol
 import com.ichi2.libanki.Card
 import com.ichi2.libanki.CardId
 import com.ichi2.libanki.Collection
 
-enum class Flag(val code: Int, @DrawableRes val drawableRes: Int, @ColorRes val browserColorRes: Int?, val displayName: String) {
-    NONE(0, R.drawable.ic_flag_transparent, null, TR.browsingNoFlag()),
-    RED(1, R.drawable.ic_flag_red, R.color.flag_red, TR.actionsFlagRed()),
-    ORANGE(2, R.drawable.ic_flag_orange, R.color.flag_orange, TR.actionsFlagOrange()),
-    GREEN(3, R.drawable.ic_flag_green, R.color.flag_green, TR.actionsFlagGreen()),
-    BLUE(4, R.drawable.ic_flag_blue, R.color.flag_blue, TR.actionsFlagBlue()),
-    PINK(5, R.drawable.ic_flag_pink, R.color.flag_pink, TR.actionsFlagPink()),
-    TURQUOISE(6, R.drawable.ic_flag_turquoise, R.color.flag_turquoise, TR.actionsFlagTurquoise()),
-    PURPLE(7, R.drawable.ic_flag_purple, R.color.flag_purple, TR.actionsFlagPurple());
+enum class Flag(val code: Int, @DrawableRes val drawableRes: Int, @ColorRes val browserColorRes: Int?) {
+    NONE(0, R.drawable.ic_flag_transparent, null),
+    RED(1, R.drawable.ic_flag_red, R.color.flag_red),
+    ORANGE(2, R.drawable.ic_flag_orange, R.color.flag_orange),
+    GREEN(3, R.drawable.ic_flag_green, R.color.flag_green),
+    BLUE(4, R.drawable.ic_flag_blue, R.color.flag_blue),
+    PINK(5, R.drawable.ic_flag_pink, R.color.flag_pink),
+    TURQUOISE(6, R.drawable.ic_flag_turquoise, R.color.flag_turquoise),
+    PURPLE(7, R.drawable.ic_flag_purple, R.color.flag_purple);
+
+    fun displayName() : String = when (this) {
+        NONE -> TR.browsingNoFlag()
+        RED -> TR.actionsFlagRed()
+        ORANGE -> TR.actionsFlagOrange()
+        GREEN -> TR.actionsFlagGreen()
+        BLUE -> TR.actionsFlagBlue()
+        PINK -> TR.actionsFlagPink()
+        TURQUOISE -> TR.actionsFlagTurquoise()
+        PURPLE -> TR.actionsFlagPurple()
+    }
 
     companion object {
         fun fromCode(code: Int): Flag {
Index: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt b/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt	(revision 9fb827d72dcbb33cfc10761fbed02216a09f0181)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt	(date 1715982065104)
@@ -822,25 +822,25 @@
     }
 
     private fun setFlagTitles(menu: Menu) {
-        menu.findItem(R.id.action_select_flag_zero).title = Flag.NONE.displayName
-        menu.findItem(R.id.action_select_flag_one).title = Flag.RED.displayName
-        menu.findItem(R.id.action_select_flag_two).title = Flag.ORANGE.displayName
-        menu.findItem(R.id.action_select_flag_three).title = Flag.GREEN.displayName
-        menu.findItem(R.id.action_select_flag_four).title = Flag.BLUE.displayName
-        menu.findItem(R.id.action_select_flag_five).title = Flag.PINK.displayName
-        menu.findItem(R.id.action_select_flag_six).title = Flag.TURQUOISE.displayName
-        menu.findItem(R.id.action_select_flag_seven).title = Flag.PURPLE.displayName
+        menu.findItem(R.id.action_select_flag_zero).title = Flag.NONE.displayName()
+        menu.findItem(R.id.action_select_flag_one).title = Flag.RED.displayName()
+        menu.findItem(R.id.action_select_flag_two).title = Flag.ORANGE.displayName()
+        menu.findItem(R.id.action_select_flag_three).title = Flag.GREEN.displayName()
+        menu.findItem(R.id.action_select_flag_four).title = Flag.BLUE.displayName()
+        menu.findItem(R.id.action_select_flag_five).title = Flag.PINK.displayName()
+        menu.findItem(R.id.action_select_flag_six).title = Flag.TURQUOISE.displayName()
+        menu.findItem(R.id.action_select_flag_seven).title = Flag.PURPLE.displayName()
     }
 
     private fun setMultiSelectFlagTitles(menu: Menu) {
-        menu.findItem(R.id.action_flag_zero).title = Flag.NONE.displayName
-        menu.findItem(R.id.action_flag_one).title = Flag.RED.displayName
-        menu.findItem(R.id.action_flag_two).title = Flag.ORANGE.displayName
-        menu.findItem(R.id.action_flag_three).title = Flag.GREEN.displayName
-        menu.findItem(R.id.action_flag_four).title = Flag.BLUE.displayName
-        menu.findItem(R.id.action_flag_five).title = Flag.PINK.displayName
-        menu.findItem(R.id.action_flag_six).title = Flag.TURQUOISE.displayName
-        menu.findItem(R.id.action_flag_seven).title = Flag.PURPLE.displayName
+        menu.findItem(R.id.action_flag_zero).title = Flag.NONE.displayName()
+        menu.findItem(R.id.action_flag_one).title = Flag.RED.displayName()
+        menu.findItem(R.id.action_flag_two).title = Flag.ORANGE.displayName()
+        menu.findItem(R.id.action_flag_three).title = Flag.GREEN.displayName()
+        menu.findItem(R.id.action_flag_four).title = Flag.BLUE.displayName()
+        menu.findItem(R.id.action_flag_five).title = Flag.PINK.displayName()
+        menu.findItem(R.id.action_flag_six).title = Flag.TURQUOISE.displayName()
+        menu.findItem(R.id.action_flag_seven).title = Flag.PURPLE.displayName()
     }
 
     private fun updatePreviewMenuItem() {

```

</details>

**Comment by criticalAY** [comment]
CI is happy now

**Review by criticalAY — APPROVED** [review]

**Review by david-allison — APPROVED** [review]
Cheers!

**Review by lukstbit — APPROVED** [review]
Thanks!

**Comment by lukstbit** [comment]
Going in after #16427(with which I'm almost done)
