### PR TITLE
Preview fix

### LINKED ISSUE #5220: Browser preview: navigation buttons missing
###### Reproduction Steps

1. Open card browser
2. Long tap on a card > preview 

###### Expected Result

Navigation buttons are showing

###### Actual Result

No navigation buttons. I can't navigate through the cards. It worked in alpha <58 but since 2.9alpha58 it's broken

###### Debug info

AnkiDroid Version = 2.9alpha60

Android Version = 8.1.0

ACRA UUID = f2d13677-d957-460e-9f8e-33ca6f832c17

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

### PR DESCRIPTION
**Pull request by timrae**
## Purpose / Description
Currently it's not possible to preview all cards starting from a given index in the browser. This is pretty unintuitive.

## Fixes
Fixes #5220 

## Approach
In the case where we have selected only one card we show all cards starting at the selected index. In the case where we have selected multiple cards, we show only those cards (this isn't supported by desktop which instead shows "please select 1 card" when multiple cards are selected).

I also switched from HashSet to LinkedHashSet for the selected card indices so that we correctly maintain insertion order, so that when multiple cards are selected for preview they show up in the correct order.

## How Has This Been Tested?

I ran through it with the emulator to check that it's all good

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java [hunk 1]
```diff
@@ -163,7 +164,7 @@
     private TextView mActionBarTitle;
     private boolean mReloadRequired = false;
     private boolean mInMultiSelectMode = false;
-    private HashSet<Integer> mCheckedCardPositions = new HashSet<>();
+    private Set<Integer> mCheckedCardPositions = new LinkedHashSet<>();
     private int mLastSelectedPosition;
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java]: Nice catch on this one
