### PR TITLE
Search text is in normal instead hint text

### LINKED ISSUE #14175: [BUG]: Search text is in hint text instead of normal text while filtering by tags
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Go to CardBrowser
2. Click on filter by tag

### Expected behaviour

The search text must be normal text
Screenshot_2023-07-30-13-02-16-88_7b5228b5a93c00ecba98ecb0735c59e2

### Actual behaviour

Search text is in hint text
Screenshot_2023-07-30-13-01-05-12_7b5228b5a93c00ecba98ecb0735c59e2

### Debug info

```text
AnkiDroid Version = 2.16.2-debug

Android Version = 13

ProductFlavor = amazon

Manufacturer = Google

Model = sdk_gphone_x86_64

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 13; sdk_gphone_x86_64 Build/TE1A.220922.031; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.71 Mobile Safari/537.36

ACRA UUID = 7401ef4f-968e-4a64-8d8b-d9b12c0774ff

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

To reproduce expected behavior: filter by flag

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by SanjaySargam**
## Purpose / Description
Search text is in hint text instead of normal text while filtering by tags

## Fixes
Fixes #14175 

## Approach
use searchWithFilterQuery function in filterByTags function

## How Has This Been Tested?
Tested on Emulator ( Pixel 5 API 33 )

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt [hunk 1]
```diff
@@ -1821,6 +1816,7 @@ open class CardBrowser :
             sb.append("($tagsConcat)") // Only if we added anything to the tag list
         }
         mSearchTerms = sb.toString()
+        searchWithFilterQuery(mSearchTerms)
         searchCards()
```
Comment (lukstbit) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt:1820]: There's no need for the searchCards() call at the end as searchWithFilterQuery() already calls searchCards().

**Review by lukstbit — CHANGES_REQUESTED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt (hunk 1 above)
Comment (SanjaySargam) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt:1820]: Ok I will remove it

**Review by lukstbit — APPROVED** [review]

**Review by mikehardy — APPROVED** [review]
Thanks!
