### PR TITLE
In-Memory Multimedia Editor

### LINKED ISSUE #5992: Advanced Editor uses original field values rather than current values
This is more problematic with the Visual Editor, but I want to get confirmation that I can get a fix in, and it won't interfere with plans for fixing #5011. 

If so, it's planned for tomorrow.

###### Reproduction Steps

1. Open Note Editor For Existing Note with text in "Front" field.
2. Type in Text in "Front"
3. Open Advanced Editor

###### Expected Result

4. You see the changed text in the advanced editor

###### Actual Result

4. You see the original text in the advanced editor

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum.

###### Relevant Code

https://github.com/ankidroid/Anki-Android/blob/1a1a041e9d18326233c24f3a1017cf58b7c42bac/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java#L1147-L1152

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description

Previously, we were using the field values from the existing model in the database when editing fields.

Now, we use the values shown in the UI.

Automated lint fixes were also executed.

## Fixes
Fixes #5992

## Approach
Pass the field values and the model ID into NoteService, rather than using the model from the card.

## How Has This Been Tested?
Unit Tests
Tested on my device, works as expected.

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5348356&bid=17512634)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5348356&bid=17512634)

File: AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.java [hunk 1]
```diff
@@ -18,7 +19,7 @@
 
 public class FieldEditText extends AppCompatEditText {
 
-    public static final String NEW_LINE = System.getProperty("line.separator");
+    public static final String NEW_LINE = CompatHelper.getCompat().getLineSeparator();
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.java:22]: This is not the proper use of the Compat infrastructure
If you can't put a comment on top of every single API that you add to Compat that explains the difference in behavior across Android versions, and in which exact version you can remove the Compat API with old workaround-implementation and inline the "modern" implementation, then it does not belong in Compat

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java [hunk 2]
```diff
@@ -96,15 +96,21 @@ protected void onCreate(Bundle savedInstanceState) {
...
 
-        mFieldIndex = this.getIntent().getIntExtra(EXTRA_FIELD_INDEX, 0);
+        mFieldIndex = intent.getIntExtra(EXTRA_FIELD_INDEX, 0);
 
         recreateEditingUi(ChangeUIRequest.init(mField));
     }
 
+    @VisibleForTesting
+    public static IField getFieldFromIntent(Intent intent) {
+        return (IField) intent.getExtras().getSerializable(EXTRA_FIELD);
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java:111]: https://developer.android.com/reference/android/content/Intent#getExtras()
"the map of all extras previously added with putExtra(), **or null** if none have been added."
...you never know

File: AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java [hunk 3]
```diff
@@ -91,4 +95,23 @@ protected JSONObject getCurrentDatabaseModelCopy(String modelName) throws JSONEx
...
     }
+
+    protected <T extends AnkiActivity> T startActivityNormallyOpenCollectionWithIntent(Class<T> clazz, Intent i) {
+        ActivityController multimediaController = Robolectric.buildActivity(clazz, i)
+                .create().start().resume().visible();
+        //noinspection unchecked
+        return (T) multimediaController.get();
+    }
+
+    protected Note addBasicNote(String front, String back) {
```
Comment (mikehardy) [inline AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java:106]:
```suggestion
    protected Note getNoteUsingBasicModel(String front, String back) {
```
...or similar, just a bit more unambiguous that the note itself isn't basic (maybe means a simple note?) but that it is attached to the basic model

File: AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java [hunk 4]
```diff
@@ -91,4 +95,23 @@ protected JSONObject getCurrentDatabaseModelCopy(String modelName) throws JSONEx
         Models collectionModels = getCol().getModels();
         return new JSONObject(collectionModels.byName(modelName).toString().trim());
     }
+
+    protected <T extends AnkiActivity> T startActivityNormallyOpenCollectionWithIntent(Class<T> clazz, Intent i) {
+        ActivityController multimediaController = Robolectric.buildActivity(clazz, i)
+                .create().start().resume().visible();
+        //noinspection unchecked
+        return (T) multimediaController.get();
+    }
```
Comment (mikehardy) [inline AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java:104]: On first read I thought this was bound to the multimedia work but it looks like you've made a fully general purpose activity starter?

```suggestion
    protected <T extends AnkiActivity> T startActivityNormallyOpenCollectionWithIntent(Class<T> clazz, Intent i) {
        ActivityController controller = Robolectric.buildActivity(clazz, i)
                .create().start().resume().visible();
        //noinspection unchecked
        return (T) controller.get();
    }
```

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java (hunk 2 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivity.java:111]: I'm just using this as an accessor to ensure consistency between the reading of the activity data in the test. There's no code change here.

File: AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.java (hunk 1 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.java:22]: I'll rebase and kill this change.

**Comment by david-allison-1** [comment]
> A couple nits but the Compat thing is a real change - I'd just nuke that whole thing, doesn't seem to fit the Compat purpose

Agreed on all counts. Will rebase rather than replying to comments. `getFieldFromIntent` has no functional change, so I'll leave it as is (with lint warning).

**Comment by mikehardy** [comment]
> > A couple nits but the Compat thing is a real change - I'd just nuke that whole thing, doesn't seem to fit the Compat purpose
> 
> Agreed on all counts. Will rebase rather than replying to comments. `getFieldFromIntent` has no functional change, so I'll leave it as is (with lint warning).

Cool - that makes the commit history on master much nicer and makes me lean much more towards rebase merge vs squash merge, and with a lint-specific change that's preferred - thanks

File: AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.java (hunk 1 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.java:22]: I have to admit since deprecation / forward-porting was the first thing I started working on in earnest in the project I feel like Compat is my baby but the structure itself already completely existed, and after learning how it worked I like it. Not sure if there is a better way to handle API differences without just bumping minSdkVersion but this one is certainly powerful and not too hard to drive as a developer. If you ever dig into the stack of deprecation issues you'll become intimately familiar, anyway :-)

**Comment by david-allison-1** [comment]
I'll try and avoid lint changes in future. I don't know what I was expecting, but I don't think this review went too well.

----

Just for grep purposes, I had a flaky test. Restarting Android Studio solved it.

Running tests again now, then will commit.

```
java.lang.RuntimeException: Stub!

	at android.content.Context.getString(Context.java:197)
	at com.ichi2.anki.AnalyticsTest.setUp(AnalyticsTest.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.internal.runners.MethodRoadie.runBefores(MethodRoadie.java:133)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:96)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:310)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:131)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.access$100(PowerMockJUnit47RunnerDelegateImpl.java:59)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner$TestExecutorStatement.evaluate(PowerMockJUnit47RunnerDelegateImpl.java:147)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.evaluateStatement(PowerMockJUnit47RunnerDelegateImpl.java:107)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:82)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:298)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:87)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:50)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:218)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:160)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:134)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:136)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:117)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:57)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by mikehardy** [comment]
I actually like de-linting? :rofl: 

I also thought the review went fine though my tone was perhaps robotic (got a lot going on today). And now you know about Compat :-)

On balance this was a pretty intricate change and at the core of it I had two naming suggestions and one easy to fix "don't do that", and it's about to merge, not bad ?

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5348356&bid=17512634)

**Comment by david-allison-1** [comment]
I don't think it was /bad/, but I definitely crossed the line of "only do relevant refactorings in a PR". 

Maybe see if we can get "no lint errors" as a stretch goal for 2.12 😸

Anyway, all pushed

**Comment by mikehardy** [comment]
Released as 2.10alpha69 as soon as google finishes processing it
