### PR TITLE
fix: borders on fullscreen Reviewer

### LINKED ISSUE #9267: fullscreen mode with hide the system bars (after v2.15.5)
hi, there.
after updated to v2.15.5, fullscreen mode with hide the system bars, there are spaces at the top and the bottom, not fully hide the system bars, and v2.15.4 works perfectly before.
many thanks.
Screenshot_01
Screenshot_02
Screenshot_03

### PR DESCRIPTION
**Pull request by david-allison-1**
When going fullscreen, the reviewer had white/blue borders rather than
filling the content

Cause:

d0d1edd moved to a single xml file for
the navigation drawer, rather than copy/pasting it into each file

Some layouts excluded `android:fitsSystemWindows="true"`, but the new
xml file always included this.

This caused the layout problems

## Fixes
Fixes #9267

## Approach
* add method: `fitsSystemWindows` and layout without the variable

## How Has This Been Tested?

My Android 11

## Learning (optional, can help others)
* I wasted a lot of time learning about `PhoneWindow` on Android Code Search

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java [hunk 1]
```diff
@@ -106,6 +107,15 @@ public void setContentView(int layoutResID) {
         setContentView(closableDrawerLayout);
     }
 
+    private @LayoutRes int getNavigationDrawerLayout() {
+        return fitsSystemWindows() ? R.layout.navigation_drawer_layout : R.layout.navigation_drawer_layout_fullscreen;
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java:111]: Question: This can likely be simplified by modifying the view after it's been inflated, but there are issues regarding padding being added via the flag. 

https://stackoverflow.com/questions/30439661/androidfitssystemwindows-at-runtime

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java [hunk 2]
```diff
@@ -267,6 +267,17 @@ protected int getContentViewAttr(int fullscreenMode) {
         }
     }
 
+    @Override
+    protected boolean fitsSystemWindows() {
+        switch (getPrefFullscreenReview()) {
+            case 1:
+            case 2:
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java:274]: Nice to have: what exactly are these magic numbers? Could they be a type somehow?

There's no indication here what the universe of values is and what each are, it's just a raw parse then an int
https://github.com/ankidroid/Anki-Android/blob/c4064f43038db172f7abede4989ccfaead2921fb/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L1924

File: AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java (hunk 1 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java:111]: At this point I think it's already tested and working, and the stackoverflow answer where you clear padding etc seems fiddly. This implementation already seems simple enough to me

**Review by mikehardy — APPROVED** [review]
One wish for a strongly typed set of layout ints, but really that's a wish as it's clearly not a regression, just that you might know them off-hand at this point and know how to make the intdef or enum really quickly at this point.

If not, just hit the merge button - works for me

**Comment by david-allison-1** [comment]
Fair comment - I was considering it anyway, held off as the only other usage was directly above

**Comment by david-allison-1** [comment]
More work than I thought, but it caught a bug (not in this code), so all worth it

**Comment by mikehardy** [comment]
Will this fix #9279  as well? it might...

**Comment by david-allison-1** [comment]
No it doesn't, there's something else going on there.

Force pushed & updated code

File: AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java [hunk 3]
```diff
@@ -326,7 +326,7 @@ private void initSubscreen(String action, PreferenceContext listener) {
                         screen.findPreference(FULL_SCREEN_MODE);
                 fullscreenPreference.setOnPreferenceChangeListener((preference, newValue) -> {
                     SharedPreferences prefs = AnkiDroidApp.getSharedPrefs(Preferences.this);
-                    if (prefs.getBoolean("gestures", false) || !FULL_SCREEN_MODE.equals(newValue)) {
+                    if (prefs.getBoolean("gestures", false) || !FULLSCREEN_ALL_GONE.equals(newValue)) {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java]: This needs a regression test - adding a "good first issue"

**Comment by mikehardy** [comment]
unit test fail is legit - looks like a symbol mixup during re-shape-basing

**Review by mikehardy — APPROVED** [review]
Wow, our full screen mode proliferation is kind of crazy.
This is now a real advance in the state of things I think, the reshape is a significant positive step to me
...and you got a bug :-)
