### PR TITLE
Fix DeckPicker freezing after theme changes

### LINKED ISSUE #19512: [BUG] DeckPicker: hand after changing theme
@david-allison Have you seen this behavior:

[Screen_recording_20251117_205246.webm](https://github.com/user-attachments/assets/2dfc17a3-a91b-4439-bba3-d91df68daf01)

Basically after changing the theme and coming back to DeckPicker I see the loading dialog. At this point everything is blocked and I have to force close the app(loading doesn't finish and I'm not syncing as I'm not logged in). I looked a bit and it's your commit for this PR where I start seeing it.

_Originally posted by @lukstbit in https://github.com/ankidroid/Anki-Android/issues/19461#issuecomment-3543424233_

### PR DESCRIPTION
**Pull request by 7se7en72025**
https://github.com/user-attachments/assets/5843d5bf-3df8-4a2e-9822-36b1080f3771

## Purpose / Description
Fixes a critical issue where DeckPicker would freeze/hang after changing themes. The app becomes unresponsive and requires force-close when users switch between light/dark themes.

## Fixes
* Fixes #19512

## Approach
The issue occurred due to two main problems:

1. **MutableSharedFlow deadlock**: DeckPickerViewModel uses `MutableSharedFlow` instances without buffers. When the activity is recreated during theme changes, collectors are temporarily inactive, causing `emit()` calls to suspend indefinitely.

- Added `extraBufferCapacity = 1` to all `MutableSharedFlow` instances in DeckPickerViewModel

## How Has This Been Tested?
- Tested theme changes manually on Android emulator (API 30) - verified app no longer freezes after switching between light/dark/black themes
- Verified all existing functionality remains intact (deck loading, navigation, sync operations)

## Learning (optional, can help others)
- `MutableSharedFlow` without buffers requires active collectors; otherwise `emit()` suspends
- `lifecycle.repeatOnLifecycle(Lifecycle.State.RESUMED)` only collects when activity is RESUMED

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 1]
```diff
@@ -1445,6 +1446,14 @@ open class DeckPicker :
 
     override fun onResume() {
         activityPaused = false
+        // Reset progress dialog flag in case it was left in an inconsistent state
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt]: I don't believe this needs to exist - I haven't seen this occur with my testing

File: AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt [hunk 2]
```diff
@@ -766,4 +767,34 @@ class DeckPickerTest : RobolectricTest() {
             return super.onPrepareOptionsMenu(menu)
         }
     }
+
+    @Test
+    fun `test progressDialogShown flag is reset in onResume`() =
```
Comment (david-allison) [inline AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt]: Remove this, it doesn't replicate a bug

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 3]
```diff
@@ -40,6 +40,7 @@ import android.view.Menu
 import android.view.MenuItem
 import android.view.View
 import android.view.ViewGroup
+import android.view.WindowManager
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt]: needs revert

File: AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt [hunk 4]
```diff
@@ -64,6 +64,7 @@ import org.robolectric.shadows.ShadowDialog
 import org.robolectric.shadows.ShadowLooper
 import timber.log.Timber
 import kotlin.test.assertFailsWith
+import kotlin.test.assertFalse
```
Comment (david-allison) [inline AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.kt]: needs revert

**Review by david-allison — APPROVED** [review]
Looks good to me, thanks!

This needs a https://github.com/ankidroid/Anki-Android/labels/squash-merge, lint CI fixup, and a couple of non-blocking nitpicks would be great to take care of.

I'm happy to take these on if another maintainer approves, leaving it on https://github.com/ankidroid/Anki-Android/labels/Pending%20Merge. I want to see this in so we can safely go to beta

The underlying change looks good to me. I went for a similar solution, in addition to an `eventFlow()` method for the `MutableSharedFlow<Unit>` pattern which we commonly use

**Comment by david-allison** [comment]
It'd be really helpful if you could stop recreating pull requests. This one was ready to go.

Instead, you can squash commits, then force push to the branch which you based the PR off

**Comment by 7se7en72025** [comment]
Got it, sorry about that. I’ll avoid creating new PRs going forward.
I’ll squash the commits and force push to the same branch from now on. Thanks for the clarification

**Comment by david-allison** [comment]
Cleaned and force pushed. Using original commit message.

Re-tested briefly with a theme change (light -> dark) and finishing a deck
