### PR TITLE
fix: TagsDialog crashes

### LINKED ISSUE #16226: [BUG]: crash on clicking "Edit tags"
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Card Browser
2. Select all
3. Edit tags from menu

### Expected behaviour

some pop up opens up

### Actual behaviour

app crashes

### Debug info

```text
AnkiDroid Version = 2.18alpha9 (7da94c1238199a166310b7db63d53d5dbb40f054)

Backend Version = 0.1.36-anki24.04 (24.04 429bc9e14cefb597646a0e1beac6ef140f226b6f)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = realme

Model = RMX2193

Hardware = mt6768

Webview User Agent = Mozilla/5.0 (Linux; Android 11; RMX2193 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/123.0.6312.99 Mobile Safari/537.36

ACRA UUID = cf265e01-9693-407f-984d-61ddf9698fac

FSRS Enabled = true

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### LINKED ISSUE #16351: Crash on switching app while edit tags dialog is open
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

- In the Browser, select a card and choose Edit tags from the menu.
- Switch to another app

### Expected behaviour

No crash

### Actual behaviour

The "AnkiDroid has encountered a problem. A report is being sent ..." message appears. On switching back to AnkiDroid, the main screen of the app is displayed, not the edit notes dialog.

### Debug info

```text
AnkiDroid Version = 2.18beta2 (dc5348852b15e0f27521acd3c5457595f4676f54)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 13 (SDK 33)

ProductFlavor = full

Manufacturer = motorola

Model = moto g62 5G

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; moto g62 5G Build/T1SSIS33.1-75-7-5; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.123 Mobile Safari/537.36

ACRA UUID = 70fd8e4a-1bcf-4f20-8bac-43ba9946410f

FSRS Enabled = true

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description

* Fix a `TransactionTooLargeException` and an `OutOfMemoryError`

This is a tradeoff of stability vs performance. We **should** do much better here in a follow-up 

## Fixes
* Fixes #16226
* Fixes #16351

## Approach
* Serialize to a file, rather than use Args
* Use `asSequence` to fix an OOM
  * This makes the dialog process 2x slower: we need to iterate the selected notes twice 
  * This may actually be faster after the PR on some collection, as we perform `select distinct nid` BEFORE loading the notes
* Add a progress dialog to help the user 

## How Has This Been Tested?
My S21, AnKing deck (31479 cards)

No longer crashes on AnKing
⚠️ It is still FAR too slow, needing to individually load 31k cards. This requires a follow-up issue

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison** [comment]
Proposal: if a reviewer requests, I'll add a final commit to wrap this in a Progress dialog

**Comment by david-allison** [comment]
For future

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt b/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt	(revision 3c3f39d7de6756959acdd2b1fdc9c89473a257ff)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt	(date 1714909257092)
@@ -1295,25 +1295,33 @@
                 // TODO!! This is terribly slow on AnKing
                 // PERF: This MUST be combined with the above sequence - this becomes O(2n) on a
                 // database operation performed over 30k times
+                val potentialTags = allTags.toMutableSet()
                 val uncheckedTags = withCol {
                     selectedNoteIds
                         .asSequence() // reduce memory pressure
                         .flatMap { nid: NoteId ->
                             progress++
-                            val note = getNote(nid) // requires withCol
-                            val noteTags: List<String?> = note.tags
-                            allTags.filter { t: String? -> !noteTags.contains(t) }
+
+                            // avoid DB access if no more tags to check
+                            if (potentialTags.isEmpty()) return@flatMap emptyList<String>()
+
+                            val noteTags = getNote(nid).tags.toSet() // requires withCol
+                            val uncheckedTagsForNote = potentialTags - noteTags
+                            // PERF: if we're returning these tags, we don't need to check them again
+                            potentialTags -= uncheckedTagsForNote
+                            uncheckedTagsForNote
                         }
                         .distinct()
                         .toList()
                 }
 
+                Timber.v("calculated uncheckedTags")
                 progressMax = null
 
                 Timber.d("showEditTagsDialog: edit tags for multiple note")
                 tagsDialogListenerAction = TagsDialogListenerAction.EDIT_TAGS
 
-                // withArguments performs IO, can be 18 seconds
+                // withArguments performs IO
                 val dialog = withContext(Dispatchers.IO) {
                     tagsDialogFactory.newTagsDialog().withArguments(
                         type = TagsDialog.DialogType.EDIT_TAGS,
@@ -1322,6 +1330,8 @@
                         allTags = allTags
                     )
                 }
+
+                Timber.v("showing dialog fragment")
                 showDialogFragment(dialog)
             }
         }
```

**Comment by david-allison** [comment]
I've added a progress dialog as well

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt [hunk 1]
```diff
@@ -370,3 +388,36 @@ class TagsDialog : AnalyticsDialogFragment {
...
+ * Temporary file containing the arguments [TagsDialog] uses
+ *
+ * to avoid [android.os.TransactionTooLargeException]
+ *
+ * @param directory parent directory of the file. Generally it should be the cache directory
+ * @param data data for the dialog to display. Typically [Context.getCacheDir]
+ */
+@WorkerThread
+class TagsFile(directory: File, data: TagsData) :
+    File(createTempFile("tagsDialog", ".tmp", directory).absolutePath) {
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt:402]: I think that this will also result in #15878

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt [hunk 2]
```diff
@@ -370,3 +388,36 @@ class TagsDialog : AnalyticsDialogFragment {
...
+            // https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/formats.md
+            outputStream.writeBytes(Json.encodeToString(data))
+        }
+    }
+
+    fun getData() = DataInputStream(FileInputStream(this)).use { inputStream ->
+        Json.decodeFromString<TagsData>(inputStream.convertToString())
+    }
+
+    @Serializable
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt:419]: Is `@Serializable` necessary here? I don't see a TagsData instance being serialized anywhere.

**Review by BrayanDSO — COMMENTED** [review]
Performance-wise, it definitely can be improved and should be improved, but I agree with you that fixing and testing it should be the priority

**Comment by mikehardy** [comment]
@david-allison this one looks like it needs a look from you?

**Comment by david-allison** [comment]
@mikehardy defer to 2.18.1 I feel

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt [hunk 3]
```diff
@@ -93,7 +108,8 @@ class TagsDialog : AnalyticsDialogFragment {
      * @param allTags all possible tags in the collection
      * @return Initialized instance of [TagsDialog]
      */
-    fun withArguments(type: DialogType, checkedTags: List<String?>, allTags: List<String?>): TagsDialog {
+    context(Context)
+    fun withArguments(type: DialogType, checkedTags: List<String>, allTags: List<String>): TagsDialog {
         return withArguments(type, checkedTags, null, allTags)
     }
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt:114]: So, this is just an overload of the `withArguments` below? Can't you add `null` as the default value of `uncheckedTags` in the method below?

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt [hunk 4]
```diff
@@ -106,31 +122,38 @@ class TagsDialog : AnalyticsDialogFragment {
...
+        )
         return this
     }
 
     override fun onCreate(savedInstanceState: Bundle?) {
         super.onCreate(savedInstanceState)
         resizeWhenSoftInputShown(requireActivity().window)
-        type = DialogType.entries[requireArguments().getInt(DIALOG_TYPE_KEY)]
+        val tagsFile = requireNotNull(
+            requireArguments().getSerializableCompat(
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt:144]: Now that this is a parcelable, `BundleCompat.getParcelable(requireArguments(), ARG_TAGS_FILE, TagsFile::class.java` can be used

not related to your PR, but now that I noted `PreviewerFragment` should use that as well instead of getSerializableCompat

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt (hunk 3 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt:114]: It's not the final argument, and that makes it easy to get the order of arguments confused

Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt:114]: Can they be reordered?

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt:114]: We can. Is it feasible we move this to a follow-up issue? This was intended to be a surgical fix, and there's a number of changes here which focus on correctness over style/speed

I suspect we can get a massive speed boost by not serializing `col.tags.all()`

Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt:114]: > Is it feasible we move this to a follow-up issue?

We should, yes. Just wanted to raise it up before I forgot about it

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt (hunk 2 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt:442]: I couldn't get this working, happy for someone to take on a follow-up

**Review by BrayanDSO — APPROVED** [review]
