### PR TITLE
fix(new-study-screen): Set Due Date snackbar

### LINKED ISSUE #19915: "Set due date" confirmation obscures bottom response bar
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

After a new due date is set, a bar appears for a moment at the bottom of the app confirming that "due date was set for 1 card". This bar obscures the "show answer" button for the next card, which breaks the review flow. 

### Expected behaviour

It should be a little higher and it would all be good. 

### Debug info

```text
AnkiDroid Version = 2.23.1 (3f3133b496b531383e9a6494f5a7704634935308)  
Backend Version = 0.1.62-anki25.09.2 (25.09.2 3890e12c9e48c028c3f12aa58cb64bd9f8895e30)  
Android Version = 16 (SDK 36)  
ProductFlavor = play  
Device Info = Google | google | panther | panther | Pixel 7 | panther  
Webview User Agent = Mozilla/5.0 (Linux; Android 16; Pixel 7 Build/BP4A.251205.006; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/143.0.7499.34 Mobile Safari/537.36  
ACRA UUID = e515004f-40f1-42a0-8536-8d5a6efe7fd9  
FSRS = 5.1.0 (Enabled: false)  
Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

I think this program appeared in a recent AnkiDroid version.

Curiously, other similar messages like "set due date undone" appear above the "show answer" bar, as they should.

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
Set Due Date snackbar was in the wrong place

## Fixes
* Fixes #19915

## Approach
* Handle `showSnackbar` on `SingleFragmentActivity`

## How Has This Been Tested?
Pixel 9 Pro - snackbar is in the correct location

## Learning (optional, can help others)
Lots of timing issues with the IME, showing the snackbar too early put it in the middle of the screen

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/SingleFragmentActivity.kt [hunk 1]
```diff
@@ -43,7 +45,13 @@ import kotlin.reflect.jvm.jvmName
  *
  * [getIntent] can be used as an easy way to build a [SingleFragmentActivity]
  */
-open class SingleFragmentActivity : AnkiActivity(R.layout.single_fragment_activity) {
+open class SingleFragmentActivity :
+    AnkiActivity(R.layout.single_fragment_activity),
+    BaseSnackbarBuilderProvider {
+    // delegate to the fragment in all cases
+    override val baseSnackbarBuilder: SnackbarBuilder
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/SingleFragmentActivity.kt:52]: This works, but there may be something better we can do architecturally

The problem is that we call `requireActivity().showSnackbar`, so we can't use a `SingleFragmentActivity` extension method

This will call the builder twice in some circumstances, which feels acceptable, but we can potentially find a better solution

**Review by mikehardy — APPROVED** [review]
I'm okay with it (and I think the insets listener for IME hidden state is a neat trick) but leaving for second review in case someone has a better idea

**Comment by mikehardy** [comment]
still open for better ideas (and follow-ons...) as ever, but going to merge this as I'm doing picks now
