### PR TITLE
Strip Image text from expected typed answer

### LINKED ISSUE #6096: "Type In Answer" displays image src as expected input
###### Reproduction Steps

1. Card template with front and back. `{{type:Back}}`
2. Back contains `ya[sound:36_ya.mp3]<div><br /></div>`

###### Expected Result

3. When card is flipped, expected value is `ya` (Anki 2.0.52/2.1.24)

###### Actual Result

3. When card is flipped, expected value is 

```
ya
paste-efbfdfbff329f818e3b5568e578234d0d0054067.png
```

###### Research
[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
[x] I have searched for similar existing issues here and on the user forum

### PR DESCRIPTION
**Pull request by david-allison**
## Anki Desktop code

https://github.com/ankitects/anki/blob/351d8a309f7d3c0cae7f818313b1a0e7aac4408a/qt/aqt/reviewer.py#L403-L435

## Purpose / Description
User reported that the image src was expected to be typed when making a "type:" card. This is different from Anki Desktop

## Fixes
Fixes #6096

## Approach
Use the same function as Anki Desktop

## How Has This Been Tested?

Unit tested, and tested on my device, no longer expects the image.

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TypedAnswer.java [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+
+package com.ichi2.anki.cardviewer;
+
+import com.ichi2.libanki.Sound;
+import com.ichi2.libanki.Utils;
+
+import java.util.regex.Matcher;
+import java.util.regex.Pattern;
+
+public class TypedAnswer {
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TypedAnswer.java:25]: Codacy Issue found: [The utility class name 'TypedAnswer' doesn't match '[A-Z][a-zA-Z0-9]+(Utils?|Helper|Constants)'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5460279)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/reviewer/TypedAnswerTest.java  1
- AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TypedAnswer.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5460279&bid=17896037)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/TypedAnswerTest.java  1
- AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TypedAnswer.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5460279&bid=17896037)

File: AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TypedAnswer.java (hunk 1 above)
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TypedAnswer.java:25]: Codacy Issue found: [The utility class name 'TypedAnswer' doesn't match '[A-Z][a-zA-Z0-9]+(Utils?|Helper|Constants)'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5460279)

**Review by mikehardy — APPROVED** [review]
Ha - 99% NF refactor (an improvement, that) and 1% "just use the right method"
Nice
