### PR TITLE
Limit same stack to 1 per device, Fixes #4949

### LINKED ISSUE #4949: Throttle crash reports from same trace
I understand there is some bespoke logic in AnkiDroidApp to do this already

ACRA (since 5.0.0) includes a limiter with the same features we want, and it would make the crash database much more useful - right now the database is quickly spammed with identical reports and it's difficult to sift through

Documentation here:
https://www.acra.ch/javadoc/latest/org/acra/annotation/AcraLimiter.html

I propose this config (this is all items, with default and proposed value):

- exceptionClassLimitlimit for reports with the same exception class
  - default 10, proposed value 1000 (intention is to not impose a limit, stack traces will catch most of the duplication but we use the same exception class all over, so...)
- failedReportLimitlimit for unsent reports
  - 5 (leave as default so we don't clutter up filesystems)
- overallLimitgeneral limit of reports
  - 25 (leave as default, unlikely more than 25 reports from a device is useful)
- periodReports which have been collected before this will not be considered for any limits except failedReportLimit()
  - 7L (leave as default, after a week we can roll reports off?)
- periodUnitUnit of period()
  - DAY (leave as default)
- resIgnoredCrashToasttoast shown when a report was not collected or sent because a limit was exceeded
  - 0 (do not display a toast if we are limiting a report)
- stacktraceLimit
  - 3 default, proposed 1 (I only want to see the same exception once, personally)

I would port this to the 2.8 series (I think it would be pretty easy since I did the ACRA changes) so we could maybe fix crash bugs for older APIs, as it is now I can't pick much out of acralyzer

### PR DESCRIPTION
**Pull request by mikehardy**
## Pull Request template

Please, go through these checks before you submit a PR.

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

## Purpose / Description
Limits crash reports of the same stack trace to 1 per device per 7 day period. Should de-clutter things a lot and make the database more useful

## Fixes
#4949 

## Approach
I just declared the limiter dependency and annotated with parameters as agreed during discussion on the linked issue

## How Has This Been Tested?

I did a local build on emulators and triggered a known crash then examined the contents of the device to make sure the limiter was working, and looked at the debug acralyzer to investigate it there as well. I only got one report on repeated triggers with reporting configured to send. Seems to work

## Learning (optional, can help others)
Note that this will not pass jacocoTestReport as submitted, it passed locally until I reverted the gradle dependency isolation changes that are part of #4950 - It was either send them in here too and have a conflict / remerge need or just queue this and have it wait, I just to have it wait - just re-trigger Travis after landing that one

### CODE REVIEW

**Comment by mikehardy** [comment]
This is unblocked. Note that it throttles in debug builds as well, and the previous local implementation of limiting code cleared the limits on restart and if you set prefs to "always". I don't feel like that's necessary, but maybe if debug is enabled we turn the limits way up or similar? the config is malleable during initialization

**Comment by mikehardy** [comment]
@timrae I'd love review particularly on the second commit and my comment about it - it was your code doing the exception hash and local limiting, and you were clearing the exception-limiting-cache on startup and when "send reports always" was checked. Was that in response to a specific concern or if all that went away would that be okay? Or would you want those features adapted in (they are possible), or...

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java [hunk 1]
```diff
@@ -893,7 +893,7 @@ private void showStartupScreensAndDialogs(SharedPreferences preferences, int ski
                 }
             }
             preferences.edit().putInt("lastUpgradeVersion", current).commit();
-            preferences.edit().remove("sentExceptionReports").commit();     // clear cache of sent exception reports
+            preferences.edit().remove("sentExceptionReports").commit(); // Added 2.6, removed 2.9, remove this later
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java]: The idea here was to clear the cache when the AnkiDroid version gets upgraded, so that we can see more accurately whether a crash went a way or reduced in quantity. Is there functionality for that in Acra limiter?

File: AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java [hunk 2]
```diff
@@ -515,7 +515,6 @@ private void updatePreference(SharedPreferences prefs, String key, PreferenceCon
                 case AnkiDroidApp.FEEDBACK_REPORT_KEY: {
                     String value = prefs.getString(AnkiDroidApp.FEEDBACK_REPORT_KEY, "");
                     AnkiDroidApp.getInstance().setAcraReportingMode(value);
-                    AnkiDroidApp.getSharedPrefs(this).edit().remove("sentExceptionReports").apply();    // clear cache
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java]: I don't remember what my reasoning for this was at the time, I think it's fine not to do it.

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java (hunk 1 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java]: Ah! That's a good idea. I'm sure I can reach into the Limiter hierarchy and clear it - I can already think of a couple ways and I'll come up with something to replace that instead of nuking it.

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java]: (worst case the file is a JSON in the data area we can just delete - I would NOT want to do break abstractions that way but you might be interested if personally testing/debugging something)

File: AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java (hunk 2 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java]: Maybe it's just that on support direction they might be doing it on purpose so we should try again. Worst case it'll generate one extra report for something clearly manual...if I'm already doing a clear in one area I'll have invested in knowing the mechanism for clear, adding it here is well is no big deal with a downside of an extra report and an upside of knowing we can get a report from someone by asking for a toggle here. I'll replace it as above too. Thanks

Comment (timrae) [reply AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java]: > an upside of knowing we can get a report from someone by asking for a toggle here

ah yeah that was it most likely

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java (hunk 1 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java]: ACRA says just delete the file for now, may support it with API in the future - https://github.com/ACRA/acra/issues/694#issuecomment-421217877 - I will implement that in this PR and the cherry-pick to 2.8.x for LTS over there

Comment (timrae) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java]: Normally we only start cherry-picking into hotfix branches when we decide that we actually need a release, but if you prefer to do it now then it's fine.

**Comment by mikehardy** [comment]
I think of this one as the one that lets me even decide if I need a release - I can't find anything reliably in the aggregate in acralyzer sadly. Except for the other commit in this cherry-pick, it's an API>15 call in the widget which is killing us on old devices that try it

**Comment by mikehardy** [comment]
@timrae this is building now, there's a test with 2 sends, a delete and a send verifying the limiting is working - it all appears fine and it's in place now where the non-ACRA implementation was. Should be good to go?
