### PR TITLE
fix + perf: use file scheme in `<img>` `<audio>`, `<video>` and `<object>`

### LINKED ISSUE #15631: [BUG]: The currentTime method can set the start position of an audio
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

The currentTime method can set the start position of an audio, which does not work in the current version (2.17.0) anymore. 

```
<audio id="audio" src={{mp3}} controls controlsList="nodownload"  preload="auto">

<script>
document.getElementById("audio").currentTime=300
document.getElementById("audio").play();
</script>
```

### Expected behaviour

Play from 300 seconds

### Actual behaviour

Play from 0 seconds（the beginning）

### Debug info

```text
AnkiDroid Version = 2.17.0 (af526585a5270c75db3f6b892d00035ad1ab17e0)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 12 (SDK 31)

ProductFlavor = full

Manufacturer = HUAWEI

Model = NOH-AN00

Hardware = kirin9000

Webview User Agent = Mozilla/5.0 (Linux; Android 12; NOH-AN00 Build/HUAWEINOH-AN00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.88 Mobile Safari/537.36

ACRA UUID = 08e625d4-35b6-480e-a91c-992f66f55712

Crash Reports Enabled = false
```

### (Optional) Anything else you want to share?

In the previous version (2.16.0) worke well.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by BrayanDSO**
## Purpose / Description

To be able to use a server to intercept POST requests in the reviewer, the base url of the reviewer isn't the media directory anymore, so files aren't automatically using the `file:///` protocol

## Fixes
* Fixes #15631

## Approach

It uses the `file:///` scheme in the tag sources, which allow seeking and has a better performance than using HTTP partial content (I tried https://github.com/ankidroid/Anki-Android/compare/main...BrayanDSO:Anki-Android:fix_audio_seeking)

### Please note that I removed the video audio because it was copyrighted

Emulator 31:

[yeah-boy_3drhy0gn.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/7cb784c8-a3a8-402b-b431-e998d7e182e4)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by BrayanDSO** [comment]
for the future, this can be made in JavaScript in the reviewer port, since most of its render is in JavaScript.

File: AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt [hunk 1]
```diff
@@ -312,3 +322,43 @@ class TemplateManager {
...
+            val uri = URI(attrValue)
+            if (uri.scheme != null) continue
+            val newValue = "file:///$mediaDir/${uri.path}"
+            elem.attr(attr, newValue)
+            madeChanges = true
+        }
+        return madeChanges
+    }
+
+    val hasMadeChanges =
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt:353]: Could you test case-sensitivity?

**Review by david-allison — CHANGES_REQUESTED** [review]
Test request

File: AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt (hunk 1 above)
Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt:368]: added it, and a bunch of other tests

**Review by mikehardy — APPROVED** [review]
All seems reasonable as I think through it, test support looks pretty solid.
Does this work for you David ?

**Review by david-allison — APPROVED** [review]
Checked this, added a test and I'm happy

**Comment by david-allison** [comment]
force pushed to fix CI
