### PR TITLE
Disallow invalid (null || only whitespace) deck names

### LINKED ISSUE #6590: Crash when creating a blank deck if a blank deck already exists
* Create Deck - Press OK
* Create Deck - Press OK
* Crash

----

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/dd86fc68-bd05-4d67-80ce-b9a191f962f1

2.12alpha20

```
com.ichi2.anki.exception.ManuallyReportedException: We looked for deck "" and instead got deck "blank".
at com.ichi2.anki.AnkiDroidApp.sendExceptionReport(AnkiDroidApp.java:1)
at com.ichi2.libanki.Decks.byName(Decks.java:5)
at com.ichi2.libanki.Decks.id(Decks.java:7)
at com.ichi2.libanki.Decks.id(Decks.java:2)
at com.ichi2.anki.DeckPicker.createNewDeck(DeckPicker.java:2)
at com.ichi2.anki.DeckPicker.p(DeckPicker.java:2)
at com.ichi2.anki.l0.onClick(lambda)
at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:7)
at android.view.View.performClick(View.java:5637)
at android.view.View$PerformClick.run(View.java:22429)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at androidx.test.espresso.base.Interrogator.a(Interrogator.java:31)
at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:130)
at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:124)
at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:59)
at androidx.test.espresso.action.GeneralSwipeAction.perform(GeneralSwipeAction.java:25)
at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:7)
at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:31)
at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6121)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

```
1	06-29 16:31:19.146 I/AnkiDroid(10382): AnkiActivity::onResume - DeckPicker
2	06-29 16:31:19.172 I/AnkiDroid(10382): Updating deck list UI
3	06-29 16:31:19.208 I/AnkiDroid(10382): AnkiActivity::onStop - MyAccount
4	06-29 16:31:19.210 I/AnkiDroid(10382): AnkiActivity::onDestroy - MyAccount
5	06-29 16:31:19.618 I/AnkiDroid(10382): DeckPicker:: Selected deck with id 1593473467576
6	06-29 16:31:19.628 W/AnkiDroid(10382): AnkiActivity/ Couldn't preload url: https://docs.ankidroid.org/manual.html#gettingStarted
7	06-29 16:31:19.653 I/AnkiDroid(10382): Updating deck list UI
8	06-29 16:31:20.139 I/AnkiDroid(10382): DeckPicker:: Selected deck with id 1593473467576
9	06-29 16:31:20.149 W/AnkiDroid(10382): AnkiActivity/ Couldn't preload url: https://docs.ankidroid.org/manual.html#gettingStarted
10	06-29 16:31:20.176 I/AnkiDroid(10382): Updating deck list UI
11	06-29 16:31:20.690 I/AnkiDroid(10382): AnkiActivity::onPause - DeckPicker
12	06-29 16:31:20.912 I/AnkiDroid(10382): AnkiActivity::onStop - DeckPicker
13	06-29 16:31:20.917 I/AnkiDroid(10382): flush - Saving information to DB...
14	06-29 16:31:21.759 I/AnkiDroid(10382): AnkiActivity::onStart - DeckPicker
15	06-29 16:31:21.801 I/AnkiDroid(10382): AnkiActivity::onResume - DeckPicker
16	06-29 16:31:21.826 I/AnkiDroid(10382): Updating deck list UI
17	06-29 16:31:26.321 I/AnkiDroid(10382): Navigating to feedback
18	06-29 16:31:26.334 I/AnkiDroid(10382): AnkiActivity::onPause - DeckPicker
19	06-29 16:31:26.511 I/AnkiDroid(10382): AnkiActivity::onStop - DeckPicker
20	06-29 16:31:27.293 I/AnkiDroid(10382): AnkiActivity::onStart - DeckPicker
21	06-29 16:31:27.323 I/AnkiDroid(10382): AnkiActivity::onResume - DeckPicker
22	06-29 16:31:27.342 I/AnkiDroid(10382): Updating deck list UI
23	06-29 16:31:29.453 I/AnkiDroid(10382): DeckPicker:: Creating new deck...
```

### PR DESCRIPTION
**Pull request by mikehardy**
## Purpose / Description

For some reason we used to allow almost anything as a deck name. Even nulls (!?)

Upstream seems to silently disallow empty decknames, and I think we can reasonably go further and say deck names that don't have at least one non-whitespace character are nonsense

## Fixes
Fixes #6590

## Approach

Create a quick valid deck name method, use it everywhere that Decks.id or Decks.rename is called to pre-validate

Toast with a new invalid deck name message if it's invalid

## How Has This Been Tested?

emulator, create a blank-named deck, rename a deck to blank name, create a filtered deck and try an empty name

Can't do any of those now

## Learning (optional, can help others)

String.trim().isEmpty() (once you have null-checked) is efficient and "good enough" for non-whitespace checking. You can do a regex on `\\w+` or similar, and maybe there are UTF-16 or HTML people can get through but that's okay I think. This will stop the majority of silly deck names and if people go to that trouble, they really mean it, let them have an empty-looking name.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java [hunk 1]
```diff
@@ -653,6 +659,11 @@ public boolean onOptionsItemSelected(MenuItem item) {
                         .negativeText(res.getString(R.string.dialog_cancel))
                         .onPositive((dialog, which) -> {
                             String filteredDeckName = mDialogEditText.getText().toString();
+                            if (!Decks.isValidDeckName(filteredDeckName)) {
+                                Timber.d("Not creating deck with invalid name");
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java:663]: list the name (in quotes)

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java]: good point - I upgraded to Timber.i (if something is interesting enough to toast a user, good enough to actually log) and included deck name in logging or exception in all cases
