### PR TITLE
fix: Image cropper screen action bar color is inconsistent with the preceding screen's one

### LINKED ISSUE #18832: Image cropper screen action bar color is inconsistent with the preceding screen's one
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

Tap a clip button on "Add" screen -> Gallery -> select an image -> "Crop image"

Preceding screen | Image cropper screen
--- | ---
Image |Image|

### Expected behaviour

The image clopper screen's action bar color is inconsistent with the color of the status bar and the preceding screen ("Add image").

### Debug info

```text
AnkiDroid Version = 2.22alpha2 (43cfaa60787193495325b5d0f1ec6fedcb8152c0)  
Backend Version = 0.1.57-anki25.07.1 (25.07.1 a83a6b5928c6563d12e7b66d4f7b7b2f51b6f22b)  
Android Version = 11 (SDK 30)  
ProductFlavor = full  
Device Info = OPPO | OPPO | OP4BAFL1 | CPH2013 | CPH2013 | qcom  
Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/138.0.7204.45 Mobile Safari/537.36  
ACRA UUID = dae56c60-345e-41f3-a616-f02ce05cd8ad  
FSRS = 4.1.1 (Enabled: false)  
Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

N/A

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by snowtimeglass**
## Purpose / Description
The image clopper screen's action bar color is inconsistent with the color of the status bar and the preceding screen ("Add image"). This PR intends to fix the inconsistency.

## Fixes
* Fixes #18832

## Approach
- Remove the codes regarding the action bar color
- Change the icon references from the current icons (hard-coded in white color) managed in CanHub repository to the new icons managed in AnkiDroid repository.
- Use Google Material Icons for the new icons
    - [Rotate](https://fonts.google.com/icons?selected=Material+Icons+Outlined:rotate_right:&icon.set=Material+Icons&icon.size=24&icon.color=%235f6368&icon.query=rotate)
    - [Flip](https://fonts.google.com/icons?selected=Material+Icons+Outlined:flip:&icon.set=Material+Icons&icon.size=24&icon.color=%235f6368&icon.query=rotate)

## How Has This Been Tested?

Checked in a physical device (Android 11)

**Before** 

**After**

https://github.com/user-attachments/assets/6c80f513-df98-47d8-be82-e2108d6b35d1

<details>
<summary>Other themes</summary>

</details>

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by snowtimeglass** [comment]
image

```
CardBrowserTest > column spinner positions are initially set from existing preferences FAILED
    kotlinx.coroutines.test.UncompletedCoroutinesError: After waiting for 1m, the test body did not run to completion
```


```
DeckPickerTest > [0] > ContextMenu testDynRebuildAndEmpty[0] FAILED
    kotlinx.coroutines.test.UncompletedCoroutinesError: After waiting for 1m, the test body did not run to completion
```

Maintainers, could you please re-run the failed check (or let me know what to do) when convenient?

File: AnkiDroid/src/main/java/com/ichi2/imagecropper/ImageCropper.kt [hunk 1]
```diff
@@ -119,44 +123,41 @@ class ImageCropper :
...
+            R.id.action_flip_horizontally -> {
+                Timber.d("Flip_horizontally clicked")
                 cropImageView.flipImageHorizontally()
                 true
             }
 
-            com.canhub.cropper.R.id.ic_flip_24_vertically -> {
-                Timber.d("Flip vertically clicked")
+            R.id.action_flip_vertically -> {
+                Timber.d("Flip_vertically clicked")
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/imagecropper/ImageCropper.kt]: Probably revert this, feels like it has negative value

File: AnkiDroid/src/main/java/com/ichi2/imagecropper/ImageCropper.kt [hunk 2]
```diff
@@ -119,44 +123,41 @@ class ImageCropper :
...
     ) {
-        menu.clear()
-        // TODO make our own menu, we shouldn't rely on third party menu files
-        menuInflater.inflate(com.canhub.cropper.R.menu.crop_image_menu, menu)
+        menuInflater.inflate(R.menu.image_cropper_menu, menu)
     }
 
     override fun onMenuItemSelected(menuItem: MenuItem): Boolean =
         when (menuItem.itemId) {
-            com.canhub.cropper.R.id.crop_image_menu_crop -> {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/imagecropper/ImageCropper.kt:129]: I would keep the ordering the same to reduce line noise in the diff

Comment (snowtimeglass) [reply AnkiDroid/src/main/java/com/ichi2/imagecropper/ImageCropper.kt:129]: Thank you for reviewing and the feedback. I'll do so.

File: AnkiDroid/src/main/java/com/ichi2/imagecropper/ImageCropper.kt (hunk 1 above)
Comment (snowtimeglass) [reply AnkiDroid/src/main/java/com/ichi2/imagecropper/ImageCropper.kt]: Could you please elaborate? You mean reverting to ~~the CanHub references for the four actions?~~"Flip vertically clicked"?

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/imagecropper/ImageCropper.kt]: The change in Timber message. It seems better as `Timber.d("Flip vertically clicked")`

**Comment by snowtimeglass** [comment]
The code has been updated as suggested. 
Tested again after the change. The "After" screenshots and video have been updated. The other themes screenshots have been added.

---

> Optional: would be useful to split this into two changes: one handling the menu, the other handling the status bar

I have just removed the parts regarding the status bar from this PR: at first I imitated the part of the preceding "Add image" screen code, but this cropper screen seems to go well without the parts. Thank you for the suggestion.

**Review by BrayanDSO — APPROVED** [review]
LGTM
