### PR TITLE
fix: Syncing handles notetype style changes

### LINKED ISSUE #14827: [BUG]: Update of styling section of card types on Anki Desktop is not reflected on AnkiDroid
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Prepare a card which already exists both on the desktop version and on AnkiDroid
  

2. Update the content of the front template of the card type on the desktop version

    **Before**
  image
↓
**After**
image

3. Update the content of the styling section of the card type as well
  
    **Before**
  image
↓
**After**
image

5. "Sync" on the desktop version 
  image

6. "Sync" on AnkiDroid
7. Show the card on AnkiDroid

### Expected behaviour

Both updates of the front template and the styling are reflected on the card

### Actual behaviour

Although the update of the front template is reflected on the card, the update of the styling is not reflected.

### Debug info

```text
AnkiDroid Version = 2.17alpha6 (393f61b229a26ec97eb13c83f0d1f09652f776c2)

Android Version = 11

ProductFlavor = play

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/118.0.0.0 Mobile Safari/537.36

ACRA UUID = df169a4d-29ec-46b6-b114-141ca7e01ba3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

Neither the front template nor the styling section is updated on AnkiDroid

After a one-way sync from AnkiWeb or completely-closing and restarting the app, the updates are reflected.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
After a sync, styling is not updated if the card was viewed beforehand

* #14827
## Fixes
* Fixes #14827

## Approach
The notetype cache needed to be cleared after a sync

## How Has This Been Tested?
API 33 emulator & Anki Desktop

## Learning (optional, can help others)
https://github.com/ankidroid/Anki-Android/issues/14827#issuecomment-1828979515

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt [hunk 1]
```diff
@@ -115,6 +117,10 @@ class Notetypes(val col: Collection) {
         return _cache.get(ntid)
     }
 
+    @NotInLibAnki
+    @NeedsTest("14827: styles are updated after syncing style changes")
+    fun clearCache() = _cache.clear()
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Notetypes.kt:122]: Isn't this in libanki?

https://github.com/ankitects/anki/blob/bba67fdab44fd9f1f899e71f854fbfac88005dd3/pylib/anki/models.py#L113-L114

**Comment by BrayanDSO** [comment]
nit: I believe that it is better, and Damien has said the same IIRC, to try using the default casing of the programming language instead of python's for libanki code. So, `_clear_cache` shouldn't be in snake case
