### PR TITLE
fix(notifications): use app language

### LINKED ISSUE #19048: Notification Doesn't Follow App Language
Forums: https://forums.ankiweb.net/t/the-x-ankidroid-cards-due-notification-is-in-the-system-language-not-the-app-language/63864

I am having the feeling that this was logged in GH, but I searched here and couldn't find any open/closed issue.

### PR DESCRIPTION
**Pull request by david-allison**
> [!NOTE]
> Assisted-by: Claude Opus 4.6 - withAppLocale + investigation

## Purpose / Description
On API 32 and earlier, `AppCompatDelegate.setApplicationLocales` only works with AppCompatActivity.

## Fixes
* Fixes #19048

## Approach
Work around this by manually setting the app locale

## How Has This Been Tested?

Android Version = 7.0 (SDK 24)  

* Set the language to German then launch the app, before and after

Screenshot 2026-04-15 at 12 04 47
Screenshot 2026-04-15 at 12 03 44

## Learning (optional, can help others)
https://developer.android.com/reference/androidx/appcompat/app/AppCompatDelegate#setApplicationLocales(androidx.core.os.LocaleListCompat)

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.kt [hunk 1]
```diff
@@ -448,9 +451,11 @@ class NotificationService : BroadcastReceiver() {
      * @see getIntent
      */
     override fun onReceive(
-        context: Context,
+        rawContext: Context,
         intent: Intent,
     ) {
+        // #19048: On API < 33, BroadcastReceiver context uses the system locale.
+        val context = rawContext.withAppLocale()
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.kt]: I'm tempted to make an `AnkiBroadcastReceiver` which handles this automatically so people can't forget. 

Thoughts?

Comment (ericli3690) [reply AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.kt]: I'm not opposed! From a brief skim it seems there are other BroadcastReceivers in the codebase that do things like show themed toasts to the user, which are probably in the incorrect language right now, ex. this line in SharedDecksDownloadFragment can be called by a BroadcastReceiver's onReceive:

```kotlin
context?.let { showThemedToast(it, R.string.something_wrong, false) }
```

So it would be good to enforce this more uniformly.

File: AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt [hunk 2]
```diff
@@ -363,6 +364,31 @@ object LanguageUtil {
...
+     * or [Service][android.app.Service]):
+     *
+     * On API < 33, [AppCompatDelegate.setApplicationLocales] only applies to Activity contexts, so
+     *  resources resolve in the system locale.
+     *
+     * Returns [this] unchanged (System language) when no in-app language is set.
+     *
+     * This method will not throw.
+     */
+    fun Context.withAppLocale(): Context =
```
Comment (ericli3690) [inline AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt:380]: Awesome!!

**Review by ericli3690 — APPROVED** [review]
Thank you David!! This looks great. I'll make a note to test this on the new review reminders system too once our strings are localized.

Only one major concern: this issue was originally opened when I found this to-do comment by @mikehardy in [NotificationChannels](https://github.com/ankidroid/Anki-Android/blob/main/AnkiDroid/src/main/java/com/ichi2/anki/NotificationChannels.kt#L44-L45):

```kotlin
/**
 * Create or update all the notification channels for the app
 *
 * In Oreo and higher, you must create a channel for all notifications.
 * This will create the channel if it doesn't exist, or if it exists it will update the name.
 *
 * Note that once a channel is created, only the name may be changed as long as the application
 * is installed on the user device. All other settings are fully under user control.
 *
 * TODO should be called in response to [Intent.ACTION_LOCALE_CHANGED]
 * @param context the context for access to localized strings for channel names
 */
fun setupNotificationChannels(context: Context) {
// ...
```

In particular the TODO portion. Do we actually need to make `setupNotificationChannels` listen to `Intent.ACTION_LOCALE_CHANGED`, or will that no longer necessary after merging this PR? If so, please remove the above comment in NotificationChannels.

**Comment by david-allison** [comment]
> Thank you David!! This looks great. I'll make a note to test this on the new review reminders system too once our strings are localized.
> 
> Only one major concern: this issue was originally opened when I found this to-do comment by @mikehardy in [NotificationChannels](https://github.com/ankidroid/Anki-Android/blob/main/AnkiDroid/src/main/java/com/ichi2/anki/NotificationChannels.kt#L44-L45):
> 
> ```kotlin
> /**
>  * Create or update all the notification channels for the app
>  *
>  * In Oreo and higher, you must create a channel for all notifications.
>  * This will create the channel if it doesn't exist, or if it exists it will update the name.
>  *
>  * Note that once a channel is created, only the name may be changed as long as the application
>  * is installed on the user device. All other settings are fully under user control.
>  *
>  * TODO should be called in response to [Intent.ACTION_LOCALE_CHANGED]
>  * @param context the context for access to localized strings for channel names
>  */
> fun setupNotificationChannels(context: Context) {
> // ...
> ```
> 
> In particular the TODO portion. Do we actually need to make `setupNotificationChannels` listen to `Intent.ACTION_LOCALE_CHANGED`, or will that no longer necessary after merging this PR? If so, please remove the above comment in NotificationChannels.

Untested, I suspect it will still be necessary

**Comment by mikehardy** [comment]
If the goal is to have "all of the app" change when a language changes - either through our in-app language picker or through a system locale change, then you also must persist new notification channel names into the android system as well, implying that - yes - that notification channel setup needs to be hooked on to whatever infra we have for handling language updates, and we should be listening to system locale change broadcast

**Comment by david-allison** [comment]
I'm leaving the `NotificationChannel` TODO as out of scope for this PR

From what I recall, the state of notification channels being semi-immutable would need some additional brainpower, whereas this is a fairly simple refactor.

File: AnkiDroid/src/main/java/com/ichi2/anki/services/AlarmManagerService.kt [hunk 3]
```diff
@@ -19,19 +19,23 @@ package com.ichi2.anki.services
...
+import com.ichi2.anki.android.AnkiBroadcastReceiver
 import com.ichi2.anki.common.time.TimeManager
 import com.ichi2.anki.reviewreminders.ReviewReminder
 import com.ichi2.anki.reviewreminders.ReviewReminderScope
 import com.ichi2.anki.reviewreminders.ReviewRemindersDatabase
 import com.ichi2.anki.reviewreminders.upsertReminder
+import com.ichi2.anki.services.AlarmManagerService.Companion.WINDOW_LENGTH_MS
+import com.ichi2.anki.services.AlarmManagerService.Companion.getIntent
+import com.ichi2.anki.services.AlarmManagerService.Companion.scheduleAllEnabledReviewReminderNotifications
+import com.ichi2.anki.services.AlarmManagerService.Companion.unscheduleReviewReminderNotifications
```
Comment (ericli3690) [inline AnkiDroid/src/main/java/com/ichi2/anki/services/AlarmManagerService.kt:38]: Why are we importing the Companion properties and methods within the same class that defines them?

File: AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.kt [hunk 4]
```diff
@@ -41,6 +41,8 @@ import com.ichi2.anki.reviewreminders.ReviewReminderScope
 import com.ichi2.anki.reviewreminders.ReviewRemindersDatabase
 import com.ichi2.anki.reviewreminders.upsertReminder
 import com.ichi2.anki.runGloballyWithTimeout
+import com.ichi2.anki.services.NotificationService.Companion.addAction
+import com.ichi2.anki.services.NotificationService.Companion.getIntent
```
Comment (ericli3690) [inline AnkiDroid/src/main/java/com/ichi2/anki/services/NotificationService.kt:45]: Similarly here?

File: AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt [hunk 5]
```diff
@@ -614,30 +615,30 @@ private fun Activity.showError(
 ) = showError(throwable.toString(), throwable.toCrashReportData(context = this, reportException))
 
 /**
- * Since BroadcastReceiver onReceive methods are expected to finish quickly, this helper function
- * is required to run a suspending function from an onReceive method. [BroadcastReceiver.goAsync]
- * extends the lifetime of the onReceive method and tells the OS not to kill the process prematurely.
+ * Since BroadcastReceiver onReceiveBroadcast methods are expected to finish quickly, this helper function
```
Comment (ericli3690) [inline AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt]: nit: change occurrences of "BroadcastReceiver" in comments on this method to "AnkiBroadcastReceiver".

**Review by ericli3690 — APPROVED** [review]
Nice!

**Comment by david-allison** [comment]
@ericli3690 Thanks so much!

Im assuming your approval still stands, but a second look would be excellent

**Review by ericli3690 — APPROVED** [review]
Yep looks great! Thanks thanks

**Review by mikehardy — APPROVED** [review]
LGTM - it is unbelievable how much effort it takes to keep an "app language may not be system language" feature working correctly in Android across Android SDK version skew... the amount of time over the years...

**Comment by david-allison** [comment]
I forgot to force push here, there will be a minor follow-up
