### PR TITLE
interface based solution for TagsDialog

### LINKED ISSUE #6174: [ACRA 2.10] - NullPointerException: TagsDialogListener
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/32723929-52d0-44f1-8f43-27d74ba2bc0c

```
java.lang.NullPointerException: Attempt to invoke interface method 'void com.ichi2.anki.dialogs.TagsDialog$TagsDialogListener.onPositive(java.util.List, int)' on a null object reference
at com.ichi2.anki.dialogs.TagsDialog.a(TagsDialog.java:3)
at com.ichi2.anki.dialogs.p1.onClick(lambda)
at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:7)
at android.view.View.performClick(View.java:6257)
at android.widget.TextView.performClick(TextView.java:11149)
at android.view.View$PerformClick.run(View.java:23705)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6780)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1500)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1390)
```

### PR DESCRIPTION
**Pull request by almas33**
## Purpose / Description
pull request made for this issue were to be reverted and to make a interface based solution

## Fixes
Fixes #6174 

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
Thanks for the PR!!

Could you change the PR title and the commit message. 6175 was already reverted: https://github.com/ankidroid/Anki-Android/pull/6350

* Could you change `onPositive` to something more descriptive
* Could you remove `setTagsDialogListener` and the member variable
* Could you cast `[require|get]Activity` to `TagsDialogListener` instead of using the member variable

**Comment by almas33** [comment]
as 4 activities were using `onPositive` so I wasn't able to think of any better name than this

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 1]
```diff
@@ -3876,21 +3876,22 @@ String getCardContent() {
...
-                displayCardQuestion(true);
-            }
-        };
         TagsDialog dialog = TagsDialog.newInstance(TagsDialog.DialogType.ADD_TAG, selTags, tags);
-        dialog.setTagsDialogListener(tagsDialogListener);
         showDialogFragment(dialog);
     }
 
+    @Override
+    public void onPositive(ArrayList<String> selectedTags, int option) {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3884]: Could we rename `TagsDialogListener.onPositive`, it has no semantic meaning in the context of the CardViewer?

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java [hunk 2]
```diff
@@ -111,7 +111,7 @@
 import static com.ichi2.anim.ActivityTransitionAnimation.Direction.*;
 
 public class CardBrowser extends NavigationDrawerActivity implements
-        DeckDropDownAdapter.SubtitleListener {
+        DeckDropDownAdapter.SubtitleListener, TagsDialog.TagsDialogListener{
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java:114]:
```suggestion
        DeckDropDownAdapter.SubtitleListener, TagsDialog.TagsDialogListener {
```

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java [hunk 3]
```diff
@@ -149,7 +149,8 @@
  *
  * @see <a href="http://ankisrs.net/docs/manual.html#cards">the Anki Desktop manual</a>
  */
-public class NoteEditor extends AnkiActivity {
+public class NoteEditor extends AnkiActivity implements
+        TagsDialog.TagsDialogListener{
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java:153]:
```suggestion
        TagsDialog.TagsDialogListener {
```

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
Looks good!

Could you also convert the `ArrayList` in `onPositive` to a `List`

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java (hunk 1 above)
Comment (almas33) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3884]: should I make another function in interface which can also have a different name for `CardBrowser` as coverting to `List` would make code less readable in `NoteEditor` because we have to make adjustments.

Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3884]: No, just rename `onPositive` to something relevant for the activities

`onTagsSelected` for example

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java [hunk 4]
```diff
@@ -311,7 +311,12 @@ public void afterTextChanged(Editable editable) {
         return keyValueMap;
     }
 
-    private void customStudyFromTags(List<String> selectedTags, int option) {
+    @Override
+    public void onSelectedTags(ArrayList<String> selectedTags, int option) {
+        /*
+         * Here's the method that gathers the final selection of tags, type of cards and
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java:317]: Convert the comment to a doccomment above the method name

Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java:317]:
```suggestion
         * Gathers the final selection of tags, type of cards and
```

**Review by david-allison-1 — COMMENTED** [review]
Pretty much there, should be the final one - should be able to convert to `list` for a nicer interface

**Review by david-allison-1 — APPROVED** [review]
Looks great to me, thanks for the quick turnaround!

**Review by mikehardy — APPROVED** [review]
This looks nice!

**Comment by mikehardy** [comment]
Hi there!

Just a friendly notice (one per person for PRs merged in March, regardless of PR quantity) that we try to process OpenCollective payments monthly - it's time for March 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

Thanks!
