### PR TITLE
Fix #15993: Scroll position wrong after editing

### LINKED ISSUE #15993: [BUG]: Card Browser doesn’t remember scroll position after editing card
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Open the Card Browser.
2. Scroll down and tap on a card low on the list.
3. Edit the card and tap the “Save” (check mark) button.

https://github.com/ankidroid/Anki-Android/assets/31406320/6b2b63fa-059c-4bb2-8a2e-6cfb2482d399

### Expected behaviour

The card list should appear in the same scroll position from which I tapped on the card

### Actual behaviour

As shown in the video:
The first time, after editing the card, it keeps the scroll position
The second time, after editing the card, it scroll to the top of the card list

I tried several times. Sometimes it works well, sometimes it works wrong: that the card list scroll to the edited card posistion instead of keep the original position

### Debug info

```text
APP Version: 2.18alpha6
Android Version: Android10.0
```

### (Optional) Anything else you want to share?

It is a regression: https://github.com/ankidroid/Anki-Android/issues/6857

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by Henriqueist**
## Purpose / Description
When editing a card in the CardBrowser, after scrolling down and selecting a card at the bottom of the list, the scroll position is lost when returning to the CardBrowser.

https://github.com/user-attachments/assets/4728dc4d-6032-4d28-aa27-3e151b8c7e44

## Fixes
* Fixes #15993 

## Approach
I added several breakpoints in the code and debugged the process of editing a card in the CardBrowser. After scrolling down, selecting a card at the end of the list, and saving it, I noticed that the scroll position was not being correctly stored when clicking on the card. As a result, when returning to the CardBrowser after the edit, the scroll would not maintain the expected position and would return inconsistently.
I now save the position of the first visible item when clicking on a card (onTap()), and when returning to the CardBrowser after saving, the scroll is adjusted back to the previously saved position (onResume()).

## How Has This Been Tested?
I tested in the emulator 34 and 35  the process of editing a card in CardBrowser, and now the scroll is adjusted back to the previously saved position.

https://github.com/user-attachments/assets/5b09b4d5-5f4d-4ebc-be67-bb0ed0486449

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt [hunk 1]
```diff
@@ -352,6 +352,8 @@ open class CardBrowser :
                 viewModel.saveScrollingState(id)
                 viewModel.oldCardTopOffset = calculateTopOffset(viewModel.lastSelectedPosition)
             } else {
+                viewModel.lastSelectedPosition = (cardsListView.layoutManager as LinearLayoutManager).findFirstVisibleItemPosition()
+                viewModel.oldCardTopOffset = calculateTopOffset(viewModel.lastSelectedPosition)
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt:356]: 🤔  Is it correct to alter the `lastSelectedPosition` by setting it to the `firstVisibleItemPosition`?

What I mean is: semantically, is the first visible item *really* the last selected position? Is it selected? Is it the last selected thing?

What happens if you do not set .lastSelectedPosition but instead `calculateTopOffset` directly from `findFirstVisibleItemPosition`?

If that works, it seems like it avoids setting state to something that may not be the real state for the thing

**Review by mikehardy — COMMENTED** [review]
Hi there! This has promise but I have a question as noted directly on the related lines

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt (hunk 1 above)
Comment (Henriqueist) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt:356]: Hello,
I tested the case of not setting lastSelectedPosition, and the same issue of not maintaining the scroll position still occurs.
I adjust lastSelectedPosition because, when performing the autoscroll afterward, it moves to the correct scroll position. However, perhaps lastSelectedPosition is not the most appropriate name, as it may not accurately reflect its purpose in this context.

**Comment by Henriqueist** [comment]
Hi,
I’ve responded to your questions directly in the code discussion above. Please let me know if any part remains unclear or if further clarification is needed.

**Review by david-allison — APPROVED** [review]
Looks good to me. Sorry this sat. Life got busy

**Review by mikehardy — APPROVED** [review]
Okay - also sorry this sat, you responded to my concern long ago but I had not come back yet. Thanks for the contribution, very much appreciated
