### PR TITLE
Handle Exception from FileProvider in crop

### LINKED ISSUE #6628: BasicImageFieldController - getUriForFile -  Failed to find configured root that contains /
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/dee25249-a86f-40f9-bce9-a038b518356c

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity}: java.lang.IllegalArgumentException: Failed to find configured root that contains /
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3448)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:7814)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
Caused by: java.lang.IllegalArgumentException: Failed to find configured root that contains /
at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:13)
at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:2)
at com.ichi2.anki.multimediacard.fields.BasicImageFieldController.getUriForFile(BasicImageFieldController.java:3)
at com.ichi2.anki.multimediacard.fields.BasicImageFieldController.createUI(BasicImageFieldController.java:5)
at com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity.recreateEditingUi(MultimediaEditFieldActivity.java:16)
at com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity.onCreate(MultimediaEditFieldActivity.java:17)
at android.app.Activity.performCreate(Activity.java:7955)
at android.app.Activity.performCreate(Activity.java:7944)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3423)
... 11 more
```

### PR DESCRIPTION
**Pull request by mikehardy**
## Purpose / Description

FileProvider can throw unchecked exceptions

Not a fan of system APIs throwing RuntimeExceptions, they catch me out like this too frequently

## Fixes
Fixes #6628 

## Approach

Pokemon error handling, fall back to non-FileProvider URI, consumers of the method already have hardening against the image still being non-existent in case fallback / non-FileProvider style results in invalid URI

## How Has This Been Tested?

Difficult to test unfortunately but when I feed bad data as image references into the image field editor I can't make it crash. I couldn't make it crash before though unfortunately and there is no good test infrastructure here yet

## Learning (optional, can help others)

Always always always check underlying APIs to see if they can throw RuntimeExceptions

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java [hunk 1]
```diff
@@ -654,13 +654,15 @@ private void handleCropResult() {
...
-        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
-            uri = FileProvider.getUriForFile(mActivity, mActivity.getApplicationContext().getPackageName() + ".apkgfileprovider", file);
-        } else {
-            uri = Uri.fromFile(file);
+        try {
+            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
+                return FileProvider.getUriForFile(mActivity, mActivity.getApplicationContext().getPackageName() + ".apkgfileprovider", file);
+            }
+        } catch (Exception e) {
+            Timber.w("getUriForFile failed on %s - attempting fallback", file);
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java:662]:
```suggestion
            Timber.w(e, "getUriForFile failed on %s - attempting fallback", file);
```

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java:662]: @david-allison-1 are you thinking sendExceptionReport with some info if it happens? That's what I infer by "telemetry", and it might help

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java]: I added one semi-speculatively as a second commit along with the forgotten root exception to Timber, in a second commit

Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java]: >  and an exception report doesn't seem appropriate here if there's a valid fallback

I don't think an exception report is the right mode of reporting here unless we can specify a "only send if `always send` is checked" - maybe that's the solution

We don't want to send an exception report if the operation succeeds due to corrective action as that's bad UX

Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java]: But, I don't think this should block the review regardless.

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java]: Good thinking, I re-pushed the second commit with a new "only send the report if the user is set to autoaccept" style, what do you think?

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 2]
```diff
@@ -342,6 +342,15 @@ public static void sendExceptionReport(Throwable e, String origin, String additi
     }
 
 
+    public static void sendExceptionReportConditionally(Throwable e, String origin, String additionalInfo, boolean onlyAlwaysOn) {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:345]: nit: `onlyAlwaysOn` doesn't seem necessary. There's no reason to pass false.

Maybe `send[Silent/Unintrusive]ExceptionReport`?

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:345]: I like that - when I began the API addition I was thinking I'd do the typical extra-optional-argument / chain others to it type deal then I as I thought about it since it touched Preferences and the others didn't, this one might be heavier so it should probably chain back to the existing API. Basically I waffled on it so it's chaining back and got a crap name. I'm going to reshape it to be the more standard pattern of API chaining into the one with more arguments and the new argument will be `onlyIfSilent` and get a good javadoc

**Comment by mikehardy** [comment]
Skipped the javadoc and instead made the log message complete + obvious as developer aid along with just good argument naming on the new sendExceptionReport that only goes if silent

Also discovered while self-reviewing again I was doing the telemetry Timber *after* sending the report which is quite useless.

I'm happy with this now

**Comment by mikehardy** [comment]
I am endlessly surprised by the quantity of improvement that can be made on even the smallest changes I attempt, on review, seemingly regardless of effort level on first cut. Thanks for the help shaping it up
