### PR TITLE
Fix Title to recall what gesture the window is for

### LINKED ISSUE #12326: Recall what gesture the window is for
When assigning gesture, there is nothing that recall on which action a gesture is currently being assigned. Can someone please add a title, so that it's certain that I didn't misclick and that I have no doubt whether I'm at button 2 or 3 already.

Ping @BrayanDSO since you worked on it

### PR DESCRIPTION
**Pull request by pratyaksh1610**
## Purpose / Description
Fixed the title to recall what gesture the window is for.

## Fixes
fixes #12326

## Before

https://user-images.githubusercontent.com/76740999/200167234-4f789859-91f3-44c9-89cb-9fff4b5e7e80.mp4

## After

https://user-images.githubusercontent.com/76740999/200167238-547473b5-fa26-4d16-9a09-007a55130589.mp4

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt [hunk 1]
```diff
@@ -54,15 +54,16 @@ class ControlPreference : ListPreference {
     @Suppress("unused") constructor(context: Context, attrs: AttributeSet?) : super(context, attrs)
     @Suppress("unused") constructor(context: Context) : super(context)
 
+    @SuppressLint("StringFormatInvalid")
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt:57]: This shouldn't be necessary

File: AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt [hunk 2]
```diff
@@ -54,15 +54,16 @@ class ControlPreference : ListPreference {
...
     fun refreshEntries() {
         val entryTitles: MutableList<CharSequence> = ArrayList()
         val entryIndices: MutableList<Int> = ArrayList()
         // negative indices are "add"
-        entryTitles.add(context.getString(R.string.binding_add_key))
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt:61]: Not needed. We only want to change the dialog title, not the options names

File: AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt [hunk 3]
```diff
@@ -54,15 +54,16 @@ class ControlPreference : ListPreference {
...
+        entryTitles.add(context.getString(R.string.binding_add_key, ADD_KEY_INDEX.toString()))
         entryIndices.add(ADD_KEY_INDEX)
         // Put "Add gesture" option if gestures are enabled
         if (AnkiDroidApp.getSharedPrefs(context).getBoolean(GestureProcessor.PREF_KEY, false)) {
-            entryTitles.add(context.getString(R.string.binding_add_gesture))
+            entryTitles.add(context.getString(R.string.binding_add_gesture, ADD_GESTURE_INDEX.toString()))
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt:66]: Ditto

File: AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt [hunk 4]
```diff
@@ -89,7 +90,7 @@ class ControlPreference : ListPreference {
         when (val index: Int = (newValue as String).toInt()) {
             ADD_GESTURE_INDEX -> {
                 MaterialDialog(context).show {
-                    title(R.string.binding_add_gesture)
+                    title(context.getString(R.string.binding_add_gesture, ADD_GESTURE_INDEX.toString()).toInt())
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt:93]: If you look at it, you will see that ADD_GESTURE_INDEX is a int constant, not the title of the preference.

As there is a `title` property on the class you are editing, you can access and pass it as parameter here

File: AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt [hunk 5]
```diff
@@ -117,7 +118,7 @@ class ControlPreference : ListPreference {
                 MaterialDialog(context).show {
                     val keyPicker: KeyPicker = KeyPicker.inflate(context)
                     customView(view = keyPicker.rootLayout)
-                    title(R.string.binding_add_key)
+                    title(context.getString(R.string.binding_add_key, ADD_KEY_INDEX.toString()).toInt())
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt:121]: Ditto

File: AnkiDroid/src/main/res/values/10-preferences.xml [hunk 6]
```diff
@@ -315,9 +315,9 @@
     <string name="donate_description"><![CDATA[You can support AnkiDroid\'s development by <a href=\"%1$s\">donating</a>. Any amount is deeply appreciated.]]></string>
 
     <!-- Controls -->
-    <string name="binding_add_gesture">Add gesture</string>
+    <string name="binding_add_gesture">Add gesture for %s</string>
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/res/values/10-preferences.xml:318]: It's probably best to discuss on the original issue which strings would be best

**Review by BrayanDSO — COMMENTED** [review]
Hello there. By looking at the code and based on the fact that lint fails, I assume that you haven't tested the result of your changes.

Before you push any changes you make, I'd like if you could run at least the linter (see the Development guide in the repository wiki to know how). Also, run the app, see the result of your changes on Settings > Controls, then take a screenshot and post it here.

**Comment by pratyaksh1610** [comment]
> Hello there. By looking at the code and based on the fact that lint fails, I assume that you haven't tested the result of your changes.
> 
> Before you push any changes you make, I'd like if you could run at least the linter (see the Development guide in the repository wiki to know how). Also, run the app, see the result of your changes on Settings > Controls, then take a screenshot and post it here.

Just ran all the tests again, found that all lint tests are passing on my machine, I think lint failed due to ` @SuppressLint("StringFormatInvalid")`

File: AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt (hunk 4 above)
Comment (pratyaksh1610) [reply AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt:93]: So in the title we need to pass `ADD_GESTURE_INDEX` only.
`title(ADD_GESTURE_INDEX)`

**Comment by david-allison** [comment]
> Just ran all the tests again, found that all lint tests are passing on my machine, I think lint failed due to ` @SuppressLint("StringFormatInvalid")`

You can either see the output on GitHub, or run `./gradlew lintPlayDebug ktLintCheck`

See: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#lint

File: AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt (hunk 4 above)
Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt:93]: Type `this` in your IDE and it will show some options. One of them will be the class you are editing `this@ControlPreference`, so you can get the control title with `this@ControlPreference.title`. Then pass it as parameter of `context.getString`

**Comment by Arthur-Milchior** [comment]
Also, can you please provide screenshot, so it's easy to see what it looks like

File: AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt (hunk 4 above)
Comment (pratyaksh1610) [reply AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt:93]: I am unable to comprehend this part, can you please explain, how it should be passed, as title should be `string`.

**Comment by david-allison** [comment]
The lint check still fails, please see the linked GitHub action, or run `./gradlew lint`

**Comment by Arthur-Milchior** [comment]
While it's not the main problem to solve here, generally, we try to rebase onto main, and not merge it. Don't hesitate to force push on this branch after that

File: AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt (hunk 4 above)
Comment (Arthur-Milchior) [reply AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt:93]: `title(text=context.getString(R.string.binding_add_gesture, ))`
Using `text=` you ensure that you can pass an explicit string.

`toInt` could not have worked. Indeed, the typing works, the trouble is that `title()`'s int is supposed to be a string resource id. The issue is that `toInt` was not a string resource id. Actually, it was not even working, since, the way `toInt` work is that `"42".toInt()` would return the number `42`. But if your string is not actually a number, then it can't create a relevant number out of it.

Personally, I'd put `val actionName = title` (in between `ADD_GESTURE_INDEX` and the `MaterialDialog(context)`, and then use this value in `title(text=context.getString(R.string.binding_add_gesture, actionName))`, I find it easier to read.

Is it more understandable @pratyaksh1610 ?

**Comment by Arthur-Milchior** [comment]
By the way @pratyaksh1610 , are you still working on it?

**Comment by pratyaksh1610** [comment]
> By the way @pratyaksh1610 , are you still working on it?

I am working on it.

**Review by david-allison — CHANGES_REQUESTED** [review]
I don't feel we need 'add gesture/key for' in the title:

* 'Add key for Answer Button 1' -> 'Answer Button 1'
* 'Add gesture for Answer Button 1' -> 'Answer Button 1'

I feel the additional context is redundant given the user's action to get here, and the UX of the dialog. Adding more text makes the purpose of the dialog less clear as the user needs to read more to get the context

File: AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt [hunk 7]
```diff
@@ -88,8 +88,9 @@ class ControlPreference : ListPreference {
     override fun callChangeListener(newValue: Any?): Boolean {
         when (val index: Int = (newValue as String).toInt()) {
             ADD_GESTURE_INDEX -> {
+                val actionName = title
                 MaterialDialog(context).show {
-                    title(R.string.binding_add_gesture)
+                    title(text = context.getString(R.string.binding_add_gesture_title, actionName))
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt:93]: You can use `this@` to remove the need for the variable, combining this with my previous suggestion:

```kotlin
                    title(text = this@ControlPreference.title?.toString())
```

Comment (oakkitten) [reply AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt:93]: You can just directly refer to `title` without `this@ControlPreference`. But I actually like `actionName`, it says more about the contents that just `title`.

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt:93]: Right you are, thanks!

**Review by david-allison — APPROVED** [review]
Looks great, thanks!

**Review by mikehardy — APPROVED** [review]
Also looks good to me now - this is now a very small + focused change, nice

**Comment by Arthur-Milchior** [comment]
Thanks a lot @pratyaksh1610. Using Gesture a lot, it'll really save me ... well seconds. But those are frustrating seconds.
