### PR TITLE
Refactor ForgetCardsDialog and potentially fix a bug

### LINKED ISSUE #17079: [BUG]: "Reset progress" can't work in Reviewer on the spot and causes error
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Show a review card in Reviewer
     
     
     (counterpart screen in Desktop)
     

2. "Reschedule" > "Reset progress" > "OK"
     

     

   (then, a message, "1 card reset", is shown) 
     

**Result**
- The numbers of review cards and new cards are unchanged. (Supposedly, the card is still treated as a review card.)
     

- Selecting an answer button causes an error
     
     

https://github.com/user-attachments/assets/1547c887-ef42-4e37-b90a-835987e62e78

### Expected behaviour

The count number of review cards decreases by one, and the count number of new cards increases by one, as in the desktop version. (The cards is treated as a new card on the spot.)

image

### Debug info

```text
AnkiDroid Version = 2.19beta2 (2dab92e5214d6e21ebe2dd3a05e20a04ed7a9858)

Backend Version = 0.1.40-anki24.06.3 (24.06.3 d678e39350a2d243242a69f4e22f5192b04398f2)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/128.0.6613.127 Mobile Safari/537.36

ACRA UUID = 5e59349c-ede4-4942-91b7-199dcf1342c0

FSRS Enabled = true

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by lukstbit**
## Purpose / Description
First commit is a refactoring for the code around ForgetCardsDialog, looked verbose for what it was doing.

Second commit is an attempt to fix the linked issue. With that change when the current card's progress is reset the reviewer removes the card and changes the counts. This seems to be the behavior on desktop, at least from what I saw. I'm not sure about this, but I also don't see any issues with having that call in production.

There are no UI changes but just to be transparent:

screenshot

## Fixes
* Fixes #17079

## How Has This Been Tested?

Ran the tests, everything seems to work.

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/scheduling/ForgetCardsDialog.kt [hunk 1]
```diff
@@ -168,6 +169,7 @@ private fun AnkiActivity.forgetCards(
             )
         }
     }
+    ChangeManager.notifySubscribers(changes, null)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/scheduling/ForgetCardsDialog.kt:172]: It feels like this should use `undoableOp` instead of `withCol`.

If there's a reason this isn't happening, could you add it as a comment

**Review by david-allison — DISMISSED** [review]
Refactoring is great

One question from an unusual, but correct line of code 

Treat this as an approval if either a comment is added, or `undoableOp` is used

File: AnkiDroid/src/main/java/com/ichi2/anki/scheduling/ForgetCardsDialog.kt (hunk 1 above)
Comment (lukstbit) [reply AnkiDroid/src/main/java/com/ichi2/anki/scheduling/ForgetCardsDialog.kt]: > It feels like this should use undoableOp instead of withCol.

It should be _undoableOp_. When I thought about notifying subscribers after the call, I just jumped to using  _ChangeManager_, completely forgetting about _undoableOp_. Thanks.
