### PR TITLE
Editing notes triggers the timebox popup

### LINKED ISSUE #18374: Editing notes triggers the timebox popup
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Set the timebox limit to 1 minute.
2. Review a card and wait for 1 minute. Don't answer.
3. Edit the note and change some fields then save.
4. The timebox popup appears.

Image

### Expected behaviour

The timebox pop-up should **only** appear after answering a card (i.e. pressing again, good, etc).

### Debug info

```AnkiDroid Version = 2.20.1 (e32a82c33646807ea19623c9c88be38965bc07e6)

Backend Version = 0.1.48-anki24.11 (24.11 c47638ca36f99dd4f3b81ae82d964aec66e392e0)

Android Version = 13 (SDK 33)

ProductFlavor = play

Manufacturer = Xiaomi

Model = 23013PC75G

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; 23013PC75G Build/TKQ1.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/136.0.7103.61 Mobile Safari/537.36

ACRA UUID = 3792582f-98ac-430e-ae42-4ace0156bf29

FSRS = 1.4.3 (Enabled: true)

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

It also leads the glitchy looking keyboard behind the pop-up.

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by Aryan171**
## Purpose / Description
Previously, the timebox limit was checked whenever the updateCurrentCard function was called, which lead to unnecessary timebox reached popup, this logic has been moved to the answerCardInner function. This makes it so that the popup is only shown when a card has been answered.

## Fixes
* Fixes #18374 

## How Has This Been Tested?
Tested on an android 15 phone

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt [hunk 1]
```diff
@@ -1234,6 +1240,12 @@ open class Reviewer :
                 showSnackbar(leechMessage, Snackbar.LENGTH_SHORT)
             }
         }
+
+        // showing the timebox reached dialog if the timebox is reached
+        val timebox = withCol { timeboxReached() }
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt:1245]: This seems reasonable: the same call is made in `currentQueueState`

**Review by mikehardy — APPROVED** [review]
great stuff, thank you!

**Comment by mikehardy** [comment]
note, from a "conventional commits" standpoint, which is frequently used in combination with "semantic release" so that a release flow can be fully automated and select the correct semantic version type between major, minor, or patch release - I would clearly classify this as a "fix" and it should generate a patch release. But you tagged the commit as "feat" which would be a new feature and generate a minor version. That is not something this project enforces, but since you put it in there I thought I'd note the correction. I squashed this PR when merging so I had a chance to edit the commit message, and I switched it from feat to fix. Cheers
