### PR TITLE
Fix: Implements go back twice to exit in the whiteboard for gesture navigation

### LINKED ISSUE #20322: "Press back twice" doesn't  work on new study screen
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

Settings: General: Turn on "Press back twice to go back/exit"

Settings: New study screen: Turn on "New study screen"

Be reviewing cards using the new study screen

Use the Android back gesture (swipe from side edge of screen)

### Expected behaviour

Expected behavior: "Press back again to exit" toast should appear on the new study screen, as it still does on the deckpicker screen and the old study screen.

Currently observed behavior: A single Back gesture causes the new study screen to immediately exit to the deck picker, even when the "Press back twice" setting is enabled.

### Debug info

```text
AnkiDroid Version = 2.23.3 
Backend Version = 0.1.62-anki25.09.2   
Android Version = 12 (SDK 31)  
ProductFlavor = play
```

### (Optional) Anything else you want to share?

This feature is useful to prevent accidentally exiting a study session when using the whiteboard, as a whiteboard stroke that accidentally starts from too close to the screen edge can be interpreted as the Android "back" gesture.

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by ShaanNarendran**
> [!NOTE]
> Tested out Opus 4.6 with code generation, still wrote all the code manually and tested everything physically

## Purpose / Description
Currently, the double tap/swipe to back option doesn't work properly in the whiteboard and a single gesture/back press exits. This was a pain point for users who were using the whiteboard for language like Japanese.
Currently, this doesn't detect gestures since it involved an external API and I wasn't very sure of how that worked so didn't want to include it here.

## Fixes
* Fixes #20322 

## Approach
Implements a new doubleBackPressCallback function which intercepts back presses when the whiteboard is enabled. If the user presses back once, a snackbar is shown. If they press back again within 2 seconds, the activity finishes. If they don't, shouldReEnable checks whether the whiteboard is still active.

## How Has This Been Tested?

[Screen_recording_20260420_121417.webm](https://github.com/user-attachments/assets/34e2bb23-1cff-47f2-8663-181f60c50f60)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — COMMENTED** [review]
I don't feel this handles Brayan's comment:

> If we can also check whether the system is using gestures instead of buttons for navigation, it would be even better.

I skimmed the discussion, as far as I understand it, requiring a confirmation should only occur if the Android back gesture is enabled, rather than buttons.

----

In addition, implementer's choice

Consider a commit to change the string:

```diff
- Press back again to exit
+ Go back again to exit
```

**Comment by ShaanNarendran** [comment]
> I don't feel this handles Brayan's comment:
> 
> > If we can also check whether the system is using gestures instead of buttons for navigation, it would be even better.
> 
> I skimmed the discussion, as far as I understand it, requiring a confirmation should only occur if the Android back gesture is enabled, rather than buttons.
> 

I had wanted to do this initially (https://stackoverflow.com/questions/74848618/how-to-detect-whether-gesture-navigation-or-button-navigation-is-active). But I was wondering why we wouldn't want to have the same thing for both navigation modes? I can make the change to using insets to detect gestures though, should just involve an extra function to detect gestures and then pass that to the ReEnable.
Edit: Since, Brayan designed reviewer I think it's best I follow his comments with the same, I'll push out a commit soon with both fixes ^^
Will change the string since then it would be nav agnostic, thanks for the find there!

**Comment by ShaanNarendran** [comment]
For future reference, using insets to detect navigation isn't reliable so using settings.secure is better
see: https://www.b4x.com/android/forum/threads/solved-how-to-determine-users-system-navigation-mode-back-button-or-side-swipe.159347/

File: AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt [hunk 1]
```diff
@@ -165,18 +167,26 @@ class ReviewerFragment :
     ) {
         super.onViewCreated(view, savedInstanceState)
 
+        val isGestureNavigation = {
+            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
+                Settings.Secure.getInt(requireContext().contentResolver, "navigation_mode", 0) == 2
+            } else {
+                false
+            }
+        }
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt]: Move this to the `compat` module, possibly named: `isUsingSystemGestureNavigation`

**Review by david-allison — CHANGES_REQUESTED** [review]
squash commits 1 and 2

File: AnkiDroid/src/main/java/com/ichi2/anki/android/back/ExitViaDoubleTapBackBackPressCallback.kt [hunk 2]
```diff
@@ -29,6 +29,31 @@ import com.ichi2.anki.snackbar.showSnackbar
...
+fun doubleBackPressCallback(
+    enabled: Boolean,
+    onFirstBack: () -> Unit,
+    shouldReEnable: () -> Boolean = { true },
+): OnBackPressedCallback =
+    object : OnBackPressedCallback(enabled) {
+        override fun handleOnBackPressed() {
+            onFirstBack()
+            isEnabled = false
+            HandlerUtils.executeFunctionWithDelay(Consts.SHORT_TOAST_DURATION) {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/android/back/ExitViaDoubleTapBackBackPressCallback.kt]: I'd extract this to a parameter and use `N.seconds` (I think it's 2)

File: AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt [hunk 3]
```diff
@@ -163,8 +166,25 @@ class ReviewerFragment :
     ) {
         super.onViewCreated(view, savedInstanceState)
 
+        val doubleBackCallback =
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt]: Match this method: it's a list of method calls. 

Extract this new code into a method and add it somewhere near the bottom of the list (in in whiteboard if you feel it's whiteboard specific)

----

I feel it belongs in `setupWhiteboard`, but that's arguable

File: compat/src/main/java/com/ichi2/anki/compat/NavigationCompat.kt [hunk 4]
```diff
@@ -0,0 +1,30 @@
...
+
+/**
+ * Returns `true` if the device is using gesture navigation (swipe from edges).
+ * Gesture navigation was introduced in Android 10 (API 29).
+ * On older versions, this always returns `false`.
+ */
+fun isUsingSystemGestureNavigation(context: Context): Boolean {
+    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.Q) return false
+    return Settings.Secure.getInt(context.contentResolver, "navigation_mode", 0) == 2
+}
```
Comment (david-allison) [inline compat/src/main/java/com/ichi2/anki/compat/NavigationCompat.kt]: Check how CompatHelper and CompatV%d classes work

**Review by david-allison — CHANGES_REQUESTED** [review]
Almost!

**Comment by ShaanNarendran** [comment]
hopefully I implemented the compat part correctly, please let me know if there's any issues

edit: failing tests will figure it out shortly

File: compat/src/main/java/com/ichi2/anki/compat/CompatV29.kt [hunk 5]
```diff
@@ -84,6 +85,9 @@ open class CompatV29 : CompatV26() {
         return newImageUri
     }
 
+    override fun isUsingSystemGestureNavigation(context: Context): Boolean =
+        Settings.Secure.getInt(context.contentResolver, "navigation_mode", 0) == 2
```
Comment (david-allison) [inline compat/src/main/java/com/ichi2/anki/compat/CompatV29.kt]: add a 'default' arg (passing in 0 or 2 to the method)

Make a note that this won't throw, but is manufacturer dependent

**Review by david-allison — CHANGES_REQUESTED** [review]
Almost!!

File: compat/src/main/java/com/ichi2/anki/compat/CompatV29.kt (hunk 5 above)
Comment (ShaanNarendran) [reply compat/src/main/java/com/ichi2/anki/compat/CompatV29.kt]: I completely missed this review, sorry for the late fix!

**Review by BrayanDSO — APPROVED** [review]
Looks great to me. Thanks

File: compat/src/main/java/com/ichi2/anki/compat/Compat.kt [hunk 6]
```diff
@@ -273,4 +273,21 @@ interface Compat {
...
+     *
+     * Note: this reads a `Settings.Secure` key that is not part of the public API.
+     * It will not throw, but the result is manufacturer dependent.
+     *
+     * @param default value returned by `Settings.Secure.getInt` if the key is unset
+     * @param gestureMode the value of `navigation_mode` representing gesture navigation
+     */
+    fun isUsingSystemGestureNavigation(
+        context: Context,
+        default: Int = 0,
```
Comment (david-allison) [inline compat/src/main/java/com/ichi2/anki/compat/Compat.kt]: It would be better to have the default as a Boolean

**Comment by ShaanNarendran** [comment]
flaky test I'm pretty sure

**Review by david-allison — COMMENTED** [review]
```patch
Index: compat/src/main/java/com/ichi2/anki/compat/BaseCompat.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/compat/src/main/java/com/ichi2/anki/compat/BaseCompat.kt b/compat/src/main/java/com/ichi2/anki/compat/BaseCompat.kt
--- a/compat/src/main/java/com/ichi2/anki/compat/BaseCompat.kt	(revision e911b16a595b247cf9f7842df36658270c0ae0db)
+++ b/compat/src/main/java/com/ichi2/anki/compat/BaseCompat.kt	(date 1776886772578)
@@ -289,8 +289,7 @@
     // Until API 29, gesture navigation does not exist
     override fun isUsingSystemGestureNavigation(
         context: Context,
-        default: Boolean,
-        gestureMode: Int,
+        defaultValue: Boolean,
     ): Boolean = false
 }
 
Index: compat/src/main/java/com/ichi2/anki/compat/CompatV29.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/compat/src/main/java/com/ichi2/anki/compat/CompatV29.kt b/compat/src/main/java/com/ichi2/anki/compat/CompatV29.kt
--- a/compat/src/main/java/com/ichi2/anki/compat/CompatV29.kt	(revision e911b16a595b247cf9f7842df36658270c0ae0db)
+++ b/compat/src/main/java/com/ichi2/anki/compat/CompatV29.kt	(date 1776886686118)
@@ -87,11 +87,10 @@
 
     override fun isUsingSystemGestureNavigation(
         context: Context,
-        default: Boolean,
-        gestureMode: Int,
+        defaultValue: Boolean,
     ): Boolean {
-        val defaultMode = if (default) gestureMode else 0
-        return Settings.Secure.getInt(context.contentResolver, "navigation_mode", defaultMode) == gestureMode
+        val defaultMode = if (defaultValue) 2 else 0
+        return Settings.Secure.getInt(context.contentResolver, "navigation_mode", defaultMode) == 2
     }
 
     companion object {
Index: compat/src/main/java/com/ichi2/anki/compat/Compat.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/compat/src/main/java/com/ichi2/anki/compat/Compat.kt b/compat/src/main/java/com/ichi2/anki/compat/Compat.kt
--- a/compat/src/main/java/com/ichi2/anki/compat/Compat.kt	(revision e911b16a595b247cf9f7842df36658270c0ae0db)
+++ b/compat/src/main/java/com/ichi2/anki/compat/Compat.kt	(date 1776886772584)
@@ -282,12 +282,10 @@
      * Note: this reads a `Settings.Secure` key that is not part of the public API.
      * It will not throw, but the result is manufacturer dependent.
      *
-     * @param default value returned when the `navigation_mode` key is unset
-     * @param gestureMode the value of `navigation_mode` representing gesture navigation
+     * @param defaultValue value returned when the `navigation_mode` key is unset
      */
     fun isUsingSystemGestureNavigation(
         context: Context,
-        default: Boolean = false,
-        gestureMode: Int = 2,
+        defaultValue: Boolean = false,
     ): Boolean
 }
```

Does this work (untested)

**Review by david-allison — APPROVED** [review]
