### PR TITLE
fix: no such column: _display_name

### LINKED ISSUE #15623: [Bug] no such column: `_display_name`
2.17beta6

https://ankidroid.org/acra/app/1/bug/132527/report/6eb783db-db1f-4a4d-b53c-26882c956961

```
android.database.sqlite.SQLiteException: no such column: _display_name (code 1 SQLITE_ERROR[1]): , while compiling: SELECT _display_name FROM ClipboardImageTable WHERE (id=894) ORDER BY _data
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:186)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:481)
	at android.content.ContentResolver.query(ContentResolver.java:1226)
	at android.content.ContentResolver.query(ContentResolver.java:1158)
	at android.content.ContentResolver.query(ContentResolver.java:1114)
	at com.ichi2.utils.ImportUtils$FileImporter.getFileNameFromContentProvider(SourceFile:25)
	at com.ichi2.utils.ImportUtils$FileImporter.getFileCachedCopy(SourceFile:1)
	at com.ichi2.utils.ImportUtils$FileImporter.getFileCachedCopy(SourceFile:5)
	at com.ichi2.utils.ImportUtils.getFileCachedCopy(SourceFile:1)
	at com.ichi2.anki.NoteEditor.onCollectionLoaded$lambda$11(SourceFile:48)
	at com.ichi2.anki.NoteEditor.m(SourceFile:1)
	at com.ichi2.anki.h5.onClick(SourceFile:1)
	at android.view.View.performClick(View.java:7792)
	at android.widget.TextView.performClick(TextView.java:16112)
	at com.google.android.material.button.MaterialButton.performClick(SourceFile:12)
	at android.view.View.performClickInternal(View.java:7769)
	at android.view.View.access$3800(View.java:910)
	at android.view.View$PerformClick.run(View.java:30218)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

### PR DESCRIPTION
**Pull request by javaman97**
## Fixes
* Fixes  #15623 

## Approach
The fix would be to return null if an exception is thrown

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt [hunk 1]
```diff
@@ -247,11 +247,22 @@ object ImportUtils {
...
+                    null,
+                    null
+                ).use { cursor ->
+                    if (cursor != null && cursor.moveToFirst()) {
+                        filename = cursor.getString(0)
+                        Timber.d("handleFileImport() Importing from content provider: %s", filename)
+                    }
                 }
+            } catch (e: Exception) {
+                Timber.e(e, "Error querying content provider")
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt:264]: One nitpick here - this is unexpected and serious (it would have crashed!) but we can recover.
That's our warning level, not error: https://github.com/ankidroid/Anki-Android/wiki/Code-style#log-levels

```suggestion
                Timber.w(e, "Error querying content provider")
```

```
The ERROR level should only be used when something fatal has happened, and it is not recoverable
The WARNING level should be used when something serious and unexpected happened, but you can recover
The INFORMATIVE level should be used to note something interesting to most people
The DEBUG level should be used to note what is happening on the device that could be relevant to investigate and debug unexpected behaviours.
The VERBOSE level should be used for everything else.
A DEBUG log should be inside an if (LOCAL_LOGD) block.
```

**Review by mikehardy — APPROVED** [review]
Great, thank you! One nit about warning level but that's it
This is one that fixes a crash so I want to cherry pick it to our stable branch for a release I'm attempting to pack up right now so I'm going to go ahead and commit my suggestion, then we'll merge this via a squash merge

**Comment by javaman97** [comment]
@mikehardy Thank you for merging my first contribution on Ankidroid. I would love to contribute more to enhance my learnings and Ankidroid.

**Comment by mikehardy** [comment]
Hey @javaman97 thank you for the crash fix! I know our users will appreciate it
