### PR TITLE
Fix: tapping back doesn't close keyboard 

### LINKED ISSUE #19063: Deck description: tapping back doesn't close keyboard
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Open deck description pop-up and try to edit it.
2. Tap on back (I'm using buttons).

I'm shown the confirmation message `Discard changes?` but it doesn't always happen. And in my other phone, where I have gestures enabled I'm not able to reproduce this at all.

FYI, this effectively prevents me from saving my changes if the descrip is long enough that the save button is now behind the keyboard (I can't scroll to it).

### Expected behaviour

The keyboard should close.

### Debug info

```text
AnkiDroid Version = 2.22.3 (4f2ec681da36b8307a865f05192498b8425adf0f)  
Backend Version = 0.1.60-anki25.07.5 (25.07.5 7172b2d26684c7ef9d10e249bd43dc5bf73ae00c)  
Android Version = 13 (SDK 33)  
ProductFlavor = full  
Device Info = Xiaomi | Redmi | miel | miel_in | 2201117SI | mt6781  
Webview User Agent = Mozilla/5.0 (Linux; Android 13; 2201117SI Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/139.0.7258.62 Mobile Safari/537.36  
ACRA UUID = 371ce523-2489-42fd-a18f-62f2c24510e9  
FSRS = 4.1.1 (Enabled: true)  
Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by criticalAY**
## Purpose / Description
- #19063

## Fixes
* Fixes  #19063

## Approach

- As soon as we typed a character, OnBackPressedCallback became enabled (isEnabled = true), and when swipe Back: The Android system detects the back gesture.
- The Interception: The system sees an active OnBackPressedCallback and immediately gives it top priority. The callback "intercepted" the back event before anything else could handle it.
- So here I am hiding the keyboard if its not hidden and then execute back(discard dialog command)

## How Has This Been Tested?
Google Pixel 9 API 31 (emulator)

## Learning (optional, can help others)
NA

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/utils/Keyboard.kt [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+import android.content.Context
+import android.view.View
+import android.view.inputmethod.InputMethodManager
+
+/**
+ * Hides the soft keyboard.
+ *
+ * @return `true` if the keyboard was visible before and is now hidden, `false` otherwise.
+ */
+fun View.hideKeyboard(): Boolean {
```
Comment (lukstbit) [inline AnkiDroid/src/main/java/com/ichi2/anki/utils/Keyboard.kt]: We already have an utility class containing all the keyboard related helpers: _AndroidUiUtils.kt_. Place this new utility there.

File: AnkiDroid/src/main/java/com/ichi2/anki/utils/Keyboard.kt [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+package com.ichi2.anki.utils
+
+import android.content.Context
+import android.view.View
+import android.view.inputmethod.InputMethodManager
+
+/**
+ * Hides the soft keyboard.
+ *
+ * @return `true` if the keyboard was visible before and is now hidden, `false` otherwise.
```
Comment (lukstbit) [inline AnkiDroid/src/main/java/com/ichi2/anki/utils/Keyboard.kt]: This is not correct per hideSoftInputFromWindow() documentation:

_This does not return the result of that request (i.e. whether the IME was actually hidden)_

Starting from the latest Android version users are going to have to double BACK when editing the description:

_For apps targeting Android Build.VERSION_CODES.BAKLAVA, onwards, it will always return true._
