### PR TITLE
Fix crash when importing APKG with long or emoji filenames

### LINKED ISSUE #19742: App crashes when importing APKG file with long name + emoji/unicode characters
### Description

AnkiDroid is crashing when I try to import a deck (.apkg) that has a very long filename and includes Unicode characters, Cyrillic text, and emoji.

https://ankidroid.org/acra/app/1/bug/325541/report

```
java.lang.RuntimeException: Error importing apkg file
	at a9.i.z(SourceFile:269)
	at android.support.v4.media.session.b.E(SourceFile:70)
	at O3.e4.z(SourceFile:17)
	at C5.a.f(SourceFile:9)
	at j7.E.run(SourceFile:117)
	at A7.w.run(SourceFile:384)
	at q7.j.run(SourceFile:3)
	at q7.a.run(SourceFile:90)
```

```
Failed to shorten file: AnkiDroid exported flashcards: Медицина 🏥::Първи курс::Латински език с медицински термини-20251210223714.apkg
    java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern : %8.
    	at j$.net.URLDecoder.decode(URLDecoder.java:214)
    	at j$.net.URLDecoder.decode(URLDecoder.java:142)
    	at com.ichi2.utils.ImportUtils$FileImporter.ensureValidLength(ImportUtils.kt:283)
    	at com.ichi2.utils.ImportUtils$FileImporter.handleContentProviderFile(ImportUtils.kt:239)
    	at com.ichi2.utils.ImportUtils$FileImporter.handleFileImportInternal(ImportUtils.kt:157)
    	at com.ichi2.utils.ImportUtils$FileImporter.handleFileImport(ImportUtils.kt:140)
    	at com.ichi2.utils.ImportUtils.handleFileImport(ImportUtils.kt:65)
    	at com.ichi2.anki.IntentHandler.handleFileImport(IntentHandler.kt:211)
    	at
```

### How to Reproduce

1. Create an .apkg file with a long name, for example:

```
AnkiDroid exported flashcards: Медицина 🏥::Първи курс::Латински език с медицински термини-20251210223714.apkg

``` 
2. Import this file

### Expected Result

The deck should import normally.

### PR DESCRIPTION
**Pull request by sanjaysargam**
## Purpose / Description
Importing APKG files with very long names or emoji characters was crashing because `URLDecoder.decode()` failed while shortening the filename.

## Fixes
* Fixes #19742

## Approach
Added a fallback: if filename shortening or decoding fails, we create a safe filename using a timestamp.

## How Has This Been Tested?
Tested using apkg file with long + emoji file name:
```
AnkiDroid exported flashcards: Медицина 🏥::Първи курс::Латински език с медицински термини-20251210223714.apkg
``` 

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt [hunk 1]
```diff
@@ -284,7 +284,7 @@ object ImportUtils {
                 }
             } catch (e: Exception) {
                 Timber.w(e, "Failed to shorten file: %s", fileName)
-                fileName
+                "file_${System.currentTimeMillis()}.${getExtension(fileName)}"
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt]: Is it possible to add a test?

**Review by david-allison — CHANGES_REQUESTED** [review]
Is it possible to add a test? I think the change is correct, but the code is brittle, and it's easy to add a bug here

+ I don't trust f7921c4fa530e0ff94061c2ab2ab9730d4ed48f3 to be correct with regards to `apkg`

File: AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt]: Nit (preference): rename to `validateFileName` and document

Nit (optional): Consider returning a `value object` to ensure that functions work on validated data:

Pseudocode:

```kotlin
value class ApkgFileName(val name: String)
```

File: AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt (hunk 1 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.kt]: (I'll accept a `@NeedsTest`, we should get this out in 2.23.1)

**Comment by david-allison** [comment]
Before merging: can this be tested on our lowest API device? 

I'm concerned the extension replacement code wouldn't work as expected

**Comment by sanjaysargam** [comment]
> Before merging: can this be tested on our lowest API device?
> 
> I'm concerned the extension replacement code wouldn't work as expected

Ok

**Comment by david-allison** [comment]
I've tested this on apkg/colpkg files

* API 24 => ✅
* API 36 => ✅

**Comment by sanjaysargam** [comment]
> I've tested this on apkg/colpkg files
> 
> * API 24 => ✅
> * API 36 => ✅

Thanks :heart:
