### PR TITLE
fix(media-import): handle OutOfMemoryError & refactorings

### LINKED ISSUE #19579: Catch `addMediaFile`'s `OutOfMemoryException` and inform user
See parent issue

```
java.lang.OutOfMemoryError: Failed to allocate a 178131144 byte allocation with 50331648 free bytes and 163MB until OOM, target footprint 416188144, growth limit 536870912
	at com.google.protobuf.AbstractMessageLite.toByteArray(AbstractMessageLite.java:47)
	at anki.backend.GeneratedBackend.addMediaFile(GeneratedBackend.kt:2883)
	at com.ichi2.anki.libanki.Media.addFile(Media.kt:69)
	at com.ichi2.anki.servicelayer.NoteService.importMediaToDirectory(NoteService.java:144)
	at com.ichi2.anki.NoteEditorFragment$addMediaFileToField$1.invokeSuspend$lambda$0(NoteEditorFragment.kt:2079)
	at com.ichi2.anki.CollectionManager.withCol$lambda$1(CollectionManager.kt:146)
	at com.ichi2.anki.CollectionManager$withQueue$3.invokeSuspend(CollectionManager.kt:128)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.java:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [r0{Cancelling}@e987957, Dispatchers.Main.immediate]
```

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
`Media.addFile` can OOM, as it copies the file to a byte array. This caused a crash. We now inform the user of the failure.

## Fixes
* Fixes #19579
* Issue #19578
  * We may want a low priority follow-up to improve the 'add image -> crop -> press 'done' -> dialog' to enable a 'try again' flow

## Approach
the OOM is due to copying the file into a byte array so we can recover from it

We will work around this issue later, so the main aim is to not crash

* Image/Video: Shows dialog after fragment is closed
* Paste: Shows snackbar
* API: Fails silently (as other exceptions do)

## How Has This Been Tested?
```patch
Index: libanki/src/main/java/com/ichi2/anki/libanki/Media.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/libanki/src/main/java/com/ichi2/anki/libanki/Media.kt b/libanki/src/main/java/com/ichi2/anki/libanki/Media.kt
--- a/libanki/src/main/java/com/ichi2/anki/libanki/Media.kt	(revision 272e783917b0ce7f78af308c4b2944520b050993)
+++ b/libanki/src/main/java/com/ichi2/anki/libanki/Media.kt	(date 1763906422384)
@@ -20,7 +20,6 @@
 import androidx.annotation.WorkerThread
 import anki.media.CheckMediaResponse
 import com.google.protobuf.ByteString
-import com.google.protobuf.kotlin.toByteString
 import com.ichi2.anki.libanki.Media.Companion.htmlMediaRegexps
 import com.ichi2.anki.libanki.exception.EmptyMediaException
 import com.ichi2.anki.libanki.utils.LibAnkiAlias
@@ -73,11 +72,7 @@
      */
     @LibAnkiAlias("add_file")
     @RustCleanup("use backend exception instead of EmptyMediaException")
-    fun addFile(file: File): String {
-        // fail if non-existing or empty
-        if (file.length() == 0L) throw EmptyMediaException()
-        return writeData(file.name, file.readBytes().toByteString())
-    }
+    fun addFile(file: File): String = throw OutOfMemoryError("Failed to allocate a 178131144 byte allocation with 50331648 free bytes and 163MB until OOM, target footprint 416188144, growth limit 536870912")
 
     /**
      * Write the file to the media folder, renaming if not unique

```

### Paste image 

Screenshot 2025-11-23 at 14 01 10

### Add image/video: after a user presses 'Done'
Screenshot 2025-11-23 at 14 00 51

## Learning (optional, can help others)
Handling the 'image' OOM should be done in another PR

I want a 'try again' UX, but a standard 'launchCatching' fix closes the fragment

Reminder for Reviewers: `e: Exception` does not catch `e: OutOfMemoryError`

We still have a lot of libAnki compat to do

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: libanki/src/main/java/com/ichi2/anki/libanki/Media.kt [hunk 1]
```diff
@@ -62,17 +64,40 @@ open class Media(
...
+    @LibAnkiAlias("add_file")
+    @RustCleanup("use backend exception instead of EmptyMediaException")
+    fun addFile(file: File?): String {
+        // fail if non-existing or empty
+        if (file == null || file.length() == 0L) {
             throw EmptyMediaException()
         }
-        Timber.v("dir now %s", dir)
-        return col.backend.addMediaFile(oFile.name, oFile.readBytes().toByteString())
+        return writeData(file.name, file.readBytes().toByteString())
```
Comment (mikehardy) [inline libanki/src/main/java/com/ichi2/anki/libanki/Media.kt:79]: Of course... a classic - "file" + readBytes + toByteString 

I guess the real solution is for the rust lib to take a file name vs contents then it can do it's own space-conscious add (streaming or renaming or whatever)

Obviously just not crashing is a positive step and also adding a file that can make you go OOM is probably not going to help your sync experience (or AnkiWeb health) so perhaps a limit would be useful instead of OOM-handling backstop, but ... back to just not crashing now

**Review by mikehardy — APPROVED** [review]
Solid.

File: libanki/src/main/java/com/ichi2/anki/libanki/Media.kt (hunk 1 above)
Comment (david-allison) [reply libanki/src/main/java/com/ichi2/anki/libanki/Media.kt:79]: I'm tracking a more permanent plan of action in the sub-issues here:

Opinions strongly welcomed

* https://github.com/ankidroid/Anki-Android/issues/19578

Comment (mikehardy) [reply libanki/src/main/java/com/ichi2/anki/libanki/Media.kt:79]: after finishing high priority reviews and discord I just rolled through notifications and saw the front-end/back-end stuff, no strong opinion against of course, mild opinion in favor of exposing all those constants for some sort of add-media dialog detailing failures (perhaps with a similar failure + sub-types style like you did with startup failures - the various add media pathways could bottleneck through a verifier for size, zip abuse, filename length etc and kick out a typed error if anything failed, pop a dialog for that or continue with the add if not...)
