### PR TITLE
Use new android.arch db APIs, make sqlite swappable, protect Reviewer from collection failures

### LINKED ISSUE #5072: Crash on Reviewer start - NullPointerException restoring preferences
###### Reproduction Steps

1. Open AnkiDroid to the Reviewer directly (e.g., via a notification or widget)
2. 
3. 

###### Expected Result

Reviewer starts on current card for the deck and you proceed

###### Actual Result

Crash, seemingly because onCreate() in this pathway touches the Collection during restorePreferences() (since some preferences are stored in the Collection.conf), but collection loading is async and onCollectionLoaded() hasn't been called yet

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/9964d8fb-0eab-4d4a-a0f6-403350bbbf60

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.Reviewer}: java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONObject com.ichi2.libanki.Collection.getConf()' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2632)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2698)
at android.app.ActivityThread.access$1000(ActivityThread.java:195)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1533)
at android.os.Handler.dispatchMessage(Handler.java:111)
at android.os.Looper.loop(Looper.java:207)
at android.app.ActivityThread.main(ActivityThread.java:5856)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1026)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:887)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONObject com.ichi2.libanki.Collection.getConf()' on a null object reference
at com.ichi2.anki.AbstractFlashcardViewer.restorePreferences(AbstractFlashcardViewer.java:1803)
at com.ichi2.anki.Reviewer.restorePreferences(Reviewer.java:397)
at com.ichi2.anki.AbstractFlashcardViewer.onCreate(AbstractFlashcardViewer.java:856)
at android.app.Activity.performCreate(Activity.java:6285)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2585)
```

### PR DESCRIPTION
**Pull request by mikehardy**
requery 3.21+ (we ported to it 6 months ago) implements standard
support framework interfaces, so we can swap those in for all the
requery-specific object usage, without altering semantics

Once we swap in support interfaces, we can use the framework classes
to get our handles

Once we use framework classes to get our handles, our sqlite implementation
is swappable

That allows us to swap in the default implementation (which exists in
robolectric) and now we can do unit testing even though the app is very
touch-y with the database

Finally, use this to demonstrate a test for and Fix #5072 - where the Reviewer must have gotten control before DeckPicker in an installation with a busted collection, so it was seeing nulls from getCol()

Here's the fundamental issue with loading native libraries under test:
https://github.com/robolectric/robolectric/issues/1171

### CODE REVIEW

**Comment by mikehardy** [comment]
@timrae this opens up the whole app for unit testing, and lets me easily demonstrate and fix #5072 but is also a cross-cutting change because of all the rawQuery() -> query() diff.

Other than the conversion to SQL String building in the ContentProvider, and obtaining the connection handle via the framework, it's pretty trivial though, and works in all my testing

What do you think? It may need polish but I wanted to put the first cut out so you could see the shape of it and tell me "no" quickly before I spent more time

File: AnkiDroid/src/main/java/com/ichi2/utils/Threads.java [hunk 1]
```diff
@@ -16,13 +16,16 @@
...
 
+import android.os.Build;
 import android.os.Looper;
 
 /**
  * Helper class for checking for programming errors while using threads.
  */
 public class Threads {
 
+    private static final boolean UNITTEST = Build.FINGERPRINT.equals("robolectric");
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/utils/Threads.java]: I should fix the codacy issue, but it's worth noting that this is necessary because robolectric doesn't have the same thread action that the real android.jar does

File: AnkiDroid/src/main/java/com/ichi2/libanki/DB.java [hunk 2]
```diff
@@ -310,14 +335,14 @@ public int update(String table, ContentValues values) {
     /** update must always be called via DB in order to mark the db as changed */
     public int update(String table, ContentValues values, String whereClause, String[] whereArgs) {
         mMod = true;
-        return getDatabase().update(table, values, whereClause, whereArgs);
+        return getDatabase().update(table, android.database.sqlite.SQLiteDatabase.CONFLICT_NONE, values, whereClause, whereArgs);
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/libanki/DB.java]: requery defaults to CONFLICT_NONE, so this was not a semantic change

File: AnkiDroid/src/main/java/com/ichi2/libanki/DB.java [hunk 3]
```diff
@@ -84,8 +105,12 @@ public void onCorruption(SQLiteDatabase db) {
      * Closes a previously opened database connection.
      */
     public void close() {
-        mDatabase.close();
-        Timber.d("Database %s closed = %s", mDatabase.getPath(), !mDatabase.isOpen());
+        try {
+            mDatabase.close();
+            Timber.d("Database %s closed = %s", mDatabase.getPath(), !mDatabase.isOpen());
+        } catch (Exception e) {
+            Timber.e(e, "Failed to close database");
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/libanki/DB.java]: The support framework throws an exception that requery eats, so when we move to the framework API we have to handle

File: AnkiDroid/src/main/java/com/ichi2/libanki/DB.java [hunk 4]
```diff
@@ -49,26 +54,42 @@
...
 
         mMod = false;
     }
 
+    public class SupportSQLiteOpenHelperCallback extends SupportSQLiteOpenHelper.Callback {
+        private SupportSQLiteOpenHelperCallback(int version) { super(version); }
+        public void onCreate(SupportSQLiteDatabase db) {/* do nothing */ }
+        public void onUpgrade(SupportSQLiteDatabase db, int oldVersion, int newVersion) { /* do nothing */ }
+    }
+
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/libanki/DB.java]: the framework lets you do all sorts of neat things, but we do them all in the caller instead of as a callback middle-layer between implementation and caller, so these are all no-ops for us

File: AnkiDroid/src/main/java/com/ichi2/libanki/DB.java [hunk 5]
```diff
@@ -49,26 +54,42 @@
...
      */
     public DB(String ankiFilename) {
-        mDatabase = SQLiteDatabase.openDatabase(ankiFilename, null,
-                    (SQLiteDatabase.OPEN_READWRITE | SQLiteDatabase.CREATE_IF_NECESSARY),
-                    new MyDbErrorHandler());
+
+        SupportSQLiteOpenHelper.Factory factory = new RequerySQLiteOpenHelperFactory();
+        if (Build.FINGERPRINT.equals("robolectric")) {
+            // Native-library loads (like requery) fail in unit tests, but default works
+            factory = new FrameworkSQLiteOpenHelperFactory();
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/libanki/DB.java]: Apart from switching to framework APIs, this and the threading is all we need to support unit testing even though we init the db everywhere

File: AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java [hunk 6]
```diff
@@ -222,26 +222,28 @@ public Cursor query(Uri uri, String[] projection, String selection, String[] sel
         switch (match) {
             case NOTES_V2: {
                 /* Search for notes using direct SQL query */
-                String[] proj = sanitizeNoteProjection(projection);
-                return col.getDb().getDatabase().query("notes", proj, selection, selectionArgs, null, null, order);
+                String columns = sanitizeNoteProjection(projection);
+                String orderBy = TextUtils.isEmpty(order) ? "" : " ORDER BY " + order;
+                return col.getDb().getDatabase().query("SELECT " + columns + " FROM notes WHERE " + selection + orderBy, selectionArgs);
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java]: These are the only bits I'm unsure of and the sample app (I tried it!) doesn't exercise them. The contract file documentation says they can be used, and also says they are ignored, but isn't precise about the format. I'm fairly certain these aren't correct yet.

File: AnkiDroid/src/main/java/com/ichi2/libanki/DB.java (hunk 3 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/libanki/DB.java]: And if my self-review is adding a "handle the error case" step I suppose we could put a boolean here or re-throw and then look at callers to see what they're doing and do the right thing. I didn't want to change the API and do all that without some consensus that switching to Framework APIs was okay then

**Comment by mikehardy** [comment]
Wow - I thought I was making my own comment with reply but accidentally edited yours. That's no good for attribution at all. Here's my comment attributed to me now - I will attempt to revert that bogon above

> Probably it's better to just do integration tests with the actual sqlite native library that we're using in prod rather than unit tests with whatever is bundled with roboelectric...?

I agree whole-heartedly - for anything that touches data on purpose, an instrumented test (with our to-be-deployed libraries) should be the rule. If there's some localization issue, or memory pressure issue, you'll only get it on device. To be very specific, robolectric [bundles the "282" version of com.almworks.sqlite4java artifact](https://github.com/robolectric/robolectric/blob/master/shadows/framework/build.gradle#L45) as it's implementation, [which in turn bundles sqlite 3.7.10](https://bitbucket.org/almworks/sqlite4java/wiki/ChangeLog) which [is from 2012](https://sqlite.org/chronology.html)

So I'd see someone doing a test that was using data as anything other than background noise and I'd send them to instrumented test land. I would document the same in the developer guide

The problem I'm grappling with is that since the app is so tightly bound, frequently static singleton (private even), and touch-y with the database that apart from integration tests, I feel I can't efficiently code unit tests for things like null-ness (as in #5072) or UI action, or lifecycle stuff, without the database loading everywhere as soon as I try to use an Activity under test. These things are mockable but that is discouraging as the amount of mocking (and the intricacy since we use static singletons and have to use the PowerMock hammer) is a real barrier. Avoiding that is supposed to be the point of robolectric in fact.

Further, UI testing then has to be done by Espresso (which I gave a solid try to) but UI tests like that are renowned for being brittle (which I re-learned) so I'm not able to do UI tests in a way I can propagate due to flakiness, but they would have caught a few showstopper crashes so I want a UI test alternative. That's the other robolectric strength.

So I'm motivated to use Robolectric to drive UI tests and test non-data logic, which is a reasonable stance I think, if the social proof of robolectric having official support deep in the toolchain counts. But for our app I need a way to have a base sqlite implementation so I can leave the mass of code alone vs mocking tons on each test.

Seemed that adopting the current framework API and using the framework factory pattern as this proposes was a reasonable step then, so here this blob is 

> protect Reviewer from collection disaster

That's #5072 - if the collection has suffered some disaster (unreadable, unopenable etc) DeckPicker isn't the only Activity that will confront it. Reviewer is an entry point as well, so needs some recognition that it can't trust the getCol() return and needs to handle collection disasters by doing the "go to advanced prefs with a toast" handling. And I piggy-backed on DeckPicker to do that, as AnkiActivity established it as a valid method of handling collection calamity.

**Comment by mikehardy** [comment]
I've had some success pushing updates upstream so I checked and almworks has an [upgrade in process to sqlite 3.24](https://bitbucket.org/almworks/sqlite4java/pull-requests/2/issue-88-upgrade/activity) which would have them almost current and get them past the big humps to stay current. Robolectric doesn't have a PR to move to current almworks (they're one behind) but that diff would be nearly pointless so it's not expected. I could try to PR the newer almworks into robolectric post-almworks PR, then the sqlite implementations would be mostly converged at any rate.

I would still not waver on sending data-reliant tests to instrumented regardless, but I'd feel a little less worried about implementation divergence if they all moved forward. At least right now with what I'd consider maximum divergence (given the PR in almworks - sqlite version skew should grow smaller in the future) there is empirical evidence with this PR that the APIs have no skew for us to handle when using both, so it doesn't really affect us.

**Comment by mikehardy** [comment]
I'm still very interested in this (I'd like to use it to prove my multi-select reset/reposition/reschedule undo is working for instance). 

While re-reading it today to see what else I could do I realized the error handler port to the framework APIs for corruption wasn't correct. So I added a test that failed at first (as expected), then fixed it. Worth noting that the coverage report showed it - I noticed the handler wasn't even instantiated, now it's green with coverage.

I also cleaned up code style and while the commits need re-shaping I believe it's in near final form

The only outstanding blocker I'm aware of now is the ContentProvider - I'd write a test for that against the requery API version of the ContentProvider then make sure the API port generated the same SQL

Prior to merge I'd re-shape the commits to be one commit that was a pure API port to Android framework APIs (make it swappable) with tests where needed, a second that implements the swap for robolectric testing, and a third that fixes the Reviewer bug and adds a test using the swap.

Are there any other problems you see with this PR, philosophical or technical?

File: AnkiDroid/src/main/java/com/ichi2/libanki/DB.java (hunk 4 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/libanki/DB.java]: When scanning for error-handling issues and looking at coverage I noticed that we needed to implement onCorruption here. fixed.

**Comment by mikehardy** [comment]
I just gained confidence in the CardContentProvider port to the framework APIs - it turns out requery had a copy of the framework SQLiteQueryBuilder.buildQueryString() and was using that internally. So I converted to a combination of using that and sending it into the framework query() API, which means there is now no logical change - just a move to pure framework APIs.

I have no other technical questions on this PR. It just needs commit re-shaping to be okay for me. If there's something else to do, let me know

**Comment by mikehardy** [comment]
I also just realized that I could easily evict the two special robolectric cases in mainline so the mainline change is really just a straight api swap to new framewi APIs. Then it'll be squeaky clean.

**Comment by mikehardy** [comment]
The commit history is now a royal mess but that's because I preferred to do this in the open in case there was feedback forthcoming.

I was still unsettled by the robolectric switches in the main code tree, so the last two commits I just pushed clean them out. src/main/java is now just a clean consumer of standard framework APIs, but with a requery factory, and unit tests have a RobolectricTest base class that swaps in the framework factory.

I'm going to preen the commit history next then it should be in a merge-able state.

File: AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java (hunk 6 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java]: fixed

**Comment by mikehardy** [comment]
Except for the last commit - a clean and well-ordered commit history and self-reviewed a few times now. 

I don't want to re-write the last 3 commits at the end of the day just to alter one import statement so I'll let the last commit stand but this is as good as I think I can make it now.

I'm probably going to pin the multi-select undo to this because I want to use the testing capability here, then after I learn undo I'll move back to template edits and try to apply it there

File: AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java [hunk 7]
```diff
@@ -60,7 +60,8 @@
 import java.util.Map;
 import java.util.Set;
 
-import io.requery.android.database.sqlite.SQLiteDatabase;
+import androidx.sqlite.db.SupportSQLiteDatabase;
+import io.requery.android.database.sqlite.SQLiteQueryBuilder;
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java]: except the factory, this was the only requery API left, and it was a remnant. Switched this to the framework API in the final patch

File: AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java [hunk 8]
```diff
@@ -223,7 +224,8 @@ public Cursor query(Uri uri, String[] projection, String selection, String[] sel
             case NOTES_V2: {
                 /* Search for notes using direct SQL query */
                 String[] proj = sanitizeNoteProjection(projection);
-                return col.getDb().getDatabase().query("notes", proj, selection, selectionArgs, null, null, order);
+                String sql = SQLiteQueryBuilder.buildQueryString(false, "notes", proj, selection, null, null, order, null);
+                return col.getDb().getDatabase().query(sql, selectionArgs);
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java]: the buildQueryString/query(string, string[]) calls are just a decomposition of the previous requery-specific API - those two framework API calls are what requery used under the covers, so this is not a semantic change

File: AnkiDroid/src/main/java/com/ichi2/libanki/DB.java [hunk 9]
```diff
@@ -46,34 +50,76 @@
...
-        mDatabase = SQLiteDatabase.openDatabase(ankiFilename, null,
-                    (SQLiteDatabase.OPEN_READWRITE | SQLiteDatabase.CREATE_IF_NECESSARY),
-                    new MyDbErrorHandler());
+
+        SupportSQLiteOpenHelper.Configuration configuration = SupportSQLiteOpenHelper.Configuration.builder(AnkiDroidApp.getInstance())
+                .name(ankiFilename)
+                .callback(getDBCallback())
+                .build();
+        SupportSQLiteOpenHelper helper = getSqliteOpenHelperFactory().create(configuration);
+        mDatabase = helper.getWritableDatabase();
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/libanki/DB.java]: getWritable is the equivalent of openDatabase with OPEN_READWRITE and CREATE_IF_NECESSARY specified

File: AnkiDroid/src/main/java/com/ichi2/libanki/DB.java [hunk 10]
```diff
@@ -310,14 +362,14 @@ public int update(String table, ContentValues values) {
     /** update must always be called via DB in order to mark the db as changed */
     public int update(String table, ContentValues values, String whereClause, String[] whereArgs) {
         mMod = true;
-        return getDatabase().update(table, values, whereClause, whereArgs);
+        return getDatabase().update(table, SQLiteDatabase.CONFLICT_NONE, values, whereClause, whereArgs);
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/libanki/DB.java]: CONFLICT_NONE was the default in the requery-specific API, passed into the framework API calls under the requery implementation, so this is not a semantic change

**Comment by mikehardy** [comment]
@timrae I just self-reviewed this again before bugging you, to see if there was anything glaring. I don't see anything and I think it's ready to go - looking at the first commit as a vertical diff is the clearest way to see the API switch. The second commit may have a philosophical hang up for you - we'll see? Then after that it's a standard crash fix (I think)

**Comment by timrae** [comment]
The crash fix itself is kind of trivial, I can accept it straight away, but the change to the content provider needs some verification, and life has been crazy recently. Maybe you wanna separate it out into its own PR

**Comment by tico-tico** [comment]
@mikehardy  Out of curiosity, why does Ankidroid use DELETE mode for sqlite transactions? I got the impression that WAL-mode is significantly faster with the same reliability.

**Comment by mikehardy** [comment]
> the change to the content provider needs some verification

agreed! I was concerned as well, and attempted to be very thorough in that area. Luckily the ContentProviderTest is one of the best tests in our codebase and it was easy to trigger failure there by adding little bugs on purpose to make sure it wasn't fake coverage - you can see the coverage on a local run here:

20181115_cardcontentprovider query_coverage

And here is one point where it is exercising that area so you can see the assertions etc: https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/ContentProviderTest.java#L269

I certainly understand you're busy and I've already followed the competing implementations through for visual inspection to justify the new implementation as well, here's a click trail that follows basically how I examined the previous implementation vs the new one:

We use to call this:
https://github.com/requery/sqlite-android/blob/master/sqlite-android/src/main/java/io/requery/android/database/sqlite/SQLiteDatabase.java#L1254

Which chains through to this while padding out the argument list with default values (false for distinct, null for limit):
https://github.com/requery/sqlite-android/blob/master/sqlite-android/src/main/java/io/requery/android/database/sqlite/SQLiteDatabase.java#L1087

Then internally chains through again (padding out with nulls) to this:
https://github.com/requery/sqlite-android/blob/master/sqlite-android/src/main/java/io/requery/android/database/sqlite/SQLiteDatabase.java#L1216

That last one is where internally they call SQLiteQueryBuilder, and the requery vs framework APIs are the same implementation - they yield the same SQL for the same inputs.

Here's the requery SQLiteQueryBuilder:
https://github.com/requery/sqlite-android/blob/master/sqlite-android/src/main/java/io/requery/android/database/sqlite/SQLiteQueryBuilder.java#L202
And here's the framework where you can see that method is identical:
https://github.com/aosp-mirror/platform_frameworks_base/blob/master/core/java/android/database/sqlite/SQLiteQueryBuilder.java#L205

requery copied the original implementation as you can see in the header:
https://github.com/aosp-mirror/platform_frameworks_base/blob/master/core/java/android/database/sqlite/SQLiteQueryBuilder.java#L205

At that point, they just execute the SQL, and in that requery vs framework are also the same - so switching it from a call that wrapped SQLiteQueryBuilder then executed the query, to a pair that calls an identical SQLiteQueryBuilder with identical args, then executes the query seems okay.

Apart from coverage of the affected area and inspection of the before / after implementations I'm not sure how else to verify but I don't want to break clients either of course. If there's any other way to verify I'll do it.

**Comment by mikehardy** [comment]
@tico-tico I think it has something to do with this: https://github.com/ankidroid/Anki-Android/issues?utf8=%E2%9C%93&q=is%3Aissue+sort%3Aupdated-desc+WAL

Maybe most specifically this: https://github.com/ankidroid/Anki-Android/issues/2696#issuecomment-125536068

So, compatibility with AnkiDesktop is my take on it.

**Comment by tico-tico** [comment]
Yes, I saw those issues but I though they are irrelevant since you switched to up-to-date sqlite library and don't depend on outdated system libs.

AnkiDesktop? Do you mean someone's exchanging PC Anki's and Ankidroid's data copying files in sqlite format? Wow, never thought about such possibility. Will try one day instead of cloud-sync.

Thanks for the answer.

**Comment by tico-tico** [comment]
Just checked, Anki itself uses WAL-mode. At least version 2.0.52 on Win.
Sorry for spamming here, btw. :cat2:

**Comment by mikehardy** [comment]
Whereas yes during operation the Collection appears to be opened with no argument specified for sync (thus making it true) so it gets wal:
https://github.com/dae/anki/blame/master/anki/storage.py#L35

On connection close it appears to finish by setting it to delete:
https://github.com/dae/anki/blob/master/anki/collection.py#L191

I put the blame version of the file up there so you could see the desktop code hasn't changed for six years, while a great deal of effort was expended in AnkiDroid about 3 years ago to handle database corruption - including using requery, removing WAL preference, adding corruption handlers etc:
https://github.com/ankidroid/Anki-Android/blame/13c27a6a1fa8465cc6656c67bd9db25afc7a51fa/AnkiDroid/src/main/java/com/ichi2/libanki/DB.java#L73

I wasn't aware AnkiDroid existed at the time :-), so I'm not qualified to say exactly what was going on, but I'm going to say since anki desktop hasn't moved in this area for a while, and AnkiDroid (while under heavy development) did make a change that seems to have worked well in the interim, there's good reason to leave that alone

**Comment by mikehardy** [comment]
@timrae I totally understand crazy life, but if you want to check my content provider verification, I do think it's a defensible change, and then maybe this can merge? https://github.com/ankidroid/Anki-Android/pull/5103#issuecomment-439130655

If so, it will unlock the PR that also fixes your v2.9 "fresh install treated as an upgrade" issue

**Comment by timrae** [comment]
OK I just skimmed over it and nothing stood out, gonna have to trust you on this one

**Comment by mikehardy** [comment]
> gonna have to trust you on this one

Hopefully that trust is rewarded, either way I promise I'll fix anything that comes up. Fingers crossed
