### PR TITLE
NF: clean study options nulls

### LINKED ISSUE #13869: NullPointerException in StudyOptionsFragment
https://ankidroid.org/acra/app/1/bug/47783/report/9663b7de-873b-436c-acad-b100aa7aee4b

```
java.lang.NullPointerException
	at com.ichi2.anki.StudyOptionsFragment.rebuildUi(StudyOptionsFragment.kt:41)
	at com.ichi2.anki.StudyOptionsFragment.access$rebuildUi(StudyOptionsFragment.kt:1)
	at com.ichi2.anki.StudyOptionsFragment$refreshInterface$1.invokeSuspend(StudyOptionsFragment.kt:51)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:119)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

Probably related with a warning at end of logcat
```

05-15 03:07:04.280 I/AnkiDroid( 2365): Starting Migrate User Data Service
05-15 03:07:04.291 I/AnkiDroid( 2365): No startup screens required
05-15 03:07:04.291 W/AnkiDroid( 2365): ActivityThread/ onStartCommand(Intent { cmp=com.ichi2.anki/.services.MigrationService }, ...)
05-15 03:07:04.294 W/AnkiDroid( 2365): BackupManager$Companion/ Collection is already open during backup... we probably shouldn't be doing this
05-15 03:07:04.294 I/AnkiDroid( 2365): Launching new thread to backup /storage/emulated/0/Android/data/com.ichi2.anki/files/AnkiDroid1/collection.anki2 to /storage/emulated/0/Android/data/com.ichi2.anki/files/AnkiDroid1/backup/collection-2023-05-15-03-07.colpkg
05-15 03:07:04.295 I/AnkiDroid( 2365): Starting Migrate User Data Service
05-15 03:07:04.298 I/AnkiDroid( 2365): Updating deck list UI
05-15 03:07:04.355 W/AnkiDroid( 2365): ActivityThread/ onStartCommand(Intent { cmp=com.ichi2.anki/.services.MigrationService }, ...)
05-15 03:07:04.355 W/AnkiDroid( 2365): ActivityThread/ MigrationService.onStartCommand has been called twice
05-15 03:07:04.377 I/AnkiDroid( 2365): Updating deck list UI
05-15 03:07:04.507 I/AnkiDroid( 2365): Backup created successfully
```

### PR DESCRIPTION
**Pull request by RobozinhoD**
## Purpose / Description
#13869 was a null pointer exception on rebuildUi method, so I cleaned some nulls

## Fixes
I don't know #13869 will be fixed by this PR, but cleaning is always good

## Approach
#13869 was a null pointer exception on rebuildUi method, so I cleaned some nulls

## How Has This Been Tested?

I don't know how to test this

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
I'm sorry @RobozinhoD but I'm not convinced by this PR.
`lateinit` usually means that this will be initialized during initialization. The trouble is that `onCreateView` may have an early return, when `container` is null. So there are valid cases where those variables are null.

However, either all of those values are null or none are null. So what I'd suggest to make this cleaner is to have a single class which contains all of those variables. I'd suggest creating a data class that contains all of those variables.
This way, you have a single point that is marked as nullabel, and it'sll also be easier to check whether its nullability is as expected.

File: AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt [hunk 1]
```diff
@@ -595,10 +595,12 @@ class StudyOptionsFragment : Fragment(), Toolbar.OnMenuItemClickListener {
                 return
             }
 
+            val col = col ?: return
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt:598]: Nope. We certainly do not want an early return. If `col` is null, we surely want a crash; something went wrong. We don't want to have a stale UI.
The good thing with a crash being we get crash report, we know we have something to investigate

File: AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt [hunk 2]
```diff
@@ -690,8 +690,9 @@ class StudyOptionsFragment : Fragment(), Toolbar.OnMenuItemClickListener {
                             textNewTotal.post(setNewTotalText)
                         }
                     }
+                }.also {
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt:693]: `.apply` instead of `.also`. It would allow to remove the `it`.
Actally, you may even be able to do something such as `.apply(::start)` (not sure of the syntax

**Review by Arthur-Milchior — DISMISSED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt [hunk 3]
```diff
@@ -147,10 +147,6 @@ class StudyOptionsFragment : Fragment(), Toolbar.OnMenuItemClickListener {
 
     override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
         Timber.i("onCreateView()")
-        if (container == null) {
-            // Currently in a layout without a container, so no reason to create our view.
-            return null
-        }
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt:153]: I'm sorry, but I'll need more explanations in the commit message. I admit that your current message makes it not clear to me whether:
* `container == null` is something that can never occur, so there was no need to test it.
* `container == null` is something that can occur; but actually we want to inflate it anyway. And in particular, what's the point of inflating this view if it not contained in anything.

Personally, I honestly have no idea which of those two cases we are in.

Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt:153]: by the commit comment, I assume that is the second case

**Review by BrayanDSO — APPROVED** [review]
PR ended up being only cleanups, so I changed the title and the description to avoid closing the related issue as we aren’t sure that this will fix it. Haven’t seen any problems with the cleanups, so I’m approving.
