### PR TITLE
[Bug Fix] handled JSONException in cardTemplateEditor

### LINKED ISSUE #8822: Crash 2.15.0beta1 CardTemplateEditor$CardTemplateFragment.getCurrentTemplate
###### Reproduction Steps

Unfortunately nothing in the logcat on this report, so it will have to be deduced from the crash trace working backwards

This was seen on 2.15alpha48 but I don't remember this code changing before beta, it should still be a valid issue

###### Expected Result

Never crashes ever

###### Actual Result

```
com.ichi2.utils.JSONException: org.json.JSONException: Index 2 out of range [0..2)
at com.ichi2.utils.JSONArray.get(JSONArray.java:2)
at org.json.JSONArray.getJSONObject(JSONArray.java:523)
at com.ichi2.utils.JSONArray.getJSONObject(JSONArray.java:2)
at com.ichi2.anki.CardTemplateEditor$CardTemplateFragment.getCurrentTemplate(CardTemplateEditor.java:2)
at com.ichi2.anki.CardTemplateEditor$CardTemplateFragment.onCreateOptionsMenu(CardTemplateEditor.java:7)
at androidx.fragment.app.Fragment.performCreateOptionsMenu(Fragment.java:3)
at androidx.fragment.app.FragmentManager.dispatchCreateOptionsMenu(FragmentManager.java:3)
at androidx.fragment.app.FragmentController.dispatchCreateOptionsMenu(FragmentController.java:1)
at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:2)
at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:1)
at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2)
at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:1)
at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:5)
at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:1)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
at android.view.Choreographer.doCallbacks(Choreographer.java:809)
at android.view.Choreographer.doFrame(Choreographer.java:740)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:246)
at android.app.ActivityThread.main(ActivityThread.java:8512)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

###### Debug info

```
-- | --
ANDROID_VERSION | 11
APP_VERSION_CODE | 321500148
APP_VERSION_NAME | 2.15alpha48
AVAILABLE_MEM_SIZE | 182676721664
BRAND | samsung
BUILD | BOARDexynos9820BOOTLOADERG977NKSU4FUCDBRANDsamsungCPU_ABIarm64-v8aCPU_ABI2DEVICEbeyondx | BOARD | exynos9820 | BOOTLOADER | G977NKSU4FUCD | BRAND | samsung | CPU_ABI | arm64-v8a | CPU_ABI2 |   | DEVICE | beyondx
BOARD | exynos9820
BOOTLOADER | G977NKSU4FUCD
BRAND | samsung
CPU_ABI | arm64-v8a
CPU_ABI2 |  
DEVICE | beyondx
```
###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by Akshay0701**
## Fixes
Fixes #8822 

the crash was occurring at getCurrentTemplate method when the program tried to fetch from index value getter than its json size 

## Output
In the below video, I intentionally tried to fetch from index getter than its size, and its works without crashes

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java [hunk 1]
```diff
@@ -633,10 +638,15 @@ private void launchCardBrowserAppearance(JSONObject currentTemplate) {
...
 
-        @CheckResult @NonNull
+        @CheckResult
         private JSONObject getCurrentTemplate() {
             int currentCardTemplateIndex = getCurrentCardTemplateIndex();
-            return mTemplateEditor.getTempModel().getModel().getJSONArray("tmpls").getJSONObject(currentCardTemplateIndex);
+            try {
+                return mTemplateEditor.getTempModel().getModel().getJSONArray("tmpls").getJSONObject(currentCardTemplateIndex);
+            } catch (JSONException e) {
+                Timber.d(e, "Exception loading template in CardTemplateFragment. Probably stale fragment.");
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java:647]: Interesting - this will stop the crash, but were you able to reproduce it? The magic of crash fixing is trying to imagine enough ways to reproduce it that you do in fact find the one, then fix the underlying cause. There should not be stale fragments should there?

Sometimes that's not possible - and just stopping the crash is good - but I'd really like to know if this was reproducible first or not - there was a comment on the related issue that made it seem like yes, you did reproduce?

**Review by mikehardy — APPROVED** [review]
Code looks good - approving in general - just a question about reproduction

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java (hunk 1 above)
Comment (Akshay0701) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java:647]: > There should not be stale fragments should there?

can you please tell me what should I put in Timber.d?

> you did reproduce?

At very first, I was unable to reproduce the crash, I tried each and every other way like adding new cards deleting and saving, pausing/resuming activity, and doing it all in the mix, at one endpoint I able to reproduce it and after doing debugging I found there is actual 2 size and program trying to access 3 (i got to know about the actual cause of the crash but to be honest I still don't understand why program tried to accessed 3 instead of 2), then I resolved this issue.

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java:647]: Fair enough - the CardTemplateEditor is difficult to make crash at this point (a good thing!) when initially switching it to the memory model it crashed all the time but by the end I was only able to make it crash using robolectric to auto-do things.

I would say it is a Timber.w (warn) since it is a real error (that moves it past info) but we can recover (that keeps it at warn vs error).

In the message you should put everything useful to maybe diagnose, that is, I think the exception will already have the real count and incorrect index, you might log the actual location (for example `CardTemplateEditor::<method name?> - <what we were trying to do>`) ?

Comment (Akshay0701) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java:647]: Timber.w(e, "CardTemplateEditor::getCurrentTemplate - fetching from index getter than its current json size");

let me know if this is correct?

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java:647]: I think the exception will hold the information from the second part, you are *assuming* that's why the exception happened. The error message should say what you were trying to do, not what you think the exception is.

More something like 

`Timber.w(e, "CardTemplateEditor::getCurrentTemplate - unexpectedly unable to fetch template? %d", currentCardTemplateIndex);`

Now you are logging the only things we are really sure of - where we are, what we attempted, with the data we know we attempted. The rest is in the exception, and no assumptions about behavior or runtime state are made in the message

Comment (Akshay0701) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java]: Thank You!

**Review by mikehardy — APPROVED** [review]
Looks good now - I verified with the change to maybe returning null that all callers of `getCurrentTemplate` were also modified :+1:
