### PR TITLE
Fix:8142 Adding Webview information to crash report

### LINKED ISSUE #8142: Add Webview information to crash report
As an aside in our crash report we should probably report the webview in use and it's version, I think recent webview updates for the Chrome subsystem are why this is showing up now but I'm not 100%, and regardless we don't have the version info that would tell us.

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/issues/7369#issuecomment-791517910_

### PR DESCRIPTION
**Pull request by kartikeysaran**
## Purpose / Description
Added webview information to ACRA crash reports with the help of package manager

## Fixes
Fixes #8142 

## Approach
Adding a custom field to ACRA report which send the Webview version name and code with the help of Package Manager

## How Has This Been Tested?

This has been tested locally

## Learning (optional, can help others)
Adding custom field to ACRA reports

https://stackoverflow.com/questions/34338262/acra-sending-a-custom-data-reportfield

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by kartikeysaran** [comment]
@mikehardy I have closed the previour pr linked to the issue #8225 due to some wrong commits previously , I was using UserAgent String to fetch Webview Information but that was not handy as we need to pass a Webview parameter to that to fetch the data and we need to include the Webview information to ACRA crash report so for that i have used Package manager .

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 1]
```diff
@@ -709,4 +713,24 @@ protected void log(int priority, String tag, @NonNull String message, Throwable
...
+            PackageManager packageManager = getPackageManager();
+            PackageInfo pi;
+            if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.O) {
+                pi = WebView.getCurrentWebViewPackage();
+                webViewInfo = "Webview version name - "+pi.versionName+" , version Code - "+pi.versionCode;
+                return webViewInfo;
+            } else {
+                pi = packageManager.getPackageInfo("com.google.android.webview", 0);
+                webViewInfo = "Webview version name - "+pi.versionName+" , version Code - "+pi.versionCode;
+                return webViewInfo;
```
Comment (4shutosh) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:729]: Common statements can be extracted from the if-else.

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 2]
```diff
@@ -709,4 +713,24 @@ protected void log(int priority, String tag, @NonNull String message, Throwable
...
 
+    @NonNull
+    private String fetchWebViewInformation () {
+        String webViewInfo;
+        try {
+            PackageManager packageManager = getPackageManager();
+            PackageInfo pi;
+            if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.O) {
+                pi = WebView.getCurrentWebViewPackage();
+                webViewInfo = "Webview version name - "+pi.versionName+" , version Code - "+pi.versionCode;
```
Comment (4shutosh) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:724]: Fix code formatting. 
Add proper spaces before and after symbols.

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 3]
```diff
@@ -709,4 +713,24 @@ protected void log(int priority, String tag, @NonNull String message, Throwable
...
+            PackageInfo pi;
+            if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.O) {
+                pi = WebView.getCurrentWebViewPackage();
+                webViewInfo = "Webview version name - " + pi.versionName + " , version Code - " + pi.versionCode ;
+                return webViewInfo;
+            } else {
+                pi = packageManager.getPackageInfo("com.google.android.webview", 0);
+                webViewInfo = "Webview version name - " + pi.versionName + " , version Code - " + pi.versionCode ;
+                return webViewInfo;
+            }
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:730]:
```suggestion
            if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.O) {
                pi = WebView.getCurrentWebViewPackage();
            } else {
                pi = packageManager.getPackageInfo("com.google.android.webview", 0);
            }
            return "Webview version name - " + pi.versionName + " , version Code - " + pi.versionCode ;
```

**Review by mikehardy — CHANGES_REQUESTED** [review]
@4shutosh is correct in this case @kartikeysaran - I made a suggestion based on that and I think it's a lot cleaner? What do you think?

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
Also got a test failure:

```
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:724: warning: [deprecation] versionCode in PackageInfo has been deprecated

                webViewInfo = "Webview version name - " + pi.versionName + " , version Code - " + pi.versionCode ;
> Task :AnkiDroid:compileDebugJavaWithJavac
                                                                                                    ^
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:728: warning: [deprecation] versionCode in PackageInfo has been deprecated
                webViewInfo = "Webview version name - " + pi.versionName + " , version Code - " + pi.versionCode ;
                                                                                                    ^
```

**Comment by kartikeysaran** [comment]
> Also got a CI failure:
> 
> ```
> /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:724: warning: [deprecation] versionCode in PackageInfo has been deprecated
> 
>                 webViewInfo = "Webview version name - " + pi.versionName + " , version Code - " + pi.versionCode ;
> > Task :AnkiDroid:compileDebugJavaWithJavac
>                                                                                                     ^
> /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:728: warning: [deprecation] versionCode in PackageInfo has been deprecated
>                 webViewInfo = "Webview version name - " + pi.versionName + " , version Code - " + pi.versionCode ;
>                                                                                                     ^
> ```
> 
> Use [PackageInfoCompat.getLongVersionCode](https://developer.android.com/reference/androidx/core/content/pm/PackageInfoCompat)

Will update the code

**Comment by kartikeysaran** [comment]
> @4shutosh is correct in this case @kartikeysaran - I made a suggestion based on that and I think it's a lot cleaner? What do you think?

Yeah it is more clean now , have pushed the code

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 4]
```diff
@@ -228,6 +232,7 @@ public CoreConfigurationBuilder getAcraCoreConfigBuilder() {
     private void setAcraConfigBuilder(CoreConfigurationBuilder acraCoreConfigBuilder) {
         this.acraCoreConfigBuilder = acraCoreConfigBuilder;
         ACRA.init(this, acraCoreConfigBuilder);
+        ACRA.getErrorReporter().putCustomData("WEBVIEW_INFORMATION",fetchWebViewInformation());
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:235]: We'd make this data machine-readable if we had two fields: `WEBVIEW_VER_NAME` and `WEBVIEW_VER_CODE`.

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 5]
```diff
@@ -709,4 +714,21 @@ protected void log(int priority, String tag, @NonNull String message, Throwable
         }
     }
 
+    @NonNull
+    private String fetchWebViewInformation () {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:718]:
```suggestion
    private String fetchWebViewInformation() {
```

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java (hunk 4 above)
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:235]:
```suggestion
        ACRA.getErrorReporter().putCustomData("WEBVIEW_INFORMATION", fetchWebViewInformation());
```

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 6]
```diff
@@ -709,4 +714,21 @@ protected void log(int priority, String tag, @NonNull String message, Throwable
...
+            PackageManager packageManager = getPackageManager();
+            PackageInfo pi;
+            if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.O) {
+                pi = WebView.getCurrentWebViewPackage();
+            } else {
+                pi = packageManager.getPackageInfo("com.google.android.webview", 0);
+            }
+            return "Webview version name - " + pi.versionName + " , version Code - " + PackageInfoCompat.getLongVersionCode(pi) ;
+        } catch (Throwable e) {
+            return e.getMessage();
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:730]: I don't think we want the full stack trace here.

We definitely want a `Timber.w`

We likely can't send a crash report here, as we're in the ACRA setup

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 7]
```diff
@@ -709,4 +714,21 @@ protected void log(int priority, String tag, @NonNull String message, Throwable
...
+        String webViewInfo;
+        try {
+            PackageManager packageManager = getPackageManager();
+            PackageInfo pi;
+            if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.O) {
+                pi = WebView.getCurrentWebViewPackage();
+            } else {
+                pi = packageManager.getPackageInfo("com.google.android.webview", 0);
+            }
+            return "Webview version name - " + pi.versionName + " , version Code - " + PackageInfoCompat.getLongVersionCode(pi) ;
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:728]:
```suggestion
            return "Webview version name - " + pi.versionName + " , version Code - " + PackageInfoCompat.getLongVersionCode(pi);
```

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
Thanks!! Almost there

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
Lint error:

```
  /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:724: Error: Consider using WebViewCompat.getCurrentWebViewPackage instead which will support more devices. [WebViewApiAvailability]
                  pi = WebView.getCurrentWebViewPackage();
```

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 8]
```diff
@@ -715,20 +719,17 @@ protected void log(int priority, String tag, @NonNull String message, Throwable
...
             PackageManager packageManager = getPackageManager();
-            PackageInfo pi;
-            if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.O) {
-                pi = WebView.getCurrentWebViewPackage();
-            } else {
-                pi = packageManager.getPackageInfo("com.google.android.webview", 0);
-            }
-            return "Webview version name - " + pi.versionName + " , version Code - " + PackageInfoCompat.getLongVersionCode(pi);
+            PackageInfo pi = WebViewCompat.getCurrentWebViewPackage(this);
+            webViewInfo.add(0,pi.versionName);
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:727]:
```suggestion
            webViewInfo.add(0, pi.versionName);
```

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 9]
```diff
@@ -715,20 +719,17 @@ protected void log(int priority, String tag, @NonNull String message, Throwable
...
+            webViewInfo.add(1,String.valueOf(PackageInfoCompat.getLongVersionCode(pi)));
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:728]:
```suggestion
            webViewInfo.add(1, String.valueOf(PackageInfoCompat.getLongVersionCode(pi)));
```

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 10]
```diff
@@ -715,20 +719,17 @@ protected void log(int priority, String tag, @NonNull String message, Throwable
...
         } catch (Throwable e) {
-            return e.getMessage();
+            Timber.w( e );
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:730]:
```suggestion
            Timber.w(e);
```

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 11]
```diff
@@ -232,7 +235,8 @@ public CoreConfigurationBuilder getAcraCoreConfigBuilder() {
     private void setAcraConfigBuilder(CoreConfigurationBuilder acraCoreConfigBuilder) {
         this.acraCoreConfigBuilder = acraCoreConfigBuilder;
         ACRA.init(this, acraCoreConfigBuilder);
-        ACRA.getErrorReporter().putCustomData("WEBVIEW_INFORMATION", fetchWebViewInformation());
+        ACRA.getErrorReporter().putCustomData("WEBVIEW_VER_NAME", fetchWebViewInformation().get(0));
+        ACRA.getErrorReporter().putCustomData("WEBVIEW_VER_CODE", fetchWebViewInformation().get(1));
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:239]: You'd be better with two functions, returning a class or setting default values. 

This will crash if an exception is thrown

**Review by david-allison-1 — CHANGES_REQUESTED** [review]

**Comment by kartikeysaran** [comment]
@david-allison-1 @mikehardy Sorry for not following the code format will take care of it in future

**Comment by david-allison-1** [comment]
> @david-allison-1 @mikehardy Sorry for not following the code format will take care of it in future

No worries! We'll later want to move to a point where this is automated

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java (hunk 11 above)
Comment (kartikeysaran) [reply AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java]: rather than creating two separate functions i have used hashmaps that would work even when if there is an exception

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 12]
```diff
@@ -709,4 +719,20 @@ protected void log(int priority, String tag, @NonNull String message, Throwable
...
+    private HashMap<String, String> fetchWebViewInformation() {
+        HashMap<String, String> webViewInfo = new HashMap<>();
+        try {
+            PackageManager packageManager = getPackageManager();
+            PackageInfo pi = WebViewCompat.getCurrentWebViewPackage(this);
+            webViewInfo.put("WEBVIEW_VER_NAME", pi.versionName);
+            webViewInfo.put("WEBVIEW_VER_CODE", String.valueOf(PackageInfoCompat.getLongVersionCode(pi)));
+        } catch (Throwable e) {
+            Timber.w(e);
+            webViewInfo.put("WEBVIEW_VER_NAME", "");
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:732]: Set these before the catch while creating the `HashMap`. If `PackageInfoCompat.getLongVersionCode(pi)` fails, then this would remove the value of `pi.versionName`

Comment (kartikeysaran) [reply AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:732]: Okay

**Review by david-allison-1 — APPROVED** [review]
Looks good to me, thanks

Note to maintainers: squash & merge

**Comment by david-allison-1** [comment]
Actually... could you confirm that this works on our test ACRA instance: 

https://918f7f55-f238-436c-b34f-c8b5f1331fe5-bluemix.cloudant.com/acralyzer/_design/acralyzer/index.html#/reports-browser/

**Comment by kartikeysaran** [comment]
> Actually... could you confirm that this works on our test ACRA instance:
> 
> https://918f7f55-f238-436c-b34f-c8b5f1331fe5-bluemix.cloudant.com/acralyzer/_design/acralyzer/index.html#/reports-browser/

Yes it does ! :) , send a crash report recently with webview information

**Review by david-allison-1 — APPROVED** [review]
Looks good to me then!

**Review by mikehardy — APPROVED** [review]
nice!
