### PR TITLE
Showing Badge for Blank Card Fronts in Previewer

### LINKED ISSUE #18107: In note editor's preview, let the user know which cards are empty
Please don't start working on this issue until another maintainer approved the change I request. Everybody else is welcome to comment as I'd be interested to know whether other people want the feature I'm requesting

How to reproduce: 
* open the add card/note editor
* optional: tap some content. Enough to have some cards displayed and some cards empty
* tap the eye to open the previewer

What I'd like is that the cards that are empty have a distinct style. For example striking their name. 
The use case is that when I want to preview my cards, I want to be able to easily check the cards that will actually be generated. Knowing which ones are empty and which are not would ensure that I don't have to tap on all of them

### PR DESCRIPTION
**Pull request by ericli3690**
## Purpose / Description
There is currently no way of telling at a glance whether a card's front is blank via the previewer screen for a card (found by navigating to the Add Note editor and then pressing the eye in the top right corner).

## Fixes
* Fixes #18107

## Approach
I could not find a way to determine if a card was empty directly from the previewer fragment screen's arguments. It seems code for checking whether a card's front is empty is located in the main Anki repository rather than AnkiDroid. See [here](https://github.com/ankitects/anki/blob/d52889f45c3f7999a45fd2dde367f79f3bc3bad4/ftl/core/card-template-rendering.ftl#L4) and [here](https://github.com/ankitects/anki/blob/d52889f45c3f7999a45fd2dde367f79f3bc3bad4/rslib/src/notetype/mod.rs#L410) in particular, if I am not mistaken. As such, the approach taken here is to check whether the HTML the Anki code injects the "question" side of the card is present, and if so, that information is stored on the ViewModel. The Page fragment reads this ViewModel field and displays a red warning badge as suggested by @BrayanDSO in #18107.

An image of the updated UI is below.

UIChangeImage

## How Has This Been Tested?
An obvious rejoinder would be that if Anki changes how it displays empty card fronts, then this code may break. I have written a unit test in TemplatePreviewerViewModelTest that will fail if this happens. Of course, if a better solution is possible than simply checking if the error HTML is present, we should refactor this change. I must confess to being slightly unknowledgeable about how to retrieve card contents optimally.

The main example I tested the code on is if an optionally-reversed note does not have its reverse card enabled.

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

This is my first PR in this repository. Apologies in advance for any mistakes I might have accidentally overlooked.

### CODE REVIEW

**Review by criticalAY — COMMENTED** [review]
The badge seems to be off, can we shift to the right top corner instead it appear to be in middle right now

File: AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerViewModel.kt [hunk 1]
```diff
@@ -105,9 +110,34 @@ class TemplatePreviewerViewModel(
...
+                                .ephemeralCard(
+                                    col = this,
+                                    ord = index,
+                                    customNoteType = notetype,
+                                    fillEmpty = fillEmpty,
+                                    deckId = arguments.deckId,
+                                ).question(
+                                    this,
+                                ).contains(
+                                    "<div>The front of this card is blank.<br><a href='https://docs.ankiweb.net/templates/errors.html#front-of-card-is-blank'>More information</a></div>",
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerViewModel.kt:136]: Doesn't work in other languages. 

And I prefer adding a method to the backend for checking this instead of hacking it.

File: AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerPage.kt [hunk 2]
```diff
@@ -55,8 +55,18 @@ class TemplatePreviewerPage : Fragment(R.layout.template_previewer_container) {
...
-                tabLayout.addTab(tabLayout.newTab().setText(templateName))
+            for ((index, templateName) in viewModel.getTemplateNames().withIndex()) {
+                val newTab = tabLayout.newTab()
+                newTab.setText(templateName)
+                viewModel.cardsWithEmptyFronts?.let { list ->
+                    if (list.await()[index]) {
+                        val badge = newTab.getOrCreateBadge()
+                        badge.text = "!"
+                        // offset vertically a bit to prevent it from overlapping with the tab title
+                        badge.verticalOffset = 2
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerPage.kt:66]: not necessary

File: AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerPage.kt [hunk 3]
```diff
@@ -55,8 +55,18 @@ class TemplatePreviewerPage : Fragment(R.layout.template_previewer_container) {
...
         lifecycleScope.launch {
-            for (templateName in viewModel.getTemplateNames()) {
-                tabLayout.addTab(tabLayout.newTab().setText(templateName))
+            for ((index, templateName) in viewModel.getTemplateNames().withIndex()) {
+                val newTab = tabLayout.newTab()
+                newTab.setText(templateName)
+                viewModel.cardsWithEmptyFronts?.let { list ->
+                    if (list.await()[index]) {
+                        val badge = newTab.getOrCreateBadge()
+                        badge.text = "!"
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerPage.kt:64]: Particularly, I don't find the `!` necessary. A template being empty may be intentional for a lot of people.

**Review by BrayanDSO — CHANGES_REQUESTED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerPage.kt (hunk 3 above)
Comment (ericli3690) [reply AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerPage.kt]: Removed. It's now just a red dot, though if that's still too urgent-looking I can change the colour, too.

File: AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerPage.kt (hunk 2 above)
Comment (ericli3690) [reply AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerPage.kt]: I've removed the vertical offset. I still think the default overlapping looks kind of ugly, though, so I've added some horizontal offset instead, let me know if I should just stick with the default.

Default:
image

With horizontal offset:
image

File: AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerViewModel.kt (hunk 1 above)
Comment (ericli3690) [reply AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerViewModel.kt]: Ah, it was silly of me to forget about language localization. However, I've taken a look at what it might take to edit the backend to support this and it looks quite complicated. If my understanding is correct the code for generating the error text here is [line 629](https://github.com/ankitects/anki/blob/d52889f45c3f7999a45fd2dde367f79f3bc3bad4/rslib/src/template.rs#L629) of the [render_card](https://github.com/ankitects/anki/blob/d52889f45c3f7999a45fd2dde367f79f3bc3bad4/rslib/src/template.rs#L595) method in the upstream Anki repo (rslib/src/template.rs), which is written in Rust. I'm not sure adding a method to template.rs will solve the problem. Perhaps we should have render_card embed some extra information about whether the front is blank in qnodes when it returns at [line 641](https://github.com/ankitects/anki/blob/d52889f45c3f7999a45fd2dde367f79f3bc3bad4/rslib/src/template.rs#L641)?

In the meantime, I've put together a slightly less hacky solution that works with other languages. A regex checks if the HTML is there but doesn't look at the contents:

image

The only disadvantage I can think of is that it misfires if a user exactly types in the error message HTML as their front-of-card field, but no normal user should do that. Let me know if I should fully commit to a backend solution, as if so I'll need to edit the anki repo and it will probably take me a week or so to complete the fix.

**Comment by Arthur-Milchior** [comment]
Please, instead of merge, rebase to ankidroid/main and force push. I want to only see commit that are useful, and that the message in the commit informs me of what I'll read in it

File: AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerViewModel.kt [hunk 4]
```diff
@@ -105,9 +110,37 @@ class TemplatePreviewerViewModel(
...
                 }
+            cardsWithEmptyFronts = null
         } else {
             clozeOrds = null
             templateNames = CompletableDeferred(notetype.templatesNames)
+            cardsWithEmptyFronts =
+                asyncIO {
+                    val note = note.await()
+                    val names = templateNames.await()
+                    withCol {
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerViewModel.kt:121]: `withCol` blocks the collection until the runnable is finished, so only stuff that require a `Collection` object should be ran inside it. Things like a regex match should be done outside it.

**Review by BrayanDSO — CHANGES_REQUESTED** [review]
Here's a patch with some suggested changes
```patch
Subject: [PATCH] wip
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerPage.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerPage.kt b/AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerPage.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerPage.kt	(revision 1efcea3c7c443a68c04942b8e014dbf3e5158d27)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerPage.kt	(revision 9c76e1eca0bf11cdd2a3b5cb8ed72a0f63ebc4a8)
@@ -55,14 +55,12 @@
         val tabLayout = view.findViewById<TabLayout>(R.id.tab_layout)
 
         lifecycleScope.launch {
+            val cardsWithEmptyFronts = viewModel.cardsWithEmptyFronts?.await()
             for ((index, templateName) in viewModel.getTemplateNames().withIndex()) {
-                val newTab = tabLayout.newTab()
-                newTab.setText(templateName)
-                viewModel.cardsWithEmptyFronts?.let { list ->
-                    if (list.await()[index]) {
-                        val badge = newTab.getOrCreateBadge()
-                        badge.horizontalOffset = -8
-                    }
+                val newTab = tabLayout.newTab().setText(templateName)
+                if (cardsWithEmptyFronts?.get(index) == true) {
+                    val badge = newTab.getOrCreateBadge()
+                    badge.horizontalOffset = -4
                 }
                 tabLayout.addTab(newTab)
             }
Index: AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerViewModel.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerViewModel.kt b/AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerViewModel.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerViewModel.kt	(revision 1efcea3c7c443a68c04942b8e014dbf3e5158d27)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerViewModel.kt	(revision 9c76e1eca0bf11cdd2a3b5cb8ed72a0f63ebc4a8)
@@ -39,6 +39,7 @@
 import kotlinx.coroutines.flow.MutableStateFlow
 import kotlinx.coroutines.flow.collectLatest
 import kotlinx.parcelize.Parcelize
+import org.intellij.lang.annotations.Language
 import org.jetbrains.annotations.VisibleForTesting
 
 class TemplatePreviewerViewModel(
@@ -64,7 +65,7 @@
     override val server = AnkiServer(this).also { it.start() }
 
     /**
-     * for use in [TemplatePreviewerFragment] when flagging cards with empty fronts.
+     * Ordered list of cards with empty fronts
      */
     internal val cardsWithEmptyFronts: Deferred<List<Boolean>>?
 
@@ -117,28 +118,19 @@
             cardsWithEmptyFronts =
                 asyncIO {
                     val note = note.await()
-                    val names = templateNames.await()
-                    withCol {
-                        // checks if each card's front contains the error text
-                        // which is defined at https://github.com/ankitects/anki/blob/d52889f45c3f7999a45fd2dde367f79f3bc3bad4/ftl/core/card-template-rendering.ftl#L4
-                        // and stores the result in a boolean array, to be used in [TemplatePreviewerPage]
-                        List(names.size) { index ->
-                            note
-                                .ephemeralCard(
-                                    col = this,
-                                    ord = index,
-                                    customNoteType = notetype,
-                                    fillEmpty = fillEmpty,
-                                    deckId = arguments.deckId,
-                                ).renderOutput(
-                                    this,
-                                ).questionText
-                                .matches(
-                                    Regex(
-                                        "^<div>.*<br><a href='https://docs\\.ankiweb\\.net/templates/errors\\.html#front-of-card-is-blank'>.*</a></div>$",
-                                    ),
-                                )
-                        }
+                    List(templateNames.await().size) { ord ->
+                        val questionText =
+                            withCol {
+                                note
+                                    .ephemeralCard(
+                                        col = this,
+                                        ord = ord,
+                                        customNoteType = notetype,
+                                        fillEmpty = fillEmpty,
+                                        deckId = arguments.deckId,
+                                    ).renderOutput(this)
+                            }.questionText
+                        EMPTY_FRONT_LINK in questionText
                     }
                 }
         }
@@ -238,6 +230,9 @@
         }
 
     companion object {
+        @Language("HTML")
+        private const val EMPTY_FRONT_LINK = """<a href='https://docs.ankiweb.net/templates/errors.html#front-of-card-is-blank'>"""
+
         fun factory(
             arguments: TemplatePreviewerArguments,
             cardMediaPlayer: CardMediaPlayer,
```

File: AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerViewModel.kt (hunk 1 above)
Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerViewModel.kt]: > Let me know if I should fully commit to a backend solution, as if so I'll need to edit the anki repo and it will probably take me a week or so to complete the fix.

Not necessary for now. Simply checking if the link is present is enough at the moment. But a backend solution is indeed better for the future, so an issue should be created on anki's repo after this is merged. I think that Damien won't oppose to adding a method to check if a template is empty.

**Comment by BrayanDSO** [comment]
Also, I recommend creating a separate branch instead of comitting to your fork's `main` branch

**Comment by ericli3690** [comment]
Sorry for the messy string of actions above -- I initially tried to implement the advice of creating a new branch and committing from there before realizing that would probably necessitate closing this PR and opening a new one. This should now follow @Arthur-Milchior's requirement of having a single clean commit with no weird "merge: ..." commits. In the future, I'll try not to let this happen again and will do my edits on a separate branch of my fork.

I've implemented the suggestions from @BrayanDSO. The horizontal offset is now -4.

My tests show this code should work. Once it's merged, I'll create an issue on the upstream Anki repository to add a backend function so we can get rid of the string-matching hack later.

File: AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerPage.kt [hunk 5]
```diff
@@ -55,8 +55,16 @@ class TemplatePreviewerPage : Fragment(R.layout.template_previewer_container) {
...
         lifecycleScope.launch {
-            for (templateName in viewModel.getTemplateNames()) {
-                tabLayout.addTab(tabLayout.newTab().setText(templateName))
+            for ((index, templateName) in viewModel.getTemplateNames().withIndex()) {
+                val newTab = tabLayout.newTab()
+                newTab.setText(templateName)
+                viewModel.cardsWithEmptyFronts?.let { list ->
+                    if (list.await()[index]) {
+                        val badge = newTab.getOrCreateBadge()
+                        badge.horizontalOffset = -8
```
[the remark this answers is not in the document]
Comment (ericli3690) [reply AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerPage.kt]: -4 sounds good to me.

**Review by BrayanDSO — APPROVED** [review]
LGTM. Thanks!

**Review by david-allison — APPROVED** [review]
Looks great, cheers!

**Comment by user1823** [comment]
On my phone, this badge appears like this:


IMO, this has an effect opposite to the intended one. It makes me think that there is something that needs my attention there.

```
AnkiDroid Version = 2.21alpha14 (d9c0a0618371ccacfc04a85687b989fd37361edd)
Backend Version = 0.1.52-anki25.02 (25.02 038d85b1d9e1896e93a3e4a26f600c79ddc33611)
Android Version = 13 (SDK 33)
ProductFlavor = full
Device Info = motorola | motorola | rhodei | rhodei_g | moto g62 5G | qcom
Webview User Agent = Mozilla/5.0 (Linux; Android 13; moto g62 5G Build/T1SSIS33.1-75-7-14; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/134.0.6998.135 Mobile Safari/537.36
```

**Comment by BrayanDSO** [comment]
> IMO, this has an effect opposite to the intended one.

I get that. Do you have  suggestions? Maybe changing the color to a more bland one, like grey.

**Comment by david-allison** [comment]
Possibly a visual on the tab/text, similar to the disabled state

**Comment by BrayanDSO** [comment]
Maybe add `(empty)` to the title instead of the bagde

**Comment by ericli3690** [comment]
Appending "(empty)" onto the title makes the most sense to me. Here's how that would look:

image

This would go against [what Arthur said](https://github.com/ankidroid/Anki-Android/issues/18107#issuecomment-2727462642) about making the user scroll more, but it's probably the clearest option.

**Comment by BrayanDSO** [comment]
Most notetypes don't have templates enough to make scrolling necessary. And I don't find it bad at all.

In the screenshot, `(empty)` looks nice to me

**Comment by ericli3690** [comment]
How does the above attempt look code-wise? Hopefully I didn't botch adding the string resource.

**Comment by david-allison** [comment]
Hi there @ericli3690! This is the OpenCollective Notice for PRs merged from [2025-03-01 through 2025-03-31](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2025-03-01..2025-03-31+author%3Aericli3690)
                      
If you are interested in compensation for this work, the process with details is here: https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

We only post one comment per person per month to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for this month

Please understand that our monthly budget is never guaranteed to cover all claims - the cap on payments-per-person may be lower, but we try to make our process as fair and transparent as possible, we just need your understanding.

Thanks!
