### PR TITLE
Fix: Block error space for TextInputLayout

### LINKED ISSUE #15620: Log-in screen input box misalignement after selecting the other
Steps:

https://github.com/ankidroid/Anki-Android/assets/69634269/f7f50c80-afa8-4358-811b-46b5394dc81c

2.17beta6, Android 14

### PR DESCRIPTION
**Pull request by criticalAY**
## Purpose / Description
The error space was not blocked resulting in misalignement of edit fields

## Fixes
* Fixes  #15620

## Approach
_How does this change address the problem?_

## How Has This Been Tested?
Oneplus nord ce
image 
image

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — CHANGES_REQUESTED** [review]
please rebase & drop the extra commits

File: AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt [hunk 1]
```diff
@@ -140,24 +140,20 @@ open class MyAccount : AnkiActivity() {
...
             if (!hasFocus) {
                 val email = username.text.toString().trim()
-                userNameLayout.apply {
-                    isErrorEnabled = email.isNotEmpty()
-                    error = if (email.isEmpty()) getString(R.string.invalid_email) else null
-                }
+                userNameLayout.error = if (email.isEmpty()) getString(R.string.invalid_email) else null
             } else {
-                userNameLayout.isErrorEnabled = false
+                userNameLayout.error = ""
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.kt:145]: why do we use `""` here, and `null` above?

**Review by david-allison — APPROVED** [review]
Very clean!
