### PR TITLE
fix: NPE when adding note via intent

### LINKED ISSUE #15584: [Bug] Can't share to AnkiDroid if an image occlusion note type is selected
###### Reproduction Steps

1. Select an image occlusion note type
2. Share an image OR share text to AnkiDroid

Image fails with:

```
FATAL EXCEPTION: main
Process: com.ichi2.anki.debug, PID: 20368
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1582825430, result=-1, data=Intent { (has extras) }} to activity {com.ichi2.anki.debug/com.ichi2.anki.NoteEditor}: java.lang.NullPointerException
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5323)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5362)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.NullPointerException
	at com.ichi2.anki.NoteEditor$requestMultiMediaEditLauncher$1.invoke(NoteEditor.kt:209)
	at com.ichi2.anki.NoteEditor$requestMultiMediaEditLauncher$1.invoke(NoteEditor.kt:194)
	at com.ichi2.anki.NoteEditor$NoteEditorActivityResultCallback.onActivityResult(NoteEditor.kt:284)
	at com.ichi2.anki.NoteEditor$NoteEditorActivityResultCallback.onActivityResult(NoteEditor.kt:278)
	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:414)
	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:371)
	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:845)
	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:151)
	at android.app.Activity.dispatchActivityResult(Activity.java:8628)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5316)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5362) 
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67) 
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loopOnce(Looper.java:201) 
	at android.os.Looper.loop(Looper.java:288) 
	at android.app.ActivityThread.main(ActivityThread.java:7872) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 

```

Text fails with:

```
05:01:31.970 ACRA                                 E  ACRA caught a NullPointerException for com.ichi2.anki.debug
                                                     java.lang.NullPointerException
                                                     	at com.ichi2.anki.NoteEditor.onCollectionLoaded(NoteEditor.kt:608)
                                                     	at com.ichi2.anki.AnkiActivity.startLoadingCollection$lambda$0(AnkiActivity.kt:287)
                                                     	at com.ichi2.anki.AnkiActivity.$r8$lambda$kj9hf0g17vxBfzngPYSgjzadw2g(Unknown Source:0)
                                                     	at com.ichi2.anki.AnkiActivity$$ExternalSyntheticLambda1.execute(Unknown Source:2)
                                                     	at com.ichi2.async.CollectionLoader$load$1.invokeSuspend(CollectionLoader.kt:52)
                                                     	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                     	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                     	at android.os.Handler.handleCallback(Handler.java:942)
                                                     	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                     	at android.os.Looper.loopOnce(Looper.java:201)
                                                     	at android.os.Looper.loop(Looper.java:288)
                                                     	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                     	at java.lang.reflect.Method.invoke(Native Method)
                                                     	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                     	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@232815d, Dispatchers.Main.immediate]
```

###### Research
AnkiDroid Version = 2.17beta5-debug (89ab6369ac90daf348ac7f5e4338a5ca9880a11c)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 13 (SDK 33)

ProductFlavor = amazon

Manufacturer = Google

Model = sdk_gphone64_arm64

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 13; sdk_gphone64_arm64 Build/TE1A.220922.034; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.71 Mobile Safari/537.36

ACRA UUID = bdcca282-35c1-4097-9b3a-5936f403928b

Crash Reports Enabled = false

### PR DESCRIPTION
**Pull request by criticalAY**
## Purpose / Description
Can't share to AnkiDroid if an image occlusion note type is selected 

## Fixes
* Fixes #15584

## Approach
Change the note type to basic when adding an image or text via share intent  

## How Has This Been Tested?
Google emulator - API 34

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt [hunk 1]
```diff
@@ -2051,6 +2053,20 @@ class NoteEditor : AnkiActivity(), DeckSelectionListener, SubtitleListener, Tags
             }
         }
 
+    private fun changeNoteTypeForAddIntent() {
+        val model = getColUnsafe.notetypes.byName("Basic")
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:2057]: not guaranteed to exist, especially if the user is non-English

Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:2057]: Is there any method to bypass it? or get the basic type?

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt [hunk 2]
```diff
@@ -2051,6 +2059,55 @@ class NoteEditor : AnkiActivity(), DeckSelectionListener, SubtitleListener, Tags
             }
         }
 
+    @OptIn(DelicateCoroutinesApi::class)
```
Comment (criticalAY) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:2062]: Not sure if we want to use it, need an alternative

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt (hunk 1 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt]: Maybe we can make a good guess using the date of creation and filtering on `originalStockKind`

Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt]: But the current updated code seems more reliable as we get the `stockNotetype.Kind.entries`  here?

**Review by david-allison — CHANGES_REQUESTED** [review]
This feels too complicated (in the selection of the next note type). How about this:

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt	(revision 6dc9907814909457bb17f6841864d281bae5097c)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt	(date 1708373812607)
@@ -518,7 +518,6 @@
                     finish()
                     return
                 }
-                changeNoteTypeForAddIntent()
                 addNote = true
             }
             // image occlusion is handled at the end of this method, grep: CALLER_IMG_OCCLUSION
@@ -527,7 +526,6 @@
                 addNote = true
             }
             CALLER_ADD_IMAGE -> {
-                changeNoteTypeForAddIntent()
                 addNote = true
             }
             else -> {}
@@ -600,6 +598,15 @@
             // set information transferred by intent
             var contents: String? = null
             val tags = intent.getStringArrayExtra(EXTRA_TAGS)
+
+            // If content has been shared, we can't share to an image occlusion note type
+            if (currentNotetypeIsImageOcclusion() && (sourceText != null || caller == CALLER_ADD_IMAGE)) {
+                val model = col.notetypes.all().first {
+                    it.getInt("originalStockKind") != StockNotetype.OriginalStockKind.ORIGINAL_STOCK_KIND_IMAGE_OCCLUSION_VALUE
+                }
+                changeNoteType(model.id)
+            }
+
             if (sourceText != null) {
                 if (aedictIntent && mEditFields!!.size == 3 && sourceText!![1]!!.contains("[")) {
                     contents = sourceText!![1]!!
@@ -2063,55 +2070,6 @@
             }
         }
 
-    private fun changeNoteTypeForAddIntent() = runBlocking {
-        coroutineScope {
-            val cardType = async {
-                getValidCardType()
-            }
-            val type = cardType.await()
-            if (type != null) {
-                val model = getColUnsafe.notetypes.byName(type)
-                val newId = model?.id
-                if (model != null) {
-                    getColUnsafe.notetypes.setCurrent(model)
-                    val currentDeck = getColUnsafe.decks.current()
-                    currentDeck.put("mid", newId)
-                    getColUnsafe.decks.save(currentDeck)
-                    if (!getColUnsafe.config.getBool(ConfigKey.Bool.ADDING_DEFAULTS_TO_CURRENT_DECK)) {
-                        deckId = model.optLong("did", Consts.DEFAULT_DECK_ID)
-                    }
-                }
-            }
-        }
-    }
-
-    private suspend fun getValidCardType(): String? {
-        var cardType: String? = null
-        withCol {
-            StockNotetype.Kind.entries
-                .filter { it != StockNotetype.Kind.UNRECOGNIZED && it != StockNotetype.Kind.KIND_IMAGE_OCCLUSION }
-                .find { kind ->
-                    var containsFrontOrBack = false
-                    val stockNotetype = BackendUtils.from_json_bytes(getStockNotetypeLegacy(kind))
-                    val tmplsArray = stockNotetype.optJSONArray("tmpls")
-                    if (tmplsArray != null) {
-                        for (i in 0 until tmplsArray.length()) {
-                            val templateObj = tmplsArray.getJSONObject(i)
-                            val qfmt = templateObj.optString("qfmt", "")
-                            val afmt = templateObj.optString("afmt", "")
-                            if (qfmt.contains("{{Front}}") || afmt.contains("{{Back}}")) {
-                                cardType = stockNotetype.optString("name", "")
-                                containsFrontOrBack = true
-                                break
-                            }
-                        }
-                    }
-                    !containsFrontOrBack
-                }
-        }
-        return cardType
-    }
-
     /**
      * Update all the field EditText views based on the currently selected note type and the mModelChangeFieldMap
      */
@@ -2161,38 +2119,42 @@
         requestIOEditorCloser.launch(intent)
     }
 
-    // ----------------------------------------------------------------------------
-    // INNER CLASSES
-    // ----------------------------------------------------------------------------
-    private inner class SetNoteTypeListener : OnItemSelectedListener {
-        override fun onItemSelected(parent: AdapterView<*>?, view: View?, pos: Int, id: Long) {
-            // If a new column was selected then change the key used to map from mCards to the column TextView
-            // Timber.i("NoteEditor:: onItemSelected() fired on mNoteTypeSpinner");
-            // In case the type is changed while adding the card, the menu options need to be invalidated
-            invalidateMenu()
-            val oldModelId = getColUnsafe.notetypes.current().getLong("id")
-            val newId = mAllModelIds!![pos]
-            Timber.i("Changing note type to '%d", newId)
-            if (oldModelId != newId) {
-                val model = getColUnsafe.notetypes.get(newId)
-                if (model == null) {
-                    Timber.w("New model %s not found, not changing note type", newId)
-                    return
-                }
-                getColUnsafe.notetypes.setCurrent(model)
-                val currentDeck = getColUnsafe.decks.current()
-                currentDeck.put("mid", newId)
-                getColUnsafe.decks.save(currentDeck)
-                // Update deck
-                if (!getColUnsafe.config.getBool(ConfigKey.Bool.ADDING_DEFAULTS_TO_CURRENT_DECK)) {
-                    deckId = model.optLong("did", Consts.DEFAULT_DECK_ID)
-                }
-                refreshNoteData(FieldChangeType.changeFieldCount(shouldReplaceNewlines()))
-                setDuplicateFieldStyles()
-                mDeckSpinnerSelection!!.updateDeckPosition(deckId)
-            }
-        }
+
+    private fun changeNoteType(newId: NoteTypeId) {
+        val oldModelId = getColUnsafe.notetypes.current().getLong("id")
+        Timber.i("Changing note type to '%d", newId)
+        if (oldModelId != newId) {
+            val model = getColUnsafe.notetypes.get(newId)
+            if (model == null) {
+                Timber.w("New model %s not found, not changing note type", newId)
+                return
+            }
+            getColUnsafe.notetypes.setCurrent(model)
+            val currentDeck = getColUnsafe.decks.current()
+            currentDeck.put("mid", newId)
+            getColUnsafe.decks.save(currentDeck)
+            // Update deck
+            if (!getColUnsafe.config.getBool(ConfigKey.Bool.ADDING_DEFAULTS_TO_CURRENT_DECK)) {
+                deckId = model.optLong("did", Consts.DEFAULT_DECK_ID)
+            }
+            refreshNoteData(FieldChangeType.changeFieldCount(shouldReplaceNewlines()))
+            setDuplicateFieldStyles()
+            mDeckSpinnerSelection!!.updateDeckPosition(deckId)
+        }
+    }
 
+    // ----------------------------------------------------------------------------
+    // INNER CLASSES
+    // ----------------------------------------------------------------------------
+    private inner class SetNoteTypeListener : OnItemSelectedListener {
+        override fun onItemSelected(parent: AdapterView<*>?, view: View?, pos: Int, id: Long) {
+            // If a new column was selected then change the key used to map from mCards to the column TextView
+            // Timber.i("NoteEditor:: onItemSelected() fired on mNoteTypeSpinner");
+            // In case the type is changed while adding the card, the menu options need to be invalidated
+            invalidateMenu()
+            changeNoteType(mAllModelIds!![pos])
+        }
+
         override fun onNothingSelected(parent: AdapterView<*>?) {
             // Do Nothing
         }
```

**Comment by criticalAY** [comment]
@david-allison I made one more change: If there is no note type having an edit field then the application still crashes (unlikely to happen but I added a check)

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt [hunk 3]
```diff
@@ -2102,6 +2119,29 @@ class NoteEditor : AnkiActivity(), DeckSelectionListener, SubtitleListener, Tags
         requestIOEditorCloser.launch(intent)
     }
 
+    private fun changeNoteType(newId: NoteTypeId) {
+        val oldModelId = getColUnsafe.notetypes.current().getLong("id")
+        Timber.i("Changing note type to '%d", newId)
+        if (oldModelId != newId) {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:2125]: invert & return early

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt [hunk 4]
```diff
@@ -590,6 +591,22 @@ class NoteEditor : AnkiActivity(), DeckSelectionListener, SubtitleListener, Tags
...
+                if (currentNotetypeIsImageOcclusion() && (sourceText != null || caller == CALLER_ADD_IMAGE)) {
+                    val model = col.notetypes.all().first {
+                        it.getInt("originalStockKind") != StockNotetype.OriginalStockKind.ORIGINAL_STOCK_KIND_IMAGE_OCCLUSION_VALUE
+                    }
+                    changeNoteType(model.id)
+                }
+            } catch (e: NoSuchElementException) {
+                showSnackbar(R.string.missing_note_type)
+                // setting the text to null would skip adding text to edit field
+                sourceText = null
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:606]: This also needs to handle the line: `if (caller == CALLER_ADD_IMAGE) handleImageIntent(intent)`

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt [hunk 5]
```diff
@@ -590,6 +591,22 @@ class NoteEditor : AnkiActivity(), DeckSelectionListener, SubtitleListener, Tags
             // set information transferred by intent
             var contents: String? = null
             val tags = intent.getStringArrayExtra(EXTRA_TAGS)
+
+            try {
+                // If content has been shared, we can't share to an image occlusion note type
+                if (currentNotetypeIsImageOcclusion() && (sourceText != null || caller == CALLER_ADD_IMAGE)) {
+                    val model = col.notetypes.all().first {
+                        it.getInt("originalStockKind") != StockNotetype.OriginalStockKind.ORIGINAL_STOCK_KIND_IMAGE_OCCLUSION_VALUE
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:599]: Note: I have a PR which defines `isImageOcclusion`. No action needed, but may want a follow-up after it's merged

https://github.com/ankidroid/Anki-Android/pull/15583/files#diff-11356b3bcc63f8b8148cba7b24bf22a55daa6b4aa99f6e7e581253f424682fa9

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt [hunk 6]
```diff
@@ -2102,6 +2120,35 @@ class NoteEditor : AnkiActivity(), DeckSelectionListener, SubtitleListener, Tags
...
+            return
+        }
+
+        getColUnsafe.notetypes.setCurrent(model)
+        val currentDeck = getColUnsafe.decks.current()
+        currentDeck.put("mid", newId)
+        getColUnsafe.decks.save(currentDeck)
+
+        // Update deck
+        if (getColUnsafe.config.getBool(ConfigKey.Bool.ADDING_DEFAULTS_TO_CURRENT_DECK).not()) {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:2143]:
```
        if (!getColUnsafe.config.getBool(ConfigKey.Bool.ADDING_DEFAULTS_TO_CURRENT_DECK)) {
```

File: AnkiDroid/src/main/res/values/02-strings.xml [hunk 7]
```diff
@@ -107,6 +107,7 @@
     <string name="select">Select</string>
     <string name="field_remapping">%1$s (from “%2$s”)</string>
     <string name="confirm_map_cards_to_nothing">Any cards mapped to nothing will be deleted. If a note has no remaining cards, it will be lost. Are you sure you want to continue?</string>
+    <string name="missing_note_type">No note type found to add text/image</string>
```
Comment (david-allison) [inline AnkiDroid/src/main/res/values/02-strings.xml:110]:
```suggestion
    <string name="missing_note_type">No note type found</string>
```

**Review by david-allison — APPROVED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt (hunk 5 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:599]: Optional: merged now

Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:599]: Will change the method

**Review by mikehardy — APPROVED** [review]
LGTM - thank you - just did a string sync to push string changes through but will follow with another one to get this change in, strings are clear between github / crowdin right now

**Comment by lukstbit** [comment]
@criticalAY 
Small conflict from merging other PRs:

 > Task :AnkiDroid:compilePlayDebugKotlin FAILED
> e: file:///home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:601:59 Unresolved reference: StockNotetype

**Comment by mikehardy** [comment]
@criticalAY yeah - this one needs a fixup anyway, so you have a chance to switch to David's method and that likely fixes the thing anyway

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt (hunk 5 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:599]: I've integrated this change locally as it fixes the compile conflict from in-flight PRs and I'm going to force push it now (apologies in advance @criticalAY please forgive me...) so it unblocks this PR which unblocks strings which unblocks beta6...

**Comment by mikehardy** [comment]
fixed up + pushed + set for auto-merge via queue when CI passes
