### PR TITLE
Synchronize deck name

### LINKED ISSUE #6612: NullPointerException - sync - sanityCheck - deckDueList - childMap
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/a83b69f2-1e97-4f89-b3e4-6446769be6ae

```
java.lang.NullPointerException: Attempt to invoke virtual method 'long com.ichi2.utils.JSONObject.getLong(java.lang.String)' on a null object reference
at com.ichi2.libanki.Decks.childMap(Decks.java:10)
at com.ichi2.libanki.sched.SchedV2.deckDueList(SchedV2.java:7)
at com.ichi2.libanki.sched.SchedV2.deckDueList(SchedV2.java:1)
at com.ichi2.libanki.sync.Syncer.sanityCheck(Syncer.java:36)
at com.ichi2.libanki.sync.Syncer.sync(Syncer.java:84)
at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:16)
at com.ichi2.async.Connection.doOneInBackground(Connection.java:2)
at com.ichi2.async.Connection.doInBackground(Connection.java:4)
at com.ichi2.async.Connection.doInBackground(Connection.java:1)
at android.os.AsyncTask$3.call(AsyncTask.java:378)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:919)
```

### LINKED ISSUE #6613: NullPointerException - __renderPage - buildDeckList
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/0ccae861-bb92-445e-aecb-799e9e58407b

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.json.JSONObject.optBoolean(java.lang.String)' on a null object reference
at com.ichi2.anki.widgets.DeckAdapter.processNodes(DeckAdapter.java:6)
at com.ichi2.anki.widgets.DeckAdapter.processNodes(DeckAdapter.java:12)
at com.ichi2.anki.widgets.DeckAdapter.buildDeckList(DeckAdapter.java:5)
at com.ichi2.anki.DeckPicker.__renderPage(DeckPicker.java:3)
at com.ichi2.anki.DeckPicker$12.onPostExecute(DeckPicker.java:8)
at com.ichi2.async.CollectionTask$TaskListener.onPostExecute(CollectionTask.java:1)
at com.ichi2.async.CollectionTask.onPostExecute(CollectionTask.java:4)
at com.ichi2.async.CollectionTask.onPostExecute(CollectionTask.java:1)
at android.os.AsyncTask.finish(AsyncTask.java:755)
at android.os.AsyncTask.access$900(AsyncTask.java:192)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:224)
at android.app.ActivityThread.main(ActivityThread.java:7520)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
## Purpose / Description

Uses normalize name for nameMap and ensure it is impossible not to do so

## Fixes
Hopefully
* Fixes #6612 
* Fixes #6613 

## Approach
Hidding the hash map in a data structure, so that it can be accessed only in the expected ways.

## How Has This Been Tested?

Running on my phone

I can't test that #6612 and #6613 won't occur again, as I don't know how it did occur, even if I would expect that in this case, there is a deck "A" with a child "a::B" and the change in case (or any other normalization process) may have created the problem in the first place

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java [hunk 1]
```diff
@@ -139,9 +139,65 @@
...
     private HashMap<Long, JSONObject> mDconf;
-    private HashMap<String, JSONObject> mNameMap;
+    // Never access mNameMap directly. Uses byName
+    private NameMap mNameMap;
     private boolean mChanged;
 
+    private class NameMap {
+        private final HashMap<String, JSONObject> mNameMap;
+
+        public NameMap(java.util.Collection<JSONObject> decks) {
```
[the remark this answers is not in the document]
Comment (Arthur-Milchior) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java:149]: I know you have already talk about static factory, but I still don't get the point. Would you have a link

**Comment by Arthur-Milchior** [comment]
I don't understand your point.

According to the stack trace, there were error null pointer exceptions. In both cases, "parents()" returned a list which contained `null` where it should have contained a deck object. So it means the parents was not found. 
It could theoretically means that either the mNameMap is not yet filled (that was my intuition) but actually it is filled during collection loading, so it is impossible. It could also mean that a deck in the collection has no parent; but this should have been found by the sanity check of the deck collection.
This very probably means that the computed parent name was wrong, which is totally possible because the full name of a deck may disagree about upper/lower case with its parents. This is one of the reason why name are normalized. So it's probably not a coincidence that the error did occur in the method where I forgot to canonify the name.

The second commit furthermore ensure that nobody can make the same mistake again.


I have no clue what would be a "diagnostic PR".

**Comment by david-allison-1** [comment]
> It could theoretically means that either the mNameMap is not yet filled (that was my intuition) but actually it is filled during collection loading, so it is impossible. It could also mean that a deck in the collection has no parent; but this should have been found by the sanity check of the deck collection.

If we don't have an example of data that caused issues in the past, then it could easily cause issues in the future. When someone comes back to this PR, they won't know the inputs and the context which caused a problem, which means it's likely to happen again.

> This very probably means that the computed parent name was wrong, which is totally possible because the full name of a deck may disagree about upper/lower case with its parents. This is one of the reason why name are normalized. So it's probably not a coincidence that the error did occur in the method where I forgot to canonify the name.

> I have no clue what would be a "diagnostic PR".

A PR to verify the cause of the issue - likely with more logging in the relevant place, so we can ensure we have regression cover from the issue (and similar bugs) in future.

File: AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java:149]: https://en.wikipedia.org/wiki/Factory_method_pattern#Overview

https://blog.thecodewhisperer.com/permalink/your-constructors-are-completely-irrational

http://misko.hevery.com/code-reviewers-guide/flaw-constructor-does-real-work/

**Comment by Arthur-Milchior** [comment]
I have now added a test which fails before this PR and succeed after. I believe it is the sort of action that can occur after a sync, or after loading a collection for the first time with a recent version of ankidroid

File: AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.java [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+    @Test
+    public void ensureDeckList() {
+        Decks decks = getCol().getDecks();
+        //decks.load("{\"2\":{\"name\":\"A\", \"id\":2}, \"3\":{\"name\":\"a::B\", \"id\":2}}", "{}");
+        for (String deckName: TEST_DECKS) {
+            addDeck(deckName);
+        }
+        JSONObject brokenDeck = decks.byName("cmxieunwoogyxsctNjmv::INSBGDS");
+        Asserts.notNull(brokenDeck,"We should get deck with given name");
+        brokenDeck.put("name", "cmxieunwoogyxSctNjmv::INSBGDS");
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.java:33]: Nit: It'd be useful to either comment that the casing changes here (the deck in `TEST_DECKS` has the same casing as this string), or pick a deck name where it's immediately obvious that the casing is changed

File: AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.java [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+import org.junit.Test;
+import org.junit.runner.RunWith;
+
+import java.util.List;
+
+import androidx.test.ext.junit.runners.AndroidJUnit4;
+
+@RunWith(AndroidJUnit4.class)
+public class DecksTest extends RobolectricTest {
+    public static final String[] TEST_DECKS = {
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.java:18]: Could you comment that this is used by external consumers

Comment (Arthur-Milchior) [reply AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.java:18]: What is external consumer ?

Comment (david-allison-1) [reply AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.java:18]: Something outside the class

File: AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.java (hunk 2 above)
Comment (Arthur-Milchior) [reply AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.java:33]: ok

File: AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.java (hunk 3 above)
Comment (Arthur-Milchior) [reply AnkiDroid/src/test/java/com/ichi2/libanki/DecksTest.java:18]: ok

**Comment by Arthur-Milchior** [comment]
Added a static constructor. Better ?
