### PR TITLE
return value from js-api with correct datatype

### LINKED ISSUE #15925: [Bug] AnkiDroidJS API returns incorrect data type
###### Reproduction Steps

1. Add a new basic type note.
2. Add the following code in the front template of the note:
    ```html
        <span>api.ankiGetCardQueue() return value type: </span>
        <span id="type"></span>


        <script>
            if (typeof AnkiDroidJS !== 'undefined') {

                var jsApiContract = {"version": "0.0.2", "developer": "example@example.com"};
                var api = new AnkiDroidJS(jsApiContract);

                api.ankiGetCardQueue().then(response => {

                    if(response.success){

                        document.getElementById("type").innerHTML = typeof(response.value);
                    }
                })

            }
        </script>


        <span style="display: none">
        {{Front}}
        </span>
    ```
3. Study the new card in AnkiDroid.

###### Expected Result

According to the `AnkiDroid Javascript API wiki`, the return value type of api.ankiGetCardQueue() is [`int`](https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API#type-of-return-value-17). Therefore, it should display `api.ankiGetCardQueue() return value type: int` on the front of the card.

###### Actual Result

It displays `api.ankiGetCardQueue() return value type: string` in the front of the card.

###### Debug info

```
AnkiDroid Version = 2.17.5 (1c1aa94ec466f37d33fd2f75020d9f9021ac811e)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 10 (SDK 29)

ProductFlavor = full

Manufacturer = HUAWEI

Model = MXW-AN00

Hardware = mt6873

Webview User Agent = Mozilla/5.0 (Linux; Android 10; MXW-AN00 Build/HONORMXW-AN00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/92.0.4515.105 Mobile Safari/537.36

ACRA UUID = 82400b65-bd87-4883-a1f6-b911150f725b

Crash Reports Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by krmanik**
## Purpose / Description

The JS API should return value with correct data types. The JS API return the value with types as it is used in the app.

## Fixes
* Fixes #15925

## Approach

The JSONObject changed to put value into with correct data types.

## How Has This Been Tested?

Tested on device with this deck, [AnkiDroid JS API Test Deck
](https://ankiweb.net/shared/info/1045118423)

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — APPROVED** [review]
LGTM. 

Could you add a `@NeedsTest`

**Review by BrayanDSO — APPROVED** [review]

File: AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidJsAPITest.kt [hunk 1]
```diff
@@ -420,7 +420,23 @@ class AnkiDroidJsAPITest : RobolectricTest() {
         }
 
         fun formatApiResult(res: Any): String {
-            return "{\"success\":true,\"value\":\"$res\"}"
+            return JSONObject().apply {
```
Comment (krmanik) [inline AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidJsAPITest.kt:423]: This is already with unit test, where should I put `@NeedTest`

Comment (david-allison) [reply AnkiDroid/src/test/java/com/ichi2/anki/AnkiDroidJsAPITest.kt:423]: If this catches the regression, it's good
