### PR TITLE
Fixed disappearing Actionbar icon after syncing

### LINKED ISSUE #9081: [Bug] Disappearing buttons on main screen (sometimes)
###### Reproduction Steps

1. Open AnkiDroid
2. Sync by pushing the button in the top right corner or swiping down
3. Open the menu on the left side by clicking the hamburger button or swiping right

###### Expected Result
Everything should be normal/as usual. 
In the top right corner of the main screen should a search button, sync button and the kebab menu button.

###### Actual Result
The search button, sync button and the kebab menu button disappear everytime. Sync by swiping down is still possible.

###### Debug info
AnkiDroid Version = 2.15.2

Android Version = 10

Manufacturer = OnePlus

Model = OnePlus Nord

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; OnePlus Nord Build/QQ3A.200805.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/89.0.4389.105 Mobile Safari/537.36

ACRA UUID = 43a01fb7-27f7-4c80-af40-d07913915574

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by prateek-singh-3212**
## Purpose / Description
 Actionbar icon is dissapearing after syncing

## Fixes
Fixes #9081

## Approach
This is a case when their is no change in collection or if their is a error while scyncing. I have done bit investigation and found out that this issue is occuring after this PR #8666 . !colIsOpen() is turned as true and their is no refreshing of action bar in this perticular case and we are seeing no icons in actionbar.

## How Has This Been Tested?

Samsung Galaxy M51 (API 30)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java [hunk 1]
```diff
@@ -1994,6 +1998,8 @@ public void onPostExecute(Payload data) {
                     dialogMessage = res.getString(R.string.sync_generic_error);
                     showSyncErrorMessage(joinSyncMessages(dialogMessage, syncMessage));
                 }
+                mMenuIsRefreshable = true;
+                supportInvalidateOptionsMenu();
             } else {
                 Timber.i("Sync was successful");
                 if (data.data[2] != null && !"".equals(data.data[2])) {
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java:2005]: How strange - I don't understand how this can be in the right place, I just reproduced the issue on my personal device and the message after sync was "collection synchronized" but the icons were gone.

How can putting extra state in the failure case of the if/else fix the problem in the success case?

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java [hunk 2]
```diff
@@ -229,6 +229,9 @@
 
     private String mExportFileName;
 
+    // Check to refresh menu actionbar (used in onPrepareOptionMenu)
+    private boolean mMenuIsRefreshable = false;
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java:233]: If we add state to the object in the form of a member new member variable, then we have a higher mental load when thinking about the object (you have just increased the universe of possible state combinations by `^2`!) plus you need to add it to the Bundle onSaveInstanceState and re-hydrate it in onCreate

For those reasons I always try very very hard to think of some way to avoid adding new state, either by using existing state or by making it unnecessary.

In this case I think it would be best to make it unnecessary. Specifically, what if - in the sync code - if the sync was successful in the no change case it reopened the collection as it's last act? Then `!isColOpen` would return true :thinking:

**Review by mikehardy — CHANGES_REQUESTED** [review]
This is one of those little UI things that bugs me too so I appreciate your taking it up
I'm not sure about the placement of the new state change or if we can avoid new state entirely though - I'd really prefer not to add new member variable state if possible

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java [hunk 3]
```diff
@@ -229,6 +229,9 @@
 
     private String mExportFileName;
 
+    // Check to refresh menu actionbar (used in onPrepareOptionMenu)
```
Comment (ShridharGoel) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java:232]: Small fix for method name: Should have been `onPrepareOptionsMenu`.

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java (hunk 2 above)
Comment (prateek-singh-3212) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java:233]: >  if the sync was successful in the no change case it reopened the collection as it's last act? Then !isColOpen would return true thinking

yes it's is the correct case

**Review by david-allison-1 — COMMENTED** [review]
Could you add a regression test here?

There's a lot of complex logic in the Deck Picker, and being able to pinpoint the issue will:

* Allow us to more safely refactor the syncing code
* Guard against regressions

**Comment by prateek-singh-3212** [comment]
I have just one question that . Shall I open the collection if case lies in `!data.success` is true. Would their will be any issue further?

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java (hunk 2 above)
Comment (prateek-singh-3212) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java:233]: This is case :- When user is synced the data and message is 'No Changes Found'  then all the collections are closed. So after this whatever we do on deckpicker activity it will not refresh menu

**Comment by prateek-singh-3212** [comment]
`if (!colIsOpen()) {
            return false;
        }    }`
Is their is any strong reson for using this ? I don't found any error after removing this.

**Comment by mikehardy** [comment]
> `if (!colIsOpen()) { return false; } }`
> Is their is any strong reson for using this ? I don't found any error after removing this.

That's what git blame is for:

https://github.com/ankidroid/Anki-Android/blame/a8f67d51fcc1eec5d67572416240ddb9b25bb878/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java#L691

leads to https://github.com/ankidroid/Anki-Android/pull/8666

So if you alter that line you need to make sure it is still consistent with the expectations there. It may be possible to do that more easily than any other change by doing a permission check in combination with the previous version of the code

Your testing experience of "it works for me" is a dangerous line of thought vs git blame inspection - most of the errors we are finding and fixing now are very rare corner cases - things that are not obvious - so I rarely trust my own local testing very far anymore other than to verify that I have not broken things completely

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java (hunk 2 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java:233]: I think this is behavior that may be changed - it seems correct to reopen the databases after sync if sync was successful (no change or otherwise). However David is right to request testing in the area as the sync code is very difficult to touch without breaking things. I think this gives us two possible avenues to a fix here, that does not involve adding state to the DeckPicker

- alter the test for colIsOpen back to getColSafe but coupled with a permission check to honor the previous PR in the area
- add a unit test for this DeckPicker expectation (after a sync, the menu items are refreshed) then alter the sync code to open the database after successful sync

**Comment by prateek-singh-3212** [comment]
Sorry, I am not blaming anyone.

**Comment by mikehardy** [comment]
Oh no! It is literally a feature in git that they have named "blame" :laughing:  no worries / no offense, and please `git blame` people frequently :-)

With that in mind please re-read my comment - it was sincerely intended to help

**Comment by prateek-singh-3212** [comment]
Oh! My bad 🤣 .

**Comment by prateek-singh-3212** [comment]
@mikehardy Sorry taking time in this PR. I am planning to switch to `getColSafe `. I am not getting any storage exception anymore. To be safer side I will check the storage permission first and then execute the `getColSafe`.

What are your thoughts on this ?

**Comment by prateek-singh-3212** [comment]
@mikehardy Sorry taking time in this PR. I am planning to switch to `getColSafe `. I am not getting any storage exception anymore. To be safer side I will check the storage permission first and then execute the `getColSafe`.

What are your thoughts on this ?

**Comment by prateek-singh-3212** [comment]
@mikehardy Sorry taking time in this PR. I am planning to switch to `getColSafe `. I am not getting any storage exception anymore. To be safer side I will check the storage permission first and then execute the `getColSafe`.

What are your thoughts on this ?

**Comment by mikehardy** [comment]
I'd prefer not to have more permissions checks scattered around, especially as permissions should go away shortly with the migration to scoped storage. I believe getColSafe with a null check is best here. It should work basically every time or be safe if not

**Comment by david-allison-1** [comment]
Would it be possible to get some logs here so we can understand the order of operations that lead to this issue?

My understanding is that `colIsOpen()` doesn't try to open the collection, and that's the issue: we can try to open the collection via `getCol`, but we need to know the best place to do this.

**Comment by mikehardy** [comment]
I think getColSafe is fine here, I looked into this one thoroughly before when I spelunked for the git blame earlier. The sync closes the collection and leaves it closed, and there's no reason opening it here (or trying to: getColSafe) could harm system state or violate expectations I think. And in the case it doesn't work (probably just for disk corruption reasons, at that point, since they were able to sync already...) then the failure case is a null is there and we return, and...we have the same issue we have now which is just that the ActionBar doesn't re-initialize which is already released to users and thus not a regression.

Seems like an "easy and done" deal.

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java [hunk 4]
```diff
@@ -688,7 +688,8 @@ protected boolean createNewDeck(String deckName) {
     @Override
     public boolean onPrepareOptionsMenu(Menu menu) {
         // Null check to prevent crash when col inaccessible
-        if (!colIsOpen()) {
+        // Don't use colIsOpen() instead getColSafe() because it cause #9081 issue
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java:691]: The comment should explain that there's a chance that the collection is not open at this point, so `colIsOpen()` is not sufficient

**Review by david-allison-1 — COMMENTED** [review]
Looks good! Quick comment and good to go

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java (hunk 4 above)
Comment (prateek-singh-3212) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java]: `using colIsOpen() is not right choice because in the case of sync failure collection is not open. ` works ?

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java [hunk 5]
```diff
@@ -688,7 +688,8 @@ protected boolean createNewDeck(String deckName) {
     @Override
     public boolean onPrepareOptionsMenu(Menu menu) {
         // Null check to prevent crash when col inaccessible
-        if (!colIsOpen()) {
+        // using colIsOpen() is not right choice because in the case of sync failure collection is not open.
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java:691]:
```suggestion
        // #9081: sync leaves the collection closed, thus colIsOpen() is insufficient, carefully open the collection if possible
```

**Review by mikehardy — COMMENTED** [review]
Enough bikeshedding on this one - I proposed what I think is a minimal / complete comment, I'll commit it, then squash merge the PR and we can all move on. Thanks @Akshay0701  :-)

**Review by mikehardy — APPROVED** [review]

**Comment by david-allison-1** [comment]
Thanks!

**Comment by mikehardy** [comment]
Hi there!

If you're already submitted something to OpenCollective for PRs merged in July 2021, you may feel free to ignore this and it will be processed shortly

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for July 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for this month)

Thanks!
