### PR TITLE
Preserve launcher animation by not animating IntentHandler finish

### LINKED ISSUE #5143: AnkiDroid launching with slide up animation
###### Reproduction Steps

1. Use a launcher that lets you adjust the default app launch animation.
2. Set that animation to something other than "slide up"
3. Launch AnkiDroid for the first time (make sure it isn't still stored in RAM)

###### Expected Result

AnkiDroid should launch with the default chosen animation.

###### Actual Result

AnkiDroid uses a slide-up animation.

###### Debug info
```
AnkiDroid Version = 2.8.4

Android Version = 8.0.0

ACRA UUID = 56bbd24a-3865-46b3-855a-440a0bdcd40a
```

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

### PR DESCRIPTION
**Pull request by mikehardy**
## Purpose / Description

Fixes #5143 by letting IntentHandler just finish, if it specifies an animation
it actually clobbers whatever system launcher animation is specified.

Piexel Launcher seems to override the override but Nova Launcher respects it,
meaning you don't get the Nova Launcher animation you configure

## How Has This Been Tested?

I used an API29 Google Play version emulator so I could install Nova, then I alternated launching the app with Google Pixel launcher (always does the zoom-type launch) and Nova (started as described in the linked issue, but now will do whatever animation you configure Nova to launch)

## Learning (optional, can help others)

AnkiDroid has a surprising amount of Activity transition animation infrastructure, and we should probably use it more, in a consistent way, to signal to the user where they are (like, always slide in from right when going more detailed, always slide out to right when going less detailed)

But! You do still want to call Activity.finish() so user can't go back: https://stackoverflow.com/a/43363868/9910298

Sometimes it takes

1.  an hour of learning, and
1.  10 minutes of tests, in order to realize you just need to
1.  delete one line of code.
1. Then 5 minutes of review to realize
1. You actually just want a plain Activity.finish() not a fancy one

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by mikehardy** [comment]
Only tagged you for review @david-allison-1 because I think the end result is funny

File: AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.java [hunk 1]
```diff
@@ -144,7 +144,6 @@ private void launchDeckPickerIfNoOtherTasks(Intent reloadIntent) {
         reloadIntent.addCategory(Intent.CATEGORY_LAUNCHER);
         reloadIntent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK);
         startActivityIfNeeded(reloadIntent, 0);
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.java:146]: Silly question: don't we still want a `finish()` here?

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.java:146]: See, now that's why everyone needs someone to review their stuff. I thought, nah, not important but you force me to justify myself (how dare you! ;-) ) and when I read up on it, apparently IntentHandler will be "back-able" unless I finish it. Also the "teardown" lifecycle methods won't be called (onPause/onStop/onDestroy - depending on where you are when finish is called) but that's not important here.

Will fix and repush

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.java:146]: https://stackoverflow.com/a/43363868/9910298
