### PR TITLE
Fix backgrounding freezing app until sync finishes

### LINKED ISSUE #14197: [Bug] anki freezes when switching to a different app during sync
###### Reproduction Steps

1. Initiate a sync from the main screen (swiping down or clicking on the sync button) 
2. Switch to a different app
3. Switch back to anki

###### Expected Result
It might take several attempts, but after following up with the reproduction steps the app consistently freezes 

###### Actual Result
Anki freezes, and becomes unresponsive 

###### Debug info
AnkiDroid Version = 2.16.2

Android Version = 13

ProductFlavor = play

Manufacturer = Google

Model = Pixel 6a

Hardware = bluejay

Webview User Agent = Mozilla/5.0 (Linux; Android 13; Pixel 6a Build/TQ3A.230705.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/115.0.5790.138 Mobile Safari/537.36

ACRA UUID = 0a6738e2-baa5-4e84-8f59-ddd1b32ff4dd

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by dae**
- Don't block the main thread in onStop() and onResume()
- Suppress multiple progress windows, so that the deck refresh that happens on onResume() doesn't cover sync progress

Closes #14197

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 1]
```diff
@@ -1008,10 +1007,7 @@ open class DeckPicker :
 
     override fun onStop() {
         super.onStop()
-        if (colIsOpenUnsafe()) {
-            WidgetStatus.updateInBackground(this)
-            // Ignore the modification - a change in deck shouldn't trigger the icon for "pending changes".
-        }
+        WidgetStatus.updateInBackground(this@DeckPicker)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:1010]: ✅

This uses `.withCol` and is therefore safe

https://github.com/ankidroid/Anki-Android/blob/7a65160e0e23e20080091a30abdd4c05fc610e06/AnkiDroid/src/main/java/com/ichi2/widget/WidgetStatus.kt#L96-L106

File: AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt [hunk 2]
```diff
@@ -123,7 +127,7 @@ abstract class NavigationDrawerActivity :
         )
         // Setup toolbar and hamburger
         mNavigationView = mDrawerLayout.findViewById(R.id.navdrawer_items_container)
-        mNavigationView.setNavigationItemSelectedListener(this)
+        mNavigationView!!.setNavigationItemSelectedListener(this)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt:130]: nit: preference for `.apply` to remove the `!!`

File: AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt [hunk 3]
```diff
@@ -243,14 +243,18 @@ suspend fun <T> withProgressDialog(
...
+            AnkiDroidApp.instance.progressDialogShown = true
+        }
     }
     try {
         op(dialog)
     } finally {
         dialogJob.cancel()
         dialog.dismiss()
         context.window.clearFlags(WindowManager.LayoutParams.FLAG_NOT_TOUCHABLE)
+        AnkiDroidApp.instance.progressDialogShown = false
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt:257]: Could do with a comment, I don't understand this logic from a quick glance:

* A dialog is showing (`progressDialogShown == true` )
* `withProgressDialog` is called a second time
* What stops this line from being executed and `progressDialogShown` being `false` with a dialog showing?

**Review by david-allison — CHANGES_REQUESTED** [review]
Requesting a comment on the logic (if it's not a bug)

**Comment by david-allison** [comment]
Also: any opposition to squashing, given some intermediate commits fail tests

File: AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt (hunk 3 above)
Comment (dae) [reply AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt]: Thanks, good catch.

File: AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt (hunk 2 above)
Comment (dae) [reply AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt:130]: Using .apply on findViewById() complains that it can't infer the type of the variable

**Comment by dae** [comment]
Squash would be good

**Review by BrayanDSO — APPROVED** [review]
Valuable progress. But for the future we need to reorganize how dialogs and UI updates are handled to avoid piling up things and creating more bugs
