### PR TITLE
Use `toList` first on `mAllTags`  for collections tag

### LINKED ISSUE #12471: [Crash] Selecting the tags option in Note Editor causes a crash.
###### Reproduction Steps

1. Click on + icon to create a new note (or open an existing note from card browser).
2. Select the tags option in the note editor.

###### Expected Result
The user is shown a list of existing tags to choose from and an option to create a new tag.

###### Actual Result
The AnkiDroid app crashes.

###### Debug info
AnkiDroid Version = 2.16alpha85

Android Version = 7.0

Manufacturer = motorola

Model = Moto C Plus

Hardware = mt6735

Webview User Agent = Mozilla/5.0 (Linux; Android 7.0; Moto C Plus Build/NRD90M.03.045; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/105.0.5195.136 Mobile Safari/537.36

ACRA UUID = c6a580cb-02cc-4970-b7a5-24615e6542e1

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by criticalAY**
## Purpose / Description
Use `toList` first on `mAllTags` then sort it to avoid crashing then use clear and add the tags to the collection

## Fixes
Fixes #12471

## How Has This Been Tested?
Tested on API24/31/27

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison** [comment]
To confirm: did this crash before the fix was in place?

**Comment by criticalAY** [comment]
Yes

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsList.kt [hunk 1]
```diff
@@ -20,6 +20,8 @@ import com.ichi2.utils.TagsUtil.getTagAncestors
 import com.ichi2.utils.TagsUtil.getTagRoot
 import com.ichi2.utils.UniqueArrayList
 import com.ichi2.utils.UniqueArrayList.Companion.from
+import org.apache.commons.collections4.CollectionUtils.addAll
+import org.slf4j.MDC.clear
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsList.kt:24]: These are unusual imports. Can I confirm that both are required?

**Review by david-allison — CHANGES_REQUESTED** [review]
Quick question for cleanup, then let's go!

**Comment by david-allison** [comment]
> The main change made in the sort() function is the use of the sortedWith function instead of mAllTags.sortWith

Isn't the fix to use `.toList()` which uses a separate collection, and then replacing the collection rather than trying to mutate it in place?

**Comment by criticalAY** [comment]
Sorry I forgot to update the template I made 2nd commit and this was from the earlier one

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsList.kt (hunk 1 above)
Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsList.kt]: They are not they were not removed automatically when I changed the code

**Review by lukstbit — APPROVED** [review]
I managed to reproduce this on lower versions(not newer versions however) and this seems to fix it. So thanks!

**Comment by criticalAY** [comment]
> I managed to reproduce this on lower versions(not newer versions however) and this seems to fix it. So thanks!

Yes it was an API specific issue :)

**Review by david-allison — APPROVED** [review]
Clean! Thank you 🙏🙏🙏
