### PR TITLE
fix(preferences): Improve UI of IncrementerNumberRangePreferenceCompat

### LINKED ISSUE #20005: Improve UI of `IncrementerNumberRangePreferenceCompat`
Off the top of my head:

1. [ ] The borders don't look good
1. [ ] The + and -  text is too small
1. [ ] buttons do not appear visibly disabled when the min/max is hit
1. [ ] A user can enter a bad value into the textbox without issue
    * 'OK' still appears enabled
1. [ ] Textbox isn't using a material theme which provides a visual `error` display

Screenshot 2026-01-05 at 00 24 05

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/issues/20001#issuecomment-3708277944_

### PR DESCRIPTION
**Pull request by Akira2206**
## Purpose / Description
Updates the UI of `IncrementerNumberRangePreferenceCompat` to use Material Design components and fixes visibility issues across different themes.

## Fixes
* Fixes #20005

## Approach
* Replaced `Button` with `MaterialButton` (Elevated button) and `EditText` with `TextInputLayout`
* Added custom attributes (`incrementerButtonBackground`, `incrementerInputBackground`, `incrementerIconColor`) to `attrs.xml` and defined specific colors for light, plain, dark, and black themes
* Verified that disabled buttons fade out correctly (alpha 0.38). For enabled buttons, I aimed for a 3:1 contrast ratio. This was achieved in most cases, with exceptions to maintain visual hierarchy:
    * [Light Theme (Icon vs Button)](https://webaim.org/resources/contrastchecker/?fcolor=04A8F1&bcolor=E2F5FC)
    * [Dark Theme (Button vs Dialog)](https://webaim.org/resources/contrastchecker/?fcolor=333D46&bcolor=424242)

## How Has This Been Tested?

https://github.com/user-attachments/assets/7d1c7dd2-f07f-4a5c-b047-95342a497707

Enabled buttons:

   

Error text and disabled buttons:

   

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by Akira2206** [comment]
I'll fix the alignment, but @ZornHadNoChoice just suggested removing the buttons entirely here: https://github.com/ankidroid/Anki-Android/issues/20005#issuecomment-3828591975

What should be done?

**Comment by david-allison** [comment]
Keep the buttons, this looks great to me aside from Brayan's comment

File: AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreferenceCompat.kt [hunk 1]
```diff
@@ -105,34 +93,16 @@ class IncrementerNumberRangePreferenceCompat :
...
-                    LinearLayout.LayoutParams.WRAP_CONTENT,
-                    LinearLayout.LayoutParams.WRAP_CONTENT,
-                    1.0f,
-                )
-
-            incrementButton.setText(R.string.plus_sign)
-            decrementButton.setText(R.string.minus_sign)
-            incrementButton.layoutParams = buttonParams
-            decrementButton.layoutParams = buttonParams
+            val view = LayoutInflater.from(context).inflate(R.layout.dialog_incrementer_preference, null)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreferenceCompat.kt]: Use view binding: 

* #11116 for examples

File: AnkiDroid/src/main/res/values/theme_light.xml [hunk 2]
```diff
@@ -163,6 +163,10 @@
 
         <!-- HTML 'blue' -->
         <item name="clozeColor">#0000FF</item>
+
+        <item name="incrementerButtonBackground">@color/white</item>
```
Comment (david-allison) [inline AnkiDroid/src/main/res/values/theme_light.xml:167]: I'll propose these for the full app theme, but in a separate issue, you've done a GREAT job here

File: AnkiDroid/src/main/res/values/attrs.xml [hunk 3]
```diff
@@ -219,4 +223,6 @@
     <attr name="checkMediaListForeground" format="color" />
 
     <attr name="progressDialogButtonTextColor" format="color"/>
+
+
```
Comment (david-allison) [inline AnkiDroid/src/main/res/values/attrs.xml]: Revert - whitespace change

**Comment by Akira2206** [comment]
Fixed alignment of the buttons with text input:




In the original light theme, the icon color used is `material_light_blue_500` (contrast: 2.37)
3 variants of the same color along with their contrast ratios:

`material_light_blue_600` (2.81:1)



`material_light_blue_700` (3.43:1)



`material_light_blue_800` (4.31:1)



I prefer 600 because it matches the other dialog buttons, though 700 is safer for accessibility

File: AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreferenceCompat.kt [hunk 4]
```diff
@@ -52,9 +50,9 @@ class IncrementerNumberRangePreferenceCompat :
     constructor(context: Context) : super(context)
 
     class IncrementerNumberRangeDialogFragmentCompat : NumberRangeDialogFragmentCompat() {
+        private var bindingRef: DialogIncrementerPreferenceBinding? = null
+        private val binding get() = bindingRef!!
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreferenceCompat.kt:54]: why not `lateinit`?

**Review by david-allison — APPROVED** [review]
Mild preference for `material_light_blue_700`

Implementer's choice - let us know what you decide on and we'll merge

Thanks!!

File: AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreferenceCompat.kt (hunk 4 above)
Comment (Akira2206) [reply AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreferenceCompat.kt:54]: Since the fragment lives longer than the view we need to make `bindingRef = null` in `onDestroyView()`, and lateinit variables cannot be set to null

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreferenceCompat.kt:54]: `by viewBinding(DialogIncrementerPreferenceBinding::bind)` won't work in this circumstance?

Comment (Akira2206) [reply AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreferenceCompat.kt:54]: I looked into it. Because we are creating the view from scratch in `onCreateDialogView` (inflating it manually to return binding.root), the `::bind` method which expects an existing view won't work here it seems, so we have to handle the lifecycle manually

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/preferences/IncrementerNumberRangePreferenceCompat.kt:54]: Preferences are weird, cheers
