### PR TITLE
fix: Use media directory as the base url of the CardViewers

### LINKED ISSUE #15911: [BUG]: localStorage does not seem to be persistent in version 2.17.5
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Create a card with the following contents on it somewhere:

```html
<script>
const STORAGE_KEY = "example-storage-location";

let existing_storage = localStorage.getItem(STORAGE_KEY);
if (existing_storage === null) {
    existing_storage = 0;
} else {
    existing_storage = parseInt(existing_storage);
}

console.log("This template has been accessed " + existing_storage + " times.");

existing_storage = existing_storage + 1;

localStorage.setItem(STORAGE_KEY, existing_storage);
console.log(STORAGE_KEY + " set to " + existing_storage);
</script>
```

2. Connect phone in debug mode.
3. Open `chrome://inspect` on phone and check the console logs.
4. Go to front, back, multiple cards, etc.
5. Exit deck to list of decks
6. Select same deck, repeat steps 2-4.

### Expected behaviour

The console should say: "This template has been accessed 0 times", then increment by 1 for each time the template is accessed (once for front, once for back, etc). The number should _not_ reset when you exit and then re-enter the deck.

### Actual behaviour

All localStorage seems to be lost when exiting the deck.

### Debug info

```text
AnkiDroid Version = 2.17.5 (1c1aa94ec466f37d33fd2f75020d9f9021ac811e)
Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)
Android Version = 14 (SDK 34)
ProductFlavor = play
Manufacturer = Google
Webview User Agent = Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro Build/UQ1A.240205.004; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.119 Mobile Safari/537.36
ACRA UUID = 
Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

I have been using `localStorage` to store persistent per-deck settings, e.g. "Show pictures automatically" or "Play TTS automatically", etc, because depending on the review situation, I want more or less automatic behavior (e.g. if I am in a room where I don't have headphones and I need to be quiet, I don't want TTS going off automatically). This worked in previous versions, but now my settings get lost any time I exit the deck.

Seems like [someone else](https://www.reddit.com/r/Anki/comments/1beape6/localstorage_issue_in_ankidroids_latest_version/?rdt=58076) is having the same issue as well, and they appear to be using localStorage to share information across decks.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### LINKED ISSUE #16139: [BUG]: Cloze cards showing 'data-ordinal="1"' when using latex and images
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

This minimal card works on desktop and ipad, but does not display correctly on Ankidroid:

--image.png--
Latex Test: {{c1::[$$]x[/$$]}}

Here --img.png-- is any image that is added to the card. The placement of the image does not seem to affect the behaviour.

Here is the relevant html:

```
<div id="qa" style="opacity: 1;"><style>.card {
    font-family: arial;
    font-size: 20px;
    text-align: center;
    color: black;
    background-color: white;
}
.cloze {
    font-weight: bold;
    color: blue;
}
.nightMode .cloze {
    color: lightblue;
}
</style><img src="anki.jpg"><br>Latex Test:&nbsp;<span class="cloze" data-cloze="[$$]x[/$$]" data-ordinal="1">[...]</span></div>
```

### Expected behaviour

desktop

### Actual behaviour

AnkiDroid

### Debug info

```text
AnkiDroid Version = 2.17.6 (568538896be943818ca793dd2635822265712def)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 11 (SDK 30)

ProductFlavor = play

Manufacturer = samsung

Model = SM-G998W

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-G998W Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/123.0.6312.99 Mobile Safari/537.36

ACRA UUID = 8dfcdc97-62c1-4dfe-8054-fc2c0a2d9507

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

These types of cards worked previously. A recent update might have changed things?

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by BrayanDSO**
## Purpose / Description

Loading files with file:/ scheme in much faster in an Android Webview, and that's what 2.15.6 did by setting the Webview base url to the media directory.

But in 2.16/2.17, in order to enable POST requests to be done, the base url was set to localhost and the files were delivered by the server. After noticing that loading files was slower with the server, a WebViewAssetLoader was used, but it was still slower than file:/. The next alternative was parsing the card's HTML to use file:/ for media sources, but that leads to CORS issues and sometimes HTML parsing issues.

So, here's what I believe that should be the definitive solution, which is to remap POST requests base url, so the Webview base url can be set to the media directory so the 2.15.6 behavior is restored.

## Fixes
* Fixes #16139
* Fixes #15911

## Approach
In the commits

## How Has This Been Tested?

Emulator 34:

Tested by adding console.log("foo"); into Custom scheduling deck option then seeing if it appeared in Logcat

Also checked if media, specially videos and audios, were properly loaded

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by BrayanDSO** [comment]
I won't be available to handle requested changes. 

Already pushed it because a related issue appeared

**Comment by mikehardy** [comment]
Should be good to go now

File: AnkiDroid/src/main/java/com/ichi2/anki/pages/AnkiServer.kt [hunk 1]
```diff
@@ -47,26 +40,35 @@ open class AnkiServer(
...
-            newChunkedResponse(data)
-        } catch (exc: Exception) {
-            Timber.w(exc, "buildResponse failure")
-            newChunkedResponse(exc.localizedMessage?.encodeToByteArray(), status = Response.Status.INTERNAL_ERROR)
+        return if (data == null) {
+            newFixedLengthResponse(null)
+        } else {
+            newChunkedResponse(status, mimeType, ByteArrayInputStream(data))
+        }.apply {
+            addHeader("Access-Control-Allow-Origin", "*")
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/pages/AnkiServer.kt:68]: [security] Is it feasible to limit this so other apps on-device can't reasonably access the server?

Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/anki/pages/AnkiServer.kt:68]: Tried it once but it didn't work immediately. Since my timeblock was gone and this was the same of what 2.15.6 did, I left it as is.

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/pages/AnkiServer.kt:68]: Do you feel we should block this PR on this?

* Historically, `collection.media` + `collection.anki2` were publicly accessible. 
   * After 2.16 & scoped storage, we should lock it down so it matches expectations
   * We don't want to be listed on the next article in this series: https://www.bellingcat.com/news/2021/05/28/us-soldiers-expose-nuclear-weapons-secrets-via-flashcard-apps/

If we have `MANAGE_EXTERNAL_STORAGE`, we **must not** allow access to files outside `collection.media`, and I would block on this

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/pages/AnkiServer.kt:68]: I've extracted this to: https://github.com/ankidroid/Anki-Android/issues/16230

Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/anki/pages/AnkiServer.kt:68]: Took a look and since the Reviewer now uses `file:///` as base url, `origin` is null so only `*` can be used as the value of `Access-Control-Allow-Origin`.

On a quick assessment, only `POST` requests are allowed. In the reviewer only `getSchedulingStatesWithContext` and `setSchedulingStates` are enabled. So, I don't see any danger right now.

**Review by david-allison — APPROVED** [review]

**Review by mikehardy — APPROVED** [review]
let's do this - thanks @BrayanDSO (and David)
