### PR TITLE
Warning when WebView (<77) is outdated

### LINKED ISSUE #14702: Alert in app startup if an old Webview (< v77) is being used
Oh I always forget that. This is an easy trap to fall in to, I believe others have as well (recently)

I think a nice ergonomic improvement would be a startup alert for people like me that forget this that checks for a minimum webview version and alerts people if it is too old

I'll re-test this on a modern emulator. I was trying to avoid the higher API emu I've got because it crashes so frequently at the moment (upstream google emulator issue, not related to any work here...)

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/issues/14622#issuecomment-1806841201_

---

The concern of the issue is that Anki HTML pages (`com.ichi2.anki.pages`: Card info, statistics, deck options, import CSV, etc) needs a not too old webview version. The task is to:

1.  Find out the approximate minimum version of WebView required for the pages to work correctly
2. If the user's WebView is old, show a dialog or snackbar at the app startup (in the deck picker to be more precise) telling the user to update their webview with a link explaining how

### PR DESCRIPTION
**Pull request by elli-hae**
## Purpose / Description
Alert the developer when the WebView version is too old to support Anki HTML pages.

## Fixes
* Fixes #14702 

## Approach
Show a Snackbar with a warning if the Android WebView version is detected to be older than the oldest supported version (currently version 77).
OldWebViewWarning

## How Has This Been Tested?
I tried it with two separate emulators, one with a WebView version <77, one emulator with a newer version and a physical phone, and the warning appears as it should.
I also ran the gradlew jacocoTestReport. It keeps failing for a few tests but they're always different ones and I can't find the connection to the code I added, so if anyone knows why tests are failing, please tell me, and I will fix it. I'm using the Medium Phone Emulator in Android Studio with API version 24 (Android 7) to test.

## Learning (optional, can help others)
It's not possible to update the WebView version on Android 5 through the Google Play Store ([more info](https://stackoverflow.com/questions/30019960/how-to-upgrade-androids-webview-in-emulator-android-5))

## Checklist
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 1]
```diff
@@ -461,6 +464,7 @@ open class DeckPicker :
         Onboarding.DeckPicker(this, mRecyclerViewLayoutManager).onCreate()
 
         launchShowingHidingEssentialFileMigrationProgressDialog()
+        checkWebviewVersion()
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:467]: Just a thought on performance - this is intended to be a developer warning only, and I wonder if it makes sense to only execute it on debug builds to make sure there is zero impact on release builds / regular users? Something like this?

```suggestion
        if (BuildConfig.DEBUG) {
            checkWebviewVersion()
        }
```

What do you think?

**Review by mikehardy — COMMENTED** [review]
This looks really good, thank you!
One thought on making sure regular users aren't impacted at all - curious for your thoughts

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt (hunk 1 above)
Comment (elli-hae) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:467]: Yes that makes sense! Thanks

**Review by mikehardy — APPROVED** [review]
Nice thank you!

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 2]
```diff
@@ -164,7 +166,8 @@ const val TIMES_STORAGE_MIGRATION_POSTPONED_KEY = "timesStorageMigrationPostpone
 @NeedsTest("On a new startup, the App Intro is displayed")
 @NeedsTest("If the collection has been created, the app intro is not displayed")
 @NeedsTest("If the user selects 'Sync Profile' in the app intro, a sync starts immediately")
-open class DeckPicker :
+open class
+DeckPicker :
```
[the remark this answers is not in the document]
Comment (elli-hae) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:170]: I was also confused about that, but I was almost 100% sure I didn't put the line break there myself, so I just left it.

[the remark this answers is not in the document]
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:170]: can this be reverted?

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 3]
```diff
@@ -480,6 +486,27 @@ open class DeckPicker :
         return prefs.getBoolean(IntroductionActivity.INTRODUCTION_SLIDES_SHOWN, false)
     }
 
+    /**
+     * Check if the current WebView version is older than the last supported version and if it is,
+     * inform the user with a snackbar.
+     */
+    private fun checkWebviewVersion() {
+        // Specifically check for Android System WebView
+        try {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:495]: Leave a comment in this method saying that it's fine to leave this untranslated as it's debug only

**Review by david-allison — COMMENTED** [review]
Good to go, with 2 minor issues:

* Line noise adds to `git blame` and we should avoid it where possible
  * When it's not possible, it should all be in 1 'large' change caused by a linter upgrade, which we can ignore in `git blame`

The other is just a comment to future readers explaining that there's nothing to do

The actual change looks good

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt (hunk 3 above)
Comment (elli-hae) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:494]: Truly sorry, completely f'd it up. Apparently I'm even worse at using git than I thought. To be honest I'm utterly lost at this point.

Comment (elli-hae) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:494]: Should I just make a new feature branch, make the changes there and make a new PR?

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:494]: git sure isn't friendly while learning it, I have done everything you did here and much more bizarre mistakes as well while I was learning it 😆 

If closing this and opening a new PR is easier (sounds like it is?) that's totally understandable, go for it

**Comment by david-allison** [comment]
Feel free to come to discord if you want some help with rebasing the PR

Otherwise, closing and cherry picking/starting again works. We've all been there

**Comment by elli-hae** [comment]
First of all, thank you very much for your patience and support. Second, I don't know why the emulator tests are failing. They were passing before and are also passing locally.

**Review by mikehardy — APPROVED** [review]
Hey, this looks great and you re-vived the PR with proper git magic 🪄 
well done

**Comment by mikehardy** [comment]
emulator test was an unrelated flake (the emulator had a total startup failure and was unable to even install the app for testing), I just restarted it

**Review by david-allison — APPROVED** [review]
That was a "really not fun" git issue to solve

Truly, congratulations, and thank you for sticking with it!

Change is good to go, thanks so much for your time 🙏

**Comment by elli-hae** [comment]
A big thank you to both of you for the encouraging support and for making this a great learning opportunity for me! Thanks to you, it was a pleasure to work on this when it could have easily been frustrating 🙏
