### PR TITLE
fix: ensure ViewPager2 content height updates in ChangeNoteTypeDialog

### LINKED ISSUE #20171: [Change note type] fields can be hidden by selecting card types
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Create a basic and reversed note.
2. In the browser, select it and choose change note type.
3. Tap on template then card 1 twice.

The back field gets hidden. It's shown again after tapping twice on the front field.

https://github.com/user-attachments/assets/efe20520-0b65-465a-bcea-383ec34b5ce5

### Expected behaviour

All fields stay visible.

### Debug info

```text
AnkiDroid Version = 2.24.0alpha4 (ae379be94b660291e90d72501f5725ed396b9a80)  
Backend Version = 0.1.63-anki25.09.2 (25.09.2 3890e12c9e48c028c3f12aa58cb64bd9f8895e30)  
Android Version = 13 (SDK 33)  
ProductFlavor = full  
Device Info = Xiaomi | POCO | mondrian | mondrian_global | 23013PC75G | qcom  
WebView Info = [com.google.android.webview | 749919233]: Mozilla/5.0 (Linux; Android 13; 23013PC75G Build/TKQ1.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/143.0.7499.192 Mobile Safari/537.36  
ACRA UUID = 4afc3b3f-e93f-4a66-bc71-2b9476ef9eb0  
FSRS = 5.1.0 (Enabled: true)  
Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by 7Collector**
## Purpose / Description
Fixes an issue where ChangeNoteTypeDialog retains incorrect height measurements when switching between pages of different sizes.

## Fixes
* Fixes #20171 

## Approach
The fix forces a requestLayout() call on the fragment's root view during onResume.

## How Has This Been Tested?

https://github.com/user-attachments/assets/3453c2f3-eb02-4e45-aadc-2e5574fdbbd5

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_
I initially attempted to fix this using minHeight constraints, but this failed
Research confirmed that forcing a layout update is the standard solution for ViewPager2 with wrap_content, this solution has also been used in other ViewPagers as well (e.g. SetDueDateDialog)
https://stackoverflow.com/questions/58492796/viewpager2-with-differing-item-heights-and-wrap-content

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ChangeNoteTypeDialog.kt [hunk 1]
```diff
@@ -328,6 +328,15 @@ class ChangeNoteTypeDialog : AnalyticsDialogFragment() {
             }
         }
 
+        override fun onResume() {
+            super.onResume()
+            // Forcing the root layout to recalculate heights of children and update itself
+            // https://stackoverflow.com/questions/58492796/viewpager2-with-differing-item-heights-and-wrap-content
+            // Alternatively, a method can be added to the onPageSelected method of the ViewPager
+            // and get the current fragment's root view there and recalculate it's height
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ChangeNoteTypeDialog.kt]: Make the comments much more succinct (ideally 1 line), and put the explanation in the commit message.

Comment (7Collector) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/ChangeNoteTypeDialog.kt]: Thanks, will keep that in mind!

**Comment by david-allison** [comment]
@7Collector 

You have a different email supplied for each of your commits:

* Your GitHub noreply email
* Your Gmail

Which one would you like to appear?

Please see: https://docs.github.com/en/account-and-profile/how-tos/email-preferences/setting-your-commit-email-address for more details. If you don't know, I'd recommend your GitHub noreply email.

**Comment by 7Collector** [comment]
Please go ahead with the GitHub one, I'll reconfigure my local machine to do the same
