### PR TITLE
Fix : Deck Picker Arrow doesn't rotate on expanding and collapsing the deck.

### LINKED ISSUE #17915: In deck picker, arrow doesn't rotate on expanding deck
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

- In the deck picker, click on the parent deck to expand it.
- The arrow (>) on the left side of the name of the parent deck doesn't rotate.

### Expected behaviour

Just like other apps, the arrow should rotate to point downwards when the parent deck is expanded.

### Debug info

```text
2.21 alpha 11
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by xenonnn4w**
## Purpose / Description
In the deck picker, arrow doesn't rotate on expanding or collapsing the deck.

## Fixes
* Fixes #17915

## Approach
`deckExpander` (the dropdown arrow) visibility and click behavior depend on `node.children.isNotEmpty()`. When the user toggles the expansion state (by clicking `deckExpander`), the dataset changes, but without `notifyItemChanged(position)`, the UI does not get updated.

## API 24
[android7.webm](https://github.com/user-attachments/assets/10667db4-57fe-4330-b7b4-ef361fe474fb)

## API 34

[androidapi35.webm](https://github.com/user-attachments/assets/6e500c7f-21df-4a08-9e67-90571e5b5f12)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by xenonnn4w** [comment]
While testing it, somehow i encountered that no deck expander is created for a deck. Maybe that due to `runBlocking` , but i'm unable to reproduce the same again.

File: AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt [hunk 1]
```diff
@@ -152,8 +153,13 @@ class DeckAdapter(
             holder.deckExpander.visibility = View.GONE
             deckLayout.setPaddingRelative(startPadding, 0, endPadding, 0)
         }
+
+        // Toggle deck expansion/collapse
```
Comment (lukstbit) [inline AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt:157]: There's no need for this comment and extra space.

**Review by lukstbit — APPROVED** [review]
Thanks!

File: AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt (hunk 1 above)
Comment (lukstbit) [reply AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt:156]: The comment should also go, the code is self explanatory and you also added extra logging below.
