### PR TITLE
fix: lateinit property viewPager has not been initialized

### LINKED ISSUE #16301: [BUG] 2.18 [CardTemplateFragment]: lateinit property viewPager has not been initialized
https://ankidroid.org/acra/app/1/bug/164453/report/436f97c8-3059-468a-a6ee-57ae6fb9feb5

```
kotlin.UninitializedPropertyAccessException: lateinit property viewPager has not been initialized
	at com.ichi2.anki.CardTemplateEditor.getViewPager(SourceFile:8)
	at com.ichi2.anki.CardTemplateEditor$CardTemplateFragment.initTabLayoutMediator(SourceFile:40)
	at com.ichi2.anki.CardTemplateEditor$CardTemplateFragment.onViewCreated(SourceFile:6)
	at androidx.fragment.app.Fragment.performViewCreated(SourceFile:15)
	at androidx.fragment.app.FragmentStateManager.createView(SourceFile:314)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(SourceFile:128)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(SourceFile:31)
	at androidx.fragment.app.FragmentManager.moveToState(SourceFile:28)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(SourceFile:10)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(SourceFile:12)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(SourceFile:5)
	at androidx.fragment.app.FragmentActivity.onStart(SourceFile:21)
	at androidx.appcompat.app.AppCompatActivity.onStart(SourceFile:1)
	at com.ichi2.anki.AnkiActivity.onStart(SourceFile:1)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1456)
	at android.app.Activity.performStart(Activity.java:8195)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3796)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2291)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8319)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
```

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
`onCollectionLoaded` is not guaranteed to be called synchronously

## Fixes
* Fixes #16301

## Approach
init the variable in `onCreate`

## How Has This Been Tested?
⚠️ Only opened the screen, felt it was obvious and low-risk

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt [hunk 1]
```diff
@@ -185,9 +186,8 @@ open class CardTemplateEditor : AnkiActivity(), DeckSelectionListener {
         }
         fieldNames = tempModel!!.notetype.fieldsNames
         // Set up the ViewPager with the sections adapter.
-        viewPager = findViewById<ViewPager2?>(R.id.pager).apply {
-            adapter = TemplatePagerAdapter(this@CardTemplateEditor)
-        }
+        viewPager.adapter = TemplatePagerAdapter(this@CardTemplateEditor)
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt:189]: 🤔 I think this is still racy
The crash was during this chunk of view creation / tab creation / tab vs pager mediator creation:

https://github.com/ankidroid/Anki-Android/blob/1a0fcdcd06b00bbc878595ef6b980b936fcbfb1e/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt#L488-L507

Now you're going to get past the uninitialized viewPager lateinit item, but tempModel will be null because onCollectionLoaded has maybe not run yet, so the tab name can't be set and view creation will still fail

We either need to defer view creation since tab count + tab names will depend on it stuff from onCollectionLoaded, or we need to load empty tempModel (and whatever else is needed to inflate view initially?) and then clobber it + re-init tab/pager/mediator in onCollectionLoaded

Or something else I haven't thought of, or I am misunderstanding

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt:189]: We have two cases:

* `savedInstanceState != null`
  * `tempModel` is loaded from state
* `savedInstanceState == null`
  * `onCreate -> ... -> `onCollectionLoaded`
    * `tempModel` is created before: 
    *  `TemplatePagerAdapter()` -> `CardTemplateFragment.newInstance`

**Review by BrayanDSO — APPROVED** [review]
Not sure if the issue is fixed, but moving viewPager out of `onCollectionLoaded` is an improvement either way, so I'll aprove

**Review by lukstbit — APPROVED** [review]
I think this is the correct fix. Related to Mike's comment, looking at the code, I don't think there's a moment the fragments will access the model before the collection is loaded. Seeing that they access the model in onCreateView() this wouldn't get called unless the adapter was set on the ViewPager which only happens after the collection is loaded.

**Comment by mikehardy** [comment]
Thanks a bunch for the second look and making sure the fix was good, much appreciated
