### PR TITLE
enhancement: show copied to clipboard toast for API ≤ 32

### LINKED ISSUE #14992: Tts voices: add "copy to clipboard"
The "Copied to clipboard." doesn't seem to be shown on my environment.

<details><summary>debug info</summary><div>

AnkiDroid Version = 2.17alpha10 (50fa39cd561d83662cd5ef1f708b14a9a15c74ac)

Backend Version = 0.1.31-anki23.10.1 (23.10.1 fac9e0ee1436ba5ac3366c72dd9394a6e692b1cf)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/118.0.0.0 Mobile Safari/537.36

ACRA UUID = df169a4d-29ec-46b6-b114-141ca7e01ba3

Crash Reports Enabled = true
</div></details>

_Originally posted by @snowtimeglass in https://github.com/ankidroid/Anki-Android/pull/14628#issuecomment-1857694833_

### PR DESCRIPTION
**Pull request by criticalAY**
## Purpose / Description
In Android 12L (API level 32) and lower, users might be unsure whether they successfully copied content or what they copied. 

## Fixes
* Fixes  #14992

## How Has This Been Tested?
Tested on Google emulator for API 12 and lower and API 33

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt [hunk 1]
```diff
@@ -84,6 +86,10 @@ fun Context.copyToClipboard(text: String): Boolean {
             text
         )
     )
+    // In Android 12L (API level 32) and lower, users might be unsure whether they successfully copied
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt:89]: This causes a number of places to show multiple toasts

**Review by david-allison — CHANGES_REQUESTED** [review]
Needs to go through the call chains of `copyToClipboard` and ensure only one toast is displayed

**Review by david-allison — APPROVED** [review]

**Comment by BrayanDSO** [comment]
There is `copyToClipboardAndShowConfirmation()` already

**Comment by david-allison** [comment]
Our confirmation is not necessary in later APIs, we don't want to show it twice.

**Comment by BrayanDSO** [comment]
My suggestion is to join both methods and remove the `showTextCopiedMessage: Boolean = false` conditional, so the message is always shown in older APIs and not duplicated in newer APIs

**Review by david-allison — CHANGES_REQUESTED** [review]
Copied from a series of Discord messages:

 want to walk through things just to be sure. Tell me where I'm going wrong

There's 2 conditions:

1. Did the copy succeed?
2. Do we need to show a notification (or the negation: did Android show a notification due to a succesful copy)

`1 && 2` -> do nothing, the notification was shown by the system
`1 && !2` -> the system didn't show a notification, show one
`!1 && (2 || !2)` -> if the copy didn't succeed, we need to show a notification

Then the final step is 'how': using a toast or a snackbar

----

Code dump, then let me explain:

```kotlin
/**
 * Copies the provided [text] to the clipboard (truncated if necessary),
 * and show either a snackbar, if possible, or a toast in case of API>32,
 * with the success or failure message.
 */
fun Context.copyToClipboard(
    text: String,
    @StringRes successMessageId: Int,
    @StringRes failureMessageId: Int
) {
    val copied = copyTextToClipboard(text)
    // in Android T and above, the system is guaranteed to show a message on a successful copy
    // so we don't need to do anything
    val doesNotNeedToShowMessage = copied && Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU

    if (doesNotNeedToShowMessage) {
        Timber.v("successful clipboard copy & system informed user of copy")
        return
    }

    val confirmationMessage = if (copied) successMessageId else failureMessageId

    // prefer a snackbar over a toast
    if (this is Activity && canProperlyShowSnackbars()) {
        showSnackbar(confirmationMessage)
    } else {
        showThemedToast(this, confirmationMessage,  shortLength = true)
    }
}

private fun Context.copyTextToClipboard(text: String): Boolean {
    val clipboardManager = this.getSystemService(Activity.CLIPBOARD_SERVICE) as? ClipboardManager
    if (clipboardManager == null) {
        Timber.w("Failed to obtain ClipboardManager")
        return false
    }

    return try {
        clipboardManager.setPrimaryClip(
            ClipData.newPlainText(
                "${VersionUtils.appName} v${VersionUtils.pkgVersionName}",
                text
            )
        )
        true
    } catch (e: Exception) {
        Timber.e("Failed to copy text to clipboard", e)
        false
    }
}
```

Firstly, there was a lot of code which effectively boiled down to setting `copied` to either `true` or `false`
It made the code much more simple to use `Refactor ... Function` to extract the method
That allows for early returns inside the `if` for example, and `return try`


image

After this, my boolean table above takes in 4 inputs, but returns two outputs:
do we want to show a message, or not

Because we only have two outputs, and 1 is 'do nothing', return early on the 'do nothing' case

Now... we want to show a message. Figure out what the message is, then figure out how to show it, preferring a Snackbar
and we're done with the refactor

File: AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt [hunk 2]
```diff
@@ -68,42 +69,39 @@ object ClipboardUtil {
...
+        copied = try {
+            clipboardManager.setPrimaryClip(
+                ClipData.newPlainText(
+                    "${VersionUtils.appName} v${VersionUtils.pkgVersionName}",
+                    text
+                )
+            )
+            true
+        } catch (e: Exception) {
+            Timber.e("Failed to copy text to clipboard", e)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt:95]: The `e` parameter comes first in Timber

Use `Timber.w` for non-fatal errors, not `Timber.e`


```suggestion
            Timber.w(e, "Failed to copy text to clipboard")
```

File: AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt [hunk 3]
```diff
@@ -68,42 +69,39 @@ object ClipboardUtil {
 }
 
 /**
- * Copies the provided text to the clipboard (truncated if necessary)
- * @return `true` if the clipboard is modified. `false` otherwise
+ * Copies the provided [text] to the clipboard (truncated if necessary),
+ * and show either a snackbar, if possible, or a toast in case of API>32,
+ * with the success or failure message.
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt:74]: rephrase this based on what the method does:

* copies the text to the clipboard
* shows a message to the user if the system does not already show a 'copied to clipboard' message
  * This happens for failure or success
* `@param`s are a nice to have here

**Review by david-allison — CHANGES_REQUESTED** [review]
Additional review comments which weren't covered from my large message

Finally: the commit message and maybe a comment should make it clear that `>= T` (or `> S_V2`) is where the system clipboard notification is added

Ideally with a link to reference the Android changelog

**Review by david-allison — APPROVED** [review]
Looks great, thanks!

File: AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt [hunk 4]
```diff
@@ -68,42 +69,54 @@ object ClipboardUtil {
 }
 
 /**
- * Copies the provided text to the clipboard (truncated if necessary)
- * @return `true` if the clipboard is modified. `false` otherwise
+ * Copies the provided [text] to the clipboard (truncated if necessary),
+ * and show either a snackbar, if possible, or a toast with a success/failure
+ * message if the system does not already show a 'copied to clipboard' message
+ * @param text the text that needs to be copied
+ * @param successMessageId message that needs to be shown after successfully coping the text
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt:76]: typo: coping

File: AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt [hunk 5]
```diff
@@ -68,42 +69,54 @@ object ClipboardUtil {
...
+    val confirmationMessage = if (copied) successMessageId else failureMessageId
+
+    if (this is Activity && canProperlyShowSnackbars()) {
+        showSnackbar(confirmationMessage)
+    } else {
+        showThemedToast(this, confirmationMessage, shortLength = true)
+    }
+}
+
+private fun Context.copyTextToClipboard(text: String): Boolean {
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt:103]: why keep two methods for copying stuff to the clipboard?

File: AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt [hunk 6]
```diff
@@ -68,42 +69,54 @@ object ClipboardUtil {
 }
 
 /**
- * Copies the provided text to the clipboard (truncated if necessary)
- * @return `true` if the clipboard is modified. `false` otherwise
+ * Copies the provided [text] to the clipboard (truncated if necessary),
+ * and show either a snackbar, if possible, or a toast with a success/failure
+ * message if the system does not already show a 'copied to clipboard' message
+ * @param text the text that needs to be copied
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt:75]: Add a blank like between the parameters and the text

File: AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt [hunk 7]
```diff
@@ -68,42 +69,54 @@ object ClipboardUtil {
 }
 
 /**
- * Copies the provided text to the clipboard (truncated if necessary)
- * @return `true` if the clipboard is modified. `false` otherwise
+ * Copies the provided [text] to the clipboard (truncated if necessary),
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt:72]: What are the exact situations that the text is going to be truncated? How many chars?

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/viewmodel/TtsVoicesViewModel.kt [hunk 8]
```diff
@@ -178,7 +179,11 @@ class TtsVoicesViewModel : ViewModel() {
     fun copyToClipboard(voice: TtsVoice) {
         // At least in API 33, we do not need to display a snackbar, as the Android OS already
         // displays the copied text
-        AnkiDroidApp.instance.copyToClipboard(voice.toString())
+        AnkiDroidApp.instance.copyToClipboard(
+            text = voice.toString(),
+            successMessageId = R.string.about_ankidroid_successfully_copied_debug_info,
+            failureMessageId = R.string.about_ankidroid_error_copy_debug_info
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/viewmodel/TtsVoicesViewModel.kt:185]: Can't these be default values for the function parameters? This seems repetitive and verbose

**Review by BrayanDSO — CHANGES_REQUESTED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt [hunk 9]
```diff
@@ -88,13 +88,11 @@ class IntentHandler : Activity() {
...
         Timber.i("Copying debug info to clipboard")
-        if (!this.copyToClipboard(intent.getStringExtra(CLIPBOARD_INTENT_EXTRA_DATA)!!)) {
-            Timber.w("Failed to obtain ClipboardManager")
-            showThemedToast(this, R.string.something_wrong, true)
-            return
-        }
-
-        showThemedToast(this, R.string.about_ankidroid_successfully_copied_debug_info, true)
+        this.copyToClipboard(
+            text = (intent.getStringExtra(CLIPBOARD_INTENT_EXTRA_DATA)!!),
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt:92]: Is it possible for `!!` to crash?  If not, add a comment so nobody has to think about it. If yes, handle it.

File: AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt (hunk 5 above)
Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt:103]: Read David's comment above

File: AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt (hunk 7 above)
Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt:72]: When the text we are copying has more than 5 lines, no exact chars are there

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/viewmodel/TtsVoicesViewModel.kt (hunk 8 above)
Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/viewmodel/TtsVoicesViewModel.kt:185]: Success message is fine but not the failure message, just noticed one more mistake I used the debug failure string in TTS

File: AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt (hunk 5 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt:105]: To elaborate, the code beforehand was:

https://github.com/ankidroid/Anki-Android/blob/c63210597cd6dbd281ed017aa5a46a6f45fc7f60/AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt#L76-L100

Too much of the method was obtaining the value of `copied`, and this obscured the additional logic of displaying feedback to the user

File: AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt [hunk 10]
```diff
@@ -68,42 +70,55 @@ object ClipboardUtil {
 }
 
 /**
- * Copies the provided text to the clipboard (truncated if necessary)
- * @return `true` if the clipboard is modified. `false` otherwise
+ * Copies the provided [text] to the clipboard (truncated if necessary, >5 lines),
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt:73]: Where does the source stating the >5 lines restriction come from? I believe that the debug info is way bigger than that

File: AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt (hunk 5 above)
Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt:105]: So please add a javadoc to the method explaining the difference between the two

File: AnkiDroid/src/main/res/values/02-strings.xml [hunk 11]
```diff
@@ -423,4 +423,5 @@ opening the system text to speech settings fails">
     </string>
 
     <string name="shared_decks_login_required">Please log in to download more decks</string>
+    <string name="failed_to_copy_voice">Failed to copy voice</string>
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/res/values/02-strings.xml:426]: I suggest creating a generic string of failing to copy to the clipboard so we don't increase translators' job for strings that are rarely going to be reached

**Review by BrayanDSO — CHANGES_REQUESTED** [review]

File: AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt (hunk 10 above)
Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/utils/ClipboardUtil.kt:73]: It is not officially on Android doc, the link is provided in the commit message but they have a preview of the copy paste and if you try copying the text in valid APIs the number of lines is 5 after that it's.
image

File: AnkiDroid/src/main/res/values/02-strings.xml [hunk 12]
```diff
@@ -423,4 +423,5 @@ opening the system text to speech settings fails">
     </string>
 
     <string name="shared_decks_login_required">Please log in to download more decks</string>
+    <string name="failed_to_copy_voice">Failed to copy</string>
```
Comment (mikehardy) [inline AnkiDroid/src/main/res/values/02-strings.xml:426]: This is no longer voice-related, altering key slightly

```suggestion
    <string name="failed_to_copy">Failed to copy</string>
```

**Review by mikehardy — APPROVED** [review]
LGTM - I believe you addressed Brayan's comments with exception of strings key remaining a little non-generic

**Comment by mikehardy** [comment]
Sorry @criticalAY I just obliterated your change there with a force-push, didn't see you were also working in there but I was operating on the principle of "you break it you buy it" since I waded in and changed the key name then (ridiculously...) forgot to change the key name ref in the code

cleaned up the conflict locally at the same time - I imagine you did both of those as well :-)

Anyway, I expect this will go green now and be ready
