### PR TITLE
SchedV2: Fix "Start of Day" not being set

### LINKED ISSUE #6203: "Start of next day" not used by SchedV2
###### Reproduction Steps

1. Set the daily rollover time to something different from the default, like 6 hours after midnight
2. Learn into the night/morning
3. Check the decks/notes before and after 4am

###### Expected Result
The decks/cards should reset at 6am

###### Actual Result
The decks/cards still reset at 4am

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description
SchedV2 introduced the concept of a "rollover" time. We did read this in SchedV2, but we did not set it in the settings.

We now set this value

⚠️ This also changes the Notification Service: We now default a new day to 4AM instead of Midnight for a notification if:
* there is an error loading the "start of new day"
* "start of new day" was not explicitly set

I chose this because the preference would use the "starts of new day" value if it was set.

## Fixes
Fixes #6203 

## Approach

* set "rollover" if the scheduler is v2
* Use "rollover" in the BootService if sched v2 is set

Replicating the logic in: https://github.com/ankitects/anki/commit/b17a0552d061af360e35e1cda48b2d228c94b66e

## How Has This Been Tested?

⚠️ This is a change which is hard to test
* minimally tested manually to ensure that it doesn't crash
* some unit tests, 
 
I don't feel these guarantee correctness. A thorough review, or further test plan would help put my mind at ease

## Learning (optional, can help others)

https://github.com/ankitects/anki/commit/b17a0552d061af360e35e1cda48b2d228c94b66e - Anki commit that we replicate

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by mikehardy** [comment]
Requesting @Arthur-Milchior review along with myself as high priority because in my mind this is *I think* the only 2.15 blocker item left - the rest of the stuff in the 2.15 milestone will likely punt off to 2.16 but I really want the timezone handling to match Anki Desktop and this is it I think

File: AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java [hunk 1]
```diff
@@ -597,6 +597,7 @@ private void initPreference(android.preference.Preference pref) {
         updateSummary(pref);
     }
 
+    /** Returns the hour that the collection rolls over */
     @VisibleForTesting
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java:601]: Is it still just VisibleForTesting if Stats is calling Preferences.getDayOffset?

**Review by mikehardy — APPROVED** [review]
This all seems fine to me and I'm excited to see it go in - I'm not sure how else you could test it? I had one tiny nit about removing a test-related annotation and that's it, I consider it good to go

File: AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java (hunk 1 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java:601]: Is it worth enabling this lint rule?

https://github.com/ankidroid/Anki-Android/blob/8ea9640cb4e7ad99a67d0e78ec75993f237d4029/lint-release.xml#L309

File: AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java [hunk 2]
```diff
@@ -599,20 +599,44 @@ private void initPreference(android.preference.Preference pref) {
 
     @VisibleForTesting
     public static int getDayOffset(Collection col) {
-        Calendar calendar = col.crtGregorianCalendar();
-        return calendar.get(Calendar.HOUR_OF_DAY);
+        switch (col.schedVer()) {
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java:602]: I'd be of the opinion that it would be nicer to have this as a function from the scheduler instead. that makes more sens than a switch over two values

File: AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java [hunk 3]
```diff
@@ -599,20 +599,44 @@ private void initPreference(android.preference.Preference pref) {
...
+        }
     }
 
     @VisibleForTesting
     public void setDayOffset(int hours) {
-        Calendar date = getCol().crtGregorianCalendar();
-        date.set(Calendar.HOUR_OF_DAY, hours);
-        getCol().setCrt(date.getTimeInMillis() / 1000);
-        getCol().setMod();
+        switch (getSchedVer(getCol())) {
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java:614]: same

**Review by Arthur-Milchior — APPROVED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java (hunk 2 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java:602]: Would you be happy with anywhere other than `libAnki`: all the additional functions that we've added or modified are slowing down the conversion by a considerable amount
