### PR TITLE
Minor refactorings and SQL window size calculation fixed

### LINKED ISSUE #8421: [Minor Bug] SQL window size calculation
https://github.com/ankidroid/Anki-Android/blob/1476aa95bd5e5b69a9b8329747b999b200b815b4/AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java#L333-L335 will return 0 if it's hit - not what we're expecting. Theoretical bug as it hasn't hit us.

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/issues/6040#issuecomment-811613816_

### PR DESCRIPTION
**Pull request by Vaibhavi1707**
## Purpose
The method `getChunk()` in Collection.java, returned zero as SQL window size if the object `db` is an instance of `DatabaseChangeDecorator`. This had to be changed to the default SQL window size. 

## Fixes
Fixes #8421 

## Approach
In the condition faced in the issue, it should return the value which is calculated considering the default SQL window size. This is because the condition that `db_name` equals to "io.requery.android.database.sqlite.SQLiteDatabase"  will not be satisfied as `db_name` doesn't exist. 

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Review by mikehardy — CHANGES_REQUESTED** [review]
Please stay focused on the single problem - the refactor is unwelcome here in my opinion - it is something different to review and test, and either way, whether people consider breaks "unnecessary" or not is down to a preference.

The bugfix is good though, I'd like to see a clean focused PR that is just the DB chunk bugfix please

**Comment by Vaibhavi1707** [comment]
Okay

File: AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java [hunk 1]
```diff
@@ -367,7 +366,7 @@ public String loadColumn(String columnName) {
                 }
                 String res = cursor.getString(0);
                 if (res.length() == 0) {
-                      break;
+                    break;
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java:369]: Please understand I am being really picky on purpose :-), because we really want the attitude of "PRs solve one problem in a clean way" to be observed by all new contributors.

I mention that because I like this PR, and I want to see it merge - but these two lines, they are not related to your task, and there should be no changes here.

Just the bug fix please :pray:  :-)

**Review by mikehardy — CHANGES_REQUESTED** [review]

File: AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java (hunk 1 above)
Comment (Vaibhavi1707) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java:369]: I added a commit to restore the break statements and removing unnecessary comments. I'll remember focussing on my task in my next PR. I am really sorry for the intrusion.

Comment (Vaibhavi1707) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java:369]: Is it fine now?

Comment (Vaibhavi1707) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java:369]: https://github.com/ankidroid/Anki-Android/pull/8433/commits/5683df0d00b32f6dac31df61e9fe8bb9b09248da The commit I pushed

Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java:369]:
```suggestion
                      break;
```

it's not fully reverted yet. This restores the line to the previous state so it will not appear in the diff I think

File: AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java [hunk 2]
```diff
@@ -330,11 +330,9 @@ private int getChunk() {
...
         // as a ceiling. Try it, with a reasonable fallback in case of failure
         SupportSQLiteDatabase db = mDb.getDatabase();
-        if (! (db instanceof DatabaseChangeDecorator)) {
-            return sChunk;
-        }
-        String db_name = ((DatabaseChangeDecorator) db).getWrapped().getClass().getName();
-        if ("io.requery.android.database.sqlite.SQLiteDatabase".equals(db_name)) {
+        String db_name = (db instanceof DatabaseChangeDecorator) ? ((DatabaseChangeDecorator) db).getWrapped().getClass().getName() : null;
+
+        if (db_name != null && "io.requery.android.database.sqlite.SQLiteDatabase".equals(db_name)) {
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java:335]: Because we use the style of "constant string first in string comparison" you don't need the null check (that is the whole point of the constant string first actually: it avoids null pointers) so you can do it like this:

```suggestion
        if ("io.requery.android.database.sqlite.SQLiteDatabase".equals(db_name)) {
```

**Review by mikehardy — CHANGES_REQUESTED** [review]
Okay - I fixed that unrelated spacing for you so that it is not a blocker and we can move forward, as I said I was being really picky on purpose and I recognize that, and now I know you understand, so no need to waste time on it further here ;-)

The last change I can think of is also just a style issue but it's a neat Java trick and worth examining I think as it is in our style guide to do comparisons the way I suggest

What do you think?

File: AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java (hunk 2 above)
Comment (Vaibhavi1707) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java:335]: Yes, this looks good. I added the null check as I thought it'd give a NullPointerException. But now I'm clear that it won't.

Comment (Vaibhavi1707) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java]: Thanks for the suggestion. It's been a good learning so far contributing to AnkiDroid :)

**Review by mikehardy — APPROVED** [review]
This is now a really clean, really focused change :-)
Thanks @Vaibhavi1707 !

**Review by david-allison-1 — APPROVED** [review]
LGTM! Thanks

**Comment by Vaibhavi1707** [comment]
Thanks for the support!
