### PR TITLE
fix: potential storage leak in AudioRecorder

### LINKED ISSUE #20381: Potential storage leak in audio recording `createTempFile`
##Description
During the implementation of the new recording logic, it was noted that createTempFile() generates files in the cacheDir without a defined cleanup strategy inspect.

OP: David 
```
What's the lifecycle of this file and who is responsible for cleanup?

Feel free to peel this one off into an issue
```

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/pull/19911#discussion_r2660695544_

### PR DESCRIPTION
**Pull request by criticalAY**
## Purpose / Description
Here I want to addresses concerns regarding the lifecycle and cleanup of temporary recording files. Previously, files created in the cacheDir could persist indefinitely.

## Fixes
* Fixes #20381

## Approach
NA

## How Has This Been Tested?
Added Unit tests

## Learning (optional, can help others)
NA

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/recorder/AudioRecorder.kt [hunk 1]
```diff
@@ -125,18 +127,27 @@ class AudioRecorder(
...
         } catch (e: RuntimeException) {
             Timber.w(e, "Failed to stop recorder: likely called too soon after start")
-            currentFile?.delete()
-            currentFile = null
+            deleteCurrentFile()
         } finally {
             isRecording = false
+
+            if (!keepFile && isTempFile) {
+                deleteCurrentFile()
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/recorder/AudioRecorder.kt:144]: why not using the standard `.deleteOnExit()` method?

Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/recorder/AudioRecorder.kt:144]: We aren't actually shutting down the VM, but just calling stop and the documentation states that we should use our custom method which is exactly we are doing in stop block. For this piece of block I find the current approach better than `.deleteOnExit()`
