### PR TITLE
Regression tests for CustomStudyDialog JSON output

### LINKED ISSUE #6289: AnkiDroid is creating broken custom study decks
A bunch of users have been reporting an error like the following:

https://anki.tenderapp.com/discussions/ankidesktop/41865-error

ec7b0356bdc6217212832bfd75a4853a6b476051 appears to be the cause - https://github.com/ankidroid/Anki-Android/blob/c6291ef91fdb2fc85bd852702541d0fad2257ed3/AnkiDroid/src/main/java/com/ichi2/utils/JSONObject.java#L15 is assigning to itself, causing it to be a null rather than a JSONObject.null, and a call in customstudy to dyn.put("delays", JSONObject.null) results in the key being missing. 

@Arthur-Milchior heads up

### PR DESCRIPTION
**Pull request by david-allison-1**
Adds more regression cover.

Fragment testing is much more complex than I'd expected, especially as we use the containing activity to access the collection.

At some point in the future:tm: we should move to a more self-contained and testable model.

Fixes #6289

### CODE REVIEW

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java  1
- AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5594895&bid=18328131)

File: AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java [hunk 1]
```diff
@@ -0,0 +1,111 @@
...
+
+        //Pick an arbitrary easy activity
+        CustomStudyActivity d = super.startActivityNormallyOpenCollectionWithIntent(CustomStudyActivity.class, new Intent());
+
+        scenario.onFragment(f -> f.setActivity(d));
+        return scenario;
+    }
+
+    private static class CustomStudyActivity extends  CardTemplateBrowserAppearanceEditor
+            implements com.ichi2.anki.dialogs.CustomStudyDialog.CustomStudyListener {
```
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java:82]: Codacy Issue found: [Unnecessary use of fully qualified name 'com.ichi2.anki.dialogs.CustomStudyDialog.CustomStudyListener' due to existing same package import 'com.ichi2.anki.dialogs.*'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5594895)

File: AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java [hunk 2]
```diff
@@ -0,0 +1,111 @@
...
+
+        @Override
+        public void onCreateCustomStudySession() {
+
+        }
+
+
+        @Override
+        public void onExtendStudyLimits() {
```
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java:91]: Codacy Issue found: [Document empty method body](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5594895)

File: AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java [hunk 3]
```diff
@@ -0,0 +1,111 @@
...
+    public static class CustomStudyDialogForTesting extends CustomStudyDialog {
+        private AnkiActivity mAnkiActivity;
+
+        @SuppressWarnings("WeakerAccess")
+        public <T extends AnkiActivity & CustomStudyListener> void setActivity(T ankiActivity) {
+            mAnkiActivity = ankiActivity;
+        }
+
+
+        @Override
```
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java:106]: Codacy Issue found: [Use explicit scoping instead of the default package private level](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5594895)

File: AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java [hunk 4]
```diff
@@ -0,0 +1,111 @@
...
+
+        scenario.onFragment(f -> f.setActivity(d));
+        return scenario;
+    }
+
+    private static class CustomStudyActivity extends  CardTemplateBrowserAppearanceEditor
+            implements com.ichi2.anki.dialogs.CustomStudyDialog.CustomStudyListener {
+
+        @Override
+        public void onCreateCustomStudySession() {
```
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java:85]: Codacy Issue found: [Document empty method body](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5594895)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java  1
- AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5594895&bid=18328131)

File: AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java [hunk 5]
```diff
@@ -0,0 +1,112 @@
...
+
+        }
+
+
+        @Override
+        public void onExtendStudyLimits() {
```
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java:92]: Codacy Issue found: [Document empty method body](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5594895)

File: AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java [hunk 6]
```diff
@@ -0,0 +1,112 @@
...
+
+        scenario.onFragment(f -> f.setActivity(d));
+        return scenario;
+    }
+
+    private static class CustomStudyActivity extends  CardTemplateBrowserAppearanceEditor
+            implements com.ichi2.anki.dialogs.CustomStudyDialog.CustomStudyListener {
+
+        @Override
+        public void onCreateCustomStudySession() {
```
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java:86]: Codacy Issue found: [Document empty method body](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5594895)

File: AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java [hunk 7]
```diff
@@ -0,0 +1,112 @@
...
+    public static class CustomStudyDialogForTesting extends CustomStudyDialog {
+        private AnkiActivity mAnkiActivity;
+
+        @SuppressWarnings("WeakerAccess")
+        public <T extends AnkiActivity & CustomStudyListener> void setActivity(T ankiActivity) {
+            mAnkiActivity = ankiActivity;
+        }
+
+
+        @Override
```
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java:107]: Codacy Issue found: [Use explicit scoping instead of the default package private level](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5594895)

File: AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java [hunk 8]
```diff
@@ -0,0 +1,112 @@
...
+
+        //Pick an arbitrary easy activity
+        CustomStudyActivity d = super.startActivityNormallyOpenCollectionWithIntent(CustomStudyActivity.class, new Intent());
+
+        scenario.onFragment(f -> f.setActivity(d));
+        return scenario;
+    }
+
+    private static class CustomStudyActivity extends  CardTemplateBrowserAppearanceEditor
+            implements com.ichi2.anki.dialogs.CustomStudyDialog.CustomStudyListener {
```
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java:83]: Codacy Issue found: [Unnecessary use of fully qualified name 'com.ichi2.anki.dialogs.CustomStudyDialog.CustomStudyListener' due to existing same package import 'com.ichi2.anki.dialogs.*'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5594895)

File: AnkiDroid/build.gradle [hunk 9]
```diff
@@ -168,6 +168,9 @@ dependencies {
     testImplementation "org.robolectric:robolectric:4.3.1"
     testImplementation 'androidx.test:core:1.2.0'
     testImplementation 'androidx.test.ext:junit:1.1.1'
+    //apparently required for testing fragments :/
+    //https://issuetracker.google.com/issues/122321150
```
Comment (mikehardy) [inline AnkiDroid/build.gradle:172]: Fascinating bug thread(s) there. For me I had to read those in order to answer the question I had, so I'd like the comment to distill it and answer the question directly, also the real tracking issue is different

```suggestion
    // debugImplementation required vs testImplementation: https://issuetracker.google.com/issues/128612536
```

Finally, I actually use standard lint rule packs in other languages and it's not a big deal but I wonder about your 'comment slashes with no space after' style - it's visually jarring to me and linted out via my standard packages. Is this important to you? If not, I humbly submit I prefer '// then comment' :-)

Comment (david-allison-1) [reply AnkiDroid/build.gradle:172]: The horrors of being a self-taught programmer. Just wait until you catch me using Allman-style braces 😉

Can we start up a wiki page or issue about these nits? Better to encode these into autolint settings, rather than add PR comments.

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java  1
- AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5594895&bid=18328131)

File: AnkiDroid/build.gradle (hunk 9 above)
Comment (mikehardy) [reply AnkiDroid/build.gradle]: Yes we can (go for it hahaha) - honestly it should all be in codacy, driven by a checkstyle or pmd xml that Android Studio reads. I think there actually is a coding standards document even? In the codebase?

Comment (david-allison-1) [reply AnkiDroid/build.gradle]: https://github.com/ankidroid/Anki-Android/blob/master/docs/code_conventions/AnkiDroid_code_conventions.html ... I missed that.

Comment (david-allison-1) [reply AnkiDroid/build.gradle]: ... we should probably have an Anki deck for this

**Comment by david-allison-1** [comment]
We've hit the multidex limit with the new dependency

**Comment by mikehardy** [comment]
May I beg :pray:  for you to apply the canonical MultiDex change? 

https://github.com/mikehardy/rnfbdemo/blob/9894256b3cc5d41a7feef0e10a18e497cbeeca36/make-demo-v6.sh#L125-L134

**Comment by david-allison-1** [comment]
> May I beg 🙏 for you to apply the canonical MultiDex change?
> 
> https://github.com/mikehardy/rnfbdemo/blob/9894256b3cc5d41a7feef0e10a18e497cbeeca36/make-demo-v6.sh#L125-L134

I've done it before. Do we want to, given the impact it'll have on apk size?

**Comment by mikehardy** [comment]
I don't recall it having a large impact on APK size? And am not in general concerned about our APK size at the moment, it's pretty tiny. We could be twice our size and still half the size of most apps at this point

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java  1
- AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5594895&bid=18328131)

**Comment by david-allison-1** [comment]
Before: 13.3MB - https://github.com/ankidroid/Anki-Android/releases/tag/v2.11alpha8

**Comment by david-allison-1** [comment]
Travis fails < API 21:

```
:AnkiDroid:connectedDebugAndroidTestcom.android.builder.testing.ConnectedDevice > No tests found.[test(AVD) - 4.1.2] FAILED 
No tests found. This usually means that your test classes are not in the form that your test runner expects (e.g. don't inherit from TestCase or lack @Test annotations).
```

**Comment by david-allison-1** [comment]
Fails on my API16 emulator. Running individual tests work.

Nothing useful from Googling so far.

Removed `DdmPreferences.setTimeOut(120000) // apparently if not multidex you do this`

**Comment by mikehardy** [comment]
I noted that yesterday but hoped you'd see immediate success when you checked it today ;-)
Most strange this effect. I've seen problems like that before (used to be one of the APIs, I think 26?) did it so I disabled that one. I have a weak memory of relation to the test orchestrator. I also note that I just saw in the androidx release notes that the test libraries have updates in the pipeline I believe the are beta or rc at this point, perhaps moving forward on the test dependencies would help, or using the nonstable channel for emulator installs to get a newer emulator

**Comment by david-allison-1** [comment]
Tried with

```
    testImplementation 'org.junit.vintage:junit-vintage-engine:5.6.2'
    testImplementation 'org.mockito:mockito-core:3.3.3'
    testImplementation 'org.powermock:powermock-core:2.0.7'
    testImplementation 'org.powermock:powermock-module-junit4:2.0.7'
    testImplementation 'org.powermock:powermock-api-mockito2:2.0.7'
    testImplementation 'org.hamcrest:hamcrest-all:1.3'
    testImplementation 'net.lachlanmckee:timber-junit-rule:1.0.1'
    testImplementation "org.robolectric:robolectric:4.3.1"
    testImplementation 'androidx.test:core:1.3.0-beta02'
    testImplementation 'androidx.test.ext:junit:1.1.2-beta02'
    // debugImplementation required vs testImplementation: https://issuetracker.google.com/issues/128612536
    debugImplementation 'androidx.fragment:fragment-testing:1.3.0-alpha05'

    // May need a resolution strategy for support libs to our versions
    androidTestImplementation 'com.azimolabs.conditionwatcher:conditionwatcher:0.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-contrib:3.2.0'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2-beta02'
    androidTestImplementation 'androidx.test:rules:1.2.0'
```

No luck. The documentation for upgrading the emulator seems sparse - is this included in the Android Studio Canary channel?

**Comment by mikehardy** [comment]
for emulator if you look at git blame / history on .travis.yml you'll see I had channel=4 (IIRC?) for a while on the emulator install line which is as you say yes - enables canary channel.

This is a throw spaghetti at the wall approach though - just trying bleeding edge of everything to see if we're chasing something already fixed but I assign low probability unfortunately. Had higher hopes on the test dependencies, sad those didn't work

**Comment by mikehardy** [comment]
My strongest hypothesis is that the fragment thing has brought in some reimplementation of test objects somehow ?

This comment was interesting that the commenter was able to work around the issue with excludes relative to a gradle dependency https://github.com/tomakehurst/wiremock/issues/931#issuecomment-386381091 - I wonder if some sort of strategy like that would be the answer. Hard to test apart the fragment and the multidex - I wonder if inspecting those specific jars (and/or do they have transitive deps? ugh) might be illuminating. Problems like this are not a lot of fun

**Comment by mikehardy** [comment]
This one was interesting from perspective of using orchestrator and debugging the runner class, you indicated you reproduced locally, perhaps this could be a path to more diagnostics? Most interesting part to me was that the runner crash was hidden until more inspection was added, and it was visible in logcat if I read correctly? https://github.com/cucumber/cucumber-android/issues/22

**Comment by mikehardy** [comment]
@david-allison-1 maybe found it? https://developer.android.com/studio/build/multidex.html?hl=en#testing

**Comment by david-allison-1** [comment]
> This one was interesting from perspective of using orchestrator and debugging the runner class, you indicated you reproduced locally, perhaps this could be a path to more diagnostics? Most interesting part to me was that the runner crash was hidden until more inspection was added, and it was visible in logcat if I read correctly? [cucumber/cucumber-android#22](https://github.com/cucumber/cucumber-android/issues/22)

Nothing in the logcat, but... one of my testing steps (using a custom runner) failed due to a ClassNotFoundException. That might be the cause, so I'm looking into this now.

**Comment by david-allison-1** [comment]
`TestRequestBuilder` uses `ClassPathScanner` which uses `DexFile`, which seems to open `.apk`, but not `dex` on API 16. When it opens an APK, it only picks `classes.dex`.

Moving to an API 23 emulator to compare the differences.

**Comment by david-allison-1** [comment]
This can be fixed. This involves overriding the following in an API < 21 context:

`ClassPathScanner::Enumeration<String> getDexEntries(DexFile dexFile)`

Note: the following test hardcoded one class name, and needs a lot of work before being production-ready
https://github.com/david-allison-1/Anki-Android/commit/d402cd9a4963fef951083fd24d484c2567d1750f

https://travis-ci.com/github/david-allison-1/Anki-Android/builds/168671888

**Comment by david-allison-1** [comment]
> @david-allison-1 maybe found it? https://developer.android.com/studio/build/multidex.html?hl=en#testing
> 
> (from [tmurakami/dexopener#7 (comment)](https://github.com/tmurakami/dexopener/issues/7#issuecomment-316000078))

We use `AndroidJUnitRunner` already. I didn't have any luck with the steps mentioned on my local machine, but that could be due to instability in the instrumentation tests/emulators.
 
Just posted a build to Travis, fingers crossed that's the end of the saga and I don't need to delve into MultiDex classloader territory: https://travis-ci.com/github/david-allison-1/Anki-Android/builds/168777106

File: AnkiDroid/src/androidTest/java/androidx/test/internal/runner/MultiDexClassPathScanner.java [hunk 10]
```diff
@@ -0,0 +1,153 @@
...
+        List<String> ret = new ArrayList<>();
+        try {
+            DexBackedDexFile dex = DexFileFactory.loadDexFile(dexPath, Build.VERSION.SDK_INT);
+            for (ClassDef classDef: dex.getClasses()) {
+                String typeName = extractTypeNameFromDef(classDef);
+                ret.add(typeName);
+            }
+
+        } catch (IOException e) {
+            throw new RuntimeException(e.getLocalizedMessage(), e);
```
Comment (timrae) [inline AnkiDroid/src/androidTest/java/androidx/test/internal/runner/MultiDexClassPathScanner.java:86]: Codacy Issue found: [Avoid throwing raw exception types.](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5594895)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java  1
- AnkiDroid/src/androidTest/java/androidx/test/runner/MultiDexJUnitRunner.java  1
- AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.java  1
- AnkiDroid/src/androidTest/java/androidx/test/internal/runner/MultiDexTestRequestBuilder.java  2
- AnkiDroid/src/androidTest/java/androidx/test/internal/runner/MultiDexClassPathScanner.java  13
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5594895&bid=18328131)

File: AnkiDroid/src/androidTest/java/androidx/test/internal/runner/MultiDexTestRequestBuilder.java [hunk 11]
```diff
@@ -0,0 +1,49 @@
...
+
+    public MultiDexTestRequestBuilder(Instrumentation instr, Bundle arguments) {
+        super(instr, arguments);
+
+        this.mContext = instr.getTargetContext();
+    }
+
+
+
+    @Override
```
Comment (timrae) [inline AnkiDroid/src/androidTest/java/androidx/test/internal/runner/MultiDexTestRequestBuilder.java:42]: Codacy Issue found: [Use explicit scoping instead of the default package private level](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5594895)

File: AnkiDroid/src/androidTest/java/androidx/test/internal/runner/MultiDexClassPathScanner.java [hunk 12]
```diff
@@ -0,0 +1,153 @@
...
+    }
+
+
+    private List<String> extractDexFilesFromApk(String path, String targetDirectory) {
+        //Modified from Utils.unzipFiles
+        ZipFile zip;
+        try {
+            zip = new ZipFile(new File(path), ZipFile.OPEN_READ);
+        } catch (IOException e) {
+            throw new RuntimeException(e);
```
Comment (timrae) [inline AnkiDroid/src/androidTest/java/androidx/test/internal/runner/MultiDexClassPathScanner.java:116]: Codacy Issue found: [Avoid throwing raw exception types.](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5594895)

File: AnkiDroid/src/androidTest/java/androidx/test/internal/runner/MultiDexClassPathScanner.java [hunk 13]
```diff
@@ -0,0 +1,153 @@
...
+
+    public MultiDexClassPathScanner(List<String> classPath, Context targetContext) {
+        super(classPath);
+        //There's no accessor in the base class.
+        this.classPathEntries = classPath;
+        //We need context to get a temporary folder to store our extracted dex files.
+        this.targetContext = targetContext;
+    }
+
+    @Override
```
Comment (timrae) [inline AnkiDroid/src/androidTest/java/androidx/test/internal/runner/MultiDexClassPathScanner.java:60]: Codacy Issue found: [Use explicit scoping instead of the default package private level](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5594895)

File: AnkiDroid/src/androidTest/java/androidx/test/runner/MultiDexJUnitRunner.java [hunk 14]
```diff
@@ -0,0 +1,46 @@
...
+    // TODO: See if we can check the number of executed tests on a full run, and ensure this exceeds a threshold.
+    // as instrumentation runs on my local machine occasionally fail to load com.ichi2.anki
+
+    @Override
+    public void onCreate(Bundle arguments) {
+        MultiDex.installInstrumentation(getContext(), getTargetContext());
+        super.onCreate(arguments);
+    }
+
+    @Override
```
Comment (timrae) [inline AnkiDroid/src/androidTest/java/androidx/test/runner/MultiDexJUnitRunner.java:42]: Codacy Issue found: [Use explicit scoping instead of the default package private level](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5594895)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- AnkiDroid/src/androidTest/java/androidx/test/internal/runner/MultiDexTestRequestBuilder.java  2
- AnkiDroid/src/androidTest/java/androidx/test/internal/runner/MultiDexClassPathScanner.java  13
- AnkiDroid/src/test/java/com/ichi2/anki/dialogs/CustomStudyDialogTest.java  1
- AnkiDroid/src/test/java/com/ichi2/utils/JSONObjectTest.java  1
- AnkiDroid/src/androidTest/java/androidx/test/runner/MultiDexJUnitRunner.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5594895&bid=18328131)

File: AnkiDroid/src/androidTest/java/androidx/test/internal/runner/MultiDexClassPathScanner.java [hunk 15]
```diff
@@ -0,0 +1,156 @@
...
+    }
+
+
+    private List<String> extractDexFilesFromApk(String path, String targetDirectory) {
+        //Modified from Utils.unzipFiles
+        ZipFile zip;
+        try {
+            zip = new ZipFile(new File(path), ZipFile.OPEN_READ);
+        } catch (IOException e) {
+            throw new RuntimeException(e);
```
Comment (timrae) [inline AnkiDroid/src/androidTest/java/androidx/test/internal/runner/MultiDexClassPathScanner.java:119]: Codacy Issue found: [Avoid throwing raw exception types.](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5594895)

File: AnkiDroid/src/androidTest/java/androidx/test/internal/runner/MultiDexClassPathScanner.java [hunk 16]
```diff
@@ -0,0 +1,156 @@
...
+        List<String> ret = new ArrayList<>();
+        try {
+            DexBackedDexFile dex = DexFileFactory.loadDexFile(dexPath, Build.VERSION.SDK_INT);
+            for (ClassDef classDef: dex.getClasses()) {
+                String typeName = extractTypeNameFromDef(classDef);
+                ret.add(typeName);
+            }
+
+        } catch (IOException e) {
+            throw new RuntimeException(e.getLocalizedMessage(), e);
```
Comment (timrae) [inline AnkiDroid/src/androidTest/java/androidx/test/internal/runner/MultiDexClassPathScanner.java:89]: Codacy Issue found: [Avoid throwing raw exception types.](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5594895)

**Comment by david-allison-1** [comment]
https://travis-ci.org/github/ankidroid/Anki-Android/jobs/692899913 - 44 tests executed. 

Looks good to go from a CI perspective. It's likely we'll need to add a few more deprecation suppression in the next few versions as `ClassPathScanner` is likely to go.

**Comment by david-allison-1** [comment]
This has already caught an error in a PR - looks like all that effort paid off.

**Comment by mikehardy** [comment]
testing harnesses are amazing that way - seems like endless work but oh yes, there is payoff
