### PR TITLE
Setting the time constraint in double back press to exit/return feature of DeckPicker and AbstractFlashCardViewer

### LINKED ISSUE #10638: [Bug] Press-back count isn't reset when returning to `Decks` screen
Thanks to developers.

###### Reproduction Steps

1. `Settings` -> `Advanced` > Check `Press back twice to go back/exit`
  image

2. Return to `Decks` screen
3. Press (Tap) `Back` button
   (Then, `Press back again to exit` toast is shown)
   image

5. Tap a deck
  (Then, `Study screen` is shown. After this step, it is OK to answer some cards, as a natural behavior for ordinary users)

6. Return to `Decks` screen
7.  Press (Tap) `Back` button

###### Expected Result
`Press back again to exit` toast is shown, as on step 3 above.

###### Actual Result
AnkiDroid is closed.

https://user-images.githubusercontent.com/10436072/160282297-2d7e66be-afb3-44bf-b5b1-b31821b489d2.mp4

###### Debug info
```
AnkiDroid Version = 2.16alpha53

Android Version = 9

Manufacturer = OPPO

Model = CPH1983

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 9; CPH1983 Build/PKQ1.190519.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.58 Mobile Safari/537.36

ACRA UUID = 057cd16c-e7f1-4e0c-a259-8401e998e532

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by UvrajSB**
## Purpose / Description
Double back pressed to exit feature wasn't working properly.

## Fixes
Fixes #10638 

## Approach
The variable storing the number of back pressed wasn't getting reset when we were moving to the next activity. So I reset the variable in the onPause function of the activity.

## How Has This Been Tested?

Physical Device: Realme 8i

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

In the video, I have demonstrated that it requires two back presses to exit the app and then in the next turn I went to a different activity and came back to the original and still it took two back presses not one which was the issue I resolved

https://user-images.githubusercontent.com/73571511/161382224-d1eadb3a-ad47-40ed-b989-58b47da6c197.mp4

### CODE REVIEW

**Comment by prateek-singh-3212** [comment]
Thanks @UvrajSB for contributing to ankidroid. Can you attach the video describing the fix of this issue?

**Comment by UvrajSB** [comment]
> Thanks @UvrajSB for contributing to ankidroid. Can you attach the video describing the fix of this issue?
Done

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java [hunk 1]
```diff
@@ -909,6 +909,7 @@ public void onRestoreInstanceState(Bundle savedInstanceState) {
     @Override
     protected void onPause() {
         Timber.d("onPause()");
+        mBackButtonPressedToExit = false;
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java:912]: Why do we want `onPause` rather than `onStop`?

Comment (UvrajSB) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java:912]: 1) Because onPause will cover all the cases of onStop callback as onStop is never called without onPause.
2) In case when a dialog box appears the UI (Activity) is still partially visible and just onPause() is called. So in case the user clicks on the back button and then opens up some dialog box and closes it back (or a dialog box pops up on its own) the count of back presses will not change if we use onStop() so I used onPause()

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java:912]: Solid defense, I think I agree with onPause as a choice

**Review by mikehardy — APPROVED** [review]

**Comment by mikehardy** [comment]
A thought - is this also useful in AbstractFlashcardViewer? It has the same feature - these two locations are the only places it exists tho https://github.com/ankidroid/Anki-Android/blob/c3c42cd59738ec461c805483e91221d7750a92fd/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L235

**Comment by UvrajSB** [comment]
> A thought - is this also useful in AbstractFlashcardViewer? It has the same feature - these two locations are the only places it exists tho
> 
> https://github.com/ankidroid/Anki-Android/blob/c3c42cd59738ec461c805483e91221d7750a92fd/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L235

According to my understanding,
We don't need to the same thing in this case because
1) In last case i.e. of DeckPicker Activity, we were going to the next activity and coming back but here we are on the same activity and its no longer a problem of the activity stack.
2) Moreover, whenever answer is displayed or question is changed mBackButtonPressedToReturn is set false in the code already
[Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java](https://github.com/ankidroid/Anki-Android/blob/c3c42cd59738ec461c805483e91221d7750a92fd/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L1550)


[Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java](https://github.com/ankidroid/Anki-Android/blob/c3c42cd59738ec461c805483e91221d7750a92fd/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L1584)

**Comment by UvrajSB** [comment]
I have also resolved issue #10634 in this pr

**Comment by david-allison** [comment]
Looks good, but please aim for 1 pull request per issue

**Comment by UvrajSB** [comment]
I have added the time constraint to press the back key second time such that if a user presses back key once and then doesn't presses it under next 2sec (i.e. the time duration of the Toast.LENGTH_SHORT) then the counter of the back press resets itself back to zero.

**Comment by UvrajSB** [comment]
> A thought - is this also useful in AbstractFlashcardViewer? It has the same feature - these two locations are the only places it exists tho
> 
> https://github.com/ankidroid/Anki-Android/blob/c3c42cd59738ec461c805483e91221d7750a92fd/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L235

@mikehardy 
Yes there also we should add the same time constraint, do you want me to add this it in the same PR or do you want me to open a new issue and then do a pr over there?

**Comment by mikehardy** [comment]
It's the same feature to me I think keeping it in this PR for consolidated discussion is best
This changes the feature somewhat and I'm not sure if 2sec (even if it has a reference in the duration of the toast) is really what we want. It might be - it very well might be the best value - but I'm curious for other's opinions just in case, since it is qualitative)

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 2]
```diff
@@ -810,6 +811,12 @@ public void onBackPressed() {
                 UIUtils.showThemedToast(this, getString(R.string.back_pressed_once_reviewer), true);
             }
             mBackButtonPressedToReturn = true;
+            new Handler(Looper.getMainLooper()).postDelayed(new Runnable() {
+                @Override
+                public void run() {
+                    mBackButtonPressedToReturn=false;
+                }
+            }, 2000);
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:819]: I feel like this should be a constant somewhere and just referenced here. I think we have a Constants file, could put it in there and just statically import it then reference it here

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java [hunk 3]
```diff
@@ -970,6 +973,12 @@ public void onBackPressed() {
                     UIUtils.showThemedToast(this, getString(R.string.back_pressed_once), true);
                 }
                 mBackButtonPressedToExit = true;
+                new Handler(Looper.getMainLooper()).postDelayed(new Runnable() {
+                    @Override
+                    public void run() {
+                        mBackButtonPressedToExit=false;
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java:979]:
```suggestion
                        mBackButtonPressedToExit = false;
```

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java [hunk 4]
```diff
@@ -970,6 +973,12 @@ public void onBackPressed() {
...
+                    }
+                }, 2000);
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java:981]: same thought that this should be a constant. Perhaps we already have a toast length constant, or there is a toast length constant we may refer to, since we are tying it to that?

**Review by mikehardy — CHANGES_REQUESTED** [review]
minor change requests, but the java->kotlin migration thing is obviously a major change for the PR, even if it is hopefully easier to handle

This looks good though as a solution the UX issue of otherwise-infinite 2-back-press time window

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt [hunk 5]
```diff
@@ -2520,7 +2524,7 @@ abstract class AbstractFlashcardViewer : NavigationDrawerActivity(), ReviewerUi,
     }
 
     open fun javaScriptFunction(): AnkiDroidJsAPI? {
-        return AnkiDroidJsAPI(this)
+        return com.ichi2.anki.AnkiDroidJsAPI(this)
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt:2527]: I don't understand why this is changed?

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt [hunk 6]
```diff
@@ -28,9 +28,7 @@ import android.content.res.Resources
 import android.graphics.Color
 import android.media.MediaPlayer
 import android.net.Uri
-import android.os.Build
-import android.os.Bundle
-import android.os.SystemClock
+import android.os.*
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt:31]: I don't understand why the imports are changed (vs just adding one)

File: AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt [hunk 7]
```diff
@@ -152,4 +152,7 @@ object Consts {
     const val DEFAULT_DECK_CONFIG_ID: Long = 1
     @JvmField
     val FIELD_SEPARATOR = Character.toString('\u001f')
+
+    /** Time duration for toasy **/
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt:156]: typo

File: AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt [hunk 8]
```diff
@@ -152,4 +152,7 @@ object Consts {
...
+    const val LENGTH_SHORT: Long = 2000
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt:157]: this name is not really descriptive, if it was SHORT_TOAST_DURATION it would be much more descriptive I think?

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java [hunk 9]
```diff
@@ -61,6 +63,7 @@
 import androidx.recyclerview.widget.LinearLayoutManager;
 import androidx.recyclerview.widget.RecyclerView;
 
+import android.provider.SyncStateContract;
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java:66]: why is this import here :thinking:

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java [hunk 10]
```diff
@@ -145,6 +150,7 @@
 import java.util.List;
 
 import kotlin.Unit;
+import kotlin.io.ConstantsKt;
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java:153]: examine all the imports, I won't comment on all of them but I think you only needed to add Consts

**Review by mikehardy — CHANGES_REQUESTED** [review]
something went wrong with the imports? Really made the PR messy unfortunately - can you make sure to *only* change lines of code (or imports) that you absolutely must change for the purpose of the PR?

And I think the name could be better - but the PR is still close

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt (hunk 5 above)
Comment (UvrajSB) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt:2527]: As I have logged a new issue, where #10734 .
So I had to go to the commit before the one which created the issues and there this thing might have changed most probably. Likewise, for all the extra import and all, it all happened because the file I was working upon changed and the ankidroid:main had issues so I had to search the latest commit which was stable.
And hence during the process of doing it and adding Constant it resulted in many imports than required.
Apologies for it, Ill remove all the clutter

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt [hunk 11]
```diff
@@ -632,6 +630,12 @@ abstract class AbstractFlashcardViewer : NavigationDrawerActivity(), ReviewerUi,
                 showThemedToast(this, getString(R.string.back_pressed_once_reviewer), true)
             }
             mBackButtonPressedToReturn = true
+            Handler(Looper.getMainLooper()).postDelayed(
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt:633]: `HandlerUtils.executeFunctionWithDelay` would be less code

**Review by david-allison — APPROVED** [review]
Code looks good. I'll follow up with a small improvement after some refactoring is done
