### PR TITLE
Ensure closing transaction won't crash

### LINKED ISSUE #7265: Cannot rollback - no transaction is active
This is a common bug with many code paths that can cause it. see: https://github.com/ankidroid/Anki-Android/blob/55f45d78c62b272dca282e53b0dc251a26567186/AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java#L156-L164

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/1ba8eb6c-3bdc-4ec5-a52b-a389130ef77f

```
android.database.sqlite.SQLiteException: cannot rollback - no transaction is active (code 1)
at io.requery.android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
at io.requery.android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:7)
at io.requery.android.database.sqlite.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:12)
at io.requery.android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:2)
at io.requery.android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:2)
at com.ichi2.utils.DatabaseChangeDecorator.endTransaction(DatabaseChangeDecorator.java:1)
at com.ichi2.async.CollectionTask.doInBackgroundAnswerCard(CollectionTask.java:16)
at com.ichi2.async.CollectionTask.actualDoInBackground(CollectionTask.java:49)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:2)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)
```

### PR DESCRIPTION
**Pull request by david-allison-1**
## Fixes
Fixes #7265 

## Approach
Call `inTransaction` and use a `try...catch`

## How Has This Been Tested?

Only unit tests

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/libanki/DB.java [hunk 1]
```diff
@@ -391,4 +385,34 @@ public void executeManyNoTransaction(String sql, List<Object[]> list) {
     public String getPath() {
         return mDatabase.getPath();
     }
+
+
+    public void executeInTransaction(Runnable r) {
+        // Ported from code which started the transaction outside the try..finally
+        getDatabase().beginTransaction();
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/libanki/DB.java:392]: Hmm - I think it's just because it can never throw? shouldn't matter?

**Review by mikehardy — APPROVED** [review]
LGTM and centralizes the BS
I'm the author of the "it can throw even if you check!" comment, I was shocked by the way exceptions bubbled out of transaction handling, good to have them in one spot

**Comment by david-allison-1** [comment]
I'd like to centralise it a little more - maybe in an `AutoClosable` once we hit an appropriate API level, one of the main issues with the lambda approach is that you can't do any control flow, such as returning values from there.

This might warrant a quick look at the unit tests to ensure there are no performance regressions
