### PR TITLE
Correction of 7066

### LINKED ISSUE #7066: [2.13beta] _deckNewLimitSingle stackoverflow
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/663437b4-40fc-44c2-9061-6decb6890c1f

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$4.done(AsyncTask.java:399)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.StackOverflowError: stack size 1039KB
at com.ichi2.utils.JSONObject.getInt(JSONObject.java:1)
at com.ichi2.libanki.sched.SchedV2._deckNewLimitSingle(SchedV2.java:1)
at com.ichi2.libanki.sched.SchedV2.a(SchedV2.java:1)
at com.ichi2.libanki.sched.f.operation(Unknown Source:2)
at com.ichi2.libanki.sched.SchedV2._deckNewLimit(SchedV2.java:6)
at com.ichi2.libanki.sched.SchedV2._deckNewLimit(SchedV2.java:1)
at com.ichi2.libanki.sched.SchedV2._fillNew(SchedV2.java:6)
at com.ichi2.libanki.sched.SchedV2._fillNew(SchedV2.java:6)
at com.ichi2.libanki.sched.SchedV2._fillNew(SchedV2.java:6)
```

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
Fixes #7066

### CODE REVIEW

File: AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java [hunk 1]
```diff
@@ -377,4 +377,25 @@ private void addDeckWithExactName(String name) {
...
+        addNoteUsingBasicModel("plop", "foo");
+        col.reset();
+        Card card = sched.getCard();
+        sched.setCurrentCard(card);
+        sched.preloadNextCard();
+        sched.answerCard(card, Consts.BUTTON_THREE);
+        card = sched.getCard();
+        sched.setCurrentCard(card);
+        // Next line was an infinite recursion in 7066. We just want to assert the run halts
+        sched.preloadNextCard();
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java:399]: AnkiAssert.assertDoesNotThrow(() -> sched.preloadNextCard());

Comment (Arthur-Milchior) [reply AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java:399]: May I ask how assertDoesNotThrow test more than running (since it fails if it throws)

Comment (mikehardy) [reply AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java]: I think it's mostly an optimization vs Codacy saying "you should assert in a test"

>     /** Helper to sort out "JUnit tests should include assert() or fail()" quality check */

**Review by mikehardy — APPROVED** [review]
huge +1 for the regression test cover, thank you!

File: AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java (hunk 1 above)
Comment (david-allison-1) [reply AnkiDroid/src/test/java/com/ichi2/libanki/sched/AbstractSchedTest.java]: You get an assertion error, rather than a method throwing an exception - which the tools detect differently

It's also more explicit that one specific line is under test.

**Review by david-allison-1 — APPROVED** [review]
If the regression tests pass, looks good to go
