### PR TITLE
Show keyboard in onResume state of Reviewer.kt

### LINKED ISSUE #13450: KeyBoard is not showing in onResume state of Reviewer Screen
###### Reproduction Steps

1. Create a Card of the type Basic ( type in the answer )
2. Review a Card 
3. And go to card browser from Reviewer Screen and change to different Deck
4. Again go back to Reviewer Screen

###### Screen Recording

https://user-images.githubusercontent.com/65113071/226091269-3b7c3055-1256-4785-a1cf-5d271c182d4f.mp4

###### Expected Result

Keyboard is showing in onResume state of Reviewer Screen

###### Actual Result

Keyboard is not showing in onResume state of Reviewer Screen

###### Debug info
AnkiDroid Version = 2.16alpha94-debug

Android Version = 10

Manufacturer = Google

Model = Android SDK built for x86

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 10; Android SDK built for x86 Build/QSR1.210802.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/74.0.3729.185 Mobile Safari/537.36

ACRA UUID = cd23b1d0-41e4-4c7a-9767-91b2f4b77aff

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

###### Approach

This can be achieved by adding `answerField!!.focusWithKeyboard()` in onResume()

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by SanjaySargam**
## Fixes
Fixes #13450

## Approach

This can be achieved by adding answerField!!.focusWithKeyboard() in onResume()

## How Has This Been Tested?

Tested on Emulator

https://user-images.githubusercontent.com/65113071/226091366-19107112-12fa-419c-9760-8833937aba62.mp4

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by pratyaksh1610 — COMMENTED** [review]
Tests fails.

**Comment by SanjaySargam** [comment]
> Tests are failing .

Now all tests passed.

**Review by pratyaksh1610 — APPROVED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt [hunk 1]
```diff
@@ -26,11 +26,7 @@ import android.content.Intent
 import android.content.SharedPreferences
 import android.content.pm.PackageManager
 import android.content.res.ColorStateList
-import android.os.Build
-import android.os.Bundle
-import android.os.Handler
-import android.os.Message
-import android.os.Parcelable
+import android.os.*
```
Comment (ShridharGoel) [inline AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt:29]: Unnecessary change

**Review by ShridharGoel — CHANGES_REQUESTED** [review]

**Comment by SanjaySargam** [comment]
Hey @ShridharGoel Can you review it

**Comment by SanjaySargam** [comment]
Can any of the maintainers will look into this ? It's been a long time

**Review by ShridharGoel — APPROVED** [review]
