### PR TITLE
Fix the handling of quotes while renaming a deck

### LINKED ISSUE #18266: Renaming Strips-off All Double-quotes
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Add a deck with `"` in the title.
2. Rename the deck without removing `"` sign.

### Expected behaviour

Renaming strips off any `"` in deck name. If you add a deck with just a `"` mark, renaming fails and shows "Invalid deck name" snackbar.

### Debug info

```text
AnkiDroid Version = 2.21alpha15 (c9c58c3efb8adf535fdfb4a7237ae56a870fafef)
Backend Version = 0.1.52-anki25.02 (25.02 038d85b1d9e1896e93a3e4a26f600c79ddc33611)
Android Version = 11 (SDK 30)
ProductFlavor = full
Device Info = realme | realme | RMX2193 | RMX2193 | RMX2193 | mt6768
Webview User Agent = Mozilla/5.0 (Linux; Android 11; RMX2193 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/135.0.7049.100 Mobile Safari/537.36
ACRA UUID = cf265e01-9693-407f-984d-61ddf9698fac
FSRS = 2.0.3 (Enabled: true)
Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by ShridharGoel**
## Purpose / Description

Fixes the handling of quotes while renaming a deck.

## Fixes
Fixes #18266

## Approach
There was an unnecessary removal of `"` happening before the renaming logic. This was also inconsistent with the deck creation logic.

## How Has This Been Tested?

Manual testing + unit tests.

### CODE REVIEW

**Review by BrayanDSO — APPROVED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt [hunk 1]
```diff
@@ -245,16 +245,15 @@ class CreateDeckDialog(
     }
 
     fun renameDeck(newDeckName: String) {
-        val newName = newDeckName.replace("\"".toRegex(), "")
```
Comment (thedroiddiv) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt:248]: Do we know, why in the first place quotes were being removed?

Comment (thedroiddiv) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt:248]: I Checked with the desktop version, it allows deck name to contain `"`

**Review by lukstbit — APPROVED** [review]
