### PR TITLE
Replaced CustomStudyListener with FragmentResultApi in CustomStudyDialog

### LINKED ISSUE #17665: Custom study option raises an exception
I'm running on HEAD 2a909fe00fbcf42ffc681d880835eeb869f86a9a

I was looking at the Custom Study screen. Trying to review forgotten cards. I just got this error message

Image

It's not very reproducible. I had to do it many times to sometime get the error. Most of the time, I just get the message that no card is found

### PR DESCRIPTION
**Pull request by Aditya13s**
## Purpose / Description
Replace `CustomStudyListener` with the `FragmentResultApi` to improve fragment communication.

## Fixes
* Fixes #17665

## Approach
Replaces the `CustomStudyListener` functions with `setFragmentResult` to pass `CustomStudyAction` inside a bundle. The result is then listened inside `DeckPicker` using `supportFragmentManager.setFragmentResultListener`.

## How Has This Been Tested?
Tested on Android 12

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by Aditya13s** [comment]
@david-allison Kindly review and advise if any additional changes are required

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt [hunk 1]
```diff
@@ -118,6 +120,11 @@ class CustomStudyDialog(
         fun onExtendStudyLimits()
     }
 
+    enum class CustomStudyAction {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt:123]: define `fromInt` and use

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt [hunk 2]
```diff
@@ -118,6 +120,11 @@ class CustomStudyDialog(
         fun onExtendStudyLimits()
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt:120]: Does this interface still need to exist?

**Review by david-allison — CHANGES_REQUESTED** [review]
* define `CustomStudyAction.fromOrdinal`
* Extract the key to a constant
  * Consider extracting the bundle arg key to a constant 
* 🐞 This doesn't handle all callers
* Remove the `CustomStudyListener`

**Comment by Aditya13s** [comment]
> Remove the `CustomStudyListener`

 @david-allison 
CustomStudyListener Interface or val ?

**Comment by david-allison** [comment]
The interface, it should no longer be necessary if you're using the result API

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 3]
```diff
@@ -599,6 +598,16 @@ open class DeckPicker :
 
         checkWebviewVersion(this)
 
+        supportFragmentManager.setFragmentResultListener(CustomStudyAction.REQUEST_KEY, this) { requestKey, bundle ->
+            val actionOrdinal = bundle.getInt(CustomStudyAction.BUNDLE_KEY)
+            val action = CustomStudyAction.fromOrdinal(actionOrdinal)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:603]: optional: `CustomStudyAction.fromBundle`

File: AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.kt [hunk 4]
```diff
@@ -53,6 +52,16 @@ class StudyOptionsActivity :
             loadStudyOptionsFragment()
         }
         setResult(RESULT_OK)
+
+        supportFragmentManager.setFragmentResultListener(CustomStudyAction.REQUEST_KEY, this) { requestKey, bundle ->
+            val actionOrdinal = bundle.getInt(CustomStudyAction.BUNDLE_KEY)
+            val action = CustomStudyAction.fromOrdinal(actionOrdinal)
+            when (action) {
+                CustomStudyAction.CUSTOM_STUDY_SESSION -> onCreateCustomStudySession()
+                CustomStudyAction.EXTEND_STUDY_LIMITS -> onExtendStudyLimits()
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.kt:61]: inline `onCreateCustomStudySession` and `onExtendStudyLimits`

File: AnkiDroid/src/main/java/com/ichi2/anki/SingleFragmentActivity.kt [hunk 5]
```diff
@@ -81,6 +79,16 @@ open class SingleFragmentActivity :
         supportFragmentManager.commit {
             replace(R.id.fragment_container, fragment, FRAGMENT_TAG)
         }
+
+        supportFragmentManager.setFragmentResultListener(CustomStudyAction.REQUEST_KEY, this) { requestKey, bundle ->
+            val actionOrdinal = bundle.getInt(CustomStudyAction.BUNDLE_KEY)
+            val action = CustomStudyAction.fromOrdinal(actionOrdinal)
+            when (action) {
+                CustomStudyAction.CUSTOM_STUDY_SESSION -> onCreateCustomStudySession()
+                CustomStudyAction.EXTEND_STUDY_LIMITS -> onExtendStudyLimits()
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/SingleFragmentActivity.kt:88]: inline `onCreateCustomStudySession` and `onExtendStudyLimits`

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt [hunk 6]
```diff
@@ -111,16 +113,21 @@ import timber.log.Timber
...
 @KotlinCleanup("remove 'collection' parameter and use withCol { }")
-@KotlinCleanup("remove 'customStudyListener' parameter and use FragmentResult")
 class CustomStudyDialog(
     private val collection: Collection,
-    private val customStudyListener: CustomStudyListener?,
 ) : AnalyticsDialogFragment(),
     TagsDialogListener {
-    interface CustomStudyListener {
-        fun onCreateCustomStudySession()
+    enum class CustomStudyAction {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt:120]: Move this to the end of the class, along with the other enums

File: AnkiDroid/src/main/java/com/ichi2/anki/pages/CongratsPage.kt [hunk 7]
```diff
@@ -110,6 +111,16 @@ class CongratsPage :
                 true
             }
         }
+
+        setFragmentResultListener(CustomStudyAction.REQUEST_KEY) { requestKey, bundle ->
+            val actionOrdinal = bundle.getInt(CustomStudyAction.BUNDLE_KEY)
+            val action = CustomStudyAction.fromOrdinal(actionOrdinal)
+            when (action) {
+                CustomStudyAction.CUSTOM_STUDY_SESSION -> onCreateCustomStudySession()
+                CustomStudyAction.EXTEND_STUDY_LIMITS -> onExtendStudyLimits()
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/pages/CongratsPage.kt:120]: again: inline

**Review by david-allison — APPROVED** [review]
Great stuff!

Some requests, but I'm putting this PR as 'need second approval', as they're all mechanical refactorings

**Review by mikehardy — APPROVED** [review]
Thank you, and also LGTM assuming suggested refactors are completed
Leaving as needs second approval, after pushing refactors re-request approval from David for final merge check is best path I think
Cheers

**Comment by Aditya13s** [comment]
@david-allison I've made the changes. Please review.

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 8]
```diff
@@ -599,6 +598,24 @@ open class DeckPicker :
...
+                CustomStudyAction.CUSTOM_STUDY_SESSION -> {
+                    updateDeckList()
+                    openStudyOptions(false)
+                }
+                CustomStudyAction.EXTEND_STUDY_LIMITS -> {
+                    if (fragmented) {
+                        fragment!!.refreshInterface()
+                    }
+                    updateDeckList()
+                }
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:614]: Yeah... good shout to inline this as well

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt [hunk 9]
```diff
@@ -480,7 +476,30 @@ class CustomStudyDialog(
...
+        EXTEND_STUDY_LIMITS,
+        CUSTOM_STUDY_SESSION,
+        ;
+
+        companion object {
+            const val REQUEST_KEY = "CustomStudyDialog"
+            const val BUNDLE_KEY = "action"
+
+            /** Converts an ordinal value to the corresponding [CustomStudyAction] */
+            fun fromBundle(ordinal: Int): CustomStudyAction? = entries.find { it.ordinal == ordinal }
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt:502]: `fromBundle` should accept a `bundle`. 

I'll fix this. It's good, I want it in.

**Review by david-allison — CHANGES_REQUESTED** [review]

**Review by david-allison — APPROVED** [review]
`+93, -98`, less code AND better code 🥳
