### PR TITLE
fix: SingleFragmentActivity: fragment has not been initialized 

### LINKED ISSUE #17246: [BUG]: `SingleFragmentActivity`: lateinit property fragment has not been initialized
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

Got this randomly while toggling night mode.

I can't reproduce it consistently.

But I'm 100% that `fragment` shouldn't be lateinit in `SingleFragmentActivity`

### Expected behaviour

It crashed, but shouldn't

### Debug info

Running at 17a44bc042dbddca3a839c6dc99392a743500918

```
kotlin.UninitializedPropertyAccessException: lateinit property fragment has not been initialized
 at com.ichi2.anki.SingleFragmentActivity.getFragment(SingleFragmentActivity.kt:44)
 at com.ichi2.anki.SingleFragmentActivity.getShortcuts(SingleFragmentActivity.kt:96)
 at com.ichi2.anki.AnkiActivity.onKeyUp(AnkiActivity.kt:654)
 at android.view.KeyEvent.dispatch(KeyEvent.java:2952)
 at android.app.Activity.dispatchKeyEvent(Activity.java:4340)
 at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.kt:103)
 at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:85)
 at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.kt:117)
 at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:604)
 at com.ichi2.anki.SingleFragmentActivity.dispatchKeyEvent(SingleFragmentActivity.kt:78)
 at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
 at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3397)
 at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:392)
 at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6945)
 at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6811)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6229)
 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6286)
 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6252)
 at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6417)
 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6260)
 at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6474)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6233)
 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6286)
 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6252)
 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6260)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6233)
 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6286)
 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6252)
 at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6450)
 at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:6661)
 at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:4278)
 at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:3715)
 at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:3706)
 at android.view.inputmethod.InputMethodManager.-$$Nest$mfinishedInputEvent(Unknown Source:0)
 at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:4255)
 at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:154)
 at android.os.MessageQueue.nativePollOnce(Native Method)
 at android.os.MessageQueue.next(MessageQueue.java:335)
 at android.os.Looper.loopOnce(Looper.java:162)
 at android.os.Looper.loop(Looper.java:294)
 at android.app.ActivityThread.main(ActivityThread.java:8177)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison**
## Fixes
* Fixes #17246

## Approach
Fixed by re-initializing `fragment`

## How Has This Been Tested?
* On an API 34 tablet, the app no longer crashes after a user types

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/SingleFragmentActivity.kt [hunk 1]
```diff
@@ -66,7 +68,7 @@ open class SingleFragmentActivity : AnkiActivity() {
             arguments = intent.getBundleExtra(FRAGMENT_ARGS_EXTRA)
         }
         supportFragmentManager.commit {
-            replace(R.id.fragment_container, fragment)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/SingleFragmentActivity.kt:69]: The `!!` felt better than either a `also { }` or an `apply { }` here

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/SingleFragmentActivity.kt:69]: 🤔 is getInstanceFromClassName capable of returning null? Huh.
I see fragment initialized it just above, and we just assume that it always works? I suppose it always should

**Review by mikehardy — APPROVED** [review]
Seems fine - I see you considered and pre-justified the !! ;-), I am still suspicious (I am always suspicious) but it seems okay

**Comment by david-allison** [comment]
@mikehardy I've recoded the `!!` given your comment

**Review by mikehardy — APPROVED** [review]
fabulous, now there's just no way a null could sneak in there because there's no iffy usage

a `!!` should never feel better than the alternative, though...perhaps I'll learn something that changes my mind in the future. For now though I like the re-write, thanks

**Comment by david-allison** [comment]
I've reproduced the error. Let's circle back to this once I understand what's going on

**Comment by david-allison** [comment]
After being able to reproduce this issue, I've simplified the fix

**Review by mikehardy — APPROVED** [review]
ah ha

**Review by lukstbit — APPROVED** [review]
LGTM, thanks for the reproduction steps.
