### PR TITLE
Don't count 'forget' and 'set due date' cards as reviews

### LINKED ISSUE #8592: 'Set Due Date' and 'Forget' are being counted as reviews
###### Reproduction Steps

1.  Select a card in the browser on Anki Desktop
2.  Select 'Forget', or 'Set Due Date' (today, tomorrow+reset interval, random choice of 3-7 days all produce the same bug)
3.  Sync Anki Desktop
4.  Sync Ankidroid

###### Expected Result
Ankidroid and Anki Desktop show the same number of reviews

###### Actual Result
Ankidroid and Anki Desktop have different review numbers because Ankidroid counts those rescheduled cards as reviews.

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by ThoreBor**
## Purpose / Description
I noticed that using 'Set Due Date' or 'Forget' on Anki Desktop (⁨2.1.41) will count as a review on Ankidroid.

**Anki Desktop:**
image
image
**Ankidroid:**
Screenshot_2021-04-12-22-20-49-768_com ichi2 anki

## Fixes
Fixes #8592

## Approach
Using 'Set Due Date' or 'Forget' will be saved in the revlog table and will therefore be counted as a review on Ankidroid. Counting only reviews that have a time value greater than 0 solves this issue.

## How Has This Been Tested?
I tested this on a (physical) Redmi Note 8 Pro (MIUI Global 12.0.4) on Android 10 QP1A.190711.020.

To reproduce this bug, select a card on Anki Desktop, select 'Forget', or 'Set Due Date' (today, tomorrow+reset interval, random choice of 3-7 days all produce the same bug), and sync.

I'm using Android SDK Platform-Tools Version 31.0.1

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
Looks good to me! Thanks so much!

Could you quickly find a diff/source code link where Anki Desktop performs this check, so we can add it as a reference to the commit message to help future developers

If you can't quickly find this, let me know and I'll take a look for you

(Optional) It'd be nice if you could add a GitHub Issue for this (it allows us to track reverts more easily, not that this change is likely problematic)

**Comment by ThoreBor** [comment]
Thanks for the fast reply. I just opened issue #8592 for this. 
I looked briefly at the code and it looks like [this](https://github.com/ankitects/anki/blob/3f3c509badbd74e064de6010b428eef53dc19576/pylib/anki/stats.py#L125) could be relevant, but I don't really see what the difference is.

**Comment by david-allison-1** [comment]
It would make more sense to me to selecting on the specific types of reviews that we are after to follow Anki Desktop. 
What do you think?

**Comment by dae** [comment]
Looks related to #8009

**Comment by ThoreBor** [comment]
Do you mean something like this?

**Comment by dae** [comment]
checking ease > 0 is more future proof

**Comment by ThoreBor** [comment]
Alright, this also seems to work

File: AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java [hunk 1]
```diff
@@ -211,7 +211,8 @@ protected String doInBackground(Object... params) {
                 //eventually put this in Stats (in desktop it is not though)
                 int cards;
                 int minutes;
-                String query = "select count(), sum(time)/1000 from revlog where id > " + ((collection.getSched().getDayCutoff() - SECONDS_PER_DAY) * 1000);
+                String query = "select sum(case when ease > 0 then 1 else 0 end), "+ /* cards, excludes rescheduled cards https://github.com/ankidroid/Anki-Android/issues/8592 */
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java:214]: if an `ease < 0`  card has a time then it would be counted, is this what the Desktop does?

**Comment by ThoreBor** [comment]
The corresponding issue #8592 is going to be closed soon because of no activity. Could someone tell me if this looks good now, or if I should change something?

**Review by mikehardy — APPROVED** [review]
I think is a good change even if temporary before more Rust conversion cleans out the stats area.

I think @dae nailed it that this is related to revlog behavior from Desktop starting to log that cards were rescheduled and us not excluding it correctly. Selecting from revlog with these ranges is an analogous change to that which was needed for the issue Damien linked

I'll mark this for second review but it's already sat for quite a while and if it sits for more than a few days I'll merge

**Comment by mikehardy** [comment]
@david-allison-1 says in Discord:

> I need to check that one over, I think it's already done, but I need to repro the bug

**Comment by david-allison-1** [comment]
I can't reproduce this one (2.16 alpha 0).

Could you confirm whether the underlying issue is still a problem?

**Comment by ThoreBor** [comment]
I checked with 2.16alpha2 and I still have the same issue

**Review by david-allison-1 — APPROVED** [review]
Okay, thanks!

LGTM then. Kicked off CI. Needs a squash merge

**Comment by mikehardy** [comment]
:zap:  Thanks everyone!

**Comment by mikehardy** [comment]
Hi there!

Apologies for the delay, and if you're already submitted something to OpenCollective for PRs merged in June 2021 PRs merged, you may feel free to ignore this and it will be processed shortly

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for June 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged in May)

Thanks!
