### PR TITLE
fix: Custom study menu may look crowded or cluttered when not all items are on a single line each

### LINKED ISSUE #19107: Custom study menu may look crowded or cluttered when not all items are on a single line each
Image

In translating into other languages, each item in Custom study menu may need more than one line, but the current layout doesn't give the items a sufficient and consistent padding even in such case. 

For example, the following is Custom study menu in German:
image
It looks a bit crowded and cluttered.

**Debug Info**

```
AnkiDroid Version = 2.22.0beta2 (01328a9fc8e15c75f5cb98a5268d9ba04ca51353)  
Backend Version = 0.1.59-anki25.07.3 (25.07.3 65b5aefd0705463cb12e72e254f798f90c96e815)  
Android Version = 11 (SDK 30)  
ProductFlavor = full  
Device Info = OPPO | OPPO | OP4BAFL1 | CPH2013 | CPH2013 | qcom  
Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/138.0.7204.157 Mobile Safari/537.36  
ACRA UUID = dae56c60-345e-41f3-a616-f02ce05cd8ad  
FSRS = 4.1.1 (Enabled: false)  
Crash Reports Enabled = true
```

### PR DESCRIPTION
**Pull request by snowtimeglass**
## Purpose / Description
In translating into other languages, each item in Custom study menu may need more than one line, but the current layout (suitable for single-line items) doesn't give the items a sufficient and consistent padding.
image
(German)

This PR intends to add the sufficient and consistent padding between the items even in such case.

## Fixes
* Fixes #19107
* Fixes https://github.com/ankidroid/Anki-Android/pull/19179

## Approach
- Use a new layout file which specifies a `paddingVertical` value instead of the current layout

- Other than that, use the same values as in the current layout file (`simple_list_item_1.xml`) below: 
```
<TextView xmlns:android="http://schemas.android.com/apk/res/android"
   android:id="@android:id/text1"
   android:layout_width="match_parent"
   android:layout_height="wrap_content"
   android:textAppearance="?android:attr/textAppearanceListItemSmall"
   android:gravity="center_vertical"
   android:paddingStart="?android:attr/listPreferredItemPaddingStart"
   android:paddingEnd="?android:attr/listPreferredItemPaddingEnd"
   android:minHeight="?android:attr/listPreferredItemHeightSmall" />
```
## How Has This Been Tested?

Checked in a physical device (Android 11)

**Before / After**
(In German)
image

----

(Original)
image

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt [hunk 1]
```diff
@@ -246,7 +246,7 @@ class CustomStudyDialog : AnalyticsDialogFragment() {
                             option.checkAvailability(deferredDefaults.getCompleted()),
                     )
                 }.forEach { (menuItem, isItemEnabled) ->
-                    (layoutInflater.inflate(android.R.layout.simple_list_item_1, container, false) as TextView)
+                    (layoutInflater.inflate(R.layout.item_custom_study, container, false) as TextView)
                         .apply {
                             text = menuItem.getTitle(requireContext().resources)
                             isEnabled = isItemEnabled
```
Comment (lukstbit) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt]: If all you're changing is the vertical padding there's no need for a custom layout:

```suggestion
                    (layoutInflater.inflate(R.layout.item_custom_study, container, false) as TextView)
                        .apply {
                            updatePadding(
                                top = 4.dp.toPx(requireContext()),
                                bottom = 4.dp.toPx(requireContext()),
                            )
                            text = menuItem.getTitle(requireContext().resources)
                            isEnabled = isItemEnabled
```

Also, _14dp_ padding is way too much.

**Review by lukstbit — COMMENTED** [review]
In what type of device was the first image produced? I fired up an emulator(and also looked on a phone), and there's enough space between the items IMO:

screen_one

**Comment by snowtimeglass** [comment]
> In what type of device was the first image produced? 

It was done in the following device:
```
AnkiDroid Version = 2.22.0beta2 (01328a9fc8e15c75f5cb98a5268d9ba04ca51353)  
Backend Version = 0.1.59-anki25.07.3 (25.07.3 65b5aefd0705463cb12e72e254f798f90c96e815)  
Android Version = 11 (SDK 30)  
ProductFlavor = full  
Device Info = OPPO | OPPO | OP4BAFL1 | CPH2013 | CPH2013 | qcom  
Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/138.0.7204.157 Mobile Safari/537.36  
ACRA UUID = dae56c60-345e-41f3-a616-f02ce05cd8ad  
FSRS = 4.1.1 (Enabled: false)  
Crash Reports Enabled = true
```

**Comment by lukstbit** [comment]
I have no issues with adding extra padding, but it should be a small value(like the _4dp_ I proposed above).

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt (hunk 1 above)
Comment (snowtimeglass) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt]: Thank you for pointing it out.

> If all you're changing is the vertical padding there's no need for a custom layout:

Just to confirm: so you actually suggest keeping the current layout: `android.R.layout.simple_list_item_1` as it is in the line 249 in `android:main`, because there's no need for replacing it with `R.layout.item_custom_study` as above, right?

Comment (lukstbit) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt]: Yes, keep the current layout _android.R.layout.simple_list_item_1_. The only changes in this PR should be the _updatePadding_ block above with a padding of 4dp or 8dp, your choice.

Comment (snowtimeglass) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt]: > Yes, keep the current layout android.R.layout.simple_list_item_1. 

I understand. Thank you.

> The only changes in this PR should be the updatePadding block above with a padding of 4dp or 8dp, your choice.

This PR, at the moment, intends to guarantee a sufficient and consistent padding between the items even if some items take more than one line each. I doubt that 4dp-padding or 8dp-padding would achieve the goal.

On German and Armenian (Hայերեն) in my device:
 - 4dp
  imageimage


 - 8dp
   imageimage

- 14dp
   imageimage



For what it's worth, 14dp-padding has been used for the spinner items of `Study by card state or tag` since this change: https://github.com/ankidroid/Anki-Android/pull/18954#event-18793001022

Comment (lukstbit) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt]: Ok, fine. Can we at least agree on a value of 12dp padding to use material theme standard dimensions(which are multiples of 4)?

Comment (snowtimeglass) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CustomStudyDialog.kt]: Thank you. I'm also fine with it.

- 12dp 
   imageimageimage

**Review by david-allison — APPROVED** [review]

**Comment by david-allison** [comment]
Hi there @snowtimeglass! This is the OpenCollective Notice for PRs merged from [2025-09-01 through 2025-09-30](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2025-09-01..2025-09-30+author%3Asnowtimeglass)

If you are interested in compensation for this work, the process with details is here: https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

We only post one comment per person per month to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for this month

Please understand that our monthly budget is never guaranteed to cover all claims - the cap on payments-per-person may be lower, but we try to make our process as fair and transparent as possible, we just need your understanding.

Thanks!
