### PR TITLE
Fix App closing after pressing "Back" on changelog

### LINKED ISSUE #7438: After install, hitting back from change log goes back to Play Store instead of home
After installation, hitting the back button from the Changelog page returns the user to the Google Play store page, instead of going to the AnkiDroid home page (see video)

https://gfycat.com/acceptablereadyarcticduck

AnkiDroid Version = 2.13.5

Android Version = 10

ACRA UUID = 03434583-cd6c-4869-8ed2-d8e7712382df

Scheduler = std

### PR DESCRIPTION
**Pull request by david-allison-1**
## Fixes
Fixes #7438 

## Approach
Don't close the app

## How Has This Been Tested?

Untested

## Learning 

The "Open Changelog" button on the Advanced Settings wasn't enough

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/Info.java [hunk 1]
```diff
@@ -191,19 +191,6 @@ private void openMarketUrl() {
         }
     }
 
-
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/Info.java:194]: This works without the code

**Review by mikehardy — APPROVED** [review]
Our startup flow is :unicorn:
