### PR TITLE
Fix Audio Whitespace Handling

### LINKED ISSUE #6693: Audio files with leading spaces are handled incorrectly
Reported: https://www.reddit.com/r/Anki/comments/hq8akk/downloaded_two_decks_and_one_deck_seems_to/

###### Reproduction Steps

1. Add a media file: `"5.mp3"`
2. Add a media file: `" 5.mp3"` (with leading space).
3. Add `[sound: 5.mp3]` to a card and preview.

###### Expected Result

`" 5.mp3"` is played (Anki Behaviour)

###### Actual Result

`"5.mp3"` is played.

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description
In Anki, whitespace before a filename matters, whereas whitespace after a file is ignored.

This is visible in the following decks:

https://ankiweb.net/shared/info/1616679068
"GENKI I Grammar Deck with native speaker audio and images"

https://ankiweb.net/shared/info/1833515795
"GENKI II Grammar Deck with native speaker audio and images"

One defines "5.mp3", and the other defines " 5.mp3".

This works in Anki Desktop.

## Fixes
Fixes #6693

## Approach
We fix this by only performing a trim on the right hand side, and only if the string is not a URI

## How Has This Been Tested?

Tested on my phone:

* With the above decks
* Added trailing whitespace, both passed.

## Learning 

See #6693 

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by mikehardy** [comment]
Wow, that seems sort of insane, like it should be trimmed fully but I guess filenames are sort of an exposed API surface area and if this is how it's handled, okay then :sweat_smile:

File: AnkiDroid/src/main/java/com/ichi2/utils/StringUtil.java [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+    /** Trims from the right hand side of a string */
+    @Nullable
+    @Contract("null -> null; !null -> !null")
+    public static String trimRight(@Nullable String s) {
+        if (s == null) {
+            return null;
+        }
+
+        int newLength = s.length();
+        while (newLength > 0 && Character.isWhitespace(s.charAt(newLength - 1))) {
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/utils/StringUtil.java:35]:
```suggestion
        while (newLength >= 0 && Character.isWhitespace(s.charAt(newLength - 1))) {
```

'>=' ? Just thinking, an rTrim of a fully whitespace string should return the empty string, so it should be valid to go all the way to zero? It appears substring only throws if endIndex is less than beginIndex so equal index values should work and empty string should be valid

https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#substring(int,%20int)

Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/utils/StringUtil.java:35]: No, if the newLength is 0, then `.charAt(newLength - 1)` will crash, and the decrement operation will take the length to -1.

But, I'll add tests to prove it.

Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/utils/StringUtil.java:35]: Done and re-pushed, No code changes in `StringUtil`

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/utils/StringUtil.java:35]: oh of course - I was mentally trying to do the index (zero-based) vs length shifts but reasoned through it incorrectly. If newLength goes through at 1 and it's whitespace it will go to 0 in the loop, break the loop then substring 0 0 - I can see it

File: AnkiDroid/src/test/java/com/ichi2/utils/StringUtilTest.java [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+
+    @Test
+    public void trimRightOnlyTrimsRight() {
+        assertThat(trimRight(" a "), is(" a"));
+    }
+
+    @Test
+    public void trimRightDoesNothingOnTrimmedString() {
+        String input = " foo";
+        assertThat(trimRight(input), sameInstance(input));
```
Comment (david-allison-1) [inline AnkiDroid/src/test/java/com/ichi2/utils/StringUtilTest.java:47]: This is a questionable test as it tests implementation - but I think it's reasonable to assert to ensure there's no performance regressions
