### PR TITLE
Fix missing minus symbol when updating tags in card browser

### LINKED ISSUE #19083: Card browser: Tags incorrectly shown
> I am missing the minus symbol when selecting several cards at once in the card browser to change, for example, one tag. Normally, tags that do not appear on every card should be marked with a minus symbol. Instead, every tag is shown with a plus symbol, which should only appear if all selected cards share that tag.
> Is this a bug? Would be great if the old behaviour could be reestablished.
> Ankidroid version 2.22.3

Originally reported on https://forums.ankiweb.net/t/tag-editing-card-browser-missing-minus-symbol/65543

### PR DESCRIPTION
**Pull request by thedroiddiv**
## Purpose / Description
Fix missing minus symbol when selecting several cards at once in the card browser to update tags.

## Fixes
* Fixes #19083

### Problem
This happened because the previous implementation
- treated all notes present in any note as "checked"
- remaining all were marked as "unchecked

### Expected
- tags present in all notes : "checked"
- tags present in some, but not all notes: "indeterminate"
- tags present in none of the notes: unchecked

### Fix
- check all notes, check if each tag is present or absent
- add to checked list if present else add to unchecked list
- this operations might result in few tags being present in both lists
- intersecting tags are the "indeterminate" ones which are correctly captured by [TagsList] 
- tags coming from intent's `extras` are treated as absolute `checked` and cannot be indeterminate 

## How Has This Been Tested?
Added unit test for "indeterminate"
Existing tests pass
Manually Tested

image
image
image
image

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModelTest.kt [hunk 1]
```diff
@@ -0,0 +1,145 @@
...
+                    noteIds = listOf(note1),
+                    checkedTags = listOf("d", "x"),
+                    isCustomStudying = false,
+                )
+
+            val tags = vm.tags.await()
+            assertTrue(tags.isIndeterminate("d")) // because it got added to unchecked list as it was not present in note1
+            assertTrue(tags.isChecked("x"))
+            assertTrue(tags.copyOfAllTagList().contains("x"))
+        }
```
Comment (thedroiddiv) [inline AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModelTest.kt]: This is a question for reviewers. Before merging, need to resolve the FIXME comment.

**Comment by thedroiddiv** [comment]
Also, the tests assume `NoteList` works as expected, any error in NoteList will result in ViewModelTest to fail, even though actual issue might not be in the ViewModel.

File: AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModelTest.kt [hunk 2]
```diff
@@ -0,0 +1,161 @@
...
+            // d    [-] - indeterminate
+            // e    [ ] - unchecked
+            // f    [ ] - unchecked
+            assertEquals(listOf("b"), checked.sorted())
+            assertEquals(listOf("a", "c", "d"), ind.sorted())
+            assertFalse(tags.isChecked("e"))
+            assertFalse(tags.isChecked("f"))
+        }
+
+    // FIXME: When a tag is not present in a note but passed as a checked tag to ViewModel.
```
Comment (david-allison) [inline AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModelTest.kt]: Can I confirm that my understanding of the situation below is correct? I haven't dug deep here.

----

TBC: I believe this only occurs in the `NoteEditorFragment`:

* Open the Note Editor with an intent:  new note and a user-provided tags list (`EXTRA_TAGS`)
* The note has neither been saved, nor updated to contain these tags

TBC: Likely also after editing the tags of a note, then re-entering the 'edit tags' dialog.

So:
* only one note is affected
* 'checked' represents the pending changes to the note
* 'checked' and not in `allTags` represents a pending addition to the tags

Indeterminate wouldn't make sense here if there's only one note

File: AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModelTest.kt (hunk 1 above)
Comment (david-allison) [reply AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModelTest.kt]: Can I confirm that my understanding of the situation below is correct? I haven't dug deep here.

----

TBC: I believe this only occurs in the `NoteEditorFragment`:

* Open the Note Editor with an intent:  new note and a user-provided tags list (`EXTRA_TAGS`)
* The note has neither been saved, nor updated to contain these tags

TBC: Likely also after editing the tags of a note, then re-entering the 'edit tags' dialog.

----

So:
* only one note is affected
* 'checked' represents the pending changes to the note
* 'checked' and not in `allTags` represents a pending addition to the tags

Indeterminate wouldn't make sense here if there's only one note

Comment (thedroiddiv) [reply AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModelTest.kt]: Then following this, we can say that since  `user-provided tags list (EXTRA_TAGS)` is not saved, they won't be present in the `allTags`.

In above example:
```kotlin
note1.tags = {a,b}
checkedTags = {d, x} // user provided tags, d cannot be here by design
allTags = {a,b,c,d,e}
```

I checked the flow, as it is exactly how you describe. Though the current implementation has potential of regression if in future somehow we ended up with scenario where a any of `EXTRA_TAGS` overlaps with `Collection.allTags`.  Should I add a test case for that, this mustn't happen, to avoid future regressions?

https://github.com/user-attachments/assets/7f84f424-f45e-456a-a4ad-a0bd87c750d9

Comment (david-allison) [reply AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModelTest.kt]: If I understand correctly: `EXTRA` refers to an extra in the intent, so there will be overlap with `allTags`

Comment (thedroiddiv) [reply AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModelTest.kt]: Yeah! That makes sense. 
So the verdict is, any tag coming from `EXTRAS` is to be absolute checked and cannot be indeterminate.

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModel.kt [hunk 3]
```diff
@@ -43,17 +43,29 @@ class TagsDialogViewModel(
...
+                noteIds.forEachIndexed { index, nid ->
+                    val noteTags = withCol { getNote(nid) }.tags
+                    _initProgress.emit(InitProgress.FetchingNoteTags(index + 1, noteIds.size))
+                    allTags.forEach { tag ->
+                        if (noteTags.contains(tag)) {
+                            allCheckedTags.add(tag)
+                        } else {
+                            uncheckedTags.add(tag)
                         }
+                    }
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModel.kt]: optional: may be cleaner using `partition`: 

https://kotlinlang.org/api/core/kotlin-stdlib/kotlin.collections/partition.html

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModel.kt [hunk 4]
```diff
@@ -43,17 +43,29 @@ class TagsDialogViewModel(
...
-                            addAll(checkedTags)
+                val allTags = withCol { tags.all() }
+                val allCheckedTags = mutableSetOf<String>()
+                val uncheckedTags = mutableSetOf<String>()
+                // For each note, put the checked tag in checked list and unchecked tags in unchecked list.
+                // This will result in few tags being present in both lists, checked and
+                // unchecked as they might be present in one note but absent in any other.
+                // Such tags are referred as `indeterminateTags` in [TagsList]
+                noteIds.forEachIndexed { index, nid ->
+                    val noteTags = withCol { getNote(nid) }.tags
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModel.kt:58]: Flag this for a performance improvement: this performs N expensive database queries which return too much information

This could be replaced with 1 query, accepting a list of NoteIds

File: AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModelTest.kt [hunk 5]
```diff
@@ -0,0 +1,164 @@
...
+import org.junit.Before
+import org.junit.Test
+import org.junit.runner.RunWith
+import kotlin.properties.Delegates
+
+@OptIn(ExperimentalCoroutinesApi::class)
+@RunWith(AndroidJUnit4::class)
+class TagsDialogViewModelTest : RobolectricTest() {
+    private var note1 by Delegates.notNull<NoteId>()
+    private var note2 by Delegates.notNull<NoteId>()
```
Comment (david-allison) [inline AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModelTest.kt:37]: I learned this from you. Thank you!

**Review by david-allison — APPROVED** [review]
Thanks!

As a request: could the conclusion of this be moved into the class/argument documentation:

https://github.com/ankidroid/Anki-Android/pull/19499#discussion_r2532184695

File: AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModelTest.kt (hunk 5 above)
Comment (thedroiddiv) [reply AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModelTest.kt:37]: Lol! I got that from IntelliJ :) 
Tried `lateinit` with primitive, it suggested me this instead

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModel.kt (hunk 3 above)
Comment (thedroiddiv) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModel.kt]: Looks clean. Will do.

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModel.kt (hunk 4 above)
Comment (thedroiddiv) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModel.kt:58]: Oh right! `withCol` is a db wrapper. I'll lift it up.

**Comment by thedroiddiv** [comment]
> As a request: could the conclusion of this be moved into the class/argument documentation:

It's there as a test, will include in docs too. 


Todos before next approval:
- [x] Add the conclusion to docs [19499#discussion_r2532184695](https://github.com/ankidroid/Anki-Android/pull/19499#discussion_r2532184695)
- [x] Replace if-else partitioning with Array::partition
- [ ] ~Lift up db call out of loop~
- [x] Add a todo for "Lift up db call out of loop"

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModel.kt (hunk 4 above)
Comment (thedroiddiv) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModel.kt:58]: I checked, there's no existing function to get all decks from a list. 
Will be needing help to add that.
`getNote` produces call to `backend.getNote(nid: Long)` from constructor itself  which I believe makes a db call too? 
```kotlin
fun getNote(id: NoteId): Note = Note(this, id)
```
I don't see a way to query a for a list of note, as the constructor itself calls backend.getNote.

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModel.kt:58]: Leave it as a TODO - no need to handle it now as it was problematic before

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModel.kt [hunk 6]
```diff
@@ -26,9 +26,12 @@ import kotlinx.coroutines.flow.asStateFlow
 /**
  * @param noteIds IDs of notes whose tags should bfe retrieved and marked as "checked"
  * @param checkedTags additional list of checked tags.
+ * These tags coming from EXTRAS are treated as absolute checked and cannot be indeterminate.
  * @param isCustomStudying true if all inputs are to be handled as unchecked tags, false otherwise(
  * this is a temporary parameter until custom study by tags is modified)
  *  They are joined with the tags retrieved from noteIds
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModel.kt:32]: This seems to be in the wrong place, as does the line below

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModel.kt [hunk 7]
```diff
@@ -26,9 +26,12 @@ import kotlinx.coroutines.flow.asStateFlow
 /**
  * @param noteIds IDs of notes whose tags should bfe retrieved and marked as "checked"
  * @param checkedTags additional list of checked tags.
+ * These tags coming from EXTRAS are treated as absolute checked and cannot be indeterminate.
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModel.kt:29]: I feel this documentation is a little too far away from the caller to understand what `EXTRAS` is

Fully optional, or moving it to another issue


```patch
Subject: [PATCH]
---
Index: AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModelTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModelTest.kt b/AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModelTest.kt
--- a/AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModelTest.kt	(revision 3957d757ab0e6000579a4586595c25819ebd63d1)
+++ b/AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModelTest.kt	(date 1764544045091)
@@ -16,8 +16,10 @@
 
 package com.ichi2.anki.dialogs.tags
 
+import androidx.lifecycle.SavedStateHandle
 import androidx.test.ext.junit.runners.AndroidJUnit4
 import com.ichi2.anki.RobolectricTest
+import com.ichi2.anki.dialogs.tags.TagsDialog.DialogType
 import com.ichi2.anki.libanki.NoteId
 import com.ichi2.anki.libanki.testutils.ext.newNote
 import kotlinx.coroutines.ExperimentalCoroutinesApi
@@ -69,7 +71,7 @@
     fun `single note produces correct checked, indeterminate and all sets`() =
         runTest(testDispatcher) {
             val vm =
-                TagsDialogViewModel(
+                createViewModel(
                     noteIds = listOf(note1),
                     checkedTags = listOf("a"),
                     isCustomStudying = false,
@@ -90,7 +92,7 @@
             // note 1           a, b, c
             // note 2              b, d
             val vm =
-                TagsDialogViewModel(
+                createViewModel(
                     noteIds = listOf(note1, note2),
                     checkedTags = emptyList(),
                     isCustomStudying = false,
@@ -118,7 +120,7 @@
     fun `extra checkedTags is absolute checked and not indeterminate`() =
         runTest(testDispatcher) {
             val vm =
-                TagsDialogViewModel(
+                createViewModel(
                     noteIds = listOf(note1),
                     checkedTags = listOf("d", "x"),
                     isCustomStudying = false,
@@ -143,7 +145,7 @@
     fun `custom study mode makes all tags unchecked`() =
         runTest(testDispatcher) {
             val vm =
-                TagsDialogViewModel(
+                createViewModel(
                     noteIds = listOf(note1, note2),
                     checkedTags = listOf("a"),
                     isCustomStudying = true,
@@ -162,3 +164,21 @@
             assertTrue(tags.copyOfAllTagList().isNotEmpty())
         }
 }
+
+private fun RobolectricTest.createViewModel(
+    noteIds: List<NoteId>,
+    checkedTags: List<String>,
+    isCustomStudying: Boolean,
+): TagsDialogViewModel {
+    val bundle = TagsDialog().withArguments(targetContext,
+        type = if (isCustomStudying) DialogType.CUSTOM_STUDY else DialogType.EDIT_TAGS,
+        noteIds = noteIds,
+        checkedTags = ArrayList(checkedTags)
+    ).arguments
+
+    val savedState = SavedStateHandle.createHandle(
+        restoredState = null,
+        defaultState = bundle
+    )
+    return TagsDialogViewModel(savedState)
+}
Index: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModel.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModel.kt b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModel.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModel.kt	(revision 3957d757ab0e6000579a4586595c25819ebd63d1)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModel.kt	(date 1764543713358)
@@ -15,29 +15,50 @@
  */
 package com.ichi2.anki.dialogs.tags
 
+import androidx.lifecycle.SavedStateHandle
 import androidx.lifecycle.ViewModel
 import com.ichi2.anki.CollectionManager.withCol
 import com.ichi2.anki.asyncIO
-import com.ichi2.anki.libanki.NoteId
+import com.ichi2.anki.browser.IdsFile
+import com.ichi2.anki.dialogs.tags.TagsDialog.Companion.ARG_CHECKED_TAGS
+import com.ichi2.anki.dialogs.tags.TagsDialog.Companion.ARG_DIALOG_TYPE
+import com.ichi2.anki.dialogs.tags.TagsDialog.Companion.ARG_TAGS_FILE
+import com.ichi2.anki.dialogs.tags.TagsDialog.DialogType
 import kotlinx.coroutines.Deferred
 import kotlinx.coroutines.flow.MutableStateFlow
 import kotlinx.coroutines.flow.asStateFlow
 
-/**
- * @param noteIds IDs of notes whose tags should bfe retrieved and marked as "checked"
- * @param checkedTags additional list of checked tags.
- * These tags coming from EXTRAS are treated as absolute checked and cannot be indeterminate.
- * @param isCustomStudying true if all inputs are to be handled as unchecked tags, false otherwise(
- * this is a temporary parameter until custom study by tags is modified)
- *  They are joined with the tags retrieved from noteIds
- *
- *  @see <a href="https://github.com/ankidroid/Anki-Android/pull/19499#discussion_r2532184695">Extra checked tags</>
- */
-class TagsDialogViewModel(
-    noteIds: Collection<NoteId> = emptyList(),
-    checkedTags: Collection<String> = emptyList(),
-    isCustomStudying: Boolean = false,
-) : ViewModel() {
+class TagsDialogViewModel(savedStateHandle: SavedStateHandle) : ViewModel() {
+
+    /**
+     * IDs of notes whose tags should bfe retrieved and marked as "checked"
+     */
+    private val noteIds =
+        requireNotNull(savedStateHandle.get<IdsFile>(ARG_TAGS_FILE)) {
+            "$ARG_TAGS_FILE is required"
+        }.getIds()
+
+    /**
+     * Additional list of checked tags.
+     *
+     * These tags are tags of a current note, and cannot be indeterminate.
+     * These tags may not yet be saved to the collection.
+     *
+     * @see <a href="https://github.com/ankidroid/Anki-Android/pull/19499#discussion_r2532184695">Extra checked tags</>
+     */
+    private val checkedTags =
+        requireNotNull(savedStateHandle.get<ArrayList<String>>(ARG_CHECKED_TAGS)) {
+            "$ARG_CHECKED_TAGS is required"
+        }
+
+    /**
+     * `true` if all inputs are to be handled as unchecked tags, `false` otherwise
+     * (this is a temporary parameter until custom study by tags is modified)
+     */
+    val isCustomStudying = savedStateHandle.get<DialogType>(ARG_DIALOG_TYPE)
+        ?.let { it == DialogType.CUSTOM_STUDY } == true
+
+
     val tags: Deferred<TagsList>
 
     private val _initProgress = MutableStateFlow<InitProgress>(InitProgress.Processing)
Index: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt	(revision 3957d757ab0e6000579a4586595c25819ebd63d1)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt	(date 1764543713364)
@@ -26,8 +26,6 @@
 import androidx.fragment.app.viewModels
 import androidx.lifecycle.flowWithLifecycle
 import androidx.lifecycle.lifecycleScope
-import androidx.lifecycle.viewmodel.initializer
-import androidx.lifecycle.viewmodel.viewModelFactory
 import androidx.recyclerview.widget.LinearLayoutManager
 import androidx.recyclerview.widget.RecyclerView
 import com.ichi2.anki.CollectionManager.TR
@@ -90,30 +88,7 @@
     private lateinit var selectedOption: CardStateFilter
 
     @VisibleForTesting
-    val viewModel: TagsDialogViewModel by viewModels {
-        val idsFile =
-            requireNotNull(
-                BundleCompat.getParcelable(requireArguments(), ARG_TAGS_FILE, IdsFile::class.java),
-            ) {
-                "$ARG_TAGS_FILE is required"
-            }
-        val noteIds = idsFile.getIds()
-        val checkedTags =
-            requireNotNull(requireArguments().getStringArrayList(ARG_CHECKED_TAGS)) {
-                "$ARG_CHECKED_TAGS is required"
-            }
-        val type = BundleCompat.getParcelable(requireArguments(), ARG_DIALOG_TYPE, DialogType::class.java)
-        val isCustomStudying = type != null && type == DialogType.CUSTOM_STUDY
-        viewModelFactory {
-            initializer {
-                TagsDialogViewModel(
-                    noteIds = noteIds,
-                    checkedTags = checkedTags,
-                    isCustomStudying = isCustomStudying,
-                )
-            }
-        }
-    }
+    val viewModel: TagsDialogViewModel by viewModels()
 
     /**
      * Constructs a new [TagsDialog] that will communicate the results using the provided listener.
@@ -439,8 +414,8 @@
 
     companion object {
         const val ARG_TAGS_FILE = "tagsFile"
-        private const val ARG_DIALOG_TYPE = "dialogType"
-        private const val ARG_CHECKED_TAGS = "checkedTags"
+        const val ARG_DIALOG_TYPE = "dialogType"
+        const val ARG_CHECKED_TAGS = "checkedTags"
 
         /**
          * The filter that constrains the inputted tag.

```

**Review by david-allison — APPROVED** [review]
You asked for a re-review. I was happy, and still treat this as an approve, but there's an optional improvement I felt was relevant

**Comment by mikehardy** [comment]
@david-allison per discussion on discord, queue for release-2.23 pick or not? I think we decided not - but perhaps later after alpha testing verifies it's working?

**Comment by david-allison** [comment]
As discussed, a little too much risk. My mistake last year with tags still haunts me.

Let's aim for a fairly quick 2.24 with this in

**Comment by thedroiddiv** [comment]
Hey, I was OOO last entire week, will sit on this PR once again coming week.

**Comment by thedroiddiv** [comment]
@david-allison @mikehardy I'm not sure what actionable item do I have here after "Queued for cherry pick..." tag.

Do I apply the suggested patch and push? Or the current code is mergable?

**Comment by david-allison** [comment]
No action needed, awaiting second approval.

After a brief discussion, tag changes are a little too high risk to cherry pick to the 2.23 release. I screwed up here last year.

**Comment by david-allison** [comment]
For second reviewer: Ensure this use case is tested, or re-open the issue once this is merged:

* https://github.com/ankidroid/Anki-Android/issues/20189#issue-3839008548

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModel.kt (hunk 7 above)
Comment (thedroiddiv) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialogViewModel.kt:29]: I think, let's keep this refactor independent from this, maybe done in another PR. This is already as you highlighted a high-risk change, so keeping the changes minimal. 

Can definitely re-look on the docs aspect.

**Review by lukstbit — APPROVED** [review]
No complaints, the fix looks good.
Also verified the linked issue and everything seems ok.

**Comment by thoral** [comment]
Thank you very much to all participants who fixed or helped to fix this bug! 
Thorsten
