### PR TITLE
AnkiDroidJS: display blank if button unavailable

### LINKED ISSUE #6623: AnkiDroidJS.ankiGetNextTime4() still returns a value even when it should be empty after failing a card
Hi, I think i got access to beta or something as AnkiDroidJS.ankiGetNextTime4() started working even though I haven't noticed an official release.

For example I have a mature card with 4 buttons available (Again/Hard/Good/Easy) and AnkiDroidJS.ankiGetNextTime4() will return "2.9 mo". I fail that card, and the next time the card is shown, it will have only 3 buttons available (Again/Good/Easy), but AnkiDroidJS.ankiGetNextTime4() will still return "2.9 mo". I believe it should be empty right? It normally is if a card wasn't mature and had only 3 buttons.

I use my custom interface and this code to always press just the "Good" option, it works fine it i don't fail a card, if i do it stops working.

   if (AnkiDroidJS.ankiGetNextTime4() == "") {
         answerButtonEase2();
     } else {
          answerButtonEase3();
     }

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description

Bugfix - Previously the previous time was shown if Ease4 was unavailable

## Fixes
Fixes #6623

## Approach
Set the text to an empty string if the button is not available.

## How Has This Been Tested?

⚠️ Unit tested only

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java [hunk 1]
```diff
@@ -693,12 +693,8 @@ protected void displayAnswerBottomBar() {
         if (shouldShowNextReviewTime()) {
             mNext1.setText(mSched.nextIvlStr(this, mCurrentCard, Consts.BUTTON_ONE));
             mNext2.setText(mSched.nextIvlStr(this, mCurrentCard, Consts.BUTTON_TWO));
-            if (buttonCount > 2) {
-                mNext3.setText(mSched.nextIvlStr(this, mCurrentCard, Consts.BUTTON_THREE));
-            }
-            if (buttonCount > 3) {
-                mNext4.setText(mSched.nextIvlStr(this, mCurrentCard, Consts.BUTTON_FOUR));
-            }
+            mNext3.setText(buttonCount > 2 ? mSched.nextIvlStr(this, mCurrentCard, Consts.BUTTON_THREE) : "");
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java:696]: The idea seems correct but rather than shoo the horses back in the barn after they escape, should all the button text be cleared on hideEaseButtons? 

https://github.com/ankidroid/Anki-Android/blob/7dd8301088b9afb80f9fb7fd9f2350cd25e80c11/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L1614-L1621

You may have already considered that, but it seems like when if we need to empty strings because in JS vs Java we don't control visibility, we should do that in the same place we control visibility in java

Otherwise, does seem like it would work here

Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java:696]: No real preference between the two - I'll re-push

**Comment by mikehardy** [comment]
Something is wrong with the test on windows but not other platforms which makes me think the test just has a race condition and needs a super.advanceLooper (or whatever I called it) or something? I can't see how the code is wrong but it is persistent on restarts of this travis job

```
com.ichi2.anki.ReviewerTest > jsTime4ShouldBeBlankIfButtonUnavailable FAILED

    java.lang.Exception: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.

        at org.robolectric.android.internal.AndroidTestEnvironment.checkStateAfterTestFailure(AndroidTestEnvironment.java:470)

        at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:548)

        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)

        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)

        at java.util.concurrent.FutureTask.run(FutureTask.java:266)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

        at java.lang.Thread.run(Thread.java:748)

        Caused by:

        java.lang.AssertionError: The 4th button should not be visible

        Expected: is <3>

             but: was <4>

            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)

            at com.ichi2.anki.ReviewerTest.jsTime4ShouldBeBlankIfButtonUnavailable(ReviewerTest.java:83)


```

**Comment by david-allison-1** [comment]
Thanks for the heads up! Worked fine on my Windows box.

**Comment by mikehardy** [comment]
> Thanks for the heads up! Worked fine on my Windows box. Do we have a mechanism to say "wait until all async tasks are completed"? I'd have hoped Robolectric would allow it.

I am not aware of one. It could be obvious and I either missed it or did not search well. I'm doing a really cheesy wait in these cases. I feel kind of bad about it, and it's worked rock stable for a year...

https://github.com/ankidroid/Anki-Android/blob/44192bbf70781755d5b2bc3a4cf1124a73763e7c/AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java#L133-L138

It's also formatted poorly, something I just see now and so is extra shameful

**Comment by david-allison-1** [comment]
Was already running `idle` on the looper, but let's see if the `Thread.sleep` will make a difference

**Comment by david-allison-1** [comment]
Still unhappy: https://travis-ci.com/github/david-allison-1/Anki-Android/jobs/358005683

```
com.ichi2.anki.ReviewerTest > jsTime4ShouldBeBlankIfButtonUnavailable FAILED
    java.lang.Exception: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.
        at org.robolectric.android.internal.AndroidTestEnvironment.checkStateAfterTestFailure(AndroidTestEnvironment.java:470)
        at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:548)
        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        Caused by:
        java.lang.AssertionError: The 4th button should not be visible
        Expected: is <3>
             but: was <4>
            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
            at com.ichi2.anki.ReviewerTest.jsTime4ShouldBeBlankIfButtonUnavailable(ReviewerTest.java:83)
```

**Comment by mikehardy** [comment]
What in the ?? It's still unhappy! Most bizarre

**Comment by david-allison-1** [comment]
We'll need to run this a few more times once we get a potential fix. The tests passed on my CI instance

**Comment by mikehardy** [comment]
You can always call advanceLooper multiple times :-)

**Comment by mikehardy** [comment]
How do you want to handle this? I don't want to go back to Travis being as flaky as it was a couple weeks ago but I want the fix in, should we just hit the re-run job button on the windows instance a bunch and see what happens? I've seen it succeed at least twice now on the last push, with no fails so far on the last push. I just clicked it again, so I am:

success: 2
fail: 0
pending: 1

**Comment by david-allison-1** [comment]
I previously had a Linux failure.

I haven't seen it fail since adding in a second `displayAnswer(reviewer)`, but I don't think that was before the line that was failing.

I'll rerun my personal Travis instance a few more times today, if that goes green, we assume we've fixed the build.

At the first sign of failure, disable the test. I have no intention of moving back to a flaky Travis.

**Comment by mikehardy** [comment]
Fair enough - I'll keep restarting the main travis for windows and linux unit test today as I remember and add to the totals. Seems pretty good right now FWIW

**Comment by mikehardy** [comment]
This no longer seems to fail, I feel I have a sufficient sample size to merge and just keep an eye on it
:muscle:
