### PR TITLE
Move essential file migration into the service

### LINKED ISSUE #13868: ForegroundServiceStartNotAllowedException on start
https://ankidroid.org/acra/app/1/bug/49980/report/fd9bac98-8c65-474f-96d2-a8e3811b5606

Seems to appear as start. Becaume logcat is very short
```

--------- beginning of main
05-15 08:13:54.251 I/AnkiDroid( 6305): AnkiActivity::onStart - DeckPicker
05-15 08:13:54.266 I/AnkiDroid( 6305): AnkiActivity::onResume - DeckPicker
05-15 08:13:54.463 E/AnkiDroid( 6305): CollectionManager/ blocked main thread for 177ms:
05-15 08:13:54.463 E/AnkiDroid( 6305): com.ichi2.anki.DeckPicker.refreshState(DeckPicker.kt:72)
05-15 08:13:54.576 I/AnkiDroid( 6305): Updating deck list UI
```

```
ndroid.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service com.ichi2.anki/.services.MigrationService
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4816)
	at android.os.Parcel.readParcelable(Parcel.java:4778)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3006)
	at android.os.Parcel.createException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.os.Parcel.readException(Parcel.java:2920)
	at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:5302)
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1894)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1870)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:822)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:822)
	at androidx.core.content.g.a(R8$$SyntheticClass:1)
	at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(ContextCompat.java:1)
	at androidx.core.content.ContextCompat.startForegroundService(ContextCompat.java:7)
	at com.ichi2.anki.DeckPicker.startMigrateUserDataService(DeckPicker.kt:18)
	at com.ichi2.anki.DeckPicker.startingStorageMigrationInterruptsStartup(DeckPicker.kt:41)
	at com.ichi2.anki.DeckPicker.handleStartup(DeckPicker.kt:45)
	at com.ichi2.anki.DeckPicker$migrate$1$elapsedMillisDuringEssentialFilesMigration$1$1$1.invokeSuspend(DeckPicker.kt:59)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:119)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:15)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:29)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)
```

### LINKED ISSUE #13970: Don't tie the essential files dialog to the activity lifecycle
Another problem with starting the service right away when starting the migration. 

A service means that the app will be much less likely to get killed while migrating essential files. You'd think that this very good, and it is, but this also means that deck picker will be more likely to get recreated or finished and relaunched while essential file migration is taking place, unlocking the UI.

However while it will be more of a problem in this case, it is a problem now as well. For instance, if you change device theme while essential files are being migrated, you are going to see the “Collection not opened error”. This here is a more general problem with `withProgress`; it is a function that shows some UI that is tied to current activity and is commonly launched in its lifecycle scope, yet often the code inside of it is ***not*** UI-related, such as running migration. That is to say, it's misused. I think we can try to fix the simple cases using a dialog fragment, but we really want to properly move to view model & friends. Also note that:
* The `launchCatchingTask {}` block is canceled when the activity is destroyed, potentially ruining the job that is performed
* A block that is canceled in this way but still running will leak the activity

But when using a service for it we can expect the activity to be not only recreated, but also completely finished and relaunched. In this case we are going to lose our fragment.

I suppose that ideally we will have to introduce yet another state—for migrating essential files—and deal with it like we deal with the UI for media migration, recreating the progress dialog.

_Originally posted by @oakkitten in https://github.com/ankidroid/Anki-Android/issues/13868#issuecomment-1584673040_

### PR DESCRIPTION
**Pull request by oakkitten**
#### Purpose / Description / Approach
See commit messages (no, really). Note the new TODO. Note string changes in the notification.

Below are the new error dialog shown when there's an error while migrating essential files, and the altered media migration error dialog.

 

A demo with a few activity recreations. Note that at the end of the video there's a rogue dialog offering to resume migration under the migration dialog, that's a result of the problem described in the TODO.

https://github.com/ankidroid/Anki-Android/assets/1710718/7ef4ca82-bad5-4c3d-ae25-c44fcfbae0fc

Thanks to @snowtimeglass for help with strings.

#### Fixes
Fixes #13970, hopefully fixes #13868 and closes #13918 as obsolete

#### How Has This Been Tested?
Tested on my device

#### Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by oakkitten** [comment]
Emulator test [are passing](https://github.com/oakkitten/Anki-Android/actions/runs/5364787475) in my repo

**Review by BrayanDSO — COMMENTED** [review]
The second commit isn't necessary to this PR, and I don't think that we should spend time discussing it. The first could be split more, since it is reasonably big and deals with a lot of different things.

But overall, LGTM. Approved after the second commit is dropped.

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 1]
```diff
@@ -2657,8 +2681,7 @@ open class DeckPicker :
             .setMessage(message)
             .setNegativeButton(R.string.dialog_cancel) { _, _ -> }
             .setPositiveButton(R.string.migration__resume_after_failed_dialog__button_positive) { _, _ ->
-                getSharedPrefs(this@DeckPicker).edit { remove(PREF_MIGRATION_ERROR_TEXT) }
-                startMigrateUserDataService()
```
[the remark this answers is not in the document]
Comment (oakkitten) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:2661]: Done

**Comment by oakkitten** [comment]
No need to discuss, just merge 😜

Updated to remove the unused method.

**Comment by BrayanDSO** [comment]
> No need to discuss, just merge

No need to merge, just drop it 😉

**Comment by oakkitten** [comment]
But it's so good 😋 And since we are merging with rebase it hardly matters history-wise.

P.S. The first commit is large, yeah, but it's actually a result of several squished comments. They were too interconnected and fixing each other, there just wasn't a point in keeping them separate, and too much effort

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 2]
```diff
@@ -418,6 +420,8 @@ open class DeckPicker :
         mShortAnimDuration = resources.getInteger(android.R.integer.config_shortAnimTime)
 
         Onboarding.DeckPicker(this, mRecyclerViewLayoutManager).onCreate()
+
+        launchShowingHidingEssentialFileMigrationProgressDialog()
```
Comment (dae) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:424]: Naming nit: I don't understand what "ShowingHiding" is intending to communicate.

File: AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt [hunk 3]
```diff
@@ -87,42 +101,50 @@ const val PREF_MIGRATION_ERROR_TEXT = "migrationErrorText"
...
 
     sealed interface Progress {
-        object CalculatingTransferSize : Progress
+        sealed interface Notificationable
+
+        sealed interface Running : Progress, Notificationable
 
-        data class Transferring(val transferredBytes: Long, val totalBytes: Long) : Progress {
-            val ratio get() = if (totalBytes == 0L) 1f else transferredBytes.toFloat() / totalBytes
+        object CopyingEssentialFiles : Running
```
Comment (dae) [inline AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt:118]: You're mixing an enumeration (can only be one) and grouping (multiple cases can match), which makes things a bit unclear. I think this would be clearer if you only list the enum cases, and use helper methods to determine group, eg

```kotlin
if (progress is Progress.Notificationable) {
```
to
```kotlin
if (progress.canNotifyUserOfChanges())
```

**Review by dae — COMMENTED** [review]
The first commit looks mostly positive: correctness and readability appear to have improved. Some minor nits below.

I second Brayan and recommend you split the second commit off into a separate PR, or you risk this PR getting held up by bikeshedding.

**Comment by BrayanDSO** [comment]
> But it's so good 😋 

If I liked the commit, I would already approved. 

Splitting a PR doesn’t hurt. Blocking things only to push a debatable NF change does.

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt (hunk 2 above)
Comment (oakkitten) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:424]: Not sure if I invented this naming pattern myself or took from somewhere but basically methods called `showHideStuff()` either show or hide stuff, that is that they can do both depending on the state or passed arguments. I think in many cases it reads better than `updateStuffVisibility` or whatever. You could say perhaps `launchHandlingEssentialFileMigrationProgressDialog` but I prefer to be more concrete.

File: AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt (hunk 3 above)
Comment (oakkitten) [reply AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt:118]: I think this kind of mixing is okay because enumeration is done using classes and grouping is done using interfaces

**Comment by oakkitten** [comment]
I made commit 2 as I didn't like the way commit 1 over-boiler-plated the `MigrationFailedDialogFragment`, and one thing I always try to avoid is leaving the code I touched in a worse state than it was before me. It's nearly perfect code (as in, one probably wouldn't implement it differently, and if they would, it must be a silly mistake on my part). It's also less than 10 lines of code in a commit that changes 500 lines. So if the problem is wasting time, by now we probably wasted more of it on arguing whether or not we want to discuss it rather than on discussing it

**Comment by BrayanDSO** [comment]
> If I liked the commit, I would already approved.

Maybe I wasn't clear, here I mean that I don't like the change, and currently wouldn't like it to get it merged, either if it is on this PR on in another one. If I wanted to merge it, I wouldn't block this. Hence I suggested to get it split so it won't block this PR over discussion over NF changes.

I won't comment this matter anymore in this PR. Another reviewer can consider my approval if it the commit was dropped.

File: AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt (hunk 3 above)
Comment (dae) [reply AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt:118]: Using interfaces for categorizing things feels like "clever code" to me, and I found it hard than necessary to follow. The intro section of this article sums up my thoughts pretty well:

https://www.linkedin.com/pulse/clear-code-vs-clever-importance-readability-software-development

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt (hunk 2 above)
Comment (dae) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:424]: I feel like there are too many verbs in the name. How about something like this?

```
lifecycleScope.launch { showOrHideEssentialFileMigrationProgressDialog() }
```

**Comment by dae** [comment]
I'm not fond of the approach in the second commit either. Personally, I think an explicit data class for each fragment is more readable than a tuple of types, and it would avoid the need for a mass of generics for different tuple lengths. But other developers may feel differently, and it may take time to reach a consensus, which is why I recommend you don't insist on tying the completion of this PR to it.

File: AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt (hunk 3 above)
Comment (oakkitten) [reply AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt:118]: Not sure I see how this is “clever”, interfaces representing certain qualities, such as `Serializable`, are very common?..

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt (hunk 2 above)
Comment (oakkitten) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:424]: To explain my reasoning for the name.

First, personally, I haven't yet decided whether or not I have a strong preference about the `lauch` suffix (`launchDoingStuff()` vs `launch { doStuff() }`). I slightly prefer the former as it unties the scope from the caller and I think it makes sense more time than it doesn't. For instance, here,

https://github.com/ankidroid/Anki-Android/blob/4e708502c2eb53b000d37856c3c29c304da8df5f/AnkiDroid/src/main/java/com/ichi2/anki/ui/preferences/screens/BackupLimitsPresenter.kt#L183

if not using the suffix, you'd have to say `viewModel.viewModelScope.launch { viewModel.fetchBackupLimits() }` (CMMIW), which is not ideal IMO. Now, while it doesn't make sense for anything else to call `launchShowingHidingEssentialFileMigrationProgressDialog` but the activity, I've been using the suffix for consistency in similar cases and it works for me I think.

Then, the name `showOrHideEssentialFileMigrationProgressDialog()` usually implies momentary action. As in, following model change, you'd call a method such as this to do a single change, and then stop. With `launchShowingHidingEssentialFileMigrationProgressDialog`, the language is kind of ambigous, it's not clear (to me) whether or not the action is one-off. While it can be confusing, I prefer to confuse than to mislead.

File: AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt (hunk 3 above)
Comment (dae) [reply AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt:118]: I think that the typical usage of interfaces is to define a set of methods common to multiple classes. Aren't empty marker interfaces somewhat less common outside of some notable exceptions, and typically used when you want third-party code to be able to opt-in to something?  And because you've mixed the interfaces and objects together and used inheritance, it's hard to see at a glance what the different possible states are. Compare something like the following, where the possible states can be more quickly seen:

```kotlin
    sealed interface Progress {
        object Unknown
        object CopyingEssentialFiles
        object CalculatingNumberOfBytesToMove
        data class MovingFiles(val movedBytes: Long, val totalBytes: Long) : Progress
        object Complete
        data class Failed(val e: Exception, val rolledBack: Boolean) : Progress
    }

    // optionally defined separately to keep the interface clean
    fun Progress.MovingFiles.ratio(): Float {
        return if (totalBytes == 0L) 1f else movedBytes.toFloat() / totalBytes
    }
```

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt (hunk 2 above)
Comment (dae) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:424]: Fair point on the momentary action - I'd forgotten that it's a long-running action that updates the interface in a loop. How about something like launchProgressDialogTask or launchProgressDialogManager?

**Comment by mikehardy** [comment]
@oakkitten when you run into solid resistance on review, don't force it. Drop the commit as requested please.

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt (hunk 2 above)
Comment (oakkitten) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:424]: This creates a new name—what is a “progress dialog task“? Making new names are okay for things that used often; this is ever going to be used only once so I'd prefer to spell it out. Besides, this way we avoid the need to have a javadoc. 

(Well, I can't be sure about the javadoc part; what I can be sure abou, I think, is that I myself reading the name of the function after a year would find it understandable still.)

File: AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt (hunk 3 above)
Comment (oakkitten) [reply AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt:118]: “Notificationable” isn't the only group here though, this also introduces the groups “running”/“not running”, group “done”, group “failed”. While we can get away with `data class Failed` (we don't have stuff like `is RolledBack` in the code), what should we do about the rest?

I can see how this doesn't read as linearly as an `enum class` but IMO it is still very readable. I'd say that I feel like the language was designed specifically with this use case in mind. It feels natural.

I would also keep the `ratio` thing in the `MovingFiles` class because the `Progress` is defined at class level and the `ratio` thing would have to be located at top level, visually too far apart from `Progress`.

**Comment by oakkitten** [comment]
...I was going to change the 2nd commit to @dae's suggested option when I have time (probably Friday), since I liked it as well (as I said). Or maybe to wait for further opinion since this is still in review and isn't going to be merged for the time being anyway. Besides, I specifically made the commit easily droppable, and also I left the checkbox on GitHub to allow maintainers to write my branch ticked, so y'all can drop the commit as well.

File: AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt (hunk 3 above)
Comment (dae) [reply AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt:118]: Personally, I don't find it "very readable", which is why I brought it up in the first place :-) You don't seem to be convinced there's a need to change this though, so I'll save us both time and won't argue the point further.

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt (hunk 2 above)
Comment (dae) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:424]: I still find ShowingHiding a bit difficult to follow, but this is a minor issue in the grand scheme of things - feel free to mark this as resolved.

Comment (oakkitten) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:424]: Suggestions welcome! I'm absolutely not bent on this naming pattern, it's likely that it is an invention of my own, and while it works well for me, I just can't judge how well it works for everyone else.

File: AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt (hunk 3 above)
Comment (oakkitten) [reply AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt:118]: I'm not bent on using interfaces here, even though I fine this very readable. But I can't think of a cleaner alternative. We still need the groups since we are using them in code. For instance, if we don't have the group `Notificationable`, `makeMigrationProgressNotification` would have to handle the the case `Unknown`, so instead of 

https://github.com/ankidroid/Anki-Android/blob/5f14cde2f71c5ba4925b89aeddc5fc97521e5d79/AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt#L221-L223

we'd have something like

```kt
 if (progress.canNotifyUserOfChanges()) { 
     startForeground(2, makeMigrationProgressNotificationOrNull(progress)!!) 
 }
```

or make `makeMigrationProgressNotification` throw an exception in the case of `Unknown`, or use another enum, or I don't know.

Comment (dae) [reply AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt:118]: Since everything but Unknown is notifiable, and Unknown seems to exist only because MutableStateFlow needs an initial value, perhaps another approach you could use is to have the flow pass a nullable value. Then instead of checking for runnable, you can check if the value is non-null, and all the other code only needs to think about the non-null value.

In any case, I don't want to hold up this PR pushing you to rewrite parts of it - we really need to get scoped storage out sooner rather than later. Please consider my comments here as feedback for future work, instead of something you should change now.

**Comment by mikehardy** [comment]
It seems to me that there is a contentious commit mixed into a PR that is essential for scoped storage, while it is not absolutely essential to the scoped storage work.

Peel it out. All attention + speed should be dedicated to getting the scoped storage commits reviewed and in.

It does appear that some consensus may be possible to get the second commit through but *as a practice* if a PR can be split and there is any contention at all on a splittable commit in a PR, we should all get in the habit of saying "oh okay" and split the thing.

So I reiterate: please split the PR, get the second commit out without any further maybe-ing or but-we-could-ing or anything. Let's get the scoped storage stuff done.

File: AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt (hunk 3 above)
Comment (oakkitten) [reply AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt:124]: Ah thanks! Implemented this, also made `rolledBack` an argument.

Comment (dae) [reply AnkiDroid/src/main/java/com/ichi2/anki/services/MigrationService.kt:124]: It's easier to follow than before :+1:

**Comment by mikehardy** [comment]
I haven't had time personally to look - I'm in the midst of packing for extended travel - but I assume with the force push just now that you have addressed current concerns (I hope I'm assuming correctly...) so I'm re-tagging this for review.

Am I correct in thinking this represents the end of functional scoped storage work? I hope so! If so this should get the highest priority from everyone so we can finish this thing. Then it's just crash fixes as we triage+prioritize them, then release...

**Review by BrayanDSO — APPROVED** [review]
The ergonomics changes were nice. Let's do this

**Comment by dae** [comment]
I didn't spot any problems, and it ran correctly for me when I attempted to migrate a collection and some media in the simulator, so LGTM.

**Review by mikehardy — APPROVED** [review]
Fantastic - syncing strings now, to merge this
