### PR TITLE
fix: cloze type in answers

### LINKED ISSUE #19799: [New study screen]: {{type:cloze:Text}} Incorrect display on the Back
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

Using {{type:cloze:Text}} on the front and back of the card, using **more than one** cloze deletion.

### Expected behaviour

Image
Image
- In the new study screen, the display for {{type:cloze:Text}} on the back shows the entire content of the Text field.
- In the old study screen, only cloze deletions were displayed.

### Debug info

```text
AnkiDroid Version = 2.23.0 (4f768aa0be34e254d65fd4ebe19781b84e8efc37)  
Backend Version = 0.1.62-anki25.09.2 (25.09.2 3890e12c9e48c028c3f12aa58cb64bd9f8895e30)  
Android Version = 14 (SDK 34)  
ProductFlavor = play  
Device Info = Xiaomi | POCO | stone | stone_p_global | 22071219CG | mt6789  
Webview User Agent = Mozilla/5.0 (Linux; Android 14; 22071219CG Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/142.0.7444.171 Mobile Safari/537.36  
ACRA UUID = a76af6f6-4ea4-4a52-bab5-2f8a2b71ffec  
FSRS = 5.1.0 (Enabled: true)  
Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by BrayanDSO**
the issue was present in the new study screen and the previewers

## Fixes
* Fixes #19799

## How Has This Been Tested?

Emulator 31 with the sample deck shared in the issue:

https://github.com/user-attachments/assets/6199ba37-8360-4680-b8c2-79c53af475a2

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
So if I am parsing this correctly - previously we were matching the whole field name (which does not start with `cloze`...) vs the regex chunk that was just the part that may actually start with `cloze` ?

If so, +1 and I'll approve because I think that understanding is right (and then the read of the code looks good) if not then I'm lost and second reviewer should chuckle at my expense

**Comment by BrayanDSO** [comment]
> previously we were matching the whole field name (which does not start with cloze...) vs the regex chunk that was just the part that may actually start with cloze ?

{{type:cloze:Example}}

Previously, the field name was used, so in the example above it would be `Example`

Now it uses the regex chunk, as upstream does, which results in `cloze:Example`

**Comment by mikehardy** [comment]
ah okay, thank you. Mentally I wasn't modeling it quite correctly, but despite the slightly incorrect thought on which chunk was being regex'd out and which wasn't, what I was thinking still fed into the conditionals in the same way so the analysis holds. +1

File: AnkiDroid/src/main/java/com/ichi2/anki/previewer/TypeAnswer.kt [hunk 1]
```diff
@@ -97,13 +97,18 @@ class TypeAnswer private constructor(
             )
         }
 
+        /**
+         * @param rawField the content (x) of a `{{type:x}}` placeholder
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/previewer/TypeAnswer.kt:101]: Although correct, this is confusing (I imagine `type` and `cloze` to be equivalent precedence in `{{type:cloze:Field}}`)

Tests would clear it up, and you've marked these are requested.

Good to go, as it's a bugfix

**Review by david-allison — APPROVED** [review]
