### PR TITLE
fix(study screen): IME shown even with a hidden `<input>`

### LINKED ISSUE #19490: [Regression, new reviewer] Hidden type-in-the-answer field opens the keyboard
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

I am using a custom JS code to modify the behavior of "type in the answer" template. It worked fine in the new reviewer till AnkiDroid 2.23 alpha 7 but there's a regression in alpha 8.

Minimum reproduction steps:
1. Enable the new reviewer
2. Enable Settings → Advanced → Type answer into the card.
3. Use this as the front template:
```html
<div id="front">{{Front}}</div>
<div id="type">{{type:Back}}</div>

<script>
var typeElement = document.querySelector("#type");

if (true) {
   typeElement.style.display = "none";
} 
</script>
```

### Expected behaviour

Because the typing box is hidden, the keyboard shouldn't pop up (as in alpha 7). However, in alpha 8, the keyboard pops up.

### Debug info

```text
AnkiDroid 2.23 alpha 8
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by BrayanDSO**
## Fixes
* Fixes #19490

## Approach

This took me way longer than I wanted to.

Calling `.focus()` in the type-in-answer `<input>`, only worked if the WebView had been touched before. To fix that, I made the reviewer show the keyboard if `auto focus` was enabled. But it created a new issue with people that hide their `<input>` fields dynamically with JavaScript (#19490), so I had to use another fix. 

The goal was to make the IME show after calling `.focus()` on JavaScript.  But this was the kind of issue where neither logic, nor the docs, nor upstream code help. You need to test stuff a lot and do some rain dance until something magically works.

I tried hacking a touch in the WebView with dispatchTouchEvent (works, but too hacky), tried using `requestFocusFromTouch` and many combinations of focus between the webview and other views, and tried many using some delays here and there. I've reviewed the old reviewer code and tried to figure out what made it work, but I was unsucessful.

Then suddenly I copied and pasted some stuff, got it working, then pinned down to the use of `loadUrl()` instead of `evaluateJavascript()`

## How Has This Been Tested?

Emulator 34

[Screen_recording_20251120_141859.webm](https://github.com/user-attachments/assets/55e9d22e-fa9b-4313-ac38-314108c14392)

## Learning (optional, can help others)

Dealing with WebViews is painful

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt [hunk 1]
```diff
@@ -262,8 +261,9 @@ class ReviewerFragment :
                     if (isHtmlTypeAnswerEnabled) {
                         if (!autoFocusTypeAnswer) return@collect
                         webViewLayout.focusOnWebView()
-                        webViewLayout.evaluateJavascript("document.getElementById('typeans').focus();", null)
-                        insetsController.show(WindowInsetsCompat.Type.ime())
+                        // `evaluateJavascript()` doesn't trigger the IME unless the WebView
+                        // has been touched before, so ´loadUrl()` is used instead.
+                        webViewLayout.loadUrl("javascript:document.getElementById('typeans')?.focus();")
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt:266]: Considered a scarily named extension method

Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt:266]: are you suggesting to extract `document.getElementById('typeans')?.focus();` into a JS function?

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt:266]: Something along the lines of 

```kotlin
webViewLayout.evaluateJavascript_UNSAFE("document.getElementById('typeans')?.focus();")
```

Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt:266]: I hope we won't need to use `loadUrl` as an `evaluateJavascript` replacement again. 

If that happens, an extension method can be created.
