### PR TITLE
Set reschedule app bar button to show never by default

### LINKED ISSUE #6054: Reviewer toolbar defaults incorrect
###### Reproduction Steps

1.  Clear AnkiDroid app data in Android settings
2.  Open AnkiDroid and start reviewing

###### Expected Result
Same items in toolbar as 2.9.x

###### Actual Result
Reschedule is set to "Always show"

It looks like the issue crept in [here](https://github.com/ankidroid/Anki-Android/commit/7855dd0216828320fe46081b4407910661d58202)

### PR DESCRIPTION
**Pull request by mikehardy**
## Purpose / Description

The reschedule button has an incorrect default from preferences

## Fixes
Fixes #6054

## Approach
Change the default in prefs xml
Note via code comment where in code things should be in sync

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.java [hunk 1]
```diff
@@ -44,6 +44,7 @@ public ActionButtonStatus(ReviewerUi reviewerUi) {
     }
 
     public void setup(SharedPreferences preferences) {
+        // NOTE: the default values below should be in sync with preferences_custom_buttons.xml and reviewer.xml
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.java:47]: Note: MENU_DISABLED is not available in `reviewer.xml`

**Comment by mikehardy** [comment]
This went out with 2.10alpha72 - available as soon as google is done processing it
