### PR TITLE
Release TextToSpeech with a Context

### LINKED ISSUE #8084: [Bug] Changing theme (night mode) breaks TTS
###### Reproduction Steps

1. Enable TTS
2. Go to Study
3. Change theme from hamburger menu (switch on/off night mode)
4. Choose 'Replay audio' from dots menu
5. Complete review

###### Expected Result
On 'Replay audio', TTS works as it did when presenting the card initially.
After completing the review of the card, TTS reads the next card.

###### Actual Result
On 'Replay audio', a 'Select language' menu comes up. After selecting a language for the TTS, a toast error comes up saying 'No text-to-speech language available (short_code_of_language)'.
On presentation of a new card, the same series of events happens.

###### Debug info
AnkiDroid Version = 2.14.3

Android Version = 10

ACRA UUID = f939c8ba-2220-489e-abb1-d041f0afd05a

Scheduler = std2

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

Similar, and possibly related to #8085, but here there is visual feedback in the form of the configuration menu.
Exiting Study fixes TTS, but not if it is still in the background (where tapping the 'back' button brings it up immidiately). So re-initialization seems to fix it. What is peculiar to me is that when you flip the switch on the theme, a toast comes up saying that TTS is being initialized, but it clearly breaks in some way.
If I go to Decks from Study and select the previous deck again to back to Study, the language selected does become the new TTS language, even though the toast indicated the selection was unsuccesful.

### PR DESCRIPTION
**Pull request by JG916**
## Purpose / Description
TextToSpeech was being released (shutdown) incorrectly due to a race condition.
When AbstractFlashcardViewer is recreated (Ex: through changing themes), the newly created activity initialized a new TextToSpeech. 
The old activity then releases that same TextToSpeech instance from onDestroy()
TextToSpeech will not work until it is re-initialized.

## Fixes
Fixes #8084

https://user-images.githubusercontent.com/16379504/110561114-1fa2ee80-8115-11eb-9a4b-db9f48ae2677.mp4

## Approach
When TextToSpeech is initialized, a Context is passed in and stored.
That Context is always 'paired' with a single instance of TextToSpeech.
Because the caller that initialized the instance wants to make sure it cleans up when it's done, it attempts to release it.
The instance is stored in a static private field in a different class, so the caller cannot tell what the state of that instance is.
To prevent a caller from releasing an instance of TextToSpeech that was initialized by another caller, the same Context must be passed it to verify if the instance belongs to it or not.

This has some caveats though. For instance, right now the only context used is AbstractFlashcardViewer, but if you were to start passing in a shared context like the application context, this problem would re-occur.

Because of the overall structure of ReadText and its connections, it was hard to find a solution that didn't involve a massive amount of time and code changes.

## How Has This Been Tested?

1. Enable TTS
2. Go to Study
3. Change theme from hamburger menu (switch on/off night mode)
4. Choose 'Replay audio' from dots menu

The audio should play after both step 3 (when the card is first shown) and step 4.

Tested on an emulator with API 29.

## Learning (optional, can help others)
https://developer.android.com/reference/android/speech/tts/TextToSpeech
http://robolectric.org/javadoc/4.0/org/robolectric/shadows/ShadowTextToSpeech.html

Text to speech is shared through all applications. Maybe it's possible that the current usage here could be changed from a (pseudo) per-activity usage to something more like a singleton? The initialization takes quite a long time to run, and it's likely that when used once, it will be used quite often throughout the session, so a different setup and destroy system could run perform better.

When re-initializing TextToSpeech inside ReadText, it's directly overriding the old reference without calling `shutdown()` on it beforehand. I'm wondering how much of an effect this has...

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java [hunk 1]
```diff
@@ -337,8 +337,14 @@ public static void buildAvailableLanguages() {
...
-    public static void releaseTts() {
-        if (mTts != null) {
+    /**
+     * Request that TextToSpeech is stopped and shutdown after it it no longer being used
+     * by the context that initialized it.
+     * No-op if the current instance of TextToSpeech was initialized by another Context
+     * @param context The context used during {@link #initializeTts(Context, ReadTextListener)}
+     */
+    public static void releaseTts(Context context) {
+        if (mTts != null && mReviewer.get() == context) {
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java:347]: I think here we should clear the context too to prevent the only version of leak we can reasonably prevent with this ugly-but-quite-practical fix?

```suggestion
        if (mTts != null && mReviewer.get() == context) {
            context = null;
```

...I think?

**Review by mikehardy — CHANGES_REQUESTED** [review]
Just one comment on freeing the context in the one case we know enough to do so?

Also, the information in the PR about a possible refactor (or total restructure, really) where TextToSpeech is changed to match it's reality (that it is per-device really, so definitely should be true singleton in the Application and just stay initialized) is valuable - could you peel that into a separate issue for "the real fix"? We can mark it as an enhancement and perhaps someone will want to take it on for polishing

File: AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java (hunk 1 above)
Comment (JG916) [reply AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java:347]: Sorry, I'm not quite sure where the leak is happening here. 
`context` is not being stored anywhere from this function, so it shouldn't be leaking here.
Or if you meant `mReviewer`, that has a type of `WeakReference<Context>`, so it shouldn't retain it here either.

Correct me if I'm wrong about this, I haven't used Java in a few months now 😅

Comment (JG916) [reply AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java:347]: I can definitely put up an issue for the 'possible' fix soon. 

Take my solution suggestion with a mountain sized grain of salt though, there's a whole lot more about the architecture here and TextToSpeech I'd need to learn about before I'd be confident about it.

Comment (Arthur-Milchior) [reply AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java:347]: If `stop` or `shutdown` takes time to return, then `context` is kept in scope and so maybe can not be garbage collected. I do not know about java internal enough to know whether the garbage collector know that `contex` won't be used anymore, and I really really wish that we don't have to deal with this level of details.
Is there any reason to expect that one of those methods take time to return Mike? In particular that it takes so much time that it's a real concern?

**Review by Arthur-Milchior — COMMENTED** [review]
First and most importantly, thanks a lot for your first contribution. I clearly would have had a hard time guessing the cause. You even have added test, which is more than what I did when I started, really love that!

May I ask you something. Since you found the cause three days ago in https://github.com/ankidroid/Anki-Android/issues/8084 , I assume it's a coincidence that your first PR arrive exactly when we announced that we are doing a Google Summer of Code internship, right ? If so, fun coincidence. 

May I please ask you to change a little bit your commit message. Maybe the title could be something such as:

> Allow to change setting without breaking TTS

and the message would contain a copy of the PR information. This way, someone reading the code in a few years would understand why this was done if needed. This is especially important since this code is far from intuitive when you don't know why it must be done this way

**Comment by JG916** [comment]
Thanks for the kind words! It's great to find a repo that is this friendly 🙂

I haven't heard about your participation of summer of code until just now. Funny timing. I'm a little bit too old to be an intern, anyway.

I just pushed up a new commit message and description, too. LMK if this looks okay or not.

**Comment by mikehardy** [comment]
The context leak is the most minor of concerns IMHO - was more of a thought "if it's easy" - I'll re-review :-)

**Review by mikehardy — APPROVED** [review]
Sorry for the delay! This looks good to go, thank you!

**Comment by mikehardy** [comment]
Hi there!

Just a friendly notice (one per person for PRs merged in March, regardless of PR quantity) that we try to process OpenCollective payments monthly - it's time for March 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

Thanks!
