### PR TITLE
fix(sync): invalid sync server

### LINKED ISSUE #18890: Media sync failed on 2.21.0
I was on 2.22.0 alpha, synced my data and when I tried going back to 2.21.0 stable it wouldn't let me anymore. Now I deleted all the data locally and tried to sync on the stable version but it's not working, I don't have a custom server, it's the default one.

### PR DESCRIPTION
**Pull request by BrayanDSO**
## Fixes
* Fixes #18890 (I hope)

## Approach

Avoid sending an empty endpoint to the sync media. Similar to 02deb0a0a5905f1cca91aa20cedf67c80cc1bc83

## How Has This Been Tested?

I haven't

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by BrayanDSO** [comment]
Currently waiting for debug info in #18890

File: AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncWorker.kt [hunk 1]
```diff
@@ -156,21 +156,20 @@ class SyncWorker(
...
-                            }
-                            syncAuth {
-                                hkey = auth.hkey
-                                endpoint = response.newEndpoint
-                            }
-                        } else {
-                            auth
+                if (!syncMedia) return
+                val syncAuth =
+                    if (response.hasNewEndpoint() && response.newEndpoint.isNotEmpty()) {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncWorker.kt:161]: If the server returns an empty endpoint, is that a request for us to remove the currently provided setting?

From this change, there's no way for the server to 'blank' a bad/old endpoint value

Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncWorker.kt:161]: better ask @dae (more context in #18776)

Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/anki/worker/SyncWorker.kt:161]: Python code seems to do the same, since empty strings are considered false there

https://github.com/ankitects/anki/blob/e77cd791deb8d412d1ed9083f2697e389605823a/qt/aqt/sync.py#L118
