### PR TITLE
Fix learn ahead limit not working after updating setting

### LINKED ISSUE #16645: [BUG]: Learn ahead limit does not work
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Create a new card.
2. Press good (default learning steps).
3. Change `learn ahead limit` to >10mins.

### Expected behaviour

card shows up immediately

### Actual behaviour

card is shown as red in the deck picker screen but clicking on the deck shows that you need to wait a minute.

### Debug info

```text
AnkiDroid Version = 2.19alpha6 (d2ddaaf122f6d03501bfec0adb88f510d93499f0)

Backend Version = 0.1.39-anki24.06.2 (24.06.2 9b4dd54312de8798a3f2bee07892bb3a488d1f9b)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = realme

Model = RMX2193

Hardware = mt6768

Webview User Agent = Mozilla/5.0 (Linux; Android 11; RMX2193 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/125.0.6422.165 Mobile Safari/537.36

ACRA UUID = cf265e01-9693-407f-984d-61ddf9698fac

FSRS Enabled = true

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by lukstbit**
## Purpose / Description

Bug reproduction:
- have the _learn ahead limit_ set to a value that is below the good step value(below 10 min default)
- create a deck with one card to see the behavior more clearly
- review the card -> press good -> deck has 0 counts  and a toast that you can learn again in  x amount is displayed
- change the _learn ahead limit_ to a value that is above the good step, ex 15 minutes
- try to review -> app attempts to go to reviewer but goes back to DeckPicker immediately with a toast being displayed that you need to wait a minute

Changing the setting works ok and the changed value is seen. The issue is that the scheduler is partially updated with the new limit. For example, the deckDueTree() is updated(in DeckPicker the counts are changed based on the updated learn ahead limit) but the backend _queuedCards_ is not updated and appears to work based on the previous learn ahead limit. This makes the reviewer behave like there are no cards and then the code goes through CongrastPage which incorrectly displays the toast asking to wait a minute.

The fix I propose is to close the collection after changing the setting. This way other screens are forced to open the collection again which reinitializes the scheduler. If there are ways to refresh the scheduler please mention them.
Closing the collection shouldn't affect the preferences screens as they use CollectionManager.withCol {} , other screens call startLoadingCollection().

Also, backend.setConfigJson is declared to return OpChanges but returns Kotlin.Unit.

## Fixes
* Fixes #16645

## How Has This Been Tested?

Ran tests, manually verified the bug behavior.

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt [hunk 1]
```diff
@@ -34,10 +36,17 @@ class ReviewingSettingsFragment : SettingsFragment() {
         // Represents the collections pref "collapseTime": i.e.
         // if there are no card to review now, but there are learning cards remaining for today, we show those learning cards if they are due before LEARN_CUTOFF minutes
         // Note that "collapseTime" is in second while LEARN_CUTOFF is in minute.
+        @NeedsTest("#16645, changing the learn ahead limit shows expected cards in review queue")
         requirePreference<NumberRangePreferenceCompat>(R.string.learn_cutoff_preference).apply {
             launchCatchingTask { setValue(withCol { sched.learnAheadSeconds() / 60 }) }
             setOnPreferenceChangeListener { newValue ->
-                launchCatchingTask { withCol { config.set("collapseTime", (newValue as Int * 60)) } }
+                launchCatchingTask {
+                    withCol { config.set("collapseTime", (newValue as Int * 60)) }
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt:44]: This seems like a great question for @dae - if you have a second Damien - what is the best way to reinitialize the scheduler after changing config? Closing / reopening as proposed here seems pretty heavy, but at same time just fine if that's the best way

**Review by mikehardy — APPROVED** [review]
This seems functional and I'm all for functional to get it in as an incremental improvement and get 2.19 out. Always curious for thoughts from those more in the know (i.e., Damien) but I'm +1 as progress

File: AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt (hunk 1 above)
Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt:44]: My question is if we can use the backend for that, like what's done for the `rollover` setting

Comment (lukstbit) [reply AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt]: > My question is if we can use the backend for that, like what's done for the rollover setting.

We can and I changed the code to do that instead of closing the collection. Thanks.
Also, for this issue, it seems using the preferences is important as using withCol/undoable  makes no difference.

File: AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt [hunk 2]
```diff
@@ -60,4 +65,17 @@ class ReviewingSettingsFragment : SettingsFragment() {
...
+    private suspend fun getLearnAheadLimit(): Int =
+        withCol { getPreferences().scheduling.learnAheadSecs }
+
+    private suspend fun setLearnAheadLimit(limit: Int) {
+        val prefs = withCol { getPreferences() }
+        val newPrefs = prefs.copy {
+            scheduling = prefs.scheduling.copy { learnAheadSecs = limit }
+        }
+
+        undoableOp { setPreferences(newPrefs) }
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt:78]: This returns an `opChanges` 👍

File: AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt [hunk 3]
```diff
@@ -34,10 +38,11 @@ class ReviewingSettingsFragment : SettingsFragment() {
         // Represents the collections pref "collapseTime": i.e.
         // if there are no card to review now, but there are learning cards remaining for today, we show those learning cards if they are due before LEARN_CUTOFF minutes
         // Note that "collapseTime" is in second while LEARN_CUTOFF is in minute.
+        @NeedsTest("#16645, changing the learn ahead limit shows expected cards in review queue")
         requirePreference<NumberRangePreferenceCompat>(R.string.learn_cutoff_preference).apply {
-            launchCatchingTask { setValue(withCol { sched.learnAheadSeconds() / 60 }) }
+            launchCatchingTask { setValue(getLearnAheadLimit() / 60) }
             setOnPreferenceChangeListener { newValue ->
-                launchCatchingTask { withCol { config.set("collapseTime", (newValue as Int * 60)) } }
+                launchCatchingTask { setLearnAheadLimit(newValue as Int * 60) }
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt:45]: Could you convert `newValue` into a `Duration`, and accept a `Duration` in the functions added

This makes the `* 60` clearer and less likely to cause bugs in the future

**Review by david-allison — APPROVED** [review]
Looks great, thanks!

File: AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt (hunk 1 above)
Comment (dae) [reply AnkiDroid/src/main/java/com/ichi2/anki/preferences/ReviewingSettingsFragment.kt]: @lukstbit has already found the solution, but to answer your question: individual config changes don't trigger a queue rebuild, as they're used a lot, and most are not related to the scheduler. set_preferences() will ensure the queue is rebuilt, among other things.
