### PR TITLE
Protect against stale field info in CardTemplatePreviewer

### LINKED ISSUE #6644: NoteEditor - CardTemplatePreviewer - ArrayIndexOutOfBoundsException
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/a01688a2-216f-4aa0-9af2-4d395f61fdc6

2.12.0beta3

```
0	--------- beginning of main
1	07-06 17:02:45.243 I/AnkiDroid(24389): CardBrowser:: Completed doInBackgroundSearchCards Successfully
2	07-06 17:02:45.382 I/AnkiDroid(24389): AnkiActivity::onStop - NoteEditor
3	07-06 17:02:45.386 I/AnkiDroid(24389): AnkiActivity::onDestroy - NoteEditor
4	07-06 17:02:45.937 I/AnkiDroid(24389): AnkiActivity::onPause - CardBrowser
5	07-06 17:02:45.953 I/AnkiDroid(24389): AnkiActivity::onCreate - NoteEditor
6	07-06 17:02:45.990 I/AnkiDroid(24389): onCollectionLoaded() Edit note activity successfully started with card id 1485680989833
7	07-06 17:02:45.997 I/AnkiDroid(24389): AnkiActivity::onStart - NoteEditor
8	07-06 17:02:46.001 I/AnkiDroid(24389): AnkiActivity::onResume - NoteEditor
9	07-06 17:02:46.011 I/AnkiDroid(24389): Disabling Extended Text UI
10	07-06 17:02:46.011 I/AnkiDroid(24389): Disabling Extended Text UI
11	07-06 17:02:46.288 I/AnkiDroid(24389): AnkiActivity::onStop - CardBrowser
12	07-06 17:02:46.291 I/AnkiDroid(24389): flush - Saving information to DB...
13	07-06 17:02:47.621 I/AnkiDroid(24389): Disabling Extended Text UI
14	07-06 17:02:47.631 I/AnkiDroid(24389): Disabling Extended Text UI
15	07-06 17:02:49.472 I/AnkiDroid(24389): NoteEditor:: Preview button pressed
16	07-06 17:02:49.474 I/AnkiDroid(24389): Saving instance
17	07-06 17:02:49.498 I/AnkiDroid(24389): AnkiActivity::onPause - NoteEditor
18	07-06 17:02:49.534 I/AnkiDroid(24389): AnkiActivity::onCreate - CardTemplatePreviewer
```

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.CardTemplatePreviewer}: java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3448)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:7814)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
at com.ichi2.libanki.Note.setField(Note.java:1)
at com.ichi2.anki.CardTemplatePreviewer.onCollectionLoaded(CardTemplatePreviewer.java:11)
at com.ichi2.anki.AnkiActivity.startLoadingCollection(AnkiActivity.java:4)
at com.ichi2.anki.CardTemplatePreviewer.onCreate(CardTemplatePreviewer.java:19)
at android.app.Activity.performCreate(Activity.java:7955)
at android.app.Activity.performCreate(Activity.java:7944)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3423)
... 11 more
```

### PR DESCRIPTION
**Pull request by mikehardy**
## Purpose / Description

Apparently it is possible for the model and the preview bundle to
be out of sync, unsure how it came about but now we won't populate off
the end of the field array and we will carefully clean up after
CardTemplatePreviewer where before no cleanup was done

## Fixes
Fixes #6644

## Approach

I harden the array access that caused the crash so that is not possible at all, so we shouldn't crash

Why did we get there though? I'm not 100% sure and don't have the time to run it to ground completely unfortunately

What I did add was cleanup though - perhaps the fields and model were out of sync because no cleanup was done? So now I do a start-for-result to open the card template previewer and I close it carefully while cleaning up the TemporaryModel file which had been orphaned before

## How Has This Been Tested?

API29 testing - I could not replicate the crash unfortunately but I could replicate crashing when I started trying to clean up after ourselves! Required a bit of internal state hardening which is an improvement I think

I know that with array length checks during array traversal we won't crash in the same way at least and since it's just a preview hopefully we don't crash at all

## Learning (optional, can help others)

I learned that to get control of the little back arrows at top left you have to override onNavigation, that was unexpected, I was thinking onOptionItem etc

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java [hunk 1]
```diff
@@ -136,6 +160,10 @@ public void onSaveInstanceState(Bundle outState) {
     @Override
     protected void onCollectionLoaded(Collection col) {
         super.onCollectionLoaded(col);
+        if (isFinishing() || (mCurrentCard == null) && (mCardList == null)) {
+            Timber.d("onCollectionLoaded - incorrect state to load, closing");
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java:164]: This doesn't `finish()` on certain cases.

Brackets would make the logic more explicit

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java [hunk 2]
```diff
@@ -936,6 +937,7 @@ public boolean onOptionsItemSelected(MenuItem item) {
                 Bundle noteEditorBundle = new Bundle();
                 onSaveInstanceState(noteEditorBundle);
                 previewer.putExtra("noteEditorBundle", noteEditorBundle);
+                startActivityForResultWithoutAnimation(previewer, REQUEST_PREVIEW);
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java:940]: This constant isn't used other than here. This seems to launch the activity twice.

**Comment by david-allison-1** [comment]
If I remember correctly: overriding the back arrows can be performed via `enableToolbar()`

**Comment by mikehardy** [comment]
Ok, let me convert this to draft and think a bit more deeply, the double-launch is a thing easily fixed I think but for the life of me I was not able to puzzle out why the fields would be out of sync between dehydration in NoteEditor and rehydration in CardTemplatePreviewer

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java (hunk 2 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java:940]: the double-launch is a big deal although (usefully?) it pointed out several areas in CardTemplatePreviewer that needed hardening which I actually liked. I couldn't figure out the double-launch on quick inspection but I'll dig in more. The constant is only used once because I don't actually care in onActivityResult, as deleting temporary model is always safe so it doesn't really need a special case. Otherwise it would be used there

**Comment by david-allison-1** [comment]
Reproduction steps added to main ticket

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java (hunk 2 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java:940]: OMG the double launch was literally right there. Sleep deprivation is a real thing.
Cleaned up the double-launch, was able to reproduce it and prove this fix worked, re-pushed

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java [hunk 3]
```diff
@@ -89,11 +91,33 @@ protected void onResume() {
...
-            finishWithoutAnimation();
+            closeCardTemplatePreviewer();
         }
     }
 
 
+    private void closeCardTemplatePreviewer() {
+        Timber.d("CardTemplatePreviewer:: closeCardTemplatePreviewer()");
+        setResult(RESULT_OK);
+        TemporaryModel.clearTempModelFiles();
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java:102]: Needs confirmation this still works with the CardTemplatePreviewer - I'd have expected this to be required for state restoration if it's too big for a bundle.

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java:102]: The NoteEditor does not do anything about it's own state being stored in a bundle, the addition of the TemporaryModel was 100% for communication with CardTemplatePreviewer, so when it returns it is always valid to clear TemporaryModel. If NoteEditor sees some preening in the future it may take advantage of TemporaryModel internally but right now it does not, and since on Preview there is no mutation possible, clearing on both sides (CardTemplatePreviewer.close / NoteEditor.onActivityResult) should be safe

This close pathway is not exercised on Activity restarts - where TemporaryModel is needed for restoration - so, also safe?

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java:102]: Confirmed working with discard activities / across activity restarts. I think this is good to go
