### PR TITLE
Fix notetype name being reverted when going to CardTemplateEditor

### LINKED ISSUE #16630: [BUG]: Renaming Note Type Doesn't Take Effect
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

`manage note types` —> select a note type and `rename` —> `edit cards` and make some changes in template —> save and close the app —> open the app and look at the note type

### Expected behaviour

the note type has the new name

### Actual behaviour

previous name is retained

### Debug info

```text
2.19alpha4
```

### (Optional) Anything else you want to share?

even just after renaming the note type, previous name is shown in the template editor or whatever you call that

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by lukstbit**
## Purpose / Description

Due to how CardTemplateEditor accesses the collection it seems it doesn't "see" the renames done in ManageNotetypes so when it saves any changes to the template it also saves the last name it "saw". I just called load() on the collection to initialize again the components, especially _Notetypes_. This should be ok, I don't think there are other side effects on calling load().

There's a warning for worker method being called on the main thread but I think it's safe as that method just initializes again several objects, it doesn't seem to do anything heavy.

We should probably move CardTemplateEditor to use CollectionManager.

## Fixes
* Fixes #16630

## How Has This Been Tested?

Ran the tests, manually tried(and failed) to replicate the issue again.

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
Our old friend CardTemplateEditor and the problem of doing all the bookkeeping correctly while handling ephemeral data. Good stuff.

This seems like a reasonable solution to me, thanks @lukstbit

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt [hunk 1]
```diff
@@ -248,6 +248,8 @@ open class CardTemplateEditor : AnkiActivity(), DeckSelectionListener {
      */
     override fun onCollectionLoaded(col: Collection) {
         super.onCollectionLoaded(col)
+        // make sure the collection components(like Notetypes) are refreshed with the latest data, see #16630
+        col.load()
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt:252]: Is `Notetypes.clearCache()` a better call here?

**Review by david-allison — APPROVED** [review]
This implies we're not doing things correctly WRT the Rust backend.

This works as a bandaid, but we should add a task to work through the underlying issue

My comment below is untested, and I strongly suspect this fix is correct

A unit test or `@NeedsTest` here would be useful, but not necessary

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt (hunk 1 above)
Comment (lukstbit) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt]: I think it is and I switched to using it, also tested it successfully.

> This works as a bandaid, but we should add a task to work through the underlying issue

We should switch to using CollectionManager and drop getColUnsafe. I don't know if this is worth it as this screen is going to be a backend page if I'm not mistaken.

I added a @ NeedsTest annotation, tried to create a test but I'm having issues with actually running the tests after updating the IDE.
