### PR TITLE
checking for bitmap size to avoid `illegalArgumentException`

### LINKED ISSUE #13972: 2.16.0beta2: java.lang.IllegalArgumentException: width and height must be > 0
```

java.lang.IllegalArgumentException: width and height must be > 0
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1118)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:957)
	at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:812)
	at com.ichi2.anki.Whiteboard.onSizeChanged(Whiteboard.kt:16)
	at android.view.View.sizeChange(View.java:25185)
	at android.view.View.setFrame(View.java:25118)
	at android.view.View.layout(View.java:24966)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24969)
	at android.view.ViewGroup.layout(ViewGroup.java:6784)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:24969)
	at android.view.ViewGroup.layout(ViewGroup.java:6784)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:144)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:29)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:49)
	at android.view.View.layout(View.java:24969)
	at android.view.ViewGroup.layout(ViewGroup.java:6784)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:57)
	at android.view.View.layout(View.java:24969)
	at android.view.ViewGroup.layout(ViewGroup.java:6784)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24969)
	at android.view.ViewGroup.layout(ViewGroup.java:6784)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24969)
	at android.view.ViewGroup.layout(ViewGroup.java:6784)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24969)
	at android.view.ViewGroup.layout(ViewGroup.java:6784)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:24969)
	at android.view.ViewGroup.layout(ViewGroup.java:6784)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1432)
	at android.view.View.layout(View.java:24969)
	at android.view.ViewGroup.layout(ViewGroup.java:6784)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4917)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4240)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3116)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10885)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
	at android.view.Choreographer.doFrame(Choreographer.java:852)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```
https://ankidroid.org/acra/app/1/bug/53958/report/d3aa3581-9284-4c01-9255-679075d919d0
Android 13 samsung, legacy backend, v2 scheduler

### PR DESCRIPTION
**Pull request by criticalAY**
## Purpose / Description
Bitmap size check to avoid the condition where bitmap size <0

## Fixes
Fixes #13972

## Approach
_How does this change address the problem?_

## How Has This Been Tested?
 condition is suffice to avoid the exception but I would like to have an opinion if we should have a default bitmap size i.e `500x500` in case this case arises. @BrayanDSO 

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by criticalAY** [comment]
Can we consider passing some default size as I mentioned in the PR?

**Comment by criticalAY** [comment]
this is the deprecated method
```fun getDisplayDimensions```
we can handle the deprecation along with the case if the dimension is zero?

**Comment by oakkitten** [comment]
Wait, I double-checked the stack trace and the method you are altering, `com.ichi2.anki.Whiteboard#createBitmap()`, does not appear in the trace

**Comment by criticalAY** [comment]
@oakkitten correct I found the correct place to handle the exception but I want to know if we should assign some default values in case it is less than zero i.e here is the changed method
```
    override fun onSizeChanged(w: Int, h: Int, oldw: Int, oldh: Int) {
        super.onSizeChanged(w, h, oldw, oldh)
        if (w > 0 && h > 0) {
            val scaledBitmap: Bitmap? = try {
                Bitmap.createScaledBitmap(mBitmap, w, h, true)
            } catch (e: IllegalArgumentException) {
                Timber.e("Bitmap size less than zero")
                null
            }
            if (scaledBitmap != null) {
                mBitmap.recycle() 
                mBitmap = scaledBitmap
                mCanvas = Canvas(mBitmap)
            } else {
                val validWidth = 500
                val validHeight = 500
                mBitmap.recycle()
                mBitmap = Bitmap.createBitmap(validWidth, validHeight, Bitmap.Config.ARGB_8888)
                mCanvas = Canvas(mBitmap)
            }
        }
    }
    ```

**Comment by oakkitten** [comment]
It's hard to say in which cases the view can have one or more sizes as 0. Might be related to very small AnkiDroid window sizes or some unfortunate chains of events that lead to a temporary weird size. Without being able to reproduce the issue, we can't be sure that the application will behave correctly when we get a 0 here. Said that, I think a view should be able to handle having a zero height or width in any case.

I do not see any advantage to resizing the bitmap to anything when we have a 0 height or width. With a zero area we can't draw anything in a meaningful way. At this point we should already have a bitmap so creating one isn't required. Besides, scaling breaks the image since, well, it scales what is supposed not to be scaled. And undo will break this scaling again. And everything is lost on screen rotation anyway. Or theme change. So I wouldn't bother to do anything here beyond a simple 

```kt
if (w == 0 && h == 0) return
```

**Comment by oakkitten** [comment]
Uhh sorry I meant to say `||` there 😅

**Comment by criticalAY** [comment]
ok but there are chances that there would be an exception somewhere else after this but chances are minimal so I think it is ok

**Comment by BrayanDSO** [comment]
Could you please add a `Timber.w` there?

**Comment by criticalAY** [comment]
what do we want to pass there ?

File: AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt [hunk 1]
```diff
@@ -223,6 +223,8 @@ class Whiteboard(activity: AnkiActivity, handleMultiTouch: Boolean, inverted: Bo
      */
     override fun onSizeChanged(w: Int, h: Int, oldw: Int, oldh: Int) {
         super.onSizeChanged(w, h, oldw, oldh)
+        Timber.w("Whiteboard::onSizeChanged width:$w height:$h")
+        if (w == 0 || h == 0) return
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt:227]:
```suggestion
        // createScaledBitmap requires a width and height > 0; #13972
        if (w <= 0 || h <= 0) {
            Timber.w("Width or height <= 0: width: $w; height: $h; Bitmap can't be created with the new size")
            return
        }
```

**Review by BrayanDSO — CHANGES_REQUESTED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt [hunk 2]
```diff
@@ -223,6 +223,12 @@ class Whiteboard(activity: AnkiActivity, handleMultiTouch: Boolean, inverted: Bo
      */
     override fun onSizeChanged(w: Int, h: Int, oldw: Int, oldh: Int) {
         super.onSizeChanged(w, h, oldw, oldh)
+        Timber.w("Whiteboard::onSizeChanged width:$w height:$h")
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt:226]:
```suggestion
        Timber.i("Whiteboard::onSizeChanged width:$w height:$h")
```
Here it's just an info, so use `Timber.i`. Below it's a potential error situation where we could recover, so it's a warn `Timber.w`

**Review by BrayanDSO — APPROVED** [review]

**Review by mikehardy — APPROVED** [review]
works for me - thank you!
