### PR TITLE
refactor(card-browser): Convert to fragment (and fix a few issues)

### LINKED ISSUE #17901: Migrate the Browser into a Fragment
Android prefers to have more fragments and less activites + it helps moving the app to a bottom bar navigation

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
Requested by @BrayanDSO

## Fixes
* Fixes #17901

## Approach
See commits:

1. Create fragment and move UI elements there
2. define accessors for UI elements via `cardBrowserFragment`
3. Go through each usage of accessors and move inside fragment
4. finally, remove the `cardBrowserFragment`, it became test only

----

* fix: maintain selection after selecting flag
* fix: don't show focused row if non-fragmented

## How Has This Been Tested?
* Unit tests
* Google Pixel 9 Pro
* API 34 tablet
  * One bug, also present in `main` : https://github.com/ankidroid/Anki-Android/issues/18462

## Learning (optional, can help others)

Easier than expected. There's more rounds if we want to tackle the menu 

I feel I did something wrong....

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserFragment.kt [hunk 1]
```diff
@@ -0,0 +1,181 @@
...
+
+    @VisibleForTesting
+    lateinit var cardsListView: RecyclerView
+
+    @VisibleForTesting
+    lateinit var browserColumnHeadings: ViewGroup
+
+    private lateinit var progressIndicator: LinearProgressIndicator
+
+    override fun onCreateView(
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserFragment.kt]: for just views configuration (you can also see it as not changing what the method returns), [onViewCreated](https://developer.android.com/reference/android/app/Fragment#onViewCreated(android.view.View,%20android.os.Bundle)) is preferred.

File: AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserFragment.kt [hunk 2]
```diff
@@ -0,0 +1,181 @@
...
+    val viewModel: CardBrowserViewModel by activityViewModels()
+
+    @VisibleForTesting(otherwise = VisibleForTesting.PRIVATE)
+    lateinit var cardsAdapter: BrowserMultiColumnAdapter
+
+    @VisibleForTesting
+    lateinit var cardsListView: RecyclerView
+
+    @VisibleForTesting
+    lateinit var browserColumnHeadings: ViewGroup
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserFragment.kt:67]: just to note, ViewBinding would be hepful here

File: AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserFragment.kt [hunk 3]
```diff
@@ -0,0 +1,181 @@
...
+            )
+        cardsListView.adapter = cardsAdapter
+        cardsAdapter.stateRestorationPolicy = RecyclerView.Adapter.StateRestorationPolicy.PREVENT_WHEN_EMPTY
+        val layoutManager = LinearLayoutManager(requireContext())
+        cardsListView.layoutManager = layoutManager
+        cardsListView.addItemDecoration(DividerItemDecoration(requireContext(), layoutManager.orientation))
+
+        this.browserColumnHeadings = view.findViewById<ViewGroup>(R.id.browser_column_headings)
+
+        progressIndicator = view.findViewById<LinearProgressIndicator>(R.id.browser_progress)
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserFragment.kt]: the IDE lint is flagging this and some other stuff

image

File: AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserFragment.kt [hunk 4]
```diff
@@ -0,0 +1,286 @@
...
+            return
+        }
+
+        if ((
+                changes.browserSidebar ||
+                    changes.browserTable ||
+                    changes.noteText ||
+                    changes.card
+            )
+        ) {
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserFragment.kt]: The parenthesis are doubled.

```suggestion
if (changes.browserSidebar || changes.browserTable || changes.noteText || changes.card) {
```

File: AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserFragment.kt [hunk 5]
```diff
@@ -0,0 +1,286 @@
...
+            cardsAdapter.notifyDataSetChanged()
+        }
+    }
+
+    private fun showColumnSelectionDialog(selectedColumn: ColumnHeading) {
+        Timber.d("Fetching available columns for: ${selectedColumn.label}")
+
+        // Prevent multiple dialogs from opening
+        if (requireActivity().supportFragmentManager.findFragmentByTag(ColumnSelectionDialogFragment.TAG) != null) {
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserFragment.kt]: Does `parentFragmentManager` works instead of `requireActivity().supportFragmentManager`?

File: AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserFragment.kt [hunk 6]
```diff
@@ -136,13 +148,43 @@ class CardBrowserFragment :
...
 
+        fun onColumnNamesChanged(columnCollection: List<ColumnHeading>) {
+            Timber.d("column names changed")
+            browserColumnHeadings.removeAllViews()
+
+            val layoutInflater = LayoutInflater.from(browserColumnHeadings.context)
+            for (column in columnCollection) {
+                Timber.d("setting up column %s", column)
+                layoutInflater.inflate(R.layout.browser_column_heading, browserColumnHeadings, false).apply {
+                    val columnView = this as TextView
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserFragment.kt]: I know that the PR is just moving this, but now that I noticed, couldn't you just write it as
```kotlin
val columnView = layoutInflater.inflate(R.layout.browser_column_heading, browserColumnHeadings, false) as TextView
```
then remove all the indent?

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt [hunk 7]
```diff
@@ -1780,16 +1785,19 @@ open class CardBrowser :
...
+    private fun createViewModel(
+        launchOptions: CardBrowserLaunchOptions?,
+        fragmented: Boolean,
+    ) = ViewModelProvider(
+        viewModelStore,
+        CardBrowserViewModel.factory(
+            lastDeckIdRepository = AnkiDroidApp.instance.sharedPrefsLastDeckIdRepository,
+            cacheDir = cacheDir,
+            options = launchOptions,
+            isFragmented = fragmented,
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt:1796]: add some docs explaining what `fragmented` is supposed to mean

File: AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt [hunk 8]
```diff
@@ -105,6 +105,7 @@ class CardBrowserViewModel(
     private val cacheDir: File,
     options: CardBrowserLaunchOptions?,
     preferences: SharedPreferencesProvider,
+    val isFragmented: Boolean,
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserViewModel.kt:117]: add some docs explaining what this `isFragmented` supposed to be.

**Comment by david-allison** [comment]
Cheers, I didn't rebase the changes in, let me know if you'd prefer this for history cleaning purposes

File: AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserFragment.kt [hunk 9]
```diff
@@ -0,0 +1,285 @@
...
+
+        cardsListView =
+            view.findViewById<RecyclerView?>(R.id.card_browser_list).apply {
+                attachFastScroller(R.id.browser_scroller)
+            }
+        DividerItemDecoration(requireContext(), DividerItemDecoration.VERTICAL).apply {
+            setDrawable(ContextCompat.getDrawable(requireContext(), R.drawable.browser_divider)!!)
+            cardsListView.addItemDecoration(this)
+        }
+        cardsAdapter =
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserFragment.kt:85]: interesting - while doing the review on #18467 I saw a lot of chatter on memory leaks related to the combination of Fragment + RecyclerView + Adapter, and it looks like this may suffer from the leak described

https://stackoverflow.com/a/46957469/9910298

the adapter will continue to live on in the fragment after the RecyclerView goes away, which will leak perhaps?

during the fragment lifecycle (ie. in onDestroyView) the adapter may be set to null and cleared out of the recyclerview to allow it to GC

there's an interaction with the var declaration as lateinit vs nullable though - and maybe I'm mis-reading it and this doesn't apply ? fine with being wrong and this being comment being closeable

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/browser/CardBrowserFragment.kt:85]: Not enough motivation to deep dive today. May not have been a problem due to the lifecycles of the activity and fragment being equal.

Fixed:

```kotlin
    override fun onDestroyView() {
        super.onDestroyView()
        if (::cardsListView.isInitialized) {
            cardsListView.adapter = null
        }
    }
```

**Review by BrayanDSO — APPROVED** [review]
Mike's comment was addressed, and we can keep looking if it causes other leaks after the merge
