### PR TITLE
fix: API crashes with UnsatisfiedLinkError

### LINKED ISSUE #14621: [BUG]: Access to the API crashes AnkiDroid with UnsatisfiedLinkError
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Make a following call from a 3rd party app to the AnkiDroid API:

```
contentResolver.query(
            /* uri = */ FlashCardsContract.ReviewInfo.CONTENT_URI,
            /* projection = */ null,
            /* selection = */ null,
            /* selectionArgs = */ null,
            /* sortOrder = */ null
        )
```

### Expected behaviour

AnkiDroid should return results normally

### Actual behaviour

Crash:

```
10-30 19:00:00.832 20038 20052 E AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for byte[][] net.ankiweb.rsdroid.NativeMethods.openBackend(byte[]) (tried Java_net_ankiweb_rsdroid_NativeMethods_openBackend and Java_net_ankiweb_rsdroid_NativeMethods_openBackend___3B) - is the library loaded, e.g. System.loadLibrary?
10-30 19:00:00.832 20038 20052 E AndroidRuntime: 	at net.ankiweb.rsdroid.NativeMethods.openBackend(Native Method)
10-30 19:00:00.832 20038 20052 E AndroidRuntime: 	at net.ankiweb.rsdroid.Backend.<init>(SourceFile:11)
10-30 19:00:00.832 20038 20052 E AndroidRuntime: 	at net.ankiweb.rsdroid.BackendFactory.getBackend(SourceFile:2)
10-30 19:00:00.832 20038 20052 E AndroidRuntime: 	at net.ankiweb.rsdroid.BackendFactory.getBackend$default(SourceFile:6)
10-30 19:00:00.832 20038 20052 E AndroidRuntime: 	at com.ichi2.anki.CollectionManager.ensureBackendInner(SourceFile:7)
10-30 19:00:00.832 20038 20052 E AndroidRuntime: 	at com.ichi2.anki.CollectionManager.ensureOpenInner(SourceFile:1)
10-30 19:00:00.832 20038 20052 E AndroidRuntime: 	at com.ichi2.anki.CollectionManager.access$ensureOpenInner(SourceFile:1)
10-30 19:00:00.832 20038 20052 E AndroidRuntime: 	at com.ichi2.anki.CollectionManager$getColUnsafe$1$1.invoke(SourceFile:2)
10-30 19:00:00.832 20038 20052 E AndroidRuntime: 	at com.ichi2.anki.CollectionManager$getColUnsafe$1$1.invoke(SourceFile:1)
10-30 19:00:00.832 20038 20052 E AndroidRuntime: 	at com.ichi2.anki.CollectionManager$withQueue$2.invokeSuspend(SourceFile:15)
10-30 19:00:00.832 20038 20052 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
10-30 19:00:00.832 20038 20052 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(SourceFile:124)
10-30 19:00:00.832 20038 20052 E AndroidRuntime: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(SourceFile:13)
10-30 19:00:00.832 20038 20052 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
10-30 19:00:00.832 20038 20052 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(SourceFile:1)
10-30 19:00:00.832 20038 20052 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(SourceFile:15)
10-30 19:00:00.832 20038 20052 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(SourceFile:29)
10-30 19:00:00.832 20038 20052 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:1)
10-30 19:00:00.835  1251 20062 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
```

### Debug info

```text
AnkiDroid Version = 2.17alpha2 (19ad510c0a44c4fa140394363a0df3bd8ab177d8)

Android Version = 13

ProductFlavor = full

Manufacturer = Google

Model = Pixel 7 Pro

Hardware = cheetah

Webview User Agent = Mozilla/5.0 (Linux; Android 13; Pixel 7 Pro Build/TQ3A.230901.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/118.0.0.0 Mobile Safari/537.36

ACRA UUID = 85314e7b-0d43-4b96-a861-e60e9dd7f848

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

(I'm not 100% sure that the API call is the cause, but the timing seems to work out - I query Anki periodically in the background).

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### LINKED ISSUE #14829: [BUG]: AnkiDroid 2.17alpha6 AnkiDroid Crashes when accessed from background processes
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

There are multiple apps that can export Anki cards to AnkiDroid.
- Jidoujisho (https://github.com/lrorpilla/jidoujisho)
- Yomichan w/ Kiwi browser + AnkiConnect Android ( https://learnjapanese.moe/yomichan/ + https://github.com/KamWithK/AnkiconnectAndroid)

Doing any Anki related features shows that AnkiDroid has stopped working

### Expected behaviour

Same as the working 2.16.5, it should not crash and allow for cards to be added.		

### Actual behaviour

"AnkiDroid has stopped working" popup occurs

### Debug info

```text
AnkiDroid Version = 2.17alpha6 (393f61b229a26ec97eb13c83f0d1f09652f776c2)

Android Version = 9

ProductFlavor = full

Manufacturer = samsung

Model = SM-N950U1

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 9; SM-N950U1 Build/PPR1.180610.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/119.0.6045.163 Mobile Safari/537.36

ACRA UUID = 85c60929-c55d-4046-ae16-545886ccf69b

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description

We needed a call to `System.loadLibrary("rsdroid")`

## Fixes

* Fixes #14621
* Fixes #14829

### Exception Fixed

```
java.lang.UnsatisfiedLinkError: No implementation found for byte[][] net.ankiweb.rsdroid.NativeMethods.openBackend(byte[]) (tried Java_net_ankiweb_rsdroid_NativeMethods_openBackend and Java_net_ankiweb_rsdroid_NativeMethods_openBackend___3B) - is the library loaded, e.g. System.loadLibrary?
    at net.ankiweb.rsdroid.NativeMethods.openBackend(Native Method)
```

## Approach
* Uninstall AnkiDroid 'stable' from my 'stable' slot
* Install AnkiDroid 'alpha'
* Figure out getting the API tested
* Verify it was just not loading `rsdroid`

## How Has This Been Tested?
Apply the following and comment/uncomment the line in the ContentProvider

```patch
Subject: [PATCH] fix: API crashes with UnsatisfiedLinkError

Enables testing API
---
Index: AnkiDroid/build.gradle
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/build.gradle b/AnkiDroid/build.gradle
--- a/AnkiDroid/build.gradle	(revision 5f2cc3b10c0ea0852560e119b443f2a46ff60432)
+++ b/AnkiDroid/build.gradle	(date 1701217101164)
@@ -93,9 +93,9 @@
     }
     buildTypes {
         debug {
-            versionNameSuffix "-debug"
+//            versionNameSuffix "-debug"
+//            applicationIdSuffix ".debug"
             debuggable true
-            applicationIdSuffix ".debug"
             splits.abi.universalApk = true // Build universal APK for debug always
             // Check Crash Reports page on developer wiki for info on ACRA testing
             // buildConfigField "String", "ACRA_URL", '"https://918f7f55-f238-436c-b34f-c8b5f1331fe5-bluemix.cloudant.com/acra-ankidroid/_design/acra-storage/_update/report"'
Index: api/build.gradle.kts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/api/build.gradle.kts b/api/build.gradle.kts
--- a/api/build.gradle.kts	(revision 5f2cc3b10c0ea0852560e119b443f2a46ff60432)
+++ b/api/build.gradle.kts	(date 1701217101165)
@@ -32,9 +32,9 @@
             buildConfigField(
                 "String",
                 "READ_WRITE_PERMISSION",
-                "\"com.ichi2.anki.debug.permission.READ_WRITE_DATABASE\""
+                "\"com.ichi2.anki.permission.READ_WRITE_DATABASE\""
             )
-            buildConfigField("String", "AUTHORITY", "\"com.ichi2.anki.debug.flashcards\"")
+            buildConfigField("String", "AUTHORITY", "\"com.ichi2.anki.flashcards\"")
         }
         release {
             isMinifyEnabled = false
```

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by mikehardy** [comment]
@hanpingchinese this  may interest you as well ? I think I am remembering correctly when I remember you mentioning something about this as well ? 2.17alpha8 has an API fix that stops crashing on API access

**Comment by david-allison** [comment]
Strong support for alpha8: we have a user who can't use either stable or alpha

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt [hunk 1]
```diff
@@ -415,6 +411,23 @@ open class AnkiDroidApp : Application() {
...
+            // Robolectric uses RustBackendLoader.ensureSetup()
+            if (Build.FINGERPRINT == "robolectric") return
+
+            try {
+                // Prevent sqlite throwing error 6410 due to the lack of /tmp on Android
+                Os.setenv("TMPDIR", context.cacheDir.path, false)
+                // Load backend library
+                System.loadLibrary("rsdroid")
+            } catch (e: Error) {
+                // this routine /may/ be called more than once: we'll know if/when it occurs
```
Comment (dae) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt:426]: Just to clarify: setenv and loadLibrary() are idempotent IIRC, so this would only throw if some other error occurs like the library not being able to be loaded. Not sure if logging/swallowing the error is the best option in that case, since the app can't be effectively used afterwards anyway.
