### PR TITLE
Fix: use field check from backend and display error accordingly

### LINKED ISSUE #16419: [BUG]: Cloze field - `Text` not consistent in AnkiDroid
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

When we reorder the cloze field then in Anki the 'Text' field is the field that accepts cloze text other than that we can use any other
but in AnkiDroid we can use any field that is first in order save the note, this should not happen.
image
image

### Expected behaviour

`Text` is the main cloze field

### Actual behaviour

First field is treated as cloze field

### Debug info

```text
latest alpha
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by criticalAY**
## Purpose / Description
AnkiDroid used custom made check on field but since Anki already has a method to do so, this PR updates that issue of manual check and check the field content via the Anki method.

## Fixes
* Fixes #16419

## Approach
Use method from backend

## How Has This Been Tested?
When first field is empty:
image

When content has no cloze:
image

Wrong cloze field:
image

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+ * @property problem A nullable string that provides details about the problem if the check failed.
+ */
+data class NoteFieldsCheckResult(val result: Boolean, val problem: String?)
+
+/** This method checks the state of the note fields and logs the state. Depending on the state, it may
+ *  return false if the note has issues that prevent it from being valid.
+ *
+ *  Passes any problem if any to [NoteFieldsCheckResult].
+ **/
+fun checkNoteFieldsResponse(col: Collection, note: Note?): NoteFieldsCheckResult {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt:40]: make this `suspend` and use `withCol` internally

Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt:40]: why is note nullable?

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt [hunk 2]
```diff
@@ -0,0 +1,80 @@
...
+    Timber.i("Checking for NoteField State")
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt:41]:
```suggestion
    Timber.d("validating note fields")
```

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt [hunk 3]
```diff
@@ -316,31 +318,29 @@ class NoteEditor : AnkiActivity(), DeckSelectionListener, SubtitleListener, Tags
...
-                return R.string.note_editor_no_first_field
-            }
-            return if (allFieldsHaveContent()) {
-                R.string.note_editor_no_cards_created_all_fields
-            } else {
-                R.string.note_editor_no_cards_created
-            }
-
-            // Otherwise, display "no cards created".
+    val getErrorMessage: String
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:339]: This needs a better name, at the very least, remove the `get` prefix

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt [hunk 4]
```diff
@@ -1017,16 +1019,14 @@ class NoteEditor : AnkiActivity(), DeckSelectionListener, SubtitleListener, Tags
...
-            // adding current note to collection
-            withProgress(resources.getString(R.string.saving_facts)) {
-                undoableOp {
-                    notetypes.current().put("tags", tags)
-                    addNote(editorNote!!, deckId)
-                }
+
+            val noteFieldsCheckResult = withCol { checkNoteFieldsResponse(col = this, editorNote) }
+            if (!noteFieldsCheckResult.result) {
+                addNoteErrorMessage = noteFieldsCheckResult.problem
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:1025]: This is a no-op if `UNRECOGNIZED` is returned, meaning an incorrect error message is displayed

**Review by david-allison — CHANGES_REQUESTED** [review]
```patch
Subject: [PATCH] test(ci): fix windows runner hanging

Tracked down to all methods on TagsDialog

Adding `: RobolectricTest()` did not resolves this

So add `@Flaky`

Fixes 16404
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt b/AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt	(revision 91beab6983f9cf148f13f4c8d7678d4c96d0a62d)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt	(date 1716226885766)
@@ -19,62 +19,55 @@
 
 import anki.notes.NoteFieldsCheckResponse
 import com.ichi2.anki.CollectionManager.TR
+import com.ichi2.anki.NoteFieldsCheckResult.*
 import com.ichi2.anki.utils.ext.isImageOcclusion
 import com.ichi2.libanki.Collection
 import com.ichi2.libanki.Note
 import timber.log.Timber
 
 /**
- * Representing the result of checking note fields.
+ * The result of [checking note fields][Note.fieldsCheck], either a [Success], or [Failure] with
+ * user-readable message
  *
- * @property result Boolean indicating if there was some issue or not.
- * @property problem A nullable string that provides details about the problem if the check failed.
+ * @see NoteFieldsCheckResponse.State
+ * @see checkNoteFieldsResponse
  */
-data class NoteFieldsCheckResult(val result: Boolean, val problem: String?)
+sealed interface NoteFieldsCheckResult {
+    data object Success : NoteFieldsCheckResult
 
-/** This method checks the state of the note fields and logs the state. Depending on the state, it may
- *  return false if the note has issues that prevent it from being valid.
+    /** @property localizedMessage user-readable error message */
+    data class Failure(val localizedMessage: String?) : NoteFieldsCheckResult
+}
+
+/** 
+ * Validates fields of a note; produces a human-readable error on failure 
  *
- *  Passes any problem if any to [NoteFieldsCheckResult].
+ * @see NoteFieldsCheckResult
+ * @see Note.fieldsCheck
  **/
 fun checkNoteFieldsResponse(col: Collection, note: Note?): NoteFieldsCheckResult {
     Timber.i("Checking for NoteField State")
-    val result = note?.fieldsCheck(col)
-    result?.let { state ->
-        when (state) {
-            NoteFieldsCheckResponse.State.NORMAL -> {
-                // Intentionally left blank
-            }
-
-            NoteFieldsCheckResponse.State.EMPTY -> {
-                val problem = if (note.notetype.isImageOcclusion) {
-                    TR.notetypesNoOcclusionCreated2()
-                } else {
-                    TR.addingTheFirstFieldIsEmpty()
-                }
-                return NoteFieldsCheckResult(false, problem)
-            }
-
-            NoteFieldsCheckResponse.State.DUPLICATE -> {
-                // Intentionally left blank
-            }
+    val fieldsCheckState = note?.fieldsCheck(col) ?: return Success
+    return when (fieldsCheckState) {
+        NoteFieldsCheckResponse.State.NORMAL, NoteFieldsCheckResponse.State.DUPLICATE 
+            -> Success
+    
+        NoteFieldsCheckResponse.State.EMPTY -> if (note.notetype.isImageOcclusion) {
+            Failure(TR.notetypesNoOcclusionCreated2())
+        } else {
+            Failure(TR.addingTheFirstFieldIsEmpty())
+        }
 
-            NoteFieldsCheckResponse.State.MISSING_CLOZE -> {
-                return NoteFieldsCheckResult(false, TR.addingYouHaveAClozeDeletionNote())
-            }
+        NoteFieldsCheckResponse.State.MISSING_CLOZE ->
+            Failure(TR.addingYouHaveAClozeDeletionNote())
 
-            NoteFieldsCheckResponse.State.NOTETYPE_NOT_CLOZE -> {
-                return NoteFieldsCheckResult(false, TR.addingClozeOutsideClozeNotetype())
-            }
+        NoteFieldsCheckResponse.State.NOTETYPE_NOT_CLOZE -> 
+            Failure(TR.addingClozeOutsideClozeNotetype())
 
-            NoteFieldsCheckResponse.State.FIELD_NOT_CLOZE -> {
-                return NoteFieldsCheckResult(false, TR.addingClozeOutsideClozeField())
-            }
+        NoteFieldsCheckResponse.State.FIELD_NOT_CLOZE -> 
+            Failure(TR.addingClozeOutsideClozeField())
 
-            NoteFieldsCheckResponse.State.UNRECOGNIZED -> {
-                return NoteFieldsCheckResult(false, null)
-            }
-        }
+        NoteFieldsCheckResponse.State.UNRECOGNIZED -> 
+            Failure(localizedMessage = null)
     }
-    return NoteFieldsCheckResult(true, null)
 }
Index: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt	(revision 91beab6983f9cf148f13f4c8d7678d4c96d0a62d)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt	(date 1716226590723)
@@ -1021,8 +1021,8 @@
             reloadRequired = true
 
             val noteFieldsCheckResult = withCol { checkNoteFieldsResponse(col = this, editorNote) }
-            if (!noteFieldsCheckResult.result) {
-                addNoteErrorMessage = noteFieldsCheckResult.problem
+            if (noteFieldsCheckResult is NoteFieldsCheckResult.Failure) {
+                addNoteErrorMessage = noteFieldsCheckResult.localizedMessage
                 displayErrorSavingNote()
                 return
             }
```

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt (hunk 1 above)
Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt:40]: because it is nullable in NoteEditor

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt (hunk 4 above)
Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:1025]: It will be null in that case and depending on the field content error message will be displayed, ig it is still better than earlier

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt (hunk 1 above)
Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt]: I changed it now not not null

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt (hunk 4 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt]: It is, can we do better?

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt [hunk 5]
```diff
@@ -0,0 +1,74 @@
...
+
+/**
+ * Validates fields of a note; produces a human-readable error on failure
+ *
+ * @see NoteFieldsCheckResult
+ * @see Note.fieldsCheck
+ **/
+suspend fun checkNoteFieldsResponse(note: Note): NoteFieldsCheckResult {
+    Timber.d("validating note fields")
+    val fieldsCheckState = withCol { note.fieldsCheck(this) }
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt:50]: optional: look into context to remove the `(this)` parameter:

https://github.com/ankidroid/Anki-Android/blob/85abd410bb517e527dbf4d4e8dd49d109ab007ab/AnkiDroid/src/main/java/com/ichi2/libanki/Note.kt#L305-L315

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt [hunk 6]
```diff
@@ -1017,16 +1019,16 @@ class NoteEditor : AnkiActivity(), DeckSelectionListener, SubtitleListener, Tags
...
 
             reloadRequired = true
-            // adding current note to collection
-            withProgress(resources.getString(R.string.saving_facts)) {
-                undoableOp {
-                    notetypes.current().put("tags", tags)
-                    addNote(editorNote!!, deckId)
+
+            lifecycleScope.launch {
+                val noteFieldsCheckResult = checkNoteFieldsResponse(editorNote!!)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:1024]: nit: consider a shorter name

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt [hunk 7]
```diff
@@ -316,31 +318,29 @@ class NoteEditor : AnkiActivity(), DeckSelectionListener, SubtitleListener, Tags
...
     }
 
+    private var addNoteErrorMessage: String? = null
+
     private fun displayErrorSavingNote() {
-        val errorMessageId = addNoteErrorResource
-        showSnackbar(resources.getString(errorMessageId))
+        val errorMessage = snackbarErrorText
+        if (errorMessage == TR.addingYouHaveAClozeDeletionNote()) {
+            showSnackbar(errorMessage, Snackbar.LENGTH_INDEFINITE) {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:326]: add a comment explaining this

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt [hunk 8]
```diff
@@ -316,31 +318,29 @@ class NoteEditor : AnkiActivity(), DeckSelectionListener, SubtitleListener, Tags
         SAME_NUMBER, INCREMENT_NUMBER
     }
 
+    private var addNoteErrorMessage: String? = null
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:321]: This isn't reset to null on success

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt [hunk 9]
```diff
@@ -316,31 +318,29 @@ class NoteEditor : AnkiActivity(), DeckSelectionListener, SubtitleListener, Tags
...
-                return R.string.note_editor_no_first_field
-            }
-            return if (allFieldsHaveContent()) {
-                R.string.note_editor_no_cards_created_all_fields
-            } else {
-                R.string.note_editor_no_cards_created
-            }
-
-            // Otherwise, display "no cards created".
+    val snackbarErrorText: String
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:339]: This should probably be a method, up to reviewer 2

Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:339]: I made it a method but earlier we had a val so I sticked to that, open to change though

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt (hunk 4 above)
Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt]: So, we should come come with a case where we can handle `UNRECOGNIZED` state differently

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt [hunk 10]
```diff
@@ -316,31 +318,32 @@ class NoteEditor : AnkiActivity(), DeckSelectionListener, SubtitleListener, Tags
...
+        get() = when {
+            addNoteErrorMessage == UNRECOGNIZED_STATE -> resources.getString(R.string.something_wrong)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:343]: remove this and move it closer to the setter

**Review by david-allison — APPROVED** [review]
One minor request, no more comments, LGTM

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt [hunk 11]
```diff
@@ -0,0 +1,78 @@
...
+import com.ichi2.anki.CollectionManager.TR
+import com.ichi2.anki.CollectionManager.withCol
+import com.ichi2.anki.NoteFieldsCheckResult.*
+import com.ichi2.anki.utils.ext.isImageOcclusion
+import com.ichi2.libanki.Note
+import com.ichi2.libanki.fieldsCheck
+import timber.log.Timber
+
+/** Unrecognized state string, to handle cases [NoteFieldsCheckResponse.State] is not recognized **/
+const val UNRECOGNIZED_STATE = "unrecognized_state"
```
[the remark this answers is not in the document]
Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt:30]: If we use null then `   private var addNoteErrorMessage: String? = null` will create problem

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt [hunk 12]
```diff
@@ -69,6 +72,6 @@ suspend fun checkNoteFieldsResponse(note: Note): NoteFieldsCheckResult {
             Failure(TR.addingClozeOutsideClozeField())
 
         NoteFieldsCheckResponse.State.UNRECOGNIZED ->
-            Failure(localizedMessage = null)
+            Failure(UNRECOGNIZED_STATE)
```
[the remark this answers is not in the document]
Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt:76]: it was removed ig, was unused

**Review by david-allison — CHANGES_REQUESTED** [review]
Seems like a review comment of mine wasn't sent, apologies for the confusion

```patch
Subject: [PATCH] test(ci): fix windows runner hanging

Tracked down to all methods on TagsDialog

Adding `: RobolectricTest()` did not resolves this

So add `@Flaky`

Fixes 16404
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt b/AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt	(revision 934e633029e728ba5756ebcc09ba67a93e4b9d23)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/NoteFieldsCheckResult.kt	(date 1716237006525)
@@ -17,6 +17,7 @@
 
 package com.ichi2.anki
 
+import android.content.Context
 import anki.notes.NoteFieldsCheckResponse
 import com.ichi2.anki.CollectionManager.TR
 import com.ichi2.anki.CollectionManager.withCol
@@ -26,9 +27,6 @@
 import com.ichi2.libanki.fieldsCheck
 import timber.log.Timber
 
-/** Unrecognized state string, to handle cases [NoteFieldsCheckResponse.State] is not recognized **/
-const val UNRECOGNIZED_STATE = "unrecognized_state"
-
 /**
  * The result of [checking note fields][Note.fieldsCheck], either a [Success], or [Failure] with
  * user-readable message
@@ -40,7 +38,9 @@
     data object Success : NoteFieldsCheckResult
 
     /** @property localizedMessage user-readable error message */
-    data class Failure(val localizedMessage: String?) : NoteFieldsCheckResult
+    data class Failure(private val localizedMessage: String?) : NoteFieldsCheckResult {
+        fun getLocalizedMessage(context: Context) = localizedMessage ?: context.getString(R.string.something_wrong)
+    }
 }
 
 /**
@@ -73,6 +73,6 @@
             Failure(TR.addingClozeOutsideClozeField())
 
         NoteFieldsCheckResponse.State.UNRECOGNIZED ->
-            Failure(UNRECOGNIZED_STATE)
+            Failure(localizedMessage = null)
     }
 }
Index: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt	(revision 934e633029e728ba5756ebcc09ba67a93e4b9d23)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt	(date 1716237006522)
@@ -340,7 +340,6 @@
     @VisibleForTesting
     val snackbarErrorText: String
         get() = when {
-            addNoteErrorMessage == UNRECOGNIZED_STATE -> resources.getString(R.string.something_wrong)
             addNoteErrorMessage != null -> addNoteErrorMessage!!
             allFieldsHaveContent() -> resources.getString(R.string.note_editor_no_cards_created_all_fields)
             else -> resources.getString(R.string.note_editor_no_cards_created)
@@ -1027,7 +1026,7 @@
             lifecycleScope.launch {
                 val noteFieldsCheck = checkNoteFieldsResponse(editorNote!!)
                 if (noteFieldsCheck is NoteFieldsCheckResult.Failure) {
-                    addNoteErrorMessage = noteFieldsCheck.localizedMessage
+                    addNoteErrorMessage = noteFieldsCheck.getLocalizedMessage(this@NoteEditor)
                     displayErrorSavingNote()
                     return@launch
                 }

```

**Comment by criticalAY** [comment]
Thankyou!

**Review by david-allison — APPROVED** [review]
Looks great, cheers!

**Comment by BrayanDSO** [comment]
> image

Please don't use a snackbar to ask for confirmation. That's what dialogs are for

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt [hunk 13]
```diff
@@ -316,31 +318,37 @@ class NoteEditor : AnkiActivity(), DeckSelectionListener, SubtitleListener, Tags
...
-                return R.string.note_editor_no_first_field
-            }
-            return if (allFieldsHaveContent()) {
-                R.string.note_editor_no_cards_created_all_fields
-            } else {
-                R.string.note_editor_no_cards_created
+    private fun noClozeDialog(errorMessage: String) {
+        AlertDialog.Builder(this).show {
+            message(text = errorMessage)
+            positiveButton(R.string.dialog_yes) {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:337]: I believe the material dialog spec prefers save/cancel over yes/no

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt [hunk 14]
```diff
@@ -1019,17 +1031,16 @@ class NoteEditor : AnkiActivity(), DeckSelectionListener, SubtitleListener, Tags
...
-                    editorNote!!.notetype.put("tags", tags)
-                    notetypes.save(editorNote!!.notetype)
-                    addNote(editorNote!!, deckId)
+
+            lifecycleScope.launch {
+                val noteFieldsCheck = checkNoteFieldsResponse(editorNote!!)
+                if (noteFieldsCheck is NoteFieldsCheckResult.Failure) {
+                    addNoteErrorMessage = noteFieldsCheck.getLocalizedMessage(this@NoteEditor)
+                    displayErrorSavingNote()
+                    return@launch
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:1040]: I'd move `addNoteErrorText = null` here (if possible)

**Review by david-allison — COMMENTED** [review]
Last changes, both implementer's choice

Add a `NeedsTest` or a test to be sure the error message is cleared

Cheers!

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt (hunk 13 above)
Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:337]: Anki had it this way, so that's why but yes android usually have save/cancel, want me to change?

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:337]: Yeah, follow the Android guidelines

File: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt [hunk 15]
```diff
@@ -316,31 +318,38 @@ class NoteEditor : AnkiActivity(), DeckSelectionListener, SubtitleListener, Tags
...
-                return R.string.note_editor_no_first_field
-            }
-            return if (allFieldsHaveContent()) {
-                R.string.note_editor_no_cards_created_all_fields
-            } else {
-                R.string.note_editor_no_cards_created
+    private fun noClozeDialog(errorMessage: String) {
+        AlertDialog.Builder(this).show {
+            message(text = errorMessage)
+            positiveButton(R.string.dialog_ok) {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt:338]: I believe prefer 'add/save' rather than OK

Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt]: Resolved!

**Review by david-allison — APPROVED** [review]
Thanks!

**Comment by criticalAY** [comment]
Put a gsoc label here since will be using the code in instant note editor too before saving the note

**Comment by david-allison** [comment]
Forgot to sync translations on this one. Running now
