### PR TITLE
fix: NoSuchFileException in card template fragment

### LINKED ISSUE #20781: java.nio.file.NoSuchFileException: /data/user/0/com.ichi2.anki/cache/notetype957925729682963336.tmp
2.24.0alpha10

https://ankidroid.org/acra/app/1/bug/397266/report/a58af326-8cd2-40c5-a85c-2ba317c5c3a2

```
java.lang.RuntimeException: An exception happened in constructor of class com.ichi2.anki.previewer.y0
	at androidx.lifecycle.SavedStateViewModelFactory_androidKt.newInstance(SavedStateViewModelFactory.android.kt:263)
	at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.android.kt:153)
	at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.android.kt:112)
	at androidx.lifecycle.viewmodel.internal.ViewModelProviderImpl_androidKt.createViewModel(ViewModelProviderImpl.android.kt:35)
	at androidx.lifecycle.viewmodel.internal.ViewModelProviderImpl.getViewModel$lifecycle_viewmodel(ViewModelProviderImpl.java:59)
	at androidx.lifecycle.viewmodel.internal.ViewModelProviderImpl.getViewModel$lifecycle_viewmodel$default(ViewModelProviderImpl.java:43)
	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:90)
	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:52)
	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:35)
	at com.ichi2.anki.previewer.TemplatePreviewerFragment.getViewModel(TemplatePreviewerFragment.kt:35)
	at com.ichi2.anki.previewer.TemplatePreviewerFragment.getViewModel(TemplatePreviewerFragment.kt:32)
	at com.ichi2.anki.previewer.CardViewerFragment.setupWebView(CardViewerFragment.kt:115)
	at com.ichi2.anki.previewer.CardViewerFragment.onViewCreated(CardViewerFragment.kt:68)
	at com.ichi2.anki.previewer.TemplatePreviewerFragment.onViewCreated(TemplatePreviewerFragment.kt:52)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3152)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:608)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:286)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1685)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3319)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3237)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:350)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:238)
	at com.ichi2.anki.AnkiActivity.onStart(AnkiActivity.kt:163)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1597)
	at android.app.Activity.performStart(Activity.java:8931)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4016)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:235)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:215)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:187)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:101)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2589)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:222)
	at android.os.Looper.loop(Looper.java:314)
	at android.app.ActivityThread.main(ActivityThread.java:8790)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.nio.file.NoSuchFileException: /data/user/0/com.ichi2.anki/cache/notetype957925729682963336.tmp
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:220)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at j$.nio.file.spi.a.v(SourceFile)
	at j$.nio.file.Files.copy(SourceFile:154)
	at com.ichi2.compat.CompatV26.copyFile(CompatV26.kt:71)
	at com.ichi2.anki.NotetypeFile.getNotetype(CardTemplateNotetype.kt:541)
	at com.ichi2.anki.previewer.TemplatePreviewerArguments.getNotetype(TemplatePreviewerViewModel.kt:291)
	at com.ichi2.anki.previewer.TemplatePreviewerViewModel.<init>(TemplatePreviewerViewModel.kt:73)
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at androidx.lifecycle.SavedStateViewModelFactory_androidKt.newInstance(SavedStateViewModelFactory.android.kt:257)

```

### PR DESCRIPTION
**Pull request by criticalAY**
> [!NOTE]
> Assisted-by: Claude Opus 4.6 - Reproduction of the issue
> Turn on Don't keep activitiy -> open template editor -> press home -> clear AnkiDroid cache -> open AnkiDroid -> crash -> report
> (I tried in Tablet)
## Purpose / Description
The previewer was crashing after process death. Android restores the activity, the ViewModel tries to rebuild by reading a temp file we'd stashed earlier, and the file is gone so the constructor throws and the app dies. so bug: SavedStateHandle promised durability, the file didn't deliver it.

## Fixes
* Fixes #20781

## Approach
- I switched  out of the cache directory i.e. Temp notetype files used to live in cacheDir, which Android is allowed to wipe whenever it wants - low storage, OEM cleaners, user tapping "Clear cache." [this is what i did]  Now they live in noBackupFilesDir.
- Since the OS no longer evicts the files for us, the ViewModel now deletes its temp file in onCleared() 
- the fragment detects this at the start of onViewCreated and just finishes the activity instead of letting the ViewModel blow up  

## How Has This Been Tested?
Emulator API 31 tablet

## Learning (optional, can help others)
I am open to any other suggestion but this is what i can think of even note editor is finished when we do that same or dont keep activity is turned on

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

<!--- Uncomment this section ONLY if this PR introduces new resources (external libraries, icons etc)
## Licenses
_For each new external resource, add a row to the table below:_

| Library | Description | License |
| --- | --- | --- |
| Sample Icon Library | Sample Description | [The Apache Software License, Version 2.0](http://www.apache.org/licenses/LICENSE-2.0.txt) |

**Maintainers:**

* [ ] Add the https://github.com/ankidroid/Anki-Android/labels/Licenses label
* [ ] Update the [licenses](https://github.com/ankidroid/Anki-Android/wiki/Licences) wiki when merging

### CODE REVIEW

**Comment by david-allison** [comment]
I haven't explicitly fixed these as I suspected there was more going on here.

It seems unusual that so many issues are coming from the OS clearing the cache, and I was concerned there was another bug at play.

If we are going to fix this:

1. Audit all screens which use `IdsFile`, add a tracking issue, and sub-issues to ensure that the `IdsFile` is deleted in all cases
    * I suspect that undeleted `IdsFile` instances are a major cause of this issue: larger caches -> more likely the cache is cleared.
3. `IdsFile.getIds()` should return a nullable list
4. Each screen should properly handle `IdsFile.getIds()` failing, likely by an early `finish()`, I'm not sure if the current handling of this issue is intuitive to developers, vs calling .finish() in the right place and skipping the ViewModel init

**Comment by criticalAY** [comment]
So, should we just add more logs for now?

**Comment by david-allison** [comment]
I added logs before 2.23, my suspicion is still that we're not cleaning up old `IdsFile` references which is causing cache pressure. This should be trivial to check by inspecting my cache. I'll do this shortly

If this is the case, we should be able to move these files in the cache to a folder, and determine a good metric for when to clear the old instances, so we don't need to rely on flaky file deletion logic

We can either 
* Delete the `IdsFile` on a clean app launch
* Ensure that each `IdsFile` is namespaced, so there can only be one `idsfile/notetypexxx.tmp`

**Comment by david-allison** [comment]
Various caching issues:

* apkg files may not be deleted
  * This one's been an issue for a long while 
* multiple idsfile references

Screenshot 2026-04-22 at 12 26 50

File: AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerFragment.kt [hunk 1]
```diff
@@ -74,11 +74,14 @@ abstract class CardViewerFragment(
...
     override fun onStart() {
         super.onStart()
+        // A subclass may call requireActivity().finish() to abort setup so skip viewModel access here
+        if (activity?.isFinishing == true) return
         viewModel.setSoundPlayerEnabled(true)
     }
 
     override fun onStop() {
         super.onStop()
+        if (activity?.isFinishing == true) return
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerFragment.kt:88]: May want a comment:

Paraphrase: explaining that it'll be disposed later if `isFinishing` is set


https://github.com/ankidroid/Anki-Android/blob/1e24f0ffaf188dd96f96668c00cb6dfea79822e9/AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerViewModel.kt#L59-L65

File: AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerFragment.kt [hunk 2]
```diff
@@ -65,6 +76,15 @@ class TemplatePreviewerFragment :
...
     }
 
+    private fun hasReadableNotetype(): Boolean =
+        BundleCompat
+            .getParcelable(
+                requireArguments(),
+                ARGS_KEY,
+                TemplatePreviewerArguments::class.java,
+            )?.notetypeFile
+            ?.getNotetypeOrNull() != null
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/previewer/TemplatePreviewerFragment.kt]: expose `TemplatePreviewerArguments.isUsable(bundle)` instead - this means the property can be kept private

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateNotetype.kt
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateNotetype.kt]:
```suggestion
            Timber.w(e, "Unable to read+parse tempNoteType from file %s", absolutePath)
```

**Review by david-allison — APPROVED** [review]
LGTM, some optional thoughts. Implementer's choice

File: AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerFragment.kt [hunk 3]
```diff
@@ -74,11 +74,14 @@ abstract class CardViewerFragment(
 
     override fun onStart() {
         super.onStart()
+        // A subclass may call requireActivity().finish() to abort setup so skip viewModel access here
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerFragment.kt:77]: so the subclass should be the one skipping `super.onStart` on its own `onStart`

Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerFragment.kt:77]: A subclass can't bypass CardViewerFragment.onStart() to call Fragment.onStart() directly - Kotlin/JVM has no grandparent-super call imo. So the isFinishing guard has to live here in the base.

**Review by mikehardy — APPROVED** [review]
LGTM - noting:

1- the fix itself, adding protection + return-fast teardown if file not usable and .finish is happening, seems like okay defensive code, and
2- there appears to be underlying cachedir cleanups not happening - an audit of usage to correct in case-by-case basis seems warranted but as Android process death may happen any time, perhaps a "converge to clean" method where if (for example) deck picker is showing in a certain configuration we simply know that whole classes of cache dir usage (apkg import, ids files...) won't be happening, so cleaning the existing set (if exists...) of those classes of usage as a background async IO thing would be good
