### PR TITLE
fix(startup): show fatal error dialog if 'AnkiDroid Directory' can't be set due to `getExternalFilesDir` returning null

### LINKED ISSUE #13207: [Bug] AnkiDroid fails to start if external storage does not exist
###### Reproduction Steps

1. fire up a windows machine (windows 11 VM, Android 12 emulator, verified that `/sdcard/AnkiDroid` did not exist - that is, it is a clean install)
2. `gradlew.bat installPlayDebug`
3. attempt to start the app after install

###### Expected Result

App starts up

###### Actual Result

NullPointerException, the wicked `!!` strikes again...

Sincere apologies for the screenshot of the stacktrace, it's on a VM where I can't copy/paste the text for "reasons"

image

But here's a link to the offender in attempt to make up for it: https://github.com/ankidroid/Anki-Android/blob/bc6caf9d9e199e8f295d49c27bbb4fbfd859f183/AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt#L492

I did get a toast saying "Device Storage Not Mounted" and the app quit, after uninstalling / reinstalling / granting storage permission

What if there is no external storage though? Should I be able to use AnkiDroid on only internal storage? That could be a valid device configuration ?

Storage config looks like this:

image

There is supposed to be a 768MB sdcard in the AVD definition but it appears it is not mounted, this shows up in logs:

> StorageManagerService  system_process  W No primary storage defined yet; hacking together a stub

It is possible this configuration is simply invalid (are there any android devices that have no "external" storage?) as I am unable to run the storage system preferences app either (`Volume external_primary not found`)

But might be worth a look / some better messaging in case something like this is out in the wild.

I'll purge this AVD and try a different one

###### Debug info

Just one commit back on main at the moment - was built from this commit sha https://github.com/ankidroid/Anki-Android/commit/4cb853c1e10cd95669f810e5987c6ef7a7cf1918

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description

There has been a rare, long-standing issue where `getExternalFilesDir` returns `null`. The root cause was not diagnosed, but it caused AnkiDroid to crash on initial startup of the app.

Due to [Bug 460912704](https://issuetracker.google.com/issues/460912704) (Android 16), this is now a pressing concern: it is the most common crash bug on Pixel devices.

The main aim of this PR is to detect when this condition occurs **[and `PREF_COLLECTION_PATH` is unset]** and inform the user that there is likely a problem with their phone.

## Fixes
* Fixes #13207

## Approach
Initially, I copied the 'fatal error' code we used for `WebviewFailed`, and applied this for a storage error. A `SystemStorageException` class was defined to isolate the error condition, and it was tested that a 'Fatal error' dialog was displayed. I also added 'help' link code, as we agreed to link to the GitHub issue if this bug occurs

I then added a unit test, which exposed a number of startup paths depending on the collection directory being available.
* `DeckPicker:onCreateOptionsMenu`
* `initializeNavigationDrawer -> enablePostShortcut()`
* `BootService`
* etc...

These were all fixed. During this time, I was documenting calls where `SystemStorageException` could be thrown and refactoring the 'fatal error' code to combine the 'WebviewFailed' and 'StorageFatalError' cases in `InitialActivity/DeckPicker`

I had two methods of manual testing:

<details>

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt b/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt	(revision f87b883ec8f159a87ed6b9e9b6969775fd291328)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.kt	(date 1763405277313)
@@ -208,6 +208,11 @@
                 fatalInitializationError = FatalInitializationError.StorageError(e)
                 null
             }
+        fatalInitializationError = FatalInitializationError.StorageError(SystemStorageException.build(
+            errorDetail = "getExternalFilesDir unexpectedly returned null",
+            infoUri = "https://github.com/ankidroid/Anki-Android/issues/13207",
+        ))
+        
         // Create the AnkiDroid directory if missing. Send exception report if inaccessible.
         if (ankiDroidDir != null && Permissions.hasLegacyStorageAccessPermission(this)) {
             try {

```

</details>

and 

<details>

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt b/AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt	(revision f87b883ec8f159a87ed6b9e9b6969775fd291328)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.kt	(date 1763404210196)
@@ -227,14 +227,14 @@
         // This value *may* be null but we strictly require it. This has caused NullPointerException
         // in previous releases as we dereference. We can't recover but for purposes of triage,
         // we will now check for null and if so try to log more information about why.
-        if (externalFilesDir == null) {
+        // if (externalFilesDir == null) {
             Timber.e("Attempting to determine collection path, but no valid external storage?")
             throw SystemStorageException.build(
                 errorDetail = "getExternalFilesDir unexpectedly returned null",
                 infoUri = "https://github.com/ankidroid/Anki-Android/issues/13207",
             )
-        }
-        return externalFilesDir.absolutePath
+        // }
+        // return externalFilesDir.absolutePath
     }
 
     /**

```

</details>

I found that a real device was skipping the `Permissions.hasLegacyStorageAccessPermission` check in `AnkiDroidApp`, (test 2) so I extracted the conditional to produce the fatal error.

Finally, I recalled an error which was displayed on the 'sync' screen by one of the reddit reports. Intuition told me this came from the AnkiDroidApp => DeckPicker =>  IntroductionActivity => Sync from AnkiWeb omboarding flow flow.

It seemed pointless to show the Introduction if we knew the app was broken, so I avoided showing the introduction if a fatal error occurred.

I finally spent a fair amount of time making sure the commits were in good shape.

## How Has This Been Tested?

A unit test was added

See patches above, these were applied to an API 36 emulator

Screenshot 2025-11-17 at 18 11 14

⚠️ A follow-up issue will be added:
* Determine how to handle `getExternalFilesDir` being null, but an existing AnkiDroid Directory is valid
  * For example: on a `full` build where `getExternalStorageDirectory` is still valid
  * I researched the failures in ACRA, and all the Pixel crashes I saw did not have 'AnkiDroid Directory' set
* Fix other broken entry points
  * `ManageSpaceActivity` for example 
  * `ensureStoragePermissions` calls

## Learning (optional, can help others)

* We cannot use `BAKLAVA` in Robolectric yet
  * `Failed to create a Robolectric sandbox: Android SDK 36 requires Java 21 (have Java 17)`
* https://issuetracker.google.com/issues/460912704 
* https://developer.android.com/reference/android/content/Context#getExternalFilesDir(java.lang.String)

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerNoExternalFilesDirTest.kt [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+import org.robolectric.annotation.Config
+import org.robolectric.annotation.Implementation
+import org.robolectric.annotation.Implements
+import org.robolectric.shadows.ShadowDialog
+import java.io.File
+
+@RunWith(AndroidJUnit4::class)
+@Config(shadows = [ShadowNullExternalFilesDir::class])
+class DeckPickerNoExternalFilesDirTest : RobolectricTest() {
+    // TODO: @Config(sdk = [Build.VERSION_CODES.BAKLAVA]) // Bug 460912704 occurs on Android 16
```
Comment (mikehardy) [inline AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerNoExternalFilesDirTest.kt:38]: JDK21 allows robolectric to use Android 16 `@Config` but our build allows JDK17

From Robolectric releases page [current release](https://github.com/robolectric/robolectric/releases/tag/robolectric-4.16)

> Robolectric 4.16 supports Android Baklava (SDK 36)

So, it should support that ? I tested it locally with this `// TODO: ` removed such that the `@Config` annotation would take effect, I noticed during test execution that the robolectric jar did appear to download, and it worked for me.

I believe this is just a local environment issue then - that you specifically are using JDK < 21 but it would work if you upgraded.

We allow this currently in our build.gradle but there's no reason we can't slide the JDK version floor up and just say for developers that 21+ is now "it"

https://github.com/ankidroid/Anki-Android/blob/1a563a3c7a2860e1959270b8534e39841509f3c4/build.gradle.kts#L113

Could be (should be!) a follow-on issue (so the first line in this comment is aimed at being a good peel-out issue line)

Comment (david-allison) [reply AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerNoExternalFilesDirTest.kt:38]: LGTM

* https://github.com/ankidroid/Anki-Android/issues/19533
