### PR TITLE
Fixed "CheckMedia" causing crash

### LINKED ISSUE #10892: [Bug] Crash : Ankidroid crashes on checking media.
###### Reproduction Steps
- Updated from 2.15.6 (Play store ver.) to 2.16alpha58
 and when i opened a card i started getting "failed to load : failed to load ...."

- So i decided to use check media which instantly crashed the app.
- After that i decided to force sync from anki web to ankidroid which also crashed the app.
- Decided to check if my library was corrupted for some reason or not by downloading a parallel of 2.15.6 on which it seemed to work perfectly, updated the parallel to alpha58 and it was also crashing.
- The alpha also doesn't seem to be detecting the backups neither is it creating them properly from what i can tell.

The only one which was good on 16/04 was made by the stable parallel.

- Just to confirm if the problem was from this alpha or from before this I decided to test on alpha 56 parallel and got the same issues uninstalled the parallel and installed alpha 55 parallel and there wasn't a crash this time, decided to update 55 to 56 and test again and there wasn't a crash, same with from 56 to 58.
- ~~Btw I did try to reinstall main alpha58 directly when i was originally getting the crash before the above point happened and the crashes still happened.~~ I thought i did but seems like i hadn't installed it directly and when I just did it seems to work fine on installing directly and this only happens if you update directly from 2.15.6 to 2.16 Alpha56/58/59.
- Have confirmed that it doesn't crash anymore on main after uninstalling 58 and installing 55 then 56 and 58 again after that.
- ~~Backup still don't seem to be being created properly but am not sure yet, so will confirm after I am.~~ It is detecting backups again and the backups are being created properly.

- Also half of this happened while writing this so it might seem like a story.

###### Expected Result

App checks media , directly syncs from anki web to ankidroid , Backup being created properly.

###### Actual Result

App crashes if you have updated directly to alpha 58 or installing alpha58 directly over current library.

###### Debug info
AnkiDroid Version = 2.16alpha58

Android Version = 11

Manufacturer = Xiaomi

Model = Redmi Note 9 Pro Max

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Redmi Note 9 Pro Max Build/RKQ1.200826.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/100.0.4896.88 Mobile Safari/537.36

ACRA UUID = d9199133-a62c-4572-ad4f-899c4d0b5307

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by dorrin-sot**
## Purpose / Description
App crashed if checkmedia was done after an update from v2.15.6
This is a followup of #10926 which didn't adress the issue of update causing the crash. (#10926 needed a reinstall)

## Fixes
Fixes #10892 

## Approach
Added a read permission check in `DeckPicker::mediaCheck()`

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by dorrin-sot** [comment]
if this actually fixes it, I would like to check other instances where write permission was previously checked to see if read permission check is also needed

**Review by mikehardy — CHANGES_REQUESTED** [review]
:thinking: the first commit is already merged, so it should be dropped from this PR
I can't think of a situation where we would want to have write but not read?
Seems like the rename is not necessary and the hasStorageAccessPermission check should be extended to check READ too every time?

**Review by mikehardy — APPROVED** [review]
Could do it :-), curious second set of eyes from @david-allison

**Comment by dorrin-sot** [comment]
Do I add to the tests that test permission requirements?

File: AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt [hunk 1]
```diff
@@ -37,15 +37,35 @@ object Permissions {
...
+    }
+
+    /**
+     * Check if we have read and write access permission to the external storage
+     * @param context
+     * @return
+     */
+    @JvmStatic
+    fun hasStorageAccessPermission(context: Context): Boolean {
+        return hasStorageReadAccessPermission(context) && hasStorageWriteAccessPermission(context)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt:66]: I believe this means we show 'Welcome to AnkiDroid' for existing users. Can we go through this logic with a fine-tooth comb to ensure that the UX is correct.

https://github.com/ankidroid/Anki-Android/blob/cf0cef3c3285af22986804411e63836d83e513d8/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt#L473-L498

Comment (dorrin-sot) [reply AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt:66]: Oh If the welcome dialog shouldn't be shown to non-first-time users, shouldn't we save it in sharedpreferences instead of savedInstanceState in order to avoid it getting displayed on every startup?

https://user-images.githubusercontent.com/59933477/164271542-2090cb6e-9304-493d-885e-71b0a5f65fab.mov

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt:66]: > Oh If the welcome dialog shouldn't be shown to non-first-time users, shouldn't we save it in sharedpreferences instead of savedInstanceState in order to avoid it getting displayed on every startup?

I think if shared preferences has any entry in it for version information, that indicates that it is not the first startup, and the welcome dialog should not be shown

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/utils/Permissions.kt:66]: > ```diff
> getSharedPreferences("", MODE_PRIVATE).all.isEmpty()
> ```

Could you submit this?

This is incorrect at the very least, we should be using `AnkiDroidApp.getSharedPreferences()`

**Comment by dorrin-sot** [comment]
@david-allison Still awaiting your feedback 😁👀

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 2]
```diff
@@ -327,7 +329,7 @@ public void onCreate() {
         CardBrowser.clearLastDeckId();
 
         // Create the AnkiDroid directory if missing. Send exception report if inaccessible.
-        if (Permissions.hasStorageAccessPermission(this)) {
+        if (hasStorageAccessPermission(this)) {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:332]: (nit): this doesn't seem necessary

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 3]
```diff
@@ -474,7 +474,8 @@ open class DeckPicker : NavigationDrawerActivity(), StudyOptionsListener, SyncEr
             Manifest.permission.WRITE_EXTERNAL_STORAGE,
             Manifest.permission.READ_EXTERNAL_STORAGE
         )
-        if (mClosedWelcomeMessage) {
+        val sharedPrefsIsntEmpty = AnkiDroidApp.getSharedPrefs(this).all.isNotEmpty()
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:477]: This no longer shows the 'welcome' dialog

**Review by david-allison — CHANGES_REQUESTED** [review]
Sorry for the delay, lots to think about when working here and I wanted to be 'fresh'

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt (hunk 3 above)
Comment (dorrin-sot) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:477]: Can I add a boolean shared preference for `firstStartup` with a default of true?

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt]: I'd say "welcomeMessageDismissed", but really: up to you

**Review by david-allison — APPROVED** [review]

**Review by mikehardy — APPROVED** [review]
Alright! Here we go  - thanks for this @dorrin-sot
