### PR TITLE
fix(study-screen): audio record behavior when put in the background

### LINKED ISSUE #20024: [New study screen] Voice record deleted after putting the app on the background

### PR DESCRIPTION
**Pull request by BrayanDSO**
1. if the audio is playing, pause it
2. if it is recording, pause the recording

## Fixes
* Fixes https://github.com/ankidroid/Anki-Android/issues/20024

## How Has This Been Tested?

Galaxy Tab S9, Android 16

[Audio sample](https://www.youtube.com/watch?v=dQw4w9WgXcQ&list=RDdQw4w9WgXcQ&start_radio=1)

https://github.com/user-attachments/assets/324a0b6f-7d23-4a73-a25d-950d7e90ae99

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/audiorecord/CheckPronunciationViewModel.kt [hunk 1]
```diff
@@ -70,6 +70,16 @@ class CheckPronunciationViewModel(
         }
     }
 
+    fun pausePlayback() {
+        if (isPlaying) {
+            progressBarUpdateJob?.cancel()
+            audioPlayer.pause()
+            viewModelScope.launch {
+                playIconFlow.emit(R.drawable.ic_play)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/audiorecord/CheckPronunciationViewModel.kt]: Future architecture: best not to have Android concerns in the ViewModel

**Review by david-allison — APPROVED** [review]
LGTM

File: AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/audiorecord/CheckPronunciationViewModel.kt (hunk 1 above)
Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/audiorecord/CheckPronunciationViewModel.kt]: fixed. Thanks for the push

**Comment by ZornHadNoChoice** [comment]
What about when going back to the main screen? [The original request](https://forums.ankiweb.net/t/new-study-screen-official-thread/67394/100?u=zornhadnochoice) also asked for this.

**Review by criticalAY — APPROVED** [review]

**Comment by BrayanDSO** [comment]
> What about when going back to the main screen? [The original request](https://forums.ankiweb.net/t/new-study-screen-official-thread/67394/100?u=zornhadnochoice) also asked for this.

#20824
