### PR TITLE
fix: update flows when screen is visible

### LINKED ISSUE #19632: Update flows when the screen is visible, but not interactive
why RESUMED?

_Originally posted by @BrayanDSO in https://github.com/ankidroid/Anki-Android/pull/19607#discussion_r2569644958_
            
----

We should be using `repeatOnLifecycle(Lifecycle.State.STARTED)`

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
Knowing what I know now, `repeatOnLifecycle(Lifecycle.State.STARTED)` is better

## Fixes
* Fixes #19632
* Split out of https://github.com/ankidroid/Anki-Android/issues/18709

## Approach
* refactor to use context parameters
* Change `State.RESUMED` => `State.STARTED`

## How Has This Been Tested?
Unit tests: 1 fixed - the Robolectric `runBlocking` workaround wasn't perfect

I went through all seemingly risky functionality using my Pixel 9 Pro - no catastrophic issues.

## Learning (optional, can help others)
Robolectric isn't perfect

Cause:
* https://github.com/ankidroid/Anki-Android/pull/17690#discussion_r1905349394
* => https://github.com/ankidroid/Anki-Android/commit/e35b5b996e7f548ad6f10f871784b2174c521fbc

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/Flow.kt [hunk 1]
```diff
@@ -37,3 +46,55 @@ fun <T> Flow<T>.collectIn(
...
+}
+
+context(activity: AnkiActivity)
+fun <T> StateFlow<T>.launchCollectionInLifecycleScope(block: suspend (T) -> Unit) {
+    activity.lifecycleScope.launch {
+        var lastValue: T? = null
+        activity.lifecycle.repeatOnLifecycle(Lifecycle.State.RESUMED) {
+            this@launchCollectionInLifecycleScope.collect {
+                // on re-resume, an unchanged value will be emitted for a StateFlow
+                if (lastValue == value) return@collect
```
Comment (criticalAY) [inline AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/Flow.kt:90]: Just curious and want to know what will happen if the app is in background and value is updated (lets say) lastValue check will see the new value when the app resumes, compare it to the new value property, and potentially skip the UI update.

**Review by criticalAY — COMMENTED** [review]
One question rest is all good, will approve once its resolved

File: AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/Flow.kt (hunk 1 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/Flow.kt:90]: @criticalAY Is it feasible to move this to a separate issue so we can audit current usages? 

I believe that the changes are handled on state flows, and ignored on shared flows, but we should document this better.

For now, I believe we've moved to accepting more UI changes: previously only 'RESUMED', now 'STARTED'

Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/utils/ext/Flow.kt:90]: Sure!
