### PR TITLE
Persist Whiteboard Visible State

### LINKED ISSUE #5065: Whiteboard toggle button disappears when exiting the review and coming back to it
###### Reproduction Steps

1. Enable whiteboard for a deck
2. Start reviewing the deck. Whiteboard is on-by-default.
3. Turn whiteboard off.
4. Stop reviewing the deck.
5. Start reviewing the deck again. Whiteboard is on-by-default again.

This also happens when switching from day mode to light mode. As I do this switch relatively often (each time I notice an image card I have is still black-on-transparent instead of black-on-white and until I get to a computer to fix it…), it's a bit of a PITA.

Do you think it'd be possible to remember this is-whiteboard-currently-on-or-not (as opposed to enabled-or-not) per-deck, or at least at a global level? :)

Anyway, thank you for making Ankidroid!

###### Debug info

AnkiDroid 2.8.4, the rest should be useless here :)

###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

### PR DESCRIPTION
**Pull request by david-allison-1**
This review was borderline "I should split this into commits". If you'd prefer this, please let me know.

I'd also love to hear "You should abstract out the whiteboard logic from `Reviewer` and test it", but I doubt it's considered to be a good use of time. 

----

## Purpose / Description
Previously, the whiteboard visible state depended on the enabled state

This caused problems when switching from Night Mode, as it would forget the Visible setting.

## Fixes
Fixes #5065

## Approach

We now persist the visible state to the internal database, this still depends on the enabled flag.

## How Has This Been Tested?

Previously it did not work on my device.

Now when switching to night mode, the visible status is saved.

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/MetaDB.java [hunk 1]
```diff
@@ -81,38 +81,49 @@ private static SQLiteDatabase upgradeDB(SQLiteDatabase mMetaDb, int databaseVers
...
+        mMetaDb.setVersion(databaseVersion);
+        Timber.i("MetaDB:: Upgrading Internal Database finished. New version: %d", databaseVersion);
+        return mMetaDb;
+    }
+
+
+    private static void updateWhiteboardState(SQLiteDatabase mMetaDb) {
+        int columnCount  = DatabaseUtil.getTableColumnCount(mMetaDb, "whiteboardState");
+
+        if(columnCount <= 0) {
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/MetaDB.java]:
```suggestion
        if (columnCount <= 0) {
```

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java [hunk 2]
```diff
@@ -169,8 +169,10 @@ protected void onCollectionLoaded(Collection col) {
 
         mPrefWhiteboard = MetaDB.getWhiteboardState(this, getParentDid());
         if (mPrefWhiteboard) {
+            //DEFECT: Slight inefficiency here, as we set the database using these methods
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java]: I believe this onCollectionLoaded callback is async yes? (I should know offhand but always have to re-trace this stuff and I'm reviewing quickly at the moment) I believe it is - if this is on the main/UI thread it could be a pain for folks, we try not to touch storage ever on the main/UI thread, thus all the AsyncTask infrastructure

Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java]: We already do it in both the unchanged lines above and below, this adds two more calls. `onCollectionLoaded` is a very rare event, so I'm not too worried about adding a few ms here.

But, I'll move this into a testable unit, and will get it fixed. Probably in the next day or two. Happy to block on this for now.

**Comment by david-allison-1** [comment]
Let's block this on extracting Whiteboard Logic from `AbstractFlashCardViewer` and `Reviewer`.

Could I get sign-off on the goals:

* Refactor current PR into commits
* Extract Whiteboard UI logic into separate class
* Test the above class
* Fix inefficiencies in whiteboard loading logic (4 DB calls -> 1 DB call)
* Test MetaDB.
  * It's going to be a bit of work, but there's value
* Refactor MetaDB to use 'REPLACE' rather than a conditional insert/update
* Refactor MetaDB to use try with resources
  * This requires that any developers upgrade to Android Studio 3.0+: https://stackoverflow.com/a/24290875

**Comment by mikehardy** [comment]
> Let's block this on extracting Whiteboard Logic from `AbstractFlashCardViewer` and `Reviewer`.
> 
> Could I get sign-off on the goals:
>     * Refactor current PR into commits

Yes - that will help

>     * Extract Whiteboard UI logic into separate class
>     * Test the above class

This isn't a strong goal of mine but is good in general

>     * Fix inefficiencies in whiteboard loading logic (4 DB calls -> 1 DB call)

This isn't a goal of mine really, esp if onCollectionLoaded is async. Perhaps just moving the current logic to whatever is async (the actual collection load perhaps) is fine - just lock the UI less

>     * Create MetaDB test harness
>       * It's going to be a bit of work, but there's value

Very coarse testing would be good - no hard requirement here, testing is usually an 80/20 deal but to corrupt the cliche 80% of the coverage can be had in 20% of the time taken to get to 100%, just getting something going would be great

>     * Refactor MetaDB to use 'REPLACE' rather than a conditional insert/update
>     * Refactor MetaDB to use try with resources
>       * This requires that any developers upgrade to Android Studio 3.0+: https://stackoverflow.com/a/24290875


Those aren't goals of mine although in general I expect people to update to stable Android Studio within a week or so of it being available and I'm fine with requiring the same. I typically merge the gradle plugin version bump with about a week lag

My list is:
- separate non-semantic and semantic changes
- questioning "are we touching storage while sync on the UI thread?", if so what's the smallest change to fix that and is it good enough?
- most basic test harness for metadb possible would be nice to bring up - but it's a stretch goal

Anything else is extra in my mind - I'm fine with extras but regressions scale with size of change so as more extras are attempted more testing should be considered

**Comment by david-allison-1** [comment]
@mikehardy Understood. Will do. 

Agreed on the testing front. I'm also of the opinion that 5% testing increases the chance of others adding tests by 500%.

**Comment by david-allison-1** [comment]
Either sync or async based on the collection status.

https://github.com/ankidroid/Anki-Android/blob/bf4ce65d58f50df5bfb2c7065ceac45e0fe99ee8/AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.java#L262-L281

Will get the other comments done tomorrow.
