### PR TITLE
fix(resizable-pane): prevent parent from intercepting touch events during resizing drag

### LINKED ISSUE #19105: Resizable panes conflict with Full navigation drawer screen setting
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

Go to Settings>General> Enable Full navigation drawer screen setting

Grab resizing divider and drag it

### Expected Behavior:
Panes resize

### Actual Behavior:
Navigation drawer opens up and intercepts resizing

### Debug info

```text
AnkiDroid Version = 2.23.0alpha1-debug (ec71279a2df7d6c1e9668f78cf0b35fd2c31ee66)  
Backend Version = 0.1.60-anki25.07.5 (25.07.5 7172b2d26684c7ef9d10e249bd43dc5bf73ae00c)  
Android Version = 15 (SDK 35)  
ProductFlavor = play  
Device Info = Google | google | emu64xa | sdk_gtablet_x86_64 | Pixel Tablet | ranchu  
Webview User Agent = Mozilla/5.0 (Linux; Android 15; Pixel Tablet Build/AE3A.240806.046.T1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.219 Safari/537.36  
ACRA UUID = 3f3f7a7b-a266-4146-ad55-07caf68e5724  
FSRS = 4.1.1 (Enabled: false)  
Crash Reports Enabled = false
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by Haz3-jolt**
## Purpose / Description
- Fixes the bug caused when resizing panes when Full screen navigation drawer setting is enabled

## Fixes
* Fixes #19105 

## Approach
- Uses `requestDisallowInterceptTouchEvent` to stop the drag event being intercepted.

## How Has This Been Tested?
- Physical Acer Chromebook API 34
- Tablet Emulator API 35
[nav.webm](https://github.com/user-attachments/assets/2459bf25-125b-40fb-8fbb-2b594d41398c)

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by Haz3-jolt** [comment]
> Could you explain this API? I would have expected that `requestDisallowInterceptTouchEvent(false)` would need to be called afterwards
> 
>     * This is only called on the touch events, not on class init, implying it's meant to be temporary

Looked at the API:
```kt
private var childRequestedNoTouchInterception = false
    private var lastWeWantToIntercept = false

    override fun requestDisallowInterceptTouchEvent(disallowIntercept: Boolean) {
        super.requestDisallowInterceptTouchEvent(disallowIntercept)
        childRequestedNoTouchInterception = disallowIntercept
    }

    override fun onInterceptTouchEvent(event: MotionEvent): Boolean {
        if (childRequestedNoTouchInterception) {
            if (event.actionMasked == ACTION_DOWN) {
                childRequestedNoTouchInterception = false
            } else {
                return false
            }
        }

        val weWantToIntercept = super.onInterceptTouchEvent(event)
        val shouldSkipThisInterception = weWantToIntercept && !lastWeWantToIntercept
        lastWeWantToIntercept = weWantToIntercept
        return if (shouldSkipThisInterception) false else weWantToIntercept
    }
```
    
If I am right, it automatically switch back to intercepting touch events. Didn't actually need to have one on ACTION_UP/CANCEL that was a mistake on my part. I'll remove it!

File: AnkiDroid/src/main/java/com/ichi2/anki/ui/ResizablePaneManager.kt [hunk 1]
```diff
@@ -77,13 +77,18 @@ class ResizablePaneManager(
 
             when (event.action) {
                 MotionEvent.ACTION_DOWN -> {
+                    // Request parent to not intercept touch events
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/ui/ResizablePaneManager.kt]: modify this to explain why

**Comment by Haz3-jolt** [comment]
@david-allison flaky run, possible to restart?
