### PR TITLE
Fix sync cancellation

### LINKED ISSUE #4512: AnkiDroid calling /sync/finish when it shouldn't
Following up on #4366, which seems to have been closed for some reason.

I'm seeing quite a few instances of AnkiDroid 2.7 connecting to /sync/meta and then immediately calling /sync/finish, without ever calling /sync/start or other sync commands. This results in a bumped usn, and if AD is saving the returned value it would likely result in sanity errors.

I've changed the server to return a HTTP 409 in such cases, but the users are probably receiving an error now, so it still needs fixing on the AD side.

### PR DESCRIPTION
**Pull request by timrae**
Previously we were calling sync/finish during abort, which is not supported by the protocol, as discussed in issue #4512. Instead we must use the new abort command. I also removed unnecessary calls to finish() during media sync, and added another check during the main file fetching loop to improve the cancellation speed during media sync.

Closes #4512 

@dae

### CODE REVIEW

**Comment by timrae** [comment]
@dae
Are you happy with this implementation with the optional boolean argument in `finish()`? There are several different ways we could do it, but we should merge into upstream libanki so I feel it should be your call.

**Comment by dae** [comment]
I did it with a separate method to emphasise the difference to finish, but it's not a big deal if overriding finish is easier in the AnkiDroid code.

https://github.com/dae/anki/commit/03b2ad37d9754640e9e1998e4227a918cd630116

**Comment by timrae** [comment]
@dae
Thanks for the link. Nah, let's do it properly... I've pushed a more clear version.

@hssm 
Do you have time to test this?

File: AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteServer.java [hunk 1]
```diff
@@ -73,60 +73,72 @@ public HttpResponse meta() throws UnknownHttpResponseException {
...
 
-
     @Override
     public long finish() throws UnknownHttpResponseException {
+        return parseLong(_run("finish", new JSONObject()));
+    }
+
+    @Override
+    public long abort() throws UnknownHttpResponseException {
+        return parseLong(_run("abort", new JSONObject()));
```
Comment (dae) [inline AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteServer.java]: abort doesn't modify the mod time, so there's no value to return. it's probably returning None encoded as json (null), but as long as you get a 200 reply the command succeeded

Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteServer.java]: Ah ok thanks, fixed

File: AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteServer.java [hunk 2]
```diff
@@ -73,60 +73,72 @@ public HttpResponse meta() throws UnknownHttpResponseException {
...
         JSONObject co = new JSONObject();
-        return _run("chunk", co);
+        return parseDict(_run("chunk", co));
     }
 
 
     @Override
     public void applyChunk(JSONObject sech) throws UnknownHttpResponseException {
-        _run("applyChunk", sech);
+        parseDict(_run("applyChunk", sech));
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteServer.java]: @dae
Is the call to `parseDict()` actually necessary here? Or do we need to inspect the return value?

Comment (dae) [inline AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteServer.java]: The return value can be ignored

https://github.com/dae/anki/blob/master/anki/sync.py#L177

**Comment by hssm** [comment]
After I canceled a sync, successive attempts at syncing are rejected by the server: `Please use the latest AnkiDroid to continue syncing.` It's been over 10 minutes since the first cancellation.

**Comment by timrae** [comment]
Any log file output?

**Comment by hssm** [comment]
```
12-29 09:15:59.616 19452-19506/com.ichi2.anki I/Connection: Sync - starting sync
12-29 09:16:01.783 19452-19506/com.ichi2.anki I/Syncer: Sync: getting meta data from server
12-29 09:16:01.785 19452-19506/com.ichi2.anki D/Collection: [1482963361] Syncer.java:sync(): rmeta,  {"scm":0,"cont":false,"musn":0,"usn":0,"ts":0,"uname":"","msg":"Please use the latest AnkiDroid to continue syncing.","mod":0}
```

My account seems to be stuck in this state now.

**Comment by timrae** [comment]
Try again now

**Comment by hssm** [comment]
Seems to be fine now.

**Comment by timrae** [comment]
Thanks, I think I was missing the gawk package when I last ran the release script which screwed up the version string. I did my testing before rebasing onto develop, sorry about that.

I'll release a new alpha after work tonight
