### PR TITLE
display languages in preferences using their own language

### LINKED ISSUE #6251: Language settings should be displayed in their own language.
###### Reproduction Steps

1. Go to Settings -> AnkiDroid -> language

###### Expected Result

Different languages' names should be displayed in their own language. 
It is possible to set a wrong language. Display languages' names in their own language can help user to change language in an unfamiliar environment.

###### Actual Result

Different languages' names are shown in the same language.

###### Debug info
Android Version = 7.0
AnkiDroid Version = 2.10alpha

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by Arthus**
sort languages alphabetically, ignoring upper/lower case

add comment on exception handler

## Purpose / Description
Make each language show up in the preference's list in their own language, sorted alphabetically. Also adds a comment for PR #6138 that was merged a little bit quick. :)

## Fixes
Fixes #6251 
Also supersedes/closes #6252 

## Approach
Gets the display name of each locale, localized with itself.
Changes TreeMap <String, String> to TreeMap <String, List<String>> and change the way the data is stored, so it automatically gets sorted correctly.

## How Has This Been Tested?

Compiled and tested in emulators, APIs 28 and 16. Works

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java [hunk 1]
```diff
@@ -810,22 +810,25 @@ private String replaceStringIfNumeric(String str, String value) {
...
+            Map<String, List<String>> items = new TreeMap<>();
             for (String localeCode : LanguageUtil.APP_LANGUAGES) {
                 Locale loc = LanguageUtil.getLocale(localeCode);
-                items.put(loc.getDisplayName(currentAppLocale), loc.toString());
+                //TreeMap always sorted by key.
+                //      Key is a String: all display names converted to lower case for correct display order.
+                //      Value is list of 2 strings:
+                //          1st element is display name with unmodified case
+                //          2nd element is locale code
+                items.put(loc.getDisplayName(loc).toLowerCase(), Arrays.asList(loc.getDisplayName(loc), loc.toString()));
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java:822]: Beware of `Arrays.asList`. It returns an implementation of `List` where calling `add` will crash. This is fine, but for future reference.

File: AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java [hunk 2]
```diff
@@ -810,22 +810,25 @@ private String replaceStringIfNumeric(String str, String value) {
 
     private void initializeLanguageDialog(PreferenceScreen screen) {
         ListPreference languageSelection = (ListPreference) screen.findPreference(LANGUAGE);
-        Locale currentAppLocale = LanguageUtil.getLocale(AnkiDroidApp.getSharedPrefs(AnkiDroidApp.getInstance())
-                .getString(Preferences.LANGUAGE, ""));
         if (languageSelection != null) {
-            Map<String, String> items = new TreeMap<>();
+            Map<String, List<String>> items = new TreeMap<>();
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java:814]: I think this will work, and will allow you to reduce complexity further down:

`Map<String, String>`: 

`new TreeMap(String.CASE_INSENSITIVE_ORDER);`

Comment (Arthus) [reply AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java]: Well, this is oviously the even simpler solution and also makes the List<String> part unnecessary, so implemented.

**Comment by mikehardy** [comment]
This will be a big help to me as I work through #6256 - with ability to switch languages easily in testing, supporting the languages as a maintainer is much easier, thanks

**Comment by mikehardy** [comment]
Finally got a chance to fix 3-letter language codes and as expected, this PR was huge. Made it trivial to test. Thanks so much for doing this!
