### PR TITLE
fix(card viewers+anki pages): onRenderProcessGone

### LINKED ISSUE #15695: [Bug] OnRenderProcessGone is not handled by Anki Desktop WebViews
`[FATAL:crashpad_client_linux.cc(745)] Render process (6903)'s crash wasn't handled by all associated  webviews, triggering application crash.`

* samsung a02q (Galaxy A02s)
* Android 12 (SDK 31)
* Version: 121701300 (2.17.1)

```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 6824 >>> com.ichi2.anki <<<

backtrace:
  #00  pc 0x00000000026f2c44  /data/app/~~nIabJGklkL2XhnxMyPPoTA==/com.google.android.trichromelibrary_616717830--WVNBIaQFGowESE3DVAbLw==/base.apk!libmonochrome.so (BuildId: db06232df52ca789848a2727c27680f63b243c65)
  #01  pc 0x00000000035cdf61  /data/app/~~nIabJGklkL2XhnxMyPPoTA==/com.google.android.trichromelibrary_616717830--WVNBIaQFGowESE3DVAbLw==/base.apk!libmonochrome.so (BuildId: db06232df52ca789848a2727c27680f63b243c65)
  #02  pc 0x0000000000c5b44f  /data/app/~~nIabJGklkL2XhnxMyPPoTA==/com.google.android.trichromelibrary_616717830--WVNBIaQFGowESE3DVAbLw==/base.apk!libmonochrome.so (BuildId: db06232df52ca789848a2727c27680f63b243c65)
  #03  pc 0x0000000002636ea3  /data/app/~~nIabJGklkL2XhnxMyPPoTA==/com.google.android.trichromelibrary_616717830--WVNBIaQFGowESE3DVAbLw==/base.apk!libmonochrome.so (BuildId: db06232df52ca789848a2727c27680f63b243c65)
  #04  pc 0x00000000026345d3  /data/app/~~nIabJGklkL2XhnxMyPPoTA==/com.google.android.trichromelibrary_616717830--WVNBIaQFGowESE3DVAbLw==/base.apk!libmonochrome.so (BuildId: db06232df52ca789848a2727c27680f63b243c65)
  #05  pc 0x0000000001b2ba91  /data/app/~~nIabJGklkL2XhnxMyPPoTA==/com.google.android.trichromelibrary_616717830--WVNBIaQFGowESE3DVAbLw==/base.apk!libmonochrome.so (BuildId: db06232df52ca789848a2727c27680f63b243c65)
  #06  pc 0x0000000002ec9925  /data/app/~~nIabJGklkL2XhnxMyPPoTA==/com.google.android.trichromelibrary_616717830--WVNBIaQFGowESE3DVAbLw==/base.apk!libmonochrome.so (BuildId: db06232df52ca789848a2727c27680f63b243c65)
  #07  pc 0x0000000002ec98f7  /data/app/~~nIabJGklkL2XhnxMyPPoTA==/com.google.android.trichromelibrary_616717830--WVNBIaQFGowESE3DVAbLw==/base.apk!libmonochrome.so (BuildId: db06232df52ca789848a2727c27680f63b243c65)
  #08  pc 0x00000000000102e5  /system/lib/libutils.so (android::Looper::pollInner(int)+700)
  #09  pc 0x000000000000ffcf  /system/lib/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+62)
  #10  pc 0x00000000000e6f53  /system/lib/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long long, int)+24)
  #11  pc 0x0000000000422a17  /data/misc/apexdata/com.android.art/dalvik-cache/arm/boot.oat (art_jni_trampoline+78)
  #12  pc 0x0000000000d709bb  /data/misc/apexdata/com.android.art/dalvik-cache/arm/boot.oat (android.os.MessageQueue.next+266)
  #13  pc 0x0000000000d6ccbb  /data/misc/apexdata/com.android.art/dalvik-cache/arm/boot.oat (android.os.Looper.loopOnce+74)
  #14  pc 0x0000000000d6cb63  /data/misc/apexdata/com.android.art/dalvik-cache/arm/boot.oat (android.os.Looper.loop+1034)
  #15  pc 0x0000000000a9ad8b  /data/misc/apexdata/com.android.art/dalvik-cache/arm/boot.oat (android.app.ActivityThread.main+1282)
  #16  pc 0x00000000003bd1d5  /apex/com.android.art/lib/libart.so (art_quick_invoke_stub_internal+68)
  #17  pc 0x00000000002cc731  /apex/com.android.art/lib/libart.so (void art::quick_invoke_reg_setup<true>(art::ArtMethod*, unsigned int*, unsigned int, art::Thread*, art::JValue*, char const*) (.__uniq.192663596067446536341070919852553954320.llvm.16200230356545185596)+260)
  #18  pc 0x000000000028a4f3  /apex/com.android.art/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+182)
  #19  pc 0x0000000000313969  /apex/com.android.art/lib/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*) (.__uniq.245181933781456475607640333933569312899.llvm.2586733929373010981)+40)
  #20  pc 0x0000000000351425  /apex/com.android.art/lib/libart.so (_jobject* art::InvokeMethod<(art::PointerSize)4>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned int)+372)
  #21  pc 0x00000000004d8e5d  /apex/com.android.art/lib/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*) (.__uniq.165753521025965369065708152063621506277)+40)
  #22  pc 0x0000000000410db1  /data/misc/apexdata/com.android.art/dalvik-cache/arm/boot.oat (art_jni_trampoline+56)
  #23  pc 0x0000000001106117  /data/misc/apexdata/com.android.art/dalvik-cache/arm/boot.oat (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+118)
  #24  pc 0x0000000001111417  /data/misc/apexdata/com.android.art/dalvik-cache/arm/boot.oat (com.android.internal.os.ZygoteInit.main+2638)
  #25  pc 0x00000000003bd1d5  /apex/com.android.art/lib/libart.so (art_quick_invoke_stub_internal+68)
  #26  pc 0x00000000002cc731  /apex/com.android.art/lib/libart.so (void art::quick_invoke_reg_setup<true>(art::ArtMethod*, unsigned int*, unsigned int, art::Thread*, art::JValue*, char const*) (.__uniq.192663596067446536341070919852553954320.llvm.16200230356545185596)+260)
  #27  pc 0x000000000028a4f3  /apex/com.android.art/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+182)
  #28  pc 0x0000000000313969  /apex/com.android.art/lib/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*) (.__uniq.245181933781456475607640333933569312899.llvm.2586733929373010981)+40)
  #29  pc 0x000000000038818d  /apex/com.android.art/lib/libart.so (art::JValue art::InvokeWithVarArgs<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, std::__va_list)+176)
  #30  pc 0x00000000002b7e4b  /apex/com.android.art/lib/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+42)
  #31  pc 0x00000000004a5f1b  /apex/com.android.art/lib/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+74)
  #32  pc 0x000000000007882d  /system/lib/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+28)
  #33  pc 0x0000000000081cc1  /system/lib/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+608)
  #34  pc 0x000000000000253f  /system/bin/app_process32 (main+978)
  #35  pc 0x000000000005e5c5  /apex/com.android.runtime/lib/bionic/libc.so (__libc_init+56)
```

### PR DESCRIPTION
**Pull request by BrayanDSO**
## Fixes
* Fixes #15695

#17486 wasn't fixed as well because its setup is less straightforward, and errors should less frequent there.

## Approach

1. Create the new SafeWebViewClient and SafeWebViewLayout class to serve as base to handling onRenderProcessGone. It forces the developer to implement a listener to handle the crashes
2. Recreate and setup the WebView after any crashes

## How Has This Been Tested?

Manually added the following patch to the fragments' onViewCreated method:

```patch
Subject: [PATCH] fix(anki pages): don't crash after onRenderProcessGone

tested with the following patch:

```patch
Subject: [PATCH] testing
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerFragment.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerFragment.kt b/AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerFragment.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerFragment.kt	(revision a3e86d739bf9049cd6673076a1ec5bb2beeac4ee)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerFragment.kt	(date 1762546566117)
@@ -37,6 +37,7 @@
 import com.ichi2.anki.R
 import com.ichi2.anki.ViewerResourceHandler
 import com.ichi2.anki.dialogs.TtsVoicesDialogFragment
+import com.ichi2.anki.launchCatchingTask
 import com.ichi2.anki.localizedErrorMessage
 import com.ichi2.anki.snackbar.showSnackbar
 import com.ichi2.anki.utils.ext.collectIn
@@ -48,6 +49,7 @@
 import com.ichi2.compat.CompatHelper.Companion.resolveActivityCompat
 import com.ichi2.themes.Themes
 import com.ichi2.utils.show
+import kotlinx.coroutines.delay
 import kotlinx.coroutines.flow.launchIn
 import kotlinx.coroutines.flow.onEach
 import timber.log.Timber
@@ -69,6 +71,13 @@
         viewModel.eval.collectIn(lifecycleScope) { eval ->
             webViewLayout.evaluateJavascript(eval)
         }
+
+        launchCatchingTask {
+            (0..2).forEach { _ ->
+                delay(3000)
+                webViewLayout.loadUrl("chrome://crash")
+            }
+        }
     }
 
     override fun onStart() {
Index: AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt b/AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt	(revision a3e86d739bf9049cd6673076a1ec5bb2beeac4ee)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt	(date 1762546610210)
@@ -31,9 +31,11 @@
 import com.google.android.material.progressindicator.CircularProgressIndicator
 import com.ichi2.anki.R
 import com.ichi2.anki.SingleFragmentActivity
+import com.ichi2.anki.launchCatchingTask
 import com.ichi2.anki.workarounds.OnWebViewRecreatedListener
 import com.ichi2.anki.workarounds.SafeWebViewLayout
 import com.ichi2.themes.Themes
+import kotlinx.coroutines.delay
 import timber.log.Timber
 import kotlin.reflect.KClass
 
@@ -118,6 +120,13 @@
         }
 
         setupWebView(savedInstanceState)
+
+        launchCatchingTask {
+            (0..2).forEach { _ ->
+                delay(3000)
+                webViewLayout.loadUrl("chrome://crash")   
+            }
+        }
     }
 
     private fun setupWebView(savedInstanceState: Bundle?) {
```

[Screen_recording_20251107_111839.webm](https://github.com/user-attachments/assets/86206608-f877-43f3-bfd4-44e2f0bd1278)

[Screen_recording_20251107_112146.webm](https://github.com/user-attachments/assets/eaf7636f-3d56-473c-96a3-e6eea9032736)

[Screen_recording_20251107_112335.webm](https://github.com/user-attachments/assets/d43a17ba-2a0b-44e1-9ead-35b4b8344981)

[Screen_recording_20251107_112016.webm](https://github.com/user-attachments/assets/f58cecd1-c382-41c9-a137-c269bd6437f0)

[Screen_recording_20251107_111955.webm](https://github.com/user-attachments/assets/1dbc2c3a-9934-4f50-9fa8-eab82fe0819e)

[Screen_recording_20251107_124513.webm](https://github.com/user-attachments/assets/582f0661-caf0-47fd-b6bd-185a8076e634)

[Screen_recording_20251107_124500.webm](https://github.com/user-attachments/assets/0e5d5d72-58d5-4883-a429-71b9d927a04c)

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerFragment.kt [hunk 1]
```diff
@@ -89,7 +91,24 @@ abstract class CardViewerFragment(
             nightMode = Themes.currentTheme.isNightMode,
         )
 
-    private fun setupWebView(savedInstanceState: Bundle?) {
+    private fun createWebView(savedInstanceState: Bundle?) {
+        val context = context ?: return
+        webView =
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerFragment.kt]: The alternate would be to define our own `WebView` and use this in the layouts

I suspect architecturally this would be better, BUT I think this is just a post-hoc thought and definitley don't want to derail the PR over it

**Review by david-allison — COMMENTED** [review]
Does this reset the 'onBackPressed' delegates if the WebView is recreated (For example: Deck Options => opening a popup/manual)

File: AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerFragment.kt (hunk 1 above)
Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerFragment.kt]: > and use this in the layouts

it would still be necessary to have a programmatic way of creating an WebView in `onRenderProcessGone` and adding it to the view hierarchy, so a similar method would persist (unless the container layout was re-inflated, but I don't think that's a better approach). 

I'm not sure if it would be actually be cleaner to have some kind of `SafeWebView` class. I guess that it would be something similar, but not strictly better.

**Comment by BrayanDSO** [comment]
> Does this reset the 'onBackPressed' delegates if the WebView is recreated (For example: Deck Options => opening a popup/manual)

Works fine here (crash delayed in 10s)

[Screen_recording_20251107_135024.webm](https://github.com/user-attachments/assets/5cec5af6-f360-4941-82f1-b46e00781e11)

File: AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerFragment.kt (hunk 1 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerFragment.kt]: Could be done as a container element which creates the WebView

But... let's shelve this, I don't think I'm being constructive, and I want this in

**Comment by david-allison** [comment]
```
SafeWebViewClient       com.ichi2.anki.debug                 W  onRenderProcessGone (didCrash true)
AndroidRuntime          com.ichi2.anki.debug                 D  Shutting down VM
AndroidRuntime          com.ichi2.anki.debug                 E  FATAL EXCEPTION: main
                                     Process: com.ichi2.anki.debug, PID: 14483
                                     java.lang.IllegalStateException: Fragment DeckOptions{d463a2f} (0b213ab3-b042-49df-b333-4928ecfabe3a) not attached to an activity.
                                     	at androidx.fragment.app.Fragment.requireActivity(Fragment.java:1005)
                                     	at com.ichi2.anki.pages.DeckOptions.onCreateWebViewClient(DeckOptions.kt:171)
                                     	at com.ichi2.anki.pages.PageFragment.setupWebView(PageFragment.kt:141)
                                     	at com.ichi2.anki.pages.PageFragment.onRenderProcessGone(PageFragment.kt:187)
                                     	at com.ichi2.anki.workarounds.SafeWebViewClient.onRenderProcessGone(SafeWebViewClient.kt:38)
                                     	at org.chromium.android_webview.AwContents.onRenderProcessGone(chromium-TrichromeWebViewGoogle6432.apk-stable-541412334:43)
                                     	at android.os.MessageQueue.nativePollOnce(Native Method)
                                     	at android.os.MessageQueue.next(MessageQueue.java:335)
                                     	at android.os.Looper.loopOnce(Looper.java:161)
                                     	at android.os.Looper.loop(Looper.java:288)
                                     	at android.app.ActivityThread.main(ActivityThread.java:7924)
                                     	at java.lang.reflect.Method.invoke(Native Method)
                                     	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
ThrowableFilterService  com.ichi2.anki.debug                 V  exceptionIsUnwanted - examining IllegalStateException
ThrowableFilterService  com.ichi2.anki.debug                 V  exceptionIsUnwanted - exception was wanted
UsageAnalytics          com.ichi2.anki.debug                 D  sendAnalyticsException() description/fatal: java.lang.IllegalStateException: Fragment DeckOptions{d463a2f} (0b213ab3-b042-49df-b333-4928ecfabe3a) not attached to an activity./true
rsdroid                 com.ichi2.anki.debug                 D  rsdroid::logging: STDOUT: [1107/170837.697977:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
rsdroid                 com.ichi2.anki.debug                 D  rsdroid::logging: STDOUT: [1107/170837.699153:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
rsdroid                 com.ichi2.anki.debug                 D  rsdroid::logging: STDOUT: [1107/170837.699695:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
rsdroid                 com.ichi2.anki.debug                 D  rsdroid::logging: STDOUT: [1107/170837.700369:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
rsdroid                 com.ichi2.anki.debug                 D  rsdroid::logging: STDOUT: [1107/170837.701076:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
rsdroid                 com.ichi2.anki.debug                 D  rsdroid::logging: STDOUT: [1107/170837.701701:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
rsdroid                 com.ichi2.anki.debug                 D  rsdroid::logging: STDOUT: [1107/170837.702272:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
rsdroid                 com.ichi2.anki.debug                 D  rsdroid::logging: STDOUT: [1107/170837.703046:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
rsdroid                 com.ichi2.anki.debug                 D  rsdroid::logging: STDOUT: [1107/170837.703591:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
rsdroid                 com.ichi2.anki.debug                 D  rsdroid::logging: STDOUT: [1107/170837.704188:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
rsdroid                 com.ichi2.anki.debug                 D  rsdroid::logging: STDOUT: [1107/170837.704646:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
rsdroid                 com.ichi2.anki.debug                 D  rsdroid::logging: STDOUT: [1107/170837.704969:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
rsdroid                 com.ichi2.anki.debug                 D  rsdroid::logging: STDOUT: [1107/170837.705643:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
rsdroid                 com.ichi2.anki.debug                 D  rsdroid::logging: STDOUT: [1107/170837.706156:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
rsdroid                 com.ichi2.anki.debug                 D  rsdroid::logging: STDOUT: [1107/170837.706697:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
rsdroid                 com.ichi2.anki.debug                 D  rsdroid::logging: STDOUT: [1107/170837.707252:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
rsdroid                 com.ichi2.anki.debug                 D  rsdroid::logging: STDOUT: [1107/170837.707947:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
rsdroid                 com.ichi2.anki.debug                 D  rsdroid::logging: STDOUT: [1107/170837.708506:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
rsdroid                 com.ichi2.anki.debug                 D  rsdroid::logging: STDOUT: [1107/170837.709066:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
rsdroid                 com.ichi2.anki.debug                 D  rsdroid::logging: STDOUT: [1107/170837.709576:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
rsdroid                 com.ichi2.anki.debug                 D  rsdroid::logging: STDOUT: [1107/170837.710166:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
rsdroid                 com.ichi2.anki.debug                 D  rsdroid::logging: STDOUT: [1107/170837.710654:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
rsdroid                 com.ichi2.anki.debug                 D  rsdroid::logging: STDOUT: [1107/170837.711340:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
rsdroid                 com.ichi2.anki.debug                 D  rsdroid::logging: STDOUT: [1107/170837.712006:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
rsdroid                 com.ichi2.anki.debug                 D  rsdroid::logging: STDOUT: [1107/170837.712477:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
rsdroid                 com.ichi2.anki.debug                 D  rsdroid::logging: STDOUT: [1107/170837.712968:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
rsdroid                 com.ichi2.anki.debug                 D  rsdroid::logging: STDOUT: [1107/170837.713506:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
rsdroid                 com.ichi2.anki.debug                 D  rsdroid::logging: STDOUT: [1107/170837.714010:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Permission denied (13)
rsdroid                 com.ichi2.anki.debug                 D  rsdroid::logging: STDOUT: [1107/170837.733028:ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: Permission denied (13)
rsdroid                 com.ichi2.anki.debug                 D  rsdroid::logging: STDOUT: [1107/170837.733473:ERROR:ptrace_client.cc(363)] Broker Open: access denied
rsdroid                 com.ichi2.anki.debug                 D  rsdroid::logging: STDOUT: [1107/170837.883674:ERROR:socket.cc(182)] incorrect payload size 0
rsdroid                 com.ichi2.anki.debug                 D  rsdroid::logging: STDOUT: [ERROR:aw_browser_terminator.cc(156)] Renderer process (14719) crash detected (code 11).
ACRA                    com.ichi2.anki.debug                 E  ACRA caught a IllegalStateException for com.ichi2.anki.debug
                                     java.lang.IllegalStateException: Fragment DeckOptions{d463a2f} (0b213ab3-b042-49df-b333-4928ecfabe3a) not attached to an activity.
                                     	at androidx.fragment.app.Fragment.requireActivity(Fragment.java:1005)
                                     	at com.ichi2.anki.pages.DeckOptions.onCreateWebViewClient(DeckOptions.kt:171)
                                     	at com.ichi2.anki.pages.PageFragment.setupWebView(PageFragment.kt:141)
                                     	at com.ichi2.anki.pages.PageFragment.onRenderProcessGone(PageFragment.kt:187)
                                     	at com.ichi2.anki.workarounds.SafeWebViewClient.onRenderProcessGone(SafeWebViewClient.kt:38)
                                     	at org.chromium.android_webview.AwContents.onRenderProcessGone(chromium-TrichromeWebViewGoogle6432.apk-stable-541412334:43)
                                     	at android.os.MessageQueue.nativePollOnce(Native Method)
                                     	at android.os.MessageQueue.next(MessageQueue.java:335)
                                     	at android.os.Looper.loopOnce(Looper.java:161)
                                     	at android.os.Looper.loop(Looper.java:288)
                                     	at android.app.ActivityThread.main(ActivityThread.java:7924)
                                     	at java.lang.reflect.Method.invoke(Native Method)
                                     	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
AnkiActivity            com.ichi2.anki.debug                 I  finishWithAnimation DEFAULT
```

**Comment by BrayanDSO** [comment]
Lovely. What are the reproduction steps?

**Comment by david-allison** [comment]
Trying for exact reproduction steps, I'm unsure what's going on here; I'm seeing fatal errors from crashes not being handled properly.

```patch
Subject: [PATCH] testing
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt b/AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt	(revision 9733855248576c12fa76e985122956bf14a4534c)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/pages/PageFragment.kt	(date 1762535135126)
@@ -32,8 +32,10 @@
 import com.google.android.material.progressindicator.CircularProgressIndicator
 import com.ichi2.anki.R
 import com.ichi2.anki.SingleFragmentActivity
+import com.ichi2.anki.launchCatchingTask
 import com.ichi2.anki.workarounds.OnRenderProcessGoneListener
 import com.ichi2.themes.Themes
+import kotlinx.coroutines.delay
 import timber.log.Timber
 import kotlin.reflect.KClass
 
@@ -129,6 +131,10 @@
         }
 
         setupWebView(savedInstanceState)
+        launchCatchingTask {
+            delay(3000)
+            webView?.loadUrl("chrome://crash")
+        }
     }
 
     private fun setupWebView(savedInstanceState: Bundle?) {
Index: AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerFragment.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerFragment.kt b/AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerFragment.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerFragment.kt	(revision 9733855248576c12fa76e985122956bf14a4534c)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/previewer/CardViewerFragment.kt	(date 1762535135133)
@@ -39,6 +39,7 @@
 import com.ichi2.anki.R
 import com.ichi2.anki.ViewerResourceHandler
 import com.ichi2.anki.dialogs.TtsVoicesDialogFragment
+import com.ichi2.anki.launchCatchingTask
 import com.ichi2.anki.localizedErrorMessage
 import com.ichi2.anki.snackbar.showSnackbar
 import com.ichi2.anki.utils.ext.collectIn
@@ -49,6 +50,7 @@
 import com.ichi2.compat.CompatHelper.Companion.resolveActivityCompat
 import com.ichi2.themes.Themes
 import com.ichi2.utils.show
+import kotlinx.coroutines.delay
 import kotlinx.coroutines.flow.launchIn
 import kotlinx.coroutines.flow.onEach
 import timber.log.Timber
@@ -68,6 +70,10 @@
     ) {
         createWebView(savedInstanceState)
         setupErrorListeners()
+        launchCatchingTask {
+            delay(3000)
+            webView?.loadUrl("chrome://crash")
+        }
     }
 
     override fun onStart() {
```

Is the WebView being disposed properly before a new WebView instance is created (and when the screen is closed)

API 33 emulator 9733855248576c12fa76e985122956bf14a4534c

* Tap the deck counts
* Open Deck Options
* Wait
* ... 
* Screen closes, rather than the WebView being reloaded

OR the WebView is reloaded

----

* Tap the deck counts
* Open Deck Options
* Tap the (?) to open help for the daily limits
* Wait 3 seconds
* ... 
* Crash

----

```
17:14:45.591 16791-16791 chromium                 A  [FATAL:crashpad_client_linux.cc(730)] Render process (16824)'s crash wasn't handled by all associated  webviews, triggering application crash.
17:14:45.591 16791-16791 libc                     A  Fatal signal 5 (SIGTRAP), code 1 (TRAP_BRKPT), fault addr 0x74fa315024 in tid 16791 (chi2.anki.debug), pid 16791 (chi2.anki.debug)
```

**Comment by BrayanDSO** [comment]
Refactored to use the container approach. Thanks for the push!

I believe that the deck options issue is fixed as well.

File: AnkiDroid/src/main/java/com/ichi2/anki/workarounds/SafeWebViewLayout.kt [hunk 2]
```diff
@@ -0,0 +1,143 @@
...
+    override fun setOnScrollChangeListener(l: OnScrollChangeListener?) = webView.setOnScrollChangeListener(l)
+
+    override fun onRenderProcessGone(webView: WebView) {
+        removeView(webView)
+        webView.destroy()
+
+        this.webView = createWebView()
+        addView(this.webView, webViewLayoutParams)
+
+        val fragment = (findFragment<Fragment>() as? OnWebViewRecreatedListener)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/workarounds/SafeWebViewLayout.kt]: Can we improve this so it will throw unconditionally if it's in a bad state in debug mode (fragment is not `OnWebViewRecreatedListener`), rather than only in an error state.

File: AnkiDroid/src/main/java/com/ichi2/anki/workarounds/SafeWebViewLayout.kt [hunk 3]
```diff
@@ -0,0 +1,143 @@
...
+    companion object {
+        private val webViewLayoutParams =
+            ViewGroup.LayoutParams(
+                LayoutParams.MATCH_PARENT,
+                LayoutParams.MATCH_PARENT,
+            )
+    }
+}
+
+interface OnWebViewRecreatedListener {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/workarounds/SafeWebViewLayout.kt]: Probably [`fun interface`](https://kotlinlang.org/docs/fun-interfaces.html)

File: AnkiDroid/src/main/java/com/ichi2/anki/workarounds/SafeWebViewLayout.kt (hunk 2 above)
Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/anki/workarounds/SafeWebViewLayout.kt]: Not sure if I understood it completely, but I think I've managed to do it in the last force push

File: AnkiDroid/src/main/java/com/ichi2/anki/workarounds/SafeWebViewLayout.kt [hunk 4]
```diff
@@ -0,0 +1,144 @@
...
+        removeView(webView)
+        webView.destroy()
+
+        this.webView = createWebView()
+        addView(this.webView, webViewLayoutParams)
+
+        val fragment = findFragment<Fragment>()
+        if (fragment !is OnWebViewRecreatedListener) {
+            if (BuildConfig.DEBUG) {
+                throw IllegalStateException("Fragment must implement OnWebViewRecreatedListener")
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/workarounds/SafeWebViewLayout.kt]: To rephrase:

This only throws in exceptional circumstances. Most interactions in debug mode will not trigger `onRenderProcessGone`

In Debug mode, is it feasible to check that the fragment is correct unconditionally, rather than inside `onRenderProcessGone`
