### PR TITLE
fix(browser): update title on deck creation

### LINKED ISSUE #15577: [Bug] Browser's deck spinner title isn't correctly updated
###### Reproduction Steps

https://github.com/ankidroid/Anki-Android/assets/69634269/e8bae304-dccc-4d5e-bf59-7c289c644aa8

###### Expected Result

The ab deck should have its name shown in the spinner title

###### Actual Result

It isn't

###### Debug info

S23, Android 14, built with main (2.17beta5)

### PR DESCRIPTION
**Pull request by david-allison**
## Fixes
* Fixes #15577

## Approach
Define `DeckSelectionDialog.deckCreationListener` and handle the change internally so the adapter doesn't need an external rebuild

## How Has This Been Tested?
Selected a deck, double selected a deck, selected a different deck
created a deck

## Learning
Everything about this is eww

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.kt [hunk 1]
```diff
@@ -206,9 +206,17 @@ class DeckSpinnerSelection(
             decks.add(SelectableDeck(ALL_DECKS_ID, context.resources.getString(R.string.card_browser_all_decks)))
         }
         val dialog = DeckSelectionDialog.newInstance(context.getString(R.string.search_deck), null, false, decks)
+        // TODO: retain state after onDestroy
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.kt:209]: Open to suggestions here

**Review by mikehardy — APPROVED** [review]
That's a lot of motion to re-add a line - it all seems reasonable but it's a little 😬 while hoping to go rc
