### PR TITLE
Gracefully handle WebView Crashes

### LINKED ISSUE #5780: Soft crash to decklist during reviews.
Every day when I review my deck, I get a "soft crash" where I get dumped back to the deck list. When this happens, the "new cards" also resets, so I get 5 more new cards for that day, even if I went through my 5 for the day.

This happens every day, so I should be able to capture this behaviour while logging or something, if neeed.

###### Reproduction Steps

1. Review cards
2. Until crash
3. The end

###### Expected Result

Complete reviews as normal

###### Actual Result

As noted above, I crash back to the deck list.

###### Debug info
AnkiDroid Version = 2.10alpha41

Android Version = 10

ACRA UUID = e2ba917d-92ec-4989-9467-4b211c9f2952

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

Edit: This bug was present at the latest version on Play Store as well.

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description
Out of Memory issues in the WebView Renderer (e.g. large fonts) were causing the application to crash and restart, going to the deck browser. This was listed as a soft crash in the bug report, but was actually killing the PID.

If a card fails once, we reset the WebView and try to render the card again.

If a card has not been rendered, or if the same card fails twice, we fail gracefully and return to the deck browser. We show a Toast to the user explaining that an OOM occurred.

## Fixes
Fixes #5780

## Approach

We catch the OOM using `onRenderProcessGone()` (API >= 26) and recreate the WebView to allow the application to continue with minor disruption.

## How Has This Been Tested?

Locally on my Android device (Android 9). Placing `crashWebViewRenderer()` inside `displayCardAnswer()`

* A single failure recreates the WebView
* A second failure on the same card takes the user to the Deck Browser.
* A failure on a different card recreates the WebView.

## Learning (optional, can help others)

StackOverflow example: https://stackoverflow.com/questions/46737984/onrenderprocessgonewebview-view-renderprocessgonedetail-detail-example

API: https://developer.android.com/reference/android/webkit/WebViewClient#onRenderProcessGone(android.webkit.WebView,%20android.webkit.RenderProcessGoneDetail)

https://developer.android.com/guide/webapps/managing-webview#termination-handle

## Checklist

- [ x ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ x ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ x ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ x ] You have commented your code, particularly in hard-to-understand areas
- [ x ] You have performed a self-review of your own code

## Review Goals

* I'm unfamiliar with internationalisation. May have screwed up
* Do we need to do anything more to handle lower API levels?
* `inflateNewView` - doesn't feel like good code.
* We currently use Toasts because they're easy, but they don't stay on the screen for long or have much room.
* lastCrashingCardId - may not be a perfect test.
* We only report the failing card ID to the user. We could do better (not sure if out of scope).

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 1]
```diff
@@ -1541,12 +1554,107 @@ public void onPageFinished(WebView view, String url) {
...
+
+            /** Fix: #5780 - WebView Renderer OOM crashes reviewer */
+            @Override
+            @TargetApi(Build.VERSION_CODES.O)
+            public boolean onRenderProcessGone(WebView view, RenderProcessGoneDetail detail) {
+
+                if (mCard == null || !mCard.equals(view)) {
+                    //A view crashed that wasn't ours. Unexpected.
+                    Timber.wtf("Unexpected WebView Renderer terminated. Crashed: %b",  detail.didCrash());
+                    return false;
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java]: "The application's implementation of this callback should only attempt to clean up the specific WebView given as a parameter, and should not assume that other WebView instances are affected" doesn't that mean that we can return true? And the right log level would be information?

**Comment by mikehardy** [comment]
Wow, this is great - the re-render attempt is a nice touch.
- I18N looks fine
- I am sad it is API26 and higher only but at least Android upgrades are becoming more common, and this covers as many as is possible anyway, can only do what we can do. I'm not aware of any API that covers lower versions though this might be where trying to figure out why the reviews were showing up as new again as interesting, under API26 this will keep happening
- inflateNewView does seem a little chewy but in the absence of better ideas I have no problem with tested code that fixes WebView crashes since that's definitely our #1 crash at this point
- we have a choice of Toasts (long or short), Snackbars, and Dialogs. A long toast actually does hang around for a while, and I think if someone has cards (or a device) where the WebView crashes they will see this repeatedly and a long toast might be good enough. I think you chose the long toast, so that works for me
- perhaps the last crash card id should be a member, persisted across Activity restarts (onSaveInstanceState etc) but otherwise the mechanism seems like a solid idea, but yes with care that we know the actual id the WebView crashed on, and know what card is loaded and is currently attempting to display

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java (hunk 1 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java]: You're correct. Anything that returns false will cause an issue. https://chromium.googlesource.com/chromium/src.git/+/62.0.3178.1/android_webview/browser/aw_browser_terminator.cc?autodive=0%2F%2F#72

**Comment by david-allison-1** [comment]
>  I'm not aware of any API that covers lower versions 

Likewise, it's a shame

>though this might be where trying to figure out why the reviews were showing up as new again as interesting, under API26 this will keep happening

I didn't see this when I studied.

Theory: New card data is stored in `col`, which is saved at a different time from `cards` (grep: `col.save()`). Crashing the application loses this data. I think new cards are more likely to have a backlog greater than the daily setting, whereas reviews, learnings and lapses typically provide all possible cards at once.

The effect would be that the "new cards studied today" count is reset, not that reviews are being lost/undone.

> we have a choice of Toasts (long or short), Snackbars, and Dialogs. A long toast actually does hang around for a while, and I think if someone has cards (or a device) where the WebView crashes they will see this repeatedly and a long toast might be good enough. I think you chose the long toast, so that works for me

Perfect! I chose a long toast, but the other options sound better.

I'd like to turn this into a `Dialog`, and display a short preview of the first few words of the first field of the card (obtained via `Spannable.fromHtml`, or the text used by the Card Browser). 

Will screenshot to confirm it's appropriate.

----

> perhaps the last crash card id should be a member, persisted across Activity restarts (onSaveInstanceState etc) but otherwise the mechanism seems like a solid idea, but yes with care that we know the actual id the WebView crashed on, and know what card is loaded and is currently attempting to display

Sounds solid at first thought.

**Comment by david-allison-1** [comment]
@mikehardy Coming back to this as my next priority. 

What's the git strategy with review comments?

Append + Squash merge, or should I rebase?

**Comment by david-allison-1** [comment]
Review comments should be fixed, except 

> perhaps the last crash card id should be a member, persisted across Activity restarts (onSaveInstanceState etc) but otherwise the mechanism seems like a solid idea, but yes with care that we know the actual id the WebView crashed on, and know what card is loaded and is currently attempting to display

I feel there's minimal value in this. If we're in a crash loop, it won't need user input to trigger. It seems like added complexity for 1 less iteration of the loop before crashing.

----

That all being said, say the word and I'll do it.

**Comment by mikehardy** [comment]
> @mikehardy Coming back to this as my next priority.

Yeah - you have a lot of plates spinning :)

> What's the git strategy with review comments?
> 
> Append + Squash merge, or should I rebase?


In general we want a squeaky clean commit history. So when I'm working on AnkiDroid stuff I'm always doing rebase HEAD~N, fixing things, and re-force-pushing. 

For final merge if the commit history is really clean (via the above strategy) I just rebase and merge, if it's messy I squash and merge

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 2]
```diff
@@ -1541,12 +1554,124 @@ public void onPageFinished(WebView view, String url) {
...
+                    UIUtils.showThemedToast(AbstractFlashcardViewer.this, errorMessage, false);
+                    finishWithoutAnimation();
+                    return true;
+                }
+
+                if (webViewRendererLastCrashedOnCard(mCurrentCard.getId())) {
+                    Timber.e("Web Renderer crash loop on card: %d", mCurrentCard.getId());
+                    displayRenderLoopDialog(mCurrentCard, detail);
+                    return true;
+                } else {
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java]: Since you return in the other branch of the if, the else seems unnecessary - I have a preference to not use an else in these cases. What I'd prefer is to have the logic that is in the else currently moved out (deleting the else) and a comment that positively asserts the state allowing us to continue executing, e.g. "If we got here, it's a recoverable crash and the first time on this card, attempt to re-display", followed by the logic

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 3]
```diff
@@ -1541,12 +1554,124 @@ public void onPageFinished(WebView view, String url) {
...
+        return lastCrashingCardId != null && lastCrashingCardId == cardId;
+    }
+
+
+    private boolean canRecoverFromWebViewRendererCrash() {
+        // DEFECT
+        // If we don't have a card to render, we're in a bad state. The class doesn't currently track state
+        // well enough to be able to know exactly where we are in the initialisation pipeline.
+        // so it's best to mark the crash as non-recoverable.
+        // We should fix this, but it's very unlikely that we'll ever get here. Logs will tell
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java]: Logs will only tell if you include a log, seems like a Timber.w might apply here as we *think* we can recover but it is unexpected / unwanted state?

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 4]
```diff
@@ -2026,6 +2155,7 @@ protected String cleanTypedAnswer(String answer) {
 
     protected void displayCardAnswer() {
         Timber.d("displayCardAnswer()");
+        crashWebViewRenderer();
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java]: I'm not sure you intend for this line to remain here? seems like it would crash any time we showed answer, and is likely just for local testing?

Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java]: 🤦‍♂

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java (hunk 3 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java]: Done at the call site

`Timber.e("Unrecoverable WebView Render crash");`

**Comment by mikehardy** [comment]
Excellent - just waiting on CI then. I'm obviously motivated by crash stats at the moment, the impact this PR should have on the stats should be incredible, even with just the higher APIs supporting it.

**Comment by david-allison-1** [comment]
@mikehardy Do you have a list of most impactful crash bugs? Would be great to power through these over the next week.

**Comment by mikehardy** [comment]
Honestly I will have to re-evaluate after this OOM fix, and the Custom Study Dialog fixes go out. It will take a week or so before I'm prepared to point at any issue now as I'm not sure there are any left that will have significant impact but it's hard to say. The last couple months has gotten almost all of them. 

If you really want to look at something impactful you might take on the zombiest issue of all time #1377 - a WYSIWYG editor mode. I'm sure there's a component for that somewhere (there *has* to be?) that can be bolted on? Not having the ability to do basic bold / underline / italic is a huge issue for many.

**Comment by mikehardy** [comment]
User report - success!

> I just got the update a little while earlier, while doing my usual routine it still seems like crashing sometimes like earlier, but then it doesn't really crash and resumes like normal just showing a pop-up in the lower part of the screen (webview renderer something, I didn't bother to actually write it up because I think you already know what it is), and most importantly my new cards never gets reset, it's basically normal operation with an hiccup here and there.
> Thanks again, from what I can see the bothersome part of this problem has been fixed!

**Comment by mikehardy** [comment]
Incidentally, this covers 58.6% of our userbase already (API26 / Android 8+)
