### PR TITLE
Make "Undo" item's title for whiteboard mode

### LINKED ISSUE #12960: [Bug] "Undo" item's title isn't switched to one for whiteboard mode
###### Reproduction Steps

1. Put "Undo" item on the action menu on Reviewer screen
image

2. Show the item in the form of "Undo _something_"
　e.g. "Undo Bury", "Undo Change Deck", "Undo Update Note"
image

3. Make one or more strokes on whiteboard mode
image

5. Show the action menu and see the "Undo" item

###### Expected Result
"Undo" item's title is switched to one for whiteboard mode.

###### Actual Result
"Undo" item's title isn't switched to one for whiteboard mode though its action itself and its icon are done.
image

https://user-images.githubusercontent.com/10436072/206903017-745aeaed-94ef-41b2-8fce-f60c38ce838c.mp4

###### Debug info
AnkiDroid Version = 2.16alpha91

Android Version = 11

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/107.0.5304.141 Mobile Safari/537.36

ACRA UUID = 69410480-0b9c-401f-ae8d-94da0f29c9dc

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by snowtimeglass**
## Purpose / Description
"Undo" item's title isn't switched to one for whiteboard mode though its action itself and its icon are done.
image

## Fixes
Fixes #12960

## Approach
Make a new string for "Undo" item's title for whiteboard mode

## How Has This Been Tested?
Checked on a physical device
image

https://user-images.githubusercontent.com/10436072/206904451-9fa0ca93-1b34-43e3-bbe7-a089d3039cbc.mp4

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt [hunk 1]
```diff
@@ -760,7 +760,11 @@ open class Reviewer : AbstractFlashcardViewer() {
         undoIcon.setEnabled(undoEnabled).iconAlpha = alphaUndo
         undoIcon.actionView!!.isEnabled = undoEnabled
         if (colIsOpen()) { // Required mostly because there are tests where `col` is null
-            if (col.undoAvailable()) {
+            if (mShowWhiteboard && whiteboard != null && whiteboard!!.isUndoModeActive) {
+                // We arrive here if whiteboard is shown and one or more strokes are retained
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt:764]: I only noticed after seeing the video that someone can only undo whiteboard actions if the whiteboard is active. Could you please add a comment explaining it here?

Comment (snowtimeglass) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt]: Thanks. Would these comments be okay?

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt [hunk 2]
```diff
@@ -760,7 +760,17 @@ open class Reviewer : AbstractFlashcardViewer() {
         undoIcon.setEnabled(undoEnabled).iconAlpha = alphaUndo
         undoIcon.actionView!!.isEnabled = undoEnabled
         if (colIsOpen()) { // Required mostly because there are tests where `col` is null
-            if (col.undoAvailable()) {
+            if (mShowWhiteboard && whiteboard != null && whiteboard!!.isUndoModeActive) {
```
Comment (oakkitten) [inline AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt:763]: I believe `whiteboard?.isUndoModeActive == true` would be a tad more idiomatic

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt [hunk 3]
```diff
@@ -760,7 +760,17 @@ open class Reviewer : AbstractFlashcardViewer() {
...
+                // Show undo title for whiteboard mode
+                // We arrive here if the first stroke for whiteboard is done.
+                // We stay here even if the first stroke is undone.
+                //  (This works as a safeguard against unintentional undo
+                //   for pre-whiteboard actions by consective tappings.)
+                // We leave here if whiteboard is inactive ("Disable whiteboard" or "Hide whiteboard")
+                //  or is reset ("Clear whiteboard")
```
Comment (oakkitten) [inline AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt:770]: This comment reads as though it should make sense for someone who has some sort of a technical knowledge which I don't. I read this five times and I still have no idea what's going on here...

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt [hunk 4]
```diff
@@ -760,7 +760,17 @@ open class Reviewer : AbstractFlashcardViewer() {
...
+                val lastStroke = resources.getString(R.string.undo_action_whiteboard_last_stroke)
+                undoIcon.title = resources.getString(R.string.studyoptions_congrats_undo, lastStroke)
```
Comment (oakkitten) [inline AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt:772]: * Why not have one string saying, "Undo [last] stroke"? 
* This makes the title "Undo Stroke", probably better to have "Undo stroke"?

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt (hunk 2 above)
Comment (snowtimeglass) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt]: Thanks! I've rewritten the part.

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt (hunk 3 above)
Comment (snowtimeglass) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt]: Sorry for the complicated explanation. I've rewritten it. Thanks!

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt (hunk 4 above)
Comment (snowtimeglass) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt]: I thought that reusing the existing string "Undo %" might be desirable, but I've switched to the more readable way. Thank you for the advise!

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt [hunk 5]
```diff
@@ -760,7 +762,9 @@ open class Reviewer : AbstractFlashcardViewer() {
         undoIcon.setEnabled(undoEnabled).iconAlpha = alphaUndo
         undoIcon.actionView!!.isEnabled = undoEnabled
         if (colIsOpen()) { // Required mostly because there are tests where `col` is null
-            if (col.undoAvailable()) {
+            if (undoIconId == R.drawable.eraser) {
```
Comment (oakkitten) [inline AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt:765]: `undoIconId == R.drawable.eraser` feels hacky, if you have a variable such as `whiteboardHasStrokesToUndo` you could use that.

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt [hunk 6]
```diff
@@ -760,7 +762,9 @@ open class Reviewer : AbstractFlashcardViewer() {
...
+                undoIcon.title = resources.getString(R.string.undo_action_whiteboard_last_stroke)
+            } else if (col.undoAvailable()) {
```
Comment (oakkitten) [inline AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt:767]: **OR better yet**, join the two if blocks. Notice how they are very similar, and you are doing the same checks and calling `col.undoAvailable()` twice.

Don't be afraid to make a bigger refactor in places that do warrant bigger refactors :p

File: AnkiDroid/src/main/res/values/01-core.xml [hunk 7]
```diff
@@ -76,6 +76,7 @@
     <string name="undo">Undo</string>
     <string name="undo_action_review">last review</string>
     <string name="undo_action_change_deck_multi">change decks</string>
+    <string name="undo_action_whiteboard_last_stroke">Undo Stroke</string>
```
Comment (oakkitten) [inline AnkiDroid/src/main/res/values/01-core.xml:79]: Still think this should be “Undo stroke”

**Review by oakkitten — COMMENTED** [review]
Sorry about a late review, life came up. I think that this _ideally_ needs simplification of behavior and logic, however this does fix the issue so I'm not against merging this pending some consensus on the capitalization of “Undo stroke”

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt (hunk 4 above)
Comment (oakkitten) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt]: I thought about this this way; if you are a translator than translating a menu item “Undo stroke” is a no-brainer, but if it's simply “stroke” then you have to think about the context in which it is used, like maybe you need to pick the correct tense and capitalization and whatever. Longer text doesn't necessary == harder to translate

**Comment by snowtimeglass** [comment]
Thank you so much for taking your precious time to give me the thoughtful reviews. I've learned a great deal from them. I'll try some more fixes following your advice.

File: AnkiDroid/src/main/res/values/01-core.xml (hunk 7 above)
Comment (snowtimeglass) [reply AnkiDroid/src/main/res/values/01-core.xml:79]: Currently, all initial letters of words are capitalized on the titles of undoing collection actions (e.g., `Undo Add Note`, `Undo Bury`) because Anki Desktop strings are used on the titles (and Anki Desktop applies the all-initial-letters-of words-capitalized style). 

https://github.com/ankidroid/Anki-Android/blob/d095bbf354ba86feb28a74f6c96681873e342df2/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt#L762-L766
image
image



>Using Anki translations is something I prefer as it represents a more "shared work" future (between Anki Desktop and AnkiDroid), which may also be read as "less work per contributor" and is thus more sustainable long-term, even if there is punctuation inconsistency.

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/issues/12446#issuecomment-1257214544_

Following the case of punctuation, I have applied the same style to the title of undoing whiteboard strokes though it makes capitalization inconsistency in action menu.

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt (hunk 4 above)
Comment (snowtimeglass) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt]: Thanks, I understand and agree with the thought.

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt [hunk 8]
```diff
@@ -744,8 +744,10 @@ open class Reviewer : AbstractFlashcardViewer() {
         // Undo button
         @DrawableRes val undoIconId: Int
         val undoEnabled: Boolean
-        if (mShowWhiteboard && whiteboard != null && whiteboard!!.isUndoModeActive) {
-            // Whiteboard is here and strokes have been added at some point
+        if (mShowWhiteboard && whiteboard != null && whiteboard?.isUndoModeActive == true) {
```
[the remark this answers is not in the document]
Comment (snowtimeglass) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt:747]: Thanks. I got it.

**Comment by snowtimeglass** [comment]
Behavior after the above commits

https://user-images.githubusercontent.com/10436072/210124495-b9ecd5c9-b826-41e5-b21f-c81fa0a1561d.mp4

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt [hunk 9]
```diff
@@ -744,8 +744,10 @@ open class Reviewer : AbstractFlashcardViewer() {
...
+            // We arrive here if the first stroke of whiteboard is done.
+            // We leave here when whiteboard is inactive (by "Disable whiteboard" or "Hide whiteboard")
+            //  or is reset (by "Clear whiteboard")
```
[the remark this answers is not in the document]
Comment (snowtimeglass) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt]: Thank you for the guidance. Following your suggestion, I've removed the `isUndoModeActive` logic.

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt (hunk 5 above)
Comment (snowtimeglass) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt]: I see. I've used a variable for this part in the new commit. Thanks!

File: AnkiDroid/src/main/res/values/01-core.xml (hunk 7 above)
Comment (oakkitten) [reply AnkiDroid/src/main/res/values/01-core.xml:79]: Right, I understand but this might be the case to consider being inconsistent for the sake of the future. Basically, we can go two ways:

* Reuse as much Anki strings as possible and introduce as few homegrown translations as possible. “Undo Add Note” is not super horrible even though it's going to be inconsistent with other menu items. In this case, “Undo Stroke” would be consistent with other “Undo” items but inconsistent with other menu items, and “Undo stroke” would be inconsistent with other “Undo” items but consistent with other menu items. 

  I'd say both of the choices are about as bad, and whatever the implementer choses works.
* Have proper capitalization, with the hope that in the future other strings will be corrected to also have proper capitalization. This will probably require some effort in the Anki repository, creating new strings for all undo actions. But then if you already have “Add note”, it's _very easy_ to translate “Undo add note”. This would be especially cool for languages that have tenses, as in English you can simply prepend “Undo” and you have a phrase that *kind of* works, but in other languages it can be much more awkward.

   In this case, it makes sense to have “Undo stroke” now.

I would personally prefer going the second route; it's quite a bit of gain and the extra translators' burden doesn't seem high. But perhaps there are pitfalls I'm not aware of, and in either case this is something that must be decided by the big guys. So I want to tag @mikehardy and @dae and ask if perhaps it would be a good idea to create proper strings for undo actions in Anki?

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt [hunk 10]
```diff
@@ -744,13 +744,12 @@ open class Reviewer : AbstractFlashcardViewer() {
         // Undo button
         @DrawableRes val undoIconId: Int
         val undoEnabled: Boolean
-        if (mShowWhiteboard && whiteboard != null && whiteboard!!.isUndoModeActive) {
-            // Whiteboard is here and strokes have been added at some point
+        val whiteboardShowsStrokesToUndo = mShowWhiteboard && whiteboard?.undoEmpty() == false
```
Comment (oakkitten) [inline AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt:747]: Nit: I'd _slightly_ prefer my original `whiteboardHasStrokesToUndo` as you can interpret your variant as “whiteboard shows [the button/menu] ‘strokes to undo’”

By the way, can we do away with `whiteboardHasStrokes`? Is it possible to have stokes and at the same time NOT being able to undo them?

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt [hunk 11]
```diff
@@ -744,13 +744,12 @@ open class Reviewer : AbstractFlashcardViewer() {
...
+        if (whiteboardShowsStrokesToUndo) {
             undoIconId = R.drawable.eraser
-            undoEnabled = !whiteboard!!.undoEmpty()
+            undoEnabled = true
         } else {
-            // We can arrive here even if `mShowWhiteboard &&
-            // mWhiteboard != null` if no stroke had ever been made
+            // We can arrive here even if whiteboard is enabled if no stroke has ever been made
```
Comment (oakkitten) [inline AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt:752]: Just a thought. What I personally prefer to do is in case of complex behavior describe it in a _single_ comment in simple, non-technical words and put it before the method. This way you can see the big picture without reading the code

**Comment by dae** [comment]
"Undo Add Note" and the like use "Title Case" for two reasons: it's what seems to be the standard in menubars, and we had a bunch of already translated actions in that case. I'm not really sure it's worth making translations translate all these actions twice. If there are inconsistency issues, couldn't you just dynamically convert particular strings to "Sentence case", perhaps for a whitelisted set of languages?

**Comment by oakkitten** [comment]
Title Case menu bars might have been standard on Windows, but it seems that this trope might be disappearing, as some modern Windows applications such as Edge, or Photos, or Clock, seem to prefer Sentence casing. Others don't, however, such as Calculator. It's definitely not standard on Android, though, and I don't know about Apple.

I would personally love Anki to switch to Sentence casing, because:

* It would be more consistent with Anki itself; other languages such as Spanish, French or Russian do no use Title Casing within Anki
* Easily reuse strings in Android
* I see no point in Title Casing in the first place

Regarding undo strings, I would still love to have new strings, because:
* It allows for easier to understand, more natural language in translations
* Not a lot of _additional_ work for the translators

> couldn't you just dynamically convert particular strings to "Sentence case", perhaps for a whitelisted set of languages

That would work for English, I guess, but not for other languages I know. A lot of languages use tenses/conjugations/whatever, so this is going to work well for a very few select cases. Can we even come up with a list with such languages? How sure can we be that this would work for those languages? Sounds dangerous to me

**Comment by dae** [comment]
From a quick look at some Apple iOS apps, Title Case appears to be the norm. But I think internal consistency is more important - if different menu items in the same menu use different cases, that looks somewhat unprofessional.

> other languages such as Spanish, French or Russian do no use Title Casing within Anki

Is that the standard for those languages, or just their Anki translations? What does the calculator app or similar look like in those languages?

> A lot of languages use tenses/conjugations/whatever, so this is going to work well for a very few select cases.

Translators have control of the template, so they can do the equivalent of `Undo '{Action Name}'` or `Undo: {Action Name}`. Is such an an approach really that awkward in other languages? (I'm not arguing here, I'm just trying to understand)

> Sounds dangerous to me

With an add-language-as-required whitelist and the ability to apply it to select strings, I suspect it'd work fairly well in practice.

**Comment by oakkitten** [comment]
> Is that the standard for those languages, or just their Anki translations? What does the calculator app or similar look like in those languages?

Good question, it seems that on Windows Sentence casing is used in those languages ... which means that there's probably not only a tense inconsistency, but also a capitalization inconsistency in the Undo menu item in Anki itself — for most languages?

> Is such an an approach really that awkward in other languages?

You can sort of see it in English, while “Undo Add Note” as a phrase sounds Ok in a menu  (at least to me — I'm not a native speaker), it should ideally be “Undo adding a note” or something. In Russian “Undo Add Note” becomes «Отменить - Добавить запись», which is bad in my opinion. Russian is just not so... flexible? in this regard. I'd surely go with «Отменить добавление записи» here. Of course, some people may have other opinions about this.

**Comment by dae** [comment]
"Add Note" -> "Undo Note Addition" might be more natural prose, but "Undo 'Add Note'" doesn't seem particularly strange to me in English. No experience with Russian, so I'll have to take your word for it there :-)

There are also "Redo: ..." and "... undone", "... redone" strings, so splitting these up into separate strings means we're making 4x the work for translators. I guess the question is, is the awkwardness of the existing strings in languages like Russian enough to justify the extra work, given that the average completion rate across the translations is only about 50% as it is?

**Comment by BrayanDSO** [comment]
About title casing, I don't see the point either.

And about using individual strings instead of a generic format string, in portuguese at least (I'm brazilian), it would be quite more natural to have individualized strings because the verbs, articles, etc should have a gender and number agreement.

Are the generic translations too odd to justify multiplying the translations' work by 5 times? Idk. In portuguese at least, they are mostly acceptable I think, but if Anki strives to be a more user friendly app on different languages, individualized strings make sense, despite the increased work load on the job of volunteer translators

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt (hunk 10 above)
Comment (snowtimeglass) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt:747]: >you can interpret your variant as “whiteboard shows [the button/menu] ‘strokes to undo’”

I beg your pardon, I don't understand the interpretation enough yet.
Does it mean “whiteboard shows the button (or the item) named `strokes to undo`”?



>Is it possible to have stokes and at the same time NOT being able to undo them?

Currently, it is possible after the action of "Hide whiteboard". The action disables undoing strokes, and enables undoing collection actions again.

https://user-images.githubusercontent.com/10436072/210235131-cd533dbd-b237-4152-a2e8-890255c486b6.mp4

Comment (oakkitten) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt:747]: > I beg your pardon, I don't understand the interpretation enough yet.
Does it mean “whiteboard shows the button (or the item) named strokes to undo”?

That was my idea but on the second thought, uh, just ignore it, it's a bit far-fetched :p

> Currently, it is possible after the action of "Hide whiteboard". The action disables undoing strokes, and enables undoing collection actions again.

Hum. But if you hide the whiteboard, then CMIIW `mShowWhiteboard` will be `false` and so our variable will be false. How about naming it `whiteboardIsShownAndHasStrokes`?

**Comment by oakkitten** [comment]
> There are also "Redo: ..." and "... undone", "... redone" strings, so splitting these up into separate strings means we're making 4x (5x since the original action names are required as well) the work for translators. I guess the question is, is the awkwardness of the existing strings in languages like Russian enough to justify the extra work, given that the average completion rate across the translations is only about 50% as it is?

As a translator (and I try to be very diligent about my translations) I would say than what takes time is understanding the context of the phrase, and trying to fit it withing constraints such as character count. Actually typing the text takes the fraction of the time for me; when there are many related phrases like in this case, I enjoy doing a lot of translations in no time.

BUT I'm only speaking for myself here, it's hard for me to judge whether this kind of a change will result in a lot of these strings untranslated for a long time or not.

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt (hunk 10 above)
Comment (snowtimeglass) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt:747]: >Hum. But if you hide the whiteboard, then CMIIW `mShowWhiteboard` will be false and so our variable will be false.

Yes, I think you're right on this point, but sorry, I'm not sure yet what you are concerned about from the fact. However, I understand that the current name of the variable, `whiteboardShowsStrokesToUndo`, is apparently ambiguous and misleading for some reason. 

>How about naming it whiteboardIsShownAndHasStrokes? Or whiteboardStrokesVisible maybe

I agree with the idea. The suggested name, `whiteboardIsShownAndHasStrokes`, is clearer for me, too. I'm going to rename it. Thank you for the suggestion :-D

Comment (snowtimeglass) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt]: Done :-)

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt (hunk 11 above)
Comment (snowtimeglass) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt:752]: Thank you for the advice. Certainly, this comment isn't simple.

Thanks to the new simple variable, `whiteboardIsShownAndHasStrokes`, suggested by you, there will be less need for the comment, I think. So, I'm going to remove it.

        if (whiteboardIsShownAndHasStrokes) {
            undoIconId = R.drawable.eraser
            undoEnabled = true
        } else {
            // We can arrive here even if whiteboard is enabled if no stroke has ever been made
            undoIconId = R.drawable.ic_undo_white
            undoEnabled = colIsOpen() && col.undoAvailable()

**Comment by snowtimeglass** [comment]
I am sorry for the late reply.

> Right, I understand but this might be the case to consider being inconsistent for the sake of the future. Basically, we can go two ways:
> 
> * Reuse as much Anki strings as possible and introduce as few homegrown translations as possible. “Undo Add Note” is not super horrible even though it's going to be inconsistent with other menu items. In this case, “Undo Stroke” would be consistent with other “Undo” items but inconsistent with other menu items, and “Undo stroke” would be inconsistent with other “Undo” items but consistent with other menu items. 
> 
>   I'd say both of the choices are about as bad, and whatever the implementer choses works.
> * Have proper capitalization, with the hope that in the future other strings will be corrected to also have proper capitalization. This will probably require some effort in the Anki repository, creating new strings for all undo actions. But then if you already have “Add note”, it's _very easy_ to translate “Undo add note”. This would be especially cool for languages that have tenses, as in English you can simply prepend “Undo” and you have a phrase that *kind of* works, but in other languages it can be much more awkward.
> 
>    In this case, it makes sense to have “Undo stroke” now.
> 
> I would personally prefer going the second route; it's quite a bit of gain and the extra translators' burden doesn't seem high. But perhaps there are pitfalls I'm not aware of, and in either case this is something that must be decided by the big guys. So I want to tag @mikehardy and @dae and ask if perhaps it would be a good idea to create proper strings for undo actions in Anki?
> 

 _Originally posted by @oakkitten in https://github.com/ankidroid/Anki-Android/pull/12961#discussion_r1059783644_

There seems to be no consensus yet on conforming capitalization to Anki Desktop ("Title Case" style), so I've rewrited the string, "Undo Stroke" to "Undo stroke" ("Sentence case" style) :-)

>“Undo stroke” would be inconsistent with other “Undo” items but consistent with other menu items.

I would like to leave the consistency problem unresolved for now and carry it over to another issue.

File: AnkiDroid/src/main/res/values/01-core.xml [hunk 12]
```diff
@@ -76,6 +76,7 @@
     <string name="undo">Undo</string>
     <string name="undo_action_review">last review</string>
     <string name="undo_action_change_deck_multi">change decks</string>
+    <string name="undo_action_whiteboard_last_stroke">Undo stroke</string>
```
Comment (david-allison) [inline AnkiDroid/src/main/res/values/01-core.xml:79]: Could you add a `comment=""` explaining the relation to the whiteboard

**Review by david-allison — CHANGES_REQUESTED** [review]
One nitpick and good to go.

**Comment by mikehardy** [comment]
This one just needs a comment in the strings file it seems?

File: AnkiDroid/src/main/res/values/01-core.xml (hunk 12 above)
Comment (snowtimeglass) [reply AnkiDroid/src/main/res/values/01-core.xml:79]: My apologies for the late response. I overlooked your comment. I will work on it now.

**Comment by snowtimeglass** [comment]
I overlooked it. Thank you for letting me notice.

**Review by david-allison — APPROVED** [review]

File: AnkiDroid/src/main/res/values/01-core.xml [hunk 13]
```diff
@@ -76,6 +76,7 @@
     <string name="undo">Undo</string>
     <string name="undo_action_review">last review</string>
     <string name="undo_action_change_deck_multi">change decks</string>
+    <string name="undo_action_whiteboard_last_stroke" comment="One of the display patterns of "Undo" item on the action menu in Reviewer. It is shown as the title of the item when the whiteboard (handwriting) feature is enabled and visible and has any strokes (handwritten lines)">Undo stroke</string>
```
Comment (david-allison) [inline AnkiDroid/src/main/res/values/01-core.xml:79]:
```suggestion
    <string name="undo_action_whiteboard_last_stroke" comment="One of the display patterns of 'Undo' item on the action menu in Reviewer. It is shown as the title of the item when the whiteboard (handwriting) feature is enabled and visible and has any strokes (handwritten lines)">Undo stroke</string>
```

**Review by david-allison — COMMENTED** [review]
`"` needs to be escaped, or just use `'`

File: AnkiDroid/src/main/res/values/01-core.xml (hunk 13 above)
Comment (snowtimeglass) [reply AnkiDroid/src/main/res/values/01-core.xml:79]: I see. Thank you so much!

**Review by david-allison — APPROVED** [review]

**Review by mikehardy — APPROVED** [review]
LGTM - strings activity is only trusted users on crowdin (frequent translators) and their translations look good based on activity stream, so I'll merge
