### PR TITLE
Fixed the empty regular deck check, now uses foreach to check all the…

### LINKED ISSUE #17965: "This deck is empty" should appear even when the deck has empty subdeck
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

* Create a deck A::B
* Tap on A

### Expected behaviour

"this deck is empty" should appear. (Same as if you tap on deck A::B)

### Debug info

```text
Ankidroid version 2.20.1
```

### (Optional) Anything else you want to share?

This message does not exists upstream at all. (And I think it should)

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by devyk100**
## Purpose / Description
_Creating a deck A::B, if B subdeck is empty and parent A is empty, clicking on the parent it should show 'this deck is empty', instead of the finished deck message._

## Fixes
* Fixes #17965 

## Approach
_The earlier code just checked for the following conditions:_
- If the deck clicked has subdecks (at the topmost list level only) - `getNodeByDid(did).children.isEmpty()`
- If only the deck clicked has 0 cards - `decks.isEmpty(did)`

This would fail at cases where the deck has subdecks, which are also empty.

_Now the check is done to not just check subdecks, but the count of cards of these subdecks too._
- using the `forEach` recursive function of `DeckNode` to traverse the entire tree of subdecks to check if all of them are empty for triggering the empty deck snackbar

## How Has This Been Tested?
ran all tests from `./gradlew jacocoTestReport` on emulator (android 15 VanillaIceCream)
PC config:
processor: i5 12500H
RAM: 16GB
SDK: 21
results: ran with 0 failures
Also I tested with creation of "A::B::C", "A::B" decks, and adding the cards to the subdecks.
| clicking on A | shows finished deck on A click |
| ------ | ------ |
| image | image | 

| clicking on B | shows finished deck on B | 
| ------ | ------ |
| image | image | 

**After fix**
| clicking on A | clicking on B | 
| ------ | ------ | 
| image | image | 

## Update commit - [2e33db4](https://github.com/ankidroid/Anki-Android/pull/18007/commits/2e33db48ecd6d6855f16039e0a41fe324e1a407f)
Now uses a new function `isDeckAndSubdeckEmpty`, and DeckNode implements Iterable<DeckNode>, and hence the entire tree empty check is done using deckNode.all{}, which efficiently returns true or false.
Also refactored the previous query function that returned enums.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by devyk100** [comment]
I'd really appreciate any feedback on improving this.

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 1]
```diff
@@ -2678,10 +2677,16 @@ open class DeckPicker :
             withCol { sched.hasCardsTodayAfterStudyAheadLimit() } -> CompletedDeckStatus.LEARN_AHEAD_LIMIT_REACHED
             withCol { sched.newDue() || sched.revDue() } -> CompletedDeckStatus.LEARN_AHEAD_LIMIT_REACHED
             withCol { decks.isFiltered(did) } -> CompletedDeckStatus.DYNAMIC_DECK_NO_LIMITS_REACHED
-            getNodeByDid(did).children.isEmpty() &&
+            run {
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:2680]: This seems very long for a condition of a `when`.
I think it'd be nicer to create a function. This would ensure not only that you could write test for the functions, but that  this would take a single line, the same way other condition does.

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 2]
```diff
@@ -2678,10 +2677,16 @@ open class DeckPicker :
...
                 withCol {
-                    decks.isEmpty(did)
-                } -> CompletedDeckStatus.EMPTY_REGULAR_DECK
+                    var allChildrenEmpty = true
+                    node.forEach { deckNode ->
+                        allChildrenEmpty = allChildrenEmpty && decks.isEmpty(deckNode.did)
+                    }
+                    allChildrenEmpty
+                }
+            } -> CompletedDeckStatus.EMPTY_REGULAR_DECK
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:2689]: I'd consider changing the documentation. Because, in this case, there won't be a "custom study".
Instead, I'd state it returns what should be done when the user tapped on the deck and review can't be done immediately

Also, change above the comment "// If the deck is empty (& has no children) then show a message saying it's empty" since it's not the case anymore we require the absence of children

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 3]
```diff
@@ -2678,10 +2677,16 @@ open class DeckPicker :
             withCol { sched.hasCardsTodayAfterStudyAheadLimit() } -> CompletedDeckStatus.LEARN_AHEAD_LIMIT_REACHED
             withCol { sched.newDue() || sched.revDue() } -> CompletedDeckStatus.LEARN_AHEAD_LIMIT_REACHED
             withCol { decks.isFiltered(did) } -> CompletedDeckStatus.DYNAMIC_DECK_NO_LIMITS_REACHED
-            getNodeByDid(did).children.isEmpty() &&
+            run {
+                val node = getNodeByDid(did)
                 withCol {
-                    decks.isEmpty(did)
-                } -> CompletedDeckStatus.EMPTY_REGULAR_DECK
+                    var allChildrenEmpty = true
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:2683]: I'm not a huge fan of this, because even if we find a non empty subdeck we still iterate over the other ones.

I think it would be more elegant to remove `forEach` in DeckNode and instead DeckNode should implements `Iterable<DeckNode>`.
This way, we could simply do `node.all { decks.isEmpty(did) }`

This would also allows to slightly improve at least one other use of `forEach`, by adding a `filter` in DeckPickerWidget

**Review by Arthur-Milchior — COMMENTED** [review]
Thank you very much for your first contribution. It does exactly what I wanted, that's great!

I have a few suggestion in order to improve the codebase quality generally.
Indeed, I didn't really know the part of the codebase you touched and it's only while reviewing your PR that I saw some improvement potential in our current codebase.

In particular, I think we can remove `CompletedDeckStatus`. When it was introduced, each status lead to a different action. Today, every status but the empty deck lead to the same action. Thus, the only thing that matter is "is the deck (and its subdeck) empty or not"
So we should have a function that answer this question (and write unit test to ensure it's answered properly) and then either display the snackbar or execute `onDeckCompleted`

Would you be willing to do all of those changes?

**Comment by devyk100** [comment]
Thanks for the review and suggestions! I'll work on improving it

**Comment by devyk100** [comment]
@Arthur-Milchior really grateful for your reviews I was able to refactor this code. Can you have a look at it now? I'd appreciate if still there any improvements possible in this.

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 4]
```diff
@@ -2167,20 +2167,14 @@ open class DeckPicker :
...
-            -> {
-                onDeckCompleted()
-            }
-            CompletedDeckStatus.EMPTY_REGULAR_DECK -> {
-                // If the deck is empty (& has no children) then show a message saying it's empty
-                showEmptyDeckSnackbar()
-                updateUi()
-            }
+
+        if (isDeckAndSubdeckEmpty(did)) {
```
Comment (devyk100) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:2171]: I did not add any comments here, as the function name should be self explanatory, and can be used in testing.

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 5]
```diff
@@ -2669,38 +2662,15 @@ open class DeckPicker :
...
-        when {
-            withCol { sched.hasCardsTodayAfterStudyAheadLimit() } -> CompletedDeckStatus.LEARN_AHEAD_LIMIT_REACHED
-            withCol { sched.newDue() || sched.revDue() } -> CompletedDeckStatus.LEARN_AHEAD_LIMIT_REACHED
-            withCol { decks.isFiltered(did) } -> CompletedDeckStatus.DYNAMIC_DECK_NO_LIMITS_REACHED
-            getNodeByDid(did).children.isEmpty() &&
-                withCol {
-                    decks.isEmpty(did)
-                } -> CompletedDeckStatus.EMPTY_REGULAR_DECK
-            else -> CompletedDeckStatus.REGULAR_DECK_NO_MORE_CARDS_TODAY
+    private suspend fun isDeckAndSubdeckEmpty(did: DeckId): Boolean {
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:2669]: nit: I believe that `areDeckAndSubdecksEmpty` is more gramatically correct

**Review by BrayanDSO — APPROVED** [review]
LGTM. Left a comment. Thanks!

**Comment by devyk100** [comment]
@Arthur-Milchior I'd really appreciate your review if possible.

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 6]
```diff
@@ -2168,20 +2168,13 @@ open class DeckPicker :
...
-                showEmptyDeckSnackbar()
-                updateUi()
-            }
+        if (areDeckAndSubdecksEmpty(did)) {
+            showEmptyDeckSnackbar()
+            updateUi()
+            return
         }
+
+        onDeckCompleted()
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:2177]: this should be in a `else` I believe. Otherwise, we get an unexpected change in behavior here

**Comment by Arthur-Milchior** [comment]
Oh also, it'd be great if you could rebase everything in a single commit we could merge as-is, with a commit message explaining why you made those changes.
You can copy paste some of the request I made, given that it explained why you can simplify the code

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt (hunk 6 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:2177]: @devyk100 it appears this comment is still waiting on you for resolution

**Comment by devyk100** [comment]
I have squashed the commits, and removed the unexpected behaviour change by adding the else block

**Review by lukstbit — APPROVED** [review]
LGTM, I think every request was handled.
Thank you.

**Comment by david-allison** [comment]
Hi there @devyk100! This is the OpenCollective Notice for PRs merged from [2025-04-01 through 2025-04-30](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2025-04-01..2025-04-30+author%3Adevyk100)
                      
If you are interested in compensation for this work, the process with details is here: https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

We only post one comment per person per month to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for this month

Please understand that our monthly budget is never guaranteed to cover all claims - the cap on payments-per-person may be lower, but we try to make our process as fair and transparent as possible, we just need your understanding.

Thanks!
