### PR TITLE
Fix webview version fix

### LINKED ISSUE #17498: [2.19.2] Android 8 WebView detection issue
User appears to be on WebView 130.X, but we are detecting it as 70.

https://www.reddit.com/r/Anki/comments/1gy8viw/cant_update_webview_android_8_whats_my_best_option/

### PR DESCRIPTION
**Pull request by mikehardy**
## Purpose / Description

Apparently the webview package on some devices can have a version code and version name that indicate they will not be compatible, but they work fine.

Inspection of the User-Agent string from the WebView indicates it advertises a Chrome version that is more than adequate.

This PR adds a fallback WebView version detection mode that will believe the User-Agent if it says it's compatible, even if the versionCode says it isn't

## Fixes
* Fixes #17498

## Approach

Most of the work: refactoring and adding a test:

- Start by refactoring all the WebView stuff in to one spot
- Continue by refactoring the gathering of information from the processing of information, so it is testable
- Add some test cases that behave how 2.19.2 currently behaves

Actual work:
Add logic to check User-Agent and verify that our confusing test cases from real world examples now work fine

## How Has This Been Tested?

- Extensively with unit tests - User-Agent from #17498 has a test case and passes
- Verified on my API24 emulator it still warns me
- Verified on my API34 emulator it is fine

## Learning (optional, can help others)

Learned some Kotlin regex

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/utils/WebViewUtils.kt [hunk 1]
```diff
@@ -16,15 +16,118 @@
...
+    val webviewPackageInfo = getAndroidSystemWebViewPackageInfo(activity.packageManager)
+    val legacyWebViewPackageInfo = getLegacyWebViewPackageInfo(activity.packageManager)
+    // TODO modify the alert dialog text to handle the usage of developer builds for system WebView
+    if (legacyWebViewPackageInfo != null) {
+        Timber.w("WebView is outdated. %s: %s", legacyWebViewPackageInfo.packageName, legacyWebViewPackageInfo.versionName)
+        showOutdatedWebViewDialog(activity, userVisibleCode, activity.getString(R.string.link_legacy_webview_update))
+    } else {
+        Timber.w("WebView is outdated. %s: %s", webviewPackageInfo?.packageName, webviewPackageInfo?.versionName)
+        showOutdatedWebViewDialog(activity, userVisibleCode, activity.getString(R.string.link_webview_update))
+    }
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/utils/WebViewUtils.kt:51]: I don't feel this matches

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/utils/WebViewUtils.kt:51]: It does - one is "either package", one is "legacy package"
And the string guidance is slightly different for each

It was confusing to me at first, had to read it a couple times.
So the change should be NF

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/utils/WebViewUtils.kt:51]: Ah, I see.

**Review by david-allison — APPROVED** [review]

File: AnkiDroid/src/main/java/com/ichi2/utils/WebViewUtils.kt [hunk 2]
```diff
@@ -16,15 +16,118 @@
...
+        CrashReportService.sendExceptionReport(e, "WebViewUtils", "some issue occurred while extracting webview user agent")
+    }
+    return null
+}
+
+/*
+ * Returns a Chrome-like WebView version if it is outdated, otherwise null if
+ * cannot be determined at all or if okay
+ */
+private fun getChromelikeWebViewVersionIfOutdated(activity: AnkiActivity): Int? {
```
Comment (lukstbit) [inline AnkiDroid/src/main/java/com/ichi2/utils/WebViewUtils.kt:68]: Small typo: _getChrome**L**ikeWebViewVersionIfOutdated()_

File: AnkiDroid/src/main/java/com/ichi2/utils/WebViewUtils.kt [hunk 3]
```diff
@@ -16,15 +16,118 @@
...
+    // but it's a webview that advertises modern capabilities via User-Agent in "Chrome" section
+    // Our warning is purely advisory, so, let's let those through if User-Agent looks okay
+    userAgent?.let {
+        val chromeRegex = """Chrome/(\d+)""".toRegex()
+        val matchResult = chromeRegex.find(userAgent)?.groupValues[1]
+        matchResult?.toInt()?.let {
+            if (it < OLDEST_WORKING_WEBVIEW_VERSION) {
+                // If we got here, even the User-Agent says it's incompatible, return something
+                // potentially useful to the user as a browser version
+                return it.toInt()
```
Comment (lukstbit) [inline AnkiDroid/src/main/java/com/ichi2/utils/WebViewUtils.kt:102]: The cast is not needed, _it_  will be an _Int_.

File: AnkiDroid/src/main/java/com/ichi2/utils/WebViewUtils.kt [hunk 4]
```diff
@@ -16,15 +16,118 @@
...
+        )
+        return null
+    }
+
+    // Sometimes the webview version code appears too old, and the package name does as well,
+    // but it's a webview that advertises modern capabilities via User-Agent in "Chrome" section
+    // Our warning is purely advisory, so, let's let those through if User-Agent looks okay
+    userAgent?.let {
+        val chromeRegex = """Chrome/(\d+)""".toRegex()
+        val matchResult = chromeRegex.find(userAgent)?.groupValues[1]
```
Comment (lukstbit) [inline AnkiDroid/src/main/java/com/ichi2/utils/WebViewUtils.kt:97]: The IDE complains about this, should probably be:

`val matchResult = chromeRegex.find(userAgent)?.groupValues?.get(1)`

to handle the possible null in _find()_.

**Review by lukstbit — APPROVED** [review]
LGTM, left some minor issues with style and nullability handling.

File: AnkiDroid/src/main/java/com/ichi2/utils/WebViewUtils.kt (hunk 4 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/utils/WebViewUtils.kt:97]: You noticed an IDE issue before in the "dialog fragment needs default constructor" case, with an unneeded `()` - in this case and the previous case my IDE wasn't lighting those up! I'll have to look into settings or something and see if I've inadvertently disabled some inspections 🤔 

Either way, I appreciate the pointers. Slowly thinking more kotlin-y with all it's fancy run-on-sentences (that's how I think about it 😆  e.g. `doThink.butOhAlsoThis { andInHere.doThis().nowUseIT {  andMaybeApplyEtc() } } }` haha

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/utils/WebViewUtils.kt]: I wasn't able to find an IDE inspection that lit that up but I did alter it to `groupValues?.get(1)` and verified it still worked, so "NF" change from perspective of test performance but safer from perspective of null-safe - thanks
