### PR TITLE
fix: Added tap outside to dismiss dialog (deck-description)

### LINKED ISSUE #19077: Deck description dialog doesn't have tap outside to cancel
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

The edit deck description dialog doesn't go back if you tap outside it.

### Expected behaviour

It should go back/bring up the confirmation dialog.

### Debug info

```text
AnkiDroid Version = 2.22.3 (4f2ec681da36b8307a865f05192498b8425adf0f)  
Backend Version = 0.1.60-anki25.07.5 (25.07.5 7172b2d26684c7ef9d10e249bd43dc5bf73ae00c)  
Android Version = 13 (SDK 33)  
ProductFlavor = play  
Device Info = Xiaomi | POCO | mondrian | mondrian_global | 23013PC75G | qcom  
Webview User Agent = Mozilla/5.0 (Linux; Android 13; 23013PC75G Build/TKQ1.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/138.0.7204.179 Mobile Safari/537.36  
ACRA UUID = 3792582f-98ac-430e-ae42-4ace0156bf29  
FSRS = 4.1.1 (Enabled: true)  
Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by argon2r**
## Purpose / Description
The deck description dialog does not dismiss when tapping outside it. This adds tap outside to dismiss functionality.

## Fixes
* Fixes #19077 

## Approach
Added a touch listener that detects taps outside the dialog and calls `viewModel.onBackRequested()`. This closes the dialog if no changes were made, or shows the discard confirmation if there are unsaved changes.

## How Has This Been Tested?

https://github.com/user-attachments/assets/9e1bf09e-4d39-41c8-8a52-8c350e169bd2

Tested on: OnePlus Nord CE2 lite

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/EditDeckDescriptionDialog.kt [hunk 1]
```diff
@@ -107,6 +110,20 @@ class EditDeckDescriptionDialog : DialogFragment() {
...
+                ?: binding.root.parent as? View
+                ?: binding.root
+
+        alertDialog.window?.decorView?.setOnTouchListener { _, event ->
+            if (event.action != MotionEvent.ACTION_DOWN) return@setOnTouchListener false
+            if (dialogContentView.rawHitTest(event)) return@setOnTouchListener false
+            viewModel.onBackRequested()
+            true
+        }
+    }
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/EditDeckDescriptionDialog.kt]: can `setOnCancelListener` be used instead? This seems complex for a 'normal' operation

**Comment by sanjaysargam** [comment]
don't you think we can simplify this ? 

```
setCanceledOnTouchOutside(true)
setCancelable(true)
``` 
just by setting this in Dialog. 

something like this : 
``` 
override fun onCancel(dialog: DialogInterface) {
        viewModel.onBackRequested()
}
``` 


@argon2r Could you try this approach once ?

**Comment by argon2r** [comment]
Hey @david-allison @sanjaysargam ,

I tried the `setCanceledOnTouchOutside(true)`  `onCancel()` approach, but it doesn't work for this case. When tapping outside, the touch event passes through to the activity before `onCancel()` is called, which triggers the deck options menu.

Since we need to show a discard confirmation when there are unsaved changes, we need to intercept and consume the touch event to prevent it from reaching the underlying activity. The touch listener approach is the only way I could find to achieve this.

**Comment by sanjaysargam** [comment]
@argon2r 
Could you provide a recording for this approach if possible ?

**Comment by argon2r** [comment]
> @argon2r Could you provide a recording for this approach if possible ?


https://github.com/user-attachments/assets/17672081-7377-4d78-8fdd-ffd0c434c013

I wasn’t able to get the expected result.

**Review by david-allison — CHANGES_REQUESTED** [review]
I'll approve after this.

`Co-authored-by: David Allison <62114487+david-allison@users.noreply.github.com>` in the commit trailer would be appreciated, but is not necessary

```patch
Subject: [PATCH] 
---
Index: AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt b/AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt
--- a/AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt	(revision 9dda7c50f10bfa1fc7989bb2272cd6cf2c273105)
+++ b/AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt	(date 1767603999545)
@@ -24,6 +24,7 @@
 import android.text.InputFilter
 import android.view.KeyEvent
 import android.view.LayoutInflater
+import android.view.MotionEvent
 import android.view.View
 import android.widget.ArrayAdapter
 import android.widget.Button
@@ -40,6 +41,7 @@
 import androidx.recyclerview.widget.DividerItemDecoration
 import androidx.recyclerview.widget.LinearLayoutManager
 import androidx.recyclerview.widget.RecyclerView
+import androidx.viewbinding.ViewBinding
 import com.google.android.material.textfield.TextInputLayout
 import com.ichi2.anki.R
 import com.ichi2.themes.Themes
@@ -378,6 +380,28 @@
 val AlertDialog.neutralButton: Button?
     get() = getButton(DialogInterface.BUTTON_NEUTRAL)
 
+
+/**
+ * Executes [block] when a touch outside the dialog occurs
+ *
+ * This MUST be called after [show] or inside [AlertDialog.setOnShowListener]
+ *
+ * This will not call [AlertDialog.cancel]
+ */
+fun AlertDialog.handleOutsideTouch(binding: ViewBinding, block: () -> Unit) {
+    val dialogContentView =
+        findViewById(com.google.android.material.R.id.contentPanel)
+            ?: binding.root.parent as? View
+            ?: binding.root
+
+    window?.decorView?.setOnTouchListener { _, event ->
+        if (event.action != MotionEvent.ACTION_DOWN) return@setOnTouchListener false
+        if (dialogContentView.rawHitTest(event)) return@setOnTouchListener false
+        block()
+        true
+    }
+}
+
 /**
  * Extension function for AlertDialog.Builder to set a list of items.
  * Items are not displayed if [AlertDialog.Builder.setMessage] has been called
Index: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/EditDeckDescriptionDialog.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/EditDeckDescriptionDialog.kt b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/EditDeckDescriptionDialog.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/EditDeckDescriptionDialog.kt	(revision 9dda7c50f10bfa1fc7989bb2272cd6cf2c273105)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/EditDeckDescriptionDialog.kt	(date 1767603999550)
@@ -18,7 +18,6 @@
 
 import android.app.Dialog
 import android.os.Bundle
-import android.view.MotionEvent
 import android.view.View
 import androidx.activity.OnBackPressedCallback
 import androidx.appcompat.app.AlertDialog
@@ -43,8 +42,8 @@
 import com.ichi2.utils.create
 import com.ichi2.utils.moveCursorToEnd
 import com.ichi2.utils.negativeButton
+import com.ichi2.utils.handleOutsideTouch
 import com.ichi2.utils.positiveButton
-import com.ichi2.utils.rawHitTest
 import com.ichi2.utils.show
 import kotlinx.coroutines.flow.filterNotNull
 import kotlinx.coroutines.launch
@@ -87,7 +86,7 @@
                 setOnShowListener {
                     positiveButton.setOnClickListener { viewModel.saveAndExit() }
                     negativeButton.setOnClickListener { viewModel.onBackRequested() }
-                    setupTouchOutsideListener()
+                    handleOutsideTouch(binding) { viewModel.onBackRequested() }
                 }
                 setCanceledOnTouchOutside(false)
                 setCancelable(false)
@@ -110,19 +109,6 @@
         }
     }
 
-    private fun setupTouchOutsideListener() {
-        val dialogContentView =
-            alertDialog.findViewById<View>(com.google.android.material.R.id.contentPanel)
-                ?: binding.root.parent as? View
-                ?: binding.root
-
-        alertDialog.window?.decorView?.setOnTouchListener { _, event ->
-            if (event.action != MotionEvent.ACTION_DOWN) return@setOnTouchListener false
-            if (dialogContentView.rawHitTest(event)) return@setOnTouchListener false
-            viewModel.onBackRequested()
-            true
-        }
-    }
 
     private fun setupDialogView(view: View) {
         binding.deckDescriptionInput.apply {

```

File: AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt [hunk 2]
```diff
@@ -376,6 +380,30 @@ val AlertDialog.negativeButton: Button
...
+ * This MUST be called after [show] or inside [AlertDialog.setOnShowListener]
+ *
+ * This will not call [AlertDialog.cancel]
+ */
+fun AlertDialog.handleOutsideTouch(
+    binding: ViewBinding,
+    block: () -> Unit,
+) {
+    val dialogContentView =
+        findViewById(com.google.android.material.R.id.contentPanel)
```
Comment (criticalAY) [inline AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt:395]: If the dialog doesn't use that specific Material ID (e.g., it's a standard androidx.appcompat.app.AlertDialog), findViewById will return null.

Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt:395]: I am okay with this being improved later or so, I can hit merge if you are okay with it

Comment (argon2r) [reply AnkiDroid/src/main/java/com/ichi2/utils/AlertDialogFacade.kt:395]: Please go ahead with this for now, I'll follow up later.
