### PR TITLE
fix: CardTemplateEditor save button disabled after error

### LINKED ISSUE #19851: Checkmark button is disabled after cloze error in the template editor
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Go to deck screen -> manage note types -> cloze and click the edit button.
2. Remove the `cloze:` from `{{cloze:Text}}`.

If you try to save you get this error (which I guess follows the desktop version, so is fine), but then the checkmark button is disabled.

Image

So the user can't fix the template and save their changes (without some unintuitive workaround).

### Expected behaviour

The checkmark button should still be tappable.

### Debug info

```text
AnkiDroid Version = 2.23.1 (3f3133b496b531383e9a6494f5a7704634935308)  
Backend Version = 0.1.62-anki25.09.2 (25.09.2 3890e12c9e48c028c3f12aa58cb64bd9f8895e30)  
Android Version = 13 (SDK 33)  
ProductFlavor = full  
Device Info = Xiaomi | POCO | mondrian | mondrian_global | 23013PC75G | qcom  
Webview User Agent = Mozilla/5.0 (Linux; Android 13; 23013PC75G Build/TKQ1.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/143.0.7499.115 Mobile Safari/537.36  
ACRA UUID = 4afc3b3f-e93f-4a66-bc71-2b9476ef9eb0  
FSRS = 5.1.0 (Enabled: true)  
Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

This didn't occur in v2.22.3.

Also, I noticed some weird inconsistency with the "The first field is empty" and "Cloze deleteion can only be used on cloze note types" warnings on the add screen vs the edit screen. But, apparently, it's [the same in Anki Desktop](https://forums.ankiweb.net/t/the-first-field-is-empty-problem/53386/13)...

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by criticalAY**
## Purpose / Description
Previously, the confirm button was disabled to prevent double-clicks but was never re-enabled if the database save operation failed. This left the user stuck on the screen with an unclickable button.

This wraps the save logic in a try-catch block to ensure the button is re-enabled on the UI thread if an exception occurs.

## Fixes
* Fixes  #19851

## Approach
try catch and enable the button

## How Has This Been Tested?
Pixel 10 API 36 (Physical)

## Learning (optional, can help others)
NA

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by criticalAY** [comment]
- Added test annotation

File: AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt [hunk 1]
```diff
@@ -931,10 +941,22 @@ open class CardTemplateEditor :
                     confirmButton.isEnabled = false
                 }
                 launchCatchingTask(resources.getString(R.string.card_template_editor_save_error)) {
-                    requireActivity().withProgress(resources.getString(R.string.saving_model)) {
-                        templateEditor.tempNoteType!!.saveToDatabase()
+                    launchCatchingTask(resources.getString(R.string.card_template_editor_save_error)) {
```
Comment (lukstbit) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt]: The new code creates a new coroutine inside the previous coroutine(?!). This shouldn't be needed.

Comment (criticalAY) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt]: I might have overlooked it sorry about it
