### PR TITLE
revert #14061

### LINKED ISSUE #14121: [Bug] Keyboard input not visible on SearchIcon click in LocaleSelectionDialog
###### Reproduction Steps

1. Go to Manage Note Types
2. Click on any note type
3. Click on Fields
4. Select `Set keyboard language hint`

###### Expected Result
Keyboard input is visible on SearchIcon click in LocaleSelectionDialog

###### Actual Result
Keyboard input not visible on SearchIcon click in LocaleSelectionDialog

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
AnkiDroid Version = 2.16.0beta5-debug

Android Version = 13

ProductFlavor = amazon

Manufacturer = realme

Model = RMX3521

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; RMX3521 Build/RKQ1.211119.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.196 Mobile Safari/537.36

ACRA UUID = 20b2dc80-f22d-4759-9817-396d281f95b3

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by SanjaySargam**
## Purpose / Description
Keyboard input not visible on SearchIcon click in LocaleSelectionDialog

## Fixes
Fixes #14121

## Approach
reverted #14061 

## How Has This Been Tested?
Tested on Realme 9

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/LocaleSelectionDialog.kt [hunk 1]
```diff
@@ -73,12 +74,12 @@ class LocaleSelectionDialog : AnalyticsDialogFragment() {
         inflateMenu(tagsDialogView, adapter)
 
         // Only show a negative button, use the RecyclerView for positive actions
-        val dialog = AlertDialog.Builder(activity)
-            .setView(tagsDialogView)
-            .setNegativeButton(R.string.dialog_cancel) { _, _ ->
+        val dialog = MaterialDialog(activity).show {
```
Comment (lukstbit) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/LocaleSelectionDialog.kt:77]: Also add a dialog mentioning:

`// when changing to AlertDialog make sure the keyboard is being shown when clicking search in the dialog toolbar`

so others know to look for this.

**Review by lukstbit — CHANGES_REQUESTED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/LocaleSelectionDialog.kt (hunk 1 above)
Comment (SanjaySargam) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/LocaleSelectionDialog.kt:77]: What do you mean by `add a dialog`?

Comment (lukstbit) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/LocaleSelectionDialog.kt:77]: @SanjaySargam Sorry, I asked for a comment.

Comment (SanjaySargam) [reply AnkiDroid/src/main/java/com/ichi2/anki/dialogs/LocaleSelectionDialog.kt:77]: Ohh ok. I little confused 😅😅

**Comment by SanjaySargam** [comment]
> Tried some things but didn't manage to make AlertDialog work. This revert will do for now.

Me too
