### PR TITLE
fix: "{{FrontSide}}" should be blank on front 

### LINKED ISSUE #8951: [Bug] {{FrontSide}} is treated as a field if used on the question side of a card template
###### Reproduction Steps

Add {{FrontSide}} to the questions side of any card template like so: https://www.dropbox.com/s/pz74fr93anelrk9/2021-05-25_Ankidroid_Bug.png?dl=0

###### Expected Result

{{FrontSide}} is treated as an empty string on the question side of a card. This is how Desktop-Anki does it (see screenshot above on the right).

###### Actual Result

AnkiDroid complains that there is no field called {{FrontSide}} and doesn't show the question side at all. https://www.dropbox.com/s/9oiiwef99gyhpt3/Fehlermeldung_AnkiDroid%20%28002%29.jpg?dl=0

###### Debug info
AnkiDroid 2.15.0

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have searched for similar existing issues here and on the user forum
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description
People use this - Anki has it special cased unintentionally due to hooks, but this is in use in AnkiDroid

It wasn't working before this, but the template `{{Front}}{{FrontSide}}` previously rendered as `helloworld{Unknown field FrontSide}` in 2.14.6

## Fixes
Fixes #8951

## Approach
Define the field on the front

## How Has This Been Tested?

Unit tested and tested on my phone
## Learning (optional, can help others)

Anki: https://github.com/ankitects/anki/blob/400254277bdc7b8aab0ac7eefd8f183cf9482e64/rslib/src/template.rs#L409-L417

Our change: 08217da (issue #7980)

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java [hunk 1]
```diff
@@ -1118,6 +1119,7 @@ public void updateFieldCache(String snids) {
             if ("q".equals(type)) {
                 format = fClozePatternQ.matcher(format).replaceAll(String.format(Locale.US, "{{$1cq-%d:", cardNum));
                 format = fClozeTagStart.matcher(format).replaceAll(String.format(Locale.US, "<%%cq:%d:", cardNum));
+                fields.put("FrontSide", "");
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java:1122]: This means that it will change the behavior of a note with a field named "FrontSide".
That's fine by me, but should be noted in the commit message. Or maybe even better, a unit test should be written, ensuring that we clearly see that Fields with name FrontSide are ignored

**Review by Arthur-Milchior — APPROVED** [review]

File: AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java (hunk 1 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java:1122]: Same behaviour as Anki (2.1.34), sure!

**Review by Arthur-Milchior — APPROVED** [review]
Thanks.

I trust you it's the same behavior as upstream.

**Review by mikehardy — APPROVED** [review]
LGTM
