### PR TITLE
fix(study-screen): require bigger window for "tablet" layout

### LINKED ISSUE #19764: Problems with new interface
In the new study screen the buttons at the bottom are toooooooo small. My fingers keep hitting the wrong one.  Thi s is a major difficulty.

### PR DESCRIPTION
**Pull request by BrayanDSO**
increase the required minimum smallest screen width from 600dp to 720dp

The answer buttons got cramped in smaller screens.

Also, it increases the buttons width to 60% of the screen, while keeping the 480dp limit

* Fixes #19764

## How Has This Been Tested?

Emulator 36 (resizable):

(Foldable)
Screenshot_20251213_180657

(Tablet)
Screenshot_20251213_181502

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt [hunk 1]
```diff
@@ -117,14 +116,15 @@ class ReviewerFragment :
     private lateinit var bindingMap: BindingMap<ReviewerBinding, ViewerAction>
     private var shakeDetector: ShakeDetector? = null
     private val sensorManager get() = ContextCompat.getSystemService(requireContext(), SensorManager::class.java)
+    private val isBigScreen by lazy { binding.complementsLayout != null }
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt]: Actually...

can we get into a bad state due to:

https://github.com/ankidroid/Anki-Android/blob/46cc209b9552b9354a0e9ef74e06cb14dbdfd3e8/AnkiDroid/src/main/AndroidManifest.xml#L463-L467

**Review by david-allison — CHANGES_REQUESTED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt (hunk 1 above)
Comment (BrayanDSO) [reply AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt]: replaced `by lazy` with `get()`

**Comment by mikehardy** [comment]
@vnams - you raised the original issue, how do the screenshots of the proposed new interface look? An improvement?

**Comment by vnams** [comment]
> @vnams - you raised the original issue, how do the screenshots of the proposed new interface look? An improvement?
I'm not sure how to see them. I see the "Show Answer" screen above, but not the other ones.
