### PR TITLE
Strip HTML comments in card browser

### LINKED ISSUE #5395: Card browser shows the contents of a HTML element that is inside of a HTML comment
###### Reproduction Steps

1. Create a template that has a HTML element, `<details>`, inside of a HTML comment,` <!-- comment -->`.  This example is from one of my templates:

`<!-- Show the Extra field in a <details> disclosure widget if Extra is not empty-->`

Note that `<details>` is not a real element since it is in a comment

2. Go to the card browser
3. The card browser shows everything after the `<details>` tag. Picture below

Screenshot_2019-07-25-14-05-02

###### Expected Result
Card Browser should ignore HTML tags that are inside of a HTML comment tag on the template

###### Actual Result
If there is a HTML element inside of a HTML comment tag, the card browser will show the contents of that element

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
AnkiDroid Version = 2.9beta3

Android Version = 7.0

ACRA UUID = dfeef969-fa5d-43f8-8f41-00761d1ba055

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[X ] I have searched for similar existing issues here and on the user forum

### PR DESCRIPTION
**Pull request by snoyes**
## Purpose / Description
https://github.com/ankidroid/Anki-Android/blob/bcc13aaf374725af69159bc4c7f68ea0d2fa3ea9/AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java#L101

The tagPattern regexp does not properly handle tags which contain a ">" character within them, such as an HTML comment like `<!-- the <b> tag -->`

## Fixes
Fix #5395

## Approach
Since HTML is not "regular", trying to fix the regular expression to handle such cases seems futile. Instead, HTML comments are stripped prior to calling `stripHTMLMedia`.

## How Has This Been Tested?

Tested on physical device.

## Learning (optional, can help others)
According to the HTML spec, comments cannot contain `-->`, so if somebody writes `<!-- a <!-- nested --> comment -->` we are under no obligation to honor it.

https://www.w3.org/TR/html4/intro/sgmltut.html#h-3.2.4 indicates that the comment closing may contain whitespace, e.g. `--  >`. However the HTML5 spec does not mention that, and Chrome didn't seem to understand it, so I left it out.

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java [hunk 1]
```diff
@@ -1331,7 +1331,9 @@ public static void updateSearchItemQA(Map<String, String> item, Card c) {
 
     private static String formatQA(String txt) {
         /* Strips all formatting from the string txt for use in displaying question/answer in browser */
-        String s = txt.replace("<br>", " ");
+        String s = txt;
+        s = s.replaceAll("<!--.*?-->", "");
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java]: This is just for the small QA chunks and the template never passes through here right?

I ask because it seems like 7 string copy / modification cycles is a bit much, but if the text is small performance is inconsequential vs code complexity

If the expected text could be large though I wonder if we could do one pattern that handled all of them? As a static this one could be a prime spot for a `@VisibleForTesting` unit test so as not to shoot feet while attempting.

I think the text is small so then this would be a nice targeted change. Possibly enough internet points to trade in for at least a pixelated silver medal :2nd_place_medal:  at this point hahaha

Comment (snoyes) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java]: The only two lines that call formatQA are putting the question and answer into the card browser list. The template never goes through it.

7 is too much, but 6 was ok? 😉

What if we change it to:
```
        String s = txt
            .replaceAll("<!--.*?-->", "")
            .replace("<br>", " ")
            .replace("<br />", " ")
            .replace("<div>", " ")
            .replace("\n", " ")
            .replaceAll("\\[sound:[^]]+\\]", "")
            .replaceAll("\\[\\[type:[^]]+\\]\\]", "");
```

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java]: If it's small - I'd ignore it - just wanted to examine briefly, and with small text 20 would be fine :-)

Comment (snoyes) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java]: Well, I don't actually know that it's small. It's the rendered question and answer. I suppose in theory that could be large, depending on your definition of "large". Unlikely to be more than a few KB anyway.

**Comment by timrae** [comment]
No idea why the build is failing on SDK 24... I guess we should just ignore it?

**Comment by mikehardy** [comment]
If you look at which API24 it is the one we have configured for jdk11, and is set to ignore - it's the last in the last and will not pass until some other work is done. It is there mostly as a proof of concept for build matrices in travis but shouldn't fail CI

**Comment by mikehardy** [comment]
Tim already liked it, I'm fine with it, and the only marginally related CI failure was addressed in #5594 which fixed JDK11 in Travis
