### PR TITLE
BugFix - Previewer: Display same card after edit

### LINKED ISSUE #7801: Editing cards in preview mode modifies previewed cards
###### Reproduction Steps

1. Seleccionar 2 o más tarjetas en el explorador de mazos.
2. Seleccionar vista previa.
3. Editar uno o más campos en la tarjeta seleccionada desde la vista previa.
4. Confirmar edición (✓).

###### Expected Result

Los cambios se guardan y la tarjeta editada debería aparecer con los cambios recien efectuados en vista previa.

###### Actual Result

Los cambios se guardan pero la aplicación reaparece en una tarjeta diferente o en el listado de exploración, y es necesario repetir el proceso para editar la siguiente tarjeta.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison**
Editing a note would call UPDATE_NOTE with parameter `isReviewer:true`.

If the card was not in the same deck as the 'currently active' deck, then
the next card was obtained from the scheduler

The UPDATE_NOTE callback gets this card and renders it, even though it's not being previewed, showing the wrong card

## Fixes
Fixes #7801

## Approach
Now, we pass a new boolean, which skips the scheduler when not reviewing

This means we still update the content, but without getting another CardId

## How Has This Been Tested?

Android 9 device, and unit tests

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 1]
```diff
@@ -1013,6 +1013,15 @@ public boolean onKeyDown(int keyCode, KeyEvent event) {
     }
 
 
+    @Override
+    protected Long getCurrentCardId() {
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:1017]: `@Nullable` maybe?

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 2]
```diff
@@ -1150,6 +1150,11 @@ protected void onActivityResult(int requestCode, int resultCode, Intent data) {
     }
 
 
+    protected boolean canAccessScheduler() {
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:1153]: perhaps a quick note on the intent of this, what it controls, for future explorers?

**Review by mikehardy — APPROVED** [review]
LGTM and this is a gross area but with this it should work well again for a while and have testing to keep it on the rails, nice

Just doc-type requests, so marking for prelim approval, after addressing and then asserting you've tested it local, feel free to merge!

**Comment by mikehardy** [comment]
I did mark this for a 2.14.3 but I'm not sold on releasing that, at some point you have to close the door and say use the alpha to affected users + focus on next

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java (hunk 1 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:1017]: Also added to the overridden method

**Review by mikehardy — APPROVED** [review]
LGTM again :)
