### PR TITLE
fix: exit message when using the review shortcut

### LINKED ISSUE #10840: [Bug] Crash: Tapping "Study" shortcut ends up closing AnkiDroid immediately without any explanation if the last-selected deck doesn't have any "due" cards
Thank you always, developers.

###### Reproduction Steps

1. On `Decks` screen, tap a deck which doesn't have any "due" cards* at the moment
*it includes the case that the deck is emptyimage
image

2. Press Back button (twice if necessary), or close AnkiDroid completely. Anyway, go back to Android Home screen 
image
3. Long tap (press) AnkiDroid app icon
4. Tap `Study` on the shortcut menu
image

###### Expected Result
AnkiDroid shows some message which explains the last-selected deck doesn't have any due cards at the moment (or is empty).
image
image

###### Actual Result
AnkiDroid "crashes". I mean, it closes immediately and unexpectedly without any explanation.
image

https://user-images.githubusercontent.com/10436072/163364495-e5c91b4e-0635-418b-9df1-6e50e979fd51.mp4

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release 
  (2.16alpha58)

### LINKED ISSUE #10841: [Bug] Crash: Studying all "due" cards started from "Study" shortcut ends up closing AnkiDroid without returning to Decks screen with "Congraturations!" snackbar
###### Reproduction Steps

1. On Decks screen, tap a deck which has one or more "due" cards
image
 (Then, Study screen gets shown)
image
2. Go back to Android Home screen
 (ex. press Back button twice [or more if necessary] )
3. Long tap (press) AnkiDroid app icon
4. Tap `Study` on the shortcut menu.
image
 (Then, Study screen gets shown again)
image
5. Answer all "due" cards in the deck.
image

###### Expected Result
Decks screen with `Congratulation! You have finished for now.` snackbar gets shown.
image

###### Actual Result
AnkiDroid "crashes". I mean, it closes unexpectedly without any explanation.
image

https://user-images.githubusercontent.com/10436072/163378134-a9eb0498-900a-41a8-bbfc-e060ab6e18b7.mp4

###### Debug info
```
AnkiDroid Version = 2.16alpha56

Android Version = 9

Manufacturer = OPPO

Model = CPH1983

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 9; CPH1983 Build/PKQ1.190519.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.73 Mobile Safari/537.36

ACRA UUID = 69410480-0b9c-401f-ae8d-94da0f29c9dc

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

```
###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release 
  (2.16alpha58)

### PR DESCRIPTION
**Pull request by fred-sab**
## Purpose / Description
When using a [shortcut](https://developer.android.com/guide/topics/ui/shortcuts) for review, we may need to inform the user when exiting the activity:
- If we successfully completed the review (otherwise the user is surprised of the sudden exit #10841)
- If there's nothing to review (otherwise the user doesn't understand why the app just opens and closes #10840)

The shortcuts were recently introduced with #8648.

## Fixes
Fixes #10841: display a message when the review is completed
fixes (partially) #10840: display a message when no card to review (but ideally the message should be "no cards to review" rather than "review finished")

## Approach
As suggested [here](https://github.com/ankidroid/Anki-Android/issues/8648#issuecomment-822581182), use a Toast to inform the user.

#10840 and #10841 suggested to return to the main view when finishing. 
However, in my opinion, the purpose of shortcuts is to quickly perform the desired action (add note, review, view notes). Therefore, exiting when finishing or having no cards to review is more coherent, wdyt?
Also, the current approach allows to keep the complexity minimal.

## How Has This Been Tested?
- With a Pixel 5 API 31 Emulator
- With a Samsung Galaxy S7

Test that a message is displayed when the review is completed #10841:
10841_review_completed

Test that a message is displayed when nothing to review #10840:
10840_no_card

## Learning (optional, can help others)
About shortcuts: https://developer.android.com/guide/topics/ui/shortcuts

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars). 
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)
  - Is it relevant for this change?

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
This seems like a nice approach to me, and is a nice small + tidy change

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt [hunk 1]
```diff
@@ -489,6 +489,11 @@ abstract class AbstractFlashcardViewer :
             val nextCardAndResult = result.value
             if (nextCardAndResult.hasNoMoreCards()) {
                 closeReviewer(RESULT_NO_MORE_CARDS, true)
+
+                // When launched with a shortcut, we want to display a message when finishing
+                if (intent.getBooleanExtra(EXTRA_STARTED_WITH_SHORTCUT, false)) {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt:494]: Very minor: could you add a `@NeedsTest("explanation")` annotation to the the top of the method where you've added the functionality

**Review by david-allison — CHANGES_REQUESTED** [review]
Looks great, thanks! One minor request so we can improve testing in future

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt (hunk 1 above)
Comment (fred-sab) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt:494]: I added a test instead, does it look good to you?

**Review by david-allison — CHANGES_REQUESTED** [review]
Absolutely going above & beyond! One nitpick to allow the tests to run on non-English machines (this may not be necessary)

**Review by david-allison — APPROVED** [review]
Beautiful, if tests pass, I'm happy

File: AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt [hunk 2]
```diff
@@ -219,6 +220,14 @@ class AbstractFlashcardViewerTest : RobolectricTest() {
         assertThat("no auto answer after onRenderProcessGone when paused", viewer.hasAutomaticAnswerQueued(), equalTo(false))
     }
 
+    @Test
+    fun shortcutShowsToastOnFinish() {
```
[the remark this answers is not in the document]
Comment (fred-sab) [reply AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.kt:224]: Thanks for the hint! And referencing the resource string seems like a good practice :)

**Review by mikehardy — APPROVED** [review]
really nice!

**Comment by david-allison** [comment]
Thanks so much for this!
