### PR TITLE
fix: various startup issues

### LINKED ISSUE #14650: [full build] - Sync From AnkiWeb -> Can't create AnkiDroid folder
###### Reproduction Steps

1. Clean Install AnkiDroid Alpha 3 
2. Open the app
3. Choose Sync from AnkiWeb
4. Enter your mail and it says it can't create AnkiDroid folder  

###### Expected Result
Before entering login credentials, it should ask for All files access which is the way it is when you choose Get Started

###### Actual Result
Error not being able to create AnkiDroid folder
`com.ichi2.anki.exception.StorageAccessException: Failed to create AnkiDroid directory / storage/emulated/0/AnkiDroid
`
###### Research
- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
* #14650
* Fix follow-on issues + add more logs
   *  Not moving from `Register -> Deck Picker`
   * Not automatically syncing
   * 'Card Browser' not working 

## Fixes
* Fixes #14650

## Approach
* Extract startup functionality to an interface
* Fix follow-on issues + add more logs
* Fix follow-up with `hasShownAppIntro`
* I knew there was a problem with 'Card Browser', so also fix this

## How Has This Been Tested?
Manually on a `full` build

## Learning (optional, can help others)
* We need many more tests here

`every { any<AnkiActivity>().hasCollectionStoragePermissions() }` in `mockk`

A callback to an ActivityLaunch wasn't fired at all as there was no call to `setResult(RESULT_OK)`

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/introduction/CollectionPermissionScreenLauncher.kt [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+import com.ichi2.anki.AnkiActivity
+import com.ichi2.anki.selectAnkiDroidFolder
+import com.ichi2.anki.ui.windows.permissions.PermissionsActivity
+import timber.log.Timber
+
+/**
+ * Launcher for [PermissionsActivity]
+ * @see collectionPermissionScreenWasOpened
+ */
+interface CollectionPermissionScreenLauncher {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/introduction/CollectionPermissionScreenLauncher.kt:32]: Kotlin interfaces act as traits

BUT: `ActivityResultLauncher` must be a field, not a property, as it needs to be setup on `init { }`, so we can't hide the property in the interface

**Review by mikehardy — APPROVED** [review]
Nice - code LGTM and it works for me locally, solved a few oddities that I had noted but not logged on that fresh install + login from intro activity usage path

**Comment by mikehardy** [comment]
going with it - this batch of fix is a major UX improvement for any one rolling through first install path
