### PR TITLE
Fix: filters usage

### LINKED ISSUE #10715: Fix `Filter` usage
> @david-allison Maybe I should add some todos to the places were I replaced FilterResultsUtils?

I'll deal with it today - embarrassing that a lot of that was my copy/pasted code

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/issues/10712#issuecomment-1088958885_

### PR DESCRIPTION
**Pull request by david-allison**
I cargo-culted this implementation, and should have spent time improving the implementation

## Fixes
Fixes #10715

## Approach
* Define `TypedFilter`: a strongly typed `Filter`
* Use `TypedFilter`: use the `results` variable in `publishResults` rather than a local
* Some Kotlin Cleanup

## How Has This Been Tested?
Unit tested, and tested on my device

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/utils/TypedFilter.kt [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+
+        return FilterResults().also {
+            it.values = items
+            it.count = items.size
+        }
+    }
+
+    @Suppress("UNCHECKED_CAST")
+    override fun publishResults(constraint: CharSequence?, results: FilterResults?) {
+        val list = results!!.values as List<T>
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/utils/TypedFilter.kt:52]: it worries me in a utility function to see the cast unchecked and the not-nullness disregarded. Since it's reusable/re-used code, does it hurt too much to check the cast and the null?

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/utils/TypedFilter.kt:52]: This is only ever called with the results from `publishResults`, which guarantees the constraints are held. I'll add this as a comment.

**Review by mikehardy — APPROVED** [review]
OK - LGTM
