### PR TITLE
Show notifications even when app is in background (fixes #4615)

### LINKED ISSUE #4615: Notification only shown when app is opened
###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Enable notifications on more than 10 due cards.
2. Enter some Cards
3. Wait until more than 10 cards are due. 

###### Expected Result
A notification should be shown without opening the app.

###### Actual Result
I have to open the app, then a notification is shown. But this does not make sense as I can see the due cards in the allready opened app.

###### Debug info
AnkiDroid Version = 2.8.2
Android Version = 6.0.1
ACRA UUID = 78549792-7916-4041-a6b2-b58d85214139

### PR DESCRIPTION
**Pull request by Nutomic**
Finally got around to this. There seems to be some bug left, as I couldn't get the Notification to show during my testing. This might have to do with the behaviour of `setInexactRepeating()`, according to the documentation, "there may be a delay of almost an entire alarm interval before the first invocation of the alarm" (so almost 24 hours delay in our case). We might have to use a different method to schedule the alarm instead.

By the way, I noticed that `BootService` would *only* get started by a device boot. In the following cases, it would never run:
- app is newly installed/updated
- app is force stopped and started again

I've added the line `startService(new Intent(this, BootService.class))` in `AnkiDroidApp` to make sure it is always started.

### CODE REVIEW

**Comment by Nutomic** [comment]
Fixed, just need to handle settings changes now.

**Comment by Nutomic** [comment]
Should be complete now, assuming I understood the settings right.

**Comment by timrae** [comment]
@madhead 

Would you be able to review this?

**Comment by madhead** [comment]
@Nutomic 

Regarding the `BootService`:

>app is newly installed/updated

In case of fresh installation there will be no existing notification preferences. Not sure about application updates, but maybe the existing alarms will work?

>app is force stopped and started again

But it implies that the device already booted, so the alarms are in place.

Regarding to the SO answers and articles I've read, boot (completed) event is enough for the notifications to work after reboots: [1](https://stackoverflow.com/a/9765413/750510), [2](https://stackoverflow.com/a/8461275/750510).

Also, I see this code touches existing logic for the widget, isn't it? What is the purpose?

Thanks!

**Comment by madhead** [comment]
@timrae, what were the original reasons of declining #4006 / #4450 was it only "inexact" timing or there were other defects?

Thanks!

**Comment by timrae** [comment]
@madhead 

Thanks for the review.

"Decline" is a strong word; it's in the master (i.e. 2.9 branch), just not in the 2.8 release. :)
As far as I remember #4525 and #4530 were the main ones, but here is the list of notification related issues:

https://github.com/ankidroid/Anki-Android/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3Aadvanced-reminders%20

**Comment by Nutomic** [comment]
@madhead One easy way to break it is by running the app from Android Studio. That's not a boot, so the receiver will not be called (verified with logs). The same thing should happen if the app is updated from Google Play, or if the app is force stopped from app settings, and started again.

Regarding the widget, it was starting the NotificationService on every update. Now that the service is started automatically via the BootService, there's no reason to start it from the widget any more.

**Comment by Nutomic** [comment]
@timrae Most of these issues seem related to the app logic/settings logic, nothing I can comment on. But #4525 is caused by the fact that you are using `setInexactRepeating()`. But tbh 7 minutes delay seems fine to me.

**Comment by timrae** [comment]
7 minutes delay is ok but you know some of users are fanatics, and they don't like it... Also, people who were testing the feature for the first time will keep opening issues to say that it's "broken", which wastes our time as well :-/ when I looked into it, it seemed very easy to make it more exact, you just have to set a new alarm each time it gets fired

**Comment by timrae** [comment]
Honestly I'm not super knowledgeable about services in Android, and haven't looked through the code in detail, but a pre-requisite for accepting this PR is that it doesn't noticeably impact battery usage, so I'm worried that the service is gonna be permanently running.

**Comment by Nutomic** [comment]
Its the same service that was there before, and its only started once (doesnt run in background). Using exact alarms would increase battery usage in theory, but that's probably not noticeable if its only once per day.

File: AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.java [hunk 1]
```diff
@@ -15,14 +19,29 @@
...
+    private static boolean sWasRun = false;
+
     public BootService() {
         super("BootService");
     }
 
     @Override
     protected void onHandleIntent(Intent intent) {
-        final AlarmManager alarmManager = (AlarmManager) getSystemService(ALARM_SERVICE);
+        if (sWasRun)
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.java]: Please use braces with your one-line `if` statements

File: AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.java [hunk 2]
```diff
@@ -62,4 +81,24 @@ protected void onHandleIntent(Intent intent) {
             throw new RuntimeException(e);
         }
     }
+
+    public static void scheduleNotification(Context context) {
+        AlarmManager alarmManager = (AlarmManager) context.getSystemService(ALARM_SERVICE);
+        SharedPreferences sp = PreferenceManager.getDefaultSharedPreferences(context);
+        if (Integer.parseInt(sp.getString("minimumCardsDueForNotification", "1000001")) <= 1000000)
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.java]: Maybe it's time we separated this into two settings instead of using the "magic number" 1000000 to represent "pending messages available"? We originally did this in an attempt to minimize the number of settings, but it's kind of counter-productive here.

**Comment by timrae** [comment]
@madhead @Nutomic 

I think it's a bit confusing having two different places where notifications are set... Maybe we can merge these two similar features to some extent? Is the main motivation for #4530 to allow opting-out of notifications for specific decks? Or is it to have a separate reminder (with a separate notification time) for each deck?

**Comment by Nutomic** [comment]
Yes I think it makes sense to seperate the notification settings. But I'm don't think it necessarily belongs into this PR. Also, like I said, I'm not really familiar with the settings.

**Comment by madhead** [comment]
>Or is it to have a separate reminder (with a separate notification time) for each deck?

The original idea was this. Each deck can remind about itself at some time of the day, independently of others.

**Comment by timrae** [comment]
At the moment it's done on a per-note-type rather than per-deck basis though, right?

**Comment by timrae** [comment]
I fixed the failing build issue, so if you could also rebase onto the latest master that would be appreciated!

```bash
git fetch --all
git rebase upstream/master
git push origin background-notifications -f
```

**Comment by Nutomic** [comment]
done ;)

**Comment by timrae** [comment]
Thanks! Can you add the missing curly braces as well?

**Comment by Nutomic** [comment]
Right, I missed your comment before.
