### PR TITLE
fix: DeckOptions on API 23

### LINKED ISSUE #15790: [BUG]: Deck options shows blank screen - impossible to edit deck options, AnkiDroid ignores deck options synchronized through AnkiWeb.
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Run AnkiDroid, enter any deck, open top right menu, select Deck Options.

### Expected behaviour

I can edit options.

### Actual behaviour

Screen is blank.

### Debug info

```text
AnkiDroid Version = 2.17.1 (dd2f3762fb214f9dd51162b215974b23cc809713)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 6.0 (SDK 23)

ProductFlavor = play

Manufacturer = HUAWEI

Model = ALE-L21

Hardware = hi6210sft

Webview User Agent = Mozilla/5.0 (Linux; Android 6.0; ALE-L21 Build/HuaweiALE-L21; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36

ACRA UUID = 8962faad-c74a-4c1c-86bb-67131cf5f770

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

AnkiDroid ignores deck options synchronized through AnkiWeb. 
I created a deck locally (AnkiDesktop) synchronized with AnkiDroid with own set of options, eg. 5 new cards per day. AnkiDroid ignores these settings, e.g. does not show any of new cards to be learned at all. They must be selected trough "custom study" feature everytime. I am unable to check what options this deck is using due to the blank screen.
In other decks (created before update to current AnkiDroid version), AnkiDroid started to show new cards dispersed among reviews, although in AnkiDroid / AnkiWeb they've always been set to be shown after repetitions. I am unable to check the options due to the blank screen.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison**
URL was changed to `page-fully-loaded:` which caused a failure

Massive thank you to our backers for this one!

## Fixes
* Fixes #15790

## Approach
* Handle `page-fully-loaded:`

## How Has This Been Tested?
* Huawei P8 Lite - Android 6.0 (ALE-L21)

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/pages/PageWebViewClient.kt [hunk 1]
```diff
@@ -83,14 +83,30 @@ open class PageWebViewClient : WebViewClient() {
...
     override fun shouldOverrideUrlLoading(view: WebView?, request: WebResourceRequest?): Boolean {
         if (view == null || request == null) return super.shouldOverrideUrlLoading(view, request)
-        if (request.url.toString() == "page-fully-loaded:") {
+        if (filterUrl(view, request.url.toString())) {
+            return true
+        }
+        return super.shouldOverrideUrlLoading(view, request)
+    }
+
+    private fun filterUrl(view: WebView, url: String): Boolean {
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/pages/PageWebViewClient.kt:103]: nit: TBH, I don't think that  `filterUrl` is a good name here, although that's the name used in AbstractFlashcardViewer.

`shouldOverrideUrl`, `handleUrl`, even repeating `shouldOverrideUrlLoading` would be better IMO.

**Review by BrayanDSO — APPROVED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/pages/PageWebViewClient.kt (hunk 1 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/pages/PageWebViewClient.kt]: Sure, I picked it specifically to be consistent

**Review by lukstbit — APPROVED** [review]

**Comment by lukstbit** [comment]
@mikehardy Just so you see this.
