### PR TITLE
Fix paste from browser into note field not working

### LINKED ISSUE #11574: [Regression] Samsung browser copy paste is broken
###### Reproduction Steps

1. Open a web Page and copy a text
2. Edit a card in Ankidroid
3. Paste to a blank field

###### Expected Result

The text is pasted to the field.

###### Actual Result

The text is not pasted. The field remains empty.
To open clipboard and paste works.

###### Debug info

AnkiDroid Version = 2.16alpha67

Android Version = 11

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-A225F Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/102.0.5005.78 Mobile Safari/537.36

ACRA UUID = 279377fa-c607-444b-8d1e-0ac5b2f9a752

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by dorrin-sot**
## Purpose / Description
Pasting plain text from samsung native browser into note fields wouldn't work.

## Fixes
Fixes #11574

## Approach
rewrote `FieldEditText::onTextContextMenuItem` to paste as plain text using `coerceToText` in `primaryClip.getItemAt(0).coerceToText(context)`.

## How Has This Been Tested?
Tested on real device:

https://user-images.githubusercontent.com/59933477/174403631-6412f7dc-07a6-4d67-9b02-7132795fd2b0.mp4

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt [hunk 1]
```diff
@@ -193,35 +193,22 @@ class FieldEditText : FixedEditText, NoteService.NoteField {
...
-             * the user's clipboard, and hence has not been used.
-             *
-             * During testing, older devices pasted text as plain text by default,
-             * so there was no need for a TO-DO
-             */
-            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
-                _id = android.R.id.pasteAsPlainText
+            if (hasImage(mClipboard)) {
+                return onImagePaste(getImageUri(mClipboard))
+            } else if (mClipboard?.hasPrimaryClip() == true) {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt:201]: don't need an `else` - previous statement is a return

File: AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt [hunk 2]
```diff
@@ -193,35 +193,22 @@ class FieldEditText : FixedEditText, NoteService.NoteField {
...
+                mClipboard?.primaryClip?.run {
+                    this@FieldEditText.run {
+                        setText("${text}${getItemAt(0).coerceToText(context)}")
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt:204]: `get(0)` can throw an IndexOutOfBoundsException if you don't check the size.

**Review by david-allison — CHANGES_REQUESTED** [review]
Looks great to me!

File: AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt [hunk 3]
```diff
@@ -198,12 +200,15 @@ class FieldEditText : FixedEditText, NoteService.NoteField {
...
                 mClipboard?.primaryClip?.run {
-                    this@FieldEditText.run {
-                        setText("${text}${getItemAt(0).coerceToText(context)}")
-                        setSelection(text!!.length)
-                    }
+                    this@FieldEditText
+                        .takeIf { itemCount > 0 }
+                        ?.run {
+                            setText("${text}${getItemAt(0).coerceToText(context)}")
+                            setSelection(text!!.length)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt:210]: Is this correct? If I paste something in, typically I don't want the whole text to be selected. This doesn't match typical UX

Comment (dorrin-sot) [reply AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt:210]: this sets the cursor at the end. `setSelection(0, text!!.length)` would select all

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt:210]: Oh, sorry. But again: that isn't the standard UX, right?

Comment (dorrin-sot) [reply AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt]: Oh Sorry I didn't think of that. I fixed it now and also added a test

File: AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt [hunk 4]
```diff
@@ -193,35 +198,33 @@ class FieldEditText : FixedEditText, NoteService.NoteField {
...
-             *
-             * During testing, older devices pasted text as plain text by default,
-             * so there was no need for a TO-DO
-             */
-            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
-                _id = android.R.id.pasteAsPlainText
+    @VisibleForTesting(otherwise = VisibleForTesting.PRIVATE)
+    fun pastePlainText(): Boolean {
+        getPlainText(mClipboard, context)?.let { pasted ->
+            selectionStart.run {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt:215]: This feels like overuse of scope functions

File: AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt [hunk 5]
```diff
@@ -193,35 +198,33 @@ class FieldEditText : FixedEditText, NoteService.NoteField {
...
+                // setText also sets selectionStart to 0
+                setText(
+                    text!!.substring(
+                        0,
+                        selectionStart
+                    ) + pasted + text!!.substring(selectionEnd)
+                )
+                setSelection(this + pasted.length)
+                return true
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt:224]: `selectionStart` is not guaranteed to be smaller than `selectionEnd`. A user can select backwards using a keyboard.

**Review by david-allison — CHANGES_REQUESTED** [review]

**Review by david-allison — CHANGES_REQUESTED** [review]

**Review by david-allison — APPROVED** [review]
Thanks! Selection code is horrible

**Review by mikehardy — APPROVED** [review]
alright then :-), quite a fix on this one, thanks!
