### PR TITLE
fix: replace cloze with blank within <tts> tag

### LINKED ISSUE #12233: When using the `<tts>` tag to only read a small selection of text, cloze `[...]` are not read as "blank."
Hello all. When using the `<tts>` tag to only read a small selection of text, cloze `[...]` are not read as "blank." TTS simply doesn't read them.

Perhaps the `.text().replace(TemplateFilters.CLOZE_DELETION_REPLACEMENT, clozeReplacement!!)` should be applied outside of the `if` statement below?

```java
object TtsParser {
    /**
     * Returns the list of text snippets contained in the given HTML fragment that should be read
     * using the Android text-to-speech engine, together with the languages they are in.
     *
     *
     * Each returned LocalisedText object contains the text extracted from a &lt;tts&gt; element
     * whose 'service' attribute is set to 'android', and the localeCode taken from the 'voice'
     * attribute of that element. This holds unless the HTML fragment contains no such &lt;tts&gt;
     * elements; in that case the function returns a single LocalisedText object containing the
     * text extracted from the whole HTML fragment, with the localeCode set to an empty string.
     */
    @JvmStatic
    fun getTextsToRead(html: String, clozeReplacement: String?): List<TTSTag> {
        val textsToRead: MutableList<TTSTag> = ArrayList()
        val elem = Jsoup.parseBodyFragment(html).body()
        parseTtsElements(elem, textsToRead)
        if (textsToRead.isEmpty()) {
            // No <tts service="android"> elements found: return the text of the whole HTML fragment
            textsToRead.add(readWholeCard(elem.text().replace(TemplateFilters.CLOZE_DELETION_REPLACEMENT, clozeReplacement!!)))
        }
        return textsToRead
    }
```

_Originally posted by @KendallPark in https://github.com/ankidroid/Anki-Android/issues/6336#issuecomment-1230845669_

### PR DESCRIPTION
**Pull request by KendallPark**
resolves ankidroid/Anki-Android#12233

## Purpose / Description
#12233

## Fixes
Fixes #12233

## Approach
Adds `replace` to another line of code which handles text within a `tts` tag.

## How Has This Been Tested?

Added a test for the `<tts service="android">` tag. It fails without the fix, passes with the fix.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by KendallPark** [comment]
Didn't add comments as changes are trivial.

**Review by david-allison — APPROVED** [review]
Awesome, thanks so much!

File: AnkiDroid/src/main/java/com/ichi2/anki/TtsParser.kt [hunk 1]
```diff
@@ -26,23 +26,23 @@ object TtsParser {
...
         return textsToRead
     }
 
-    private fun parseTtsElements(element: Element, textsToRead: MutableList<TTSTag>) {
+    private fun parseTtsElements(element: Element, textsToRead: MutableList<TTSTag>, clozeReplacement: String?) {
         if ("tts".equals(element.tagName(), ignoreCase = true) &&
             "android".equals(element.attr("service"), ignoreCase = true)
         ) {
-            textsToRead.add(localisedText(element.text(), element.attr("voice")))
+            textsToRead.add(localisedText(element.text().replace(TemplateFilters.CLOZE_DELETION_REPLACEMENT, clozeReplacement!!), element.attr("voice")))
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/TtsParser.kt:41]: :thinking: clozeReplacement is `String?` coming in, but then `!!`ed here. Is that right?

**Review by mikehardy — CHANGES_REQUESTED** [review]
Thanks for taking this up! I'm unsure on the `!!` treatment, given it's an optional param, what happens when it's null?

File: AnkiDroid/src/main/java/com/ichi2/anki/TtsParser.kt (hunk 1 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/TtsParser.kt:41]: Yes, still pending Kotlin nullability fixes 

`context.getString(R.string.reviewer_tts_cloze_spoken_replacement)`

Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/TtsParser.kt:41]: I'll put in a follow-up PR to clean this

Comment (KendallPark) [reply AnkiDroid/src/main/java/com/ichi2/anki/TtsParser.kt:41]: @mikehardy I'm not a Kotlin dev, so I couldn't say what that's about. I simply copied the code and conventions from line 32 and the surrounding function.

Seems to be a side effect of: https://github.com/ankidroid/Anki-Android/commit/effe98771a40cd12286a55e5a3677cbd8eeb194a

**Comment by KendallPark** [comment]
Tested on my phone and it is working as expected.

File: AnkiDroid/src/main/java/com/ichi2/anki/TtsParser.kt (hunk 1 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/TtsParser.kt:41]: Thanks David - that makes sense, and thanks again Kendall

**Review by mikehardy — APPROVED** [review]
