### PR TITLE
Fix pie chart in statistics

### LINKED ISSUE #4319: Statistics - are my graphs wrong for card types?
###### Research

_Enter an [ x ] character to confirm the points below:_

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum
###### Reproduction Steps
1. Open up AnkiDroid 
2. Open up statistics via left panel
3. Go to card types pie chart
###### Expected Result

Displays the pie chart according to legend (%) for the current deck.
###### Actual Result

Colours dont seem to match up to the stats (sorry for the gigantic images), I've attached images for all 3 filters which are month, year and alltime.

alltime
month
year`
###### Debug info

Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.5.4
Android Version = 6.0.1
ACRA UUID = 125db60d-bab3-48e4-82a7-6c52f203eb46

### PR DESCRIPTION
**Pull request by dmitry-timofeev**
Fixes #4319 
- Fix sectors drawing when there are zero values
- Make `PieChart` clients responsible for providing a complete color legend
- Add local unit tests

### CODE REVIEW

File: AnkiDroid/src/main/java/com/wildplot/android/rendering/PieChart.java [hunk 1]
```diff
@@ -24,29 +24,23 @@
...
-	public PieChart(PlotSheet plotSheet, double[] vals){
-		this.mPlotSheet = plotSheet;
-		mValues = vals;
-		//mValues = new double[] {5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5};
+    private double[] mPercent;
+    private double mSum;
+
+    public PieChart(PlotSheet plotSheet, double[] values, ColorWrap[] colors) {
+        checkArguments(plotSheet, values, colors);
+		mPlotSheet = plotSheet;
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/wildplot/android/rendering/PieChart.java]: Can you fix the indentation here?

File: AnkiDroid/build.gradle [hunk 2]
```diff
@@ -61,6 +61,14 @@ dependencies {
     compile 'com.jakewharton.timber:timber:2.7.1'
     compile 'com.google.code.gson:gson:2.4'
     compile project(":api")
+
+    testCompile 'junit:junit:4.12'
```
Comment (timrae) [inline AnkiDroid/build.gradle]: Does anyone have any objections to including this extra dependencies?

File: AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartTestParametersBuilder.java [hunk 3]
```diff
@@ -0,0 +1,84 @@
...
+
+
+import com.wildplot.android.rendering.graphics.wrapper.ColorWrap;
+
+import static java.lang.String.format;
+import static org.powermock.api.mockito.PowerMockito.mock;
+import static org.powermock.api.mockito.PowerMockito.when;
+
+final class PieChartTestParametersBuilder {
+    private final double[] values;
```
Comment (timrae) [inline AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartTestParametersBuilder.java]: Member variables should have an `m` prefix.

File: AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartTestParametersBuilder.java [hunk 4]
```diff
@@ -0,0 +1,84 @@
...
+    }
+
+    private void calcArcLengths() {
+        for (int i = 0; i < numberOfValues; i++) {
+            arcLengths[i] = 360.0 * values[i] / sum;
+        }
+    }
+
+    private void calcStartAngles() {
+        startAngles[0] = firstSectorAngle;
```
Comment (timrae) [inline AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartTestParametersBuilder.java]: This isn't really great, as `startAngles` could be empty.

File: AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartParameterizedTest.java [hunk 5]
```diff
@@ -0,0 +1,154 @@
...
+        for (double[] v : values) {
+            parameters.add(createParameters(v));
+        }
+        return parameters;
+    }
+
+    private static Object[] createParameters(double[] values) {
+        PieChartTestParametersBuilder builder = new PieChartTestParametersBuilder(values,
+                PieChart.FIRST_SECTOR_OFFSET);
+        return new Object[] {
```
Comment (timrae) [inline AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartParameterizedTest.java]: It's better to make a container class to hold these values, as you lose the type-checking and bounds-checking features of the language with an `Object[]`.

File: AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartParameterizedTest.java [hunk 6]
```diff
@@ -0,0 +1,154 @@
...
+                values,
+                builder.getStartAngles(),
+                builder.getArcLengths(),
+                builder.getColors()
+        };
+    }
+
+    private static double[] values(double... d) {
+        return d;
```
Comment (timrae) [inline AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartParameterizedTest.java]: What's the point of this method? It doesn't appear to be doing anything useful.

File: AnkiDroid/src/main/java/com/wildplot/android/rendering/PieChart.java (hunk 1 above)
Comment (dmitry-timofeev) [inline AnkiDroid/src/main/java/com/wildplot/android/rendering/PieChart.java]: Sure, I'll replace then a few code indented with tabs with spaces in the whole file.

File: AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartTestParametersBuilder.java (hunk 4 above)
Comment (dmitry-timofeev) [inline AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartTestParametersBuilder.java]: No, it couldn't be, because the class [checks](https://github.com/ankidroid/Anki-Android/pull/4463/files/ef19a172bb8028a6fa28848c6a8e7883875ef279#diff-4c9a080251af73c00a280089224ce623R22 ) the argument (a list of double values) to be non-empty.

File: AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartParameterizedTest.java (hunk 6 above)
Comment (dmitry-timofeev) [inline AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartParameterizedTest.java]: It's a kind of syntactic sugar to write `values(<your values>)` instead of `new double[]{<your values>}`. It's used a lot in `PieChartParameterizedTest#data`.

File: AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartParameterizedTest.java (hunk 5 above)
Comment (dmitry-timofeev) [inline AnkiDroid/src/test/java/com/wildplot/android/rendering/PieChartParameterizedTest.java]: A `Collection` of arrays of `Objects` is a fixed signature of a method that supplies test parameters. Each field annotated with `@Parameter(parameterIndex)` is initialized with the corresponding parameter.

In case you supply wrong types of parameters, or a wrong number of them, the test runner will quite verbosely tell you what's wrong, and only that test will be failed. Here is an example: 
```Trying to set arcLengths with the value p2 that is not the right type (String instead of double[]).```

**Comment by hssm** [comment]
This looks like good work. Thanks!

The tests are pretty valuable. The extra dependencies shouldn't be an issue, and they're only for test builds anyway.

@timrae You can merge this if you're okay with it.
