### PR TITLE
CardViewer: Add Help for missing images

### LINKED ISSUE #7009: Improve "Can't find image" workflow
###### Reproduction Steps

1. Download an image heavy deck (example: AnKing with media) on Desktop
2. Sync to AnkiDroid, cancel sync before media sync completes
3. View Deck
4. A "cannot find image" symbol is displayed

###### Expected Result

* A snackbar of some sort to prompt the user with suggestions to fix the problem

###### Actual Result

* Nothing

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description
Many users had problems with missing images due to a media sync not completing

This gives them advice, and hopefully reduces the support load

## Fixes
Fixes #7009

## Approach
_How does this change address the problem?_

##### API 16 emulator
* Nothing on API 16 (as expected)  `onReceivedError` is not called. 

##### API 22 emulator 
* Nothing (unexpected) - `onReceivedError` is not called. 

##### Android 9 physical device
* Reviewer, Previewer and Card Template Previewer work
* Link has been tested
* Unit Tested

## Learning

* Moving a snackbar is hard. I used https://stackoverflow.com/a/48472087
* https://github.com/ankidroid/Anki-Android/wiki/FAQ#why-doesnt-my-sound-or-image-work-on-ankidroid

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.java [hunk 1]
```diff
@@ -18,9 +20,10 @@
 import static com.ichi2.async.CollectionTask.TASK_TYPE.*;
 import com.ichi2.async.TaskData;
 import com.ichi2.async.TaskListener;
-import com.ichi2.libanki.Collection;
 import com.ichi2.libanki.utils.Time;
 
+import org.jetbrains.annotations.NotNull;
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/UIUtils.java:25]: !!

File: AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/MissingImageHandlerTest.java [hunk 2]
```diff
@@ -0,0 +1,161 @@
...
+
+import static org.hamcrest.MatcherAssert.assertThat;
+import static org.hamcrest.Matchers.contains;
+import static org.hamcrest.Matchers.greaterThanOrEqualTo;
+import static org.hamcrest.Matchers.is;
+import static org.junit.Assume.assumeThat;
+
+// PERF:
+// Theoretically should be able to get away with not using this, but it requires WebResourceRequest (easy to mock)
+// and URLUtil.guessFileName (static - likely harder)
```
Comment (mikehardy) [inline AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/MissingImageHandlerTest.java:42]: Just to say that static mocking with Mockito is possible now and not too hard, there examples in our codebase if you grep mockStatic I believe. Not concerned about the actual comment you left, this is just knowledge-sharing / FYI

File: AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/MissingImageHandlerTest.java [hunk 3]
```diff
@@ -0,0 +1,161 @@
...
+@RunWith(AndroidJUnit4.class)
+public class MissingImageHandlerTest {
+
+    private MissingImageHandler mSut;
+    private int mTimesCalled = 0;
+    private List<String> mFileNames;
+
+    @Before
+    public void before() {
+        // couldn't get Config(minSDK) to work, as that produced multiple test calls.
```
Comment (mikehardy) [inline AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/MissingImageHandlerTest.java:52]: specifying SDK configs in robolectric should produce multiple runs ?, It is like using parameterized tests, you get one run in the default SDK I think and then one in the one you specify? The LanguageUtil test should show it. I guess that is surprising as you'd expect a single config API annotation to get you only one run with only that API, but you get the default API as well?

**Review by mikehardy — APPROVED** [review]
This looks really cool, it should reduce support load. None of my comments were material with regard to merge or not, they were all just meta, aimed at learning more about testing

File: AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/MissingImageHandlerTest.java (hunk 3 above)
Comment (david-allison-1) [reply AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/MissingImageHandlerTest.java:52]: I was expecting `minApi` to be a predicate on the current version, causing an ignore if `current < minApi` rather than including using all versions from minApi to v30

Comment (mikehardy) [reply AnkiDroid/src/test/java/com/ichi2/anki/cardviewer/MissingImageHandlerTest.java:52]: Hmm - this does what I expect, FWIW, runs on these-and-only-these APIs

https://github.com/ankidroid/Anki-Android/blob/f5479302a3f3964dad0e6d31c4f974a7dd612002/AnkiDroid/src/test/java/com/ichi2/compat/CompatCopyFileTest.java#L39
