### PR TITLE
fix: hide save button in fragmented activity to prevent duplication

### LINKED ISSUE #18921: Duplicate Save Note buttons when NoteEditor is in X-Large CardBrowser and preview icon missing
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

Image

Most likely caused by both the activity and the fragment adding a save note buttons separately.

### Expected behaviour

Singular Save Note button, and preview icon should be visible

### Debug info

```text
AnkiDroid Version = 2.22.0beta1-debug (057b14806f618e995146b3f4e594291466f7f73c)  
Backend Version = 0.1.58-anki25.07.2 (25.07.2 3adcf05ca6d00b32938f439b3e5fc71786b21c26)  
Android Version = 15 (SDK 35)  
ProductFlavor = play  
Device Info = Google | google | emu64xa | sdk_gtablet_x86_64 | Pixel Tablet | ranchu  
Webview User Agent = Mozilla/5.0 (Linux; Android 15; Pixel Tablet Build/AE3A.240806.046.T1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.219 Safari/537.36  
ACRA UUID = ce3fdf9b-f07f-4b6f-8660-076aa61c0945  
FSRS = 4.1.1 (Enabled: false)  
Crash Reports Enabled = false
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by Haz3-jolt**
## Purpose / Description
- Hides the save button from `NoteEditorFragment` in cardBrowser to prevent duplication

## Fixes
* Fixes #18921 

## Approach
- The cardBrowser already has a 'save_note' being added, and noteEditorFragment adds another one. 
- Here we introduce a check to prevent additional 'save_note' buttons from being added.
- This occurred after the NoteEditor was separated into the NoteEditorActivity.
- Since NoteEditorFragment is a MenuProvider we do not need onCreateMenu anymore.

## How Has This Been Tested?

image

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by Haz3-jolt** [comment]
> I don't feel the issue, PR or commit message explain why this is occurring.
> 
> What's producing the other save button? Why are we removing it from the Note Editor?

I've added some context in the PR, I'll also do so in the commit message

**Comment by david-allison** [comment]
I'd remove adding the menu item 'action_save' from the Browser. It should be a responsibility of the note editor.

The Browser should instead override the `action_save`, instead of passing it down to the fragment

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt [hunk 1]
```diff
@@ -1021,9 +1021,10 @@ open class CardBrowser :
             showBackIcon()
             increaseHorizontalPaddingOfOverflowMenuIcons(menu)
         }
-        // Append note editor menu to card browser menu if fragmented and deck is not empty
-        if (fragmented && viewModel.rowCount != 0) {
-            fragment?.onCreateMenu(menu, menuInflater)
+        // Remove save note and preview note options if there are no notes
+        if (fragmented && viewModel.rowCount == 0) {
+            menu.removeItem(R.id.action_save)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt:1025]: Why is this no longer calling `onCreateMenu` on the fragment?

Comment (Haz3-jolt) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt:1025]: Because the Fragment is a MenuProvider for any activity hosting it

**Review by Arthur-Milchior — COMMENTED** [review]
In the commit message "save note" and "preview" should be quoted. Or even you should state that it remove the menu entry named "save note" and "preview". As those are verbs that are used as noun, it makes the sentence very confusing otherwise.

I really don't understand what the last line mean. I have now idea which check you're referring to. How could a check disappear. 

I appreciate that your commit message are longer than a single line, but it's still hard to follow.

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt (hunk 1 above)
Comment (Arthur-Milchior) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt:1025]: Please explain it in the commit message then. And give a real explanation. Right now, I really have no idea what it means.

Do you mean that calling `onCreateMenu` was actually useless and should never have been done. If so, I guess it could be its own commit, or even its own PR.
Did it have no effect? If it did have an effect, what was it, explain why this effect must be reverted

Or if this was necessary but it's not anymore because of the other changes in your commit, please explain in the commit message how this removed line relate to the other lines of the commit.


This is really hard to follow.
You must understand that I don't know every details of every menu. Right now, you probably are one of the person who know the best how activity with multiple fragments works in ankidroid. I could of course read the code and learn how it works, but that takes time, and reviewing commits already takes a lot of time. Instead, it's your role to write a few line in the commit to explain everything relevant to give the context for everything relevant so that we understand why this change is right.

**Comment by Haz3-jolt** [comment]
Should have a more clear message rn! Thanks for the heads up, it was a lot more obvious to me because I worked on it!
Hindsight blinded me ig 😆

**Review by david-allison — APPROVED** [review]
Ok, consider making the title ~50 chars:

`fix(card-browser): remove duplicate menu items`
