### PR TITLE
Fix "AnkiDroid database problem" if database is locked 

### LINKED ISSUE #8075: [Bug] Rust: error while compiling: "openAnkiDroidCollection": Anki already open, or media currently syncing.
```
android.database.sqlite.SQLiteException: error while compiling: "openAnkiDroidCollection": Anki already open, or media currently syncing.
at net.ankiweb.rsdroid.BackendV1Impl.openAnkiDroidCollection(BackendV1Impl.java:10)
at net.ankiweb.rsdroid.BackendMutex.openAnkiDroidCollection(BackendMutex.java:2)
at net.ankiweb.rsdroid.BackendUtils.openAnkiDroidCollection(BackendUtils.java:1)
at net.ankiweb.rsdroid.database.RustSupportSQLiteOpenHelper.createRustSupportSQLiteDatabase(RustSupportSQLiteOpenHelper.java:4)
at net.ankiweb.rsdroid.database.RustSupportSQLiteOpenHelper.getWritableDatabase(RustSupportSQLiteOpenHelper.java:2)
at com.ichi2.libanki.DB.<init>(DB.java:9)
at com.ichi2.libanki.backend.RustDroidBackend.openCollectionDatabase(RustDroidBackend.java:1)
at com.ichi2.libanki.Storage.Collection(Storage.java:6)
at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:8)
at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:3)
at com.ichi2.anki.CollectionHelper.getColSafe(CollectionHelper.java:1)
at com.ichi2.anki.DeckPicker.firstCollectionOpen(DeckPicker.java:11)
at com.ichi2.anki.DeckPicker.onCreate(DeckPicker.java:5)
at android.app.Activity.performCreate(Activity.java:7963)
at android.app.Activity.performCreate(Activity.java:7952)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3629)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:8167)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: net.ankiweb.rsdroid.BackendException$BackendDbException: Anki already open, or media currently syncing.
at net.ankiweb.rsdroid.RustBackendImpl.validateMessage(RustBackendImpl.java:3)
at net.ankiweb.rsdroid.BackendV1Impl.openAnkiDroidCollection(BackendV1Impl.java:6)
... 27 more
```

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description
Due to the Rust DB code, we now lock the database, if two Anki clients are using the same

On startup, we didn't differentiate between DB locked and DB corrupt, which I expect would confuse users, and likely lead some to delete their databases.

## Fixes
Fixes #8075 

## Approach
* Detect the specific exception (now possible)
* If the exception is thrown, use the "locked" dialog that I added ages ago for check datbase.

## How Has This Been Tested?

Unit tests, and on my device

* Both from a "no permission" and "normal" scenario
* Also a janky unit test to ensure that no ACRA errors are raised

image

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.java [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+package com.ichi2.anki;
+
+import android.content.Context;
+
+import androidx.annotation.CheckResult;
+import androidx.annotation.NonNull;
+import timber.log.Timber;
+
+/** Utilities for launching the first activity (currently the DeckPicker) */
+public class InitialActivity {
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.java:28]: I wonder if DeckPicker and MyAccount and CardBrowser etc could extend InitialActivity and the cast that crashes on #5075 could be fixed.

**Review by mikehardy — APPROVED** [review]
This looks really good - a couple things that can be improved as you noted in the code but the underlying issue is conclusively fixed it appears (or if there is some corner case all the structure exists) and the TODOs are nice to haves vs vital

File: AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.java (hunk 1 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/InitialActivity.java:28]: The issue there is that `DeckPicker` isn't being opened when we explicitly send an intent to switch to the screen, it's on the back of my mind as one of the larger crashes, and we should be able to resolve it now I've added logging (so we can reproduce it).

I do later want to abstract out the `HomeScreen` from the `DeckPicker`, but there's a lot of considerations, especially with the `DeckPicker` startup flow being as messy as it it.
