### PR TITLE
fix(card-browser): retain state in 'onStart'

### LINKED ISSUE #14220: [BUG]: After updating a note in Card browser, the top of the list of notes is shown instead of the note's position on the list
### Checked for duplicates?

- [X] This issue is not a duplicate (maybe)

### What are the steps to reproduce this bug?

1. Open Card browser
2. Scroll down in the list of notes (or cards)
3. Tap a note
4. ~~Edit and update the note~~ Go back to the list screen from the note editor screen

### Expected behaviour

The position of the list of notes before editing the note is shown again, as on version 2.15.6.

### Actual behaviour

The top of the list of notes is shown.

### Debug info

```text
AnkiDroid Version = 2.16.2

Android Version = 11

ProductFlavor = play

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/115.0.5790.166 Mobile Safari/537.36

ACRA UUID = 5ba46727-9ddb-47f3-a810-53f66d97a89e

New schema = false (and true)

Scheduler = std2 (and std3 with new schema)

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

The following is a review of an user

> Love the app, but frustrated after the storage folder migration update. Every time I edit/update a note, I'm taken all the way back to to TOP of the deck in the card browser, instead of staying on the same note (in the browser) where I was before the edit. I have ~6k notes in my deck that I'm going through, and being forced to the top of the deck, then having to search to get back to where I was *EACH TIME* I edit is time consuming & annoying. Also, scroller in the browser is now glitchy. PLZ FX

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
The flows were refreshed, causing a search if a user backgrounded the app and restored it

Also with editing notes in different activities

## Fixes
* Fixes #14220

## Approach

~~We add `flowWhenActive` to handle this~~

From review comments: remove `flowWithLifecycle` instead

## How Has This Been Tested?
On my S21: editing notes and backgrounding the app:

* editing removes selection (as previously)
* backgrounding now maintains scroll position

## Learning (optional, can help others)
I did not know this issue that a `StateFlow` would refresh when backgrounded. This won't be a problem when we move searching into the `ViewModel`, but is for now

https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/distinct-until-changed.html

## Checklist
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt [hunk 1]
```diff
@@ -419,19 +421,12 @@ open class CardBrowser :
...
-            .flowWithLifecycle(lifecycle, Lifecycle.State.STARTED)
-            .onEach { cardsAdapter.notifyDataSetChanged() }
-            .launchIn(lifecycleScope)
+        viewModel.isTruncatedFlow.flowWhenActive { cardsAdapter.notifyDataSetChanged() }
 
-        viewModel.cardsOrNotesFlow
-            .flowWithLifecycle(lifecycle, Lifecycle.State.STARTED)
-            .onEach { runOnUiThread { searchCards() } }
-            .launchIn(lifecycleScope)
+        viewModel.cardsOrNotesFlow.flowWhenActive { runOnUiThread { searchCards() } }
```
Comment (oakkitten) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt:426]: Why `runOnUiThread`?

**Review by oakkitten — CHANGES_REQUESTED** [review]
Only did a cusory look through the code.

If I may suggest, 

* I am not sure if `flowWithLifecycle` is useful here. You use `flowWithLifecycle` when you wan to start/stop collecting a flow when the lifecycle moves in and out of some state. Usually you do this when you have a long-running action that updates state, but you don't want to waste resources updating UI when the activity is stopped.

        |------------------state updates------------------|
               |--UI active--|   |----UI active----|

    An example of such an action would a file upload that happens in background, and UI with progress.

    For stuff like updating the “Truncate content” state, using this is probably redundant because:

   * Truncate content is a momentary change, and
   * It can only happen when UI is active, anyway.

    Instead, simply do something along

    ```kt
    fun onCreate(...) {
    	lifecycleScope.launch {
    		flowOfisContentTruncated.collect { ... }
    	}
    }
    ```

* Something with the name `isTruncatedFlow` should probably be a `Boolean`. I suggest the syntax `flowOfThing` (disclaimer: my own invention, as used in `ManageSpaceFragment`).

* `flowWhenActive` does not reflect what is happening. Whan is “active”?

**Review by BrayanDSO — APPROVED** [review]

**Review by oakkitten — APPROVED** [review]
5d467ac77fb33adc7f62def0bca1c48e924fea35 removes a single `runOnUiThread` out of a few. Suggest either removing all of the redundant calls or dropping the commit.

P.S. Something like `dataFlow` is readable enough, but as, in in the example above, `isTruncatedFlow`, you may run into problems when you combine the suffix `Flow` with the more conventional boolean prefix `is`. This just might be confusing for some as “Is the flow truncated?” sounds like a perfectly fine question. `flowOf`, on the other hand, is very un-problematic in my experience. You can slap it onto anything, and it will not lead to confusion. You can't read in other ways besides “Flow of ‘is truncated?’”

**Review by mikehardy — APPROVED** [review]
