### PR TITLE
Deck Export with media: Skip missing files

### LINKED ISSUE #7023: Export fails if missing media
###### Reproduction Steps

1. Add an image to a note
2. Delete from `collection.media`
3. Export Deck

###### Expected Result

4. Export occurs, with warning that some files could not be found

###### Actual Result

4. Export fails with "Error exporting apkg file"

###### Debug info

```
2020-09-04 07:33:06.222 23541-23852/com.ichi2.anki E/CollectionTask: FileNotFoundException in doInBackgroundExportApkg
    java.io.FileNotFoundException: /storage/emulated/0/AnkiDroidThree/collection.media/img_202009021920498931922221469823880.jpg (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:231)
        at java.io.FileInputStream.<init>(FileInputStream.java:165)
        at java.io.FileInputStream.<init>(FileInputStream.java:112)
        at com.ichi2.libanki.ZipFile.write(AnkiPackageExporter.java:467)
        at com.ichi2.libanki.AnkiPackageExporter._exportMedia(AnkiPackageExporter.java:388)
        at com.ichi2.libanki.AnkiPackageExporter._exportMedia(AnkiPackageExporter.java:380)
        at com.ichi2.libanki.AnkiPackageExporter.exportFiltered(AnkiPackageExporter.java:408)
        at com.ichi2.libanki.AnkiPackageExporter.exportInto(AnkiPackageExporter.java:340)
        at com.ichi2.async.CollectionTask.doInBackgroundExportApkg(CollectionTask.java:1535)
        at com.ichi2.async.CollectionTask.actualDoInBackground(CollectionTask.java:403)
        at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:308)
        at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:89)
        at android.os.AsyncTask$2.call(AsyncTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
```

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description

Anki Desktop has the same behaviour.

Previously threw a FileNotFound

## Fixes
Fixes #7023

## Approach
Check the files exist, and skip if they don't

## How Has This Been Tested?
Integration test and tested on my Android 9 phone

## Learning
This one had been live for a long time, still need more tests

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

File: AnkiDroid/src/test/java/com/ichi2/libanki/AnkiPackageExporterTest.java [hunk 1]
```diff
@@ -0,0 +1,164 @@
...
+ *  You should have received a copy of the GNU General Public License along with
+ *  this program.  If not, see <http://www.gnu.org/licenses/>.
+ */
+
+package com.ichi2.libanki;
+
+import com.ichi2.anki.RobolectricTest;
+import com.ichi2.anki.exception.ImportExportException;
+
+import org.jetbrains.annotations.NotNull;
```
Comment (mikehardy) [inline AnkiDroid/src/test/java/com/ichi2/libanki/AnkiPackageExporterTest.java:22]: I think you've got a new lint rule that will fail this?

**Review by mikehardy — APPROVED** [review]
LGTM pending annotation switch

**Comment by mikehardy** [comment]
This is a semi-frequent user issue, thanks for fixing it!

File: AnkiDroid/src/test/java/com/ichi2/libanki/AnkiPackageExporterTest.java (hunk 1 above)
Comment (david-allison-1) [reply AnkiDroid/src/test/java/com/ichi2/libanki/AnkiPackageExporterTest.java:22]: Actually... I don't think they run in tests... but thanks!

**Comment by david-allison-1** [comment]
Rebased

**Review by mikehardy — APPROVED** [review]
