### PR TITLE
fix(deck-options): crash on API 30 and below

### LINKED ISSUE #20456: [2.24.0alpha8] FilteredDeckOptions crashes on open
> 2.24.0alpha8 crashes on opening filtered deck options or after naming a new filtered deck

-- Khonkhortisan

Probably the following. API 30

```
Caused by: java.lang.ClassCastException: android.content.res.TypedArray cannot be cast to java.lang.AutoCloseable
	at com.ichi2.preferences.NumberRangePreference.getMinFromAttributes(NumberRangePreference.kt:118)
	at com.ichi2.preferences.NumberRangePreference.<init>(NumberRangePreference.kt:43)
	at com.ichi2.preferences.IncrementerNumberRangePreference.<init>(IncrementerNumberRangePreference.kt:43)
	... 26 more
```

<details>

<summary>Full stack trace</summary>

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.FilteredDeckOptions}: android.view.InflateException: Binary XML file line #31: Error inflating class java.lang.reflect.Constructor
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3502)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3654)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2116)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7720)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
Caused by: android.view.InflateException: Binary XML file line #31: Error inflating class java.lang.reflect.Constructor
	at android.preference.GenericInflater.createItem(GenericInflater.java:409)
	at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:439)
	at android.preference.GenericInflater.rInflate(GenericInflater.java:490)
	at android.preference.GenericInflater.rInflate(GenericInflater.java:502)
	at android.preference.GenericInflater.inflate(GenericInflater.java:334)
	at android.preference.GenericInflater.inflate(GenericInflater.java:271)
	at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:343)
	at android.preference.PreferenceActivity.addPreferencesFromResource(PreferenceActivity.java:1541)
	at com.ichi2.anki.FilteredDeckOptions.addPreferences(FilteredDeckOptions.kt:264)
	at com.ichi2.anki.FilteredDeckOptions.onCreate(FilteredDeckOptions.kt:239)
	at android.app.Activity.performCreate(Activity.java:8000)
	at android.app.Activity.performCreate(Activity.java:7984)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3475)
	... 11 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.preference.GenericInflater.createItem(GenericInflater.java:392)
	... 23 more
Caused by: java.lang.ClassCastException: android.content.res.TypedArray cannot be cast to java.lang.AutoCloseable
	at com.ichi2.preferences.NumberRangePreference.getMinFromAttributes(NumberRangePreference.kt:118)
	at com.ichi2.preferences.NumberRangePreference.<init>(NumberRangePreference.kt:43)
	at com.ichi2.preferences.IncrementerNumberRangePreference.<init>(IncrementerNumberRangePreference.kt:43)
	... 26 more
```

</details>

https://ankidroid.org/acra/app/1/bug/388244/report/8d02a928-c4aa-4f49-b719-d38ec143a95b

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
`TypedArray` crashes when cast to `AutoCloseable` on API 30 or below

## Fixes
* Fixes #20456

## Approach
Replace `.use` with `usingStyledAttributes`

## How Has This Been Tested?
No longer crashes on an API 29 emulator

## Learning (optional, can help others)
Introduced by f157e172f2158c69f71f070fa9c9e0651072d8b0

TypedArray crashes when cast to AutoCloseable on API 30 or below

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/compat/CompatV30.kt [hunk 1]
```diff
@@ -0,0 +1,84 @@
...
+ *   [TypedArray], used only if [defStyleAttr] is 0 or can not be found in the theme. Can be 0 to
+ *   not look for defaults.
+ * @param block The block that will be executed.
+ *
+ * @return The result of [block]
+ *
+ * @see Context.obtainStyledAttributes
+ * @see android.content.res.Resources.Theme.obtainStyledAttributes
+ */
+inline fun <T> Context.withStyledAttributesResult(
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/compat/CompatV30.kt]: this is a duplicate of `Context.usingStyledAttributes` in `com.ichi2.anki.utils.ext`

**Review by BrayanDSO — CHANGES_REQUESTED** [review]
