### PR TITLE
Fix incorrect key handling in some screens

### LINKED ISSUE #16955: [BUG]: Cannot Return to Edit/Add Screen from Template Editor
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

* Go to Edit screen/Add screen.
* Click **Cards** to open Card Template Editor.
* Try to go back to the previous screen.

### Expected behaviour

Edit/Add screen reopens.

### Actual behaviour

Cannot return to the previous screen. I'm able to use the **← Navigate up** button. Gestures and keyboard presses are not working.

### Debug info

```text
AnkiDroid Version = 2.19alpha12 (f720ae030b8920c73f957d64d7044e95242f7719)

Backend Version = 0.1.40-anki24.06.3 (24.06.3 d678e39350a2d243242a69f4e22f5192b04398f2)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = realme

Model = RMX2193

Hardware = mt6768

Webview User Agent = Mozilla/5.0 (Linux; Android 11; RMX2193 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/127.0.6533.103 Mobile Safari/537.36

ACRA UUID = cf265e01-9693-407f-984d-61ddf9698fac

FSRS Enabled = true

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### LINKED ISSUE #16983: [BUG]: Can't delete characters of field search after an initial search
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

After an initial search such as front:dog the characters of front:dog can no longer be deleted from the search bar

[Recording_2024-08-28-10-06-29.webm](https://github.com/user-attachments/assets/9823868b-4c15-484e-9682-134e545de1a3)

### Expected behaviour

They should be deleted

### Actual behaviour

They aren't deleted

### Debug info

```text
AnkiDroid Version = 2.19beta1 (6630ff411d643bf03206e106c4d940dc7076e738)

Backend Version = 0.1.40-anki24.06.3 (24.06.3 d678e39350a2d243242a69f4e22f5192b04398f2)

Android Version = 12 (SDK 31)

ProductFlavor = full

Hardware = timelm

Webview User Agent = Mozilla/5.0 (Linux; Android 12; LM-V600 Build/SKQ1.211103.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/127.0.6533.103 Mobile Safari/537.36

ACRA UUID = 7b39fb43-528f-4fa8-b8dd-a53a3c863516

FSRS Enabled = true

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### LINKED ISSUE #16984: Typing 't' in the Card Browser search opens Tags Dialog
```
AnkiDroid Version = 2.19beta1-debug (f9ea4df68e15b7e205e7d059ced8fd15dda3ad12)

Backend Version = 0.1.40-anki24.06.3 (24.06.3 d678e39350a2d243242a69f4e22f5192b04398f2)

Android Version = 14 (SDK 34)

ProductFlavor = full

Manufacturer = Google

Model = sdk_gphone64_arm64

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 14; sdk_gphone64_arm64 Build/UE1A.230829.036.A2; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/126.0.6478.134 Mobile Safari/537.36

ACRA UUID = 4a360462-a9c8-4ceb-a6a2-c8498685ab32

FSRS Enabled = true

Crash Reports Enabled = false
```

### PR DESCRIPTION
**Pull request by lukstbit**
## Purpose / Description

This PR fixes the linked issues + one more(edit note screen is shown on every E event) by properly following the contract of the onKeyUp method of returning true only if the event is handled there and using a modifier to not trigger on simple key events/checking the state of the search box to see if it's regular input.

In CardBrowser I introduced two new shortcuts by using the modifier that was not used in that when selection clause:

old: _T -> Show filter by tags dialog_ vs. new: _Ctrl+T: Show filter by tags dialog_

Feel free to propose other shortcuts.

@SanjaySargam I've made this PR to help seeing that you still have work on the Gsoc front.

## Fixes
* Fixes  #16955
* Fixes #16984
* Fixes #16983

## How Has This Been Tested?

I don't see the previous behavior.

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — APPROVED** [review]

**Comment by SanjaySargam** [comment]
@lukstbit Thank You ❤️

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt [hunk 1]
```diff
@@ -656,9 +656,10 @@ open class CardBrowser :
                     Timber.i("Ctrl+E: Add Note")
                     launchCatchingTask { addNoteFromCardBrowser() }
                     return true
-                } else {
-                    Timber.i("E: Edit note")
+                } else if (event.isShiftPressed) {
+                    Timber.i("Shift+E: Edit note")
```
Comment (BrayanDSO) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt:660]: Shift+E can be used to write capital E in the search box and this impedes that.

**Review by BrayanDSO — CHANGES_REQUESTED** [review]

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt (hunk 1 above)
Comment (lukstbit) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt]: Didn't realize that, I've changed the code to look at the state of the searchbox. Thanks!

**Review by BrayanDSO — APPROVED** [review]
