### PR TITLE
Fix background image visibility based on collection state #18073

### LINKED ISSUE #18073: Improve background when the collection is empty
How to reproduce.
* start ankidroid with no card
* open settings > appearance>select image and add a background
* go back to the deck picker

Expected result: 
* the text is still readable

Actual result:
* text is hard to read. See below
Image

I think the nice thing to do would be to have the text to be on top of a small view with a background whose color is the same as the default deck picker background. So that the text can still be read. I believe the standard would be to have a view with rounded corner, probably a border too. 

If it's too hard, I guess just not displaying the background when there are no card would work too.

I suspect it's a very rare case. I have a hard time imagining someone really wanting to add a background before adding a card. So treat this as very low priority, as very few people will ever see your work when you fix it

### PR DESCRIPTION
**Pull request by Tushar4059x**
## Purpose / Description
Previously, the background image remained visible even when the collection was empty, causing readability issues. This update ensures that the background image is correctly toggled based on whether there are decks in the collection.

## Fixes
* Fixes #18073 

## Approach
- Adjusted updateBackgroundVisibility to properly show/hide the background image based on deck presence.

How Has This Been Tested?

- Tested on Pixel 8 Android Emulator (API 34).
- Verified that the background image correctly appears when decks are added and disappears when the collection is empty.
- Ensured there were no UI glitches or unexpected behavior during deck updates.
- Checked performance to confirm no redundant memory usage.

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

Uploading Screen Recording 2025-03-26 at 6.37.36 PM.mov…

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 1]
```diff
@@ -274,6 +274,8 @@ open class DeckPicker :
 
     private lateinit var floatingActionMenu: DeckPickerFloatingActionMenu
 
+    private lateinit var currentAnkiDroidDirectory: String
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:277]: why?

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 2]
```diff
@@ -2244,8 +2246,23 @@ open class DeckPicker :
...
+        }
+    }
+
+    /**
+     * Updates the background visibility based on the collection state
+     * Hides the background when collection is empty for better text readability
+     */
+    private fun updateBackgroundVisibility(collectionIsEmpty: Boolean) {
+        val backgroundView = findViewById<ImageView>(R.id.background)
+        if (collectionIsEmpty) {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:2259]: This logic doesn't feel correct, I would expect the same logic to be used to show the placeholder:

https://github.com/ankidroid/Anki-Android/blob/dc37ead165e924082738eacf60dc2c13db22d61b/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt#L2254-L2279

**Review by david-allison — COMMENTED** [review]
Thanks!

**Comment by Tushar4059x** [comment]
My pleasure ,sir!

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt (hunk 1 above)
Comment (Tushar4059x) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:277]: I thought it would be a good idea to declare the variable with all the other declarations..

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt (hunk 2 above)
Comment (Tushar4059x) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:2259]: No worries! I’ll rethink the solution based on the algorithm and re-do implementation accordingly.

**Comment by ericli3690** [comment]
Hi! It's advised that you force push on top of your old commit so that there's only one commit associated with each issue. This way, the commit history of the repo stays clean and descriptive. This was a mistake I made when I first contributed. You can do this by running `git reset --soft [commit hash to revert to]`, committing, then running `git push -f origin [branch name]`.

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 3]
```diff
@@ -2244,8 +2244,8 @@ open class DeckPicker :
                 layoutParams.setMargins(0, 0, 0, reviewSummaryTextView.height / 2)
                 fabLinearLayout.layoutParams = layoutParams
             }
+            Timber.d("Startup - Deck List UI Completed")
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:2247]: revert - doesn't seem relevant

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 4]
```diff
@@ -2257,9 +2257,11 @@ open class DeckPicker :
             updateDeckList()
             return
         }
-
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:2260]: revert - ditto

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 5]
```diff
@@ -2257,9 +2257,11 @@ open class DeckPicker :
...
         // Check if default deck is the only available and there are no cards
         val isEmpty = tree.children.size == 1 && tree.children[0].did == 1L && collectionIsEmpty
+        // Update background visibility based on collection state
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:2262]: improve the comment to explain the 'why', not the 'what'

**Review by david-allison — COMMENTED** [review]
Code looks good! A couple of 'line noise' changes in the diff which should be reverted to keep things clean

And a request for a comment change to explain why the line exists

**Review by david-allison — APPROVED** [review]
Cheers, thanks so much, looks great!

File: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt [hunk 6]
```diff
@@ -2245,7 +2245,6 @@ open class DeckPicker :
                 fabLinearLayout.layoutParams = layoutParams
             }
         }
-        Timber.d("Startup - Deck List UI Completed")
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:2248]: Wait... this line shouldn't be removed

(missed this on the diff from my notifications)

Comment (Tushar4059x) [reply AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:2248]: okay i'll just add it again

**Comment by Tushar4059x** [comment]
done
