### PR TITLE
Issue4987/previewer issues

### LINKED ISSUE #4987: Crash in AbstractFlashCardViewer.onCollectionLoaded() ArrayIndexOutOfBoundsException
The lifecycle changes in #4972 are the gift that keep on giving :-)

###### Reproduction Steps

1. Click top-left hamburger to get NavDrawer, Select Card Browser
2. Either have an empty collection or search for something that doesn't exist so the browser is empty
3. Click top-right options menu, note "Preview" option exists, tap it

###### Expected Results

This menu is already dynamic, so probably shouldn't have the Preview option there when there are no cards, but if it is there, it should toast "No cards to preview" or something.

###### Actual Result

Issue 1 - Crash when you hit "Preview" on the options menu in card browser when there are no cards.

Issue 2 - Also, the Card Browser Preview cycling is inconsistent. It starts with a cycle-left button but if you cycle right then back all the way left, the button is disabled. Should be disabled to start.

Issue 3 - Also the cycling right vs left to advance is probably a localization RTL issue (ha!)

This is from the pre-launch Firebase "Robo" test that Google Play conducts automatically on all releases, with 2.9alpha36

The "MATE 9" device here https://play.google.com/apps/publish/?account=5338425030304417978#PreLaunchReportPlace:p=com.ichi2.anki&appid=4973711737547064258&plrtab=CRASH&plrvc=20900136

09-20 07:16:50.650: E/MonitoringInstr(9942): Exception encountered by: com.ichi2.anki.Previewer@5936a01. Dumping thread state to outputs and pining for the fjords.
09-20 07:16:50.650: E/MonitoringInstr(9942): java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
09-20 07:16:50.650: E/MonitoringInstr(9942): 	at com.ichi2.anki.Previewer.onCollectionLoaded(Previewer.java:57)
09-20 07:16:50.650: E/MonitoringInstr(9942): 	at com.ichi2.anki.AnkiActivity.startLoadingCollection(AnkiActivity.java:253)
09-20 07:16:50.650: E/MonitoringInstr(9942): 	at com.ichi2.anki.AbstractFlashcardViewer.onCreate(AbstractFlashcardViewer.java:826)
09-20 07:16:50.650: E/MonitoringInstr(9942): 	at com.ichi2.anki.Previewer.onCreate(Previewer.java:48)
09-20 07:16:50.650: E/MonitoringInstr(9942): 	at android.app.Activity.performCreate(Activity.java:6910)
09-20 07:16:50.650: E/MonitoringInstr(9942): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
09-20 07:16:50.650: E/MonitoringInstr(9942): 	at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:215)

### PR DESCRIPTION
**Pull request by mikehardy**
## Purpose / Description
3 of the 9 robots google play sent at our last alpha errored in an easy way on the CardBrowser, this fixes that error as well as quite a few CardBrowser/Previewer integration issues

## Fixes
Fixes #4987 

## Approach

1. commit 1 - fixing the Previewer cycling - showing <, > and - at right times
1. commit 2 - Preview option menu item in CardBrowser dynamic so it is hidden if the browser is empty (prevents the crash), also save CardBrowser search state when you go to other activities and return
1. commit 3 - A UI test to exercise all this stuff, but isolated in it's own package and excluded from CI (they are flaky there)

## How Has This Been Tested?
A ton by hand, and I made another UI unit test. I posted videos on the linked issue demonstrating before and after

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 1]
```diff
@@ -822,8 +822,10 @@ protected void onCreate(Bundle savedInstanceState) {
 
         View mainView = findViewById(android.R.id.content);
         initNavigationDrawer(mainView);
-        // Open collection asynchronously
-        startLoadingCollection();
+        // Open collection asynchronously unless our sub-class signaled they need to end
+        if (!isFinishing()) {
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java]: This doesn't make any sense to me, please explain

File: AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java [hunk 2]
```diff
@@ -104,17 +104,20 @@ protected void executeCommand(int which) {
...
-                } else if (view.getId() == R.id.flashcard_layout_ease2) {
+            if (mShowingAnswer) {
+                if (view.getId() == R.id.flashcard_layout_ease2) {
                     mIndex++;
+                    mCurrentCard = getCol().getCard(mCardList[mIndex]);
                 }
-                mCurrentCard = getCol().getCard(mCardList[mIndex]);
                 displayCardQuestion();
             }
+            else {
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java]: Can you please fix the style file? It should be `} else {`, I think this is the third time I mentioned this :p

File: AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java [hunk 3]
```diff
@@ -104,17 +104,20 @@ protected void executeCommand(int which) {
...
         @Override
         public void onClick(View view) {
-            if (!mShowingAnswer) {
-                displayCardAnswer();
-            } else {
-                if (view.getId() == R.id.flashcard_layout_ease1) {
-                    mIndex--;
-                } else if (view.getId() == R.id.flashcard_layout_ease2) {
+            if (mShowingAnswer) {
+                if (view.getId() == R.id.flashcard_layout_ease2) {
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java]: A comment to explain the intended logic would be appreciated I think

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java [hunk 4]
```diff
@@ -964,6 +974,7 @@ private void searchCards() {
     private void updateList() {
         mCardsAdapter.notifyDataSetChanged();
         mDropDownAdapter.notifyDataSetChanged();
+        updatePreviewMenuItem();
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java]: I think calling `invalidateOptionsMenu()` and checking the size when the options menu is created would be a more standard approach.

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java [hunk 5]
```diff
@@ -511,7 +511,7 @@ public boolean onItemLongClick(AdapterView<?> adapterView, View view, final int
         getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_ALWAYS_HIDDEN);
 
         // initialize mSearchTerms to a default value
-        mSearchTerms = "";
+        //mSearchTerms = "";
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java]: Please don't just leave code commented out like this; make a decision to keep it or remove it

File: AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/CardBrowserPreviewUI.java [hunk 6]
```diff
@@ -0,0 +1,324 @@
...
+    @Rule
+    public GrantPermissionRule mRuntimePermissionRule =
+            GrantPermissionRule.grant(Manifest.permission.WRITE_EXTERNAL_STORAGE);
+
+    @Rule
+    public ActivityTestRule<IntentHandler> mActivityTestRule = new ActivityTestRule<>(IntentHandler.class);
+
+
+    @Test
+    public void cardBrowserPreview3UI() throws Exception {
```
[the remark this answers is not in the document]
Comment (mikehardy) [reply AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/CardBrowserPreviewUI.java]: If I move these new UI tests to com.ichi2.anki.uitests (new package), can you have Codacy ignore that package? 

They are made by a code-generator connected to an AndroidStudio recorder and making a 3rd party code generator conform to our standards seems out of scope but the warnings on these tests ruin signal/noise

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java (hunk 4 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java]: I tried that, but it seems the card searches and loads are async and invalidateOptionsMenu()/onOptionsMenuCreate() was being called and finishing prior to the deck counts being reliably good. I really hate how updatePreviewMenuItem() is sprinkled everywhere actually but I was not able to get reliable behavior without every one of these - that's why I wrote the automated UI test - I was really banging on it. I think we want to re-do the AsyncTask stuff at some point so my thinking was I could either perfect the current style here and sprinkle fewer hooks in, or get this done and the whole thing will change later. I went for finishing this with UI test to at least support correct behavior later when threading changes

File: AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java (hunk 3 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java]: Sure thing - intention is "If we're on answer, forward means show the next card, only enable forward button if there is a next card", and vice versa. Will document

File: AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java (hunk 2 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java]: Ah sorry! And every time I was thinking "yeah, we do elses on new lines", completely missing that you were telling me the opposite. So yes, I'm persistently generating it wrong. Will fix

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java (hunk 4 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java]: I will try this though, just in case - for the avoidance of doubt

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java (hunk 1 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java]: 1. Previewer.onStart() immediately realizes it inherited an invalid state in it's intent and calls finish()/finishWithoutAnimation(). Activity.onFinishing() is now true but Lifecycle.getCurrentState().isAtLeast(CREATED) is still true
1. You must call super.onStart() though, or the framework throws an exception - it is a hard requirement, so you can't call return or exit or anything
1. AnkiActivity.onStart() forks a thread to load the collection
1. Framework does not call onResume() or onCreateOptionsMenu() or anything, because you Activity.onFinishing() is true - onCreate() executes fully everywhere but other than that you are tearing down. Many member variables are uninitialized
1. AnkiActivity.loadCollection() thread completes work and does callbacks
1. Previewer and AbstractFlashCardViewer.onLoadCollection() and start to do all sorts of UI updates but nothing is in a state to display - this is literally the #4987 crash stack trace, fully reproducible - in current alpha just get the CardBrowser to an empty list state and pick Preview from options menu

So instead of loading the collection in to an Activity that clearly signalled they were finishing (implying it's time to get to work), we demur and Previewer safely goes away. I could have protected Previewer.onLoadCollection() and AbstractFlashCardViewer.onLoadCollection() so they were safe even if finish() was called, but there may be other things like this in any AnkiActivity subclass and I think the general idea of "isFinishing()?, okay, forget it" seemed correct.

File: AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java (hunk 2 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java]: In Codacy, you want to go here: left bar "Code patterns" -> Pick "Checkstyle" -> seek to "RightCurly". I believe the default setting is what you want and what is specified in our code style doc?

http://checkstyle.sourceforge.net/apidocs/com/puppycrawl/tools/checkstyle/checks/blocks/RightCurlyOption.html#SAME

Our internal / commited AndroidStudio config already does this, as mentioned above I was somehow thinking preference was opposite so had been line-breaking. :disappointed:

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java (hunk 5 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java]: of course - consumers of this variable are null safe now so this is unneeded

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java (hunk 4 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java]: I re-tried and I see the problem a little more clearly now, but not a great solution. It looks like the options menu initialization and the action bar state (which is a larger scope than the options menu unless I am mistaken?) have been co-mingled. If you cause an options menu reinitialization, it messes with the action bar state, and in this specific case it takes your search (which I was using to achieve a zero-cards-in-browser state) to disappear. The menu status is right, but action bar status is wrong. If I just update the menu state directly here instead of fully reinitializing it, the Preview option is there or not correctly, and the ActionBar search state is preserved. A real solution would involve cleaning this thing up, but I've already gone so far past just fixing an easy crash I want to cut scope here and get back to notifications...

File: AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java [hunk 7]
```diff
@@ -153,8 +159,7 @@ private void updateButtonState() {
         mEase2Layout.setOnClickListener(mSelectScrollHandler);
         mEase2Layout.setBackgroundResource(background[0]);
 
-
-        if (mIndex == 0 && mShowingAnswer) {
+        if (mIndex == 0 && !mShowingAnswer) {
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java]: This was just a mistake in the original implementation as far as I can tell. It meant that on when we are only displaying the question on the first card, a "previous" button was shown, even though there is no previous to go to.

**Comment by mikehardy** [comment]
Hey @timrae - I know you were out - so I'm basically just re-sending this but as one coherent / complete nugget:
- I believe I have responded to everything. If you accept the responses I'll tidy up all the commits and re-push and re-tag you. If you want more changes obviously holler.
- The [Codacy config changes](https://github.com/ankidroid/Anki-Android/pull/4988#discussion_r219573286) (ignore the com.ichi2.anki.uitests package, and set RightCurly checkstyle) are things only you can do either way - Codacy will be green if recorded UI tests are ignored

I'm keen on this one because it's an immediate batch of crash reports every alpha release at the moment

File: AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java [hunk 8]
```diff
@@ -105,14 +105,17 @@ protected void executeCommand(int which) {
         @Override
         public void onClick(View view) {
             if (mShowingAnswer) {
+                // If we are showing the answer, any click any click will show the question
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/anki/Previewer.java]: Typo

**Comment by mikehardy** [comment]
```
I don't understand, as far as I can tell I gave you admin access to codacy...? I 
want Codacy to fail whenever someone writes code that goes against our style file. 
Isn't there an option to enable that without having to manually set each style rule 
individually?
```
I checked and I don't have the "settings" option on the left of [the codacy site](https://app.codacy.com/project/timrae/Anki-Android/dashboard) so I can't configure it myself to help, or I would. I'm a member, but no settings access?

For having codacy verify against our style file we'd have to put the style file where codacy looks for it - in the project root - and from [PR 4919](https://github.com/ankidroid/Anki-Android/pull/4919#issuecomment-416422301) where we implemented it you asked me not to do that 
```
In terms of the idea file, I'd rather have it on codacy than duplicated in git. And 
we should probably make a feature request to support a standard Android layout, which 
I believe we have?!
```

The feature request is not possible because we went from checkstyle->idea config and that's a one-way transform while codacy just runs a checkstyle in a docker, not an idea verifier. Our checkstyle and idea files are still identical though I think and don't move much? so either moving the file to root or doing a one-time codacy checkstyle audit / fix would be the full action.

...or just adding right curly rule, or me just finally getting the clue about the right curly...

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java (hunk 1 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java]: I pulled that out and re-pushed, the separate PR has the reasoning self-contained in PR description

**Comment by mikehardy** [comment]
@timrae thanks again for the review. This no longer has threading/loading changes in it and I fixed the typo. If this passes muster then I'll clean up the commits (mostly squashing the last 5, but putting anything relevant in the first 2) and re-push, then it should be ready for a clean merge

**Comment by mikehardy** [comment]
@timrae I just rebased and re-packaged the commits so they are clean and coherent, but didn't change the logic any after peeling out the threading change. I'd like another alpha soon that fixes both crashes #4987 and #5000 and I did my level best to respond to everything here, so I'm going to wait a bit to give you a chance to raise your hand in case you object but otherwise merge it

**Comment by mikehardy** [comment]
@timrae we have two crash fixes lined up on master now, I don't know what it's like to operate the release machinery but if you wanted to pull the cord and fire it up to send a new alpha out, I'll run around with the broom and dustpan after to pick up any pieces (fingers crossed there aren't any...)
