### PR TITLE
fix(filtered-decks): handle duplicate name on creation

### LINKED ISSUE #18761: Filtered decks search issues
### Bugs:
- [x] If there's a filtered deck with an empty search that has been rebuilt, then you can't create a filtered deck with search `d`, but you can with search `is:new`.
- [ ] Creating a filtered deck with search `is:new` caused the default search when you create a new filtered deck to be also `is:new`.

https://github.com/user-attachments/assets/547bacc6-725c-4952-b910-db2b1e5362b4

 _Originally posted by @ZornHadNoChoice in [#18627](https://github.com/ankidroid/Anki-Android/issues/18627#issuecomment-3030017618)_

### PR DESCRIPTION
**Pull request by david-allison**
In Anki Desktop, creating a filtered deck suffixes a "+" if the deck name is already found.

Before this change, AnkiDroid edited the provided deck, rather than creating a new one

We now perform the same operation

* Fixes #18761

Tested via unit tests

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt [hunk 1]
```diff
@@ -195,12 +195,26 @@ class CreateDeckDialog(
     }
 
     fun createFilteredDeck(deckName: String): Boolean {
+        fun validFilteredDeckName(initialName: String): String {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt:198]: Our Filtered Deck flow isn't the same as Anki Desktop and has a LOT of deprecated code

I expect the code to go fairly soon, so won't use the upstream flow/functionality here
