### PR TITLE
Handle Backup restoration-related crashes

### LINKED ISSUE #7630: Startup crash if app is being backed up
Note: Outcomes of the restore haven't been tested, might be best to perform on a parallel release

* Open AnkiDroid
* `adb shell bmgr restore com.ichi2.anki`
* Open AnkiDroid

```
2020-11-09 03:18:01.758 7937-7937/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 7937
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.DeckPicker}: java.lang.NullPointerException: Attempt to read from field 'java.lang.Throwable com.ichi2.anki.AnkiDroidApp.mWebViewError' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.Throwable com.ichi2.anki.AnkiDroidApp.mWebViewError' on a null object reference
        at com.ichi2.anki.AnkiDroidApp.webViewFailedToLoad(AnkiDroidApp.java:612)
        at com.ichi2.anki.DeckPicker.firstCollectionOpen(DeckPicker.java:576)
        at com.ichi2.anki.DeckPicker.onCreate(DeckPicker.java:436)
        at android.app.Activity.performCreate(Activity.java:7458)
        at android.app.Activity.performCreate(Activity.java:7448)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7625) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) 
2020-11-09 03:18:01.858 1268-1620/? E/WindowManager: win=Window{2021bc7 u0 Splash Screen com.ichi2.anki EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true
2020-11-09 03:18:02.002 1777-11040/? E/DollieAdapterService: notifyActivityState pkg:com.ichi2.anki/com.ichi2.anki.IntentHandler state:18 fg:false mUid:10455
```

This wouldn't hit ACRA as onCreate is not called

Related: #6870 (and likely a lot more)

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose

If the app is restored from a backup, then `Application.onCreate` is not called. This lead to a lot of crashes as this was assumed to always happen.

## Fixes
Fixes #7630 

## Approach
* On each activity `onCreate`
* Detect if the failure occurred
* Show a message
* Kill the app so it starts normally.

## How Has This Been Tested?

My Android 9 

Test via: `.\adb shell bmgr restore com.ichi2.anki`

image

## Learning

https://stackoverflow.com/questions/57211036/why-backup-related-process-might-cause-applications-oncreate-is-not-executed

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] Strings resources: All strings added as resources are unique or contain a comment for seemingly duplicate strings to explain the difference between both resources

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java [hunk 1]
```diff
@@ -190,6 +191,17 @@ public static InputStream getResourceAsStream(@NonNull String name) {
     }
 
 
+    public static boolean wasStartedAfterBackupRestoration() {
+        return sInstance == null;
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:195]: There may be a better way to do this (check if Application is an instance of another class), this is the main line that worries me, as if this fails, it means the process will be killed.

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:195]: Seems like you could know for sure if it "wasStartedAfterBackupRestoration" if you implemented a BackupAgent a la https://stackoverflow.com/a/57244796/9910298 and stored the related state so you could query the BackupAgent implementation if onRestoreFinished has already been called.

But that is likely overkill, I think the assumption is valid now, but it is embedded in the name, perhaps you could change the method name to something that exposes the assumption in case calling code doesn't understand there is an assumption, like "singletonInstanceInitialized" with a comment that with current code if onCreate was called, it will always be true, so it can be used as a shorthand for that currently, and thus serves as a shorthand for a backup restoration test

**Review by mikehardy — APPROVED** [review]
This is an epic crash fix! I learned a lot just reading about it, thanks.
I left a comment about just documenting the assumption (effectively) by changing the name you use for the critical conditional, but a name change doesn't preclude approval. Implementor's choice on that one then merge at will. Kudos

File: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java (hunk 1 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:195]: Renamed to `isInitialized`

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:195]: works for me!

**Comment by mikehardy** [comment]
I like the partially shaved looking bison approximating a yak shave on your screen

**Comment by mikehardy** [comment]
windows unit test failure in CI appears to be some racy thing, unrelated

```
com.ichi2.anki.DeckPickerTest > limitAppliedAfterReview FAILED
    java.lang.NullPointerException
        at com.ichi2.anki.DeckPickerTest.lambda$limitAppliedAfterReview$6(DeckPickerTest.java:176)
        at androidx.test.core.app.ActivityScenario.lambda$onActivity$2$ActivityScenario(ActivityScenario.java:660)
        at androidx.test.core.app.ActivityScenario$$Lambda$4.run(Unknown Source)
        at androidx.test.core.app.ActivityScenario.onActivity(ActivityScenario.java:670)
        at com.ichi2.anki.DeckPickerTest.limitAppliedAfterReview(DeckPickerTest.java:174)
```

**Comment by david-allison-1** [comment]
> windows unit test failure in CI appears to be some racy thing, unrelated (restarted...)
> 
> ```
> com.ichi2.anki.DeckPickerTest > limitAppliedAfterReview FAILED
>     java.lang.NullPointerException
>         at com.ichi2.anki.DeckPickerTest.lambda$limitAppliedAfterReview$6(DeckPickerTest.java:176)
>         at androidx.test.core.app.ActivityScenario.lambda$onActivity$2$ActivityScenario(ActivityScenario.java:660)
>         at androidx.test.core.app.ActivityScenario$$Lambda$4.run(Unknown Source)
>         at androidx.test.core.app.ActivityScenario.onActivity(ActivityScenario.java:670)
>         at com.ichi2.anki.DeckPickerTest.limitAppliedAfterReview(DeckPickerTest.java:174)
> ```

#7565 - will get it looked at.
