### PR TITLE
fix[lint]: allow Kotlin companion objects 

### LINKED ISSUE #9223: [Bug] Kotlin: `COMPANION` is caught by naming conventions [ConstantFieldName]
```
* What went wrong:
Execution failed for task ':AnkiDroid:lintPlayRelease'.
> Lint found errors in the project; aborting build.
  
  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...
  Errors found:
  
  /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/analytics/Acra.kt: Error: Field should be named: 'COMPANION' [ConstantFieldName]
 
```

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description
`ConstantFieldName` lint was triggered by auto-generated Kotlin
companion objects named "Companion" (expected: COMPANION)

## Fixes
Fixes #9223
Unblocks #9222

## Approach
As these are auto-generated, allow constants called "Companion"

## How Has This Been Tested?
Lint no longer fails on #9222

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: lint-rules/src/main/java/com/ichi2/anki/lint/rules/ConstantFieldDetector.java [hunk 1]
```diff
@@ -53,7 +52,10 @@ protected boolean isApplicable(@NonNull UVariable variable) {
         // For instance: the only thing that matters is final - are these constants:
         // public final int - no
         // private static final - maybe?
-        return variable.isStatic() && variable.getVisibility() == UastVisibility.PUBLIC && variable.isFinal();
+        return variable.isStatic()
+                && variable.getVisibility() == UastVisibility.PUBLIC
+                && variable.isFinal()
+                && !"Companion".equals(variable.getName()); // #9223 - fix for kotlin companion objects
```
Comment (ShridharGoel) [inline lint-rules/src/main/java/com/ichi2/anki/lint/rules/ConstantFieldDetector.java:58]: Shouldn't it be "companion" with the first alphabet in lower case since that's the keyword.

Comment (ShridharGoel) [reply lint-rules/src/main/java/com/ichi2/anki/lint/rules/ConstantFieldDetector.java:58]: Shouldn't it be "companion" with the first alphabet in lower case since that's the keyword?

Comment (david-allison-1) [reply lint-rules/src/main/java/com/ichi2/anki/lint/rules/ConstantFieldDetector.java:58]: Checked via string concatenation in the output and the variable internally is cased as provided

**Review by mikehardy — APPROVED** [review]
Nice
