### PR TITLE
Simplify rules for initially selected deck in stats and browser

### LINKED ISSUE #4999: One deck always set as current when switching to browser
###### Reproduction Steps

0. I have a couple of decks: Geography, English, German, Spanish and French. French is the one I created only recently, about 2 weeks ago.
1. Pick any deck other than French by clicking it - it becomes the 'current/selected' deck and it is marked with a 'grayed' background.
2. Go to 'Browse cards'.

###### Expected Result

I expect the browser to have the 'current' deck selected and show its cards as specified in the manual and allow me to perform searches in that very deck.

###### Actual Result

No matter which deck was selected, the browser shows French whenever it is started, and I need to change the deck to perform searches I want to. When I go back, the French deck is 'grayed' i.e. current/selected by AnkiDroid, overriding my preference from before starting the browser.

###### Debug info

AnkiDroid Version = 2.8.4

Android Version = 8.1.0

ACRA UUID = 57ffb637-79cd-4fc7-a8ed-83cd0c0fa31a

###### Research

*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

### LINKED ISSUE #5010: Changing deck in Browser and Statistics changes the currently selected deck
###### Reproduction Steps

1. Start from Deck Picker with Deck A selected
2. Open Browser or Stats
3. Select Deck B
4. Go back to the Deck Picker

###### Expected Result
Deck A is still the selected deck

###### Actual Result
Deck B is the selected deck

This is strongly related to #4999

### PR DESCRIPTION
**Pull request by timrae**
## Purpose / Description
For both stats and browser, the deck spinner no longer changes the libanki current deck. Changing the libanki deck was awkward and unintuitive, and we were only doing that to avoid changing libanki (in #766).

When opening the browser for the first time, the current libanki deck is always selected. When the deck is changed via the spinner, we remember the choice and use it next time the browser is opened (as before). Now however, the choice is cleared when the app is first started or a new deck is selected from the deck picker to avoid a seemingly "random" deck getting selected. This memory of the deck id deviates somewhat from Anki Desktop, but IMO it makes sense to deviate here, since users often switch back and forward between the reviewer and the browser while reviewing. This use case is addressed in Anki Desktop by allowing users to keep both windows open, which in general we can't do in AnkiDroid. 

For stats, there is little benefit to remembering the deck id, so the current libanki deck is always shown when the stats Activity is opened, as per Anki Desktop. The user can change to "all decks", or a specific deck (a feature not yet offered by Anki desktop) via the deck spinner, which no longer affects the libanki selected deck.

## Fixes
Fixes #4999
Fixes #5010 

## Approach
* Refactor libanki a bit to allow getting stats for an arbitrary deck id
* Remove a bunch of intent crud for handling the previous business logic
* Implement the business logic described above from scratch

## How Has This Been Tested?

Basic functionality testing on the emulator

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java [hunk 1]
```diff
@@ -324,6 +330,27 @@ private void changeDeck(int selectedDeck) {
...
 
+    private Long getLastDeckId() {
+        SharedPreferences state = getSharedPreferences(PERSISTENT_STATE_FILE,0);
+        if (!state.contains(LAST_DECK_ID_KEY)) {
+            return null;
+        }
+        return state.getLong(LAST_DECK_ID_KEY, -1);
+    }
+
+    static void clearLastDeckId() {
```
[the remark this answers is not in the document]
Comment (timrae) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java]: It's funny, Android studio suggested me to change it from public to package-private... It doesn't hurt to make it explicitly public I guess.

**Comment by mikehardy** [comment]
There are a few things that I had to change from default android studio, the access specifier stuff is one of those

File: AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java [hunk 2]
```diff
@@ -307,13 +309,18 @@ public boolean onNavigationItemSelected(final MenuItem item) {
...
-     */
     protected void openCardBrowser() {
-        Intent cardBrowser = new Intent(this, CardBrowser.class);
-        cardBrowser.putExtra("selectedDeck", getCol().getDecks().selected());
-        startActivityForResultWithAnimation(cardBrowser, REQUEST_BROWSE_CARDS, ActivityTransitionAnimation.LEFT);
+        Intent intent = new Intent(NavigationDrawerActivity.this, CardBrowser.class);
+        Long currentCardId = getCurrentCardId();
+        if (currentCardId != null) {
+            intent.putExtra("currentCard", currentCardId);
+        }
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java]: Is this related? This looks like a fix for some unlinked issue

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java]: Ahh - it's pulling something from Reviewer up the object hierarchy to make it more generally possible, if I read the change to Reviewer correctly.

File: AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java [hunk 3]
```diff
@@ -340,6 +340,34 @@ public static String ids2str(JSONArray ids) {
         return str.toString();
     }
 
+    /**
+     * Note: NOT in libanki
+     * Return a string of deck ids for the provided deck and its children, suitable for an SQL query
+     * @param deckId the deck id to filter on, or zero for all decks
+     * @param col collection
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java]: param doc says zero for all decks, but logic branches on null for all decks

File: AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java [hunk 4]
```diff
@@ -68,12 +70,14 @@
     public static final int ANSWER_BUTTONS_TAB_POSITION = 7;
     public static final int CARDS_TYPES_TAB_POSITION = 8;
 
+    private static final long ALL_DECKS_ID = 0L;
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java]: combined with the Stats area where the long is boxed and null-checked to mean all decks, having the unboxed long here use 0L to mean all decks seems confusing to me. One or the other?

**Comment by mikehardy** [comment]
I've internally put myself on stricter probation since the upgrade logic issue and until I can justify my Prefs crash change, so I won't say it's a review - but I left some comments - hopefully they're useful

File: AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java (hunk 4 above)
Comment (timrae) [reply AnkiDroid/src/main/java/com/ichi2/anki/Statistics.java]: Yeah you're right. I initially wanted to use null to mean all decks, but then as the patch evolved I needed null to mean no last selected deck in the browser. I'll change it in stats to make it consistent with the browser.

**Comment by timrae** [comment]
Should be ready to go now

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java [hunk 5]
```diff
@@ -508,8 +535,14 @@ public boolean onItemLongClick(AdapterView<?> adapterView, View view, final int
 
         getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_ALWAYS_HIDDEN);
 
-        // set the currently selected deck
-        selectDropDownItem(getDeckPositionFromDeckId(getIntent().getLongExtra("defaultDeckId", -1)));
+        // If a valid value for last deck exists then use it, otherwise use libanki selected deck
+        if (getLastDeckId() != null && getLastDeckId() == ALL_DECKS_ID) {
+            selectDropDownItem(0);
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java]: This could be ALL_DECKS_ID again to avoid the magical zero here I think?

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java [hunk 6]
```diff
@@ -923,20 +956,15 @@ public void selectDropDownItem(int position) {
         mActionBarSpinner.setSelection(position);
         if (position == 0) {
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java]: I'm not intending to harp on this 0 thing but *if* (and only if) you want to do one more polish to avoid magic numbers, the 0 here is also "all decks" and could be the same constant - it would have helped me the first time I met this code, at least...

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java (hunk 5 above)
Comment (timrae) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java]: Nope it's not the same thing. One is an index, the other a deck id. They happen to have the same value but that's just a coincidence.

Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java]: Ah cool - they do conflate easily but works for me. I have no nits left to pick, this feature is something I will actually notice in personal use - good stuff

**Comment by timrae** [comment]
No problem with nitpicks
