### PR TITLE
fixed: deck search not scrolling to current deck in statistics

### LINKED ISSUE #9935: [Bug] regression: deck search: scroll to current deck in statistics
###### Problem

I'm using the latest version from Google Play. It looks like in recent versions the window that helps you select a deck in statistics has changed from a simple drop-down to a full-fledged window with search. One thing that I noticed that was missing and what I relied very much on was that when I press drop-down, I expect the drop-down to be scrolled down so that to the current deck is on top of the view.

image

As you can see, I'm in "statistics" view, the current deck is "norwegian". When I tap on the drop-down, the first deck on top of the window is "_off". But anki should scroll down so that "norwegian" is on the top -- that's how it was in the previous versions and it was convenient because I mostly switch between decks that are close to each other. Now I have to scroll or type a deck name.

### PR DESCRIPTION
**Pull request by yshubham8419**
## Purpose / Description
fix: deck search not scrolling to current deck in statistics

## Fixes
Fixes #9935 

## Approach
1.Passed the current deck Id as argument to the dialog fragment
2.found the position of the deck in recycler view
3.Scroll to that position

## How Has This Been Tested?
Tested on my personal device.

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
seems reasonable, thank you!

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt [hunk 1]
```diff
@@ -105,6 +110,19 @@ open class DeckSelectionDialog : AnalyticsDialogFragment() {
...
+        var pos = 0
+        for (item in decks.sorted()) {
+            if (did == item.deckId) {
+                pos = i
+                break
+            }
+            i++
+        }
+        return pos
+    }
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt:124]:
```suggestion
    private fun getPositionOfDeck(did: Long, decks: List<SelectableDeck>)
        = decks.sorted().indexOfFirst { it.deckId == did }
```

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt [hunk 2]
```diff
@@ -105,6 +110,19 @@ open class DeckSelectionDialog : AnalyticsDialogFragment() {
         return mDialog!!
     }
 
+    private fun getPositionOfDeck(did: Long, decks: List<SelectableDeck>): Int {
+        var i = 0
+        var pos = 0
+        for (item in decks.sorted()) {
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt:116]: Explain in a comment why `sorted()` is needed (both 'all decks' and the individual ids I presume)

I'd prefer that the sorted (immutable) list from `DecksArrayAdapter` was provided to this function so we don't need to be concerned with the implementation details of other classes

**Review by david-allison — CHANGES_REQUESTED** [review]
Can you use `DeckId` instead of `Long` for the type. It should  already exist as a `typealias`

**Comment by yshubham8419** [comment]
@david-allison thanks for the hints

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt [hunk 3]
```diff
@@ -105,6 +110,19 @@ open class DeckSelectionDialog : AnalyticsDialogFragment() {
...
+        var pos = 0
+        for (item in decks) {
+            if (did == item.deckId) {
+                pos = i
+                break
+            }
+            i++
+        }
+        return pos
+    }
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt:124]: My suggestion was not applied here. Was there a reason?

**Review by david-allison — APPROVED** [review]
Looks great, thanks!

**Comment by david-allison** [comment]
Done, congrats!!!

If you're on [our Discord](https://discord.gg/qjzcRTx), send me a PM and I'll add some roles
