### PR TITLE
Fix #5253 - Deck Options Corruption on Export

### LINKED ISSUE #5253: Deck option group changes after deck export
###### Reproduction Steps

1. Have a deck with an own option group (other than default)
2. Choose "export" from menu, untick the checkboxes and export
3. In the following dialogue choose "save file" and save to any folder

###### Expected Result

The export won't change anything on my collection

###### Actual Result

The export causes the option group of the exported deck to change to "default". That means, all cards will eventually be re-sorted, all deck settings will change and AnkiDroid will most likely require a full sync (so in my case).

The original deck option group is still there, users have to switch manually back to this group and cards will (eventually) be re-sorted. 

This sorting and syncing forth and back costs a lot of time and in addition it's not sure if the original sort order or anything else might be screwed up now (Anki desktop is needed to check this since there's no way to view the due time on Ankidroid).

###### Debug info

AnkiDroid Version = 2.9alpha66

Android Version = 9

ACRA UUID = f2d13677-d957-460e-9f8e-33ca6f832c17

Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

### LINKED ISSUE #5708: Collection not opened - custom study
I can't use custom study. Every time I open the deck and click on a card (to see the answer) I get the following message:

"Collection not opened - An error occurred, while accessing your collection. It may have been caused by a harmless bug, or there might be a problem with it.

Try running check database, or restoring from backup by pressing "options" button. If you continue to see this message, please file a bug report."

I did the abovementioned steps, but it didn't help. What else can I try to be able to enter custom study again?

My bug report is this:

AnkiDroid Version = 2.9.1

Android Version = 8.0.0

ACRA UUID = 5d6e2fc5-d664-46b2-b69f-cbb0be3fa9e8

###### Reproduction Steps

1. Running check data base
2. Restoring all decks from backup
3. Deleting custom study deck and tried again

###### Expected Result

I hoped to be able to access custom study.

###### Actual Result

I receive the following message: 
"Collection not opened - An error occurred, while accessing your collection. It may have been caused by a harmless bug, or there might be a problem with it..."

###### Debug info

AnkiDroid Version = 2.9.1

Android Version = 8.0.0

ACRA UUID = 5d6e2fc5-d664-46b2-b69f-cbb0be3fa9e8

###### Research
*Enter an [ x ] character to confirm the points below:*

x

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description

User complaint that exporting a deck reset the deck options to 1.

This also appears to have been the cause of a dynamic deck having options, and therefore being corrupted. 

## Fixes
Fixes #5253
Fixes #5708

## Approach
We fix this via an inefficient deep clone.

## How Has This Been Tested?

1. New Collection - created on 2.10alpha46
2. Create New Deck
3. Create new options group and assign to new deck
4. Fails - new deck's option group is set to default
5. Load 2.10alpha51
5. Export
6. Passes - deck is still the same

Also tested with default deck and a custom study deck, both were corrupt (database errors on study).

## Learning (optional, can help others)

[stackOverflow: How do I clone an org.json.JSONObject in Java?](https://stackoverflow.com/questions/12809779/how-do-i-clone-an-org-json-jsonobject-in-java)

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by mikehardy** [comment]
for things in libanki the first question I always have is "how does anki desktop do it?" - a link to the corresponding code in anki desktop python would be tremendously useful

good catch though :-)

File: AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java [hunk 1]
```diff
@@ -313,6 +315,17 @@ public void setIncludeMedia(boolean includeMedia) {
     public void setDid(Long did) {
         mDid = did;
     }
+
+    private static class JSONObjectUtils {
+        private JSONObjectUtils() {
```
Comment (timrae) [inline AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java]: Codacy Issue found: [Avoid unnecessary constructors - the compiler will generate these for you](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5212732)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5212732&bid=17092898)

**Comment by david-allison-1** [comment]
> for things in libanki the first question I always have is "how does anki desktop do it?" - a link to the corresponding code in anki desktop python would be tremendously useful
> 
> good catch though :-)

https://github.com/ankitects/anki/blob/e3a57a41936d57314cb72996955aaaf45f313c9c/pylib/anki/exporting.py#L236-L248

**Comment by mikehardy** [comment]
> > for things in libanki the first question I always have is "how does anki desktop do it?" - a link to the corresponding code in anki desktop python would be tremendously useful
> > good catch though :-)
> 
> Code:
> 
> [ankitects/anki:pylib/anki/exporting.py@`e3a57a4`#L236-L248](https://github.com/ankitects/anki/blob/e3a57a41936d57314cb72996955aaaf45f313c9c/pylib/anki/exporting.py#L236-L248)
> 
> Note the `dict()`, which I believe acts as a clone.

Yep https://python-reference.readthedocs.io/en/latest/docs/functions/dict.html#remarks - if you provide it a mapping, it copies the mapping - this looks right then

**Comment by mikehardy** [comment]
marked for 2.9.x pick because as it stands it's imminently pickable - can change of course if this blows up as it goes from draft to real

**Comment by david-allison-1** [comment]
Confirmed as fixed. Moving to regular PR.

File: AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java (hunk 1 above)
Comment (david-allison-1) [reply AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java]: I feel a private constructor is more explicit.

**Comment by mikehardy** [comment]
2.10alpha52 is launched with this, available as soon as google finishes chewing on it

**Comment by david-allison-1** [comment]
Also fixes #5202
