### PR TITLE
fix: stabilise description dialog shaking

### LINKED ISSUE #19323: Deck description dialog shakes sometimes
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Edit the description of a deck.
2. Add some text.
3. Add (or remove) new lines before that text on a separate line from that text.

https://github.com/user-attachments/assets/3e131d6e-3777-438d-990d-4b93dbc97fa8

### Expected behaviour

No shaking.

### Debug info

```text
AnkiDroid Version = 2.23.0alpha4 (fb3fadbdebac9b191096a739e730d47ad9f6db09)  
Backend Version = 0.1.61-anki25.09 (25.09 539054c34dccf8b89ca7ea9c9c40ecaf172de759)  
Android Version = 13 (SDK 33)  
ProductFlavor = full  
Device Info = Xiaomi | POCO | mondrian | mondrian_global | 23013PC75G | qcom  
Webview User Agent = Mozilla/5.0 (Linux; Android 13; 23013PC75G Build/TKQ1.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/140.0.7339.208 Mobile Safari/537.36  
ACRA UUID = b9d03d9a-5af9-4e67-987e-cc15799171e2  
FSRS = 5.1.0 (Enabled: true)  
Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by HS0204**
## Purpose / Description
When multiple lines are entered in edit deck description dialog, the dialog shakes.
This was caused by a conflict between the calculation performed by `TextInputLayout` and the changes to the height of `TextInputEditText`.
This PR stabilises the description dialog by resolving the conflicting frame calculations.

## Fixes
* Fixes #19323 

## Approach
- To find the cause out, I looked at the `dialog_deck_description.xml`, `NestedScrollView` - `TextInputLayout` - `TextInputEditText`.
- When I removed `TextInputLayout`, it was stable without shaking and I identified that main cause was from it.
- Problem: `TextInputLayout` triggered multiple `requestLayout()` calls within the same frame as `TextInputEditText` height changes.
- Solution: Post `requestLayout()` to the end of the message queue via `post {}`, ensuring it runs after `TextInputLayout`'s internal layout pass completes.
- I left the comment because the reason for the code seemed a bit vague if someone didn't know this situation.

## How Has This Been Tested?
Manually tested on a device. Compared the behaviour before and after the fix.
- Issue reproduction

https://github.com/user-attachments/assets/81633917-5bfa-4c56-a820-b428b67e005a

- After the fix

https://github.com/user-attachments/assets/916c2561-4cc6-434f-8607-29ea483102ac

## Learning (optional, can help others)
N/A

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/EditDeckDescriptionDialog.kt [hunk 1]
```diff
@@ -134,6 +134,32 @@ class EditDeckDescriptionDialog : DialogFragment() {
...
+
+                override fun onTextChanged(
+                    s: CharSequence?,
+                    start: Int,
+                    before: Int,
+                    count: Int,
+                ) {}
+
+                override fun afterTextChanged(s: Editable?) {
+                    // stabilise TextInputLayout by posting a deferred requestLayout()
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/dialogs/EditDeckDescriptionDialog.kt]: This mostly explains the 'what', could you have another pass at making this explain the 'why'. It doesn't need to be very verbose.

I feel the PR description is excellent, but the code/commit message doesn't explain it as well, and the code & commit message will last much longer than the PR

**Comment by HS0204** [comment]
@david-allison I've changed the code and the comments. I've also tested it locally on a device and it worked.
Could you review it again?

Thank you for the helpful advice on writing maintainable code! Please let me know if I've tweaked the comments too simply.

**Review by david-allison — APPROVED** [review]
BEAUTIFUL!
