### PR TITLE
fix(empty-cards): make undoable, correct result, use backend strings

### LINKED ISSUE #16945: Notifies the subscriber after Card Check removed cards
See #16941 for the details. This issue can be closed specifically when, after a "Check cards" ends by deleting cards, `ChangeManager.notifySubscribers` is called with a `OpChanges` where all at least `card`, `browser_table`, `study_queues` are set to true

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
* #16945

## Fixes
* Fixes #16945

## Approach
* Extract operation to ViewModel
* Extract output to Flow
* add `opChanges { }`
* Use the result of `opChangesWithCount`
* Use `TR` rather than `strings`
* Add `Undo` to the snackbar, and only show it for a short duration
* Test!

## How Has This Been Tested?

⚠️ Unit tests only

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/DeckPickerViewModel.kt [hunk 1]
```diff
@@ -77,6 +80,22 @@ class DeckPickerViewModel : ViewModel() {
...
+    fun findEmptyCards() =
+        viewModelScope.async {
+            return@async withCol { emptyCids() }
+        }
+
+    /**
+     * Removes the provided list of cards from the collection.
+     * @param cids ids from [findEmptyCards]
+     */
+    fun emptyCards(cids: List<CardId>) =
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/DeckPickerViewModel.kt:94]: 🤔  pretty destructive activity - maybe "deleteEmptyCards" ?

**Review by mikehardy — APPROVED** [review]
last commit looks good to me, just bikeshedded you on a name.
approving because that naming is not that important to me vs moving right along here, do what you wish

File: AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt [hunk 2]
```diff
@@ -531,9 +531,11 @@ class Collection(
             Timber.d("removeNotes: %d changes", it.count)
         }
 
-    fun removeCardsAndOrphanedNotes(cardIds: Iterable<Long>) {
-        backend.removeCards(cardIds)
-    }
+    /**
+     * @return the number of deleted cards
+     */
+    // if an invalid/duplicate CardId provided, the output count may be less than the input
```
Comment (lukstbit) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt:537]: Why not include this in the actual method javadoc?

File: AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/DeckPickerViewModel.kt [hunk 3]
```diff
@@ -77,6 +80,22 @@ class DeckPickerViewModel : ViewModel() {
             val targetDeckId = withCol { decks.selected() }
             deleteDeck(targetDeckId).join()
         }
+
+    /** Returns a list of cards to be passed to [deleteEmptyCards] (after user confirmation) */
+    fun findEmptyCards() =
+        viewModelScope.async {
```
Comment (lukstbit) [inline AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/DeckPickerViewModel.kt:86]: Why async?

File: AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt (hunk 2 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Collection.kt:537]: It felt like too much information. I'll fix, thanks!

File: AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/DeckPickerViewModel.kt (hunk 3 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/DeckPickerViewModel.kt]: We need to use the return value, and we need to call a method on the collection

I've changed it to a `suspend fun`, this typically isn't advised for VIewModels, but it's cleaner, and it's fine for this to be cancelled if we lose the activity.

@lukstbit Was this the request?

**Comment by mikehardy** [comment]
you're probably aware but unit tests failed, marked author reply

**Comment by david-allison** [comment]
> you're probably aware but unit tests failed, marked author reply

I wasn't. Fixed!

File: AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/DeckPickerViewModel.kt (hunk 3 above)
Comment (lukstbit) [reply AnkiDroid/src/main/java/com/ichi2/anki/deckpicker/DeckPickerViewModel.kt]: I just had a quick look when I asked(was curious about the _async_ followed by an immediate _await_ but I didn't delve deeper). The suspended function looks ok IMO.

**Review by lukstbit — APPROVED** [review]
LGTM, thanks!
