### PR TITLE
[BugFix] Card Browser Preview works after sorting

### LINKED ISSUE #7286: bug report about preview
I'm in latest verion [2.13.3](https://github.com/ankidroid/Anki-Android/releases/tag/v2.13.3)

###### Reproduction Steps

Enter into Card browser→Change display order→By created time(▼)

Then you select some card to Preview, actually you will preveiw the card by the "By created time(▲)" still. It is a crazy bug.

to preview:

result of preview:

fix it please..

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description
Due to the addition of `CardCache`, the `position` variable was out-of-sync with reality after performing `Collection.reverse()`

## Fixes
Fixes #7286 

## Approach
* Extract to a structure where this can no longer happen
* Fix the numbers after a `reverse()`

## How Has This Been Tested?

Unit & Integration tested

Tested on my phone briefly

## Learning
We still need more tests

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
That is fiendish!

**Comment by mikehardy** [comment]
We have enough release-2.13 branch items I think to do it if I can cherry-pick successfully after all the refactors, if not I might do a release-2.14 cut quickly to get the pending stack of fixes out of alpha and into users' hands. Good catch + fix here!

File: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java [hunk 1]
```diff
@@ -1092,18 +1095,7 @@ public boolean onOptionsItemSelected(MenuItem item) {
...
-                    previewer.putExtra("cardList", getSelectedCardIds());
-                } else {
-                    // Preview all cards, starting from the one that is currently selected
-                    int startIndex = mCheckedCards.isEmpty() ? 0 : mCheckedCards.iterator().next().getPosition();
-                    previewer.putExtra("index", startIndex);
-                    previewer.putExtra("cardList", getAllCardIds());
-                }
-                startActivityForResultWithoutAnimation(previewer, PREVIEW_CARDS);
+                onPreview();
                 return true;
```
Comment (Arthur-Milchior) [inline AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java:1099]: If it does not takes too much time, it would have been nice for review to have it in its own commit, since this part is trivial to check

**Review by Arthur-Milchior — APPROVED** [review]
