### PR TITLE
"Card Browser" action item: Display DeckPicker if no Permissions

### LINKED ISSUE #5930: [ACRA 2.9.6] - Crash on Application Startup from Deck Browser
###### Reproduction Steps

1. Remove permissions from AnkiDroid
2. Select text and click "Card Browser"
3. Opens Browser -> Crash -> Displays request for storage permissions

###### Expected Result

4. No Crash, likely show "welcome to AnkiDroid screen"

###### Actual Result

4. Crash

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/df680ed2-2cc9-43e0-abac-d9f10d2ff55e

```
java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONObject com.ichi2.libanki.Collection.getConf()' on a null object reference
at com.ichi2.anki.CardBrowser.onCreateOptionsMenu(CardBrowser.java:9)
at android.app.Activity.onCreatePanelMenu(Activity.java:3575)
at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:1)
at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:1)
at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2)
at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:1)
at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:5)
at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:1)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7080)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description
Starting the CardBrowser via the 'Card Browser' action item with no permissions would previously crash.

## Fixes
Fixes #5930

## Approach
Now we show a permissions dialog from the DeckPicker.

## How Has This Been Tested?

Tested via unit tests, and on my device.

I've left a TODO in, because I feel the reduction in code duplication would slightly help maintenance, but `IntentHandler` isn't well tested, and it's a lot of effort in a critical part of the code for a slight gain.

## Learning (optional, can help others)
Some unit tests take significantly longer to get right than the code itself.

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5541150&bid=18165981)

File: AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java [hunk 1]
```diff
@@ -248,6 +257,29 @@ public void flagValueIsShownOnCard() {
...
+        app.denyPermissions(Manifest.permission.READ_EXTERNAL_STORAGE);
+        app.denyPermissions(Manifest.permission.WRITE_EXTERNAL_STORAGE);
+        Intent inputIntent = new Intent("android.intent.action.PROCESS_TEXT");
+
+        CardBrowser cardBrowser = Robolectric.buildActivity(CardBrowser.class, inputIntent).create().get();
+
+
+        Intent outputIntent = shadowOf(cardBrowser).getNextStartedActivity();
+        ComponentName component = outputIntent.getComponent();
+        ShadowActivity shadow = Shadows.shadowOf(cardBrowser);
```
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java:273]: Codacy Issue found: [Unnecessary use of fully qualified name 'Shadows.shadowOf' due to existing static import 'org.robolectric.Shadows.shadowOf'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5541150)

File: AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java [hunk 2]
```diff
@@ -248,6 +257,29 @@ public void flagValueIsShownOnCard() {
         assertThat("The card flag value should be reflected in the UI", actualFlag, is(1));
     }
 
+    @Test
+    public void startupFromCardBrowserActionItemShouldEndActivityIfNoPermissions() {
+        Application application = ApplicationProvider.getApplicationContext();
+        ShadowApplication app = Shadows.shadowOf(application);
```
Comment (timrae) [inline AnkiDroid/src/test/java/com/ichi2/anki/CardBrowserTest.java:263]: Codacy Issue found: [Unnecessary use of fully qualified name 'Shadows.shadowOf' due to existing static import 'org.robolectric.Shadows.shadowOf'](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5541150)

**Comment by mikehardy** [comment]
released in 2.11alpha5 / 2.10.3beta1
