### PR TITLE
Fix getsize() and getMetrics deprecations

### LINKED ISSUE #9332: FLAG_FULLSCREEN deprecation in API 30
* FLAG_FULLSCREEN
  * Use WindowInsetsController.hide(int) with WindowInsets.Type.statusBars() instead.
  * Only the usage in `AnkiActivity` needs to be fixed. The usage in `Reviewer.kt` doesn't need to be fixed because the screen is deprecated 

---
The deprecations below don't need to be fixed because the screen that uses it is deprecated and will be eventually removed.

* ~~View.setOnSystemUiVisibilityChangeListener~~
   * ~~Use WindowInsets.isVisible(int) to find out about system bar visibilities by setting a View.OnApplyWindowInsetsListener on this view~~
* ~~View.getSystemUiVisibility()~~
  * ~~SystemUiVisibility flags are deprecated. Use WindowInsetsController instead.~~

### LINKED ISSUE #9333: Display/Size related deprecation in API 30
* WindowManager.getDefaultDisplay()
  * Use Context.getDisplay() instead.
* Display
  * getSize(point)
    * Use WindowManager.getCurrentWindowMetrics() to obtain an instance of WindowMetrics and use WindowMetrics.getBounds() instead.
  * getMetrics()
    * Use WindowMetrics.getBounds() to get the dimensions of the application window area, and Configuration.densityDpi to get the current density

### PR DESCRIPTION
**Pull request by jainv4156**
## Purpose / Description
Replaced deprecated methods Display.getMetrics() and Display.getSize(Point) with WindowManager.getCurrentWindowMetrics().getBounds() for Android R (API 30+) to obtain screen dimensions. Additionally, used Configuration.densityDpi for retrieving screen density. For backward compatibility, retained the use of Display.getMetrics() and Display.getSize(Point) on older Android versions

## Fixes
* Fixes #9333

## How Has This Been Tested?

The changes were tested using Logcat by logging the values obtained from WindowMetrics.getBounds() and comparing them with the values from Display.getSize(Point) and Display.getMetrics(). The results were consistent across devices running Android 30+ and older versions.

 - getmetrix() 
WhatsApp Image 2025-01-24 at 4 01 53 PM

- getSize()

WhatsApp Image 2025-01-24 at 4 06 59 PM
1st log is of getSize() used by UsageAnalitics
2nd , 3rd log is of getSize() used by whiteboard portrate, landscape

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by lukstbit** [comment]
Please fill the PR template with more info about what was done, especially how the changes were tested. Also you linked to the incorrect issue.

**Comment by jainv4156** [comment]
> Please fill the PR template with more info about what was done, especially how the changes were tested. Also you linked to the incorrect issue.



> Please fill the PR template with more info about what was done, especially how the changes were tested. Also you linked to the incorrect issue.

My mistake, thanks for pointing that out!

**Comment by jainv4156** [comment]
> ## Purpose / Description
> _Describe the problem or feature and motivation_
> 
> ## Fixes
> * Fixes [Display/Size related deprecation in API 30 #9333](https://github.com/ankidroid/Anki-Android/issues/9333)
> 
> ## Approach
Replaced deprecated methods Display.getMetrics() and Display.getSize(Point) with WindowManager.getCurrentWindowMetrics().getBounds() for Android R (API 30+) to obtain screen dimensions. Additionally, used Configuration.densityDpi for retrieving screen density. For backward compatibility, retained the use of Display.getMetrics() and Display.getSize(Point) on older Android versions
> ## How Has This Been Tested?
> tested it through log statements and recieving
> 
> ## Checklist
> _Please, go through these checks before submitting the PR._
> 
> * [x]  You have a descriptive commit message with a short title (first line, max 50 chars).
> * [x]  You have commented your code, particularly in hard-to-understand areas
> * [x]  You have performed a self-review of your own code
> * [x]  UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
> * [ ]  UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

**Comment by jainv4156** [comment]
Hey Lubstic,

I’ve made the changes you mentioned. Can you take a look at the testing approach and let me know if it’s sufficient or if you think any additional testing is needed?

Thanks!

**Comment by lukstbit** [comment]
> The results were consistent across devices running Android 30+

When I tested it on an emulator(Pixel8A API 35) the width seems to be identical only for portrait and not for landscape: 2279(old code) vs 2400 new code.

File: AnkiDroid/src/main/java/com/ichi2/utils/DisplayUtils.kt [hunk 1]
```diff
@@ -17,18 +17,38 @@
...
+            val windowInsets: WindowInsets = windowMetrics.getWindowInsets()
+            val insets: Insets =
+                windowInsets.getInsetsIgnoringVisibility(
+                    WindowInsets.Type.navigationBars()
+                        or WindowInsets.Type.displayCutout(),
+                )
+
+            val insetsWidth: Int = insets.right + insets.left
+            val insetsHeight: Int = insets.top + insets.bottom
+            point.x = bounds.width() - (insetsWidth)
```
Comment (lukstbit) [inline AnkiDroid/src/main/java/com/ichi2/utils/DisplayUtils.kt:46]: This is too verbose, it should be reduced to one line:

```
point.x = bounds.width() - insets.right - insets.left
point.y = bounds.height() - insets.top - insets.bottom
```

The same for _screenWidth_.

**Review by lukstbit — APPROVED** [review]
LGTM, this looks much better now with the handling of insets.

I left one minor code style to implement as the code is a bit too verbose.

File: AnkiDroid/src/main/java/com/ichi2/utils/DisplayUtils.kt (hunk 1 above)
Comment (jainv4156) [reply AnkiDroid/src/main/java/com/ichi2/utils/DisplayUtils.kt]: Done

Comment (lukstbit) [reply AnkiDroid/src/main/java/com/ichi2/utils/DisplayUtils.kt]: In _screenWidth_ the update code is not equivalent with the previous code, you are subtracting one inset and adding the other inset. Either use parenthesis like in the other class or subtract both insets.

**Review by BrayanDSO — APPROVED** [review]

**Comment by david-allison** [comment]
Hi there @jainv4156! This is the OpenCollective Notice for PRs merged from [2025-02-01 through 2025-02-28](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2025-02-01..2025-02-28+author%3Ajainv4156)
                      
If you are interested in compensation for this work, the process with details is here: https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

We only post one comment per person per month to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for this month

Please understand that our monthly budget is never guaranteed to cover all claims - the cap on payments-per-person may be lower, but we try to make our process as fair and transparent as possible, we just need your understanding.

Thanks!
