### PR TITLE
No counts in abstract flash card viewer

### LINKED ISSUE #7039: [2.13alpha28] Card Template Editor Preview Crash: sched.counts - ArrayIndexOutOfBoundsException
* SchedV1, new profile
* Add a new Basic Note
* Bury Card
* Card Browser - Edit Note - Edit Card Template - Preview

Crash:

```
 FATAL EXCEPTION: Thread-6
Process: com.ichi2.anki, PID: 19157
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.CardTemplatePreviewer}: java.lang.ArrayIndexOutOfBoundsException: length=3; index=-2
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at androidx.test.espresso.base.Interrogator.a(Interrogator.java:31)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:130)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:124)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:40)
	at androidx.test.espresso.action.MotionEvents.a(MotionEvents.java:68)
	at androidx.test.espresso.action.Tap.a(Tap.java:13)
	at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:2)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:9)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:6)
	at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:140)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:4)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=3; index=-2
	at com.ichi2.libanki.sched.Sched.counts(Sched.java:142)
	at com.ichi2.anki.AbstractFlashcardViewer.updateScreenCounts(AbstractFlashcardViewer.java:1879)
	at com.ichi2.anki.AbstractFlashcardViewer.updateForNewCard(AbstractFlashcardViewer.java:1863)
	at com.ichi2.anki.AbstractFlashcardViewer.fillFlashcard(AbstractFlashcardViewer.java:2397)
	at com.ichi2.anki.AbstractFlashcardViewer.updateCard(AbstractFlashcardViewer.java:2264)
	at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:2034)
	at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:1996)
	at com.ichi2.anki.CardTemplatePreviewer.displayCardQuestion(CardTemplatePreviewer.java:157)
	at com.ichi2.anki.CardTemplatePreviewer.onCollectionLoaded(CardTemplatePreviewer.java:246)
	at com.ichi2.anki.AnkiActivity.startLoadingCollection(AnkiActivity.java:325)
	at com.ichi2.anki.CardTemplatePreviewer.onCreate(CardTemplatePreviewer.java:91)
	at android.app.Activity.performCreate(Activity.java:7144)
	at android.app.Activity.performCreate(Activity.java:7135)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:13)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
	... 25 more
```

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
## Purpose / Description

Currently, previewer does not display counts, but still compute it. The trouble is that counts takes current card into consideration, assuming it's a card sent to the reviewer, so in one of the three queue. 

This ensure that the counts (and ETA) are only computed when we actually need them. This save computation time and avoid the problem #7039.

If you accept this design, I'd also suggest to move all members related to the four buttons to Reviewer, since they are never shown in the previewer

Note that this lead to a question: what should we send to JS in the previewer. After all, there is no count, no eta, no list of new card to see... So it's not easy to know what we should send if we ask it. Currently, I return "" and 0, but this may easily be changed
## Fixes
Fixes #7039

## Approach
Ensuring that counts is not called unless we actually want its values

## How Has This Been Tested?

On my phone, using preview of suspended card and reviewing

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 1]
```diff
@@ -3783,22 +3718,25 @@ public String init(String jsonData) {
 
         @JavascriptInterface
         public String ankiGetNewCardCount() {
-            return newCount.toString();
+            return "";
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java]: As mentioned elsewhere I want default values that are obviously "wrong" for the type but nevertheless workable in the javascript type function. Please return -1 for all "number" types

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java [hunk 2]
```diff
@@ -1058,4 +1162,33 @@ public boolean onMenuItemClick(MenuItem item) {
             }
         }
     }
+
+    public JavasScriptFunction javaScriptFunction() {
+        return new JavasScriptFunction();
+    }
+    public class JavasScriptFunction extends AbstractFlashcardViewer.JavaScriptFunction {
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java:1169]:
```suggestion

    public class JavasScriptFunction extends AbstractFlashcardViewer.JavaScriptFunction {
```

**Review by mikehardy — CHANGES_REQUESTED** [review]
Some minor but real things to change - marked separately

Some questions
- did you reproduce the original issue and then verify this fixes it?
- how does this work with CardTemplatePreviewer (it's a part of the AbstractFlashcardViewer family)

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java (hunk 1 above)
Comment (Arthur-Milchior) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java]: Done

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java (hunk 2 above)
Comment (Arthur-Milchior) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java:1169]: Done

**Comment by Arthur-Milchior** [comment]
> * did you reproduce the original issue and then verify this fixes it?

I did try to reproduce on the correction. Didn't try the original one. 

> * how does this work with CardTemplatePreviewer (it's a part of the AbstractFlashcardViewer family)

In both previewer, it simply means that no numbers/eta are shown. Appart from that, it does not change anything (except when you preview the template of a card not in any of the queues of course)

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java [hunk 3]
```diff
@@ -3783,22 +3718,25 @@ public String init(String jsonData) {
 
         @JavascriptInterface
         public String ankiGetNewCardCount() {
-            return newCount.toString();
+            return "-1";
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3721]: Could you leave a comment explaining why, and that this is overridden in a subclass

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java [hunk 4]
```diff
@@ -1060,4 +1162,34 @@ public boolean onMenuItemClick(MenuItem item) {
             }
         }
     }
+
+    public JavasScriptFunction javaScriptFunction() {
+        return new JavasScriptFunction();
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java:1167]:
```suggestion
        return new ReviewerJavaScriptFunction();
```

**Comment by Arthur-Milchior** [comment]
I've been able to reproduce the bug on master.

This is how you preview card from card browser

2020-09-07-153705_622x1151_scrot


2020-09-07-153703_622x1151_scrot 

And this is how you preview them from the template editor

2020-09-07-153716_622x1151_scrot
2020-09-07-153714_622x1151_scrot

File: AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java (hunk 3 above)
Comment (mikehardy) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3721]: I updated the Wiki with the policy I'm attempting to put in place: https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API/_compare/e21015172d53c6a2ade17729b7415141f2975584...1d35c0c37a070f3666c031af56b1717591990e39

Comment (Arthur-Milchior) [reply AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3725]: Done

File: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java [hunk 5]
```diff
@@ -1060,4 +1162,34 @@ public boolean onMenuItemClick(MenuItem item) {
             }
         }
     }
+
+    public ReviewerJavasScriptFunction javaScriptFunction() {
+        return new ReviewerJavasScriptFunction();
+    }
+
+    public class ReviewerJavasScriptFunction extends JavaScriptFunction {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java:1170]:
```suggestion
    public class ReviewerJavaScriptFunction extends JavaScriptFunction {
```

Comment (Arthur-Milchior) [reply AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java:1170]: Oops

**Review by david-allison-1 — APPROVED** [review]
LGTM

**Review by mikehardy — APPROVED** [review]
I like it - thanks for going with me on the default values for javascript, as mentioned separately it has worked well for me in the past for an API consumed by frequently-novice programmers, I hope it will again here
