### PR TITLE
Fixes #7983 Remaining time wrongly displayed as "0s" when falling und…

### LINKED ISSUE #7983: [Bug] Remaining time wrongly displayed as "0s" when falling under "1min"
###### Reproduction Steps

1. Review your cards until remaining time is 1 minute
2. Review a few more cards

###### Expected Result

It should either show "0 minute" or "55 seconds" (or whatever estimate is accurate given seconds/card)

###### Actual Result

It shows "0s". It suggests that Anki chooses the appropriate unite based on the remaining time (it does show "1h 5min" if over 59min), despite computing the remaining time in minutes. The smallest unit of display should match the estimation unit.
Admittedly, this is a minor bug, but perhaps it's trivial to fix :)

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by AyaanJaved**
Added an if check which clamps the remaining time to 1 minute in case it goes under it.

## Purpose / Description
Intends to fix the wrong time (0 minute) displayed when the remaining time is under a minute.

Screenshot_20210326-170251

## Fixes
Fixes #7983 

After Fix
Screenshot_20210326-170731

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java [hunk 1]
```diff
@@ -195,6 +195,9 @@ public static String remainingTime(Context context, long time_s) {
         Resources res = context.getResources();
         if (time_s < TIME_HOUR_LONG) {
             time_x = (int) Math.round(time_s / TIME_MINUTE);
+            if(time_x == 0) {
```
Comment (david-allison-1) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java:198]: nitpick: matches coding style
```suggestion
            if (time_x == 0) {
```

**Review by david-allison-1 — APPROVED** [review]
Thanks!!!

File: AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java [hunk 2]
```diff
@@ -195,6 +195,9 @@ public static String remainingTime(Context context, long time_s) {
         Resources res = context.getResources();
         if (time_s < TIME_HOUR_LONG) {
             time_x = (int) Math.round(time_s / TIME_MINUTE);
+            if (time_x == 0) {
+                time_x++;
+            }
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java:200]: This is going to seem like a nitpick but I think it's important

1- if the idea is to "clamp" something, you want to wipe out the whole range below the value you want to clamp, just in case, not just one specific value (0), so Math.max(ETA, 1) is better (changing it to `< 1` as a comparison could also work but we're already using Math methods, just throw one more in...)
2- there should be a comment so future code readers know why we are doing this

```suggestion
            // get time remaining, but never less than 1
            time_x = Math.max((int) Math.round(time_s / TIME_MINUTE), 1);
```

**Review by mikehardy — CHANGES_REQUESTED** [review]

File: AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java (hunk 2 above)
Comment (AyaanJaved) [reply AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java]: Thanks for the suggestions
Definitely gonna keep them in mind the next time I contribute

**Review by mikehardy — APPROVED** [review]
of course my own code suggestion looks good to me :laughing: - but seriously, this looks good to go now, thank you!

**Comment by mikehardy** [comment]
Hi there!

Just a friendly notice (one per person for PRs merged in March, regardless of PR quantity) that we try to process OpenCollective payments monthly - it's time for March 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

Thanks!
