### PR TITLE
Fix(Card Browser): ANR on using scrollbar

### LINKED ISSUE #20173: The scrollbar can cause lag
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

Simply drag the scrollbar in the card browser. 

This doesn't happen in v2.23.1.

https://github.com/user-attachments/assets/6f30b533-5211-4228-8e59-68be53c3ef03

### Expected behaviour

No lag.

### Debug info

```text
AnkiDroid Version = 2.24.0alpha4 (ae379be94b660291e90d72501f5725ed396b9a80)  
Backend Version = 0.1.63-anki25.09.2 (25.09.2 3890e12c9e48c028c3f12aa58cb64bd9f8895e30)  
Android Version = 13 (SDK 33)  
ProductFlavor = full  
Device Info = Xiaomi | POCO | mondrian | mondrian_global | 23013PC75G | qcom  
WebView Info = [com.google.android.webview | 749919233]: Mozilla/5.0 (Linux; Android 13; 23013PC75G Build/TKQ1.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/143.0.7499.192 Mobile Safari/537.36  
ACRA UUID = 4afc3b3f-e93f-4a66-bc71-2b9476ef9eb0  
FSRS = 5.1.0 (Enabled: true)  
Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by ShaanNarendran**
## Purpose / Description
ANR when the scrollbar was dragged or tapped in larger collections, arose due to the addition of pr #19980

* #19980

## Fixes
* Fixes #20173 

## Approach
I deleted the previous delta based logic implemented and let the new function handle dragging and tapping which doesn't cause ANRs, for extra optimisation added a scrolltopositionwithoffset.

## How Has This Been Tested?
Tested the scrolling with a deck of 100k cards and found no issue on rapid scrolling for 30 seconds along with taps throughout the browser

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison** [comment]
>  the new function 

Please clarify this

----

In general, if you can list 'reverted X', then name the commit which is in `HEAD`, as this makes it easier to understand what was reverted, and what was fixed forward

I believe the commit is: ca95728ecd200713576b50d3fd05e90c9a87b9a6

**Comment by ShaanNarendran** [comment]
> > the new function
> 
> Please clarify this

Ah, by new function I meant the overriding of onTouchEvent which I had done for the main issue of tap and drag, should've phrased it better oops. Will edit the commit message now.

**Comment by ShaanNarendran** [comment]
> In general, if you can list 'reverted X', then name the commit which is in `HEAD`, as this makes it easier to understand what was reverted, and what was fixed forward
> 
> I believe the commit is: [ca95728](https://github.com/ankidroid/Anki-Android/commit/ca95728ecd200713576b50d3fd05e90c9a87b9a6)

Would I not have to mention [3c0b2bb](https://github.com/ankidroid/Anki-Android/commit/3c0b2bb1469f5d9a63d7afef399b5ab959ecfb81) since I removed the onTouchListener introduced in that commit, wouldn't it be better to write 'Reverts the onTouchListener introduced in 3c0b2bb'? I could be confusing the meaning of revert here so I just wanted to clarify.
Edit: 'Reverts ca95728' also seems right since introducing that pr is what caused the issue, so I suppose that's more appropriate like you said.

**Comment by ShaanNarendran** [comment]
Not sure if the new commit description works, but it made sense like this in my head

**Comment by ShaanNarendran** [comment]
@david-allison do we want to draft since the new browser redesign is coming?

**Comment by david-allison** [comment]
Let's keep going with this. 

The redesign will be dev only for a long time, and I expect "production" features to break it.

In addition, I'm mostly reworking search, the rendered rows won't change

**Comment by ShaanNarendran** [comment]
> I tested it since you removed had the logic set by pixels and you are counting items by number, add cards with uneven content (basically not equal height for all cards) then scroll the cards you will see a sudden snap while browsing the list

Could I have the deck file? I think either way, it has to be a tradeoff since if we revert to pixels then ANR is possible for decks with a large number of cards so we wouldn't be able to implement the tap and drag functionality otherwise we stick to using indexes to solve this issue but there would be the snapping you mentioned. I will look into it more though once I reproduce and see what I can do

Edit: I've reproduced it and I see the issue, will try and figure something out
Edit 2: Think I can use offset scroll with some decimal approximations to get it to work, should have it out tomorrow

**Comment by ShaanNarendran** [comment]
I implemented a fix but it's more of just a band-aid. We basically just use proportional scrolling rather than calculating pixels so it changes according to the size of the card, thereby making it smoother and not jumpy but in my testing there still is a little jump when you have very varied sizes.

File: AnkiDroid/src/main/java/com/ichi2/anki/ui/RecyclerFastScroller.kt [hunk 1]
```diff
@@ -411,14 +365,24 @@ class RecyclerFastScroller
...
+                    recyclerView?.removeCallbacks(scrollTask)
+                    recyclerView?.postDelayed(scrollTask, 20)
                     true
                 }
                 MotionEvent.ACTION_UP, MotionEvent.ACTION_CANCEL -> {
                     handle.isSelected = false
+                    if (recyclerView != null) {
+                        recyclerView!!.removeCallbacks(scrollTask)
+                        scrollTask.run()
+                    }
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/ui/RecyclerFastScroller.kt:383]: prefer `?.let { }` to remove the !!

File: AnkiDroid/src/main/java/com/ichi2/anki/ui/RecyclerFastScroller.kt [hunk 2]
```diff
@@ -384,14 +307,45 @@ class RecyclerFastScroller
...
+                val lm = recyclerView?.layoutManager ?: return@Runnable
+                val adapter = recyclerView?.adapter ?: return@Runnable
+
+                try {
+                    // Calculate the exact target including the decimal
+                    val targetIndexDouble = pendingScrollProportion * adapter.itemCount
+                    val targetIndex = targetIndexDouble.toInt().coerceIn(0, adapter.itemCount - 1)
+
+                    // The fraction is how deep into the card we are (0.0 to 1.0)
+                    val fraction = targetIndexDouble - targetIndex
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/ui/RecyclerFastScroller.kt]: Define `fun Double.wholeAndFraction(): Pair<Long, Double>` in `com.ichi2.anki.utils.ext:Double.kt`, then use it, implementer's choice on the style, but I feel this is readable

```kotlin
val (targetIndex, fraction) = (pendingScrollProportion * adapter.itemCount).wholeAndFraction()
```

File: AnkiDroid/src/main/java/com/ichi2/anki/ui/RecyclerFastScroller.kt [hunk 3]
```diff
@@ -384,14 +307,45 @@ class RecyclerFastScroller
...
+
+                    // Estimate height using the first visible view, this is a heuristic
+                    val firstChild = recyclerView?.getChildAt(0)
+                    val estimatedHeight = firstChild?.height ?: 0
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/ui/RecyclerFastScroller.kt]:
```suggestion
                    val estimatedHeight = recyclerView?.getChildAt(0)?.height ?: 0
```

File: AnkiDroid/src/main/java/com/ichi2/anki/ui/RecyclerFastScroller.kt [hunk 4]
```diff
@@ -384,14 +307,45 @@ class RecyclerFastScroller
...
+
+                    // Calculate the offset by pushing the item up by the fraction of its height
+                    // e.g. If at 99.9%, push the last card up by 90% of its height so we can see the bottom.
+                    val offset = -(fraction * estimatedHeight).toInt()
+
+                    (lm as? LinearLayoutManager)?.scrollToPositionWithOffset(targetIndex, offset)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/ui/RecyclerFastScroller.kt]: Perform the cast at the start of the function (maybe throw if it's a non-null type which is incorrect)

File: AnkiDroid/src/main/java/com/ichi2/anki/ui/RecyclerFastScroller.kt [hunk 5]
```diff
@@ -411,14 +365,24 @@ class RecyclerFastScroller
...
+                        (recyclerView?.layoutManager as? LinearLayoutManager)
+                            ?.scrollToPositionWithOffset(targetPosition, 0)
+                            ?: recyclerView?.scrollToPosition(targetPosition)
                     } catch (e: Exception) {
                         Timber.w(e, "scrollToPosition")
                     }
+
+                    // destroys any redundant calls to the scrolltask and sets a small delay to improve performance
+                    recyclerView?.removeCallbacks(scrollTask)
+                    recyclerView?.postDelayed(scrollTask, 20)
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/ui/RecyclerFastScroller.kt]: If you ever see `20` used as something to mean 20 milliseconds

* check for an extension method which takes `20.milliseconds`
* If one doesn't exist, consider creating one

https://github.com/ankidroid/Anki-Android/blob/c09aa11fa05e0016585802c0e02a764f530bc522/AnkiDroid/src/main/java/com/ichi2/anki/utils/Time.kt#L99-L105

File: AnkiDroid/src/main/java/com/ichi2/anki/ui/RecyclerFastScroller.kt [hunk 6]
```diff
@@ -384,14 +307,45 @@ class RecyclerFastScroller
             }
         }
 
+        private var pendingScrollProportion = 0f
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/ui/RecyclerFastScroller.kt:314]: Add a brief comment

File: AnkiDroid/src/main/java/com/ichi2/anki/ui/RecyclerFastScroller.kt [hunk 7]
```diff
@@ -384,14 +307,45 @@ class RecyclerFastScroller
...
+
+        private val scrollTask =
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/ui/RecyclerFastScroller.kt:317]: optional: brief one-line comment summarizing intent

File: AnkiDroid/src/main/java/com/ichi2/anki/ui/RecyclerFastScroller.kt (hunk 2 above)
Comment (ShaanNarendran) [reply AnkiDroid/src/main/java/com/ichi2/anki/ui/RecyclerFastScroller.kt]: This was giving me quite a lot of type errors, and I didn't want to deviate too much from my structure. If  we want this, I'll do it

**Comment by ShaanNarendran** [comment]
I think I really messed up the git in my branch..

File: AnkiDroid/src/main/java/com/ichi2/anki/ui/RecyclerFastScroller.kt (hunk 2 above)
Comment (david-allison) [reply AnkiDroid/src/main/java/com/ichi2/anki/ui/RecyclerFastScroller.kt]: I'll send in a patch when I get home, it was only expected to be a 10 minute job, apologies!

Comment (ShaanNarendran) [reply AnkiDroid/src/main/java/com/ichi2/anki/ui/RecyclerFastScroller.kt]: Nonono, let me try and figure it out don't want to deviate you from other work. I'll have a push in soon
Edit: I've done what you suggested, not sure if we still want the coerce to be safe but tested this and no ANRs upon scrolling to the last index or tapping it so I think it should be all good

**Comment by david-allison** [comment]
undo the 'merge' and rebase instead

**Comment by david-allison** [comment]
My review still stands, Cheers! 
Needs a quick fix to make CI happy 

I'm going to unwatch this one, ping me if I'm needed
